# -*- coding: utf-8 -*-
# ACHIEVEMENT kategorisi. NAME_1..16 = bolum (act) baslklari (MENU ile tutarli).
T = {
"ACHIEVEMENT__DESC_1": "1. bölümü tamamla",
"ACHIEVEMENT__DESC_2": "2. bölümü tamamla",
"ACHIEVEMENT__DESC_3": "3. bölümü tamamla",
"ACHIEVEMENT__DESC_4": "4. bölümü tamamla",
"ACHIEVEMENT__DESC_5": "5. bölümü tamamla",
"ACHIEVEMENT__DESC_6": "6. bölümü tamamla",
"ACHIEVEMENT__DESC_7": "7. bölümü tamamla",
"ACHIEVEMENT__DESC_8": "8. bölümü tamamla",
"ACHIEVEMENT__DESC_9": "9. bölümü tamamla",
"ACHIEVEMENT__DESC_10": "10. bölümü tamamla",
"ACHIEVEMENT__DESC_11": "11. bölümü tamamla",
"ACHIEVEMENT__DESC_12": "12. bölümü tamamla",
"ACHIEVEMENT__DESC_13": "13. bölümü tamamla",
"ACHIEVEMENT__DESC_14": "14. bölümü tamamla",
"ACHIEVEMENT__DESC_15": "15. bölümü tamamla",
"ACHIEVEMENT__DESC_16": "16. bölümü tamamla",
"ACHIEVEMENT__DESC_17": "Tüm bölümleri tamamla",
"ACHIEVEMENT__DESC_18": "Tüm çiçekleri bul",
"ACHIEVEMENT__DESC_19": "Tüm tüyleri bul",
"ACHIEVEMENT__DESC_20": "Tüm gizli sandıkları aç",
"ACHIEVEMENT__DESC_21": "Tüm hatıraları an",
"ACHIEVEMENT__DESC_22": "Sapanı tamamen yükselt",
"ACHIEVEMENT__DESC_23": "Arbaleti tamamen yükselt",
"ACHIEVEMENT__DESC_24": "Donanımı tamamen yükselt",
"ACHIEVEMENT__DESC_25": "Aletleri tamamen yükselt",
"ACHIEVEMENT__DESC_26": "Simyayı tamamen yükselt",
"ACHIEVEMENT__DESC_27": "40 ateş söndür",
"ACHIEVEMENT__DESC_28": "100 cephane üret",
"ACHIEVEMENT__DESC_29": "İhtiyat yeteneklerini tamamen geliştir",
"ACHIEVEMENT__DESC_30": "Saldırgan yeteneklerini tamamen geliştir",
"ACHIEVEMENT__DESC_31": "Fırsatçılık yeteneklerini tamamen geliştir",
"ACHIEVEMENT__DESC_32": "Tüm çam kozalaklarını vur",
"ACHIEVEMENT__DESC_33": "Taçlar oyunundaki tüm atışları başarıyla tamamla",
"ACHIEVEMENT__DESC_34": "Mabetteki eski koruyucunun tüm eşyalarıyla etkileş",
"ACHIEVEMENT__DESC_35": "Rıhtımdaki muhafızı öldürme",
"ACHIEVEMENT__NAME_1": "Yeni Bir Güneşin Altında",
"ACHIEVEMENT__NAME_2": "Yeni Gelenler",
"ACHIEVEMENT__NAME_3": "Bir Kan Yükü",
"ACHIEVEMENT__NAME_4": "Koruyucunun Görevi",
"ACHIEVEMENT__NAME_5": "Ardımızda",
"ACHIEVEMENT__NAME_6": "Her Şeyi Geride Bırakarak",
"ACHIEVEMENT__NAME_7": "Hainler",
"ACHIEVEMENT__NAME_8": "Vaatler Denizi",
"ACHIEVEMENT__NAME_9": "Hikâyeler ve İfşalar",
"ACHIEVEMENT__NAME_10": "Kan Bağı",
"ACHIEVEMENT__NAME_11": "Yüzyılların Beşiği",
"ACHIEVEMENT__NAME_12": "Hak Ettiğimiz Hayat",
"ACHIEVEMENT__NAME_13": "Geriye Hiçbir Şey Kalmadı",
"ACHIEVEMENT__NAME_14": "Yaralarımızı Sararken",
"ACHIEVEMENT__NAME_15": "Ölen Güneş",
"ACHIEVEMENT__NAME_16": "Kral Hugo",
"ACHIEVEMENT__NAME_17": "Şövalyeler!",
"ACHIEVEMENT__NAME_18": "Şifacı",
"ACHIEVEMENT__NAME_19": "Kuş Bilimci",
"ACHIEVEMENT__NAME_20": "Kâşif",
"ACHIEVEMENT__NAME_21": "Ölümsüz anılar",
"ACHIEVEMENT__NAME_22": "Artık oyuncak değil",
"ACHIEVEMENT__NAME_23": "Geliştirilmiş arbalet",
"ACHIEVEMENT__NAME_24": "Bir avuç cep",
"ACHIEVEMENT__NAME_25": "Etkili aletler",
"ACHIEVEMENT__NAME_26": "Cep laboratuvarı",
"ACHIEVEMENT__NAME_27": "Gece nöbetçisi",
"ACHIEVEMENT__NAME_28": "Simyacı",
"ACHIEVEMENT__NAME_29": "Sinsi",
"ACHIEVEMENT__NAME_30": "Dövüşçü",
"ACHIEVEMENT__NAME_31": "Kötücül",
"ACHIEVEMENT__NAME_32": "Kusursuz atış",
"ACHIEVEMENT__NAME_33": "Kusursuz fırlatış",
"ACHIEVEMENT__NAME_34": "Eski koruyucu",
"ACHIEVEMENT__NAME_35": "Merhamet",
}
