# -*- coding: utf-8 -*-
# Genel Sesler GS3: BANDIT_S1+S2+S3 generic VO (936 satir). Haydutlar: kaba, argo, "sen".
T = {
"VO__BANDIT_S1__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Biri bizimle oynuyor! İzini sürün!",
"VO__BANDIT_S1__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Biri benimle dalga geçiyor! Bölgeyi aramama yardım edin!",
"VO__BANDIT_S1__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Bazı serseriler bizi aptal yerine koyuyor! Onları durdurma vakti!",
"VO__BANDIT_S1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Oyun oynamayı bırak! Seni bir yakalarsam...",
"VO__BANDIT_S1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Benimle uğraşmayı öğreteceğim sana!",
"VO__BANDIT_S1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Beni bir daha kandıramazsın, buna pişman edeceğim seni!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT__001__M__1": "Burada biri var! Alarma geçin!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT__001__M__2": "Davetsiz misafir! Yakalayın onları!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT__001__M__3": "İzinsiz girenler! Gelin buraya!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Sen! Kıpırdama!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Sen de kimsin be...?! Dur orada!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Hemen dur! Yanlış yere geldin!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Sana ulaşacağım, bir yolunu bulacağım!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "Sonsuza dek burada tıkılı kalmayacağım, biliyorsun değil mi?!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Emin ol, seni yakalamanın yolunu yakında bulacağım!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Sana ulaşmanın yolunu bulacağım ve sonra...!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Sana ulaşmanın bir yolu olmalı...!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Orada bekle sen, sana ulaşmanın yolunu bulacağım!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_DYING__001__M__1": "Kahretsin! Adam vuruldu!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_DYING__001__M__2": "Olamaz! Biri gitti!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_DYING__001__M__3": "Bir adam öldürüldü... Dikkat edin!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Seni kül edeceğim.",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Seni dumanla dışarı çıkaracağım!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "Seni burada, şimdi kızartacağım!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Benimle gel, davetsiz misafirler var!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Burada davetsiz misafirler var! Takip edin, yakalayalım onları!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Kımıldayın! Misafirimiz var!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılın! Bölgeyi arayın!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Yayılın! Yakınlarda olmalılar!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "İzlerini sürün, her yeri arayın!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Beni öldürecek cesaretin yok!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Korktun mu? Korkmalısın da!",
"VO__BANDIT_S1__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Ya sen ya ben!",
"VO__BANDIT_S1__GENERIC__PATROL__BURNING__001__M__1": "Yanıyor mu?!",
"VO__BANDIT_S1__GENERIC__PATROL__BURNING__001__M__2": "Ateş mi?!",
"VO__BANDIT_S1__GENERIC__PATROL__BURNING__001__M__3": "Bu ateş de ne?!",
"VO__BANDIT_S1__GENERIC__PATROL__CAPTURE__001__M__1": "Kısa keseceğim!",
"VO__BANDIT_S1__GENERIC__PATROL__CAPTURE__001__M__2": "Merak etme, bunu daha önce yaptım.",
"VO__BANDIT_S1__GENERIC__PATROL__CAPTURE__001__M__3": "Bugün şanslı günün değildi.",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE__001__M__1": "Aptallığı bırak da kalk! Kalk ayağa!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE__001__M__2": "Kalk ayağa tembel herif! Hadi!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE__001__M__3": "Kalk ayağa! Hey!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Uyuyor mu ne?!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Ne yapıyor o şimdi?!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Lanet tembel, uyuyor olsa iyi olur!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Yanmış bir ceset!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Şu ceset kül olmuş...",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Kömüre dönmüş bir ceset bu!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Aptal olunca böyle olur işte.",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Kötü bir ölüm şekli...",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Daha dikkatli olmalıydı.",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Adam vuruldu! Bunu kim yaptıysa bulun!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Burada bir ceset var! Bölgeyi arayın!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Öldü! Bunu yapan serseriyi bulun!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Ceset hâlâ sıcak! Hâlâ buralardasın, biliyorum, serseri!",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Ölmüş... Seni kimin öldürdüğünü bulacağım...",
"VO__BANDIT_S1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Biri bizi öldürüyor! Seni bulacağım!",
"VO__BANDIT_S1__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Demek bu kadar?",
"VO__BANDIT_S1__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Elinden gelen bu mu?!",
"VO__BANDIT_S1__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Hak ettiğini buldun!",
"VO__BANDIT_S1__GENERIC__PATROL__DYING__001__M__1": "Ne oluy--",
"VO__BANDIT_S1__GENERIC__PATROL__DYING__001__M__2": "Ha?!",
"VO__BANDIT_S1__GENERIC__PATROL__DYING__001__M__3": "Of!",
"VO__BANDIT_S1__GENERIC__PATROL__FLEE_RATS__001__M__1": "Hayır hayır hayır hayır hayır!",
"VO__BANDIT_S1__GENERIC__PATROL__FLEE_RATS__001__M__2": "Çekilin üstümden! Çekilin!",
"VO__BANDIT_S1__GENERIC__PATROL__FLEE_RATS__001__M__3": "Bırakın beni! Bırakın!",
"VO__BANDIT_S1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Bok herifler, bugün beni yiyemeyeceksiniz!",
"VO__BANDIT_S1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Beni ziyafetiniz yapamayacaksınız!",
"VO__BANDIT_S1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "Uzak durun benden, pis serseriler!",
"VO__BANDIT_S1__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Bazı serseriler peşimde! Bulun onları!",
"VO__BANDIT_S1__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Saldırıya uğradım! Davetsiz misafirler var!",
"VO__BANDIT_S1__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Biri bana saldırıyor! Gelin buraya!",
"VO__BANDIT_S1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Bunun bedelini ödeyeceksin!",
"VO__BANDIT_S1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Acıdı mı sandın?! Bir daha denersen...",
"VO__BANDIT_S1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Kim yaptı bunu?!",
"VO__BANDIT_S1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Gittin... mi?",
"VO__BANDIT_S1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Hâlâ orada mısın?",
"VO__BANDIT_S1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Hâlâ orada mısın?",
"VO__BANDIT_S1__GENERIC__PATROL__OIL__001__M__1": "Bu da ne? Katran mı?",
"VO__BANDIT_S1__GENERIC__PATROL__OIL__001__M__2": "Ne? Her yer katran mı?!",
"VO__BANDIT_S1__GENERIC__PATROL__OIL__001__M__3": "Ne be—Kim döktü bunu?!",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION__001__M__1": "Ha?",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION__001__M__2": "Hı?",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION__001__M__3": "Bir saniye...",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION_RATS__001__M__1": "Beni yakalamaya çalış! Seni..!",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION_RATS__001__M__2": "Haşarat! Beni asla yakalayamazsınız!",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION_RATS__001__M__3": "Ne oldu? Bana ulaşamıyor musunuz?",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Geçmeme izin verecek misiniz? Tabii ki vermezsiniz...",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "Geçmeme izin vermeyeceksiniz, ha?",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Aman Tanrım... Sadece şuraya geçmeye çalışıyorum...",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "O zaman ben burada kalayım.",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "Peki o zaman, siz gidene kadar bekleyeceğim.",
"VO__BANDIT_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Kımıldayacak gibi görünmüyorlar...",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME__001__M__1": "Hep kafamın içinde...",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME__001__M__2": "Hiçbir şey...",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME__001__M__3": "Hayal mi görüyorum?!",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Yine bir şey yok, kusura bakma.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Az önceki gibi bir şey yok.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Sanırım sonuçta bir şey yokmuş.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Hâlâ etrafta bir şey yok.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Yine hiçbir şey yok...",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Bir kez daha, hiçbir şey...",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_RATS__001__M__1": "Bunlara alışmak mümkün değil.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_RATS__001__M__2": "Pis sıçanlar.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_RATS__001__M__3": "Lanet haşarat.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Hiçbir şey bulamıyorum.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Burası tamamen temiz.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Benim tarafımda bir şey yok.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Fazla gerginim...",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Sorun yok... sadece benim.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Bir şey yokmuş...",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Ne diyordum? Ah evet!",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Bir şey söyleyecektim... Ha doğru!",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Nerede kalmıştık? Ah, hatırladım!",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Bunu tahmin etmiştim.",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Bir şey olmadığını biliyordum...",
"VO__BANDIT_S1__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Biliyordum...",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH__001__M__1": "Kaçırdım onları! Her yere bakın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH__001__M__2": "Kayboldular! Her köşeyi arayın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH__001__M__3": "Serseriler kaçtı! Bulun onları!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Hâlâ burada olduğunu biliyorum! Seni bulacağım!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Nerede saklanıyorsunuz, ödlekler?!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Kaçabileceğini sanma!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Bana bırak!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Hallederim!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Yakalayalım onları!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Eminim oradasın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Demek epey yakınsın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "O tarafta olmalısın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Buldum onları! Bu taraftan!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Buraya! Görüyorum onları!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "İşte! Yakalayın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Olduğun yerde kal!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Dur orada!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "İşte buradasın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Misafirimiz var! Bulmama yardım edin!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Biri bölgede saklanıyor! Aramaya başlayın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Kıçınızı kaldırın! Davetsiz misafirler var!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Tamam!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Anlaşıldı!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Tamamdır!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Eminim onlar!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Tüm bunların arkasında onlar var!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Bununla bir ilgileri olmalı...",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Kaçırdım onları!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Neredeler lanet olsun?!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Serseriler beni atlattı!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Orada saklanıyor olmalılar! Yakalarım onları!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Orada saklanabileceklerini sanıyorlar! Gidiyorum...",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Oraya siper aldığını biliyorum!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Onun arkasında uzun süre saklanamazsın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Orada arkada, değil mi? Ölmeye hazırlan!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Onun arkasına mı saklanıyorsun? Duanı et...",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı indiler! Peşlerine düşeceğim!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı atladılar! Hemen arkalarındayım!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağı atladılar! Bir bakacağım!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağıda olduğunu biliyorum!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Aşağıda saklanamayacaksın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Aşağıda güvende olduğunu sanma!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "Çimenliğe girdiklerini gördüm!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Sanırım çimenliğe girdiler!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "O çimenlikte olmalılar!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Ben gelirken çimen sana yardım etmeyecek.",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Çimenlikte uzun süre saklanamazsın.",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Uzun çimen senin için güvenli bir yer olmayacak.",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altına girdiler! Peşlerine düşeceğim!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altındalar! Hemen arkalarındayım!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Sanırım oranın altına saklandılar! Bir bakacağım!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Oranın altında olduğunu biliyorum!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Oranın altında saklanamayacaksın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Oranın altında güvende olduğunu sanma!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Yukarı çıktılar! Peşlerinden!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "Yukarı tırmandılar! Yakalayın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Sanırım yukarıdalar! Bir bakalım!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarıda olduğunu biliyorum!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Yukarıda saklanamayacaksın!",
"VO__BANDIT_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Yukarıda güvende olduğunu sanma!",
"VO__BANDIT_S1__GENERIC__PATROL__SMOKE__001__M__1": "Bu duman da ne?",
"VO__BANDIT_S1__GENERIC__PATROL__SMOKE__001__M__2": "Duman mı? Gidip baksam iyi olur...",
"VO__BANDIT_S1__GENERIC__PATROL__SMOKE__001__M__3": "Ateş olmayan yerden duman çıkmaz, emin olalım...",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "İşte yine başladı!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine oluyor!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "Yine mi?!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine mi oluyor? Baksam iyi olur!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Yine mi?!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "İşte yine başladı!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Gidip bakacağım.",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Yola çıkıyorum.",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Gidiyorum.",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Duydun mu şunu?! Bir bakacağım!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "Bir şey duydum! Bana bırak...",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Sen de duydun mu?! Gidip bakacağım!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu sesi çıkaran da ne lan?",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Neydi o ses?",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Bu duyduğum da ne?",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "Şu ateşin nesi var?! Bir bakacağım!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "Gözlerim mi beni yanıltıyor?! Şuna baksam iyi olur!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Şu ateşe ne oluyor?",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Şu ateşte bir tuhaflık var...",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Şu ateşe ne oluyor?",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Şu ateşin nesi var lan?",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Sapan sesine benziyordu! Bakacağım.",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Sapan mıydı o? Gidip baksam iyi olur.",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "O çıtırtı neydi? Gidip bakacağım.",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Sapan sesine benziyordu...",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "Bir çatırtı duyduğumu biliyorum...",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "Kırbaç sesi miydi neydi?!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Tuhaf bir şey gördüm, baksam iyi olur.",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Sen de gördün mü? Bir bakacağım.",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "O tarafta bir şey gördüm. Hemen dönerim.",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Orada bir şeyin kımıldadığını gördüm...",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Ha?!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "O neydi...?",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Dikkatli ol.",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Şüphelenirsen, yüksek sesle bağır!",
"VO__BANDIT_S1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Bir şey görürsen bağır. Yüksek sesle.",
"VO__BANDIT_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Burada hiçbir şey bulamıyorum...",
"VO__BANDIT_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Burada bir şey yok...",
"VO__BANDIT_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Serseriler burada değil...",
"VO__BANDIT_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Bu taraf temiz...",
"VO__BANDIT_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Nerede saklanıyorlar...",
"VO__BANDIT_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Kimse yok burada...",
"VO__BANDIT_S1__GENERIC__STATIC__ALERT_ALONE__001__M__1": "Seni görüyorum!",
"VO__BANDIT_S1__GENERIC__STATIC__ALERT_ALONE__001__M__2": "Sen! Öldün sen! Duydun mu?!",
"VO__BANDIT_S1__GENERIC__STATIC__ALERT_ALONE__001__M__3": "Ne işin var burada lan?!",
"VO__BANDIT_S1__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__1": "Bunu yapan serseri kim?!",
"VO__BANDIT_S1__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__2": "Buna pişman edeceğim seni!",
"VO__BANDIT_S1__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__3": "Kafama nişan alsaydın bari!",
"VO__BANDIT_S1__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__1": "Boş ver. Bir şey yokmuş.",
"VO__BANDIT_S1__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__2": "Boş ver, yine bir şey yok...",
"VO__BANDIT_S1__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__3": "Tamam, yine bir şey yokmuş.",
"VO__BANDIT_S1__GENERIC__STATIC__RESUME_SPOTTER__001__M__1": "Bir şey yokmuş herhalde.",
"VO__BANDIT_S1__GENERIC__STATIC__RESUME_SPOTTER__001__M__2": "Sanırım sorun yok.",
"VO__BANDIT_S1__GENERIC__STATIC__RESUME_SPOTTER__001__M__3": "Temiz görünüyor.",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_ALONE__001__M__1": "Saklanıyoruz, ha?! Çık dışarı!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_ALONE__001__M__2": "Buradan canlı çıkamayacaksın!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_ALONE__001__M__3": "Saklanmak seni kurtarmaz!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_FOUND__001__M__1": "Buradalar! Kaçmalarına izin vermeyin!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_FOUND__001__M__2": "Görüyorum onları! Gelin buraya!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_FOUND__001__M__3": "Buraya! Buldum onları!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER__001__M__1": "Hayır, göremiyorum onları!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER__001__M__2": "Nereye gittiler?!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER__001__M__3": "Kahretsin... Neredeler?!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__1": "Hemen arkada saklanıyorlar! İzlerini sürün!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__2": "Oraya siper aldılar!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__3": "Arkaya saklandıklarını biliyorum! Burada durdurun onları!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Oraya saklandığını gördüm... Göster kendini!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Orada arkada saklandığını biliyorum... Göster kendini!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Onun arkasına saklanmak seni kurtarmaz!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağıdalar! Peşlerinden koşun!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı atladılar! Yakalayın!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağı inin ve peşlerinden gidin!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Nerede olduğunu biliyorum! Geri çık buraya!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Aşağıda olduğunu bilmediğimi mi sanıyorsun?!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Aşağısı senin için güvenli değil!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__1": "Sanırım çimenliğe girdiler!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__2": "Çimenliğe girdiler! Peşlerinden gidin!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__3": "O serseriler çimenliğe girdi! Bulun onları!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Çimenlikte saklanmak seni kurtarmaz!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "O çimenin seni benden saklayabileceğini mi sanıyorsun?!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Birkaç çimen yaprağı seni kurtarmaz!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altındalar! Peşlerinden koşun!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altına girdiler! Yakalayın!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__3": "Oranın altına saklandıklarını gördüm! Peşlerinden gidin!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Oranın altına süründüğünü biliyorum!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Oranın altında olduğunu bilmediğimi mi sanıyorsun?!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Oranın altı senin için güvenli değil!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__1": "Yukarıdalar! Peşlerinden koşun!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__2": "Yukarı tırmandılar! Yakalayın!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__3": "Yukarı çıkın... Peşlerinden gidin!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Nerede olduğunu biliyorum! Geri in buraya!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Yukarıda olduğunu bilmediğimi mi sanıyorsun?!",
"VO__BANDIT_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Yukarısı senin için güvenli değil!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__1": "Şaka yapıyor olmalısın! Git tekrar bak!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__2": "Neler oluyor be?! Geri dön ve ne olduğuna bak!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__3": "Yine mi?! Git ve neler olduğuna bak!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Ne be?! Yine mi?!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Yine olmasın!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Hayır, yine mi?!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__1": "O sesi duydun mu? Gidip ne olduğuna bakacağım.",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__2": "Bir ses duydum! Gidip bir bakacağım!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__3": "Duydun mu şunu?! Sanırım şu taraftan geldi!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu sesi çıkaran da ne?",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Bu ses de ne?",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Yakından geldi gibi...",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__1": "Şu ateşte bir tuhaflık var! Git bak şuna!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__2": "Şu ateş tuhaf görünüyor...",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__3": "Bu nasıl tuhaf bir ateş böyle?",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Gözlerim mi oyun oynuyor? Şu ateşe ne oldu?",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Şu ateş! Bu... Bu büyücülük mü?!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Şu ateşe ne oluyor?",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__1": "Orada bir şey kımıldıyor.",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__2": "Orada bir şey var!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__3": "Orada bir hareket gördüm.",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__1": "Orada biri mi var?!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__2": "Ne ol--",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__3": "Kim o...?",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__1": "Hayır, bu sadece rüzgâr değil, onun arkasında bir şey kımıldadı!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__2": "Orada arkada bir hareket gördüm!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__3": "Uydurmuyorum... Onun arkasında bir şey kımıldadı!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__1": "Aşağıda! Az önce bir şey gördüm!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__2": "Aşağıda bir şey kımıldadı!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__3": "Aşağıda! Bir hareket gördüm!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__1": "Hey! Çimende bir hareket gördüm!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__2": "İşte! Çimende bir şey var!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__3": "O uzun çimen az önce kımıldadı!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__1": "Orada bir şeyler oluyor!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__2": "Hey..! Orada bir şey kımıldadı!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__3": "Az önce orada bir hareket gördüm!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__1": "Yukarıda! Az önce bir şey gördüm!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__2": "Yukarıda bir şey kımıldadı!",
"VO__BANDIT_S1__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__3": "Yukarıda! Bir hareket gördüm!",
"VO__BANDIT_S2__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Görünüşe göre bölgede şakacılar var! Her yeri arayın!",
"VO__BANDIT_S2__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Biri bizimle uğraşıyor! Her yeri arayın!",
"VO__BANDIT_S2__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Aramaya başlayın çocuklar! Davetsiz misafirler bizden akıllı olduklarını sanıyor!",
"VO__BANDIT_S2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Bu kadar yeter! Seni bulmaya geliyorum!",
"VO__BANDIT_S2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Yine mi? Beni kandırabileceğini mi sanıyorsun?!",
"VO__BANDIT_S2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Benimle uğraştığına pişman olacaksın!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT__001__M__1": "Burada izinsiz girenler var!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT__001__M__2": "Gelin buraya! Davetsiz misafirler var!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT__001__M__3": "Davetsiz misafirler var! Peşlerinden gidin!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Sen! Orada kal! Geliyorum!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Seni görmem sandın, gel buraya!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Sen! Kaçabileceğini sanma!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Kaçtığını mı sandın? Göreceğiz!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "İyi oynadın, ama yine de yakalayacağım seni...",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Tadını çıkar bakalım. Hemen orada olacağım.",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Yakalayacağım seni! Bir yolunu bulacağım!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Güvende olduğunu mu sanıyorsun? Onu göreceğiz!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Gülebildiğin kadar gül: hâlâ peşindeyim!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_DYING__001__M__1": "Adam vuruldu!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_DYING__001__M__2": "Hayır! Birimiz öldürüldü!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_DYING__001__M__3": "Biri öldü! Dikkat edin!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Çimen yanınca ne olur, görmek üzeresin!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Çimenliğe mi saklanmak istiyorsun, ha? Pek akıllıca değil.",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "Şimdi o çimende ne kadar saklanabilirsin dersin?!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Burada davetsiz misafirler var! Onları durdurmama yardım edin!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Hey! Burada serseriler var! Yakalayın onları!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Benimle! Davetsiz misafirleri köşeye sıkıştırın!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılın! Bölgeyi kapatın!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Kımıldayın ve onları kuşatın! Kaçmalarına izin vermeyin!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Ayrılın ve yakalayın o serserileri!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "İşin bitti!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Şu işi bitirelim!",
"VO__BANDIT_S2__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Senin için her şey bitti artık!",
"VO__BANDIT_S2__GENERIC__PATROL__BURNING__001__M__1": "Bir şey yanıyor!",
"VO__BANDIT_S2__GENERIC__PATROL__BURNING__001__M__2": "O ateş nereden çıktı?!",
"VO__BANDIT_S2__GENERIC__PATROL__BURNING__001__M__3": "Bir şey tutuştu!",
"VO__BANDIT_S2__GENERIC__PATROL__CAPTURE__001__M__1": "Umarım bir cennet vardır.",
"VO__BANDIT_S2__GENERIC__PATROL__CAPTURE__001__M__2": "Buraya geldiğine pişman oldun, eminim.",
"VO__BANDIT_S2__GENERIC__PATROL__CAPTURE__001__M__3": "Kimse cesedini bulamayacak.",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE__001__M__1": "Uyuyor musun? Hadi, kalk!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE__001__M__2": "Kalk ayağa sarhoş! Hemen!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE__001__M__3": "Hey! Oyalanmayı bırak!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Sakın uyuyakaldığını söyleme!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Hey! Ne yapıyorsun?!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Yerde ne işi var?",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Yanarak ölmüş!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Diri diri mi yakıldı?!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Ateşe verilmiş!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Of... Kemiğine kadar yenmiş!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Hay aksi. Senin gibi olmayacağımdan emin olacağım...",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Lanet sıçanların seni yakalamasına izin verdin. Salak herif.",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Öldü! Bunu kim yaptıysa bulalım!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Adam vuruldu! Davetsiz misafirler var!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Adamlarımızdan birini kaybettik! Bölgeyi arayın!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Seni öldüren serseriyi ezeceğim!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Ceset hâlâ taze! Kim olursan ol, bunun bedelini ödeyeceksin!",
"VO__BANDIT_S2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Ölmüş... Katil hâlâ yakınlarda olmalı!",
"VO__BANDIT_S2__GENERIC__PATROL__DEATH_VEIL__001__M__1": "İşin bitti, serseri!",
"VO__BANDIT_S2__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Gördün mü?! Kaçamayacaksın!",
"VO__BANDIT_S2__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Acıdı mı?! Güzel!",
"VO__BANDIT_S2__GENERIC__PATROL__DYING__001__M__1": "Siktir!",
"VO__BANDIT_S2__GENERIC__PATROL__DYING__001__M__2": "Aman Tanrım! Neler oluyor?!",
"VO__BANDIT_S2__GENERIC__PATROL__DYING__001__M__3": "Hay aksi!",
"VO__BANDIT_S2__GENERIC__PATROL__FLEE_RATS__001__M__1": "Ölmeyi hak etmiyorum!",
"VO__BANDIT_S2__GENERIC__PATROL__FLEE_RATS__001__M__2": "Dokunmayın bana!",
"VO__BANDIT_S2__GENERIC__PATROL__FLEE_RATS__001__M__3": "Beni öldüremeyeceksiniz, sıçanlar!",
"VO__BANDIT_S2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Hâlâ... yaşıyorum... galiba...",
"VO__BANDIT_S2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Bugün beni yakalayamayacaksınız!",
"VO__BANDIT_S2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "İşte böyle, sizin için fazla hızlıyım!",
"VO__BANDIT_S2__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Burada bana saldırıyorlar!",
"VO__BANDIT_S2__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Biri peşimde! Yardım edin!",
"VO__BANDIT_S2__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Bazı serseriler peşimizde! Bulun onları!",
"VO__BANDIT_S2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Seni küçük— Pestilini çıkaracağım!",
"VO__BANDIT_S2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Kavga mı istiyorsun? Ben varım!",
"VO__BANDIT_S2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Bunu yanına bırakacağını sanma!",
"VO__BANDIT_S2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Ne oldu?",
"VO__BANDIT_S2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "İyi misin?",
"VO__BANDIT_S2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Orada mısın?",
"VO__BANDIT_S2__GENERIC__PATROL__OIL__001__M__1": "Buraya katranı kim döktü?!",
"VO__BANDIT_S2__GENERIC__PATROL__OIL__001__M__2": "Bu ne? Katran kokuyor!",
"VO__BANDIT_S2__GENERIC__PATROL__OIL__001__M__3": "Hangi serseri döktü bunu buraya?",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION__001__M__1": "Ha?",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION__001__M__2": "Dur...",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION__001__M__3": "O da neydi?",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION_RATS__001__M__1": "Benimle uğraşma sakın.",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION_RATS__001__M__2": "Niye susmuyorsunuz artık?!",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION_RATS__001__M__3": "Beni yakalayamayacaksınız. Boşuna uğraşmayın.",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Şimdi oraya nasıl geçeceğim? Aptal haşarat.",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "Lanet sıçanlar. Çekilin yoldan!",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Yolumdan çekilir misiniz, serseriler?",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "Sanırım ancak buraya kadar gidebiliyorum...",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "Görünüşe göre o tarafa gitmiyorum...",
"VO__BANDIT_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Geçmeme izin verecek gibi durmuyorsunuz.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME__001__M__1": "Hayal görmüş olmalıyım.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME__001__M__2": "Boşa vakit kaybı...",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME__001__M__3": "Şimdi de aklımı kaçırıyorum.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Yok, yine bir şey yok...",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Bir şey yokmuş... Yine!",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Öncekiyle aynı...",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Yine hiçbir şey yok... Delirmek üzereyim.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Hâlâ bir şey yok...",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Yine hiçbir şey yok...",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_RATS__001__M__1": "Pis serseriler.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_RATS__001__M__2": "O sıçanlardan nefret ediyorum!",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_RATS__001__M__3": "Lanet sıçanlar.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Burada bir şey yok.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Her şey normal görünüyor.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Tamam... Bir şey yokmuş.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Orada bir şey yok...",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Hiçbir şey...",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Hiçbir şey bulamıyorum.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Neyse, ne diyordum? Ah evet!",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Nerede kalmıştık? Ah, hatırladım!",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Nerede kalmıştık? Ah evet!",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Böylesi daha iyi.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Hayırlısı buymuş.",
"VO__BANDIT_S2__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Boş verelim gitsin.",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH__001__M__1": "Kaçırdım onları! Her köşeyi arayın!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH__001__M__2": "Hâlâ buralarda olmalılar! Kaçmalarına izin vermeyin!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH__001__M__3": "Serseriler kaçtı! Aramaya devam edin!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Neredesin? Çık dışarı!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Seni bulamam mı sandın?! Ödlekler!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Merak etme, buradan canlı çıkamayacaksın.",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Hadi yapalım!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Yakalayacağız onları!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Yakalayacağız onları!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Demek bu taraftasın?!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Ah, sen olmalısın!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Hı! Orada olan sen olmalısın!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Buldum onları! Kaçmalarına izin vermeyin!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Buraya! Yakalayın onları!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Görüyorum onları! Bu taraftan!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Sonunda buldum seni!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Buldum seni!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Bak kim buradaymış!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "İzinsiz girenler var! Bölgeyi arayın!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Biri etrafta dolaşıyor! Bulun onları!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Gözünüzü açın, bulun izinsiz girenleri!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Hallederim!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Tamamdır!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Hallediyorum!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Onlar! Buralarda olmalılar...",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Onlar olmalı!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Bunu onlar yaptı, yakınlardalar!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Kaçıyorlar!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Kaçtılar!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Çok uzağa gitmiş olamazlar!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Orada mı saklanıyorsun? Seni bulamayız mı sandın?!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Orada gerçekten güvende olduğunu mu sanıyorsun?!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Seni orada bulamayız mı sandın!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Orada olduğunu biliyorum! Aptal mıyım sandın?",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Onun arkasında güvende olduğunu mu sanıyorsun?!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Oraya saklandığını gördüm! Kaçmanın anlamı yok!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı indiklerini gördüm! İzlerindeyim!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı kaçtılar! Peşlerinden gidiyorum!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağı atladılar! Hallettim!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Geri çık buraya, ödlek!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Aşağıda güvende olduğunu mu sanıyorsun?!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Seni aşağıda bulamam mı sandın?!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "Çimenliğe girdiler! Peşlerinden gideceğim!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Şu çimeni görüyor musun? Sanırım oradalar!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Çimenlikte saklanıyorlar!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Çimenlikte mi saklanıyorsun? Kötü seçim!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "O çimende ne kadar güvende olduğunu sanıyorsun?!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Uzun çimenin seni kurtarabileceğini mi sanıyorsun?",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altına saklandıklarını gördüm! Peşlerinden gideceğim!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altına kaçtılar! Peşlerinden gidiyorum!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Oranın altındalar! Hallettim!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "İstediğin kadar oranın altına saklan! Yine de yakalayacağım seni!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Oranın altında güvende olduğunu mu sanıyorsun?!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Seni oranın altında bulamam mı sandın?!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Yukarı çıktıklarını gördüm! İzlerine düşün!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "Yukarı kaçtılar! Peşlerinden gidin!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Yukarı tırmandılar, yakalayın onları!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Geri in buraya, ödlek!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Yukarıda güvende olduğunu mu sanıyorsun?!",
"VO__BANDIT_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Seni yukarıda bulamam mı sandın?!",
"VO__BANDIT_S2__GENERIC__PATROL__SMOKE__001__M__1": "Şu duman... Baksam iyi olur!",
"VO__BANDIT_S2__GENERIC__PATROL__SMOKE__001__M__2": "O duman nereden geliyor?",
"VO__BANDIT_S2__GENERIC__PATROL__SMOKE__001__M__3": "Duman... burada mı?",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Ciddi olamazsın! Yine mi?!",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine mi? Bu da ne?",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "Geri geldi! Biri bizimle oynamıyor olsa iyi olur!",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine oluyor!",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Geri geldi. Kahretsin!",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "İşte yine başladı! Gidip baksam iyi olur.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Bana bırak.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Merak etme, hallederim.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Beni gözünün önünde tut.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Sen de duydun mu?! Gidiyorum!",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "Kulağa hoş gelmiyor... Arkamı kolla!",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Gidip o sesi çıkaran şeye bakacağım.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "O ses. Neydi o?",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "O sesi çıkaran neydi lan.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Az önce ne duydum?",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "Şu ateş normal değil. Bir bakacağım.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "Ateşte bir sorun var. Bir bakacağım.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Büyücülük olmalı. Gidip bakacağım.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Şu ateşe az önce ne oldu?",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Şu ateşin nesi var lan?!",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Şu ateş. Kara büyü mü bu?",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Sapan sesine benziyordu! Gidiyorum!",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Sapandı, değil mi? Gidip bakacağım.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "Yakından geldi! Gidip ne olduğuna bakacağım.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Kim sapanla oynuyor?",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "Sapan mıydı... olamaz!",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "Yakından geldi gibi...",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Bir bakacağım, sanırım bir şey gördüm.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Sen de gördün, değil mi? Bir bakacağım.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Sanırım burada bir şey var.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "O da neydi lan...?",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Bir şey kımıldadı...",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Yemin ederim bir şey gördüm...",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Arkanı kolla.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Bir şey görürsen haber ver.",
"VO__BANDIT_S2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Kahraman olmaya kalkma.",
"VO__BANDIT_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Burada değiller...",
"VO__BANDIT_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Burada her şey temiz...",
"VO__BANDIT_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Hiçbir şey bulamıyorum...",
"VO__BANDIT_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Burada hiçbir şey yok...",
"VO__BANDIT_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Neredeler...",
"VO__BANDIT_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Burada arayarak vakit kaybediyorum...",
"VO__BANDIT_S2__GENERIC__STATIC__ALERT_ALONE__001__M__1": "Hey! Buraya geldiğine pişman edeceğim seni!",
"VO__BANDIT_S2__GENERIC__STATIC__ALERT_ALONE__001__M__2": "Sen, oradaki!",
"VO__BANDIT_S2__GENERIC__STATIC__ALERT_ALONE__001__M__3": "Hey! Dur orada!",
"VO__BANDIT_S2__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__1": "Eline geçersen bunun bedelini ödersin!",
"VO__BANDIT_S2__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__2": "Bunun hesabını soracağım senden!",
"VO__BANDIT_S2__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__3": "Serseri! Ödeyeceksin bunu!",
"VO__BANDIT_S2__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__1": "Her şey hâlâ temiz görünüyor.",
"VO__BANDIT_S2__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__2": "Yine hiçbir şey yok!",
"VO__BANDIT_S2__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__3": "Yine bir şey yok... Ben olmalıyım...",
"VO__BANDIT_S2__GENERIC__STATIC__RESUME_SPOTTER__001__M__1": "Hiçbir şey bulamıyorum.",
"VO__BANDIT_S2__GENERIC__STATIC__RESUME_SPOTTER__001__M__2": "Burada bir şey yok.",
"VO__BANDIT_S2__GENERIC__STATIC__RESUME_SPOTTER__001__M__3": "Her şey normal görünüyor.",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_ALONE__001__M__1": "Saklanmayı bırakın, ödlekler!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_ALONE__001__M__2": "İstediğin kadar saklan! Seni kurtarmaz!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_ALONE__001__M__3": "Neredesiniz?! Gösterin kendinizi!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_FOUND__001__M__1": "Gelin buraya! Buldum onları!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_FOUND__001__M__2": "Buraya! Çabuk kımıldayın!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_FOUND__001__M__3": "İşte! Görüyorum onları!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER__001__M__1": "Gözden kaybettim onları!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER__001__M__2": "O serseriler hâlâ yakında olmalı!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER__001__M__3": "Neredeler?!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__1": "Oraya siper alıyorlar, yakalayın onları!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__2": "Tam arkada, gidin yakalayın onları!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__3": "Orada siper almaya çalışıyorlar! Peşlerinden!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Utanma, çık oradan!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Oraya saklanmayı bırak, ödlek!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Seni onun arkasında gözden kaçırırım mı sandın?!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı indiler! Gidin!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı indiler, peşlerinden!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağı inin ve yakalayın o serserileri!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağı atladığını gördüm! Ödlek!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Geri çık buraya ve dövüş!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Aşağı atladığını görmedim mi sandın?!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__1": "Çimene saklandıklarını gördüm!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__2": "O çimenlikteler! Peşlerinden gidin!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__3": "Çimenliğe girdiler! Takip edin onları!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Çık o çimenden! Hemen!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "O çimenden çıkmasan iyi edersin!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Çimende saklanıyorsunuz, ödlekler!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altına girdiler! Gidin!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altındalar! Acele edin!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__3": "Çıkarın onları oranın altından!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Oranın altına girdiğini gördüm! Ödlek!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Çık oranın altından ve dövüş!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Oranın altına girdiğini görmedim mi sandın?!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__1": "Yukarı çıktılar! Yakalayın onları!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__2": "Yukarıdalar! Acele edin!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__3": "Yukarı tırmanın ve yakalayın o serserileri!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarı tırmandığını gördüm! Ödlek!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Geri in buraya ve dövüş!",
"VO__BANDIT_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Yukarı tırmandığını görmedim mi sandın?!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__1": "Yine mi?! Gel buraya!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__2": "İşte yine başladı! Bak bakalım neydi!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__3": "Geri geldi! Bak ne olduğuna!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Geri geldi! Olamaz!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Yine mi?",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Yine olmasın!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__1": "O ses neydi? Bir baksak iyi olur!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__2": "Bak bakalım o sesi ne çıkardı!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__3": "Orada bir şey duydum! Git bir bak!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "O ses neydi?",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Bu sesi çıkaran ne?",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "O ses neydi?",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__1": "Git bak, şu ateşin nesi var!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__2": "Şu ateşe ne oluyor? Git bak!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__3": "Ateş! Sen de gördün! Git bir bak!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Ateş! Bir terslik var!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Bu lanet ateşin nesi var be, kahretsin?!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Büyücülük olmalı!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__1": "Orada bir şey gördüm.",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__2": "Orada bir şey var.",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__3": "Orada bir şey kımıldadı.",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__1": "Kim var orada?! Göster kendini!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__2": "O da neydi...?",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__3": "Hey! Orada biri mi var?!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__1": "Sanırım orada arkada bir şey gördüm...",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__2": "Ha?! Orada arkada bir şey kımıldadı!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__3": "Orada arkada! Az önce bir şey gördüm!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__1": "Aşağıda bir şeyler oluyor!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__2": "Gördün mü?! Aşağıda bir şey var!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__3": "Hareket! Aşağıda!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__1": "Sanırım çimende bir şeyin kımıldadığını gördüm!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__2": "O çimende bir şey kımıldadı!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__3": "Çimende bir hareket gördüm!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__1": "Hey! Orada bir şey kımıldadı!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__2": "Yemin ederim orada bir şey gördüm!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__3": "Hey! Az önce orada bir hareket gördüm!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__1": "Yukarıda bir şeyler oluyor!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__2": "Gördün mü?! Yukarıda bir şey var!",
"VO__BANDIT_S2__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__3": "Hareket! Yukarıda!",
"VO__BANDIT_S3__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Her yeri arayın! Biri bela arıyor!",
"VO__BANDIT_S3__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Biri bizimle oynuyor, bölgeyi tarayın!",
"VO__BANDIT_S3__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Her yeri arayın! İki kez yeterdi...",
"VO__BANDIT_S3__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Bu kadar yeter! Göster kendini hemen!",
"VO__BANDIT_S3__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Beni bir daha kandıramazsın!",
"VO__BANDIT_S3__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Akıllı olduğunu mu sanıyorsun? Göreceğiz!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT__001__M__1": "Davetsiz misafirlerimiz var!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT__001__M__2": "Davetsiz misafirler! Peşlerinden!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT__001__M__3": "Burada izinsiz girenler var!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Ne işin var burada?!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Sen! Hemen dur!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Durun burada, serseriler!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Bu kadar kolay pes etmem, yakalayacağım seni!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "Şimdi sana ulaşamam, ama sen bekle bakalım!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Hep böyle tıkılı kalmayacağım, inan bana!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Tıkıldım mı sandın? Beni tanımıyorsun!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Burada kalacağımı sanma! Bir yolunu bulacağım...",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "İşim daha bitmedi sanma. Yakalayacağım seni.",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_DYING__001__M__1": "Öldü! Kahretsin!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_DYING__001__M__2": "Kahretsin! Öldü!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_DYING__001__M__3": "Öldürüldü!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Ateşin o çimene ne yaptığını göreceksin!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Biri çimende saklanmıyor olsa iyi olur!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "Seni dumanla dışarı çıkaralım!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Kaçıyorlar! Yakalayın onları!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Şunları yakalamama yardım edin!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Şu davetsiz misafirleri burada durdurun, çabuk!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılın! Yakınlarda olmalılar!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Herkes! Bölgeyi kapatın!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Yayılın ve yakalayın o serserileri!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Artık yakaladım seni, serseri!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Artık kaçamazsın!",
"VO__BANDIT_S3__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Öldün sen! Duydun mu?!",
"VO__BANDIT_S3__GENERIC__PATROL__BURNING__001__M__1": "Niye yanıyor?!",
"VO__BANDIT_S3__GENERIC__PATROL__BURNING__001__M__2": "Bir şey yanıyor!",
"VO__BANDIT_S3__GENERIC__PATROL__BURNING__001__M__3": "Ateş mi? Burada mı?!",
"VO__BANDIT_S3__GENERIC__PATROL__CAPTURE__001__M__1": "Sen olman benden iyidir.",
"VO__BANDIT_S3__GENERIC__PATROL__CAPTURE__001__M__2": "İnan bana, daha kötü ölüm şekilleri var.",
"VO__BANDIT_S3__GENERIC__PATROL__CAPTURE__001__M__3": "Son dileklerle uğraşmam ben.",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE__001__M__1": "Sana ne oldu böyle?",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE__001__M__2": "Her şey yolunda mı? Hey!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE__001__M__3": "Hasta mısın nesin? Hey!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Hey! Uyuyor musun?",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Hey dostum! Uyan!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Hadi, kalk ayağa!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Diri diri yanmış...",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Tamamen yanmış... İğrenç!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Biri kan peşinde...",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Eh... Görünüşe göre sıçanlar akşam yemeğini bulmuş!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Aklını kullansaydın bu olmazdı.",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Lanet sıçanların seni yemesine nasıl izin verdin?!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Biri adamlarımızdan birini hakladı! Her yeri arayın!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Gözünüzü açık tutun! Biri öldürüldü!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Saldırı altındayız! Bölgeyi arayın!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Soğukkanlılıkla öldürülmüş. Kim yaptı bunu?!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Gitti... Bunu yapan serseriyi bulacağım!",
"VO__BANDIT_S3__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Zavallı serseri... Sana bunu yapanı yakalayacağım!",
"VO__BANDIT_S3__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Hoşuna gitti mi?!",
"VO__BANDIT_S3__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Ölü etisin sen!",
"VO__BANDIT_S3__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Kaçamazsın, gördün mü?!",
"VO__BANDIT_S3__GENERIC__PATROL__DYING__001__M__1": "Kahretsin!",
"VO__BANDIT_S3__GENERIC__PATROL__DYING__001__M__2": "Ne oluyor lan...",
"VO__BANDIT_S3__GENERIC__PATROL__DYING__001__M__3": "Hay aksi!",
"VO__BANDIT_S3__GENERIC__PATROL__FLEE_RATS__001__M__1": "Hayır!",
"VO__BANDIT_S3__GENERIC__PATROL__FLEE_RATS__001__M__2": "Kaçın!",
"VO__BANDIT_S3__GENERIC__PATROL__FLEE_RATS__001__M__3": "Yardım edin!",
"VO__BANDIT_S3__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Bu... çok yakındı...",
"VO__BANDIT_S3__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Yaşıyor muyum? Yaşıyor muyum?!",
"VO__BANDIT_S3__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "Başardım! Alın size... sizi sıçanlar!",
"VO__BANDIT_S3__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Biri bana saldırıyor! Bulun onları!",
"VO__BANDIT_S3__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Vuruldum! Bunu yapan serserileri bulun!",
"VO__BANDIT_S3__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Biri beni öldürmeye çalışıyor! Yardım edin!",
"VO__BANDIT_S3__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Serseri! Bunun bedelini ödeteceğim!",
"VO__BANDIT_S3__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Bunun bedelini ödeyeceksin!",
"VO__BANDIT_S3__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Bunun için öleceksin!",
"VO__BANDIT_S3__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "İyi misin?",
"VO__BANDIT_S3__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Bir sorun mu var?",
"VO__BANDIT_S3__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Bir şey mi oldu?",
"VO__BANDIT_S3__GENERIC__PATROL__OIL__001__M__1": "Her yer katran mı? Kim yaptı bunu?",
"VO__BANDIT_S3__GENERIC__PATROL__OIL__001__M__2": "Hangi aptal döktü bunu?!",
"VO__BANDIT_S3__GENERIC__PATROL__OIL__001__M__3": "Katran kokuyor...",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION__001__M__1": "Şimdi ne var?",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION__001__M__2": "Ne oluyor lan?",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION__001__M__3": "O da neydi?",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION_RATS__001__M__1": "Buraya kadar gelebilirsin!",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION_RATS__001__M__2": "Bu kadar yeter!",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION_RATS__001__M__3": "Tam orada kal sen!",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Lanet sıçanlar! Daha ileri gidemiyorum.",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "Siz sıçanlar daha ileri gitmeme izin vermeyecek misiniz?!",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Burada kalmamı mı istiyorsunuz? Sizin bileceğiniz iş.",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "Beni yemeden geçmeme izin verme ihtimaliniz var mı?",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "Biraz daha ilerlersem diri diri yenilirim.",
"VO__BANDIT_S3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Ben burada kalayım o zaman...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME__001__M__1": "Kendine gel...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME__001__M__2": "Biraz uyumam lazım...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME__001__M__3": "Yok be...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Tamam, daha fazla aramaya gerek yok.",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Yine yanılmışım...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Bir yanlış alarm daha...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "İlk seferki gibi yanılmışım...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Yine tamamen yanılmışım...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Hâlâ bir şey yok...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_RATS__001__M__1": "Bu haşarattan nefret ediyorum.",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_RATS__001__M__2": "Çılgın sıçanlar.",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_RATS__001__M__3": "Serseri sürüsü.",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Eh, bir şey yokmuş.",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Rapor edecek bir şey yok.",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Tamam, bir şey yok...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Pekâlâ, halüsinasyon görüyor olmalıyım...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Burada bir şey yok...",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Güzel, her yer temiz.",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Bir şey söyleyecektim... Ah evet!",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Eee, nerede kalmıştık? Ha doğru!",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Neyse, ne diyordum? Ah, hatırladım!",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Neyse boş ver.",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Bir dahaki sefere artık.",
"VO__BANDIT_S3__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Tamam, bir sonrakine kadar...",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH__001__M__1": "Kaçırdım onları! Gözünüzü dört açın!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH__001__M__2": "Hâlâ buralarda olmalılar! Tetikte olun!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH__001__M__3": "Serseriler kaçtı! Her yere bakın!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Seni bulamam mı sandın?!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Benden kaçamayacaksın!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Seni bulmamam için dua et!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Tamamdır!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Tamam!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Hallediyorum!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Şimdi eminim seni burada bulacağım!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Demek o taraftasın?!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Kendinizi ele verdiniz, serseriler!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Buraya! Peşlerinden!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Buradalar! Çabuk kımıldayın!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Buradalar! Yakalayın onları!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Kıpırdama!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Seni bulacağımı biliyordum!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Artık yakaladım seni!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Davetsiz misafirlerimiz var! Bir şey görürseniz haber verin!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Biri etrafta dolaşıyor! Aramaya başlayın!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Hey! Öyle dikilmeyin! Davetsiz misafirler var!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Elbette!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Yakalayacağız onları!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Tamamdır!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Onlar olduğundan kesinlikle eminim...",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Onlar... Hayatıma bahse girerim!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Bunu onlar yaptı! Eminim!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Artık göremiyorum onları!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "O serseriler uzakta olamaz!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Yakında bir yerde saklanıyor olmalılar!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Orada arkada saklanıyorlar! Ben hallederim!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Serserilerin oraya saklandığını gördüm! Peşlerinden gidiyorum!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Oraya siper aldılar! Hallediyorum!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Onun arkasına saklanıp akıllılık ettiğini mi sanıyorsun?",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Siper almaya mı çalışıyorsun, ha? İşe yaramayacak!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Tam orada arkada kal, geliyorum!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağıdalar! Avdayım!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı atladılar! Yakalayacağım onları!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Serseriler aşağı indi! Peşlerinden gideceğim!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağıda saklanmak seni kurtarmaz!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Neden aşağı atladın? Gerçekten güvende olacağını mı sandın?!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Aşağı atladığını gördüm! Kaçamayacaksın!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "O çimenlikteler! Bulacağım onları!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Çimenliğe girdiler!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Çimenliğin bir yerindeler! Yakalayacağım onları!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Eminim o çimendesin!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Çimende güvende olduğunu mu sanıyorsun?!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Orada arkada kal, geliyorum!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altına girdiler! Avdayım!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altında saklanıyorlar! Yakalayacağım onları!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Serseriler oranın altına girdi! Peşlerinden gideceğim!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Siz serseriler oranın altına mı süründünüz?! Artık kapana kısıldınız!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Neden oranın altına girdin? Güvende olduğunu mu sanıyorsun?!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Oranın altına girdiğini gördüm! Kaçamazsın!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Yukarıdalar! Ava çıkalım!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "Yukarı tırmandılar! Yakalayın!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Serseriler yukarı çıktı! Peşlerinden gidin!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarıda saklanmak seni kurtarmaz!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Yukarı tırmanmak seni kurtarmaz!",
"VO__BANDIT_S3__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Yukarı çıktığını gördüm! Kaçamayacaksın!",
"VO__BANDIT_S3__GENERIC__PATROL__SMOKE__001__M__1": "Bu dumanı çıkaran ne?",
"VO__BANDIT_S3__GENERIC__PATROL__SMOKE__001__M__2": "Bir şey mi tütüyor?!",
"VO__BANDIT_S3__GENERIC__PATROL__SMOKE__001__M__3": "Burada duman mı var? Gidip bakalım.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Orada hâlâ bir şey var!",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine olmasın!",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "Yine oluyor! Temiz olduğundan emin olmalıyız...",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine başlıyorum...",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Biri beni iki kez mi kandırıyor? Tamam, öğreneceğim...",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Yine mi?!",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Gidiyorum.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Hallederim.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Bunu hallederim.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Ha..! O sesin ne olduğuna baksam iyi olur!",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "Sen de duydun mu?! Misafirlerimiz olabilir!",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "O ses neydi? Gidip bir bakacağım!",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bir şey duydum...",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Ne? O ses neydi lan?",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "O ses mi?! Nedir o?",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "Tuhaftı, şu ateşe ne olduğuna baksam iyi olur.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "Bu büyü! Daha yakından bakacağım!",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Ateşte bir terslik var... Gidip bir bakacağım!",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Şu ateş normal değil?! Nedir o?",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Bu büyücülük mü?!",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Bu ateş... Normal değil?!",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Kim sapanla oynuyor? Hemen dönerim.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "O çıtırtı tuhaftı?... Bakacağım.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "O çatırtı yakındı... Şuna bir bakayım...",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Sapan mı o, bizden biri değil...",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "Sapandı o...",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "O çıtırtı neydi?! Emin olsam iyi olur...",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Sanırım orada bir şey var. Bir bakacağım.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Bir şeyin kımıldadığını gördüm. Bir dakika ver.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Onu gördün mü? Emin olalım...",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Kimdi o...?",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "O mu...? Bakalım.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Dışarıda biri mi var?!",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Köşeleri kolla.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Bir şey görürsen bağır yeter.",
"VO__BANDIT_S3__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Sakın öldürülme.",
"VO__BANDIT_S3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Hiçbir şey bulamıyorum.",
"VO__BANDIT_S3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Nereye gittiler...",
"VO__BANDIT_S3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Burada bir şey bulamayacağım...",
"VO__BANDIT_S3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "İzleri yok...",
"VO__BANDIT_S3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Neredeler o serseriler?",
"VO__BANDIT_S3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Neredeler?",
"VO__BANDIT_S3__GENERIC__STATIC__ALERT_ALONE__001__M__1": "Sen oradaki! Kıpırdama!",
"VO__BANDIT_S3__GENERIC__STATIC__ALERT_ALONE__001__M__2": "Olduğun yerde kal, anlaşıldı mı?!",
"VO__BANDIT_S3__GENERIC__STATIC__ALERT_ALONE__001__M__3": "Görüyorum seni! Kıpırdama!",
"VO__BANDIT_S3__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__1": "Kim ateş ediyor bana?!",
"VO__BANDIT_S3__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__2": "Ateş etmeyi kes bana! Hayvan!",
"VO__BANDIT_S3__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__3": "Kes şunu! Seni pis serseri!",
"VO__BANDIT_S3__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__1": "Yine bir şey yok.",
"VO__BANDIT_S3__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__2": "İlk seferki gibi hiçbir şey yok...",
"VO__BANDIT_S3__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__3": "Yine hiçbir şey bulamıyorum.",
"VO__BANDIT_S3__GENERIC__STATIC__RESUME_SPOTTER__001__M__1": "Her yer temiz ve sessiz...",
"VO__BANDIT_S3__GENERIC__STATIC__RESUME_SPOTTER__001__M__2": "Normal görünüyor.",
"VO__BANDIT_S3__GENERIC__STATIC__RESUME_SPOTTER__001__M__3": "Boş ver, her şey temiz görünüyor.",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_ALONE__001__M__1": "Hâlâ orada olduğunu biliyorum! Çık dışarı!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_ALONE__001__M__2": "Saklanmak seni benden kurtarmaz!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_ALONE__001__M__3": "Neredesin?!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_FOUND__001__M__1": "Buldum onları! Bu taraftan!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_FOUND__001__M__2": "Görüyorum onları! Kaçmalarına izin vermeyin!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_FOUND__001__M__3": "İşte! Peşlerinden!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER__001__M__1": "Kaçtılar!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER__001__M__2": "Gittiler! Lanet serseriler!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER__001__M__3": "Saklanıyor olmalılar!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__1": "Oraya arkaya geçtiler! Yakalayın onları!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__2": "Oraya arkaya saklanmalarına izin vermeyin!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__3": "Serseriler orada arkada sinmeye çalışıyor! Kımıldayın!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Seni ödlek! Çık oradan arkadan!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Onun arkasına saklanmana gerek yok.",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Orada arkada saklanmayı bırak! Göster kendini!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı indiler! Yakalayın o serserileri!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağıdalar! Çabuk yakalayın onları!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağı atladılar! Peşlerinden koşun!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Hey, aşağıda güvende olmayacaksın!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Aşağı inmek seni kurtarmaz!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Neden aşağı indin? Korktun mu?!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__1": "Uzun çimenliğe girdiler! Peşlerinden!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__2": "O çimende saklanabileceklerini sanıyorlar! Yakalayın onları!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__3": "Uzun çimenliğin içinde kayboldular! Bulun onları!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "O çimene girdiğini görmedim mi sandın!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Çimenin bir yerinde saklandığını biliyorum, serseriler!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Çık o çimenden, ödlek!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altına girdiler! Yakalayın o serserileri!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altındalar! Çabuk yakalayın onları!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__3": "Oranın altına saklanıyorlar! Peşlerinden koşun!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Siz serseriler oranın altına mı süründünüz?! Artık kapana kısıldınız!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Oranın altına girmek seni kurtarmaz!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Neden oranın altına saklanıyorsun? Korktun mu?!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__1": "Yukarı çıktılar! Yakalayın o serserileri!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__2": "Yukarıdalar! Çabuk yakalayın onları!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__3": "Yukarı tırmandılar! Peşlerinden koşun!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarıda kal, peşindeyiz!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Yukarı çıkmak seni kurtarmaz!",
"VO__BANDIT_S3__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Neden yukarı çıktın? Korktun mu?!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__1": "Yine oluyor! Orada!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__2": "Ne ol-- Orada hâlâ bir şey var!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__3": "Orada hâlâ bir şey var!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Ne?! Yine mi?!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Yine mi?! Bakalım burada neler oluyor!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Bir kez daha mı?! Gerçekten mi?!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__1": "Gidip o sesi ne çıkardı baksam iyi olur!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__2": "Sen de duydun mu?! Git bak ne olduğuna!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__3": "Bir şey duydum! Şu taraftan geldi!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu ses de ne?",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Bu sesi çıkaran ne?",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "O sesi ne çıkardı...?",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__1": "Şu ateşe ne oluyor? Git baksan iyi olur!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__2": "Şu ateşe ne oldu lan? Git bak!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__3": "Git bak, şu ateşin nesi var!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "O ateş ne yapıyor?!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Ateşe az önce ne oldu?!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Şu ateşin nesi var lan?!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__1": "Orada bir şeyler oluyor.",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__2": "Burada bir şey kımıldadı...",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__3": "Sanırım orada bir şey var.",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__1": "Ha?! O da neydi...?",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__2": "Kim var etrafta?",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__3": "Hey! Kim var orada?!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__1": "Orada arkada! Bir hareket gördüm!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__2": "Gördün mü?! Tam arkada bir şey kımıldadı!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__3": "Arkasında! Sanırım bir şey gördüm!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__1": "Aşağıda bir şeyler oluyor!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__2": "Aşağıda! Sanırım bir şey kımıldadı!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__3": "Sanırım az önce aşağıda bir hareket gördüm!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__1": "Gördün mü?! Çimende bir hareket vardı!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__2": "Sanırım az önce çimende bir şey gördüm!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__3": "Uzun çimen! Az önce kımıldadı!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__1": "Sanırım orada bir şeyin kımıldadığını gördüm!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__2": "Orada! Bir şeyin kımıldadığını gördüm!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__3": "Yemin ederim onun arkasında bir hareket gördüm!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__1": "Yukarıda bir şeyler oluyor!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__2": "Yukarıda! Sanırım bir şey kımıldadı!",
"VO__BANDIT_S3__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__3": "Sanırım az önce yukarıda bir hareket gördüm!",
}
