# -*- coding: utf-8 -*-
# Genel Sesler GS6: SOLDIER_N1+N2+N3 generic VO (681 satir). Askerler: disiplinli, sert, "sen/siz".
T = {
"VO__SOLDIER_N1__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Biri bizimle uğraşıyor! Bulun onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Biri kesinlikle bizimle oynuyor! Gidin bulun onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Oynamak mı istiyorsun? Tamam! Herkes, misafirimiz var!",
"VO__SOLDIER_N1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Yine mi? Tamam, küçük oyununu bitireceğim!",
"VO__SOLDIER_N1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Benimle uzun süre oynayamazsın! Geliyorum!",
"VO__SOLDIER_N1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Bu sefer beni oyalamana izin vermeyeceğim!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT__001__M__1": "Burada davetsiz misafirler var!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT__001__M__2": "Buraya! Misafirimiz var!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT__001__M__3": "Gelin buraya! İzinsiz girenler var!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Sen oradaki! Ne yapıyorsun?!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Sen! Kıpırdama!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Orada kal! Yoksa pişman ederim seni!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Bittiğini sanma! Sana ulaşmanın bir yolunu bulacağım!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "Burada tıkalı olabilirim ama seninle işimiz daha bitmedi!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Bir şekilde sana ulaşacağım! Ve sonra...",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Sonsuza dek ulaşılmaz kalamayacaksın.",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Sana ulaşmanın yolunu bulacağım!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Merak etme! Sana ulaşmanın yolunu bulacağım!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BOMB__001__M__1": "Ye bunu!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BOMB__001__M__2": "Yakala bunu!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BOMB__001__M__3": "Bum!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BOMB__001__M__4": "Geliyor!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BOMB__001__M__5": "Al bunu serseri!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_BOMB__001__M__6": "Patlamanın tadını çıkar!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_DYING__001__M__1": "Hayır hayır hayır! Öldürüldü!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_DYING__001__M__3": "Agh! Öldü!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Dünyanı ateşe verelim!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Şenlik ateşlerine bayılırım, ya sen?",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "Çimen yangınından öldü!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Çabuk hareket edin! Yakalayın davetsiz misafirleri!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Sen! Öldürelim o serserileri.",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Hemen benimle! İzinsiz girenler var!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılın! Uzağa kaçmış olamazlar!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Dağılın, bölgeyi arayın!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Yayılın! Serserilerin kaçmasına izin vermeyin!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Üzgünüm, işin bitti!",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Bitti ve sen de biliyorsun...",
"VO__SOLDIER_N1__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Hikâyenin sonu...",
"VO__SOLDIER_N1__GENERIC__PATROL__BURNING__001__M__1": "Aman Tanrım, yanıyor!",
"VO__SOLDIER_N1__GENERIC__PATROL__BURNING__001__M__2": "Bir ateş! Bu nasıl olur?",
"VO__SOLDIER_N1__GENERIC__PATROL__BURNING__001__M__3": "Bu ateşi burada kim yaktı?",
"VO__SOLDIER_N1__GENERIC__PATROL__CAPTURE__001__M__1": "Sana son bir an vereceğim.",
"VO__SOLDIER_N1__GENERIC__PATROL__CAPTURE__001__M__2": "Görünüşe göre bu senin son günün.",
"VO__SOLDIER_N1__GENERIC__PATROL__CAPTURE__001__M__3": "Gözlerini kapat.",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE__001__M__1": "Kalk! Hey!",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE__001__M__2": "Hadi, kalk! Kalk!",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE__001__M__3": "İyi misin? Hey!",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Kalkmıyor...",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Neden orada yatıyor?!",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Hey! Ne oldu? Hey!",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Tamamen yanmış!",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Ateşe verilmiş... Zavallı adam.",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Kavrulmuş...",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Kemiğine kadar yenmiş...",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Acımasız küçük serseriler...",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Umarım sıçanlar sana ulaştığında çoktan ölmüştün...",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Burada biri öldürülmüş! Dikkat!",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Burada bir ceset var! Bölgeyi arayın!",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Öldü! Dikkat! Davetsiz misafirler var!",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Gerçekten ölmüş... Birisi bunun bedelini ödeyecek!",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Hay aksi... Ölmüş! Yemin ederim katili bulacağım!",
"VO__SOLDIER_N1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Öldürülmüş! Katil hâlâ buralarda olmalı...",
"VO__SOLDIER_N1__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Görünüşe göre senin için bu kadar.",
"VO__SOLDIER_N1__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Yapabileceğinin en iyisi bu mu?!",
"VO__SOLDIER_N1__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Sana bir ders vereceğim!",
"VO__SOLDIER_N1__GENERIC__PATROL__DYING__001__M__1": "Dur hayır!",
"VO__SOLDIER_N1__GENERIC__PATROL__DYING__001__M__2": "Yapma!",
"VO__SOLDIER_N1__GENERIC__PATROL__DYING__001__M__3": "Neler oluyor?",
"VO__SOLDIER_N1__GENERIC__PATROL__FLEE_RATS__001__M__1": "Geri çekilin sıçanlar!",
"VO__SOLDIER_N1__GENERIC__PATROL__FLEE_RATS__001__M__2": "Bunu hak etmiyorum!",
"VO__SOLDIER_N1__GENERIC__PATROL__FLEE_RATS__001__M__3": "Beni yakalayamayacaksınız!",
"VO__SOLDIER_N1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Şimdi ne yapacaksın, ha?!",
"VO__SOLDIER_N1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Ucu ucuna kurtuldum...",
"VO__SOLDIER_N1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "Gerçekten işimin bittiğini sanmıştım...",
"VO__SOLDIER_N1__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Saldırı altındayım! Yardım edin!",
"VO__SOLDIER_N1__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Biri beni hedef alıyor! Yardım!",
"VO__SOLDIER_N1__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Hedef alınıyorum! Davetsiz misafirler var!",
"VO__SOLDIER_N1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Lanet olsun! Eline geçtiğin zaman görürsün!",
"VO__SOLDIER_N1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Bana bir daha vurmayı dene! Bak neler olacak!",
"VO__SOLDIER_N1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Seni küçük— Bunun için öldüreceğim seni!",
"VO__SOLDIER_N1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Her şey yolunda mı?",
"VO__SOLDIER_N1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Bir sorun mu var?",
"VO__SOLDIER_N1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Hâlâ orada mısın?",
"VO__SOLDIER_N1__GENERIC__PATROL__OIL__001__M__1": "Buraya nasıl katran dökülmüş?",
"VO__SOLDIER_N1__GENERIC__PATROL__OIL__001__M__2": "Bu da ne? Sanki... katran mı?",
"VO__SOLDIER_N1__GENERIC__PATROL__OIL__001__M__3": "Burada neden katran var?",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION__001__M__1": "Ne?",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION__001__M__2": "Ne oluyor lan?",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION__001__M__3": "O da ne?!",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION_RATS__001__M__1": "Orada kal, tamam mı?",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION_RATS__001__M__2": "Siz serseriler beni gerçekten seviyor gibisiniz.",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION_RATS__001__M__3": "Gidin başka bir akşam yemeği bulun, haşarat!",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Görünüşe göre daha ileri gitmeyeceğim!",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "Tamam, burada güvende kalayım...",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Görünüşe göre burada sıkıştım...",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "Onların yanından nasıl geçeceğim...",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "Peki, burada güvende kalalım...",
"VO__SOLDIER_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Geçmeme izin vermeyeceksiniz, ha?",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME__001__M__1": "Bir şey yok...",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME__001__M__2": "Tuhaf...",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME__001__M__3": "Garip...",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Öncekiyle aynı, boş ver!",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Endişelenecek bir şey yok, az önceki gibi.",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Bir yanlış alarm daha...",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Yine yanlış alarm. Bilmeliydim...",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Bir yanlış alarm daha, biliyordum!",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Yine bir şey yok...",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_RATS__001__M__1": "Pis hayvanlar.",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_RATS__001__M__2": "İğrenç yaratıklar.",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_RATS__001__M__3": "Lanet haşarat.",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Her yer temiz.",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Burada bir şey yok.",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Hiçbir şey yok...",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Bir şey yokmuş herhalde...",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Her yer temiz...",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Sadece yanlış alarmmış...",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Neyse, ne diyordum? Ah, geliyor aklıma!",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Ne diyordum? Ah, hatırladım!",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Eee, ne diyordum? Ah evet!",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Ne sürpriz ama!",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Sürpriz değil...",
"VO__SOLDIER_N1__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Nöbete dönelim...",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH__001__M__1": "Bulamıyorum onları! Aramaya devam edin!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH__001__M__2": "Uzağa gitmiş olamazlar! Her köşeyi arayın!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH__001__M__3": "Nereye gittiler?! Bulun onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Saklanıyoruz, ha? Yine de bulacağım seni!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Çıkın dışarı, ödlekler!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Seni bulduğumda pişman olacaksın!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Derhal...",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Gidelim!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Bitmiş bil.",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Orada olduğunu biliyorum!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Sizi aptallar! Artık nerede saklandığınızı biliyorum!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Orada saklanıyor olmalılar!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Buraya! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Buradalar! Durdurun onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Buldum onları! Gelin yardım edin!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Benimsin!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "İşte buradasın!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "İşiniz bitti, serseriler!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Misafirimiz var! Bir şey görürseniz haber verin!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Bölgeyi arayın! Misafirimiz var!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Bölgede davetsiz misafirler var! Aramaya başlayın!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Gidiyorum!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Tamam!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Gidelim!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Onun arkasındalar! Eminim!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Onlar bu, eminim!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Bunu onlar yaptı... Şüphe yok!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Nereye gitti lan... Kaybettim onları...",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "İmkânsız, nereye gittiler?",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Hadi ama! Az önce buradaydılar ve sonra...",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Orada arkaya siper aldılar! Yakalayacağım onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Onun arkasına saklandıklarını gördüm! Benimle!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "İzinsiz girenler oranın arkasına geçti! Bulun onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Orada arkada mı saklanıyorsun?! Uzun sürmez!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Onun arkasında güvende olduğunu mu sanıyorsun?!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Orada arkada mı saklanıyorsun?! İşin bitti!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı indiler! Yakalayacağım onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı atladılar! Yakalayacağım onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağı atladıklarını gördüm! Takip ediyorum onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Seni ödlek! Geri çık buraya!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Aşağı atladığını biliyorum! İyi saklansan iyi edersin!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Seni aşağıda bulamayacağımı mı sanıyorsun?!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "İşleri bitti, çimendeler!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Şu çimenin bir yerindeler!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Çimene sığındıklarını gördüm!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Çimende, ha?! Daha akıllı olursun sanmıştım!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Seni çimenden ayaklarından sürükleyeceğim, söz veriyorum.",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Çimenin seni benden saklayacağını mı sanıyorsun?",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Sanırım oranın altındalar! Köklerini kazıyacağım!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altına girdiler! Yakalayacağım onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Oranın altında saklanıyorlar! Onları oradan sürükleyip çıkaracağım!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Seni ödlek! Oranın altında bile yakalarım seni...",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Seni oradan sürükleyip çıkarabilirim, biliyorsun değil mi?!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Çıksan iyi edersin oranın altından!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Sanırım yukarı çıktılar!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "Oraya tırmandılar! Yakalayın onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Tırmandıklarını gördüm! Takip edin onları!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Seni ödlek! Geri in buraya!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Tırmandığını biliyorum! İyi saklansan iyi edersin!",
"VO__SOLDIER_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Seni yukarıda bulamayacağımı mı sanıyorsun?!",
"VO__SOLDIER_N1__GENERIC__PATROL__SMOKE__001__M__1": "Bu duman da ne?",
"VO__SOLDIER_N1__GENERIC__PATROL__SMOKE__001__M__2": "Şu duman bulutu... Bir baksam iyi olur...",
"VO__SOLDIER_N1__GENERIC__PATROL__SMOKE__001__M__3": "Duman, nereden?",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Olamaz... Yine mi?",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yemin ederim biri bizimle dalga geçiyor! Bana bırak!",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "İmkânsız, yine mi?! Şunu halledelim...",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "İki kez mi? Neler olduğunu öğrensem iyi olur...",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Yine mi? Ve burada tek başımayım...",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Ne oluyor be? Yine mi?! Peki, bir bakalım!",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Gidip bakacağım.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Ben ilgilenirim.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Hallederim.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "O sesin ne olduğuna baksam iyi olur!",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "O ses bir davetsiz misafir olabilir! Bakacağım!",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Orada sesler duyuyorum! Gidip bakacağım!",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu sesi çıkaran ne?",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Sanırım bir şey duydum...",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "O ses. Neler oluyor?",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "O ateş neden böyle tuhaf davranıyor? Gidip bakacağım.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "Şu ateşi gördün mü?! Burada bekle, bakacağım.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Şu ateşte bir terslik var! Bir bakacağım!",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Şu ateş... tuhaf... Dikkatli olsam iyi olur.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Şu ateş... Normal olamaz...",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Şu ateş tuhaf görünüyor... Bu hayra alamet değil...",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Sanki şu taraftan geldi... Bir bakayım.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "O ses... Gidip ne olduğuna bakacağım.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "Bir tür çatırtı duydum. Araştıracağım.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "O çatırtıyı çıkaran her neyse yakın olmalı...",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "O çatırtı... Dikkatli olsam iyi olur...",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "O çatırtı neydi?",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Orada bir şey mi gördün...? Gidip baksam iyi olur...",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Orada bir hareket gördüm. Gidip ne olduğuna bakacağım.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Sanırım orada bir şey kımıldadı. Bakayım.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Orada ne kımıldıyor...? Daha yakından baksam iyi olur.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Bir şey gördüm... Bakacağım...",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Ha?! Bir baksam iyi olur...",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Bir şey görürsen bağır.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Tetikte ol.",
"VO__SOLDIER_N1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Bir şey görürsen bağır.",
"VO__SOLDIER_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Başka bir bölgeyi tarasam iyi olur...",
"VO__SOLDIER_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Burada aramanın anlamı yok...",
"VO__SOLDIER_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Bu bölge temiz...",
"VO__SOLDIER_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Belki oraya gittiler...",
"VO__SOLDIER_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Burada kimse yok. Devam edelim.",
"VO__SOLDIER_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "İzleri yok...",
"VO__SOLDIER_N2__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Biri bizimle oynuyor! Her yeri arayın!",
"VO__SOLDIER_N2__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Bizimle kim oynuyor bilmiyorum ama çabuk yakalayalım onları!",
"VO__SOLDIER_N2__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Küçük bir serseri oyun oynuyor! Hemen durdurun onları!",
"VO__SOLDIER_N2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Bu sefer göster kendini, ödlek!",
"VO__SOLDIER_N2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Artık sıkılıyorum! Buna pişman edeceğim seni!",
"VO__SOLDIER_N2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Bu sefer eline geçeceksin!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT__001__M__1": "İşte, davetsiz misafirler! Hemen yakalayın onları!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT__001__M__2": "Burada davetsiz misafirler var! Yakalayın onları!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT__001__M__3": "Gelin buraya! Misafirimiz var!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Sen de kimsin be?!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Dur! Burada işin yok!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Sen! Dur yoksa kendim durdururum seni!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Er ya da geç seni yakalamanın yolunu bulacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "Sana ulaşamıyorum diye güvende olduğunu mu sanıyorsun?",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Geliyorum, duyuyor musun? Bir yolunu bulacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Güvende olduğunu mu sanıyorsun?! O kadar emin olmazdım! Seni yine de yakalayacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Burada işimizin bittiğini sanma!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Şimdi burada tıkıldım ama sonsuza dek değil!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BOMB__001__M__1": "Al bakalım!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BOMB__001__M__2": "Geliyor!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BOMB__001__M__3": "Al şunu!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BOMB__001__M__4": "Sana küçük bir hediye atıyorum!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BOMB__001__M__5": "Al bakalım!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_BOMB__001__M__6": "Al bunu!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_DYING__001__M__1": "Adam vuruldu!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_DYING__001__M__2": "Neler oluyor? Öldü!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_DYING__001__M__3": "Aman... Siktir! Öldü!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Diri diri yanacaksın!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Çık dışarı ya da yan. Senin seçimin.",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "Oradaysan kavrulacaksın...",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Davetsiz misafirler! Benimle gelin!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "İşte, yakalayın onları!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "O serseriler burada, yakalayın onları!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Ayrılın! Bölgeyi arayın!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Uzakta olamazlar! Bölgeyi arayın!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Ayrılın! Uzağa kaçmış olamazlar!",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Vaktin doldu.",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Kaçmanın anlamı yok.",
"VO__SOLDIER_N2__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Artık çıkış yok...",
"VO__SOLDIER_N2__GENERIC__PATROL__BURNING__001__M__1": "O ateşi kim çıkardı?",
"VO__SOLDIER_N2__GENERIC__PATROL__BURNING__001__M__2": "Bu... ateş mi?",
"VO__SOLDIER_N2__GENERIC__PATROL__BURNING__001__M__3": "Kahretsin... ateş mi?",
"VO__SOLDIER_N2__GENERIC__PATROL__CAPTURE__001__M__1": "Son sözlerin var mı?",
"VO__SOLDIER_N2__GENERIC__PATROL__CAPTURE__001__M__2": "Uzun sürmeyecek.",
"VO__SOLDIER_N2__GENERIC__PATROL__CAPTURE__001__M__3": "Tanrı ruhuna merhamet etsin.",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE__001__M__1": "Neler oluyor? Hey!",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE__001__M__2": "Hâlâ yaşıyor musun? Hey!",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE__001__M__3": "Uyuyor musun? Hey!",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Neden geri kalkmıyor?",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Yoksa o...?",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Ne yapıyor?",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Tamamen kül olmuş.",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Aman Tanrım... kemiğine kadar yanmış...",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Tamamen yanmış...",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Tamamen yutulmuş...",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Ne korkunç bir ölüm...",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Sıçanlar tarafından yenmiş...",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Biri bize saldırıyor! Tetikte olun!",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Saldırı altındayız! Bulun davetsiz misafirleri!",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Dikkat! Bizimkilerden biri öldürülmüş!",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Ölü mü?! Suçluyu paramparça edeceğim.",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Burada ölü bir asker var! Bulalım katili!",
"VO__SOLDIER_N2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Ölü asker... Bunu kim yaptı...?",
"VO__SOLDIER_N2__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Bunun bittiğini mi sanıyorsun?!",
"VO__SOLDIER_N2__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Teslim ol. İki kez söylemem...",
"VO__SOLDIER_N2__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Son sözlerini söylesen iyi edersin!",
"VO__SOLDIER_N2__GENERIC__PATROL__DYING__001__M__1": "Hayır! Siktir!",
"VO__SOLDIER_N2__GENERIC__PATROL__DYING__001__M__2": "Ciddi misin?!",
"VO__SOLDIER_N2__GENERIC__PATROL__DYING__001__M__3": "Neler oluyor lan!",
"VO__SOLDIER_N2__GENERIC__PATROL__FLEE_RATS__001__M__1": "Defolun, sizi sıçanlar!",
"VO__SOLDIER_N2__GENERIC__PATROL__FLEE_RATS__001__M__2": "Kaybolun!",
"VO__SOLDIER_N2__GENERIC__PATROL__FLEE_RATS__001__M__3": "Defolun başımdan!",
"VO__SOLDIER_N2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Zar zor kaçtım!",
"VO__SOLDIER_N2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Çok yakındı...",
"VO__SOLDIER_N2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "Tam zamanında!",
"VO__SOLDIER_N2__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Biri bana saldırıyor! Bölgeyi arayın!",
"VO__SOLDIER_N2__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Saldırı altındayız! Bulun davetsiz misafirleri!",
"VO__SOLDIER_N2__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Biri bize saldırıyor! Bulun onları!",
"VO__SOLDIER_N2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Bunu yanına bırakacağımı mı sanıyorsun?!",
"VO__SOLDIER_N2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Tamam! Oynamak mı istiyorsun?! Eline geçene kadar bekle!",
"VO__SOLDIER_N2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Buna pişman olacaksın!",
"VO__SOLDIER_N2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Seni duyamıyorum?!",
"VO__SOLDIER_N2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Hey? Nereye gittin?",
"VO__SOLDIER_N2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Konuşmayı mı kestin? İyi misin?",
"VO__SOLDIER_N2__GENERIC__PATROL__OIL__001__M__1": "Biri bir çömlek dökmüş olmalı...",
"VO__SOLDIER_N2__GENERIC__PATROL__OIL__001__M__2": "O katran burada olmamalı...",
"VO__SOLDIER_N2__GENERIC__PATROL__OIL__001__M__3": "Yerde katran... alışılmadık.",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION__001__M__1": "O muydu...?",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION__001__M__2": "Hı?",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION__001__M__3": "Bir saniye...",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION_RATS__001__M__1": "Tam orada kal, duydun mu?!",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION_RATS__001__M__2": "Sıçanlarda bir terslik olduğunu hep biliyordum.",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION_RATS__001__M__3": "Nasıl bu kadar acımasız oldunuz?",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Kahretsin! Daha ileri gidemiyorum!",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "Geçmeme izin verin serseriler!",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Bu zevki size vermeyeceğim, sizi canavarlar!",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "Sizin yüzünüzden burada sıkıştım!",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "Aptal değilim, geçmeye çalışmam!",
"VO__SOLDIER_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Görünüşe göre bir süre burada olacağım...",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME__001__M__1": "Yok, bir şey yokmuş...",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME__001__M__2": "Eh...",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME__001__M__3": "Biraz uyumam lazım...",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Yine bir şey yok. Aklım oyun oynuyor olmalı...",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Hiçbir şey, ilk seferki gibi hiçbir şey...",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Tabii ki yine bir şey yok... Biliyordum!",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Yanlış. Yine.",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Yine bir şey yok!",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Önce bir şey yok... şimdi bir şey yok... pöf!",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_RATS__001__M__1": "Lanet yaratıklar.",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_RATS__001__M__2": "Pis yaratıklar.",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_RATS__001__M__3": "Pis haşarat...",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Üzgünüm, yanlış alarm!",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Bölge temiz görünüyor.",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Kimseyi bulamıyorum.",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Bir şey yokmuş...",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Yanlış alarm...",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Eh, sadece yanlış alarmmış...",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Nerede kalmıştık? Ah evet!",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Neyse, nerede kalmıştık? Ah, hatırladım!",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Eee, ne diyordum? Ah evet!",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Hayırlısı buymuş...",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Umarım artık sakin olur.",
"VO__SOLDIER_N2__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Hep böyle...",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH__001__M__1": "Bulamıyorum onları! Tetikte olun!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH__001__M__2": "Az önce buradaydılar! Bulun onları!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH__001__M__3": "Nereye gittiler?! Aramaya devam edin!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "İstediğin kadar saklan! Yine de bulacağım seni!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Nereye kaçtın? Kaçabileceğini sanma!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Benden ne kadar kaçabileceğini sanıyorsun?!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Hallederim!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Tamam!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Hemen!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Bu taraftan gittiler, şüphe yok...",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Tamam, artık nerede olduğunu biliyorum!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "İşte buradasın.",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Buldum onları! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Kaçamazlar! İzlerini sürün!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Yakaladım onları! Gelin buraya!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "İşin bitti...",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Kaçmak boşunaydı...",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Bak kim ayağıma kadar gelmiş?!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Misafirimiz var! Tetikte olun!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Biri bölgede saklanıyor! Her yeri arayın!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Davetsiz misafirleri aramaya başlayın! Bir şey görürseniz haber verin!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Tabii, veririm!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Hemen!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Anlaşıldı!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Bunu onlar yaptı, serseriler...",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Onlar, onlar olmalı!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Lanet davetsiz misafirler, onlar olmalı!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Nasıl kaybolmayı başardılar?!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Uzakta olamazlar!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Eminim hâlâ buralardalar...",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Orada arkaya siper aldılar! Gidiyorum!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Onun arkasına geçtiler, köklerini kazıyacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "İzinsiz girenler tam orada arkada saklanıyor! Yakalayalım onları!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Onun arkasına saklanıp akıllılık ettiğini mi sanıyorsun?",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Siper almaya mı çalışıyorsun, ha? İşe yaramayacak!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Onun arkasına geçtiğini gördüm! Benimsin!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Sanırım aşağı indiler! Bakacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağıdalar! Acele edin!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağı atladılar! Peşlerindeyim!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağıda saklanamazsın! Bulacağım seni!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Geri çık buraya! Sadece işi daha da kötüleştiriyorsun!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Nerede olduğunu bilmediğimi sanma! Aşağı atladığını gördüm!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "İzinsiz girenler çimene girdi!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Çimende saklanıyorlar! Peşlerinden gideceğim!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Çimende, benimle arayın!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Çık o çimenden!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Şu çimen seni sonsuza dek saklamaz.",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Şu çimenin seni kurtaracağını gerçekten mi sanıyorsun?!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Sanırım oranın altındalar! Bakacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altına girdiler! Yakalayacağım onları!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Oranın altında saklanıyorlar! Peşlerindeyim!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Güvende olduğunu mu sanıyorsun! Yakalayacağım seni...",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Oranın altında kapana kısıldın, biliyorsun değil mi?",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Oranın altına saklandığını gördüm!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Sanırım yukarı çıktılar! Bakalım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "Yukarıdalar, yakalayın onları!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Yukarı tırmandılar! Peşlerinden!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarıda saklanamazsın! Bulacağım seni!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Geri in buraya! Sadece işi daha da kötüleştiriyorsun!",
"VO__SOLDIER_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Tırmandığını gördüm!",
"VO__SOLDIER_N2__GENERIC__PATROL__SMOKE__001__M__1": "Şu dumanın nesi var lan?",
"VO__SOLDIER_N2__GENERIC__PATROL__SMOKE__001__M__2": "Bu duman da ne?",
"VO__SOLDIER_N2__GENERIC__PATROL__SMOKE__001__M__3": "Şu duman normal değil... Bakalım...",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Yine neler oluyor? Bunu çabuk kontrol etsem iyi olur...",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine oluyor! Gözünü açık tut.",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "Yine mi?! Gidip bir bakacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Bir kez daha mı?! Baksam iyi olur...",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Gerçekten, yine mi...? Peki bakalım...",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Bu ikinci oldu..! Gidip baksam iyi olur.",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Neler olduğuna bakacağım.",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Ben giderim. Sen orada kal.",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Ben ilgilenirim.",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "O ses, sen miydin?! Bakacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "O ses... Gidip bakacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Sen de duydun mu?! Gidip bakacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu ses nereden geliyor lan?",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Bu ses de ne?",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "O ses... Alışılmadık...",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "Şu ateşe gidip bakacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "Büyücülük olmalı! Gidip bakacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Ateşin neden tuhaf davrandığına bakmaya gidiyorum. Sen geri dur!",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Bu ateşe neler oluyor?",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Tuhaf, bu ateşe neler oluyor?",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Garip, bu ateşe neler oluyor?",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "O çatırtı nereden geldi?! Bakacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Yakından geldi... Araştıracağım.",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "Duydun mu şunu? Bir bakacağım!",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Bu bir kırbaç mı?",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "O çatırtı... şu taraftan geldi...",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "O ses neydi?",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Orada, gördün mü? Burada bekle, gidip bakacağım.",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Göremiyorum ama orada kımıldıyor. Bakayım.",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Arkamı kolla, orada kımıldayan şeye bakmak istiyorum...",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Bu da ne?!",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Burada biri var gibi...",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Hey! Burada kimse var mı?!",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Yardıma ihtiyacın olursa haber ver.",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Bir şey bulursan haber ver.",
"VO__SOLDIER_N2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Beni haberdar et, tamam!",
"VO__SOLDIER_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Burada bir şey yok...",
"VO__SOLDIER_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Başka bir bölgeye geçsem iyi olur...",
"VO__SOLDIER_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Her şey temiz görünüyor...",
"VO__SOLDIER_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Başka yere bakalım...",
"VO__SOLDIER_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Burada izleri yok...",
"VO__SOLDIER_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Bölge temiz...",
"VO__SOLDIER_N3__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Artık birinin olduğuna eminim! Bulun onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Biri bizimle oynamak istiyor! Bulun onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Sinsi serseriler! Bu sefer yakaladığımızdan emin olun!",
"VO__SOLDIER_N3__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Komik mi sanıyorsun? Bana göre değil, göreceksin!",
"VO__SOLDIER_N3__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Bir daha kanmam! Bulacağım seni...",
"VO__SOLDIER_N3__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Bunun bana yine işe yarayacağını gerçekten mi sandın?",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT__001__M__1": "Burada davetsiz misafirler var! Benimle gelin!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT__001__M__2": "Burada izinsiz girenler var! Yakalayın onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT__001__M__3": "Buraya! Birkaç izinsiz giren buldum!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Burada bulunmamalısın!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Dur orada!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Sen! Kıpırdama!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Sana ulaşmanın bir yolunu bulacağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "Kahretsin... Burada tıkıldım... Yakalayacağım seni!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Burada tıkıldım ama bu uzun sürmeyecek, biliyorsun!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Şimdi tıkalı olabilirim ama güvende değilsin.",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Burada uzun süre tıkalı kalmayacağım, duydun mu?",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Şimdi burada tıkıldım! Ama bir dahaki sefere kaçamayacaksın!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BOMB__001__M__1": "Sana bir şeyim var!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BOMB__001__M__2": "Patlayacak!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BOMB__001__M__3": "Atıyorum!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BOMB__001__M__4": "Bu senin için!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BOMB__001__M__5": "Dikkat!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_BOMB__001__M__6": "Ye bunu!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_DYING__001__M__2": "Öldü! Dikkat!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Seni dumanla dışarı çıkaracağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Çimenle birlikte yanacaksın!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "Çimende mi saklanıyorsun, ha? Akıllıca bir seçim değil.",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Kımıldayın! Davetsiz misafirler var!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Burada davetsiz misafirler var! Benimle!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Benimle gelin, burada davetsiz misafirler var!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılalım ve bölgeyi arayalım!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Yayılın! Uzakta olamazlar!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Ayrılın! Bölgeyi kapatın!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Elinden gelen bu mu!",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Buradan canlı çıkamayacaksın...",
"VO__SOLDIER_N3__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Senin için bu kadar!",
"VO__SOLDIER_N3__GENERIC__PATROL__BURNING__001__M__1": "O ateş nasıl çıktı!",
"VO__SOLDIER_N3__GENERIC__PATROL__BURNING__001__M__2": "O ateş nasıl çıktı?",
"VO__SOLDIER_N3__GENERIC__PATROL__BURNING__001__M__3": "Bu ateş de ne?",
"VO__SOLDIER_N3__GENERIC__PATROL__CAPTURE__001__M__1": "Gözlerini kapatsan iyi olur.",
"VO__SOLDIER_N3__GENERIC__PATROL__CAPTURE__001__M__2": "Söyleyecek bir şeyin varsa, tam zamanı.",
"VO__SOLDIER_N3__GENERIC__PATROL__CAPTURE__001__M__3": "Üstüme kan bulaştırmamaya çalış.",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE__001__M__1": "Orada hâlâ canlı mısın? Hey!",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE__001__M__2": "Hey! Sorun ne?",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE__001__M__3": "Beni duyuyor musun orada? Hey!",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Bayıldı mı?",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Orada iyi misin?",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Biri yerde...",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Ateşe mi verilmiş..?!",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Çıtır çıtır yanmış...",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Yakılmış... Tanıyamıyorum bile!",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Bu sıçanların sana yaptığı için üzgünüm...",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Daha kötü bir kader düşünemiyorum...",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Senden neredeyse hiçbir şey kalmamış...",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Biri öldürülmüş! Bunun arkasındaki kim bulun!",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Öldürülmüş mü?! İzinsiz girenler var!",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Ölü..! Dikkat! Saldırı altındayız!",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Öldürülmüş mü?! Bunu kim yaptıysa bulacağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Ölmüş... Bunu yapan serseriyi yakalayacağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Biri onu öldürmüş! Bunun bedelini ödeyeceksin!",
"VO__SOLDIER_N3__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Acısız yapacağım.",
"VO__SOLDIER_N3__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Kaçma şansın vardı!",
"VO__SOLDIER_N3__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Başaramayacağını biliyorsun.",
"VO__SOLDIER_N3__GENERIC__PATROL__DYING__001__M__1": "Ne oluyor lan?!",
"VO__SOLDIER_N3__GENERIC__PATROL__DYING__001__M__2": "Ne ol--",
"VO__SOLDIER_N3__GENERIC__PATROL__DYING__001__M__3": "Aman! Hayır hayır hayır!",
"VO__SOLDIER_N3__GENERIC__PATROL__FLEE_RATS__001__M__1": "Geri çekilin!",
"VO__SOLDIER_N3__GENERIC__PATROL__FLEE_RATS__001__M__2": "Uzaklaşın, uzaklaşın!",
"VO__SOLDIER_N3__GENERIC__PATROL__FLEE_RATS__001__M__3": "Hayır hayır hayır!",
"VO__SOLDIER_N3__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Yaşadığıma şükür!",
"VO__SOLDIER_N3__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Pis dişlerinizi başka yere geçirin!",
"VO__SOLDIER_N3__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "Ben, ben güvendeyim... Çok yakındı!",
"VO__SOLDIER_N3__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Tamam... biri buralarda! Bölgeyi arayın!",
"VO__SOLDIER_N3__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Saldırıya uğradım! Bulun şu serserileri!",
"VO__SOLDIER_N3__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Saldırı altındayım! Davetsiz misafirler var!",
"VO__SOLDIER_N3__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Seni küçük..! Yanlış kişiyle uğraşıyorsun!",
"VO__SOLDIER_N3__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Bunun bedelini ödeteceğim!",
"VO__SOLDIER_N3__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Kahretsin..! Bunu yanına bırakmayacaksın!",
"VO__SOLDIER_N3__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Dilini mi yuttun?",
"VO__SOLDIER_N3__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Sesin mi kesildi ne?!",
"VO__SOLDIER_N3__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Ha, iyi misin?",
"VO__SOLDIER_N3__GENERIC__PATROL__OIL__001__M__1": "Bu katranla burada ne oldu?",
"VO__SOLDIER_N3__GENERIC__PATROL__OIL__001__M__2": "Bütün bu katran nereden geldi?",
"VO__SOLDIER_N3__GENERIC__PATROL__OIL__001__M__3": "Öf... Kesinlikle katran.",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION__001__M__1": "Ha?",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION__001__M__2": "Dur...",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION__001__M__3": "O da neydi?",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION_RATS__001__M__1": "Beni bir ısırmak isterdin, ha?",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION_RATS__001__M__2": "Ne de aç görünüyorsunuz.",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION_RATS__001__M__3": "Sorun ne?! Işığı sevmiyor musunuz?!",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Şaka olmalı, burada kapana kısıldım...",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "İstesem de istemesem de tam burada kalacağım...",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Hayır, geçmeye çalışmam!",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "Ben burada kalayım...",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "Görünüşe göre hiçbir yere gitmiyorum.",
"VO__SOLDIER_N3__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Şimdi oraya nasıl geçeceğim..?",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME__001__M__1": "Boş ver...",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME__001__M__2": "Yok be...",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME__001__M__3": "Her zamanki gibi bir şey yok...",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Yine bir şey yokmuş...",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Bir şey yok, yine yanılmışım...",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Sadece bir yanlış alarm daha.",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Yanlış... yine.",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Peki... yine yanılmışım...",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Hâlâ bir şey yok... Benim neyim var..?",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_RATS__001__M__1": "Lanet sıçanlar.",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_RATS__001__M__2": "Pis yaratıklar.",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_RATS__001__M__3": "Pis yaratıklar.",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Bölge temiz.",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Kimseyi göremiyorum.",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Her şey normal!",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Bir şey yok... Tamam...",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Endişelenecek bir şey yok.",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Harika... Yanlış alarm...",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Eee, nerede kalmıştık? Ah, hatırladım!",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Bir şey söyleyecektim... Ah doğru!",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Eee, ne diyordum? Ah evet!",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Tamam, böylesi daha iyi...",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Böylesi hoşuma gidiyor...",
"VO__SOLDIER_N3__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Devriyene geri dön.",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH__001__M__1": "Bulamıyorum onları! Gözünüzü dört açın!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH__001__M__2": "Buralarda bir yerdeler! Bölgeyi arayın!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH__001__M__3": "Nereye gittiler?! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Buralarda bir yerde olduğunu biliyorum! Bulacağım seni!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "İstediğin kadar saklan, kaçamayacaksın!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Nereye kaçtın? Çık dışarı!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Yakalayacağız onları, merak etme!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Sadece an meselesi.",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Elimizin altındalar!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Şu taraftan geldi...",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Demek orada mı saklanıyorsun?",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Demek oraya mı gittin?!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Görüyorum onları! Bu taraftan!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Oradalar! Peşlerinden!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Orada! Durdurun onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Artık işin bitti!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Sonunda!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "İşte buradasın!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "İzinsiz girenler var! Gözünüzü dört açın!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Biri etrafta dolaşıyor! Bir şey görürseniz haber verin!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Bölgede davetsiz misafirler var! Aramaya başlayın!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Derhal!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Elbette!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Tamam!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Onun arkasında olmalılar!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Bunu onlar yaptı... Şüphe yok!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Bir pis numaraları daha...",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Kahretsin... Gözden kaybettim onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Az önce buradaydılar!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Yakındalar! Bulalım onları.",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Tam orada arkada! Benimle gel!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Orada arkada sinmişler! Gidiyorum!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Şu siperin arkasına saklanmaya çalışıyorlar! Yakaladım onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Orada arkada mı saklanıyorsun, ha?! Bana göre yeterince zeki değilsin!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Orada arkada olduğunu biliyorum... Yakında pişman olacaksın!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Onun arkasında güvende değilsin!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı indiler! Takip edeceğim onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "İzinsiz girenler aşağı atladı! Gidip bakacağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağıda bir yerdeler! Takip edeceğim onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağısı senin için güvenli değil!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Aşağı atladığını gördüm! Yine de bulacağım seni!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Aşağıda uzun süre saklanamayacaksın!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "Buradalar! Uzun çimende!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Uzun çimenin bir yerinde saklanıyorlar!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Uzun çimene girdiler! Beni takip edin!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Çimende kaçamayacaksın!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Çimende oynamayı bırak, yine de yakalayacağım seni.",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Seni şu çimenden kendim sürükleyip çıkaracağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altına girdiler! Hallediyorum!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "İzinsiz girenler oranın altında! Yakalayın onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Oranın altındalar! Yakalayın onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Oranın altı senin için güvenli değil!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Oranın altına girdiğini gördüm!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Seni oradan sürükleyip çıkaracağım, biliyorsun!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Oraya tırmandılar! Takip edin onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "İzinsiz girenler yukarı çıkmış olmalı! Gidip bakın!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Yukarıda bir yerdeler! Takip edin onları!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarısı senin için güvenli değil!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Tırmandığını gördüm! Yine de bulacağım seni!",
"VO__SOLDIER_N3__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Yukarıda uzun süre saklanamayacaksın!",
"VO__SOLDIER_N3__GENERIC__PATROL__SMOKE__001__M__1": "Duman..? Neler oluyor..?",
"VO__SOLDIER_N3__GENERIC__PATROL__SMOKE__001__M__2": "Şu duman nereden geliyor?",
"VO__SOLDIER_N3__GENERIC__PATROL__SMOKE__001__M__3": "Şu dumanı çıkaran ne lan?",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Yine mi? Bu normal değil, bakacağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine olmasın!? Bir şey olmadığından emin olacağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "Yine bir şey... Şunu kontrol edelim!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine mi?! Arkasında bir şey olmalı!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Şimdi ikinci kez mi? Peki, bakalım...",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "İşte yine başladı!? Bu sefer emin olmam lazım.",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Bana bırak.",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Kendim gidip bakacağım.",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Bunu bana bırak.",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Tuhaf bir sesti?!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "O ses... Gidip baksam iyi olur!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Kulağa doğru gelmiyor... Gidip bakacağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu ses de ne?",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Tuhaf bir sesti... Baksam iyi olur.",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Bu tuhaf ses de ne?",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "Ateşi gördün mü?! Bir baksam iyi olur.",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "Şu ateşe neler oluyor?! Baksam iyi olur!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Ateşin değiştiğini gördün mü?! Daha yakından bakacağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "O ateş ele geçirilmiş mi..?",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Bu büyücülük mü?!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "O ateş... Az önce ne oldu?",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Bir tür çatırtı duydum... Araştıracağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "O ses... Bir bakacağım.",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "Duydun mu şunu? Gidip araştıracağım!",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Bu... bir sapan mı?",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "O ses nereden geldi?",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "Bir kırbaç şaklaması... nereden?",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Orada bir şey var. Gidiyorum.",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "O neydi...? Burada bekle, bir bakacağım...",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Tetikte ol, orada neler olduğuna bakacağım...",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "O da ne...? Gidip baksam iyi olur...",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Orada az önce bir şey mi kımıldadı? Ne olduğuna bakacağım...",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Şu oradaki ne? Daha yakından baksam iyi olur.",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Bir şey görürsen bildir.",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Bölgenin güvenli olduğundan emin ol.",
"VO__SOLDIER_N3__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Bir şey görürsen hemen bildir.",
"VO__SOLDIER_N3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Bir şey yok... Devam etsem iyi olur.",
"VO__SOLDIER_N3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Bir şey yok... Burada vakit kaybediyorum.",
"VO__SOLDIER_N3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Burada bir şey yok...",
"VO__SOLDIER_N3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Başka bir bölgeyi arasam iyi olur...",
"VO__SOLDIER_N3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Burada kimseyi bulamam...",
"VO__SOLDIER_N3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Burada hiçbir şey bulamıyorum...",
}
