# -*- coding: utf-8 -*-
# Genel Sesler GS4: BANDIT_N1+N2 generic VO (456 satir). Haydutlar: kaba, argo, "sen".
T = {
"VO__BANDIT_N1__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Biri bizi aptal yerine koyuyor! Her yeri arayın!",
"VO__BANDIT_N1__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Bu kadar yeter! Her yeri arayın!",
"VO__BANDIT_N1__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Herkes tetikte! Üçüncü kez bir şey gördüm...",
"VO__BANDIT_N1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Oynamak mı istiyorsun? Seni kesin bulacağım!",
"VO__BANDIT_N1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Komik olduğunu mu sanıyorsun? Bu sefer gitmene izin vermeyeceğim!",
"VO__BANDIT_N1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Akıllı olduğunu mu sanıyorsun?!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT__001__M__1": "Herkes ayağa! Davetsiz misafirler var!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT__001__M__2": "Davetsiz misafirler!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT__001__M__3": "İzinsiz girenler! Yakalayın onları!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Hadi! Yine de öldüreceğim seni...",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Dur! Seni çabucak öldüreceğim!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Burada bekleyin serseriler!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Burada tıkıldım mı sandın? Yakalayacağım seni!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "Hep tıkalı kalmayacağım! Göreceksin..!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Ne olursa olsun peşindeyim!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Ben burada tıkıldım diye güvende olduğunu sanma!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Burada tıkalı olabilirim... ama yakında bedelini ödeyeceksin!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Şimdi sana ulaşamam ama sen bekle bakalım!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BOMB__001__M__1": "Al bakalım ve geber!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BOMB__001__M__2": "Ye bunu serseri!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BOMB__001__M__3": "Yakala!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BOMB__001__M__4": "Al! Bu senin için!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BOMB__001__M__5": "Bu senin için!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_BOMB__001__M__6": "Al bakalım!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_DYING__001__M__1": "Olamaz! Öldürüldü!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_DYING__001__M__2": "Adam vuruldu!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_DYING__001__M__3": "Siktir! Öldü!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Alevler seni çimenden dışarı çıkaracak!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Siz serseriler için bir şenlik ateşi!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "O çimende uzun süre saklanamayacaksın!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Sen benimle! Şu davetsiz misafirleri durdurun!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Bana katıl! Şu davetsiz misafirleri durdurun!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Şu serseriler orada! Yakalayın onları!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılın! Uzakta olamazlar!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Yayılın! Bölgeyi arayın!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Ayrılın! Serserilerin kaçmasına izin vermeyin!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Elinden geleni yap!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Benimsin!",
"VO__BANDIT_N1__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Hadi göster kendini o zaman!",
"VO__BANDIT_N1__GENERIC__PATROL__BURNING__001__M__1": "Bu ateşi kim çıkardı?!",
"VO__BANDIT_N1__GENERIC__PATROL__BURNING__001__M__2": "Bu ateş nasıl çıktı...",
"VO__BANDIT_N1__GENERIC__PATROL__BURNING__001__M__3": "Şu ateşi çıkaran da ne lan?!",
"VO__BANDIT_N1__GENERIC__PATROL__CAPTURE__001__M__1": "Birazdan biter.",
"VO__BANDIT_N1__GENERIC__PATROL__CAPTURE__001__M__2": "İşin bitti senin.",
"VO__BANDIT_N1__GENERIC__PATROL__CAPTURE__001__M__3": "Böyle biteceğini düşünmemiştin, ha?",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE__001__M__1": "Hey sen? Sorun ne?",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE__001__M__2": "Hey! İyi misin?!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE__001__M__3": "Hâlâ bizimle misin? Hey!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Hey sen?! Kendine gel!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Ne yapıyor o? Uyan!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Şekerleme yaptığına inanamıyorum!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Yakılmış mı? Olamaz!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Kül olmuş... Kimse bunu hak etmez!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Küle dönmüş...",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Senin için eğlenceli olmamış olmalı.",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Onu diri diri mi yediler?!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Diri diri... yenmiş...",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Öldü! Davetsiz misafirler var!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Burada bir ceset var! Bunu yapan serseriyi bulun!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Dikkat! Biri bize saldırıyor!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Ölmüş! Bir katil dolaşıyor...",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Öldürülmüş. Davetsiz misafirimiz var!",
"VO__BANDIT_N1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Bunu kim yaptıysa, öldüreceğim onu!",
"VO__BANDIT_N1__GENERIC__PATROL__DEATH_VEIL__001__M__1": "İnan bana, daha başlangıçtı bu!",
"VO__BANDIT_N1__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Acımış gibi göründü!",
"VO__BANDIT_N1__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Dua etmek istiyorsan, tam zamanı.",
"VO__BANDIT_N1__GENERIC__PATROL__DYING__001__M__1": "Hayır!",
"VO__BANDIT_N1__GENERIC__PATROL__DYING__001__M__2": "Neler oluyor?",
"VO__BANDIT_N1__GENERIC__PATROL__DYING__001__M__3": "Ne oluyor lan!",
"VO__BANDIT_N1__GENERIC__PATROL__FLEE_RATS__001__M__1": "Dokunmayın bana!",
"VO__BANDIT_N1__GENERIC__PATROL__FLEE_RATS__001__M__2": "Yaklaşmayın bana...",
"VO__BANDIT_N1__GENERIC__PATROL__FLEE_RATS__001__M__3": "Çekin pençelerinizi üstümden!",
"VO__BANDIT_N1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Bir saniye daha olsa işim bitmişti...",
"VO__BANDIT_N1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Başardım! Gerçekten başardım!",
"VO__BANDIT_N1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "Çok yakındı...",
"VO__BANDIT_N1__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Biri bana saldırıyor! Bulun onları!",
"VO__BANDIT_N1__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Saldırıya uğradım! Bölgeyi arayın!",
"VO__BANDIT_N1__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Biri bana saldırıyor! Davetsiz misafirler var!",
"VO__BANDIT_N1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Bana mı vurdun?! Bunun bedelini ödeteceğim!",
"VO__BANDIT_N1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Bunu yapmaman gerekirdi!",
"VO__BANDIT_N1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Serseri! Bunun hesabını soracağım!",
"VO__BANDIT_N1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Hâlâ orada mısın?",
"VO__BANDIT_N1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Sana bir şey mi oldu?",
"VO__BANDIT_N1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Neden konuşmayı kestin?",
"VO__BANDIT_N1__GENERIC__PATROL__OIL__001__M__1": "Buraya dökülen bu şey de ne?",
"VO__BANDIT_N1__GENERIC__PATROL__OIL__001__M__2": "Yerde katran mı?",
"VO__BANDIT_N1__GENERIC__PATROL__OIL__001__M__3": "Biri mi döktü bunu?",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION__001__M__1": "Ne?",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION__001__M__2": "Ha?",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION__001__M__3": "O da ne?",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION_RATS__001__M__1": "Sakin olur musunuz, küçük serseriler?!",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION_RATS__001__M__2": "Bu kadar yeter!",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION_RATS__001__M__3": "Siz cıyaklayan serseriler hiç susmayacak mısınız?!",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Tamam, bu sefer siz kazandınız.",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "Kahretsin! Oraya nasıl geçeceğim...?",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Diri diri yenmeye niyetim yok!",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "Sanırım artık oraya gitmeyeceğim...",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "Yolu kapatıyorlar... Kahretsin...",
"VO__BANDIT_N1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Geçemiyorum... Lanet sıçanlar...",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME__001__M__1": "Boş ver...",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME__001__M__2": "Vakit kaybı.",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME__001__M__3": "Burada vakit kaybediyorum...",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Yine yanlış alarm...",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Hâlâ bir şey yok burada.",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Yine yanılmışım... Her şey yolunda.",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Yine bir şey yok.",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Hâlâ temiz...",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Hâlâ bir şey yok... Kahretsin...",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_RATS__001__M__1": "Pis canavarlar.",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_RATS__001__M__2": "Şu sıçanlardan bıktım...",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_RATS__001__M__3": "Lanet haşarat.",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Sanırım bir şey yokmuş.",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Eh, kimse yok burada.",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Kimseyi göremiyorum.",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Burada bir şey yok...",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Hiçbir şey bulamıyorum...",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Rapor edecek bir şey yok...",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Neyse, dediğime dönelim...",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Bir şey söyleyecektim... Ah evet!",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Nerede kalmıştık? Ah doğru!",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Tabii ki bir şey yokmuş!",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Bir şey olmadığını biliyordum!",
"VO__BANDIT_N1__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Şaşırdın mı sanki?",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH__001__M__1": "Kaçırdım onları! Bölgeyi arayın!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH__001__M__2": "Hareket hâlinde olmalılar! Gözünüzü dört açın!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH__001__M__3": "Serseriler kaçtı! Her köşeyi arayın!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Seni yakalatma bana!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Merak etme, yine de bulacağım seni!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Uzun süre saklı kalamayacaksın.",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Merak etme, yakalarız onları.",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Uzun süre saklı kalamazlar.",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Uzakta olamazlar!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Sen olmalısın...",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Artık seni bulmak kolay!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Demek orada mı saklanıyorsun?!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Buraya! Kaçmalarına izin vermeyin!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Buldum onları! Buraya gelin!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Görüyorum onları! Peşlerinden!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Bak burada ne varmış?",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Eh, işin bitmiş gibi görünüyor!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Kaçmaya kalkma!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Misafirimiz var! Her yeri arayın!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Davetsiz misafir ihbarı var! Gözünüzü açık tutun!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Bölgede davetsiz misafirler var! Harekete geçin!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Yakalayalım şu serserileri!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Yakalayalım onları!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Hadi, gidelim!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Bunu onlar yaptı!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Bu onların işi olmalı!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Bununla bir ilgileri olmalı!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Az önce buradaydılar!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Serseriler uzağa gitmiş olamaz!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Hâlâ yakında olmalılar!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Oraya siper aldılar! Peşlerindeyim!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Oraya siper aldıklarını gördüm! Hallediyorum!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Serseriler orada arkada çömeliyor! Yakalayacağım onları!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Onun arkasına mı saklanıyorsun?! Uzun süre güvende olmayacaksın!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Orada arkada saklandığını mı sanıyorsun?!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Onun arkasında güvende değilsin!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı indiler! Yakalayacağım onları!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı atladıklarını gördüm! Peşlerinden gidiyorum!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Lanet serseriler aşağı indi! İzlerindeyim!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağıda saklanabileceğini mi sanıyorsun?!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Seni aşağıda gördüm! Geliyorum!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Hey aşağıdaki! Göster kendini!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "İşte! Çimende saklanıyorlar!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Uzun çimenin bir yerinde saklanıyorlar!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Çimene girdiler! Gözünüzü açık tutun!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Çimende saklanıyorsun! Dalga mı geçiyorsun benimle!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "O çimen sana yardım etmeyecek!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Çimende mi saklanıyorsun, ha? Senin için iyi bitmeyecek!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altına girdiler! Yakalayacağım onları!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altına girdiklerini gördüm! Peşlerinden gidiyorum!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Lanet serseriler oranın altına girdi! İzlerindeyim!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Oranın altında saklanabileceğini mi sanıyorsun?!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Oranın altına girdiğini gördüm!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Oranın altında olduğunu biliyorum!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Yukarı çıktılar! Yakalayın onları!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "Yukarı tırmandıklarını gördüm! Peşlerinden gidiyorum!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Yukarı çıktılar! Peşlerine düşün!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarıda saklanabileceğini mi sanıyorsun?!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Nereye gittiğini gördüm! Yukarı çıkıyorum!",
"VO__BANDIT_N1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Nerede olduğunu biliyorum! Hemen yukarı geliyorum!",
"VO__BANDIT_N1__GENERIC__PATROL__SMOKE__001__M__1": "Duman mı? Neymiş baksam iyi olur.",
"VO__BANDIT_N1__GENERIC__PATROL__SMOKE__001__M__2": "Duman mı? Burada mı? Bakalım...",
"VO__BANDIT_N1__GENERIC__PATROL__SMOKE__001__M__3": "Çok fazla duman... Bir baksam iyi olur...",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Bu, ikinci kez oluyor..!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Orada hâlâ bir şeyler oluyor!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "O şey geri döndü!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine mi?... Bakalım...",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Olamaz!? Şuna bakmam lazım...",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Öf... Yine mi?!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Hallederim.",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Bakacağım.",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Neler olduğuna bakacağım.",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Gürültülüydü... Gidip bakacağım!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "O sesi ne çıkardı bakacağım!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Sanırım bir şey duydum! Bir bakacağım!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "O ses... nedir o?",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Tuhaf ses, nedir o?",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Tuhaf geldi...",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "Şu ateşte tuhaf bir şey var! Gidip bakacağım!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "Şu ateş... Orada neler oluyor?!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Şu ateş tuhaflaşıyor! Gidip bir bakacağım!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Şu ateşin nesi var lan?!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Şu ateşin nesi var?!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Şu ateş çıldırmış mı ne?!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "O bir kırbaçtı! Gidip bakacağım!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Bir çatırtı duydum! Hemen dönerim!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "O çatırtı nereden geldi? Bakacağım!",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Bu ses de ne? Şuna bakmam lazım...",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "O ses neydi?",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "O bir kırbaçtı, eminim...",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Sanırım bir şey gördüm... Emin olmam lazım.",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Bir şey kımıldıyor... Gözünü açık tut...",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Sanırım bir şey gördüm. Arkamı kolla.",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Oradaki ne? Bakalım...",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Orada bir şey var...",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Gölge miydi o? Yaklaşalım.",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Neymiş haber ver.",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Tamam, sen benim gözüm ol...",
"VO__BANDIT_N1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Bir şey bulursan haber ver.",
"VO__BANDIT_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Burada bir şey bulamam...",
"VO__BANDIT_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Kaygan küçük serseriler...",
"VO__BANDIT_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Vakit kaybı...",
"VO__BANDIT_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Her yerde saklanıyor olabilirler...",
"VO__BANDIT_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Belki orada saklanıyorlardır...",
"VO__BANDIT_N1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "İlerlesem iyi olur...",
"VO__BANDIT_N2__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Biri bizimle oynuyor! Aramaya başlayın!",
"VO__BANDIT_N2__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Biri beni çileden çıkarıyor! Yakalayın şu şakacıyı!",
"VO__BANDIT_N2__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Biri burada benimle oynuyor! Her yeri arayın!",
"VO__BANDIT_N2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Beni bir daha kandırabileceğini sanma!",
"VO__BANDIT_N2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Benimle yine mi oynuyorsun? Şimdi durduracağım seni!",
"VO__BANDIT_N2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Oyun yeter, bu sefer yakalayacağım seni!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT__001__M__1": "İzinsiz girenler var!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT__001__M__2": "Alarm! Davetsiz misafirler!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT__001__M__3": "Alarm! Yakalayın şu davetsiz misafirleri!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Sen! Burada bulunmana izin yok!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Dur orada!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Ne işin var burada?!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "İşimiz daha bitmedi! Yakalayacağım seni!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "Sana ulaşmanın yolunu bulacağım, inan bana!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Yakalayacağım seni! Şu ya da bu şekilde...",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Bitmedi! Şu ya da bu şekilde yakalayacağım seni.",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Siz ödlekler, sana ulaşmanın yolunu bulacağım!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Dikkat et, burada uzun süre tıkalı kalmayacağım!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BOMB__001__M__1": "Al bakalım!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BOMB__001__M__2": "Yakala bunu!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BOMB__001__M__3": "Geliyor!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BOMB__001__M__4": "Bu senin için!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BOMB__001__M__5": "Ye bunu serseri!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_BOMB__001__M__6": "Bak ne geliyor!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_DYING__001__M__1": "Öldü! Dikkat!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_DYING__001__M__2": "Siktir! Öldürüldü!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_DYING__001__M__3": "Adam vuruldu! Dikkat edin!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Çimende saklanmamayı öğreteceğim sana!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Şimdi saklan bakalım o çimende!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "Seni dumanla o çimenden çıkaracağım!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Tam alarm! Öldürün şu davetsiz misafirleri!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Beni takip edin! Davetsiz misafirler var!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Benimle! İzinsiz girenler burada!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılalım ve yakalayalım o serserileri!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Peşlerinden! Yakalayın davetsiz misafirleri!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Yayılın! Uzağa gitmiş olamazlar!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Daha yeni başlıyorum!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Kaçacak yerin yok!",
"VO__BANDIT_N2__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Ölü ya da diri, fark etmez!",
"VO__BANDIT_N2__GENERIC__PATROL__BURNING__001__M__1": "Neler oluyor? Ateş mi?!",
"VO__BANDIT_N2__GENERIC__PATROL__BURNING__001__M__2": "Bu ateşi kim çıkardı?",
"VO__BANDIT_N2__GENERIC__PATROL__BURNING__001__M__3": "Hay aksi! Bu ateşi kim çıkardı?",
"VO__BANDIT_N2__GENERIC__PATROL__CAPTURE__001__M__1": "Şşş! Birazdan biter.",
"VO__BANDIT_N2__GENERIC__PATROL__CAPTURE__001__M__2": "Şu an senin yerinde olmak istemezdim.",
"VO__BANDIT_N2__GENERIC__PATROL__CAPTURE__001__M__3": "Tıpkı uykuya dalmak gibi.",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE__001__M__1": "Hey! Uyan!",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE__001__M__2": "Hey! Kes şunu!",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE__001__M__3": "Çok komik. Şimdi kalk!",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Hey! Kalk ayağa tembel...",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Orada ne yapıyor?",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Hadi! Kalk ayağa!",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Ah, tamamen kömür olmuş...",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Yanmış ceset...",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Ateşe verilmiş bir ceset mi?!",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Öf... Diri diri yenmiş...",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Sıçanlar tarafından yenmiş...",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Bu gerçekten çok acıtmış olmalı.",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Dikkat! Biri bize saldırıyor!",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Davetsiz misafirler var! Bulun şu serseriyi!",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Öldürülmüş! Saldırı altındayız!",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Ceset hâlâ sıcak! Katil yakında olmalı!",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Öldü! Katil uzakta olamaz...",
"VO__BANDIT_N2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Ölmüş... Katil hâlâ buralarda olmalı...",
"VO__BANDIT_N2__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Bu daha başlangıçtı!",
"VO__BANDIT_N2__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Daha yeni başlıyoruz!",
"VO__BANDIT_N2__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Daha yeni ısınıyorum!",
"VO__BANDIT_N2__GENERIC__PATROL__DYING__001__M__1": "Ne ol--",
"VO__BANDIT_N2__GENERIC__PATROL__DYING__001__M__2": "İmkânsız!",
"VO__BANDIT_N2__GENERIC__PATROL__DYING__001__M__3": "Hayır, olamaz...",
"VO__BANDIT_N2__GENERIC__PATROL__FLEE_RATS__001__M__1": "Uzak durun serseriler!",
"VO__BANDIT_N2__GENERIC__PATROL__FLEE_RATS__001__M__2": "Geri çekilin!",
"VO__BANDIT_N2__GENERIC__PATROL__FLEE_RATS__001__M__3": "Çekilin üstümden, pis sıçanlar!",
"VO__BANDIT_N2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Kahretsin... Çok yakındı...",
"VO__BANDIT_N2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Aman Tanrım! Neredeyse üstümde hissettim onları...",
"VO__BANDIT_N2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "Şimdi yakala bakalım beni!",
"VO__BANDIT_N2__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Hedef alındım! Bölgeyi arayın!",
"VO__BANDIT_N2__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Biri bana saldırıyor! Gelin buraya!",
"VO__BANDIT_N2__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Bazı serseriler peşimizde! Bulun davetsiz misafirleri!",
"VO__BANDIT_N2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Bunun için öldüreceğim seni!",
"VO__BANDIT_N2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Seni küçük bok! Bir daha dene!",
"VO__BANDIT_N2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Bir daha dene! Yakalayacağım seni!",
"VO__BANDIT_N2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Hey! Dilini mi yuttun?",
"VO__BANDIT_N2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Hey! Sesin mi kesildi?!",
"VO__BANDIT_N2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Neden konuşmayı kestin?",
"VO__BANDIT_N2__GENERIC__PATROL__OIL__001__M__1": "Bu siyah şey de ne lan?",
"VO__BANDIT_N2__GENERIC__PATROL__OIL__001__M__2": "Katran mı? Burada ne işi var?",
"VO__BANDIT_N2__GENERIC__PATROL__OIL__001__M__3": "Buraya neden katran dökülmüş?",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION__001__M__1": "Ne ol--?",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION__001__M__2": "Hı?",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION__001__M__3": "Ha?",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION_RATS__001__M__1": "Hadi! Yemeye çalışın beni!",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION_RATS__001__M__2": "Hadi! Yiyin beni!",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION_RATS__001__M__3": "Tam buradayım! Hadi!",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Aptal değilim. Geçmeye çalışmam.",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "Kahretsin, daha ileri gidemiyorum!",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Oraya gitmeme izin vermeyeceksiniz, değil mi?",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "Peki, istediğiniz buysa burada kalırım...",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "Burada kalacağım... Sizi lanet sıçanlar!",
"VO__BANDIT_N2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Peki, daha ileri gitmeye çalışmam...",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME__001__M__1": "Eh, kendine gel...",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME__001__M__2": "Bir şey yokmuş herhalde...",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME__001__M__3": "Kendine gel...",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Burada bir şey yok.",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Her şey yolunda, yine yanılmışım.",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Yanlış alarm. Yine.",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Bir yanlış alarm daha mı...?",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Demek yine yanılmışım.",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Hadi ama... iki kez yeter...",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_RATS__001__M__1": "Pis sıçanlar...",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_RATS__001__M__2": "Cıyaklamaya devam edin! Bakın ne kadar umurumda!",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_RATS__001__M__3": "Lanet yaratıklar.",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Yok, her yer temiz.",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Bana normal görünüyor.",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Bil bakalım ne oldu? Orada bir şey yok.",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Her yer temiz.",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Bir şey yokmuş...",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Sanırım hayal görüyorum...",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Eee, nerede kalmıştık? Ah, hatırladım!",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Nerede kalmıştık? Ah doğru!",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Neyse, ne diyordum? Ha doğru!",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Güzel.",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Bu bir rahatlama.",
"VO__BANDIT_N2__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Umarım öyle kalır.",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH__001__M__1": "Kaçırdım onları! Aramaya devam edin!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH__001__M__2": "Az önce buradaydılar! Aramaya devam edin!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH__001__M__3": "Serseriler kaçtı! Bölgeyi arayın!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Seni bulamam mı sanıyorsun?!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Eline geçtiğin zaman görürsün sen.",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Olduğun yerde kal, geliyorum!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Bana bırak!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Yakalayalım onları!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Kaçmalarına izin vermeyeceğim!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Kötü hamle! Şimdi bulacağım seni.",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Anladım! Oradasın!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Demek o tarafa gittin?! Tamam!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Orada! Yakalayın onları!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Yakaladım onları! Bu taraftan!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Buldum onları! Kaçmalarına izin vermeyin!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "İşte buradasın!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Sonunda yakaladım seni!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Kaçmasan iyi edersin!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Uyumayı bırakın da davetsiz misafirleri arayın!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Davetsiz misafirler! Yakalayın onları!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Davetsiz misafirler var! Harekete geçin!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Yakalayacağız onları.",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Neler yapabileceğimizi gösterelim!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Ava başlayalım!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Serseriler. Bunun arkasında olduğunuzu biliyorum!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Bunu onlar yaptı! Şüphe yok!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Onlar olmalı!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Bir saniye önce buradaydılar!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Yakında olmalılar!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Kahretsin... Nereye gittiler?!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Oraya siper aldıklarını gördüm! Ben hallederim!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Tam onun arkasına saklandılar!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Orada arkada! Yakalayalım onları!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Orada arkada saklanmanın anlamı yok!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Orada arkada saklanmak seni kurtarmaz!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Onun arkasına saklanmanın anlamı yok! Yine de yakalayacağım seni!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı indiler! Ben hallederim!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı kaçtılar! Gidiyorum!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Lanet serseriler aşağı indi! Takip ediyorum onları!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağıda iyi saklansan iyi edersin!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Aşağı atladığını gördüm! Bulacağım seni!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Nerede olduğunu biliyorum! Geri çık buraya!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "O serserilerin uzun çimene atladığını gördüm!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Yakalayın onları, çimene saklandılar!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Peşlerinden! Uzun çimene girdiler!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Başını o çimenden çıkarmasan iyi edersin!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "O çimende saklanmanın ne anlamı var?!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Çimende mi saklanıyorsun?! Daha iyisini yapabilirsin!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altına girdiler! Ben hallederim!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altına kaçtılar! Gidiyorum!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Lanet serseriler oranın altına girdi! Takip ediyorum onları!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Oranın altında iyi saklansan iyi edersin!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Oranın altına girdiğini gördüm!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Oranın altında olduğunu biliyorum!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Yukarı çıktılar! Yakalayalım onları!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "Yukarı kaçtılar! Gidelim!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Lanet serseriler yukarı çıktı! Takip edelim onları!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarıda iyi saklansan iyi edersin!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Yukarı tırmandığını gördüm! Bulacağım seni!",
"VO__BANDIT_N2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Nerede olduğunu biliyorum! Geri in buraya!",
"VO__BANDIT_N2__GENERIC__PATROL__SMOKE__001__M__1": "Şu duman nereden geldi? Bir baksam iyi olur...",
"VO__BANDIT_N2__GENERIC__PATROL__SMOKE__001__M__2": "Şu duman... Daha yakından baksam iyi olur.",
"VO__BANDIT_N2__GENERIC__PATROL__SMOKE__001__M__3": "Şu duman nereden geliyor?",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Yine oluyor...",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine mi? Şaka olmalı!",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "İşte yine başladı! Bir bakacağım!",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine mi? Bu bir şaka mı ne?",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "İşte yine başladı...",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Kahretsin! Geri döndü!",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Bana bırak.",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Ben ilgilenirim.",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Kendim yaparım.",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Dinle, duydun mu şunu? Gidip bakacağım.",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "O ses... Gidip baksam iyi olur!",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Ben de duydum onu! Hallediyorum!",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu kadar gürültüyü çıkaran ne?",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Ne duydum?",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "O ses neydi?",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "Şu ateşte bir şeyler oluyor! Burada kal!",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "Şu ateşe ne oldu lan? Gidip bakacağım!",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Büyücülük mü?! Bir bakacağım!",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Şu ateşe bir şeyler oluyor...",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Şu ateşin nesi var?!",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Şu ateş... Kara büyü mü...?",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Bir çatırtı duydum... Bir bakacağım!",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Bu bir çatırtı mı?! Şuna bir bakayım...",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "O çatırtıyı duydun mu? Bakmam lazım...",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "O çatırtı neydi...? Öğrensem iyi olur.",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "Kırbaca benziyor... Bilmek istediğimden emin değilim...",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "O ses de neydi lan?!",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Sen de gördün mü? Bir bakacağım.",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "O neydi? Bakacağım.",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Sen de gördün, değil mi? Gidip bir bakacağım.",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Bir şey gördüm... Emin olmam lazım.",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Bir şeyin kımıldadığını gördüm...",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Orada bir şey var...",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Aptalca bir şey yapma.",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Çabuk dön, tamam mı?",
"VO__BANDIT_N2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Bir şey bulursan haber ver.",
"VO__BANDIT_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Orada olabilir...",
"VO__BANDIT_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Belki onun yerine oraya gitmişlerdir...",
"VO__BANDIT_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Madem öyle, oraya baksam iyi olur...",
"VO__BANDIT_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Burada izleri yok...",
"VO__BANDIT_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Serseriler beni atlattı...",
"VO__BANDIT_N2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Vakit kaybı... Burada kimse yok...",
}
