# -*- coding: utf-8 -*-
# GS7: SOLDIER_B1 + SOLDIER_B2 (455 replik) - askerler, disiplinli/sert ton
T = {
# --- SOLDIER_B1 ---
"VO__SOLDIER_B1__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Biri bizimle oyun oynuyor! Bulun onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Bizi aptal yerine koyanı bulmama yardım edin!",
"VO__SOLDIER_B1__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Soytarılar bizimle oynuyor! Yakalayın!",
"VO__SOLDIER_B1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Bu sana komik mi geliyor?",
"VO__SOLDIER_B1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Oyun oynamayı bırak!",
"VO__SOLDIER_B1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Buralarda bir yerdesin, biliyorum! Seni bulacağım!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT__001__M__1": "Yanıma! Davetsizler!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT__001__M__2": "Alarm! Şu davetsizleri yakalamama yardım edin!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT__001__M__3": "Misafirimiz var! Yakalayın onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Hemen dur!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Olduğun yerde dur!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Sen de kimsin?! Gel buraya!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Şimdi sıkıştım ama yakında yakalarım seni!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "Sen! Sana ulaşmanın yolunu bulunca görürsün!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Seni ellerime geçirmenin bir yolunu bulacağım!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Bitmedi, bir şekilde sana ulaşacağım...",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Pekâlâ! Şimdi yolum kapalı ama sonsuza dek değil!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Arkanı kolla, sana ulaşmanın bir yolunu bulacağım!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_DYING__001__M__1": "Hayır! Biri vuruldu!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_DYING__001__M__2": "Adam yere düştü! Dikkat!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_DYING__001__M__3": "Öldürdüler onu! Dikkat edin!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Ateş seni o otların arasından çıkaracak, inan bana!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Hadi şimdi şu otların arasına saklan bakalım!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "Otların arasına saklanmak hiç iyi bir fikir değil!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Davetsizler var... Benimle gel!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Burada davetsizler var! Yakalayın onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Uyanın! Davetsizler var!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılın askerler! Yakalayacağız onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Ayrılın ve bulun onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Dağılalım ve bölgeyi tarayalım!",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Kaçamayacaksın, sen de biliyorsun.",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Seçeneğin kalmadı.",
"VO__SOLDIER_B1__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Buraya gelmemeliydin!",
"VO__SOLDIER_B1__GENERIC__PATROL__BURNING__001__M__1": "Bir şeyler yanıyor!",
"VO__SOLDIER_B1__GENERIC__PATROL__BURNING__001__M__2": "Bu ateşi de kim çıkardı?",
"VO__SOLDIER_B1__GENERIC__PATROL__BURNING__001__M__3": "Bu ateş nasıl çıktı?",
"VO__SOLDIER_B1__GENERIC__PATROL__CAPTURE__001__M__1": "Hiç değilse onurunla ölmeye çalış.",
"VO__SOLDIER_B1__GENERIC__PATROL__CAPTURE__001__M__2": "Keyfine bak, hepimiz bir gün öleceğiz.",
"VO__SOLDIER_B1__GENERIC__PATROL__CAPTURE__001__M__3": "Ruhun için dua etmeye başlasan iyi olur.",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE__001__M__1": "Hey seni tembel! Kalk ayağa!",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE__001__M__2": "Kalk ayağa seni sarhoş! Hemen!",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE__001__M__3": "Hâlâ nefes alıyor musun?! Hey!",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Hey sen?! İyi misin?",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Yine görev başında mı uyuyorsun?!",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Hey! Ne yapıyorsun yerde?!",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Tamamen yanmış...",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Lanet olsun... Kavrulmuş...",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Bütün derisi gitmiş...",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Yüce Tanrım... Sıçanlar yemiş...",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Ne biçim bir ölüm!",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Parçalayıp yemişler onu...",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Öldürülmüş! Bunu yapan alçağı bulun!",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Adam vurulmuş! Saldırı altındayız!",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Ölmüş! Dikkatli olun!",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Ölmüş! Katil bunu pahalıya ödeyecek!",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Ölmüş... Bunu kim yaptıysa bulalım!",
"VO__SOLDIER_B1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Bunu yapan alçağı parçalayacağım.",
"VO__SOLDIER_B1__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Beni yenebileceğini mi sandın, ha?!",
"VO__SOLDIER_B1__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Bir tane daha kaldırabilir misin?!",
"VO__SOLDIER_B1__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Sağlam çıktın!",
"VO__SOLDIER_B1__GENERIC__PATROL__DYING__001__M__1": "Bu da ne?",
"VO__SOLDIER_B1__GENERIC__PATROL__DYING__001__M__2": "Lanet!",
"VO__SOLDIER_B1__GENERIC__PATROL__DYING__001__M__3": "Lanet olsun!",
"VO__SOLDIER_B1__GENERIC__PATROL__FLEE_RATS__001__M__1": "Çekilin!",
"VO__SOLDIER_B1__GENERIC__PATROL__FLEE_RATS__001__M__2": "Geri çekilin!",
"VO__SOLDIER_B1__GENERIC__PATROL__FLEE_RATS__001__M__3": "Kahretsin!",
"VO__SOLDIER_B1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Ah, bittim sanmıştım!",
"VO__SOLDIER_B1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Başaracağımı biliyordum! Oh be...",
"VO__SOLDIER_B1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "Ne oldu? Şimdi yakalayamıyor musun beni?!",
"VO__SOLDIER_B1__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Saldırı altındayız! Bölgeyi arayın!",
"VO__SOLDIER_B1__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Bana saldırıyorlar! Davetsizleri bulun!",
"VO__SOLDIER_B1__GENERIC__PATROL__HIT_SEARCH__001__M__3": "İmdat! Beni hedef alıyorlar",
"VO__SOLDIER_B1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Bana mı saldırıyorsun?! Parçalarım seni!",
"VO__SOLDIER_B1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Seni bulmamam için dua etsen iyi olur!",
"VO__SOLDIER_B1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Acıttı seni lanet korkak! Ellerime geçireceğim seni!",
"VO__SOLDIER_B1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Hey! İyi misin?",
"VO__SOLDIER_B1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Nereye gittin?",
"VO__SOLDIER_B1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Hâlâ orada mısın?",
"VO__SOLDIER_B1__GENERIC__PATROL__OIL__001__M__1": "Iyy, her yere katran erimiş...",
"VO__SOLDIER_B1__GENERIC__PATROL__OIL__001__M__2": "Yerde katran mı? Neden?",
"VO__SOLDIER_B1__GENERIC__PATROL__OIL__001__M__3": "Katrana benziyor...",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION__001__M__1": "Şimdi ne oldu?",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION__001__M__2": "Ne oluyor?",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION__001__M__3": "O da neydi?",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION_RATS__001__M__1": "Pes etmiyorlar...",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION_RATS__001__M__2": "İnatçısınız, bunu kabul ediyorum.",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION_RATS__001__M__3": "Bunu daha ne kadar sürdürebilirsiniz?",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Aranızdan nasıl geçeceğim, haşarat!",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "Bunları geçmenin bir yolu var mı, alçaklar!",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Bugün beni yiyemeyeceksiniz! Tam burada kalıyorum!",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "Görünüşe göre hiçbir yere gitmiyorum.",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "Yemek vakti yok, tam burada kalıyorum...",
"VO__SOLDIER_B1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Sanırım burada kalsam daha iyi olacak...",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME__001__M__1": "Mmmm...",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME__001__M__2": "Vaktimi boşa harcıyorum.",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME__001__M__3": "Bir şey yokmuş herhâlde...",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Hiçbir şey bulamadım...",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Hâlâ bir şey yok.",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Yine yanlış alarm...",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Yine bir şey yok... Biliyordum...",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Yine bir şey olmadığını anlamalıydım...",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Yine yanlış alarm işte...",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_RATS__001__M__1": "İğrenç yaratıklar.",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_RATS__001__M__2": "Ha, pis mahluklar.",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_RATS__001__M__3": "Hepinizden nefret ediyorum, haşarat!",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Etrafta bir şey yok.",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Burada her şey temiz!",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Bu tarafta her şey yolunda.",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Bir şey yok...",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Eh, her yer sessiz...",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Tamam, bir şey yokmuş....",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Bir şey diyecektim... Ah, geldi aklıma!",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Nerede kalmıştık? Ah, doğru!",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Ne diyordum? Ha, evet!",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Nöbete geri dönelim...",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "En iyisi bu.",
"VO__SOLDIER_B1__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Göreve geri dönelim...",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH__001__M__1": "Görmüyorum onları! Her köşeyi arayın!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH__001__M__2": "Az önce buradaydılar! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH__001__M__3": "Nereye gittiler?! Her yere bakın!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "İstediğin kadar saklan, geliyorum peşinden!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Çık çık ortaya...",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Seni bulmam an meselesi!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Yakalayalım onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Uzağa gitmiş olamazlar!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Merak etme, yakalayacağız onları.",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "O ahmaklar orada olmalı...",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Bunu yapmak ne kadar tedbirsizce!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Beni tam üstlerine getiriyorlar...",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "İşte oradalar! Yakalayın onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Buldum onları! Çabuk!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Orada! Gel buraya!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Benden saklanabileceğini mi sandın?!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Nereye gittiğini sanıyorsun?",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Buldum seni!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Davetsizler var! Bulmama yardım edin!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Etrafta izinsiz girenler var! Aramaya başlayın!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Biri etrafta dolanıyor! Bölgeyi arayın!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Hallediyorum!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Seninleyim!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Gidelim!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Onlar yaptı! Eminim!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Kesinlikle onların oyunlarından biri!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Beni yine kandırmaya çalışacaklarını bilmeliydim...",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Az önce buradaydılar! Yemin ederim!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Hâlâ yakında olmalılar! Her yeri arayın!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Uzakta olamazlar! Aramaya devam edin.",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Şurada saklanıyorlar! İcaplarına bakalım!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Şuraya sığındıklarını gördüm! Yakalayın onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Alçaklar şuraya saklandı!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Şunun arkasında saklanıyorsun, bilmediğimi mi sandın?",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Tam şunun arkasındasın! Seni gördüm!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Şunun arkasına saklanmak seni kurtarmaz!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı indiler! Bulacağım onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağıda bir yerdeler! Peşlerinden gideceğim!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağı atladılar! Yakalayacağım onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağıda saklanabileceğini sanma!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Aşağı indiğini biliyorum! Seni kurtarmaz!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Nereye gittiğini gördüm! Hemen aşağıdayım!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "Onları otların arasından kovalayacağım! Yanıma!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Onları otların arasından çıkaralım!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Davetsizler otların arasına girdi!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Seni şu otların arasından bizzat sürükleyip çıkaracağım!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Otların arasına mı saklanıyorsun?",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Otların arasına girdiğini gördüm!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Şunun altına girdiler! Onları bizzat sürükleyip çıkaracağım.",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "Şunun altındalar! Yakalayacağım onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Şunun altında olmalılar! Yakalayacağım onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Şunun altına saklanabileceğini sanma!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Şunun altına girdiğini biliyorum! Seni kurtarmaz!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Şunun altına saklanmak seni benden kurtarmaz!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Yukarı çıktılar! Bulun onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "Yukarıdalar! Peşlerinden gidin!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Yukarı tırmandılar! Yakalayın onları!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarıda saklanabileceğini sanma!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Yukarı tırmandığını biliyorum! Seni kurtarmaz!",
"VO__SOLDIER_B1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Nereye gittiğini gördüm! Hemen yukarı geliyorum!",
"VO__SOLDIER_B1__GENERIC__PATROL__SMOKE__001__M__1": "Şu duman da ne? Emin olalım.",
"VO__SOLDIER_B1__GENERIC__PATROL__SMOKE__001__M__2": "Bu duman da ne böyle?",
"VO__SOLDIER_B1__GENERIC__PATROL__SMOKE__001__M__3": "Duman mı? Burada mı? Tuhaf...",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Yine mi?! Orada neler oluyor bakalım!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Bu tuhaf... Yine mi?",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "Olamaz... Yine mi?! Neler oluyor?!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine mi?! Bir bakalım...",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Başka bir şey mi?! Emin olsam iyi olur...",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Hadi ama, yine mi! Bir kez olsun kontrol edelim.",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Hemen!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Bende.",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Gidip bakacağım!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Fazla gürültü var, davetsizler olabilir mi?! Ben hallederim!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "Bu ses hiç hoşuma gitmedi! Gidip bakacağım!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Zahmet etme, o sesin ne olduğuna ben bakarım.",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu gürültü de ne?",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Bu sesi çıkaran ne?",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Bu tuhaf ses de ne?",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "Şu ateş tuhaflaşıyor! Yakından bakacağım!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "Şu ateş... Gördün mü? Gidip bakacağım.",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Şuradaki ateşi gördün mü? Gidip baksak iyi olur.",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Ateş... Bu ne biçim bir hile?",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Şu ateşte tuhaf bir şeyler oluyor...",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Şu ateş... doğal değil!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Yakında bir şıklama duydum! Bana bırakın!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Şuradan bir şaklama sesi geldi!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "Bir şey şıkladı... Ne olduğuna gidip bakacağım.",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Şurada biri sapan mı kullanıyor?",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "Şak... şöyle bir etrafa bakalım...",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "Bu bir kamçı sesi miydi?",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Burada bir şey gördüm, bakacağım.",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Şu tarafta bir şey gördüm. Arkamı kolla.",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "O da neydi? Gidip bakacağım.",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Kim var orada?",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Hey? Kimse var mı? Geliyorum!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Biri mi var orada?",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Çok uzun sürmesin.",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Bir şey bulursan bağır!",
"VO__SOLDIER_B1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Bir şey bulursan haber ver.",
"VO__SOLDIER_B1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Burada her şey temiz...",
"VO__SOLDIER_B1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Burada değiller...",
"VO__SOLDIER_B1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Burada aramanın anlamı yok...",
"VO__SOLDIER_B1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Burada kimse yok...",
"VO__SOLDIER_B1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Burada kimse yok...",
"VO__SOLDIER_B1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Orada bir şey yok...",
# --- SOLDIER_B2 ---
"VO__SOLDIER_B2__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Görünüşe göre burada birkaç soytarı var. Bulun onları hemen!",
"VO__SOLDIER_B2__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Bölgeyi arayın, yakınlarda birkaç soytarı var!",
"VO__SOLDIER_B2__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Bizi aptal mı sanıyorlar?! Ne gerekiyorsa yapın, yakalayın onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Bu sana komik mi geliyor? Seni durdurmak için ne gerekiyorsa yapacağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Sen dur bakalım, şimdi bulacağım seni.",
"VO__SOLDIER_B2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Komik değilsin! Şu küçük oyunlarına son vereceğim.",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT__001__M__1": "Buraya! Davetsizler!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT__001__M__2": "Davetsizler! Buraya gelin!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT__001__M__3": "Buraya! İzinsiz girenler!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Sen! Dur!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Olduğun yerde dur!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Sen! Kaçmak için çok geç! Orada kal!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Bir yol bulduğumda, fena pataklayacağım seni!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "Ellerime geçireceğim seni, başka bir yol bulacağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Sana ulaşacağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Sonsuza dek burada sıkışıp kalmayacağım! Yakalayacağım seni!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Şu ana dek iyi oynadın ama sana ulaşacağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Peşini bırakmayacağım! Burada uzun süre sıkışıp kalmayacağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_DYING__001__M__1": "Lanet! Adam yere düştü!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_DYING__001__M__2": "Olamaz! Öldü!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_DYING__001__M__3": "Kahretsin! Birimiz öldü!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Yanacaksın!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Seni dumanla çıkaracağım dışarı, seni küçük alçak!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "Bu alevler seni otların arasından çıkaracak!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Yakalayın şu davetsizleri! Çabuk!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Uyanın! İzinsiz girenler var!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Çabuk olun! Durdurun alçakları!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Kaçmalarına izin vermeyin! Bölgeye yayılın!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Dağılın ve bulun onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Dağılın! Davetsizler geçiyor!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Dualarını et!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Bugün öleceksin!",
"VO__SOLDIER_B2__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Bana bulaşmamalıydın!",
"VO__SOLDIER_B2__GENERIC__PATROL__BURNING__001__M__1": "Alevler mi?!",
"VO__SOLDIER_B2__GENERIC__PATROL__BURNING__001__M__2": "Ateş mi? Olamaz!",
"VO__SOLDIER_B2__GENERIC__PATROL__BURNING__001__M__3": "Hadi ama! Bir de ateş mi çıktı?!",
"VO__SOLDIER_B2__GENERIC__PATROL__CAPTURE__001__M__1": "Çırpınmak şimdi sana yardım etmez!",
"VO__SOLDIER_B2__GENERIC__PATROL__CAPTURE__001__M__2": "Fazla kıpırdama! Temiz bir ölüm istiyorum!",
"VO__SOLDIER_B2__GENERIC__PATROL__CAPTURE__001__M__3": "Görünüşe göre son günün.",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE__001__M__1": "Sana ne oldu? Hey! Beni duyuyor musun?!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE__001__M__2": "Hey! Kalk ayağa, oyalanmayı bırak!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE__001__M__3": "Senin neyin var? Hey!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Bir türlü kalkmıyor...",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Hey! İyi misin?!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Bayıldı falan mı?",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Kavrulmuş bir ceset!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Tamamen yanmış!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Alev alev yanmış!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Olduğu yerde parçalanmış...",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Sıçanlar yemiş...",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Kimse böyle ölmeyi hak etmez...",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Biri katledilmiş! Bulun katili!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Adamlarımızdan biri ölmüş! Bulun katili!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Ölmüş! Tarayın bölgeyi!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Bir köpek gibi öldürülmüş! Bunu yapanı cezalandıracağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Ölmüş mü?! Bunu yapanı durduracağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Cinayet! O alçağı hemen durdursam iyi olur!",
"VO__SOLDIER_B2__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Merhamet dilenmeye kalkma.",
"VO__SOLDIER_B2__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Sağlamsın, ha?! Ama yine de ezeceğim seni.",
"VO__SOLDIER_B2__GENERIC__PATROL__DEATH_VEIL__001__M__3": "İkimiz de bunun nasıl biteceğini biliyoruz.",
"VO__SOLDIER_B2__GENERIC__PATROL__DYING__001__M__1": "Tanrım!",
"VO__SOLDIER_B2__GENERIC__PATROL__DYING__001__M__2": "Ne...?!",
"VO__SOLDIER_B2__GENERIC__PATROL__DYING__001__M__3": "Hey?!",
"VO__SOLDIER_B2__GENERIC__PATROL__FLEE_RATS__001__M__1": "Hayır hayır hayır hayır!",
"VO__SOLDIER_B2__GENERIC__PATROL__FLEE_RATS__001__M__2": "Bu bir kâbus!",
"VO__SOLDIER_B2__GENERIC__PATROL__FLEE_RATS__001__M__3": "Yapmayın! Sizi haşarat!",
"VO__SOLDIER_B2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Kurtuldum... Gerçekten kurtuldum...",
"VO__SOLDIER_B2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Kendinize başka bir yemek bulun, gözü dönmüş alçaklar!",
"VO__SOLDIER_B2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "Beni yakalayamayacaksınız! Duydunuz mu?!",
"VO__SOLDIER_B2__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Vuruldum! Davetsizler var!",
"VO__SOLDIER_B2__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Biri beni vurdu! Yakalayın alçağı!",
"VO__SOLDIER_B2__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Biri bana ateş ediyor! Tutuklayın onu!",
"VO__SOLDIER_B2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Bana mı ateş ediyorsun?! Bunu ödeteceğim sana, korkak!",
"VO__SOLDIER_B2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Bir daha dene! Şimdi gelip bulacağım seni!",
"VO__SOLDIER_B2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Beni öldürmek mi istiyorsun? Seni bulmamam için dua et!",
"VO__SOLDIER_B2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Hey! Nereye gittin?",
"VO__SOLDIER_B2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Hadi ama, neredesin?",
"VO__SOLDIER_B2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Konuşmayı mı kestin?",
"VO__SOLDIER_B2__GENERIC__PATROL__OIL__001__M__1": "Buraya neden katran dökülmüş...?",
"VO__SOLDIER_B2__GENERIC__PATROL__OIL__001__M__2": "Yerde neden katran var...",
"VO__SOLDIER_B2__GENERIC__PATROL__OIL__001__M__3": "O ahmaklardan biri yine bir küp mü kırdı?",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION__001__M__1": "Ne?",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION__001__M__2": "Ha?",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION__001__M__3": "O da ne?",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION_RATS__001__M__1": "Bırakın artık şunu!",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION_RATS__001__M__2": "Beni yakalayamayacağınızı ne zaman anlayacaksınız?!",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION_RATS__001__M__3": "İşte böyle, yorun kendinizi.",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Bırakın da geçeyim sizi pis alçaklar!",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "Bunun içinden nasıl geçeceğim?",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Açılın yoldan haşarat!",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "Çekilin yolumdan, lanet sıçanlar!",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "Lanet! Geçemeyeceğim.",
"VO__SOLDIER_B2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Pekâlâ! Daha ileri gitmeye çalışmayacağım...",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME__001__M__1": "Bir şey yokmuş...",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME__001__M__2": "Tuhaf...",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME__001__M__3": "İşime geri dönsem iyi olur.",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Üçüncü kez olmasa iyi olur...",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Eh, ikinci yanlış alarm.",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Yine yanlış alarmmış...",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Yine yanlış alarm...",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Bir şey yok... yine...",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Bir şey yok... Yine yanılmışım.",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_RATS__001__M__1": "Pis haşarat.",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_RATS__001__M__2": "İğrenç yaratıklar.",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_RATS__001__M__3": "Lanet mahluklar.",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Pekâlâ adamlar, bir şey yokmuş...",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Burası temiz.",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Burada her şey sakin.",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Burada bir şey yok...",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Endişelenecek bir şey yok.",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Bir şey yokmuş.",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Eee, nerede kalmıştık? Ah, geldi aklıma!",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Her neyse, nerede kalmıştık? Ha, biliyorum!",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Eee, konuşmamıza geri dönelim...",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Devriyene geri dön.",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Umarım artık iyi olur...",
"VO__SOLDIER_B2__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Sürpriz bile değil...",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH__001__M__1": "Uzakta olamazlar! Her yeri arayın!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH__001__M__2": "Buralarda bir yerdeler! Bulun onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH__001__M__3": "Nereye gittiler?! Her köşeyi arayın!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Korkaklar! Yine de bulacağım sizi!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Buralarda bir yerdesin, biliyorum! Çık ortaya!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Nereye saklanıyorsun?!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Merak etme, kaçamayacaklar!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Yakalayalım onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Uzun süre gülemeyecekler.",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Onları bulacağımı biliyordum.",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Onlar olduğuna eminim!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Onlardı, eminim...",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Görüyorum onları! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Buradalar! Yakalayın onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Yakaladım onları! Buraya!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Vay, şuna da bakın?!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "İşin bitti!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "İşte bu!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "İzinsiz girenler var! Tetikte olun!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Biri bölgede saklanıyor! Bir şey görürseniz haber verin!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Bölgede davetsizler var! Her köşeyi arayın!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Tamamdır!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Anlaşıldı!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Geliyorum!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Hadi ama! Yine onlar!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Onlar, burada durmayacaklarını biliyordum...",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Bunu ONLAR yaptı!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Lanet olsun! Kaçtılar!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Artık göremiyorum onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Yakında olduklarına eminim!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Şuraya sığındıklarını gördüm! Ben hallederim onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Şurada saklanıyorlar! Yakalayalım onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Şunun arkasında saklanmaya çalışıyorlar! Geliyorum!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Bu siperin yeterli olacağını mı sanıyorsun?",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Şunun arkasına saklanmak sana yardım etmeyecek!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Çık şunun arkasından, çabuk!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Davetsizler aşağı indi! Peşlerinden gidiyorum!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı atladılar! Yakalayın onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağı indiler! Yakalayacağım onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağı peşinden gelmeyeceğimi mi sanıyorsun?!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Buraya yukarı gel de dövüş!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Aşağı inmemi mi istiyorsun? Bildiğin gibi olsun!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "Onları uzun otların arasından kovalayalım!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Uzun otların arasındalar! Bulalım onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Otların arasındalar! Kaçmalarına izin veremeyiz!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Otların arasından kaçmaya mı çalışıyorsun? Benim nöbetimde olmaz!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Çık otların arasından!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Çık ortaya! Otların arasında olduğunu biliyorum!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Davetsizler şunun altına girdi! Peşlerinden gidiyorum!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "Şunun altında olmalılar! Onları bizzat çıkaracağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Şunun altına saklanıyorlar! Yakalayacağım onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Seni şunun altından sürükleyip çıkarmayacağımı mı sanıyorsun?!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Şunun altına süründün, seni yakalamayacağımı mı sanıyorsun?",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Şunun altına girdiğini görmediğimi mi sanıyorsun?!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Davetsizler yukarı çıktı! Peşlerinden gidin!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "Yukarı tırmandılar! Peşlerinden gidin!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Yukarı çıktılar! Yakalayın onları!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarı peşinden gelmeyeceğimi mi sanıyorsun?!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Buraya aşağı gel de dövüş!",
"VO__SOLDIER_B2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Yukarı çıkmamı mı istiyorsun? Bildiğin gibi olsun!",
"VO__SOLDIER_B2__GENERIC__PATROL__SMOKE__001__M__1": "Şu duman tuhaf görünüyor. Bakalım.",
"VO__SOLDIER_B2__GENERIC__PATROL__SMOKE__001__M__2": "Bunca duman. Bir terslik var.",
"VO__SOLDIER_B2__GENERIC__PATROL__SMOKE__001__M__3": "Şu dumana bir bakalım...",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Tamam! Tekrar gidip bakacağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine mi...? Gidip baksam iyi olur!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "Bir şeyler hâlâ ters! Bir bakalım.",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Hadi ama, yine mi?! Öğrenelim!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Olamaz! Tekrar baksam iyi olur...",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Ha?! Yine mi...? İcabına baksam iyi olur!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Tamam bakacağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Tabii, bakarım.",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Bana güvenebilirsin!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Sen de duydun mu? Bakayım...",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "Bu kulağa şüpheli geldi! Gidip bakacağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Duydun mu? Baksam iyi olur....",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu ses normal değildi...",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "O gürültü de neydi böyle?",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "O ses... Orada neler oluyor?",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "Şu ateşin nesi var?! Gidip araştıracağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "Büyü mü?! Şu aleve bir bakmalıyım...",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Bu değişen ışık hoşuma gitmedi! Bakmalıyım!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Ateş büyüsü mü?! Emin olalım.",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Şu ışığa ne oluyor? Bakmak istiyorum.",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Şurada ışık mı değişiyor? Bir bakalım...",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Şu şaklamayı duydun mu?! Şuradan geldi...",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "O şaklama sesi nereden geldi? Bakacağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "Bu bir kamçı değil miydi? Gidip bakacağım!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Oldukça yakından geldi...",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "Ha?! Bir patlama mı? Gözüm üstünde olacak...",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "O şaklama da ne?! Gidip bakacağım...",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Bir şeyin kıpırdadığını gördüm. Bir dakika ver.",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Sen de gördün mü?... Ben emin olana dek burada bekle.",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Biri mi var burada? Ben bakana dek gözle.",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Kim var orada!? Şuna bakmalıyım!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Lanet olsun, o da ne?!",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Şurada kıpırdayan ne? Kendim baksam iyi olur.",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Geri dön ve rapor ver.",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Dikkatli ol.",
"VO__SOLDIER_B2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Tuhaf bir şey görürsen haber ver!",
"VO__SOLDIER_B2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Burada kimse yok... Hareket etsem iyi olur.",
"VO__SOLDIER_B2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Başka bir yere baksam iyi olur...",
"VO__SOLDIER_B2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Nerede olabilirler?",
"VO__SOLDIER_B2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Başka yere baksam iyi olur...",
"VO__SOLDIER_B2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Burada bir şey yok...",
"VO__SOLDIER_B2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Neredesin...",
"VO__SOLDIER_B2__GENERIC__STATIC__FALCON_ATTACK__001__M__1": "Saldır!",
"VO__SOLDIER_B2__GENERIC__STATIC__FALCON_ATTACK__001__M__2": "Öldür!",
"VO__SOLDIER_B2__GENERIC__STATIC__FALCON_ATTACK__001__M__3": "Bana gözlerini getir!",
"VO__SOLDIER_B2__GENERIC__STATIC__FALCON_ATTACK__001__M__4": "Yakala onları!",
"VO__SOLDIER_B2__GENERIC__STATIC__FALCON_ATTACK__001__M__5": "Hadi! Git!",
"VO__SOLDIER_B2__GENERIC__STATIC__FALCON_ATTACK__001__M__6": "Hemen git!",
"VO__SOLDIER_B2__GENERIC__STATIC__FALCON_ATTACK__001__M__7": "Çabuk!",
"VO__SOLDIER_B2__GENERIC__STATIC__FALCON_ATTACK__001__M__8": "Uç!",
"VO__SOLDIER_B2__GENERIC__STATIC__FALCON_ATTACK__001__M__9": "Orada!",
"VO__SOLDIER_B2__GENERIC__STATIC__FALCON_ATTACK__001__M__10": "Orada! Saldır!",
"VO__SOLDIER_B2__GENERIC__STATIC__FALCON_ATTACK__001__M__11": "Öldürün onları!",
}
