# -*- coding: utf-8 -*-
# Genel Sesler GS1: AMICIA generic VO (407 satir).
T = {
"VO__AMICIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__1": "Olamaz...",
"VO__AMICIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__2": "Uzak dur...",
"VO__AMICIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__3": "Bu taraftan değil... Bu taraftan değil...",
"VO__AMICIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__4": "İyi değil...",
"VO__AMICIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__1": "Bu tarafa geliyorlar...",
"VO__AMICIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__2": "Bu tarafa yöneldiler!",
"VO__AMICIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__3": "Yaklaşıyorlar...",
"VO__AMICIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__4": "Buraya geliyorlar!",
"VO__AMICIA__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__1": "Şşşt!",
"VO__AMICIA__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__2": "Tek ses çıkmasın...",
"VO__AMICIA__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__3": "Sessiz ol!",
"VO__AMICIA__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__4": "Sessizlik!",
"VO__AMICIA__GENERIC__INTERACT__CAUGHT__001__M__1": "Hayır! Bırakın onu!",
"VO__AMICIA__GENERIC__INTERACT__CAUGHT__001__M__2": "Onu rahat bırakın!",
"VO__AMICIA__GENERIC__INTERACT__CAUGHT__001__M__3": "Çekin ellerinizi ondan!",
"VO__AMICIA__GENERIC__INTERACT__CAUGHT__001__M__4": "Ona dokunmayın!",
"VO__AMICIA__GENERIC__INTERACT__CHEST__001__M__1": "Bakalım burada ne varmış?",
"VO__AMICIA__GENERIC__INTERACT__CHEST__001__M__2": "İçinde ne var, bir bakalım.",
"VO__AMICIA__GENERIC__INTERACT__CHEST__001__M__3": "Bize ne getirdin bakalım?",
"VO__AMICIA__GENERIC__INTERACT__CHEST__001__M__4": "Tadaaa!",
"VO__AMICIA__GENERIC__INTERACT__CHEST__001__M__5": "Bize bir şey var mı acaba?",
"VO__AMICIA__GENERIC__INTERACT__CHEST__001__M__6": "Burada ne bulduk bakalım?",
"VO__AMICIA__GENERIC__INTERACT__CHEST__001__M__7": "Umarım işe yarar bir şey vardır.",
"VO__AMICIA__GENERIC__INTERACT__CHEST__001__M__8": "İçinde işe yarar bir şey var mı?",
"VO__AMICIA__GENERIC__INTERACT__CHEST_STRESSED__001__M__1": "Lütfen işe yarar bir şey olsun.",
"VO__AMICIA__GENERIC__INTERACT__CHEST_STRESSED__001__M__2": "Bakalım içinde ne var.",
"VO__AMICIA__GENERIC__INTERACT__CHEST_STRESSED__001__M__3": "Umarım değerli bir şey vardır.",
"VO__AMICIA__GENERIC__INTERACT__CHEST_STRESSED__001__M__4": "Burada işe yarar bir şey var mı?",
"VO__AMICIA__GENERIC__INTERACT__CHEST_STRESSED__001__M__5": "Bize bir şey var mı burada?",
"VO__AMICIA__GENERIC__INTERACT__CHEST_STRESSED__001__M__6": "İşe yarar bir şey?",
"VO__AMICIA__GENERIC__INTERACT__CLIMB__001__M__1": "Tırman.",
"VO__AMICIA__GENERIC__INTERACT__CLIMB__001__M__2": "Hadi, yukarı!",
"VO__AMICIA__GENERIC__INTERACT__CLIMB__001__M__3": "Yukarı çıkıyoruz...",
"VO__AMICIA__GENERIC__INTERACT__CLIMB__001__M__4": "Yukarı...",
"VO__AMICIA__GENERIC__INTERACT__CLIMB_DISCREET__001__M__1": "Yukarı, oraya...",
"VO__AMICIA__GENERIC__INTERACT__CLIMB_DISCREET__001__M__2": "Gel hadi, yukarı...",
"VO__AMICIA__GENERIC__INTERACT__CLIMB_DISCREET__001__M__3": "Yukarı...",
"VO__AMICIA__GENERIC__INTERACT__CLIMB_DISCREET__001__M__4": "Ve yukarı...",
"VO__AMICIA__GENERIC__INTERACT__CLIMB_STRESSED__001__M__1": "Çabuk yukarı...",
"VO__AMICIA__GENERIC__INTERACT__CLIMB_STRESSED__001__M__2": "Hemen çık yukarı...",
"VO__AMICIA__GENERIC__INTERACT__CLIMB_STRESSED__001__M__3": "Yukarı, hemen...",
"VO__AMICIA__GENERIC__INTERACT__CLIMB_STRESSED__001__M__4": "Çabuk yukarı!",
"VO__AMICIA__GENERIC__INTERACT__DIALOG_INTERUPT_DISCREET__001__M__1": "Bekle...",
"VO__AMICIA__GENERIC__INTERACT__DIALOG_INTERUPT_DISCREET__001__M__2": "Sonra...",
"VO__AMICIA__GENERIC__INTERACT__DIALOG_INTERUPT_DISCREET__001__M__3": "Sessiz ol...",
"VO__AMICIA__GENERIC__INTERACT__DIALOG_INTERUPT_DISCREET__001__M__4": "Şimdi olmaz...",
"VO__AMICIA__GENERIC__INTERACT__DIALOG_INTERUPT_DISCREET__001__M__5": "Şşt... Sessiz...",
"VO__AMICIA__GENERIC__INTERACT__DIALOG_INTERUPT_DISCREET__001__M__6": "Şşşş...",
"VO__AMICIA__GENERIC__INTERACT__DROP__001__M__1": "Aşağı dikkat et.",
"VO__AMICIA__GENERIC__INTERACT__DROP__001__M__2": "Buradaki düşüşe dikkat.",
"VO__AMICIA__GENERIC__INTERACT__DROP__001__M__3": "Aşağı atlamamız gerek.",
"VO__AMICIA__GENERIC__INTERACT__DROP__001__M__4": "İnerken dikkatli ol.",
"VO__AMICIA__GENERIC__INTERACT__DROP_DISCREET__001__M__1": "Usulca atla.",
"VO__AMICIA__GENERIC__INTERACT__DROP_DISCREET__001__M__2": "Düşüşe dikkatli ol...",
"VO__AMICIA__GENERIC__INTERACT__DROP_DISCREET__001__M__3": "Düşüşe dikkat et...",
"VO__AMICIA__GENERIC__INTERACT__DROP_DISCREET__001__M__4": "Yumuşak inmeye çalış...",
"VO__AMICIA__GENERIC__INTERACT__DROP_STRESSED__001__M__1": "Aşağı atla! Hadi!",
"VO__AMICIA__GENERIC__INTERACT__DROP_STRESSED__001__M__2": "İn aşağı!",
"VO__AMICIA__GENERIC__INTERACT__DROP_STRESSED__001__M__3": "Aşağı atla!",
"VO__AMICIA__GENERIC__INTERACT__DROP_STRESSED__001__M__4": "Buradaki düşüşe dikkat et!",
"VO__AMICIA__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__1": "Kahretsin!",
"VO__AMICIA__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__2": "Olamaz!",
"VO__AMICIA__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__3": "Bizi gördüler!",
"VO__AMICIA__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__4": "Peşimizdeler!",
"VO__AMICIA__GENERIC__INTERACT__HELP__001__M__1": "Bana yardım eder misin?",
"VO__AMICIA__GENERIC__INTERACT__HELP__001__M__2": "Yardımına ihtiyacım var.",
"VO__AMICIA__GENERIC__INTERACT__HELP__001__M__3": "Bunda yardım eder misin?",
"VO__AMICIA__GENERIC__INTERACT__HELP__001__M__4": "Yardım edebilir misin?",
"VO__AMICIA__GENERIC__INTERACT__HELP_DISCREET__001__M__1": "Yardımına ihtiyacım var.",
"VO__AMICIA__GENERIC__INTERACT__HELP_DISCREET__001__M__2": "Gel bana bir el at.",
"VO__AMICIA__GENERIC__INTERACT__HELP_DISCREET__001__M__3": "Bunda yardım et bana.",
"VO__AMICIA__GENERIC__INTERACT__HELP_DISCREET__001__M__4": "Yardım edebilir misin?",
"VO__AMICIA__GENERIC__INTERACT__HELP_STRESSED__001__M__1": "Bir ele ihtiyacım var!",
"VO__AMICIA__GENERIC__INTERACT__HELP_STRESSED__001__M__2": "Yardım eder misin?",
"VO__AMICIA__GENERIC__INTERACT__HELP_STRESSED__001__M__3": "Bunda yardım et bana!",
"VO__AMICIA__GENERIC__INTERACT__HELP_STRESSED__001__M__4": "Yardım edebilir misin?!",
"VO__AMICIA__GENERIC__INTERACT__HUGO__001__M__1": "Hadi bakalım, Hugo.",
"VO__AMICIA__GENERIC__INTERACT__HUGO__001__M__2": "Sen hallet, Hugo.",
"VO__AMICIA__GENERIC__INTERACT__HUGO__001__M__3": "Bunu sana bırakıyorum, Hugo.",
"VO__AMICIA__GENERIC__INTERACT__HUGO__001__M__4": "Hugo, yardımına ihtiyacım var.",
"VO__AMICIA__GENERIC__INTERACT__HUGO_DISCREET__001__M__1": "Sana kalmış, Hugo...",
"VO__AMICIA__GENERIC__INTERACT__HUGO_DISCREET__001__M__2": "Lütfen benim için yap Hugo...",
"VO__AMICIA__GENERIC__INTERACT__HUGO_DISCREET__001__M__3": "Bu sana göre bir iş Hugo.",
"VO__AMICIA__GENERIC__INTERACT__HUGO_DISCREET__001__M__4": "Bu senin görevin Hugo.",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT__001__M__1": "Artık durabilirsin.",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT__001__M__2": "Artık bırakabilirsin.",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT__001__M__3": "Bırakabilirsin.",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT__001__M__4": "Dur.",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT_DISCREET__001__M__1": "Bırak.",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT_DISCREET__001__M__2": "Durabilir misin?",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT_DISCREET__001__M__3": "Durdurabilirsin.",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT_DISCREET__001__M__4": "Tamam, dur.",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT_STRESSED__001__M__1": "Bırakabilirsin.",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT_STRESSED__001__M__2": "Tamam, bırak!",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT_STRESSED__001__M__3": "Hemen dur.",
"VO__AMICIA__GENERIC__INTERACT__INTERRUPT_STRESSED__001__M__4": "Bu kadar yeter! Bırak!",
"VO__AMICIA__GENERIC__INTERACT__LADDER_DOWN__001__M__1": "Dikkatlice in.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_DOWN__001__M__2": "Aşağı inelim.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_DOWN__001__M__3": "Aşağı inelim. Dikkatli ol.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_DOWN__001__M__4": "Benimle in aşağı.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_DOWN_DISCREET__001__M__1": "Aşağı in. Dikkatli ol.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_DOWN_DISCREET__001__M__2": "Sessizce in aşağı.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_DOWN_DISCREET__001__M__3": "Aşağı iniyoruz.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_DOWN_STRESSED__001__M__1": "Aşağı in!",
"VO__AMICIA__GENERIC__INTERACT__LADDER_DOWN_STRESSED__001__M__2": "Çabuk aşağı!",
"VO__AMICIA__GENERIC__INTERACT__LADDER_DOWN_STRESSED__001__M__3": "Merdivenden in! Hemen!",
"VO__AMICIA__GENERIC__INTERACT__LADDER_RATS__001__M__1": "Aşağıda çok fazla sıçan var...",
"VO__AMICIA__GENERIC__INTERACT__LADDER_RATS__001__M__2": "Önce şu sıçanlardan kurtulmamız gerek...",
"VO__AMICIA__GENERIC__INTERACT__LADDER_RATS__001__M__3": "Aşağıdaki sıçanlarla çok tehlikeli...",
"VO__AMICIA__GENERIC__INTERACT__LADDER_UP__001__M__1": "Önce sen tırman!",
"VO__AMICIA__GENERIC__INTERACT__LADDER_UP__001__M__2": "Tırman yukarı.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_UP__001__M__3": "Hadi, tırman...",
"VO__AMICIA__GENERIC__INTERACT__LADDER_UP__001__M__4": "Hadi, tırman yukarı.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_UP_DISCREET__001__M__1": "Tırman, hemen arkandayım...",
"VO__AMICIA__GENERIC__INTERACT__LADDER_UP_DISCREET__001__M__2": "Tırman yukarı. Dikkatlice.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_UP_DISCREET__001__M__3": "Hemen çık yukarı!",
"VO__AMICIA__GENERIC__INTERACT__LADDER_UP_STRESSED__001__M__1": "Tırman yukarı.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_UP_STRESSED__001__M__2": "Çık yukarı. Hemen.",
"VO__AMICIA__GENERIC__INTERACT__LADDER_UP_STRESSED__001__M__3": "Çabuk çık yukarı!",
"VO__AMICIA__GENERIC__INTERACT__LOSS__001__M__1": "Hayır! HAYIIIR!",
"VO__AMICIA__GENERIC__INTERACT__LOSS__001__M__2": "Olamaz! HAYIR!",
"VO__AMICIA__GENERIC__INTERACT__LOSS__001__M__3": "Hayır! Lütfen olmaz! HAYIR!",
"VO__AMICIA__GENERIC__INTERACT__LOSS__001__M__4": "Hayır, hayır, hayır, hayır! HAYIIIR!",
"VO__AMICIA__GENERIC__INTERACT__LOSS_HUGO__001__M__1": "Hugo! HUGOOO!",
"VO__AMICIA__GENERIC__INTERACT__LOSS_HUGO__001__M__2": "Hayır! HAYIIR!",
"VO__AMICIA__GENERIC__INTERACT__LOSS_HUGO__001__M__3": "Hayır! Hayır! HUGOOOO!",
"VO__AMICIA__GENERIC__INTERACT__LOSS_HUGO__001__M__4": "Hugo! HUGO! HAYIIIIR!",
"VO__AMICIA__GENERIC__INTERACT__LUCAS__001__M__1": "Lucas, bununla senin ilgilenmeni istiyorum.",
"VO__AMICIA__GENERIC__INTERACT__LUCAS__001__M__2": "Lucas, bu senin işin.",
"VO__AMICIA__GENERIC__INTERACT__LUCAS__001__M__3": "Lucas, halledebilir misin?",
"VO__AMICIA__GENERIC__INTERACT__LUCAS__001__M__4": "Lucas, yardımına ihtiyacım var.",
"VO__AMICIA__GENERIC__INTERACT__LUCAS_DISCREET__001__M__1": "Bunu sana bırakıyorum Lucas...",
"VO__AMICIA__GENERIC__INTERACT__LUCAS_DISCREET__001__M__2": "Lucas, bunu benim için yap.",
"VO__AMICIA__GENERIC__INTERACT__LUCAS_DISCREET__001__M__3": "Bu konuda sana güveniyorum, Lucas.",
"VO__AMICIA__GENERIC__INTERACT__LUCAS_DISCREET__001__M__4": "Lucas, bunu yapacak kişi sensin.",
"VO__AMICIA__GENERIC__INTERACT__MISSING_COMPANION__001__M__1": "Kimseden vazgeçmeyeceğim.",
"VO__AMICIA__GENERIC__INTERACT__MISSING_COMPANION__001__M__2": "Herkes olmadan ilerleyemem...",
"VO__AMICIA__GENERIC__INTERACT__MISSING_COMPANION__001__M__3": "Kimse geride kalmayacak.",
"VO__AMICIA__GENERIC__INTERACT__MISSING_COMPANION__001__M__4": "Kimseyi yüzüstü bırakmayacağım.",
"VO__AMICIA__GENERIC__INTERACT__MISSING_COMPANION_DISCREET__001__M__1": "Kimseyi geride bırakmıyorum...",
"VO__AMICIA__GENERIC__INTERACT__MISSING_COMPANION_DISCREET__001__M__2": "Herkes olmadan ilerleyemem...",
"VO__AMICIA__GENERIC__INTERACT__MISSING_COMPANION_DISCREET__001__M__3": "Kimse geride kalmaz!",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_COOLDOWN__001__M__1": "Yapma. Bir an dinlenmen gerek.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_COOLDOWN__001__M__2": "Dinlen, ben bizi korurum.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_COOLDOWN__001__M__3": "Önce sakinleşmen gerek.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_COOLDOWN__001__M__4": "Sen şimdilik rahatla, ben hallederim.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_RELEASE__001__M__1": "Üstünlüğü onlara kaptırmamalısın.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_RELEASE__001__M__2": "Daha dikkatli olmalısın!",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_RELEASE__001__M__3": "Seni alt etmelerine izin veremezsin.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_RELEASE__001__M__4": "Bir dahakine daha erken bırak. Önce sen gelirsin.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_1__001__M__1": "Odaklan.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_1__001__M__2": "Nefes al.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_1__001__M__3": "Tıpkı geçen seferki gibi.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_1__001__M__4": "Bunu yapabilirsin.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_2__001__M__1": "Kendini zorlama.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_2__001__M__2": "Dikkatli ol.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_2__001__M__3": "Aşırıya kaçma.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_2__001__M__4": "Çok zorlaşırsa bırak.",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_3__001__M__1": "Hugo dur! Dur!",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_3__001__M__2": "Dur Hugo!",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_3__001__M__3": "Bırak! Hemen!",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_STEP_3__001__M__4": "Bırak onları!",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_TRIGGERED__001__M__1": "Hugo!",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_TRIGGERED__001__M__2": "Olamaz, hayır hayır!",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_TRIGGERED__001__M__3": "Aman Tanrım!",
"VO__AMICIA__GENERIC__INTERACT__OVERCHARGE_TRIGGERED__001__M__4": "Neler oluyor?!",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH__001__M__1": "Buradan.",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH__001__M__2": "Beni takip et.",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH__001__M__3": "Benimle gel.",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH__001__M__4": "Bu taraftan gidelim.",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH_DISCREET__001__M__1": "Beni takip et... Sessizce...",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH_DISCREET__001__M__2": "Arkama geç...",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH_DISCREET__001__M__3": "Benimle gel...",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH_DISCREET__001__M__4": "Bu taraftan gideceğiz...",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH_STRESSED__001__M__1": "Bu taraftan!",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH_STRESSED__001__M__2": "Beni takip et!",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH_STRESSED__001__M__3": "Arkamdan gel!",
"VO__AMICIA__GENERIC__INTERACT__PASSTHROUGH_STRESSED__001__M__4": "Buradan!",
"VO__AMICIA__GENERIC__INTERACT__PUSH__001__M__1": "Şunu itelim.",
"VO__AMICIA__GENERIC__INTERACT__PUSH__001__M__2": "Şunu itmeme yardım et.",
"VO__AMICIA__GENERIC__INTERACT__PUSH__001__M__3": "Şunu benimle it.",
"VO__AMICIA__GENERIC__INTERACT__PUSH__001__M__4": "Şunu itmeye hazır mısın?",
"VO__AMICIA__GENERIC__INTERACT__PUSH_DISCREET__001__M__1": "Şunu itmemiz gerek.",
"VO__AMICIA__GENERIC__INTERACT__PUSH_DISCREET__001__M__2": "Şunu itmeme yardım et.",
"VO__AMICIA__GENERIC__INTERACT__PUSH_DISCREET__001__M__3": "Şunu itmemiz lazım.",
"VO__AMICIA__GENERIC__INTERACT__PUSH_DISCREET__001__M__4": "Şunu itmeme yardım et.",
"VO__AMICIA__GENERIC__INTERACT__PUSH_STRESSED__001__M__1": "Şunu itelim!",
"VO__AMICIA__GENERIC__INTERACT__PUSH_STRESSED__001__M__2": "Şunu itmeme yardım et!",
"VO__AMICIA__GENERIC__INTERACT__PUSH_STRESSED__001__M__3": "Şunu itelim, HEMEN!",
"VO__AMICIA__GENERIC__INTERACT__PUSH_STRESSED__001__M__4": "Çabuk, şunu itelim!",
"VO__AMICIA__GENERIC__INTERACT__PYRITE_TRIGGERED__001__M__1": "Bana yakın dur!",
"VO__AMICIA__GENERIC__INTERACT__PYRITE_TRIGGERED__001__M__2": "Yakın dur!",
"VO__AMICIA__GENERIC__INTERACT__PYRITE_TRIGGERED__001__M__3": "Bana yakın!",
"VO__AMICIA__GENERIC__INTERACT__PYRITE_WARNING__001__M__1": "Pirit uzun sürmez, acele et!",
"VO__AMICIA__GENERIC__INTERACT__PYRITE_WARNING__001__M__2": "Etkisi birazdan bitecek...",
"VO__AMICIA__GENERIC__INTERACT__PYRITE_WARNING__001__M__3": "Vakti tükeniyor!",
"VO__AMICIA__GENERIC__INTERACT__QUICK_TRAVERSAL__001__M__1": "Yukarı.",
"VO__AMICIA__GENERIC__INTERACT__QUICK_TRAVERSAL__001__M__2": "Yukarı ve karşıya.",
"VO__AMICIA__GENERIC__INTERACT__QUICK_TRAVERSAL__001__M__3": "Hadi.",
"VO__AMICIA__GENERIC__INTERACT__QUICK_TRAVERSAL__001__M__4": "Beraber.",
"VO__AMICIA__GENERIC__INTERACT__QUICK_TRAVERSAL_STRESSED__001__M__1": "Yukarı!",
"VO__AMICIA__GENERIC__INTERACT__QUICK_TRAVERSAL_STRESSED__001__M__2": "Yukarı ve karşıya!",
"VO__AMICIA__GENERIC__INTERACT__QUICK_TRAVERSAL_STRESSED__001__M__3": "Hadi!",
"VO__AMICIA__GENERIC__INTERACT__QUICK_TRAVERSAL_STRESSED__001__M__4": "Beraber!",
"VO__AMICIA__GENERIC__INTERACT__SAVED__001__M__1": "İyi misin?!",
"VO__AMICIA__GENERIC__INTERACT__SAVED__001__M__2": "Lütfen iyi olduğunu söyle!",
"VO__AMICIA__GENERIC__INTERACT__SAVED__001__M__3": "Zarar görmedin değil mi?!",
"VO__AMICIA__GENERIC__INTERACT__SAVED__001__M__4": "Lütfen iyi olduğunu söyle!",
"VO__AMICIA__GENERIC__INTERACT__UPGRADE_COMPLETE__001__M__1": "Bu işleri biraz kolaylaştırır.",
"VO__AMICIA__GENERIC__INTERACT__UPGRADE_COMPLETE__001__M__2": "Çok daha iyi.",
"VO__AMICIA__GENERIC__INTERACT__UPGRADE_COMPLETE__001__M__3": "Gayet iyi görünüyor!",
"VO__AMICIA__GENERIC__INTERACT__UPGRADE_COMPLETE__001__M__4": "Tam da ihtiyacım olan şey.",
"VO__AMICIA__GENERIC__INTERACT__UPGRADE_COMPLETE__001__M__5": "Ve... işte!",
"VO__AMICIA__GENERIC__INTERACT__UPGRADE_COMPLETE__001__M__6": "Bununla gurur duyuyorum!",
"VO__AMICIA__GENERIC__INTERACT__VAULT__001__M__1": "Elini ver.",
"VO__AMICIA__GENERIC__INTERACT__VAULT__001__M__2": "Sana yardım edeyim.",
"VO__AMICIA__GENERIC__INTERACT__VAULT__001__M__3": "Dikkat et.",
"VO__AMICIA__GENERIC__INTERACT__VAULT__001__M__4": "Dikkatli ol.",
"VO__AMICIA__GENERIC__INTERACT__VAULT_DISCREET__001__M__1": "Sessizce.",
"VO__AMICIA__GENERIC__INTERACT__VAULT_DISCREET__001__M__2": "Hadi geç.",
"VO__AMICIA__GENERIC__INTERACT__VAULT_DISCREET__001__M__3": "Tek ses çıkarma.",
"VO__AMICIA__GENERIC__INTERACT__VAULT_DISCREET__001__M__4": "Dikkatli ol.",
"VO__AMICIA__GENERIC__INTERACT__VAULT_STRESSED__001__M__1": "Çabuk olalım!",
"VO__AMICIA__GENERIC__INTERACT__VAULT_STRESSED__001__M__2": "Hadi!",
"VO__AMICIA__GENERIC__INTERACT__VAULT_STRESSED__001__M__3": "Çabuk geç!",
"VO__AMICIA__GENERIC__INTERACT__VAULT_STRESSED__001__M__4": "Beraber!",
"VO__AMICIA__GENERIC__INTERACT__WORKBENCH_ENTER__001__M__1": "Bakalım neler yapabiliriz...",
"VO__AMICIA__GENERIC__INTERACT__WORKBENCH_ENTER__001__M__2": "Pekâlâ, işe koyulalım.",
"VO__AMICIA__GENERIC__INTERACT__WORKBENCH_ENTER__001__M__3": "İşe koyulma vakti...",
"VO__AMICIA__GENERIC__INTERACT__WORKBENCH_ENTER__001__M__4": "Birkaç değişiklik yapalım.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD__001__M__1": "Arnaud, bir ele ihtiyacım var.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD__001__M__2": "Arnaud, biraz yardım?",
"VO__AMICIA__GENERIC__ORDER__ARNAUD__001__M__3": "Sen halledebilir misin, Arnaud?",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_DISCREET__001__M__1": "Arnaud, sana kalmış!",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_DISCREET__001__M__2": "Arnaud, yardım et lütfen...",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_DISCREET__001__M__3": "Arnaud, bir el at.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_FOLLOW__001__M__1": "Arnaud, gidelim.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_FOLLOW__001__M__2": "Hareket edelim Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_FOLLOW__001__M__3": "Hadi Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_FOLLOW_DISCREET__001__M__1": "Benimle gel Arnaud...",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_FOLLOW_DISCREET__001__M__2": "Benimle Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_FOLLOW_DISCREET__001__M__3": "Hadi Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_FOLLOW_STRESSED__001__M__1": "Gidelim Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_FOLLOW_STRESSED__001__M__2": "Gel Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_FOLLOW_STRESSED__001__M__3": "Beni takip et Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_GROUPFIGHT_ORDER__001__M__1": "Arnaud, şununla ilgilen!",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_GROUPFIGHT_ORDER__001__M__2": "O senin, Arnaud!",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_GROUPFIGHT_ORDER__001__M__3": "Arnaud, sen onun icabına bak!",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STAY__001__M__1": "Arnaud, burada kal.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STAY__001__M__2": "Burada kal Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STAY__001__M__3": "Burada bekle Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STAY_DISCREET__001__M__1": "Arnaud kıpırdama. Geri döneceğim.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STAY_DISCREET__001__M__2": "Beni burada bekle.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STAY_DISCREET__001__M__3": "Ben dönene kadar burada kal, Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STAY_STRESSED__001__M__1": "Ben dönene kadar kıpırdama, Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STAY_STRESSED__001__M__2": "Beni burada bekle, Arnaud.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STAY_STRESSED__001__M__3": "Burada bekle Arnaud, döneceğim.",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STRESSED__001__M__1": "Arnaud! Sen hallet!",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STRESSED__001__M__2": "Sana bırakıyorum Arnaud!",
"VO__AMICIA__GENERIC__ORDER__ARNAUD_STRESSED__001__M__3": "Sıra sende Arnaud.",
"VO__AMICIA__GENERIC__ORDER__HUGO_COME_CLOSE_DISCREET_RC__001__M__1": "Onları çağır...",
"VO__AMICIA__GENERIC__ORDER__HUGO_COME_CLOSE_DISCREET_RC__001__M__2": "Çağır onları...",
"VO__AMICIA__GENERIC__ORDER__HUGO_COME_CLOSE_DISCREET_RC__001__M__3": "Onları çağır...",
"VO__AMICIA__GENERIC__ORDER__HUGO_COME_CLOSE_DISCREET_RC__001__M__4": "Onlara ihtiyacımız var...",
"VO__AMICIA__GENERIC__ORDER__HUGO_COME_CLOSE_RC__001__M__1": "Çağır onları...",
"VO__AMICIA__GENERIC__ORDER__HUGO_COME_CLOSE_RC__001__M__2": "Gelmelerini söyle.",
"VO__AMICIA__GENERIC__ORDER__HUGO_COME_CLOSE_RC__001__M__3": "Onları buraya çağır...",
"VO__AMICIA__GENERIC__ORDER__HUGO_COME_CLOSE_RC__001__M__4": "Onları çağır.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW__001__M__1": "Gel hadi, Hugo.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW__001__M__2": "Bana yakın dur.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW__001__M__3": "Elimi tut Hugo.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW__001__M__4": "Yakın dur, Hugo.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW_DISCREET__001__M__1": "Hugo, bana yakın dur.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW_DISCREET__001__M__2": "Hugo, benimle gel.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW_DISCREET__001__M__3": "Elimi tut Hugo.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW_DISCREET__001__M__4": "Yakın dur Hugo.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW_STRESSED__001__M__1": "Hadi gel, Hugo.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW_STRESSED__001__M__2": "Yola koyulalım, Hugo.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW_STRESSED__001__M__3": "Hugo, elimi tut.",
"VO__AMICIA__GENERIC__ORDER__HUGO_FOLLOW_STRESSED__001__M__4": "Hugo! Bana yakın dur!",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY__001__M__1": "Burada kal, uzun sürmez.",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY__001__M__2": "Burada bekle.",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY__001__M__3": "Burada kal.",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY__001__M__4": "Beni burada bekle.",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY_DISCREET__001__M__1": "Ben dönene kadar sessizce burada kal.",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY_DISCREET__001__M__2": "Burada kal, sessizce!",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY_DISCREET__001__M__3": "Ben dönene kadar sessiz ol.",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY_DISCREET__001__M__4": "Tam burada kalıyorsun, anlaşıldı mı?",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY_STRESSED__001__M__1": "Burada kal Hugo!",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY_STRESSED__001__M__2": "Kıpırdama, hemen döneceğim.",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY_STRESSED__001__M__3": "Tam burada kal, anlaşıldı mı?!",
"VO__AMICIA__GENERIC__ORDER__HUGO_STAY_STRESSED__001__M__4": "Ben dönene kadar burada kal.",
"VO__AMICIA__GENERIC__ORDER__HUGO_STRESSED__001__M__1": "Çabuk yap!",
"VO__AMICIA__GENERIC__ORDER__HUGO_STRESSED__001__M__2": "Yapabilir misin Hugo?",
"VO__AMICIA__GENERIC__ORDER__HUGO_STRESSED__001__M__3": "Hugo, yapabileceğini biliyorum!",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOGWALK_ORDER__001__M__1": "Lucas? Bir Stupefacio işe yarar.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOGWALK_ORDER__001__M__2": "Lucas, bir Stupefacio lütfen.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOGWALK_ORDER__001__M__3": "Bir Stupefacio kullanabilir misin, Lucas?",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOGWALK_ORDER_DISCREET__001__M__1": "Lucas, bir Stupefacio at.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOGWALK_ORDER_DISCREET__001__M__2": "Lucas, bir Stupefacio kullan.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOGWALK_ORDER_DISCREET__001__M__3": "Belki bir Stupefacio?",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW__001__M__1": "Gidelim, Lucas.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW__001__M__2": "Beni takip et.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW__001__M__3": "Yola koyulalım.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW__001__M__4": "Benimle gel Lucas.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW_DISCREET__001__M__1": "Lucas, gidelim.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW_DISCREET__001__M__2": "Lucas, benimle, çabuk.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW_DISCREET__001__M__3": "Beni takip et Lucas.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW_DISCREET__001__M__4": "Bana yakın dur Lucas.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW_STRESSED__001__M__1": "Hareket edelim Lucas.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW_STRESSED__001__M__2": "Beni takip et Lucas.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW_STRESSED__001__M__3": "Gidelim Lucas.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_FOLLOW_STRESSED__001__M__4": "Lucas, beni takip et.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY__001__M__1": "Burada bekle Lucas, hemen döneceğim.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY__001__M__2": "Burada kal Lucas, ben ileriye bakacağım.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY__001__M__3": "Lucas burada bekle, döneceğim.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY__001__M__4": "Lucas burada kal, önce ben gideceğim.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY_DISCREET__001__M__1": "Burada bekle Lucas. Hemen döneceğim.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY_DISCREET__001__M__2": "Lucas, burada kal. İleride ne var bir bakacağım.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY_DISCREET__001__M__3": "Lucas, burada bekle. Hemen döneceğim.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY_DISCREET__001__M__4": "Burada kal Lucas. Geri döneceğim.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY_STRESSED__001__M__1": "Burada bekle, senin için döneceğim Lucas.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY_STRESSED__001__M__2": "Beni burada bekle, uzun sürmeyecek Lucas.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY_STRESSED__001__M__3": "Beni tam burada bekle Lucas.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STAY_STRESSED__001__M__4": "Burada kal Lucas. Sonra gelip seni bulurum.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STRESSED__001__M__1": "Lucas, bu sana göre bir iş.",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STRESSED__001__M__2": "Lucas! Bu sana kalmış!",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STRESSED__001__M__3": "Sen hallet, Lucas!",
"VO__AMICIA__GENERIC__ORDER__LUCAS_STRESSED__001__M__4": "Sana kalmış, Lucas!",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW__001__M__1": "Hadi.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW__001__M__2": "Beni takip edin.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW__001__M__3": "Gelin, güvenli görünüyor.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW__001__M__4": "Benimle gelin.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW_DISCREET__001__M__1": "Hadi gelin...",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW_DISCREET__001__M__2": "Beni takip edin. Sessizce...",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW_DISCREET__001__M__3": "Gidelim, sessiz olun.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW_DISCREET__001__M__4": "Benimle gelin. Dikkatli olun...",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW_STRESSED__001__M__1": "Hadi gelin!",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW_STRESSED__001__M__2": "Beni takip edin!",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW_STRESSED__001__M__3": "Benimle!",
"VO__AMICIA__GENERIC__ORDER__PLURAL_FOLLOW_STRESSED__001__M__4": "Benimle gelin!",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY__001__M__1": "Burada kalın.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY__001__M__2": "Burada bekleyin, uzun sürmez.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY__001__M__3": "Ben dönene kadar burada kalın.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY__001__M__4": "İkiniz de burada bekleyin. Hemen döneceğim.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY_DISCREET__001__M__1": "Burada kalın, sizin için döneceğim.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY_DISCREET__001__M__2": "Burada bekleyin, hemen döneceğim.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY_DISCREET__001__M__3": "Beni burada bekleyin, görünmeyin.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY_DISCREET__001__M__4": "Ben dönene kadar burada saklanın.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY_STRESSED__001__M__1": "Burada bekleyin, hemen döneceğim.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY_STRESSED__001__M__2": "Burada kalın, uzun sürmez.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY_STRESSED__001__M__3": "Burada güvende kalın, hemen döneceğim.",
"VO__AMICIA__GENERIC__ORDER__PLURAL_STAY_STRESSED__001__M__4": "İkiniz burada kalın, beni bekleyin.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA__001__M__1": "Sophia, sen halledebilir misin?",
"VO__AMICIA__GENERIC__ORDER__SOPHIA__001__M__2": "Yardımına ihtiyacım var, Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA__001__M__3": "Sophia, sana güvenebilir miyim?",
"VO__AMICIA__GENERIC__ORDER__SOPHIA__001__M__4": "Bir ele ihtiyacım var, Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_DISCREET__001__M__1": "Sophia! Yapabilir misin?",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_DISCREET__001__M__2": "Yapılacak iş var Sophia...",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_DISCREET__001__M__3": "Sophia, bu sana göre.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_DISCREET__001__M__4": "Yardım et bana, Sophia...",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW__001__M__1": "Hareket edelim Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW__001__M__2": "Hadi Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW__001__M__3": "Hareket edelim, Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW__001__M__4": "Sophia, gidelim.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW_DISCREET__001__M__1": "Sophia, gel.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW_DISCREET__001__M__2": "Sophia, hadi gel.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW_DISCREET__001__M__3": "Sophia benimle.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW_DISCREET__001__M__4": "Gidelim Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW_STRESSED__001__M__1": "Beni takip et, Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW_STRESSED__001__M__2": "Gel Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW_STRESSED__001__M__3": "Benimle gel, Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_FOLLOW_STRESSED__001__M__4": "Sophia, gidelim.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_PRISM_DISTRACT_ORDER_DISCREET__001__M__1": "Sophia? Numaran burada işe yarar.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_PRISM_DISTRACT_ORDER_DISCREET__001__M__2": "Sophia, prizman işe yarardı.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_PRISM_DISTRACT_ORDER_DISCREET__001__M__3": "Sophia, prizmanı kullanabilir misin?",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_PRISM_REPULSE_ORDER__001__M__1": "Sophia! Bize bir yol aç!",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_PRISM_REPULSE_ORDER__001__M__2": "Sophia! Yolumuzu aydınlat!",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_PRISM_REPULSE_ORDER__001__M__3": "Bize yolu aç, Sophia?!",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY__001__M__1": "Burada kal Sophia, uzun sürmez.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY__001__M__2": "Sophia, burada bekle, hemen döneceğim.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY__001__M__3": "Ben bir göz atarken burada bekle Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY__001__M__4": "Burada kal Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY_DISCREET__001__M__1": "Burada bekle Sophia. Tek başıma gideceğim.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY_DISCREET__001__M__2": "Ben ileriye bakarken burada kal.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY_DISCREET__001__M__3": "Sophia, burada bekle.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY_DISCREET__001__M__4": "Şimdilik burada kal. Uzun sürmez.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY_STRESSED__001__M__1": "Burada kal Sophia. Tek gideceğim.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY_STRESSED__001__M__2": "Ben dönene kadar kıpırdama Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY_STRESSED__001__M__3": "Hemen dönerim Sophia. Burada kal.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STAY_STRESSED__001__M__4": "Sen burada kal Sophia.",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STRESSED__001__M__1": "Sophia, sen hallet!",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STRESSED__001__M__2": "Sophia! Hadi yap!",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STRESSED__001__M__3": "Sophia! Hemen, yap!",
"VO__AMICIA__GENERIC__ORDER__SOPHIA_STRESSED__001__M__4": "Bu sana göre, Sophia...",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER__001__M__1": "İlginç.",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER__001__M__2": "Bu çok işe yarar.",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER__001__M__3": "Tavsiyen için sağ ol.",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER__001__M__4": "Değerli bir tavsiye.",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER_DISCREET__001__M__1": "Çok faydalı, teşekkürler.",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER_DISCREET__001__M__2": "İyi tavsiye.",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER_DISCREET__001__M__3": "İyi öneri.",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER_DISCREET__001__M__4": "Harika fikir, sağ ol.",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER_STRESSED__001__M__1": "Harika! İşe yarıyor.",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER_STRESSED__001__M__2": "İyi fikir.",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER_STRESSED__001__M__3": "İyi düşündün.",
"VO__AMICIA__GENERIC__RESPONSE__HELPER_ANSWER_STRESSED__001__M__4": "Tam zamanında bir tavsiye!",
}
