# -*- coding: utf-8 -*-
# Genel Sesler GS5: SOLDIER_S1+S2 generic VO (624 satir). Askerler: disiplinli, sert, "sen/siz".
T = {
"VO__SOLDIER_S1__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Biri bizimle oynuyor! Aramaya başlayın!",
"VO__SOLDIER_S1__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Biri bizimle uğraşmak istiyor! Bulun kim olduğunu!",
"VO__SOLDIER_S1__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Biri bizi kandırmaya çalışıyor! Arayın onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Şu ana kadar şanslıydın ama seni bulacağım!",
"VO__SOLDIER_S1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Beni bir daha kandırabileceğini mi sanıyorsun?! Hemen göster kendini!",
"VO__SOLDIER_S1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Beni aptal yerine mi koymaya çalışıyorsun? Yakalayacağım seni!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT__001__M__1": "Burada biri var! Herkes! Benimle!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT__001__M__2": "Burada davetsiz misafirler var!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT__001__M__3": "İzinsiz girenler! Herkes benimle!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Sen! Gel buraya!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Kaçmaya kalkma, seni serseri!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Sen oradaki! Dur!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Sonsuza dek tıkalı kaldığımı sanma, peşine düşeceğim!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "İşimiz daha bitmedi, sana ulaşacağım.",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "İşimiz daha bitmedi, sizi yakalayacağım serseriler!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Daha bitmedi, peşindeyim!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Bu kadar kolay pes etmem, bir şekilde yakalayacağım seni.",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Şimdi tıkalı olabilirim ama arkanı kolla!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_DYING__001__M__1": "Biri öldürüldü! Dikkat!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_DYING__001__M__2": "Kahretsin! Biri gitti!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_DYING__001__M__3": "Siktir! Öldü!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Yanmaya hazır mısın?!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Orada kim varsa kül edeceğim!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "Çıksan iyi edersin! Orası çok ısınacak!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "İşte! Davetsiz misafirler var!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Benimle! Durdurun davetsiz misafirleri!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Burada bulunmamaları gerekiyor! Yakalayın onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılın ve yakalayın o serserileri!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Yayılın! Bölgeyi kapatın!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Harekete geçin! Kuşatalım onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Buradan canlı çıkamayacaksın!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Şansın olduğunu mu sanıyorsun?!",
"VO__SOLDIER_S1__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Hayatın için yalvarmaya başlasan iyi edersin!",
"VO__SOLDIER_S1__GENERIC__PATROL__BURNING__001__M__1": "Ateş mi? Bu nasıl bir şeytan işi?",
"VO__SOLDIER_S1__GENERIC__PATROL__BURNING__001__M__2": "Alevler mi? Neler oluyor?",
"VO__SOLDIER_S1__GENERIC__PATROL__BURNING__001__M__3": "Bir şey yanıyor!",
"VO__SOLDIER_S1__GENERIC__PATROL__CAPTURE__001__M__1": "Olacağı buydu.",
"VO__SOLDIER_S1__GENERIC__PATROL__CAPTURE__001__M__2": "Korkma, ben asla ıskalamam.",
"VO__SOLDIER_S1__GENERIC__PATROL__CAPTURE__001__M__3": "Tanrı'yla buluşma vaktin geldi.",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE__001__M__1": "Kalk! Yapacak bir işin var.",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE__001__M__2": "Ayağa kalk! Hadi!",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE__001__M__3": "Hâlâ bizimle misin? Hey!",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Ona ne oldu?",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Yerde yatarak ne yapıyor?",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Hey! Şekerleme vakti değil!",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Aman Tanrım... Eti erimiş...",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Kim olursan ol... huzur içinde yat.",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Aman! Cehennem gibi... Midem bulanacak...",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Aman! Öyle yenmeyi bir düşün!...",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Hı... Sıçanları üstünden atamamış... Zavallı serseri.",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Hı... Umarım çabuk ölmüştür...",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Biri bizimkilerden birini öldürmüş! Dikkat!",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Saldırı altındayız! Bulun davetsiz misafirleri!",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Adamlarımızdan biri öldürülmüş! Bölgeyi arayın!",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Öldü! Katili yakalayacağım!",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Cesedi hâlâ taze... Bunun bedelini ödeyeceksin, serseri!",
"VO__SOLDIER_S1__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Öldürülmüş! Suçluyu yakalayacağım!",
"VO__SOLDIER_S1__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Daha fazlasını mı istiyorsun?!",
"VO__SOLDIER_S1__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Sana daha çok şey var!",
"VO__SOLDIER_S1__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Daha işim bitmedi!",
"VO__SOLDIER_S1__GENERIC__PATROL__DYING__001__M__1": "Neler oluyor be?!",
"VO__SOLDIER_S1__GENERIC__PATROL__DYING__001__M__2": "Hayır! Olamaz!",
"VO__SOLDIER_S1__GENERIC__PATROL__DYING__001__M__3": "Hayır! Ne oldu?!",
"VO__SOLDIER_S1__GENERIC__PATROL__FLEE_RATS__001__M__1": "Rahat bırakın beni!",
"VO__SOLDIER_S1__GENERIC__PATROL__FLEE_RATS__001__M__2": "Geri çekilin! Geri çekilin!",
"VO__SOLDIER_S1__GENERIC__PATROL__FLEE_RATS__001__M__3": "Defolun başımdan!",
"VO__SOLDIER_S1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Ucu ucuna kurtuldum!",
"VO__SOLDIER_S1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Evet! Başardım!",
"VO__SOLDIER_S1__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "Bu... Başardım...",
"VO__SOLDIER_S1__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Saldırıya uğradım! Bulun şu serserileri!",
"VO__SOLDIER_S1__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Biri beni hedef alıyor! Bölgeyi arayın!",
"VO__SOLDIER_S1__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Saldırı altındayız! Yardım edin!",
"VO__SOLDIER_S1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Beni öldürmeye mi çalışıyorsun?! Hadi o zaman!",
"VO__SOLDIER_S1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Seni ödlek! Yakalayacağım seni!",
"VO__SOLDIER_S1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Bunun bedelini ödeteceğim sana!",
"VO__SOLDIER_S1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Hey! İyi misin?",
"VO__SOLDIER_S1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Hâlâ orada mısın?",
"VO__SOLDIER_S1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Hey, her şey yolunda mı?",
"VO__SOLDIER_S1__GENERIC__PATROL__OIL__001__M__1": "Bu da ne? Sanki... katran mı?",
"VO__SOLDIER_S1__GENERIC__PATROL__OIL__001__M__2": "Her yer katran... Ne oluyor be...",
"VO__SOLDIER_S1__GENERIC__PATROL__OIL__001__M__3": "Kim döktü bunu?",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION__001__M__1": "O muydu...?",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION__001__M__2": "Hı?",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION__001__M__3": "Bir saniye...",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION_RATS__001__M__1": "Beni yemek mi istiyorsunuz? Daha çok uğraşın!",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION_RATS__001__M__2": "İstediğiniz kadar uğraşın, beni yakalayamazsınız!",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION_RATS__001__M__3": "Acımasızsınız, tamam... ama beni yakalamaya yetmez!",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Bu yol kapalı, lanet sıçanlar.",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "Ah! Peki, sanırım geçmeme izin vermeyeceksiniz...",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Geçmek imkânsız, kahretsin!",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "Şimdi ne yapacağım...",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "Geçmeme izin verme ihtimaliniz var mı? Beni mıncıklamadan?",
"VO__SOLDIER_S1__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Şimdi resmen yandım...",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME__001__M__1": "Bunu unutalım gitsin...",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME__001__M__2": "Aklımı kaçırıyorum...",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME__001__M__3": "Boş ver...",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Yine bir şey yok...",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Yine hiçbir şey bulamıyorum.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Temiz... Yine yanlış alarm...",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Hı. Ben olmalıyım. Yine bir şey yok.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Hâlâ bir şey yok. Aklımı kaçırıyor olmalıyım.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Hayal görüyorum.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_RATS__001__M__1": "Pis canavarlar.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_RATS__001__M__2": "İğrenç! Sizi lanet sıçanlar!",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_RATS__001__M__3": "Aptal sıçanlar.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Yanlış alarm. Burada bir şey yok.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Bölge temiz.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Kimseyi bulamıyorum.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Sanırım bir şey yokmuş...",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Hı... Rapor edecek bir şey yok...",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Yanılmışım... Güzel.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Ne diyordum? Ah, geliyor aklıma!",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Eee, nerede kalmıştık? Ah evet!",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Neyse, nerede kalmıştık? Ah! Doğru!",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Böylesi daha iyi.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Böyle olması daha iyi.",
"VO__SOLDIER_S1__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Şikâyet etmem.",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH__001__M__1": "Göremiyorum onları! Her yere bakın!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH__001__M__2": "Uzağa gitmiş olamazlar! Bulun onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH__001__M__3": "Nereye gittiler?! Gözünüzü dört açın!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Seni bulmama izin verme!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Uzağa gitmiş olamazsınız! Gösterin kendinizi!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "İstediğin kadar saklan! Kaçamayacaksın!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Bana güven!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Tamam!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Anlaşıldı!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Artık seni nerede bulacağımı biliyorum...",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Orada mı saklanıyoruz?",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "O taraftan! Biliyordum!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Buradalar! Görüyorum onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "İşte! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Buraya! İşleri bitti!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "İşin bitti!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Sonunda buldum seni!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Bak ne buldum!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Etrafta davetsiz misafirler var! Bulun onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Yardımına ihtiyacım var! Etrafta dolaşan izinsiz girenler var!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Hey, bölgeyi arayın! Davetsiz misafirler var!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Hemen!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Yakalayalım o serserileri!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Kaçamayacaklar!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Bunu onlar yaptı! Eminim!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Onlar olmalı!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Onlardır bu!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Göremiyorum onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Kaçırdım onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Kaçtılar!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Oraya siper alıyorlar! Kökünü kazıyalım!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Onun arkasına siper alıyorlar!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Oraya saklandıklarını gördüm! Yakalayın onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Orada arkada olduğunu bilmediğimi mi sanıyorsun?!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Beni kandırabileceğini mi sanıyorsun? Orada arkada olduğunu biliyorum!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Onun arkasına saklanmanın anlamı yok!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı indiler! Takip edeceğim onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı atladılar! Ben hallederim!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Onları yakalamak için aşağı iniyorum!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağı indiğini gördüm!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "İstediğin kadar aşağıda saklan! Yine de bulacağım seni!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Aşağıda olduğunu biliyorum! Çabuk saklansan iyi edersin!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "Çimende kayboldular! Peşlerinden gidiyorum!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Orada çimene girdiler!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "O çimendeler!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Çimende mi saklanıyorsun? Akıllıca bir karar değil.",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "O çimen seni saklamaz! Geliyorum!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Çık o çimenden!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altına girdiler! Takip edeceğim onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altında saklanıyorlar! Ben hallederim!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Arkamı kolla, onları oradan çıkaracağım!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Oranın altına girdiğini gördüm!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "İstediğin kadar oranın altına saklan! Yine de bulacağım seni!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Oranın altında olduğunu biliyorum!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Yukarı çıktılar! Takip edin onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "Yukarı tırmandılar! Hallet şunu!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Yukarıdalar! Yakalayalım onları!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarı çıktığını gördüm!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "İstediğin kadar yukarıda saklan! Yine de bulacağım seni!",
"VO__SOLDIER_S1__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Yukarıda olduğunu biliyorum! Çabuk saklansan iyi edersin!",
"VO__SOLDIER_S1__GENERIC__PATROL__SMOKE__001__M__1": "Duman mı? Şuna bakmam lazım.",
"VO__SOLDIER_S1__GENERIC__PATROL__SMOKE__001__M__2": "Bu kadar dumanı çıkaran ne?",
"VO__SOLDIER_S1__GENERIC__PATROL__SMOKE__001__M__3": "Duman mı? Burada mı? Neler olduğuna baksam iyi olur...",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Yine mi? Bir daha bakacağım!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine o şey... Gidip bakacağım!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "İşte yine başladı!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine mi?! Ne oluyor be?!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "İkinci kez kanmam buna.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Umarım bu sefer boşuna olmaz!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Arkamı kolla.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Bir bakacağım.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Gidip bakacağım.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Bir şey duyduğuma eminim. Bakacağım...",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "Sanırım bir şey duydum! Şu taraftan geldi!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Duydun mu şunu?! Bakacağım!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "O sesin nesi var?",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "O ses... Tuhaf...",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Bu duyduğum da ne?",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "Şu ateşe tuhaf bir şey oldu! Bir bakacağım!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "O ateş büyülenmiş! Emin olacağım!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Kara büyü olabilir! Geri durun, ben hallederim!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "O ateş büyülenmiş mi ne?",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "O ateşe bakmam lazım...",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Ateş... nesi var bunun?!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Kim sapan kullanıyor? Hemen dönerim.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Bahse girerim o bir sapandı! Emin olacağım.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "O çatırtıyı duydun mu? Bekle beni, gidiyorum.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Ha? Bunu kim yapıyor... Çat!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "Sapan sesine benziyordu?!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "O çatırtı sesi... Ben bakmazsam kimse bakmaz...",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Şüpheli görünüyordu... Şuna bir bakacağım.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Orada bir hareket var. Gidip bakacağım.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Bir şey gördüğüme eminim... Bir bakacağım.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "O da ne?!",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Burada biri mi var? Şuna bakacağım...",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Gölge miydi yoksa... Hayır, bir bakacağım.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Kör noktaları kontrol etmeyi unutma.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Gözüm üstünde olacak.",
"VO__SOLDIER_S1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Beni haberdar et.",
"VO__SOLDIER_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Eh, burada değiller...",
"VO__SOLDIER_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Uzağa gitmiş olamazlar...",
"VO__SOLDIER_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Başka yere bakmaya başlasam iyi olur...",
"VO__SOLDIER_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Burada hiçbir şey bulamıyorum...",
"VO__SOLDIER_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Burada hayaletlerden başka bir şey yok...",
"VO__SOLDIER_S1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Burası temiz.",
"VO__SOLDIER_S1__GENERIC__STATIC__ALERT_ALONE__001__M__1": "Kıpırdama, duydun mu?!",
"VO__SOLDIER_S1__GENERIC__STATIC__ALERT_ALONE__001__M__2": "Sen! Olduğun yerde kal!",
"VO__SOLDIER_S1__GENERIC__STATIC__ALERT_ALONE__001__M__3": "Buraya kadar gelebilirsin!",
"VO__SOLDIER_S1__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__1": "Bana bir daha vuramayacaksın, söz veriyorum!",
"VO__SOLDIER_S1__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__2": "Bir fırsat daha bulamadan durduracağım seni!",
"VO__SOLDIER_S1__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__3": "Kim yaptı bunu?!",
"VO__SOLDIER_S1__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__1": "Az önceki gibi bir şey yok... Boş ver.",
"VO__SOLDIER_S1__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__2": "Yine bir şey yokmuş.",
"VO__SOLDIER_S1__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__3": "Hâlâ bir şey yok...",
"VO__SOLDIER_S1__GENERIC__STATIC__RESUME_SPOTTER__001__M__1": "Görünürde kimse yok.",
"VO__SOLDIER_S1__GENERIC__STATIC__RESUME_SPOTTER__001__M__2": "Kimseyi göremiyorum.",
"VO__SOLDIER_S1__GENERIC__STATIC__RESUME_SPOTTER__001__M__3": "Temiz görünüyor.",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_ALONE__001__M__1": "Nereye kaçtın? Gösterin kendinizi!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_ALONE__001__M__2": "Seni görmeme izin verme!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_ALONE__001__M__3": "Başını çıkar! Bak bakalım ne oluyor!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_FOUND__001__M__1": "Yakaladım onları! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_FOUND__001__M__2": "Görüyorum onları! Gelin buraya!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_FOUND__001__M__3": "Buraya! Durdurun onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER__001__M__1": "Artık göremiyorum onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER__001__M__2": "Gözden kaybettim onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER__001__M__3": "Uzağa gitmiş olamazlar!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__1": "Orada arkaya sığındılar! Yakalayalım onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__2": "Oraya siper aldıklarını gördüm! Peşlerinden gidin!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__3": "Tam onun arkasındalar! Kuşatalım onları.",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Orada arkada mı saklanıyorsun?! Ödlekler!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Siper almaya mı çalışıyorsun?!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Orada arkada iyi saklansan iyi edersin! Geliyorum!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağıda bir yerdeler! Bulun onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı atladılar! Takip edin onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağı kaçtılar! Yakalayın onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağıda olduğunu biliyorum! Gösterin kendinizi!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Aşağıda saklanmana gerek yok! Nerede olduğunu biliyorum!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Aşağıda mı saklanıyoruz, ha?",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__1": "Sanırım çimene girdiler! Yakalayın onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__2": "Çimene girdiler! Peşlerinden gidin!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__3": "Davetsiz misafirler çimene girdi! Çıkarın onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Bir tutam çimenin seni kurtaracağını mı sanıyorsun?!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Çimende ne kadar saklanabilirsin sanıyorsun?",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "O çimenin seni benden saklayacağını mı sanıyorsun?!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altında bir yerdeler! Yakalayın onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altında saklanıyorlar! Gidin!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__3": "Oranın altına girdiler! Yakalayın onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Oranın altında olduğunu biliyorum! Gösterin kendinizi!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Oranın altına saklanmanın boşuna olduğunu biliyorsun değil mi?!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Oranın altında mı saklanıyoruz, ha?",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__1": "Yukarıda bir yerdeler! Bulun onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__2": "Oraya tırmandılar! Takip edin onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__3": "Yukarı kaçtılar! Yakalayın onları!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarıda olduğunu biliyorum! Gösterin kendinizi!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Yukarı çıktığını gördüm! İşimiz daha bitmedi!",
"VO__SOLDIER_S1__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Yukarıda mı saklanıyoruz, ha?",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__1": "Yine ne var?! Geri dönün askerler!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__2": "Geri geldi! Bir baksan iyi edersin!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__3": "Ne ol-- Yine mi?! Bak ne olduğuna!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine mi? Ciddi misin?",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "İşte yine başladı? Bir terslik var!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Geri döndü... Nedir o?",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__1": "Bu kadar gürültüyü çıkaran ne?",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__2": "Davetsiz misafirlere benziyor! Bak ne olduğuna!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__3": "Duydun mu şunu? Git bak!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "O ses... Nedir o?",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "O ses, neler oluyor?",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Yakından geldi.",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__1": "O ateş normal değil! Çabuk git bak!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__2": "Şu ateşi kontrol et, tuhaf bir şey oluyor!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__3": "Sen de ateşin değiştiğini gördün mü?! Git bir bak!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "O ateş... Bir tür büyücülük mü?",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Şu ateşe ne oluyor?!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "Ateş neden öyle yapıyor?",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__1": "Orada bir şey gördüm.",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__2": "Sanırım orada bir şey gördüm.",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__3": "O tarafta bir şey kımıldadı.",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__1": "Orada bir tuhaflık var...",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__2": "Kımıldayan bir şey mi yoksa...",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__3": "Orada bir şey kımıldadı! Eminim!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__1": "Onun arkasında bir şey gördüm!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__2": "Orada arkada bir şey mi var?",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__3": "Ha?! Tam onun arkasında bir hareket gördüm!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__1": "Aşağıda neler oluyor?!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__2": "Aşağıda az önce bir şey kımıldadı!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__3": "Az önce aşağıda bir hareket vardı!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__1": "Az önce çimende bir hareket gördüm!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__2": "Çimende bir şey var!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__3": "Gördün mü?! Çimen az önce kımıldadı!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__1": "Orada bir şey gördüm!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__2": "Az önce bir şey kımıldadı! Orada!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__3": "Ne oluyor lan?! Orada bir hareket gördüm!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__1": "Yukarıda neler oluyor?!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__2": "Yukarıda az önce bir şey kımıldadı!",
"VO__SOLDIER_S1__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__3": "Az önce yukarıda bir hareket vardı!",
"VO__SOLDIER_S2__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Biri benimle uğraşıyor, gidin bulun onları!",
"VO__SOLDIER_S2__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Biri yine mi oyun oynuyor ne? Yakalayın onları!",
"VO__SOLDIER_S2__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Bizi aptal yerine koyuyorlar, durdurun onları artık!",
"VO__SOLDIER_S2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Senden bıktım! Yakında yakalayacağım seni!",
"VO__SOLDIER_S2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Benimle uğraşıp duruyorsun! Göreceksin neler olacağını!",
"VO__SOLDIER_S2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Bu sefer işini kolaylaştırmayacağım!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT__001__M__1": "İzinsiz girenler! Buraya!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT__001__M__2": "Gelin buraya, davetsiz misafirler!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT__001__M__3": "Herkes buraya! Davetsiz misafirler!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Hiçbir yere gitmiyorsun!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Dur orada!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Sen! Dur orada!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Hep tıkalı kalacağımı mı sanıyorsun, ödlekler?",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "Henüz pes etmiyorum! Yakında peşinizde olacağım!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Bu kadar kolay yenilgiyi kabul etmem! Sana ulaşacağım!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Seni durdurmanın bir yolunu bulacağım! An meselesi...",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Nerede tıkıldığımı mı sanıyorsun? Göreceğiz!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Seni küçük— Yine de yakalayacağım seni!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_DYING__001__M__1": "Öldürüldü! Kahretsin!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_DYING__001__M__2": "Aman! Hayır! Öldürüldü!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_DYING__001__M__3": "Siktir! Öldü!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_IGNITE__001__M__1": "Seni çimenle birlikte yakalım!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_IGNITE__001__M__2": "Çimen yanar, sen de onunla... Gör bak!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_IGNITE__001__M__3": "Çık dışarı, yoksa cehennemde yan.",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Davetsiz misafirler! Kımıldayın!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Benimle! İzinsiz girenler var!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Yakalamama yardım edin!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılın! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Ayrılın! Yakında olmalılar!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Her yeri arayın! Bulun davetsiz misafirleri!",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Hayal kırıklığı olacağını biliyordum.",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Yeterince iyi değilsin...",
"VO__SOLDIER_S2__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Ölmeye hazırlan...",
"VO__SOLDIER_S2__GENERIC__PATROL__BURNING__001__M__1": "Alevler mi? Burada ne oldu?",
"VO__SOLDIER_S2__GENERIC__PATROL__BURNING__001__M__2": "Ateş! İmkânsız!",
"VO__SOLDIER_S2__GENERIC__PATROL__BURNING__001__M__3": "Yanıyor! Bu nasıl olur?",
"VO__SOLDIER_S2__GENERIC__PATROL__CAPTURE__001__M__1": "Görünüşe göre senin için işin sonu bu.",
"VO__SOLDIER_S2__GENERIC__PATROL__CAPTURE__001__M__2": "Kıpırdama! Birazdan biter.",
"VO__SOLDIER_S2__GENERIC__PATROL__CAPTURE__001__M__3": "Duanı et.",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE__001__M__1": "Senin neyin var?! Hey!",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE__001__M__2": "Hâlâ nefes alıyor musun?! Hey!",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE__001__M__3": "Ayağa kalk. Hey!",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_AFAR__001__M__1": "Uyuyor mu yoksa...",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_AFAR__001__M__2": "Hey! Her şey yolunda mı?",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_AFAR__001__M__3": "Kim o?",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_CALCINED__001__M__1": "Kavrulmuş bir ceset bu!",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_CALCINED__001__M__2": "Çıtır çıtır yanmış...",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_CALCINED__001__M__3": "Ateş hakladı onu!",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_RATS__001__M__1": "Derisi kalmamış...",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_RATS__001__M__2": "Lanet kemirgenler...",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_RATS__001__M__3": "Yutulmuş...",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_SEARCH__001__M__1": "Biri öldürülmüş! Gözünüzü açın!",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_SEARCH__001__M__2": "Ortalıkta bir katil var! Bulun onları!",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_SEARCH__001__M__3": "Öldü! Bunun arkasındaki kimse bulun!",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__1": "Öldü! Bunun yanlarına kalmasına izin vermeyeceğim.",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__2": "Öldürülmüş, katili durdurmalıyım!",
"VO__SOLDIER_S2__GENERIC__PATROL__CORPSE_SEARCH_ALONE__001__M__3": "Ölü mü? Nerede o katil?!",
"VO__SOLDIER_S2__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Görünüşe göre vaktin doldu.",
"VO__SOLDIER_S2__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Senin için bitti!",
"VO__SOLDIER_S2__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Daha iyisini yapabilirsin!",
"VO__SOLDIER_S2__GENERIC__PATROL__DYING__001__M__1": "Aman Tanrım!",
"VO__SOLDIER_S2__GENERIC__PATROL__DYING__001__M__2": "Aman...",
"VO__SOLDIER_S2__GENERIC__PATROL__DYING__001__M__3": "Olamaz!",
"VO__SOLDIER_S2__GENERIC__PATROL__FLEE_RATS__001__M__1": "Sakın...",
"VO__SOLDIER_S2__GENERIC__PATROL__FLEE_RATS__001__M__2": "Çekilin yolumdan!",
"VO__SOLDIER_S2__GENERIC__PATROL__FLEE_RATS__001__M__3": "Defolun yolumdan!",
"VO__SOLDIER_S2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__1": "Kalbim patlayacak gibi...",
"VO__SOLDIER_S2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__2": "Evet! Başardım!",
"VO__SOLDIER_S2__GENERIC__PATROL__FLEE_RATS_ESCAPE__001__M__3": "Neredeyse... yakalıyordun beni...",
"VO__SOLDIER_S2__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Biri beni hedef alıyor! Bulun onları!",
"VO__SOLDIER_S2__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Hedef alınıyoruz! Bulun davetsiz misafirleri!",
"VO__SOLDIER_S2__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Buraya! Saldırıya uğradım!",
"VO__SOLDIER_S2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Kim yaptı bunu?! Göster kendini!",
"VO__SOLDIER_S2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Bana ateş etme! Pestilini çıkaracağım!",
"VO__SOLDIER_S2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Bunu yaptığına pişman olacaksın!",
"VO__SOLDIER_S2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "İyi misin?!",
"VO__SOLDIER_S2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Hey, hâlâ orada mısın?",
"VO__SOLDIER_S2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Hey, hâlâ orada mısın?",
"VO__SOLDIER_S2__GENERIC__PATROL__OIL__001__M__1": "Bu katran buraya nasıl gelmiş...?",
"VO__SOLDIER_S2__GENERIC__PATROL__OIL__001__M__2": "Bu katran mı?",
"VO__SOLDIER_S2__GENERIC__PATROL__OIL__001__M__3": "Her yer katran...",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION__001__M__1": "Ha?",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION__001__M__2": "Dur...",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION__001__M__3": "O da neydi lan?",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION_RATS__001__M__1": "Hâlâ beni yakalayabileceğinizi mi sanıyorsunuz?!",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION_RATS__001__M__2": "Bugün beni yakalayamayacaksınız!",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION_RATS__001__M__3": "Sizi mutlu ediyorsa cıyaklamaya devam edin.",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__1": "Görünüşe göre ancak buraya kadar gidebiliyorum...",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__2": "Onların yanından nasıl geçeceğim...",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__3": "Sadece o tarafa gitmeye çalışıyorum.",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__4": "Şimdi resmen yandım...",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__5": "O tarafa gidebilecek gibi görünmüyorum...",
"VO__SOLDIER_S2__GENERIC__PATROL__REACTION_RATS_BLOCKED__001__M__6": "Şimdi ne yapacağım...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME__001__M__1": "Tuhaf...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME__001__M__2": "Paranoyaklaşıyorum...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME__001__M__3": "Dağılıyorum...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Yok, hâlâ bir şey yok...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Her şey yolunda, bir şey yokmuş... yine...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Yine bir şey yok...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Bilmeliydim... Hâlâ temiz.",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Etrafta bir şey yok... az önceki gibi.",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Hâlâ bir şey yok.",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_RATS__001__M__1": "İğrenç yaratıklar...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_RATS__001__M__2": "Haşarat...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_RATS__001__M__3": "O lanet sıçanlar, yemin ederim...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Bana iyi görünüyor.",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Meğer bir şey yokmuş.",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Rapor edecek bir şey yok.",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Sanırım hayal görüyorum...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Hiçbir şey yok...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Hepsi kafamdaymış...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Neyse, nerede kalmıştık? Ha doğru!",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Bir şey söyleyecektim... Ah, hatırladım!",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Nerede kalmıştık? Ah, geliyor aklıma!",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Nöbet görevine geri dönelim.",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Eh, bunu geride bırakalım...",
"VO__SOLDIER_S2__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "İşimize dönelim.",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH__001__M__1": "Bulamıyorum onları! Bölgeyi arayın!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH__001__M__2": "Gittiler! Gözünüzü dört açın!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH__001__M__3": "Nereye gittiler?! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Buralarda bir yerde olduğunu biliyorum! Gösterin kendinizi!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Saklanıyoruz, ha? Kaçabileceğini sanma!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Uzağa gitmiş olamazsın! Yine de bulacağım seni!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Hemen!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Bana bırak!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Derhal!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Buralarda bir yerde olduğunu biliyorum!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Burada olduğunu biliyorum!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Kendinizi ele verdiniz, sizi aptallar...",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "İşte! Görüyorum onları!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "İşte oradalar! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "İşte! Durdurun onları!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Senin için bitti.",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Sonunda!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Yakaladım seni!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Misafirimiz var! Bulun onları!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Biri etrafta dolaşıyor! Her köşeyi arayın!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Bölgede davetsiz misafirler var! Tetikte olun!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Elbette!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Hadi yapalım!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Emredersin!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Tüm bunların arkasında onlar var, eminim!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Onlar! Bunu onlar yaptı!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Kahretsin! Onlar olduğuna eminim!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Hâlâ buralarda olmalılar!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Uzakta olamazlar!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Yakında olmalılar! Aramaya devam edin.",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Onun arkasına siper aldılar! Ben gidiyorum!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Buraya siper aldıklarını gördüm! Peşlerindeyim!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Onun arkasına sığındılar! Benimle!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Orada arkada saklandığını görmedim mi sanıyorsun?!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Seni orada arkada görüyorum! Çık hemen!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Orada arkada saklanabilirsin ama yine de bulacağım seni!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı indiler! Yakalayacağım onları!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı atladılar! Peşlerinden gideceğim!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN__001__M__3": "Davetsiz misafirler aşağı atladı! Takip ediyorum onları!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Aşağıya, peşinden geliyorum!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Benden bu kadar kolay kurtulacağını sanma! Aşağı iniyorum!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Aşağıda saklanamayacaksın! Bulacağım seni!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "O çimenin bir yerindeler!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Uzun süre saklı kalamayacaksın!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "O çimenin bir yerindeler! Gözünüzü açık tutun!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Çimene saklanma! İşi çok kolaylaştırıyorsun!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "O çimen seni uzun süre saklamaz!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "O çimen kaçmana yardım etmeyecek!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altına girdiler! Yakalayacağım onları!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__2": "Oranın altında saklanıyorlar! Peşlerinden gideceğim!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE__001__M__3": "Oranın altına girdiklerini gördüm! Ben hallederim!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Seni oradan çıkaracağım!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Benden bu kadar kolay kurtulamayacaksın!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Oranın altına saklanmana gerek yok. Seni gördüm!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__1": "Yukarı çıktılar! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__2": "Yukarı tırmandılar! Peşlerinden gidin!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP__001__M__3": "Davetsiz misafirler oraya tırmandı! Takip edin onları!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Yukarıya, peşinden geliyorum!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Yukarıda saklanmanın iyi bir fikir olduğunu mu sanıyorsun?! Geliyorum!",
"VO__SOLDIER_S2__GENERIC__PATROL__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Yukarıda saklanamayacaksın! Bulacağım seni!",
"VO__SOLDIER_S2__GENERIC__PATROL__SMOKE__001__M__1": "Burada biraz duman var... Neler oluyor?",
"VO__SOLDIER_S2__GENERIC__PATROL__SMOKE__001__M__2": "Ateş olmayan yerden duman çıkmaz. Emin olsam iyi olur...",
"VO__SOLDIER_S2__GENERIC__PATROL__SMOKE__001__M__3": "O duman da ne? Nasıl olur?",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Üst üste iki kez mi? Bir terslik var...",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine mi?! Bakmam lazım...",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "İki kez mi?! Gidip bakacağım...",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine mi? Yemin ederim eli boş dönmeyeceğim...",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "İki kez... Bir kez ve sonsuza dek emin olalım...",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Yine bakacağım, iki kez normal değil.",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__1": "Gidiyorum.",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__2": "Yoldayım.",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_ANSWER__001__M__3": "Ben ilgilenirim.",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Sen de duydun, değil mi? Gidip bakacağım!",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "Ha?! O ses de neydi lan...",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Bir şey duydum! Hallediyorum!",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "O ses neydi?",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Bu ses de ne?",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Sanırım şu taraftan geldi...",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__1": "Bu bir tür büyücülük! Gidip bakacağım!",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__2": "Büyücülük olmalı! Daha yakından bakacağım!",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER__001__M__3": "Geri durun! Kara büyü olabilir!",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "Ateşe ne oluyor?!",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Şu ateşin nesi var lan?!",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "O ateş ele geçirilmiş!",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "O bir sapandı! Sanırım şu taraftan geldi...",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Hangi serseri sapan kullanıyor?! Gidip bakacağım!",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "O çatırtı alışılmadık geldi...",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Biri sapan mı kullanıyor?",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "O ses... Nereden geldi...?",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "O çatırtı... Şu taraftan geldi...",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Gördün mü şunu? Bir baksam iyi olur!",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Bana mı öyle geldi yoksa orada bir şey mi kımıldadı? Bakayım.",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Orada az önce ne kımıldadı lan? Gidip bakacağım.",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Orada az önce bir şey mi kımıldadı...?",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Bir şey kımıldadı... Baksam iyi olur.",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Neydi o, baksam iyi olur...",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Kendine dikkat et.",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Sakın öldürülme.",
"VO__SOLDIER_S2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Bu sefer bir şey bul!",
"VO__SOLDIER_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Burada aramanın anlamı yok...",
"VO__SOLDIER_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Şuraya baksam iyi olur...",
"VO__SOLDIER_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Bu bölge güvenli...",
"VO__SOLDIER_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Başka bir yerde olmalılar...",
"VO__SOLDIER_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Başka bir bölgeyi tarasam iyi olur...",
"VO__SOLDIER_S2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Başka bir yere baksam iyi olur...",
"VO__SOLDIER_S2__GENERIC__STATIC__ALERT_ALONE__001__M__1": "Sen! Olduğun yerde kal!",
"VO__SOLDIER_S2__GENERIC__STATIC__ALERT_ALONE__001__M__2": "Kıpırdama!",
"VO__SOLDIER_S2__GENERIC__STATIC__ALERT_ALONE__001__M__3": "Kimsin sen? Gel buraya!",
"VO__SOLDIER_S2__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__1": "Buna pişman olacaksın!",
"VO__SOLDIER_S2__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__2": "Buna pişman olacaksın!",
"VO__SOLDIER_S2__GENERIC__STATIC__HIT_SEARCH_ALONE__001__M__3": "Bunu bir daha denemene izin vermeyeceğim! Seni bulduğumuzda...",
"VO__SOLDIER_S2__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__1": "Hâlâ bir şey yok...",
"VO__SOLDIER_S2__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__2": "Bölge temiz, yine yanılmış olmalıyım.",
"VO__SOLDIER_S2__GENERIC__STATIC__RESUME_AGAIN_SPOTTER__001__M__3": "Yine bir şey yok... Stres beni etkiliyor olmalı...",
"VO__SOLDIER_S2__GENERIC__STATIC__RESUME_SPOTTER__001__M__1": "Her şey temiz görünüyor.",
"VO__SOLDIER_S2__GENERIC__STATIC__RESUME_SPOTTER__001__M__2": "Kimseyi göremiyorum.",
"VO__SOLDIER_S2__GENERIC__STATIC__RESUME_SPOTTER__001__M__3": "Bana normal görünüyor.",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_ALONE__001__M__1": "Sadece ödlekler saklanır!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_ALONE__001__M__2": "Nerede olduğunu bilmediğimi mi sanıyorsun?!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_ALONE__001__M__3": "Hâlâ buralarda bir yerde olduğunu biliyorum!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_FOUND__001__M__1": "İşte! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_FOUND__001__M__2": "Orada! Acele edin!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_FOUND__001__M__3": "İşte oradalar! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER__001__M__1": "Göremiyorum onları!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER__001__M__2": "Kaçırdım onları ama kesinlikle buradalar!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER__001__M__3": "Buralardalar... Aramaya devam edelim!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__1": "Tam onun arkasında! Onları kaçırmazsınız!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__2": "Orada arkada sinmeye çalışıyorlar! Ne yapacağını biliyorsun!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER__001__M__3": "Davetsiz misafirlerin onun arkasına siper aldığını gördüm! Acele edin!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Orada arkada olduğunu biliyorum!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Nerede olduğunu bilmediğimi gerçekten mi sanıyorsun?",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Onun arkasına saklanıyorsun, fark etmedim mi sandın?",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__1": "Aşağı atladılar! Acele edin!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__2": "Aşağı takip edin onları!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN__001__M__3": "Aşağı inin ve bulun onları!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__1": "Geri çık buraya! Nerede olduğunu biliyorum!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__2": "Aşağı indiğini gördüm!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_DOWN_ALONE__001__M__3": "Aşağıda kaçamayacaksın!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__1": "Çimene girdiler! Kaçmalarına izin vermeyin!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__2": "Çimende kayboldular! Acele edin!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS__001__M__3": "Sanırım o çimende saklanıyorlar! Bulun onları!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "O çimene saklanmak yapacağın son hata olacak.",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Ha?! O çimende saklanmanın ne anlamı var?",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Başını o çimenden çıkar! Bize bir şans ver!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__1": "Oranın altına girdiler! Acele edin!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__2": "Ben burada nöbet tutarım, siz onları oradan çıkarın!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE__001__M__3": "Gidin onları oranın altından çıkarın!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Çık oranın altından! Hemen!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Oranın altına girdiğini gördüm!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Seni oranın altında göremiyorum mu sanıyorsun?!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__1": "Yukarı çıktılar! Acele edin!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__2": "Ben burada nöbet tutarım, siz onları yukarı takip edin!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP__001__M__3": "Yukarı çıkın ve bulun onları!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__1": "Geri in buraya! Nerede olduğunu biliyorum!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__2": "Yukarı çıktığını gördüm!",
"VO__SOLDIER_S2__GENERIC__STATIC__SEARCH_SPOTTER_UP_ALONE__001__M__3": "Yukarıda kaçamayacaksın!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__1": "Tekrar bak! Normal değil.",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__2": "Geri dön ve tekrar bak! Bir şey olmalı.",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER__001__M__3": "Tekrar bak! Bir sebebi olmalı...",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine mi?! Tamam -- bakalım neler oluyor.",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "İki kez olması normal olamayacak kadar tuhaf.",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "İki kez olması bir terslik olduğu anlamına gelir.",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__1": "O ses şu taraftan geldi! Gidip baksan iyi olur!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__2": "Kesinlikle bir şey duydum! Git araştır!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER__001__M__3": "Sen de duydun mu?! Git öğren!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu sesi çıkaran ne?",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Bu da ne? O ses?",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Bir şey mi duydum?",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__1": "Şu ateşte bir terslik var! Git bir bak!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__2": "Şu ateşte bir terslik var! Git bir bak!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER__001__M__3": "Bu ışık tuhaf davranıyor. Hemen git bak!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__1": "O ateş... normal değil.",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__2": "Şu ateşin nesi var bilmiyorum.",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_LIGHT_SPOTTER_ALONE__001__M__3": "O ateş... Büyücülük olmalı!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__1": "Yemin ederim bir şey gördüm. Bakalım.",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__2": "Buraya! Bu tarafı kontrol et!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER__001__M__3": "Sen de gördün mü?",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__1": "Bu... Bu biri mi...?",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__2": "O şekil... Biri miydi...?",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_ALONE__001__M__3": "Hey! Dışarıda kim kımıldıyor?!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__1": "Onun arkasında bir hareket... Git bir bak...",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__2": "Onun arkasında bir şey kımıldadı!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_COVER__001__M__3": "Orada arkada! Sanırım biri saklanıyor!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__1": "Aşağıda bir şey var!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__2": "Aşağıda kımıldayan bir şey var!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_DOWN__001__M__3": "Az önce aşağıda bir hareket gördüm!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__1": "Hareket! İşte! Çimende!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__2": "Çimende bir şey var!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_GRASS__001__M__3": "Ne ol-- Çimende bir şey kımıldadı!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__1": "Sanırım orada bir şey gördüm!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__2": "Orada bir şey kımıldadı!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_INSIDE__001__M__3": "Gördün mü şunu? Orada bir hareket vardı!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__1": "Yukarıda bir şey var!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__2": "Yukarıda kımıldayan bir şey var!",
"VO__SOLDIER_S2__GENERIC__STATIC__SUSPICION_SPOTTER_UP__001__M__3": "Az önce yukarıda bir hareket gördüm!",
}
