# -*- coding: utf-8 -*-
# GS8: PEOPLE_M1 + M2 + M3 + M4 (528 replik) - halk/milis, kaba ama disiplinsiz ton
T = {
# --- PEOPLE_M1 ---
"VO__PEOPLE_M1__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Kesinlikle biri var burada! Dikkatli olun!",
"VO__PEOPLE_M1__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Biri bizimle oynuyor! Bulalım onları!",
"VO__PEOPLE_M1__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Görünüşe göre bölgede birkaç soytarı var! Arayın burayı!",
"VO__PEOPLE_M1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Biri bela arıyor besbelli, ha?",
"VO__PEOPLE_M1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Burada olduğunu biliyorum! Bu sefer yakalarım seni!",
"VO__PEOPLE_M1__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Bu sefer ellerime geçireceğim seni!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT__001__M__1": "Çabuk olun! Burada davetsizler var!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT__001__M__2": "Buraya! Gelin yakalayın onları!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT__001__M__3": "Davetsizler! Bırakmayın onları!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Sen! Dur!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Kıpırdama!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Olduğun yerde bekle!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Şurada! Kovalayın davetsizleri!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "İzinsiz giriyorlar, yakalayın onları!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Burada olmamalılar! Durdurun onları hemen!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılalım! Onlar bizim.",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Dağılın, kaçamazlar!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Ayrılın ve kuşatın onları! Çabuk!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Senin işin bitti!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Ah, demek o kadar da akıllı değilmişsin!",
"VO__PEOPLE_M1__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Üzgünüm. Bir ısırdım mı, bir daha bırakmam...",
"VO__PEOPLE_M1__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Son dersini almaya hazır mısın?!",
"VO__PEOPLE_M1__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Artık saklanamazsın.",
"VO__PEOPLE_M1__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Benimle uğraşmamalıydın!",
"VO__PEOPLE_M1__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Bana saldırıyorlar! Yardım edin!",
"VO__PEOPLE_M1__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Biri bana saldırıyor! İmdat!",
"VO__PEOPLE_M1__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Bana saldırıyorlar! Yardım edin!",
"VO__PEOPLE_M1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Bunun bedelini ödeyeceksin!",
"VO__PEOPLE_M1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Buna pişman edeceğim seni!",
"VO__PEOPLE_M1__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Acıdı lanet olsun! Bunun hesabını soracağım!",
"VO__PEOPLE_M1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Hey! Ne oldu?",
"VO__PEOPLE_M1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Hâlâ orada mısın?",
"VO__PEOPLE_M1__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Hâlâ orada mısın?",
"VO__PEOPLE_M1__GENERIC__PATROL__REACTION__001__M__1": "O muydu...?",
"VO__PEOPLE_M1__GENERIC__PATROL__REACTION__001__M__2": "Hı?",
"VO__PEOPLE_M1__GENERIC__PATROL__REACTION__001__M__3": "Bir saniye...",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME__001__M__1": "Vakit kaybı...",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME__001__M__2": "Yok be...",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME__001__M__3": "Sanırım biraz uzanmam gerek...",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Yine bir şey yok.",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "İkinci yanlış alarm! Yeter artık.",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Lanet, yine bir şey yok...",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Hâlâ bir şey bulamıyorum.",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Yine bir şey yok!",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Eh, ikinci yanlış alarm...",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Bir şey yok.",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Bir şey yok, kusura bakma!",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Şimdilik her şey temiz...",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Tamam. Bir şey yokmuş...",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "İyi ki bir şey yokmuş.",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Bir şey yok...",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Eee, ne diyordum? Ah, hatırladım!",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Nerede kalmıştık? Ha, evet!",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Her neyse, nerede kalmıştık? Ha, evet!",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Boş ver.",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "İyi bitti...",
"VO__PEOPLE_M1__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Her şey yolunda...",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH__001__M__1": "Görmüyorum onları! Arayın bölgeyi!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH__001__M__2": "Kaçtılar! Aramaya devam edin!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH__001__M__3": "Alçaklar kaçtı! Gözünüzü dört açın!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Çık ortaya! Sana zarar vermem...",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Gösterin kendinizi!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Saklanmak sana bir fayda sağlamaz!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Yakalayacağım onları, emin ol!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Buralarda olduklarına eminim!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Uzakta olamazlar!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Beni tam üstünüze getireceksiniz, ahmaklar...",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Daha tedbirli olmalısın!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Demek bu tarafa gittin...",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Davetsizler! Buraya gelin!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Davetsizler! Yakalayın onları!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Davetsizler buldum! Yakalayın onları!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Yakaladım seni!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Buldum seni!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Yakaladım seni! Nihayet!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Davetsizler var! Dikkat edin!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Davetsizleri görürseniz haber verin!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Arayın burayı, birini görürseniz söyleyin!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Tamam!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Anlaşıldı!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Olur!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Eminim bunu onlar yaptı.",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Hak ettiklerini bulacaklar...",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Bunun arkasında onlar olmalı!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Az önce buralarda gördüm onları, arayalım!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Olamaz! Hâlâ yakında olmalılar...",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Yakındalar, gelin benimle arayın onları.",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Şurada saklanıyorlar! Kaçmalarına izin veremeyiz.",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Şurada gördüm onları! Bitirelim şu işi...",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Tam şunun arkasındalar! Yakalayalım onları!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Oraya saklanmak bir hataydı, haberin olsun!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Çık şunun arkasından!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Çık şunun arkasından!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "Otların arasına! Yakalayalım onları!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Otların arasına daldılar!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Uzun otlar! Oradalar!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Hadi ama! Uzun otlar seni kurtarmaz!",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Seni o otların arasında bulamayacağımı mı sanıyorsun!?",
"VO__PEOPLE_M1__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Otlar seni koruyamaz! Çık dışarı!",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "O da ne, yine mi? Gidip baksam iyi olur.",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine mi?! Baksam iyi olur...",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "Yine olmasın! Gidip bir bakayım.",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine başladı! Ne olduğunu öğrensem iyi olur.",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Yine mi?! Tamam şuraya bir bakalım...",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Yine başladı işte!?",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Duydun mu şunu?! Ben hallederim...",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "Hiç böyle bir şey duymamıştım! Bakalım.",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Duydun mu? Şuraya bir bakalım.",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bir şey duydum... Nedir bu?!",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Burada neler oluyor? Şu sese baksam iyi olur...",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Bu gürültü de ne böyle?",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Deli miyim, yoksa bu bir kamçı mıydı? Gidip bakacağım.",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Dinle! Bu bir patlama mıydı? Bakacağım!",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "Bu çok sesliydi! Ne olduğuna bakalım.",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Bir şıklama?... şu taraftan geldi...",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "Bu bir sapan mıydı, neydi?",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "O şıklamayı çıkaran neydi?",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Şüpheli bir şey gördüm. Bekle beni.",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Bekle, şurada kıpırdayan şeye bakayım...",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Evet, sanırım orada bir şey gördüm. Gidiyorum.",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Şurada bir şey kıpırdıyor. Emin olsam iyi olur...",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Şurada kıpırdayan şeye baksam iyi olur...",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Şurada kıpırdayan şeyi göremiyorum... Yaklaşayım.",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Bir şey görürsen bağır.",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Bir şey görür görmez bağır!",
"VO__PEOPLE_M1__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Bir şey görürsen söyle, tamam mı?",
"VO__PEOPLE_M1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Burada hiçbir şey yok...",
"VO__PEOPLE_M1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Bir şey yok... Hareket etsem iyi olur.",
"VO__PEOPLE_M1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Burada kimse yok, gitsem iyi olur...",
"VO__PEOPLE_M1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Etrafta kimse yok... Gidelim.",
"VO__PEOPLE_M1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Burada rapor edecek bir şey yok...",
"VO__PEOPLE_M1__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Kimse yok... Başka yerde arayalım.",
# --- PEOPLE_M2 ---
"VO__PEOPLE_M2__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Etrafta soytarılar var. Çabucak durdursak iyi olur!",
"VO__PEOPLE_M2__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Oyun bitti! Buna hemen son verelim!",
"VO__PEOPLE_M2__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Yine başladı! Biri etrafta, arayın burayı!",
"VO__PEOPLE_M2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Biri burada! Eminim!",
"VO__PEOPLE_M2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Sizi pis hırsızlar! Geliyorum peşinizden!",
"VO__PEOPLE_M2__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Hemen ellerime geçireceğim seni! Göreceksin!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT__001__M__1": "Şurada! İzinsiz giren!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT__001__M__2": "Burada davetsizler var, yakalayın! Çabuk!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT__001__M__3": "Buraya gelin! Davetsizler buldum!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Sen, dur da bir yakala seni!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Sen! Dur!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Sen! Gel buraya!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Burada davetsizler var! Yanıma!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Şurada davetsizler var! Durdurun onları!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Yakalayın şu davetsizleri! Çabuk!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılın ve bulun onları!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Kaçmaya çalışıyorlar! Durdurun onları!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Ayrılın, kaçmalarına izin vermeyin!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Kaçamazsın, alçak!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Kapana kısıldın!",
"VO__PEOPLE_M2__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Senin işin bitti!",
"VO__PEOPLE_M2__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Dahası için hazır mısın?!",
"VO__PEOPLE_M2__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Seni bulamayız sandın, ha?!",
"VO__PEOPLE_M2__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Neden teslim olmuyorsun?",
"VO__PEOPLE_M2__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Biri bana ateş ediyor! Dikkat!",
"VO__PEOPLE_M2__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Bana saldırıyorlar! İmdat!",
"VO__PEOPLE_M2__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Biri beni öldürmeye çalışıyor! İmdat!",
"VO__PEOPLE_M2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Ateş etmeyi kes! Yemin ederim buradan canlı çıkamayacaksın!",
"VO__PEOPLE_M2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Bunu kim yaptı az önce?!",
"VO__PEOPLE_M2__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Benim de sana bir hediyem var, küçük alçak!",
"VO__PEOPLE_M2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Hey! İyi misin?",
"VO__PEOPLE_M2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Konuşmayı mı kestin? Her şey yolunda mı?",
"VO__PEOPLE_M2__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "İyi misin?",
"VO__PEOPLE_M2__GENERIC__PATROL__REACTION__001__M__1": "Ha?",
"VO__PEOPLE_M2__GENERIC__PATROL__REACTION__001__M__2": "Dur...",
"VO__PEOPLE_M2__GENERIC__PATROL__REACTION__001__M__3": "Hı?",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME__001__M__1": "Tuhaf...",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME__001__M__2": "Burada vaktimi boşa harcıyorum...",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME__001__M__3": "Her şey yolunda.",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Aynı şey... Yanlış alarm.",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Yine bir şey yok, boş ver!",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Hâlâ bir şey bulamıyorum.",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Bir yanlış alarm daha.",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Yine bir şey yok.",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Yine bir şey yokmuş.",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Burada bir şey yok.",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Bir şey yokmuş...",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Hiçbir şey göremiyorum!",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Sadece benim. Burada bir şey yok...",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Bir şey yok, tabii ki...",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Eh, bir şey yokmuş...",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Eee, ne diyordum? Ha, doğru!",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Nerede kalmıştık? Ha, evet!",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Eee, nerede kalmıştık? Ha, doğru!",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Odaklanalım.",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Devam edelim.",
"VO__PEOPLE_M2__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Normale dönelim...",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH__001__M__1": "Kaçtılar! Her köşeyi arayın!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH__001__M__2": "Uzağa gitmiş olamazlar! Her yere bakın!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH__001__M__3": "Alçaklar kaçtı! Kaçmalarına izin vermeyin!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Nereye kaçtın?!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Seni bulamayacağımı sanma!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Burada olduğunu biliyorum! Çık ortaya!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Pekâlâ.",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Anlaşıldı.",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Yakında yakalarız onları...",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Ahmaklar, artık nerede olduğunuzu biliyorum!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Artık nereye saklandığını biliyorum!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Demek oradaymışsın!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Orada! Bırakmayın onları!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Şurada! Peşlerinden!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Davetsizler orada! Yakalayın onları!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Yakaladım seni!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "İşte buradasın!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Buldum seni!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Haber yayın, biri burada!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Öylece durmayın. Davetsizler var!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Kıpırdayın! Davetsizler var!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Bana bırak!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Yakalayalım onları!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Bana güven!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Olamaz! Bunun arkasında onlar olmalı!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Onlar, hiç şüphe yok!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Yine onlar!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Buralarda bir yerdeler, biliyorum!...",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Az önce buradaydılar?!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Ah alçaklar, nereye gittiniz böyle?",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Alçakların şuraya saklandığını gördüm!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Tam şunun arkasına sığındılar. Gidiyorum!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Şuraya saklandılar! Yakalayın onları!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Şunun arkasına mı saklanıyorsun? Kötü fikir!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "O siper seni kurtarmaz!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Şunun arkasında güvende olduğunu mu sanıyorsun?",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "Uzun otların arasına girdiler! Eminim!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Otların arasına girdiler!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Şu alçaklar otların arasına girdi!",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Otların arasına mı saklanıyorsun?",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Otların seni saklayacağını mı sanıyorsun?",
"VO__PEOPLE_M2__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Birkaç ot sapı seni kurtarmaz!",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Tekrar bakalım, ne olur ne olmaz...",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Ne... yine mi... Bir bakalım!",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "Yine bir şey var... Bakalım!",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Hayır, yine olmasın... Hadi ama!",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Yine mi?!",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Şaka yapıyor olmalısın! İki kez mi?!",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "O sesin ne olduğuna gidip bakacağım.",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "Şu sese bir bakayım...",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Tuhaf bir ses bu. Gidip bakacağım!",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu tuhaf ses de ne?",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Bu garip gürültü de ne?",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "O gürültü neydi?",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Bir şıklama duydum! Gidip bakacağım...",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Bu bir kamçı gibiydi! Gidip bakacağım!",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "Şu şıklamayı duydun mu? Bir bakayım.",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "O şıklama nereden geldi?",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "Bu bir sapan mıydı?",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "Bu kulağa bir kamçı gibi geldi.",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Burada şüpheli bir şey var... Bir bakayım.",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Gördün mü şunu? Ben bakana dek burada kal.",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Orada bir şeyler oluyor... Bir dakika ver.",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Bir şey mi gördüm...? Baksam iyi olur.",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "O da neydi böyle?",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Şurada bir şey kıpırdıyor...",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "En kısa zamanda haber ver.",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Dışarıda dikkatli ol.",
"VO__PEOPLE_M2__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Neler olduğunu öğren...",
"VO__PEOPLE_M2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Burada bir şey yok...",
"VO__PEOPLE_M2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Tamam, başka yere baksam iyi olur...",
"VO__PEOPLE_M2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Bir şey yok... gitsem iyi olur.",
"VO__PEOPLE_M2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Hiçbir şey yok... gidelim.",
"VO__PEOPLE_M2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Neredeler...",
"VO__PEOPLE_M2__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Burada yeterince vakit kaybettim...",
# --- PEOPLE_M3 ---
"VO__PEOPLE_M3__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Biri bizi aptal yerine koyuyor! Bitirelim şunu!",
"VO__PEOPLE_M3__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Biri burada benimle oynuyor! Arayın burayı!",
"VO__PEOPLE_M3__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Burada bir soytarı var... Kaçmasına izin vermeyin!",
"VO__PEOPLE_M3__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Seni soytarı, bunun için cezalandıracağım seni!",
"VO__PEOPLE_M3__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Beni bir daha kandıramazsın, peşindeyim!",
"VO__PEOPLE_M3__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Bulacağım seni, bu sefer kaçamazsın.",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT__001__M__1": "Buraya! Yakalayın şu davetsizleri!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT__001__M__2": "Buraya! İzinsiz giren!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT__001__M__3": "Hey! Biri burada!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Olduğun yerde dur!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Hemen dur!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Sen! Olduğun yerde kal!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Burada davetsizler var! Yakalayın onları!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Sen! Davetsizler var!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Burada izinsiz girenler var! Benimle gel!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılalım! Kaçmalarına izin vermeyin!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Dağılın, ölmeliler!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Ayrılın! Uzakta olamazlar!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Senin işin bitti!",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Sonunda yakaladım seni...",
"VO__PEOPLE_M3__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Pekâlâ, senden çok daha iyiyim.",
"VO__PEOPLE_M3__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Bunu hak ettin!",
"VO__PEOPLE_M3__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Bizimle uğraşmamalıydın!",
"VO__PEOPLE_M3__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Dur! Dahası var...",
"VO__PEOPLE_M3__GENERIC__PATROL__HIT_SEARCH__001__M__1": "İmdat! Biri bana saldırıyor!",
"VO__PEOPLE_M3__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Bana saldırıyorlar! İmdat!",
"VO__PEOPLE_M3__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Beni hedef alıyorlar! Yardım edin!",
"VO__PEOPLE_M3__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Bunu kim yaptı?!",
"VO__PEOPLE_M3__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Ne...?! Sana bir ders vereceğim!",
"VO__PEOPLE_M3__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Seni alçak! Parçalarım seni!",
"VO__PEOPLE_M3__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Her şey yolunda mı?",
"VO__PEOPLE_M3__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Bir terslik mi var?",
"VO__PEOPLE_M3__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Ne oldu?",
"VO__PEOPLE_M3__GENERIC__PATROL__REACTION__001__M__1": "Şimdi ne oldu?",
"VO__PEOPLE_M3__GENERIC__PATROL__REACTION__001__M__2": "Ne oluyor?",
"VO__PEOPLE_M3__GENERIC__PATROL__REACTION__001__M__3": "O da neydi?",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME__001__M__1": "Bir şey yok...",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME__001__M__2": "Sakinleşmem lazım...",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME__001__M__3": "Sakin ol... Bir şey yokmuş...",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Yine vakit kaybı...",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Yine bir şey yokmuş, tabii ki...",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Öncekiyle aynı... bir şey yok.",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Yine yanlış alarm, çocuklar...",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "İyi, yine bir şey yokmuş...",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Yine bir şey yok, ne büyük rahatlık!",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Her yer temiz!",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Bir şey yok...",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Her yer temiz!",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Görünürde bir şey yok...",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Burada bir şey yok...",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "İyi, hiçbir şey yok.",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Eee, nerede kalmıştık? Ah, geliyor aklıma!",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Her neyse, ne diyordum? Ha, evet!",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Eee, nerede kalmıştık? Ha, evet!",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Hadi, boş ver.",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Her neyse, gitti işte.",
"VO__PEOPLE_M3__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Normale dönelim...",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH__001__M__1": "Görmüyorum onları! Aramaya devam edin!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH__001__M__2": "Lanet! Yer değiştirdiler! Gözünüzü dört açın!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH__001__M__3": "Nereye gittiler?! Arayın bölgeyi!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Eninde sonunda bulacağım seni!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Buralarda bir yerdesin, biliyorum!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Saklanmanın seni kurtaracağını mı sanıyorsun?!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Dediğin gibi olsun!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Anlaşıldı.",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Durduracağız onları!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Eminim şurada saklanıyorlardır...",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Demek bu tarafa gittiler!?",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Şurada olanlar onlar olmalı!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Davetsizleri buldum! Buraya gelin!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Davetsizleri görüyorum! Buraya gelin!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Burada! Yakalayalım onları!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Bak kim varmış burada...",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Sen! Dur orada!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "İşte, sonunda buldum seni!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Biri etrafta. Gidin bulun onları!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Etrafta davetsizler var, arayın onları!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Misafirimiz var! Bulun onları!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Pekâlâ!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Geliyorum!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Tabii, yapalım şu işi!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Bunu onlar yaptı! Şüphesiz...",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Yemin ederim yine onlar!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Eminim bunu onlar yaptı...",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Bölgedeler, kesinlikle!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Alçaklar! Bölgedeler, peşlerinden hemen!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Uzakta değiller! Kaçıramam onları...",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Şurada sinmişler! Ben hallederim!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Tam şunun arkasında! Yakalayalım onları.",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Şunun arkasındalar! Yakalayalım onları!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Şunun arkasına saklanma, yine de bulurum seni!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Seni orada göremeyeceğimi mi sanıyorsun?!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Şunun arkasında güvende değilsin!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "Şu otların arasındalar! Bulurum onları!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Uzun otların arasında yakalayalım onları!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Otların arasında bir yerdeler! Yakalarım onları!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "Otlar çıkış yolu değil! Gel buraya çabuk!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Çık şu otların arasından, işin bitti!",
"VO__PEOPLE_M3__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "Otların arasına saklanmak, ne büyük hata!",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Yine mi? Neler olduğunu öğrensem iyi olur...",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine başlıyor! Şuraya bakacağım!",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "Yine mi?! Şuraya bakmalıyım, çabuk!",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Dur... yine mi? Tamam, bu sefer emin olalım...",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Yine ne var? Baksam iyi olur...",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Yine mi? Bu sefer kaçırmam!",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Duydun mu şunu?! Gidip bakacağım.",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "Duydun mu? Baksam iyi olur...",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "Dur, bu ses de ne? Bir bakayım...",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Duyduğum şey de ne?",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Bu gürültü de ne?",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Tuhaf bir ses, nedir bu?",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Şurada büyük bir şıklama duydum... Bir bakayım...",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Bu bir sapan değil miydi? Bakacağım.",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "Bir tür şıklama duydum. Araştıracağım.",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Kulaklarım beni yanıltıyor mu... bu bir... sapan mıydı?",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "Bu sesi çıkaran kim? Öğrenmem lazım.",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "Ha?! Kulağa sapan gibi geldi! Öğrensem iyi olur...",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Burada bir şeyler oluyor... Bakacağım.",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Bir şey kıpırdıyor... Bir dakika.",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Şurada kıpırdayan ne...? Bir bakayım.",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "...orada bir şey mi var? Emin olsam iyi olur.",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Gözlerim mi yanılıyor?! Gidip bakmalıyım...",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Hayal mi görüyorum?! Emin olalım.",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Bana ihtiyacın olursa bağır!",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Dikkatli ol.",
"VO__PEOPLE_M3__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Bir şey görürsen söyle.",
"VO__PEOPLE_M3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Burada bulunacak bir şey yok.",
"VO__PEOPLE_M3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Nereye gittiler bunlar?",
"VO__PEOPLE_M3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Burada kalmanın anlamı yok...",
"VO__PEOPLE_M3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Burada görünürde kimse yok...",
"VO__PEOPLE_M3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Başka bir yere bakacağım...",
"VO__PEOPLE_M3__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Başka yere baksam iyi olur...",
# --- PEOPLE_M4 ---
"VO__PEOPLE_M4__GENERIC__PATROL__AGAIN_SEARCH__001__M__1": "Bu sefer olmaz! Benimle oynayanı bulacağım!",
"VO__PEOPLE_M4__GENERIC__PATROL__AGAIN_SEARCH__001__M__2": "Burada bir soytarı var! Bir kez olsun bir şey yapın, bulun onları!",
"VO__PEOPLE_M4__GENERIC__PATROL__AGAIN_SEARCH__001__M__3": "Her yere bakın! Bulalım şu soytarıyı!",
"VO__PEOPLE_M4__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Biri burada, bu sefer hiçbir yere gidemeyecekler.",
"VO__PEOPLE_M4__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Bu sefer benimsin! Duydun mu?",
"VO__PEOPLE_M4__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Artık oynamayacağım! Karşıma çıkmaya hazırlan!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT__001__M__1": "Davetsizler! Buraya gelin!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT__001__M__2": "Buraya! Yakalamama yardım edin!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT__001__M__3": "Buraya! İzinsiz girenler var!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_ALONE__001__M__1": "Kıpırdamayın, sizi alçaklar!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_ALONE__001__M__2": "Kıpırdama!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Buraya geldiğine pişman edeceğim seni!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_PROPAGATE__001__M__1": "Hadi! Yakalayın onları!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_PROPAGATE__001__M__2": "Çabuk olun! Davetsizler var!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_PROPAGATE__001__M__3": "Çabuk olun! Durdurun davetsizleri!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_SPREAD__001__M__1": "Dağılın, durdurun şu davetsizleri!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_SPREAD__001__M__2": "Kaçmalarına izin vermeyin! Dağılın!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_SPREAD__001__M__3": "Uzakta olamazlar! Çabuk dağılın!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Direnmeyi bırak, işin bitti.",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Burada öleceğini biliyorsun!",
"VO__PEOPLE_M4__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Bir böcek gibi ezeceğim seni!...",
"VO__PEOPLE_M4__GENERIC__PATROL__DEATH_VEIL__001__M__1": "Acıyor mu? Güzel!",
"VO__PEOPLE_M4__GENERIC__PATROL__DEATH_VEIL__001__M__2": "Nasıl bir his?!",
"VO__PEOPLE_M4__GENERIC__PATROL__DEATH_VEIL__001__M__3": "Şimdi çok daha iyi görünüyorsun!",
"VO__PEOPLE_M4__GENERIC__PATROL__HIT_SEARCH__001__M__1": "Biri beni hedef alıyor! Arayın burayı!",
"VO__PEOPLE_M4__GENERIC__PATROL__HIT_SEARCH__001__M__2": "Biri bana saldırıyor! Her bir karışı arayın!",
"VO__PEOPLE_M4__GENERIC__PATROL__HIT_SEARCH__001__M__3": "Yardım edin! Bana saldıranı bulun!",
"VO__PEOPLE_M4__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__1": "Of! Canımı mı yakmak istiyorsun? Dur da bir ellerime geçireyim seni!",
"VO__PEOPLE_M4__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__2": "Alçak! Buna pişman olacaksın!",
"VO__PEOPLE_M4__GENERIC__PATROL__HIT_SEARCH_ALONE__001__M__3": "Bana saldırmayı kes, korkak! Nerede olursan ol bulurum seni!",
"VO__PEOPLE_M4__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__1": "Neler oluyor?!",
"VO__PEOPLE_M4__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__2": "Hey, orada mısın?",
"VO__PEOPLE_M4__GENERIC__PATROL__IDLE_INTERRUPTION__001__M__3": "Hey, bir terslik mi var?",
"VO__PEOPLE_M4__GENERIC__PATROL__REACTION__001__M__1": "Ne?",
"VO__PEOPLE_M4__GENERIC__PATROL__REACTION__001__M__2": "Ha?",
"VO__PEOPLE_M4__GENERIC__PATROL__REACTION__001__M__3": "O da ne?",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME__001__M__1": "Bir şey yokmuş...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME__001__M__2": "Fazla endişeleniyorum...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME__001__M__3": "Endişelenecek bir şey yok...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__1": "Bir şey yok, tıpkı az önceki gibi...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__2": "Yine bir şey yokmuş... çok şükür!",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_AGAIN_SPOTTER__001__M__3": "Yine bir şey yok...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__1": "Hâlâ bir şey yok...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__2": "Öncekiyle aynı... Bir şey yok.",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_AGAIN_SPOTTER_ALONE__001__M__3": "Yine bir şey yok işte...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_SPOTTER__001__M__1": "Eh, sanırım sorun yok.",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_SPOTTER__001__M__2": "Bir şey yok!",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_SPOTTER__001__M__3": "Her şey yolunda...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Pekâlâ, fazla endişeleniyorum...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Bir şey yok!",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Eh, neyse. Bir şey yokmuş...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_TALKING__001__M__1": "Nerede kalmıştık? Ha, doğru!",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_TALKING__001__M__2": "Eee, ne diyordum? Ha, doğru!",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_TALKING__001__M__3": "Her neyse, söylediğime geri döneyim...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_WATCHER__001__M__1": "Tamam, boş verelim.",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_WATCHER__001__M__2": "Hepsi en iyisi için...",
"VO__PEOPLE_M4__GENERIC__PATROL__RESUME_WATCHER__001__M__3": "Şimdiye dek iyi gidiyor.",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH__001__M__1": "Onlardan iz yok! Bulun onları!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH__001__M__2": "Gittiler! Her köşeyi arayın!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH__001__M__3": "Alçaklar kaçtı! Tetikte olun!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Daha ne kadar saklanacaksın, korkak?!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Çık artık ortaya!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "İstediğin kadar saklan, hiçbir şey değişmez!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_ANSWER__001__M__1": "Tabii, seninleyim!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_ANSWER__001__M__2": "Olur!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_ANSWER__001__M__3": "Durduralım onları!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_DISTRACT__001__M__1": "Alçaklar, kendinizi ele verdiniz işte.",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_DISTRACT__001__M__2": "Orada saklandığını biliyorum!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_DISTRACT__001__M__3": "Ah! Kendini ele verdin!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_FOUND__001__M__1": "Buradalar! Gelin yardım edin!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_FOUND__001__M__2": "Davetsizler buldum! Yakalayın onları!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_FOUND__001__M__3": "Şurada! Davetsizler!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "İşte buradasın, sonunda!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Olduğun yerde dur!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Bak kimi buldum!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__1": "Etrafta davetsizler var! Tetikte olun!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__2": "Kıpırdayın! Biri burada!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_PROPAGATE__001__M__3": "Davetsizler var, bulmama yardım edin!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__1": "Tabii, gidelim!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__2": "Hallederim!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_PROPAGATE_ANSWER__001__M__3": "Yakalarız onları!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__1": "Bunu onlar yaptı, bahse girerim!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__2": "Yine onlar! Kesinlikle eminim...",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_REACT_TO_SOMETHING__001__M__3": "Bu onların pis oyunlarından biri!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Gözden kaybettim onları! Tekrar bulmama yardım edin.",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Şu alçaklar uzağa gitmedi, eminim!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Hadi ama! Neredesin şimdi?!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__1": "Tam şuraya saklandılar! Yakalarım onları!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__2": "Tam şunun arkasında! Yakalayalım onları çabuk!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_COVER__001__M__3": "Tam şunun arkasında! Kolayca yakalarız onları!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "Şunun arkasına saklanmakla akıllılık ettiğini mi sanıyorsun?",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Siper almaya mı çalışıyorsun? İşe yaramayacak!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Orada olduğunu biliyorum... Kaçamazsın!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__1": "Şuraya saklandıklarını gördüm! Arayın otları!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__2": "Şu otların arasındalar! Peşlerinden!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_GRASS__001__M__3": "Otların arasına girdiler! Takip edin onları!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__1": "O otların arasında uzağa gidemezsin, inan bana!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__2": "Otlar senin için güvenli bir yer değil!",
"VO__PEOPLE_M4__GENERIC__PATROL__SEARCH_SPOTTER_GRASS_ALONE__001__M__3": "O otlar acınası bir saklanma yeri!",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__1": "Yine bir şey oluyor... Gidiyorum!",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__2": "Yine bir şey mi?! Bakmam lazım...",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER__001__M__3": "Yine... Olamaz..?! Neler oluyor bakacağım...",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Yine... Ne olabilir ki..?",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Yine ne var..? Bir daha baksam iyi olur.",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Yine başladı! Ne olduğunu öğrensem iyi olur.",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__1": "Duydun mu o sesi? Bakmam lazım...",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__2": "Tuhaf bir sesti! Bakacağım!",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER__001__M__3": "O ses... Gidip bakacağım!",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Bu kulağa tuhaf geldi!",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Tuhaf bir ses, neler oluyor?",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "O gürültü neydi?",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__1": "Bir şey patlıyor! Emin olmak istiyorum...",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__2": "Az önce bu bir kamçı mıydı..? Gidip bakayım.",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SLING_SPOTTER__001__M__3": "O şıklama tuhaf geldi, baksam iyi olur.",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__1": "Kim... kamçıyla mı oynuyor?",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__2": "O şıklama yakından geldi...",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SLING_SPOTTER_ALONE__001__M__3": "O şıklama da neydi?!",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__1": "Sen de gördün mü? Hemen dönerim.",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__2": "Şunu fark ettin mi? Bir bakayım...",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SPOTTER__001__M__3": "Bu sadece rüzgâr olamaz. Bakmam lazım.",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "Gözlerim mi oyun oynuyor? Baksam iyi olur...",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Şurada kıpırdayan ne? Emin olmak istiyorum!",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Bir şey kıpırdıyor, değil mi?! Bakalım...",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_WATCHER__001__M__1": "Bir şey görürsen söyle, tamam mı?",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_WATCHER__001__M__2": "Bir şey fark edersen söyle!",
"VO__PEOPLE_M4__GENERIC__PATROL__SUSPICION_WATCHER__001__M__3": "Dikkatli ol.",
"VO__PEOPLE_M4__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Etrafta kimse yok...",
"VO__PEOPLE_M4__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Şu küçük alçaklardan iz yok...",
"VO__PEOPLE_M4__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Burada kimse yok kesinlikle...",
"VO__PEOPLE_M4__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Bakalım dışarıda ne var...",
"VO__PEOPLE_M4__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Sanırım başka bir yere baksam iyi olur...",
"VO__PEOPLE_M4__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Muhtemelen başka bir yere gitmişlerdir...",
}
