# -*- coding: utf-8 -*-
# GAME kategorisi: uyarilar, gecisler, kodeks (cicek/kus bilgileri, hatiralar).
# Oyun basligi (GAME__TITLE_1) korunur.
T = {
"GAME__ALERT_AMICIA": "AMICIA FARK EDİLDİ",
"GAME__ALERT_HUGO": "HUGO FARK EDİLDİ",
"GAME__CAPTURE_HUGO": "HUGO YAKALANDI",
"GAME__CODEX_CATEGORY_1": "Hugo'nun Herbaryumu",
"GAME__CODEX_CATEGORY_1_DESC": "Kategorinin açıklaması",
"GAME__CODEX_CATEGORY_1_ITEM_1": "Papatya",
"GAME__CODEX_CATEGORY_1_ITEM_1_DESC": "Papatya, masumiyet ve saflığın simgesidir; ününü muhtemelen taç yapraklarının beyazlığına borçludur. Yatıştırıcı ve sindirimi kolaylaştırıcı özellikleri olan demlemelerde kullanılır, ayrıca yara izlerinin iyileşmesine yardımcı olduğu bilinirdi. Papatya taç yaprakları salatalarda da kullanılır ve hafif biberimsi tatları sayesinde hem soylular hem de halk arasında rağbet görürdü.",
"GAME__CODEX_CATEGORY_1_ITEM_2": "Karanfiller",
"GAME__CODEX_CATEGORY_1_ITEM_2_DESC": "Bazı dillerde \"Tanrı'nın çiçeği\" olarak anılır. Kimi bu lakabı güzelliğine, kimi ise Mesih'in yaralarının kanından ya da Meryem Ana'nın gözyaşlarından doğduğu efsanelerine bağlar. Böylece aşkın, tutkunun ve bağlılığın simgesi hâline gelmiştir. Taç yaprakları, ateş düşürmekte kullanıldığında terlemeyi artırıyor gibi görünür; ayrıca hıyarcıkları temizlemek için sirkesi yapılır, bu da ününe katkıda bulunmuştur.",
"GAME__CODEX_CATEGORY_1_ITEM_3": "Haseki Küpesi",
"GAME__CODEX_CATEGORY_1_ITEM_3_DESC": "Pençeye benzeyen taç yapraklarının biçiminden ötürü, Latincede kartal anlamına gelen \"aquila\" sözcüğünden adını alır. Haseki küpesi; hüznün, huzursuz ruhların, hatta deliliğin simgesidir. Çiçekleri tatlı ve yenilebilir olsa da kökleri ve sapları son derece zehirlidir. Yutulduğunda tüm sindirim sisteminin iltihaplanmasına yol açar ve tehlikeli çarpıntılara neden olabilir.",
"GAME__CODEX_CATEGORY_1_ITEM_4": "Kuzgunkılıcı",
"GAME__CODEX_CATEGORY_1_ITEM_4_DESC": "Hem bakımlı bahçelerde hem de yabani tarlalarda bulunur; pek çok türü zehirlidir, ama bir tanesi yemeklerde tüketilir ve ilaçlarda kullanılırdı. Gladius kılıcını andıran yapraklarının biçimi, onu Roma döneminde kahramanların ve gladyatörlerin çiçeği yaptı: güç ve dinçlik simgesi.",
"GAME__CODEX_CATEGORY_1_ITEM_5": "Akdiken",
"GAME__CODEX_CATEGORY_1_ITEM_5_DESC": "Bahçelerin ve mülklerin sınırlarını belirlemekte kullanılan dikenli bir çalı olan akdiken, temkinli umudun simgesi hâline gelmiştir. Pek çok efsaneye konu olur; bunların en saygını onu Mesih'in dikenli tacı olarak betimler. Demlenip içildiğinde kalp atışını düzenler ve nefes darlığıyla savaşır.",
"GAME__CODEX_CATEGORY_1_ITEM_6": "Sarı Kantaron",
"GAME__CODEX_CATEGORY_1_ITEM_6_DESC": "\"Aziz Yahya otu\" olarak da adlandırılan sarı kantaron, düşmanlığın olduğu kadar korumanın ve ışığın da simgesidir; melankoliye ve diğer ruhsal rahatsızlıklara bir derman sayılır. \"Şeytan avcısı\" lakabına rağmen, yutulması yine de kalp ritmini ciddi biçimde bozarak aritmiye ve taşikardiye yol açabilir.",
"GAME__CODEX_CATEGORY_1_ITEM_7": "Lavanta",
"GAME__CODEX_CATEGORY_1_ITEM_7_DESC": "Lavanta, kokusuyla ve dokumacılar arasında rengiyle yaygın olarak bilinir. İyi eğitimliler ayrıca arındırıcı değerleri için onu birçok lapada kullanır. Zehri zayıflatmak için engerek ısırıklarına ya da bitle savaşmak için çocukların saçlı derisine sürülürdü. Zamanla adanmışlığın ve sadakatin simgesi hâline gelmiştir.",
"GAME__CODEX_CATEGORY_1_ITEM_8": "Ormangülü",
"GAME__CODEX_CATEGORY_1_ITEM_8_DESC": "Ormangülünün kendisi zararsız olsa da çiçeklerinden yapılan balın halüsinojen ve müshil etkili toksinler taşıdığı söylenir. Görünüşe göre Yunan ordusunu bozguna uğratıp On Binlerin Ricatı'na yol açan da budur; askerler yağmanın ardından bu bala doyasıya yüklenmiş ve etkilerine maruz kalmıştır. Apaçık zararı, muhtemelen onu riskin ve tehlikenin simgesi yapan şeydir.",
"GAME__CODEX_CATEGORY_1_ITEM_9": "Beşparmak Otu",
"GAME__CODEX_CATEGORY_1_ITEM_9_DESC": "Adını taç yapraklarının sayısına borçludur: bir eldeki parmaklar gibi beş. Tıbbi açıdan, Antik Çağ'dan beri sindirim yolu hastalıklarıyla savaşmak, ateşi düşürmek ve kanamayı durdurmak için macun ya da kaynatma hâlinde kullanılırdı. Ayrıca hanedan armacılığında önemli bir simgedir ve kuzeybatı Fransa'nın büyük ailelerinin armalarını süsler.",
"GAME__CODEX_CATEGORY_1_ITEM_10": "Nergis",
"GAME__CODEX_CATEGORY_1_ITEM_10_DESC": "Kendi yansımasına bakarken ölen mitolojik bir figür olan Narkissos'un kalıntılarından bittiği söylenir. Bencilliği ve hodgâmlığı simgeler. Antik Çağ'dan beri insanlığın bildiği belirgin zehirleme potansiyeline rağmen, birçok Avrupa ülkesi onu tümörleri, sara nöbetlerini ve saç dökülmesini tedavi etmekte kullanmıştır—değişen başarı derecelerinde.",
"GAME__CODEX_CATEGORY_1_ITEM_11": "Köpek Üzümü",
"GAME__CODEX_CATEGORY_1_ITEM_11_DESC": "Bir hakikat simgesi olan ve kimilerince şeytani büyücülükle ilişkilendirilen köpek üzümünün kaygı verici pek çok lakabı vardır: \"şeytan otu\", \"ölüm kirazları\" ve \"güzel ölüm\". Meyvelerinin zehirliliği elbette bunda bir etken; onları yemek ölüme yol açabilir.",
"GAME__CODEX_CATEGORY_1_ITEM_12": "Taşkıran",
"GAME__CODEX_CATEGORY_1_ITEM_12_DESC": "\"Taş kıran\" olarak da bilinen taşkıran, çoğunlukla soğuk, dağlık ortamlarda bulunur ve dondan korunmak için kaya çatlaklarına sızar. Kaçınılmazlığı ve bir tür çaresizliği simgeler. Bu lakap, böbrek taşlarını eritmenin bir yolu sayılmasından gelir.",
"GAME__CODEX_CATEGORY_1_ITEM_13": "Noel Gülü",
"GAME__CODEX_CATEGORY_1_ITEM_13_DESC": "Antik Çağ'dan beri bunamayı ve bazı felç türlerini tedavi etmekte kullanılan bitki, kısa sürede kaygının ve huzursuzluğun simgesi hâline geldi—bu muhtemelen zehirliliğinden ötürüdür, zira çıplak elle tutulması şiddetli tahrişlere, yutulması ise daha da ağır tepkilere yol açar. Tuhaftır ki Noel zamanı doğum tasvirlerinde yer alır. Yeni doğan Mesih'e bir armağan sunmaya can atan genç çoban kız Madelon'un gözyaşlarından doğduğu söylenir.",
"GAME__CODEX_CATEGORY_2": "Hugo'nun koleksiyonu",
"GAME__CODEX_CATEGORY_2_ITEM_1": "Ok Otu",
"GAME__CODEX_CATEGORY_2_ITEM_1_DESC": "Bu minik, beyaz yıldız; çoğunlukla sığ göllerde ve kale hendeklerinde bulunan, koloni oluşturan, suda yetişen bir kır çiçeğidir. Cins adı \"sagitta\", Latincede \"ok\" anlamına gelir ve yapraklarının biçiminden gelir. Genellikle haşlanarak yenen yumrular ürettiği için \"ördek patatesi\" olarak da bilinir. Simyadaki yedi \"saf metal\"den ikisi olan bakır ya da kurşun gibi ağır metalik öğeleri büyük miktarlarda emdiği söylenir.",
"GAME__CODEX_CATEGORY_2_ITEM_2": "Mayıs Papatyası",
"GAME__CODEX_CATEGORY_2_ITEM_2_DESC": "Doğada minik papatya başlarını andırır; tarlaları beyaz ve sarı çiçeklerle benekler. Geleneksel olarak şifacılar onu güçlü bir uyku yardımcısı olarak önerir. Koruyucu özelliklerinin büyüleri savuşturduğuna da inanılır ve çiçekleri sık sık şansla ve mali başarıyla ilişkilendirilir: birçok kumarbaz, para çekmek için ellerini ondan yapılan çayda yıkardı.",
"GAME__CODEX_CATEGORY_2_ITEM_3": "Centiyane",
"GAME__CODEX_CATEGORY_2_ITEM_3_DESC": "Yaşlı Plinius'a göre adını, yaraları temizlemekte kullanırken onun özel şifalı etkilerini deneyimleyen İllirya'nın son kralı Gentius'tan alır. Alpler kökenli olan bazı türlerinin kökleri, müshil ve canlandırıcı etkileri için iştah açıcı olarak içilen mayhoş bir liköre dönüştürülür. Dağların kraliçesi olan bu çiçeğin parlak, koyu rengi açıkça keder ve acıyla bağlantılıdır. Bir centiyane buketi sunmak, küçümsemenizi ifade eder.",
"GAME__CODEX_CATEGORY_2_ITEM_4": "Anemon",
"GAME__CODEX_CATEGORY_2_ITEM_4_DESC": "Akdeniz kıyılarında gürleyen \"Anemôné\", Yunancada \"rüzgârın kızı\" anlamına gelir. Rüzgâr çiçeği olarak da anılır; sert havalarda açar, ardından tüy gibi tohumlarını büyük mesafelere savurur. Yunan mitolojisinde terk edilmişlikle ilişkilendirilir ve tanrıça Afrodit'in Adonis'in ölümüne yas tutarken döktüğü gözyaşlarından doğduğu söylenir. Köylü inançlarına göre anemonun kapanması, yaklaşan bir yağmurun işaretidir.",
"GAME__CODEX_CATEGORY_2_ITEM_5": "Karanfil",
"GAME__CODEX_CATEGORY_2_ITEM_5_DESC": "\"Tanrıların çiçeği\"nin kökenleri Antik Çağ'a dek uzanabilir. Yunanlar taç giyme törenlerinde \"corone\" (çiçek çelenkleri) sunar, Romalılar ise üstün performansları için sporcuları \"Jüpiter'in Çiçekleri\"yle ödüllendirirdi. Hristiyan efsanelerinde Meryem'in oğlunun yasını tutarken döktüğü gözyaşları pembe karanfillere dönüşmüş, \"carnis\" sözcüğü ise Mesih'in tenine işaret eder olmuştur. Saflığın ve şükranın simgesi olan buketleri, bir zamanlar bir annenin sevgisini onurlandırırdı.",
"GAME__CODEX_CATEGORY_2_ITEM_6": "Alakarga",
"GAME__CODEX_CATEGORY_2_ITEM_6_DESC": "Ormanın nöbetçisi olan alakarganın gür çağrısı, avcılar yaklaştığında çevredeki tüm canlıları uyarır. Efsaneye göre bir zamanlar diğer kuşlar tarafından haksız yere suçlanmış ve her biri ona bir tüy bağışlamaya mahkûm edilmiş. Belki de bu yüzden, renkli ve parlak tüyleriyle en karanlık yerleri bile aydınlatan ışığın amblemi sayılır. Tüyünü bulursan, sana iyileşme ve asla pes etmeme enerjisini getirir.",
"GAME__CODEX_CATEGORY_2_ITEM_7": "Karabaş Martı",
"GAME__CODEX_CATEGORY_2_ITEM_7_DESC": "Cana yakın ve gürültücü olan karabaş martı, genellikle açık kıyılarda ve kumullarda sürüler hâlinde toplanır. Denizciler ve denizde gemisi batanlar için büyük önem taşır: çağrısını duyanlar yakında karayı görecek ve evlerine dönecektir. Halk masallarında anaç bağı simgeler. Bir martı görmek, anneye acılı bir veda işaretidir; ondan bir tüy bulmak ise özgürlük ve aileden bağımsızlaşmak anlamına gelir.",
"GAME__CODEX_CATEGORY_2_ITEM_8": "Kara Çaylak",
"GAME__CODEX_CATEGORY_2_ITEM_8_DESC": "Bir leşçil olan kara çaylak; alçak, tiz bir çağrıya ve göller üzerinde daireler çizerek süzülen zarif bir siluete sahip, büyüleyici ama yanlış anlaşılan bir yırtıcı kuştur. Yunan mitolojisinde güneş tanrısı Apollon'la ilişkilendirilir ve farkındalık ile öngörü armağanını barındırır. Çaylağın anlamı, geçmişi kabullenmek ve ileriye gitmektir. Tüyü ortaya çıkarsa, yakında hayatında köklü bir değişim yaşayacaksın.",
"GAME__CODEX_CATEGORY_2_ITEM_9": "Peçeli Baykuş",
"GAME__CODEX_CATEGORY_2_ITEM_9_DESC": "Hayalet gibi solgun ve kara gözlü olan bu beyaz hanım, terk edilmiş ahırlara ya da oyuk kütüklere musallat olur ve genellikle kehanet ve bilgelikle ilişkilendirilir. Tüyüne sahip olmak seni içsel yeteneklerine bağlar ve sezgilerini izlerken hayatında eyleme geçme gücü verir. Bu gece avcısının yoluna çıkması, dünyanın—karanlık ve acımasız olsa bile—hâlâ harikalarla dolu olabileceğini de hatırlatır.",
"GAME__CODEX_CATEGORY_2_ITEM_10": "Kuzgun",
"GAME__CODEX_CATEGORY_2_ITEM_10_DESC": "Tarihî çağlardan beri batıl inanç onu kötü alametlerle ve büyücülükle ilişkilendirir; bunun bir nedeni tedirgin edici, yanardöner tüyleri, bir diğeri ise karşılaştığı her leşten kendine bir şölen çıkarmasıdır. ~Rüyada gelen bir kuzgun, kişinin kendini dönüştürmesinin simgesidir: bu ruh rehberi, zihnimizin karanlığında yatan güçleri keşfetmemize yardım eder. Tüyü, büyük değişimlerin üstesinden gelme gücünü ve hayatın çetin yolculuğunda birinin bizi gözettiği vaadini getirir.",
"GAME__CODEX_CATEGORY_2_ITEM_11": "Saka Kuşu",
"GAME__CODEX_CATEGORY_2_ITEM_11_DESC": "Hoş ötüşü ve parlak limon rengiyle bu sevimli dost, genellikle taşkın ovalarında yaşadığından mağaralarda yolunu kaybetmiş olmalı. Gagalaması için ona kenger tohumu sunarsan bahçeni ziyaret eder—yaygın adlarından biri de \"diken ispinozu\"dur. Dinî geleneklerde dirilişi ve canlılığı simgeler; eski pagan inançları ise onun veba belasına karşı güçlü bir koruma getirebileceğini bile düşünürdü.",
"GAME__CODEX_CATEGORY_2_ITEM_12": "Boz Kaz",
"GAME__CODEX_CATEGORY_2_ITEM_12_DESC": "Avlumuzdaki kazların bu atası, birçok Avrupa sulak alanında bulunabilir. Çok eskiden Roma'da, Juno tapınağının kutsal kazlarının tehlikeyi sezdiği söylenir ve saldırılara karşı uyarıda bulunurlardı. Halk folklorunda ayrıca maceraya çağrıyı ve efsanevi yerlere yolculukları simgeler. Geleneksel olarak yazı yazmak için tercih edilen tüyleri, sana aileni izlemen ve köklerini asla unutmaman gerektiğini hatırlatır.",
"GAME__CODEX_CATEGORY_3": "Hatıralar",
"GAME__CODEX_CATEGORY_3_ITEM_1": "En iyi oyuncu",
"GAME__CODEX_CATEGORY_3_ITEM_2": "Huzur içinde ol",
"GAME__CODEX_CATEGORY_3_ITEM_3": "Bir mezar",
"GAME__CODEX_CATEGORY_3_ITEM_4": "Yuvamız",
"GAME__CODEX_CATEGORY_3_ITEM_5": "İpek hazinesi",
"GAME__CODEX_CATEGORY_3_ITEM_6": "Bir kum tanesi",
"GAME__CODEX_CATEGORY_3_ITEM_7": "Geyiğin böğürtüsü",
"GAME__CODEX_CATEGORY_3_ITEM_8": "Huuuugoooo!",
"GAME__CODEX_CATEGORY_3_ITEM_9": "Uçtuğunu hayal et!",
"GAME__CODEX_CATEGORY_3_ITEM_10": "Hangi rengi istersin?",
"GAME__CODEX_CATEGORY_3_ITEM_11": "Hayatta Kalan",
"GAME__CODEX_CATEGORY_3_ITEM_12": "İlk insanlar",
"GAME__CODEX_CATEGORY_3_ITEM_13": "Sessiz Lucinda",
"GAME__CODEX_CATEGORY_3_ITEM_14": "Çiçekten taç",
"GAME__CODEX_CATEGORY_3_ITEM_15": "Bin yıl daha",
"GAME__CODEX_CATEGORY_3_ITEM_16": "Tramontana",
"GAME__CODEX_CATEGORY_3_ITEM_17": "Güzel bir cıyaklama",
"GAME__CODEX_CATEGORY_3_ITEM_18": "Bir bez bebek",
"GAME__CODEX_CATEGORY_3_ITEM_19": "Chateau d'Ombrage",
"GAME__CODEX_CATEGORY_3_ITEM_20": "Oyuncakları...",
"GAME__CODEX_CATEGORY_3_ITEM_21": "Darmadağın",
"GAME__DEATH_ARNAUD": "ARNAUD ÖLDÜ",
"GAME__DEATH_BEATRICE": "BEATRICE ÖLDÜ",
"GAME__DEATH_HUGO": "HUGO ÖLDÜ",
"GAME__DEATH_LUCAS": "LUCAS ÖLDÜ",
"GAME__DEATH_PLAYER": "AMICIA ÖLDÜ",
"GAME__DEATH_SOPHIA": "SOPHIA ÖLDÜ",
"GAME__INTROTEXT": "Focus Home Interactive sunar",
"GAME__INTROTEXT2": "Bir Asobo Studio oyunu",
"GAME__TRANSITION_CH1_01": "FRANSA KRALLIĞI",
"GAME__TRANSITION_CH1_02": "HAZİRAN 1349",
"GAME__TRANSITION_CH17_01": "BİR YIL SONRA",
"GAME__TRANSITION_CH17_02": "HAZİRAN 1350",
}
