# -*- coding: utf-8 -*-
# Genel Sesler GS2: ARNAUD+BEATRICE+COUNT+HUGO+LUCAS+SOPHIA generic VO (596 satir).
T = {
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_BEGIN__001__M__1": "Yaaaaaaaaaargh! Gel buraya sen!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_BEGIN__001__M__2": "Yaaaaaaaaaargh! Sen ve ben!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_BEGIN__001__M__3": "Yaaaaaaaaaargh! Kısa keseceğim!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_LOSSWARNING__001__M__1": "Burada dengeyi sağlayacak birine ihtiyacım var!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_LOSSWARNING__001__M__2": "Bunu sonsuza kadar sürdüremem!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_LOSSWARNING__001__M__3": "Onları daha fazla tutamayacağım!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_RESUMEWIN__001__M__1": "Merak etme, sıra sende!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_RESUMEWIN__001__M__2": "Hani arkadaşın nerede şimdi?!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_RESUMEWIN__001__M__3": "Bakalım tek başına nasıl dövüşüyorsun!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_STARTLOSE__001__M__1": "Bire iki mi?! Adil dövüşten mi korkuyorsunuz?!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_STARTLOSE__001__M__2": "Pöh! Siz ödlekler bana karşı birleşmek zorundasınız!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_STARTLOSE__001__M__3": "Korkaklar! Tek başınıza benimle baş edemiyor musunuz?!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_WIN__001__M__1": "Kaybettin!",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_WIN__001__M__2": "Üzgünüm, kaybetmek seçeneklerim arasında yoktu.",
"VO__ARNAUD__GENERIC__EVENT__ARNAUD_GROUPFIGHT_WIN__001__M__3": "Kazanmak benim kaderimdi!",
"VO__ARNAUD__GENERIC__EVENT__CAUGHT_RATS__001__M__1": "Çekilin üstümden!",
"VO__ARNAUD__GENERIC__EVENT__CAUGHT_RATS__001__M__2": "Lanet sıçanlar!",
"VO__ARNAUD__GENERIC__EVENT__CAUGHT_RATS__001__M__3": "Üstüme çıktılar! Yardım edin!",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__1": "Geliyor...",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__2": "Biri geliyor...",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__3": "Misafirimiz var...",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__4": "Fark edildik...",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__1": "Bizi bulacaklar!",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__2": "Çember daralıyor!",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__3": "Bu tarafa geliyorlar.",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__4": "Burada güvende değiliz!",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__1": "Dikkat et...",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__2": "Dikkatli ol...",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__3": "Sessiz ol...",
"VO__ARNAUD__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__4": "Kapayın çenenizi...",
"VO__ARNAUD__GENERIC__EVENT__JOIN_AMICIA_LONG__001__M__1": "Geç kaldın.",
"VO__ARNAUD__GENERIC__EVENT__JOIN_AMICIA_LONG__001__M__2": "Beni beklettin.",
"VO__ARNAUD__GENERIC__EVENT__JOIN_AMICIA_LONG__001__M__3": "Döndüğüne sevindim.",
"VO__ARNAUD__GENERIC__EVENT__JOIN_AMICIA_LONG_DISCREET__001__M__1": "Tam zamanı!",
"VO__ARNAUD__GENERIC__EVENT__JOIN_AMICIA_LONG_DISCREET__001__M__2": "Nihayet döndün.",
"VO__ARNAUD__GENERIC__EVENT__JOIN_AMICIA_LONG_DISCREET__001__M__3": "Güvende olmana sevindim.",
"VO__ARNAUD__GENERIC__INTERACT__CANT_JOIN__001__M__1": "Şu an sana ulaşamam.",
"VO__ARNAUD__GENERIC__INTERACT__CANT_JOIN__001__M__2": "Sana katılamıyorum!",
"VO__ARNAUD__GENERIC__INTERACT__CANT_JOIN__001__M__3": "Yanına dönemiyorum!",
"VO__ARNAUD__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__1": "Şu an sana katılamam.",
"VO__ARNAUD__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__2": "Şu an sana ulaşamıyorum.",
"VO__ARNAUD__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__3": "Sana ulaşamıyorum!",
"VO__ARNAUD__GENERIC__INTERACT__CAUGHT__001__M__1": "Hemen bir el lazım!",
"VO__ARNAUD__GENERIC__INTERACT__CAUGHT__001__M__2": "Yardım lazım, HEMEN!",
"VO__ARNAUD__GENERIC__INTERACT__CAUGHT__001__M__3": "Amicia, başım belada!",
"VO__ARNAUD__GENERIC__INTERACT__CAUGHT__001__M__4": "Amicia, gel yardım et!",
"VO__ARNAUD__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__1": "Bizi gördüler!",
"VO__ARNAUD__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__2": "Bizi fark ettiler!",
"VO__ARNAUD__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__3": "Artık burada olduğumuzu biliyorlar!",
"VO__ARNAUD__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__4": "Üstümüze geliyorlar!",
"VO__ARNAUD__GENERIC__INTERACT__LOSS__001__M__1": "Olamaz...",
"VO__ARNAUD__GENERIC__INTERACT__LOSS__001__M__2": "Kahretsin! Hayır!",
"VO__ARNAUD__GENERIC__INTERACT__LOSS__001__M__3": "Kızım!",
"VO__ARNAUD__GENERIC__INTERACT__LOSS__001__M__4": "Hayır!",
"VO__ARNAUD__GENERIC__INTERACT__SAVED__001__M__1": "Arkamı kolladın!",
"VO__ARNAUD__GENERIC__INTERACT__SAVED__001__M__3": "Ölmem.",
"VO__ARNAUD__GENERIC__INTERACT__SAVED__001__M__4": "Yardımın için minnettarım.",
"VO__ARNAUD__GENERIC__INTERACT__STUCK__001__M__1": "Oraya ulaşmama imkân yok.",
"VO__ARNAUD__GENERIC__INTERACT__STUCK__001__M__2": "Ona erişemiyorum bile.",
"VO__ARNAUD__GENERIC__INTERACT__STUCK__001__M__3": "Burada sıkışıp kaldım işte.",
"VO__ARNAUD__GENERIC__INTERACT__STUCK__001__M__4": "Oraya geçemiyorum.",
"VO__ARNAUD__GENERIC__INTERACT__STUCK_DISCREET__001__M__1": "Oraya gerçekten geçemiyorum...",
"VO__ARNAUD__GENERIC__INTERACT__STUCK_DISCREET__001__M__2": "Gidebileceğim bir yer değil.",
"VO__ARNAUD__GENERIC__INTERACT__STUCK_DISCREET__001__M__3": "Orası gidemeyeceğim bir yer.",
"VO__ARNAUD__GENERIC__INTERACT__STUCK_DISCREET__001__M__4": "Oraya gidemem.",
"VO__ARNAUD__GENERIC__INTERACT__STUCK_STRESSED__001__M__1": "Oraya geçmeme imkân yok!",
"VO__ARNAUD__GENERIC__INTERACT__STUCK_STRESSED__001__M__2": "İmkânsız, oraya ulaşamam.",
"VO__ARNAUD__GENERIC__INTERACT__STUCK_STRESSED__001__M__3": "Üzgünüm, oraya ulaşamıyorum.",
"VO__ARNAUD__GENERIC__INTERACT__STUCK_STRESSED__001__M__4": "Oraya ulaşmama imkân yok!",
"VO__ARNAUD__GENERIC__INTERACT__YES__001__M__1": "Bu benim işim.",
"VO__ARNAUD__GENERIC__INTERACT__YES__001__M__2": "Tamamdır!",
"VO__ARNAUD__GENERIC__INTERACT__YES__001__M__3": "Tabii ki.",
"VO__ARNAUD__GENERIC__INTERACT__YES__001__M__4": "Elbette.",
"VO__ARNAUD__GENERIC__INTERACT__YES_DISCREET__001__M__1": "Olur.",
"VO__ARNAUD__GENERIC__INTERACT__YES_DISCREET__001__M__2": "Evet...",
"VO__ARNAUD__GENERIC__INTERACT__YES_DISCREET__001__M__3": "Hadi yapalım...",
"VO__ARNAUD__GENERIC__INTERACT__YES_DISCREET__001__M__4": "Elbette.",
"VO__ARNAUD__GENERIC__INTERACT__YES_STRESSED__001__M__1": "Gidelim.",
"VO__ARNAUD__GENERIC__INTERACT__YES_STRESSED__001__M__2": "Gidelim!",
"VO__ARNAUD__GENERIC__INTERACT__YES_STRESSED__001__M__3": "Geliyorum!",
"VO__ARNAUD__GENERIC__INTERACT__YES_STRESSED__001__M__4": "Bana uyar.",
"VO__ARNAUD__GENERIC__ORDER__ARNAUD_GROUPFIGHT_ORDER__001__M__1": "Dövüşmeye hazırım!",
"VO__ARNAUD__GENERIC__ORDER__ARNAUD_GROUPFIGHT_ORDER__001__M__2": "Dövüşelim!",
"VO__ARNAUD__GENERIC__ORDER__ARNAUD_GROUPFIGHT_ORDER__001__M__3": "Bir kavgaya her zaman hazırım.",
"VO__ARNAUD__GENERIC__PATROL__ALERT_ALONE__001__M__1": "İşte buradasın!",
"VO__ARNAUD__GENERIC__PATROL__ALERT_ALONE__001__M__2": "İşte buradasın kızım!",
"VO__ARNAUD__GENERIC__PATROL__ALERT_ALONE__001__M__3": "Seni buldum!",
"VO__ARNAUD__GENERIC__PATROL__REACTION__001__M__1": "Orada biri mi var?",
"VO__ARNAUD__GENERIC__PATROL__REACTION__001__M__2": "Bana göre yeterince zeki değilsin evlat.",
"VO__ARNAUD__GENERIC__PATROL__REACTION__001__M__3": "Daha gizli oynamalısın!",
"VO__ARNAUD__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__1": "Burada bir şey yok... Yazık...",
"VO__ARNAUD__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__2": "Burası temiz.",
"VO__ARNAUD__GENERIC__PATROL__RESUME_SPOTTER_ALONE__001__M__3": "Burada değil... Neyse.",
"VO__ARNAUD__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Galiba bir ses... muhtemelen o... Bakalım...",
"VO__ARNAUD__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Şu ses... Sen misin kızım?",
"VO__ARNAUD__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Bu kadar ses çıkarmamalısın.",
"VO__ARNAUD__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "O olmalı...",
"VO__ARNAUD__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "O mu? Bir bakalım!",
"VO__ARNAUD__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Saklanmayı bırak, seni orada gördüm!",
"VO__ARNAUD__GENERIC__RESPONSE__BUSY__001__M__1": "Başka bir işle meşgulüm.",
"VO__ARNAUD__GENERIC__RESPONSE__BUSY__001__M__2": "Önce bitirmem gereken başka bir iş var!",
"VO__ARNAUD__GENERIC__RESPONSE__BUSY__001__M__3": "Şu an başka bir şey yapıyorum!",
"VO__ARNAUD__GENERIC__RESPONSE__FOLLOW__001__M__1": "Tabii, hareket edelim.",
"VO__ARNAUD__GENERIC__RESPONSE__FOLLOW__001__M__2": "Tamam, hadi.",
"VO__ARNAUD__GENERIC__RESPONSE__FOLLOW__001__M__3": "Beraber gidelim.",
"VO__ARNAUD__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__1": "Tamam, hareket edelim.",
"VO__ARNAUD__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__2": "Tabii, buradayım.",
"VO__ARNAUD__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__3": "Tamam, bana güven.",
"VO__ARNAUD__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__1": "Tabii, takip ediyorum...",
"VO__ARNAUD__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__2": "Yola koyulalım.",
"VO__ARNAUD__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__3": "Tamam, yanındayım.",
"VO__ARNAUD__GENERIC__RESPONSE__STAY__001__M__1": "Orada arkanı kolla.",
"VO__ARNAUD__GENERIC__RESPONSE__STAY__001__M__2": "Doğru, dikkatli ol.",
"VO__ARNAUD__GENERIC__RESPONSE__STAY__001__M__3": "Tamam, burada bekleyeceğim.",
"VO__ARNAUD__GENERIC__RESPONSE__STAY_DISCREET__001__M__1": "Gözden uzak duracağım, güven bana.",
"VO__ARNAUD__GENERIC__RESPONSE__STAY_DISCREET__001__M__2": "Bekleyeceğim. Yakalanma.",
"VO__ARNAUD__GENERIC__RESPONSE__STAY_DISCREET__001__M__3": "Burada kalıyorum. Dikkatli ol.",
"VO__ARNAUD__GENERIC__RESPONSE__STAY_STRESSED__001__M__1": "Tabii, tehlikeden uzak dur.",
"VO__ARNAUD__GENERIC__RESPONSE__STAY_STRESSED__001__M__2": "Tabii. Orada dikkatli ol.",
"VO__ARNAUD__GENERIC__RESPONSE__STAY_STRESSED__001__M__3": "Tamam, ama dikkat et.",
"VO__BEATRICE__GENERIC__INTERACT__LOSS__001__M__1": "HAYIR! HAYIR! Kızım...",
"VO__BEATRICE__GENERIC__INTERACT__LOSS__001__M__2": "Amicia! HAYIR!",
"VO__BEATRICE__GENERIC__INTERACT__LOSS__001__M__3": "Lütfen olmaz... AMICIA!",
"VO__BEATRICE__GENERIC__INTERACT__LOSS__001__M__4": "Hayır hayır hayır! AMICIA!",
"VO__BEATRICE__GENERIC__INTERACT__LOSS_HUGO__001__M__1": "Hugo! HUGOOOO!",
"VO__BEATRICE__GENERIC__INTERACT__LOSS_HUGO__001__M__2": "Hayır! HAYIIR!",
"VO__BEATRICE__GENERIC__INTERACT__LOSS_HUGO__001__M__3": "Hayır! HUGOOOO!",
"VO__BEATRICE__GENERIC__INTERACT__LOSS_HUGO__001__M__4": "HUGO! HAYIIIIR!",
"VO__COUNT__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__1": "Bu küçük oyunlarını oynayabilirsin. Ama sonunda ben kazanacağım.",
"VO__COUNT__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__2": "Beni kızdırmak akıllıca değil.",
"VO__COUNT__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__3": "Bu kadarı yeter! İnan bana seni yakalayacağım!",
"VO__COUNT__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__4": "Buradasın, artık eminim.",
"VO__COUNT__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__5": "Zekisin, ama bu sefer ben daha zekice oynayacağım!",
"VO__COUNT__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__6": "Bu sefer ya sen ya ben!",
"VO__COUNT__GENERIC__PATROL__AGAIN_SEARCH_ALONE__001__M__7": "Benimle daha fazla oyun oynayamayacaksın!",
"VO__COUNT__GENERIC__PATROL__ALERT_BLOCKED__001__M__1": "Hımf! İyi oynadın.",
"VO__COUNT__GENERIC__PATROL__ALERT_BLOCKED__001__M__2": "Epey direniyorsun!",
"VO__COUNT__GENERIC__PATROL__ALERT_BLOCKED__001__M__3": "Yiğitçe bir çaba.",
"VO__COUNT__GENERIC__PATROL__ALERT_BLOCKED__001__M__4": "Kayda değer.",
"VO__COUNT__GENERIC__PATROL__ALERT_BLOCKED__001__M__5": "Ruhuna hayranım.",
"VO__COUNT__GENERIC__PATROL__ALERT_BLOCKED__001__M__6": "Bunu bana kolaylaştırmıyorsun.",
"VO__COUNT__GENERIC__PATROL__ALERT_TAUNT__001__M__1": "Asilce dövüşüyorsun.",
"VO__COUNT__GENERIC__PATROL__ALERT_TAUNT__001__M__2": "Direnmenin anlamı yok.",
"VO__COUNT__GENERIC__PATROL__ALERT_TAUNT__001__M__3": "Mücadele etmek nafile.",
"VO__COUNT__GENERIC__PATROL__REACTION__001__M__1": "Orada mı saklanıyorsun?",
"VO__COUNT__GENERIC__PATROL__REACTION__001__M__2": "Nerede olduğunu biliyorum.",
"VO__COUNT__GENERIC__PATROL__REACTION__001__M__3": "Seni bulacağım.",
"VO__COUNT__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Nerede olabilirsin?",
"VO__COUNT__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Saklanmak nafile, gidecek yerin yok.",
"VO__COUNT__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Sonsuza dek saklanamayacaksın.",
"VO__COUNT__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "İşte buradasın!",
"VO__COUNT__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "İşte oradasın.",
"VO__COUNT__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Kaçmanın anlamı yok Amicia.",
"VO__COUNT__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__4": "Hiçbir yere gidemeyeceğini biliyorsun...",
"VO__COUNT__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__5": "Direnme!",
"VO__COUNT__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__6": "Amicia, gel bana!",
"VO__COUNT__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__7": "Buldum seni.",
"VO__COUNT__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__8": "Sonunda yakaladım seni!",
"VO__COUNT__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__9": "Amicia, işte buradasın!",
"VO__COUNT__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__10": "Demek buradasın!",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER__001__M__1": "Nereye gittin?",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER__001__M__2": "Saklanıyoruz, öyle mi?",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER__001__M__3": "Nereye gittin lanet olsun!",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__1": "O siper seni benden kurtarmaz...",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__2": "Amicia, onun arkasında benden saklanamazsın!",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__3": "Onun arkasına saklanmanın seni kurtaracağını mı sanıyorsun?",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__4": "Amicia, oraya saklanma! Çık dışarı!",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__5": "Orada güvende olmayacaksın! Yüzleş benimle!",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER_COVER_ALONE__001__M__6": "Onun arkasına saklanmak... Amicia, senden daha fazlasını beklerdim?!",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__1": "Seni gördüm. Çık oranın altından.",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__2": "Oranın altına saklanmak seni kurtarmaz.",
"VO__COUNT__GENERIC__PATROL__SEARCH_SPOTTER_INSIDE_ALONE__001__M__3": "Oranın altına saklanmanın beni kandıracağını mı sanıyorsun?",
"VO__COUNT__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Benimle gerçekten oyun mu oynuyorsun?",
"VO__COUNT__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Amicia benimle oynamayı bırak!",
"VO__COUNT__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Küçük oyunların boşuna!",
"VO__COUNT__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Amicia ne kadar gürültücüsün... Böyle kaçamazsın...",
"VO__COUNT__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Seni duydum! Olduğun yerde kal!",
"VO__COUNT__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Bu, saklanmaya çalışan birinin sesi.",
"VO__COUNT__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__4": "Ne çok gürültü! Beni doğruca sana götürecek!",
"VO__COUNT__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__5": "Ah, seni duyuyorum! Benden kaçamazsın.",
"VO__COUNT__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__6": "Böyle saklanarak benden kaçamazsın, genç hanım!",
"VO__COUNT__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__7": "Çok gürültücüsün Amicia! Daha iyisini yapmalısın!",
"VO__COUNT__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Nerede olabilirsin?",
"VO__COUNT__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Saklanmayı biliyorsun, bunu kabul ediyorum.",
"VO__COUNT__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Er ya da geç seni bulacağım.",
"VO__COUNT__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Burada değilsen, neredesin?",
"VO__COUNT__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Nereye gittin?",
"VO__COUNT__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Neredesin?",
"VO__HUGO__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__1": "Olamaz!",
"VO__HUGO__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__2": "Hayır hayır hayır...",
"VO__HUGO__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__3": "Bu tarafa geliyor!",
"VO__HUGO__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__4": "Bizi görecek!",
"VO__HUGO__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__1": "Her yere bakıyorlar...",
"VO__HUGO__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__2": "Tam yollarının üstündeyiz!",
"VO__HUGO__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__3": "Geliyorlar Amicia!",
"VO__HUGO__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__4": "Bizi görecekler!",
"VO__HUGO__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__1": "Ah... ah...",
"VO__HUGO__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__2": "Amicia...!",
"VO__HUGO__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__3": "Sessiz olalım...",
"VO__HUGO__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__4": "Korkuyorum.",
"VO__HUGO__GENERIC__EVENT__JOIN_AMICIA_LONG__001__M__1": "Lütfen beni yine bırakma...",
"VO__HUGO__GENERIC__EVENT__JOIN_AMICIA_LONG__001__M__2": "Bu sefer birlikte kalabilir miyiz?",
"VO__HUGO__GENERIC__EVENT__JOIN_AMICIA_LONG__001__M__3": "Uzaktayken hoşuma gitmiyor...",
"VO__HUGO__GENERIC__EVENT__JOIN_AMICIA_LONG_DISCREET__001__M__1": "Burada olmana çok sevindim!",
"VO__HUGO__GENERIC__EVENT__JOIN_AMICIA_LONG_DISCREET__001__M__2": "Hiç dönmeyeceksin sandım.",
"VO__HUGO__GENERIC__EVENT__JOIN_AMICIA_LONG_DISCREET__001__M__3": "Yalnız kalmaktan korktum.",
"VO__HUGO__GENERIC__INTERACT__ABILITY_LOCKED__001__M__1": "Sıçanları hissetmiyorum, Amicia...",
"VO__HUGO__GENERIC__INTERACT__ABILITY_LOCKED__001__M__2": "Sıçanlar burada değil...",
"VO__HUGO__GENERIC__INTERACT__ABILITY_LOCKED__001__M__3": "Sıçanları hissedemiyorum...",
"VO__HUGO__GENERIC__INTERACT__ABILITY_LOCKED_DISCREET__001__M__1": "Sıçanlar etrafta değil Amicia...",
"VO__HUGO__GENERIC__INTERACT__ABILITY_LOCKED_DISCREET__001__M__2": "Etrafta sıçan yok Amicia.",
"VO__HUGO__GENERIC__INTERACT__ABILITY_LOCKED_DISCREET__001__M__3": "Sıçanları sezemiyorum...",
"VO__HUGO__GENERIC__INTERACT__ABILITY_NOT_USABLE__001__M__1": "Çok fazlalar!",
"VO__HUGO__GENERIC__INTERACT__ABILITY_NOT_USABLE__001__M__2": "Çok fazla sıçan var, Amicia!",
"VO__HUGO__GENERIC__INTERACT__ABILITY_NOT_USABLE__001__M__3": "Çok fazlalar!",
"VO__HUGO__GENERIC__INTERACT__ABILITY_NOT_USABLE_DISCREET__001__M__1": "Çok fazla sıçan var!",
"VO__HUGO__GENERIC__INTERACT__ABILITY_NOT_USABLE_DISCREET__001__M__2": "Çok fazlalar, Amicia...",
"VO__HUGO__GENERIC__INTERACT__ABILITY_NOT_USABLE_DISCREET__001__M__3": "Çok fazlalar, beni dinlemezler...",
"VO__HUGO__GENERIC__INTERACT__CANT_JOIN__001__M__1": "Amicia, sana ulaşamıyorum!",
"VO__HUGO__GENERIC__INTERACT__CANT_JOIN__001__M__2": "Yol kapalı Amicia!",
"VO__HUGO__GENERIC__INTERACT__CANT_JOIN__001__M__3": "Daha ileri gidemiyorum!",
"VO__HUGO__GENERIC__INTERACT__CANT_JOIN__001__M__4": "Sıkışıp kaldım Amicia!",
"VO__HUGO__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__1": "Yol kapalı Amicia!",
"VO__HUGO__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__2": "Sana ulaşamıyorum, Amicia...",
"VO__HUGO__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__3": "Daha ileri gidemiyorum...",
"VO__HUGO__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__4": "Amicia, sıkıştım...",
"VO__HUGO__GENERIC__INTERACT__CAUGHT__001__M__1": "Kurtar beni Amicia!",
"VO__HUGO__GENERIC__INTERACT__CAUGHT__001__M__2": "Amicia! Amicia!",
"VO__HUGO__GENERIC__INTERACT__CAUGHT__001__M__3": "Amicia! Yardım et!",
"VO__HUGO__GENERIC__INTERACT__CAUGHT__001__M__4": "Beni öldürecek!",
"VO__HUGO__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__1": "Ne yapacağız Amicia?!",
"VO__HUGO__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__2": "Burada olduğumuzu biliyorlar!",
"VO__HUGO__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__3": "Geliyorlar!",
"VO__HUGO__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__4": "Bizi gördüler!",
"VO__HUGO__GENERIC__INTERACT__LOSS__001__M__1": "Amicia! HAYIR!",
"VO__HUGO__GENERIC__INTERACT__LOSS__001__M__2": "Amicia! AMICIA!",
"VO__HUGO__GENERIC__INTERACT__LOSS__001__M__3": "Hayııır! AMICIA!",
"VO__HUGO__GENERIC__INTERACT__LOSS__001__M__4": "AMICIA!",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_COOLDOWN__001__M__1": "Başım hâlâ dönüyor...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_COOLDOWN__001__M__2": "Başım çok ağrıyor...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_COOLDOWN__001__M__3": "Çok... yorgunum...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_COOLDOWN__001__M__4": "Ben... yapamıyorum...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_RELEASE__001__M__1": "Neredeyse... kazanıyorlardı, Amicia...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_RELEASE__001__M__2": "Ben... biliyorum...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_RELEASE__001__M__3": "Ben... özür dilerim...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_RELEASE__001__M__4": "Onlar... bize geliyorlardı...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_STEP_1__001__M__1": "Evet...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_STEP_1__001__M__2": "Yapabilirim...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_STEP_1__001__M__3": "Deniyorum, Amicia...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_STEP_1__001__M__4": "İyiyim...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_STEP_2__001__M__2": "Yapabilirim...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_STEP_2__001__M__3": "Ben... iyiyim...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_STEP_2__001__M__4": "Devam edebilirim...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_STEP_3__001__M__1": "Amicia...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_STEP_3__001__M__2": "Başım...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_STEP_3__001__M__3": "Onlar... karşı koyuyorlar...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_STEP_3__001__M__4": "Ben... yapamıyorum...",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_TRIGGERED__001__M__3": "Argh!",
"VO__HUGO__GENERIC__INTERACT__OVERCHARGE_TRIGGERED__001__M__4": "Amicia!",
"VO__HUGO__GENERIC__INTERACT__QUICK_TRAVERSAL__001__M__1": "Umpf...",
"VO__HUGO__GENERIC__INTERACT__QUICK_TRAVERSAL__001__M__2": "Ohf...",
"VO__HUGO__GENERIC__INTERACT__QUICK_TRAVERSAL__001__M__3": "Hımf...",
"VO__HUGO__GENERIC__INTERACT__QUICK_TRAVERSAL__001__M__4": "Öf...",
"VO__HUGO__GENERIC__INTERACT__QUICK_TRAVERSAL_STRESSED__001__M__1": "Umpf!",
"VO__HUGO__GENERIC__INTERACT__QUICK_TRAVERSAL_STRESSED__001__M__2": "Ohf!",
"VO__HUGO__GENERIC__INTERACT__QUICK_TRAVERSAL_STRESSED__001__M__3": "Hımf!",
"VO__HUGO__GENERIC__INTERACT__QUICK_TRAVERSAL_STRESSED__001__M__4": "Öf!",
"VO__HUGO__GENERIC__INTERACT__RATCONTROLFAIL_FIRE__001__M__1": "Işık onları engelliyor!",
"VO__HUGO__GENERIC__INTERACT__RATCONTROLFAIL_FIRE__001__M__2": "Ateş yollarına çıkıyor!",
"VO__HUGO__GENERIC__INTERACT__RATCONTROLFAIL_FIRE__001__M__3": "Ateş onları engelliyor!",
"VO__HUGO__GENERIC__INTERACT__RATCONTROLFAIL_FIRE__001__M__4": "Yapamıyorlar... ışık yüzünden!",
"VO__HUGO__GENERIC__INTERACT__RATCONTROLFAIL_RANGE__001__M__1": "Cevap vermiyorlar...",
"VO__HUGO__GENERIC__INTERACT__RATCONTROLFAIL_RANGE__001__M__2": "Beni dinlemek istemiyorlar...",
"VO__HUGO__GENERIC__INTERACT__RATCONTROLFAIL_RANGE__001__M__3": "Dinlemiyorlar...",
"VO__HUGO__GENERIC__INTERACT__RATCONTROLFAIL_RANGE__001__M__4": "Beni dinlemiyorlar...",
"VO__HUGO__GENERIC__INTERACT__SAVED__001__M__1": "Beni korkuttu...",
"VO__HUGO__GENERIC__INTERACT__SAVED__001__M__2": "Bana zarar verecek sandım...",
"VO__HUGO__GENERIC__INTERACT__SAVED__001__M__3": "Korktum Amicia...",
"VO__HUGO__GENERIC__INTERACT__SAVED__001__M__4": "Evet...",
"VO__HUGO__GENERIC__INTERACT__STUCK__001__M__1": "Ama oraya ulaşamıyorum!",
"VO__HUGO__GENERIC__INTERACT__STUCK__001__M__2": "Yapamıyorum Amicia!",
"VO__HUGO__GENERIC__INTERACT__STUCK__001__M__3": "Oraya gitmek imkânsız.",
"VO__HUGO__GENERIC__INTERACT__STUCK__001__M__4": "Ona erişemiyorum!",
"VO__HUGO__GENERIC__INTERACT__STUCK_CLIMB__001__M__1": "Çok yüksek Amicia!",
"VO__HUGO__GENERIC__INTERACT__STUCK_CLIMB__001__M__2": "Oraya çıkamıyorum!",
"VO__HUGO__GENERIC__INTERACT__STUCK_CLIMB__001__M__3": "Erişemiyorum!",
"VO__HUGO__GENERIC__INTERACT__STUCK_CLIMB__001__M__4": "Yardım lazım Amicia!",
"VO__HUGO__GENERIC__INTERACT__STUCK_CLIMB_DISCREET__001__M__1": "Çıkmam için bir el at!",
"VO__HUGO__GENERIC__INTERACT__STUCK_CLIMB_DISCREET__001__M__2": "Beni oraya çıkar lütfen...",
"VO__HUGO__GENERIC__INTERACT__STUCK_CLIMB_DISCREET__001__M__3": "Beni yukarı çek lütfen...",
"VO__HUGO__GENERIC__INTERACT__STUCK_CLIMB_DISCREET__001__M__4": "Yardımına ihtiyacım var Amicia...",
"VO__HUGO__GENERIC__INTERACT__STUCK_DISCREET__001__M__1": "Oraya ulaşamıyorum.",
"VO__HUGO__GENERIC__INTERACT__STUCK_DISCREET__001__M__2": "Amicia oraya geçemiyorum.",
"VO__HUGO__GENERIC__INTERACT__STUCK_DISCREET__001__M__3": "Oraya gitmek mümkün değil...",
"VO__HUGO__GENERIC__INTERACT__STUCK_DISCREET__001__M__4": "Ona ulaşamıyorum...",
"VO__HUGO__GENERIC__INTERACT__STUCK_STRESSED__001__M__1": "Oraya tek başıma gidemem.",
"VO__HUGO__GENERIC__INTERACT__STUCK_STRESSED__001__M__2": "Yapamıyorum işte.",
"VO__HUGO__GENERIC__INTERACT__STUCK_STRESSED__001__M__3": "Oraya gidemiyorum.",
"VO__HUGO__GENERIC__INTERACT__STUCK_STRESSED__001__M__4": "Sanmıyorum yapabileceğimi.",
"VO__HUGO__GENERIC__INTERACT__YES__001__M__1": "Evet!",
"VO__HUGO__GENERIC__INTERACT__YES__001__M__2": "Tamam!",
"VO__HUGO__GENERIC__INTERACT__YES__001__M__3": "Hı hı!",
"VO__HUGO__GENERIC__INTERACT__YES__001__M__4": "Pekâlâ!",
"VO__HUGO__GENERIC__INTERACT__YES_DISCREET__001__M__1": "Deneyeceğim...",
"VO__HUGO__GENERIC__INTERACT__YES_DISCREET__001__M__2": "Geliyorum...",
"VO__HUGO__GENERIC__INTERACT__YES_DISCREET__001__M__3": "Elimden geleni yapacağım...",
"VO__HUGO__GENERIC__INTERACT__YES_DISCREET__001__M__4": "Elbette...",
"VO__HUGO__GENERIC__INTERACT__YES_STRESSED__001__M__1": "Anlaşıldı!",
"VO__HUGO__GENERIC__INTERACT__YES_STRESSED__001__M__2": "Tabii!",
"VO__HUGO__GENERIC__INTERACT__YES_STRESSED__001__M__3": "Yaparım!",
"VO__HUGO__GENERIC__INTERACT__YES_STRESSED__001__M__4": "Anladım!",
"VO__HUGO__GENERIC__RESPONSE__BUSY__001__M__1": "Önce bunu bitirmem lazım.",
"VO__HUGO__GENERIC__RESPONSE__BUSY__001__M__2": "Henüz olmaz, meşgulüm.",
"VO__HUGO__GENERIC__RESPONSE__BUSY__001__M__3": "Zaten meşgulüm.",
"VO__HUGO__GENERIC__RESPONSE__BUSY__001__M__4": "Üzgünüm ama zaten bir şey yapıyorum.",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW__001__M__1": "Geliyorum!",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW__001__M__2": "Hemen oradayım.",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW__001__M__3": "Tam buradayım.",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW__001__M__4": "Geliyorum!",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__1": "Geliyorum...",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__2": "Buradayım...",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__3": "Geliyorum.",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__4": "Buradayım, Amicia.",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__1": "Geliyorum Amicia!",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__2": "Tamam, Amicia.",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__3": "Seni takip edeceğim.",
"VO__HUGO__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__4": "Geliyorum.",
"VO__HUGO__GENERIC__RESPONSE__STAY__001__M__1": "Anladım, sessiz olacağım.",
"VO__HUGO__GENERIC__RESPONSE__STAY__001__M__2": "Tamam, burada kalırım.",
"VO__HUGO__GENERIC__RESPONSE__STAY__001__M__3": "Çok uzun kalma.",
"VO__HUGO__GENERIC__RESPONSE__STAY__001__M__4": "Çabuk dön.",
"VO__HUGO__GENERIC__RESPONSE__STAY_DISCREET__001__M__1": "Çok uzun kalma...",
"VO__HUGO__GENERIC__RESPONSE__STAY_DISCREET__001__M__2": "Benden çok uzaklaşma...",
"VO__HUGO__GENERIC__RESPONSE__STAY_DISCREET__001__M__3": "Yolda dikkatli ol...",
"VO__HUGO__GENERIC__RESPONSE__STAY_DISCREET__001__M__4": "Tam burada kalacağım.",
"VO__HUGO__GENERIC__RESPONSE__STAY_STRESSED__001__M__1": "Tamam, seni burada bekleyeceğim!",
"VO__HUGO__GENERIC__RESPONSE__STAY_STRESSED__001__M__2": "Kalıyorum.",
"VO__HUGO__GENERIC__RESPONSE__STAY_STRESSED__001__M__3": "Kıpırdamıyorum, söz!",
"VO__HUGO__GENERIC__RESPONSE__STAY_STRESSED__001__M__4": "Burada bekleyeceğim!",
"VO__LUCAS__GENERIC__EVENT__CAUGHT_RATS__001__M__1": "Yardım et!",
"VO__LUCAS__GENERIC__EVENT__CAUGHT_RATS__001__M__2": "Hayır! Amicia!",
"VO__LUCAS__GENERIC__EVENT__CAUGHT_RATS__001__M__3": "Yardım edin!",
"VO__LUCAS__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__1": "Saklanmamız lazım!",
"VO__LUCAS__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__2": "Gözden uzak dur...",
"VO__LUCAS__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__3": "Buraya geliyor...",
"VO__LUCAS__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__4": "Olamaz...",
"VO__LUCAS__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__1": "Bizi bulacaklar!",
"VO__LUCAS__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__2": "Buraya geliyorlar...",
"VO__LUCAS__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__3": "Bizi fark edecekler!",
"VO__LUCAS__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__4": "Yer değiştirmemiz lazım!",
"VO__LUCAS__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__1": "Olamaz...",
"VO__LUCAS__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__2": "Hayır...",
"VO__LUCAS__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__3": "Dikkatli ol...",
"VO__LUCAS__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__4": "Dikkat et...",
"VO__LUCAS__GENERIC__EVENT__LUCAS_FOGWALK_SUCCESS__001__M__1": "Çabuk! Fazla vaktimiz yok!",
"VO__LUCAS__GENERIC__EVENT__LUCAS_FOGWALK_SUCCESS__001__M__2": "Acele et! Birazdan dağılacak!",
"VO__LUCAS__GENERIC__EVENT__LUCAS_FOGWALK_SUCCESS__001__M__3": "Uzun sürmez, hemen gitmeliyiz!",
"VO__LUCAS__GENERIC__INTERACT__CANT_JOIN__001__M__1": "Seni takip edemiyorum Amicia!",
"VO__LUCAS__GENERIC__INTERACT__CANT_JOIN__001__M__2": "Gelemiyorum Amicia!",
"VO__LUCAS__GENERIC__INTERACT__CANT_JOIN__001__M__3": "Sana ulaşamıyorum!",
"VO__LUCAS__GENERIC__INTERACT__CANT_JOIN__001__M__4": "Sana erişemiyorum Amicia!",
"VO__LUCAS__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__1": "Seni takip edemiyorum, Amicia...",
"VO__LUCAS__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__2": "Amicia, yanına gelemiyorum...",
"VO__LUCAS__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__3": "Sana ulaşamıyorum, Amicia...",
"VO__LUCAS__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__4": "Amicia, sana erişemiyorum...",
"VO__LUCAS__GENERIC__INTERACT__CAUGHT__001__M__1": "Yardım et!",
"VO__LUCAS__GENERIC__INTERACT__CAUGHT__001__M__2": "Kurtar beni!",
"VO__LUCAS__GENERIC__INTERACT__CAUGHT__001__M__3": "Amicia!",
"VO__LUCAS__GENERIC__INTERACT__CAUGHT__001__M__4": "Gel kurtar beni lütfen!",
"VO__LUCAS__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__1": "Fark edildik!",
"VO__LUCAS__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__2": "Bizi buldular!",
"VO__LUCAS__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__3": "Üstümüzdeler!",
"VO__LUCAS__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__4": "Bizi gördüler!",
"VO__LUCAS__GENERIC__INTERACT__JOIN_AMICIA_LONG__001__M__1": "Seni tekrar görmek güzel.",
"VO__LUCAS__GENERIC__INTERACT__JOIN_AMICIA_LONG__001__M__2": "Endişelenmeye başlamıştım.",
"VO__LUCAS__GENERIC__INTERACT__JOIN_AMICIA_LONG__001__M__3": "Döndüğüne sevindim.",
"VO__LUCAS__GENERIC__INTERACT__JOIN_AMICIA_LONG__001__M__4": "Seni tekrar görmek mutluluk verici.",
"VO__LUCAS__GENERIC__INTERACT__JOIN_AMICIA_LONG_DISCREET__001__M__1": "İşte buradasın!",
"VO__LUCAS__GENERIC__INTERACT__JOIN_AMICIA_LONG_DISCREET__001__M__2": "Tekrar hoş geldin.",
"VO__LUCAS__GENERIC__INTERACT__JOIN_AMICIA_LONG_DISCREET__001__M__3": "Senin için çok endişelendim...",
"VO__LUCAS__GENERIC__INTERACT__JOIN_AMICIA_LONG_DISCREET__001__M__4": "Seni görünce çok rahatladım.",
"VO__LUCAS__GENERIC__INTERACT__LOSS__001__M__1": "Hayır! Amicia! HAYIR!",
"VO__LUCAS__GENERIC__INTERACT__LOSS__001__M__2": "Olamaz! Hayır hayır hayır hayır!",
"VO__LUCAS__GENERIC__INTERACT__LOSS__001__M__3": "Hayır! AMICIA!",
"VO__LUCAS__GENERIC__INTERACT__LOSS__001__M__4": "Hayır! HAYIR!",
"VO__LUCAS__GENERIC__INTERACT__SAVED__001__M__1": "İyiyim, senin sayende...",
"VO__LUCAS__GENERIC__INTERACT__SAVED__001__M__2": "Evet... Beni kurtardığın için sağ ol.",
"VO__LUCAS__GENERIC__INTERACT__SAVED__001__M__3": "Sanırım...",
"VO__LUCAS__GENERIC__INTERACT__SAVED__001__M__4": "Ben... sanırım iyiyim.",
"VO__LUCAS__GENERIC__INTERACT__STUCK__001__M__1": "Sıkıştım.",
"VO__LUCAS__GENERIC__INTERACT__STUCK__001__M__2": "Ona ulaşamıyorum.",
"VO__LUCAS__GENERIC__INTERACT__STUCK__001__M__3": "Ona erişemiyorum.",
"VO__LUCAS__GENERIC__INTERACT__STUCK__001__M__4": "Üzgünüm ama oraya ulaşamıyorum.",
"VO__LUCAS__GENERIC__INTERACT__STUCK_DISCREET__001__M__1": "Başaramayacağım...",
"VO__LUCAS__GENERIC__INTERACT__STUCK_DISCREET__001__M__2": "Ona erişemeyeceğim.",
"VO__LUCAS__GENERIC__INTERACT__STUCK_DISCREET__001__M__3": "Oraya gitmek mümkün değil!",
"VO__LUCAS__GENERIC__INTERACT__STUCK_DISCREET__001__M__4": "Oraya geçemiyorum. Üzgünüm.",
"VO__LUCAS__GENERIC__INTERACT__STUCK_STRESSED__001__M__1": "Oraya gidemiyorum.",
"VO__LUCAS__GENERIC__INTERACT__STUCK_STRESSED__001__M__2": "Oraya gitmemin imkânı yok.",
"VO__LUCAS__GENERIC__INTERACT__STUCK_STRESSED__001__M__3": "Oraya gidemiyorum.",
"VO__LUCAS__GENERIC__INTERACT__STUCK_STRESSED__001__M__4": "Mümkün değil!",
"VO__LUCAS__GENERIC__INTERACT__YES__001__M__1": "Tabii ki!",
"VO__LUCAS__GENERIC__INTERACT__YES__001__M__2": "Elbette.",
"VO__LUCAS__GENERIC__INTERACT__YES__001__M__3": "Pekâlâ!",
"VO__LUCAS__GENERIC__INTERACT__YES__001__M__4": "Tamam!",
"VO__LUCAS__GENERIC__INTERACT__YES_DISCREET__001__M__1": "Anlaşıldı!",
"VO__LUCAS__GENERIC__INTERACT__YES_DISCREET__001__M__2": "Evet!",
"VO__LUCAS__GENERIC__INTERACT__YES_DISCREET__001__M__3": "Geliyorum!",
"VO__LUCAS__GENERIC__INTERACT__YES_DISCREET__001__M__4": "Hallediyorum!",
"VO__LUCAS__GENERIC__INTERACT__YES_STRESSED__001__M__1": "Tamam!",
"VO__LUCAS__GENERIC__INTERACT__YES_STRESSED__001__M__2": "Anlaştık!",
"VO__LUCAS__GENERIC__INTERACT__YES_STRESSED__001__M__3": "Hemen!",
"VO__LUCAS__GENERIC__INTERACT__YES_STRESSED__001__M__4": "Derhal!",
"VO__LUCAS__GENERIC__ORDER__LUCAS_FOGWALK_ORDER__001__M__1": "Evet, duman çıkınca hızlı hareket et!",
"VO__LUCAS__GENERIC__ORDER__LUCAS_FOGWALK_ORDER__001__M__2": "Tabii! Hazır ol!",
"VO__LUCAS__GENERIC__ORDER__LUCAS_FOGWALK_ORDER__001__M__3": "İyi fikir. Parlamada harekete geç.",
"VO__LUCAS__GENERIC__ORDER__LUCAS_FOGWALK_ORDER_DISCREET__001__M__1": "Hallederim. Hazır ol.",
"VO__LUCAS__GENERIC__ORDER__LUCAS_FOGWALK_ORDER_DISCREET__001__M__2": "Evet! Duman yayılınca hareket et...",
"VO__LUCAS__GENERIC__ORDER__LUCAS_FOGWALK_ORDER_DISCREET__001__M__3": "Tamam! Harekete hazır ol...",
"VO__LUCAS__GENERIC__PATROL__REACTION__001__M__1": "Orada kim pusuya yatmış olabilir?!",
"VO__LUCAS__GENERIC__PATROL__REACTION__001__M__2": "Sen miydin, Kral Hugo?",
"VO__LUCAS__GENERIC__PATROL__REACTION__001__M__3": "Duyularım bir şey sezdi!",
"VO__LUCAS__GENERIC__PATROL__RESUME__001__M__1": "Keskin bakışlarımdan sonsuza dek kaçamazsın!",
"VO__LUCAS__GENERIC__PATROL__RESUME__001__M__2": "Uzun süre saklı kalamayacaksın! Korkunun izini süreceğim!",
"VO__LUCAS__GENERIC__PATROL__RESUME__001__M__3": "Şimdilik beni atlatabilirsin, ama seni bulacağım! Bu kaçınılmaz!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_ALONE__001__M__1": "Hain Lucas peşinde!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_ALONE__001__M__2": "Pençemden kaçmaya hiç umudun yok!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_ALONE__001__M__3": "Yakında gücüm karşısında diz çökeceksin...",
"VO__LUCAS__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__1": "Artık seni yakaladım, Sör Hugo!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__2": "Görüyorum seni! Bitti!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__3": "Tahttan indirildin, yufka yürekli kralım!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__4": "Bak kim şatosunu kaybetti!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__5": "Seni gördüm! Her şey bitti!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__6": "Hain, gözlerini sana dikti! Bitti!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__7": "Seni görmeyeceğimi mi sandın?!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__8": "Evet! Hain Lucas artık muzaffer!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__9": "İşte buradasın! Kral düştü!",
"VO__LUCAS__GENERIC__PATROL__SEARCH_FOUND_ALONE__001__M__10": "Buldum seni! Gücümü küçümsedin!",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__1": "Ne?! Her Şeyi Duyan Lucas'ı kandırmaya kalkma!",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__2": "Mistik ruhani yeteneklerim tekrar yakında olduğunu sezdi!",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_AGAIN_SPOTTER_ALONE__001__M__3": "Oyunlar yeter... Sen benimsin... benim!",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__1": "Seni duyabiliyorum... Keskin duyularımı kandırabileceğini mi sanıyorsun?",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__2": "Bu kadar gürültü çıkarınca seni takip etmek kolay...",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__3": "Bu, gazabımdan korkan birinin sesi!",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__4": "Ne çok gürültü! Beni doğruca sana götüreceksin!",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__5": "Acınası bir kaçış girişimi tespit ettim!",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__6": "Bir canavar olabilirim ama sağır değilim!",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_AUDIO_SPOTTER_ALONE__001__M__7": "Seni duyabiliyorum! Daha dikkatli basmalısın...",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__1": "O da neydi? Keskin duyularımdan hiçbir şey kaçmaz!",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__2": "Ha? Oradaysan, seni bulacağım!",
"VO__LUCAS__GENERIC__PATROL__SUSPICION_SPOTTER_ALONE__001__M__3": "Gözlerim beni mi yanıltıyor? Yoksa burada gerçekten biri mi var?",
"VO__LUCAS__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__1": "Orada mısın?! Nerede olabilirsin?!",
"VO__LUCAS__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__2": "Beceriklisin! Ama yine de seni bulacağım!",
"VO__LUCAS__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__3": "Seni yakalamam an meselesi!",
"VO__LUCAS__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__4": "Sabrım daha önce çok kez sınandı. Seni bulacağım.",
"VO__LUCAS__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__5": "Nereye gittin, küçük kral?",
"VO__LUCAS__GENERIC__PATROL__SWITCH_SEARCH_ALONE__001__M__6": "Benden uzun süre saklanamazsın!",
"VO__LUCAS__GENERIC__RESPONSE__BUSY__001__M__1": "Aynı anda iki iş yapamam!",
"VO__LUCAS__GENERIC__RESPONSE__BUSY__001__M__2": "Zaten meşgulüm.",
"VO__LUCAS__GENERIC__RESPONSE__BUSY__001__M__3": "Yapamam! Zaten bir şey yapıyorum!",
"VO__LUCAS__GENERIC__RESPONSE__BUSY__001__M__4": "Zaten başka bir işteyim...",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW__001__M__1": "Anlaşıldı, hemen arkandayım.",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW__001__M__2": "Elbette, seninleyim.",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW__001__M__3": "Seninle kalacağım!",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW__001__M__4": "Tabii, sana katılacağım.",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__1": "Tabii, takip edeceğim.",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__2": "Seninle kalacağım.",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__3": "Yanındayım.",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__4": "Buradayım.",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__1": "Tabii, gidelim.",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__2": "Seninle geleceğim.",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__3": "Elbette, yanındayım.",
"VO__LUCAS__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__4": "Seninleyim.",
"VO__LUCAS__GENERIC__RESPONSE__STAY__001__M__1": "Anlaşıldı, yakında görüşürüz.",
"VO__LUCAS__GENERIC__RESPONSE__STAY__001__M__2": "Çok uzaklaşma.",
"VO__LUCAS__GENERIC__RESPONSE__STAY__001__M__3": "Çok uzun kalma...",
"VO__LUCAS__GENERIC__RESPONSE__STAY__001__M__4": "Sen dönene kadar kıpırdamam.",
"VO__LUCAS__GENERIC__RESPONSE__STAY_DISCREET__001__M__1": "Sen dönene kadar seni bekleyeceğim.",
"VO__LUCAS__GENERIC__RESPONSE__STAY_DISCREET__001__M__2": "Elbette, burada bekliyorum.",
"VO__LUCAS__GENERIC__RESPONSE__STAY_DISCREET__001__M__3": "Güvende ol, burada kalacağım.",
"VO__LUCAS__GENERIC__RESPONSE__STAY_DISCREET__001__M__4": "Tabii, çabuk dön!",
"VO__LUCAS__GENERIC__RESPONSE__STAY_STRESSED__001__M__1": "Çabuk dön!",
"VO__LUCAS__GENERIC__RESPONSE__STAY_STRESSED__001__M__2": "Tamam! Burada kalacağım!",
"VO__LUCAS__GENERIC__RESPONSE__STAY_STRESSED__001__M__3": "Burada bekleyeceğim, kendine dikkat et!",
"VO__LUCAS__GENERIC__RESPONSE__STAY_STRESSED__001__M__4": "Tamam! Dikkatli ol!",
"VO__SOPHIA__GENERIC__EVENT__CAUGHT_RATS__001__M__1": "Üstüme çıktılar! Çekin onları!",
"VO__SOPHIA__GENERIC__EVENT__CAUGHT_RATS__001__M__2": "Yardııım!",
"VO__SOPHIA__GENERIC__EVENT__CAUGHT_RATS__001__M__3": "Çekin onları üstümden!",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__1": "Dikkatli ol...",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__2": "Burada olduğumuzu biliyor...",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__3": "Hareket edelim!",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_DISCREET__001__M__4": "Bizi arıyor...",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__1": "Bize yaklaşıyorlar!",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__2": "Burada olduğumuzu biliyorlar...",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__3": "Bizi fark ettiler...!",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_BEGIN_INVESTIGATE_PLURAL_DISCREET__001__M__4": "Bizi arıyorlar...",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__1": "Sakin...",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__2": "Dikkatli ol...",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__3": "Sessiz ol...",
"VO__SOPHIA__GENERIC__EVENT__ENEMY_REACT_DISCREET__001__M__4": "Ses çıkarma...",
"VO__SOPHIA__GENERIC__EVENT__SOPHIA_PRISM_DISTRACT_SUCCESS_DISCREET__001__M__1": "İşi öyle kolaylaştırıyorlar ki.",
"VO__SOPHIA__GENERIC__EVENT__SOPHIA_PRISM_DISTRACT_SUCCESS_DISCREET__001__M__2": "Hadi bakalım, işe yarıyor!",
"VO__SOPHIA__GENERIC__EVENT__SOPHIA_PRISM_DISTRACT_SUCCESS_DISCREET__001__M__3": "Her seferinde işe yarıyor.",
"VO__SOPHIA__GENERIC__EVENT__SOPHIA_PRISM_REPULSE_WARNING_OBSTACLE__001__M__1": "Dikkat, prizmam için ışık şu an zar zor yetiyor.",
"VO__SOPHIA__GENERIC__EVENT__SOPHIA_PRISM_REPULSE_WARNING_OBSTACLE__001__M__2": "Bekle, çok uzaklaşma, prizmam için fazla karanlık oluyor.",
"VO__SOPHIA__GENERIC__EVENT__SOPHIA_PRISM_REPULSE_WARNING_OBSTACLE__001__M__3": "Prizmam buraya pek ışık almıyor. Dikkatli ol.",
"VO__SOPHIA__GENERIC__INTERACT__CANT_JOIN__001__M__1": "Elimden geleni yapıyorum ama sana katılamıyorum.",
"VO__SOPHIA__GENERIC__INTERACT__CANT_JOIN__001__M__2": "Sana katılmak mümkün değil!",
"VO__SOPHIA__GENERIC__INTERACT__CANT_JOIN__001__M__3": "Seni takip edemiyorum.",
"VO__SOPHIA__GENERIC__INTERACT__CANT_JOIN__001__M__4": "Üzgünüm, sana ulaşamıyorum.",
"VO__SOPHIA__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__1": "Şimdilik sana ulaşamıyorum.",
"VO__SOPHIA__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__2": "Şu an sana katılamıyorum.",
"VO__SOPHIA__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__3": "Amicia, seni takip edemiyorum.",
"VO__SOPHIA__GENERIC__INTERACT__CANT_JOIN_DISCREET__001__M__4": "Yol şu an güvenli değil.",
"VO__SOPHIA__GENERIC__INTERACT__CAUGHT__001__M__1": "Çabuk yardım et! Acele!",
"VO__SOPHIA__GENERIC__INTERACT__CAUGHT__001__M__2": "Yardımına ihtiyacım var Amicia!",
"VO__SOPHIA__GENERIC__INTERACT__CAUGHT__001__M__3": "Lütfen, yardımıma koş!",
"VO__SOPHIA__GENERIC__INTERACT__CAUGHT__001__M__4": "Yardım et lütfen!",
"VO__SOPHIA__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__1": "Üstümüzdeler!",
"VO__SOPHIA__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__2": "Doğruca üstümüze geliyorlar.",
"VO__SOPHIA__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__3": "Bizden haberleri var...",
"VO__SOPHIA__GENERIC__INTERACT__ENEMY_BEGIN_ALERT__001__M__4": "Üstümüzdeler!",
"VO__SOPHIA__GENERIC__INTERACT__JOIN_AMICIA_LONG__001__M__1": "Beni özlediğin belli.",
"VO__SOPHIA__GENERIC__INTERACT__JOIN_AMICIA_LONG__001__M__2": "Döndüğüne sevindim!",
"VO__SOPHIA__GENERIC__INTERACT__JOIN_AMICIA_LONG__001__M__3": "Burada olmana sevindim!",
"VO__SOPHIA__GENERIC__INTERACT__JOIN_AMICIA_LONG__001__M__4": "Bak kim dönmüş!",
"VO__SOPHIA__GENERIC__INTERACT__JOIN_AMICIA_LONG_DISCREET__001__M__1": "Sonunda döndün!",
"VO__SOPHIA__GENERIC__INTERACT__JOIN_AMICIA_LONG_DISCREET__001__M__2": "Nihayet döndün.",
"VO__SOPHIA__GENERIC__INTERACT__JOIN_AMICIA_LONG_DISCREET__001__M__3": "İyi ki buradasın.",
"VO__SOPHIA__GENERIC__INTERACT__JOIN_AMICIA_LONG_DISCREET__001__M__4": "Seni görmek güzel.",
"VO__SOPHIA__GENERIC__INTERACT__LOSS__001__M__1": "Amicia! AMICIA!",
"VO__SOPHIA__GENERIC__INTERACT__LOSS__001__M__2": "HAYIR! AMICIA!",
"VO__SOPHIA__GENERIC__INTERACT__LOSS__001__M__3": "Hayır, hayır, hayır, HAYIR!",
"VO__SOPHIA__GENERIC__INTERACT__LOSS__001__M__4": "Olamaz! HAYIR!",
"VO__SOPHIA__GENERIC__INTERACT__SAVED__001__M__1": "Ucuz kurtardık! Sağ ol!",
"VO__SOPHIA__GENERIC__INTERACT__SAVED__001__M__2": "Evet, orada beni kurtardın.",
"VO__SOPHIA__GENERIC__INTERACT__SAVED__001__M__3": "Orada olman şansımaymış!",
"VO__SOPHIA__GENERIC__INTERACT__SAVED__001__M__4": "Görünüşe göre sana bir borcum daha var.",
"VO__SOPHIA__GENERIC__INTERACT__STUCK__001__M__1": "Oraya ulaşmak imkânsız.",
"VO__SOPHIA__GENERIC__INTERACT__STUCK__001__M__2": "Oraya ulaşmama imkân yok.",
"VO__SOPHIA__GENERIC__INTERACT__STUCK__001__M__3": "Maalesef burada sıkıştım.",
"VO__SOPHIA__GENERIC__INTERACT__STUCK__001__M__4": "Ona erişemiyorum!",
"VO__SOPHIA__GENERIC__INTERACT__STUCK_DISCREET__001__M__1": "Burada resmen sıkıştım!",
"VO__SOPHIA__GENERIC__INTERACT__STUCK_DISCREET__001__M__2": "Oraya geçişim yok.",
"VO__SOPHIA__GENERIC__INTERACT__STUCK_DISCREET__001__M__3": "Keşke... ama oraya gidemiyorum.",
"VO__SOPHIA__GENERIC__INTERACT__STUCK_DISCREET__001__M__4": "Oraya geçemiyorum işte...",
"VO__SOPHIA__GENERIC__INTERACT__STUCK_STRESSED__001__M__1": "Önüm kapalı...",
"VO__SOPHIA__GENERIC__INTERACT__STUCK_STRESSED__001__M__2": "Oraya gidemiyorum.",
"VO__SOPHIA__GENERIC__INTERACT__STUCK_STRESSED__001__M__3": "Oraya ulaşamıyorum.",
"VO__SOPHIA__GENERIC__INTERACT__STUCK_STRESSED__001__M__4": "Oraya gidemem, canım.",
"VO__SOPHIA__GENERIC__INTERACT__YES__001__M__1": "Bitmiş bil.",
"VO__SOPHIA__GENERIC__INTERACT__YES__001__M__2": "Memnuniyetle.",
"VO__SOPHIA__GENERIC__INTERACT__YES__001__M__3": "Tamamdır!",
"VO__SOPHIA__GENERIC__INTERACT__YES__001__M__4": "Hadi yapalım.",
"VO__SOPHIA__GENERIC__INTERACT__YES_DISCREET__001__M__1": "Ben hallederim.",
"VO__SOPHIA__GENERIC__INTERACT__YES_DISCREET__001__M__2": "Tabii ki...",
"VO__SOPHIA__GENERIC__INTERACT__YES_DISCREET__001__M__3": "Nasıl istersen...",
"VO__SOPHIA__GENERIC__INTERACT__YES_DISCREET__001__M__4": "Emrindeyim...",
"VO__SOPHIA__GENERIC__INTERACT__YES_STRESSED__001__M__1": "Tamam.",
"VO__SOPHIA__GENERIC__INTERACT__YES_STRESSED__001__M__2": "Anlaştık!",
"VO__SOPHIA__GENERIC__INTERACT__YES_STRESSED__001__M__3": "Hallettim!",
"VO__SOPHIA__GENERIC__INTERACT__YES_STRESSED__001__M__4": "Elbette...",
"VO__SOPHIA__GENERIC__ORDER__SOPHIA_PRISM_DISTRACT_ORDER_DISCREET__001__M__1": "Biraz ot yakma vakti...",
"VO__SOPHIA__GENERIC__ORDER__SOPHIA_PRISM_DISTRACT_ORDER_DISCREET__001__M__2": "Yanması uzun sürmez.",
"VO__SOPHIA__GENERIC__ORDER__SOPHIA_PRISM_DISTRACT_ORDER_DISCREET__001__M__3": "Işığı yakalayalım.",
"VO__SOPHIA__GENERIC__ORDER__SOPHIA_PRISM_REPULSE_ORDER__001__M__1": "Herkes ışıkta kalsın!",
"VO__SOPHIA__GENERIC__ORDER__SOPHIA_PRISM_REPULSE_ORDER__001__M__2": "Yanımda kalın!",
"VO__SOPHIA__GENERIC__ORDER__SOPHIA_PRISM_REPULSE_ORDER__001__M__3": "Bana yakın kalın!",
"VO__SOPHIA__GENERIC__RESPONSE__BUSY__001__M__1": "Şu an epey meşgulüm...",
"VO__SOPHIA__GENERIC__RESPONSE__BUSY__001__M__2": "Zaten meşgulüm, üzgünüm!",
"VO__SOPHIA__GENERIC__RESPONSE__BUSY__001__M__3": "Aynı anda iki iş, imkânsız.",
"VO__SOPHIA__GENERIC__RESPONSE__BUSY__001__M__4": "Bekle, zaten meşgulüm.",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW__001__M__1": "Tamam, gidelim.",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW__001__M__2": "Yoldayım.",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW__001__M__3": "Hemen arkandayım.",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW__001__M__4": "Yanındayım.",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__1": "Yoldayım...",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__2": "Yanında kalıyorum.",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__3": "Seni takip ediyorum.",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW_DISCREET__001__M__4": "Tamam, seninleyim.",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__1": "Elbette, seninleyim.",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__2": "Tamam, gidelim.",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__3": "Geliyorum!",
"VO__SOPHIA__GENERIC__RESPONSE__FOLLOW_STRESSED__001__M__4": "Hadi yapalım.",
"VO__SOPHIA__GENERIC__RESPONSE__STAY__001__M__1": "Başını derde sokmamaya çalış.",
"VO__SOPHIA__GENERIC__RESPONSE__STAY__001__M__2": "Çok uzun sürmesin.",
"VO__SOPHIA__GENERIC__RESPONSE__STAY__001__M__3": "Tabii, yerimden kıpırdamam.",
"VO__SOPHIA__GENERIC__RESPONSE__STAY__001__M__4": "Anlaşıldı, burada kalırım.",
"VO__SOPHIA__GENERIC__RESPONSE__STAY_DISCREET__001__M__1": "Tam burada duruyorum.",
"VO__SOPHIA__GENERIC__RESPONSE__STAY_DISCREET__001__M__2": "Tamam, çabuk dön.",
"VO__SOPHIA__GENERIC__RESPONSE__STAY_DISCREET__001__M__3": "Kıpırdamam, dikkatli ol!",
"VO__SOPHIA__GENERIC__RESPONSE__STAY_DISCREET__001__M__4": "Burada kalırım. Başını derde sokma.",
"VO__SOPHIA__GENERIC__RESPONSE__STAY_STRESSED__001__M__1": "Burada kalırım. Arkanı kolla.",
"VO__SOPHIA__GENERIC__RESPONSE__STAY_STRESSED__001__M__2": "Dikkatli ol. Kıpırdamayacağım.",
"VO__SOPHIA__GENERIC__RESPONSE__STAY_STRESSED__001__M__3": "Burada olacağım. Güvende ol.",
"VO__SOPHIA__GENERIC__RESPONSE__STAY_STRESSED__001__M__4": "Kıpırdamam. Çabuk dön.",
}
