# -*- coding: utf-8 -*-
# HUD kategorisi. Ozel isimler (AMICIA:, HUGO:, VAUDIN: vb.) builder tarafindan
# degistirilmez (sozlukte yer almaz). Yalnizca rol/etiket konusmacilar ceviridir.
T = {
"HUD__BUTTONS_A_CRAFT": "Üretmek için {STR_CRAFT} basılı tut",
"HUD__BUTTONS_A_FIRST_UPGRADE": "Sapanı onarmak için {STR_CRAFT} basılı tut",
"HUD__BUTTONS_A_UPGRADE": "Yükseltmek için {STR_CRAFT} basılı tut",
"HUD__BUTTONS_AUTO": "Otomatik",
"HUD__BUTTONS_BACK": "Geri",
"HUD__BUTTONS_CLOSE": "Kapat",
"HUD__BUTTONS_CONFIRM": "Onayla",
"HUD__BUTTONS_CONTINUE": "Devam et",
"HUD__BUTTONS_DEFAULT": "Varsayılan",
"HUD__BUTTONS_DETAILS": "Ayrıntılar",
"HUD__BUTTONS_E_CRAFT": "Üretmek için {STR_CRAFT} basılı tut",
"HUD__BUTTONS_EQUIP": "Donat",
"HUD__BUTTONS_NEXT": "İleri",
"HUD__BUTTONS_NO": "Hayır",
"HUD__BUTTONS_PLAY": "Oyna",
"HUD__BUTTONS_RESET": "Sıfırla",
"HUD__BUTTONS_SELECT": "Seç",
"HUD__BUTTONS_STOP": "Dur",
"HUD__BUTTONS_UNAVAILABLE": "Kullanılamaz",
"HUD__BUTTONS_UNEQUIP": "Çıkar",
"HUD__BUTTONS_YES": "Evet",
"HUD__CONTEXTUAL_COUNTER": "Karşıla",
"HUD__CONTEXTUAL_DISTRACT": "Dikkat dağıt",
"HUD__CONTEXTUAL_DROP": "Bırak",
"HUD__CONTEXTUAL_FREEZE": "Saklan",
"HUD__CONTEXTUAL_FREEZE_STOP": "Ayağa kalk",
"HUD__CONTEXTUAL_OPEN": "Aç",
"HUD__CONTEXTUAL_PYRITE_STOP": "Dur",
"HUD__CONTEXTUAL_RECYCLE": "Geri dönüştür",
"HUD__CONTEXTUAL_RELEASE": "Bırak",
"HUD__CONTEXTUAL_STAB": "Bıçakla",
"HUD__CONTEXTUAL_STARTLE": "Ürküt",
"HUD__CONTEXTUAL_STRIKE": "Vur",
"HUD__GAMEMENU_CRAFT_CATEGORY_MIXTURES": "Karışımlar",
"HUD__GAMEMENU_CRAFT_CATEGORY_PROJECTILES": "Mermiler",
"HUD__GAMEMENU_CRAFT_INVENTORY_FULL": "ENVANTER DOLU",
"HUD__GAMEMENU_INSUFFICIENT_MATERIALS": "YETERLİ MALZEME YOK",
"HUD__GAMEMENU_INSUFFICIENT_XP": "YETERLİ DENEYİM YOK",
"HUD__GAMEMENU_SKILLS_ALCHEMY": "Fırsatçılık",
"HUD__GAMEMENU_SKILLS_ALCHEMY_1_DESC": "Simya konusundaki üstün bilgisi sayesinde Amicia, simyasal cephaneyi daha hızlı üretir.",
"HUD__GAMEMENU_SKILLS_ALCHEMY_1_TITLE": "Simya bilgisi",
"HUD__GAMEMENU_SKILLS_ALCHEMY_2_DESC": "Simyasal işçiliğini en iyi hâle getiren Amicia, simyasal cephane üretirken kullandığı kaynaklardan birini koruma şansı elde eder.",
"HUD__GAMEMENU_SKILLS_ALCHEMY_2_TITLE": "Hiçbir Şey Boşa Gitmez",
"HUD__GAMEMENU_SKILLS_ALCHEMY_3_DESC": "Daha titiz davranan Amicia, simyasal cephane üretirken parça elde eder.",
"HUD__GAMEMENU_SKILLS_ALCHEMY_3_TITLE": "Malzeme ayrımı",
"HUD__GAMEMENU_SKILLS_ALCHEMY_4_DESC": "Sanatını mükemmelleştiren Amicia, aynı kaynaklarla bir tane daha fazla simyasal cephane üretir.",
"HUD__GAMEMENU_SKILLS_ALCHEMY_4_TITLE": "Saf ürün",
"HUD__GAMEMENU_SKILLS_COMBAT": "Saldırgan",
"HUD__GAMEMENU_SKILLS_COMBAT_1_DESC": "Çevresinin farkında olan Amicia, yakın dövüşte saldırırken düşmanları ateşe veya farelere iterek onları anında öldürebilir.",
"HUD__GAMEMENU_SKILLS_COMBAT_1_TITLE": "Pehlivan",
"HUD__GAMEMENU_SKILLS_COMBAT_2_DESC": "Saldırıya uğradığında sakinliğini koruyan Amicia, darbelerden daha hızlı toparlanır.",
"HUD__GAMEMENU_SKILLS_COMBAT_2_TITLE": "Toparlanma",
"HUD__GAMEMENU_SKILLS_COMBAT_3_DESC": "Hayati noktalarını bilen Amicia, düşmanları sapanıyla daha hızlı ve daha sessiz boğar.",
"HUD__GAMEMENU_SKILLS_COMBAT_3_TITLE": "Hayati noktalar",
"HUD__GAMEMENU_SKILLS_COMBAT_4_DESC": "Daha becerikli olan Amicia, silahlarını çok daha hızlı doldurur ve kullanır.",
"HUD__GAMEMENU_SKILLS_COMBAT_4_TITLE": "Hızlı Parmaklar",
"HUD__GAMEMENU_SKILLS_STEALTH": "İhtiyat",
"HUD__GAMEMENU_SKILLS_STEALTH_1_DESC": "Amicia hareket ederken daha az ses çıkarır ve böylece yakındaki düşmanların gözünden daha kolay kaçar.",
"HUD__GAMEMENU_SKILLS_STEALTH_1_TITLE": "Hafif adım",
"HUD__GAMEMENU_SKILLS_STEALTH_2_DESC": "Daha iyi bir denge duygusu sayesinde Amicia, çömelirken daha hızlı hareket eder.",
"HUD__GAMEMENU_SKILLS_STEALTH_2_TITLE": "Çeviklik",
"HUD__GAMEMENU_SKILLS_STEALTH_3_DESC": "Amicia, nesneleri daha uzağa fırlatmak için vücut duruşunu geliştirir.",
"HUD__GAMEMENU_SKILLS_STEALTH_3_TITLE": "Atış duruşu",
"HUD__GAMEMENU_SKILLS_STEALTH_4_DESC": "Amicia artık zayıf noktalarını görebildiği için zırhlı düşmanları arkadan bıçakla vurabilir.",
"HUD__GAMEMENU_SKILLS_STEALTH_4_TITLE": "Zırh delici",
"HUD__GAMEMENU_TAB_CODEX": "Kodeks",
"HUD__GAMEMENU_TAB_CRAFT": "Üretim",
"HUD__GAMEMENU_TAB_SKILLS": "Yetenekler",
"HUD__GAMEMENU_TAB_UPGRADE": "Yükseltme",
"HUD__GAMEMENU_UPGRADE_ALREADY_DONE": "ZATEN YÜKSELTİLDİ",
"HUD__GAMEMENU_UPGRADE_NEED_PREVIOUS": "ÖNCEKİ YÜKSELTME GEREKLİ",
"HUD__GAMEMENU_UPGRADES_ALCHEMY": "Simya",
"HUD__GAMEMENU_UPGRADES_ALCHEMY_1_DESC": "Donanımına yeni cepler dikmek, Amicia'nın ek simyasal cephane taşımasına yardımcı olur.",
"HUD__GAMEMENU_UPGRADES_ALCHEMY_1_TITLE": "Gizli cepler",
"HUD__GAMEMENU_UPGRADES_ALCHEMY_2_DESC": "Amicia, bir çömleği Ignifer ile birleştirerek fırlatıp düşmanları öldürmesini sağlayan simyasal cephaneyi geliştirir.",
"HUD__GAMEMENU_UPGRADES_ALCHEMY_2_TITLE": "Güçlü ateş",
"HUD__GAMEMENU_UPGRADES_ALCHEMY_3_DESC": "Amicia, Odoris'in ateşle temas ettiğinde patlayarak zırhsız düşmanları öldürmesini sağlamak için simyasal cephaneyi geliştirir.",
"HUD__GAMEMENU_UPGRADES_ALCHEMY_3_TITLE": "Kararsız tepkime",
"HUD__GAMEMENU_UPGRADES_CROSSBOW": "Arbalet",
"HUD__GAMEMENU_UPGRADES_CROSSBOW_1_DESC": "Arbaletin kolu için daha yumuşak bir metal seçmek, Amicia'nın onu çok daha hızlı doldurmasını sağlar.",
"HUD__GAMEMENU_UPGRADES_CROSSBOW_1_TITLE": "Esnek kol",
"HUD__GAMEMENU_UPGRADES_CROSSBOW_2_DESC": "Daha büyük bir sadak ile Amicia, ek oklar taşıyabilir.",
"HUD__GAMEMENU_UPGRADES_CROSSBOW_2_TITLE": "Daha büyük sadak",
"HUD__GAMEMENU_UPGRADES_CROSSBOW_3_DESC": "Arbalet oklarını güçlendiren Amicia, onları düşmanların cesetlerinden geri alabilir.",
"HUD__GAMEMENU_UPGRADES_CROSSBOW_3_TITLE": "Güçlendirilmiş oklar",
"HUD__GAMEMENU_UPGRADES_GEAR": "Donanım",
"HUD__GAMEMENU_UPGRADES_GEAR_1_DESC": "Kemerindeki yeni bir halka, Amicia'nın fazladan bir çömlek taşımasına yardımcı olur.",
"HUD__GAMEMENU_UPGRADES_GEAR_1_TITLE": "Halkalı kemer",
"HUD__GAMEMENU_UPGRADES_GEAR_2_DESC": "Amicia, çantasındaki yeni bir cep sayesinde ek simyasal kaynaklar taşıyabilir.",
"HUD__GAMEMENU_UPGRADES_GEAR_2_TITLE": "Dipsiz çanta",
"HUD__GAMEMENU_UPGRADES_GEAR_3_DESC": "Kemerine bölmeler eklemek, Amicia'nın ek bıçaklar ve ek Pyrite taşımasına yardımcı olur.",
"HUD__GAMEMENU_UPGRADES_GEAR_3_TITLE": "Kemer bölmeleri",
"HUD__GAMEMENU_UPGRADES_SLING": "Sapan",
"HUD__GAMEMENU_UPGRADES_SLING_1_DESC": "İpleri uzatarak sapanla atılan taşlar daha güçlü olur ve düşmanları daha uzun süre sersemletir.",
"HUD__GAMEMENU_UPGRADES_SLING_1_TITLE": "Uzatılmış ipler",
"HUD__GAMEMENU_UPGRADES_SLING_2_DESC": "Sapana ikinci bir yuva ekleyen Amicia, yeniden doldurmadan önce ikinci kez atış yapabilir.",
"HUD__GAMEMENU_UPGRADES_SLING_2_TITLE": "Çift yuva",
"HUD__GAMEMENU_UPGRADES_SLING_3_DESC": "İpleri yumuşatan Amicia, sapanı kullandığında daha az ses çıkarır.",
"HUD__GAMEMENU_UPGRADES_SLING_3_TITLE": "Yumuşatılmış ipler",
"HUD__GAMEMENU_UPGRADES_TOOLS": "Aletler",
"HUD__GAMEMENU_UPGRADES_TOOLS_1_DESC": "Geri dönüşüm aleti, Amicia'nın yeri kalmadığında çömlekleri, bıçağı, Pyrite'ları ve okları parçalara ayırması için kullanışlıdır.",
"HUD__GAMEMENU_UPGRADES_TOOLS_1_TITLE": "Geri dönüşüm aleti",
"HUD__GAMEMENU_UPGRADES_TOOLS_2_DESC": "Amicia, ekipmanını alet maliyeti olmadan yükseltmek için kırılmaz bir alet kullanabilir.",
"HUD__GAMEMENU_UPGRADES_TOOLS_2_TITLE": "Kırılmaz alet",
"HUD__GAMEMENU_UPGRADES_TOOLS_3_DESC": "Gezgin aletleriyle Amicia, ekipmanını bir tezgâh kullanmadan her yerde yükseltebilir.",
"HUD__GAMEMENU_UPGRADES_TOOLS_3_TITLE": "Gezgin aletleri",
"HUD__GAMEMENU_UPGRADES_VAMBRACE_DESC": "Kolluğu takan Amicia, düşman saldırılarından daha hızlı toparlanır.",
"HUD__GAMEMENU_UPGRADES_WORKBENCH": "YÜKSELTMEK İÇİN BİR TEZGÂH BULUN",
"HUD__HOLD_BACK_TO_SKIP": "Atlamak için {STR_RTC_SKIP} basılı tut",
"HUD__LOAD_TEXT": "Yükle",
"HUD__LOG_AUTOSAVE": "Oyun kaydedildi",
"HUD__LOG_CODEX_PROMPT": "Daha fazla bilgi için {STR_CRAFTMENU} tuşuna bas",
"HUD__LOG_COLLECTIBLE": "Öge Kodeks'e eklendi",
"HUD__LOG_COLLECTION": "Hugo'nun koleksiyonuna eklendi:",
"HUD__LOG_FULL_INVENTORY": "Envanter dolu",
"HUD__LOG_RAT_CONTROL": "Imperium",
"HUD__LOG_RAT_SENSE": "Echo",
"HUD__LOG_SKILL_ALCHEMY": "Fırsatçılık yeteneği açıldı:",
"HUD__LOG_SKILL_COMBAT": "Saldırgan yeteneği açıldı:",
"HUD__LOG_SKILL_STEALTH": "İhtiyat yeteneği açıldı:",
"HUD__LOG_SOUVENIR": "Yeni hatıra:",
"HUD__ORPHAN_COMMAND_BOMB": "Stupefacio",
"HUD__ORPHAN_COMMAND_BREAK": "Kır",
"HUD__ORPHAN_COMMAND_CRAWL": "Sürün",
"HUD__ORPHAN_COMMAND_FIGHT": "Savaş",
"HUD__ORPHAN_COMMAND_FOLLOW": "Takip et",
"HUD__ORPHAN_COMMAND_GOTHROUGH": "İçinden geç",
"HUD__ORPHAN_COMMAND_INTERACTION_DEFAULT": "Etkileş",
"HUD__ORPHAN_COMMAND_KILL": "Öldür",
"HUD__ORPHAN_COMMAND_LEVER": "Kullan",
"HUD__ORPHAN_COMMAND_PRISM_DISTRACT": "Dikkat dağıt",
"HUD__ORPHAN_COMMAND_PRISM_REFRACT": "Kır (ışık)",
"HUD__ORPHAN_COMMAND_PUSH": "İt - Çek",
"HUD__ORPHAN_COMMAND_RELEASE": "Bırak",
"HUD__ORPHAN_COMMAND_STAY": "Bekle",
"HUD__ORPHAN_COMMAND_STOP": "Dur",
"HUD__ORPHAN_COMMAND_TAKE": "Al",
"HUD__ORPHAN_COMMAND_THROW": "Fırlat",
"HUD__ORPHAN_ORDER": "Yoldaş emirleri",
"HUD__POICAM": "{STR_POI_CAM} BAK",
"HUD__SAVE_TEXT": "Kaydediliyor",
"HUD__SUBTITLE_SPEAKER_BANDIT": "PARALI ASKER:",
"HUD__SUBTITLE_SPEAKER_BEEKEEPER": "ARICI:",
"HUD__SUBTITLE_SPEAKER_BOURGEOIS": "BURJUVA:",
"HUD__SUBTITLE_SPEAKER_BOURGEOISE": "BURJUVA:",
"HUD__SUBTITLE_SPEAKER_CAPTAIN": "KAPTAN:",
"HUD__SUBTITLE_SPEAKER_CAPTIVE": "TUTSAK:",
"HUD__SUBTITLE_SPEAKER_COUNT": "KONT:",
"HUD__SUBTITLE_SPEAKER_COUNTESS": "KONTES:",
"HUD__SUBTITLE_SPEAKER_CULTIST": "TARİKATÇI:",
"HUD__SUBTITLE_SPEAKER_DYING_MAN": "ÖLEN ADAM:",
"HUD__SUBTITLE_SPEAKER_FARMER": "ÇİFTÇİ:",
"HUD__SUBTITLE_SPEAKER_FLAGELLANT": "KAMÇILI:",
"HUD__SUBTITLE_SPEAKER_FLAGELLANT_LEADER": "KAMÇILILAR LİDERİ:",
"HUD__SUBTITLE_SPEAKER_GUARD": "MUHAFIZ:",
"HUD__SUBTITLE_SPEAKER_HEAVY_GUARD": "AĞIR MUHAFIZ:",
"HUD__SUBTITLE_SPEAKER_ISLANDER_F": "ADALI:",
"HUD__SUBTITLE_SPEAKER_ISLANDER_M": "ADALI:",
"HUD__SUBTITLE_SPEAKER_KID": "ÇOCUK:",
"HUD__SUBTITLE_SPEAKER_MONK": "KEŞİŞ:",
"HUD__SUBTITLE_SPEAKER_OLD_BROTHER": "EN BÜYÜK KARDEŞ:",
"HUD__SUBTITLE_SPEAKER_PEOPLE_F": "KADIN:",
"HUD__SUBTITLE_SPEAKER_PEOPLE_M": "ADAM:",
"HUD__SUBTITLE_SPEAKER_PRISONER": "MAHKÛM:",
"HUD__SUBTITLE_SPEAKER_SERVANT": "HİZMETKÂR:",
"HUD__SUBTITLE_SPEAKER_SERVANT_F": "HİZMETKÂR:",
"HUD__SUBTITLE_SPEAKER_SLAVE": "KÖLE:",
"HUD__SUBTITLE_SPEAKER_SLAVER": "KÖLE TÜCCARI:",
"HUD__SUBTITLE_SPEAKER_SOLDIER": "ASKER:",
"HUD__SUBTITLE_SPEAKER_VILLAGER": "KÖYLÜ:",
"HUD__SUBTITLE_SPEAKER_VILLAGER_F": "KÖYLÜ:",
"HUD__SUBTITLE_SPEAKER_WOLF": "CANAVAR:",
"HUD__SUBTITLE_SPEAKER_YOUNG_BROTHER": "EN KÜÇÜK KARDEŞ:",
}
