# -*- coding: utf-8 -*-
# LOADING kategorisi (bolum ozetleri - anlati). Donemsel, edebi uslup.
# USLUP KURALI: anlati genis zamani (recap -ir/-er, "Simdi/Artik..." -iyor). Gecmis zaman (-di) KARISMAZ.
# Macula korunur; Order->Duzen, Carrier->Tasiyici, Protector->Koruyucu.
T = {
"LOADING__CHAPTER__1": "1349. Amicia ve Hugo De Rune; savaş, fareler ve genç çocuğa, miras aldığı doğaüstü güce el koymak isteyen Engizisyon güçleri tarafından harap edilmiş topraklarından kaçar. Kır yollarında, anneleri Beatrice ve çırak bir simyacı olan yoldaşları Lucas'la birlikte bir nebze huzur bulurlar. Şimdi, Hugo'nun damarlarında dolaşan hastalık olan Macula hakkında daha fazlasını öğrenmeyi umdukları Provence Kontluğu'nu keşfediyorlar.",
"LOADING__CHAPTER__2": "Köylülerle yaşanan trajik bir olay Amicia'yı yeniden öldürmeye zorlarken, Hugo, Macula'nın çaresini barındırabilecek hayalî bir adanın imgesine sığınır. Kurbanının yakınlarına yakalanan Amicia, kendisini travmaya sürükleyen acımasız bir çatışmada ailesini kurtarmak zorunda kalır. Şimdi kızıl şehrin eşiğinde, dördü de Beatrice'in Hugo'nun hastalığı konusunda danışmak istediği Düzen'in Magisteri Vaudin'i arıyor.",
"LOADING__CHAPTER__3": "Hugo'yu muayene edecek simyacı Vaudin'le buluşmaya giderken Amicia ve Lucas, kızıl şehrin, sakinleri karantinaya alınıp Isırık'la kırılmış yoksul bir mahallesini bulur. Orada, hem paralı askerlerle hem de derinliklerden yükselip ortalığı kasıp kavuran binlerce fareyle yüzleşirler. Laboratuvarında Vaudin, Amicia'ya, Düzen'in Macula Taşıyıcısı'yla bağını belirtmek için verdiği unvanla \"Koruyucu\" der. Şimdi üçünün de Hugo'ya katılma vakti.",
"LOADING__CHAPTER__4": "Vaudin, Hugo'nun hastalığını incelemeye başlar, ama tedavisi çocuğun nöbet geçirmesine yol açar. Amicia ve Lucas yatıştırıcı otlar aramaya gider. Farelerin kızıl şehrin bazı bölgelerine saldırmaya başladığını öğrenir ve ısırığı kontrol altına almak için sakinler üzerinde kör bir temizliğe girişen Kont'un ordusuna karşı savaşırlar. Amicia yeniden, kendisini bunaltan ve tutuklanmalarına yol açan bir şiddete dalar. İkili ölüme mahkûm edilir, ama Lucas Amicia'ya sorumluluklarını hatırlatır ve o kendini toparlar. İkisi de tam vaktinde kaçıp bitkileri geri getirir.",
"LOADING__CHAPTER__5": "Vaudin, Hugo'nun kurtulamayacağını düşünür ve Beatrice'i, oğlunun yıkıcı gücünün dizginlenebileceği Marsilya'daki Düzen karargâhına gitmeye ikna eder. Amicia buna karşıdır, yine de Lucas'ın limana ve onları gemisine alacak tekne kaptanı Joseph'e ulaşmasına yardım eder. Bilinçsiz hâldeki Hugo, şehri yutan devasa fare dalgaları salar. Amicia kardeşini yatıştırmayı başaramadan Vaudin ölür. Çocuk, sevdiği bu şehre yaptığı şey karşısında dehşete düşmüştür. Yeniden bir araya gelen aile şimdi Marsilya'ya doğru yola koyulur.",
"LOADING__CHAPTER__6": "Marsilya'ya giden durgun su yolları boyunca De Rune'lerin teknesi, kızıl şehirde daha önce yüzleştikleri paralı askerlerin pususuna düşer. Amicia gemiyi kurtarmaya çalışır, ama çete lideri Arnaud, Hugo kardeşini kurtarmak için fareleri saldırganlarının üzerine salmadan önce başını fena hâlde yaralar. Kıyıda kalan kardeşler, gemiyi uzaklaşmaya bırakmaya karar verir; böylece anneleri Beatrice'i ve hocasını terk etmek istemeyen Lucas'ı geride bırakırlar. Amicia ile Hugo artık ikisi birlikte Hugo'nun rüyalarındaki adayı arıyor.",
"LOADING__CHAPTER__7": "Hugo ve Amicia, çocuğun kehanetteki adasını arayarak Provence kontluğunda tek başlarına dolaşır. Kont'un birliklerince avlanan ikili, eski bir taş ocağının labirentini aşar. Arnaud tarafından ağır yaralanan Amicia gitgide güçten düşer ve bu, Hugo'yu fareler üzerinde gelişen gücünü kullanarak onlara bir yol açmaya zorlar. Askerler peşlerinden koştuğunda Hugo, mekânı sular gibi kaplayan sürü üzerindeki kontrolünü yitirir. Beklenmedik bir el, son anda Amicia'yı ölümden çekip alır.",
"LOADING__CHAPTER__8": "Arnaud, Amicia'yı ölümden kurtarır ve Hugo'nun güvenini kazanır. Yaşlı şövalye, Hugo'ya, çocuğun rüyalarındaki ada olan La Cuna'ya ulaşmalarına yardım etmesi için Sophia adlı bir kaçakçıdan rica edeceğine söz verir. Amicia başta, daha önce kendisini öldürmeye çalışan Arnaud'ya karşıdır, ama onun hikâyesini ve Kont yüzünden yaşadığı kaybı öğrenir; aranan bir adam olan Arnaud artık De Rune'lerle birlikte kaçmak istemektedir. Bir saklanma yerinde kaçakçıların reisi Sophia, Kont'un askerlerince ele geçirilen gemisini geri almaları koşuluyla onlarla yelken açmayı kabul eder. Fırtına kudururken dördü nihayet adaya doğru yola çıkar.",
"LOADING__CHAPTER__9": "Amicia, Hugo ve Arnaud, yıllık kutlamaların ortasında La Cuna adasına ayak basar. Kont'un konuşması sırasında Arnaud, Hugo'yu fareleri çağırıp can düşmanı olan lordu öldürmeye ikna etmeye çalışır. Amicia, Arnaud'nun kıtada kendisini, Hugo'nun fareleriyle Kont'u öldürmesine yardım etmesi karşılığında kurtardığını öğrenir. Arnaud yine de Kont'la dövüşür, ama daha fazla zarar vermeden Amicia onu durdurur ve Arnaud zindana gönderilir. Kontes Emilie gelir ve Hugo ile Amicia'yı, kendisinin ve tüm adanın taptığı çocuk-tanrı olan Köz Çocuğu hakkında onlara daha fazlasını anlattığı muhteşem sarayına davet eder.",
"LOADING__CHAPTER__10": "Hugo'nun açıklanamayan rüyalarına yanıt ararken kardeşler Sophia'yla yeniden karşılaşır. Adanın kalbinde, Düzen'in sembolüne dayanan bir harita keşfederler. Harita onları, bir zamanlar simyacılar topluluğuna ait olan bir mabede götürür. Orada, Köz Çocuğu'nun ana babası olmaya can atan Kont ve karısının yönettiği bir pagan ayinine gizlice tanık olurlar. Amicia ve Hugo ayrıca, eski bir Macula Taşıyıcısı olan Basilius'un ve çocuktan koparılıp bir hisara götürülen Koruyucusu Aelia'nın varlığını öğrenir. De Rune'ler artık Hugo'yu kurtaracak bir yol umuduyla seleflerinin izini sürüyor.",
"LOADING__CHAPTER__11": "Amicia, Hugo ve Sophia hisara ulaşır. Orada köle tüccarları, Köz Çocuğu'na kendi ibadet biçimleriyle köleler kurban etmektedir. Liderleri Milo, Çocuk'un tahtının yanında kendine yer edinmeyi ve Kont'u devirmeyi planlamaktadır, ama Hugo gücünü fanatikleri cezalandırmak için kullanır; bu da Amicia'yla gerginliklere yol açar. Antik bir şapelin kriptasında Amicia, eski Taşıyıcı'nın yerini de içeren Aelia'nın mirasını gün yüzüne çıkarır. Sophia, De Rune kardeşleri kurtarmak için Milo'yu öldürdükten sonra Hugo yine Amicia'ya karşı gelir ve hisarı fareleriyle yıkar. Sophia onları hizaya getirdikten sonra üçlü, ada haritasına geri döner.",
"LOADING__CHAPTER__12": "Milo'yla yaşadıkları çatışma sırasında Hugo, adanın ve nüfusunun bir kısmını silip süpürür. Bir kez daha taptığı bir yeri yok etmiş olmaktan yıkılmıştır. Adanın haritasının altında üçlü, yer altındaki bir tapınağa açılan bir giriş bulur. Orada, eski Taşıyıcı ile Koruyucusunun kaderini öğrenirler: Aelia, Basilius'u kurtaramamıştır. Terk edilmiş ve yalnız hisseden çocuk ölmüş, bunu yaparken de Justinianus vebasını salmıştır. Yine de bu, Amicia'ya gerçeği gösterir: Amicia yanında kaldığı sürece Hugo yaşayacak ve huzurlu bir hayat süreceklerdir.",
"LOADING__CHAPTER__13": "Beatrice ve Lucas, Amicia ve Hugo'nun izini yeniden bulur. Kont'un sarayında bir araya gelen Amicia, öğrendikleri her şeyi annesine anlatır. Beatrice gurur duyar ve ne kadar yanıldığını kabul eder. Ama Kont, Hugo'yu karısına sunmak için Amicia'ya ihanet eder; bu da ailenin geri kalanını öldürmek anlamına gelir. Acımasız bir çatışmada Emilie, Beatrice'i Amicia'nın gözleri önünde infaz eder. Hugo uyanıp bu katliamı gördüğünde fareleri salar ve Amicia yanındayken Sarayı yerle bir eder. Emilie, onları yeniden bulacağına yemin eden Kont'un gözleri önünde fareler tarafından yenir.",
"LOADING__CHAPTER__14": "Amicia, annesinin ölümünün ardından yastan yıkılmış hâldedir ve Hugo, Macula'nın etkisiyle bunalmış, artık kendisi değildir. Lucas'ın yardımıyla devasa bir yer altı fare yuvasını aşarlar. Amicia, kardeşini Macula'nın kötücül etkisinden korumak için tüm gücünü toplar. Hugo yavaşça hayata döner. Asılmak üzere olan Arnaud'yu kurtarmakta ısrar eder. Bunu başarırlar ve sonunda Sophia'ya yetişir, ardından gemisiyle yelken açarlar. Şimdi Amicia, Hugo ve Lucas'ın hayatlarının geri kalanını geçirebileceği bir yuva bulmak için kıtaya doğru yol alıyorlar.",
"LOADING__CHAPTER__15": "Adadan sağ çıktıktan sonra kıtaya yelken açarken Hugo ve Amicia, gelecekteki yeni hayatlarının hayalini kurar. Ama Hugo ve Amicia karısını öldürdüğünden beri keder ve öfkeyle dolu olan Kont onlara yetişir ve savaş gemisiyle gemilerine çıkartma yapar. Amicia ve Arnaud, Kont'un adamlarıyla dövüşür, ama Amicia vurulup düşer. Kardeşini ölmüş sanan Hugo, kendisini ele geçiren Kont'a saldırır. Kont, Hugo'yu fetih ordusunun mızrak ucu olarak kullanmayı planlamaktadır. Köşeye sıkışan Arnaud, hâlâ baygın olan Amicia'yla birlikte denize atlayarak kaçmayı seçer.",
"LOADING__CHAPTER__16": "Amicia, Arnaud, Lucas ve Sophia, Sophia'nın gemisinin batışından sağ çıkar ve Kont'u durdurmaya çalışır. Bir zamanlar Kont yüzünden bir savaş alanında çocuğunu yitiren Arnaud, onunla bir düelloda dövüşür. Amicia'ya nihayet Kont'u öldürme fırsatını sunarak kendini feda eder. Ama Hugo, farelerin her yere dizginsizce yayılmasını sağlayacak devasa bir Nebula bulutu salar. Çocuğun Marsilya'da olduğunu artık bildiklerinden Amicia, Sophia ve Lucas, şehri içeriden kasıp kavuran farelerden kaçar ve sonunda kentin kapısının önüne varır.",
"LOADING__CHAPTER__17": "Amicia ve Lucas, kendini Macula'ya teslim etmiş ve her şeyi yok etmenin eşiğine gelmiş Hugo'ya ulaşmayı başarır. Hugo, içindeki son insanlık kıvılcımını kullanarak kız kardeşini ve Lucas'ı, çok geç olmadan kendisini öldürmeye ikna eder. Acıya rağmen Amicia ve Lucas, Hugo'nun ıstırabına son verip sevdiği dünyayı kurtarmak için bu trajik kararı almak zorundadır.",
"LOADING__MISC__TITLE": "Yükleniyor",
}
