# -*- coding: utf-8 -*-
# LOOT kategorisi. Sahte-Latince/oyun-ici adlar korunur:
# Odoris, Exstinguis, Ignifer, Episanguis, Pyrite -> oldugu gibi.
# Gercek kelimeler cevrilir: Tar->Katran, Rock->Tas, Pot->Comlek vb.
T = {
"LOOT__ALCOHOL": "Alkol",
"LOOT__BASE_ATTRACT": "Odoris",
"LOOT__BASE_EXTINGUISH": "Exstinguis",
"LOOT__BASE_FIRE": "Ignifer",
"LOOT__BASE_OIL": "Katran",
"LOOT__BASE_ROCK": "Taş",
"LOOT__CROSSBOW_ATTRACT": "Odoris oku",
"LOOT__CROSSBOW_BOLT": "Ok",
"LOOT__CROSSBOW_EXTINGUISH": "Exstinguis oku",
"LOOT__CROSSBOW_FIRE": "Ignifer oku",
"LOOT__CROSSBOW_OIL": "Katran oku",
"LOOT__DESC_ALCOHOL": "Alkol",
"LOOT__DESC_BASE_ATTRACT": "Çevredeki fareleri kısa bir süre kendine çeker",
"LOOT__DESC_BASE_EXTINGUISH": "Ateşleri söndürür",
"LOOT__DESC_BASE_FIRE": "Korları tutuşturur",
"LOOT__DESC_BASE_OIL": "Yanıcı yüzeyler yayar veya ateşi güçlendirir",
"LOOT__DESC_CROSSBOW_ATTRACT": "Saplandığında çevredeki fareleri süresiz kendine çeker",
"LOOT__DESC_CROSSBOW_BOLT": "Zırhla korunmayan düşmanları öldürür",
"LOOT__DESC_CROSSBOW_EXTINGUISH": "Saplandığında, düşmanları kör eden ve fareleri yavaşlatan bir bulut oluşturmak için kırılabilir",
"LOOT__DESC_CROSSBOW_FIRE": "Saplandığında kalıcı bir ışık bölgesi oluşturur",
"LOOT__DESC_CROSSBOW_OIL": "Saplandığında, yanıcı bir katran birikintisi oluşturmak için kırılabilir",
"LOOT__DESC_EPISANGUIS": "Episanguis",
"LOOT__DESC_HAND_ATTRACT": "Çevredeki fareleri kısa bir süre kendine çeker",
"LOOT__DESC_HAND_EXTINGUISH": "Ateşleri söndürür",
"LOOT__DESC_HAND_FIRE": "Korları tutuşturur",
"LOOT__DESC_HAND_OIL": "Hâlihazırda yanan ateşi güçlendirir",
"LOOT__DESC_HAND_ROCK": "Metal nesnelere çarptığında çevredeki düşmanların dikkatini dağıtır",
"LOOT__DESC_JAR": "Yakındaki düşmanların dikkatini dağıtır",
"LOOT__DESC_JAR_ATTRACT": "Fareleri uzun süre kendine çeken bir alan oluşturur",
"LOOT__DESC_JAR_EXTINGUISH": "Düşmanları kör eden ve fareleri yavaşlatan bir bulut oluşturur",
"LOOT__DESC_JAR_FIRE": "Geçici bir ışık bölgesi oluşturur",
"LOOT__DESC_JAR_OIL": "Sonradan tutuşturulabilen bir katran birikintisi oluşturur",
"LOOT__DESC_KNIFE": "Bir düşmanı sessizce ortadan kaldırır",
"LOOT__DESC_PYRITE": "Çarptığında güçlü bir ışık yayarak fareleri uzaklaştırır",
"LOOT__DESC_RESIN": "Reçine",
"LOOT__DESC_SALPETER": "Güherçile",
"LOOT__DESC_SCRAP": "Parça",
"LOOT__DESC_SLINGSHOT_ATTRACT": "Çevredeki fareleri kısa bir süre kendine çeker",
"LOOT__DESC_SLINGSHOT_EXTINGUISH": "Ateşleri söndürür",
"LOOT__DESC_SLINGSHOT_FIRE": "Korları tutuşturur",
"LOOT__DESC_SLINGSHOT_OIL": "Hâlihazırda yanan ateşi güçlendirir",
"LOOT__DESC_SLINGSHOT_ROCK": "Kafasından vurulan düşmanları öldürür",
"LOOT__DESC_SULPHUR": "Kükürt",
"LOOT__DESC_TOOL": "Alet",
"LOOT__EPISANGUIS": "Episanguis",
"LOOT__GAUNTLET": "Temel",
"LOOT__GAUNTLET_ATTRACT": "Odoris",
"LOOT__GAUNTLET_EXTINGUISH": "Exstinguis",
"LOOT__GAUNTLET_FIRE": "Ignifer",
"LOOT__GAUNTLET_OIL": "Katran",
"LOOT__HAND_ATTRACT": "El atışı Odoris",
"LOOT__HAND_EXTINGUISH": "El atışı Exstinguis",
"LOOT__HAND_FIRE": "El atışı Ignifer",
"LOOT__HAND_OIL": "El atışı Katran",
"LOOT__HAND_ROCK": "El atışı taş",
"LOOT__JAR": "Çömlek",
"LOOT__JAR_ATTRACT": "Odoris çömleği",
"LOOT__JAR_EXTINGUISH": "Exstinguis çömleği",
"LOOT__JAR_FIRE": "Ignifer çömleği",
"LOOT__JAR_OIL": "Katran çömleği",
"LOOT__KNIFE": "Bıçak",
"LOOT__PYRITE": "Pyrite",
"LOOT__RESIN": "Reçine",
"LOOT__SALPETER": "Güherçile",
"LOOT__SCRAP": "Parça",
"LOOT__SLINGSHOT_ATTRACT": "Sapanla Odoris",
"LOOT__SLINGSHOT_EXTINGUISH": "Sapanla Exstinguis",
"LOOT__SLINGSHOT_FIRE": "Sapanla Ignifer",
"LOOT__SLINGSHOT_OIL": "Sapanla Katran",
"LOOT__SLINGSHOT_ROCK": "Sapanla taş",
"LOOT__SULPHUR": "Kükürt",
"LOOT__TOOL": "Alet",
"LOOT__TOOL_CROSSBOW": "Arbalet",
"LOOT__TOOL_HANDTRHOW": "El atışı",
"LOOT__TOOL_JAR": "Çömlek",
"LOOT__TOOL_SLING": "Sapan",
"LOOT__VAMBRACE": "Kolluk",
}
