# -*- coding: utf-8 -*-
# MENU kategorisi Turkce ceviri (gercek TR karakterlerle; builder ikame uygular)
T = {
"MENU__ACCESSIBILITY_HELD": "Özel etkileşimler",
"MENU__ACCESSIBILITY_HELD_DESC": "Bazı etkileşimler artık gerçekleştirilmek için tuşun basılı tutulmasını gerektirmez.",
"MENU__ACCESSIBILITY_HELD_INPUT": "Basılı tutmalı girişler",
"MENU__ACCESSIBILITY_HELD_INPUT_DESC": "Silah ve cephane seçimi ile nişan almada aç/kapa yerine basılı tutmalı girişler kullanır.",
"MENU__ACCESSIBILITY_INPUT_HELD": "Basılı tut",
"MENU__ACCESSIBILITY_INPUT_PRESS": "Bas",
"MENU__ACCESSIBILITY_QTE": "Zamanlı girişleri otomatik uygula",
"MENU__ACCESSIBILITY_QTE_DESC": "Ekranda beliren zamanlı girişler otomatik olarak gerçekleştirilir.",
"MENU__ACCESSIBILITY_SHAKE": "Sabit kamera",
"MENU__ACCESSIBILITY_SHAKE_DESC": "Kamera hareketini ve sarsıntıyı azaltır.",
"MENU__ACCESSIBILITY_TIMED": "Otomatik hızlı etkileşimler",
"MENU__ACCESSIBILITY_TIMED_DESC": "Hızlı tepki gerektiren etkileşimler otomatik olarak çözülür.",
"MENU__ADVANCED_GRAPHICS_SETTINGS": "Gelişmiş Ayarlar",
"MENU__AIM_ASSIST_LOW": "Düşük",
"MENU__AIM_ASSIST_NORMAL": "Normal",
"MENU__AMBIENT_OCCLUSION": "Ortam örtüşmesi",
"MENU__AMBIENT_OCCLUSION_DESC": "Ortam örtüşmesinin kalitesini ayarlar.",
"MENU__ANTI_ALIASING": "Kenar yumuşatma",
"MENU__ARMS_SELECTION": "Aile armanızı seçin",
"MENU__AUDIO_3D": "3D Ses",
"MENU__AUDIO_3D_DESC": "3D Ses, işletim sisteminiz üzerinden belirlenir.~ ~  Lütfen Windows Ses Denetim Masası'na gidin, tercih ettiğiniz Oynatma Aygıtı için Özellikler'i açın ve bir Uzamsal Ses çıkışı seçin.",
"MENU__AUDIO_BACKGROUND": "Ortam ses düzeyi",
"MENU__AUDIO_BACKGROUND_DESC": "Ortam seslerinin düzeyini ayarlamanızı sağlar.",
"MENU__AUDIO_DIALOG": "Diyalog ses düzeyi",
"MENU__AUDIO_DIALOG_DESC": "Diyalog ses düzeyini ayarlamanızı sağlar.",
"MENU__AUDIO_HEADPHONES": "Kulaklık",
"MENU__AUDIO_LANGUAGE": "Seslendirme dili",
"MENU__AUDIO_LANGUAGE_DESC": "Konuşulan diyalogların dilini değiştirir.",
"MENU__AUDIO_MASTER": "Ana ses düzeyi",
"MENU__AUDIO_MASTER_DESC": "Oyunun ana ses düzeyini ayarlamanızı sağlar.",
"MENU__AUDIO_MENU": "Menü ses düzeyi",
"MENU__AUDIO_MENU_DESC": "Menü ses düzeyini ayarlamanızı sağlar.",
"MENU__AUDIO_MODE": "Dinleme modu",
"MENU__AUDIO_MODE_DESC": "En iyi ses deneyimi için kurulumunuza uygun seçeneği seçmenizi sağlar.~ ~  HiFi: Ses çubukları ve stereo hoparlörler için önerilir.~ ~ TV: Dahili TV hoparlörleri kullanılırken önerilir.~ ~ Kulaklık: Kulaklık kullanılırken önerilir.~ ~ Ev Sineması: Surround ses için önerilir (Dolby Atmos™, 7.1, 5.1).~ ~",
"MENU__AUDIO_MONO": "Mono",
"MENU__AUDIO_MONO_DESC": "Tüm sesi, sol ve sağ kanallardan eşit şekilde çalan tek bir çıkışta birleştirir.",
"MENU__AUDIO_MUSIC": "Müzik ses düzeyi",
"MENU__AUDIO_MUSIC_DESC": "Müzik ses düzeyini ayarlamanızı sağlar.",
"MENU__AUDIO_SETTINGS": "Ses",
"MENU__AUDIO_SFX": "Efekt ses düzeyi",
"MENU__AUDIO_SFX_DESC": "Ses efektlerinin düzeyini ayarlamanızı sağlar.",
"MENU__AUDIO_SOUNDBAR": "HiFi",
"MENU__AUDIO_SURROUD": "Ev Sineması",
"MENU__AUDIO_TVSPEAKERS": "TV",
"MENU__AUDIO_VO_HAPTIC": "Konuşmadan titreşime",
"MENU__AUDIO_VO_HAPTIC_DESC": "Etkinleştirildiğinde, konuşulan diyaloglar kumandada dokunsal titreşim olarak da hissedilir.",
"MENU__BACK": "Geri",
"MENU__BLOOM": "Parlama",
"MENU__BORDERLESS": "Kenarlıksız",
"MENU__BRIGHTNESS": "Parlaklık",
"MENU__BRIGHTNESS_DESC": "Parlaklık ayarı menüsünü açar.",
"MENU__CAMERA_SETTINGS": "Oynanış",
"MENU__CHANGE_ARMS": "Aile Armasını Değiştir",
"MENU__CHANGE_PROFILE": "Profil Değiştir",
"MENU__CHAPTER_SELECTION": "Bölüm Seçimi",
"MENU__CHAPTER_SELECTION_PROMPT": "Başka bir bölümdeki ilerlemeniz kaybolacak. Bu bölümü oynamak istiyor musunuz?",
"MENU__CHAPTER1": "I - Yeni Bir Güneşin Altında",
"MENU__CHAPTER1_1": "1 - Uzun bir yolculuk",
"MENU__CHAPTER1_2": "2 - Kovanlar",
"MENU__CHAPTER1_3": "3 - Başka diyarların hayali",
"MENU__CHAPTER1_4": "4 - Yalanlar",
"MENU__CHAPTER1_5": "5 - Kudurmuş ateş",
"MENU__CHAPTER2": "II - Yeni Gelenler",
"MENU__CHAPTER2_1": "1 - Kasabaya varış",
"MENU__CHAPTER2_2": "2 - Arenaya doğru",
"MENU__CHAPTER2_3": "3 - Kemerli geçitler",
"MENU__CHAPTER2_4": "4 - Tribünlerde hesaplaşma",
"MENU__CHAPTER2_5": "5 - Yer altı",
"MENU__CHAPTER2_6": "6 - Ignifer",
"MENU__CHAPTER2_7": "7 - Gladyatörler",
"MENU__CHAPTER3": "III - Bir Kan Yükü",
"MENU__CHAPTER3_1": "1 - Kasabayı geçmek",
"MENU__CHAPTER3_2": "2 - Kasaplar mahallesi",
"MENU__CHAPTER3_3": "3 - Rodric'in aleti",
"MENU__CHAPTER3_4": "4 - Kapı",
"MENU__CHAPTER3_5": "5 - Şehrin kıyısında",
"MENU__CHAPTER3_6": "6 - Şifacıda",
"MENU__CHAPTER3_7": "7 - Zindanda",
"MENU__CHAPTER3_8": "8 - Depo",
"MENU__CHAPTER4": "IV - Koruyucunun Görevi",
"MENU__CHAPTER4_1": "1 - Sokağa çıkma yasağı",
"MENU__CHAPTER4_2": "2 - Gece işi",
"MENU__CHAPTER4_3": "3 - Tehlikeli güzergâh",
"MENU__CHAPTER4_4": "4 - Katran atölyesi",
"MENU__CHAPTER4_5": "5 - Zorunlu iş birliği",
"MENU__CHAPTER4_6": "6 - Bataklığın toplu mezarı",
"MENU__CHAPTER4_7": "7 - Hugo'nun çağrısı",
"MENU__CHAPTER5": "V - Ardımızda",
"MENU__CHAPTER5_1": "1 - Nehirde",
"MENU__CHAPTER5_2": "2 - Akıntı feribotu",
"MENU__CHAPTER5_3": "3 - Yapım hâlindeki köprü",
"MENU__CHAPTER5_4": "4 - Pusu",
"MENU__CHAPTER5_5": "5 - Kancalar",
"MENU__CHAPTER6": "VI - Her Şeyi Geride Bırakarak",
"MENU__CHAPTER6_1": "1 - Denize doğru",
"MENU__CHAPTER6_2": "2 - Bir hac yolu",
"MENU__CHAPTER6_3": "3 - Bağlantı",
"MENU__CHAPTER6_4": "4 - Aşı boyaları",
"MENU__CHAPTER6_5": "5 - Farelerin çağrısı",
"MENU__CHAPTER6_6": "6 - Av dersi",
"MENU__CHAPTER6_7": "7 - Saldırı",
"MENU__CHAPTER7": "VII - Hainler",
"MENU__CHAPTER7_1": "1 - Sahile varış",
"MENU__CHAPTER7_2": "2 - Mağaralardan geçiş",
"MENU__CHAPTER7_3": "3 - Daha fazla fare",
"MENU__CHAPTER7_4": "4 - Arnaud'ya göre dövüş",
"MENU__CHAPTER7_5": "5 - Balıkçı köyü",
"MENU__CHAPTER7_6": "6 - Kuru havuz",
"MENU__CHAPTER8": "VIII - Vaatler Denizi",
"MENU__CHAPTER8_1": "1 - Aydınlık günlerin kutlaması",
"MENU__CHAPTER8_2": "2 - Anlaşma",
"MENU__CHAPTER8_3": "3 - Arnaud'yu durdurmak",
"MENU__CHAPTER8_4": "4 - Konuklar",
"MENU__CHAPTER9": "IX - Hikâyeler ve İfşalar",
"MENU__CHAPTER9_1": "1 - Keşif",
"MENU__CHAPTER9_2": "2 - Mabede doğru",
"MENU__CHAPTER9_3": "3 - Dağda",
"MENU__CHAPTER9_4": "4 - Mabede giriş",
"MENU__CHAPTER9_5": "5 - Gece ve Gündüz",
"MENU__CHAPTER9_6": "6 - Anka",
"MENU__CHAPTER9_7": "7 - Dalış",
"MENU__CHAPTER10": "X - Kan Bağı",
"MENU__CHAPTER10_1": "1 - Yuvarlak kuleye doğru",
"MENU__CHAPTER10_2": "2 - Kıyı",
"MENU__CHAPTER10_3": "3 - Köle tüccarları",
"MENU__CHAPTER10_4": "4 - Eski tapınak",
"MENU__CHAPTER10_5": "5 - Kaleye yaklaşırken",
"MENU__CHAPTER10_6": "6 - Avluda",
"MENU__CHAPTER10_7": "7 - Şapel",
"MENU__CHAPTER11": "XI - Yüzyılların Beşiği",
"MENU__CHAPTER11_1": "1 - Çıkışın ardından",
"MENU__CHAPTER11_2": "2 - Haritaya dönüş",
"MENU__CHAPTER11_3": "3 - Mühürlü geçit",
"MENU__CHAPTER11_4": "4 - Bizans teknolojisi",
"MENU__CHAPTER11_5": "5 - Savunma sistemi",
"MENU__CHAPTER11_6": "6 - Aelia",
"MENU__CHAPTER11_7": "7 - Fare tankı",
"MENU__CHAPTER11_8": "8 - Kuyu",
"MENU__CHAPTER11_9": "9 - Kadim çürüme",
"MENU__CHAPTER12": "XII - Hak Ettiğimiz Hayat",
"MENU__CHAPTER12_1": "1 - La Cuna'dan ayrılış",
"MENU__CHAPTER12_2": "2 - Saraydaki sığınmacılar",
"MENU__CHAPTER12_3": "3 - Ölümcül tuzak",
"MENU__CHAPTER12_4": "4 - Mahzenden kaçış",
"MENU__CHAPTER12_5": "5 - Sınıra ulaşmak",
"MENU__CHAPTER13": "XIII - Geriye Hiçbir Şey Kalmadı",
"MENU__CHAPTER13_1": "1 - Yas",
"MENU__CHAPTER13_2": "2 - Yuvanın içinde",
"MENU__CHAPTER13_3": "3 - Temiz hava",
"MENU__CHAPTER13_4": "4 - Yıkık köy",
"MENU__CHAPTER13_5": "5 - Kurtarma",
"MENU__CHAPTER14": "XIV - Yaralarımızı Sararken",
"MENU__CHAPTER14_1": "1 - Anakaraya dönüş",
"MENU__CHAPTER14_2": "2 - Kaçış",
"MENU__CHAPTER14_3": "3 - Baskın",
"MENU__CHAPTER15": "XV - Ölen Güneş",
"MENU__CHAPTER15_1": "1 - Karaya vurmuş",
"MENU__CHAPTER15_2": "2 - Düello",
"MENU__CHAPTER15_3": "3 - Arabada",
"MENU__CHAPTER16": "XVI - Kral Hugo",
"MENU__CHAPTER16_1": "1 - Marsilya",
"MENU__CHAPTER16_2": "2 - İniş",
"MENU__CHAPTER16_3": "3 - Nebula",
"MENU__CHAPTER17": "XVII - De Rune Ailesinin Mirası",
"MENU__CHAPTER17_1": "1 - Bir Yıl",
"MENU__CHAPTER17_2": "2 - Zirveye giden yol",
"MENU__CHAPTER17_3": "3 - Veda",
"MENU__COMPLETE": "Tamamlandı",
"MENU__COMPLETED_CROSSBOW_DESCRIPTION": "Arbalet için özel bir boya kazandınız. Donatmak için Ekstralar menüsüne gidin.",
"MENU__CONGRAT": "Tebrikler!",
"MENU__CONTACT_SHADOWS": "Temas gölgeleri",
"MENU__CONTACT_SHADOWS_DESC": "Temas gölgelerinin kalitesini ayarlar.",
"MENU__CONTINUE": "Devam et",
"MENU__CONTROLS": "Kontroller",
"MENU__CONTROLS_AIM": "Nişan alma",
"MENU__CONTROLS_AIM_DESC": "Nişan almak için tuşu basılı tutma veya basma arasında seçim yapmanızı sağlar.",
"MENU__CONTROLS_AMMO_DEFAULT": "Varsayılan cephaneyi seç",
"MENU__CONTROLS_AMMO_DOWN": "Ignifer'i seç",
"MENU__CONTROLS_AMMO_LEFT": "Katranı seç",
"MENU__CONTROLS_AMMO_NEXT": "Sonraki cephane",
"MENU__CONTROLS_AMMO_PREVIOUS": "Önceki cephane",
"MENU__CONTROLS_AMMO_RIGHT": "Odoris'i seç",
"MENU__CONTROLS_AMMO_SELECTION": "Silah ve Cephane seçimi",
"MENU__CONTROLS_AMMO_SELECTION_DESC": "Silah ve cephane seçim menüsünü göstermek/gizlemek için tuşu basılı tutma veya basma arasında seçim yapmanızı sağlar.",
"MENU__CONTROLS_AMMO_UP": "Exstinguis'i seç",
"MENU__CONTROLS_BIND_CONFLICT": "Seçili giriş artık birden fazla eyleme atanmış. Çakışan atamaların yeniden eşlenmesi gerekebilir.",
"MENU__CONTROLS_BIND_CONFLICT1": "Seçili {INPUT} daha önce şuna atanmıştı:",
"MENU__CONTROLS_BIND_CONFLICT2": "Çakışan atamaların yeniden eşlenmesi gerekebilir.",
"MENU__CONTROLS_BIND_PROMPT": "Şuna atamak istediğiniz girişe basın:",
"MENU__CONTROLS_CAMERA": "Kamerayı ayarla",
"MENU__CONTROLS_CANCEL": "İptal",
"MENU__CONTROLS_CRAFT": "Üret",
"MENU__CONTROLS_CRAFT_DESC": "Üretmek için tuşu basılı tutma veya basma arasında seçim yapmanızı sağlar.",
"MENU__CONTROLS_CRAFTMENU": "Üretim menüsü",
"MENU__CONTROLS_CROUCH": "Çömel",
"MENU__CONTROLS_CYCLE_AMMO": "Cephane değiştir",
"MENU__CONTROLS_CYCLE_TOOL": "Silah değiştir",
"MENU__CONTROLS_DOWN": "Geri",
"MENU__CONTROLS_DROP": "Bırak (taşırken)",
"MENU__CONTROLS_GAMEPAD": "Kumanda",
"MENU__CONTROLS_INTERACT": "Etkileş / Al",
"MENU__CONTROLS_KEYBIND_ALL_RESET": "Tümünü varsayılana sıfırla",
"MENU__CONTROLS_KEYBIND_RESET": "Sıfırla",
"MENU__CONTROLS_KEYBOARD": "Klavye",
"MENU__CONTROLS_LAYOUT": "Düzen",
"MENU__CONTROLS_LEFT": "Sol",
"MENU__CONTROLS_MOUSE": "Fare",
"MENU__CONTROLS_MOVE": "Karakter hareketi",
"MENU__CONTROLS_MULTIPLE": "Birden fazla giriş",
"MENU__CONTROLS_ORPHAN_ABILITY": "Emir: Yetenek",
"MENU__CONTROLS_ORPHAN_CANCEL": "Emir: İptal",
"MENU__CONTROLS_ORPHAN_CLOSE": "Emir: Yakın dur",
"MENU__CONTROLS_ORPHAN_INTERACT": "Emir: Etkileş",
"MENU__CONTROLS_ORPHAN_ORDERS": "Emir seçimi",
"MENU__CONTROLS_ORPHAN_ORDERS_DESC": "Emir seçim menüsünü göstermek/gizlemek için tuşu basılı tutma veya basma arasında seçim yapmanızı sağlar.",
"MENU__CONTROLS_ORPHAN_STAY": "Emir: Bekle",
"MENU__CONTROLS_PAUSE": "Duraklat",
"MENU__CONTROLS_POI_CAM": "Bak",
"MENU__CONTROLS_QUICKCRAFT": "Üret (nişan alırken)",
"MENU__CONTROLS_RATSENS_AIM": "Faresezgi",
"MENU__CONTROLS_RESET_CAM": "Kamerayı Sıfırla",
"MENU__CONTROLS_RIGHT": "Sağ",
"MENU__CONTROLS_SETUP": "Kurulum",
"MENU__CONTROLS_SHOOT": "Ateş et (nişan alırken)",
"MENU__CONTROLS_SLING_SLASH": "Vur (yakın dövüşte)",
"MENU__CONTROLS_SPRINT": "Koş",
"MENU__CONTROLS_SPRINT_DESC": "Koşmak için tuşu basılı tutma veya basma arasında seçim yapmanızı sağlar.",
"MENU__CONTROLS_UP": "İleri",
"MENU__CONTROLS_VAULT": "Atla / Tırman",
"MENU__CONTROLS_WALK": "Yürü",
"MENU__CONTROLS_WALK_DESC": "Yürümek için tuşu basılı tutma veya basma arasında seçim yapmanızı sağlar.",
"MENU__CONTROLS_WEAPON": "Silah seçimi",
"MENU__CONTROLS_WEAPON_DOWN": "Sapanı seç",
"MENU__CONTROLS_WEAPON_LEFT": "El atışını seç",
"MENU__CONTROLS_WEAPON_NEXT": "Sonraki silah",
"MENU__CONTROLS_WEAPON_PREVIOUS": "Önceki silah",
"MENU__CONTROLS_WEAPON_RIGHT": "Çömleği seç",
"MENU__CONTROLS_WEAPON_UP": "Arbaleti seç",
"MENU__CREDITS": "Jenerik",
"MENU__CROSSBOW_NG_COMPLETE": "Macera tamamlandı: Kont'un arbaleti",
"MENU__CROSSBOW_NG_PLUS_COMPLETE": "Yeni Oyun+ tamamlandı: Düzen'in arbaleti",
"MENU__D3D12": "DirectX 12",
"MENU__D3D12_DESC": "DirectX 12 işlemeyi etkinleştirir. ~ ~ Yeniden başlatma gerektirir.",
"MENU__DEPTH_OF_FIELD": "Alan derinliği",
"MENU__DEPTH_OF_FIELD_DESC": "Alan derinliğinin kalitesini ayarlar.",
"MENU__DIFFICULTY_HARD": "Zor",
"MENU__DIFFICULTY_LEVEL": "Zorluk",
"MENU__DIFFICULTY_LEVEL_DESC": "De Rune kardeşlerle yaşayacağınız deneyimin niteliğini belirler.~ ~ Anlatı: Keşif ve hikâyeye odaklanan, sürükleyici bir yolculuk.~ ~ Normal: Macera ile zorluklar arasında en iyi dengeyi sunan, dengeli bir deneyim.~ ~ Zor: Acımasız koşullarla örülmüş, hayatta kalma için çetin bir mücadele.~",
"MENU__DIFFICULTY_LEVEL_GAME_PLUS": "Yeni Oyun+: Son oynayışınızda elde ettiğiniz tüm Kodeks, Yükseltme ve Yeteneklerle birlikte Nihai Zorluk modunda yeni bir maceraya başlamak için.",
"MENU__DIFFICULTY_MEDIUM": "Normal",
"MENU__DIFFICULTY_NARRATIVE": "Anlatı",
"MENU__DIFFICULTY_NEW_GAME_PLUS": "Yeni Oyun+",
"MENU__DISPLAY_AMMOSTATUS": "Cephane durumu",
"MENU__DISPLAY_ENEMYGLOW": "Düşman varlığı göstergesi",
"MENU__DISPLAY_ENEMYGLOW_DESC": "Yakında bir düşman olduğunda ekranın kenarında bir efekt gösterir.",
"MENU__DISPLAY_ENEMYJAUGE": "Düşman durumu göstergesi",
"MENU__DISPLAY_ENEMYJAUGE_DESC": "Düşmanların üzerinde göstergeler görüntüler.",
"MENU__DISPLAY_ENEMYVISION": "Düşman görüşü",
"MENU__DISPLAY_HIGHLIGHT": "Etkileşimleri vurgula",
"MENU__DISPLAY_HIGHLIGHT_DESC": "Etkileşimli ögelerin arka planda parlamasını sağlar.",
"MENU__DISPLAY_LOG": "Ganimet kaydı",
"MENU__DISPLAY_LOG_DESC": "Envanterdeki her yeni öge için bir ganimet kaydı görüntüler.",
"MENU__DISPLAY_MODE": "Görüntü modu",
"MENU__DISPLAY_MODE_DESC": "Oyunu tam ekranda veya yeniden boyutlandırılabilir bir pencerede gösterme seçeneği sunar.",
"MENU__DISPLAY_NOISELEVEL": "Gürültü düzeyi",
"MENU__DISPLAY_OBJECTIVES": "Hedefler",
"MENU__DISPLAY_OBJECTIVES_DESC": "Geçerli hedefi ekranın sağ üst köşesinde görüntüler.",
"MENU__DISPLAY_ORPHANDANGER": "Tehlikedeki yoldaşlar",
"MENU__DISPLAY_ORPHANDANGER_DESC": "Bir yoldaş tehlikedeyken arayüzü görüntüler.",
"MENU__DISPLAY_ORPHANSTATUS": "Yoldaş durumu",
"MENU__DISPLAY_ORPHANSTATUS_DESC": "Yoldaşlarınızın durumunu ekranın sol altında görüntüler.",
"MENU__DISPLAY_OUTLINE": "Yardım dış hattı",
"MENU__DISPLAY_OUTLINE_DESC": "Aynı yerde çok fazla vakit geçirildiğinde, bölümü çözmek için gereken ögelerin dış hatlarını belirginleştirir.",
"MENU__DISPLAY_RETICLES": "Nişangâhlar",
"MENU__DISPLAY_RETICLES_DESC": "Silah nişangâhlarını görüntüler.",
"MENU__DISPLAY_SUBTITLES": "Altyazıları göster",
"MENU__DISPLAY_SUBTITLES_DESC": "Altyazıların görüntülenmesini etkinleştirir.",
"MENU__DISPLAY_SUBTITLES_SPEAKER": "Karakter adlarını göster",
"MENU__DISPLAY_SUBTITLES_SPEAKER_DESC": "Altyazıların yanında karakterlerin adlarının görüntülenmesini etkinleştirir.",
"MENU__DISPLAY_TUTORIAL": "Öğretici",
"MENU__DISPLAY_TUTORIAL_DESC": "Yeni özellikler keşfedildiğinde ekranın ortasında öğreticiler görüntüler.",
"MENU__DISPLAY_VAULT_PROMPT": "Engel aşma",
"MENU__DISPLAY_VAULT_PROMPT_DESC": "Engel aşma arayüzünü görüntüler.",
"MENU__DLAA": "DLAA",
"MENU__DLSS": "NVIDIA DLSS Süper Çözünürlük",
"MENU__DLSS_AUTO": "Otomatik",
"MENU__DLSS_BALANCED": "Dengeli",
"MENU__DLSS_DESC": "NVIDIA DLSS, en yüksek grafik ayarlarında mümkün olan en yüksek kare hızlarını sağlamak için yapay zekâ Süper Çözünürlüğü kullanır. DLSS, bir NVIDIA RTX ekran kartı gerektirir.~ ~Kapalı: DLSS'yi kapatır.~ ~Otomatik: Geçerli çıkış çözünürlüğü için en iyi DLSS modunu seçer.~ ~Kalite: Dengeli moddan daha yüksek görüntü kalitesi sunar.~ ~Dengeli: Hem optimize edilmiş performans hem de görüntü kalitesi sunar.~ ~Performans: Dengeli moddan daha yüksek bir performans artışı sunar.~ ~Ultra Performans: En yüksek performans artışını sunar. Yalnızca 8K oynanış için önerilir.~ ~DLAA: GPU'da boş kapasitesi olan ve daha yüksek görüntü kalitesi isteyen kullanıcılar için yapay zekâ tabanlı kenar yumuşatma modu.",
"MENU__DLSS_DLAA": "DLAA",
"MENU__DLSS_OFF": "Kapalı",
"MENU__DLSS_PERFORMANCE": "Performans",
"MENU__DLSS_QUALITY": "Kalite",
"MENU__DLSS_ULTRA_PERFORMANCE": "Ultra performans",
"MENU__DLSS_ULTRA_QUALITY": "Ultra kalite",
"MENU__DLSSG": "NVIDIA DLSS Kare Üretimi",
"MENU__DLSSG_DESC": "DLSS Kare Üretimi, görüntü kalitesinden veya yanıt hızından ödün vermeden ek kareler oluşturmak için yapay zekâ kullanır.~ ~Bu özellik bir GeForce RTX 40 Serisi ekran kartı gerektirir.~ ~Donanım hızlandırmalı GPU Zamanlaması (HWS), Windows Ayarları > Sistem > Görüntü > Grafik ayarları üzerinden etkinleştirilmelidir.",
"MENU__DRAW_DISTANCE": "Çizim mesafesi",
"MENU__DRAW_DISTANCE_DESC": "Arka plan ögelerinin görüntülenme mesafesini belirler.",
"MENU__EMPTY_SLOT": "Boş yuva",
"MENU__ERASE_SLOT": "Sil",
"MENU__ERASE_SLOT_PROMPT": "Bu yuva silinsin mi? Tüm ilerlemeniz kaybolacak.",
"MENU__EXTRAS": "Ekstralar",
"MENU__FULLSCREEN": "Tam ekran",
"MENU__FXAA": "FXAA",
"MENU__GAMEPLAY_SETTINGS": "Genel",
"MENU__GAMMA_DESCRIPTION": "Ağacı zar zor görünür hâle getirmek için parlaklığı {STR_MENU_LEFT} ve {STR_MENU_RIGHT} ile ayarlayın.",
"MENU__GRAPHICS_BACKMENU_MODE": "Seçili grafik seçeneğini etkinleştirmek için ana menüye dönüp oyununuzu yeniden başlatmalısınız. Devam etmek istiyor musunuz?",
"MENU__GRAPHICS_CONFIRM": "Bu değişiklikleri korumak istiyor musunuz?",
"MENU__GRAPHICS_CONFIRM_REBOOT": "Yeniden başlatma gerekli. Değişiklikleri uygulamak için oyunu yeniden başlatmalısınız.",
"MENU__GRAPHICS_CUSTOM": "Özel",
"MENU__GRAPHICS_DETAILS": "Grafik ön ayarı",
"MENU__GRAPHICS_DETAILS_DESC": "Oyunun görsel kalitesini ayarlamanızı sağlar.",
"MENU__GRAPHICS_FRAMELIMITER": "Maks. kare hızı",
"MENU__GRAPHICS_FRAMELIMITER_DESC": "Maks. kare hızı, saniyedeki kare sayısının üst sınırını belirler.",
"MENU__GRAPHICS_FRAMELIMITER_UNIT": "FPS",
"MENU__GRAPHICS_FRAMELIMITER_UNLIMITED": "Sınırsız",
"MENU__GRAPHICS_HIGH": "Yüksek",
"MENU__GRAPHICS_LOW": "Düşük",
"MENU__GRAPHICS_MEDIUM": "Orta",
"MENU__GRAPHICS_MODE": "Grafik modu",
"MENU__GRAPHICS_MODE_DESC": "Grafik modunu ayarlamanızı sağlar:~ ~Çözünürlük: Daha yüksek çözünürlük ve netlik, ancak saniyede 30 kareyle sınırlı.~ ~Performans: Daha düşük çözünürlük ve netlikte saniyede 60 kare hedefler.",
"MENU__GRAPHICS_MODE_PERFORMANCE": "Performansı önceliklendir",
"MENU__GRAPHICS_MODE_QUALITY": "Çözünürlüğü önceliklendir",
"MENU__GRAPHICS_NONE": "Yok",
"MENU__GRAPHICS_RESOLUTION_OPTIM": "Çözünürlük iyileştirici",
"MENU__GRAPHICS_RESOLUTION_OPTIM_DESC": "Çözünürlük iyileştirici, kare hızlarınızı artırmak için zamansal bir ölçekleme teknolojisi kullanır.~ ~Ultra Performans: En yüksek performans artışını sunar.~ ~Performans: Dengeli moddan daha yüksek bir performans artışı sunar.~ ~Dengeli: Hem optimize edilmiş performans hem de görüntü kalitesi sunar.~ ~Kalite: Dengeli moddan daha yüksek görüntü kalitesi sunar.~ ~Ultra Kalite: Performansa büyük etkisiyle birlikte en iyi görüntü kalitesini sunar.",
"MENU__GRAPHICS_SETTINGS": "Grafik",
"MENU__GRAPHICS_ULTRA": "Ultra",
"MENU__HDR_ADJUST": "Hem karanlık hem de aydınlık bölgelerde ayrıntıları görebilene dek parlaklığı {STR_MENU_LEFT} ve {STR_MENU_RIGHT} ile ayarlayın.",
"MENU__HDR_INFO": "En iyi deneyim için lütfen oyunu çalıştırmadan önce HDR'yi ayarlayın.",
"MENU__HDR_SETTINGS": "HDR Ayarları",
"MENU__HDR_SETTINGS_DESC": "HDR ayar menüsünü açar.",
"MENU__HDR10": "HDR",
"MENU__HDR10_DESC": "HDR işlemeyi etkinleştirir.",
"MENU__HELPER": "Yardım sıklığı",
"MENU__HELPER_DESC": "Yardım belirmeden önceki süreyi devre dışı bırakır veya ayarlar.",
"MENU__HELPER_LONG": "Uzun",
"MENU__HELPER_NORMAL": "Normal",
"MENU__HELPER_OFF": "Kapalı",
"MENU__HELPER_SHORT": "Kısa",
"MENU__HUD_ANIMATED": "Sabit arka plan",
"MENU__HUD_ANIMATED_DESC": "Menülerin arkasındaki hareketli arka planları devre dışı bırakır.",
"MENU__HUD_CONTRAST": "Kontrastlı HUD",
"MENU__HUD_CONTRAST_DESC": "Okunabilirliği artırmak için bazı arayüz ögelerinin arkasına opak arka planlar ekler.",
"MENU__HUD_CUSTOM": "Özel",
"MENU__HUD_IMMERSIVE": "Sürükleyici",
"MENU__HUD_NORMAL": "Standart",
"MENU__HUD_PRESET": "HUD ön ayarı",
"MENU__HUD_PRESET_DESC": "Ekranda görüntülenen arayüz ögelerini değiştirmenizi sağlar.~ ~Standart: Tüm göstergelerin ve arayüz ögelerinin görüntülendiği normal oyun deneyimi.~ ~Sürükleyici: Çoğu gösterge ve arayüz ögesi devre dışıdır. Bu oyun modunu seçmek daha fazla dikkat gerektirir. Bu seçenekleri Ayarlar menüsünden istediğiniz zaman değiştirebilirsiniz.",
"MENU__HUD_SETTINGS": "Gelişmiş HUD ayarları",
"MENU__INVERT_CAMERA_X": "Kamera yatay eksenini ters çevir",
"MENU__INVERT_CAMERA_X_DESC": "Kameranın yatay eksenini ters çevirir.",
"MENU__INVERT_CAMERA_Y": "Kamera dikey eksenini ters çevir",
"MENU__INVERT_CAMERA_Y_DESC": "Kameranın dikey eksenini ters çevirir.",
"MENU__INVERT_JOYSTICK": "Çubuk değiştir",
"MENU__INVERT_JOYSTICK_DESC": "Sol ve sağ analog çubukları yer değiştirir. Kamera kontrolü sol çubukta, hareket ise sağ çubukta olur.",
"MENU__INVINCIBLE": "Yenilmez modu",
"MENU__INVINCIBLE_DESC": "Bu modu etkinleştirmek, insan düşmanlara karşı yenilmezlik sağlar (ateş, fareler ve diğer çevresel tehlikelerin hâlâ ölümcül olduğunu unutmayın).",
"MENU__INVINCIBLE_DISCLAIMER": "Bu modu etkinleştirmek insanlara karşı yenilmez olmanızı sağlar (fareler, ateş ve diğerleri ölümcül kalır). Dikkat, bu mod deneyimi zayıflatır ve yalnızca erişilebilirlik nedeniyle etkinleştirmenizi öneririz.",
"MENU__LANGUAGE_VO_ARABIC": "Arapça",
"MENU__LANGUAGE_VO_CHINESE": "Basitleştirilmiş Çince",
"MENU__LANGUAGE_VO_CZECH": "Çekçe",
"MENU__LANGUAGE_VO_ENGLISH": "İngilizce",
"MENU__LANGUAGE_ENGLISH": "Türkçe (by MiAsimBilir)",
"MENU__LANGUAGE_VO_FRENCH": "Fransızca",
"MENU__LANGUAGE_VO_GERMAN": "Almanca",
"MENU__LANGUAGE_VO_ITALIAN": "İtalyanca",
"MENU__LANGUAGE_VO_JAPAN": "Japonca",
"MENU__LANGUAGE_VO_KOREAN": "Korece",
"MENU__LANGUAGE_VO_POLISH": "Lehçe",
"MENU__LANGUAGE_VO_PORTUGUESE": "Portekizce (Brezilya)",
"MENU__LANGUAGE_VO_RUSSIAN": "Rusça",
"MENU__LANGUAGE_VO_SPANISH": "İspanyolca",
"MENU__LANGUAGE_VO_SPANISH_US": "İspanyolca~(Latin Amerika)",
"MENU__LANGUAGE_VO_TCHINESE": "Geleneksel Çince",
"MENU__LANGUAGE_VO_UKRAINIAN": "Ukraynaca",
"MENU__LANGUAGES_SETTINGS": "Dil",
"MENU__LAST_SAVE": "Kontrol noktasından başlat",
"MENU__LAST_SAVE_CONFIRM": "Kontrol noktasından başlatılsın mı?",
"MENU__LIGHT_SHAFTS": "Işık huzmeleri",
"MENU__LIGHT_SHAFTS_DESC": "Işık huzmelerinin kalitesini ayarlar.",
"MENU__LOAD_SLOT": "Onayla",
"MENU__MAIN_MENU": "Ana menü",
"MENU__MAIN_MENU_CONFIRM": "Kaydedilmemiş tüm ilerleme kaybolacak. ~Ana menüye çıkılsın mı?",
"MENU__MORE_OPTIONS": "Daha fazla ayar",
"MENU__MORE_OPTIONS_DESC": "Deneyiminizi özelleştirmek için daha fazla seçeneğe erişin.",
"MENU__MOTION_BLUR": "Hareket bulanıklığı",
"MENU__MOTION_BLUR_DESC": "Hareket bulanıklığını etkinleştirir.",
"MENU__NEW_GAME": "Yeni Oyun",
"MENU__NEW_GAME_PLUS": "Yeni Oyun+",
"MENU__NEW_GAME_PLUS_CREATION": "YO+ oluştur",
"MENU__NEW_GAME_PLUS_DESCRIPTION": "Artık son oynayışınızda elde ettiğiniz tüm Kodeks, Yükseltme ve Yeteneklerle, özel bir zorluk seviyesinde yeni bir oyun yuvası oluşturabilirsiniz.",
"MENU__NG_COMPLETED": "Macera tamamlandı",
"MENU__NG_PLUS_COMPLETED": "Yeni Oyun+ tamamlandı",
"MENU__NO_EMPTY_SLOTS": "Boş yuva yok. 1 kayıtlı oyunu silmelisiniz.",
"MENU__NPC_FREQUENCY": "NPC yenileme hızı",
"MENU__NPC_FREQUENCY_DESC": "Ekrandaki oyuncu olmayan karakterlerin yenileme hızını ayarlar. İşlemci kullanımını azaltır.",
"MENU__PHOTO_ABERRATION": "Renk sapması",
"MENU__PHOTO_ADJUSTMENTS": "Ayarlamalar",
"MENU__PHOTO_AMICIA": "Amicia",
"MENU__PHOTO_BRIGHTNESS": "Parlaklık",
"MENU__PHOTO_CAMERA": "Kamera",
"MENU__PHOTO_CAPTURE": "Yakala",
"MENU__PHOTO_CHARACTER": "Karakter",
"MENU__PHOTO_COLOR": "Renk",
"MENU__PHOTO_COMPANIONS": "Yoldaşlar",
"MENU__PHOTO_CONTRAST": "Kontrast",
"MENU__PHOTO_DEPTH_OF_FIELD": "Alan derinliği",
"MENU__PHOTO_ENEMIES": "Düşmanlar",
"MENU__PHOTO_EXIT": "Çık",
"MENU__PHOTO_EXPOSURE": "Pozlama",
"MENU__PHOTO_FOCAL": "Odak",
"MENU__PHOTO_GRAIN": "Gren",
"MENU__PHOTO_HIDE": "Gizli",
"MENU__PHOTO_HUGO": "Hugo",
"MENU__PHOTO_MODE": "Fotoğraf modu",
"MENU__PHOTO_MOVE": "Hareket ettir",
"MENU__PHOTO_NAVIGATE": "Gezin",
"MENU__PHOTO_NEAR_FOCUS": "Yakın odak mesafesi",
"MENU__PHOTO_OTHER": "Diğer karakterler ve hayvanlar",
"MENU__PHOTO_RATS": "Fareler",
"MENU__PHOTO_RESET": "Sıfırla",
"MENU__PHOTO_ROTATE": "Döndür",
"MENU__PHOTO_SATURATION": "Doygunluk",
"MENU__PHOTO_SHARPEN": "Keskinleştir",
"MENU__PHOTO_SHOW_UI": "Arayüzü Göster / Gizle",
"MENU__PHOTO_SHOWN": "Gösteriliyor",
"MENU__PHOTO_TILT": "Eğ",
"MENU__PHOTO_UPDOWN": "Yukarı / Aşağı",
"MENU__PHOTO_VIGNETTE": "Vinyet",
"MENU__PHOTO_VISIBILITY": "Görünürlük",
"MENU__POSTPROCESS_COLOR_GRADING": "Renk derecelendirme",
"MENU__POSTPROCESS_EYE_ADAPTATION": "Göz uyumu",
"MENU__POSTPROCESS_FILM_GRAIN": "Film greni",
"MENU__POSTPROCESS_FRINGE": "Renk sapması",
"MENU__POSTPROCESS_FRINGE_DESC": "Renk sapmasını etkinleştirir.",
"MENU__POSTPROCESS_FRINGE_LOW": "Düşük",
"MENU__POSTPROCESS_FRINGE_NORMAL": "Normal",
"MENU__POSTPROCESS_LENS_BLUR": "Mercek bulanıklığı",
"MENU__POSTPROCESS_LENS_DIRT": "Mercek kiri",
"MENU__POSTPROCESS_LENS_DISTORTION": "Mercek bozulması",
"MENU__POSTPROCESS_LENS_FLARE": "Mercek parlaması",
"MENU__POSTPROCESS_SHARPEN": "Keskinleştirme",
"MENU__POSTPROCESS_VIGNETTE": "Vinyet",
"MENU__PRE_ORDER_BONUS_01": "Kızıl Hanımefendi",
"MENU__PRE_ORDER_BONUS_01_DESCRIPTION": "Arbalet için özel bir boya kazandınız. Donatmak için Ekstralar menüsüne gidin.",
"MENU__PRE_ORDER_BONUS_02": "Üretim Malzemesi",
"MENU__PRE_ORDER_BONUS_02_DESCRIPTION": "İlk tezgâhta ekipmanınızı yükseltmek için Bir Alet ve birkaç Parça elde edeceksiniz",
"MENU__PRE_ORDER_BONUS_03": "Hugo'nun Bitki Koleksiyonu",
"MENU__PRE_ORDER_BONUS_03_DESCRIPTION": "Hugo'nun A Plague Tale: Innocence'ta topladığı tüm çiçekler Kodeks'te donatılabilir.",
"MENU__PRE_ORDER_BONUS_DESCRIPTION": "Ek içerik kilidi açıldı.",
"MENU__PRE_ORDER_BONUS_TITLE": "Koruyucu Paketi kilidi açıldı",
"MENU__PRE_ORDER_CROSSBOW_EQUIPPED": "Donatıldı",
"MENU__PRE_ORDER_CROSSBOW_SELECTION": "Arbalet Seçimi",
"MENU__PRE_ORDER_CROSSBOW_SKIN1": "Joseph'in arbaleti",
"MENU__PRE_ORDER_CROSSBOW_SKIN1_DESCRIPTION": "V. Bölüm'de kilidi açılır",
"MENU__PRE_ORDER_CROSSBOW_SKIN2": "Düzen'in arbaleti",
"MENU__PRE_ORDER_CROSSBOW_SKIN2_DESCRIPTION": "Oyunu bitirerek kilidi açılır",
"MENU__PRE_ORDER_CROSSBOW_SKIN3": "Kont'un arbaleti",
"MENU__PRE_ORDER_CROSSBOW_SKIN3_DESCRIPTION": "YO+ bitirerek kilidi açılır",
"MENU__PRE_ORDER_CROSSBOW_SKIN4": "Kızıl Hanımefendi",
"MENU__PRE_ORDER_CROSSBOW_SKIN4_DESCRIPTION": "Koruyucu Paketi",
"MENU__PRE_ORDER_CROSSBOW_TITLE": "Arbaletinizi seçin",
"MENU__QUIT": "Masaüstüne çık",
"MENU__QUIT_CONFIRM": "Kaydedilmemiş tüm ilerleme kaybolacak ~Oyundan çıkıp masaüstüne dönülsün mü?",
"MENU__RATS_FREQUENCY": "Fare yenileme hızı",
"MENU__RATS_FREQUENCY_DESC": "Ekrandaki farelerin yenileme hızını ayarlar. İşlemci kullanımını azaltır.",
"MENU__RATS_LOD": "Hareketli fare sayısı",
"MENU__RATS_LOD_DESC": "Ekrandaki hareketli fare sayısını ayarlar. İşlemci kullanımını azaltır.",
"MENU__RAYTRACED_SHADOWS": "Işın izlemeli gölgeler",
"MENU__RAYTRACED_SHADOWS_DESC": "Gölgeler için ışın izleme kullanımını etkinleştirir.",
"MENU__RAYTRACING": "Işın izleme",
"MENU__RAYTRACING_DESC": "Işın izleme kullanımını etkinleştirir.",
"MENU__READ_DATAGATHERING": "Veri Toplama bildirimini oku",
"MENU__READ_EULA": "Son Kullanıcı Lisans Sözleşmesi'ni oku",
"MENU__REFLEX": "NVIDIA Reflex Düşük Gecikme",
"MENU__REFLEX_BOOST": "Etkin+Hızlandırma",
"MENU__REFLEX_DESC": "NVIDIA Reflex, sistem gecikmesini azaltarak PC yanıt hızını artırmak için kullanılır.",
"MENU__REFLEX_OFF": "Devre dışı",
"MENU__REFLEX_ON": "Etkin",
"MENU__RESET_SETTINGS_CONFIRM": "Bu ayarları sıfırlamak istediğinizden emin misiniz?",
"MENU__RESET_TO_DEFAULT": "Varsayılana sıfırla",
"MENU__RESOLUTION_SCALE": "Çözünürlük ölçeği",
"MENU__RESOLUTION_SCALE_DESC": "Oyunun işleme ölçeğini ayarlamanızı sağlar.",
"MENU__RESTART": "Bölümü yeniden başlat",
"MENU__RESTART_CONFIRM": "Son bölüm yeniden başlatılsın mı?",
"MENU__RESUME": "Oyuna devam et",
"MENU__RTAO": "Işın izlemeli ortam örtüşmesi",
"MENU__RTAO_DESC": "Ortam örtüşmesi için ışın izleme kullanımını etkinleştirir.",
"MENU__SCREEN_RESOLUTION": "Ekran çözünürlüğü",
"MENU__SCREEN_RESOLUTION_APPLY": "Çözünürlüğü uygula",
"MENU__SCREEN_RESOLUTION_DESC": "İşleme çözünürlüğünü ayarlamanızı sağlar.",
"MENU__SELECT_SETTINGS": "Ayarlarınızı seçin",
"MENU__SENSITIVITY_AIM": "Nişan alma duyarlılığı",
"MENU__SENSITIVITY_AIM_DESC": "Nişan alırken kameranın hızını ayarlar.",
"MENU__SENSITIVITY_CAMERA": "Kamera duyarlılığı",
"MENU__SENSITIVITY_CAMERA_DESC": "Nişan almadığınızda kameranın hızını ayarlar.",
"MENU__SENSITIVITY_MOUSE": "Fare duyarlılığı",
"MENU__SENSITIVITY_MOUSE_DESC": "Fare duyarlılığını ayarlar.",
"MENU__SENSITIVITY_MOVEMENT": "Hareket duyarlılığı",
"MENU__SENSITIVITY_MOVEMENT_DESC": "Hareketin duyarlılığını ayarlar.",
"MENU__SETTINGS": "Ayarlar",
"MENU__SETTINGS_TOGGLE_ACTIVATE": "Evet",
"MENU__SETTINGS_TOGGLE_DEACTIVATE": "Hayır",
"MENU__SHADOW_MAPS": "Gölge haritaları",
"MENU__SHADOW_MAPS_DESC": "Gölge kalitesini ayarlar.",
"MENU__SLOT_1": "Yuva 1",
"MENU__SLOT_2": "Yuva 2",
"MENU__SLOT_3": "Yuva 3",
"MENU__SLOT_SELECTION": "Bir yuva seçin",
"MENU__SS_REFLECTIONS": "Ekran uzayı yansımaları",
"MENU__SS_REFLECTIONS_DESC": "Ekran uzayı yansımalarının kalitesini ayarlar.",
"MENU__START": "{STR_MENU_VALID} tuşuna basın",
"MENU__START_PC": "Herhangi bir tuşa basın",
"MENU__SUBTITLE_LANGUAGE": "Altyazı dili",
"MENU__SUBTITLE_LANGUAGE_DESC": "Altyazıların dilini değiştirir.",
"MENU__SUBTITLES_BACKGROUND": "Arka plan",
"MENU__SUBTITLES_BACKGROUND_COLOR": "Arka plan rengi",
"MENU__SUBTITLES_BACKGROUND_COLOR_DESC": "Okunabilirliği artırmak için altyazı arka planının rengini değiştirir.",
"MENU__SUBTITLES_BACKGROUND_DESC": "Okunabilirliği artırmak için altyazıların arkasında koyu bir arka plan etkinleştirir.",
"MENU__SUBTITLES_BACKGROUND_OPACITY": "Arka plan saydamlığı",
"MENU__SUBTITLES_BACKGROUND_OPACITY_DESC": "Altyazı arka planının saydamlığını ayarlar.",
"MENU__SUBTITLES_COLOR": "Renk",
"MENU__SUBTITLES_COLOR_BLACK": "Siyah",
"MENU__SUBTITLES_COLOR_BLUE": "Mavi",
"MENU__SUBTITLES_COLOR_DESC": "Okunabilirliği artırmak için altyazıların rengini değiştirir.",
"MENU__SUBTITLES_COLOR_GREEN": "Yeşil",
"MENU__SUBTITLES_COLOR_RED": "Kırmızı",
"MENU__SUBTITLES_COLOR_WHITE": "Beyaz",
"MENU__SUBTITLES_COLOR_YELLOW": "Sarı",
"MENU__SUBTITLES_SIZE": "Boyut",
"MENU__SUBTITLES_SIZE_DESC": "Altyazı metninin boyutunu ayarlar.",
"MENU__SUBTITLES_SIZE_LARGE": "Büyük",
"MENU__SUBTITLES_SIZE_MEDIUM": "Orta",
"MENU__SUBTITLES_SIZE_SMALL": "Küçük",
"MENU__SUBTITLES_SPEAKER_COLOR": "Karakter adları rengi",
"MENU__SUBTITLES_SPEAKER_COLOR_DESC": "Altyazılarda her karakter adına belirli bir renk atar.",
"MENU__TAA": "TAA",
"MENU__TEXT_LANGUAGE": "Metin dili",
"MENU__TEXT_LANGUAGE_DESC": "Ekrandaki metnin dilini değiştirir.",
"MENU__TEXTURES_QUALITY": "Doku kalitesi",
"MENU__TEXTURES_QUALITY_DESC": "Dokuların kalitesini ayarlar.",
"MENU__TRIAL_BACK": "Geri",
"MENU__TRIAL_NEXT": "İleri",
"MENU__TRIAL_QUIT": "Ana menü",
"MENU__TRIAL_SAVE_FALSE": "Seçili yuva, tam oyunun kayıt verilerini içeriyor. Yeni bir oyuna başlamadan önce lütfen verileri silin.",
"MENU__TRIAL_SHOP": "Tam sürümü indir",
"MENU__TRIAL_VERSION": "Deneme sürümü",
"MENU__USE_AIM_ASSIST": "Nişan yardımını kullan",
"MENU__USE_AIM_ASSIST_DESC": "Nişan Yardımı, bir düşman hedefinin üzerine geldiğinizde nişangâhınızın hareketini hafifçe yavaşlatır.",
"MENU__VIBRATION": "Titreşim",
"MENU__VIBRATION_DESC": "Kumandanın titreşimini ayarlar.",
"MENU__VIBRATION_LOW": "Düşük",
"MENU__VIBRATION_NORMAL": "Normal",
"MENU__VIBRATION_OFF": "Kapalı",
"MENU__VOLUMETRIC_LIGHTS": "Hacimsel ışıklar",
"MENU__VOLUMETRIC_LIGHTS_DESC": "Hacimsel ışıkların kalitesini ayarlar.",
"MENU__VSYNC": "Dikey eşitleme",
"MENU__VSYNC_DESC": "Dikey eşitlemeyi etkinleştirir.",
"MENU__WINDOWED": "Pencereli",
"MENU__WORK_IN_PROGRESS": "Yapım aşamasında",
}
