# -*- coding: utf-8 -*-
# OBJECTIVE kategorisi (gorev hedefleri). Ozel isimler korunur.
T = {
"OBJECTIVE__CH1_ATTACKCASTLE": "Kaleye saldır",
"OBJECTIVE__CH1_FINDENTRANCE": "Nehri takip et",
"OBJECTIVE__CH1_FINDOTHERS": "Diğerlerini bul",
"OBJECTIVE__CH1_FOLLOWHUGO": "Kral Hugo'yu takip et",
"OBJECTIVE__CH1_FOLLOWPHOENIX": "Kuşu takip et",
"OBJECTIVE__CH1_GETBEHINDLOG": "Kütüğün arkasına geç",
"OBJECTIVE__CH1_GETOUTOFFARM": "Kaleden çıkış yolu bul",
"OBJECTIVE__CH1_GETSLINGBACK": "Sapanı geri al",
"OBJECTIVE__CH1_HIDEFROMLUCAS": "Hain Lucas'tan saklan",
"OBJECTIVE__CH1_REACHBIGTOWER": "Kaleye ulaş",
"OBJECTIVE__CH1_REACHCITY": "Şehre ulaş",
"OBJECTIVE__CH1_SAVEBEATRICE": "Beatrice'i kurtar",
"OBJECTIVE__CH1_SCARELUCAS": "Hain Lucas'ı korkut",
"OBJECTIVE__CH1_SHOOT": "Kral Hugo'nun krallığını savun",
"OBJECTIVE__CH2_CRAFTIGNIFER": "Biraz Ignifer üret",
"OBJECTIVE__CH2_EXITUNDERGROUNDS": "Arenanın yer altı bölgelerinden çık",
"OBJECTIVE__CH2_EXPLOREALCOVES": "Girintileri keşfet",
"OBJECTIVE__CH2_FINDHERBALIST": "Çiçekçiyi bul",
"OBJECTIVE__CH2_FINDHERBALISTHUSBAND": "Çiçekçinin kocasını bul",
"OBJECTIVE__CH2_FINDVAUDIN": "Vaudin'i bul",
"OBJECTIVE__CH2_FOLLOWORDERSYMBOLS": "Düzen'in sembollerini takip et",
"OBJECTIVE__CH2_GETALCOHOL": "Alkol al",
"OBJECTIVE__CH2_GETSULPHUR": "Kükürt al",
"OBJECTIVE__CH2_GETSULPHURANDALCOHOL": "Kükürt ve alkol al",
"OBJECTIVE__CH2_LIGHTBRASERO": "Merkezdeki mangalı yak",
"OBJECTIVE__CH2_LOWERPLATFORM": "Merkezdeki platformu indir",
"OBJECTIVE__CH2_REACHTOWER": "Güney kulesine ulaş",
"OBJECTIVE__CH2_REJOINLUCAS": "Lucas'la yeniden buluş",
"OBJECTIVE__CH2_REORDERSYMBOLS": "Sembolleri doğru sıraya diz",
"OBJECTIVE__CH2_TOHOUSE": "Eve yürü",
"OBJECTIVE__CH2_TOTHEARENA": "Arenaya ulaş",
"OBJECTIVE__CH2_WAYINARENA": "Arenanın içine girecek bir yol bul",
"OBJECTIVE__CH3_ESCAPEDUNGEON": "Zindandan kaç",
"OBJECTIVE__CH3_ESCAPEFORT": "Hisardan kaç",
"OBJECTIVE__CH3_FINDANDHELPLUCAS": "Lucas'ı bul ve kurtar",
"OBJECTIVE__CH3_FINDANESCAPE": "Şaşırtma yaratacak bir yol bul",
"OBJECTIVE__CH3_FINDNIGHTSHADE": "Eşyaları bul",
"OBJECTIVE__CH3_GETBELONGINGS": "Eşyaları depodan geri al",
"OBJECTIVE__CH3_GETTOHERBORIST": "Şifacının ormanına ulaş",
"OBJECTIVE__CH3_SAVEHERBALIST": "Şifacıyı kurtar",
"OBJECTIVE__CH3_SURVIVEASSAULT": "Saldırıdan sağ çık",
"OBJECTIVE__CH3_TOTHEBUTCHERDISTRICT": "Lucas'ı kasaplar mahallesine kadar takip et",
"OBJECTIVE__CH3_USEBALLISTA": "Şaşırtma yaratmak için balistayı kullan",
"OBJECTIVE__CH3_USEWORKBENCH": "Tezgâhı kullan",
"OBJECTIVE__CH3_WAYOUTOFCITY": "Şehirden çık",
"OBJECTIVE__CH4_ASKLUCAS": "Lucas'tan malzeme iste",
"OBJECTIVE__CH4_COOPERATEWITHSOLDIER": "İskeleyi geçmek için askerle iş birliği yap",
"OBJECTIVE__CH4_CRAFTTAR": "Katran üret",
"OBJECTIVE__CH4_FINDBOAT": "Düzen'in teknesini bul",
"OBJECTIVE__CH4_REACHBOAT": "Düzen'in teknesine ulaş",
"OBJECTIVE__CH4_REACHBOATMAN": "İskeledeki Joseph'e ulaş",
"OBJECTIVE__CH4_REACHRIVER": "Nehre ulaş",
"OBJECTIVE__CH4_REJOINLUCAS": "Lucas'ın yanına dön",
"OBJECTIVE__CH4_RUN": "Farelerden kaç",
"OBJECTIVE__CH4_SAVEBOATMAN": "Joseph'i kurtar",
"OBJECTIVE__CH4_TOTHEDOCKS": "Rıhtıma ulaş",
"OBJECTIVE__CH5_ARNAUD": "Arnaud'dan kaç",
"OBJECTIVE__CH5_CLEARBOATPATH": "Tekne için yolu aç",
"OBJECTIVE__CH5_CROSSCAMP": "İnşaat alanını geç",
"OBJECTIVE__CH5_DEALWITHBANDITS": "Haydutlardan kurtul",
"OBJECTIVE__CH5_FINDAWAYTOBOAT": "Tekneye ulaşacak bir yol bul",
"OBJECTIVE__CH5_FREEBOAT": "Tekneyi kurtar",
"OBJECTIVE__CH5_HELPLUCAS": "Lucas'a yardım et",
"OBJECTIVE__CH5_REACHFAMILY": "Arnaud'dan önce tekneye ulaş",
"OBJECTIVE__CH5_UNBLOCKBOAT": "Tekneyi kurtar",
"OBJECTIVE__CH6_ASKWAY": "Kıyıya giden yolu sor",
"OBJECTIVE__CH6_DEALWITHCAPTAIN": "Canavar'la hesaplaş",
"OBJECTIVE__CH6_DEALWITHSOLDIERS": "Askerlerle hesaplaş",
"OBJECTIVE__CH6_ESCAPE": "Askerlerden kaç",
"OBJECTIVE__CH6_EXITDYEWORKS": "Boyahaneden çık",
"OBJECTIVE__CH6_REACHBUILDING": "Binaya ulaş",
"OBJECTIVE__CH6_RUNFROMRATS": "Farelerden kaç",
"OBJECTIVE__CH6_WAYOUT": "Çıkış yolu bul",
"OBJECTIVE__CH6_WAYOUTOFBUILDING": "Binadan çıkış yolu bul",
"OBJECTIVE__CH6_WAYTOCOAST": "Kıyıya giden bir yol bul",
"OBJECTIVE__CH7_CROSSBEACH": "Sahili geç",
"OBJECTIVE__CH7_CROSSCAVES": "Mağaraları geç",
"OBJECTIVE__CH7_EXITCAVES": "Mağaralardan çık",
"OBJECTIVE__CH7_FINDAWAYTOCROSS": "Arnaud'ya bir yol aç",
"OBJECTIVE__CH7_FINDSMUGGLERSDEN": "Kaçakçının inini bul",
"OBJECTIVE__CH7_FOLLOWHUGO": "Hugo'ya yetiş",
"OBJECTIVE__CH7_FREEBOAT": "Sophia'nın teknesini kurtar",
"OBJECTIVE__CH7_REACHBOAT": "Sophia'nın teknesine ulaş",
"OBJECTIVE__CH7_REACHWRECK": "Gemi enkazına ulaş",
"OBJECTIVE__CH8_BACKTOARNAUD": "Arnaud'yu bul",
"OBJECTIVE__CH8_ENTERVILLAGE": "Köye gir",
"OBJECTIVE__CH8_ESCAPE": "Kont'un askerlerinden kaç",
"OBJECTIVE__CH8_ESCAPEFROMFALCONEER": "Doğancıdan kaç",
"OBJECTIVE__CH8_EXPLOREBOAT": "Diğerleriyle konuş",
"OBJECTIVE__CH8_FINDTOOL": "Hugo'yla tekneyi keşfet",
"OBJECTIVE__CH8_FOLLOWCOUNTESS": "Kont ve Kontes'i takip et",
"OBJECTIVE__CH8_FOLLOWPROCESSION": "Geçit törenini takip et",
"OBJECTIVE__CH8_REACHPLAZA": "Ada hakkında bilgi için etrafına bak",
"OBJECTIVE__CH8_STOPARNAUD": "Arnaud'yu durdur",
"OBJECTIVE__CH8_TALKTOSOPHIA": "Yanaşmak için Sophia'yla konuş",
"OBJECTIVE__CH9_AROUNDCHECKPOINT": "Kontrol noktasının etrafından dolaşacak bir yol bul",
"OBJECTIVE__CH9_ENTERQUARTERS": "Kutsal bölgeye ulaş",
"OBJECTIVE__CH9_EXPLOREISLAND": "Adayı keşfet",
"OBJECTIVE__CH9_EXPLOREQUARTERS": "Kutsal bölgeyi keşfet",
"OBJECTIVE__CH9_FINDMAP": "Harabelerin neyi sakladığını öğren",
"OBJECTIVE__CH9_FOLLOWRITUAL": "Ayini izle",
"OBJECTIVE__CH9_FOLLOWSTATUES": "Kuş heykellerini takip et",
"OBJECTIVE__CH9_LEAVESANCTUARY": "Mabetten ayrıl",
"OBJECTIVE__CH9_REACHSANCTUARY": "Las Madres'e ulaş",
"OBJECTIVE__CH9_SIDEENTRANCE": "Mabedin içine başka bir yol bul",
"OBJECTIVE__CH10_CROSSCOURTYARD": "Avluyu geç",
"OBJECTIVE__CH10_ENTERCHAPEL": "Şapele gir",
"OBJECTIVE__CH10_FINDAELIA": "Aelia'nın izini bul",
"OBJECTIVE__CH10_FINDAWAYTOTHEFORT": "Hisara giden bir yol bul",
"OBJECTIVE__CH10_FINDCHAPEL": "Hisarı bul",
"OBJECTIVE__CH10_FINDROUNDTOWER": "Yuvarlak kuleyi bul",
"OBJECTIVE__CH10_INNERCOURTYARD": "İç avluya ulaş",
"OBJECTIVE__CH10_REACHFORT": "Hisara ulaş",
"OBJECTIVE__CH10_SURVIVE": "Saldırıdan sağ çık",
"OBJECTIVE__CH10_USEPRISM": "Sophia'nın prizmasını kullan",
"OBJECTIVE__CH11_BACKTOMAP": "Adanın merkezindeki harabelere ulaş",
"OBJECTIVE__CH11_ENTERTOMB": "Harabelere gir",
"OBJECTIVE__CH11_EXPLOREREMAINS": "Yer altı bölgesinin geri kalanını keşfet",
"OBJECTIVE__CH11_EXPLOREUNDERGROUNDS": "Yer altı bölgesini keşfet",
"OBJECTIVE__CH11_FINDAWAYINSIDE": "Harabelerin içine girecek bir yol bul",
"OBJECTIVE__CH11_OPENGATE": "Kapıyı aç",
"OBJECTIVE__CH11_RUNAWAY": "Taşıyıcının zindanından kaç",
"OBJECTIVE__CH11_SHOOTATTANK": "Tanka ateş et",
"OBJECTIVE__CH12_ATTACKCOUNT": "Kont'a saldır",
"OBJECTIVE__CH12_ESCAPECELLAR": "Mahzenden çıkış yolu bul",
"OBJECTIVE__CH12_ESCAPECOUNT": "Kont'tan kaç",
"OBJECTIVE__CH12_FINDAMICIA": "Amicia'yı bul",
"OBJECTIVE__CH12_FOLLOWCOUNT": "Kont'u takip et",
"OBJECTIVE__CH12_FOLLOWSOLDIER": "Askeri takip et",
"OBJECTIVE__CH12_KILLCOUNTESS": "Merkez sahnedeki Kontes'i öldür",
"OBJECTIVE__CH12_REACHHARBOR": "Limana ulaş",
"OBJECTIVE__CH12_TRIGGEROVERCHARGE": "Hugo'yu sınıra zorla",
"OBJECTIVE__CH13_EXITBASEMENT": "Yüzeye çıkacak bir yol bul",
"OBJECTIVE__CH13_FREEARNAUD": "Arnaud'yu kurtar",
"OBJECTIVE__CH13_REACHBOAT": "Tekneye ulaş",
"OBJECTIVE__CH13_REACHPORT": "Limana ulaş",
"OBJECTIVE__CH13_REACHSURFACE": "Yüzeye ulaş",
"OBJECTIVE__CH13_THROUGHNEST": "Fare yuvasını geç",
"OBJECTIVE__CH14_PROTECTSOPHIAANDLUCAS": "Sophia ve Lucas'ı koru",
"OBJECTIVE__CH14_SAVEARNAUD": "Arnaud'yu kurtar",
"OBJECTIVE__CH14_SPEEDBOAT": "Kont'un teknesinden uzaklaş",
"OBJECTIVE__CH14_TALKTOCREW": "Diğerleriyle konuş",
"OBJECTIVE__CH14_TALKTOHUGO": "Hugo'yla konuş",
"OBJECTIVE__CH15_HUGO": "Hugo'ya ulaş",
"OBJECTIVE__CH15_JOINGROUP": "Lucas ve Sophia'yla yeniden buluş",
"OBJECTIVE__CH15_KILLCOUNT": "Kont'u öldür",
"OBJECTIVE__CH15_SAVEARNAUD": "Arnaud'yu kurtar",
"OBJECTIVE__CH16_FINDHUGO": "Hugo'yu bul",
"OBJECTIVE__CH16_REACHHUGO": "Hugo'ya ulaş",
"OBJECTIVE__CH17_GETTOHORSES": "Atlara ulaş",
"OBJECTIVE__CH17_REACHSUMMIT": "Zirveye ulaş",
}
