# -*- coding: utf-8 -*-
# TRC kategorisi (sistem/yasal mesajlar). URL+renk kodlu satirlar (LINK) degismez.
T = {
"TRC__AUTOSAVE_NOTIFICATION": "Bu oyun otomatik kaydetme özelliği kullanır. Otomatik kaydetme göstergesi görünürken cihazın gücünü kapatmayın.~ ~Türkçe çeviri: MiAsimBilir",
"TRC__CANCEL": "İptal",
"TRC__CHAPTER_INSTALLING_IN_GAME": "Sonraki bölümün kurulumu henüz tamamlanmadı. Hazır olduğunda otomatik olarak yüklenmeye başlayacak.",
"TRC__CHAPTER_INSTALLING_MAIN_MENU": "Bu bölümün kurulumu henüz tamamlanmadı.",
"TRC__CONTROLLER_DISCONNECTED": "Kumanda bağlantısı kesildi. Lütfen bir kumanda yeniden bağlayın, ardından devam etmek için {STR_MENU_VALID} tuşuna basın.",
"TRC__ENDUSER_AGREEMENT_AGREE": "Kabul ediyorum",
"TRC__ENDUSER_AGREEMENT_DESC": "Oyunu oynamak için lütfen Son Kullanıcı Lisans Sözleşmemizi kabul edin.~ ~Bu belgeyle, Lisans Sözleşmesi'ni okuyup anladığınızı ve Multimedya Programının kurulumunun, aşağıdaki hükümlerle sözleşme yoluyla bağlı olmayı kabul ettiğinizin teyidi olduğunu onayladığınızı kabul edersiniz. Bu Lisans Sözleşmesi'nin yalnızca Focus Entertainment ile sizin aranızdaki tüm anlaşmayı belirttiğini ve Lisans Sözleşmesi'nin, sözlü ya da yazılı olsun önceki veya mevcut her türlü anlaşmanın yanı sıra, Multimedya Programına eşlik eden ve bu şartlarla tutarsız ve/veya bunlara aykırı olan her türlü yazılı lisans sözleşmesi dâhil olmak üzere, Focus Entertainment ile sizin aranızdaki diğer her türlü iletişimin yerini aldığını kabul ve beyan edersiniz.",
"TRC__ENDUSER_AGREEMENT_READ": "Son Kullanıcı Lisans Sözleşmemizi şu adreste okuyun:",
"TRC__ENDUSER_AGREEMENT_REFUSE": "Reddediyorum",
"TRC__ENDUSER_AGREEMENT_TITLE": "Son Kullanıcı Lisans Sözleşmesi",
"TRC__GAME_CORRUPTED": "Kurulu oyun bozulmuş. Oyun kapanacak. Bu oyunu oynamak için kurulu oyunu silip yeniden kurmalısınız.",
"TRC__HERO_CRAFTED": "Üretilen cephane",
"TRC__HERO_CROUCH": "Çömel",
"TRC__HERO_DARK": "Işık söndürüldü",
"TRC__HERO_LIGHT": "Işık yakıldı",
"TRC__HERO_THROWN": "El atışı",
"TRC__HERO_TIME": "Oynanan süre",
"TRC__INSTALLING": "Kuruluyor...",
"TRC__INSUFFICIENT_SPACE_FOR_SAVE_NO_SIZE": "Gerekli kayıt verisi dosyalarını oluşturmak için yeterli alan yok.",
"TRC__LOAD_CORRUPTED": "Yükleme başarısız oldu. Kayıtlı oyun hasarlı görünüyor ve kullanılamıyor. Üzerine yazmak ister misiniz?",
"TRC__NO_CONTROLLER_CONNECTED": "Bağlı kumanda yok. Devam etmek için lütfen bir kumanda bağlayın.",
"TRC__PREORDER_BONUS_LICENCE_INVALID": "Ön sipariş bonusu DLC için lisansınız geçersiz. İlgili içerik, lisansınız başarıyla geri yüklenene dek devre dışı bırakılacak.",
"TRC__RETRY": "Tekrar dene",
"TRC__RICH_PRESENCE_IDLE": "Boşta",
"TRC__RICH_PRESENCE_MENU": "Menüde",
"TRC__RICH_PRESENCE_PLAYING": "{0} oynanıyor",
"TRC__SAVE_CORRUPTED": "Mevcut kaydınız bozulmuş ve silinmesi gerekiyor. Yerine yeni bir kayıt yazılacak.",
"TRC__SETMEMBERDISPLAYNAME_1": "Yeni Bir Güneşin Altında",
"TRC__SETMEMBERDISPLAYNAME_2": "Yeni Gelenler",
"TRC__SETMEMBERDISPLAYNAME_3": "Bir Kan Yükü",
"TRC__SETMEMBERDISPLAYNAME_4": "Koruyucunun Görevi",
"TRC__SETMEMBERDISPLAYNAME_5": "Ardımızda",
"TRC__SETMEMBERDISPLAYNAME_6": "Her Şeyi Geride Bırakarak",
"TRC__SETMEMBERDISPLAYNAME_7": "Hainler",
"TRC__SETMEMBERDISPLAYNAME_8": "Vaatler Denizi",
"TRC__SETMEMBERDISPLAYNAME_9": "Hikâyeler ve İfşalar",
"TRC__SETMEMBERDISPLAYNAME_10": "Kan Bağı",
"TRC__SETMEMBERDISPLAYNAME_11": "Yüzyılların Beşiği",
"TRC__SETMEMBERDISPLAYNAME_12": "Hak Ettiğimiz Hayat",
"TRC__SETMEMBERDISPLAYNAME_13": "Geriye Hiçbir Şey Kalmadı",
"TRC__SETMEMBERDISPLAYNAME_14": "Yaralarımızı Sararken",
"TRC__SETMEMBERDISPLAYNAME_15": "Ölen Güneş",
"TRC__SETMEMBERDISPLAYNAME_16": "Kral Hugo",
"TRC__SETMEMBERDISPLAYNAME_17": "De Rune Ailesinin Mirası",
"TRC__SETTINGS_LOAD_CORRUPTED": "Yükleme başarısız oldu. Oyun ayarları hasarlı görünüyor ve kullanılamıyor. Varsayılan oyun ayarlarıyla değiştirilecekler.",
"TRC__SLOT_CORRUPTED": "Yuva bozulmuş",
"TRC__TELEMETRY_AGREE": "Telemetriyle devam et",
"TRC__TELEMETRY_DESC": "Nasıl oynadığınızı bilmek, oyunlarımızı geliştirmemize yardımcı olur!~ ~Oyunun mevcut ve gelecekteki içeriğinin mümkün olan en iyi kalitede olmasını sağlamak için biz (Asobo Studio ve Focus Entertainment) bize yararlı olacak verileri toplamak ve işlemek istiyoruz. Bu, nasıl oynadığınıza dair bilgilerin yanı sıra hata kayıtlarını ve donanım yapılandırmasını içerir. Bu işlem tamamen otomatik ve gizlidir; bu veriler en fazla iki yıllık bir sürenin ardından otomatik olarak silinecektir. Telemetriyi Ayarlar Menüsünden istediğiniz an devre dışı bırakabilir veya yeniden etkinleştirebilirsiniz.~ ~Bu verileri nasıl işlediğimiz hakkında daha fazla bilgi edinmek ve haklarınızı kullanmak için lütfen şuraya başvurun:",
"TRC__TELEMETRY_NEXT": "İleri",
"TRC__TELEMETRY_OPTION_DESC": "Oyuncu etkinliği verilerinin otomatik toplanmasını etkinleştirir",
"TRC__TELEMETRY_OPTION_OFF": "Kapalı",
"TRC__TELEMETRY_OPTION_ON": "Açık",
"TRC__TELEMETRY_OPTION_TITLE": "Telemetri",
"TRC__TELEMETRY_REFUSE": "Telemetriyi devre dışı bırak",
"TRC__TELEMETRY_TITLE": "Focus Entertainment genel kişisel veri koruma politikası",
}
