# -*- coding: utf-8 -*-
# TUTO kategorisi. {STR_...} tus kodlari ve ^761...^000 vurgu kodlari AYNEN korunur.
T = {
"TUTO__AIM_RING": "Sapanınla ^761halkaya^000 nişan almak için {STR_AIM_MODE} basılı tut.",
"TUTO__AMMO_SWITCH": "Nişan alırken {STR_CYCLE_AMMO_DOWN} tuşuna basarak ^761temel cephaneyi^000 hızlıca seçebilirsin.",
"TUTO__ARMORED": "Zırhlı düşmanlar saldırılara karşı ^761yenilmezdir^000.~Onu ortadan kaldırabilmek için ^761zayıf noktayı^000 bul ve kır.",
"TUTO__ARNAUD_ORDER": "{STR_COMPANION_ORDER_MODE} basılı tut, bir düşmana nişan al ve ardından Arnaud'yu ^761onunla dövüşmeye^000 göndermek için {STR_COMPANION_ORDER_INTERACT} tuşuna bas.",
"TUTO__ARNAUD_OUTCOME": "^761Dövüş gürültüsü^000 yakındaki düşmanları çeker.~Düşmanlar Arnaud'dan çok uzun süre fazla olursa, sonunda onu öldürürler.",
"TUTO__ATTRACT": "Odoris, kısa bir süre boyunca merminin çarptığı noktaya ^761fareleri çeker^000.~Fareleri hareket ettirmek için bir yüzeye nişan al ve bir Odoris at.",
"TUTO__ATTRACT_CRAFT": "Artık ^761Odoris^000 üretebilirsin. ~Seçim menüsünü açmak için {STR_WEAPON_SELECTION_OPEN} basılı tut.",
"TUTO__BACKWARD_COUNT": "Kont'tan ^761kaçmak^000 için geri çekil.",
"TUTO__BLAST_BAG": "Patlayıp yakındaki engelleri yok etmeleri için ^761bakır tanklara^000 bir Ignifer at.",
"TUTO__CHAINS": "Sapanınla ^761birleştirici halkaya^000 atış yaparak zincirleri kırabilirsin.",
"TUTO__COMPANION_ORDER_CANCEL": "Mevcut bir emri ^761iptal etmek^000 için {STR_COMPANION_ORDER_MODE} basılı tut, yoldaşa bak ve {STR_COMPANION_ORDER_INTERACT} tuşuna bas.",
"TUTO__COMPANION_ORDER_INTERACT": "Bir yoldaşa, vurgulanmış bir nesneyle ^761etkileşmesini^000 emretmek için onu işaretle ve {STR_COMPANION_ORDER_INTERACT} tuşuna bas.",
"TUTO__COMPANION_ORDER_LUCAS": "^761Lucas'ın yeteneğini^000 kullanmak için bir ateş kaynağına nişan al ve {STR_COMPANION_ORDER_INTERACT} tuşuna bas.",
"TUTO__COMPANION_ORDER_MODE": "Yoldaşların için ^761etkileşimli ögeleri vurgulamak^000 üzere {STR_COMPANION_ORDER_MODE} basılı tut.",
"TUTO__COMPANION_ORDER_SOPHIA": "Sophia, ^761düşmanları yüksek otların içine çekebilir^000.~{STR_COMPANION_ORDER_MODE} basılı tut, ardından yüksek otlara nişan al ve şaşırtma yaratmak için {STR_COMPANION_ORDER_INTERACT} tuşuna bas.",
"TUTO__COMPANION_ORDER_SOPHIA_LIGHT": "Sophia, prizmasıyla çevresinde bir ^761ışık alanı^000 oluşturabilir.~{STR_COMPANION_ORDER_MODE} basılı tut, bir ateş kaynağına nişan al ve {STR_COMPANION_ORDER_INTERACT} tuşuna bas.",
"TUTO__COMPANION_ORDER_SOPHIA_LOS": "Prizmadan ateş kaynağına giden ışın ^761bir engelle kesilirse^000, Sophia'nın çevresindeki ışık alanı kaybolur.",
"TUTO__CRAFT": "{STR_CYCLE_AMMO_UP} ile ^761Ignifer'i^000 seç ve onu üretmek için {STR_CRAFT} basılı tut.",
"TUTO__CRAFT_IGNIFER": "Artık ^761Ignifer^000 üretebilirsin. ~Seçim menüsünü açmak için {STR_WEAPON_SELECTION_OPEN} basılı tut.",
"TUTO__CRAFT_JAR": "Herhangi bir etki bir ^761çömlekle^000 birleştirilebilir. ~Seçim menüsünü açmak için {STR_WEAPON_SELECTION_OPEN} basılı tut.",
"TUTO__CRAFT_JAR_SELECT": "Bir cephane türüyle birleştirilen bir çömlek, çarpma anında ^761geniş bir geçici etki alanı^000 oluşturur. Çömleği {STR_CUSTOM1} ile seç.",
"TUTO__CRANK": "Krank kolunu ^761çevirmek^000 için {STR_INTERACT} basılı tut.",
"TUTO__CRANK_DROP": "Krankı ^761bırakmak^000 için {STR_DROP} tuşuna bas.",
"TUTO__CRANK_NOHOLD": "Krank kolunu ^761çevirmek^000 için {STR_INTERACT} tuşuna bas.",
"TUTO__CRANK_REVERT": "Bırakıldığında krank, ilk hâline ^761giderek geri döner^000.",
"TUTO__CROSSBOW_AIM": "Arbaletle ^761nişan almak^000 için {STR_AIM_MODE} basılı tut.",
"TUTO__CROSSBOW_PLANT": "Arbalet oku ahşap ögelere ^761saplanabilir^000 ve böylece etkileri ^761kalıcı^000 olur.",
"TUTO__CROSSBOW_PLANT_IGNIFER": "^761Kalıcı bir ateş kaynağı^000 oluşturmak için ahşap bir ögeye Ignifer oku at.",
"TUTO__CROSSBOW_RELOAD": "Arbalet, nişan alırken ^761otomatik olarak yeniden dolar^000.",
"TUTO__CROSSBOW_SAIL": "Yakıp tekneyi kurtarmak için ^761katran kaplı enkaza^000 bir Ignifer oku at.",
"TUTO__CROSSBOW_SELECT": "^761Arbaleti^000 aldın. ~Seçim menüsünü açmak için {STR_WEAPON_SELECTION_OPEN} basılı tut",
"TUTO__CROSSBOW_SELECT_SWITCH": "Arbalet, ^761gövdeye^000 isabetle düşmanları öldürebilir.~Oklar ahşap ögelere saplanabilir ve etkileri ^761kalıcı^000 olur.~Onu {STR_CUSTOM1} ile seç.",
"TUTO__CROSSBOW_SHOOT": "Bir arbalet oku ^761ateşlemek^000 için {STR_SHOOT} tuşuna bas.",
"TUTO__CROSSBOW_SWITCH": "Arbaletle ^761çeşitli türde^000 ok atabilirsin.~Seçim menüsünü açmak için {STR_WEAPON_SELECTION_OPEN} basılı tut.",
"TUTO__CROSSBOW_SWITCH_IGNIFER": "{STR_CYCLE_AMMO_UP} ile ^761Ignifer'i^000 seç.",
"TUTO__CROSSBOW_TURRET_COVER": "Nişan almadığında taretin arkasında ^761korunursun^000.",
"TUTO__CROUCH": "^761Çömelmek^000 için {STR_CROUCH} tuşuna bas.",
"TUTO__DONT_SLING": "Sapanının sesi düşmanları sana çeker.~^761Daha gizli olmak^000 için {STR_WEAPON_SELECTION_OPEN} basılı tutarak mermileri başka bir şekilde kullan.",
"TUTO__EFFECT_SELECT": "Tüm cephanen, silahlarından herhangi biriyle atılabilir. ~{STR_CUSTOM1} ile ^761Sapanı^000 seç.",
"TUTO__EMBERS": "Korları ^761Ignifer^000 ile tutuşturmak, fareler arasında yolunu bulmana yardımcı olur.",
"TUTO__EMERGENCY_DISTRACT": "Varlığından haberdar olmuş bir düşmanın ^761dikkatini dağıtmak^000 için {STR_INTERACT} tuşuna bas.",
"TUTO__EXTINGUISH": "Exstinguis cephanesi ^761ateşleri söndürebilir^000. ~Söndürmek için yanan bir ateşe nişan al ve bir Exstinguis at.",
"TUTO__EXTINGUISH_BAG": "Alevleri söndüren ve düşmanları boğan bir bulut oluşturmak için bir ^761güherçile torbasına^000 ^761sapanınla taş^000 at.",
"TUTO__EXTINGUISH_CRAFT": "Artık ^761Exstinguis^000 üretebilirsin. ~Seçim menüsünü açmak için {STR_WEAPON_SELECTION_OPEN} basılı tut.",
"TUTO__EXTINGUISH_JAR": "^761Exstinguis'i bir çömlekle^000 birleştirebilirsin. ~Bir Exstinguis bulutu oluşturmak için çömleği fırlat.",
"TUTO__FALCON": "Şahin, seni görmeye ve herhangi bir sese hızla tepki verir. Olabildiğince ^761siperde^000 kal; onun ^761dikkatini dağıtmak^000 için aletlerini ve çevreni kullan.",
"TUTO__FLAMETHROWER": "Taretle ^761nişan almak^000 için {STR_AIM_MODE} basılı tut ve ^761ateş etmek^000 için {STR_SHOOT} tuşuna bas.",
"TUTO__FOCUS": "Atışını ^761hazırlamak^000 için {STR_SHOOT} basılı tut ve ateş etmek için bırak.",
"TUTO__FREEZE_WATER_HOLD": "Bir süre su altına ^761dalmak^000 için {STR_TRAVERSAL} tuşuna bas.",
"TUTO__FREEZE_WATER_RELEASE": "^761Nefesin tükenmeden^000 ve çevredeki düşmanları uyarmadan önce yeniden {STR_TRAVERSAL} tuşuna bas.",
"TUTO__HANDTHROW": "Daha gizli olmak için mermileri ^761elle^000 fırlatabilirsin.~Seçim menüsünü açmak için {STR_WEAPON_SELECTION_OPEN} basılı tut.",
"TUTO__HANDTHROW_JAR": "Bir ^761çömlek^000 aldın. ~Seçim menüsünü açmak için {STR_WEAPON_SELECTION_OPEN} basılı tut",
"TUTO__HANDTHROW_JAR_SWITCH": "{STR_CUSTOM1} ile ^761çömlek atışını^000 seç.",
"TUTO__HANDTHROW_SWITCH": "{STR_CUSTOM1} ile ^761el atışını^000 seç.",
"TUTO__HEADSHOT": "Düşmanları ^761sapanınla kafalarından^000 vurarak ortadan kaldırabilirsin. Nişan almak için {STR_AIM_MODE} basılı tut, sonra ^761hazırlamak^000 için {STR_SHOOT} basılı tut ve ateş etmek için bırak.",
"TUTO__HELMET": "Sapan, ^761miğferli düşmanlara karşı etkisizdir^000. ~Gizli ol ve doğrudan çatışmadan kaçın.",
"TUTO__HUGO_CRAWL": "Hugo, ^761dar alanlarda sürünebilir^000. Mevcut seçenekleri görüntülemek için {STR_COMPANION_ORDER_MODE} basılı tut.",
"TUTO__HUGO_CRAWL_ORDER": "{STR_COMPANION_ORDER_MODE} basılı tut, geçide nişan al ve ondan ^761sürünerek geçmesini istemek^000 için {STR_COMPANION_ORDER_INTERACT} tuşuna bas.",
"TUTO__HUGO_GAUGE": "Hugo'nun yeteneklerini kullanmak onun ^761stres düzeyini^000 artırır.~Onu aşırı strese sokmamak için bunları dikkatle kullan.",
"TUTO__IGNIFER": "Ignifer, üzerine atıldığı korları tutuşturmanı sağlar.~^761Korlara nişan almak^000 için {STR_THROW_AIM_MODE} basılı tut.",
"TUTO__IGNIFER_THROW": "Korları tutuşturmak için {STR_SHOOT} ile korların içine bir ^761Ignifer^000 at.",
"TUTO__IGNITE": "Yanıcı bir öge tutarken, ^761onu tutuşturmak^000 için bir ateş kaynağının yakınında {STR_INTERACT} tuşuna bas.",
"TUTO__JAR_AIM_SHOOT": "Nişan almak için {STR_THROW_AIM_MODE} basılı tut, ardından ^761çömleği^000 fırlatmak için {STR_SHOOT} kullan. ~Daire, onun ^761etki alanını^000 gösterir.",
"TUTO__LUCAS_SCARE": "Lucas'ın ^761arkasından gizlice^000 yaklaş ve onu korkutmak için {STR_SLING_SLASH} basılı tut.",
"TUTO__MELEE_BACK": "Zırhsız bir düşmanın ^761arkasından gizlice^000 yaklaş ve onu öldürmek için {STR_SLING_SLASH} basılı tut.",
"TUTO__MELEE_COUNTER": "Saldıran bir düşmanı ^761karşılamak^000 için {STR_SLING_SLASH} basılı tut.",
"TUTO__MELEE_FINISH": "Sapanınla yakın dövüşte vurup ^761zırhsız bir düşmanı öldürmek^000 için {STR_SLING_SLASH} basılı tut.",
"TUTO__MELEE_NOISE": "Yakın dövüşte bir düşmana saldırmak ^761gürültü^000 çıkarır ve yakındaki düşmanları uyarır.",
"TUTO__METAL": "{STR_AIM_MODE} basılı tut ve ^761alet sandığına^000 nişan al, sonra fırlatmak için {STR_SHOOT} tuşuna bas.",
"TUTO__NO_SLING": "Amicia'nın ^761ekipmanı elinden alındı^000 ve artık sapanını veya envanterini kullanamıyor.",
"TUTO__OBSTACLE_SOCKET": "Elinde meşaleyle yüksek engelleri aşamazsın.~Meşaleni yanar tutmak ve engeli aşmak için ^761bir yuvaya^000 yerleştir.",
"TUTO__OIL_AMPLIFY": "Bir ateş kaynağını ^761güçlendirmek^000 için üzerine katran at.",
"TUTO__OIL_BURN": "Tutuşunca katran ^761hızla^000 yanar.",
"TUTO__OIL_CRAFT": "Artık ^761katran^000 üretebilirsin. ~Seçim menüsünü açmak için {STR_WEAPON_SELECTION_OPEN} basılı tut.",
"TUTO__OIL_GENERATOR": "Bir katran birikintisi oluşturmak için ^761katran çömleklerine^000 ateş et.",
"TUTO__OIL_IGNIFER": "^761Katran^000, üzerine bir Ignifer atılarak tutuşturulabilir.~Işık fareleri uzak tutar, ama alevler dokundukları her şeyi yakar.",
"TUTO__OIL_JAR": "^761Katranı bir çömlekle^000 birleştirebilirsin. ~Çarpılan yüzeyde bir katran birikintisi oluşturmak için çömleği fırlat.",
"TUTO__OIL_KILL": "Bir düşmanı ^761katran birikintisiyle^000 yavaşlat, sonra onu ortadan kaldırmak için ^761tutuştur^000. Düşmanları tuzağa düşürmek için katranı bir ^761çömlekle^000 birleştir ya da çevredeki ^761katran çömleklerini^000 kır.",
"TUTO__ORPHAN_DYING": "Yoldaşın saldırı altında! ^761Yardım etmezsen^000 ölecek.",
"TUTO__PUSH": "Arabayı ^761itmek/çekmek^000 için {STR_UPDOWN}, yönlendirmek için {STR_CUSTOM1} kullan. Bırakmak için {STR_DROP} tuşuna bas.",
"TUTO__PYRITE_USE": "^761Pyrite^000, çarpma anında ışık üretir ve kısa bir süre farelerden kaçmanı sağlar.",
"TUTO__RAT_STRIKE": "Bir hedefe nişan al, sonra ^761fareleri göndermek^000 için {STR_SHOOT} tuşuna bas.",
"TUTO__RATMOVE_CANCEL": "Sürü kontrolünü ^761durdurmak^000 için {STR_RATSENSE_AIM} tuşuna bas.",
"TUTO__RATMOVE_CONTROLS": "{STR_CUSTOM2} ile ^761sürüyü hareket ettirebilir^000 ve {STR_CUSTOM1} ile yönlendirebilirsin.",
"TUTO__RATMOVE_START": "Hugo artık bir fare sürüsünü ^761kontrol edebilir^000. Farelerle bağ kurmak için {STR_RATSENSE_AIM} basılı tut.",
"TUTO__RATMOVE_TAKECONTROL": "Bir ^761fare sürüsüne^000 nişan al ve sürünün kontrolünü ele almak için {STR_SHOOT} tuşuna bas.",
"TUTO__RATS_REPULSE": "Kendini farelerden korumak için bir ışık kaynağının yakınında kal.~Bir ^761meşaleyle^000 etkileşerek onu alıp yanında taşıyabilirsin.",
"TUTO__RATSENSE": "Hugo ile fareler arasında bir ^761bağ^000 kurmak için {STR_RATSENSE_AIM} basılı tut.",
"TUTO__ROCK_SELECT": "{STR_CUSTOM1} ile ^761sapanı^000 seç, sonra ^761taşı^000 seçmek için {STR_CYCLE_AMMO_DOWN} kullan.",
"TUTO__ROPE_BASICS": "İple etkileşmek için bir ^761çapa noktasının^000 yakınında {STR_INTERACT} tuşuna bas.~İpi çekerek ona bağlı nesneleri hareket ettirebilir veya indirebilirsin.",
"TUTO__ROPE_BOLT_SHOOT": "Bir ^761çapa noktasından^000, bir nesneye bağ oluşturmak için arbaleti kullanabilirsin.",
"TUTO__ROPE_CONTROLS": "^761İpi kendine doğru çekmek^000 için {STR_INTERACT} basılı tut.",
"TUTO__SHOOT": "Sapanınla ^761nişan almak^000 için {STR_AIM_MODE} basılı tut.",
"TUTO__SKILLS": "Durumlarla başa çıkma şeklin, ^761Amicia'nın yeteneklerinin^000 gelişimini etkiler.~Yetenekler menüsünü açmak için {STR_SELECT_MODE} tuşuna bas.",
"TUTO__SKILLS_OPEN": "Amicia, yaklaşım tarzına ve kullandığın aletlere göre ^7613 tür yeteneğinin^000 ustalığını otomatik olarak artırır. Menüyü kapatmak için {STR_SELECT_MODE} tuşuna bas.",
"TUTO__SLIING_SELECT": "^761Sapanınla^000 birleştirici halkaya atış yaparak zincirleri kırabilirsin. Seçim menüsünü açmak için {STR_WEAPON_SELECTION_OPEN} basılı tut.",
"TUTO__SLING_BACK": "Amicia ekipmanını buldu ve artık yeniden ^761sapanını ve envanterini^000 kullanabilir.",
"TUTO__SPRINT": "^761Koşmak^000 için {STR_SPRINT} basılı tut.",
"TUTO__STAND": "^761Ayağa kalkmak^000 için {STR_CROUCH} tuşuna bas.",
"TUTO__STEALTH": "Sessiz kalmak için {STR_CROUCH} tuşuna basarak ^761çömelmiş^000 kal ve görünmez olmak için uzun otların arasına saklan.",
"TUTO__STEALTH_FAILED": "Çok fazla gürültü çıkarıyorsun! ^761Çömelmek^000 ve sessizce hareket etmek için {STR_CROUCH} tuşuna bas.",
"TUTO__STEALTH_GARDEN": "Sessiz kalmak için ^761çömelmiş^000 kal ve görünmez olmak için uzun otların arasına saklan.",
"TUTO__STUN_SHIELD": "Muhafızları ^761sersemletmek ve gardlarını düşürmek^000 için güherçile torbalarını vur ya da üzerlerine bir Exstinguis at.",
"TUTO__THROW_AIM_SHOOT": "Ignifer, ^761korları tutuşturmanı^000 sağlar.~Korlara nişan almak için {STR_THROW_AIM_MODE} basılı tut, sonra fırlatmak için {STR_SHOOT} kullan.",
"TUTO__THROW_CARRIABLE": "Taşıdığın nesneyi ^761fırlatabilirsin^000.~Nişan almak için {STR_THROW_AIM_MODE} basılı tut, sonra fırlatmak için {STR_SHOOT} tuşuna bas.",
"TUTO__THROW_JAR": "Nişan almak için {STR_AIM_MODE} basılı tut ve çömleği bir yüzeye fırlatmak için {STR_SHOOT} tuşuna bas.~Beyazla vurgulanan düşmanlar çarpma sesini duyar ve en yakındaki ^761araştırmaya gelir^000.",
"TUTO__THROW_SELECT": "{STR_CUSTOM1} ile ^761el atışını^000 seç.",
"TUTO__THROW_SELECT_AGAIN": "Seçim menüsünü açmak ve ^761el atışını^000 seçmek için {STR_WEAPON_SELECTION_OPEN} basılı tut.",
"TUTO__TOOL": "Aletler, ekipmanını bir tezgâhta ^761yükseltmeni^000 sağlar.",
"TUTO__UPGRADE": "{STR_SELECT_MODE} tuşuna basarak üretim menüsünü istediğin zaman açabilirsin, ama ekipmanını yükseltmek için bir ^761tezgâha^000 ihtiyacın var.",
"TUTO__VAMBRACE": "^761Kolluk^000 sayesinde Amicia, düşman saldırılarından daha hızlı toparlanır.",
"TUTO__VAULT": "Bazı engelleri ^761aşmak^000 için {STR_TRAVERSAL} tuşuna bas.",
"TUTO__WARNING_SANCTUARY": "Yasak bir bölgedesin; fark edilmemeli ya da hiçbir asker öldürmemelisin.",
"TUTO__WARNING_SPLIT": "Yoldaşından ayrı düştün. Amicia onsuz devam etmeyi reddedecek. ^761Yeniden bir araya gelmenin^000 bir yolunu bul.",
"TUTO__WOODSTICK": "Çubuklar sönmeden önce yalnızca ^761birkaç an yanar^000.",
}
