# -*- coding: utf-8 -*-
# CH16 VO - kaynak proper Turkce; build asamasinda SUB uygulanir.
# phoenix->anka, carnation->karanfil, pilgrims->hacilar, Macula/Nebula/Exstinguis korunur, son esik, pota.
T = {
"VO__AMICIA__CH16__CHATTER__1ST_PHOENIX_CLOSE__010__M__1": "Bir anka... burada mı?!",
"VO__AMICIA__CH16__CHATTER__1ST_PHOENIX_FAR__010__M__1": "O da ne?",
"VO__AMICIA__CH16__CHATTER__1ST_PHOENIX_FAR__020__M__1": "Hayır... Olamaz...",
"VO__AMICIA__CH16__CHATTER__2ND_PHOENIX_SPOT__010__M__1": "Bir tane daha... Neler oluyor?!",
"VO__AMICIA__CH16__CHATTER__2ND_PHOENIX_SPOT__020__M__1": "Neler oluyor?... Burası neresi?",
"VO__AMICIA__CH16__CHATTER__5TH_COVER_FALL__010__M__1": "Hayır, hayır! Orada kalma!",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE__010__M__1": "Onları... buraya sen mi koydun, Hugo?",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE__030__M__1": "Hugo! Şükürler olsun! Neredesin?",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE__050__M__1": "Seni göremiyorum!",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE__070__M__1": "Buradaki tek şey o kuşlar! Yolu gösteriyorlar, değil mi?",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE__090__M__1": "Tamamen değil... Onda... Onda bir gerçek vardı!",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE__110__M__1": "İnsanlar getirdi onu! Hugo... Seni buradan çıkarmanın bir yolu lazım bana!",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE__130__M__1": "Deniyorum... Deniyorum!",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE_IDLE_1__010__M__1": "Düşün, Amicia... Buralarda bir yerde...",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE_IDLE_2__010__M__1": "Ha... Bir şey yap! Bir şey yap...",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE_IDLE_3__010__M__1": "Yeni yollar...",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE_LOST__010__M__1": "Kayboldum, Hugo! Ne yapacağımı bilmiyorum!",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE_LOST__030__M__1": "Yani... bir çıkış lazım bana...",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE_TRYING_EXIT__010__M__1": "Lanet kuşlar, bırakın beni!... Hadi, dümdüz koş...",
"VO__AMICIA__CH16__CHATTER__A_PHOENIX_LIE_TRYING_EXIT__020__M__1": "Dosdoğru ileri... Eninde sonunda çıkarsın.",
"VO__AMICIA__CH16__CHATTER__AFTER_FALL__010__M__1": "Devam et... Hugo yakında... Önce Lucas'ı bulmak lazım.",
"VO__AMICIA__CH16__CHATTER__BREAKING_TRAP__005__M__1": "Bana... ne oluyor?... Hissediyorum...",
"VO__AMICIA__CH16__CHATTER__BREAKING_TRAP__020__M__1": "Ne gerekiyorsa yapacağım... Seni... görmek istiyorum.",
"VO__AMICIA__CH16__CHATTER__BREAKING_TRAP_FEEL__010__M__1": "Evet... bu işte, galiba... Devam et...",
"VO__AMICIA__CH16__CHATTER__BREAKING_TRAP_FOG_2__020__M__1": "Dayan... Dayan...",
"VO__AMICIA__CH16__CHATTER__BREAKING_TRAP_FOG_3__020__M__1": "Yoldayım...",
"VO__AMICIA__CH16__CHATTER__BREAKING_TRAP_FOG_4__020__M__1": "Çabuk...",
"VO__AMICIA__CH16__CHATTER__CALLING_OUT__010__M__1": "Lucas? Tanrım...",
"VO__AMICIA__CH16__CHATTER__CALLING_OUT__020__M__1": "Lucas! Neredesin?! Ha...",
"VO__AMICIA__CH16__CHATTER__CALLING_OUT__030__M__1": "Ah... başım... dönüyor...",
"VO__AMICIA__CH16__CHATTER__CALLING_OUT__040__M__1": "Burada neler oluyor?... Lucas! Buradayım!",
"VO__AMICIA__CH16__CHATTER__CALLING_OUT__050__M__1": "Odaklan... Önce Hugo... Onu bul.",
"VO__AMICIA__CH16__CHATTER__CARNATION__010__M__1": "Bir karanfil... Hugo'nun bana verdiği ilk çiçek... seninle tanışmamızdan hemen önce, Lucas.",
"VO__AMICIA__CH16__CHATTER__CARNATION__040__M__1": "Evet...",
"VO__AMICIA__CH16__CHATTER__CAVE__010__M__1": "Ah...",
"VO__AMICIA__CH16__CHATTER__CAVE__015__M__1": "O da ne?... Hugo! Neredeyim ben?!",
"VO__AMICIA__CH16__CHATTER__CAVE__020__M__1": "Hayır...",
"VO__AMICIA__CH16__CHATTER__CAVE__025__M__1": "Onlar olmasın, hayır!",
"VO__AMICIA__CH16__CHATTER__CAVE__030__M__1": "Defolun!",
"VO__AMICIA__CH16__CHATTER__DEATH_DOOR_RTE__010__M__1": "Pekâlâ... Şimdi ne olacak?",
"VO__AMICIA__CH16__CHATTER__DEATH_DOOR_RTE__020__M__1": "Hugo? Neredesin?!",
"VO__AMICIA__CH16__CHATTER__DEATH_DOOR_RTE__030__M__1": "NEREDESİN?!",
"VO__AMICIA__CH16__CHATTER__DEATH_DOOR_RTE__050__M__1": "Hazır mıyım?! Buna nasıl hazır olabilirim ki?!",
"VO__AMICIA__CH16__CHATTER__DEATH_DOOR_RTE__070__M__1": "Hugo...",
"VO__AMICIA__CH16__CHATTER__DEATH_DOOR_RTE__090__M__1": "Seni seviyorum!... Seni çok seviyorum...",
"VO__AMICIA__CH16__CHATTER__DEATH_INTRO__014__M__1": "Nerede... Neredesin?",
"VO__AMICIA__CH16__CHATTER__DEATH_INTRO__020__M__1": "Hugo!... Gel!... Gel!",
"VO__AMICIA__CH16__CHATTER__DEATH_INTRO__030__M__1": "Seni bir daha asla göremeyeceğim sanmıştım...",
"VO__AMICIA__CH16__CHATTER__DEATH_INTRO__043__M__1": "Çok korkmuştum...",
"VO__AMICIA__CH16__CHATTER__DEATH_INTRO__050__M__1": "Evet... Buradan nasıl çıkılacağını... biliyor musun?",
"VO__AMICIA__CH16__CHATTER__DEATH_INTRO__080__M__1": "Ha... Hadi... gidelim...",
"VO__AMICIA__CH16__CHATTER__DEATH_MOVE__010__M__1": "Bu cehennemden çıkalım... öyle ya da böyle...",
"VO__AMICIA__CH16__CHATTER__DEATH_MOVE__030__M__1": "Biliyorum...",
"VO__AMICIA__CH16__CHATTER__DEATH_MOVE__050__M__1": "Hugo... Elimizden gelen her şeyi denedik...",
"VO__AMICIA__CH16__CHATTER__DEATH_MOVE__070__M__1": "Hadi buradan çıkalım. Buna son verebiliriz. Anne'nin evini bulacağız... Ve yaşayacağız... gerçekten yaşayacağız...",
"VO__AMICIA__CH16__CHATTER__DEATH_MOVE__090__M__1": "Bunu hak ettik.",
"VO__AMICIA__CH16__CHATTER__EPICENTRE__020__M__1": "Evet...",
"VO__AMICIA__CH16__CHATTER__EPICENTRE__040__M__1": "Evet...",
"VO__AMICIA__CH16__CHATTER__FIRE_EXTINGUISH__010__M__1": "İşte! Anladım! Bu boşuna...",
"VO__AMICIA__CH16__CHATTER__FIRE_EXTINGUISH__020__M__1": "Teslim oluyorum! Bütün bunlardan yoruldum!... Savaşamayacak kadar yorgunum...",
"VO__AMICIA__CH16__CHATTER__FIRE_EXTINGUISH__040__M__1": "Lütfen, seni görmem gerek...",
"VO__AMICIA__CH16__CHATTER__FIRE_EXTINGUISH_LOOP_2__010__M__1": "Cehenneme git. Artık benim savaşım değilsin...",
"VO__AMICIA__CH16__CHATTER__FIRE_EXTINGUISH_LOOP_3__010__M__1": "Hadi, hadi! Bırak onu göreyim...",
"VO__AMICIA__CH16__CHATTER__FIRE_EXTINGUISH_LOOP_4__010__M__1": "İşte... Bunu bitirmem gerek...",
"VO__AMICIA__CH16__CHATTER__FIRST_STEPS__030__M__1": "Hep en sevdiği oyundu... Fethetmek...",
"VO__AMICIA__CH16__CHATTER__GOLEM_COLLAPSING_FIRST__010__M__1": "Hayır! Hayır! Hayııır!",
"VO__AMICIA__CH16__CHATTER__GOLEM_COLLAPSING_SECOND__010__M__1": "Hayır! Kahrolun!",
"VO__AMICIA__CH16__CHATTER__GOLEM_COLLAPSING_THIRD__010__M__1": "Hayır... Hayır! Kahrolun!",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_2__010__M__1": "Bir yol olmalı!",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_2__030__M__1": "Anladığımı onlara göstermek için...",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_2_BACK__010__M__1": "Ha... O şeyler yakında... Bu sefer daha iyisini yap... Doğru yap bunu!",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_2_BACK__020__M__1": "Mangal onları durduramaz... Daha keskin olmalısın!",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_3_KEEP_KILLING__010__M__1": "Bunu ne için yapıyorsun? Bu savaş hiçbir yere varmıyor. Biliyorsun...",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_3_KEEP_KILLING__020__M__1": "Buna son ver! Söndür şu ateşi! Teslim ol... Onun için...",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_3_KILLING_1__010__M__1": "Anlamaya çalışıyorum! Ama biraz zaman kazanmam gerek!",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_3_KILLING_1__030__M__1": "Şu mangal...",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_3_KILLING_1__050__M__1": "Onu... söndürmem gerek...",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_3_KILLING_2__010__M__1": "Bırak... bunu bitireyim!",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_3_KILLING_2__040__M__1": "Onu... söndürmeliyim... evet.",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_4_KILLING_1__010__M__1": "Nefret ediyorum sizden... Bıktım bundan...",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_4_KILLING_3__020__M__1": "Biliyorum... Çok zor, Hugo!",
"VO__AMICIA__CH16__CHATTER__GOLEM_LOOP_4_KILLING_3__040__M__1": "Evet... Sadece bir Exstinguis...",
"VO__AMICIA__CH16__CHATTER__GOLEMS_COMING__010__M__1": "Bu da ne?!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_COMING__015__M__1": "Geri çekil!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_COMING__020__M__1": "Hâlâ sadece lanet sıçanlarsınız... Hepinizi yakacağım!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_KILLING_1__010__M__1": "Kaçmamı mı istiyorsun?!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_KILLING_1__020__M__1": "Onu geri alacağım! Duydun mu?!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_KILLING_2__020__M__1": "Merak etme! İcabına bakarım onların!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_KILLING_2__040__M__1": "Ya biz ya onlar! Başka seçeneğim yok!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_KILLING_3__020__M__1": "Umurumda değil!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_KILLING_3__040__M__1": "Ne gibi?!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_KILLING_3__060__M__1": "Onlar hâlâ önemli! Önemliler!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_KILLING_4__010__M__1": "Gelmeyi... kesin!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_KILLING_4__030__M__1": "Sağlam olmam gerek! Yıkılamam!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_KILLING_4__050__M__1": "Hayır, Hugo! Bana güven!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_LOOP_2__050__M__1": "Bu alev... Bu benim...",
"VO__AMICIA__CH16__CHATTER__GOLEMS_LOOP_2_KILL_1__020__M__1": "Üstüme gelip duruyorlar!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_LOOP_2_KILL_1__040__M__1": "Ne demek istiyorsun?!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_LOOP_2_KILL_1__060__M__1": "Ne... Ne?!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_LOOP_2_KILL_2__005__M__1": "Bunu... ben yaratıyor olamam...",
"VO__AMICIA__CH16__CHATTER__GOLEMS_LOOP_2_KILL_3__010__M__1": "Bu savaş boşunaysa... onu nasıl durduracağım?!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_LOOP_2_KILL_3__030__M__1": "Nasıl? Yine yakalayacaklar beni!",
"VO__AMICIA__CH16__CHATTER__GOLEMS_LOOP_3_BACK__010__M__1": "Pekâlâ... Aynı hatayı yapmayı bırak...",
"VO__AMICIA__CH16__CHATTER__GOLEMS_LOOP_3_BACK__020__M__1": "İlerlemen gerek... Bu savaşı bitir...",
"VO__AMICIA__CH16__CHATTER__GOLEMS_LOOP_4_BACK__010__M__1": "Şimdi de sıçanlar... Yorgunum...",
"VO__AMICIA__CH16__CHATTER__GOLEMS_LOOP_4_BACK__020__M__1": "Korkuyorum... Bu savaşın bitmesinden çok korkuyorum...",
"VO__AMICIA__CH16__CHATTER__LACUNA_FAIR__010__M__1": "Hugo, durabilir mi bu?",
"VO__AMICIA__CH16__CHATTER__LACUNA_FAIR__030__M__1": "Demek son bu?",
"VO__AMICIA__CH16__CHATTER__LACUNA_FAIR__050__M__1": "Söyle bana... Her şeyi yaparım...",
"VO__AMICIA__CH16__CHATTER__LACUNA_FAIR__070__M__1": "Ben...",
"VO__AMICIA__CH16__CHATTER__LACUNA_FAIR__090__M__1": "Hugo...",
"VO__AMICIA__CH16__CHATTER__LAST_CALL__015__M__1": "Biliyorum...",
"VO__AMICIA__CH16__CHATTER__LAST_RUN__030__M__1": "Köprü! Çabuk!",
"VO__AMICIA__CH16__CHATTER__LAST_RUN__050__M__1": "Başarabiliriz! Koş!",
"VO__AMICIA__CH16__CHATTER__LAST_RUN_START__010__M__1": "Hadi, Lucas!",
"VO__AMICIA__CH16__CHATTER__LOST__030__M__1": "Hugo, benim! Yaşıyorum! Geri döndüm!",
"VO__AMICIA__CH16__CHATTER__LOST__040__M__1": "Neredesin?!",
"VO__AMICIA__CH16__CHATTER__MARKET_TRANSITION__010__M__1": "Biliyorum...",
"VO__AMICIA__CH16__CHATTER__MARKET_TRANSITION__030__M__1": "Belki gidersek... durur...",
"VO__AMICIA__CH16__CHATTER__MOVING_ON__010__M__1": "Yolu gösterdiler...",
"VO__AMICIA__CH16__CHATTER__PHOENIX_AGAIN__020__M__1": "Ona götürüyor olmalılar...",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_2__010__M__1": "Ha... Ne...? Ne oldu?",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_2__020__M__1": "Hayır... Geri döndüm... Geri gittim!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_2__030__M__1": "Hugo! Ne yaptım ben?!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_2__060__M__1": "Yapacağım! Tekrar yapacağım... Öğreneceğim...",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_2_ANOTHER_ONE__010__M__1": "Bir tane daha... Hayır... Onlardan uzaklaş!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_2_BACK__002__M__1": "Aynı şekilde işlemeli... Oraya geri dönmem gerek!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_2_BACK__005__M__1": "Çıkış... O çıkış lazım bana... şu kuşlardan uzakta...",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_2_BACK__008__M__1": "Dümdüz git... Varırsın oraya...",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_2_BACK__010__M__1": "Bu lanet döngüden çıkmam gerek...",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_2_IDLE__010__M__1": "Bu çılgınlık... Ama yapacağım... Sana ulaşmak için ne gerekiyorsa yapacağım...",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_3__010__M__1": "Hayır! Yine o lanet ankalar mı?!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_3__020__M__1": "Düşün, kahretsin! Ne yapıyorsun?!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_3__040__M__1": "Evet! Bunu bitireceğim!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_3_IDLE__010__M__1": "Hadi... Geri dönmem gerek! Hadi!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_4__010__M__1": "Hayır! Asla!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_4__030__M__1": "Deniyorum! Bu sadece... Sanki... bir parçam istemiyor!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_4__050__M__1": "Seni yüzüstü bırakmayacağım, duydun mu?! Senin için geliyorum!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_4_BACK__002__M__1": "Oraya geri dönmeliyim... Buna son vermeliyim... cesur ol...",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_5__010__M__1": "Hayır! Üzgünüm Hugo!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_5__030__M__1": "Ama seni şimdi görmem gerek!",
"VO__AMICIA__CH16__CHATTER__PHOENIX_LOOP_5__050__M__1": "Yine gideceğim. Ve kaç kez gerekirse gereksin gitmeye devam edeceğim!",
"VO__AMICIA__CH16__CHATTER__PHOENX_LOOP_2_BREAKING_TRAP__010__M__1": "İşte böyle... Yapıyorsun... Öğreniyorsun...",
"VO__AMICIA__CH16__CHATTER__PHOENX_LOOP_3_ANOTHER_ONE__010__M__1": "Lanet kuş... Sen hep bir yalandın...",
"VO__AMICIA__CH16__CHATTER__PHOENX_LOOP_3_BREAKING_TRAP__010__M__1": "Beni yine yakalayamayacaksın... Ona ulaşıyorum... Onu... geri alıyorum...",
"VO__AMICIA__CH16__CHATTER__PHOENX_LOOP_4_ANOTHER_ONE__010__M__1": "Hayır, hayır, hayır!",
"VO__AMICIA__CH16__CHATTER__PHOENX_LOOP_4_BREAKING_TRAP__010__M__1": "Yoldayım...",
"VO__AMICIA__CH16__CHATTER__PHOENX_LOOP_5_BREAKING_TRAP__010__M__1": "Geliyorum, Hugo. Birazcık daha bekle...",
"VO__AMICIA__CH16__CHATTER__PILGRIMS_DEATHS__010__M__1": "Merhaba... Daha önce tanışmıştık...",
"VO__AMICIA__CH16__CHATTER__PILGRIMS_DEATHS__030__M__1": "Hey! Ne oluyor sana?!",
"VO__AMICIA__CH16__CHATTER__PILGRIMS_DEATHS__050__M__1": "Onu mu öldürdün?! Bu da ne böyle?!",
"VO__AMICIA__CH16__CHATTER__PILGRIMS_DEATHS__060__M__1": "Neler oluyor?!",
"VO__AMICIA__CH16__CHATTER__PILGRIMS_DEATHS__080__M__1": "Nasıl?! Hiç sıçan görmüyorum!",
"VO__AMICIA__CH16__CHATTER__PILGRIMS_DEATHS__100__M__1": "Burada kalmayalım—gel!",
"VO__AMICIA__CH16__CHATTER__PILGRIMS_SIGHT__010__M__1": "Burası... tanıdık geliyor...",
"VO__AMICIA__CH16__CHATTER__PILGRIMS_TRANSITION__020__M__1": "Bir... Bir çözüm bulacağız. Ama önce buradan çıkmalıyız!",
"VO__AMICIA__CH16__CHATTER__POST_DEATH_DOOR__010__M__1": "Ama... Sen gidince...",
"VO__AMICIA__CH16__CHATTER__POST_DEATH_DOOR__020__M__1": "Başka hiçbir şey kalmayacak...",
"VO__AMICIA__CH16__CHATTER__POST_DEATH_DOOR__030__M__1": "Yalnız kalacağım...",
"VO__AMICIA__CH16__CHATTER__POST_DEATH_DOOR__040__M__1": "Yapayalnız...",
"VO__AMICIA__CH16__CHATTER__POST_DEATH_DOOR__070__M__1": "Yapamam...",
"VO__AMICIA__CH16__CHATTER__RATS_EMERGENCE__010__M__1": "Hugo!",
"VO__AMICIA__CH16__CHATTER__RATS_EMERGENCE__020__M__1": "Ah lütfen... Şimdi de ne bu?!",
"VO__AMICIA__CH16__CHATTER__REACH_1ST_COVER__013__M__1": "İşe yaradı...",
"VO__AMICIA__CH16__CHATTER__REACH_1ST_COVER__020__M__1": "Saklan, bekle ve tekrarla.",
"VO__AMICIA__CH16__CHATTER__REACH_1ST_COVER__040__M__1": "Tamam...",
"VO__AMICIA__CH16__CHATTER__REACH_2ND_COVER__010__M__1": "İşte böyle...",
"VO__AMICIA__CH16__CHATTER__REACH_3RD_COVER__010__M__1": "Şu kapı sıkışmış görünüyor!",
"VO__AMICIA__CH16__CHATTER__REACH_3RD_COVER__018__M__1": "Geliyorlar... Hadi... yap şunu!",
"VO__AMICIA__CH16__CHATTER__REACH_3RD_COVER__030__M__1": "Hazır mısın?",
"VO__AMICIA__CH16__CHATTER__REACH_4TH_COVER__010__M__1": "Ha...",
"VO__AMICIA__CH16__CHATTER__REACH_5TH_COVER__010__M__1": "Lütfen dayan...",
"VO__AMICIA__CH16__CHATTER__REACH_6TH_COVER__020__M__1": "Dayanacak... Nefes al...",
"VO__AMICIA__CH16__CHATTER__REACH_BRIDGE__010__M__1": "Geldik... Sanırım... güvendeyiz...",
"VO__AMICIA__CH16__CHATTER__REACH_BRIDGE__030__M__1": "Orada, Lucas... ulaşabileceğimiz yerde...",
"VO__AMICIA__CH16__CHATTER__RED_CITY_MARKET__020__M__1": "Buna son vermelisin...",
"VO__AMICIA__CH16__CHATTER__RED_CITY_MARKET__033__M__1": "Sadece odaklan! Daha önce yaptın bunu!",
"VO__AMICIA__CH16__CHATTER__RED_CITY_MARKET__040__M__1": "Bu bir yalan! Macula oyun oynuyor!",
"VO__AMICIA__CH16__CHATTER__RED_CITY_MARKET__060__M__1": "Ne?... Hayır...",
"VO__AMICIA__CH16__CHATTER__RED_CITY_MARKET__080__M__1": "Hayır, hayır, hayır!",
"VO__AMICIA__CH16__CHATTER__RUN_TO_2ND_COVER__010__M__1": "Şimdi!",
"VO__AMICIA__CH16__CHATTER__RUN_TO_3RD_COVER__010__M__1": "Gidelim!",
"VO__AMICIA__CH16__CHATTER__RYTHMIC_CYCLE__010__M__1": "Ha... Bu gerçekten... sen misin?...",
"VO__AMICIA__CH16__CHATTER__RYTHMIC_CYCLE__020__M__1": "Hey!",
"VO__AMICIA__CH16__CHATTER__RYTHMIC_CYCLE__040__M__1": "Yürüyemiyor! Artık sadece ikimiz kaldık!",
"VO__AMICIA__CH16__CHATTER__RYTHMIC_CYCLE__060__M__1": "Evet! Ama dur... dur! Tek bir hata ve...",
"VO__AMICIA__CH16__CHATTER__RYTHMIC_CYCLE__080__M__1": "Tanrım... Tamam... tamam!",
"VO__AMICIA__CH16__CHATTER__SLING_MISS_1__010__M__1": "Odaklan...",
"VO__AMICIA__CH16__CHATTER__SLING_RELEASE_1__010__M__1": "Ha... Ha...",
"VO__AMICIA__CH16__CHATTER__SLING_RELEASE_2__010__M__1": "Lütfen... Lütfen...",
"VO__AMICIA__CH16__CHATTER__SOPHIA_GOODBYE__020__M__1": "Senin için geri döneceğiz.",
"VO__AMICIA__CH16__CHATTER__STOP_ME__010__M__1": "Bunu... benden isteyemezsin.",
"VO__AMICIA__CH16__CHATTER__STOP_ME__030__M__1": "Sen bir canavar değilsin...",
"VO__AMICIA__CH16__CHATTER__STOP_ME__050__M__1": "Anlıyorum... ama...",
"VO__AMICIA__CH16__CHATTER__STOP_ME__070__M__1": "Ben... Deneyeceğim...",
"VO__AMICIA__CH16__CHATTER__THE_ONLY_WAY__010__M__1": "Aklımı mı kaçırıyorum?...",
"VO__AMICIA__CH16__CHATTER__THE_ONLY_WAY__020__M__1": "Hugo?! Bunu sen mi yapıyorsun?!",
"VO__AMICIA__CH16__CHATTER__THE_ONLY_WAY__025__M__1": "“Tüm doğa yasaları burada son bulur”... Tamam... Buna tutun...",
"VO__AMICIA__CH16__CHATTER__THE_ONLY_WAY__030__M__1": "Ankalar... Bir anlamı vardı...",
"VO__AMICIA__CH16__CHATTER__TO_1ST_WALL_AMICIA__010__M__1": "Koş! Koş! Koş!",
"VO__AMICIA__CH16__CHATTER__TO_1ST_WALL_LUCAS__010__M__1": "Şimdi!",
"VO__AMICIA__CH16__CHATTER__TO_3RD_COVER_CRACK__010__M__1": "Vay! Dikkat!",
"VO__AMICIA__CH16__CHATTER__TO_4TH_COVER_START__005__M__1": "Şimdi!",
"VO__AMICIA__CH16__CHATTER__TO_4TH_COVER_START__010__M__1": "Hayır, hayır, hayır!",
"VO__AMICIA__CH16__CHATTER__TO_4TH_COVER_START__030__M__1": "Yürü!",
"VO__AMICIA__CH16__CHATTER__TO_6TH_COVER_RUN__010__M__1": "Lucas, çatı!",
"VO__AMICIA__CH16__CHATTER__TO_6TH_COVER_START__020__M__1": "Yürü! Yürü!",
"VO__AMICIA__CH16__CHATTER__TO_7TH_COVER_SQUEEZE__010__M__1": "İşte!",
"VO__AMICIA__CH16__CHATTER__TO_7TH_COVER_SQUEEZE__030__M__1": "Sakin ol!",
"VO__AMICIA__CH16__CHATTER__TO_7TH_COVER_SQUEEZE__050__M__1": "Bu duvarlar dayanmalı...",
"VO__AMICIA__CH16__CHATTER__TO_7TH_COVER_START__010__M__1": "Geçiyorum!",
"VO__AMICIA__CH16__CHATTER__WAITING_1__020__M__1": "Biliyorum!",
"VO__AMICIA__CH16__CHATTER__WAITING_2__020__M__1": "Ha...",
"VO__AMICIA__CH16__CHATTER__WAITING_3__020__M__1": "Bırak... bırak... yapayım...",
"VO__AMICIA__CH16__CHATTER__WRONG_WAY_1__020__M__1": "Evet. Vakit kaybetmeyelim.",
"VO__AMICIA__CH16__CHATTER__WRONG_WAY_2__020__M__1": "Evet... Gidelim...",
"VO__AMICIA__CH16__CHATTER__WRONG_WAY_3__020__M__1": "Gerçekten bir çıkış var mı?",
"VO__AMICIA__CH16__CHATTER__WRONG_WAY_3__040__M__1": "Tamam...",
"VO__AMICIA__CH16__CHATTER__WRONG_WAY_4__020__M__1": "Bu yanlış. Bütün bunlar... yanlış.",
"VO__AMICIA__CH16__CHATTER__WRONG_WAY_4__040__M__1": "Ha... Belki...",
"VO__AMICIA__CH16__CHATTER__WRONG_WAY_5__020__M__1": "Hâlâ... çok zor...",
"VO__AMICIA__CH16__CHATTER__WRONG_WAY_5__040__M__1": "Sadece bırak... Bana biraz zaman ver.",
"VO__AMICIA__CH16__HELPER__A_PHOENIX_LIE_1__010__M__1": "Ankalar işe yaramayacak... Onları geride bırakmalıyım...",
"VO__AMICIA__CH16__HELPER__A_PHOENIX_LIE_2__010__M__1": "Daireler çiziyorsun... Ankaları bırak... Yoldan çık...",
"VO__AMICIA__CH16__RTC__880_A_LONG_CLIMB__025__M__1": "Değilim. Sadece bazen unutuyorum.",
"VO__AMICIA__CH16__RTC__880_A_LONG_CLIMB__030__M__1": "Lucas... Söylemeliyim ki... Seni yanımda bulundurmak bir onur. Dünyadaki en güvenilir... en sağlam... en iyi şeysin.",
"VO__AMICIA__CH16__RTC__880_A_LONG_CLIMB__070__M__1": "Yaşamalı. Bundan çok daha iyisini hak ediyor.",
"VO__AMICIA__CH16__RTC__890_NEST__020__M__1": "Bunu... o mu yaptı?",
"VO__AMICIA__CH16__RTC__890_NEST__050__M__1": "Üzgünüm.",
"VO__AMICIA__CH16__RTC__890_NEST__080__M__1": "Dinle, ben gideceğim. Bunu yapan benim...",
"VO__AMICIA__CH16__RTC__890_NEST__100__M__1": "O hâlde dalalım.",
"VO__AMICIA__CH16__RTC__895_SLIDING__030__M__1": "Hugo...",
"VO__AMICIA__CH16__RTC__895_SLIDING__035__M__1": "Bir şeye tutun!",
"VO__AMICIA__CH16__RTC__895_SLIDING__100__M__1": "Kırık mı?",
"VO__AMICIA__CH16__RTC__895_SLIDING__130__M__1": "Sophia yaralı!",
"VO__AMICIA__CH16__RTC__895_SLIDING__150__M__1": "Kımıldama!",
"VO__AMICIA__CH16__RTC__895_SLIDING__170__M__1": "Karaya çıkmak için değil, o kesin.",
"VO__AMICIA__CH16__RTC__895_SLIDING__190__M__1": "Üzülme. Fazlasıyla yeterince yaptın. Lucas'la ben... bunu daha önce de yaşadık. Sayılır.",
"VO__AMICIA__CH16__RTC__895_SLIDING__220__M__1": "Güneşin altında görüşürüz.",
"VO__AMICIA__CH16__RTC__900_INGREDIENT__020__M__1": "Şu hâline bak... Battaniyenin altına saklanmışsın, tıpkı üzgün olduğun zamanlardaki gibi...",
"VO__AMICIA__CH16__RTC__900_INGREDIENT__070__M__1": "Ne bulmayı beklemeliyiz?",
"VO__AMICIA__CH16__RTC__900_INGREDIENT__120__M__1": "Demek onu da geçmemiz gerek...",
"VO__AMICIA__CH16__RTC__900_INGREDIENT__140__M__1": "Tamam.",
"VO__AMICIA__CH16__RTC__901_NEBULA_SLOPE__010__M__1": "Derin bir nefes al.",
"VO__AMICIA__CH16__RTC__901_NEBULA_SLOPE__020__M__1": "Ah... Lucas?... LUCAS!",
"VO__AMICIA__CH16__RTC__910_BURNING__150__M__1": "Lucas...?",
"VO__AMICIA__CH16__RTC__910_BURNING__170__M__1": "Olamaz...",
"VO__AMICIA__CH16__RTC__910_BURNING__190__M__1": "Evet!",
"VO__AMICIA__CH16__RTC__920_SILENCE__190__M__1": "YAPAMAM!",
"VO__AMICIA__CH16__RTC__920_SILENCE__210__M__1": "HAYIIIR!",
"VO__HUGO__CH16__CHATTER__A_PHOENIX_LIE__020__M__1": "Hayır... sen koydun.",
"VO__HUGO__CH16__CHATTER__A_PHOENIX_LIE__040__M__1": "Buradayım. Yakınım.",
"VO__HUGO__CH16__CHATTER__A_PHOENIX_LIE__060__M__1": "Çünkü hâlâ arkana bakıyorsun.",
"VO__HUGO__CH16__CHATTER__A_PHOENIX_LIE__080__M__1": "O yolu denedik, Amicia, ve bir yalandı...",
"VO__HUGO__CH16__CHATTER__A_PHOENIX_LIE__100__M__1": "Bir yalandı ve ölüm getirdi.",
"VO__HUGO__CH16__CHATTER__A_PHOENIX_LIE_LOST__005__M__1": "Neden hâlâ o kuşları takip ediyorsun?",
"VO__HUGO__CH16__CHATTER__A_PHOENIX_LIE_LOST__020__M__1": "Burası geçmişe ait. Burayı bırak. Kendi yolunu bul.",
"VO__HUGO__CH16__CHATTER__BREAKING_TRAP__010__M__1": "Kaybolduğunu ve korktuğunu biliyorum... Ama yanındayım...",
"VO__HUGO__CH16__CHATTER__DEATH_DOOR_RTE__040__M__1": "Üzgünüm. Ama artık hazırsın. Her şeyi kurtarmaya.",
"VO__HUGO__CH16__CHATTER__DEATH_DOOR_RTE__060__M__1": "Biliyorum... Ama artık kendimi durduramıyorum. Beni sadece sen durdurabilirsin.",
"VO__HUGO__CH16__CHATTER__DEATH_DOOR_RTE__080__M__1": "Seni seviyorum. Seninle mutlu oldum. Elveda, Amicia.",
"VO__HUGO__CH16__CHATTER__DEATH_INTRO__010__M__1": "Seninle gurur duyuyorum.",
"VO__HUGO__CH16__CHATTER__DEATH_INTRO__017__M__1": "Buradayım...",
"VO__HUGO__CH16__CHATTER__DEATH_INTRO__040__M__1": "Ben de...",
"VO__HUGO__CH16__CHATTER__DEATH_INTRO__046__M__1": "Ama başardın... Yürüyebiliyor musun?",
"VO__HUGO__CH16__CHATTER__DEATH_INTRO__060__M__1": "Evet...",
"VO__HUGO__CH16__CHATTER__DEATH_INTRO__070__M__1": "Gel.",
"VO__HUGO__CH16__CHATTER__DEATH_MOVE__020__M__1": "Amicia... Öldüğünü sanmıştım... Gerçekten sanmıştım...",
"VO__HUGO__CH16__CHATTER__DEATH_MOVE__040__M__1": "Sanki... yapayalnızdım... bu yüzden bir hata yaptım...",
"VO__HUGO__CH16__CHATTER__DEATH_MOVE__060__M__1": "Ama bu büyük bir hata. Şu an o kadar çok insan ölüyor ki, hissedebiliyorum... ve daha başlangıç bu...",
"VO__HUGO__CH16__CHATTER__DEATH_MOVE__080__M__1": "Ama...",
"VO__HUGO__CH16__CHATTER__GOLEM_LOOP_2__020__M__1": "Var... Eskiden yapmayacağın bir şey.",
"VO__HUGO__CH16__CHATTER__GOLEM_LOOP_3_KILLING_1__005__M__1": "Yine başlıyorsun...",
"VO__HUGO__CH16__CHATTER__GOLEM_LOOP_3_KILLING_1__020__M__1": "Aradığın cevap yakında... Bir koruma yanılsaması...",
"VO__HUGO__CH16__CHATTER__GOLEM_LOOP_3_KILLING_1__040__M__1": "Evet. Çok eskiden kalma bir sembol... geçmiş inançlarından...",
"VO__HUGO__CH16__CHATTER__GOLEM_LOOP_3_KILLING_2__030__M__1": "Seni geride tutan bu alev. Söndür onu. Acısız olacak...",
"VO__HUGO__CH16__CHATTER__GOLEM_LOOP_4_KILLING_2__010__M__1": "Onlar düşman değil. Kendinle barış. Lütfen...",
"VO__HUGO__CH16__CHATTER__GOLEM_LOOP_4_KILLING_3__030__M__1": "Yapabilirsin... Bırak gitsin. Bir kez olsun teslim ol. Söndür bu alevi ve bana katıl.",
"VO__HUGO__CH16__CHATTER__GOLEMS_KILLING_2__010__M__1": "Seni o kadar çok kez savaşırken gördüm ki...",
"VO__HUGO__CH16__CHATTER__GOLEMS_KILLING_2__030__M__1": "Yine de geri adım atmayacaksın, değil mi?",
"VO__HUGO__CH16__CHATTER__GOLEMS_KILLING_2__050__M__1": "Bir seçeneğin var... Ama seni korkutuyor.",
"VO__HUGO__CH16__CHATTER__GOLEMS_KILLING_3__010__M__1": "Çok fazlalar, Amicia...",
"VO__HUGO__CH16__CHATTER__GOLEMS_KILLING_3__030__M__1": "Ama umursuyorum... Ve seni öyle savaşırken görmek acı veriyor...",
"VO__HUGO__CH16__CHATTER__GOLEMS_KILLING_3__050__M__1": "Eskisi gibi... her savaşın önemli olduğu zamanlardaki gibi...",
"VO__HUGO__CH16__CHATTER__GOLEMS_KILLING_4__020__M__1": "Yapmayacaklar... Bu kadar sağlam olmaya çalışmayı bırak... belki bir şey öğrenirsin. Bunu hatırlıyor musun?",
"VO__HUGO__CH16__CHATTER__GOLEMS_KILLING_4__040__M__1": "Yıkılacaksın... Yıkılman gerek.",
"VO__HUGO__CH16__CHATTER__GOLEMS_LOOP_2__040__M__1": "Eski benliğini söndür.",
"VO__HUGO__CH16__CHATTER__GOLEMS_LOOP_2_KILL_1__010__M__1": "Neden hâlâ savaşıyorsun?",
"VO__HUGO__CH16__CHATTER__GOLEMS_LOOP_2_KILL_1__030__M__1": "Evet, çünkü onlara ihtiyacın var! Savaşmak için bir bahaneye ihtiyacın var.",
"VO__HUGO__CH16__CHATTER__GOLEMS_LOOP_2_KILL_1__050__M__1": "Savaşmak kazanabileceğin anlamına gelir, ama... gerçek şu ki... savaşma zamanı bitti, Amicia. Bunu kabul etmen gerek.",
"VO__HUGO__CH16__CHATTER__GOLEMS_LOOP_2_KILL_2__010__M__1": "Bu senin umudun... işleri eskisi gibi düzeltebileceğin... Tıpkı bu alevin eskiden işe yaradığı gibi...",
"VO__HUGO__CH16__CHATTER__GOLEMS_LOOP_2_KILL_3__020__M__1": "Anladığını göster onlara.",
"VO__HUGO__CH16__CHATTER__LACUNA_FAIR__020__M__1": "Onları yiyorum, Amicia. Sadece onları değil, hepsini, ve sıçanlar yayıldıkça daha da fazlasını.",
"VO__HUGO__CH16__CHATTER__LACUNA_FAIR__040__M__1": "Tamamen değil... Bir şansımız var. Sonuncusu...",
"VO__HUGO__CH16__CHATTER__LACUNA_FAIR__060__M__1": "Sanırım çoktan biliyorsun...",
"VO__HUGO__CH16__CHATTER__LACUNA_FAIR__080__M__1": "Beni durdurmalısın... Macula'yı durdurmak için.",
"VO__HUGO__CH16__CHATTER__MARKET_TRANSITION__005__M__1": "Macula'nın beni tamamen ele geçirmesine izin verdim. Şimdi olan bu...",
"VO__HUGO__CH16__CHATTER__MARKET_TRANSITION__020__M__1": "Bir şey yapmalıyız, insanların ölmesini durdurmalıyız!",
"VO__HUGO__CH16__CHATTER__PHOENIX_LIE___120__M__1": "Yeni yollara ihtiyacın var. Her şey değişti, ama sen hâlâ değişmemiş gibi düşünüyorsun.",
"VO__HUGO__CH16__CHATTER__PHOENIX_LOOP_2__050__M__1": "Kafanın içine sıkışıp kaldın. Korktuğunda ilerlemek zordur, biliyorum... Sorun değil. Yapacaksın.",
"VO__HUGO__CH16__CHATTER__PHOENIX_LOOP_3__030__M__1": "Kendine bu kadar yüklenme. Kolay değil, hepsi bu... Ama artık daha net görüyorsun. Öğrendin.",
"VO__HUGO__CH16__CHATTER__PHOENIX_LOOP_3__050__M__1": "Biliyorum.",
"VO__HUGO__CH16__CHATTER__PHOENIX_LOOP_4__020__M__1": "Neredeyse vardın...",
"VO__HUGO__CH16__CHATTER__PHOENIX_LOOP_4__040__M__1": "Hep böyledir... Değişmek zaman alır.",
"VO__HUGO__CH16__CHATTER__PHOENIX_LOOP_5__020__M__1": "Üzülme. Hazır olduğunda varacaksın.",
"VO__HUGO__CH16__CHATTER__PHOENIX_LOOP_5__040__M__1": "Yeterince güçlü olduğunda beni göreceksin. Bu çok önemli...",
"VO__HUGO__CH16__CHATTER__PILGRIMS_DEATHS__020__M__1": "Hacılar...",
"VO__HUGO__CH16__CHATTER__PILGRIMS_DEATHS__040__M__1": "Üzgünüm!",
"VO__HUGO__CH16__CHATTER__PILGRIMS_DEATHS__070__M__1": "Haklı, bunu ben yapıyorum...",
"VO__HUGO__CH16__CHATTER__PILGRIMS_DEATHS__090__M__1": "Yaptığım hata bu. Dönüştüğüm şey bu...",
"VO__HUGO__CH16__CHATTER__PILGRIMS_SIGHT__020__M__1": "Çıkış en sonda.",
"VO__HUGO__CH16__CHATTER__PILGRIMS_TRANSITION__010__M__1": "Bunu düzeltmemiz gerek, Amicia...",
"VO__HUGO__CH16__CHATTER__PILGRIMS_TRANSITION__030__M__1": "Evet...",
"VO__HUGO__CH16__CHATTER__RED_CITY_MARKET__005__M__1": "Onlara bak...",
"VO__HUGO__CH16__CHATTER__RED_CITY_MARKET__010__M__1": "Burayı sevmiştim... ve bu insanları...",
"VO__HUGO__CH16__CHATTER__RED_CITY_MARKET__030__M__1": "Yapamam.",
"VO__HUGO__CH16__CHATTER__RED_CITY_MARKET__037__M__1": "Şimdiden unuttun mu?!",
"VO__HUGO__CH16__CHATTER__RED_CITY_MARKET__050__M__1": "Ben artık Macula'YIM! Öyleyim!",
"VO__HUGO__CH16__CHATTER__RED_CITY_MARKET__070__M__1": "Olabileceğini biliyordun. Çok geç.",
"VO__HUGO__CH16__CHATTER__STOP_ME__020__M__1": "Beni canavara dönüşmekten durdurabilecek... tek kişi sensin.",
"VO__HUGO__CH16__CHATTER__STOP_ME__040__M__1": "Olacağım... sevdiğim her şeyi öldürürsem... Bana gösterdiğin bütün o güzel şeyleri...",
"VO__HUGO__CH16__CHATTER__STOP_ME__060__M__1": "Lütfen Amicia...",
"VO__HUGO__CH16__CHATTER__WRONG_WAY_1__010__M__1": "İlerlemeliyiz, Amicia.",
"VO__HUGO__CH16__CHATTER__WRONG_WAY_2__010__M__1": "Hayır, Amicia. Öbür uca ulaşmamız gerek.",
"VO__HUGO__CH16__CHATTER__WRONG_WAY_3__010__M__1": "Burada kalamayız...",
"VO__HUGO__CH16__CHATTER__WRONG_WAY_3__030__M__1": "Evet... Devam edelim, lütfen... Yardımına ihtiyacım var...",
"VO__HUGO__CH16__CHATTER__WRONG_WAY_4__010__M__1": "Ne yapıyorsun?",
"VO__HUGO__CH16__CHATTER__WRONG_WAY_4__030__M__1": "Evet... Ama buradan tek bir çıkış var, Amicia. Geri dönelim.",
"VO__HUGO__CH16__CHATTER__WRONG_WAY_5__010__M__1": "Çıkmamız gerek, Amicia.",
"VO__HUGO__CH16__CHATTER__WRONG_WAY_5__030__M__1": "Biliyorum... ama burada sonsuza dek kalamayız...",
"VO__HUGO__CH16__CHATTER__WRONG_WAY_5__050__M__1": "Evet...",
"VO__LUCAS__CH16__CHATTER__4TH_COVER_FALL__020__M__1": "Koş!",
"VO__LUCAS__CH16__CHATTER__CARNATION__020__M__1": "Ah... Kendimi yaşlı hissettirdi bu...",
"VO__LUCAS__CH16__CHATTER__CARNATION_INTRO__010__M__1": "Bak, kim sağ kurtulmuş...",
"VO__LUCAS__CH16__CHATTER__EPICENTRE__010__M__1": "Orada...",
"VO__LUCAS__CH16__CHATTER__EPICENTRE__030__M__1": "Ne yapman gerektiğini... biliyor musun?",
"VO__LUCAS__CH16__CHATTER__FIRST_STEPS__020__M__1": "Öyleler, artık Hugo onların lideri olduğuna göre.",
"VO__LUCAS__CH16__CHATTER__LAST_CALL__010__M__1": "Amicia... Geldik...",
"VO__LUCAS__CH16__CHATTER__LAST_RUN__020__M__1": "Hayır...",
"VO__LUCAS__CH16__CHATTER__LAST_RUN__040__M__1": "Başaramayacağız!",
"VO__LUCAS__CH16__CHATTER__LAST_RUN__060__M__1": "Evet! Evet... Ha...",
"VO__LUCAS__CH16__CHATTER__LAST_RUN_START__020__M__1": "Yanındayım!",
"VO__LUCAS__CH16__CHATTER__REACH_1ST_COVER__010__M__1": "Oh...",
"VO__LUCAS__CH16__CHATTER__REACH_1ST_COVER__016__M__1": "Evet... Devam edelim... ayakta kalan duvarlara koşalım...",
"VO__LUCAS__CH16__CHATTER__REACH_1ST_COVER__030__M__1": "Evet... Yol göster.",
"VO__LUCAS__CH16__CHATTER__REACH_2ND_COVER__020__M__1": "Buradayım!",
"VO__LUCAS__CH16__CHATTER__REACH_3RD_COVER__014__M__1": "Dur! Dur...",
"VO__LUCAS__CH16__CHATTER__REACH_3RD_COVER__020__M__1": "İşte böyle!",
"VO__LUCAS__CH16__CHATTER__REACH_3RD_COVER__040__M__1": "Sanırım öyle!",
"VO__LUCAS__CH16__CHATTER__REACH_5TH_COVER__020__M__1": "Bu çılgınlık...",
"VO__LUCAS__CH16__CHATTER__REACH_6TH_COVER__010__M__1": "Ah... kalbim...",
"VO__LUCAS__CH16__CHATTER__REACH_BRIDGE__020__M__1": "Ne kadar süreyle?...",
"VO__LUCAS__CH16__CHATTER__REACH_BRIDGE__040__M__1": "Evet...",
"VO__LUCAS__CH16__CHATTER__RUN_TO_2ND_COVER__020__M__1": "Evet!",
"VO__LUCAS__CH16__CHATTER__RUN_TO_2ND_COVER__030__M__1": "Ha... Daha hızlı...",
"VO__LUCAS__CH16__CHATTER__RYTHMIC_CYCLE__015__M__1": "Amicia! Buradayım!",
"VO__LUCAS__CH16__CHATTER__RYTHMIC_CYCLE__030__M__1": "Peki Sophia?!",
"VO__LUCAS__CH16__CHATTER__RYTHMIC_CYCLE__050__M__1": "Bunu hâlâ başarabiliriz! Aşağıda ayakta duran şu duvar parçasını görüyor musun?!... Sıçanlar etrafından dolaşıyor! Orada buluşalım!",
"VO__LUCAS__CH16__CHATTER__RYTHMIC_CYCLE__070__M__1": "Biliyorum! Ama sayıyordum, ve tıpatıp aynı tempoyu koruyorlar! İki dalga arasında yetişebiliriz!",
"VO__LUCAS__CH16__CHATTER__RYTHMIC_CYCLE__090__M__1": "Sen hazır olunca! Merak etme, sana ayak uydururum!",
"VO__LUCAS__CH16__CHATTER__TO_1ST_WALL_LUCAS__020__M__1": "Aman Tanrım!",
"VO__LUCAS__CH16__CHATTER__TO_4TH_COVER_START__020__M__1": "Kahrolası!",
"VO__LUCAS__CH16__CHATTER__TO_6TH_COVER_RUN__020__M__1": "Görüyorum!",
"VO__LUCAS__CH16__CHATTER__TO_6TH_COVER_START__010__M__1": "Yanındayım!",
"VO__LUCAS__CH16__CHATTER__TO_7TH_COVER_SQUEEZE__020__M__1": "Yürü! Lütfen yürü!",
"VO__LUCAS__CH16__CHATTER__TO_7TH_COVER_START__010__M__1": "Tamam...",
"VO__LUCAS__CH16__CHATTER__TO_7TH_COVER_START__020__M__1": "Başka bir yol! Çabuk!",
"VO__LUCAS__CH16__CHATTER__TO_LUCAS_POSITION__010__M__1": "Bana ulaşmaya çalış, Amicia! Aşağı inmeye devam etmeliyiz!",
"VO__LUCAS__CH16__CHATTER__WAITING_1__010__M__1": "Amicia...",
"VO__LUCAS__CH16__CHATTER__WAITING_2__010__M__1": "Vaktimiz... yok...",
"VO__LUCAS__CH16__CHATTER__WAITING_3__010__M__1": "Eğer yapamıyorsan...",
"VO__LUCAS__CH16__RTC__880_A_LONG_CLIMB__020__M__1": "Ben de seni durdurulamaz sanırdım...",
"VO__LUCAS__CH16__RTC__880_A_LONG_CLIMB__040__M__1": "Bilmiyorum... Ama... sen benim ailemsin.",
"VO__LUCAS__CH16__RTC__890_NEST__030__M__1": "Artık Macula'yla bir o...",
"VO__LUCAS__CH16__RTC__890_NEST__070__M__1": "Ona ulaşabilirsek... Belki. Ama derin bir dalış olacak.",
"VO__LUCAS__CH16__RTC__890_NEST__090__M__1": "Amicia, onu bu dünyaya bağlayan her ne ise ona ihtiyacımız var... Ve hepimiz ona bağlıyız. Yani...",
"VO__LUCAS__CH16__RTC__895_SLIDING__040__M__1": "Hayır!",
"VO__LUCAS__CH16__RTC__895_SLIDING__120__M__1": "İyi misin?!",
"VO__LUCAS__CH16__RTC__895_SLIDING__140__M__1": "Sana katılmaya çalışacağım!",
"VO__LUCAS__CH16__RTC__900_INGREDIENT__030__M__1": "Nebula onun etrafında yoğunlaşıyor... İçeride çok şey oluyor olmalı...",
"VO__LUCAS__CH16__RTC__900_INGREDIENT__090__M__1": "Söylemesi zor... Onu dev bir pota gibi düşün; içinde... Macula, Hugo ve Nebula birleşiyor... Kandırılmış bir çocuğun hayalleri... atmosfere karışıyor... dünyayı değiştiriyor.",
"VO__LUCAS__CH16__RTC__900_INGREDIENT__100__M__1": "Bu son eşik. Tüm doğa yasaları burada son bulur.",
"VO__LUCAS__CH16__RTC__900_INGREDIENT__130__M__1": "Kardeşine ulaşmak için, evet.",
"VO__LUCAS__CH16__RTC__910_BURNING__110__M__1": "Ayağa kalk! Amicia, ayağa kalkmalısın!",
"VO__LUCAS__CH16__RTC__910_BURNING__120__M__1": "Amicia burada, Hugo! Yaşıyor! Senin için geldi!",
"VO__LUCAS__CH16__RTC__910_BURNING__130__M__1": "Sanırım beni duydu, Amicia! Şimdi ona ulaşmalıyız! Amicia! Bunu tek başıma yapamam! Sana ihtiyacım var! Sana ihtiyacım var!",
"VO__LUCAS__CH16__RTC__910_BURNING__140__M__1": "Lütfen...",
"VO__LUCAS__CH16__RTC__910_BURNING__160__M__1": "Buradayım. Buradayım.",
"VO__LUCAS__CH16__RTC__910_BURNING__180__M__1": "Ayağa kalkabilir misin?!",
"VO__LUCAS__CH16__RTC__920_SILENCE__180__M__1": "Amicia!",
"VO__LUCAS__CH16__RTC__920_SILENCE__200__M__1": "Üzgünüm... Üzgünüm.",
"VO__PEOPLE_F3__CH16__CHATTER__PILGRIMS_DEATHS__045__M__1": "Bu oğlan! Onu o öldürdü!",
"VO__SOPHIA__CH16__CHATTER__CARNATION__030__M__1": "O çiçek kesinlikle yüzünü güldürür.",
"VO__SOPHIA__CH16__CHATTER__FIRST_STEPS__010__M__1": "Gerçekten bir orduya benziyorlar...",
"VO__SOPHIA__CH16__CHATTER__FIRST_STEPS__040__M__1": "Birinin rüyası gerçek olmuş işte...",
"VO__SOPHIA__CH16__CHATTER__SOPHIA_GOODBYE__010__M__1": "Hiçbir yere gitmiyorum, Amicia.",
"VO__SOPHIA__CH16__CHATTER__SOPHIA_GOODBYE__030__M__1": "Biliyorum. Git, git!",
"VO__SOPHIA__CH16__RTC__880_A_LONG_CLIMB__050__M__1": "Bütün bunları başaramayacağını düşündüğün için mi paylaşıyorsun?",
"VO__SOPHIA__CH16__RTC__880_A_LONG_CLIMB__060__M__1": "Daha yaşayacak çok şeyiniz var. O yüzden başaracaksınız. Bu kesin bir emir.",
"VO__SOPHIA__CH16__RTC__880_A_LONG_CLIMB__080__M__1": "Şimdi, sadece adımına dikkat et.",
"VO__SOPHIA__CH16__RTC__890_NEST__010__M__1": "Bu da ne...?",
"VO__SOPHIA__CH16__RTC__890_NEST__040__M__1": "Demek cidden oraya giriyoruz?",
"VO__SOPHIA__CH16__RTC__890_NEST__060__M__1": "Sorun değil. Sanırım yeterince eğlendim, hem teknem zaten paramparça oldu. Sadece bunu durdurabileceğimizi söyle...",
"VO__SOPHIA__CH16__RTC__895_SLIDING__090__M__1": "Ben hayattayım. Sen hayatta mısın?",
"VO__SOPHIA__CH16__RTC__895_SLIDING__105__M__1": "Hayır hayır hayır, sadece...",
"VO__SOPHIA__CH16__RTC__895_SLIDING__160__M__1": "Söylemiştim... Ben kara için yaratılmadım...",
"VO__SOPHIA__CH16__RTC__895_SLIDING__180__M__1": "Üzgünüm...",
"VO__SOPHIA__CH16__RTC__895_SLIDING__200__M__1": "Her efsanenin denizciye ihtiyacı yok, ha? Üzücü.",
"VO__SOPHIA__CH16__RTC__895_SLIDING__210__M__1": "Git. Ve onunla geri dön.",
}
