# -*- coding: utf-8 -*-
# CH14 VO - kaynak proper Turkce; build asamasinda SUB uygulanir.
# Arnaud=sen(kaba), Count Victor->Amicia=sen(dusman). Rascasse/La Cuna korunur. sancak/yelken/guverte.
T = {
"VO__AMICIA__CH14__CHATTER__ABOUT_ARNAUD__010__M__1": "Hey, neler oluyor?",
"VO__AMICIA__CH14__CHATTER__ABOUT_ARNAUD__030__M__1": "Kim bilir?... Doğrudan ona sorsak nasıl olur?",
"VO__AMICIA__CH14__CHATTER__AMICIA_KILL_1__010__M__1": "Alçaklar!",
"VO__AMICIA__CH14__CHATTER__AMICIA_KILL_6__010__M__1": "Kaç tane var?!",
"VO__AMICIA__CH14__CHATTER__AMICIA_KILL_8__010__M__1": "Defolun!",
"VO__AMICIA__CH14__CHATTER__AMICIA_KILL_8__040__M__1": "Neredeyse bitti Hugo! Seni buradan çıkarıyorum!",
"VO__AMICIA__CH14__CHATTER__AMICIA_KILL_9__020__M__1": "Önce seni ezecek, sonra da geri kalan herkesi!",
"VO__AMICIA__CH14__CHATTER__AMICIA_KILL_10__010__M__1": "Şu delinin emirlerine uymayı bırakın! Hepinizi öldürtecek!",
"VO__AMICIA__CH14__CHATTER__AMICIA_KILL_10__030__M__1": "Bunun için daha çok asker lazım size!",
"VO__AMICIA__CH14__CHATTER__AMICIA_KILL_11__010__M__1": "Pes etmemizi bekleme! Ölülere teslim olunmaz!",
"VO__AMICIA__CH14__CHATTER__AMICIA_KILL_12__030__M__1": "Kendin gel, Victor! Adamlarını yerine ölmeye yollamayı bırak!",
"VO__AMICIA__CH14__CHATTER__ARCHER_APPEARING__030__M__1": "Onları ben hallederim!",
"VO__AMICIA__CH14__CHATTER__ARCHER_APPEARING__040__M__1": "Gitmek için son şansın bu, Kont!",
"VO__AMICIA__CH14__CHATTER__ARCHER_APPEARING__060__M__1": "Şansım mı?! Annemizi elimizden aldın! Ve karın bunun bedelini ödedi!",
"VO__AMICIA__CH14__CHATTER__ARCHERS_APPROACH__010__M__1": "Bize toslayacaklar!",
"VO__AMICIA__CH14__CHATTER__ARCHERS_SHOOTING__020__M__1": "Cehenneme gidin! Hepiniz!",
"VO__AMICIA__CH14__CHATTER__ARNAUD_INTERACT__010__M__1": "Bayılmış... Orada kal, bundan sonra uyanmak istemezsin, inan bana...",
"VO__AMICIA__CH14__CHATTER__ARNAUD_KILL_1__020__M__1": "Dayanmalıyız, Arnaud!",
"VO__AMICIA__CH14__CHATTER__ARNAUD_KILL_2__030__M__1": "İçeride kal, Hugo!",
"VO__AMICIA__CH14__CHATTER__ARNAUD_KILL_2__040__M__1": "Teknenin işi bitti, Arnaud!",
"VO__AMICIA__CH14__CHATTER__ARNAUD_KILL_3__030__M__1": "Yarın diye bir şey olmayacak! Hiç kimse için!",
"VO__AMICIA__CH14__CHATTER__ARNAUD_KILL_3__050__M__1": "Hayır! Biz... bunu başarabiliriz!",
"VO__AMICIA__CH14__CHATTER__ARNAUD_KILL_7__020__M__1": "Arnaud! Çok fazlalar! Başaramayacağız!",
"VO__AMICIA__CH14__CHATTER__ARNAUD_KILL_7__030__M__1": "Dayan... Biraz daha!",
"VO__AMICIA__CH14__CHATTER__BOAT_COLLIDE__010__M__1": "Olamaz... hayır... Hayır!",
"VO__AMICIA__CH14__CHATTER__CAUGHT_UP__020__M__1": "O SENİN çocuğun değil, seni kaçık!",
"VO__AMICIA__CH14__CHATTER__DEATH_VEIL_1__010__M__1": "Hayır, hayır!... Sakın... şimdi ölme!",
"VO__AMICIA__CH14__CHATTER__DEATH_VEIL_2__010__M__1": "Ha... Hayır, hayır, hayır! Odaklan!",
"VO__AMICIA__CH14__CHATTER__FIRST_ARROWS__010__M__1": "Okçular!",
"VO__AMICIA__CH14__CHATTER__FIRST_ARROWS__060__M__1": "Tamam... Dayan! Geliyorum!",
"VO__AMICIA__CH14__CHATTER__GETTING_SAIL_DOWN__010__M__1": "Hadi, daha hızlı...",
"VO__AMICIA__CH14__CHATTER__GETTING_SAIL_DOWN__030__M__1": "Onları atlatmalıyız! Bizi basarlarsa...",
"VO__AMICIA__CH14__CHATTER__INTERACT_BED__010__M__1": "Haftalarca uyuyabilirim... Bir banyo da lazım bana...",
"VO__AMICIA__CH14__CHATTER__INTERACT_MAST__010__M__1": "Rascasse... Hayatımızı kurtardın...",
"VO__AMICIA__CH14__CHATTER__INTERACT_REAR_BOAT__010__M__1": "Umarım La Cuna şimdi sular altındadır... Çıkar onu... aklından. Bitti artık.",
"VO__AMICIA__CH14__CHATTER__LUCAS_HUGO_HIDE__050__M__1": "Bir şey olmaz, Hugo!",
"VO__AMICIA__CH14__CHATTER__LUCAS_SAY_HI__040__M__1": "Pekâlâ.",
"VO__AMICIA__CH14__CHATTER__NEED_MORE_SAIL__030__M__1": "Geliyorum!",
"VO__AMICIA__CH14__CHATTER__PUSHING_CRATE__020__M__1": "Geliyorum!",
"VO__AMICIA__CH14__CHATTER__QUIETNESS__010__M__1": "Temiz hava...",
"VO__AMICIA__CH14__CHATTER__RESUME_PUSHING__010__M__1": "Fazla yaklaşıyorlar!",
"VO__AMICIA__CH14__CHATTER__RESUME_PUSHING__020__M__1": "Neden geri dönmek zorundaydı ki?!",
"VO__AMICIA__CH14__CHATTER__RESUME_PUSHING__040__M__1": "Evet, evet.",
"VO__AMICIA__CH14__CHATTER__SAIL_DOWN__010__M__1": "Tamam!",
"VO__AMICIA__CH14__CHATTER__SAIL_DOWN__040__M__1": "Hayır, hayır, hayır! Şimdi ne oldu?!",
"VO__AMICIA__CH14__CHATTER__SAIL_DOWN__070__M__1": "Hemen!",
"VO__AMICIA__CH14__CHATTER__SAIL_TURN__020__M__1": "Evet!",
"VO__AMICIA__CH14__CHATTER__SAIL_TURNING__010__M__1": "Bizi basarlarsa ne yapacağız?!",
"VO__AMICIA__CH14__CHATTER__SAIL_TURNING__025__M__1": "Bunu başaramama hakkımız yok, Arnaud!",
"VO__AMICIA__CH14__CHATTER__SHOCK__010__M__1": "Hayır, hayır, hayır! Bu olamaz...",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_HUGO__010__M__1": "Manzara nasıl?",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_HUGO__030__M__1": "Aklından ne geçiyor?",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_HUGO__050__M__1": "Şey, bilmiyorum... Acıktın mı?",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_HUGO__070__M__1": "Eh, hâlâ aynı!",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_HUGO__090__M__1": "Buna büyümek deniyor, Hugo. Bazı... şeyler... onu daha da hızlandırıyor.",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_HUGO__110__M__1": "Evet... Ama bundan sonra her şeyi yavaşlatacağız. İhtiyacımız olan tüm zamanı kullanacağız.",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_HUGO__130__M__1": "Yakında. Çok yakında... Eve gidiyoruz, Hugo. Bizim evimize.",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_LUCAS__010__M__1": "Hey...",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_LUCAS__030__M__1": "Önce sen.",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_LUCAS__050__M__1": "Değişmiş...",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_LUCAS__070__M__1": "Artık ileride bir yuva var, Lucas. Bizimle gelir misin?",
"VO__AMICIA__CH14__CHATTER__TALKING_TO_LUCAS__090__M__1": "Seninle olmaktan mutluyuz.",
"VO__AMICIA__CH14__CHATTER__UPPDER_DECK__020__M__1": "Pekâlâ!",
"VO__AMICIA__CH14__RTC__798_INTRO_SEA__010__M__1": "Ah, tamam... Sakin olalım.",
"VO__AMICIA__CH14__RTC__798_INTRO_SEA__040__M__1": "Hey!",
"VO__AMICIA__CH14__RTC__799_A_NEW_PLAN__005__M__1": "Hey!",
"VO__AMICIA__CH14__RTC__799_A_NEW_PLAN__020__M__1": "Öldüğümü sanarak uyandım.",
"VO__AMICIA__CH14__RTC__799_A_NEW_PLAN__060__M__1": "Annem... Bir evi vardı... Dağlarda, eski bir ev.",
"VO__AMICIA__CH14__RTC__799_A_NEW_PLAN__070__M__1": "Ona mutlu olma şansı sözü verdim. Onu orada bulacağız.",
"VO__AMICIA__CH14__RTC__799_A_NEW_PLAN__090__M__1": "Orada her zaman başımızın üstünde yerin var. Yükseklikleri sevmediğini biliyorum...",
"VO__AMICIA__CH14__RTC__800_LEAVING__090__M__1": "Hepimiz kurtulamadık.",
"VO__AMICIA__CH14__RTC__800_LEAVING__100__M__1": "Ama o artık iyileşecek. Hepimiz iyileşeceğiz.",
"VO__AMICIA__CH14__RTC__800_LEAVING__160__M__1": "Bakın kim nihayet kibar olmaya karar vermiş...",
"VO__AMICIA__CH14__RTC__800_LEAVING__180__M__1": "Savaş bitti, Arnaud. Hepimiz biraz dinlenmeyi hak ettik. Sen de denemelisin.",
"VO__AMICIA__CH14__RTC__800_LEAVING__220__M__1": "Kahretsin, Kont bu!",
"VO__AMICIA__CH14__RTC__801_IMPACT__020__M__1": "Lucas! Sophia!",
"VO__AMICIA__CH14__RTC__801_IMPACT__030__M__1": "Hayır!",
"VO__AMICIA__CH14__RTC__801_IMPACT__050__M__1": "Çok fazlalar, Arnaud!",
"VO__AMICIA__CH14__RTC__801_IMPACT__070__M__1": "Geliyorum!",
"VO__AMICIA__CH14__RTC__810_DARKNESS__040__M__1": "İçeride kal!",
"VO__ARNAUD__CH14__CHATTER__AMICIA_KILL_1__010__M__1": "Aferin, leydi!",
"VO__ARNAUD__CH14__CHATTER__AMICIA_KILL_6__020__M__1": "Gittikçe azalıyorlar! Önemli olan da bu!",
"VO__ARNAUD__CH14__CHATTER__AMICIA_KILL_8__020__M__1": "Evet! Devam et!",
"VO__ARNAUD__CH14__CHATTER__AMICIA_KILL_9__030__M__1": "Ona nefretini beslemeyi bırakınca düzelecek!",
"VO__ARNAUD__CH14__CHATTER__AMICIA_KILL_11__030__M__1": "Adamların da senden iyi değil!",
"VO__ARNAUD__CH14__CHATTER__ARCHER_APPEARING__020__M__1": "Okçuları sana bırakıyorum!",
"VO__ARNAUD__CH14__CHATTER__ARNAUD_KILL_1__010__M__1": "Adamlarının ölüşünü izlemek hoşuna gidiyor mu, Victor?!",
"VO__ARNAUD__CH14__CHATTER__ARNAUD_KILL_1__030__M__1": "Merak etme! Bu alçak ölene dek durmayacağım!",
"VO__ARNAUD__CH14__CHATTER__ARNAUD_KILL_2__010__M__1": "Hadi! Gelin! Cesetlerinizin üstünde dans edeceğim!",
"VO__ARNAUD__CH14__CHATTER__ARNAUD_KILL_2__050__M__1": "Biz de onlarınkini alırız!",
"VO__ARNAUD__CH14__CHATTER__ARNAUD_KILL_3__010__M__1": "O oğlana asla dokunamayacaksın, duydun mu?!",
"VO__ARNAUD__CH14__CHATTER__ARNAUD_KILL_4__010__M__1": "Gelmeye devam edin! Isınıyorum! Daha çabuk geberirsiniz!",
"VO__ARNAUD__CH14__CHATTER__ARNAUD_KILL_5__010__M__1": "Bağırsaklarınızı denize döküp kıpkırmızı edeceğim!",
"VO__ARNAUD__CH14__CHATTER__BOAT_COLLIDE__060__M__1": "Amicia... Amicia! Neler oluyor?! Olamaz... Denize düştüler! Kalk Amicia!",
"VO__ARNAUD__CH14__CHATTER__CAUGHT_UP__030__M__1": "Ona dokunursan ölürsün, Victor!",
"VO__ARNAUD__CH14__CHATTER__FIGHT_BEGINNING__020__M__1": "Buraya gel, Victor! Korkaklık etme!",
"VO__ARNAUD__CH14__CHATTER__FIGHT_BEGINNING__040__M__1": "Defol! Sana daha çok sürprizim var!",
"VO__ARNAUD__CH14__CHATTER__FIRST_ARROWS__020__M__1": "Herkes eğilsin!",
"VO__ARNAUD__CH14__CHATTER__FIRST_ARROWS__050__M__1": "Yükü ben hallederim! Git!",
"VO__ARNAUD__CH14__CHATTER__GETTING_SAIL_DOWN__020__M__1": "O alçak bir türlü vazgeçemedi...",
"VO__ARNAUD__CH14__CHATTER__NEED_MORE_SAIL__020__M__1": "Dümeni tutmaya devam et. Şu yelkeni indireceğiz!",
"VO__ARNAUD__CH14__CHATTER__NEED_MORE_SAIL__025__M__1": "Amicia, buraya yukarı! Benimle!",
"VO__ARNAUD__CH14__CHATTER__PUSHING_CRATE__010__M__1": "Ha... Bir el at, Amicia!",
"VO__ARNAUD__CH14__CHATTER__RESUME_PUSHING__030__M__1": "Onu sonraya sakla! Odaklanmanı istiyorum!",
"VO__ARNAUD__CH14__CHATTER__SAIL_DOWN__030__M__1": "Hâlâ mesafeyi kapatıyorlar!",
"VO__ARNAUD__CH14__CHATTER__SAIL_DOWN__060__M__1": "Amicia! Alt güverteye in!",
"VO__ARNAUD__CH14__CHATTER__SAIL_TURN__010__M__1": "Sen kendine doğru çekerken ben biraz gevşeteceğim!",
"VO__ARNAUD__CH14__CHATTER__SAIL_TURN_OK__020__M__1": "Ama bu yetmeyecek! Geliyorlar!",
"VO__ARNAUD__CH14__CHATTER__SAIL_TURN_OK__070__M__1": "Hallediyorum!",
"VO__ARNAUD__CH14__CHATTER__SAIL_TURNING__020__M__1": "Bir arada kalıp onları parça parça doğrarız!",
"VO__ARNAUD__CH14__CHATTER__SAIL_TURNING__035__M__1": "İzin vermeyiz!",
"VO__ARNAUD__CH14__CHATTER__UPPDER_DECK__010__M__1": "Öbür taraftaki ipi tut!",
"VO__ARNAUD__CH14__HELPER__HOIST_SAIL_1__010__M__1": "Ne yapıyorsun?! Kendi tarafındaki yelkeni indir!",
"VO__ARNAUD__CH14__HELPER__HOIST_SAIL_2__010__M__1": "Öbür taraftaki ip, Amicia! Çabuk!",
"VO__ARNAUD__CH14__HELPER__PUSHING_CRATE_1__010__M__1": "Burada sana ihtiyacım var, Amicia!",
"VO__ARNAUD__CH14__HELPER__PUSHING_CRATE_2__010__M__1": "Amicia! Şunu itmeme yardım et!",
"VO__ARNAUD__CH14__HELPER__SAIL_TURN_ROPE_1__010__M__1": "Yelkeni döndürmek için sancak ipini çek! Hemen!",
"VO__ARNAUD__CH14__HELPER__SAIL_TURN_ROPE_2__010__M__1": "Amicia, çabuk sancağa geç ve ipi çek!",
"VO__ARNAUD__CH14__RTC__800_LEAVING__120__M__1": "Sen ne dersin?",
"VO__ARNAUD__CH14__RTC__800_LEAVING__140__M__1": "Yerinde tespit.",
"VO__ARNAUD__CH14__RTC__800_LEAVING__150__M__1": "Hey... Üzgünüm... her şey için. Kız kardeşini bana yardım etmeye ikna ettiğin için teşekkürler. Beni kurtardın.",
"VO__ARNAUD__CH14__RTC__800_LEAVING__151__M__1": "Hey... Üzgünüm... her şey için.",
"VO__ARNAUD__CH14__RTC__800_LEAVING__152__M__1": "Kız kardeşini bana yardım etmeye ikna ettiğin için teşekkürler. Beni kurtardın.",
"VO__ARNAUD__CH14__RTC__800_LEAVING__170__M__1": "Pişman etme beni.",
"VO__ARNAUD__CH14__RTC__800_LEAVING__190__M__1": "Hımm.",
"VO__ARNAUD__CH14__RTC__800_LEAVING__240__M__1": "Gördün mü? Savaşın olayı bu işte...",
"VO__ARNAUD__CH14__RTC__800_LEAVING__245__M__1": "Ne zaman biteceğine sen karar veremezsin.",
"VO__ARNAUD__CH14__RTC__801_IMPACT__040__M__1": "Hadi! Hepinizi parça parça doğrayacağım!",
"VO__ARNAUD__CH14__RTC__801_IMPACT__060__M__1": "İkimiz varsak olmaz!",
"VO__ARNAUD__CH14__RTC__810_DARKNESS__110__M__1": "Hugo! Benimle gel!",
"VO__ARNAUD__CH14__RTC__810_DARKNESS__115__M__1": "HUGO, BURAYA GEL!",
"VO__ARNAUD__CH14__RTC__810_DARKNESS__122__M__1": "HAYIR!",
"VO__ARNAUD__CH14__RTC__810_DARKNESS__126__M__1": "Tamam, sen kazandın! Ona zarar verme!",
"VO__ARNAUD__CH14__RTC__810_DARKNESS__170__M__1": "O bizim sonumuz, Victor!",
"VO__ARNAUD__CH14__RTC__810_DARKNESS__180__M__1": "Onu bırakman gerek... kız kardeşine...",
"VO__ARNAUD__CH14__RTC__810_DARKNESS__220__M__1": "Onunla ne planlıyorsan... İşe yaramayacak! Seni yok edecek!",
"VO__ARNAUD__CH14__RTC__810_DARKNESS__240__M__1": "Bitmedi, seni korkak!",
"VO__ARNAUD__CH14__RTC__810_DARKNESS__250__M__1": "Bana kan borçlusun!",
"VO__COUNT__CH14__CHATTER__AMICIA_KILL_9__010__M__1": "Bu çılgınlığa son ver ve Çocuğu bana ver!",
"VO__COUNT__CH14__CHATTER__AMICIA_KILL_10__020__M__1": "Biri şunu susturabilir mi lütfen?!",
"VO__COUNT__CH14__CHATTER__AMICIA_KILL_11__020__M__1": "Hadi, askerler! Eğitildiğiniz şeyi yapın! Durdurun onu!",
"VO__COUNT__CH14__CHATTER__AMICIA_KILL_12__040__M__1": "Ah, geleceğim! Vakti gelince!",
"VO__COUNT__CH14__CHATTER__ARCHER_APPEARING__010__M__1": "Askerler! Şu adamı öldürün! Okçular! Kızın menzili daha geniş! Ona odaklanın!",
"VO__COUNT__CH14__CHATTER__ARCHER_APPEARING__050__M__1": "Hayal görüyorsun, Amicia! Ve artık şansını fazla zorladın!",
"VO__COUNT__CH14__CHATTER__ARCHER_APPEARING__070__M__1": "Emilie onun bedeninde yaşayacak! Onun üzerinden hüküm sürecek!",
"VO__COUNT__CH14__CHATTER__ARNAUD_KILL_1__040__M__1": "O zaman nefesini boşa harcama, ihtiyar!",
"VO__COUNT__CH14__CHATTER__ARNAUD_KILL_3__020__M__1": "İndirin... onları! Yarın için savaşımız burada başlıyor!",
"VO__COUNT__CH14__CHATTER__ARNAUD_KILL_4__020__M__1": "O Çocuğu hak etmiyorsun! O daha yüce bir amaca hizmet edecek!",
"VO__COUNT__CH14__CHATTER__CAUGHT_UP__010__M__1": "Gerçekten BENİM çocuğumla gidebileceğini mi sandın?!",
"VO__COUNT__CH14__CHATTER__CAUGHT_UP__040__M__1": "Çocuğa zarar vermeyin! Geri kalanını öldürün!",
"VO__COUNT__CH14__CHATTER__FIGHT_BEGINNING__030__M__1": "Stratejiyi korkaklıkla karıştırıyorsun! Ama şaşırmadım!",
"VO__COUNT__CH14__CHATTER__ORDER_1__010__M__1": "Devam edin, askerler! Sadece iki kişiler!",
"VO__COUNT__CH14__CHATTER__ORDER_2__010__M__1": "Onları öldürün, yanımda bir yer kazanın!",
"VO__COUNT__CH14__CHATTER__ORDER_3__010__M__1": "Yoldaşlarınız sizin için kendilerini feda ediyor! Ölümlerini onurlandırın! Derhâl yok edin onları!",
"VO__COUNT__CH14__CHATTER__ORDER_4__010__M__1": "Kıpırdayın, askerler! Ordumuza yüz karasısınız!",
"VO__COUNT__CH14__CHATTER__ORDER_5__010__M__1": "Saldırmayı kesin! Kahretsin! Bir açık bekleyin!",
"VO__COUNT__CH14__RTC__810_DARKNESS__035__M__1": "Ateş!",
"VO__COUNT__CH14__RTC__810_DARKNESS__120__M__1": "Üzgünüm, çocuk. Sıçanlar burada sana yardım edemez.",
"VO__COUNT__CH14__RTC__810_DARKNESS__124__M__1": "Ne kadar kırılgan, küçük bir şey...",
"VO__COUNT__CH14__RTC__810_DARKNESS__135__M__1": "Ona zarar mı vereyim?...",
"VO__COUNT__CH14__RTC__810_DARKNESS__150__M__1": "O Emilie'nin oğlu... benim oğlum! O bir tanrı!",
"VO__COUNT__CH14__RTC__810_DARKNESS__190__M__1": "Hayır. Bunu Emilie'ye borçluyum.",
"VO__COUNT__CH14__RTC__810_DARKNESS__200__M__1": "Onunla, bu dünyanın sadece... kan... ve savaştan... ibaret olmadığına inanmak için çok uğraştım. Bu alevlerin üstüne bir örtü serebileceğime. Ama gerçek şu ki...",
"VO__COUNT__CH14__RTC__810_DARKNESS__210__M__1": "Bizim gibi insanlar... O ateşi beslemek için doğarız.",
"VO__COUNT__CH14__RTC__810_DARKNESS__230__M__1": "Ona neyi söylersem onu yok edecek... Bu dünyayı ateşe vereceğiz! Ve o ateşten bir imparatorluk dövüp çıkaracağım! Daha adil olanını.",
"VO__COUNT__CH14__RTC__810_DARKNESS__260__M__1": "O bedeli çoktan ödedim. Şimdi, oğlumun dinlenmesi gerek.",
"VO__COUNT__CH14__RTC__810_DARKNESS__270__M__1": "Bitirin şunu!",
"VO__HUGO__CH14__CHATTER__ABOUT_ARNAUD__020__M__1": "O... iyi mi?",
"VO__HUGO__CH14__CHATTER__ABOUT_ARNAUD__040__M__1": "Tamam...",
"VO__HUGO__CH14__CHATTER__AMICIA_KILL_8__030__M__1": "Amicia! Hava çok ısınıyor!",
"VO__HUGO__CH14__CHATTER__ARNAUD_KILL_2__020__M__1": "Amicia! Yangın kokusu alıyorum!",
"VO__HUGO__CH14__CHATTER__ARNAUD_KILL_3__040__M__1": "Gel saklan!",
"VO__HUGO__CH14__CHATTER__ARNAUD_KILL_7__010__M__1": "Ölmeden gel saklan!",
"VO__HUGO__CH14__CHATTER__HUGO_CALLS__010__M__1": "Amicia, gel bak!",
"VO__HUGO__CH14__CHATTER__LUCAS_HUGO_HIDE__020__M__1": "Peki ya diğerleri?!",
"VO__HUGO__CH14__CHATTER__LUCAS_HUGO_HIDE__040__M__1": "Tamam!",
"VO__HUGO__CH14__CHATTER__LUCAS_HUGO_HIDE__060__M__1": "Dikkatli ol!",
"VO__HUGO__CH14__CHATTER__TALKING_TO_HUGO__020__M__1": "Güzel...",
"VO__HUGO__CH14__CHATTER__TALKING_TO_HUGO__040__M__1": "Sence farklı mıyım?",
"VO__HUGO__CH14__CHATTER__TALKING_TO_HUGO__060__M__1": "Hı... Öyle mi?",
"VO__HUGO__CH14__CHATTER__TALKING_TO_HUGO__080__M__1": "Ha... Farklı hissediyorum. Şeyler... farklı geliyor.",
"VO__HUGO__CH14__CHATTER__TALKING_TO_HUGO__100__M__1": "Öyle mi?",
"VO__HUGO__CH14__CHATTER__TALKING_TO_HUGO__120__M__1": "Dağa varmak için sabırsızlanıyorum.",
"VO__HUGO__CH14__CHATTER__TALKING_TO_HUGO__140__M__1": "Evet!",
"VO__HUGO__CH14__RTC__800_LEAVING__110__M__1": "Yaşıyor musun?",
"VO__HUGO__CH14__RTC__800_LEAVING__130__M__1": "Ölü insanlar konuşmaz...",
"VO__HUGO__CH14__RTC__810_DARKNESS__030__M__1": "Gel, Amicia!",
"VO__HUGO__CH14__RTC__810_DARKNESS__090__M__1": "HAYIR! Amicia, hayır!",
"VO__HUGO__CH14__RTC__810_DARKNESS__095__M__1": "Amicia!",
"VO__HUGO__CH14__RTC__810_DARKNESS__099__M__1": "Amicia...",
"VO__HUGO__CH14__RTC__810_DARKNESS__105__M__1": "Onu öldürdün...",
"VO__LUCAS__CH14__CHATTER__BOAT_COLLIDE__010__M__1": "Dikkat! Yangın!",
"VO__LUCAS__CH14__CHATTER__BOAT_COLLIDE__040__M__1": "Haaaaaa!",
"VO__LUCAS__CH14__CHATTER__FIRST_ARROWS__030__M__1": "Fazla yaklaşıyorlar!",
"VO__LUCAS__CH14__CHATTER__LUCAS_HUGO_HIDE__010__M__1": "İçeri gir, Hugo! Daha güvenli olur!",
"VO__LUCAS__CH14__CHATTER__LUCAS_HUGO_HIDE__030__M__1": "Onlar hallederler! Ne olursa olsun kamarada kal, tamam mı?",
"VO__LUCAS__CH14__CHATTER__LUCAS_HUGO_HIDE__070__M__1": "Hugo, masanın ya da yatağın altına saklan! Güvende olana dek orada kal!",
"VO__LUCAS__CH14__CHATTER__LUCAS_SAY_HI__030__M__1": "İstersen gel konuşalım.",
"VO__LUCAS__CH14__CHATTER__TALKING_TO_LUCAS__020__M__1": "Ah, merhaba. Nasıl hissediyorsun?",
"VO__LUCAS__CH14__CHATTER__TALKING_TO_LUCAS__040__M__1": "Tıpkı... garip bir rüyanın ardından gibi... korkunç bir rüya... Ama onu görmeden uyanamıyordum...",
"VO__LUCAS__CH14__CHATTER__TALKING_TO_LUCAS__060__M__1": "Yeniden doğmuş... gibi neredeyse.",
"VO__LUCAS__CH14__CHATTER__TALKING_TO_LUCAS__080__M__1": "Şey, sanırım... sen ve Hugo benim yuvamsınız, yani... evet.",
"VO__LUCAS__CH14__RTC__800_LEAVING__088__M__1": "Asla geri dönemeyeceğiz sanmıştım...",
"VO__LUCAS__CH14__RTC__800_LEAVING__230__M__1": "Hızla yaklaşıyor.",
"VO__SOLDIER_N1__CH14__CHATTER__FIGHT_BEGINNING__010__M__1": "Şu tekneyi ele geçirin! Provence Kontu için!",
"VO__SOLDIER_S1__CH14__CHATTER__ARCHERS_SHOOTING__010__M__1": "Kont'u duydunuz! Ateş!",
"VO__SOLDIER_S2__CH14__CHATTER__ARCHERS_SHOOTING__030__M__1": "ATEŞ!",
"VO__SOLDIER_S2__CH14__CHATTER__ARNAUD_KILL_5__020__M__1": "Çocuğu geri ver bize!",
"VO__SOPHIA__CH14__CHATTER__BOAT_COLLIDE__010__M__1": "TEKNEM! LANET OLASI ALÇAKLAR!",
"VO__SOPHIA__CH14__CHATTER__BOAT_COLLIDE__030__M__1": "Amicia! Hayır!",
"VO__SOPHIA__CH14__CHATTER__BOAT_COLLIDE__050__M__1": "Olamaz!",
"VO__SOPHIA__CH14__CHATTER__FIRST_ARROWS__040__M__1": "Sapanın burada lazım, Amicia! Çabuk!",
"VO__SOPHIA__CH14__CHATTER__NEED_MORE_SAIL__010__M__1": "Daha hızlı olmalıyız! Ana yelken!",
"VO__SOPHIA__CH14__CHATTER__SAIL_DOWN__020__M__1": "Güzel!",
"VO__SOPHIA__CH14__CHATTER__SAIL_DOWN__050__M__1": "Yelkeni rüzgâra çevir! Daha iyi bir açı lazım!",
"VO__SOPHIA__CH14__CHATTER__SAIL_TURN_OK__010__M__1": "İşe yarıyor! Hızlanıyoruz!",
"VO__SOPHIA__CH14__CHATTER__SAIL_TURN_OK__030__M__1": "Çok ağırız! Biraz yükü denize at!",
"VO__SOPHIA__CH14__RTC__798_INTRO_SEA__030__M__1": "Günaydın, güneşim.",
"VO__SOPHIA__CH14__RTC__799_A_NEW_PLAN__010__M__1": "İyi uyudun mu?",
"VO__SOPHIA__CH14__RTC__799_A_NEW_PLAN__030__M__1": "O hissi bilirim...",
"VO__SOPHIA__CH14__RTC__799_A_NEW_PLAN__050__M__1": "Şimdi ne yapacaksın?",
"VO__SOPHIA__CH14__RTC__799_A_NEW_PLAN__080__M__1": "Kulağa hoş geliyor.",
"VO__SOPHIA__CH14__RTC__799_A_NEW_PLAN__100__M__1": "Hey... İnsanlar değişir.",
"VO__SOPHIA__CH14__RTC__800_LEAVING__210__M__1": "HEY! GEMİ!",
"VO__SOPHIA__CH14__RTC__800_LEAVING__250__M__1": "Güvertedeki kapak! İçeriden ne lazımsa al! Bordalamaya hazır olun!",
"VO__SOPHIA__CH14__RTC__801_IMPACT__010__M__1": "Sıkı tutunun!",
}
