# -*- coding: utf-8 -*-
# CH08 VO. onom/EMPTY atlanir. Count(Kont Victor), Countess(Emilie/Anne/Rahibe), Sophia, Arnaud.
# Child of Embers->Koz Cocugu, Brighter Days->Aydinlik Gunler, La Cuna korunur.
# Amicia/Hugo<->Kont/Kontes=siz (resmi); Kontes->Hugo=sen (anac). Arnaud<->Kont=sen (nefret).
T = {
"VO__AMICIA__CH08__CHATTER__ABOUT_SCULPTURE__020__M__1": "Hugo... gerçekten senin kuşun mu? İyice bak ona!",
"VO__AMICIA__CH08__CHATTER__ABOUT_SCULPTURE__040__M__1": "Güzel. Çok güzel. Hadi onların yanına dönelim.",
"VO__AMICIA__CH08__CHATTER__ABOUT_SCULPTURE__045__M__1": "Ve buradaki kimseye bundan bahsetme, tamam mı? Bu bizim sırrımız!",
"VO__AMICIA__CH08__CHATTER__ALONE_CABIN_BED__010__M__1": "Ne güzel bir yatak. Kaptanımızın zevki iyiymiş.",
"VO__AMICIA__CH08__CHATTER__ALONE_CABIN_INCENSE__010__M__1": "Şu koku... tütsü... harika... Hmmm...",
"VO__AMICIA__CH08__CHATTER__ALONE_CABIN_JEWELS__010__M__1": "Kolyeler, yüzükler... Epey zarif bir hanım...",
"VO__AMICIA__CH08__CHATTER__ALONE_CABIN_MAP__010__M__1": "Akdeniz... La Cuna burada bir yerde olmalı... Bu mu... Yoksa bu mu?",
"VO__AMICIA__CH08__CHATTER__ALONE_CABIN_POTS__010__M__1": "Otlar ve merhemler... Hugo'ya verdiği işe yaradı... Umarım daha iyidir.",
"VO__AMICIA__CH08__CHATTER__ALONE_DECK_STATUETTES__010__M__1": "Hayvanlar... Belki... Afrika'dan?... Hugo onlarla oynamış gibi. Umarım bir şey kırmamıştır...",
"VO__AMICIA__CH08__CHATTER__ALONE_DECK_VIEW__010__M__1": "Artık kıtayı göremiyoruz... Anne, Lucas, umarım güvendesinizdir...",
"VO__AMICIA__CH08__CHATTER__ALONE_HOLD_BOOKS__010__M__1": "Kitaplar... Epey nadir...",
"VO__AMICIA__CH08__CHATTER__ALONE_HOLD_CARPETS__010__M__1": "Bütün bunları elde etmek için çok seyahat etmiş olmalı... Ve şimdi muhtemelen onları kaçak satacak...",
"VO__AMICIA__CH08__CHATTER__ALONE_HOLD_MATTRESS__010__M__1": "Ah evet, bu Arnaud'nunki... Fırtınanın içinde horladığını duyduğuma inanamıyorum...",
"VO__AMICIA__CH08__CHATTER__ALONE_INTERACT_SHIELD__010__M__1": "Demek... ateşten sağ çıktı.",
"VO__AMICIA__CH08__CHATTER__ALONE_INTERACT_SHIELD__030__M__1": "İşte burada kırılmış...",
"VO__AMICIA__CH08__CHATTER__ALONE_INTERACT_SHIELD__050__M__1": "Sen mi?",
"VO__AMICIA__CH08__CHATTER__ALONE_INTERACT_SHIELD__070__M__1": "Ah... Anlıyorum... O zaman saklanması... acı bir hatıra...",
"VO__AMICIA__CH08__CHATTER__ALONE_INTERACT_SHIELD__090__M__1": "Sanırım ne demek istediğini anlıyorum...",
"VO__AMICIA__CH08__CHATTER__ALONE_INTERACT_SHIELD_AFTER__020__M__1": "Zaten öyle.",
"VO__AMICIA__CH08__CHATTER__ARNAUD_SIGHT__010__M__1": "Buradalar! Kont yaşıyor!",
"VO__AMICIA__CH08__CHATTER__BANQUETHALL_FRUIT_END__020__M__1": "Guyenne. Savaştan ve vebadan kaçtık. Buraya geldik, daha iyi bir hayat... umuduyla. Ve bu adayı duyduk.",
"VO__AMICIA__CH08__CHATTER__BANQUETHALL_FRUIT_END__050__M__1": "Biliyorum! Odamızı görmek için sabırsızlanıyorum!",
"VO__AMICIA__CH08__CHATTER__BANQUETHALL_FRUIT_OFFER__030__M__1": "Bir meyve, Hugo.",
"VO__AMICIA__CH08__CHATTER__BANQUETHALL_FRUIT_OFFER__060__M__1": "Tabii, ekselansları. Lütfen yavaş ol Hugo.",
"VO__AMICIA__CH08__CHATTER__BROKE_POTS_NOISE__030__M__1": "Ne?! Hayır!",
"VO__AMICIA__CH08__CHATTER__BROKE_POTS_NOISE__040__M__1": "Hayır, hayır!",
"VO__AMICIA__CH08__CHATTER__BROKE_POTS_NOISE__050__M__1": "Çabuk!",
"VO__AMICIA__CH08__CHATTER__BROKE_POTS_NOISE__060__M__1": "Eğil!",
"VO__AMICIA__CH08__CHATTER__CALL_SAIL__020__M__1": "Evet!... Ne yapacağız?",
"VO__AMICIA__CH08__CHATTER__CALL_SAIL__040__M__1": "Anlaşıldı!",
"VO__AMICIA__CH08__CHATTER__CLIMB_SPOT__020__M__1": "Ah, çok yüksek. Hadi tırmanacak bir şey bulalım!",
"VO__AMICIA__CH08__CHATTER__COMPASS_INTERACT__010__M__1": "İhtiyar ablanla biraz vakit geçirmeye var mısın?",
"VO__AMICIA__CH08__CHATTER__COMPASS_INTERACT__030__M__1": "Muhtemelen aletler... Etrafta olabilir. Ya da ona sorabiliriz.",
"VO__AMICIA__CH08__CHATTER__DISCOVER_HOLD_ALONE__010__M__1": "Vay... Aşağıda gerçekten epey hazinesi var.",
"VO__AMICIA__CH08__CHATTER__DISTRACT_01__010__M__1": "Hadi, şimdi! Sipere!",
"VO__AMICIA__CH08__CHATTER__DISTRACT_02__010__M__1": "Hadi, hadi, hadi!",
"VO__AMICIA__CH08__CHATTER__DISTRACT_03__020__M__1": "Ona güven...",
"VO__AMICIA__CH08__CHATTER__DISTRACT_05__020__M__1": "Zaten buradan çıkıyoruz.",
"VO__AMICIA__CH08__CHATTER__DISTRACT_06__010__M__1": "Ha! Lanet hayvan!",
"VO__AMICIA__CH08__CHATTER__DISTRACT_07__010__M__1": "Git buradan!",
"VO__AMICIA__CH08__CHATTER__DISTRACT_08__010__M__1": "Çok yakın...",
"VO__AMICIA__CH08__CHATTER__DOOR_SAFE__010__M__1": "Öf, çok yakındı... Ama başardık.",
"VO__AMICIA__CH08__CHATTER__DOWN_STAIRS_AFTER__010__M__1": "Ada hâlâ görünüyor mu?",
"VO__AMICIA__CH08__CHATTER__DOWN_STAIRS_AFTER__030__M__1": "Gerçekten öğretti!",
"VO__AMICIA__CH08__CHATTER__DOWN_STAIRS_BEFORE__010__M__1": "Hey, denizci! Hâlâ görevinin başında! Bildirecek bir şey var mı? Bir ada belki?",
"VO__AMICIA__CH08__CHATTER__DOWN_STAIRS_BEFORE__030__M__1": "Bu harika...",
"VO__AMICIA__CH08__CHATTER__ENTER_CABIN__010__M__1": "Uyumak çok güzeldi...",
"VO__AMICIA__CH08__CHATTER__ENTRANCE__040__M__1": "Çok güzel, evet. Ama şimdi seni buraya çağıran her ne ise onu bulmamız gerek...",
"VO__AMICIA__CH08__CHATTER__ENTRANCE__070__M__1": "Evet!",
"VO__AMICIA__CH08__CHATTER__ENTRANCE_ARNAUD__020__M__1": "Pekâlâ, yani, ee... biraz tuhaf, ama... Şey, devam et, Hugo...",
"VO__AMICIA__CH08__CHATTER__ENTRANCE_ARNAUD__050__M__1": "Pazarda sorabiliriz! Hadi!",
"VO__AMICIA__CH08__CHATTER__FABRICS_STAND__010__M__1": "Merhaba efendim. Acaba...",
"VO__AMICIA__CH08__CHATTER__FABRICS_STAND__060__M__1": "Şey, teşekkürler efendim.",
"VO__AMICIA__CH08__CHATTER__FABRICS_STAND__100__M__1": "Gerisine bakalım.",
"VO__AMICIA__CH08__CHATTER__FALCON_PROGRESS_1__030__M__1": "Ama aptal... Yanımda kal yeter, bir şey olmaz.",
"VO__AMICIA__CH08__CHATTER__FALCON_PROGRESS_2__010__M__1": "Çok hızlı. Bir hata ve işimiz biter.",
"VO__AMICIA__CH08__CHATTER__FALCON_PROGRESS_3__020__M__1": "Değil. Kuşunu bulacağız.",
"VO__AMICIA__CH08__CHATTER__FALCON_PROGRESS_04__010__M__1": "Çok uzun sürüyor... Arnaud, Kont'a bir şey yaptıysan...",
"VO__AMICIA__CH08__CHATTER__FALCON_PROGRESS_5__010__M__1": "Acele yok... Dikkat... Dikkat...",
"VO__AMICIA__CH08__CHATTER__FALCON_PROGRESS_6__010__M__1": "Lanet kuş...",
"VO__AMICIA__CH08__CHATTER__FALCON_PROGRESS_7__010__M__1": "Neredeyse vardık... Neredeyse...",
"VO__AMICIA__CH08__CHATTER__FALCONEER__020__M__1": "Bir şahin! Öldürmek için eğitilmiş...",
"VO__AMICIA__CH08__CHATTER__FALCONEER__040__M__1": "Çok hızlı... Ben nişan almadan beni yakalar.",
"VO__AMICIA__CH08__CHATTER__FALCONEER__050__M__1": "Şu şahini oyalamamız gerek... Onu uzaklaştırmaya çalışacağım... Saldırdığında siperden sipere geçeceğiz! Hazır ol!",
"VO__AMICIA__CH08__CHATTER__FIRST_SHOT_FAIL__010__M__1": "Ah, lanet...",
"VO__AMICIA__CH08__CHATTER__FIRST_SHOT_SUCCESS__010__M__1": "Evet!",
"VO__AMICIA__CH08__CHATTER__FIRST_SHOT_SUCCESS__030__M__1": "Arnaud...",
"VO__AMICIA__CH08__CHATTER__FISHERMAN_EXIT__030__M__1": "Sabırlı ol, Hugo...",
"VO__AMICIA__CH08__CHATTER__FISHERMAN_STAND__010__M__1": "Merhaba!",
"VO__AMICIA__CH08__CHATTER__FISHERMAN_STAND__030__M__1": "Acaba... özel kuşlar bulabileceğimiz bir sahil biliyor musunuz?",
"VO__AMICIA__CH08__CHATTER__FISHERMAN_STAND__080__M__1": "Ha, sizinki de...",
"VO__AMICIA__CH08__CHATTER__FLOWERS_EXIT__020__M__1": "Tabii, hadi başka bir yerde ortalığı birbirine katalım...",
"VO__AMICIA__CH08__CHATTER__FLOWERS_EXIT__040__M__1": "Gerçekten neden acaba...",
"VO__AMICIA__CH08__CHATTER__GAME_AIM__020__M__1": "Lütfen, odaklanmaya çalışıyorum...",
"VO__AMICIA__CH08__CHATTER__GAME_END_NO_PLAY__020__M__1": "Sonra geri geliriz, tamam mı? Yoksa şenlikleri kaçırabiliriz.",
"VO__AMICIA__CH08__CHATTER__GAME_FULL_WIN__020__M__1": "Teşekkürler!",
"VO__AMICIA__CH08__CHATTER__GAME_FULL_WIN__050__M__1": "Gerisine bakmaya gidelim.",
"VO__AMICIA__CH08__CHATTER__GAME_LOSE__020__M__1": "Yine de teşekkürler!",
"VO__AMICIA__CH08__CHATTER__GAME_LOSE__050__M__1": "Belki onu senin suratında çalışırım.",
"VO__AMICIA__CH08__CHATTER__GAME_MEDIUM_WIN__015__M__1": "Teşekkürler.",
"VO__AMICIA__CH08__CHATTER__GAME_MEDIUM_WIN__040__M__1": "Neyse, gidip gerisine bakalım!",
"VO__AMICIA__CH08__CHATTER__GARDENS_FOLLOWING__030__M__1": "Gel, Hugo.",
"VO__AMICIA__CH08__CHATTER__GARDENS_PARENTS__040__M__1": "Ee... Hugo...",
"VO__AMICIA__CH08__CHATTER__GARDENS_PRIDE_INTRO__020__M__1": "Muhteşem...",
"VO__AMICIA__CH08__CHATTER__GARDENS_TALK_FLOWERS__070__M__1": "Çok teşekkür ederim. Nazik ve doğru sözlerdi.",
"VO__AMICIA__CH08__CHATTER__GATE_OPEN__020__M__1": "Hadi şu arabayı yerine koyalım!",
"VO__AMICIA__CH08__CHATTER__GO_PROCESSION__040__M__1": "Tabii, kulağa hoş geliyor.",
"VO__AMICIA__CH08__CHATTER__GOAT_CORRIDOR__010__M__1": "Şurada ne var?",
"VO__AMICIA__CH08__CHATTER__GOAT_DENIED__010__M__1": "Gel Hugo.",
"VO__AMICIA__CH08__CHATTER__GOAT_DENIED__030__M__1": "Daha keşfedecek çok şeyimiz var.",
"VO__AMICIA__CH08__CHATTER__GUEST__014__M__1": "Affedersiniz...",
"VO__AMICIA__CH08__CHATTER__GUEST__020__M__1": "Tabii.",
"VO__AMICIA__CH08__CHATTER__GUEST__035__M__1": "Her çocuk dünyanın geleceğini taşır. Tek bir çocuk her şeyi değiştirebilir.",
"VO__AMICIA__CH08__CHATTER__HOW_TO_BACK__010__M__1": "Geri dönecek bir yol lazım. Mümkünse gözden uzak bir yol.",
"VO__AMICIA__CH08__CHATTER__HOW_TO_BACK__030__M__1": "Doğaçlama yaparız. Unutma...",
"VO__AMICIA__CH08__CHATTER__HOW_TO_BACK__050__M__1": "Hem de nasıl iyiyiz.",
"VO__AMICIA__CH08__CHATTER__HUGO_ARNAUD_AFTER__020__M__1": "Öyle de kokuyor...",
"VO__AMICIA__CH08__CHATTER__HUGO_BOAT_STERN__010__M__1": "Deniz... sadece deniz... her yerde...",
"VO__AMICIA__CH08__CHATTER__HUGO_BOAT_STERN__030__M__1": "Çünkü... kesinlikle hiçbir fikrim yok. Ama bu iyi bir şey.",
"VO__AMICIA__CH08__CHATTER__HUGO_CABIN_CROSSBOW__010__M__1": "O arbalet hayatımızı kurtardı. Joseph olmasa başaramazdık...",
"VO__AMICIA__CH08__CHATTER__HUGO_CABIN_CROSSBOW__030__M__1": "Evet. Ona layık olmaya çalışacağım.",
"VO__AMICIA__CH08__CHATTER__HUGO_CABIN_MAP__010__M__1": "Bu Akdeniz.",
"VO__AMICIA__CH08__CHATTER__HUGO_CABIN_MAP__030__M__1": "Ve faydalı! Sophia hangi adanın doğru olduğunu anlamak için onu kullanıyor.",
"VO__AMICIA__CH08__CHATTER__HUGO_CABIN_PRISM__005__M__1": "Hey, şuna bak!",
"VO__AMICIA__CH08__CHATTER__HUGO_CABIN_PRISM__020__M__1": "Hiç sanmıyorum, ama kesinlikle değerli. Ona dokunmayalım.",
"VO__AMICIA__CH08__CHATTER__HUGO_COMPASS_ALONE__020__M__1": "Büyük liderimiz pusula...",
"VO__AMICIA__CH08__CHATTER__HUGO_DECK_END__020__M__1": "Evet! Geldik!",
"VO__AMICIA__CH08__CHATTER__HUGO_DISCOVER_CABIN__020__M__1": "Evet... Aynı anda... onlarca farklı yer gibi kokuyor.",
"VO__AMICIA__CH08__CHATTER__HUGO_DISCOVER_HOLD__020__M__1": "Sanırım öyle. Tabii mürettebatından çalmadıysa...",
"VO__AMICIA__CH08__CHATTER__HUGO_HELLO_SOPHIA__005__M__1": "Hey!",
"VO__AMICIA__CH08__CHATTER__HUGO_HOLD_ASTRO__005__M__1": "İşte bu ilgini çekecek...",
"VO__AMICIA__CH08__CHATTER__HUGO_HOLD_ASTRO__020__M__1": "Bu bir usturlap. Babam bir keresinde, yıldızlarla yolunu bulmak için kullanıldığını söylemişti!",
"VO__AMICIA__CH08__CHATTER__HUGO_HOLD_ASTRO__040__M__1": "Belki geceleyin, bakarız.",
"VO__AMICIA__CH08__CHATTER__HUGO_HOLD_COMPASS__010__M__1": "Hey, bak, bir pusula!",
"VO__AMICIA__CH08__CHATTER__HUGO_HOLD_COMPASS__030__M__1": "Evet, ama dikkatli ol.",
"VO__AMICIA__CH08__CHATTER__HUGO_HOLD_COMPASS__050__M__1": "O iğne her zaman kuzeyin nerede olduğunu gösterir!",
"VO__AMICIA__CH08__CHATTER__HUGO_HOLD_COMPASS__070__M__1": "Şey, o zaman kımıldamayı kes.",
"VO__AMICIA__CH08__CHATTER__HUGO_HOLD_COMPASS__090__M__1": "Tam gittiğimiz yön!",
"VO__AMICIA__CH08__CHATTER__HUGO_HOLD_COMPASS__110__M__1": "Evet, ama kırma! Tabii Sophia'yla yüzleşmek istemiyorsan...",
"VO__AMICIA__CH08__CHATTER__HUGO_INTERACT_ARNAUD__005__M__1": "Selam...",
"VO__AMICIA__CH08__CHATTER__HUGO_INTERACT_ARNAUD__070__M__1": "İşte bu tam biziz!",
"VO__AMICIA__CH08__CHATTER__HUGO_INTERACT_ARNAUD__080__M__1": "Hadi, Hugo.",
"VO__AMICIA__CH08__CHATTER__HUGO_INTERACT_SOPHIA__005__M__1": "Görünüşe göre birinin bir sorusu var...",
"VO__AMICIA__CH08__CHATTER__HUGO_INTERACT_SOPHIA__060__M__1": "Bazı aletlerine bir göz atmamızın sakıncası var mı, Sophia?",
"VO__AMICIA__CH08__CHATTER__HUGO_LADDER_INTERACT__010__M__1": "Ambara!",
"VO__AMICIA__CH08__CHATTER__LEFT_DOOR_TRY__010__M__1": "Sanırım arkada bir araba var...",
"VO__AMICIA__CH08__CHATTER__LEFT_DOOR_TRY__020__M__1": "Kilitli! Ha!...",
"VO__AMICIA__CH08__CHATTER__MAID_TALK__040__M__1": "Hayır... sembolik!",
"VO__AMICIA__CH08__CHATTER__MARKET_CRIER__040__M__1": "Demek devam ediyor...",
"VO__AMICIA__CH08__CHATTER__MARKET_CRIER__060__M__1": "O zaman hepsini görmemiz gerekecek!",
"VO__AMICIA__CH08__CHATTER__MARKET_ENTRANCE__020__M__1": "Ne çok renk... ve koku...",
"VO__AMICIA__CH08__CHATTER__MARKET_GOAT_AFTERMEMORY__010__M__1": "İtiraf etmeliyim, beni de biraz ürküttü.",
"VO__AMICIA__CH08__CHATTER__MARKET_GOAT_AFTERMEMORY__030__M__1": "Savaşa melemeni duymak için sabırsızlanıyorum...",
"VO__AMICIA__CH08__CHATTER__MARKET_GOAT_CALL__005__M__1": "Merhaba demek ister misin?",
"VO__AMICIA__CH08__CHATTER__MARKET_GOAT_MEMORY__010__M__1": "Devam et...",
"VO__AMICIA__CH08__CHATTER__MARKET_GOAT_MEMORY__015__M__1": "Korkma.",
"VO__AMICIA__CH08__CHATTER__MARKET_GOAT_MEMORY__090__M__1": "İyi misin?",
"VO__AMICIA__CH08__CHATTER__MARKET_GOAT_MEMORY__120__M__1": "Buna meleme denir. Böyle konuşurlar.",
"VO__AMICIA__CH08__CHATTER__MARKET_GOAT_MEMORY__140__M__1": "Sadece korktun, o kadar. Hadi gidelim. Teşekkürler efendim!",
"VO__AMICIA__CH08__CHATTER__MARKET_GOAT_TEETH__010__M__1": "Keçilerin ön dişi olmadığını biliyor muydun?",
"VO__AMICIA__CH08__CHATTER__MARKET_SPICES_CALL__030__M__1": "Evet. Soracağım.",
"VO__AMICIA__CH08__CHATTER__PALACE__040__M__1": "Bu... İnanılmaz!",
"VO__AMICIA__CH08__CHATTER__PRAY__015__M__1": "Tabii... Hugo?",
"VO__AMICIA__CH08__CHATTER__PRAY__050__M__1": "...çok parlak.",
"VO__AMICIA__CH08__CHATTER__PRAY__070__M__1": "Ee, pardon... Anne. Babamız için... dua etmek üzere... biraz vakit ayırabilir miyiz? Hugo?",
"VO__AMICIA__CH08__CHATTER__PROCESSION_ABOVE__020__M__1": "Sakin ol, onlara yetişiriz.",
"VO__AMICIA__CH08__CHATTER__PROCESSION_ARNAUDBUSINESS__010__M__1": "Bu Köz Çocuğu da kim ki?",
"VO__AMICIA__CH08__CHATTER__PROCESSION_ARNAUDBUSINESS__050__M__1": "Huzurlu biri.",
"VO__AMICIA__CH08__CHATTER__PROCESSION_DANCE__010__M__1": "Görüyorum! Bunu dans etmeyi biliyor musun, Arnaud?",
"VO__AMICIA__CH08__CHATTER__PROCESSION_DANCE__012__M__1": "Hiç belli olmaz...",
"VO__AMICIA__CH08__CHATTER__PROCESSION_FAR__020__M__1": "Yakın...",
"VO__AMICIA__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__010__M__1": "Tam zamanında geldik!",
"VO__AMICIA__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__090__M__1": "Hugo...",
"VO__AMICIA__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__115__M__1": "Aman Tanrım...",
"VO__AMICIA__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__130__M__1": "Bunun için özür dilerim...",
"VO__AMICIA__CH08__CHATTER__PROCESSION_LOOK_AT__010__M__1": "Buradalar! Birazdan başlayacaklar.",
"VO__AMICIA__CH08__CHATTER__PROCESSION_LOOK_AT__060__M__1": "Evet, onlara ulaşmaya çalışalım!",
"VO__AMICIA__CH08__CHATTER__PROCESSION_SPOT_CALL__010__M__1": "İyi bir yer gibi görünüyor, değil mi?",
"VO__AMICIA__CH08__CHATTER__PROCESSION_WATERWHEEL__020__M__1": "Hepsi öyle... rüya gibi, evet...",
"VO__AMICIA__CH08__CHATTER__PROCESSION_WATERWHEEL__040__M__1": "Ah, karamsarlaşma.",
"VO__AMICIA__CH08__CHATTER__PUSHING_CART__010__M__1": "Bu arada, Arnaud Kont'a neden saldırdı?",
"VO__AMICIA__CH08__CHATTER__PUSHING_CART__030__M__1": "Önemi yok. Kont'a canlı lazım yoksa biz de zindana atılırız.",
"VO__AMICIA__CH08__CHATTER__REACHING_DOOR__010__M__1": "Evet! Geldik!",
"VO__AMICIA__CH08__CHATTER__REACHING_SQUARE__050__M__1": "Bir kalabalık!",
"VO__AMICIA__CH08__CHATTER__REACHING_TOP__010__M__1": "Güzel. Şimdi dikkat.",
"VO__AMICIA__CH08__CHATTER__REINFORCEMENT_COUNT__030__M__1": "Onları takip etmeye çalışalım!",
"VO__AMICIA__CH08__CHATTER__RIGHT_DOOR_TRY__010__M__1": "Bu kapı... Meydan tam arkasında olmalı!",
"VO__AMICIA__CH08__CHATTER__RIGHT_DOOR_TRY__020__M__1": "Kilitli... Tabii ki...",
"VO__AMICIA__CH08__CHATTER__RUN__020__M__1": "Koş, Hugo!",
"VO__AMICIA__CH08__CHATTER__RUN__035__M__1": "Canı cehenneme!",
"VO__AMICIA__CH08__CHATTER__RUN__037__M__1": "Çabuk!",
"VO__AMICIA__CH08__CHATTER__RUN__050__M__1": "Hayır... hayır!",
"VO__AMICIA__CH08__CHATTER__RUN__070__M__1": "Buradan!",
"VO__AMICIA__CH08__CHATTER__RUN_ADD__010__M__1": "Lanet olsun...",
"VO__AMICIA__CH08__CHATTER__SAIL_INTERACT__010__M__1": "Tuttum!",
"VO__AMICIA__CH08__CHATTER__SAIL_PULL_DONE__010__M__1": "Benim tarafım tamam! Arnaud?",
"VO__AMICIA__CH08__CHATTER__SAIL_PULLING__010__M__1": "Ben... buna... bayılıyorum!",
"VO__AMICIA__CH08__CHATTER__SEARCHING_FOR_ARNAUD__010__M__1": "Şimdi nerede o lanet Arnaud?",
"VO__AMICIA__CH08__CHATTER__SEARCHING_FOR_ARNAUD__030__M__1": "Evet... Evet! Çabuk!",
"VO__AMICIA__CH08__CHATTER__SOPHIA_BOAT_FAR__010__M__1": "Bak, teknemizi görebiliyorsun!",
"VO__AMICIA__CH08__CHATTER__SOPHIA_BOAT_FAR__040__M__1": "Gel, yoksa şarkıcılarımızı kaçıracağız!",
"VO__AMICIA__CH08__CHATTER__SPICES_EXIT__010__M__1": "Gölet yok... belki kuşlar...",
"VO__AMICIA__CH08__CHATTER__SPICES_STAND__005__M__1": "Merhaba efendim.",
"VO__AMICIA__CH08__CHATTER__SPICES_STAND__020__M__1": "Belki sonra! Bize... şifalı özellikleri olan bir su göletinden bahsettiler. Nerede olduğunu biliyor musunuz?",
"VO__AMICIA__CH08__CHATTER__SPICES_STAND__040__M__1": "Ah, bilmek güzel!",
"VO__AMICIA__CH08__CHATTER__SPICES_STAND__070__M__1": "Şey, vakit ayırdığınız için teşekkürler!",
"VO__AMICIA__CH08__CHATTER__STABLE__010__M__1": "Bir ahırdayız. Bir şey olmalı.",
"VO__AMICIA__CH08__CHATTER__START__010__M__1": "Deniz çok sakin... Ufuktan başka bir şey yok... Tadını çıkar...",
"VO__AMICIA__CH08__CHATTER__STATUE_REVEAL__020__M__1": "Dur...",
"VO__AMICIA__CH08__CHATTER__STREET_COUNT_ARMY__010__M__1": "Buradaki Kont'un ordusundan endişelenmeli miyiz? Epey sakin görünüyorlar.",
"VO__AMICIA__CH08__CHATTER__STREET_COUNT_ARMY__030__M__1": "Güzel.",
"VO__AMICIA__CH08__CHATTER__THEATER_FEATHER_FALCON__010__M__1": "İşte, biraz tüy! Bu koyu renk...",
"VO__AMICIA__CH08__CHATTER__THEATER_FEATHER_FALCON__030__M__1": "Bu sana yakışır. Al.",
"VO__AMICIA__CH08__CHATTER__THEATER_FEATHER_FALCON__060__M__1": "Amma da yırtıcısın...",
"VO__AMICIA__CH08__CHATTER__THEATER_INTERACT__005__M__1": "İyi günler!",
"VO__AMICIA__CH08__CHATTER__THEATER_INTERACT__020__M__1": "Daha yeni geldik ve... bir... sahil duyduk? Çok uzakta olmayan bir göletle?",
"VO__AMICIA__CH08__CHATTER__THEATER_INTERACT__060__M__1": "Yine de teşekkürler!",
"VO__AMICIA__CH08__CHATTER__THEATER_LEAVE_INTERACT__030__M__1": "Tekrar sorarız.",
"VO__AMICIA__CH08__CHATTER__THEATER_SHADE__010__M__1": "Pekâlâ. Buradan birine sormayı deneyelim...",
"VO__AMICIA__CH08__CHATTER__THROUGH_HOLE__010__M__1": "Çok dikkatli ol...",
"VO__AMICIA__CH08__CHATTER__THROUGH_HOLE__050__M__1": "Hugo?",
"VO__AMICIA__CH08__CHATTER__UP_GAME_FAR__020__M__1": "Bir bakalım...",
"VO__AMICIA__CH08__CHATTER__UP_GAME_START__003__M__1": "İyi günler! Oynayabilir miyiz?",
"VO__AMICIA__CH08__CHATTER__UP_GAME_START__010__M__1": "Pekâlâ, bakalım nasıl yapacağım!",
"VO__AMICIA__CH08__CHATTER__WRONGWAY_BASIN__020__M__1": "Evet, geri dönelim... Burası harika...",
"VO__AMICIA__CH08__CHATTER__WRONGWAY_BASIN__040__M__1": "Evet, geliyoruz, pardon!",
"VO__AMICIA__CH08__RTC__349_SOPHIA__010__M__1": "Bunu kullanmak harika olmalı.",
"VO__AMICIA__CH08__RTC__349_SOPHIA__070__M__1": "Bu... harika...",
"VO__AMICIA__CH08__RTC__349_SOPHIA__090__M__1": "Bizi getirdiğin için... teşekkürler.",
"VO__AMICIA__CH08__RTC__349_SOPHIA__110__M__1": "Ah...",
"VO__AMICIA__CH08__RTC__349_SOPHIA__140__M__1": "Ah, görev çağırıyor, üzgünüm...",
"VO__AMICIA__CH08__RTC__349_SOPHIA__151__M__1": "Teşekkürler.",
"VO__AMICIA__CH08__RTC__350_EARTH__040__M__1": "Orada her ne varsa, onu birlikte bulacağız.",
"VO__AMICIA__CH08__RTC__350_EARTH__050__M__1": "Ada kâşifleri!",
"VO__AMICIA__CH08__RTC__350_EARTH__070__M__1": "Ne? Neden bahsediyorsun?",
"VO__AMICIA__CH08__RTC__350_EARTH__090__M__1": "Tanrım... Hayır. Hugo, çok üzgünüm. Bu olmayacak.",
"VO__AMICIA__CH08__RTC__350_EARTH__140__M__1": "Evet, tabii...",
"VO__AMICIA__CH08__RTC__350_EARTH__150__M__1": "Burada seninle olduğum için mutluyum.",
"VO__AMICIA__CH08__RTC__360_HARBOR__070__M__1": "Pekâlâ. Hava aydınlıkken bir tur atarız. Ve uyuyacak bir yer buluruz.",
"VO__AMICIA__CH08__RTC__360_HARBOR__090__M__1": "Anlıyorum.",
"VO__AMICIA__CH08__RTC__360_HARBOR__170__M__1": "Güle güle!",
"VO__AMICIA__CH08__RTC__360_HARBOR__180__M__1": "Şey, bu epey iyi bir başlangıç, değil mi?",
"VO__AMICIA__CH08__RTC__360_HARBOR__200__M__1": "Başarılı olmamız için dua et.",
"VO__AMICIA__CH08__RTC__360_HARBOR__210__M__1": "Hadi gel, Majesteleri!",
"VO__AMICIA__CH08__RTC__370_BASTARD__090__M__1": "Fareler...",
"VO__AMICIA__CH08__RTC__370_BASTARD__110__M__1": "Hey! Ne yapıyorsun?",
"VO__AMICIA__CH08__RTC__370_BASTARD__140__M__1": "Dur! Ne? Anlaşman BU muydu?",
"VO__AMICIA__CH08__RTC__370_BASTARD__150__M__1": "Senin için Kont'u öldürsün diye mi beni kurtardın?",
"VO__AMICIA__CH08__RTC__370_BASTARD__170__M__1": "HAYIR! Bir çocuğu kullanıp buna anlaşma diyemezsin, Arnaud! Bunca yolu ONUN için geldik! Bunu MAHVETMEYECEKSİN!",
"VO__AMICIA__CH08__RTC__370_BASTARD__190__M__1": "Hayır! Arnaud!",
"VO__AMICIA__CH08__RTC__370_BASTARD__260__M__1": "Hayır... HAYIR!",
"VO__AMICIA__CH08__RTC__370_BASTARD__270__M__1": "Bu bizim kavgamız değil! Koş!",
"VO__AMICIA__CH08__RTC__375_STOPPING_ARNAUD__010__M__1": "Bunu öngörmeliydim!",
"VO__AMICIA__CH08__RTC__375_STOPPING_ARNAUD__020__M__1": "İşte bu yüzden insanlara güvenemezsin, Hugo...",
"VO__AMICIA__CH08__RTC__375_STOPPING_ARNAUD__060__M__1": "Geri dönüyoruz.",
"VO__AMICIA__CH08__RTC__375_STOPPING_ARNAUD__080__M__1": "Hayır. İşler her zaman güzel olmaz, ama onları değiştirebilirsin.",
"VO__AMICIA__CH08__RTC__375_STOPPING_ARNAUD__100__M__1": "Her zaman yaptığımız gibi. Dövüşürüz. Arnaud daha çok zarar vermeden onu durdururuz.",
"VO__AMICIA__CH08__RTC__375_STOPPING_ARNAUD__110__M__1": "Rüyanı kurtarırız.",
"VO__AMICIA__CH08__RTC__380_COUNT_AND_COUNTESS__030__M__1": "Bunu kendin yaptın!",
"VO__AMICIA__CH08__RTC__380_COUNT_AND_COUNTESS__050__M__1": "Hayır! Durun...",
"VO__AMICIA__CH08__RTC__380_COUNT_AND_COUNTESS__140__M__1": "Bir tekneyi paylaştık ve yolda sohbet edecek vaktimiz oldu ama sizin peşinizde olduğunu bilmiyordum, efendim.",
"VO__AMICIA__CH08__RTC__380_COUNT_AND_COUNTESS__160__M__1": "Amicia. Ve bu da kardeşim Hugo. Biraz korkuyor.",
"VO__AMICIA__CH08__RTC__380_COUNT_AND_COUNTESS__180__M__1": "Emin misiniz? Yani...",
"VO__AMICIA__CH08__RTC__381_COUNT_AND_COUNTESS__010__M__1": "Hugo, gel!",
"VO__AMICIA__CH08__RTC__390_COUNTESS__020__M__1": "Bu fazla...",
"VO__AMICIA__CH08__RTC__390_COUNTESS__050__M__1": "Şşş...",
"VO__AMICIA__CH08__RTC__390_COUNTESS__080__M__1": "Hugo!...",
"VO__AMICIA__CH08__RTC__390_COUNTESS__120__M__1": "Teşekkürler.",
"VO__ARNAUD__CH08__CHATTER__ABOUT_PROCESSION__020__M__1": "Ben de bir ejderha-adam görmek isterdim...",
"VO__ARNAUD__CH08__CHATTER__ALONE_INTERACT_SHIELD__020__M__1": "Evet, bundan fazlası gerekir. İspanya'dan, Burgonya'dan... Guyenne'den sağ çıktı... şey, o sefer zar zor.",
"VO__ARNAUD__CH08__CHATTER__ALONE_INTERACT_SHIELD__040__M__1": "Evet. Koruyamadığı tek sefer.",
"VO__ARNAUD__CH08__CHATTER__ALONE_INTERACT_SHIELD__060__M__1": "Hayır. Armamı paylaştığım biri.",
"VO__ARNAUD__CH08__CHATTER__ALONE_INTERACT_SHIELD__080__M__1": "Bazı hatıralar gitmek istemez, çocuk.",
"VO__ARNAUD__CH08__CHATTER__ALONE_INTERACT_SHIELD_AFTER__010__M__1": "Kardeşine göz kulak olmaya devam et. Bu seni kurtarır.",
"VO__ARNAUD__CH08__CHATTER__ARNAUD_FIGHT__010__M__1": "Kapa çeneni! Seni de adamların gibi öldüreceğim!",
"VO__ARNAUD__CH08__CHATTER__ARNAUD_FIGHT__030__M__1": "Umurumda değil!",
"VO__ARNAUD__CH08__CHATTER__CALL_SAIL__030__M__1": "Git diğer taraftaki halatı çek! Ben kendi tarafımdan biraz gevşetirim!",
"VO__ARNAUD__CH08__CHATTER__ENTRANCE__030__M__1": "...fena değil...",
"VO__ARNAUD__CH08__CHATTER__ENTRANCE_ARNAUD__010__M__1": "Hey, dur, dur... Şu rüyayı duydum, ve, şey... yardım etmek isterim, ama önce ne aradığınızı bilmem lazım.",
"VO__ARNAUD__CH08__CHATTER__ENTRANCE_ARNAUD__040__M__1": "Güzel. Yani kuş, ağaç ve su... Her yerde olabilir. Ama sanırım bir başlangıç!",
"VO__ARNAUD__CH08__CHATTER__FABRICS_STAND__080__M__1": "Boyun kadar ince düşünüyorsun.",
"VO__ARNAUD__CH08__CHATTER__FIRST_SHOT_FAIL__020__M__1": "Ah, bu kötü...",
"VO__ARNAUD__CH08__CHATTER__FIRST_SHOT_SUCCESS__020__M__1": "Seninle gurur duyuyorum!",
"VO__ARNAUD__CH08__CHATTER__FISHERMAN_EXIT__020__M__1": "Şey, martılardan anlıyor.",
"VO__ARNAUD__CH08__CHATTER__FISHERMAN_STAND__043__M__1": "Pek rüyası görülecek bir kuş değil, bahse girerim.",
"VO__ARNAUD__CH08__CHATTER__FISHERMAN_STAND__060__M__1": "Hey!... Teşekkürler efendim!",
"VO__ARNAUD__CH08__CHATTER__GAME_AIM__010__M__1": "Yapamazsan seni sert yargılarım...",
"VO__ARNAUD__CH08__CHATTER__GAME_FULL_WIN__040__M__1": "O taçların hiç şansı yoktu.",
"VO__ARNAUD__CH08__CHATTER__GAME_LOSE__040__M__1": "Sağ elinle sorun mu yaşıyorsun?",
"VO__ARNAUD__CH08__CHATTER__GAME_MEDIUM_WIN__020__M__1": "O da pek iyi değil...",
"VO__ARNAUD__CH08__CHATTER__HUGO_INTERACT_ARNAUD__020__M__1": "İşini görüyor. Hayatımı yeterince kurtardı.",
"VO__ARNAUD__CH08__CHATTER__HUGO_INTERACT_ARNAUD__040__M__1": "Bu bir grifon—yarı aslan, yarı kartal... yani yarı haklısın. Bu benim armamdı. Cesaret ve kurnazlık. İşte ben.",
"VO__ARNAUD__CH08__CHATTER__HUGO_INTERACT_ARNAUD__060__M__1": "İyi bir arma da. Güç, istikrar, bilgelik...",
"VO__ARNAUD__CH08__CHATTER__MARKET_CRIER__050__M__1": "Köy ta yukarıya kadar uzanıyor.",
"VO__ARNAUD__CH08__CHATTER__MARKET_GOAT_AFTERMEMORY__020__M__1": "Bu aslında bir düşmanın aklını karıştırmanın iyi bir yolu olurdu.",
"VO__ARNAUD__CH08__CHATTER__MARKET_GOAT_AFTERMEMORY__040__M__1": "Belki bir dahaki sefere.",
"VO__ARNAUD__CH08__CHATTER__MARKET_GOAT_MEMORY__050__M__1": "Seni seviyor!",
"VO__ARNAUD__CH08__CHATTER__MARKET_GOAT_MEMORY__080__M__1": "İşte! Keçi dilinde \"seni seviyorum\" bu.",
"VO__ARNAUD__CH08__CHATTER__MARKET_GOAT_TEETH__020__M__1": "Tıpkı bazı adamlarım gibi.",
"VO__ARNAUD__CH08__CHATTER__MARKET_SPICES_CALL__020__M__1": "Onlara bunun bir rüya olduğunu söylememelisin. Ve çok fazla kişiye sorma. Hiç belli olmaz.",
"VO__ARNAUD__CH08__CHATTER__PROCESSION_ARNAUDBUSINESS__020__M__1": "Yerel bir tanrı, belli ki. Kıtada Aziz Yahya haftası—Yaz gündönümü, yani muhtemelen bereket ve refahla ilgili.",
"VO__ARNAUD__CH08__CHATTER__PROCESSION_ARNAUDBUSINESS__040__M__1": "O bir tanrı. Pagan bir tanrı.",
"VO__ARNAUD__CH08__CHATTER__PROCESSION_DANCE__011__M__1": "Öyle bir hâlim mi var?",
"VO__ARNAUD__CH08__CHATTER__PROCESSION_DANCE__030__M__1": "Otuz yıl geç kaldın, evlat.",
"VO__ARNAUD__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__150__M__1": "Sen tam bir vahşisin, ufaklık...",
"VO__ARNAUD__CH08__CHATTER__PROCESSION_WATERWHEEL__030__M__1": "Adalar güzel küçük sığınaklar olabilir. Ama kırılgan olanlardan.",
"VO__ARNAUD__CH08__CHATTER__SAIL_PULL_DONE__015__M__1": "Ben de!",
"VO__ARNAUD__CH08__CHATTER__SAME_CROWN_THREE__010__M__1": "Aynısına iki kez vurmaman gerekiyor, biliyorsun değil mi?",
"VO__ARNAUD__CH08__CHATTER__SECOND_SHOT_SUCCESS__020__M__1": "Doğra o taçları!",
"VO__ARNAUD__CH08__CHATTER__SOPHIA_BOAT_FAR__030__M__1": "Gelir. İyi bir bira biranı asla kaçırmaz.",
"VO__ARNAUD__CH08__CHATTER__STREET_COUNT_ARMY__020__M__1": "Farklı kaptan, farklı adamlar, farklı diyar. Sanmıyorum.",
"VO__ARNAUD__CH08__CHATTER__THEATER_FEATHER_FALCON__020__M__1": "Bir yırtıcı kuş derim... Küçük bir tane. Hızlı avcılar, şeytan kadar zeki.",
"VO__ARNAUD__CH08__CHATTER__THEATER_FEATHER_FALCON__040__M__1": "İyi görünüyorsun, ufaklık.",
"VO__ARNAUD__CH08__CHATTER__THEATER_LEAVE_INTERACT__020__M__1": "Rüyalar ruhun masallarıdır, bacaksız. Bu dünyanın değil.",
"VO__ARNAUD__CH08__CHATTER__THIRD_SHOT_FAIL__030__M__1": "Baskıyı kaldıramıyorsun, ha?",
"VO__ARNAUD__CH08__CHATTER__THIRD_SHOT_SUCCESS__020__M__1": "Gerçekten etkileyici.",
"VO__ARNAUD__CH08__HELPER__SAIL_1__010__M__1": "Amicia... Kendi tarafında yardım etsen iyi olur!",
"VO__ARNAUD__CH08__HELPER__SAIL_2__010__M__1": "Hey! Benim tarafım tamam! Şu halatlarda elini taşın altına koyar mısın?!",
"VO__ARNAUD__CH08__RTC__360_HARBOR__030__M__1": "Selam!",
"VO__ARNAUD__CH08__RTC__360_HARBOR__040__M__1": "Pekâlâ millet, gelin!",
"VO__ARNAUD__CH08__RTC__360_HARBOR__130__M__1": "Görünüşe göre yeni bir kralımız var.",
"VO__ARNAUD__CH08__RTC__360_HARBOR__190__M__1": "Kilise bu konuda ne düşünür acaba... Ama başarılı görünüyorlar!",
"VO__ARNAUD__CH08__RTC__370_BASTARD__030__M__1": "Evet...",
"VO__ARNAUD__CH08__RTC__370_BASTARD__070__M__1": "Bu o, gel...",
"VO__ARNAUD__CH08__RTC__370_BASTARD__130__M__1": "Anlaşmamız vardı! Çağır farelerini!",
"VO__ARNAUD__CH08__RTC__370_BASTARD__160__M__1": "Sağ kaldın! Bunun bir bedeli var!",
"VO__ARNAUD__CH08__RTC__370_BASTARD__180__M__1": "Boş ver. Sana ihtiyacım yok.",
"VO__ARNAUD__CH08__RTC__370_BASTARD__210__M__1": "Bu sefer ıskalamayacağım!",
"VO__ARNAUD__CH08__RTC__380_COUNT_AND_COUNTESS__010__M__1": "Hayır! HAYIR!",
"VO__ARNAUD__CH08__RTC__380_COUNT_AND_COUNTESS__020__M__1": "Seni lanet hain!",
"VO__ARNAUD__CH08__RTC__380_COUNT_AND_COUNTESS__100__M__1": "Kaltağını öldüreceğim, Kont! Sevdiğin şeyi kaybetmenin ne demek olduğunu sana öğreteceğim!",
"VO__COUNT__CH08__CHATTER__ARNAUD_FIGHT__020__M__1": "Nasılsa öleceksin! Hem de ne uğruna?! Geçmiş geçmişte kaldı!",
"VO__COUNT__CH08__CHATTER__BANQUETHALL_FRUIT_END__010__M__1": "Peki nerelisiniz?",
"VO__COUNT__CH08__CHATTER__BANQUETHALL_FRUIT_HUGO__020__M__1": "Evet... Aydınlık Günler boyunca, La Cuna'nın tüm halkı tek vücut olur, Köz Çocuğu etrafında birleşir.",
"VO__COUNT__CH08__CHATTER__BANQUETHALL_FRUIT_HUGO__050__M__1": "Tam bir \"bon vivant\"!",
"VO__COUNT__CH08__CHATTER__GARDENS_FOLLOWING__020__M__1": "Elbette, aşkım.",
"VO__COUNT__CH08__CHATTER__GARDENS_HERITAGE_TALK__020__M__1": "Bize, O'nun Annesine ve Babasına.",
"VO__COUNT__CH08__CHATTER__GARDENS_PARENTS__010__M__1": "Böyle uzun bir yolculuk için epey gençsiniz. Ana babanız nerede?",
"VO__COUNT__CH08__CHATTER__GARDENS_PARENTS__030__M__1": "Kim tarafından? Nasıl?!",
"VO__COUNT__CH08__CHATTER__GARDENS_PARENTS__060__M__1": "Hm, beni tanırsın.",
"VO__COUNT__CH08__CHATTER__GARDENS_PRIDE_INTRO__030__M__1": "Nihayet havuzları temizlemişler!",
"VO__COUNT__CH08__CHATTER__GUEST__005__M__1": "Yarın için her şey hazır mı?",
"VO__COUNT__CH08__CHATTER__GUEST__030__M__1": "İtiraf etmeliyim, Çocuk'a bu kadar gönülden saygı göstermenizi... takdir ediyoruz.",
"VO__COUNT__CH08__RTC__370_BASTARD__010__M__1": "Nerede o? Çoktan burada olmalıydı!",
"VO__COUNT__CH08__RTC__370_BASTARD__020__M__1": "Pekâlâ! Hepiniz beni tanırsınız! Söz adamı değilimdir. Rahibeniz Emilie, o... yakında burada olacak!",
"VO__COUNT__CH08__RTC__370_BASTARD__050__M__1": "Bu Aydınlık Günler'i güzel sözleriyle açacak. Bir annenin sözleriyle!",
"VO__COUNT__CH08__RTC__370_BASTARD__060__M__1": "Köz Çocuğu'nun Annesiyle!",
"VO__COUNT__CH08__RTC__370_BASTARD__080__M__1": "Kutsal topraklarını hastalık ve savaş farelerinden koruyan Çocuk'la!",
"VO__COUNT__CH08__RTC__370_BASTARD__195__M__1": "Bu da ne?",
"VO__COUNT__CH08__RTC__370_BASTARD__200__M__1": "Biliyordum!",
"VO__COUNT__CH08__RTC__370_BASTARD__250__M__1": "Onun icabına ben bakarım! Kızı yakalayın!",
"VO__COUNT__CH08__RTC__380_COUNT_AND_COUNTESS__040__M__1": "Demek ordusu bu? Bir kız ve bir oğlan!",
"VO__COUNT__CH08__RTC__380_COUNT_AND_COUNTESS__070__M__1": "Emilie...",
"VO__COUNT__CH08__RTC__380_COUNT_AND_COUNTESS__090__M__1": "Elbette, aşkım.",
"VO__COUNT__CH08__RTC__380_COUNT_AND_COUNTESS__110__M__1": "Sen hep şövalyeliğe bir yüz karasıydın, Arnaud! Ve uzun zamandır başımın belasısın!",
"VO__COUNT__CH08__RTC__380_COUNT_AND_COUNTESS__120__M__1": "Kilitleyin onu, sonra icabına bakarım!",
"VO__COUNT__CH08__RTC__380_COUNT_AND_COUNTESS__130__M__1": "Peki bu canavarı nereden tanıyorsunuz?",
"VO__COUNT__CH08__RTC__380_COUNT_AND_COUNTESS__190__M__1": "Tabii! Emilie haklı. Yardım ettiniz. Hak ediyorsunuz.",
"VO__COUNT__CH08__RTC__390_COUNTESS__030__M__1": "Saçmalık. Siz konuğumuzsunuz. Güzel bir akşam yemeği pişiyor.",
"VO__COUNT__CH08__RTC__390_COUNTESS__090__M__1": "O yargılanacak. Kötülük yapan herkes yargılanır. O da çok kötülük yaptı.",
"VO__COUNT__CH08__RTC__390_COUNTESS__100__M__1": "Ama isterseniz tanıklık etme fırsatınız olacak.",
"VO__COUNT__CH08__RTC__390_COUNTESS__135__M__1": "Leydim.",
"VO__COUNTESS__CH08__CHATTER__BANQUETHALL_FRUIT_END__030__M__1": "Buraya gelmekle doğru yaptınız. Devam edelim. Bu... maceradan sonra yorgun olmalısınız.",
"VO__COUNTESS__CH08__CHATTER__BANQUETHALL_FRUIT_HUGO__010__M__1": "Tüm bunların epey resmî göründüğünü biliyorum, ama lütfen... Burada ben \"ekselansları\" değilim. Ben Anne'yim. Ben kendimim, o yüzden sen de kendin ol!",
"VO__COUNTESS__CH08__CHATTER__BANQUETHALL_FRUIT_HUGO__030__M__1": "Eee?",
"VO__COUNTESS__CH08__CHATTER__BANQUETHALL_FRUIT_HUGO__060__M__1": "Dikkatli ol. Çok besleyiciler.",
"VO__COUNTESS__CH08__CHATTER__BANQUETHALL_FRUIT_OFFER__010__M__1": "Öyle! Ve bu sarayın sadece küçük bir kısmı! Ah, odanıza geçmeden önce biraz hurma ister misin?",
"VO__COUNTESS__CH08__CHATTER__BANQUETHALL_FRUIT_OFFER__050__M__1": "Hadi.",
"VO__COUNTESS__CH08__CHATTER__GARDENS_FOLLOWING__010__M__1": "Size başka bir şey göstereyim. Victor?",
"VO__COUNTESS__CH08__CHATTER__GARDENS_GO_FLOWERS__010__M__1": "Yanıma gel, Hugo.",
"VO__COUNTESS__CH08__CHATTER__GARDENS_HERITAGE_TALK__010__M__1": "Buradaki topraklar güçlüdür. Köz Çocuğu ona can verir. Onu kutlamak için Aydınlık Günler'i yarattık; kehanette söylendiği gibi bize geri dönmesi umuduyla.",
"VO__COUNTESS__CH08__CHATTER__GARDENS_HERITAGE_TALK__030__M__1": "Ve halka.",
"VO__COUNTESS__CH08__CHATTER__GARDENS_PARENTS__050__M__1": "Victor, bu kadar... askerî olma.",
"VO__COUNTESS__CH08__CHATTER__GARDENS_PRIDE_INTRO__010__M__1": "Ve bunlar bahçelerimiz! En sevdiğim kısım!",
"VO__COUNTESS__CH08__CHATTER__GARDENS_PRIDE_INTRO__040__M__1": "Evet. Güzel değiller mi?",
"VO__COUNTESS__CH08__CHATTER__GARDENS_TALK_FLOWERS__010__M__1": "Şu bitkileri görüyor musunuz? Çoğu buralı değil. Ama yine de onları büyütmeyi başardık.",
"VO__COUNTESS__CH08__CHATTER__GARDENS_TALK_FLOWERS__030__M__1": "Bolca sevgi ve özen sayesinde. Biz de tıpkı onlar gibiyiz, biliyor musunuz...",
"VO__COUNTESS__CH08__CHATTER__GARDENS_TALK_FLOWERS__050__M__1": "Ve bize iyi bir toprak, sevgi ve özen lazım. Burada büyümeye devam etmek isterseniz, bu topraklar size açık.",
"VO__COUNTESS__CH08__CHATTER__GARDENS_TALK_FLOWERS__060__M__1": "Ama elbette, kararı abla verir, değil mi Amicia?",
"VO__COUNTESS__CH08__CHATTER__GUEST__010__M__1": "Evet... yeni cübbeler harika görünüyor. Bu... mükemmel olacak.",
"VO__COUNTESS__CH08__CHATTER__GUEST__016__M__1": "Ah... Gidelim mi?",
"VO__COUNTESS__CH08__CHATTER__GUEST__037__M__1": "Bu çok doğru.",
"VO__COUNTESS__CH08__CHATTER__MAID_TALK__010__M__1": "Agnes? Lütfen iki kişilik bir oda hazırla.",
"VO__COUNTESS__CH08__CHATTER__PALACE__010__M__1": "Peki, terasımızı nasıl buldunuz?",
"VO__COUNTESS__CH08__CHATTER__PALACE__030__M__1": "Burası yuva!",
"VO__COUNTESS__CH08__CHATTER__PALACE_GETTINGINSIDE__010__M__1": "Gelin! İçeri buyurun!",
"VO__COUNTESS__CH08__CHATTER__PRAY__010__M__1": "Benimle dua eder misiniz? Kendi yönteminizle yapabilirsiniz.",
"VO__COUNTESS__CH08__CHATTER__PRAY__020__M__1": "Mütevazı bir alev... gecesini aydınlatsın. Ve yükselsin... bir güneş... bir oğul... pırıl pırıl!",
"VO__COUNTESS__CH08__CHATTER__PRAY__060__M__1": "Teşekkürler... Minnettarım. Gidelim mi?",
"VO__COUNTESS__CH08__CHATTER__PRAY_AFTER__010__M__1": "Elbette, anlıyorum. Sizi bekleyeceğim. Bitince gelin.",
"VO__COUNTESS__CH08__CHATTER__ROOM_ARRIVAL__040__M__1": "İşte burası.",
"VO__COUNTESS__CH08__CHATTER__STATUE_INTRO__010__M__1": "Ona bir tanrı olarak değil, uzun zamandır uyuyan çocuğumuz olarak dua ederiz.",
"VO__COUNTESS__CH08__CHATTER__STATUE_INTRO__020__M__1": "Onu sever ve yüceltiriz...",
"VO__COUNTESS__CH08__CHATTER__STATUE_INTRO__030__M__1": "Alevini yeniden canlandırmak için.",
"VO__COUNTESS__CH08__CHATTER__WRONGWAY_BASIN__030__M__1": "Etrafta gezinmek için sonra bolca vaktiniz olacak.",
"VO__COUNTESS__CH08__RTC__380_COUNT_AND_COUNTESS__060__M__1": "Victor! DUR!",
"VO__COUNTESS__CH08__RTC__380_COUNT_AND_COUNTESS__080__M__1": "Kendini kaptırma. Yardım etti. Tehdit değiller.",
"VO__COUNTESS__CH08__RTC__380_COUNT_AND_COUNTESS__125__M__1": "İyi misiniz?",
"VO__COUNTESS__CH08__RTC__380_COUNT_AND_COUNTESS__150__M__1": "Madem haydut değilsiniz... kimsiniz?",
"VO__COUNTESS__CH08__RTC__380_COUNT_AND_COUNTESS__170__M__1": "O zaman korkmayın. Tehlikeden çok korku vardı. Bu günler hayata ve barışa adanmıştır! Akşam yemeğinde konuğumuz olmayı kabul eder misiniz?",
"VO__COUNTESS__CH08__RTC__380_COUNT_AND_COUNTESS__200__M__1": "Bizimle gelin!",
"VO__COUNTESS__CH08__RTC__390_COUNTESS__010__M__1": "Devam et!",
"VO__COUNTESS__CH08__RTC__390_COUNTESS__060__M__1": "Ah! Size yeni kıyafetler bulmamız gerek. Görünüşe göre uzun bir yolculuk yapmışsınız.",
"VO__COUNTESS__CH08__RTC__390_COUNTESS__110__M__1": "Ama bu kadar yeter. Sizi dinlenmeye bırakıyoruz. Yarın La Cuna'nın tadını çıkarın. Aydınlık Günler bunun için en güzel zamandır.",
"VO__COUNTESS__CH08__RTC__390_COUNTESS__140__M__1": "Yataklar harika! Üstlerinde zıplamayı deneyin!",
"VO__HUGO__CH08__CHATTER__ABOUT_PROCESSION__010__M__1": "Umarım bir ejderha-adam olur!",
"VO__HUGO__CH08__CHATTER__ABOUT_SCULPTURE__010__M__1": "Sevgili Baba...",
"VO__HUGO__CH08__CHATTER__ABOUT_SCULPTURE__030__M__1": "Ah... Evet, hissediyorum! Aynı gagaya sahip ve... Sadece biliyorum işte...",
"VO__HUGO__CH08__CHATTER__ABOUT_SCULPTURE__050__M__1": "Biliyorum!",
"VO__HUGO__CH08__CHATTER__ARNAUD_SIGHT__020__M__1": "Onu durdurabilir misin?!",
"VO__HUGO__CH08__CHATTER__BANQUETHALL_ENTERING__010__M__1": "Vaay! Çok büyük!",
"VO__HUGO__CH08__CHATTER__BANQUETHALL_FRUIT_END__040__M__1": "Harika!",
"VO__HUGO__CH08__CHATTER__BANQUETHALL_FRUIT_HUGO__040__M__1": "Bayıldım!",
"VO__HUGO__CH08__CHATTER__BANQUETHALL_FRUIT_OFFER__020__M__1": "Hurma! Bu ne?!",
"VO__HUGO__CH08__CHATTER__BANQUETHALL_FRUIT_OFFER__040__M__1": "Alabilir miyim?!",
"VO__HUGO__CH08__CHATTER__BANQUETHALL_FRUIT_OFFER__070__M__1": "Evet!",
"VO__HUGO__CH08__CHATTER__CLIMB_SPOT__010__M__1": "Yukarı bak! Tırmanıp kapının üstünden geçebiliriz?",
"VO__HUGO__CH08__CHATTER__CLIMB_SPOT__030__M__1": "Evet!",
"VO__HUGO__CH08__CHATTER__COMPASS_INTERACT__020__M__1": "İhtiyar değilsin... Söylesene, Sophia La Cuna'ya giden yolu nereden biliyor?",
"VO__HUGO__CH08__CHATTER__COMPASS_INTERACT__040__M__1": "Evet!",
"VO__HUGO__CH08__CHATTER__DISTRACT_06__020__M__1": "Neden durmuyor?!",
"VO__HUGO__CH08__CHATTER__DISTRACT_07__020__M__1": "Kışt! Kışt!",
"VO__HUGO__CH08__CHATTER__DOOR_SAFE__020__M__1": "O kuş berbattı!",
"VO__HUGO__CH08__CHATTER__DOWN_STAIRS_AFTER__020__M__1": "Ona yaklaşıyoruz! Sophia sana tekne kullanmayı öğretti mi?",
"VO__HUGO__CH08__CHATTER__DOWN_STAIRS_BEFORE__020__M__1": "Henüz değil! Ama çok güzel. Renkler durmadan değişiyor ve kocaman balıklar gördüm! Belki bir yunustu!",
"VO__HUGO__CH08__CHATTER__ENTRANCE__010__M__1": "Rüyamdayız, Amicia! Gördüğüm en güzel yer!",
"VO__HUGO__CH08__CHATTER__ENTRANCE__060__M__1": "Hadi, çabuk!",
"VO__HUGO__CH08__CHATTER__ENTRANCE_ARNAUD__030__M__1": "Evet! Rüyamda bir sahilde uyandım, hastaydım ve korkuyordum, ama büyük bir kuş geldi ve onu takip ettim. Öldüğümü sandım... ama kuş bana beni iyileştiren suyu gösterdi. Ve kocaman bir ağaç da vardı! Her seferinde işte orada uyanıyorum.",
"VO__HUGO__CH08__CHATTER__FABRICS_STAND__020__M__1": "Burada sihirli bir gölet var mı? Kuşlu? Ve ağaçlı?",
"VO__HUGO__CH08__CHATTER__FABRICS_STAND__050__M__1": "Belki bir kuşunuz vardır?",
"VO__HUGO__CH08__CHATTER__FABRICS_STAND__090__M__1": "Ne?",
"VO__HUGO__CH08__CHATTER__FALCON_PROGRESS_1__020__M__1": "O kuş korkunç!",
"VO__HUGO__CH08__CHATTER__FALCON_PROGRESS_3__010__M__1": "Rüyamdaki kuş olamaz... Olamaz...",
"VO__HUGO__CH08__CHATTER__FALCON_PROGRESS_6__020__M__1": "Beni ısırmasını istemiyorum!",
"VO__HUGO__CH08__CHATTER__FALCONEER__010__M__1": "O ne kuşu?!",
"VO__HUGO__CH08__CHATTER__FALCONEER__030__M__1": "Onu durdurabilir misin?!",
"VO__HUGO__CH08__CHATTER__FISHERMAN_EXIT__010__M__1": "Hiçbir şey bilmiyor!",
"VO__HUGO__CH08__CHATTER__FISHERMAN_STAND__050__M__1": "Bu bir martı değil! Gidelim!",
"VO__HUGO__CH08__CHATTER__FLOWERS_EXIT__010__M__1": "Geçit törenini takip edelim!",
"VO__HUGO__CH08__CHATTER__FLOWERS_EXIT__030__M__1": "İnsanları kutsamayı seviyorum!",
"VO__HUGO__CH08__CHATTER__GAME_END_NO_PLAY__010__M__1": "Oynamanı izlemek istiyorum, Amicia!",
"VO__HUGO__CH08__CHATTER__GAME_END_NO_PLAY__030__M__1": "Ah evet! Dansçılar!",
"VO__HUGO__CH08__CHATTER__GAME_FULL_WIN__030__M__1": "Çok iyisin!",
"VO__HUGO__CH08__CHATTER__GAME_LOSE__030__M__1": "Üzülme.",
"VO__HUGO__CH08__CHATTER__GAME_MEDIUM_WIN__030__M__1": "İyi yaptın! Onu dinleme!",
"VO__HUGO__CH08__CHATTER__GARDENS_GO_FLOWERS__020__M__1": "Evet...",
"VO__HUGO__CH08__CHATTER__GARDENS_PARENTS__020__M__1": "Annem bir yerlerde, ama babam öldürüldü.",
"VO__HUGO__CH08__CHATTER__GARDENS_TALK_FLOWERS__020__M__1": "Ve harika görünüyorlar!",
"VO__HUGO__CH08__CHATTER__GARDENS_TALK_FLOWERS__040__M__1": "Biz su içeriz!",
"VO__HUGO__CH08__CHATTER__GATE_OPEN__010__M__1": "Burada!",
"VO__HUGO__CH08__CHATTER__GO_PROCESSION__030__M__1": "Ah! Amicia, biz de gidebilir miyiz?!",
"VO__HUGO__CH08__CHATTER__GOAT_CORRIDOR__020__M__1": "Keçiler!",
"VO__HUGO__CH08__CHATTER__GOAT_DENIED__020__M__1": "Evet!",
"VO__HUGO__CH08__CHATTER__HOW_TO_BACK__020__M__1": "Ya Arnaud öldüyse ya da Kont'u öldürdüyse?",
"VO__HUGO__CH08__CHATTER__HOW_TO_BACK__040__M__1": "Bunda... iyi miyiz?",
"VO__HUGO__CH08__CHATTER__HUGO_ARNAUD_AFTER__010__M__1": "Komik biri. Ayıya benziyor.",
"VO__HUGO__CH08__CHATTER__HUGO_BOAT_STERN__020__M__1": "Nasıl bu kadar çok su olabiliyor?!",
"VO__HUGO__CH08__CHATTER__HUGO_BOAT_STERN__040__M__1": "Evet! Bizi La Cuna'ya götürüyor!",
"VO__HUGO__CH08__CHATTER__HUGO_CABIN_CROSSBOW__020__M__1": "Eminim onun sende olmasına seviniyordur.",
"VO__HUGO__CH08__CHATTER__HUGO_CABIN_MAP__020__M__1": "Çok güzel!",
"VO__HUGO__CH08__CHATTER__HUGO_CABIN_PRISM__010__M__1": "Vay... Bir elmas mı?",
"VO__HUGO__CH08__CHATTER__HUGO_COMPASS_ALONE__010__M__1": "Herkes dinlesin, ben Kaptan de Rune, ve güneye gidiyoruz diyorum!",
"VO__HUGO__CH08__CHATTER__HUGO_COMPASS_ALONE__015__M__1": "Pusula öyle diyor! O yüzden hepiniz pusulayı dinleyin!",
"VO__HUGO__CH08__CHATTER__HUGO_DECK_END__010__M__1": "Hugo ve Amicia güvertede!",
"VO__HUGO__CH08__CHATTER__HUGO_DISCOVER_CABIN__010__M__1": "Tuhaf kokuyor!",
"VO__HUGO__CH08__CHATTER__HUGO_DISCOVER_CABIN__030__M__1": "Ya da... at gibi.",
"VO__HUGO__CH08__CHATTER__HUGO_DISCOVER_HOLD__010__M__1": "Vaay... Bunların hepsi gerçekten onun mu?",
"VO__HUGO__CH08__CHATTER__HUGO_HOLD_ASTRO__010__M__1": "Ah! Bu ne?",
"VO__HUGO__CH08__CHATTER__HUGO_HOLD_ASTRO__030__M__1": "Ah! Şimdi deneyebilir miyiz?",
"VO__HUGO__CH08__CHATTER__HUGO_HOLD_COMPASS__020__M__1": "Tutabilir miyim?",
"VO__HUGO__CH08__CHATTER__HUGO_HOLD_COMPASS__040__M__1": "Ağır...",
"VO__HUGO__CH08__CHATTER__HUGO_HOLD_COMPASS__060__M__1": "Ben kımıldayınca o da kımıldıyor!",
"VO__HUGO__CH08__CHATTER__HUGO_HOLD_COMPASS__080__M__1": "İşte! Ada güneyde, değil mi?",
"VO__HUGO__CH08__CHATTER__HUGO_HOLD_COMPASS__100__M__1": "Oynamak için onu alabilir miyim?",
"VO__HUGO__CH08__CHATTER__HUGO_INTERACT_ARNAUD__010__M__1": "Harika bir kalkan...",
"VO__HUGO__CH08__CHATTER__HUGO_INTERACT_ARNAUD__030__M__1": "Üstündeki kuşu sevdim.",
"VO__HUGO__CH08__CHATTER__HUGO_INTERACT_ARNAUD__050__M__1": "Bizim armamız bir ağaç!",
"VO__HUGO__CH08__CHATTER__HUGO_INTERACT_SOPHIA__010__M__1": "La Cuna'ya giden yolu nereden biliyorsun? Deniz çok büyük!",
"VO__HUGO__CH08__CHATTER__HUGO_INTERACT_SOPHIA__030__M__1": "Ne?! Neredeler?! Bir tane görebilir miyim?!",
"VO__HUGO__CH08__CHATTER__HUGO_INTERACT_SOPHIA__050__M__1": "Ah, evet... Deniz kızları daha kolaymış...",
"VO__HUGO__CH08__CHATTER__HUGO_PROCESSION__010__M__1": "Amicia, çabuk!",
"VO__HUGO__CH08__CHATTER__HUGO_PROCESSION__030__M__1": "Buradalar! Merhabaa!",
"VO__HUGO__CH08__CHATTER__MAID_TALK__030__M__1": "O, onun annesi mi?!",
"VO__HUGO__CH08__CHATTER__MARKET_ENTRANCE__010__M__1": "Ah, harika!",
"VO__HUGO__CH08__CHATTER__MARKET_GOAT_CALL__010__M__1": "Cana yakın mı?",
"VO__HUGO__CH08__CHATTER__MARKET_GOAT_MEMORY__020__M__1": "Adı ne?",
"VO__HUGO__CH08__CHATTER__MARKET_GOAT_MEMORY__040__M__1": "İyi bir keçisin, Lucinda...",
"VO__HUGO__CH08__CHATTER__MARKET_GOAT_MEMORY__060__M__1": "Gerçekten mi?",
"VO__HUGO__CH08__CHATTER__MARKET_GOAT_MEMORY__100__M__1": "Bana bağırdı!",
"VO__HUGO__CH08__CHATTER__MARKET_GOAT_MEMORY__130__M__1": "Hiç hoş değil!",
"VO__HUGO__CH08__CHATTER__MARKET_GOAT_MEMORY__160__M__1": "Güle güle...",
"VO__HUGO__CH08__CHATTER__MARKET_SPICES_CALL__010__M__1": "Amicia... İnsanlara rüyamı sorabilir miyiz?",
"VO__HUGO__CH08__CHATTER__PALACE__020__M__1": "Burası gerçekten senin evin mi?!",
"VO__HUGO__CH08__CHATTER__PRAY__017__M__1": "Ben kuşa dua edeceğim.",
"VO__HUGO__CH08__CHATTER__PRAY__040__M__1": "...pırıl pırıl",
"VO__HUGO__CH08__CHATTER__PRAY__080__M__1": "Evet...",
"VO__HUGO__CH08__CHATTER__PROCESSION_ABOVE__010__M__1": "Yukarıdalar! Çabuk! Çabuk!",
"VO__HUGO__CH08__CHATTER__PROCESSION_ARNAUDBUSINESS__030__M__1": "Sihirli mi?",
"VO__HUGO__CH08__CHATTER__PROCESSION_ARNAUDBUSINESS__060__M__1": "Evet...",
"VO__HUGO__CH08__CHATTER__PROCESSION_DANCE__020__M__1": "Dans edişini görmek isterim!",
"VO__HUGO__CH08__CHATTER__PROCESSION_DANCE__040__M__1": "O zaman hayal ederim!",
"VO__HUGO__CH08__CHATTER__PROCESSION_DANCE_START__010__M__1": "Ah! Dansçılar! Amicia! Dansçılar!",
"VO__HUGO__CH08__CHATTER__PROCESSION_FAR__010__M__1": "İlahiler!",
"VO__HUGO__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__020__M__1": "Vay...",
"VO__HUGO__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__040__M__1": "Onlara biraz mı atayım?",
"VO__HUGO__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__060__M__1": "Böyle mi?",
"VO__HUGO__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__070__M__1": "Çocuk kutsansın!",
"VO__HUGO__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__080__M__1": "Dur, dansçıları da kutsayacağım!",
"VO__HUGO__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__100__M__1": "Herkes kutsansın!",
"VO__HUGO__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__120__M__1": "Tamamdır! Teşekkürler!",
"VO__HUGO__CH08__CHATTER__PROCESSION_LOOK_AT__050__M__1": "Yakından görebilir miyiz?",
"VO__HUGO__CH08__CHATTER__PROCESSION_RESUME_HUGO__010__M__1": "Acele et!",
"VO__HUGO__CH08__CHATTER__PROCESSION_WATERWHEEL__010__M__1": "Bütün bunlar rüyamda yoktu, ama burayı çok seviyorum!",
"VO__HUGO__CH08__CHATTER__PUSHING_CART__020__M__1": "Kalkanının kırık olmasının Kont yüzünden olduğunu söyledi.",
"VO__HUGO__CH08__CHATTER__REACHING_DOOR__020__M__1": "Hadi çıkalım, çabuk!",
"VO__HUGO__CH08__CHATTER__REACHING_SQUARE__060__M__1": "Neler oluyor?!",
"VO__HUGO__CH08__CHATTER__RUN__030__M__1": "Ama Arnaud...",
"VO__HUGO__CH08__CHATTER__SAME_CROWN_THREE__010__M__1": "Amicia, başka birine atmayı dene.",
"VO__HUGO__CH08__CHATTER__SEARCHING_FOR_ARNAUD__020__M__1": "Dinle! Kılıç sesleri!",
"VO__HUGO__CH08__CHATTER__SECOND_SHOT_FAIL__020__M__1": "Yapabilirsin!",
"VO__HUGO__CH08__CHATTER__SECOND_SHOT_SUCCESS__010__M__1": "Evet! Devam et!",
"VO__HUGO__CH08__CHATTER__SOPHIA_BOAT_FAR__020__M__1": "Keşke Sophia burada olsaydı!",
"VO__HUGO__CH08__CHATTER__SPICES_EXIT__020__M__1": "Evet!",
"VO__HUGO__CH08__CHATTER__SPICES_STAND__050__M__1": "Bu adada büyük bir kuş var mı?!",
"VO__HUGO__CH08__CHATTER__STATUE_REVEAL__010__M__1": "Amicia! Taşın üstünde, o kuş!",
"VO__HUGO__CH08__CHATTER__THEATER_FEATHER_FALCON__050__M__1": "Şeytan kadar zeki!",
"VO__HUGO__CH08__CHATTER__THEATER_INTERACT__040__M__1": "Büyük bir ağaç da var!",
"VO__HUGO__CH08__CHATTER__THEATER_LEAVE_INTERACT__010__M__1": "Neden bilmiyorlar?!",
"VO__HUGO__CH08__CHATTER__THIRD_SHOT_FAIL__020__M__1": "Önemi yok!",
"VO__HUGO__CH08__CHATTER__THIRD_SHOT_SUCCESS__010__M__1": "Tam isabet!",
"VO__HUGO__CH08__CHATTER__THROUGH_HOLE__020__M__1": "Merak etme, biliyorum.",
"VO__HUGO__CH08__CHATTER__UP_GAME_FAR__010__M__1": "Ah, bir oyun!",
"VO__HUGO__CH08__CHATTER__UP_GAME_START__020__M__1": "Kazanacaksın!",
"VO__HUGO__CH08__CHATTER__WRONGWAY_BASIN__010__M__1": "Bizi bekliyorlar, Amicia.",
"VO__HUGO__CH08__HELPER__BOAT_HUGO_SOPHIA_DISCOVERY_1__010__M__1": "Eminim aletler yakındadır. Onları görmek için sabırsızlanıyorum!",
"VO__HUGO__CH08__HELPER__BOAT_HUGO_SOPHIA_DISCOVERY_2__010__M__1": "Sophia'nın bazı şeyleri aşağıda, ambarda tuttuklarını söylediğini duydum. Belki aletler oradadır?",
"VO__HUGO__CH08__HELPER__LOCKED_1__010__M__1": "Amicia! Kapının arkasındaki araba! Belki ona ulaşmanın bir yolu vardır...",
"VO__HUGO__CH08__HELPER__LOCKED_2__010__M__1": "Duvarda bir delik var, Amicia! Belki kapıyı açabilirim! Gitmemi ister misin?",
"VO__HUGO__CH08__HELPER__MARKET_NPC_BLOCKING_1__010__M__1": "Görülecek daha çok şey var, Amicia!",
"VO__HUGO__CH08__HELPER__MARKET_NPC_BLOCKING_2__010__M__1": "Hadi, Amicia! Pazar bu taraftan devam ediyor!",
"VO__HUGO__CH08__RTC__349_SOPHIA__130__M__1": "Amicia! Amicia!",
"VO__HUGO__CH08__RTC__350_EARTH__005__M__1": "Amicia, gel!",
"VO__HUGO__CH08__RTC__350_EARTH__010__M__1": "Bak! Orada bir şey var!",
"VO__HUGO__CH08__RTC__350_EARTH__020__M__1": "İşte bu! La Cuna!",
"VO__HUGO__CH08__RTC__350_EARTH__025__M__1": "Tıpkı rüyalarımdaki gibi!",
"VO__HUGO__CH08__RTC__350_EARTH__030__M__1": "Teşekkürler!",
"VO__HUGO__CH08__RTC__350_EARTH__060__M__1": "Evet! Biliyor musun... Ölsem önemli değil...",
"VO__HUGO__CH08__RTC__350_EARTH__080__M__1": "Magister Vaudin öleceğimi söyledi.",
"VO__HUGO__CH08__RTC__350_EARTH__100__M__1": "Üzülme. Burada olduğum için mutluyum. Bu tekne en iyisi! Ve Sophia'yı seviyorum. Sen sevmesen de Arnaud'yu da.",
"VO__HUGO__CH08__RTC__360_HARBOR__010__M__1": "Vuuuh! Çıkartmaya hazırlanın!",
"VO__HUGO__CH08__RTC__360_HARBOR__050__M__1": "Sıra bende!",
"VO__HUGO__CH08__RTC__360_HARBOR__120__M__1": "Teşekkürler!",
"VO__HUGO__CH08__RTC__360_HARBOR__135__M__1": "İyi Kral Hugo!",
"VO__HUGO__CH08__RTC__360_HARBOR__160__M__1": "Teşekkürler!",
"VO__HUGO__CH08__RTC__370_BASTARD__040__M__1": "Ne?...",
"VO__HUGO__CH08__RTC__370_BASTARD__100__M__1": "Hayır, dur!",
"VO__HUGO__CH08__RTC__370_BASTARD__120__M__1": "Çünkü o Kont, Amicia!",
"VO__HUGO__CH08__RTC__375_STOPPING_ARNAUD__030__M__1": "Hiçbir şey güzel kalmıyor...",
"VO__HUGO__CH08__RTC__375_STOPPING_ARNAUD__040__M__1": "Her zaman kötüye gidiyor! Her zaman!",
"VO__HUGO__CH08__RTC__375_STOPPING_ARNAUD__050__M__1": "Neden?...",
"VO__HUGO__CH08__RTC__375_STOPPING_ARNAUD__070__M__1": "Çok geç...",
"VO__HUGO__CH08__RTC__375_STOPPING_ARNAUD__090__M__1": "Nasıl?...",
"VO__HUGO__CH08__RTC__380_COUNT_AND_COUNTESS__005__M__1": "Ne yapacağız?",
"VO__HUGO__CH08__RTC__390_COUNTESS__040__M__1": "Gerçek bir akşam yemeği, Amicia!",
"VO__HUGO__CH08__RTC__390_COUNTESS__070__M__1": "Arnaud'yu öldürecek misiniz?",
"VO__HUGO__CH08__RTC__390_COUNTESS__130__M__1": "Teşekkürler!",
"VO__HUGO__CH08__RTC__390_COUNTESS__150__M__1": "Evet!",
"VO__ISLANDER_F1__CH08__CHATTER__THEATER_BACKGROUND__010__M__1": "Süslemeler için herkese aferin! Ve hâlâ yardım etmek isteyen varsa, bu geceki ziyafet için bir ele ihtiyacımız var!",
"VO__ISLANDER_F1__CH08__CHATTER__THEATER_INTERACT__010__M__1": "Merhaba!",
"VO__ISLANDER_F1__CH08__CHATTER__THEATER_INTERACT__030__M__1": "Hm... Çok özel bir şey bu... Bilen var mı?",
"VO__ISLANDER_F1__CH08__CHATTER__THEATER_INTERACT__050__M__1": "Şey, bir sürü büyük ağacımız var! Yaylada birkaç tane bulursunuz.",
"VO__ISLANDER_F1__CH08__CHATTER__THEATER_INTERACT__070__M__1": "Elbette!",
"VO__ISLANDER_M1__CH08__CHATTER__STAND_FLOWERS_CALL__010__M__1": "Gelin çiçeklerimi görün! Şenlikler için mükemmel!",
"VO__ISLANDER_M1__CH08__CHATTER__STAND_FLOWERS_CALL__020__M__1": "Hâlâ şenliklerde atacak çiçek mi lazım? Çekinmeyin!",
"VO__ISLANDER_M2__CH08__CHATTER__FIRST_SHOT_SUCCESS__040__M__1": "Güzel başlangıç!",
"VO__ISLANDER_M2__CH08__CHATTER__GAME_FULL_WIN__010__M__1": "Şaşırtıcı iş! Umarım bir lütfun işaretidir!",
"VO__ISLANDER_M2__CH08__CHATTER__GAME_LOSE__010__M__1": "Ah, çok yazık! Olur böyle!",
"VO__ISLANDER_M2__CH08__CHATTER__GAME_MEDIUM_WIN__010__M__1": "Şey, fena değil!",
"VO__ISLANDER_M2__CH08__CHATTER__SAME_CROWN_ONCE__010__M__1": "Aynısına iki kez vurmamaya çalış.",
"VO__ISLANDER_M2__CH08__CHATTER__STAND_BUTCHERS_CALL__010__M__1": "Kızarmış domuz hazır! İsteyen var mı?",
"VO__ISLANDER_M2__CH08__CHATTER__STAND_BUTCHERS_CALL__020__M__1": "Tam sevdiğiniz gibi tuzlu! Daha iyi jambon yok!",
"VO__ISLANDER_M2__CH08__CHATTER__UP_GAME_CALL__005__M__1": "Beceri oyunu! Gelin beceriniz deneyin!",
"VO__ISLANDER_M2__CH08__CHATTER__UP_GAME_FAR__030__M__1": "Bedava oynayın! Ve belki Köz Çocuğu'nun dikkatini çekersiniz!",
"VO__ISLANDER_M2__CH08__CHATTER__UP_GAME_START__005__M__1": "Tabii! Basit! Her tacın içinden bir çömlek geçir! Çömleğin bitince oyun biter! Aynı taca asla iki kez atma! Anladın mı?",
"VO__ISLANDER_M3__CH08__CHATTER__STAND_OINTMENTS_CALL__010__M__1": "Zeytinyağı, otlar, sofranız için gereken her şey!",
"VO__ISLANDER_M3__CH08__CHATTER__STAND_OINTMENTS_CALL__020__M__1": "Pomatlar! Çürükleriniz için pomat, bir fiyatına iki!",
"VO__ISLANDER_M3__CH08__CHATTER__STAND_TISSUES_CALL__010__M__1": "Parlak kumaş, Aydınlık Günler'de giymek için mükemmel!",
"VO__ISLANDER_M3__CH08__CHATTER__UNLOADING__020__M__1": "Sonra. Bitkinim.",
"VO__ISLANDER_M4__CH08__CHATTER__ENTRANCE__050__M__1": "Hoş geldiniz! Pazar caddenin hemen yukarısında! Görecek bir sürü şey var!",
"VO__ISLANDER_M4__CH08__CHATTER__STAND_FISHES_CALL__010__M__1": "Balıklar, büyük ve taze! Doğrudan limanımızdan!",
"VO__ISLANDER_M4__CH08__CHATTER__STAND_FISHES_CALL__020__M__1": "Gelin bir bakın... Çipura, levrek, sardalye, her zevke balık var!",
"VO__ISLANDER_M4__CH08__CHATTER__STAND_FRUITS_CALL__010__M__1": "Taze meyveler! Doğrudan Annemizin bahçesinden!",
"VO__PEOPLE_F1__CH08__CHATTER__AUDIENCE_WAITING__020__M__1": "Aylardır prova yaptıklarını biliyorum.",
"VO__PEOPLE_F1__CH08__CHATTER__MARKET_CRIER__020__M__1": "Gerisini görmek için sabırsızlanıyorum!",
"VO__PEOPLE_F1__CH08__CHATTER__REACHING_SQUARE__020__M__1": "Anne kutsansın!",
"VO__PEOPLE_F1__CH08__CHATTER__THEATER_BACKGROUND__040__M__1": "Ben de!",
"VO__PEOPLE_F2__CH08__CHATTER__HUGO_PROCESSION__020__M__1": "Köz Çocuğu kutsansın! Anne kutsansın!",
"VO__PEOPLE_F2__CH08__CHATTER__PROCESSION_DANCE_END__010__M__1": "Bağlılık Yürüyüşü başladı! Geçit töreni geliyor!",
"VO__PEOPLE_F2__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__030__M__1": "Söylesene, onları çiçeklerle kutsamak ister misin?",
"VO__PEOPLE_F2__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__050__M__1": "İşte böyle!",
"VO__PEOPLE_F2__CH08__CHATTER__PROCESSION_FLOWERS_INTERACT__140__M__1": "Ah olma! Yüreğine sadık kaldı! Artık uzun uzun yıllar kutsanmış oldular!",
"VO__PEOPLE_F2__CH08__CHATTER__PROCESSION_LOOK_AT__020__M__1": "Köz Çocuğu için söylüyorum ve onun enerjiye ihtiyacı var!",
"VO__PEOPLE_F2__CH08__CHATTER__REACHING_SQUARE__030__M__1": "Anne konuşmak üzere!",
"VO__PEOPLE_F3__CH08__CHATTER__MARKET_NPC_RESTINPARK__010__M__1": "Yarınki tören muhteşem olacak, canım.",
"VO__PEOPLE_F3__CH08__CHATTER__PROCESSION_FAR__030__M__1": "Lütfen! Ritme sadık kal, tamam mı Lucy? Doğaçlama yok!",
"VO__PEOPLE_F3__CH08__CHATTER__PROCESSION_LOOK_AT__040__M__1": "Pekâlâ, odaklanın lütfen! Birazdan çıkıyoruz!",
"VO__PEOPLE_F4__CH08__CHATTER__MARKET_NPC_BLOCKING__020__M__1": "Sanırım sonuncusundan iki kat fazla tezgâhımız var!",
"VO__PEOPLE_F4__CH08__CHATTER__OLD_LADIES__010__M__1": "Bu yere yaptıkları harika. İnsanların kıtaya göçtüğü günleri hatırlıyor musun?",
"VO__PEOPLE_F4__CH08__CHATTER__OLD_LADIES__030__M__1": "Ama göreceğiz canım, göreceğiz.",
"VO__PEOPLE_F4__CH08__CHATTER__OLD_LADIES__050__M__1": "Doğru, doğru...",
"VO__PEOPLE_F5__CH08__CHATTER__MAID_TALK__020__M__1": "Elbette, Anne.",
"VO__PEOPLE_F5__CH08__RTC__360_HARBOR__100__M__1": "La Cuna'ya hoş geldiniz!",
"VO__PEOPLE_F5__CH08__RTC__360_HARBOR__110__M__1": "Bu senin için yavrum! Varlığınızdan büyük onur duyuyoruz!",
"VO__PEOPLE_F5__CH08__RTC__360_HARBOR__140__M__1": "Doğru! Aydınlık Günler boyunca bütün çocuklar kraldır! Tıpkı adamızı gözeten Köz Çocuğu gibi. Varlığın bir lütuftur, çünkü sen de Onun gibi geleceksin. Çünkü o hepimizi karanlıktan kurtaracak.",
"VO__PEOPLE_F5__CH08__RTC__360_HARBOR__150__M__1": "Lütfen şenliklerin tadını çıkarın.",
"VO__PEOPLE_F6__CH08__CHATTER__OLD_LADIES__020__M__1": "Evet! Bir ara köyde ayakta kalan son kişiler biz olacağız sanmıştım...",
"VO__PEOPLE_F6__CH08__CHATTER__OLD_LADIES__040__M__1": "Senin eau de vie'n sayesinde!",
"VO__PEOPLE_M1__CH08__CHATTER__HUGO_PROCESSION__040__M__1": "Ah, merhaba!",
"VO__PEOPLE_M1__CH08__CHATTER__REACHING_SQUARE__010__M__1": "Anne kutsansın!",
"VO__PEOPLE_M3__CH08__CHATTER__FABRICS_STAND__040__M__1": "Heh... Ben buralı değilim biliyor musunuz, sadece pazar için geliyorum...",
"VO__PEOPLE_M3__CH08__CHATTER__FABRICS_STAND__070__M__1": "Her zaman!",
"VO__PEOPLE_M3__CH08__CHATTER__MARKET_GOAT_CALL__020__M__1": "Elbette öyle.",
"VO__PEOPLE_M3__CH08__CHATTER__MARKET_GOAT_MEMORY__030__M__1": "Lucinda.",
"VO__PEOPLE_M3__CH08__CHATTER__MARKET_GOAT_MEMORY__110__M__1": "O bir keçi, biliyorsun. Onlar böyle yapar.",
"VO__PEOPLE_M3__CH08__CHATTER__MARKET_GOAT_MEMORY__150__M__1": "Her zaman!",
"VO__PEOPLE_M3__CH08__CHATTER__PROCESSION_LOOK_AT__030__M__1": "Ama o kadar da değil!",
"VO__PEOPLE_M3__CH08__CHATTER__THEATER_BACKGROUND__020__M__1": "Gidip yardım edeceğim!",
"VO__PEOPLE_M3__CH08__CHATTER__THEATER_BACKGROUND__033__M__1": "Pardon, gerçekten bilmiyorum.",
"VO__PEOPLE_M3__CH08__CHATTER__UNLOADING__010__M__1": "Daha boşaltmamız gerekiyor mu?",
"VO__PEOPLE_M3__CH08__CHATTER__UNLOADING__030__M__1": "Ben de... Bu yılki pazar çılgınca.",
"VO__PEOPLE_M3__CH08__RTC__360_HARBOR__020__M__1": "Merhaba!",
"VO__PEOPLE_M4__CH08__CHATTER__GO_PROCESSION__020__M__1": "Ha! Onu görmek için sabırsızlanıyorum, gidelim!",
"VO__PEOPLE_M4__CH08__CHATTER__MARKET_CRIER__005__M__1": "Hâlâ geçemiyor muyuz? Çok uzun sürdü!",
"VO__PEOPLE_M4__CH08__CHATTER__MARKET_CRIER__030__M__1": "Biliyorum! Her yıl gitgide daha iyi oluyor!",
"VO__PEOPLE_M4__CH08__CHATTER__SPICES_STAND__010__M__1": "Merhaba! Sizin için ne yapabilirim? Baharat lazım mı?",
"VO__PEOPLE_M4__CH08__CHATTER__SPICES_STAND__030__M__1": "Hiç fikrim yok! Ama Aydınlık Günler'de kutsanmanın bir sürü yolu var!",
"VO__PEOPLE_M4__CH08__CHATTER__SPICES_STAND__060__M__1": "Heh! Şurada burada birkaç tane var! Belki görürsünüz!",
"VO__PEOPLE_M4__CH08__CHATTER__SPICES_STAND__080__M__1": "Rica ederim!",
"VO__PEOPLE_M4__CH08__CHATTER__THEATER_BACKGROUND__030__M__1": "Varım!",
"VO__PEOPLE_M5__CH08__CHATTER__FISHERMAN_STAND__020__M__1": "Merhaba!",
"VO__PEOPLE_M5__CH08__CHATTER__FISHERMAN_STAND__040__M__1": "Ha! Burası bir ada, o yüzden kuşların çoğu martıdır!",
"VO__PEOPLE_M5__CH08__CHATTER__FISHERMAN_STAND__047__M__1": "Ha! Hepsi lanet hırsız, diyorum size!",
"VO__PEOPLE_M5__CH08__CHATTER__FISHERMAN_STAND__070__M__1": "Gününüz aydınlık olsun!",
"VO__PEOPLE_M5__CH08__CHATTER__MARKET_NPC_BLOCKING__010__M__1": "Ah! Bu yılki şenlik her zamankinden daha kalabalık gibi.",
"VO__PEOPLE_M6__CH08__CHATTER__AUDIENCE_WAITING__010__M__1": "Geçen yıl çok güzeldi, sence daha iyisini yapabilirler mi?",
"VO__PEOPLE_M6__CH08__CHATTER__REACHING_SQUARE__040__M__1": "Anne kutsansın!",
"VO__SOLDIER_B2__CH08__CHATTER__BROKE_POTS_NOISE__020__M__1": "Buldum seni!",
"VO__SOLDIER_B2__CH08__CHATTER__BROKE_POTS_NOISE__070__M__1": "Diğerleri meşgul, ama benim kuşum onların üçüne bedel! Öldün sen!",
"VO__SOLDIER_B2__CH08__CHATTER__DISTRACT_01__020__M__1": "Nihayet yüzünü göstermeye mi karar verdin?!",
"VO__SOLDIER_B2__CH08__CHATTER__DISTRACT_02__020__M__1": "Ah, o oyunu mu oynamak istiyorsun?! Hadi oynayalım!",
"VO__SOLDIER_B2__CH08__CHATTER__DISTRACT_03__010__M__1": "Bir noktada hata yapacaksın!",
"VO__SOLDIER_B2__CH08__CHATTER__DISTRACT_04__010__M__1": "Hadi! Yakala onları! Seni işe yaramaz serçe!",
"VO__SOLDIER_B2__CH08__CHATTER__DISTRACT_05__010__M__1": "Orada olduğunu biliyorum!",
"VO__SOLDIER_B2__CH08__CHATTER__DISTRACT_08__020__M__1": "Ha! Eninde sonunda seni yakalar! Sen bekle!",
"VO__SOLDIER_B2__CH08__CHATTER__FALCON_BEGINNING__010__M__1": "Nerede olduğunu biliyorum! Kaçacak yerin yok!",
"VO__SOLDIER_B2__CH08__CHATTER__NO_DAMAGE__010__M__1": "Onunla ne yapacağını sanıyorsun?!",
"VO__SOLDIER_B2__CH08__CHATTER__NO_DAMAGE__020__M__1": "Taşların zırhımı çizmez bile!",
"VO__SOLDIER_B2__CH08__CHATTER__REINFORCEMENT_COUNT__020__M__1": "Git! Ben diğerlerini gözlerim!",
"VO__SOLDIER_B2__CH08__RTC__370_BASTARD__015__M__1": "Ben... üzgünüm, efendim...",
"VO__SOLDIER_N1__CH08__CHATTER__AUDIENCE_WAITING__030__M__1": "Umarım yine ana meydandan geçerler. En güzel an o!",
"VO__SOLDIER_N1__CH08__CHATTER__GO_PROCESSION__010__M__1": "Dansçılar ve müzisyenler artık yerinde! Şenlikler başlamak üzere! Gelin!",
"VO__SOLDIER_N1__CH08__CHATTER__MARKET_CRIER__010__M__1": "Sabırlı olun! Şimdilik yolun açık olması gerek! Sadece malları meydana taşıyorlar!",
"VO__SOLDIER_N1__CH08__CHATTER__REINFORCEMENT_COUNT__010__M__1": "Acele edin! Kont saldırıya uğruyor!",
"VO__SOLDIER_N2__CH08__CHATTER__PALACE__005__M__1": "Baba. Anne.",
"VO__SOLDIER_N2__CH08__CHATTER__RUN__040__M__1": "Hey! Neler oluyor?! Dur!",
"VO__SOLDIER_S1__CH08__CHATTER__RUN__010__M__1": "Yakalayın onları! Kızı ve çocuğu!",
"VO__SOLDIER_S2__CH08__CHATTER__RUN__060__M__1": "Hey, sen!",
"VO__SOPHIA__CH08__CHATTER__CALL_SAIL__010__M__1": "Hey, siz ikiniz! Yelken iskele tarafına çekiyor! Bir el lazım!",
"VO__SOPHIA__CH08__CHATTER__HUGO_DECK_END__030__M__1": "Biliyoruz!",
"VO__SOPHIA__CH08__CHATTER__HUGO_HELLO_SOPHIA__010__M__1": "Hey! Fırtınanın korkunç kardeşleri!",
"VO__SOPHIA__CH08__CHATTER__HUGO_INTERACT_SOPHIA__020__M__1": "Sakin... Deniz kızları! Bütün rotaları bilirler.",
"VO__SOPHIA__CH08__CHATTER__HUGO_INTERACT_SOPHIA__040__M__1": "Epey utangaçtırlar, biliyor musun... Bu yüzden aletler ve haritalar da kullanırım. Çok teknik bir iştir, ama ben zekiyimdir, yani...",
"VO__SOPHIA__CH08__CHATTER__HUGO_INTERACT_SOPHIA__070__M__1": "Hayır... Ama onları kırma, yoksa seni denize atarım.",
"VO__SOPHIA__CH08__CHATTER__HUGO_INTERACT_SOPHIA__090__M__1": "Şaka yapmıyorum.",
"VO__SOPHIA__CH08__CHATTER__SAIL_PULL_DONE__020__M__1": "Aferin!",
"VO__SOPHIA__CH08__RTC__349_SOPHIA__020__M__1": "Diğer bütün dertlere değer...",
"VO__SOPHIA__CH08__RTC__349_SOPHIA__030__M__1": "Hadi, tut!",
"VO__SOPHIA__CH08__RTC__349_SOPHIA__050__M__1": "Hadi! Hiçbir şeye çarpmazsın!",
"VO__SOPHIA__CH08__RTC__349_SOPHIA__060__M__1": "Eee?",
"VO__SOPHIA__CH08__RTC__349_SOPHIA__080__M__1": "Hissettiğin şey deniz. Özgürlük.",
"VO__SOPHIA__CH08__RTC__349_SOPHIA__100__M__1": "Arnaud'ya teşekkür et. Genelde bu kadar nazik olmam.",
"VO__SOPHIA__CH08__RTC__349_SOPHIA__120__M__1": "O bir alçak, biliyorum. Olmak için sebepleri var. Derin yaralar. Bu onu mazur göstermez ama...",
"VO__SOPHIA__CH08__RTC__349_SOPHIA__150__M__1": "Rica ederim.",
"VO__SOPHIA__CH08__RTC__350_EARTH__110__M__1": "Pardon...",
"VO__SOPHIA__CH08__RTC__350_EARTH__120__M__1": "...sadece yakında karaya çıkmaya hazırlanacağımızı söyleyecektim. Yardımın lazım olacak. Hazır olunca... gel beni gör...",
"VO__SOPHIA__CH08__RTC__360_HARBOR__060__M__1": "Ben kalıyorum! Burada birkaç şey onarıp sonra size katılırım.",
"VO__SOPHIA__CH08__RTC__360_HARBOR__080__M__1": "Kulağa hoş geliyor! Bu arada... Bu topraklar Kont'un yasası altında. \"Uslu\" durun, anladınız mı?",
}
