# -*- coding: utf-8 -*-
# CH13 VO - kaynak proper Turkce; build asamasinda SUB uygulanir.
# Arnaud (the Wall=Duvar): kaba paral asker, sen. Defiler->Kirletici. Nebula korunur (Gunes Katili/Isik Yutan).
T = {
"VO__AMICIA__CH13__CHATTER__AFTER_DROP__020__M__1": "Elimizden geleni yapıyoruz.",
"VO__AMICIA__CH13__CHATTER__AFTER_DROP__040__M__1": "Mecbur kalmayacaksın. Onu oradan çıkaracağız. Sophia'yı da.",
"VO__AMICIA__CH13__CHATTER__ARM_PAIN__010__M__1": "Nefes al...",
"VO__AMICIA__CH13__CHATTER__BEFORE_EXECUTION__050__M__1": "Onu bana bırak!",
"VO__AMICIA__CH13__CHATTER__BELFRY_OK__020__M__1": "Evet. Şimdi Arnaud nerede...",
"VO__AMICIA__CH13__CHATTER__BLOCKED_HALLWAY__010__M__1": "Tıkalı... Bu şeyi buradan kımıldatamam...",
"VO__AMICIA__CH13__CHATTER__BY_MYSELF__010__M__1": "Dayan... Dayanman gerek...",
"VO__AMICIA__CH13__CHATTER__CART_CLOSE__010__M__1": "Bu, belki.",
"VO__AMICIA__CH13__CHATTER__CHASE_TENSION__010__M__1": "Kahrolun! Hepiniz kahrolun! Buradan çıkıyoruz!",
"VO__AMICIA__CH13__CHATTER__CHASE_TENSION__020__M__1": "ONU ALAMAYACAKSINIZ! DUYDUNUZ MU?! BİTTİ ARTIK!",
"VO__AMICIA__CH13__CHATTER__CLOSE_TO_CLIFF__020__M__1": "Bilmek istemiyorum.",
"VO__AMICIA__CH13__CHATTER__COMING_BACK__020__M__1": "Evet...",
"VO__AMICIA__CH13__CHATTER__CROSSBOW_PULL__010__M__1": "Dikkat! Ben... kapıyı açıyorum...",
"VO__AMICIA__CH13__CHATTER__CROSSBOW_PULL_OK__020__M__1": "Nasıl o?",
"VO__AMICIA__CH13__CHATTER__CROSSBOW_PULL_OK__030__M__1": "Ha... Evet...",
"VO__AMICIA__CH13__CHATTER__CROSSBOW_PULL_OK__040__M__1": "Yani... kendine gelmiyor...",
"VO__AMICIA__CH13__CHATTER__DIVE_IN__010__M__1": "Çok yakınımda kal.",
"VO__AMICIA__CH13__CHATTER__DROP_CHASE__020__M__1": "Aşağı! Aşağı in, çabuk!",
"VO__AMICIA__CH13__CHATTER__EGG_TRENCH_EVENT__020__M__1": "Evet, hâlâ buradalar...",
"VO__AMICIA__CH13__CHATTER__EGG_TRENCH_EVENT__050__M__1": "Hugo...",
"VO__AMICIA__CH13__CHATTER__ENCOUNTER_END__010__M__1": "Kont hâlâ hayatta ve yalanlarını yayıyor. Her neyse, peşimizdeler, o yüzden dikkatli ol.",
"VO__AMICIA__CH13__CHATTER__ENTER_PUZZLE_ROOM__020__M__1": "Nasıl...?",
"VO__AMICIA__CH13__CHATTER__ENTER_PUZZLE_ROOM__035__M__1": "Ben bakarım. Sen onunla kal.",
"VO__AMICIA__CH13__CHATTER__ENTER_PUZZLE_ROOM__037__M__1": "Onu... geri getirmeye çalış... nasıl olursa... Lütfen.",
"VO__AMICIA__CH13__CHATTER__EXIT_GATE__020__M__1": "Ondan geriye kalan...",
"VO__AMICIA__CH13__CHATTER__EXIT_GATE__030__M__1": "Çok yüksek... Ona ulaşmak için bir şey lazım.",
"VO__AMICIA__CH13__CHATTER__FALLEN_BELFRY__020__M__1": "Suyun üstünde zar zor asılı duruyor ama...",
"VO__AMICIA__CH13__CHATTER__FALLEN_BELFRY__040__M__1": "Başka çare yok.",
"VO__AMICIA__CH13__CHATTER__FEATHER_VILLAGE__010__M__1": "Bir tüy...",
"VO__AMICIA__CH13__CHATTER__FEATHER_VILLAGE__020__M__1": "Hugo, bak... Ne olduğunu bilmiyorum ama... ister misin onu?",
"VO__AMICIA__CH13__CHATTER__FEATHER_VILLAGE__040__M__1": "Çünkü... onları seversin. Al... senin olsun.",
"VO__AMICIA__CH13__CHATTER__FEATHER_VILLAGE__060__M__1": "Her şey yoluna girecek.",
"VO__AMICIA__CH13__CHATTER__FIRST_SHOT__010__M__1": "İşte buradasın...",
"VO__AMICIA__CH13__CHATTER__FIRST_SHOT__018__M__1": "Kes sesini! Seni buradan çıkarıyoruz!",
"VO__AMICIA__CH13__CHATTER__FIRST_SHOT__040__M__1": "Yanımdan ayrılma!",
"VO__AMICIA__CH13__CHATTER__FURIOUS_RATSTRIKE_INTRO__025__M__1": "Olamaz...",
"VO__AMICIA__CH13__CHATTER__GIANT_EGG_AHEAD__010__M__1": "Lucas, ileride... bir şey var...",
"VO__AMICIA__CH13__CHATTER__GOING_DOWN__010__M__1": "Sessiz...",
"VO__AMICIA__CH13__CHATTER__GROWTH__010__M__1": "Evet.",
"VO__AMICIA__CH13__CHATTER__GROWTH_EXPLOSION_1__020__M__1": "Ne?! Biliyor... Burada olduğumuzu biliyor!",
"VO__AMICIA__CH13__CHATTER__GROWTH_EXPLOSION_1__040__M__1": "Sanırım... bunu o yapıyor...",
"VO__AMICIA__CH13__CHATTER__GROWTH_EXPLOSION_1__060__M__1": "Bedeninin... kasıldığını hissettim... Tam her şey patlamadan önce...",
"VO__AMICIA__CH13__CHATTER__GROWTH_EXPLOSION_1__080__M__1": "Hâlâ orada olduğunu biliyorum, Hugo... Lütfen dayan...",
"VO__AMICIA__CH13__CHATTER__GROWTHS_CHASE__020__M__1": "Arkada gün ışığı var! Ona doğru koş! Var gücünle!",
"VO__AMICIA__CH13__CHATTER__HARBOR_VISTA__020__M__1": "Kara yok olmuş!",
"VO__AMICIA__CH13__CHATTER__HARBOR_VISTA__040__M__1": "Hayır...",
"VO__AMICIA__CH13__CHATTER__HARBOR_VISTA__080__M__1": "Hayır! Bunu Kont ve Kontes yaptı... Gidelim... Hadi gidelim...",
"VO__AMICIA__CH13__CHATTER__HEAVY_DEAD__040__M__1": "Yapma! Seni alamayacaklar, Hugo, söz veriyorum!",
"VO__AMICIA__CH13__CHATTER__HEAVY_INCOMING__020__M__1": "O, gerçeği görmek istemediği için öldü! Tıpkı geri kalanınız gibi!",
"VO__AMICIA__CH13__CHATTER__HEAVY_INCOMING__050__M__1": "Onları boş ver, Hugo!",
"VO__AMICIA__CH13__CHATTER__IDLE_1__020__M__1": "Kendi sonlarıyla yüzleşmektense birini öldürmeyi yeğlerler. Yeni bir şey değil...",
"VO__AMICIA__CH13__CHATTER__IDLE_2__005__M__1": "Hugo... Hâlâ iyi misin?",
"VO__AMICIA__CH13__CHATTER__IDLE_2__020__M__1": "Tamam. Sadece... sakin kalmaya çalış.",
"VO__AMICIA__CH13__CHATTER__IDLE_3__010__M__1": "Buradan çıkıyoruz. Sophia'yı bulacağız. Yelken açıp gideceğiz... ve yeni bir hayata başlayacağız...",
"VO__AMICIA__CH13__CHATTER__IDLE_4__010__M__1": "Bu kadar yol geldik... Bu ada batsa da umurumuzda değil, biz gidiyoruz.",
"VO__AMICIA__CH13__CHATTER__IDLE_5__020__M__1": "Bir tane bulacağız. Kıyıya kadar kürek çekmek gerekse bile...",
"VO__AMICIA__CH13__CHATTER__IDLE_VILLAGE_1__020__M__1": "Umarım Sophia hayattadır.",
"VO__AMICIA__CH13__CHATTER__IDLE_VILLAGE_2__030__M__1": "Umarım biz gidince burada kalırlar...",
"VO__AMICIA__CH13__CHATTER__IDLE_VILLAGE_3__010__M__1": "Hugo... Lütfen bizimle kal...",
"VO__AMICIA__CH13__CHATTER__IDLE_VILLAGE_3__020__M__1": "O yüzden sadece... kal, yalvarırım.",
"VO__AMICIA__CH13__CHATTER__KILL_HARBOR_1__010__M__1": "“Kirletici”den selam olsun...",
"VO__AMICIA__CH13__CHATTER__KILL_HARBOR_2__010__M__1": "Yürümeye devam edelim...",
"VO__AMICIA__CH13__CHATTER__KILL_HARBOR_2__030__M__1": "Çekilin yolumuzdan...",
"VO__AMICIA__CH13__CHATTER__KILL_HARBOR_3__020__M__1": "Hadi, hadi...",
"VO__AMICIA__CH13__CHATTER__KILL_POST_NEST_1__010__M__1": "Biri gitti...",
"VO__AMICIA__CH13__CHATTER__KILL_POST_NEST_2__010__M__1": "Sadece... bırakın gidelim!",
"VO__AMICIA__CH13__CHATTER__KILL_POST_NEST_3__010__M__1": "Buraya kaç kişi yığmışlar?...",
"VO__AMICIA__CH13__CHATTER__KILL_POST_NEST_4__010__M__1": "Yürüyelim...",
"VO__AMICIA__CH13__CHATTER__LAST_ONE_STANDING__010__M__1": "Yeter!",
"VO__AMICIA__CH13__CHATTER__LAST_ONE_STANDING__030__M__1": "Evet... tamam...",
"VO__AMICIA__CH13__CHATTER__LEDGE_PROGRESS__030__M__1": "Çabuk! Burayı paramparça edecekler!",
"VO__AMICIA__CH13__CHATTER__LOCKED_DOOR_1__010__M__1": "Hayır...",
"VO__AMICIA__CH13__CHATTER__LOCKER_SHOT__010__M__1": "Devam et...",
"VO__AMICIA__CH13__CHATTER__LOOK_AROUND__010__M__1": "Ona göz kulak ol, hemen dönerim.",
"VO__AMICIA__CH13__CHATTER__LUCAS_HELP__020__M__1": "Evet!",
"VO__AMICIA__CH13__CHATTER__MORE_SOLDIERS__010__M__1": "Kalan bütün askerler burada...",
"VO__AMICIA__CH13__CHATTER__MORE_WAVE_2__017__M__1": "Ne yaptığımı sanıyorsun?!",
"VO__AMICIA__CH13__CHATTER__NEST_EXPLOSION_1__010__M__1": "Dikkat, serbest kaldılar...",
"VO__AMICIA__CH13__CHATTER__NEST_EXPLOSION_2__010__M__1": "İşte size... Sizin için askerlerim var...",
"VO__AMICIA__CH13__CHATTER__OPPOSITION__020__M__1": "Hugo! Burada kal!",
"VO__AMICIA__CH13__CHATTER__OTHER_WAY__010__M__1": "Yakıyor!",
"VO__AMICIA__CH13__CHATTER__OTHER_WAY__030__M__1": "Onları görüyorum!",
"VO__AMICIA__CH13__CHATTER__PINNED_DOWN_1__050__M__1": "Evet!",
"VO__AMICIA__CH13__CHATTER__POLE_ROOM_GRATING__010__M__1": "İpli bir sırık...",
"VO__AMICIA__CH13__CHATTER__POST_FINAL_RATS__050__M__1": "Bitti artık.",
"VO__AMICIA__CH13__CHATTER__POST_FINAL_RATS__070__M__1": "Evet... Nefes al. Sakin ol artık... Arnaud'yu kurtaralım, olur mu?",
"VO__AMICIA__CH13__CHATTER__POST_TRENCH_EVENT__040__M__1": "Bunu yaptığını hiç görmemiştim...",
"VO__AMICIA__CH13__CHATTER__POST_TRENCH_EVENT__060__M__1": "Soğumasını bekle...",
"VO__AMICIA__CH13__CHATTER__POST_VISTA_GALLOW__030__M__1": "Hak etmese bile.",
"VO__AMICIA__CH13__CHATTER__PULL_1ST_SHELF__010__M__1": "Hadi...",
"VO__AMICIA__CH13__CHATTER__PULLING_BACK__020__M__1": "Bu da ne...",
"VO__AMICIA__CH13__CHATTER__PULLING_BACK__040__M__1": "Bu... her şeyden beter...",
"VO__AMICIA__CH13__CHATTER__PUZZLE_ROOM_SEE_PUSH__010__M__1": "Şu... yukarıdaki araba...",
"VO__AMICIA__CH13__CHATTER__RAT_MOVE_1__020__M__1": "Üzgünüm, Hugo! Limana ulaşmak için onlara ihtiyacımız var!",
"VO__AMICIA__CH13__CHATTER__RAT_MOVE_2__030__M__1": "Yakında duracak...",
"VO__AMICIA__CH13__CHATTER__RAT_MOVE_3__020__M__1": "Başarabilirsin... Birkaç tane daha.",
"VO__AMICIA__CH13__CHATTER__REACHED_VILLAGE__010__M__1": "Girdik!",
"VO__AMICIA__CH13__CHATTER__SHOOT_CHAIN__010__M__1": "Tamam, bu... Ah...",
"VO__AMICIA__CH13__CHATTER__SHOOT_LOCKER__010__M__1": "İşte...",
"VO__AMICIA__CH13__CHATTER__SOLDIERS__020__M__1": "Askerler...",
"VO__AMICIA__CH13__CHATTER__SOUVENIR_HUGO__010__M__1": "Tanrım!",
"VO__AMICIA__CH13__CHATTER__SOUVENIR_LIBRARY__010__M__1": "Ne dağınıklık... Yapamıyorum...",
"VO__AMICIA__CH13__CHATTER__SOUVENIR_LIBRARY__020__M__1": "Ah lütfen... Lütfen... Bunu nasıl yapacağım?...",
"VO__AMICIA__CH13__CHATTER__SOUVENIR_LIBRARY__025__M__1": "Lütfen... Yapamıyorum... Yardım edin... Ha... Tanrım...",
"VO__AMICIA__CH13__CHATTER__SOUVENIR_LIBRARY__030__M__1": "Ha... Dur... Dur... Ayağa kalk. Ayağa kalk ve yürü.",
"VO__AMICIA__CH13__CHATTER__TO_SHELF__010__M__1": "Şunu... kullanalım...",
"VO__AMICIA__CH13__CHATTER__VAULT__010__M__1": "Yukarı! Çabuk!",
"VO__AMICIA__CH13__CHATTER__VAULT__040__M__1": "Gel, Hugo!",
"VO__AMICIA__CH13__CHATTER__VISTA_GALLOW__010__M__1": "Daha yakına gidelim...",
"VO__AMICIA__CH13__CHATTER__VISTA_GALLOW__050__M__1": "Evet. Hazırlan...",
"VO__AMICIA__CH13__CHATTER__VISTA_GALLOW_UP__040__M__1": "Tanrım... Gidelim, daha yakına gitmeliyiz.",
"VO__AMICIA__CH13__CHATTER__WORKBENCH_SPECIFIC__010__M__1": "Hadi... Her şey işe yarar... buna ihtiyacın var...",
"VO__AMICIA__CH13__HELPER__SHOOT_LOCKER_1__010__M__1": "Şu kapıyı açmanın bir yolu olmalı...",
"VO__AMICIA__CH13__HELPER__SHOOT_LOCKER_2__010__M__1": "Sapanımla şu kilidi kırabilirim belki...",
"VO__AMICIA__CH13__RTC__680_MOURNING__010__M__1": "Lütfen... Hugo... Bir şey söyle...",
"VO__AMICIA__CH13__RTC__680_MOURNING__020__M__1": "Bana bak... Lütfen... Sana ihtiyacım var...",
"VO__AMICIA__CH13__RTC__680_MOURNING__040__M__1": "Benimle konuşmuyor...",
"VO__AMICIA__CH13__RTC__680_MOURNING__060__M__1": "Hugo... Cevap ver...",
"VO__AMICIA__CH13__RTC__680_MOURNING__080__M__1": "Nereye gideceğiz...?",
"VO__AMICIA__CH13__RTC__680_MOURNING__100__M__1": "Dinlenmek... istiyorum...",
"VO__AMICIA__CH13__RTC__680_MOURNING__120__M__1": "Asla olamayacağız, Lucas... Asla...",
"VO__AMICIA__CH13__RTC__680_MOURNING__130__M__1": "Bizim için huzur olamaz... Ona bak... Bak...",
"VO__AMICIA__CH13__RTC__682_EPAULE__020__M__1": "Omuz...",
"VO__AMICIA__CH13__RTC__682_EPAULE__040__M__1": "Yap...",
"VO__AMICIA__CH13__RTC__685_RATS_NEST__010__M__1": "Başka yol yok, Lucas.",
"VO__AMICIA__CH13__RTC__685_RATS_NEST__030__M__1": "O şeyleri Taşıyıcı'nın mezarında gördük...",
"VO__AMICIA__CH13__RTC__685_RATS_NEST__045__M__1": "Ne?",
"VO__AMICIA__CH13__RTC__685_RATS_NEST__090__M__1": "Hayır, hayır, burası yuva değil... Hugo, bana bak!",
"VO__AMICIA__CH13__RTC__685_RATS_NEST__120__M__1": "Ben... Onu kurtarmalıydım. Ama bunu hâlâ bitirebiliriz...",
"VO__AMICIA__CH13__RTC__685_RATS_NEST__130__M__1": "Beni duyuyor musun Hugo? O alçak Kont'u bulup öldürebiliriz!",
"VO__AMICIA__CH13__RTC__685_RATS_NEST__160__M__1": "Tamam... Tamam!",
"VO__AMICIA__CH13__RTC__700_HOME__020__M__1": "İçeride kaç tane var?",
"VO__AMICIA__CH13__RTC__700_HOME__040__M__1": "Hey!",
"VO__AMICIA__CH13__RTC__700_HOME__060__M__1": "Gidelim, Lucas. Hemen.",
"VO__AMICIA__CH13__RTC__700_HOME__080__M__1": "Gel, Hugo!",
"VO__AMICIA__CH13__RTC__700_HOME__100__M__1": "Burada sana ait hiçbir şey yok!",
"VO__AMICIA__CH13__RTC__700_HOME__120__M__1": "DUR!",
"VO__AMICIA__CH13__RTC__700_HOME__130__M__1": "İstesen de istemesen de benimle geliyorsun!",
"VO__AMICIA__CH13__RTC__700_HOME__140__M__1": "Beni duyuyor musunuz?! O... benimle... geliyor!",
"VO__AMICIA__CH13__RTC__720_EXIT_NEST__020__M__1": "Hugo... Hugo!",
"VO__AMICIA__CH13__RTC__720_EXIT_NEST__030__M__1": "Gördün mü? ... Hâlâ ışık var...",
"VO__AMICIA__CH13__RTC__720_EXIT_NEST__040__M__1": "Evet... Bu bizim kanımız. Bu sensin.",
"VO__AMICIA__CH13__RTC__720_EXIT_NEST__050__M__1": "Daha işimiz bitmedi. Gitmeliyiz.",
"VO__AMICIA__CH13__RTC__720_EXIT_NEST__070__M__1": "Hâlâ limana ulaşmamız gerek.",
"VO__AMICIA__CH13__RTC__780_ARNAUD__020__M__1": "Bu Sophia'nın!",
"VO__AMICIA__CH13__RTC__780_ARNAUD__030__M__1": "Evet!",
"VO__AMICIA__CH13__RTC__780_ARNAUD__040__M__1": "Lütfen hayatta ol. Lütfen hayatta ol...",
"VO__AMICIA__CH13__RTC__780_ARNAUD__090__M__1": "Arnaud...",
"VO__AMICIA__CH13__RTC__780_ARNAUD__110__M__1": "Vaktimiz yok!",
"VO__AMICIA__CH13__RTC__780_ARNAUD__130__M__1": "Cidden mi? Onca yaptığından sonra bile mi?!",
"VO__AMICIA__CH13__RTC__780_ARNAUD__140__M__1": "Pekâlâ. Zaten o limana ulaşmamız gerek. Yol üstünde Arnaud'yu alırız ve buradan gideriz.",
"VO__AMICIA__CH13__RTC__790_RESCUE__020__M__1": "Sus. Seni kurtarıyorum.",
"VO__AMICIA__CH13__RTC__790_RESCUE__070__M__1": "Küçük bir çocuğa ihanet ettin, ve sana ikinci bir şans veren de o. Şimdi havlamayı kes ve dinle.",
"VO__AMICIA__CH13__RTC__790_RESCUE__080__M__1": "Sophia'nın teknesine ulaşmamız gerek. Başında nöbetçiler olacak. Bizimle kıta arasına giren herkesi öldürebilirsin. Ondan sonra, işimiz biter. Anlaştık mı?",
"VO__AMICIA__CH13__RTC__790_RESCUE__100__M__1": "Hadi.",
"VO__AMICIA__CH13__RTC__790_RESCUE__130__M__1": "Öyle olsa iyi olur.",
"VO__AMICIA__CH13__RTC__795_GREATEST_GIFT__010__M__1": "Sophia!",
"VO__AMICIA__CH13__RTC__795_GREATEST_GIFT__060__M__1": "Gitmeliyiz. Hemen.",
"VO__AMICIA__CH13__RTC__795_GREATEST_GIFT__100__M__1": "Biliyorum...",
"VO__AMICIA__CH13__RTC__795_GREATEST_GIFT__120__M__1": "Ben de... Ama o biliyordu. Her şeyi, çoktan... Sen onun en büyük armağanıydın. Seni olduğun gibi sevdi. Seni yarattığı hâlinle...",
"VO__AMICIA__CH13__RTC__795_GREATEST_GIFT__130__M__1": "Yaşayacağız. Ve iyileşeceğiz.",
"VO__AMICIA__CH13__RTC__795_GREATEST_GIFT__140__M__1": "Yaralar... Onları saklarız. Unutmamak için. Kabullenebilmek için. Artık acıtmaz olana dek.",
"VO__ARNAUD__CH13__CHATTER__AMICIA_KILLS_1__010__M__1": "Kıçlarına öyle bir tekme at ki kıymaya dönsünler!",
"VO__ARNAUD__CH13__CHATTER__AMICIA_KILLS_2__010__M__1": "İşte böyle! Göster onlara ne kadar değersiz olduklarını!",
"VO__ARNAUD__CH13__CHATTER__FIRST_SHOT__017__M__1": "Vay canına... Beni temizlemeye mi geldin?",
"VO__ARNAUD__CH13__CHATTER__FURIOUS_RATSTRIKE_INTRO__010__M__1": "Dikkat! Ağır herifler geliyor!",
"VO__ARNAUD__CH13__CHATTER__HEAVY_INCOMING__070__M__1": "Hadi! Gebertin şu lanet herifleri!",
"VO__ARNAUD__CH13__CHATTER__LAST_ONE_STANDING__020__M__1": "Güzel! Şimdi şu lanet ipi boynumdan çıkarır mısın?!",
"VO__ARNAUD__CH13__CHATTER__MORE_COMING_1__010__M__1": "Daha fazlası geliyor!",
"VO__ARNAUD__CH13__CHATTER__MORE_COMING_2__010__M__1": "Takviye almışlar!",
"VO__ARNAUD__CH13__CHATTER__MORE_COMING_3__010__M__1": "Dahası var! Benim için gebert onları!",
"VO__ARNAUD__CH13__CHATTER__MORE_WAVE_1__015__M__1": "Köpekler! Korkaklar! Elimden gelse kafanızı ezerdim!",
"VO__ARNAUD__CH13__CHATTER__MORE_WAVE_2__015__M__1": "Hadi! Bitir şu kuklaları!",
"VO__ARNAUD__CH13__CHATTER__MORE_WAVE_2__020__M__1": "Göreceğiz bakalım!",
"VO__ARNAUD__CH13__CHATTER__POST_FINAL_RATS__040__M__1": "Kahrolası... cehennem...",
"VO__ARNAUD__CH13__CHATTER__POST_FINAL_RATS__080__M__1": "Evet... Lütfen.",
"VO__ARNAUD__CH13__RTC__790_RESCUE__010__M__1": "Sen... Seni öldüreceğim...",
"VO__ARNAUD__CH13__RTC__790_RESCUE__030__M__1": "Bana ihanet ettin!",
"VO__ARNAUD__CH13__RTC__790_RESCUE__075__M__1": "Hımm...",
"VO__ARNAUD__CH13__RTC__790_RESCUE__090__M__1": "Anlaştık.",
"VO__ARNAUD__CH13__RTC__790_RESCUE__110__M__1": "Sence Sophia hayatta mı?",
"VO__ARNAUD__CH13__RTC__790_RESCUE__140__M__1": "Bana uyar.",
"VO__ARNAUD__CH13__RTC__790_RESCUE__150__M__1": "Şimdi yapmamız gereken...",
"VO__ARNAUD__CH13__RTC__790_RESCUE__160__M__1": "Siper alın!",
"VO__HUGO__CH13__CHATTER__AFTER_DROP__010__M__1": "Daha hızlı gitmeliyiz. Onu öldürecekler.",
"VO__HUGO__CH13__CHATTER__AFTER_DROP__030__M__1": "Onu öldürürlerse, hepsini öldürürüm.",
"VO__HUGO__CH13__CHATTER__BEFORE_EXECUTION__040__M__1": "Şimdi, Amicia! Bir şey yap!",
"VO__HUGO__CH13__CHATTER__EGG_TRENCH_EVENT__030__M__1": "Hep...",
"VO__HUGO__CH13__CHATTER__EGG_TRENCH_EVENT__040__M__1": "Hep kafamın içinde...",
"VO__HUGO__CH13__CHATTER__EGG_TRENCH_EVENT__070__M__1": "Sözü geçen sen değilsin...",
"VO__HUGO__CH13__CHATTER__EGG_TRENCH_EVENT__080__M__1": "Sözü geçen BENİM!",
"VO__HUGO__CH13__CHATTER__EGG_TRENCH_EVENT__090__M__1": "Sen BANA itaat edersin! Duydun mu?! Sen... BANA... İTAAT... EDERSİN!",
"VO__HUGO__CH13__CHATTER__FEATHER_VILLAGE__030__M__1": "Neden?",
"VO__HUGO__CH13__CHATTER__FEATHER_VILLAGE__050__M__1": "Evet.",
"VO__HUGO__CH13__CHATTER__FIRST_SHOT__015__M__1": "Buradayız Arnaud!",
"VO__HUGO__CH13__CHATTER__FIRST_SHOT__030__M__1": "Hayır!",
"VO__HUGO__CH13__CHATTER__FURIOUS_RATSTRIKE_INTRO__060__M__1": "Yanlış!",
"VO__HUGO__CH13__CHATTER__HARBOR_VISTA__030__M__1": "Bu benim...",
"VO__HUGO__CH13__CHATTER__HARBOR_VISTA__050__M__1": "Bunu ben yaptım...",
"VO__HUGO__CH13__CHATTER__HARBOR_VISTA__070__M__1": "Yaptım... Ben yaptım!",
"VO__HUGO__CH13__CHATTER__HEAVY_DEAD__030__M__1": "Denersen seni öldürürüm!",
"VO__HUGO__CH13__CHATTER__HEAVY_INCOMING__040__M__1": "Sessiz ol!",
"VO__HUGO__CH13__CHATTER__IDLE_2__010__M__1": "Bilmiyorum.",
"VO__HUGO__CH13__CHATTER__IDLE_VILLAGE_3__015__M__1": "Buradayım.",
"VO__HUGO__CH13__CHATTER__NEST_EXPLOSION_6__010__M__1": "Çok fazlalar...",
"VO__HUGO__CH13__CHATTER__OPPOSITION__010__M__1": "Asla!",
"VO__HUGO__CH13__CHATTER__POST_TRENCH_EVENT__050__M__1": "Çünkü acıyor...",
"VO__HUGO__CH13__CHATTER__POST_VISTA_GALLOW__020__M__1": "Evet... Onu kurtarmalıyız.",
"VO__HUGO__CH13__RTC__685_RATS_NEST__035__M__1": "Güneşi öldürecek.",
"VO__HUGO__CH13__RTC__685_RATS_NEST__080__M__1": "Evimdeyim.",
"VO__HUGO__CH13__RTC__700_HOME__030__M__1": "Evet. Buradayım.",
"VO__HUGO__CH13__RTC__700_HOME__050__M__1": "Bekliyorum.",
"VO__HUGO__CH13__RTC__700_HOME__090__M__1": "HAYIR! Ben kalıyorum!",
"VO__HUGO__CH13__RTC__700_HOME__110__M__1": "Burası... benim... yuvam! Burası...",
"VO__HUGO__CH13__RTC__780_ARNAUD__100__M__1": "Ölmedi! Bize ihtiyacı var!",
"VO__HUGO__CH13__RTC__780_ARNAUD__120__M__1": "Gitmeliyiz!",
"VO__HUGO__CH13__RTC__795_GREATEST_GIFT__050__M__1": "O geri dönmeyecek...",
"VO__HUGO__CH13__RTC__795_GREATEST_GIFT__090__M__1": "Bir daha asla dönmeyecek.",
"VO__HUGO__CH13__RTC__795_GREATEST_GIFT__110__M__1": "Ben... Ona... bir sürü şey... söylemek istiyordum...",
"VO__LUCAS__CH13__CHATTER__BEFORE_PUZZLE_ROOM__010__M__1": "Bir çıkış yolu olmalı!",
"VO__LUCAS__CH13__CHATTER__BELFRY_OK__010__M__1": "Oh... Dayandı...",
"VO__LUCAS__CH13__CHATTER__CLOSE_TO_CLIFF__010__M__1": "Bu şey ne kadar derine iniyor? Görünür tek bir kaya bile kalmamış...",
"VO__LUCAS__CH13__CHATTER__COMING_BACK__015__M__1": "İyi... misin?",
"VO__LUCAS__CH13__CHATTER__CROSSBOW_PULL_OK__010__M__1": "Vay!",
"VO__LUCAS__CH13__CHATTER__CROSSBOW_PULL_OK__020__M__1": "Bu iş gördü! Aferin!... Yukarı tırmanmayı deneyeceğiz!",
"VO__LUCAS__CH13__CHATTER__CROSSBOW_PULL_OK__030__M__1": "Zihni... sönmüş. Bence bu sadece şok değil... Bu, Macula...",
"VO__LUCAS__CH13__CHATTER__CROSSBOW_PULL_OK__050__M__1": "Henüz değil.",
"VO__LUCAS__CH13__CHATTER__DROP_CHASE__010__M__1": "Burada bir uçurum var! Yavaşlama!",
"VO__LUCAS__CH13__CHATTER__EGG_TRENCH_EVENT__010__M__1": "Aman Tanrım... Sarsıntılar şu lanet yumurtaları açığa çıkardı!",
"VO__LUCAS__CH13__CHATTER__EGG_TRENCH_EVENT__060__M__1": "Bırak yapsın, Amicia.",
"VO__LUCAS__CH13__CHATTER__EGG_TRENCH_EVENT__110__M__1": "Pekâlâ... Sanırım... seni duydular...",
"VO__LUCAS__CH13__CHATTER__ENTER_PUZZLE_ROOM__010__M__1": "Bak! Şu yukarıda! Bir açıklık! Çıkış yolumuz bu!",
"VO__LUCAS__CH13__CHATTER__ENTER_PUZZLE_ROOM__030__M__1": "Üst kat... Yukarıda kullanabileceğimiz şeyler olabilir!",
"VO__LUCAS__CH13__CHATTER__ENTER_PUZZLE_ROOM__036__M__1": "Amicia, hâlâ yaralısın!",
"VO__LUCAS__CH13__CHATTER__ENTER_PUZZLE_ROOM__040__M__1": "Peki. Ama fazla uzaklaşma.",
"VO__LUCAS__CH13__CHATTER__ENTER_PUZZLE_ROOM__060__M__1": "Pekâlâ, Hugo... Sanırım beni duyabiliyorsun. Üzgünüm... İyi olup olmadığını bilmem gerek.",
"VO__LUCAS__CH13__CHATTER__ENTER_PUZZLE_ROOM__070__M__1": "Gözlerine bir bakayım? Hım... Göz bebeklerin büyümemiş... Neredeyse hiç kırpmıyorsun...",
"VO__LUCAS__CH13__CHATTER__EXIT_GATE__010__M__1": "Şu yukarıdaki kapı, sanırım... köyün girişi.",
"VO__LUCAS__CH13__CHATTER__FALLEN_BELFRY__010__M__1": "Çan kulesi... Köyün öbür tarafına geçmenin tek yolu o gibi görünüyor.",
"VO__LUCAS__CH13__CHATTER__FALLEN_BELFRY__030__M__1": "Başka çare yok, herhâlde?",
"VO__LUCAS__CH13__CHATTER__FEATHER_VILLAGE__070__M__1": "Yakında. Yakında...",
"VO__LUCAS__CH13__CHATTER__FIRE_JAR_SPOT__010__M__1": "Hemen yanlarında katran küpleri var!",
"VO__LUCAS__CH13__CHATTER__FIRST_SHOT__050__M__1": "Ona güven, Hugo!",
"VO__LUCAS__CH13__CHATTER__GIANT_EGG_AHEAD__020__M__1": "Görüyorum... Bu da ne böyle?...",
"VO__LUCAS__CH13__CHATTER__GROWTH__005__M__1": "Nebula her yanımızda. Meşaleni koru.",
"VO__LUCAS__CH13__CHATTER__GROWTH_EXPLOSION_1__010__M__1": "Ah... Olamaz!",
"VO__LUCAS__CH13__CHATTER__GROWTH_EXPLOSION_1__030__M__1": "Ne olmuş?! Yürü!",
"VO__LUCAS__CH13__CHATTER__GROWTH_EXPLOSION_1__050__M__1": "Ne?",
"VO__LUCAS__CH13__CHATTER__GROWTH_EXPLOSION_1__070__M__1": "Sana söylemiştim... Macula'yla bağı gittikçe güçleniyor!",
"VO__LUCAS__CH13__CHATTER__GROWTH_WARNING__010__M__1": "Dikkat...",
"VO__LUCAS__CH13__CHATTER__GROWTHS_CHASE__010__M__1": "Ah... Bu çok kötü!",
"VO__LUCAS__CH13__CHATTER__HARBOR_VISTA__010__M__1": "Dur... Köy... denizde bir terslik var...",
"VO__LUCAS__CH13__CHATTER__HARBOR_VISTA__060__M__1": "Bunu sıçanlar yaptı.",
"VO__LUCAS__CH13__CHATTER__HEAVY_INCOMING__060__M__1": "Yanındayız! Eve gidiyoruz!",
"VO__LUCAS__CH13__CHATTER__IDLE_1__010__M__1": "Hâlâ ölmeni istiyorlar... bu karmaşanın ortasında bile...",
"VO__LUCAS__CH13__CHATTER__IDLE_4__005__M__1": "Amicia, nasıl dayanıyorsun?",
"VO__LUCAS__CH13__CHATTER__IDLE_5__010__M__1": "Umarım tekneler fazla sıkı korunmuyordur...",
"VO__LUCAS__CH13__CHATTER__IDLE_VILLAGE_1__040__M__1": "Gerçekten... bizi öldürmek istemeyen biriyle tanışmak isterdim...",
"VO__LUCAS__CH13__CHATTER__IDLE_VILLAGE_2__010__M__1": "Sıçanların böyle bir güce ulaşabileceğini hiç hayal etmemiştim...",
"VO__LUCAS__CH13__CHATTER__IDLE_VILLAGE_2__050__M__1": "Bu... Hugo'ya bağlı olacak...",
"VO__LUCAS__CH13__CHATTER__KILL_HARBOR_3__040__M__1": "Sakin ol, başarıyoruz.",
"VO__LUCAS__CH13__CHATTER__LEDGE_PROGRESS__010__M__1": "Duvara yakın dur!",
"VO__LUCAS__CH13__CHATTER__LOOK_AROUND__020__M__1": "Evet.",
"VO__LUCAS__CH13__CHATTER__LUCAS_CHECK_HUGO_1__010__M__1": "Cildin solgun... Ama Macula'nın izi... daha büyük görünüyor... Zihnindeki yayılmayı yansıtıyor olmalı...",
"VO__LUCAS__CH13__CHATTER__LUCAS_CHECK_HUGO_2__010__M__1": "Hugo... Sesimi duyabiliyorsan... bir parmağını oynat.",
"VO__LUCAS__CH13__CHATTER__LUCAS_CHECK_HUGO_3__010__M__1": "Baban... Engizisyon geldi, ve o... idam edildi. Seni istiyorlardı... Hatırlıyor musun? Ha... O bile işe yaramadı...",
"VO__LUCAS__CH13__CHATTER__LUCAS_HELP__010__M__1": "Birkaç Exstinguis'im var! Yardım edeceğim!",
"VO__LUCAS__CH13__CHATTER__LUCAS_POST_THROW_1__010__M__1": "O senin!",
"VO__LUCAS__CH13__CHATTER__LUCAS_POST_THROW_2__010__M__1": "Sıra sende!",
"VO__LUCAS__CH13__CHATTER__LUCAS_POST_THROW_3__010__M__1": "Tam isabet!",
"VO__LUCAS__CH13__CHATTER__LUCAS_POST_THROW_4__010__M__1": "Sana, Amicia!",
"VO__LUCAS__CH13__CHATTER__LUCAS_POST_THROW_5__010__M__1": "Gözü kör oldu!",
"VO__LUCAS__CH13__CHATTER__LUCAS_THROW_1__010__M__1": "İşte!",
"VO__LUCAS__CH13__CHATTER__LUCAS_THROW_2__010__M__1": "Al bakalım!",
"VO__LUCAS__CH13__CHATTER__LUCAS_THROW_3__010__M__1": "Al sana!",
"VO__LUCAS__CH13__CHATTER__LUCAS_THROW_4__010__M__1": "Onu kör edeceğim!",
"VO__LUCAS__CH13__CHATTER__LUCAS_THROW_5__010__M__1": "Dikkat et!",
"VO__LUCAS__CH13__CHATTER__NEST_EXPLOSION_3__010__M__1": "Bu şeyler... çok yanlış...",
"VO__LUCAS__CH13__CHATTER__NEST_EXPLOSION_4__010__M__1": "Onlara karşı dikkatli ol...",
"VO__LUCAS__CH13__CHATTER__OTHER_WAY__020__M__1": "Önümüzde! Daha çok duman!",
"VO__LUCAS__CH13__CHATTER__PINNED_DOWN_1__040__M__1": "Dayan, Amicia! Başarıyorsun!",
"VO__LUCAS__CH13__CHATTER__POST_FINAL_RATS__060__M__1": "Başardık, Hugo...",
"VO__LUCAS__CH13__CHATTER__POST_VISTA_GALLOW__010__M__1": "Demek “bu” Arnaud? “Duvar” dedikleri adam?!",
"VO__LUCAS__CH13__CHATTER__POST_VISTA_GALLOW__040__M__1": "Anlıyorum... Epey bir ekip toplamışsın.",
"VO__LUCAS__CH13__CHATTER__PULLING_BACK__010__M__1": "Hey! Dikkat et!",
"VO__LUCAS__CH13__CHATTER__PULLING_BACK__030__M__1": "İşte bundan bahsediyordum! Şu dumanlardan uzak dur!",
"VO__LUCAS__CH13__CHATTER__PULLING_BACK__050__M__1": "Tetikte ol... Dahası var...",
"VO__LUCAS__CH13__CHATTER__RAT_MOVE_2__020__M__1": "Dayan...",
"VO__LUCAS__CH13__CHATTER__SHOOT_CHAIN__020__M__1": "Pekâlâ... Gidelim, çabuk.",
"VO__LUCAS__CH13__CHATTER__SOLDIERS__060__M__1": "Kirletici... yeni bir unvan kazandın, Amicia...",
"VO__LUCAS__CH13__CHATTER__SOUVENIR_HUGO__020__M__1": "Kahrolası... cehennem! Daha dikkatli olmalıyız!",
"VO__LUCAS__CH13__CHATTER__VAULT__030__M__1": "Olamaz olamaz! ARKANA BAKMA! KOŞ!",
"VO__LUCAS__CH13__CHATTER__VISTA_GALLOW__040__M__1": "Burası... kalabalık...",
"VO__LUCAS__CH13__CHATTER__VISTA_GOAL__005__M__1": "Ah... İşte başlıyor...",
"VO__LUCAS__CH13__RTC__680_MOURNING__030__M__1": "Amicia. Burada kalamayız.",
"VO__LUCAS__CH13__RTC__680_MOURNING__050__M__1": "Gitmemiz gerek.",
"VO__LUCAS__CH13__RTC__680_MOURNING__070__M__1": "Amicia! Gitmemiz gerek!",
"VO__LUCAS__CH13__RTC__680_MOURNING__090__M__1": "Liman! Burayı terk ediyoruz!",
"VO__LUCAS__CH13__RTC__680_MOURNING__110__M__1": "Güvende olunca dinlenirsin!",
"VO__LUCAS__CH13__RTC__680_MOURNING__140__M__1": "Ben yol göstereceğim. Düşünme. Sadece beni takip et.",
"VO__LUCAS__CH13__RTC__680_MOURNING__150__M__1": "Sizin yolunuz ben olacağım. İkinizin de. Gerekirse taşırım. Ama sizi buradan çıkarıyorum.",
"VO__LUCAS__CH13__RTC__680_MOURNING__160__M__1": "Derin bir nefes al... ve ayağa kalk.",
"VO__LUCAS__CH13__RTC__680_MOURNING__170__M__1": "Başardın!",
"VO__LUCAS__CH13__RTC__680_MOURNING__180__M__1": "Hadi, Hugo!",
"VO__LUCAS__CH13__RTC__680_MOURNING__190__M__1": "Güzel. Sizi buradan çıkarıyorum.",
"VO__LUCAS__CH13__RTC__682_EPAULE__010__M__1": "Kolun mu?",
"VO__LUCAS__CH13__RTC__682_EPAULE__030__M__1": "Onu yerine oturtmalıyız.",
"VO__LUCAS__CH13__RTC__682_EPAULE__050__M__1": "Kımıldama. Acıyacak.",
"VO__LUCAS__CH13__RTC__682_EPAULE__070__M__1": "İyi misin?",
"VO__LUCAS__CH13__RTC__682_EPAULE__080__M__1": "Hadi.",
"VO__LUCAS__CH13__RTC__682_EPAULE__090__M__1": "Hugo, gidelim.",
"VO__LUCAS__CH13__RTC__685_RATS_NEST__005__M__1": "Sıkıştı! Çok yüksek!",
"VO__LUCAS__CH13__RTC__685_RATS_NEST__015__M__1": "Amicia, itelim de arkasında ne var görelim.",
"VO__LUCAS__CH13__RTC__685_RATS_NEST__020__M__1": "Alevleri söndürdü...",
"VO__LUCAS__CH13__RTC__685_RATS_NEST__055__M__1": "Güneş Katili...",
"VO__LUCAS__CH13__RTC__685_RATS_NEST__065__M__1": "Işık Yutan! Eski metinlerin söz ettiği Nebula bu!",
"VO__LUCAS__CH13__RTC__685_RATS_NEST__075__M__1": "Gerçekmiş...",
"VO__LUCAS__CH13__RTC__685_RATS_NEST__110__M__1": "O değil bu Amicia! Konuşan Macula, annenin ölümünün bıraktığı boşluğu doldurmaya çalışıyor!",
"VO__LUCAS__CH13__RTC__685_RATS_NEST__140__M__1": "HAYIR! YETER! Bu lanet kayalıktan ayrılıp onu buradan uzaklaştırmamız gerek!",
"VO__LUCAS__CH13__RTC__685_RATS_NEST__150__M__1": "Boğuluyor, Amicia! Odaklan! Karşı koymalısın. Onunla konuş, su yüzünde tut. SANA ihtiyacı var!",
"VO__LUCAS__CH13__RTC__685_RATS_NEST__170__M__1": "Onu buradan çıkaralım!",
"VO__LUCAS__CH13__RTC__700_HOME__010__M__1": "Olamaz...",
"VO__LUCAS__CH13__RTC__700_HOME__070__M__1": "Evet.",
"VO__LUCAS__CH13__RTC__700_HOME__150__M__1": "Onu çok öfkelendirdin!",
"VO__LUCAS__CH13__RTC__700_HOME__160__M__1": "Geliyorlar! Koş!",
"VO__LUCAS__CH13__RTC__720_EXIT_NEST__010__M__1": "Nefes al... Nefes al...",
"VO__LUCAS__CH13__RTC__720_EXIT_NEST__060__M__1": "Evet. Hazırım.",
"VO__LUCAS__CH13__RTC__780_ARNAUD__010__M__1": "Şurada bir tekne var...",
"VO__LUCAS__CH13__RTC__790_RESCUE__085__M__1": "Hugo onun olduğunu söylüyor.",
"VO__SOLDIER_B1__CH13__CHATTER__ABOUT_COUNT__020__M__1": "Henüz bir şey yok. Kont eşini gömüyordur.",
"VO__SOLDIER_B1__CH13__CHATTER__ABOUT_COUNT__025__M__1": "Korkunç olmalı. Yakaladıkları insanlara neler yaptıklarını görünce...",
"VO__SOLDIER_B1__CH13__CHATTER__ABOUT_FUTURE__020__M__1": "Çocuk bunu düzeltecek!",
"VO__SOLDIER_B1__CH13__CHATTER__ABOUT_FUTURE__040__M__1": "Bunu ONUN yüzünden yaptı! Ama Kont ona öğretecek. Dünyaya nasıl ışık saçacağını gösterecek!",
"VO__SOLDIER_B1__CH13__CHATTER__SOLDIERS_IDLE_1__010__M__1": "Kont'un başına gelen korkunç...",
"VO__SOLDIER_B2__CH13__CHATTER__ASK_REINFORCE_1__010__M__1": "Bana gelin! Her adam derhâl burada olsun!",
"VO__SOLDIER_B2__CH13__CHATTER__ASK_REINFORCE_3__010__M__1": "Ne yapıyorsunuz?! Saldırın! Saldırın!",
"VO__SOLDIER_B2__CH13__CHATTER__FIRST_SHOT__020__M__1": "Ne?! O kadın! Kirletici! Çocuk onda! Onu elinden alın!",
"VO__SOLDIER_B2__CH13__CHATTER__HEAVY_DEAD__020__M__1": "Burada daha çok adam lazım! Korkma, Çocuk! Seni dürüst Baban'a geri götüreceğiz!",
"VO__SOLDIER_B2__CH13__CHATTER__HEAVY_INCOMING__010__M__1": "Sen! Pis zavallı! Kontesimiz ışığın hizmetkârıydı! Ve sen onu katlettin!",
"VO__SOLDIER_B2__CH13__CHATTER__HEAVY_INCOMING__030__M__1": "Bu adayı mahvettin!",
"VO__SOLDIER_B2__CH13__CHATTER__MORE_WAVE_1__010__M__1": "Hadi! Yakalayın onları! Diğerlerini uyarın!",
"VO__SOLDIER_B2__CH13__CHATTER__MORE_WAVE_1__030__M__1": "Arles Kontu Victor için! Köz Çocuğu için!",
"VO__SOLDIER_B2__CH13__CHATTER__MORE_WAVE_2__010__M__1": "Bu sadece bizim için değil! Bu Çocuk tüm dünyaya ait! O bizim geleceğimiz! Onun için savaşın!",
"VO__SOLDIER_N1__CH13__CHATTER__BEFORE_EXECUTION__015__M__1": "Burası paramparça oluyor! Cellatın canı cehenneme!",
"VO__SOLDIER_N1__CH13__CHATTER__BELFRY_FALL__030__M__1": "Emredersiniz, efendim!",
"VO__SOLDIER_N1__CH13__CHATTER__FURIOUS_RATSTRIKE_INTRO__020__M__1": "İşte bu kadar! Bitti! Yeterince zarar verdin!",
"VO__SOLDIER_N1__CH13__CHATTER__FURIOUS_RATSTRIKE_INTRO__030__M__1": "Çocuğu teslim et, sana çabuk bir ölüm bağışlayalım!",
"VO__SOLDIER_N1__CH13__CHATTER__IDLE_ABOUT_MILO__010__M__1": "Hey! Milo'yu duydun mu?",
"VO__SOLDIER_N1__CH13__CHATTER__IDLE_ABOUT_MILO__030__M__1": "Öldü. Sığınağı, adamları, köleler... Hepsi yok! Bu karmaşanın orada başladığını söylüyorlar! Kirletici'nin bunun için Çocuğu kullandığını söylüyorlar.",
"VO__SOLDIER_N1__CH13__CHATTER__PUSH_FORWARD_1__020__M__1": "Buradalar! Durdurun onları!",
"VO__SOLDIER_N1__CH13__CHATTER__SOLDIERS__010__M__1": "Lanet! Hissettin mi?! O sarsıntı yağ küplerini paramparça etti!",
"VO__SOLDIER_N1__CH13__CHATTER__SOLDIERS__040__M__1": "Bu, o Kirletici kızın etkisi altında olduğu için oldu! Kont onun ne pahasına olursa olsun ölmesini bu yüzden istiyor!",
"VO__SOLDIER_N1__CH13__CHATTER__SOLDIERS_IDLE_1__020__M__1": "Toparlanır. Ölümü tanır. Unutma, savaş görmüş biri. Adam yüzlerce muharebede şan kazandı.",
"VO__SOLDIER_N1__CH13__CHATTER__SOLDIERS_IDLE_2__020__M__1": "Köz Çocuğu'nu bulana dek olmaz!",
"VO__SOLDIER_N1__CH13__CHATTER__SOLDIERS_IDLE_2__040__M__1": "O zaman buna değmiş olur! Görevine odaklan!",
"VO__SOLDIER_N1__CH13__CHATTER__UPSTAIRS_SOLDIER__010__M__1": "Çocuk bizden vazgeçmiş olamaz. Onun için verdiğimiz onca şeyden sonra olmaz! Çok genç... çok savunmasız... evet. Kont bir çaresini bulacaktır.",
"VO__SOLDIER_N1__CH13__RTC__780_ARNAUD__050__M__1": "Kontesimizin öldüğüne inanamıyorum! Kont o kadar yıkılmış ki asılışta bile bulunmayacakmış. Arnaud için liman meydanına bir darağacı kurdular.",
"VO__SOLDIER_N1__CH13__RTC__780_ARNAUD__085__M__1": "Evet, ben de!",
"VO__SOLDIER_N2__CH13__CHATTER__ABOUT_COUNT__010__M__1": "Saraydan haber var mı?",
"VO__SOLDIER_N2__CH13__CHATTER__ABOUT_COUNT__030__M__1": "Evet. Bizim de ölülerimiz var. Çoğu da düzgün bir mezar bulamayacak.",
"VO__SOLDIER_N2__CH13__CHATTER__ABOUT_FUTURE__010__M__1": "Aydınlık günler de neymiş! Burası tam bir cehenneme dönmüş!",
"VO__SOLDIER_N2__CH13__CHATTER__ABOUT_FUTURE__030__M__1": "Bunu Çocuk yaptı!",
"VO__SOLDIER_N2__CH13__CHATTER__ABOUT_FUTURE__050__M__1": "Umarım onu görecek kadar yaşarım.",
"VO__SOLDIER_N2__CH13__CHATTER__ASK_REINFORCE_2__010__M__1": "Takviye! Hemen! Öldürün şu kızı!",
"VO__SOLDIER_N2__CH13__CHATTER__BEFORE_EXECUTION__030__M__1": "Öldürün şu kasabı!",
"VO__SOLDIER_N2__CH13__CHATTER__BELFRY_FALL__020__M__1": "Öyle dikilip izlemeyin! Kıpırdayın! Tek çıkış yolları burası ve vakitleri bizimki kadar kısa! Devriye gezmeye devam edin! Çocuğu Kirletici'nin elinden alın!",
"VO__SOLDIER_N2__CH13__CHATTER__PUSH_FORWARD_1__030__M__1": "Öldürün Kirletici'yi! Ne pahasına olursa olsun Çocuğu alın!",
"VO__SOLDIER_N2__CH13__CHATTER__VISTA_GALLOW__030__M__1": "Duvar bu mu?... Şimdi bir bok yığınından farkı yok!",
"VO__SOLDIER_N2__CH13__CHATTER__VISTA_GALLOW_UP__030__M__1": "Kont'un bunu görmek için burada olmaması ne kötü!",
"VO__SOLDIER_N2__CH13__RTC__780_ARNAUD__080__M__1": "Duvar'ı mı asıyorlar? Kahretsin! Bunu görmek isterdim!",
"VO__SOLDIER_N3__CH13__CHATTER__BELFRY_FALL__010__M__1": "Dikkat!",
"VO__SOLDIER_N3__CH13__CHATTER__FURIOUS_RATSTRIKE_INTRO__050__M__1": "Seni kurtarmaya geldik, Çocuk!",
"VO__SOLDIER_N3__CH13__CHATTER__SOLDIERS_ATTACK_1__010__M__1": "Oğlana zarar vermeyin! O bizim kurtuluşumuzun anahtarı!",
"VO__SOLDIER_S1__CH13__CHATTER__BEFORE_EXECUTION__035__M__1": "Ölecek, tamam mı?! Şimdi kapa şu çeneni!",
"VO__SOLDIER_S1__CH13__CHATTER__SOLDIERS__030__M__1": "Çocuğu neden hâlâ istiyoruz ki? Sonumuz olacak! Her şeyi mahvetti!",
"VO__SOLDIER_S1__CH13__CHATTER__SOLDIERS__050__M__1": "Ha... umarım işe yarar...",
"VO__SOLDIER_S1__CH13__CHATTER__SOLDIERS_IDLE_2__010__M__1": "Ne zaman tahliye edeceğimizi bilen var mı?",
"VO__SOLDIER_S1__CH13__CHATTER__SOLDIERS_IDLE_2__030__M__1": "Ya ondan önce zemin tamamen çökerse?!",
"VO__SOLDIER_S2__CH13__CHATTER__BEFORE_EXECUTION__020__M__1": "Çok haklısın! Bu alçak benim yoldaşlarımı öldürdü! Gerekirse kendi elimle yaparım!",
"VO__SOLDIER_S2__CH13__CHATTER__IDLE_ABOUT_MILO__020__M__1": "Köle tüccarı mı? Ne olmuş ona?",
"VO__SOLDIER_S2__CH13__CHATTER__IDLE_ABOUT_MILO__040__M__1": "Adamı sevmezdim ama... o kız tam bir ifrit...",
"VO__SOLDIER_S2__CH13__CHATTER__VISTA_GALLOW__020__M__1": "Kolyen nasıl, Arnaud?",
"VO__SOLDIER_S2__CH13__CHATTER__VISTA_GALLOW_UP__010__M__1": "Gördünüz mü, çocuklar?!... O böğüren domuz şimdi sessiz sedasız...",
"VO__SOLDIER_S2__CH13__CHATTER__VISTA_GOAL__010__M__1": "Çan kulesi! Yıkılıyor!",
"VO__SOPHIA__CH13__RTC__795_GREATEST_GIFT__020__M__1": "Amma da ağırdan aldın! Gemiye binin!",
"VO__SOPHIA__CH13__RTC__795_GREATEST_GIFT__030__M__1": "Git bir köşede yığıl.",
"VO__SOPHIA__CH13__RTC__795_GREATEST_GIFT__040__M__1": "Dur, peki ya annen?",
"VO__SOPHIA__CH13__RTC__795_GREATEST_GIFT__070__M__1": "Anlıyorum... Bundan sonrasını ben hallederim...",
"VO__SOPHIA__CH13__RTC__795_GREATEST_GIFT__080__M__1": "Sen! Gel!",
}
