# -*- coding: utf-8 -*-
# CH11 VO - kaynak proper Turkce; build asamasinda SUB uygulanir.
T = {
"VO__AMICIA__CH11__CHATTER__2ND_TANK_EXPLOSION__010__M__1": "Yine bir fıçı mı?",
"VO__AMICIA__CH11__CHATTER__2ND_TANK_EXPLOSION__040__M__1": "Herkes iyi mi?",
"VO__AMICIA__CH11__CHATTER__2ND_TWISTED_DOOR__030__M__1": "Hım... Şöyle bir bakınalım.",
"VO__AMICIA__CH11__CHATTER__ACTIVATE_BREAK__020__M__1": "Hımm... Sanırım bu bir fren. Çubuğu yerinde tutmak için.",
"VO__AMICIA__CH11__CHATTER__AFTER_EXPLOSION__010__M__1": "Açıldı... galiba!",
"VO__AMICIA__CH11__CHATTER__AFTER_EXPLOSION__030__M__1": "Çünkü ben de... onun kadar çaresizim de ondan?",
"VO__AMICIA__CH11__CHATTER__AFTER_EXPLOSION__050__M__1": "Şey...",
"VO__AMICIA__CH11__CHATTER__BARRELS__010__M__1": "O da ne?",
"VO__AMICIA__CH11__CHATTER__BARRELS__030__M__1": "Zaten çoktan gitmiş. Devam edelim.",
"VO__AMICIA__CH11__CHATTER__BEAM_WALK__020__M__1": "Seni yukarı iteceğim! Devam et!",
"VO__AMICIA__CH11__CHATTER__BODIES_GROUND__020__M__1": "Düzen'in muhafızları, herhâlde. Aelia'nın izini yine bulduk.",
"VO__AMICIA__CH11__CHATTER__BODIES_GROUND__040__M__1": "Üstüne gitmişler, sanırım.",
"VO__AMICIA__CH11__CHATTER__BRIDGE_COLLAPSE__020__M__1": "Koşmaya devam et! Arkana bakma!",
"VO__AMICIA__CH11__CHATTER__BRIDGE_INCOMING__020__M__1": "Evet... Evet! Nihayet!",
"VO__AMICIA__CH11__CHATTER__BRIDGE_MISSING__010__M__1": "Sonuna kadar gidiyor gibi...",
"VO__AMICIA__CH11__CHATTER__BRIDGE_MISSING__030__M__1": "Evet...",
"VO__AMICIA__CH11__CHATTER__BRIDGE_MISSING__050__M__1": "Tamam...",
"VO__AMICIA__CH11__CHATTER__BRIDGEIN__005__M__1": "Aman... vay... Bu nasıl mümkün olabilir ki?",
"VO__AMICIA__CH11__CHATTER__BRIDGEIN__015__M__1": "Şuradaki kapı bize söyleyecek!",
"VO__AMICIA__CH11__CHATTER__BRIDGEPUZZLE_2LIGHT_FAR__020__M__1": "Şimdi düşünmem lazım... Şu öteki ışık o kadar yakın ki.",
"VO__AMICIA__CH11__CHATTER__BRIDGEPUZZLE_ADD_SWITCH__010__M__1": "Rayda bir ayrım var... Yönü değiştirelim...",
"VO__AMICIA__CH11__CHATTER__BRIDGEPUZZLE_EAST_BLOCKED__010__M__1": "Ha... Köprü hemen ötede.",
"VO__AMICIA__CH11__CHATTER__BRIDGEPUZZLE_EAST_BLOCKED__030__M__1": "Bilmiyorum. Başka bir açı lazım. Geri dönüp bakalım.",
"VO__AMICIA__CH11__CHATTER__BRIDGEPUZZLE_END__010__M__1": "Geldik... Başardık!",
"VO__AMICIA__CH11__CHATTER__BRIDGEPUZZLE_END__030__M__1": "Evet... İlerleyelim.",
"VO__AMICIA__CH11__CHATTER__BRIDGEPUZZLE_RIGHT_HUGO__010__M__1": "Güvendeyiz... bu ateşler durdukça...",
"VO__AMICIA__CH11__CHATTER__BRIDGEPUZZLE_WEST_END__010__M__1": "Sıkıştı!",
"VO__AMICIA__CH11__CHATTER__BRIDGERATS__010__M__1": "Ne?! Hayır, hayır!",
"VO__AMICIA__CH11__CHATTER__BRIDGERATS__020__M__1": "Dur, dur!... Şu ateşler... Şu raylar! Bütün bunları onları uzak tutmak için yapmışlar!",
"VO__AMICIA__CH11__CHATTER__BRIDGERATS__060__M__1": "Evet! Bir yol açabiliriz!",
"VO__AMICIA__CH11__CHATTER__CANT_GO__020__M__1": "Lütfen, biliyorum...",
"VO__AMICIA__CH11__CHATTER__CANT_GO__040__M__1": "Gel...",
"VO__AMICIA__CH11__CHATTER__CANT_GO_INTERACT__010__M__1": "Seni taşırım. Bunu birlikte yapacağız.",
"VO__AMICIA__CH11__CHATTER__CANT_GO_INTERACT__030__M__1": "Bunu yapacağız. Birlikte.",
"VO__AMICIA__CH11__CHATTER__CARRYING_HUGO__010__M__1": "Bunları yaşamak zorunda kaldığın için üzgünüm. Senin için yapıyorum.",
"VO__AMICIA__CH11__CHATTER__CARRYING_HUGO__030__M__1": "Ona kavuşacaksın. Ama önce yaşaman gerek. Sana ihtiyacım var.",
"VO__AMICIA__CH11__CHATTER__CARRYING_HUGO__050__M__1": "Dur. Yaşayacaksın. Savaşacağız. Dayanacağız.",
"VO__AMICIA__CH11__CHATTER__CART_BLOCKER__010__M__1": "Bir kiriş...",
"VO__AMICIA__CH11__CHATTER__CART_BLOCKER__030__M__1": "Onu oynatmanın bir yolu lazım...",
"VO__AMICIA__CH11__CHATTER__CART_EXPLOSION__010__M__1": "Öf!",
"VO__AMICIA__CH11__CHATTER__CART_EXPLOSION_OK__040__M__1": "Tıkırında, sağ ol. Arabaya geri dönüyorum!",
"VO__AMICIA__CH11__CHATTER__CART_LEVER_BAR_OK__010__M__1": "Bir çubuk tamam, şimdi gerisi...",
"VO__AMICIA__CH11__CHATTER__CART_RESTING__030__M__1": "Bu... tehlikeli görünüyor.",
"VO__AMICIA__CH11__CHATTER__CART_ROLLING__010__M__1": "Hadi bakalım!",
"VO__AMICIA__CH11__CHATTER__CART_WONT_MOVE__010__M__1": "Tıkanmış!",
"VO__AMICIA__CH11__CHATTER__CARTPUZZLE_CRANK__020__M__1": "Bir bakalım...",
"VO__AMICIA__CH11__CHATTER__CARTPUZZLE_CRANK_AMICIAFIRST__010__M__1": "Demir kafesi açıyor!",
"VO__AMICIA__CH11__CHATTER__CAVE_SLOPE__010__M__1": "Göreceğiz!...",
"VO__AMICIA__CH11__CHATTER__CAVE_SQUEEZE_AFTER__010__M__1": "Dikkatli ol. Hugo... Tam arkamda kal.",
"VO__AMICIA__CH11__CHATTER__CAVE_SQUEEZE_AFTER__030__M__1": "Merak etme, yüzyıllardır ayakta.",
"VO__AMICIA__CH11__CHATTER__CAVE_SQUEEZE_BEFORE__010__M__1": "Arkada boşluk var, oradan geçmeyi deneyelim.",
"VO__AMICIA__CH11__CHATTER__CHAIN_DOWN__020__M__1": "Şu zincirler! Köprüyü onlar idare ediyor!",
"VO__AMICIA__CH11__CHATTER__CHAIN_DOWN_BIS__020__M__1": "Tamam, ilerlemeye devam edip ne yapabileceğime bakacağım!",
"VO__AMICIA__CH11__CHATTER__CHAIN_SHOOT__010__M__1": "Lütfen işe yara...",
"VO__AMICIA__CH11__CHATTER__CHAIN_STUCKED__010__M__1": "Şimdi... Nasıl geri döneceğim?",
"VO__AMICIA__CH11__CHATTER__CHEST_THERE__020__M__1": "Mükemmel! Kendimi... kuşatılmış hissediyorum!",
"VO__AMICIA__CH11__CHATTER__CISTERN_AMICIA_CHAINS_1__013__M__1": "Dur. Şu zincirler... Karşı ağırlıklar... Köprü parçalarını onlar kaldırıyor!",
"VO__AMICIA__CH11__CHATTER__CISTERN_AMICIA_CHAINS_2__017__M__1": "Bunlar hâlâ yukarıda!",
"VO__AMICIA__CH11__CHATTER__CISTERN_AMICIA_DOWN__010__M__1": "İşe yarayabilir... Önce ben deneyeyim...",
"VO__AMICIA__CH11__CHATTER__CISTERN_ENTRANCE__005__M__1": "O da ne?!",
"VO__AMICIA__CH11__CHATTER__CISTERN_ENTRANCE__030__M__1": "Bir bakalım...",
"VO__AMICIA__CH11__CHATTER__CISTERN_GOING_DOWN__020__M__1": "Hayır! Sadece... biraz sarsıldım, ama artık biliyoruz... Kötü bir fikirdi.",
"VO__AMICIA__CH11__CHATTER__CISTERN_GOING_DOWN__030__M__1": "Etrafa bakıp ne yapabileceğime bakacağım! Beni bekleyin!",
"VO__AMICIA__CH11__CHATTER__CISTERN_LEVER__010__M__1": "Ah...",
"VO__AMICIA__CH11__CHATTER__CISTERN_LEVER__040__M__1": "Devam edelim.",
"VO__AMICIA__CH11__CHATTER__CLIMB_BURST__010__M__1": "Tanrım! Tırman! Çabuk!",
"VO__AMICIA__CH11__CHATTER__COLLAPSE__020__M__1": "Hâlâ başarabiliriz!",
"VO__AMICIA__CH11__CHATTER__CONTINUE__010__M__1": "Hadi...",
"VO__AMICIA__CH11__CHATTER__CONTINUE__030__M__1": "Gerçekten mi?...",
"VO__AMICIA__CH11__CHATTER__CONTINUE__100__M__1": "Teşekkürler, Sophia...",
"VO__AMICIA__CH11__CHATTER__CONTINUE_RATS_END__010__M__1": "Güzel...",
"VO__AMICIA__CH11__CHATTER__CONTINUE_RATS_END__030__M__1": "Şimdilik...",
"VO__AMICIA__CH11__CHATTER__CORRIDOR__010__M__1": "Ah...",
"VO__AMICIA__CH11__CHATTER__CORRIDOR__030__M__1": "Sıçan yuvası... Ama hava çok daha ağır...",
"VO__AMICIA__CH11__CHATTER__CORRIDOR__050__M__1": "Basilius'tan... beri mi?",
"VO__AMICIA__CH11__CHATTER__CORRIDOR__070__M__1": "Başın mı?",
"VO__AMICIA__CH11__CHATTER__CORRIDOR__090__M__1": "Cesaret...",
"VO__AMICIA__CH11__CHATTER__CROSSING_CART__010__M__1": "Bir pamuk ipliğine bağlı... Tanrım, umarım yanılmıyorumdur...",
"VO__AMICIA__CH11__CHATTER__CROSSING_CART__030__M__1": "Elbette yapacağım! Bütün bunlara değdireceğim, Hugo!",
"VO__AMICIA__CH11__CHATTER__CROSSING_CART__050__M__1": "Hayır, yapacağım. Bunu yapacağım!",
"VO__AMICIA__CH11__CHATTER__CROSSING_CART__070__M__1": "Hadi, Basilius, bize bir şey ver. O buna değer, söz veriyorum. Yalvarırım.",
"VO__AMICIA__CH11__CHATTER__DOOR__020__M__1": "Ne karmaşa... Burada ne olmuş?...",
"VO__AMICIA__CH11__CHATTER__DOOR__050__M__1": "Bence... patlatılarak açılmışlar...",
"VO__AMICIA__CH11__CHATTER__DOOR__065__M__1": "Gerisine bakalım...",
"VO__AMICIA__CH11__CHATTER__DOOR__070__M__1": "Bunu kim yaptı?...",
"VO__AMICIA__CH11__CHATTER__DOOR_BLOCKED__020__M__1": "O olmalı! Aelia... Şapelden kaçmış...",
"VO__AMICIA__CH11__CHATTER__DOOR_BLOCKED__040__M__1": "Basilius'u geri almak istemiş... Zorla yol açmış! İzindeyiz!",
"VO__AMICIA__CH11__CHATTER__DOOR_RIGHT__010__M__1": "Şu kapıda onun izi var... Arkasından çökmüş gibi...",
"VO__AMICIA__CH11__CHATTER__DOOR_RIGHT__030__M__1": "Bunu nasıl açacağız?",
"VO__AMICIA__CH11__CHATTER__DOOR_STUCK__010__M__1": "Sıkışmış.",
"VO__AMICIA__CH11__CHATTER__EXPLORE__030__M__1": "Hayır! Hayır, hayır, hayır!",
"VO__AMICIA__CH11__CHATTER__FEATHER_INTERACT__010__M__1": "Bak...",
"VO__AMICIA__CH11__CHATTER__FEATHER_INTERACT__040__M__1": "Demek ki burada yalnız değiliz...",
"VO__AMICIA__CH11__CHATTER__FEATHER_INTERACT__060__M__1": "Aynen. Devam edelim, belki görürüz? Eğer... fazla korkmadıysa...",
"VO__AMICIA__CH11__CHATTER__FEATHER_SPOT__010__M__1": "İnanılmaz...",
"VO__AMICIA__CH11__CHATTER__FIRE_LINE__010__M__1": "Dur... Bir şeyler oluyor.",
"VO__AMICIA__CH11__CHATTER__FIRST_PULL_BEGIN__010__M__1": "Tamam, bu mangallar kımıldatılabiliyor...",
"VO__AMICIA__CH11__CHATTER__FIRST_PULL_BEGIN__030__M__1": "Düzen sıçanlarla nasıl baş edileceğini biliyor...",
"VO__AMICIA__CH11__CHATTER__FIRST_PULL_OVER__010__M__1": "Bu da bir şey...",
"VO__AMICIA__CH11__CHATTER__FIRST_PUSH__010__M__1": "Hadi!",
"VO__AMICIA__CH11__CHATTER__FIRST_PUSH_START__010__M__1": "Güzel, itilebiliyorlar da! Bir el atar mısın?",
"VO__AMICIA__CH11__CHATTER__GATE_AELIA__010__M__1": "Aelia... Umarım senden daha şanslı olurum...",
"VO__AMICIA__CH11__CHATTER__GATE_APPROACH__010__M__1": "Lütfen... Bize bir şey ver...",
"VO__AMICIA__CH11__CHATTER__GATE_CART__010__M__1": "Bir araba mı? Burada ne işi var?...",
"VO__AMICIA__CH11__CHATTER__GATE_CART_ALONE__010__M__1": "Bunu açık tutmak için yardım lazım...",
"VO__AMICIA__CH11__CHATTER__GATE_CART_LEVER_CONNECTED__010__M__1": "İşe yarıyor!",
"VO__AMICIA__CH11__CHATTER__GATE_CART_OPENED__010__M__1": "Üzerine bir sırık bağlı... Bir işe yarıyor olmalı...",
"VO__AMICIA__CH11__CHATTER__GATE_DONE__010__M__1": "Sanırım işe yaradı... Bırakabiliriz!",
"VO__AMICIA__CH11__CHATTER__GATE_HUGO_REUNITED__010__M__1": "Daha iyi misin?",
"VO__AMICIA__CH11__CHATTER__GATE_LOST__010__M__1": "Bu kapıyı kaç kişi çalıştırıyormuş? Ona geri dönmek lazım...",
"VO__AMICIA__CH11__CHATTER__GATE_OPENING__010__M__1": "İşliyor...",
"VO__AMICIA__CH11__CHATTER__GATE_OPENING__016__M__1": "Öf... Bu koku da ne?!",
"VO__AMICIA__CH11__CHATTER__GATE_OPENING__030__M__1": "Hayır... Basilius'u bulacağız...",
"VO__AMICIA__CH11__CHATTER__GATE_OPENING__060__M__1": "Hayır... Hayır, hayır... O kapıdan geçeceğiz, hep birlikte!",
"VO__AMICIA__CH11__CHATTER__GATE_OPENING_INTERACT__010__M__1": "Hadi! Bu çok önemli!",
"VO__AMICIA__CH11__CHATTER__GATE_READY__010__M__1": "Şunu açalım, Sophia.",
"VO__AMICIA__CH11__CHATTER__GATE_START__010__M__1": "Peki... nereden başlıyoruz?",
"VO__AMICIA__CH11__CHATTER__GOING_DOWN_1__010__M__1": "Hugo... her şeyi yoluna koymadan önce... yaşaman gerek...",
"VO__AMICIA__CH11__CHATTER__GOING_DOWN_1__030__M__1": "Ama bunu bilerek yapmıyorsun!",
"VO__AMICIA__CH11__CHATTER__GOING_DOWN_1__050__M__1": "Sen... Sen bir çocuksun...",
"VO__AMICIA__CH11__CHATTER__GOING_DOWN_1__080__M__1": "Evet...",
"VO__AMICIA__CH11__CHATTER__GOING_DOWN_2__050__M__1": "Yaklaşıyoruz. Belki Basilius...",
"VO__AMICIA__CH11__CHATTER__GOING_DOWN_2__070__M__1": "Yakınız! O aşağıdaysa, seni kurtarabilecek şey de orada!",
"VO__AMICIA__CH11__CHATTER__GOING_DOWN_2__090__M__1": "Dur! Bana güvenmen gerek!",
"VO__AMICIA__CH11__CHATTER__GRABBING_TANK__010__M__1": "Yavaş ol...",
"VO__AMICIA__CH11__CHATTER__GREEK_FIRE_PASS__010__M__1": "Hey! Buradayım!",
"VO__AMICIA__CH11__CHATTER__GREEK_FIRE_PASS__060__M__1": "Mükemmel!",
"VO__AMICIA__CH11__CHATTER__HALL_PUZZLE_DONE__010__M__1": "Yine Düzen muhafızları...",
"VO__AMICIA__CH11__CHATTER__HALL_PUZZLE_DONE__020__M__1": "Onlarla tek başına başa çıkmış, inanamıyorum...",
"VO__AMICIA__CH11__CHATTER__HALL_PUZZLE_DONE__040__M__1": "Çok... kararlıymış. O, onun için... her şeymiş.",
"VO__AMICIA__CH11__CHATTER__HALL_PUZZLE_DONE__060__M__1": "Ne olduğunu... biliyor musun?",
"VO__AMICIA__CH11__CHATTER__HALL_PUZZLE_DONE__080__M__1": "Tanrım... Umarım başarmıştır.",
"VO__AMICIA__CH11__CHATTER__HALLWAY__010__M__1": "Neler oluyor?",
"VO__AMICIA__CH11__CHATTER__HALLWAY__030__M__1": "Ama mecburuz. Mecburuz...",
"VO__AMICIA__CH11__CHATTER__HALLWAY_BACKTRACK__020__M__1": "Hayır, sadece çıkış yolunu kontrol ediyorum. Buraya ne için geldiysek bitirelim.",
"VO__AMICIA__CH11__CHATTER__HUB3_CART_PULL__010__M__1": "Hazır... ol!",
"VO__AMICIA__CH11__CHATTER__HUB3_FESTIVAL_BACK__045__M__1": "Hayır!",
"VO__AMICIA__CH11__CHATTER__HUB3_FESTIVAL_BACK__080__M__1": "Bitti... Yürüyelim... Gel...",
"VO__AMICIA__CH11__CHATTER__HUB3_FESTIVAL_CARTFREE__010__M__1": "Ona yakın duralım!",
"VO__AMICIA__CH11__CHATTER__HUB3_FESTIVAL_CARTMOVING__020__M__1": "Yaklaşıyoruz... Harita... Taşıyıcı... Anahtar o...",
"VO__AMICIA__CH11__CHATTER__HUB3_FESTIVAL_CARTMOVING__040__M__1": "Geriye bir şey kalmış olmalı! Seni kurtaracak bir şey!",
"VO__AMICIA__CH11__CHATTER__HUB3_FESTIVAL_CARTMOVING__060__M__1": "Böyle deme... Sen... her şeysin.",
"VO__AMICIA__CH11__CHATTER__HUB3_FESTIVAL_CARTMOVING__100__M__1": "Haklı, Hugo. Başka hiçbir şeyimiz yok.",
"VO__AMICIA__CH11__CHATTER__HUB3_GRASS__010__M__1": "Sadece alevlere dikkat et...",
"VO__AMICIA__CH11__CHATTER__HUB3_IDLE_MAP__020__M__1": "Düşününce... var olduğunu bile bilmiyorduk...",
"VO__AMICIA__CH11__CHATTER__HUB3_MAP_AMPHI__030__M__1": "Evet... Aşağıda olmalı. Harita giriş noktası olabilir.",
"VO__AMICIA__CH11__CHATTER__HUB3_MAP_AMPHI__050__M__1": "Sanırım öyle...",
"VO__AMICIA__CH11__CHATTER__HUB3_MAP_CLOSE__005__M__1": "Geldik... Nihayet...",
"VO__AMICIA__CH11__CHATTER__HUB3_MAP_CLOSE__020__M__1": "Şimdi, Basilius... neredesin?",
"VO__AMICIA__CH11__CHATTER__HUB3_PUZZLE_CART__010__M__1": "Bu duracak.",
"VO__AMICIA__CH11__CHATTER__HUB3_PUZZLE_CART__030__M__1": "Hugo...",
"VO__AMICIA__CH11__CHATTER__HUB3_PUZZLE_CART__050__M__1": "Evet... bizi koruyacak.",
"VO__AMICIA__CH11__CHATTER__HUB3_START__010__M__1": "Bu yakında bitecek, Hugo.",
"VO__AMICIA__CH11__CHATTER__HUB3_START__030__M__1": "Sıçanların cehenneme gitmekten başka çaresi kalmayacak.",
"VO__AMICIA__CH11__CHATTER__HUB3_TORCH_LEDGE__010__M__1": "Yukarıda... Orada.",
"VO__AMICIA__CH11__CHATTER__HUB3_VILLAGE__010__M__1": "Hadi!",
"VO__AMICIA__CH11__CHATTER__KEEP_UP__020__M__1": "Çalışıyorum! Hemen peşimizdeler!",
"VO__AMICIA__CH11__CHATTER__LADDER_INSIDE__020__M__1": "Hadi bakalım...",
"VO__AMICIA__CH11__CHATTER__LADDER_INSIDE__040__M__1": "İşe yaradı mı?",
"VO__AMICIA__CH11__CHATTER__LADDER_OUTSIDE__020__M__1": "Yaparım, merak etme! Lütfen... kolay bir yol olsun...",
"VO__AMICIA__CH11__CHATTER__LAST_CART_PUSH__030__M__1": "Ben koca kız oldum artık!",
"VO__AMICIA__CH11__CHATTER__LAST_CART_PUSH_START__010__M__1": "Kaldığımız yere dönelim...",
"VO__AMICIA__CH11__CHATTER__LAST_CART_PUSH_START__020__M__1": "Şimdi odaklan. Basilius'u bul. Ne bulursan al ve çık. Sonra... Sonra o yaşayacak.",
"VO__AMICIA__CH11__CHATTER__LAST_RUN__010__M__1": "O köprünün ötesinde ne olduğunu görmek için sabırsızlanıyorum...",
"VO__AMICIA__CH11__CHATTER__LAST_RUN__030__M__1": "Nasıl olmasın? Her şey burayı işaret ediyor! Aelia bizi buraya getirdi...",
"VO__AMICIA__CH11__CHATTER__LAST_RUN__050__M__1": "Ve elimizdeki tek şey onlar! Gerçek!",
"VO__AMICIA__CH11__CHATTER__LAST_RUN__100__M__1": "Hadi, Hugo, neredeyse vardık...",
"VO__AMICIA__CH11__CHATTER__LAST_RUN__120__M__1": "Eminim ki... Hugo'nun bu adayı rüyasında görmesinin sebebi bu Taşıyıcı, bundan eminim... Ama en çok da başka seçeneğimiz olmadığından eminim!",
"VO__AMICIA__CH11__CHATTER__LAST_RUN__140__M__1": "Hayır, gerçekten üzgünüm. Ama bunu yapmak zorundayız.",
"VO__AMICIA__CH11__CHATTER__LAST_RUN__160__M__1": "Değilim. Ben... senin için üzülüyorum.",
"VO__AMICIA__CH11__CHATTER__LEFT_PATH_NEW__010__M__1": "Buraya kadarmış.",
"VO__AMICIA__CH11__CHATTER__LEFT_PATH_NEW__030__M__1": "Bir bakayım...",
"VO__AMICIA__CH11__CHATTER__LEFT_PATH_RIGHT_DONE__010__M__1": "Buraya kadarmış.",
"VO__AMICIA__CH11__CHATTER__LEFT_PATH_RIGHT_DONE__030__M__1": "Bir bakayım...",
"VO__AMICIA__CH11__CHATTER__LEVER_BOTH__010__M__1": "Şu yerdeki kol artık tamamen çıkmış görünüyor! Bir deneyelim!",
"VO__AMICIA__CH11__CHATTER__LEVER_LEFT__010__M__1": "Bu, üst ve alt çubukları açıyor.",
"VO__AMICIA__CH11__CHATTER__LEVER_LEFT_OR_RIGHT__010__M__1": "Dur... yerden çıkan şu şey... Bir manivela mı o?!",
"VO__AMICIA__CH11__CHATTER__LEVER_RIGHT__010__M__1": "Tamam, bu bir şey...",
"VO__AMICIA__CH11__CHATTER__LEVER_RIGHT_RELEASE__010__M__1": "Tutmuyor...",
"VO__AMICIA__CH11__CHATTER__LIGHT__020__M__1": "Onu yakacağım.",
"VO__AMICIA__CH11__CHATTER__LIGHT__030__M__1": "Şu mekânın büyüklüğüne bak...",
"VO__AMICIA__CH11__CHATTER__LIGHT__060__M__1": "Öyle görünüyor, evet...",
"VO__AMICIA__CH11__CHATTER__OPENED_GATE_CORRIDOR__010__M__1": "Geldik... Geri dönmek istersen Sophia, tam zamanı.",
"VO__AMICIA__CH11__CHATTER__OPENED_GATE_CORRIDOR__040__M__1": "Lütfen, Hugo...",
"VO__AMICIA__CH11__CHATTER__ORDER_SIGN__020__M__1": "Evet! Burası işte!",
"VO__AMICIA__CH11__CHATTER__OUT_OF_SIGHT__020__M__1": "Sophia!",
"VO__AMICIA__CH11__CHATTER__PORTCULLIS_OPENED__010__M__1": "Sanırım buradan geçmiş...",
"VO__AMICIA__CH11__CHATTER__PULLING_LEFT__010__M__1": "Hugo, şu sıçanların bizi kaç kez yakalamaya çalıştığının farkında mısın?",
"VO__AMICIA__CH11__CHATTER__PULLING_LEFT__030__M__1": "Ama hep onları alt ettik. Çünkü birbirlerini umursamıyorlar.",
"VO__AMICIA__CH11__CHATTER__PULLING_LEFT__050__M__1": "Aynen!",
"VO__AMICIA__CH11__CHATTER__PULLING_TANK__010__M__1": "Sıkışmış... Gel... buraya!",
"VO__AMICIA__CH11__CHATTER__PULLING_TANK__020__M__1": "Evet... Bu yeter...",
"VO__AMICIA__CH11__CHATTER__PUSHING_CART__020__M__1": "Doğru. Halkına barınak sunmak Kont'un görevidir.",
"VO__AMICIA__CH11__CHATTER__PUSHING_TANK__020__M__1": "Görüyorum!",
"VO__AMICIA__CH11__CHATTER__RATS_BURSTING__030__M__1": "Onları boş ver, Hugo! Nefes al! Koşmaya devam et!",
"VO__AMICIA__CH11__CHATTER__RATS_SWARM__020__M__1": "Ne?!",
"VO__AMICIA__CH11__CHATTER__RATS_SWARM__040__M__1": "Hadi! Hadi!",
"VO__AMICIA__CH11__CHATTER__RATS_SWARM__060__M__1": "DURMA!",
"VO__AMICIA__CH11__CHATTER__REUNITING__020__M__1": "Hey...",
"VO__AMICIA__CH11__CHATTER__REUNITING__040__M__1": "Sorun yok... Sorun yok... Bırak gitsin...",
"VO__AMICIA__CH11__CHATTER__REUNITING__060__M__1": "Hayır, gitsek iyi olur... Artık buradayım. Gidelim.",
"VO__AMICIA__CH11__CHATTER__REUNITING_LADDER__010__M__1": "Köprünün sonu... Nereye çıktığını görmenin vakti.",
"VO__AMICIA__CH11__CHATTER__REUNITING_LEAVE__020__M__1": "Biliyorum. Çok şey atlattık.",
"VO__AMICIA__CH11__CHATTER__REUNITING_WALKING_WATCH__010__M__1": "Bu... Basilius'unki mi?",
"VO__AMICIA__CH11__CHATTER__SECOND_PULL__010__M__1": "Gel buraya...",
"VO__AMICIA__CH11__CHATTER__SECOND_PULL__030__M__1": "Hayır... Macula hepsini birbirine bağlıyor...",
"VO__AMICIA__CH11__CHATTER__SECOND_PULL_OVER__010__M__1": "Güzel... Bir bakalım...",
"VO__AMICIA__CH11__CHATTER__SLOPE_EDGE__010__M__1": "Daha derine iniyoruz.",
"VO__AMICIA__CH11__CHATTER__SOUVENIR_BARBICAN__010__M__1": "Bu... burayı gösteren bir harita. Rayları ve mangalları görebiliyorsun...",
"VO__AMICIA__CH11__CHATTER__SOUVENIR_BARBICAN__040__M__1": "Haklısın! Avlu burası, bütün mangallarıyla...! Peki şunlar ne?",
"VO__AMICIA__CH11__CHATTER__SOUVENIR_BARBICAN__060__M__1": "Düzen'in bu kadar yayıldığından haberim yoktu...",
"VO__AMICIA__CH11__CHATTER__SOUVENIR_BARBICAN__090__M__1": "Bir Veba... Hadi... Hadi gidelim.",
"VO__AMICIA__CH11__CHATTER__SOUVENIR_GATE__010__M__1": "Bak... Çocuk kıyafetleri, oyuncaklar...",
"VO__AMICIA__CH11__CHATTER__SOUVENIR_GATE__050__M__1": "Demek ki yakında... Şu kapının ötesinde bir yerde!",
"VO__AMICIA__CH11__CHATTER__SOUVENIR_GATE__070__M__1": "Sıradan bir çocuk değil... Göreceğiz. Şu kapıya geri dönelim...",
"VO__AMICIA__CH11__CHATTER__STAIRS_VISTA__020__M__1": "Tanrım... Sanki bir... katedral gibi...",
"VO__AMICIA__CH11__CHATTER__STAIRS_VISTA__050__M__1": "Evet. Bütün bunların merkezinde... Son eşiğin yapacağı şeye... benziyor... Aelia ona ulaşamadı... Ve olan bu oldu...",
"VO__AMICIA__CH11__CHATTER__STAIRS_VISTA__070__M__1": "Mecbursun. Seni buraya o getirdi. Bu... senin mirasın...",
"VO__AMICIA__CH11__CHATTER__START__011__M__1": "Bak... Bu bir yere çıkıyor.",
"VO__AMICIA__CH11__CHATTER__START__015__M__1": "İşte burası... Hissediyorum.",
"VO__AMICIA__CH11__CHATTER__START__040__M__1": "Bırakmam. Merak etme.",
"VO__AMICIA__CH11__CHATTER__STONES__010__M__1": "Her şey çökecek...",
"VO__AMICIA__CH11__CHATTER__STONES__030__M__1": "Onları boş ver! Sadece koş!",
"VO__AMICIA__CH11__CHATTER__STONES__040__M__1": "Aman Tanrım, hız kesmiyorlar!",
"VO__AMICIA__CH11__CHATTER__STORAGE__020__M__1": "Basilius için korkmuş...",
"VO__AMICIA__CH11__CHATTER__STORAGE_BAG__020__M__1": "O bir silah değil mi?",
"VO__AMICIA__CH11__CHATTER__STORAGE_BAG__035__M__1": "Sence... patlayabilir mi...?",
"VO__AMICIA__CH11__CHATTER__STORAGE_BAG__070__M__1": "Sadece ona güven, Hugo.",
"VO__AMICIA__CH11__CHATTER__STORAGE_EXPLOSION_AFTER__010__M__1": "İşe yaradı!",
"VO__AMICIA__CH11__CHATTER__STORAGE_EXPLOSION_AFTER__030__M__1": "Gördün mü? Dayanıyor... Hadi!",
"VO__AMICIA__CH11__CHATTER__STORAGE_EXPLOSION_AFTER__070__M__1": "Bir şey olmaz.",
"VO__AMICIA__CH11__CHATTER__STORAGE_EXPLOSION_HURT__030__M__1": "Vay... Başım... çınlıyor...",
"VO__AMICIA__CH11__CHATTER__STORAGE_EXPLOSION_HURT__050__M__1": "... Geçiyor... Devam edelim...",
"VO__AMICIA__CH11__CHATTER__STUCK_CART__010__M__1": "Ha... Lanet enkaz!",
"VO__AMICIA__CH11__CHATTER__STUCK_CART__030__M__1": "Evet! Arabamla daha öteye gidemem!",
"VO__AMICIA__CH11__CHATTER__STUCK_CART__050__M__1": "Geliyorum!",
"VO__AMICIA__CH11__CHATTER__TAKING_NEWS__030__M__1": "Çıkış görüyor musun?!",
"VO__AMICIA__CH11__CHATTER__TANK_BARRICADE_BOOM__010__M__1": "Yol açık! Geri dönelim!",
"VO__AMICIA__CH11__CHATTER__TANK_SHOOT_FAIL__020__M__1": "Ah, evet...",
"VO__AMICIA__CH11__CHATTER__TANK_SHOOT_FAIL__040__M__1": "Yapacağım!",
"VO__AMICIA__CH11__CHATTER__TANK_SHOOT_READY__010__M__1": "Dikkat et! Onu patlatacağım!",
"VO__AMICIA__CH11__CHATTER__THIRD_PULL__010__M__1": "Hadi bakalım...",
"VO__AMICIA__CH11__CHATTER__THIRD_PULL__020__M__1": "Nasılsın, Hugo?...",
"VO__AMICIA__CH11__CHATTER__THIRD_PULL__040__M__1": "Bu normal. Her şey yoluna girecek.",
"VO__AMICIA__CH11__CHATTER__THIRD_PULL_OVER__010__M__1": "Tamam, bu da bitti.",
"VO__AMICIA__CH11__CHATTER__TURNINGWHEEL__030__M__1": "Şey...",
"VO__AMICIA__CH11__CHATTER__TURNINGWHEEL_UNCHECKED__010__M__1": "Aşağıdaki o kapı zaten harap görünüyordu!",
"VO__AMICIA__CH11__CHATTER__UPSTAIRS__010__M__1": "Çabuk... çabuk!",
"VO__AMICIA__CH11__CHATTER__UPSTAIRS_CRATE__005__M__1": "Hayır!",
"VO__AMICIA__CH11__CHATTER__UPSTAIRS_CRATE__010__M__1": "Yukarı! Yukarı! Yukarı!",
"VO__AMICIA__CH11__CHATTER__UPSTAIRS_CRATE__020__M__1": "Sophia!",
"VO__AMICIA__CH11__CHATTER__UPSTAIRS_PASSAGE__010__M__1": "Evet!",
"VO__AMICIA__CH11__CHATTER__UPSTAIRS_TIMING__010__M__1": "Hadi, Hugo!",
"VO__AMICIA__CH11__CHATTER__UPSTAIRS_TWO__020__M__1": "Hiçbir şey ele geçiremeyecekler!",
"VO__AMICIA__CH11__CHATTER__WRECK_BOOM_NEW__016__M__1": "Araba enkazı kalmadı...",
"VO__AMICIA__CH11__CHATTER__WRONG_WAY_NO_LIGHT__020__M__1": "Tamam... Sakin ol.",
"VO__AMICIA__CH11__HELPER__CISTERN_AMICIA_CHAINS_1__010__M__1": "Karşı ağırlıkları serbest bırakmanın bir yolu olmalı...",
"VO__AMICIA__CH11__HELPER__CISTERN_AMICIA_CHAINS_2__010__M__1": "Şu zincirlerde bir kilit var. Her şeyi o tutuyor olmalı...",
"VO__AMICIA__CH11__HELPER__CISTERN_DOWN_1__010__M__1": "Bazı zincirler hâlâ sağlam olmalı...",
"VO__AMICIA__CH11__RTC__520_BACK_FROM_THE_FORT__030__M__1": "Değil. Orada ne olduğunu hepimiz biliyoruz.",
"VO__AMICIA__CH11__RTC__530_ENTER_TOMB__020__M__1": "Geride dur, tamam mı?",
"VO__AMICIA__CH11__RTC__530_ENTER_TOMB__030__M__1": "Hazır mısın?",
"VO__AMICIA__CH11__RTC__530_ENTER_TOMB__075__M__1": "Hadi.",
"VO__AMICIA__CH11__RTC__530_ENTER_TOMB__080__M__1": "Bir koridor...",
"VO__AMICIA__CH11__RTC__530_ENTER_TOMB__090__M__1": "Mühürlenmiş.",
"VO__AMICIA__CH11__RTC__530_ENTER_TOMB__120__M__1": "Gidip bakalım...",
"VO__AMICIA__CH11__RTC__530_ENTER_TOMB__130__M__1": "İşte burası! Gel!",
"VO__AMICIA__CH11__RTC__530_ENTER_TOMB__160__M__1": "Hadi, ışığı bulacağız.",
"VO__AMICIA__CH11__RTC__550_ALTAR__020__M__1": "Bu o... Aelia... Taşıyıcı'nın Koruyucusu...",
"VO__AMICIA__CH11__RTC__550_ALTAR__040__M__1": "Ama tek başına ölmüş.",
"VO__AMICIA__CH11__RTC__550_ALTAR__050__M__1": "Neyin var, Hugo?",
"VO__AMICIA__CH11__RTC__550_ALTAR__070__M__1": "Ben hayattayım. Hayattayım.",
"VO__AMICIA__CH11__RTC__550_ALTAR__090__M__1": "O hissi biliyorum... Tek başına savaşmak... Yalnız kalmamak için savaşmak... Umarım olduğun yerde huzuru bulmuşsundur.",
"VO__AMICIA__CH11__RTC__550_ALTAR__130__M__1": "Daha iyi misin?",
"VO__AMICIA__CH11__RTC__550_ALTAR__150__M__1": "Hey, hepimiz yorgunuz... Ama birlikteyiz, değil mi?",
"VO__AMICIA__CH11__RTC__550_ALTAR__160__M__1": "Pekâlâ... şu kapıyı açalım.",
"VO__AMICIA__CH11__RTC__555_COLLAPSE__010__M__1": "Ah...",
"VO__AMICIA__CH11__RTC__555_COLLAPSE__030__M__1": "Hayır...",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__005__M__1": "Hadi! Gel.",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__020__M__1": "Taşıyıcı...",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__030__M__1": "Onu hapsetmişler...",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__050__M__1": "Ondan korkmuşlar. Gücünden.",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__060__M__1": "Bütün... bunları bu yüzden yapmışlar. Hep korktular.",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__080__M__1": "Sıçanları o saldı. Duvarlarını parçaladılar. Onları durduramadılar.",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__090__M__1": "Burada başladı...",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__110__M__1": "Justinianus Vebası.",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__130__M__1": "Demek Macula bizi bu yüzden buraya getirdi?... Bir şey olmalı... Bir parşömen... Bir şişe... Bir şey!",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__170__M__1": "Aelia... Başaramamış...",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__190__M__1": "Başaramamış, Sophia!",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__240__M__1": "Ölmeyeceksin.",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__260__M__1": "Hayır... Hugo... Onun ölmesi gerekmiyordu! Koruyucusundan koparıldığında umudunu yitirdi, böylece Macula'ya teslim oldu ve hepsini lanetledi!",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__270__M__1": "Hayır... Ama ondan tek bir söz ona ulaşsaydı, yalnız olmadığını bilirdi! Yaşardı! Ve milyonlarca canı bağışlardı!",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__280__M__1": "Anlıyor musun? ÖLMEYECEKSİN! Senin yanındayım. Ve sana hak ettiğin hayatı vereceğim... Savaşsız bir hayat... İster misin?",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__300__M__1": "Hadi kendimize bir yuva bulalım.",
"VO__AMICIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__320__M__1": "Neler oluyor?",
"VO__AMICIA__CH11__RTC__570_LETS_GO_HOME__012__M__1": "Sanırım iyiyiz... Yaralanan var mı? Hugo?",
"VO__AMICIA__CH11__RTC__570_LETS_GO_HOME__030__M__1": "Evet... Bunu görmek zorunda kaldığın için üzgünüm... Macula seni içine çekti...",
"VO__AMICIA__CH11__RTC__570_LETS_GO_HOME__060__M__1": "Evet... ama yaşayacaksın. En önemlisi bu.",
"VO__AMICIA__CH11__RTC__570_LETS_GO_HOME__080__M__1": "Haklısın...",
"VO__AMICIA__CH11__RTC__570_LETS_GO_HOME__085__M__1": "Dinle... her zaman korkunç şeyler yapan insanlar olacak... dünya böyle... Ama kendi iyiliğine güvenmen gerek. Ve başkalarının iyiliğine. Seni önemseyen insanlara. Mutlu olmanı isteyenlere. Dostlara...",
"VO__AMICIA__CH11__RTC__570_LETS_GO_HOME__110__M__1": "Dostlar insana iyi olmayı istetir, değil mi?",
"VO__AMICIA__CH11__RTC__570_LETS_GO_HOME__140__M__1": "Şüphe ediyorsan anlarım... ama bana güvenebilirsin.",
"VO__AMICIA__CH11__RTC__570_LETS_GO_HOME__145__M__1": "Bize güvenebilirsin.",
"VO__AMICIA__CH11__RTC__570_LETS_GO_HOME__160__M__1": "Kendimize ait bir yer bulacağız.",
"VO__AMICIA__CH11__RTC__570_LETS_GO_HOME__165__M__1": "Bu adadan ayrılalım.",
"VO__AMICIA__CH11__RTC__570_LETS_GO_HOME__190__M__1": "Bizi durduramayacaklar. Her şey değişti.",
"VO__HUGO__CH11__CHATTER__2ND_TANK_EXPLOSION__020__M__1": "Ha... kulaklarım...",
"VO__HUGO__CH11__CHATTER__ACTIVATE_BREAK__010__M__1": "Duvardan bir şey çıkıyor...",
"VO__HUGO__CH11__CHATTER__ACTIVATE_BREAK__030__M__1": "Belki yardım edebilirim?",
"VO__HUGO__CH11__CHATTER__BARRELS__020__M__1": "İçinde bir şey vardı...",
"VO__HUGO__CH11__CHATTER__BODIES_GROUND__010__M__1": "Ölü insanlar...",
"VO__HUGO__CH11__CHATTER__BRIDGE_COLLAPSE__010__M__1": "Sanırım... Yıkılıyor! Amicia!",
"VO__HUGO__CH11__CHATTER__BRIDGE_MISSING__020__M__1": "Ama bir parça eksik...",
"VO__HUGO__CH11__CHATTER__BRIDGE_STAIRS__010__M__1": "Burada olmamalıyız...",
"VO__HUGO__CH11__CHATTER__BRIDGEPUZZLE_EAST_BLOCKED__020__M__1": "Ama şu enkaz yolu kapatıyor... Ondan kurtulabilir miyiz?",
"VO__HUGO__CH11__CHATTER__BRIDGEPUZZLE_RIGHT_HUGO__020__M__1": "Evet...",
"VO__HUGO__CH11__CHATTER__BRIDGERATS__012__M__1": "Biliyordum! Burası kötü bir yer!",
"VO__HUGO__CH11__CHATTER__CANT_GO__010__M__1": "Ben... Yapamıyorum... Amicia!... Sophia!",
"VO__HUGO__CH11__CHATTER__CANT_GO__030__M__1": "Hayır, bilmiyorsun! Neden bunu yapıyorsun?",
"VO__HUGO__CH11__CHATTER__CARRYING_HUGO__020__M__1": "Dinlenmek istiyorum...",
"VO__HUGO__CH11__CHATTER__CARRYING_HUGO__040__M__1": "Kendimden korkuyorum, Amicia...",
"VO__HUGO__CH11__CHATTER__CART_BLOCKER__020__M__1": "Ağır görünüyor!",
"VO__HUGO__CH11__CHATTER__CART_EXPLOSION__020__M__1": "Ho!",
"VO__HUGO__CH11__CHATTER__CART_EXPLOSION_OK__050__M__1": "Evet! Çabuk! Neredeyse vardın!",
"VO__HUGO__CH11__CHATTER__CART_RESTING__020__M__1": "Ah...",
"VO__HUGO__CH11__CHATTER__CART_ROLLING__020__M__1": "Ah...",
"VO__HUGO__CH11__CHATTER__CAVE_SQUEEZE_AFTER__020__M__1": "Cidden oradan mı geçeceğiz?",
"VO__HUGO__CH11__CHATTER__CHAIN_DOWN_BIS__010__M__1": "Şurada bir parça daha eksik!",
"VO__HUGO__CH11__CHATTER__CHEST_THERE__010__M__1": "Amicia! Nasıl gidiyor?!",
"VO__HUGO__CH11__CHATTER__CISTERN_AMICIA_DOWN__020__M__1": "Dikkatli ol!",
"VO__HUGO__CH11__CHATTER__CISTERN_ENTRANCE__015__M__1": "Hım...",
"VO__HUGO__CH11__CHATTER__CISTERN_GOING_DOWN__010__M__1": "İyi misin?!",
"VO__HUGO__CH11__CHATTER__CISTERN_GOING_DOWN__025__M__1": "Nasıl geri döneceksin?!",
"VO__HUGO__CH11__CHATTER__CISTERN_GOING_DOWN__040__M__1": "Evet!",
"VO__HUGO__CH11__CHATTER__CISTERN_LEVER__030__M__1": "Bir köprü...",
"VO__HUGO__CH11__CHATTER__CLIMB_BURST__020__M__1": "Deniyorum!",
"VO__HUGO__CH11__CHATTER__COLLAPSE__010__M__1": "Her şey... her şey çöküyor!",
"VO__HUGO__CH11__CHATTER__CONTINUE__015__M__1": "Canı yanacak, Sophia...",
"VO__HUGO__CH11__CHATTER__CONTINUE__040__M__1": "Ama yapayalnız... ve onlar o kadar çok ki!",
"VO__HUGO__CH11__CHATTER__CONTINUE__060__M__1": "Evet...",
"VO__HUGO__CH11__CHATTER__CONTINUE__080__M__1": "Gerçekten çok mu korkuyorsun?",
"VO__HUGO__CH11__CHATTER__CONTINUE__095__M__1": "Söz.",
"VO__HUGO__CH11__CHATTER__CONTINUE_RATS_END__020__M__1": "Güvendesin!",
"VO__HUGO__CH11__CHATTER__CORRIDOR__040__M__1": "Uzun zamandır orada.",
"VO__HUGO__CH11__CHATTER__CORRIDOR__060__M__1": "Sanırım... Ah... Tuhaf hissediyorum...",
"VO__HUGO__CH11__CHATTER__CORRIDOR__080__M__1": "Bir... ses var...",
"VO__HUGO__CH11__CHATTER__CROSSING_CART__020__M__1": "Devam et! Başaracaksın!",
"VO__HUGO__CH11__CHATTER__CROSSING_CART__040__M__1": "İstediğini biliyorum.",
"VO__HUGO__CH11__CHATTER__DOOR__040__M__1": "Bir... kaza mıydı?",
"VO__HUGO__CH11__CHATTER__DOOR_BLOCKED__030__M__1": "Bütün bunları o mu yıktı?",
"VO__HUGO__CH11__CHATTER__EXPLORE__010__M__1": "Koş!",
"VO__HUGO__CH11__CHATTER__FEATHER_INTERACT__020__M__1": "Burada kuş mu var?",
"VO__HUGO__CH11__CHATTER__FEATHER_INTERACT__050__M__1": "Ve o da yalnız değil.",
"VO__HUGO__CH11__CHATTER__FEATHER_INTERACT__070__M__1": "Evet!",
"VO__HUGO__CH11__CHATTER__FIRST_PUSH_START__030__M__1": "Evet...",
"VO__HUGO__CH11__CHATTER__GATE_CHATTER_STUCK__010__M__1": "Çok üzülmedin, değil mi Sophia?",
"VO__HUGO__CH11__CHATTER__GATE_CHATTER_STUCK__030__M__1": "Bütün o... kötü şeyler yüzünden...",
"VO__HUGO__CH11__CHATTER__GATE_CHATTER_STUCK__050__M__1": "Tamam. Güzel...",
"VO__HUGO__CH11__CHATTER__GATE_HUGO_REUNITED__020__M__1": "Hı-hı.",
"VO__HUGO__CH11__CHATTER__GATE_OPENING__020__M__1": "Açık olmamalı... Onu hâlâ kapatabiliriz.",
"VO__HUGO__CH11__CHATTER__GATE_OPENING__050__M__1": "Daha da... derine iniyor... Hâlâ gidebiliriz, Amicia...",
"VO__HUGO__CH11__CHATTER__GOING_DOWN_1__020__M__1": "Bunu istiyorsun ama ben her şeyi mahvedip duruyorum!",
"VO__HUGO__CH11__CHATTER__GOING_DOWN_1__040__M__1": "Yine de yapıyorum!",
"VO__HUGO__CH11__CHATTER__GOING_DOWN_1__060__M__1": "Kızıl şehirde de çocuklar vardı.",
"VO__HUGO__CH11__CHATTER__GOING_DOWN_2__040__M__1": "Başım... Gittikçe... yükseliyor...",
"VO__HUGO__CH11__CHATTER__GOING_DOWN_2__060__M__1": "Onu kafamdan atmak istiyorum!",
"VO__HUGO__CH11__CHATTER__GOING_DOWN_2__080__M__1": "Her şeyi mahvedip duruyorsam ne anlamı var ki?!",
"VO__HUGO__CH11__CHATTER__GREEK_FIRE_PASS__030__M__1": "Daha çok Rum ateşi bulduk!",
"VO__HUGO__CH11__CHATTER__GREEK_FIRE_PASS__050__M__1": "Yakalayabilesin diye etrafına bir ip bağladık!",
"VO__HUGO__CH11__CHATTER__HALL_PUZZLE_DONE__050__M__1": "Ona kötü bir şey oluyordu. O bunu biliyordu.",
"VO__HUGO__CH11__CHATTER__HALL_PUZZLE_DONE__070__M__1": "Sadece... karanlık hissediyorum. Tıpkı rüyamdaki gibi, ölürken.",
"VO__HUGO__CH11__CHATTER__HALLWAY__020__M__1": "Orada, Amicia... İstemiyorum...",
"VO__HUGO__CH11__CHATTER__HALLWAY_START__020__M__1": "Ah... Yanlış... Çok yanlış...",
"VO__HUGO__CH11__CHATTER__HUB3_FESTIVAL_BACK__040__M__1": "Size yardım edeceğiz!",
"VO__HUGO__CH11__CHATTER__HUB3_FESTIVAL_BACK__050__M__1": "Hayır, HAYIR! Onları bırak! Lütfen!",
"VO__HUGO__CH11__CHATTER__HUB3_FESTIVAL_BACK__070__M__1": "Neden?! Senden nefret ediyorum! HEPİNİZDEN NEFRET EDİYORUM!",
"VO__HUGO__CH11__CHATTER__HUB3_FESTIVAL_CARTMOVING__030__M__1": "Ama çok eski! Öleli uzun zaman olmuş!",
"VO__HUGO__CH11__CHATTER__HUB3_FESTIVAL_CARTMOVING__050__M__1": "Kendimi umursamıyorum...",
"VO__HUGO__CH11__CHATTER__HUB3_FESTIVAL_CARTMOVING__110__M__1": "Biliyorum...",
"VO__HUGO__CH11__CHATTER__HUB3_MAP_AMPHI__020__M__1": "Yer altında...",
"VO__HUGO__CH11__CHATTER__HUB3_PUZZLE_CART__020__M__1": "Çok geç. Her şey mahvoldu.",
"VO__HUGO__CH11__CHATTER__HUB3_START__020__M__1": "Sıçanlar bunu istemeyecek... Şu an mutlular.",
"VO__HUGO__CH11__CHATTER__HUB3_START__040__M__1": "Karşılık verecekler.",
"VO__HUGO__CH11__CHATTER__HUB3_START__060__M__1": "Bilmiyorum...",
"VO__HUGO__CH11__CHATTER__LADDER_OUTSIDE__015__M__1": "Şimdi geri dönmenin bir yolunu bulmalısın!",
"VO__HUGO__CH11__CHATTER__LAST_CART_PUSH__020__M__1": "Başardın!",
"VO__HUGO__CH11__CHATTER__LAST_CART_PUSH__040__M__1": "Biliyorum! Korkmadım...",
"VO__HUGO__CH11__CHATTER__LAST_PUSH_CORRIDOR__010__M__1": "Hayır!",
"VO__HUGO__CH11__CHATTER__LAST_RUN__060__M__1": "Gerçeği bilmek istemiyorum, Amicia...",
"VO__HUGO__CH11__CHATTER__LAST_RUN__080__M__1": "Tuhaf... hissediyorum...",
"VO__HUGO__CH11__CHATTER__LAST_RUN__150__M__1": "Evet... Kızma...",
"VO__HUGO__CH11__CHATTER__LAST_RUN__170__M__1": "Öyle olma...",
"VO__HUGO__CH11__CHATTER__LIGHT__005__M__1": "Karanlık çöküyor...",
"VO__HUGO__CH11__CHATTER__LIGHT__040__M__1": "Bu da ne?!",
"VO__HUGO__CH11__CHATTER__OPENED_GATE_CORRIDOR__030__M__1": "Geri dönmek istiyorum...",
"VO__HUGO__CH11__CHATTER__ORDER_SIGN__030__M__1": "Basilius burada... bir yerde...",
"VO__HUGO__CH11__CHATTER__OUT_OF_SIGHT__010__M__1": "Sophia nerede?!",
"VO__HUGO__CH11__CHATTER__PULLING_LEFT__020__M__1": "Evet... Çok...",
"VO__HUGO__CH11__CHATTER__PULLING_LEFT__040__M__1": "Ama biz umursarız...",
"VO__HUGO__CH11__CHATTER__PUSHING_CART__030__M__1": "Evet... Gerçek bir şövalye.",
"VO__HUGO__CH11__CHATTER__RATS_BURSTING__020__M__1": "Bizi bırakın! BİZİ BIRAKIN!",
"VO__HUGO__CH11__CHATTER__RATS_SWARM__010__M__1": "Olamaz! Hayır!",
"VO__HUGO__CH11__CHATTER__RATS_SWARM__030__M__1": "Geliyorlar! O kadar çoklar ki!",
"VO__HUGO__CH11__CHATTER__RATS_SWARM__050__M__1": "Bacaklarım...",
"VO__HUGO__CH11__CHATTER__REUNITING__010__M__1": "Buradasın!",
"VO__HUGO__CH11__CHATTER__REUNITING__030__M__1": "Buradasın...",
"VO__HUGO__CH11__CHATTER__REUNITING__070__M__1": "Evet...",
"VO__HUGO__CH11__CHATTER__REUNITING_LEAVE__010__M__1": "Üzgünüm ve korkuyorum, Amicia...",
"VO__HUGO__CH11__CHATTER__REUNITING_LEAVE__030__M__1": "Ama sanki... sanki kendi aklım değil...",
"VO__HUGO__CH11__CHATTER__REUNITING_WALKING_WATCH__020__M__1": "Belki. Gerçekten çok ağır... Korkuyorum...",
"VO__HUGO__CH11__CHATTER__SOUVENIR_BARBICAN__030__M__1": "Başkaları da var... Şurada... Chateau d'Ombrage'a benziyor, Amicia!",
"VO__HUGO__CH11__CHATTER__SOUVENIR_BARBICAN__070__M__1": "Çünkü her yerde olabilir...",
"VO__HUGO__CH11__CHATTER__SOUVENIR_GATE__020__M__1": "Basilius... Onunkiler...",
"VO__HUGO__CH11__CHATTER__SOUVENIR_GATE__040__M__1": "Onu elinden almışlar...",
"VO__HUGO__CH11__CHATTER__STAIRS_VISTA__030__M__1": "Bunu onun için yapmışlar.",
"VO__HUGO__CH11__CHATTER__STAIRS_VISTA__065__M__1": "Bilmek istemiyorum...",
"VO__HUGO__CH11__CHATTER__STAIRS_VISTA__080__M__1": "Miras istemiyorum. Normal olmak istiyorum!",
"VO__HUGO__CH11__CHATTER__START__030__M__1": "Elimi bırakma...",
"VO__HUGO__CH11__CHATTER__STONES__020__M__1": "Çok öfkeliler...",
"VO__HUGO__CH11__CHATTER__STORAGE__030__M__1": "Haklıymış...",
"VO__HUGO__CH11__CHATTER__STORAGE_BAG__050__M__1": "Gerçekten mi?",
"VO__HUGO__CH11__CHATTER__STORAGE_BAG__065__M__1": "Ama...",
"VO__HUGO__CH11__CHATTER__STORAGE_EXPLOSION__020__M__1": "Ah!",
"VO__HUGO__CH11__CHATTER__STORAGE_EXPLOSION_AFTER__020__M__1": "Çok gürültülüydü...",
"VO__HUGO__CH11__CHATTER__STORAGE_EXPLOSION_HURT__020__M__1": "Amicia!",
"VO__HUGO__CH11__CHATTER__TANK_SHOOT_READY__020__M__1": "Devam et!",
"VO__HUGO__CH11__CHATTER__THIRD_PULL__030__M__1": "Korkuyorum...",
"VO__HUGO__CH11__CHATTER__TO_COVER__020__M__1": "Yeterince uzaklaştık mı?",
"VO__HUGO__CH11__CHATTER__TURNINGWHEEL__020__M__1": "Araba birazdan gidecek!",
"VO__HUGO__CH11__CHATTER__UPSTAIRS_TWO__010__M__1": "Gitmemi istemiyorlar!",
"VO__HUGO__CH11__CHATTER__WRECK_BOOM_NEW__013__M__1": "Öff...",
"VO__HUGO__CH11__CHATTER__WRONG_WAY_NO_LIGHT__010__M__1": "Işıksız gidemeyiz, Amicia!",
"VO__HUGO__CH11__HELPER__ACTIVATE_LOCK_1__010__M__1": "Şu çubukları nasıl uzak tutacağız?",
"VO__HUGO__CH11__HELPER__CISTERN_DOWN_2__010__M__1": "Amicia! Şu zincirleri kesmelisin!",
"VO__HUGO__CH11__HELPER__EXPLOSION_GATE_1__010__M__1": "O kapıyı da mı patlatacağız?",
"VO__HUGO__CH11__HELPER__HUB3_GRASS_FIRE_1__010__M__1": "Bütün şunları geçmek için büyük bir ateş gerekecek...",
"VO__HUGO__CH11__RTC__520_BACK_FROM_THE_FORT__010__M__1": "Buraya gelmişler... Amicia... İnsanlar... Benim suçum!",
"VO__HUGO__CH11__RTC__530_ENTER_TOMB__060__M__1": "Zavallı harita...",
"VO__HUGO__CH11__RTC__530_ENTER_TOMB__110__M__1": "İçerideki karanlığa karşı...",
"VO__HUGO__CH11__RTC__530_ENTER_TOMB__140__M__1": "Çok karanlık...",
"VO__HUGO__CH11__RTC__550_ALTAR__060__M__1": "Ölmeni istemiyorum...",
"VO__HUGO__CH11__RTC__550_ALTAR__110__M__1": "Geri dönmeliyiz...",
"VO__HUGO__CH11__RTC__555_COLLAPSE__020__M__1": "AMICIA! HAYIR!",
"VO__HUGO__CH11__RTC__560_REMAINS_OF_A_CARRIER__040__M__1": "Ama neden?...",
"VO__HUGO__CH11__RTC__560_REMAINS_OF_A_CARRIER__120__M__1": "Üzgünmüş. Çok üzgün ve öfkeli.",
"VO__HUGO__CH11__RTC__560_REMAINS_OF_A_CARRIER__175__M__1": "Bu haksızlık!",
"VO__HUGO__CH11__RTC__560_REMAINS_OF_A_CARRIER__215__M__1": "Bu haksızlık!",
"VO__HUGO__CH11__RTC__560_REMAINS_OF_A_CARRIER__230__M__1": "Ben ölünce...",
"VO__HUGO__CH11__RTC__560_REMAINS_OF_A_CARRIER__250__M__1": "Ben de hepsini öldüreceğim!",
"VO__HUGO__CH11__RTC__560_REMAINS_OF_A_CARRIER__265__M__1": "Ve haklıymış!",
"VO__HUGO__CH11__RTC__570_LETS_GO_HOME__015__M__1": "Korkunçtu...",
"VO__HUGO__CH11__RTC__570_LETS_GO_HOME__050__M__1": "Ona zincir vurmuşlar...",
"VO__HUGO__CH11__RTC__570_LETS_GO_HOME__065__M__1": "En önemlisi bu değil! İnsanların bu kadar kötü olabileceğini düşünmek beni korkutuyor... Bana neler yaptıracaklarından korkuyorum.",
"VO__HUGO__CH11__RTC__570_LETS_GO_HOME__150__M__1": "Sana güveniyorum.",
"VO__PEOPLE_F1__CH11__CHATTER__HUB3_FESTIVAL_BACK__020__M__1": "Bakın! Sağ kalanlar!",
"VO__PEOPLE_M4__CH11__CHATTER__HUB3_FESTIVAL_BACK__030__M__1": "Fazla yaklaşmayın!",
"VO__SOPHIA__CH11__CHATTER__2ND_TANK_EXPLOSION__030__M__1": "Lanet olsun...",
"VO__SOPHIA__CH11__CHATTER__2ND_TANK_EXPLOSION__050__M__1": "Öyle galiba...",
"VO__SOPHIA__CH11__CHATTER__2ND_TWISTED_DOOR__010__M__1": "Kapı epey harap olmuş...",
"VO__SOPHIA__CH11__CHATTER__AFTER_EXPLOSION__020__M__1": "Biliyor musun... Onu sende görmeye başladım... Aelia'yı...",
"VO__SOPHIA__CH11__CHATTER__AFTER_EXPLOSION__040__M__1": "Çünkü pes etmiyorsun.",
"VO__SOPHIA__CH11__CHATTER__BEAM_WALK__030__M__1": "Bu aşağılık şeyler vazgeçmiyor!",
"VO__SOPHIA__CH11__CHATTER__BODIES_GROUND__030__M__1": "Esir almayı sevmezmiş...",
"VO__SOPHIA__CH11__CHATTER__BRIDGE_COLLAPSE__030__M__1": "Lanet... yaratıklar! Cehenneme gidin!",
"VO__SOPHIA__CH11__CHATTER__BRIDGE_INCOMING__010__M__1": "İşte köprü!",
"VO__SOPHIA__CH11__CHATTER__BRIDGE_INCOMING__030__M__1": "İlerleyin!",
"VO__SOPHIA__CH11__CHATTER__BRIDGE_MISSING__040__M__1": "Bak, şurada... Aşağı inen bir yol var. Şey, dik ama...",
"VO__SOPHIA__CH11__CHATTER__BRIDGE_STAIRS__020__M__1": "Şey... ama buradayız.",
"VO__SOPHIA__CH11__CHATTER__BRIDGEIN__010__M__1": "Burası neresi?",
"VO__SOPHIA__CH11__CHATTER__BRIDGEPUZZLE_2LIGHT_FAR__010__M__1": "Şimdi ne olacak?",
"VO__SOPHIA__CH11__CHATTER__BRIDGEPUZZLE_END__020__M__1": "Nihayet... Aferin...",
"VO__SOPHIA__CH11__CHATTER__BRIDGEPUZZLE_RIGHT_HUGO__030__M__1": "Bunca Rum ateşi şimdi anlam kazanıyor...",
"VO__SOPHIA__CH11__CHATTER__BRIDGEPUZZLE_WEST_END__020__M__1": "Lanet... ray hasarlı...",
"VO__SOPHIA__CH11__CHATTER__BRIDGEPUZZLE_WEST_HELPER2__010__M__1": "Şey, bunu geri koymak istediğine emin misin?",
"VO__SOPHIA__CH11__CHATTER__BRIDGERATS__011__M__1": "Biraz ateş lazım, Amicia, çabuk!",
"VO__SOPHIA__CH11__CHATTER__BRIDGERATS__030__M__1": "Ne?!",
"VO__SOPHIA__CH11__CHATTER__BRIDGERATS__070__M__1": "Sen öyle diyorsan! Nereden başlıyoruz?!",
"VO__SOPHIA__CH11__CHATTER__CANT_GO__015__M__1": "Canım...",
"VO__SOPHIA__CH11__CHATTER__CANT_GO__035__M__1": "Amicia...",
"VO__SOPHIA__CH11__CHATTER__CANT_GO_INTERACT__020__M__1": "Bu kadarı fazla...",
"VO__SOPHIA__CH11__CHATTER__CART_EXPLOSION_OK__030__M__1": "İşe yaradı mı?!",
"VO__SOPHIA__CH11__CHATTER__CART_RESTING__010__M__1": "Bak... Şu arabada gördüğümüz aynı Rum ateşi fıçısından var...",
"VO__SOPHIA__CH11__CHATTER__CART_WONT_MOVE__020__M__1": "Yerde bir şey var...",
"VO__SOPHIA__CH11__CHATTER__CARTPUZZLE_CRANK__010__M__1": "Bak, burada bir manivela...",
"VO__SOPHIA__CH11__CHATTER__CAVE_SLOPE__020__M__1": "Vay, vay!",
"VO__SOPHIA__CH11__CHATTER__CAVE_SQUEEZE_AFTER__040__M__1": "Geç, Hugo, ben arkanı kollarım.",
"VO__SOPHIA__CH11__CHATTER__CHAIN_DOWN__010__M__1": "Hey! Ne yaptın bilmiyorum ama işe yaradı!",
"VO__SOPHIA__CH11__CHATTER__CHAIN_DOWN_BIS__030__M__1": "Seni bekleyeceğiz!",
"VO__SOPHIA__CH11__CHATTER__CHEST_THERE__030__M__1": "Buna fazla alışma!",
"VO__SOPHIA__CH11__CHATTER__CISTERN_ENTRANCE__010__M__1": "Burası... pek davetkâr değil.",
"VO__SOPHIA__CH11__CHATTER__CISTERN_GOING_DOWN__015__M__1": "Kırık çıkık yok ya?!",
"VO__SOPHIA__CH11__CHATTER__CISTERN_GOING_DOWN__035__M__1": "Dikkat et!",
"VO__SOPHIA__CH11__CHATTER__CISTERN_LEVER__015__M__1": "Bir şeyi tetikledi...",
"VO__SOPHIA__CH11__CHATTER__CISTERN_LEVER__018__M__1": "Kesinlikle... Koşmaya hazır ol... her ihtimale karşı...",
"VO__SOPHIA__CH11__CHATTER__CISTERN_LEVER__035__M__1": "Burası lanet bir yer altı kalesi!",
"VO__SOPHIA__CH11__CHATTER__CLIMB_BURST__030__M__1": "Yürü! Yürü! Yürü!",
"VO__SOPHIA__CH11__CHATTER__CONTINUE__020__M__1": "Ona bir şey olmaz. Tanıdığım en becerikli kadın o!",
"VO__SOPHIA__CH11__CHATTER__CONTINUE__050__M__1": "Onu tanıyorsun! Bunu daha önce de yaptı! İnatçıdır. Onlardan çok daha inatçı.",
"VO__SOPHIA__CH11__CHATTER__CONTINUE__070__M__1": "Bütün bunlar çok korkunç... Ben de korkuyorum... Ama yine de güçsüz olduğumuz anlamına gelmez, değil mi?",
"VO__SOPHIA__CH11__CHATTER__CONTINUE__090__M__1": "Evet. Aramızda kalsın mı..?",
"VO__SOPHIA__CH11__CHATTER__CONTINUE_RATS_END__040__M__1": "Başaracağını söylemiştim!",
"VO__SOPHIA__CH11__CHATTER__CORRIDOR__020__M__1": "Öff... Ne... soluyoruz biz?",
"VO__SOPHIA__CH11__CHATTER__CROSSING_CART__060__M__1": "Bak, ciddi söylüyor evlat. Ona güven.",
"VO__SOPHIA__CH11__CHATTER__DOOR__010__M__1": "Şu kapıya bak!",
"VO__SOPHIA__CH11__CHATTER__DOOR__030__M__1": "Yanık izleri... Burada bir patlama olmuş...",
"VO__SOPHIA__CH11__CHATTER__DOOR__060__M__1": "Evet. Birisi içeri girmeyi cidden çok istemiş.",
"VO__SOPHIA__CH11__CHATTER__DOOR_BLOCKED__010__M__1": "Burada da bir patlama daha olmuş! Kapı tahrip olmuş...",
"VO__SOPHIA__CH11__CHATTER__EXPLORE__020__M__1": "Merdiven!",
"VO__SOPHIA__CH11__CHATTER__FEATHER_INTERACT__030__M__1": "Evet, mağara kuşları.",
"VO__SOPHIA__CH11__CHATTER__FIRE_LINE__020__M__1": "Ah lütfen, olmasın...",
"VO__SOPHIA__CH11__CHATTER__FIRST_PULL_BEGIN__020__M__1": "Raylara monte edilmiş, Rum ateşiyle besleniyor. Akıllıca.",
"VO__SOPHIA__CH11__CHATTER__FIRST_PUSH_START__020__M__1": "Tabii!",
"VO__SOPHIA__CH11__CHATTER__GATE_CHATTER_STUCK__020__M__1": "Hayır... Neden üzüleyim ki?",
"VO__SOPHIA__CH11__CHATTER__GATE_CHATTER_STUCK__040__M__1": "Merak etme evlat, bu dünyanın ne kadar... karmaşık olabildiğini bilirim.",
"VO__SOPHIA__CH11__CHATTER__GATE_CHATTER_STUCK__060__M__1": "Bunu çözeceğiz.",
"VO__SOPHIA__CH11__CHATTER__GATE_OPENING__014__M__1": "Evet, oluyor işte...",
"VO__SOPHIA__CH11__CHATTER__GATE_OPENING__040__M__1": "Aman Tanrım... İçeride gördüğüm şey hoşuma gitmedi...",
"VO__SOPHIA__CH11__CHATTER__GATE_READY__020__M__1": "Doğrusu biraz gerginim.",
"VO__SOPHIA__CH11__CHATTER__GATE_START__020__M__1": "Birkaç manivela görüyorum.",
"VO__SOPHIA__CH11__CHATTER__GOING_DOWN_1__070__M__1": "Zor, Hugo. Birbirimizi pek tanımıyoruz, ama ikinci bir şansı hak ettiğini biliyorum, onu cehennemde bulmamız gerekse bile.",
"VO__SOPHIA__CH11__CHATTER__GREEK_FIRE_PASS__020__M__1": "İyi misin?!",
"VO__SOPHIA__CH11__CHATTER__GREEK_FIRE_PASS__040__M__1": "O şeyi yoldan çekmen için sana bir fıçı göndereceğim!",
"VO__SOPHIA__CH11__CHATTER__HALL_PUZZLE_DONE__030__M__1": "O kız amma korkunç bir savaşçıymış...",
"VO__SOPHIA__CH11__CHATTER__HALLWAY_BACKTRACK__010__M__1": "Geri dönmüyoruz, değil mi?",
"VO__SOPHIA__CH11__CHATTER__HALLWAY_START__010__M__1": "Şu koku... boğucu...",
"VO__SOPHIA__CH11__CHATTER__HUB3_FESTIVAL_BACK__060__M__1": "Aman Tanrım...",
"VO__SOPHIA__CH11__CHATTER__HUB3_FESTIVAL_CARTFREE__020__M__1": "Oh... Kıl payı.",
"VO__SOPHIA__CH11__CHATTER__HUB3_FESTIVAL_CARTMOVING__090__M__1": "Hey, kendinize eziyet etmeyi keser misiniz ikiniz de?! Burası cehennem, evet, ama bir izimiz var, o yüzden birlikte kalıp bu işi sonuna kadar götüreceğiz!",
"VO__SOPHIA__CH11__CHATTER__HUB3_IDLE_MAP__010__M__1": "Bu ada benim için haritada küçük bir noktaydı sadece, düşünsene...",
"VO__SOPHIA__CH11__CHATTER__HUB3_MAP_AMPHI__010__M__1": "En değerli hazineni nereye saklarsın?",
"VO__SOPHIA__CH11__CHATTER__HUB3_MAP_AMPHI__040__M__1": "Onu... kırıyor muyuz?",
"VO__SOPHIA__CH11__CHATTER__HUB3_MAP_CLOSE__010__M__1": "Burnumuzun dibindeymiş, düşünsene...",
"VO__SOPHIA__CH11__CHATTER__HUB3_PUZZLE_CART__040__M__1": "Şu araba...",
"VO__SOPHIA__CH11__CHATTER__HUB3_START__050__M__1": "Onlar aptal hayvanlar, Hugo. Bizse üç akıllı ve güçlü insanız.",
"VO__SOPHIA__CH11__CHATTER__KEEP_UP__010__M__1": "Yetişebiliyor musun?!",
"VO__SOPHIA__CH11__CHATTER__LADDER_INSIDE__030__M__1": "Aferin!",
"VO__SOPHIA__CH11__CHATTER__LADDER_OUTSIDE__010__M__1": "Evet! Baştan sona geçebiliriz!",
"VO__SOPHIA__CH11__CHATTER__LAST_CART_PUSH__050__M__1": "Buna ben şahidim.",
"VO__SOPHIA__CH11__CHATTER__LAST_PUSH_CORRIDOR__015__M__1": "Var gücünle bas, Hugo! Neredeyse çıktık!",
"VO__SOPHIA__CH11__CHATTER__LAST_PUSH_CORRIDOR__020__M__1": "Cehennem olsun bu aşağılıklar! Çıkıyoruz!",
"VO__SOPHIA__CH11__CHATTER__LAST_RUN__020__M__1": "Bu Taşıyıcı'nın... ihtiyacın olan cevap olduğuna gerçekten emin misin?",
"VO__SOPHIA__CH11__CHATTER__LAST_RUN__040__M__1": "Birbirini gösterip duran ölü insanlar bunlar!",
"VO__SOPHIA__CH11__CHATTER__LAST_RUN__063__M__1": "Ha... Siz ikiniz...",
"VO__SOPHIA__CH11__CHATTER__LAST_RUN__070__M__1": "Nasılsın, Hugo?",
"VO__SOPHIA__CH11__CHATTER__LAST_RUN__090__M__1": "Nasıl tuhaf?",
"VO__SOPHIA__CH11__CHATTER__LAST_RUN__110__M__1": "Bundan ne kadar eminsin? Çünkü burası...",
"VO__SOPHIA__CH11__CHATTER__LAST_RUN__130__M__1": "Tamam! O... boş ver.",
"VO__SOPHIA__CH11__CHATTER__LEFT_PATH_NEW__020__M__1": "Hey, doğruca köprüye giden bir ray var! Ama şu enkaz tam ortasında gibi...",
"VO__SOPHIA__CH11__CHATTER__LEFT_PATH_RIGHT_DONE__020__M__1": "Şuradaki öteki ray köprüye gidiyor! Peki... şu lanet enkazı ne yapacağız?",
"VO__SOPHIA__CH11__CHATTER__LEVER_LEFT_OR_RIGHT__020__M__1": "Sanırım öyle!",
"VO__SOPHIA__CH11__CHATTER__LEVER_RIGHT__020__M__1": "Ortadaki çubukları hareket ettiriyor!",
"VO__SOPHIA__CH11__CHATTER__LEVER_RIGHT_RELEASE__020__M__1": "Tabii ki.",
"VO__SOPHIA__CH11__CHATTER__LIGHT__020__M__1": "Vay... Bu da ne böyle?!",
"VO__SOPHIA__CH11__CHATTER__LIGHT__030__M__1": "Evet, lütfen.",
"VO__SOPHIA__CH11__CHATTER__LIGHT__050__M__1": "Bir tür tapınak mı?",
"VO__SOPHIA__CH11__CHATTER__MOONLIGHT__010__M__1": "Sağda! Işık görüyorum!",
"VO__SOPHIA__CH11__CHATTER__MOONLIGHT__020__M__1": "Evet! Dışarısı!",
"VO__SOPHIA__CH11__CHATTER__OPENED_GATE_CORRIDOR__020__M__1": "Ha... Gidelim.",
"VO__SOPHIA__CH11__CHATTER__ORDER_SIGN__010__M__1": "Yerde, bak... Yine Düzen'in sembolü mü?",
"VO__SOPHIA__CH11__CHATTER__OUT_OF_SIGHT__030__M__1": "Hemen buradayım!",
"VO__SOPHIA__CH11__CHATTER__PUSHING_CART__010__M__1": "Ve eminim ki sağ kalanlar vardır! Sarayları bir kale gibi!",
"VO__SOPHIA__CH11__CHATTER__PUSHING_TANK__010__M__1": "Geri çekil, Hugo... İşte geliyor!",
"VO__SOPHIA__CH11__CHATTER__REACHING_LEFT_LIGHT__010__M__1": "Aferin!",
"VO__SOPHIA__CH11__CHATTER__REACHING_LEFT_LIGHT__020__M__1": "Şunu itelim.",
"VO__SOPHIA__CH11__CHATTER__REUNITING__050__M__1": "İster misin... biraz mola verelim?",
"VO__SOPHIA__CH11__CHATTER__REUNITING_WALKING_WATCH__030__M__1": "Sanırım bu, yaklaştığımız anlamına geliyor...",
"VO__SOPHIA__CH11__CHATTER__SECOND_PULL__020__M__1": "Demek bunu daha önce de gördün, ülkenin öbür ucunda? Tesadüf değildir herhâlde...",
"VO__SOPHIA__CH11__CHATTER__SLOPE_EDGE__020__M__1": "Umarım bir yerde ona yetişiriz.",
"VO__SOPHIA__CH11__CHATTER__SOUVENIR_BARBICAN__020__M__1": "Harita değil, bir plan... mekanizmaları görebiliyorsun...",
"VO__SOPHIA__CH11__CHATTER__SOUVENIR_BARBICAN__050__M__1": "Daha çok plan... Bunların isimleri var... Danimarka... Konstantinopolis... Bu Afrika gibi... Asya?!",
"VO__SOPHIA__CH11__CHATTER__SOUVENIR_BARBICAN__080__M__1": "Ne?",
"VO__SOPHIA__CH11__CHATTER__SOUVENIR_GATE__030__M__1": "Bu artık bir oyun odasına benzemiyor.",
"VO__SOPHIA__CH11__CHATTER__SOUVENIR_GATE__060__M__1": "Bir çocuk için fazlasıyla sağlam bir kapı.",
"VO__SOPHIA__CH11__CHATTER__STAIRS_VISTA__010__M__1": "Ah, kötü görünüyor...",
"VO__SOPHIA__CH11__CHATTER__STAIRS_VISTA__040__M__1": "Demek... aşağıda...",
"VO__SOPHIA__CH11__CHATTER__STAIRS_VISTA__060__M__1": "Ama ne? Ne oldu?! Ve ona ne oldu?",
"VO__SOPHIA__CH11__CHATTER__START__020__M__1": "Uzun zamandır buraya gelen ilk kişiyiz...",
"VO__SOPHIA__CH11__CHATTER__STORAGE__010__M__1": "Toprak kayması. Eğer bu onunsa, burayı baştan aşağı sarsmış.",
"VO__SOPHIA__CH11__CHATTER__STORAGE_BAG__010__M__1": "Hey, dur! Şu fıçılar... İçlerinde Rum ateşi varmış!",
"VO__SOPHIA__CH11__CHATTER__STORAGE_BAG__030__M__1": "Her zaman değil. Işıklarını yanık tutmak için kullanmış olmalılar. Biri hâlâ mühürlü...",
"VO__SOPHIA__CH11__CHATTER__STORAGE_BAG__040__M__1": "Öyle bir fıçıyla mı? Evet! Şu kapıda deneyelim!",
"VO__SOPHIA__CH11__CHATTER__STORAGE_BAG__060__M__1": "Bu duvarlar yeterince dayandı!",
"VO__SOPHIA__CH11__CHATTER__STORAGE_BAG__063__M__1": "Bunu yapıyoruz...",
"VO__SOPHIA__CH11__CHATTER__STORAGE_BAG__080__M__1": "Bir şeyleri patlatmaktan payıma düşeni almışımdır, bilesin!",
"VO__SOPHIA__CH11__CHATTER__STORAGE_BAG__090__M__1": "İşte!",
"VO__SOPHIA__CH11__CHATTER__STORAGE_EXPLOSION_HURT__040__M__1": "Tabii ki! Patlamaya fazla yakındın... Yaralandın mı?!",
"VO__SOPHIA__CH11__CHATTER__STUCK_CART__020__M__1": "Hey! Sıkıştın, değil mi?!",
"VO__SOPHIA__CH11__CHATTER__STUCK_CART__040__M__1": "Enkazın etrafından dolaş! Sana bir şeyimiz var!",
"VO__SOPHIA__CH11__CHATTER__TAKING_NEWS__040__M__1": "Henüz bir şey yok! Devam et!",
"VO__SOPHIA__CH11__CHATTER__TANK_SHOOT_FAIL__010__M__1": "Hayır! Onu arabaya yaklaştırman gerek! Çekmek için okunu kullan!",
"VO__SOPHIA__CH11__CHATTER__TANK_SHOOT_FAIL__030__M__1": "Sana bir tane daha göndereceğim! Bu sefer odaklan!",
"VO__SOPHIA__CH11__CHATTER__TO_COVER__010__M__1": "Şimdi siper al! Amicia, ateşlemeyi sen hallet!",
"VO__SOPHIA__CH11__CHATTER__TO_COVER__030__M__1": "Evet! Sadece başını eğik tut.",
"VO__SOPHIA__CH11__CHATTER__TURNINGWHEEL__040__M__1": "Tam da ihtiyacımız olan şey bu...",
"VO__SOPHIA__CH11__CHATTER__UPSTAIRS__020__M__1": "Yürü!",
"VO__SOPHIA__CH11__CHATTER__UPSTAIRS__030__M__1": "Sağa!",
"VO__SOPHIA__CH11__CHATTER__UPSTAIRS_CRATE__030__M__1": "Solunda! Kırık kapı!",
"VO__SOPHIA__CH11__CHATTER__UPSTAIRS_PASSAGE__040__M__1": "Tam orada!",
"VO__SOPHIA__CH11__CHATTER__UPSTAIRS_TWO__030__M__1": "Nefesini boşa harcama! Yanımda kal!",
"VO__SOPHIA__CH11__CHATTER__WRECK_BOOM_NEW__010__M__1": "Vay!",
"VO__SOPHIA__CH11__CHATTER__WRECK_BOOM_NEW__020__M__1": "Şimdi tek yapmamız gereken şu öteki raya ulaşmak...",
"VO__SOPHIA__CH11__HELPER__ACTIVATE_LOCK_2__010__M__1": "Çözdüm! Çubukları sonuna kadar çekebilirim, ve şu öteki kolla onları orada tutabiliriz! Hazır olunca söyle!",
"VO__SOPHIA__CH11__HELPER__BRIDGEPUZZLE_2LIGHT_FAR_1__010__M__1": "Şu mangala ulaşacak bir şeyin var mı? Yedeğinde simyacı numaraların var mı?",
"VO__SOPHIA__CH11__HELPER__BRIDGEPUZZLE_2LIGHT_FAR_2__010__M__1": "Katranınla o ışığı güçlendirmenin bir yolu var mı?",
"VO__SOPHIA__CH11__HELPER__BRIDGEPUZZLE_TANK_1__010__M__1": "Şu enkazdan kurtulmanın bir yolu olmalı...",
"VO__SOPHIA__CH11__HELPER__BRIDGEPUZZLE_TANK_2__010__M__1": "Hey! Şuraya bak! Bir fıçı daha var! Patlatalım!",
"VO__SOPHIA__CH11__HELPER__CISTERN_BRIDGE_1__010__M__1": "Belki hâlâ o köprüyü kaldırmanın bir yolu vardır?",
"VO__SOPHIA__CH11__HELPER__CISTERN_BRIDGE_2__010__M__1": "Amicia, şu şeyi kırmayı denesen?",
"VO__SOPHIA__CH11__HELPER__EXPLOSION_GATE_2__010__M__1": "Hey! Galiba şurada bir fıçı gördüm! O bizi geçirir!",
"VO__SOPHIA__CH11__HELPER__FIRST_PULL_BEGIN_ROPE_1__010__M__1": "Anlaşılan o arabalar kapıya tek yolumuz.",
"VO__SOPHIA__CH11__HELPER__FIRST_PULL_BEGIN_ROPE_2__010__M__1": "O arabalardan birini yay numaranla çekmeyi denemek ister misin? Tam şurada bir ip var.",
"VO__SOPHIA__CH11__HELPER__GET_ROPE_CART_1__010__M__1": "Sanırım o kapıyı açmak için fazladan bir el gerekecek...",
"VO__SOPHIA__CH11__HELPER__GET_ROPE_CART_2__010__M__1": "Hey! Şurada bir araba var! Belki onu kullanabiliriz!",
"VO__SOPHIA__CH11__HELPER__HUB3_CARTSTUCK_1__010__M__1": "Bu araba işe yarayabilir, değil mi?",
"VO__SOPHIA__CH11__HELPER__HUB3_CARTSTUCK_2__010__M__1": "Şu ipi kullanıp arabayı kurtarsana?",
"VO__SOPHIA__CH11__HELPER__HUB3_GRASS_FIRE_2__010__M__1": "Hey! Şu otları ateşe vermeyi denesen?",
"VO__SOPHIA__CH11__HELPER__STORAGE_EXPLOSION_IGNITE_1__010__M__1": "Şu fıçıyı patlat, Amicia!",
"VO__SOPHIA__CH11__HELPER__STORAGE_EXPLOSION_IGNITE_2__010__M__1": "Ateş şeylerinden birini fıçıya kullan. O patlatır.",
"VO__SOPHIA__CH11__HELPER__UNLOCK_DOOR_1__010__M__1": "Yani... her iki taraftaki çubukları da kilitlememiz gerek...",
"VO__SOPHIA__CH11__HELPER__UNLOCK_DOOR_2__010__M__1": "Galiba çözdüm! Hugo! Sen çubukların bir tarafını kilitle! Amicia, sen de öteki tarafı kilitlemek için şu arabayı kullan! Sonra manivelayı birlikte hallederiz!",
"VO__SOPHIA__CH11__HELPER__USE_ROPE_CART_1__010__M__1": "Acaba bir kolu basılı tutmak için arabayı kullanabilir miyiz?",
"VO__SOPHIA__CH11__HELPER__USE_ROPE_CART_2__010__M__1": "Hey! Şu kolu yayınla arabaya bağlasana?",
"VO__SOPHIA__CH11__RTC__520_BACK_FROM_THE_FORT__040__M__1": "Fazla kafa yorma. Haritaya gidelim. Buraya bunun için geldin.",
"VO__SOPHIA__CH11__RTC__530_ENTER_TOMB__040__M__1": "İt!",
"VO__SOPHIA__CH11__RTC__530_ENTER_TOMB__050__M__1": "Vuhu, bu rahatlatıcıydı...",
"VO__SOPHIA__CH11__RTC__530_ENTER_TOMB__070__M__1": "... ama yazık oldu çünkü çok eskiydi, evet.",
"VO__SOPHIA__CH11__RTC__530_ENTER_TOMB__100__M__1": "Neye karşı mühürlenmiş?",
"VO__SOPHIA__CH11__RTC__530_ENTER_TOMB__150__M__1": "Ama karanlık senden de korkuyor. Tek bir ışık, ve kayboluyor...",
"VO__SOPHIA__CH11__RTC__550_ALTAR__010__M__1": "“Birini Koru, Hepsini Koru.” Kaledeki şapelde yazan buydu.",
"VO__SOPHIA__CH11__RTC__550_ALTAR__030__M__1": "Onlara cehennemi yaşatmış resmen...",
"VO__SOPHIA__CH11__RTC__550_ALTAR__080__M__1": "Hadi ama, koca adam oldun sen! Şu kapıya bir bakalım.",
"VO__SOPHIA__CH11__RTC__550_ALTAR__100__M__1": "Bunu nasıl açacağımıza dair bir fikrin var mı?",
"VO__SOPHIA__CH11__RTC__550_ALTAR__120__M__1": "Ne? Bunca şeyden sonra mı? Hadi ama!",
"VO__SOPHIA__CH11__RTC__550_ALTAR__140__M__1": "Eh işte...",
"VO__SOPHIA__CH11__RTC__555_COLLAPSE__040__M__1": "YÜRÜ!",
"VO__SOPHIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__010__M__1": "Bu...?",
"VO__SOPHIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__070__M__1": "Bir çocuğu ölüme terk etmişler...",
"VO__SOPHIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__100__M__1": "Ne?",
"VO__SOPHIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__160__M__1": "Hiçbir şey görmüyorum!",
"VO__SOPHIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__180__M__1": "Amicia...",
"VO__SOPHIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__200__M__1": "Biliyorum!",
"VO__SOPHIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__310__M__1": "Pek aynı fikirde değiller gibi.",
"VO__SOPHIA__CH11__RTC__560_REMAINS_OF_A_CARRIER__330__M__1": "Gitmeliyiz!",
"VO__SOPHIA__CH11__RTC__570_LETS_GO_HOME__010__M__1": "İçeride kapalı kaldıklarını söyle bana...",
"VO__SOPHIA__CH11__RTC__570_LETS_GO_HOME__040__M__1": "Macula'nın çocuklarla arası gerçekten iyi.",
"VO__SOPHIA__CH11__RTC__570_LETS_GO_HOME__090__M__1": "Benim gibi!",
"VO__SOPHIA__CH11__RTC__570_LETS_GO_HOME__170__M__1": "Yakalamamız gereken bir tekne var, ve önce bir sıçan denizini geçmemiz gerek.",
}
