# -*- coding: utf-8 -*-
# CH04 VO (katran atolyesi, Joseph, sehrin yikilisi). onom/EMPTY atlanir.
# Carrier->Tasiyici, threshold->esik, Protector->Koruyucu, tar->katran, resin->recine,
# basin->havuz, the Bite->Isirik, the Beast->Canavar, Marseille->Marsilya.
T = {
"VO__ALCHEMIST__CH04__RTC__124_CONDEMNED__070__M__1": "Bir Taşıyıcı'nın son eşiğe ulaşması çok nadir bir olaydır. Vahim bir olay. Elbette, bundan böyle onu tecrit etmemiz gerek. Düzen'in özel binaları var...",
"VO__ALCHEMIST__CH04__RTC__124_CONDEMNED__090__M__1": "Kardeşinin neler yapabileceğini biliyor musun? Çok daha beterini yapacak.",
"VO__ALCHEMIST__CH04__RTC__124_CONDEMNED__110__M__1": "Bu yüzden onu götürmemiz gerek. Günleri kısaldıkça gücü daha da artacak.",
"VO__ALCHEMIST__CH04__RTC__124_CONDEMNED__150__M__1": "Son eşik, Taşıyıcı'nın ölümü demektir.",
"VO__ALCHEMIST__CH04__RTC__124_CONDEMNED__170__M__1": "Kardeşin ilk eşiğe ulaştığında arkadaşın sana zaman kazandırdı, ama bu başka bir şey. Bunu durdurmanın yolu yok. Ne iksir ne de macun.",
"VO__ALCHEMIST__CH04__RTC__124_CONDEMNED__190__M__1": "Bu bir çocuğun hayali!",
"VO__ALCHEMIST__CH04__RTC__124_CONDEMNED__220__M__1": "Zavallı kız... Gerçeklikten kaçıyorsun! Kardeşinin kaderini ve kendininkini kabul etmelisin... Ve bir Koruyucu'nun kaderi, Düzen'in buyurduğunu yapmaktır.",
"VO__ALCHEMIST__CH04__RTC__124_CONDEMNED__280__M__1": "En kısa zamanda Marsilya'daki Düzen karargâhına gidiyoruz. Limanda bekleyen bir teknem ve bir adamım var, Joseph; uyarılması gerek. Bana gelince, dinlenmeye gidiyorum. Gitmeye hazır olduğunuzda haber verin.",
"VO__ALCHEMIST__CH04__RTC__150_JUST_A_NIGHTMARE__030__M__1": "O senin oğlun! Bir şey yap!",
"VO__ALCHEMIST__CH04__RTC__150_JUST_A_NIGHTMARE__040__M__1": "Ah! Koruyucu, nihayet!",
"VO__AMICIA__CH04__CHATTER__1ST_BASIN_LIGHT__010__M__1": "Pekâlâ! Bu bir şey!...",
"VO__AMICIA__CH04__CHATTER__1ST_BASIN_LIGHT__030__M__1": "Bu, hıı...",
"VO__AMICIA__CH04__CHATTER__1ST_BASIN_LIGHT__060__M__1": "Çok yazık, çünkü paçanı kurtaracak!",
"VO__AMICIA__CH04__CHATTER__1ST_BASIN_LIGHT__080__M__1": "Askerler...",
"VO__AMICIA__CH04__CHATTER__1ST_BASIN_POURRING__010__M__1": "Ve yine başlıyoruz...",
"VO__AMICIA__CH04__CHATTER__1ST_BASIN_POURRING__030__M__1": "Evet...",
"VO__AMICIA__CH04__CHATTER__1ST_BASIN_SHOULD_LIGHT__020__M__1": "Yöntemlerimiz var...",
"VO__AMICIA__CH04__CHATTER__1ST_BASIN_SHOULD_LIGHT__040__M__1": "Sadece bekle...",
"VO__AMICIA__CH04__CHATTER__1ST_BASIN_SHOULD_POUR__020__M__1": "Teşekkürler!",
"VO__AMICIA__CH04__CHATTER__1ST_BASIN_SHOULD_POUR__040__M__1": "Ya da henüz çözememiştir...",
"VO__AMICIA__CH04__CHATTER__2ND_BASIN_LIGHT__010__M__1": "İşte böyle!",
"VO__AMICIA__CH04__CHATTER__2ND_BASIN_POURRING__010__M__1": "İşte...",
"VO__AMICIA__CH04__CHATTER__2ND_BASIN_SHOULD_LIGHT__020__M__1": "Onu bana bırak!",
"VO__AMICIA__CH04__CHATTER__2ND_BASIN_SHOULD_POUR__010__M__1": "Harika! Yerinde.",
"VO__AMICIA__CH04__CHATTER__3RD_BASIN_LIGHT__010__M__1": "İşte!",
"VO__AMICIA__CH04__CHATTER__3RD_BASIN_POURRING__010__M__1": "Hadi bakalım...",
"VO__AMICIA__CH04__CHATTER__3RD_BASIN_SHOULD_LIGHT__010__M__1": "Ve tamam!",
"VO__AMICIA__CH04__CHATTER__A_WAY_OUT__020__M__1": "Bir katran birikintisi... Arkadaki o kapıya giden yolumuz olabilir!",
"VO__AMICIA__CH04__CHATTER__A_WAY_OUT__040__M__1": "Ona ulaşmanın bir yolunu bulabiliriz...",
"VO__AMICIA__CH04__CHATTER__AFTER_ATTACK__020__M__1": "Çok fazlalar!",
"VO__AMICIA__CH04__CHATTER__AFTER_CLOSE_DOOR__010__M__1": "Aman Tanrım...",
"VO__AMICIA__CH04__CHATTER__ALCOHOL_DONE__020__M__1": "Pekâlâ!",
"VO__AMICIA__CH04__CHATTER__AMPLIFY_LUCKY_USES__010__M__1": "Vay! Ne?!",
"VO__AMICIA__CH04__CHATTER__AMPLIFY_LUCKY_USES__040__M__1": "Anladım! Onu sonra yapalım.",
"VO__AMICIA__CH04__CHATTER__AMPLIFY_TUTORIAL__010__M__1": "Hayır... Işık yeterince uzağa ulaşmıyor!",
"VO__AMICIA__CH04__CHATTER__AMPLIFY_TUTORIAL__050__M__1": "Pekâlâ, deneyelim!",
"VO__AMICIA__CH04__CHATTER__AMPLIFY_TUTORIAL__080__M__1": "Vaay! Gözlerim!",
"VO__AMICIA__CH04__CHATTER__AMPLIFY_TUTORIAL__100__M__1": "Çok parlak!",
"VO__AMICIA__CH04__CHATTER__AMPLIFY_TUTORIAL__120__M__1": "Mükemmel işe yaradı! Teşekkürler!",
"VO__AMICIA__CH04__CHATTER__AMPLIFY_TUTORIAL__130__M__1": "Çömlekleri gördük... Onunla ne yapıyorsun?",
"VO__AMICIA__CH04__CHATTER__AMPLIFY_TUTORIAL__150__M__1": "Hmmm. Doğru...",
"VO__AMICIA__CH04__CHATTER__ATTACK__010__M__1": "Aman Tanrım!",
"VO__AMICIA__CH04__CHATTER__ATTACK__030__M__1": "Geride dur!",
"VO__AMICIA__CH04__CHATTER__BACK_CITY__011__M__1": "Başardık.",
"VO__AMICIA__CH04__CHATTER__BACK_CITY__020__M__1": "Evet. Acelemiz var.",
"VO__AMICIA__CH04__CHATTER__BACK_CITY__040__M__1": "Aslında, o yöne devam etmeliyiz.",
"VO__AMICIA__CH04__CHATTER__BACK_CITY__060__M__1": "Bırakın gidelim! Üzerimize düşeni yaptık!",
"VO__AMICIA__CH04__CHATTER__BACK_CITY__072__M__1": "Bırak geçelim, yoksa pişman olursun...",
"VO__AMICIA__CH04__CHATTER__BACK_CITY__080__M__1": "Öyleyim! Bu çok önemli!",
"VO__AMICIA__CH04__CHATTER__BEFORE_MEETING__020__M__1": "Dikkatli olacağız... Şehirde karşılaşsaydık kim bilir ne yapardı...",
"VO__AMICIA__CH04__CHATTER__BEFORE_MEETING__040__M__1": "Evet... her ne idiyseler...",
"VO__AMICIA__CH04__CHATTER__BEHIND_LAST_DOOR__020__M__1": "Orada!",
"VO__AMICIA__CH04__CHATTER__BIG_BOATS__010__M__1": "Geldik... Peki teknemiz nerede?",
"VO__AMICIA__CH04__CHATTER__BITE__005__M__1": "Herkesi hasta saymışlar...",
"VO__AMICIA__CH04__CHATTER__BITE__015__M__1": "Evet... İnsanları içeri hapset, sonra onlardan kurtul.",
"VO__AMICIA__CH04__CHATTER__BOAT__090__M__1": "İyi olacaksın Hugo. Sana söz veriyorum.",
"VO__AMICIA__CH04__CHATTER__BODIES_REACTIONS_1__010__M__1": "Aralarında Annemi ve Hugo'yu göreceğim diye çok korkuyorum...",
"VO__AMICIA__CH04__CHATTER__BODIES_REACTIONS_1__030__M__1": "Umarım haklısındır.",
"VO__AMICIA__CH04__CHATTER__CAREFUL__010__M__1": "Vay!... O neydi?!",
"VO__AMICIA__CH04__CHATTER__CAREFUL__030__M__1": "Bu... hızlı bir yöntem... Lucas, çok tehlikeli oluyor. Ya öldürülürüz ya da o tekneyi kaçırırız... Sapanımı yeniden kullanmam gerek.",
"VO__AMICIA__CH04__CHATTER__CAREFUL__050__M__1": "Güzel, gidelim.",
"VO__AMICIA__CH04__CHATTER__CART_PULL__021__M__1": "Sakinleşmezlerse...",
"VO__AMICIA__CH04__CHATTER__CART_STUCK__050__M__1": "Ve aynı hatayı tekrarlıyorlar...",
"VO__AMICIA__CH04__CHATTER__CHARIOT_WHAT__020__M__1": "Doğru...",
"VO__AMICIA__CH04__CHATTER__CLIMB_UP_FENCE__010__M__1": "Hadi... gel...",
"VO__AMICIA__CH04__CHATTER__CLOSE_DOOR__010__M__1": "Hayır, hayır, hayır!",
"VO__AMICIA__CH04__CHATTER__COLLAPSING__010__M__1": "Lütfen Hugo... Buna son ver!",
"VO__AMICIA__CH04__CHATTER__COLLAPSING__020__M__1": "Sana geliyorum!",
"VO__AMICIA__CH04__CHATTER__COMPONENTS_THROW__020__M__1": "O canavarlar... çok yakın!",
"VO__AMICIA__CH04__CHATTER__COMPONENTS_THROW__040__M__1": "Hadi!",
"VO__AMICIA__CH04__CHATTER__COURTYARD__010__M__1": "Hugo! Benim!",
"VO__AMICIA__CH04__CHATTER__CRANK_LET_GO__020__M__1": "Yine deneyeceğim.",
"VO__AMICIA__CH04__CHATTER__CROSSBOW__010__M__1": "Hayır! Sıkıştık!",
"VO__AMICIA__CH04__CHATTER__DID_IT_DOOR__010__M__1": "Ha... Tanrım...",
"VO__AMICIA__CH04__CHATTER__DID_IT_DOOR__030__M__1": "Artık hiçbirine güvenmiyorum!",
"VO__AMICIA__CH04__CHATTER__DOWN_PATROL__005__M__1": "Bir devriye!",
"VO__AMICIA__CH04__CHATTER__DOWN_PATROL__040__M__1": "İşte! Bütün şehri kapatıyorlar!",
"VO__AMICIA__CH04__CHATTER__DOWN_PATROL__070__M__1": "Koca bir şehri temizlemeye cüret edemezler, değil mi?!",
"VO__AMICIA__CH04__CHATTER__DOWN_PATROL__090__M__1": "O tekneye çabuk lazım.",
"VO__AMICIA__CH04__CHATTER__END_PUSH__010__M__1": "Daha öteye gitmeyecek...",
"VO__AMICIA__CH04__CHATTER__ENTRY_DEPOT__007__M__1": "Öf... Şu koku...",
"VO__AMICIA__CH04__CHATTER__ENTRY_DEPOT__010__M__1": "Hiç fare sesi duymuyorum?...",
"VO__AMICIA__CH04__CHATTER__ENTRY_DEPOT__030__M__1": "Tanrım... Bütün bunlar ne?",
"VO__AMICIA__CH04__CHATTER__FAULT__040__M__1": "Üzgünüm...",
"VO__AMICIA__CH04__CHATTER__FINDING_CRANK__030__M__1": "İçeriden kilitli...",
"VO__AMICIA__CH04__CHATTER__FIRE_AFAR__020__M__1": "Kimsenin şehirden kaçmadığından emin oluyorlar...",
"VO__AMICIA__CH04__CHATTER__FIRS_STEPS_JETTY__020__M__1": "Evet...",
"VO__AMICIA__CH04__CHATTER__FIRST_STEPS__015__M__1": "Ben yaparım.",
"VO__AMICIA__CH04__CHATTER__FIRST_STEPS__030__M__1": "Bir şey yok... Uyumaya dön...",
"VO__AMICIA__CH04__CHATTER__FIRST_STEPS__050__M__1": "Öylesine \"olmadı\" bu, Anne!",
"VO__AMICIA__CH04__CHATTER__FIRST_STEPS__070__M__1": "Bunu biz yaptık...",
"VO__AMICIA__CH04__CHATTER__FIRST_STEPS_BEA__020__M__1": "Gel!",
"VO__AMICIA__CH04__CHATTER__FLAMES__030__M__1": "Sipere!",
"VO__AMICIA__CH04__CHATTER__FLAMES__035__M__1": "Lanet...",
"VO__AMICIA__CH04__CHATTER__FLAMES__050__M__1": "Bu Joseph simyacı değil...",
"VO__AMICIA__CH04__CHATTER__FLOWER__010__M__1": "Ah...",
"VO__AMICIA__CH04__CHATTER__FLOWER__020__M__1": "Çok güzel görünüyor... Onu alacağım... Hugo için.",
"VO__AMICIA__CH04__CHATTER__FLOWER__040__M__1": "Ona çok daha fazlasını sunmak isterdim...",
"VO__AMICIA__CH04__CHATTER__FLOWER__060__M__1": "Buna katılır mı emin değilim.",
"VO__AMICIA__CH04__CHATTER__FOOTBRIDGE_MOVE__030__M__1": "Geliyorum!",
"VO__AMICIA__CH04__CHATTER__FOOTBRIDGE_MOVE__050__M__1": "Hazır mıyız?",
"VO__AMICIA__CH04__CHATTER__FOOTBRIDGE_SET__020__M__1": "Pekâlâ!",
"VO__AMICIA__CH04__CHATTER__FOOTBRIDGE_SET__040__M__1": "Bırakıyorum! Tutun!",
"VO__AMICIA__CH04__CHATTER__FRONT_HANGAR__010__M__1": "Ha... Daha fazlası...",
"VO__AMICIA__CH04__CHATTER__GATE__080__M__1": "Askerler! Miğferli... Etraflarından sıvışmamız gerekecek...",
"VO__AMICIA__CH04__CHATTER__GATE__100__M__1": "Sence arkasında ne var?",
"VO__AMICIA__CH04__CHATTER__GATE_END__020__M__1": "İskele o kapının arkasında olmalı...",
"VO__AMICIA__CH04__CHATTER__GATE_END__040__M__1": "Başı dertte olabilir. Daha hızlı hareket etmeliyiz.",
"VO__AMICIA__CH04__CHATTER__GEAR_SPOTTED__020__M__1": "Oraya geçmeliyiz.",
"VO__AMICIA__CH04__CHATTER__HUGO_AWAKE__020__M__1": "Bakma... Gözlerini kapalı tut...",
"VO__AMICIA__CH04__CHATTER__HUGO_AWAKE__040__M__1": "Bu... fareler... saldırdılar...",
"VO__AMICIA__CH04__CHATTER__HUGO_AWAKE__060__M__1": "Üzgünüm...",
"VO__AMICIA__CH04__CHATTER__IDLE_FIRE_ZONE_3__020__M__1": "Umarım birkaç saatlik meseledir. Joseph dövüşmeyi biliyor. Bu iyi bir şey.",
"VO__AMICIA__CH04__CHATTER__IDLE_FIRE_ZONE_4__020__M__1": "Şimdi ben de kokladım...",
"VO__AMICIA__CH04__CHATTER__IDLE_FIRE_ZONE_6__020__M__1": "Joseph güvenilir görünüyor... Aradığımız yardım o olabilir.",
"VO__AMICIA__CH04__CHATTER__IDLE_FIRE_ZONE_6__040__M__1": "Para biziz. Ve yardıma ihtiyacımız var, gerisi umurumda değil.",
"VO__AMICIA__CH04__CHATTER__IGNIFER_OK__020__M__1": "Geliyorum!",
"VO__AMICIA__CH04__CHATTER__IM_HERE__010__M__1": "Buradayım...",
"VO__AMICIA__CH04__CHATTER__INTERACT_CRANK__020__M__1": "Onu bana bırak...",
"VO__AMICIA__CH04__CHATTER__INTERACT_LADDER__010__M__1": "Bir bakayım...",
"VO__AMICIA__CH04__CHATTER__INTERACT_LADDER__020__M__1": "Hm... Evet, ya katran ya hiç...",
"VO__AMICIA__CH04__CHATTER__INTRO_SIMON_BRIGDGE_DOWN__020__M__1": "Evet... Biz... Sadece geçiyoruz!",
"VO__AMICIA__CH04__CHATTER__INTRO_SIMON_BRIGDGE_DOWN__070__M__1": "Bir planımız var! Şu köprüyü bize gönderebilir misin?",
"VO__AMICIA__CH04__CHATTER__INTRO_SIMON_BRIGDGE_UP__040__M__1": "Biz... Sadece geçiyoruz!",
"VO__AMICIA__CH04__CHATTER__INTRO_SIMON_BRIGDGE_UP__055__M__1": "Bir planımız var! Şu köprüye erişimin var mı?",
"VO__AMICIA__CH04__CHATTER__INTRO_SIMON_BRIGDGE_UP__090__M__1": "Onu hâllederim!",
"VO__AMICIA__CH04__CHATTER__JAR_DONE__010__M__1": "Tamam!",
"VO__AMICIA__CH04__CHATTER__JAR_FAIL__011__M__1": "Hayır... Daha iyi nişan almam lazım...",
"VO__AMICIA__CH04__CHATTER__JOSEPH_3RD_KILL__020__M__1": "Bilmiyorum... Asker olmuş olmalı...",
"VO__AMICIA__CH04__CHATTER__JOSEPH_4TH_KILL__010__M__1": "Bir tane daha indirdi!",
"VO__AMICIA__CH04__CHATTER__JOSEPH_5TH_KILL__020__M__1": "En azından Düzen işe yarar bir şey yaptı...",
"VO__AMICIA__CH04__CHATTER__JOSEPH_6TH_KILL__010__M__1": "Biri eksildi... Devam edelim!",
"VO__AMICIA__CH04__CHATTER__LAST_RUN__010__M__1": "Dayan... Hugo! Neredeyse... vardık...",
"VO__AMICIA__CH04__CHATTER__LAST_WORKBENCH__010__M__1": "Şunu çabuk yapalım...",
"VO__AMICIA__CH04__CHATTER__LINES_PATROL__040__M__1": "Evet, şimdi onlara \"denetiminin\" ne demek olduğunu anlat...",
"VO__AMICIA__CH04__CHATTER__LOCK_SHOT__020__M__1": "Demek artık katran yapıyoruz...",
"VO__AMICIA__CH04__CHATTER__LOCK_SHOT__040__M__1": "Hadi, işe koyulalım...",
"VO__AMICIA__CH04__CHATTER__LUCAS_SHOULD_JOIN__010__M__1": "Lucas gelebilirsin, yol açık!",
"VO__AMICIA__CH04__CHATTER__LUCAS_WONT_MOVE_FOOTBRIGE__020__M__1": "Haklısın.",
"VO__AMICIA__CH04__CHATTER__MARKET_STEALTH__010__M__1": "Bunların hepsi yanlış...",
"VO__AMICIA__CH04__CHATTER__MARKET_STEALTH__030__M__1": "Fareler oraya dalana kadar bekle!",
"VO__AMICIA__CH04__CHATTER__MARKET_VISTA__020__M__1": "Yaklaşıyoruz...",
"VO__AMICIA__CH04__CHATTER__MID_ZONE__010__M__1": "Evet... Kocaman...",
"VO__AMICIA__CH04__CHATTER__MID_ZONE__030__M__1": "Anlaşılan biri karanlıktan korkuyor...",
"VO__AMICIA__CH04__CHATTER__MOVE_2ND_GATE_EARLY_STOP__010__M__1": "Haklısın. Önce şunu bitirelim.",
"VO__AMICIA__CH04__CHATTER__MOVE_2ND_GATE_EARLY_SUCCEED__010__M__1": "İkinci havuza sonra döneriz!",
"VO__AMICIA__CH04__CHATTER__NEAR_SQUEEZE__010__M__1": "Buradan!...",
"VO__AMICIA__CH04__CHATTER__NEXT_2ND_BASIN__020__M__1": "O zaman işe koyulalım.",
"VO__AMICIA__CH04__CHATTER__NEXT_2ND_BASIN__040__M__1": "Pekâlâ. Sana ihtiyacım olunca söylerim!",
"VO__AMICIA__CH04__CHATTER__NEXT_3RD_BASIN__010__M__1": "Hâlâ yolu kapatan bir tekne var!",
"VO__AMICIA__CH04__CHATTER__OIL_HOT__010__M__1": "Şu alevlere dikkat...",
"VO__AMICIA__CH04__CHATTER__OIL_HOUSE_NEAR__010__M__1": "Buradan deneyelim...",
"VO__AMICIA__CH04__CHATTER__OIL_TUTO__010__M__1": "Onu nasıl geçeceğiz?!",
"VO__AMICIA__CH04__CHATTER__OIL_TUTO__020__M__1": "Yerdeki o sıvı... çömleklerinden!",
"VO__AMICIA__CH04__CHATTER__OIL_TUTO__023__M__1": "Evet... Evet... Deneyelim...",
"VO__AMICIA__CH04__CHATTER__OIL_TUTO__024__M__1": "Bak! O kapıyı bir zincir kapatıyor! Onu kırabilir misin?!",
"VO__AMICIA__CH04__CHATTER__OPEN_SPACE__010__M__1": "Lütfen, sakin ol... Üzgün ve öfkeli olmaya hakkın var... Ama seni yarı yolda bırakmam, bunu biliyorsun...",
"VO__AMICIA__CH04__CHATTER__OPEN_SPACE_CRY__030__M__1": "Çok geç. Devam et.",
"VO__AMICIA__CH04__CHATTER__OPEN_SPACE_HELP__030__M__1": "Uyumaya çalış Hugo. Bunu benim için yap...",
"VO__AMICIA__CH04__CHATTER__OUTSIDE3_INTRO__020__M__1": "Hayır! Hugo'yu biliyor muydun?!",
"VO__AMICIA__CH04__CHATTER__OUTSIDE3_INTRO__040__M__1": "Bilmeliydin! Kardeşimden bahsediyoruz Lucas!",
"VO__AMICIA__CH04__CHATTER__OUTSIDE3_INTRO__060__M__1": "Tanrım... Yapamıyorum... Ha... Hadi devam edelim...",
"VO__AMICIA__CH04__CHATTER__OVER_GATE__010__M__1": "Ah... hayır...",
"VO__AMICIA__CH04__CHATTER__OVER_GATE__015__M__1": "Tanrım... Bir savaş alanına... benziyor...",
"VO__AMICIA__CH04__CHATTER__OVER_GATE__030__M__1": "Bilmiyorum ama... Şu arabayı takip edelim. Ve gözümüzü açık tutalım.",
"VO__AMICIA__CH04__CHATTER__PASSAGE__020__M__1": "Daha çok belaya bulaşıyoruz, derim.",
"VO__AMICIA__CH04__CHATTER__PASSAGE__060__M__1": "Evet. Ve yakında sen de birinde yerini alacaksın.",
"VO__AMICIA__CH04__CHATTER__PLANNING__020__M__1": "Evet, şu merdivenden çık! Platformu yaklaştıracağım!",
"VO__AMICIA__CH04__CHATTER__PONTOON_CHEST__010__M__1": "Umarım geçebiliriz.",
"VO__AMICIA__CH04__CHATTER__POST_DEPOT_DEBRIEF__010__M__1": "Bundan o kadar emin olma.",
"VO__AMICIA__CH04__CHATTER__POST_DEPOT_DEBRIEF__030__M__1": "Sadece... hazır değildim. Onu kaybedemem... Kaybedemem.",
"VO__AMICIA__CH04__CHATTER__POST_DEPOT_DEBRIEF__050__M__1": "Bulacağız.",
"VO__AMICIA__CH04__CHATTER__POURING_ALCOHOL__020__M__1": "Miktarları biliyor musun?",
"VO__AMICIA__CH04__CHATTER__POURING_ALCOHOL__040__M__1": "Lütfen bizi öldürme...",
"VO__AMICIA__CH04__CHATTER__PUSHABLE_BRAZIER__020__M__1": "Evet...",
"VO__AMICIA__CH04__CHATTER__PUZZLE_END__009__M__1": "Öf... paçamı kurtardın...",
"VO__AMICIA__CH04__CHATTER__PUZZLE_END__020__M__1": "Her neyse, teşekkürler...",
"VO__AMICIA__CH04__CHATTER__PYRE__020__M__1": "Hepsi burada son buluyor...",
"VO__AMICIA__CH04__CHATTER__QUAI__066__M__1": "Hareket etmeye devam et. Sessizce.",
"VO__AMICIA__CH04__CHATTER__RAT_BURST__030__M__1": "Şimdi ne olacak? Sıkıştım!",
"VO__AMICIA__CH04__CHATTER__RATS_FIGHT_BLINDING__015__M__1": "Buna vaktimiz yok!",
"VO__AMICIA__CH04__CHATTER__RATS_FIGHT_BLINDING__020__M__1": "Koş! Merdivenlere!",
"VO__AMICIA__CH04__CHATTER__RATS_THINKING__020__M__1": "Vaudin gibi insanlar mı?! Sence bu nasıl bitecek?!",
"VO__AMICIA__CH04__CHATTER__RATS_THINKING__040__M__1": "Burada kalmak zaten ölmek demek.",
"VO__AMICIA__CH04__CHATTER__REGION__018__M__1": "Umarım hâlâ vaktimiz vardır...",
"VO__AMICIA__CH04__CHATTER__REGION__030__M__1": "Her zaman yapabilirler.",
"VO__AMICIA__CH04__CHATTER__RESUME_RUN__020__M__1": "Hadi! Hadi!",
"VO__AMICIA__CH04__CHATTER__ROOF_SPRINT__010__M__1": "Daha hızlı... Daha hızlı!",
"VO__AMICIA__CH04__CHATTER__RUMBLE__020__M__1": "Hugo... Neler oluyor?! Sana ne yaptılar?!",
"VO__AMICIA__CH04__CHATTER__RUN__010__M__1": "Hayır... Hayır!",
"VO__AMICIA__CH04__CHATTER__RUN_ALLEY__020__M__1": "Orada kalma hanımefendi! Geliyorlar!",
"VO__AMICIA__CH04__CHATTER__RUN_BACK__010__M__1": "Hayır... Nerede...?",
"VO__AMICIA__CH04__CHATTER__RUN_BACK__020__M__1": "Çekilin yoldan!",
"VO__AMICIA__CH04__CHATTER__RUN_COLLAPSE__010__M__1": "Onu alamayacaksınız! Alamayacaksınız!",
"VO__AMICIA__CH04__CHATTER__RUN_DOOR__005__M__1": "Söylemiştim! Bunun olacağını söylemiştim!",
"VO__AMICIA__CH04__CHATTER__RUN_DOOR__010__M__1": "Eminim o lanet Vaudin yüzünden!",
"VO__AMICIA__CH04__CHATTER__RUN_FALL__020__M__1": "Ha... Tanrım...",
"VO__AMICIA__CH04__CHATTER__RUN_SQUEEZE__010__M__1": "Hadi... Daha hızlı kımılda!",
"VO__AMICIA__CH04__CHATTER__RUN_STAIRS__010__M__1": "Lütfen buna son ver...",
"VO__AMICIA__CH04__CHATTER__RUN_TOWER__010__M__1": "Ne?!",
"VO__AMICIA__CH04__CHATTER__RUN_TOWER__030__M__1": "Sizi lanet... iblisler!",
"VO__AMICIA__CH04__CHATTER__RUN_VISTA__010__M__1": "Ev... Yapabilirim!",
"VO__AMICIA__CH04__CHATTER__RUN_VISTA_CASTLE__010__M__1": "Ne?...",
"VO__AMICIA__CH04__CHATTER__RUN_VISTA_CASTLE__020__M__1": "Eyvah... hayır... Hayır!",
"VO__AMICIA__CH04__CHATTER__RUN_WINDOW__010__M__1": "Ev! Hâlâ ayakta... Hadi, hadi!",
"VO__AMICIA__CH04__CHATTER__SECOND_BRIDGE_SIMON__020__M__1": "Deneyeceğim, evet!",
"VO__AMICIA__CH04__CHATTER__SECOND_FIRE_PASSED__020__M__1": "Harika!",
"VO__AMICIA__CH04__CHATTER__SHORE__020__M__1": "Hâlâ orada... Güzel...",
"VO__AMICIA__CH04__CHATTER__SHORE__040__M__1": "Yerinde tespit.",
"VO__AMICIA__CH04__CHATTER__SHOULD_LIGHT_REMAINING_BASIN__020__M__1": "Haklısın, az kalsın unutuyordum...",
"VO__AMICIA__CH04__CHATTER__SIMON_DEAD_SAD__020__M__1": "Çoktan yeterince zarar verdiler.",
"VO__AMICIA__CH04__CHATTER__SIMON_END__010__M__1": "Hadi, tekne hemen şurada.",
"VO__AMICIA__CH04__CHATTER__SIMON_GO_TO_CRANK__020__M__1": "Korkuyor.",
"VO__AMICIA__CH04__CHATTER__SIMON_OUTRO__010__M__1": "Lanet inatçı budala...",
"VO__AMICIA__CH04__CHATTER__SIMON_OUTRO_DEAD__010__M__1": "Riske giremezdim... Aptalca...",
"VO__AMICIA__CH04__CHATTER__SOLUTION__020__M__1": "Ne yapalım? Onlara fare ve ölüm getirdiğimizi mi söyleyelim? Bundan kaçış yok! Hiç olmadı!",
"VO__AMICIA__CH04__CHATTER__SOUVENIR__010__M__1": "Sanırım ipek... Lucas... Bak... gerçek ipek...",
"VO__AMICIA__CH04__CHATTER__SOUVENIR__030__M__1": "Birileri bunu dünyanın öbür ucunda yapmış...",
"VO__AMICIA__CH04__CHATTER__SOUVENIR__038__M__1": "Belki değil... Henüz değil.",
"VO__AMICIA__CH04__CHATTER__SOUVENIR_SEE__010__M__1": "Burada... terk edilmiş bir yük var...",
"VO__AMICIA__CH04__CHATTER__SOUVENIR_TWO__020__M__1": "Hiç gelmemeliydik.",
"VO__AMICIA__CH04__CHATTER__SOUVENIR_TWO__040__M__1": "Ben bir kum tanesi değilim Lucas.",
"VO__AMICIA__CH04__CHATTER__SOUVENIR_TWO__060__M__1": "Belki... Gel, bizi bekleyen bir tekne var. Hadi Hugo'yu buradan çıkaralım.",
"VO__AMICIA__CH04__CHATTER__STAIRS__020__M__1": "Bunu söylemene sevindim.",
"VO__AMICIA__CH04__CHATTER__STAIRS__040__M__1": "Bu konuda yalnız hissetmememe yardımcı oluyor.",
"VO__AMICIA__CH04__CHATTER__TAR_AIM__010__M__1": "Lütfen çalış...",
"VO__AMICIA__CH04__CHATTER__TAR_IGNITE_PREPARE__010__M__1": "Hadi bakalım...",
"VO__AMICIA__CH04__CHATTER__TAR_SHOOT__009__M__1": "İşe yarıyor!",
"VO__AMICIA__CH04__CHATTER__TAR_SHOOT__019__M__1": "Mükemmel!",
"VO__AMICIA__CH04__CHATTER__TAR_SHOOT__030__M__1": "Geliyorum!",
"VO__AMICIA__CH04__CHATTER__THANKS_JOSEPH__010__M__1": "Teşekkürler Joseph!",
"VO__AMICIA__CH04__CHATTER__THANKS_JOSEPH__030__M__1": "Pekâlâ!",
"VO__AMICIA__CH04__CHATTER__THAT_GATE__010__M__1": "Şu kapıya bakalım...",
"VO__AMICIA__CH04__CHATTER__TO_DOOR__010__M__1": "Şu tekneye bakalım!",
"VO__AMICIA__CH04__CHATTER__TO_LOOT__030__M__1": "Ne dedi?",
"VO__AMICIA__CH04__CHATTER__TO_LOOT__050__M__1": "İki zirveli bir sembol! Tıpkı Hugo'nun rüyasındaki gibi!",
"VO__AMICIA__CH04__CHATTER__TO_SOUVENIR__020__M__1": "Şimdi Isırık'ın yayılması için bir kapı olacak.",
"VO__AMICIA__CH04__CHATTER__TO_THE_2ND_BASIN__020__M__1": "Bu yerden kaçıyoruz...",
"VO__AMICIA__CH04__CHATTER__TO_THE_2ND_BASIN__040__M__1": "Evet, ve insanlar zaten ölüyor, o yüzden şansımızı deniyoruz!",
"VO__AMICIA__CH04__CHATTER__TO_THE_3RD_BASIN__020__M__1": "Çok... kendimize güvenmek zorunda kaldık...",
"VO__AMICIA__CH04__CHATTER__UPSTAIRS__030__M__1": "Evet... korkunç olacak—gerçek bir fare karnavalı.",
"VO__AMICIA__CH04__CHATTER__UPSTAIRS__050__M__1": "Evet. Aceleyle yapmışlar. Ve tekneye giden yolumuzu kapatıyor...",
"VO__AMICIA__CH04__CHATTER__VISTA_ARENA__020__M__1": "Gitmeliyiz...",
"VO__AMICIA__CH04__CHATTER__VISTA_TOWER__022__M__1": "Rıhtım mı? Oraya gidiyoruz, değil mi?...",
"VO__AMICIA__CH04__CHATTER__VISTA_TOWER__040__M__1": "Demek onları buraya getiriyorlar...",
"VO__AMICIA__CH04__CHATTER__VISTA_TOWER__060__M__1": "Merak etme. Seni ilk seferinde duydum. Başka... yollar bulurum.",
"VO__AMICIA__CH04__CHATTER__WINDOW_VISTA__010__M__1": "İşte!",
"VO__AMICIA__CH04__CHATTER__WORKBENCH__020__M__1": "Faydalı olabilir...",
"VO__AMICIA__CH04__CHATTER__WORKSHOP_1ST_STEPS__020__M__1": "Burası farklı kokuyor...",
"VO__AMICIA__CH04__CHATTER__WORKSHOP_1ST_STEPS__035__M__1": "Devam etmeliyiz...",
"VO__AMICIA__CH04__CHATTER__WORKSHOP_1ST_STEPS__040__M__1": "Eyvah!",
"VO__AMICIA__CH04__CHATTER__WORKSHOP_1ST_STEPS__060__M__1": "Bizi takip ediyorlar...",
"VO__AMICIA__CH04__CHATTER__YARD_FIRST_CRANK__010__M__1": "Pekâlâ, ne yaptığına bakalım...",
"VO__AMICIA__CH04__CHATTER__YARD_FIRST_CRANK__025__M__1": "O şey burada lazım...",
"VO__AMICIA__CH04__CHATTER__YARD_FIRST_CRANK__030__M__1": "Daha öteye gitmeyecek.",
"VO__AMICIA__CH04__CHATTER__YARD_INTRO__020__M__1": "Evet! Gidelim!",
"VO__AMICIA__CH04__CHATTER__YARD_INTRO__030__M__1": "Buradalar! Aşağısı kaynıyor!",
"VO__AMICIA__CH04__CHATTER__YARD_INTRO__045__M__1": "O hâlde onu teknemize giden bir yol açmak için kullanalım!",
"VO__AMICIA__CH04__CHATTER__YARD_INTRO__060__M__1": "Ne gün ama...",
"VO__AMICIA__CH04__ONOM__EVENT_HIT__010__M__1": "Ha!",
"VO__AMICIA__CH04__ONOM__RUN_FALL__010__M__1": "Ahh!",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__020__M__1": "İki gün oldu!",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__030__M__1": "Nasıl öyle durup hiçbir şey yapmazsınız?!",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__040__M__1": "Bunu hak etmiyor...",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__050__M__1": "Onu oradan çıkarıyorum!",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__080__M__1": "Onu kilit altına mı almak istiyorsunuz?",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__100__M__1": "Hey! O bir çocuk! Bu onun suçu değil! Ve siz ona ne kadar acı çektirirseniz, dışarıda o kadar çok fare olur ve o kadar çok insan ölür!",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__135__M__1": "Ne? Ne demek istiyorsunuz?",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__160__M__1": "Hayır. Hayır... Bir yol olmalı... Lucas başardı...",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__180__M__1": "Durun! Bir ada var! Durmadan bir adadan bahsediyor. Belki Macula onun ardındadır. Bizim...",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__200__M__1": "Peki bir çocuğun hayalinin laboratuvarınızın duvarında ne işi var?!",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__210__M__1": "Evet... Orada ne var?!",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__230__M__1": "\"Düzen\"iniz hiç umurumda değil! Sizi tanımıyorum ve sizin için çalışmıyorum! Bırakın onu göreyim!",
"VO__AMICIA__CH04__RTC__124_CONDEMNED__250__M__1": "Bırakın geçeyim!",
"VO__AMICIA__CH04__RTC__130_ENTER_SHIPYARD_AREA__020__M__1": "Henüz ölmedi...",
"VO__AMICIA__CH04__RTC__130_ENTER_SHIPYARD_AREA__040__M__1": "Anladım. Öldürme yok, fark edilme yok. Hadi şu tekneyi alalım.",
"VO__AMICIA__CH04__RTC__135_MEETING_JOSEPH__060__M__1": "Evet, ve bela geliyor. Hareket etmeliyiz.",
"VO__AMICIA__CH04__RTC__135_MEETING_JOSEPH__120__M__1": "Joseph! Bekle!",
"VO__AMICIA__CH04__RTC__135_MEETING_JOSEPH__140__M__1": "Magister Vaudin adına buradayız! Şehirden ayrılmamız gerek!",
"VO__AMICIA__CH04__RTC__135_MEETING_JOSEPH__220__M__1": "Evet! Hadi!",
"VO__AMICIA__CH04__RTC__140_FIRST_OUTBURST__010__M__1": "Bizi yarı yolda bırakmadığın için teşekkürler!",
"VO__AMICIA__CH04__RTC__140_FIRST_OUTBURST__040__M__1": "Şehirde, gitmeye hazırlanıyorlar. Benim...",
"VO__AMICIA__CH04__RTC__140_FIRST_OUTBURST__060__M__1": "Hugo...",
"VO__AMICIA__CH04__RTC__140_FIRST_OUTBURST__070__M__1": "Ne yaptılar?",
"VO__AMICIA__CH04__RTC__140_FIRST_OUTBURST__080__M__1": "Gidip onları getireceğim! Sen bizi evin yanındaki rıhtımdan al!",
"VO__AMICIA__CH04__RTC__140_FIRST_OUTBURST__095__M__1": "İşte... ev...",
"VO__AMICIA__CH04__RTC__140_FIRST_OUTBURST__170__M__1": "Hayır... Hayır! KAÇIN! HEPİNİZ!",
"VO__AMICIA__CH04__RTC__150_JUST_A_NIGHTMARE__060__M__1": "Bırak ben!",
"VO__AMICIA__CH04__RTC__150_JUST_A_NIGHTMARE__070__M__1": "Hugo! Hugo, buradayım!",
"VO__AMICIA__CH04__RTC__150_JUST_A_NIGHTMARE__075__M__1": "Şşş... Sakinleş, lütfen. Lütfen!",
"VO__AMICIA__CH04__RTC__150_JUST_A_NIGHTMARE__080__M__1": "Neden üzgün olduğunu biliyorum... Şşşş... Hugo, lütfen! Şşşş...",
"VO__AMICIA__CH04__RTC__150_JUST_A_NIGHTMARE__090__M__1": "Hey.",
"VO__AMICIA__CH04__RTC__150_JUST_A_NIGHTMARE__110__M__1": "Biliyorum...",
"VO__AMICIA__CH04__RTC__150_JUST_A_NIGHTMARE__140__M__1": "Evet, Lucas rıhtımda bekliyor olmalı. Gidelim.",
"VO__BEATRICE__CH04__CHATTER__BOAT__030__M__1": "Hepimiz sağ salimiz, Lucas.",
"VO__BEATRICE__CH04__CHATTER__BOAT__070__M__1": "Bir... nöbet daha geçirdi...",
"VO__BEATRICE__CH04__CHATTER__FAULT__020__M__1": "Hayır... Rüyalar rüyadır, tamam mı?... Teknede sana bir şey vereceğim. Seni sakinleştirecek!",
"VO__BEATRICE__CH04__CHATTER__FAULT__060__M__1": "Geçecek! Marsilya'da sana yardım edecekler!",
"VO__BEATRICE__CH04__CHATTER__FAULT__080__M__1": "Hugo... Ben...",
"VO__BEATRICE__CH04__CHATTER__FIRST_STEPS__010__M__1": "Amicia... Onu ben taşımalıyım...",
"VO__BEATRICE__CH04__CHATTER__FIRST_STEPS__040__M__1": "Bu nasıl olabildi?",
"VO__BEATRICE__CH04__CHATTER__FIRST_STEPS__060__M__1": "Ne?",
"VO__BEATRICE__CH04__CHATTER__FIRST_STEPS_BEA__010__M__1": "Bu... görülmemiş bir şey...",
"VO__BEATRICE__CH04__CHATTER__HUGO_AWAKE__051__M__1": "Gidiyoruz, Hugo.",
"VO__BEATRICE__CH04__CHATTER__HUGO_AWAKE__080__M__1": "Sakinleş, lütfen!",
"VO__BEATRICE__CH04__CHATTER__OPEN_SPACE__020__M__1": "Bir yol bulacağız... Bulacağız...",
"VO__BEATRICE__CH04__CHATTER__OPEN_SPACE_CRY__020__M__1": "Bu insanlar...",
"VO__BEATRICE__CH04__CHATTER__VISTA_ARENA__010__M__1": "Şehir... yok oldu... Hepsi...",
"VO__BEATRICE__CH04__RTC__124_CONDEMNED__130__M__1": "Magister, lütfen...",
"VO__BEATRICE__CH04__RTC__124_CONDEMNED__140__M__1": "Amicia, Hugo mahkûm.",
"VO__BEATRICE__CH04__RTC__124_CONDEMNED__240__M__1": "Hugo yorgun, Amicia. Bu hâlinle odasına giremezsin.",
"VO__BEATRICE__CH04__RTC__124_CONDEMNED__260__M__1": "Sakinleşene kadar olmaz! Kendin söyledin. Macula onun duygularıyla besleniyor.",
"VO__BEATRICE__CH04__RTC__124_CONDEMNED__290__M__1": "Lucas, lütfen limana git ve şu Joseph'i bul.",
"VO__BEATRICE__CH04__RTC__124_CONDEMNED__320__M__1": "Dikkatli olun...",
"VO__BEATRICE__CH04__RTC__124_CONDEMNED__330__M__1": "...ikiniz de.",
"VO__BEATRICE__CH04__RTC__150_JUST_A_NIGHTMARE__050__M__1": "Sakinleşmiyor! Ne yapacağımı bilmiyorum!",
"VO__BEATRICE__CH04__RTC__150_JUST_A_NIGHTMARE__130__M__1": "Her şey çökmeden çıkmalıyız.",
"VO__BEATRICE__CH04__RTC__160_CARNAGE__010__M__1": "Sadece biziz. Magister Vaudin...",
"VO__BOATMAN__CH04__CHATTER__BEHIND_LAST_DOOR__010__M__1": "Lanet olsun! Asla başaramazsınız sanmıştım! Gelin!",
"VO__BOATMAN__CH04__CHATTER__BOAT__050__M__1": "Gitmeye hazırız!",
"VO__BOATMAN__CH04__CHATTER__BOAT__080__M__1": "Kımıldayın! Onlar... geri gelmeden... ya da daha beterinden önce!",
"VO__BOATMAN__CH04__CHATTER__THANKS_JOSEPH__020__M__1": "Devam edin, ben sizi korumaya devam ederim!",
"VO__BOATMAN__CH04__RTC__135_MEETING_JOSEPH__020__M__1": "Bir müşteri bekliyorum ve sözleşmelerime her zaman sadık kalırım, dostum.",
"VO__BOATMAN__CH04__RTC__135_MEETING_JOSEPH__070__M__1": "Pekâlâ, bak ne diyeceğim? Gidecek daha iyi yerlerim var.",
"VO__BOATMAN__CH04__RTC__135_MEETING_JOSEPH__090__M__1": "Hadi ama!",
"VO__BOATMAN__CH04__RTC__135_MEETING_JOSEPH__110__M__1": "Bak ne diyeceğim? Defol!",
"VO__BOATMAN__CH04__RTC__135_MEETING_JOSEPH__130__M__1": "Olduğun yerde kal!",
"VO__BOATMAN__CH04__RTC__135_MEETING_JOSEPH__150__M__1": "Sence ne yapıyorum? Burası darmadağın!",
"VO__BOATMAN__CH04__RTC__135_MEETING_JOSEPH__170__M__1": "Pekâlâ, pekâlâ! Bir sonraki iskelede buluşalım!",
"VO__BOATMAN__CH04__RTC__135_MEETING_JOSEPH__210__M__1": "Kımıldayın! Hemen!",
"VO__BOATMAN__CH04__RTC__140_FIRST_OUTBURST__030__M__1": "Şey, üzerine düşeni yaptın... Şimdi grubun geri kalanı nerede?",
"VO__BOATMAN__CH04__RTC__140_FIRST_OUTBURST__050__M__1": "Neler oluyor?",
"VO__BOATMAN__CH04__RTC__160_CARNAGE__020__M__1": "Anlıyorum... O zaman vakit kaybetmeyelim.",
"VO__BOATMAN__CH04__RTC__160_CARNAGE__030__M__1": "Biliyordum... Ruhlarımızın çürümesinin bir bedelini ödeyeceğimizi biliyordum...",
"VO__HUGO__CH04__CHATTER__FAULT__010__M__1": "Hayır... Benim suçum!",
"VO__HUGO__CH04__CHATTER__FAULT__030__M__1": "Hayır! Gerçekten durmasını istiyorum!",
"VO__HUGO__CH04__CHATTER__FAULT__050__M__1": "Durmasını istiyorum, Amicia...",
"VO__HUGO__CH04__CHATTER__FAULT__070__M__1": "Doğru değil! Hep öyle diyorsun ama yalan söylüyorsun! Yalan!",
"VO__HUGO__CH04__CHATTER__FIRST_STEPS__020__M__1": "Neler oluyor? Başım dönüyor...",
"VO__HUGO__CH04__CHATTER__HUGO_AWAKE__010__M__1": "Hayır... Ben...",
"VO__HUGO__CH04__CHATTER__HUGO_AWAKE__030__M__1": "Amicia! Ne oldu?",
"VO__HUGO__CH04__CHATTER__HUGO_AWAKE__050__M__1": "Hayır, hayır, hayır...",
"VO__HUGO__CH04__CHATTER__HUGO_AWAKE__070__M__1": "Tıpkı kâbusumdaki gibi! Benim yüzümden!",
"VO__HUGO__CH04__CHATTER__OPEN_SPACE_HELP__020__M__1": "Kim... o?...",
"VO__HUGO__CH04__RTC__150_JUST_A_NIGHTMARE__100__M__1": "Bir kâbus gördüm...",
"VO__HUGO__CH04__RTC__150_JUST_A_NIGHTMARE__120__M__1": "Ne oldu?",
"VO__LUCAS__CH04__CHATTER__1ST_BASIN_LIGHT__040__M__1": "Ev yapımı! Temel simya!",
"VO__LUCAS__CH04__CHATTER__1ST_BASIN_SHOULD_POUR__030__M__1": "Kaçışımızdan haberi yok gibi.",
"VO__LUCAS__CH04__CHATTER__3RD_BASIN_SHOULD_LIGHT__020__M__1": "Yak onu, Amicia!",
"VO__LUCAS__CH04__CHATTER__A_WAY_OUT__010__M__1": "Panik yapma... Reçinemiz var... Sadece yukarıdaki şu inceltici lazım, sonra katran elde ederiz!",
"VO__LUCAS__CH04__CHATTER__A_WAY_OUT__030__M__1": "Yine de o fıçı epey yüksek...",
"VO__LUCAS__CH04__CHATTER__AFTER_ATTACK__010__M__1": "Bu mümkün değil...",
"VO__LUCAS__CH04__CHATTER__ALCOHOL_DONE__010__M__1": "Güzel!... Sanırım onu yakabilirsin!",
"VO__LUCAS__CH04__CHATTER__ALCOHOL_DONE__030__M__1": "Bakalım katranımız neye yarıyor...",
"VO__LUCAS__CH04__CHATTER__AMPLIFY__010__M__1": "Bizi affet...",
"VO__LUCAS__CH04__CHATTER__AMPLIFY_LUCKY_USES__030__M__1": "Haklı! Önce şu ikinci havuza giden yolu açmalısın!",
"VO__LUCAS__CH04__CHATTER__AMPLIFY_TUTO_MISS__010__M__1": "Şu ateşe katran at!",
"VO__LUCAS__CH04__CHATTER__AMPLIFY_TUTO_MISS__020__M__1": "Hadi, şu havuza katran at!",
"VO__LUCAS__CH04__CHATTER__AMPLIFY_TUTORIAL__020__M__1": "Bir yol olmalı...",
"VO__LUCAS__CH04__CHATTER__AMPLIFY_TUTORIAL__040__M__1": "Bu... şey, evet, işe yarar...",
"VO__LUCAS__CH04__CHATTER__AMPLIFY_TUTORIAL__084__M__1": "Gözlerim...",
"VO__LUCAS__CH04__CHATTER__AMPLIFY_TUTORIAL__122__M__1": "Bu aslında epey zekiceydi...",
"VO__LUCAS__CH04__CHATTER__BACK_CITY__013__M__1": "Artık gitsek, değil mi?",
"VO__LUCAS__CH04__CHATTER__BACK_CITY__055__M__1": "Hadi ama!",
"VO__LUCAS__CH04__CHATTER__BACK_CITY__092__M__1": "Amicia! Onu kör edebilirsin! Katranla!",
"VO__LUCAS__CH04__CHATTER__BACK_CITY__100__M__1": "Şimdi Amicia!",
"VO__LUCAS__CH04__CHATTER__BEFORE_MEETING__010__M__1": "Onunla yüz yüze tanışma vakti mi?",
"VO__LUCAS__CH04__CHATTER__BEFORE_MEETING__030__M__1": "Emirlere uymak mı?",
"VO__LUCAS__CH04__CHATTER__BIG_BOATS__020__M__1": "Kırmızı beyaz yelken... Tam şurada!",
"VO__LUCAS__CH04__CHATTER__BITE__010__M__1": "Bu yüzden şehri kapattılar!",
"VO__LUCAS__CH04__CHATTER__BITE__020__M__1": "Bu... bir savaş stratejisi...",
"VO__LUCAS__CH04__CHATTER__BOAT__010__M__1": "İşte geldiler!",
"VO__LUCAS__CH04__CHATTER__BOAT__020__M__1": "İyi misin?! Senin... olduğunu sandım...",
"VO__LUCAS__CH04__CHATTER__BOAT__040__M__1": "Tekneye bin, çabuk!",
"VO__LUCAS__CH04__CHATTER__BOAT__060__M__1": "Hugo'ya ne oldu?!",
"VO__LUCAS__CH04__CHATTER__BODIES_REACTIONS_1__020__M__1": "Sanırım... önce aşağı mahalleleri temizlemeye başladılar. Ev kasabanın yukarı kısmında. Hâlâ vakit var.",
"VO__LUCAS__CH04__CHATTER__CAREFUL__020__M__1": "Joseph bir çömlek katran kırdı! Meşaleyle tepkimeye girdi!",
"VO__LUCAS__CH04__CHATTER__CAREFUL__040__M__1": "Evet... Ne yapman gerekiyorsa yap. O tekne ne pahasına olursa olsun lazım.",
"VO__LUCAS__CH04__CHATTER__CART_PULL__022__M__1": "Sanırım... çok geç. Buradalar...",
"VO__LUCAS__CH04__CHATTER__CART_STUCK__040__M__1": "Sanırım... bu yerin başına ne geldiğini biliyorum...",
"VO__LUCAS__CH04__CHATTER__CHARIOT_WHAT__010__M__1": "Geldik.",
"VO__LUCAS__CH04__CHATTER__COMPONENTS_THROW__010__M__1": "Dur! Sanırım... burada bazı bileşenlerle deney yaptılar ve... Evet, işe yarayabilir! Onları sana fırlatacağım!",
"VO__LUCAS__CH04__CHATTER__COMPONENTS_THROW__030__M__1": "İşte! Yakalamaya hazır olunca söyle!",
"VO__LUCAS__CH04__CHATTER__COMPONENTS_THROW__050__M__1": "Artık reçinen ve alkolün var. Karıştır onları!",
"VO__LUCAS__CH04__CHATTER__DID_IT_DOOR__020__M__1": "Bu insanlar...",
"VO__LUCAS__CH04__CHATTER__DID_IT_DOOR__040__M__1": "Evet...",
"VO__LUCAS__CH04__CHATTER__DOWN_PATROL__060__M__1": "Kapatılan mahalleyi hatırla...",
"VO__LUCAS__CH04__CHATTER__DOWN_PATROL__080__M__1": "Bilmiyorum...",
"VO__LUCAS__CH04__CHATTER__ENTRY_DEPOT__005__M__1": "Vay... Ne dağınıklık...",
"VO__LUCAS__CH04__CHATTER__ENTRY_DEPOT__009__M__1": "Katran... başını döndürüyor...",
"VO__LUCAS__CH04__CHATTER__ENTRY_DEPOT__020__M__1": "Hayır... ama buradaydılar. Şuna bak.",
"VO__LUCAS__CH04__CHATTER__ENTRY_DEPOT__040__M__1": "Bir katran atölyesi... tekne gövdelerini sızdırmaz yapmak için kullanıyor olmalılar.",
"VO__LUCAS__CH04__CHATTER__FIRE_AFAR__010__M__1": "Limandan çıktık—burada neden asker var?",
"VO__LUCAS__CH04__CHATTER__FIRS_STEPS_JETTY__010__M__1": "Çok yakındı...",
"VO__LUCAS__CH04__CHATTER__FLAMES__020__M__1": "Askerler...",
"VO__LUCAS__CH04__CHATTER__FLOWER__030__M__1": "Bir centiyane, sanırım... Eminim bayılacak.",
"VO__LUCAS__CH04__CHATTER__FLOWER__050__M__1": "Senden gelen her şeyi sever...",
"VO__LUCAS__CH04__CHATTER__FOOTBRIDGE_MOVE__010__M__1": "Vay!",
"VO__LUCAS__CH04__CHATTER__FOOTBRIDGE_MOVE__020__M__1": "Havuzlara geri dön!",
"VO__LUCAS__CH04__CHATTER__FOOTBRIDGE_MOVE__040__M__1": "İnceltici... Anladım... Alkol, elbette!",
"VO__LUCAS__CH04__CHATTER__FOOTBRIDGE_SET__010__M__1": "Güzel! Ben söyleyene kadar tut...",
"VO__LUCAS__CH04__CHATTER__FOOTBRIDGE_SET__030__M__1": "Hazırım!",
"VO__LUCAS__CH04__CHATTER__FRONT_HANGAR__020__M__1": "Soldaki o bina daha güvenli görünüyor...",
"VO__LUCAS__CH04__CHATTER__GATE__090__M__1": "Umarım o kapıyı geçmek için yan bir yol vardır.",
"VO__LUCAS__CH04__CHATTER__GATE__110__M__1": "Çok yakında öğreneceğiz...",
"VO__LUCAS__CH04__CHATTER__GATE_END__010__M__1": "Joseph'in teknesi nerede?!",
"VO__LUCAS__CH04__CHATTER__GATE_END__030__M__1": "Çoktan yanaştıysa...",
"VO__LUCAS__CH04__CHATTER__GEAR_SPOTTED__010__M__1": "Bakalım... Bu ipler platformu hareket ettiriyor. Operatörler parmaklığın arkasındaki şu merdivenle üzerine çıkmış.",
"VO__LUCAS__CH04__CHATTER__IDLE_FIRE_ZONE_3__010__M__1": "Bu şehir kaosa sürüklenecek. İnsanlar o kadar kolay teslim olmayacak. Karşılık verecekler.",
"VO__LUCAS__CH04__CHATTER__IDLE_FIRE_ZONE_4__010__M__1": "Bu pis koku... Katran üstünü örtmüş ama...",
"VO__LUCAS__CH04__CHATTER__IDLE_FIRE_ZONE_6__030__M__1": "Paralı askerler yalnızca paraya inanır.",
"VO__LUCAS__CH04__CHATTER__IGNIFER_OK__010__M__1": "Ah! Pekâlâ, bu da işe yarar! Şimdi hadi! Şuradaki ikinci birikintiyi tutuştur! Katran o!",
"VO__LUCAS__CH04__CHATTER__INTERACT_CRANK__010__M__1": "Evet! Sonuna kadar çevir!",
"VO__LUCAS__CH04__CHATTER__INTERACT_LADDER__020__M__1": "Geliyorum!",
"VO__LUCAS__CH04__CHATTER__JAR_DONE__020__M__1": "Mükemmel! Şimdi bu iki büyük havuzun arasına bir çömlek katran at...",
"VO__LUCAS__CH04__CHATTER__JAR_FAIL__010__M__1": "Bu işe yaramaz! İşte! Bir tane daha üret! Başaramaz da bir tane daha gerekirse bana sor! Ama... lütfen odaklan!",
"VO__LUCAS__CH04__CHATTER__JOSEPH_3RD_KILL__010__M__1": "Bunu nasıl yapıyor?",
"VO__LUCAS__CH04__CHATTER__JOSEPH_4TH_KILL__020__M__1": "Bu inanılmaz...",
"VO__LUCAS__CH04__CHATTER__JOSEPH_5TH_KILL__010__M__1": "Bir tane daha indi! Hiç ıskalamıyor...",
"VO__LUCAS__CH04__CHATTER__JOSEPH_NO_HELP__010__M__1": "Bir şey yap Amicia! Joseph ateş edemiyor!",
"VO__LUCAS__CH04__CHATTER__LOCK_SHOT__010__M__1": "İyi gördün!",
"VO__LUCAS__CH04__CHATTER__LOCK_SHOT__030__M__1": "Biliyorum... ama uzun sürmemeli.",
"VO__LUCAS__CH04__CHATTER__LUCAS_ARRIVED__010__M__1": "Başardım!",
"VO__LUCAS__CH04__CHATTER__LUCAS_SHOULD_JOIN__020__M__1": "Pekâlâ!",
"VO__LUCAS__CH04__CHATTER__LUCAS_SHOULD_JOIN__030__M__1": "Amicia! Sıkıştım!",
"VO__LUCAS__CH04__CHATTER__LUCAS_WONT_MOVE_FOOTBRIGE__010__M__1": "Amicia, bir sonrakine geçmeden önce bu havuzu bitirmeliyiz.",
"VO__LUCAS__CH04__CHATTER__MARKET_STEALTH__020__M__1": "Umarım Marsilya farklıdır...",
"VO__LUCAS__CH04__CHATTER__MARKET_VISTA__010__M__1": "Joseph'in teknesi...",
"VO__LUCAS__CH04__CHATTER__MID_ZONE__005__M__1": "Ortadaki şu ateşe bak...",
"VO__LUCAS__CH04__CHATTER__MID_ZONE__020__M__1": "Katran kokusu alıyorum!... Demek onunla bunu yapıyorlarmış!",
"VO__LUCAS__CH04__CHATTER__MOVE_2ND_GATE_EARLY__010__M__1": "Amicia! Dur! İkinci havuz henüz yanmadı!",
"VO__LUCAS__CH04__CHATTER__NEAR_LAST_DOOR__020__M__1": "Tanrım, geldik... Lütfen orada ol, Joseph. Lütfen, lütfen!",
"VO__LUCAS__CH04__CHATTER__NEAR_SQUEEZE__020__M__1": "Evet... Öf...",
"VO__LUCAS__CH04__CHATTER__NEXT_2ND_BASIN__030__M__1": "Amicia, incelticiyi yönetmek için şu köprüye çıkmalısın. Onu hareket ettirmek için kranı ben hâllederim!",
"VO__LUCAS__CH04__CHATTER__OIL_TUTO__022__M__1": "Katran gibi kokuyor! Öyleyse çok yanıcıdır! Ateşe vermeyi dene!",
"VO__LUCAS__CH04__CHATTER__OIL_TUTO__040__M__1": "Ben... bunu beklemiyordum...",
"VO__LUCAS__CH04__CHATTER__OIL_TUTO__050__M__1": "Onlar da beklemiyordu...",
"VO__LUCAS__CH04__CHATTER__OUTSIDE3_INTRO__010__M__1": "İyi... misin?",
"VO__LUCAS__CH04__CHATTER__OUTSIDE3_INTRO__030__M__1": "Ben... Sana söylemek istedim, ama—",
"VO__LUCAS__CH04__CHATTER__OUTSIDE3_INTRO__050__M__1": "Magister Vaudin'in sana böyle söyleyeceğini bilmiyordum!",
"VO__LUCAS__CH04__CHATTER__OUTSIDE3_INTRO__070__M__1": "Peki...",
"VO__LUCAS__CH04__CHATTER__OVER_GATE__020__M__1": "Burada ne oldu?!",
"VO__LUCAS__CH04__CHATTER__PASSAGE__010__M__1": "Ne yapıyorlar?",
"VO__LUCAS__CH04__CHATTER__PLANNING__010__M__1": "Güzel. Hazne kısmını ben mi hâlledeyim? Ne dersin?",
"VO__LUCAS__CH04__CHATTER__PONTOON_CHEST__005__M__1": "Fareler iskelenin geri kalanını yok etmiş...",
"VO__LUCAS__CH04__CHATTER__POST_DEPOT_DEBRIEF__005__M__1": "Teknemiz tam ileride olmalı, değil mi?",
"VO__LUCAS__CH04__CHATTER__POST_DEPOT_DEBRIEF__020__M__1": "Dinle Amicia... Hugo konusunda... Magister Vaudin'le annenin arasında kaldım ve... Hiçbir mazeretim yok. Yanıldım.",
"VO__LUCAS__CH04__CHATTER__POST_DEPOT_DEBRIEF__040__M__1": "Doğru olanı yapacağız.",
"VO__LUCAS__CH04__CHATTER__POURING_ALCOHOL__010__M__1": "Evet! Hadi şu katranı yapalım!",
"VO__LUCAS__CH04__CHATTER__POURING_ALCOHOL__012__M__1": "Döküyorum!",
"VO__LUCAS__CH04__CHATTER__POURING_ALCOHOL__030__M__1": "Hayır! Doğaçlama yapıyorum!",
"VO__LUCAS__CH04__CHATTER__PUSHABLE_BRAZIER__010__M__1": "Şu mangal... itilebiliyor...",
"VO__LUCAS__CH04__CHATTER__PUZZLE_END__010__M__1": "Katran... işte bunu yaptı, bu şey mucize yaratıyor.",
"VO__LUCAS__CH04__CHATTER__PUZZLE_END__030__M__1": "Ona gerek yok...",
"VO__LUCAS__CH04__CHATTER__PYRE__010__M__1": "O ateş... yanan odun değil...",
"VO__LUCAS__CH04__CHATTER__PYRE__015__M__1": "Cesetler...",
"VO__LUCAS__CH04__CHATTER__QUAI__065__M__1": "İşte geldiler...",
"VO__LUCAS__CH04__CHATTER__RAT_BURST__020__M__1": "Eh, bu bir adım!",
"VO__LUCAS__CH04__CHATTER__RATS_THINKING__010__M__1": "Amicia, Düzen'in Marsilya'da özel binaları olacak... ekipman ve insanlar!",
"VO__LUCAS__CH04__CHATTER__RATS_THINKING__030__M__1": "Ha...",
"VO__LUCAS__CH04__CHATTER__REGION__010__M__1": "Joseph'e ulaşır ulaşmaz çabucak eve dönmeliyiz...",
"VO__LUCAS__CH04__CHATTER__REGION__020__M__1": "Engizisyon'dan daha beterini yapabileceklerini düşünmemiştim.",
"VO__LUCAS__CH04__CHATTER__SHORE__030__M__1": "Umarım kaptanımız da öyledir.",
"VO__LUCAS__CH04__CHATTER__SIMON_DEAD_SAD__010__M__1": "Ona gerçekten bir şans vermedin...",
"VO__LUCAS__CH04__CHATTER__SIMON_END__020__M__1": "Evet...",
"VO__LUCAS__CH04__CHATTER__SIMON_GO_TO_CRANK__010__M__1": "Makul... görünüyor.",
"VO__LUCAS__CH04__CHATTER__SIMON_GO_TO_CRANK__040__M__1": "O zaman bizim için iyi.",
"VO__LUCAS__CH04__CHATTER__SOLUTION__010__M__1": "Kont burada olsaydı, belki... Makul davranırdı. Bir görüşme isteyebilir ve...",
"VO__LUCAS__CH04__CHATTER__SOLUTION__030__M__1": "Zaten çok geç. Burası merkez üssü. Artık sadece yayılabilir.",
"VO__LUCAS__CH04__CHATTER__SOUVENIR__020__M__1": "Muhtemelen Çin'den gelmiş... Bu kadarını hiç görmedim... burada bir servet var...",
"VO__LUCAS__CH04__CHATTER__SOUVENIR__035__M__1": "Sence Çin'de de aynı mı? Sence onlarda da... fareler var mı?",
"VO__LUCAS__CH04__CHATTER__SOUVENIR__040__M__1": "Buna son vermeliyiz...",
"VO__LUCAS__CH04__CHATTER__SOUVENIR_TWO__010__M__1": "O kadar çok... insan şu an... ölüyor olmalı... Ama... her şey o kadar sessiz ki...",
"VO__LUCAS__CH04__CHATTER__SOUVENIR_TWO__030__M__1": "Bunun üzerinde denetimin olduğunu sanıp duruyorsun... Ama biz Macula'nın yolundaki birer kum tanesiyiz sadece.",
"VO__LUCAS__CH04__CHATTER__SOUVENIR_TWO__050__M__1": "Sadece diyorum ki... kendini suçlu hissetmeyi bırakmalısın.",
"VO__LUCAS__CH04__CHATTER__SOUVENIR_TWO__070__M__1": "Pekâlâ.",
"VO__LUCAS__CH04__CHATTER__SOUVENIR_UP__020__M__1": "Bu iç karartıcı.",
"VO__LUCAS__CH04__CHATTER__STAIRS__010__M__1": "Biliyorum... Ada, Macula'nın uyanması, Düzen... Çok fazla.",
"VO__LUCAS__CH04__CHATTER__STAIRS__030__M__1": "Şey, pek faydası yok.",
"VO__LUCAS__CH04__CHATTER__STAIRS__050__M__1": "Değilsin. Ben buradayım.",
"VO__LUCAS__CH04__CHATTER__TAR_AIM_OK__010__M__1": "İyi görünüyor! Yak onu!",
"VO__LUCAS__CH04__CHATTER__TAR_SHOOT__011__M__1": "Evet!",
"VO__LUCAS__CH04__CHATTER__TAR_SHOOT__020__M__1": "Evet! Buradaki o son birikinti çoktan katranla dolu!",
"VO__LUCAS__CH04__CHATTER__TO_LOOT__020__M__1": "Magister Vaudin'e adayı sormamı istedin. Kulübesindeki fresk.",
"VO__LUCAS__CH04__CHATTER__TO_LOOT__040__M__1": "\"Sadece\" bir sembol dedi.",
"VO__LUCAS__CH04__CHATTER__TO_SOUVENIR__010__M__1": "Bu şehrin eskiden Akdeniz'e açılan ticari bir kapı olduğunu duydum...",
"VO__LUCAS__CH04__CHATTER__TREMORS__030__M__1": "Daha ileri gitme, Amicia!",
"VO__LUCAS__CH04__CHATTER__UPSTAIRS__020__M__1": "Bu kapatma hepsini öldürtecek.",
"VO__LUCAS__CH04__CHATTER__UPSTAIRS__040__M__1": "Şu duvara bak...",
"VO__LUCAS__CH04__CHATTER__UPSTAIRS__060__M__1": "Yaklaşalım...",
"VO__LUCAS__CH04__CHATTER__VISTA_TOWER__010__M__1": "Bak— arkadaki o gözetleme kulesi limana açılıyor!",
"VO__LUCAS__CH04__CHATTER__VISTA_TOWER__025__M__1": "Arabalarındaki o kafesler... Sanırım... arenadan cesetler!",
"VO__LUCAS__CH04__CHATTER__VISTA_TOWER__050__M__1": "Amicia... Oraya vardığımızda... sapanını çekmeyeceksin, tamam mı? Bir başka... ahır... durumuna ihtiyacımız yok. Yani... artık asker öldürmek yok.",
"VO__LUCAS__CH04__CHATTER__WORKBENCH__010__M__1": "Bir tezgâh!",
"VO__LUCAS__CH04__CHATTER__WORKSHOP_1ST_STEPS__010__M__1": "Bu mekanizmalar hâlâ sağlam!",
"VO__LUCAS__CH04__CHATTER__WORKSHOP_1ST_STEPS__030__M__1": "Reçine. Bu bir karıştırma havuzu.",
"VO__LUCAS__CH04__CHATTER__WORKSHOP_1ST_STEPS__031__M__1": "Yukarıdaki o fıçı inceltici olmalı!",
"VO__LUCAS__CH04__CHATTER__WORKSHOP_1ST_STEPS__050__M__1": "Geride dur!",
"VO__LUCAS__CH04__CHATTER__YARD_FIRST_CRANK__020__M__1": "Köprüyü o kumanda ediyor!",
"VO__LUCAS__CH04__CHATTER__YARD_INTRO__010__M__1": "Bak, şurada! Joseph'in gemisi! Epey yakınız!",
"VO__LUCAS__CH04__CHATTER__YARD_INTRO__040__M__1": "Dur, bak... Şurada reçine var, şurada da bir fıçı inceltici... Burada daha çok katran yapıyorlarmış...",
"VO__LUCAS__CH04__CHATTER__YARD_INTRO__050__M__1": "Evet... Yine katran yapmaya!",
"VO__LUCAS__CH04__HELPER__1ST_LIGHT_2__010__M__1": "Amicia! Katrana bir Ignifer at!",
"VO__LUCAS__CH04__HELPER__3RD_LIGHT_2__010__M__1": "Amicia! Havuzu bir Ignifer'le yakman gerekecek!",
"VO__LUCAS__CH04__HELPER__AMPLIFY_1__010__M__1": "Geçemiyorum, Amicia!",
"VO__LUCAS__CH04__HELPER__FRONT_HANGAR_EXT_FISH_1__010__M__1": "O kapıya ulaşamayız... Şu fareleri yoldan çekene kadar...",
"VO__LUCAS__CH04__HELPER__FRONT_HANGAR_EXT_FISH_2__010__M__1": "Amicia! Şu asılı balık! Onu yem olarak kullanabiliriz!",
"VO__LUCAS__CH04__HELPER__JAR_DONE_HANGAR_CATCH_1__010__M__1": "Yakalamaya hazır olunca söyle!",
"VO__LUCAS__CH04__HELPER__JAR_DONE_HANGAR_CATCH_2__010__M__1": "Amicia! Malzemeleri ne zaman atmamı istediğini söyle!",
"VO__LUCAS__CH04__HELPER__LIGHT_BASIN_2__010__M__1": "Amicia! İkinci havuzu bir Ignifer'le yakabilir misin?!",
"VO__LUCAS__CH04__HELPER__LOCK_SHOT_HANGAR_1__010__M__1": "Belki o krank fıçıyı hareket ettiriyor... Ama oraya nasıl gidilir bilmiyorum...",
"VO__LUCAS__CH04__HELPER__LOCK_SHOT_HANGAR_2__010__M__1": "Bak! O kapıyı bir zincir kapatıyor! Onu kırabilir misin?!",
"VO__LUCAS__CH04__HELPER__LUCAS_ORDER_1__010__M__1": "Amicia! Onu hareket ettirmemi ister misin?",
"VO__LUCAS__CH04__HELPER__LUCAS_ORDER_2__010__M__1": "Köprüyü ne zaman hareket ettirmemi istediğini söyle!",
"VO__LUCAS__CH04__HELPER__LUCAS_STUCK_1__010__M__1": "Sana gelemiyorum Amicia! Tekne yolumu kesiyor!",
"VO__LUCAS__CH04__HELPER__LUCAS_STUCK_2__010__M__1": "Amicia! Geçmem için kranı kullanman gerek!",
"VO__LUCAS__CH04__HELPER__OIL_TUTO_DOCK_1__010__M__1": "Şu katranı tutuşturursan karşıya geçebiliriz!",
"VO__LUCAS__CH04__HELPER__OIL_TUTO_DOCK_2__010__M__1": "Şu katrana biraz Ignifer atmayı dene!",
"VO__LUCAS__CH04__HELPER__OPEN_TRAPDOOR_DOCK_1__010__M__1": "Aşağı inecek bir yol bulmalıyız...",
"VO__LUCAS__CH04__HELPER__OPEN_TRAPDOOR_DOCK_2__010__M__1": "Amicia! Bu kapakta bana yardım et!",
"VO__LUCAS__CH04__HELPER__SECOND_BRIDGE_SIMON_2__010__M__1": "Amicia! Sanırım o zinciri kırarsan geçebilecek!",
"VO__LUCAS__CH04__HELPER__SLING_BRIDGE_1__010__M__1": "O askere yolu açmamız gerek.",
"VO__LUCAS__CH04__HELPER__SLING_BRIDGE_2__010__M__1": "Köprüdeki o zinciri görüyor musun? Buradan vurabilir misin?",
"VO__LUCAS__CH04__HELPER__TAR_POT_SHOOT_HANGAR_1__010__M__1": "Havuzların arasına bir çömlek katran at!",
"VO__LUCAS__CH04__HELPER__TAR_POT_SHOOT_HANGAR_2__010__M__1": "Amicia! Yere bir çömlek katran atman gerek!",
"VO__LUCAS__CH04__HELPER__TAR_SHOOT_HANGAR_1__010__M__1": "Katranı yak, Amicia!",
"VO__LUCAS__CH04__HELPER__TAR_SHOOT_HANGAR_2__010__M__1": "Katrana bir Ignifer at! Onu tutuşturur!",
"VO__LUCAS__CH04__RTC__124_CONDEMNED__010__M__1": "Yapma! Zor olduğunu biliyorum, ama yapılması gerek.",
"VO__LUCAS__CH04__RTC__124_CONDEMNED__060__M__1": "Amicia... Yapma...",
"VO__LUCAS__CH04__RTC__124_CONDEMNED__300__M__1": "Peki Magistra.",
"VO__LUCAS__CH04__RTC__124_CONDEMNED__310__M__1": "Amicia... Gelmelisin.",
"VO__LUCAS__CH04__RTC__130_ENTER_SHIPYARD_AREA__010__M__1": "Üzgünüm Amicia, Hugo için...",
"VO__LUCAS__CH04__RTC__130_ENTER_SHIPYARD_AREA__030__M__1": "Pekâlâ... Unutma: artık asker öldürmek yok. Artık bizi öldürmek yok.",
"VO__LUCAS__CH04__RTC__135_MEETING_JOSEPH__050__M__1": "Adamımız o.",
"VO__LUCAS__CH04__RTC__135_MEETING_JOSEPH__160__M__1": "Lütfen! Burada sıkıştık! Yanımızda bir çocuk var!",
"VO__LUCAS__CH04__RTC__140_FIRST_OUTBURST__020__M__1": "Ve... yardım eli için...",
"VO__LUCAS__CH04__RTC__140_FIRST_OUTBURST__090__M__1": "Dikkatli ol!",
"VO__PEOPLE_F1__CH04__CHATTER__BARKS_PANICKED__010__M__1": "Defolun buradan!",
"VO__PEOPLE_F2__CH04__CHATTER__AFTERMATH_TWO__010__M__1": "Hadi... Lütfen...",
"VO__PEOPLE_F2__CH04__CHATTER__RUN_BACK__030__M__1": "Dikkat et!",
"VO__PEOPLE_F2__CH04__RTC__140_FIRST_OUTBURST__110__M__1": "Sence neydi o?",
"VO__PEOPLE_F2__CH04__RTC__140_FIRST_OUTBURST__160__M__1": "Yalan yeter!",
"VO__PEOPLE_F3__CH04__CHATTER__BARKS_PETRIFIED__030__M__1": "Aman Tanrım...",
"VO__PEOPLE_F3__CH04__RTC__140_FIRST_OUTBURST__130__M__1": "Kötü bir alamet! Diyorum size!",
"VO__PEOPLE_F4__CH04__CHATTER__RUN_ALLEY___010__M__1": "Kalk! Gitmeliyiz!",
"VO__PEOPLE_F5__CH04__CHATTER__BARKS_CONFUSED__060__M__1": "Bu gürültü de ne?",
"VO__PEOPLE_M1__CH04__CHATTER__DOWN_PATROL__020__M__1": "Neler oluyor?!",
"VO__PEOPLE_M1__CH04__CHATTER__OPEN_SPACE_CRY__010__M__1": "Hayır... Hayıır!",
"VO__PEOPLE_M1__CH04__CHATTER__OPEN_SPACE_HELP__010__M__1": "Eyvah, eyvah, lütfen...",
"VO__PEOPLE_M2__CH04__CHATTER__BARKS_PANICKED__020__M__1": "Kımılda!",
"VO__PEOPLE_M2__CH04__RTC__140_FIRST_OUTBURST__120__M__1": "Bilmiyorum ama beni uyandırdı.",
"VO__PEOPLE_M2__CH04__RTC__140_FIRST_OUTBURST__150__M__1": "Neler oluyor? Bize gerçeği söyleyin!",
"VO__PEOPLE_M6__CH04__CHATTER__BARKS_PETRIFIED__040__M__1": "Tanrı merhamet etsin!",
"VO__SOLDIER_N1__CH04__CHATTER__CART_PULL__030__M__1": "Öldük... Öldük!",
"VO__SOLDIER_N1__CH04__CHATTER__CART_PUSH__020__M__1": "Daha sabit gidemiyorum!",
"VO__SOLDIER_N1__CH04__CHATTER__FLAMES__011__M__1": "İskeleden geldi! Benimle gel!",
"VO__SOLDIER_N1__CH04__CHATTER__FLAMES__040__M__1": "Hey!",
"VO__SOLDIER_N1__CH04__CHATTER__GATE__040__M__1": "Karşıya geçene kadar çömleklere göz kulak ol!",
"VO__SOLDIER_N1__CH04__CHATTER__GATE_TALK__020__M__1": "Hiçbir şeye inanmıyorum. Sadece şehirden ceset gelip durduğunu, bizim de buna kendimizden çok fazlasını eklediğimizi biliyorum.",
"VO__SOLDIER_N1__CH04__CHATTER__GATE_TALK__040__M__1": "Dua et... Elimizde kalan tek şey bu.",
"VO__SOLDIER_N1__CH04__CHATTER__GUARDS_GATE__010__M__1": "Hey! Bunca ceset... Evlerini koruyacak kimse yok, değil mi?",
"VO__SOLDIER_N1__CH04__CHATTER__GUARDS_GATE__030__M__1": "Bir bakabiliriz. Bu gece. Büyük bir torbayla.",
"VO__SOLDIER_N1__CH04__CHATTER__GUARDS_GATE__050__M__1": "Tabii!",
"VO__SOLDIER_N1__CH04__CHATTER__LINES_PATROL__020__M__1": "Sokaklar kasaba muhafızı dışında herkese yasak!",
"VO__SOLDIER_N1__CH04__CHATTER__RIGHT_SPEAR__020__M__1": "Evet... ve hâlâ yakacak çok cesedimiz var.",
"VO__SOLDIER_N1__CH04__CHATTER__RIGHT_SPEAR__040__M__1": "Lanet... Haklısın... Umarım çocuklarımız o çömleklerle çabuk gelir... yoksa...",
"VO__SOLDIER_N1__CH04__CHATTER__SOLDIERS_PYRE__010__M__1": "Katranımız bitti ve cesetler gelmeye devam ediyor...",
"VO__SOLDIER_N1__CH04__CHATTER__SOLDIERS_PYRE__030__M__1": "Bu \"temizlik\" değil... Bu insanların çoğu hasta bile değildi! Canavar şehri boşaltıyor! Bu bir katliam!",
"VO__SOLDIER_N2__CH04__CHATTER__1ST_BASIN_LIGHT__020__M__1": "Hey! Oraya attığın o alevli şey de neydi?!",
"VO__SOLDIER_N2__CH04__CHATTER__1ST_BASIN_LIGHT__050__M__1": "Simya mı?!... Buralarda bunlardan pek hoşlanmayız!",
"VO__SOLDIER_N2__CH04__CHATTER__1ST_BASIN_LIGHT__070__M__1": "Hmmm...",
"VO__SOLDIER_N2__CH04__CHATTER__1ST_BASIN_POURRING__020__M__1": "Ateşten hoşlanmıyorlar, değil mi?",
"VO__SOLDIER_N2__CH04__CHATTER__1ST_BASIN_SHOULD_LIGHT__010__M__1": "Güzel! Peki onu nasıl yakacaksın?",
"VO__SOLDIER_N2__CH04__CHATTER__1ST_BASIN_SHOULD_LIGHT__030__M__1": "Etrafta hiç meşale görmüyorum...",
"VO__SOLDIER_N2__CH04__CHATTER__1ST_BASIN_SHOULD_POUR__010__M__1": "İşte incelticin!",
"VO__SOLDIER_N2__CH04__CHATTER__2ND_BASIN_FAR__010__M__1": "Hey! Havuzun üstünden geçiyorsun! Yavaşla!",
"VO__SOLDIER_N2__CH04__CHATTER__2ND_BASIN_FAR__020__M__1": "Çok ileri gittin! Biraz geri gel!",
"VO__SOLDIER_N2__CH04__CHATTER__2ND_BASIN_POURRING_FAIL__020__M__1": "Çok uzaktasın! Alkol içine düşmüyor!",
"VO__SOLDIER_N2__CH04__CHATTER__2ND_BASIN_SHOULD_LIGHT__010__M__1": "Güzel! Bunu da yakma vakti!",
"VO__SOLDIER_N2__CH04__CHATTER__3RD_BASIN_SHOULD_POUR__010__M__1": "Neredeyse vardık! Sadece şu son havuzu doldur!",
"VO__SOLDIER_N2__CH04__CHATTER__AMPLIFY_LUCKY_USES__020__M__1": "Dur! Şimdi daha ileri gitme! O etki uzun sürmez!",
"VO__SOLDIER_N2__CH04__CHATTER__AMPLIFY_TUTORIAL__030__M__1": "Evet! Doğrudan ateşin içine katran at! Alevleri bir süre güçlendirir!",
"VO__SOLDIER_N2__CH04__CHATTER__AMPLIFY_TUTORIAL__090__M__1": "Şimdi git! O katran uzun süre yanmaz!",
"VO__SOLDIER_N2__CH04__CHATTER__AMPLIFY_TUTORIAL__126__M__1": "\"Simya\"yı bilmeyebiliriz, ama katranla hayli haşır neşir olduk, tamam mı?",
"VO__SOLDIER_N2__CH04__CHATTER__AMPLIFY_TUTORIAL__140__M__1": "O... gizli!",
"VO__SOLDIER_N2__CH04__CHATTER__BACK_CITY__010__M__1": "Şey, iyi iş çıkardın!",
"VO__SOLDIER_N2__CH04__CHATTER__BACK_CITY__012__M__1": "Bu gece kanunu çiğnemeye karar verdiğin için şanslıyım!",
"VO__SOLDIER_N2__CH04__CHATTER__BACK_CITY__030__M__1": "Tabii, sizi eve geri götürürüm.",
"VO__SOLDIER_N2__CH04__CHATTER__BACK_CITY__050__M__1": "İmkânsız. Evinize dönüyorsunuz!",
"VO__SOLDIER_N2__CH04__CHATTER__BACK_CITY__070__M__1": "Kanun kanundur!",
"VO__SOLDIER_N2__CH04__CHATTER__BACK_CITY__073__M__1": "Provence ordusunun bir askerini mi tehdit ediyorsun?!",
"VO__SOLDIER_N2__CH04__CHATTER__BACK_CITY__090__M__1": "Dur... Dur! Kenar mahallede... adamlarımız bir kız ve bir oğlanın saldırısına uğradı... Sen... Sen kaçtın!",
"VO__SOLDIER_N2__CH04__CHATTER__BACK_CITY__094__M__1": "Adaleti kendim sağlayacağım! Dualarını et!",
"VO__SOLDIER_N2__CH04__CHATTER__CART_LOW__010__M__1": "Pekâlâ! Kapıyı açın!",
"VO__SOLDIER_N2__CH04__CHATTER__GATE__060__M__1": "Mevki alın!",
"VO__SOLDIER_N2__CH04__CHATTER__GATE__070__M__1": "İyi şanslar çocuklar!",
"VO__SOLDIER_N2__CH04__CHATTER__GATE_TALK__010__M__1": "Sence bu sefer başarırlar mı?",
"VO__SOLDIER_N2__CH04__CHATTER__GATE_TALK__030__M__1": "Fırsatım varken annemi görmeye gitmeliydim...",
"VO__SOLDIER_N2__CH04__CHATTER__GATE_TALK__050__M__1": "Bu pek bir şey değil...",
"VO__SOLDIER_N2__CH04__CHATTER__GUARDS_GATE__020__M__1": "Hmmm, evet... Neye varmak istediğini anlıyorum...",
"VO__SOLDIER_N2__CH04__CHATTER__GUARDS_GATE__040__M__1": "Riskli görünüyor ama... Bunu sonra konuşalım...",
"VO__SOLDIER_N2__CH04__CHATTER__INTRO_SIMON_BRIGDGE_DOWN__010__M__1": "Hey! Kimsiniz?! O köprüyü siz mi indirdiniz?!",
"VO__SOLDIER_N2__CH04__CHATTER__INTRO_SIMON_BRIGDGE_DOWN__050__M__1": "Geçmek mi?! Nasıl?! Saatlerdir şu farelerle burada sıkışıp kaldım! Buradan çıkmam lazım!",
"VO__SOLDIER_N2__CH04__CHATTER__INTRO_SIMON_BRIGDGE_DOWN__100__M__1": "Evet! Bir dakika bekleyin!",
"VO__SOLDIER_N2__CH04__CHATTER__INTRO_SIMON_BRIGDGE_UP__010__M__1": "Hey! Kimsiniz?!",
"VO__SOLDIER_N2__CH04__CHATTER__INTRO_SIMON_BRIGDGE_UP__050__M__1": "Geçemezsiniz işte! Asırlardır şu farelerle burada sıkıştım! Buradan çıkmam lazım!",
"VO__SOLDIER_N2__CH04__CHATTER__INTRO_SIMON_BRIGDGE_UP__060__M__1": "Evet, ama yardımın lazım! Köprüyü kaldırdılar!",
"VO__SOLDIER_N2__CH04__CHATTER__LINES_PATROL__010__M__1": "Evlerinizde kalın! Arles Kontu Victor'un emriyle!",
"VO__SOLDIER_N2__CH04__CHATTER__LUCAS_CROSSING__010__M__1": "Neredeyse vardın!",
"VO__SOLDIER_N2__CH04__CHATTER__LUCAS_STUCK__010__M__1": "Hadi! Şu tekneyi kaldır da arkadaşın geçebilsin!",
"VO__SOLDIER_N2__CH04__CHATTER__NEXT_2ND_BASIN__010__M__1": "Güzel, şimdi önde iki havuz daha var!",
"VO__SOLDIER_N2__CH04__CHATTER__NEXT_3RD_BASIN__020__M__1": "Bunu kaldırmak sana kalmış!",
"VO__SOLDIER_N2__CH04__CHATTER__RIGHT_SPEAR__010__M__1": "O ateş katran olmadan fazla dayanmaz...",
"VO__SOLDIER_N2__CH04__CHATTER__RIGHT_SPEAR__030__M__1": "Aynen! Tam şurada devasa bir ziyafet var ve üzerine saldırdıklarında elimizde sadece meşalelerimiz olacak!",
"VO__SOLDIER_N2__CH04__CHATTER__RIGHT_SPEAR__050__M__1": "Koşarız...",
"VO__SOLDIER_N2__CH04__CHATTER__SECOND_BRIDGE_SIMON__010__M__1": "Hey, şu şeyini yine kullanabilir misin? Burada sıkıştım!",
"VO__SOLDIER_N2__CH04__CHATTER__SECOND_FIRE_PASSED__030__M__1": "Vay canına! Başardın!",
"VO__SOLDIER_N2__CH04__CHATTER__SHOULD_LIGHT_REMAINING_BASIN__010__M__1": "Kızım, ikinci havuz daha hazır değil.",
"VO__SOLDIER_N2__CH04__CHATTER__SLING_BRIDGE__010__M__1": "Lanet!... Bunu beklemiyordum!",
"VO__SOLDIER_N2__CH04__CHATTER__SLING_BRIDGE__020__M__1": "Bir dakika bekleyin!",
"VO__SOLDIER_N2__CH04__CHATTER__TO_THE_2ND_BASIN__010__M__1": "Peki, nereye gidiyorsunuz bakalım?",
"VO__SOLDIER_N2__CH04__CHATTER__TO_THE_2ND_BASIN__030__M__1": "İkiniz de bir kapatmanın ortasında olduğumuzu biliyorsunuz, değil mi?!",
"VO__SOLDIER_N2__CH04__CHATTER__TO_THE_2ND_BASIN__050__M__1": "Hm, anlıyorum...",
"VO__SOLDIER_N2__CH04__CHATTER__TO_THE_3RD_BASIN__010__M__1": "İyi takım çalışması! Siviller için şaşırtıcı derecede beceriklisiniz.",
"VO__SOLDIER_N2__CH04__HELPER__1ST_LIGHT_1__010__M__1": "Havuzu yakmanın bir yolunu buldun mu?",
"VO__SOLDIER_N2__CH04__HELPER__1ST_POUR_1__010__M__1": "Hadi! Alkolü havuza dök!",
"VO__SOLDIER_N2__CH04__HELPER__1ST_POUR_2__010__M__1": "Ne bekliyorsun? O havuzu doldurmak için fıçıyı kullan!",
"VO__SOLDIER_N2__CH04__HELPER__2ND_LIGHT_1__010__M__1": "Şu havuzu yakacak mısın, yakmayacak mısın?",
"VO__SOLDIER_N2__CH04__HELPER__2ND_LIGHT_2__010__M__1": "Havuzu yakmak için şu simya şeyini kullan!",
"VO__SOLDIER_N2__CH04__HELPER__2ND_POUR_1__010__M__1": "Şu sonraki havuzu doldurmalısın!",
"VO__SOLDIER_N2__CH04__HELPER__2ND_POUR_2__010__M__1": "Hadi! Havuzu doldurmak için fıçıyı kullan!",
"VO__SOLDIER_N2__CH04__HELPER__3RD_LIGHT_1__010__M__1": "Hey! Şu katranı yakmak için simyanı kullaman gerekmiyor mu?",
"VO__SOLDIER_N2__CH04__HELPER__3RD_POUR_1__010__M__1": "Şu havuzu doldur! Tıpkı eskisi gibi!",
"VO__SOLDIER_N2__CH04__HELPER__3RD_POUR_2__010__M__1": "Havuzu doldurmak için fıçının kranını çevir!",
"VO__SOLDIER_N2__CH04__HELPER__AMPLIFY_2__010__M__1": "Fareleri uzaklaştırmak için şu ateşe katran kullanman gerekecek!",
"VO__SOLDIER_N2__CH04__HELPER__CRANK_2ND_GATE_1__010__M__1": "Tekneyi kaldırmanın bir yolunu bulmalısın!",
"VO__SOLDIER_N2__CH04__HELPER__CRANK_2ND_GATE_2__010__M__1": "Kız! Şu kranı çevir yoksa köprü yukarı çıkamaz!",
"VO__SOLDIER_N2__CH04__HELPER__LIGHT_BASIN_1__010__M__1": "Bütün havuzları yakmazsan arkadaşın geçemez!",
"VO__SOLDIER_N2__CH04__HELPER__LUCAS_STOP_ORDER_1__010__M__1": "Hey! İkinci havuza geri dönmen gerek!",
"VO__SOLDIER_N2__CH04__HELPER__LUCAS_STOP_ORDER_2__010__M__1": "Hey! Arkadaşına söyle şu kranktan insin!",
"VO__SOLDIER_N2__CH04__HELPER__SECOND_BRIDGE_SIMON_1__010__M__1": "İkiniz beni karşıya geçirecek bir yol görüyor musunuz?",
"VO__SOLDIER_N3__CH04__CHATTER__CART_PULL__005__M__1": "Eyvah, hayır, hayır! Geliyorlar!",
"VO__SOLDIER_N3__CH04__CHATTER__CART_STUCK__070__M__1": "Sıkıştı! Yardım edin işte!",
"VO__SOLDIER_N3__CH04__CHATTER__PASSAGE__030__M__1": "Bu yerden gitsek iyi olur...",
"VO__SOLDIER_N3__CH04__CHATTER__QUAI__060__M__1": "Hadi! Çoktan kapıda olmalıydın!",
"VO__SOLDIER_N3__CH04__CHATTER__VISTA_TOWER__020__M__1": "Hazır olun çocuklar! Yükümüzü yakında rıhtıma taşıyacağız!",
"VO__SOLDIER_S1__CH04__CHATTER__CART_PULL__010__M__1": "İtin! Tekerlekleri itin!",
"VO__SOLDIER_S1__CH04__CHATTER__CART_PULL__040__M__1": "Kapayın çenenizi! Sen! Bakmaya devam et! Siz ikiniz! Birlikte itin!",
"VO__SOLDIER_S1__CH04__CHATTER__CART_PUSH__010__M__1": "Hey! Ne yapıyorsun?! Dikkat et!",
"VO__SOLDIER_S1__CH04__CHATTER__CART_STUCK__030__M__1": "Ah, hadi ama!",
"VO__SOLDIER_S1__CH04__CHATTER__DOWN_PATROL__003__M__1": "Duyduk duymadık demeyin! Arles Kontu sokağa çıkma yasağı buyurdu! Bütün kasaba halkı, evlerinizde kalın!",
"VO__SOLDIER_S1__CH04__CHATTER__DOWN_PATROL__031__M__1": "Şehir kapatıldı! Sokakta yakalanan herkes tutuklanacak!",
"VO__SOLDIER_S1__CH04__CHATTER__FLAMES__010__M__1": "Hey! Şunu duydun mu?!",
"VO__SOLDIER_S1__CH04__CHATTER__GATE__030__M__1": "Siz acemiler, emirlerinizi aldınız mı?",
"VO__SOLDIER_S1__CH04__CHATTER__GATE__050__M__1": "Hayatımız buna bağlı! Şimdi dua etmeye başlayın ve gidelim!",
"VO__SOLDIER_S1__CH04__CHATTER__PASSAGE__050__M__1": "Guyenne'de olduğunda geriye toplu mezarlardan başka bir şey bırakmadığını duydum...",
"VO__SOLDIER_S1__CH04__CHATTER__QUAI__070__M__1": "Rahat bırak beni! Bu çömlekleri kırmaya gücümüz yok!",
"VO__SOLDIER_S1__CH04__CHATTER__QUAI__090__M__1": "Bu çömlekler şehre sağlam lazım! O yüzden sakin ol!",
"VO__SOLDIER_S1__CH04__CHATTER__TREMORS__010__M__1": "Hey! O da ne...?",
"VO__SOLDIER_S1__CH04__RTC__135_MEETING_JOSEPH__010__M__1": "Bu bir halk sağlığı meselesi. Hâlâ fırsatın varken gitmeliydin, Joseph.",
"VO__SOLDIER_S1__CH04__RTC__135_MEETING_JOSEPH__030__M__1": "O zaman sözleşmeni iptal say. Liman kapatıldı ve sen izinsiz giriyorsun.",
"VO__SOLDIER_S1__CH04__RTC__135_MEETING_JOSEPH__073__M__1": "Hayır. Çok şey gördün. Seni tutukluyorum!",
"VO__SOLDIER_S1__CH04__RTC__140_FIRST_OUTBURST__140__M__1": "Sokağa çıkma yasağı hâlâ geçerli! Evlerinize dönün!",
"VO__SOLDIER_S2__CH04__CHATTER__CART_PULL__020__M__1": "Kalamayız! Burada olmaz! Kıpırdayın!",
"VO__SOLDIER_S2__CH04__CHATTER__CART_STUCK__060__M__1": "Bir şey yapın, Allah aşkına!",
"VO__SOLDIER_S2__CH04__CHATTER__LINES_PATROL__030__M__1": "Paniğe gerek yok! Provence ordusu durumu kontrol altında tutuyor!",
"VO__SOLDIER_S2__CH04__CHATTER__QUAI__080__M__1": "Şehrin vakti tükeniyor!",
"VO__SOLDIER_S2__CH04__CHATTER__QUAI__100__M__1": "Tartışma yeter, askerler! Kımıldayın! Kımıldayın!",
"VO__SOLDIER_S2__CH04__CHATTER__SOLDIERS_PYRE__020__M__1": "Şey, bu temizleyicilerimizin ilerlediği anlamına gelir...",
"VO__SOLDIER_S2__CH04__CHATTER__SOLDIERS_PYRE__040__M__1": "Hepsi muhtemelen hasta. Kimseyi dışarı bırakma riskini alamayız, bunu biliyorsun.",
"VO__SOLDIER_S2__CH04__CHATTER__TREMORS__020__M__1": "Onlar... İşte onlar!",
"VO__SOLDIER_S2__CH04__RTC__135_MEETING_JOSEPH__180__M__1": "Kimsiniz? Kaptan nerede?",
"VO__SOLDIER_S2__CH04__RTC__135_MEETING_JOSEPH__200__M__1": "DAVETSİZLER!",
}
