# -*- coding: utf-8 -*-
# CH12 VO - kaynak proper Turkce; build asamasinda SUB uygulanir.
# Count of Provence (Victor) <-> Amicia: dusman, sen. Countess (Emilie) <-> Hugo/Victor: sen.
# Beatrice (Anne) <-> Amicia/Hugo: sen. Askerler -> Amicia: siz (Leydi/Efendim).
T = {
"VO__AMICIA__CH12__CHATTER___LAST_STRIKE__010__M__1": "Şimdi Hugo!",
"VO__AMICIA__CH12__CHATTER__ABOUT_MOTHER__020__M__1": "Gerçek... Aradığımızı bulduk. Ve suçlanacak kişi benim.",
"VO__AMICIA__CH12__CHATTER__ABOUT_MOTHER__040__M__1": "Kahramanım benim.",
"VO__AMICIA__CH12__CHATTER__AFTER__005__M__1": "Yani... sıçanlar mı?",
"VO__AMICIA__CH12__CHATTER__AFTER__020__M__1": "Evet...",
"VO__AMICIA__CH12__CHATTER__AFTER_HIT__020__M__1": "Hugo... Koş...",
"VO__AMICIA__CH12__CHATTER__ANY_EVACUATION__010__M__1": "Tahliye etmeyi düşünmüyor musunuz?",
"VO__AMICIA__CH12__CHATTER__BARS__010__M__1": "Kapı... Açmanın bir yolu olmalı...",
"VO__AMICIA__CH12__CHATTER__BEHIND_DOOR__020__M__1": "Lütfen... Dur... bu çılgınlığa son ver...",
"VO__AMICIA__CH12__CHATTER__BREAK_JARS_1__010__M__1": "Hayır!",
"VO__AMICIA__CH12__CHATTER__BREAK_JARS_2__010__M__1": "Ah lütfen, olmasın...",
"VO__AMICIA__CH12__CHATTER__BREAK_JARS_3__010__M__1": "Harika...",
"VO__AMICIA__CH12__CHATTER__BRIEFING_REACT__010__M__1": "Bunların hepsi boşuna.",
"VO__AMICIA__CH12__CHATTER__BRIEFING_REACT__030__M__1": "Dinlemezler. Anne'yi bulalım.",
"VO__AMICIA__CH12__CHATTER__CELL_HELPER__010__M__1": "İşte! Onu... şu odaya hapsedebilirim...",
"VO__AMICIA__CH12__CHATTER__CELLAR_AGAIN__020__M__1": "O kadar uzun süre yalan içinde yaşadın ki... artık gerçeği göremiyorsun!",
"VO__AMICIA__CH12__CHATTER__CELLAR_AGAIN__050__M__1": "Lütfen... Lütfen... Bir sığınak... Herhangi bir şey...",
"VO__AMICIA__CH12__CHATTER__CELLS__010__M__1": "Çıkış yok...",
"VO__AMICIA__CH12__CHATTER__COME_CLOSER__010__M__1": "Gel, geçeceğiz.",
"VO__AMICIA__CH12__CHATTER__CONFESSION__010__M__1": "Ne?...",
"VO__AMICIA__CH12__CHATTER__CONFESSION__030__M__1": "Onu bir yalanla beslemişsin!",
"VO__AMICIA__CH12__CHATTER__CONFESSION_KITCHEN__013__M__1": "Cehenneme git, alçak herif!",
"VO__AMICIA__CH12__CHATTER__CONFESSION_KITCHEN__023__M__1": "Hayır... Hayır! Onu alamayacaksın...",
"VO__AMICIA__CH12__CHATTER__CONFESSION_LOCKED__010__M__1": "Hadi!",
"VO__AMICIA__CH12__CHATTER__CONFESSION_RUN__020__M__1": "Onlara geri dön... Git...",
"VO__AMICIA__CH12__CHATTER__CONFESSION_RUN__040__M__1": "Cehenneme git...",
"VO__AMICIA__CH12__CHATTER__CONFESSION_RUN__060__M__1": "Onu alamayacaksın!",
"VO__AMICIA__CH12__CHATTER__CONFESSION_STAIRS__020__M__1": "Yürü...",
"VO__AMICIA__CH12__CHATTER__CONFESSION_STAIRS_LOW__010__M__1": "Sağa... Hadi...",
"VO__AMICIA__CH12__CHATTER__CONFESSION_STAIRS_LOW__020__M__1": "Çabuk...",
"VO__AMICIA__CH12__CHATTER__CONTROL_LOST__020__M__1": "Evet! İşte böyle!",
"VO__AMICIA__CH12__CHATTER__CONTROL_LOST__030__M__1": "Başardın...",
"VO__AMICIA__CH12__CHATTER__COUNT_ENTERS__060__M__1": "Hayır... Kes sesini!",
"VO__AMICIA__CH12__CHATTER__CRANK__010__M__1": "Ha... Çok... gürültülü...",
"VO__AMICIA__CH12__CHATTER__CRANK__030__M__1": "Hayır...",
"VO__AMICIA__CH12__CHATTER__CRANK__050__M__1": "Vakit yok... çabuk! Yürü!",
"VO__AMICIA__CH12__CHATTER__CRANK_HELPER__010__M__1": "Çok uzun sürüyor... Onu bir yere... kilitleyebilsem...",
"VO__AMICIA__CH12__CHATTER__CRANK_OPEN__010__M__1": "Evet... Git... Git!",
"VO__AMICIA__CH12__CHATTER__CRANK_TRY1__010__M__1": "Bu lanet... gürültü...",
"VO__AMICIA__CH12__CHATTER__CRANK_TRY2__010__M__1": "Daha hızlı... Hadi, hadi!",
"VO__AMICIA__CH12__CHATTER__DISCOVER_CELLAR__010__M__1": "Yukarı çıkmanın bir yolu olmalı...",
"VO__AMICIA__CH12__CHATTER__DISCOVER_CELLAR__020__M__1": "Omzumu tamamen mahvetti...",
"VO__AMICIA__CH12__CHATTER__DISCOVER_CELLAR__030__M__1": "Acıyor...",
"VO__AMICIA__CH12__CHATTER__DOOR__020__M__1": "Siz de.",
"VO__AMICIA__CH12__CHATTER__DOOR_CLOSE__020__M__1": "Cehenneme git!... Ha... seni domuz...",
"VO__AMICIA__CH12__CHATTER__DOOR_CLOSE__030__M__1": "Diğerlerini bulmam lazım... Çabuk...",
"VO__AMICIA__CH12__CHATTER__ESCORT__040__M__1": "Kont'un benden... ne istediğini biliyor musunuz?",
"VO__AMICIA__CH12__CHATTER__ESCORT__060__M__1": "Sanmıştım ki... daha acil işlerle ilgileniyordur.",
"VO__AMICIA__CH12__CHATTER__ESCORT__080__M__1": "Pekâlâ... öyle yaparım.",
"VO__AMICIA__CH12__CHATTER__EVACUATE__010__M__1": "Şşş... Lütfen...",
"VO__AMICIA__CH12__CHATTER__FIGHT_RATS__005__M__1": "Saray dayanacak mı, efendim?",
"VO__AMICIA__CH12__CHATTER__FIGHT_RATS__020__M__1": "Onu gördük...",
"VO__AMICIA__CH12__CHATTER__FIGHT_RATS_CHARIOT__020__M__1": "Şşş... Evet. Bunu nereden bulmuşlar?",
"VO__AMICIA__CH12__CHATTER__FIGHT_RATS_CHARIOT__040__M__1": "Evet... Biliyoruz.",
"VO__AMICIA__CH12__CHATTER__FIRST_STRIKES__040__M__1": "Bunun bedelini ödetiyoruz! Devam et, Hugo!",
"VO__AMICIA__CH12__CHATTER__GARDEN__020__M__1": "Anlaşıldı.",
"VO__AMICIA__CH12__CHATTER__HOSPITAL__050__M__1": "Evet... yakında yayılacak...",
"VO__AMICIA__CH12__CHATTER__IDLE_CHASE1__010__M__1": "Onu atlat, çabuk...",
"VO__AMICIA__CH12__CHATTER__IDLE_CHASE2__010__M__1": "Saklan...",
"VO__AMICIA__CH12__CHATTER__IDLE_CHASE3__010__M__1": "Durma... Başarabilirsin...",
"VO__AMICIA__CH12__CHATTER__IDLE_CHASE5__020__M__1": "Kapa şu çeneni...",
"VO__AMICIA__CH12__CHATTER__IDLE_CHASE7__010__M__1": "Hadi... Devam et... Hugo, Anne, Lucas... Önemli olan tek şey onlar...",
"VO__AMICIA__CH12__CHATTER__IDLE_CHASE8__020__M__1": "Seni öldüreceğim... ilk fırsatta...",
"VO__AMICIA__CH12__CHATTER__IMPENDING_LAST_STRIKE__010__M__1": "Sıra sende, Emilie! Şimdi SENİN kanını dökeceğiz!",
"VO__AMICIA__CH12__CHATTER__KITCHEN_CHAINS__010__M__1": "Lanet olsun, hayır...",
"VO__AMICIA__CH12__CHATTER__KITCHEN_CHAINS__030__M__1": "Beni... ele geçiremeyeceksin...",
"VO__AMICIA__CH12__CHATTER__KITCHEN_HIDE__060__M__1": "Olamaz...",
"VO__AMICIA__CH12__CHATTER__KITCHEN_IN__020__M__1": "Gözden uzak dur...",
"VO__AMICIA__CH12__CHATTER__KITCHEN_IN__040__M__1": "Kımıldamam lazım!",
"VO__AMICIA__CH12__CHATTER__KITCHEN_OUT__020__M__1": "Geri dur!",
"VO__AMICIA__CH12__CHATTER__KITCHEN_SERVANT__030__M__1": "Yardım lazım! Lütfen! Buradan nasıl çıkacağım?!",
"VO__AMICIA__CH12__CHATTER__LOSING_CONTROL__020__M__1": "Evet! Al onları! Senindirler! Hepsi senin!",
"VO__AMICIA__CH12__CHATTER__LOSING_CONTROL__040__M__1": "Öyle olsun!",
"VO__AMICIA__CH12__CHATTER__LURE__010__M__1": "Buraya gel... Gel...",
"VO__AMICIA__CH12__CHATTER__LURE_DOOR__010__M__1": "Kapı... Onu içeri kilitlemeliyim...",
"VO__AMICIA__CH12__CHATTER__LURE_HELPER__010__M__1": "Belki... onu şu hücrelere kilitlerim.",
"VO__AMICIA__CH12__CHATTER__LURE_SQUEEZE__010__M__1": "Buradan... sessizce...",
"VO__AMICIA__CH12__CHATTER__MOTHER__010__M__1": "Sıkıştı! Devirin onu! Daha çok çağırın!",
"VO__AMICIA__CH12__CHATTER__MOTHER__030__M__1": "İşte kanın! Bırakın sıçanlar onları yesin!",
"VO__AMICIA__CH12__CHATTER__NEAR_END__010__M__1": "Yapamıyorum...",
"VO__AMICIA__CH12__CHATTER__NEAR_END__020__M__1": "Şimdi... bayılma... Hugo... Onu... alıp götürecekler...",
"VO__AMICIA__CH12__CHATTER__NEAR_END__030__M__1": "Anne... Lucas... Onları buradan çıkar... Ha... Acısa bile...",
"VO__AMICIA__CH12__CHATTER__NEAR_END__040__M__1": "Acı... Elindeki tek şey o... İyi bilirsin... O hâlde kullan... onlara karşı kullan onu...",
"VO__AMICIA__CH12__CHATTER__NEAR_END__050__M__1": "Çıkış... evet...",
"VO__AMICIA__CH12__CHATTER__PRAYING__020__M__1": "Çocuk gerçekten geliyor mu?",
"VO__AMICIA__CH12__CHATTER__RAT_EXPLANATION__010__M__1": "Güzel... Şimdi her şeyi güvenli ve yavaş yapacağız. Aptalca riskler yok. Hugo, tuhaf hissedersen hemen söyle.",
"VO__AMICIA__CH12__CHATTER__RAT_HEAT__020__M__1": "Durma, Hugo! Neredeyse vardın!",
"VO__AMICIA__CH12__CHATTER__RAT_HEAT__040__M__1": "Evet! Parçala onları!",
"VO__AMICIA__CH12__CHATTER__RATS_SHOO__020__M__1": "Az önce atlattığımızdan beter olamaz. Başaracağız.",
"VO__AMICIA__CH12__CHATTER__RATS_TORCH_PICK__010__M__1": "Başka çare yok... Üzgünüm...",
"VO__AMICIA__CH12__CHATTER__REACHING_DOOR__010__M__1": "İşte...",
"VO__AMICIA__CH12__CHATTER__RUN__010__M__1": "Çıkış nerede?!... Bir çıkış ver şu lanet olası!",
"VO__AMICIA__CH12__CHATTER__RUN__040__M__1": "Kapa... şu lanet... çeneni!",
"VO__AMICIA__CH12__CHATTER__RUNNING__010__M__1": "Anne, Lucas... Onlara dokunduysa...",
"VO__AMICIA__CH12__CHATTER__RUNNING__030__M__1": "Alçak... alçak...",
"VO__AMICIA__CH12__CHATTER__RUNNING_CELLAR__025__M__1": "Benden uzak dur!",
"VO__AMICIA__CH12__CHATTER__RUNNING_CELLAR__040__M__1": "Delisin! Onu bizden alırsan hepiniz öleceksiniz!",
"VO__AMICIA__CH12__CHATTER__SECOND_STRIKES__020__M__1": "İşe yarıyor! Devam et! Daha çok sıçan geliyor!",
"VO__AMICIA__CH12__CHATTER__SECOND_STRIKES__080__M__1": "Güzel..! Bırak yapsın!",
"VO__AMICIA__CH12__CHATTER__SECOND_WAVE__050__M__1": "Evet, gelin! Bana gelin! Kanınızı verin bize!",
"VO__AMICIA__CH12__CHATTER__SOUP_GO__020__M__1": "Ah, ben... değilim... Affedersiniz...",
"VO__AMICIA__CH12__CHATTER__STAIRS__030__M__1": "Yine de... bakmamaya çalış.",
"VO__AMICIA__CH12__CHATTER__WALK__043__M__1": "Güçbela... Üzgünüm... topraklarınız için.",
"VO__AMICIA__CH12__CHATTER__WALK__046__M__1": "Anlıyorum. Yaralar hâlâ çok taze. İnsan sadece huzur isterken zihnini dolduruyorlar... Pardon, ben...",
"VO__AMICIA__CH12__CHATTER__WALK__048__M__1": "Bu çok insani, bence.",
"VO__AMICIA__CH12__CHATTER__WALK__060__M__1": "Evet.",
"VO__AMICIA__CH12__CHATTER__WALK_OUT__015__M__1": "Pekâlâ.",
"VO__AMICIA__CH12__CHATTER__WAR__020__M__1": "Tahliye etmeliler.",
"VO__AMICIA__CH12__RTC__600_TO_THE_PALACE__020__M__1": "Başkaları daha önce denedi ve yine de öldü. Çok geç, gitmeliyiz.",
"VO__AMICIA__CH12__RTC__600_TO_THE_PALACE__040__M__1": "Artık mesele sadece bu ada değil, Hugo. Gitmeliyiz, yoksa her şeyi mahvedeceğiz.",
"VO__AMICIA__CH12__RTC__605_ESCORT__024__M__1": "Pekâlâ, liman... Gel!",
"VO__AMICIA__CH12__RTC__605_ESCORT__060__M__1": "Hayır...",
"VO__AMICIA__CH12__RTC__605_ESCORT__080__M__1": "Aslında... tam gitmek üzereydik...",
"VO__AMICIA__CH12__RTC__605_ESCORT__100__M__1": "Misafirler mi?... Kim?",
"VO__AMICIA__CH12__RTC__605_ESCORT__130__M__1": "Elbette...",
"VO__AMICIA__CH12__RTC__605_ESCORT__150__M__1": "Bilmiyorum, ben...",
"VO__AMICIA__CH12__RTC__605_ESCORT__170__M__1": "Evet. Sanırım bundan kaçamayız...",
"VO__AMICIA__CH12__RTC__605_ESCORT__200__M__1": "Bunu al. Ne olursa olsun, bu alevi canlı tut, olur mu?",
"VO__AMICIA__CH12__RTC__605_ESCORT__220__M__1": "Öne geç o zaman.",
"VO__AMICIA__CH12__RTC__610_A_BANQUET__040__M__1": "Anne...",
"VO__AMICIA__CH12__RTC__610_A_BANQUET__056__M__1": "Anne!",
"VO__AMICIA__CH12__RTC__610_A_BANQUET__080__M__1": "Sorun değil, merak etme... Bizi nasıl buldun?",
"VO__AMICIA__CH12__RTC__610_A_BANQUET__150__M__1": "Evet, altıncı yüzyılda. Basilius adında bir çocuk. Onu bulduk... özellikle onun için tasarlanmış bir Düzen zindanında zincirlenmiş hâlde...",
"VO__AMICIA__CH12__RTC__610_A_BANQUET__156__M__1": "... Sanırım son eşiğine ulaştığında panikledi onlar. Onu Koruyucusundan kopardılar. Oraya kilitlediler... olacakları... kontrol altında tutmak için.",
"VO__AMICIA__CH12__RTC__610_A_BANQUET__180__M__1": "Evet... Anne, Magister Vaudin Hugo'nun lanetli olduğunu söyledi, ama Düzen'in inandığı bu, geçmişte Basilius'la yaptıkları hataya dayanıyor. Eğer onun da Koruyucusu olsaydı, tıpkı Hugo'nun bizler gibi, eminim hiçbir şey olmazdı...",
"VO__AMICIA__CH12__RTC__610_A_BANQUET__190__M__1": "Bir düşün... Yollardaki son aylarda, sakin olan zamanlarda, her şey gayet yolundaydı. O iyiydi.",
"VO__AMICIA__CH12__RTC__610_A_BANQUET__210__M__1": "İçimden bir ses diyor ki... güvenli bir yere yerleşip orada bir aile olarak yaşarsak...",
"VO__AMICIA__CH12__RTC__610_A_BANQUET__216__M__1": "Daha kötüye gitmeyi bırakır.",
"VO__AMICIA__CH12__RTC__610_A_BANQUET__240__M__1": "Ben mi? Şimdi mi? Ama tam gitmek üzereydik.",
"VO__AMICIA__CH12__RTC__610_A_BANQUET__300__M__1": "Peki. Beni ona götür.",
"VO__AMICIA__CH12__RTC__620_DECEIVED__015__M__1": "Ne... Neden?!",
"VO__AMICIA__CH12__RTC__620_DECEIVED__030__M__1": "Neyden emin?!",
"VO__AMICIA__CH12__RTC__620_DECEIVED__050__M__1": "Hayır, hayır... Dinle... Bu konuda hepiniz tamamen yanılıyorsunuz! Tarikatınız... Her şey!",
"VO__AMICIA__CH12__RTC__630_THE_BALLROOM__017__M__1": "Kes sesini! Bu aile üzerinde hiçbir hakkın yok!",
"VO__AMICIA__CH12__RTC__630_THE_BALLROOM__050__M__1": "Hugo nerede?",
"VO__AMICIA__CH12__RTC__640_DUEL__030__M__1": "Yaparım... Kardeşimi alamayacaksın.",
"VO__AMICIA__CH12__RTC__640_DUEL__080__M__1": "Ben asker değilim...",
"VO__AMICIA__CH12__RTC__640_DUEL__100__M__1": "Çok konuşuyorsun... Korkak!",
"VO__AMICIA__CH12__RTC__640_DUEL__140__M__1": "Her neyse... Yine de... korkağın tekisin...",
"VO__AMICIA__CH12__RTC__640_DUEL__160__M__1": "Ben... Amicia de Rune...",
"VO__AMICIA__CH12__RTC__640_DUEL__180__M__1": "Ve ben... HİÇ KİMSENİN önünde diz çökmem!",
"VO__AMICIA__CH12__RTC__650_AMICIAS_CALL__030__M__1": "Hayır... HAYIR!",
"VO__AMICIA__CH12__RTC__660_NOW_THEY_DIE__048__M__1": "Hugo...",
"VO__AMICIA__CH12__RTC__660_NOW_THEY_DIE__110__M__1": "Daha fazlası lazım! Daha çok sıçan lazım sana!",
"VO__AMICIA__CH12__RTC__665_DEVOURED__070__M__1": "Hayır...",
"VO__AMICIA__CH12__RTC__670_ANGER__030__M__1": "Buradayım... Buradayım!",
"VO__AMICIA__CH12__RTC__670_ANGER__040__M__1": "Ah... Olamaz... Hugo... Hugo... Hugo... Hayır!",
"VO__AMICIA__CH12__RTC__670_ANGER__050__M__1": "Cevap ver! Bir şey söyle! Hugo... Hayır...",
"VO__AMICIA__CH12__RTC__670_ANGER__060__M__1": "Ah... Şükürler olsun... Şükürler olsun!",
"VO__AMICIA__CH12__RTC__670_ANGER__070__M__1": "İyiyiz... İyisin... İyiyiz.",
"VO__BANDIT_N2__CH12__CHATTER__SOLDIERS_INCOMING_2__030__M__1": "Anne uğruna canım feda!",
"VO__BANDIT_S3__CH12__CHATTER__SOLDIERS_INCOMING_2__010__M__1": "Benimle!",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__030__M__1": "Tanrım! Yaşıyorsun!",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__050__M__1": "Gel buraya...",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__053__M__1": "Lütfen... Gel buraya.",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__060__M__1": "Nasılsın?",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__070__M__1": "Başın!",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__090__M__1": "Arkanda epey bir iz bırakmışsın...",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__100__M__1": "Ama söyle: bu mu o? Bu ada?",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__153__M__1": "Ne?!",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__170__M__1": "Justinianus Vebası. Macula'yla bağlantılı olduğunu biliyorduk, ama...",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__173__M__1": "...demek burada başladı, bu Basilius'la!",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__200__M__1": "Bu doğru.",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__213__M__1": "Belki Veba... zamanla durur...",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__220__M__1": "Korku zihnimizi gerçekten bulandırdı, değil mi? Seninki hariç, Koruyucu.",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__226__M__1": "Dağlardaki o evimizi hatırla. Orada çok iyi oluruz!",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__285__M__1": "Evet.",
"VO__BEATRICE__CH12__RTC__610_A_BANQUET__295__M__1": "Seni bekleyeceğiz. Şimdilik burada dışarıdan daha güvendeyiz zaten.",
"VO__BEATRICE__CH12__RTC__630_THE_BALLROOM__012__M__1": "Hugo geçmişinin yaralarını iyileştirmeyecek. İçindeki boşluğu doldurmayacak. Öleceksin. Herkes ölecek.",
"VO__BEATRICE__CH12__RTC__630_THE_BALLROOM__019__M__1": "Amicia...",
"VO__BEATRICE__CH12__RTC__640_DUEL__210__M__1": "Hayır! Amicia! Hayır! ... Lütfen.",
"VO__BEATRICE__CH12__RTC__650_AMICIAS_CALL__001__M__1": "Lütfen dur... LÜTFEN! DUR! Bir anneden diğerine.",
"VO__BEATRICE__CH12__RTC__650_AMICIAS_CALL__022__M__1": "Sevgi öldürebilir, Emilie. Bunu fark ettiğinde çok geç olacak.",
"VO__BEATRICE__CH12__RTC__650_AMICIAS_CALL__025__M__1": "Seninle gurur duyuyorum.",
"VO__COUNT__CH12__CHATTER__AFTER__010__M__1": "Sadece sıçanlar değil. Gel, kendi gözünle göreceksin.",
"VO__COUNT__CH12__CHATTER__AFTER_HIT__010__M__1": "Haaa! Kahrol!",
"VO__COUNT__CH12__CHATTER__BATTLE_PLAN__020__M__1": "Ana kapı şimdilik yeterince güvenli, ama batı surları hâlâ zayıf! Sıçanlar oradan girerse yaralıları tahliye edemeyiz. Şimdi, o sıçanların nereden geldiğini öğrenmek istiyorum. Keşif kolu yollayın. Onları yavaşlatmanın, durdurmanın ya da cehenneme yollamanın bir yolunu bulabilirsek, riske değer.",
"VO__COUNT__CH12__CHATTER__BATTLE_PLAN__065__M__1": "Güzel.",
"VO__COUNT__CH12__CHATTER__BATTLE_PLAN__067__M__1": "Bu, hiçbirine benzemeyen bir savaş. Ama yine de bir savaş.",
"VO__COUNT__CH12__CHATTER__BATTLE_PLAN__070__M__1": "Dağılın! Ve inancınızı koruyun! Daha bitmedi!",
"VO__COUNT__CH12__CHATTER__BEHIND_DOOR__010__M__1": "Ah, bana eski zamanları anımsatıyorsun... Kendimi... Şimdi seni... kanının aktığı yerde göreceğim...",
"VO__COUNT__CH12__CHATTER__CELLAR_AGAIN__010__M__1": "Bırak gitsin işte.",
"VO__COUNT__CH12__CHATTER__CELLAR_AGAIN__030__M__1": "Gerçek şu ki, o hariç her şey çürümüş! Bu dünyanın yanmamasının tek sebebi o!",
"VO__COUNT__CH12__CHATTER__CELLAR_AGAIN__040__M__1": "Ama kardeşini o çürümeden koruyacağız! Buna gücümüz yeter!",
"VO__COUNT__CH12__CHATTER__CONFESSION__020__M__1": "Emilie... O lanet ailesi, canına kıymaya çalışana dek aklını paramparça etti. Kendi bedenini zehirledi... Ben de onu buraya getirdim, ona şu Köz Çocuğu hikâyesini sundum... Sadece inanmakla kalmadı, onu halk için bir umuda dönüştürdü!",
"VO__COUNT__CH12__CHATTER__CONFESSION__040__M__1": "Ne yapmaya çalışıyorsun?... Kaderini kabul et.",
"VO__COUNT__CH12__CHATTER__CONFESSION_KITCHEN__021__M__1": "Seni bulacağım! Ve bir köpek gibi GEBERECEKSİN!",
"VO__COUNT__CH12__CHATTER__CONFESSION_RUN__010__M__1": "Ne cüretle?! Geri gel!",
"VO__COUNT__CH12__CHATTER__CONFESSION_RUN__030__M__1": "Onu kaybetmeyeceğim! Hele senin yüzünden asla!",
"VO__COUNT__CH12__CHATTER__CONFESSION_RUN__050__M__1": "Nereye gidiyorsun?!",
"VO__COUNT__CH12__CHATTER__CONFESSION_STAIRS__010__M__1": "Onu kendinden ben bile kurtaramam! Ama kardeşin kurtarabilir!",
"VO__COUNT__CH12__CHATTER__CONFESSION_STAIRS_LOW__030__M__1": "Neyin tehlikede olduğunu hayal bile edemezsin!",
"VO__COUNT__CH12__CHATTER__COUNT_AGGRESSIVE__010__M__1": "Hiçbir yere gidemezsin!",
"VO__COUNT__CH12__CHATTER__COUNT_COME_BACK__010__M__1": "Emilie! Buradayım!",
"VO__COUNT__CH12__CHATTER__COUNT_COME_BACK__030__M__1": "Bırak onu, Emilie! O, Köz Çocuğu değil! Bana gel!",
"VO__COUNT__CH12__CHATTER__COUNT_COME_BACK__050__M__1": "Yapabilirsin! Dene! Elini ver bana!",
"VO__COUNT__CH12__CHATTER__COUNT_ENTERS__040__M__1": "Nerede o?!",
"VO__COUNT__CH12__CHATTER__CRANK__040__M__1": "Zor yolu seçtin!",
"VO__COUNT__CH12__CHATTER__CRANK__060__M__1": "Seni duyuyorum! Korku seni dikkatsizleştiriyor!",
"VO__COUNT__CH12__CHATTER__DOOR_CLOSE__010__M__1": "Pekâlâ, oynayalım! Bu oyunda iyiyimdir, göreceksin!",
"VO__COUNT__CH12__CHATTER__IDLE_CHASE4__010__M__1": "Burada kapana kısıldın! Nereye gidersen git, seni bulurum! Bunun için eğitildim!",
"VO__COUNT__CH12__CHATTER__IDLE_CHASE5__010__M__1": "Korkunç acıyor, değil mi?! Acını dindirebilirim! Bana güven...",
"VO__COUNT__CH12__CHATTER__IDLE_CHASE6__010__M__1": "Hayatta kalma içgüdün... Hayranım buna... Çok şey atlatmışsın, belli. Bu işi daha da heyecanlı kılıyor.",
"VO__COUNT__CH12__CHATTER__IDLE_CHASE8__010__M__1": "Avlanmayalı uzun zaman oldu... Emilie'yle tanıştığımdan beri... Ve sen muhteşem bir avsın!",
"VO__COUNT__CH12__CHATTER__IDLE_CHASE9__010__M__1": "Senden hoşlanmıştı, biliyor musun, Emilie... Ama fazla tehlikelisin... Bizim için... Çocuk için!...",
"VO__COUNT__CH12__CHATTER__IMPENDING_LAST_STRIKE__020__M__1": "Hayır! Emilie, çabuk!",
"VO__COUNT__CH12__CHATTER__IMPENDING_LAST_STRIKE__040__M__1": "Elini ver!",
"VO__COUNT__CH12__CHATTER__KITCHEN_DOOR__010__M__1": "Nereye kaçıyorsun?! Kaçış yok!",
"VO__COUNT__CH12__CHATTER__KITCHEN_HIDE__010__M__1": "Hadi, şunu bitirelim!",
"VO__COUNT__CH12__CHATTER__KITCHEN_HIDE__035__M__1": "Haksızlık gibi göründüğünü biliyorum...",
"VO__COUNT__CH12__CHATTER__KITCHEN_HIDE__040__M__1": "Ama yönetmek için neler gerektiğini bilmiyorsun!",
"VO__COUNT__CH12__CHATTER__KITCHEN_HIDE__050__M__1": "Savaş... çok kolay. Her şeyi yok edebilirdim... Ama o bana başka bir yol gösterdi... İçinde bir ışık var! Sen de gördün!",
"VO__COUNT__CH12__CHATTER__KITCHEN_IN__010__M__1": "Pekâlâ, herkes dışarı!",
"VO__COUNT__CH12__CHATTER__KITCHEN_IN__030__M__1": "Sen ve ben, şimdi...",
"VO__COUNT__CH12__CHATTER__LURE__020__M__1": "Kapana kısıldın...",
"VO__COUNT__CH12__CHATTER__LURE_OUT__010__M__1": "Oyun yeter! Buraya gel!",
"VO__COUNT__CH12__CHATTER__LURE_OUT_AGAIN__010__M__1": "Aaah! Seni öldüreceğim!",
"VO__COUNT__CH12__CHATTER__LURE_TRAPPED__010__M__1": "Ne? Seni pis küçük...",
"VO__COUNT__CH12__CHATTER__LURE_TRAPPED_AGAIN__010__M__1": "Seni küstah velet! Bunun acısını çektireceğim sana!",
"VO__COUNT__CH12__CHATTER__NOISES_KITCHEN__025__M__1": "Sabırlı olmaya çalıştım...",
"VO__COUNT__CH12__CHATTER__PRAYING__030__M__1": "Bütün işaretler ortada.",
"VO__COUNT__CH12__CHATTER__RUN__020__M__1": "Yine mi kaçıyorsun?!... Yorulmak bilmiyorsun...",
"VO__COUNT__CH12__CHATTER__RUN__030__M__1": "Keşke adamlarımda senin azminin yarısı olsaydı!",
"VO__COUNT__CH12__CHATTER__RUN__050__M__1": "Başardın! İnanılmaz...",
"VO__COUNT__CH12__CHATTER__RUNNING__020__M__1": "Çok geç! Artık onun varlığını biliyor!",
"VO__COUNT__CH12__CHATTER__RUNNING_CELLAR__020__M__1": "İnsanlar ona, Çocuğa inandıkları kadar inanıyor!",
"VO__COUNT__CH12__CHATTER__RUNNING_CELLAR__027__M__1": "Anlamıyor musun?! Bu senden çok daha büyük bir şey!",
"VO__COUNT__CH12__CHATTER__RUNNING_CELLAR__028__M__1": "Pes et! Kardeşini teslim et! Bunu kolay yoldan halledebiliriz!",
"VO__COUNT__CH12__CHATTER__RUNNING_CELLAR__050__M__1": "Bu kadar dramatik olma... Öylece yok olup gideceksin. Ve dünyanın umurunda bile olmayacak!",
"VO__COUNT__CH12__CHATTER__WALK__040__M__1": "Demek o canavarlardan sağ kurtuldun...",
"VO__COUNT__CH12__CHATTER__WALK__044__M__1": "Bir lord, hiçbir barışın sonsuza dek sürmediğini bilmeli. Ama itiraf ederim ki... yıllarca süren savaşın ardından... bu barışın süreceğini... ummaya cüret etmiştim.",
"VO__COUNT__CH12__CHATTER__WALK__047__M__1": "Hayır, hayır. Tam da... öyle.",
"VO__COUNT__CH12__CHATTER__WALK__050__M__1": "Haklısın. Ama bu, savaş çağırdığında orada olmana engel değil.",
"VO__COUNT__CH12__CHATTER__WALK_OUT__010__M__1": "Gel, sana ihtiyacım var.",
"VO__COUNT__CH12__RTC__620_DECEIVED__020__M__1": "Emilie çocuğu istiyor, Amicia. Üzgünüm ama artık emin.",
"VO__COUNT__CH12__RTC__620_DECEIVED__040__M__1": "Kardeşinin Köz Çocuğu olduğundan. Ona sahip olmalı, o yüzden sen ölmelisin.",
"VO__COUNT__CH12__RTC__620_DECEIVED__060__M__1": "Muhtemelen haklısın... Çünkü çoğunu ben uydurdum. Ve bunu onun için yaptım.",
"VO__COUNT__CH12__RTC__630_THE_BALLROOM__080__M__1": "Üzgünüm aşkım, ama bu kız müthiş bir savaşçı!",
"VO__COUNT__CH12__RTC__630_THE_BALLROOM__090__M__1": "İşte bu...",
"VO__COUNT__CH12__RTC__630_THE_BALLROOM__100__M__1": "Reddedemeyeceğim bir davet.",
"VO__COUNT__CH12__RTC__640_DUEL__010__M__1": "Beni gafil avladın. Etkilendim.",
"VO__COUNT__CH12__RTC__640_DUEL__020__M__1": "Sen tam bir olaysın, biliyor musun... Karşıma dikiliyorsun. Tüm benliğinle, beni yenebileceğine inanarak!",
"VO__COUNT__CH12__RTC__640_DUEL__040__M__1": "Hıh. Ne adanmışlık...",
"VO__COUNT__CH12__RTC__640_DUEL__050__M__1": "İçinde yanan bir ateş var.",
"VO__COUNT__CH12__RTC__640_DUEL__060__M__1": "Ama disiplinsiz bir alev, asker olmaz...",
"VO__COUNT__CH12__RTC__640_DUEL__070__M__1": "... onları içten içe tüketir.",
"VO__COUNT__CH12__RTC__640_DUEL__090__M__1": "Ah, biliyorum. Sen başka çaren olmadığı için savaşıyorsun. Ben bu hayatı seçtim. İşte bu yüzden başarısız olacaksın.",
"VO__COUNT__CH12__RTC__640_DUEL__110__M__1": "Duruşunu sağlamlaştır! Yerini koru!",
"VO__COUNT__CH12__RTC__640_DUEL__120__M__1": "Şu kılıcı düzgün tut! Ona yüz karasısın!",
"VO__COUNT__CH12__RTC__640_DUEL__130__M__1": "Asla kendini savunmak için savaşma! Öldürmek için savaş! Fethetmek için!",
"VO__COUNT__CH12__RTC__640_DUEL__150__M__1": "BANA KAFA TUTACAK KADAR KENDİNİ NE SANIYORSUN?",
"VO__COUNT__CH12__RTC__640_DUEL__170__M__1": "Ha. Kes sesini!",
"VO__COUNT__CH12__RTC__640_DUEL__200__M__1": "Kes sesini!",
"VO__COUNT__CH12__RTC__640_DUEL__220__M__1": "Gördün mü? Gayet güzel diz çöküyorsun işte.",
"VO__COUNTESS__CH12__CHATTER__COUNT_COME_BACK__020__M__1": "Victor! Aklını kaçırdı!",
"VO__COUNTESS__CH12__CHATTER__COUNT_COME_BACK__040__M__1": "Sana ulaşamıyorum!",
"VO__COUNTESS__CH12__CHATTER__COUNT_COME_BACK__060__M__1": "Yapamıyorum!",
"VO__COUNTESS__CH12__CHATTER__FIRST_STRIKES__030__M__1": "Ne yapıyorsun?!",
"VO__COUNTESS__CH12__CHATTER__IMPENDING_LAST_STRIKE__030__M__1": "Çok geç, Victor!",
"VO__COUNTESS__CH12__CHATTER__IMPENDING_LAST_STRIKE__050__M__1": "Sorun yok!",
"VO__COUNTESS__CH12__CHATTER__SECOND_STRIKES__040__M__1": "Seni kandırıyor, Hugo! Buna son ver!",
"VO__COUNTESS__CH12__CHATTER__SECOND_STRIKES__060__M__1": "Lütfen!",
"VO__COUNTESS__CH12__CHATTER__SECOND_WAVE__010__M__1": "Dur! Sana zarar vermezler, yavrum! İstedikleri o!",
"VO__COUNTESS__CH12__CHATTER__SECOND_WAVE__030__M__1": "Hayır, Hugo! Bu bir hata!",
"VO__COUNTESS__CH12__RTC__630_THE_BALLROOM__010__M__1": "Korkma... Evet, başarısız oldun ama... bu çocuk hiçbir zaman gerçekten senin olmadı.",
"VO__COUNTESS__CH12__RTC__630_THE_BALLROOM__014__M__1": "Hayır! O sevilecek! Daha parlak bir güneş gibi ışıyacak! Bu karanlığı kovacak! Ve ben... ben sadece bir anne olacağım, bir tanrının ilk adımlarını izleyen.",
"VO__COUNTESS__CH12__RTC__630_THE_BALLROOM__015__M__1": "Kendimi onunla... dopdolu hissediyorum.",
"VO__COUNTESS__CH12__RTC__630_THE_BALLROOM__040__M__1": "Sen nasıl hâlâ hayattasın?",
"VO__COUNTESS__CH12__RTC__630_THE_BALLROOM__060__M__1": "Nihayet!",
"VO__COUNTESS__CH12__RTC__650_AMICIAS_CALL__010__M__1": "Oyun yeter, Victor. Buraya bunun için gelmedik.",
"VO__COUNTESS__CH12__RTC__650_AMICIAS_CALL__012__M__1": "Üzgünüm. Savaş kocamı yıprattı. Bazen... kendini kaptırıyor.",
"VO__COUNTESS__CH12__RTC__650_AMICIAS_CALL__013__M__1": "Sana hayranım. Çocukların güçlü. Bağların güçlü.",
"VO__COUNTESS__CH12__RTC__650_AMICIAS_CALL__014__M__1": "Onun yaşındayken... böyle bir sevgiyi ancak hayal edebilirdim.",
"VO__COUNTESS__CH12__RTC__650_AMICIAS_CALL__015__M__1": "Ama mesele sadece biz değiliz, çünkü sevgi paylaşılmak içindir...",
"VO__COUNTESS__CH12__RTC__650_AMICIAS_CALL__016__M__1": "Işığa dönüşmek, tüm dünyanın üzerine parlamak için!",
"VO__COUNTESS__CH12__RTC__650_AMICIAS_CALL__020__M__1": "Köz Çocuğu'nun kaderi böyledir işte.",
"VO__COUNTESS__CH12__RTC__650_AMICIAS_CALL__024__M__1": "Şimdilik, hızlı olacak.",
"VO__COUNTESS__CH12__RTC__660_NOW_THEY_DIE__040__M__1": "Ah benim yavru oğlum...",
"VO__COUNTESS__CH12__RTC__660_NOW_THEY_DIE__046__M__1": "Yatağına dönmelisin.",
"VO__COUNTESS__CH12__RTC__660_NOW_THEY_DIE__060__M__1": "Hayır, hayır... Seni yatağına götüreyim mi? Victor... onu geri götür, olur mu?",
"VO__COUNTESS__CH12__RTC__660_NOW_THEY_DIE__080__M__1": "Sensin... Sensin! Biliyordum!",
"VO__COUNTESS__CH12__RTC__660_NOW_THEY_DIE__100__M__1": "Hayır! Ne yapıyorsun?... Lütfen... Lütfen...",
"VO__COUNTESS__CH12__RTC__660_NOW_THEY_DIE__120__M__1": "Daha iyi bir anne olacağım...",
"VO__COUNTESS__CH12__RTC__660_NOW_THEY_DIE__130__M__1": "Daha iyi bir anne olacağım!",
"VO__COUNTESS__CH12__RTC__660_NOW_THEY_DIE__140__M__1": "Lütfen!",
"VO__COUNTESS__CH12__RTC__665_DEVOURED__008__M__1": "Aşkım...",
"VO__HUGO__CH12__CHATTER__ABOUT_MOTHER__010__M__1": "Ona ne diyeceğiz?",
"VO__HUGO__CH12__CHATTER__ABOUT_MOTHER__030__M__1": "Seni savunacağım.",
"VO__HUGO__CH12__CHATTER__BLOOD__035__M__1": "Hayır... Değil... Bu gerçek...",
"VO__HUGO__CH12__CHATTER__BLOOD__041__M__1": "Bu bir rüya mı?",
"VO__HUGO__CH12__CHATTER__BRIEFING_REACT__020__M__1": "Onlara gitmelerini söylemeliyiz, Amicia...",
"VO__HUGO__CH12__CHATTER__CATACOMBS__007__M__1": "Amicia?...",
"VO__HUGO__CH12__CHATTER__CHARIOT_BUILT__020__M__1": "Bir tane daha...",
"VO__HUGO__CH12__CHATTER__CHILDREN__010__M__1": "Çocuklar...",
"VO__HUGO__CH12__CHATTER__EVACUATE__005__M__1": "Bu benim suçum...",
"VO__HUGO__CH12__CHATTER__FIGHT_RATS_CHARIOT__010__M__1": "Ah... Gördüğümüze benziyor... şu kırık olana!",
"VO__HUGO__CH12__CHATTER__FIND_FAMILY__040__M__1": "Ah, başım...",
"VO__HUGO__CH12__CHATTER__HEARING_NOISE_OUT__006__M__1": "Amicia... onun sesiydi... Onu duydum...",
"VO__HUGO__CH12__CHATTER__HEARING_NOISE_OUT__010__M__1": "Ah... İnsanlar var!",
"VO__HUGO__CH12__CHATTER__HOSPITAL__040__M__1": "Bunlar ısırılmış olanlar...",
"VO__HUGO__CH12__CHATTER__LEAVE_ROOM__010__M__1": "Anneciğim...?",
"VO__HUGO__CH12__CHATTER__LEAVE_ROOM__011__M__1": "Amicia...?",
"VO__HUGO__CH12__CHATTER__LEAVE_ROOM__013__M__1": "Lucas...? Neredesin?!",
"VO__HUGO__CH12__CHATTER__LEAVE_ROOM__015__M__1": "Herkes nerede?",
"VO__HUGO__CH12__CHATTER__LOSING_CONTROL__010__M__1": "Daha... çok... et istiyorum!",
"VO__HUGO__CH12__CHATTER__MOTHER__020__M__1": "Kan için gelecekler!",
"VO__HUGO__CH12__CHATTER__RAT_EXPLANATION__020__M__1": "Söylerim.",
"VO__HUGO__CH12__CHATTER__RAT_HEAT__030__M__1": "Biz... KAN istiyoruz!",
"VO__HUGO__CH12__CHATTER__RATS_CHARIOT__010__M__1": "Ah...",
"VO__HUGO__CH12__CHATTER__RATS_TORCH_PICK__005__M__1": "Ah... ölmüş...",
"VO__HUGO__CH12__CHATTER__RATS_TORCH_PICK__020__M__1": "Evet. Üzgünüm.",
"VO__HUGO__CH12__CHATTER__SECOND_STRIKES__050__M__1": "Hayır! Sizi diri diri yiyeceğim!",
"VO__HUGO__CH12__CHATTER__SECOND_WAVE__020__M__1": "Kapayın çenenizi! Hepiniz öleceksiniz!",
"VO__HUGO__CH12__CHATTER__STAIRS__020__M__1": "Kanı bilirim.",
"VO__HUGO__CH12__CHATTER__WAR__010__M__1": "Savaşa benziyor...",
"VO__HUGO__CH12__CHATTER__WAR__030__M__1": "Evet. Onlara karşı kimse kazanamaz.",
"VO__HUGO__CH12__RTC__600_TO_THE_PALACE__030__M__1": "Ama...",
"VO__HUGO__CH12__RTC__605_ESCORT__120__M__1": "Ho!",
"VO__HUGO__CH12__RTC__605_ESCORT__140__M__1": "Sence bizi azarlayacak mı?",
"VO__HUGO__CH12__RTC__605_ESCORT__160__M__1": "Onu görmeye gitmeliyiz. Uzun zaman oldu.",
"VO__HUGO__CH12__RTC__605_ESCORT__205__M__1": "Evet... dikkatli ol.",
"VO__HUGO__CH12__RTC__610_A_BANQUET__010__M__1": "Anneciğim!",
"VO__HUGO__CH12__RTC__610_A_BANQUET__120__M__1": "Benim gibi başka bir Taşıyıcı varmış!",
"VO__HUGO__CH12__RTC__610_A_BANQUET__176__M__1": "Ama onun suçu değildi! Sadece yapayalnız ve korkmuştu!",
"VO__HUGO__CH12__RTC__610_A_BANQUET__224__M__1": "Evet...",
"VO__HUGO__CH12__RTC__610_A_BANQUET__230__M__1": "Kocaman ve uzun olacağız!",
"VO__HUGO__CH12__RTC__651_HUGOSROOM__010__M__1": "Amicia? Anneciğim?",
"VO__HUGO__CH12__RTC__651_HUGOSROOM__020__M__1": "Tuhaf hissediyorum...",
"VO__HUGO__CH12__RTC__660_NOW_THEY_DIE__020__M__1": "Ne yapıyorsun?",
"VO__HUGO__CH12__RTC__660_NOW_THEY_DIE__044__M__1": "A... Anne?",
"VO__HUGO__CH12__RTC__660_NOW_THEY_DIE__050__M__1": "Onu öldürdün...",
"VO__ISLANDER_M1__CH12__CHATTER__BRIEFING__020__M__1": "Ya... ya sıçanlar saraya girerse?",
"VO__ISLANDER_M1__CH12__CHATTER__HOSPITAL__030__M__1": "Kolum... yanıyor...",
"VO__ISLANDER_M1__CH12__CHATTER__PREACH__030__M__1": "Neden bizi öldürüyor O?!",
"VO__ISLANDER_M1__CH12__CHATTER__REFUGEES__010__M__1": "Bunlar freskteki sıçanlar, diyorum size!",
"VO__ISLANDER_M2__CH12__CHATTER__PREACH__040__M__1": "Yüreklerinizi yatıştırın! O'na dua edin. Sadece dua edin.",
"VO__LUCAS__CH12__CHATTER__CONTROL_LOST__015__M__1": "Hugo! Dur!",
"VO__LUCAS__CH12__CHATTER__FIRST_STRIKES__050__M__1": "Vay! Ne?! O da ne?!",
"VO__LUCAS__CH12__CHATTER__LOSING_CONTROL__030__M__1": "Durun! Kontrolünü kaybedecek!",
"VO__LUCAS__CH12__CHATTER__SECOND_STRIKES__070__M__1": "Dayanamayacak, Amicia!",
"VO__LUCAS__CH12__CHATTER__SECOND_WAVE__060__M__1": "Çok yakın... Fazlasıyla yakınlar!",
"VO__LUCAS__CH12__RTC__610_A_BANQUET__010__M__1": "Buradasın!",
"VO__LUCAS__CH12__RTC__610_A_BANQUET__110__M__1": "Rüyandaki mi?",
"VO__LUCAS__CH12__RTC__610_A_BANQUET__140__M__1": "Başka bir Taşıyıcı...",
"VO__LUCAS__CH12__RTC__610_A_BANQUET__160__M__1": "Yeni bir veba... altıncı yüzyılda, yani...",
"VO__LUCAS__CH12__RTC__630_THE_BALLROOM__055__M__1": "İçeri! Hadi! Koşun!",
"VO__LUCAS__CH12__RTC__660_NOW_THEY_DIE__035__M__1": "Hayır... Hugo...",
"VO__LUCAS__CH12__RTC__670_ANGER__010__M__1": "Amicia!...",
"VO__LUCAS__CH12__RTC__670_ANGER__020__M__1": "Amicia, neredesin?!",
"VO__PEOPLE_F1__CH12__CHATTER__COUNT_ENTERS__050__M__1": "Hı, şu dolabın arkasında!",
"VO__PEOPLE_F1__CH12__CHATTER__KITCHEN_SERVANT__020__M__1": "Sen kimsin?!",
"VO__PEOPLE_F1__CH12__CHATTER__PRAYING__005__M__1": "Size yalvarırım, kardeşlerim! Korkmayın! Sıçanlar, Köz Çocuğu'nun habercileridir! Yakında bize geri dönecek!",
"VO__PEOPLE_F1__CH12__CHATTER__REFUGEES__020__M__1": "Yani Çocuk geliyor mu demek bu?",
"VO__PEOPLE_F1__CH12__CHATTER__SOUP__015__M__1": "Çok değil, ama erzakımıza dikkat etmeliyiz.",
"VO__PEOPLE_F2__CH12__CHATTER__GATE_CART__020__M__1": "Peki ya eşyalarım?!",
"VO__PEOPLE_F2__CH12__CHATTER__GATE_CART__040__M__1": "Pekâlâ, anlıyorum. Bol şans.",
"VO__PEOPLE_F2__CH12__CHATTER__HOSPITAL_BED__010__M__1": "Hayır... O ölmedi... Ölmüş olamaz!",
"VO__PEOPLE_F2__CH12__CHATTER__HOSPITAL_BED__030__M__1": "Hayır... hayır!",
"VO__PEOPLE_F3__CH12__CHATTER__SOUP__010__M__1": "Bu yemek için Kont'a şükürler olsun...",
"VO__PEOPLE_F4__CH12__CHATTER__KITCHEN_SERVANT__010__M__1": "Hey! Neler oluyor?!",
"VO__PEOPLE_F4__CH12__CHATTER__PREACH__020__M__1": "Sıçanlar gerçekten O'nun gelişini mi müjdeliyor?",
"VO__PEOPLE_F4__CH12__CHATTER__SOUP_GO__010__M__1": "Pardon, ama sıraya geri dönmelisiniz.",
"VO__PEOPLE_M2__CH12__CHATTER__PREACH__010__M__1": "Bu, Çocuğun bize gönderdiği bir sınavdan başka bir şey değil. İnancınızı yitirmemelisiniz.",
"VO__PEOPLE_M3__CH12__CHATTER__HOSPITAL_BED__020__M__1": "Bitti... Bırak gitsin.",
"VO__PEOPLE_M3__CH12__CHATTER__HOSPITAL_BED__040__M__1": "Kendine gel! Daha çok yaralı geliyor!",
"VO__PEOPLE_M3__CH12__CHATTER__KITCHEN_OUT__010__M__1": "Hey! Neler oluyor?!",
"VO__PEOPLE_M3__CH12__CHATTER__KITCHEN_OUT__030__M__1": "Hayır! İzinsiz giriyorsun!",
"VO__PEOPLE_M3__CH12__CHATTER__REFUGEES__030__M__1": "Çocuğun bizi aydınlık günlere götürmesi gerekiyordu! Bu katliama değil!",
"VO__PEOPLE_M4__CH12__CHATTER__SOUP__020__M__1": "Dua edelim de bu kâbus yakında bitsin...",
"VO__PEOPLE_M5__CH12__CHATTER__DEFENSES__010__M__1": "Gel şuna bir el at!",
"VO__PEOPLE_M5__CH12__CHATTER__MORE_WOOD2__010__M__1": "Burada biraz yardım lazım!",
"VO__PEOPLE_M5__CH12__CHATTER__PREACH__005__M__1": "Bu, Çocuğun bize gönderdiği bir sınavdan başka bir şey değil. İnancınızı yitirmemelisiniz.",
"VO__PEOPLE_M5__CH12__CHATTER__PREACH__035__M__1": "Yüreklerinizi yatıştırın! O'na dua edin. Sadece dua edin.",
"VO__SOLDIER_B1__CH12__CHATTER__BATTLE_PLAN__010__M__1": "Burada bekleyin.",
"VO__SOLDIER_B1__CH12__CHATTER__BATTLE_PLAN__060__M__1": "Efendim... O geldi.",
"VO__SOLDIER_B1__CH12__CHATTER__ESCORT__010__M__1": "Beni takip edin...",
"VO__SOLDIER_B1__CH12__CHATTER__ESCORT__020__M__1": "Kont'u bekletmemek en iyisi. Gelin.",
"VO__SOLDIER_B1__CH12__CHATTER__ESCORT__030__M__1": "Etrafta dolaşmanın zamanı değil. Beni takip edin.",
"VO__SOLDIER_B1__CH12__CHATTER__ESCORT__050__M__1": "Hayır.",
"VO__SOLDIER_B1__CH12__CHATTER__ESCORT__070__M__1": "Sizi görmek istemesi acil bir mesele olmalı. Huzurunda saygınlıkla davranın. Karanlık zamanlar bunlar. Hepimiz gibi onun da yarası var.",
"VO__SOLDIER_B1__CH12__CHATTER__GARDEN__010__M__1": "Tüm yan girişler kilitli. Ana kapıyı kullanın.",
"VO__SOLDIER_B1__CH12__CHATTER__MOTHER__025__M__1": "Kontesi ne pahasına olursa olsun koruyun!",
"VO__SOLDIER_B1__CH12__CHATTER__WAITING_1__010__M__1": "Leydi! Kont sizi bekliyor!",
"VO__SOLDIER_B1__CH12__CHATTER__WAITING_2__020__M__1": "Leydi... Kont'la görüşmeniz var!",
"VO__SOLDIER_B1__CH12__CHATTER__WAITING_3__030__M__1": "Biz sizi beklerken insanlar ölüyor!",
"VO__SOLDIER_B1__CH12__CHATTER__WALK_OUT__020__M__1": "Kont.",
"VO__SOLDIER_B1__CH12__RTC__610_A_BANQUET__233__M__1": "Böldüğüm için üzgünüm.",
"VO__SOLDIER_B1__CH12__RTC__610_A_BANQUET__236__M__1": "Kont sizi görmek istiyor.",
"VO__SOLDIER_B1__CH12__RTC__610_A_BANQUET__255__M__1": "O, Provence Kontu, leydim.",
"VO__SOLDIER_B2__CH12__CHATTER__BRIEFING__010__M__1": "Surlar boyunca hendekler kazın ve katranla doldurun! Yanık tutun onları! En küçük bir gedik sarayı düşürebilir!",
"VO__SOLDIER_B2__CH12__CHATTER__BRIEFING__030__M__1": "O zaman ölürsün. Yanık... tutun... onları!",
"VO__SOLDIER_B2__CH12__CHATTER__SOLDIERS_INCOMING_2__020__M__1": "Seni yakalayacağız, cadı!",
"VO__SOLDIER_N1__CH12__CHATTER__ANY_EVACUATION__020__M__1": "Henüz değil. Herkesi bir araya toplayana dek olmaz.",
"VO__SOLDIER_N1__CH12__CHATTER__BATTLE_PLAN__080__M__1": "Emredersiniz, efendim!",
"VO__SOLDIER_N1__CH12__CHATTER__CHARIOT_BUILT__030__M__1": "Başımdan git! Bu şey o kadar eski ki her an patlayabilir!",
"VO__SOLDIER_N1__CH12__CHATTER__DOOR__010__M__1": "Şuradan. Sağlıcakla.",
"VO__SOLDIER_N1__CH12__CHATTER__FIGHT_RATS__010__M__1": "Şimdilik... Kont kapıları halka açtı... ama o kadar çok ölü ve yaralı var ki...",
"VO__SOLDIER_N1__CH12__CHATTER__FIGHT_RATS_CHARIOT__030__M__1": "Bu çizginin içinde kaldığınız sürece güvendesiniz. Ama dışarıda, ışıksız...",
"VO__SOLDIER_N1__CH12__CHATTER__FIGHT_RATS_CHARIOT__070__M__1": "Her neyse, artık güvendesiniz.",
"VO__SOLDIER_N1__CH12__CHATTER__HOSPITAL__020__M__1": "Daha fazlası var...",
"VO__SOLDIER_N1__CH12__CHATTER__HOSPITAL_CONTINUE__010__M__1": "Lütfen acele edin, fazla vaktimiz yok!",
"VO__SOLDIER_N1__CH12__CHATTER__MORE_WOOD__020__M__1": "Hızlanın! Bu alevleri besleyin!",
"VO__SOLDIER_N1__CH12__CHATTER__RATS_CHARIOT__030__M__1": "Dikkat! Geri durun!",
"VO__SOLDIER_N1__CH12__CHATTER__REFUGEES_TALK__010__M__1": "Sessizlik! Tartışmanın zamanı değil!",
"VO__SOLDIER_N1__CH12__CHATTER__SECOND_WAVE__040__M__1": "Şu lanet kızı öldürün! Ne pahasına olursa olsun!",
"VO__SOLDIER_N1__CH12__CHATTER__STAIRS__010__M__1": "Yukarıda yaralılarımız var, hoş bir manzara değil. Çocuk... başka tarafa baksa iyi olur.",
"VO__SOLDIER_N2__CH12__CHATTER__BATTLE_PLAN__083__M__1": "Emredersiniz, efendim!",
"VO__SOLDIER_N2__CH12__CHATTER__FIGHT_RATS_WOOD__020__M__1": "Askerler! Yorgun olduğunuzu biliyorum, ama devam edin!",
"VO__SOLDIER_N2__CH12__CHATTER__GATE_CART__010__M__1": "Araba burada kalır, leydi. Yaralıları taşımak için lazım olacak.",
"VO__SOLDIER_N2__CH12__CHATTER__GATE_CART__030__M__1": "Onları içeri getirebilirsiniz.",
"VO__SOLDIER_N2__CH12__CHATTER__RATS_CHARIOT__020__M__1": "Geliyorlar! Rum ateşi, çabuk!",
"VO__SOLDIER_N2__CH12__CHATTER__SOLDIERS_INCOMING_1__010__M__1": "Burada daha çok adam lazım!",
"VO__SOLDIER_N3__CH12__CHATTER__BACKGROUND_NOISE__010__M__1": "Acele edin! Onlar dönmeden kımıldayın!",
"VO__SOLDIER_N3__CH12__CHATTER__BACKGROUND_NOISE__030__M__1": "Mevzilerinize geçin!",
"VO__SOLDIER_N3__CH12__CHATTER__BATTLE_PLAN__086__M__1": "Emredersiniz, efendim.",
"VO__SOLDIER_S1__CH12__CHATTER__BACKGROUND_NOISE__020__M__1": "Şu ateşleri yeniden yakın!",
"VO__SOLDIER_S1__CH12__CHATTER__BACKGROUND_NOISE__040__M__1": "Köprüye gidin! Hattı tutun!",
"VO__SOLDIER_S1__CH12__CHATTER__CHARIOT_BUILT__010__M__1": "Pistonu tamir ettin mi? Bu arabaya surlarda acilen ihtiyacımız var!",
"VO__SOLDIER_S1__CH12__CHATTER__DEFENSES__020__M__1": "Sıçanlar doğu kanadımıza yükleniyor! Oraya meşale lazım!",
"VO__SOLDIER_S1__CH12__CHATTER__FIGHT_RATS_WOOD__010__M__1": "Buraya daha çok odun!",
"VO__SOLDIER_S1__CH12__CHATTER__SOLDIERS_INCOMING_1__020__M__1": "Sarın onları! Aydınlık Günler için!",
"VO__SOLDIER_S1__CH12__RTC__605_ESCORT__030__M__1": "Hey! Leydim!",
"VO__SOLDIER_S1__CH12__RTC__605_ESCORT__050__M__1": "Kontesin misafiri sizsiniz, değil mi? Yaralı mısınız?",
"VO__SOLDIER_S1__CH12__RTC__605_ESCORT__070__M__1": "Sizi saraya güvenle ulaştırma emri aldık.",
"VO__SOLDIER_S1__CH12__RTC__605_ESCORT__090__M__1": "Sizin... misafirleriniz var.",
"VO__SOLDIER_S1__CH12__RTC__605_ESCORT__110__M__1": "Anneniz ve bir oğlan.",
"VO__SOLDIER_S1__CH12__RTC__660_NOW_THEY_DIE__075__M__1": "Efendim! Burada kalamayız. Onu içeriden alırız!",
"VO__SOLDIER_S1__CH12__RTC__665_DEVOURED__020__M__1": "Efendim!",
"VO__SOLDIER_S1__CH12__RTC__665_DEVOURED__040__M__1": "Efendim! Tahliye etmeliyiz, efendim! Çok geç!",
"VO__SOLDIER_S1__CH12__RTC__665_DEVOURED__050__M__1": "Efendim, halkınızın size ihtiyacı var! Efendim!",
"VO__SOLDIER_S2__CH12__CHATTER__DEFENSES__040__M__1": "Savaşmayan herkes içeri! Yolu açın!",
"VO__SOLDIER_S2__CH12__CHATTER__MORE_WOOD__010__M__1": "Ana yolda daha çok ateş lazım!",
"VO__SOPHIA__CH12__CHATTER__RAT_EXPLANATION__021__M__1": "Bu kayalıktan ayrılmak için sabırsızlanıyorum...",
"VO__SOPHIA__CH12__CHATTER__RATS_SHOO__010__M__1": "Limana ulaşmak... epey çetin olacak.",
"VO__SOPHIA__CH12__HELPER__TORCH_HELPER_1__010__M__1": "Ateş olmadan geçemeyiz...",
"VO__SOPHIA__CH12__HELPER__TORCH_HELPER_2__010__M__1": "Geçmek için şu meşaleyi kullansak nasıl olur?",
"VO__SOPHIA__CH12__RTC__600_TO_THE_PALACE__010__M__1": "İşler düzelmiyor...",
"VO__SOPHIA__CH12__RTC__600_TO_THE_PALACE__015__M__1": "Yine de şu yaratıkları çözmüş gibi görünüyorlar...",
"VO__SOPHIA__CH12__RTC__605_ESCORT__040__M__1": "Şimdi ne oldu?...",
"VO__SOPHIA__CH12__RTC__605_ESCORT__180__M__1": "Vay, şu hâlinize bakın... İnsanın üzerinde ancak bir anne böyle bir güce sahip olabilir... Pekâlâ, bakın ne diyeceğim? Ben limana gidip tekneyi hazırlayayım. Siz de en kısa zamanda bana katılın.",
"VO__SOPHIA__CH12__RTC__605_ESCORT__210__M__1": "Merak etme, ikinizden de öğrendim!",
}
