# -*- coding: utf-8 -*-
# CH02 VO bolum 2/2 (satir 721-1052). onom/EMPTY atlanir.
# Saticilar/tellal->Amicia=siz (kibar); muhafiz->Amicia=resmi; tutsaklar=yalvaran.
T = {
"VO__LUCAS__CH02__CHATTER__CAGES_LODGE__020__M__1": "Kafesler... İçlerinde başka hayvanlar vardı.",
"VO__LUCAS__CH02__CHATTER__CANCEL_LUCAS_NOTREADY__010__M__1": "Sorun değil, ben burada kalırım. Sen gidip diğerini idare edebilirsin.",
"VO__LUCAS__CH02__CHATTER__CANT_LIGHT_BRASIER__010__M__1": "Burada ışık lazım!",
"VO__LUCAS__CH02__CHATTER__CART_SPOT__020__M__1": "Sana el atayım.",
"VO__LUCAS__CH02__CHATTER__CATCH_FLAM_STICK__010__M__1": "Sağ ol ama... Yanmayan bir tane lazım! Daha güvenli olur!",
"VO__LUCAS__CH02__CHATTER__CENTRAL_LIFT_CRANK__010__M__1": "Kranklarımız işte: yukarıda, kemerlerin altında!",
"VO__LUCAS__CH02__CHATTER__CHASE_BURST__020__M__1": "İşimiz bitti...",
"VO__LUCAS__CH02__CHATTER__CHASE_DOOR__005__M__1": "Gel! Çabuk!",
"VO__LUCAS__CH02__CHATTER__CHASE_DOOR__020__M__1": "Yardım et!",
"VO__LUCAS__CH02__CHATTER__CHEST_SPOT_SMITHY__020__M__1": "Evet! Şu kalaslara biraz dökülmüş. Yukarıdaki sandıkta daha fazlası olabilir! Taze kükürt mükemmel olur!",
"VO__LUCAS__CH02__CHATTER__CLIMB_QUICK__010__M__1": "Ee? Şunu duyuyor musun? Fren kırılıyor olabilir!",
"VO__LUCAS__CH02__CHATTER__CRANK_DROP_INCOMPLETE__020__M__1": "Ne oldu?",
"VO__LUCAS__CH02__CHATTER__CRANK_USE_ALONE__025__M__1": "Yapamıyorum...",
"VO__LUCAS__CH02__CHATTER__CRANK_USE_ALONE__040__M__1": "Diğer taraftaki krank bunun için işte! İki kişi lazım!",
"VO__LUCAS__CH02__CHATTER__CRANK_USE_ALONE__070__M__1": "İşaretini bekleyeceğim!",
"VO__LUCAS__CH02__CHATTER__CROSSING_RATS_TORCH__020__M__1": "Milyonlarcası var!",
"VO__LUCAS__CH02__CHATTER__CROSSING_RATS_TORCH__030__M__1": "Nasıl?! Şimdiden nasıl bu kadar çok olabilir?!",
"VO__LUCAS__CH02__CHATTER__DEAD_FAMILY__010__M__1": "Ha... Ben... buna alışamıyorum...",
"VO__LUCAS__CH02__CHATTER__DYING_WOMAN__070__M__1": "İyi yaptın...",
"VO__LUCAS__CH02__CHATTER__ELEPHANT_REMAINS__020__M__1": "Bunu okumuştum... Bir fil! Afrika'dan! Romalılar bunları sirk oyunlarında kullanırdı!",
"VO__LUCAS__CH02__CHATTER__ELEPHANT_REMAINS__040__M__1": "Bu... gerçeküstü.",
"VO__LUCAS__CH02__CHATTER__ELEVATOR_LEVER__010__M__1": "Bir krank...",
"VO__LUCAS__CH02__CHATTER__ELVATR_CART__010__M__1": "Hı... İşaretinle.",
"VO__LUCAS__CH02__CHATTER__ELVATR_CRANK_USE__010__M__1": "İyi misin?",
"VO__LUCAS__CH02__CHATTER__ELVATR_CRANK_USE__020__M__1": "Yardım edeyim mi?",
"VO__LUCAS__CH02__CHATTER__ELVATR_POSITIONING__020__M__1": "Kule o kadar uzak değil! Vaudin'i bulur bulmaz, o...",
"VO__LUCAS__CH02__CHATTER__ELVATR_POSITIONING__040__M__1": "Hey! Tek seferde bir şey!",
"VO__LUCAS__CH02__CHATTER__ELVATR_WITH_AMICIA__020__M__1": "O kadar ağır değilsin.",
"VO__LUCAS__CH02__CHATTER__ENTER_ENCOUNTER__020__M__1": "Bak, şurada... Bir sembol daha!",
"VO__LUCAS__CH02__CHATTER__ENTER_ENCOUNTER__040__M__1": "Saldırı izine rastlamadım...",
"VO__LUCAS__CH02__CHATTER__ENTER_STOCKS__020__M__1": "Koruyucu bir madde lazım, mesela... alkol... Belki şu sandıkta vardır!",
"VO__LUCAS__CH02__CHATTER__FIRST_HAM_SHOOT__010__M__1": "Güzel. Ama yeterli olmayacak.",
"VO__LUCAS__CH02__CHATTER__FIRST_KILL__010__M__1": "Bundan emin misin?",
"VO__LUCAS__CH02__CHATTER__FLOWER_NO_LEAVE__010__M__1": "Amicia, gelip bunu görmelisin. Bence hoşuna gidecek.",
"VO__LUCAS__CH02__CHATTER__FOUND_HIM_2__010__M__1": "Burada.",
"VO__LUCAS__CH02__CHATTER__GATE_PASS_1__010__M__1": "Hı... Ah... Bu da ne be?!",
"VO__LUCAS__CH02__CHATTER__HAM_SHOOT__009__M__1": "Güvenli görünüyor!",
"VO__LUCAS__CH02__CHATTER__HAM_SHOOT__020__M__1": "Hâlâ bir milyon yıldır yememiş gibi görünüyorlar.",
"VO__LUCAS__CH02__CHATTER__HIDDEN_HELPER__011__M__1": "Ne yapacağız?",
"VO__LUCAS__CH02__CHATTER__HOUSE_FINAL_LUCAS__010__M__1": "İçeri girmeye hazır mısın?",
"VO__LUCAS__CH02__CHATTER__HOUSE_LUCASCHAT__010__M__1": "Evet... Yuva... Bu kelimeyi söylemeyeli epey oldu.",
"VO__LUCAS__CH02__CHATTER__HUNGRY_PIGGY__020__M__1": "Buradan çıkmalıyız...",
"VO__LUCAS__CH02__CHATTER__IDLE_BODIES__030__M__1": "Böyle tıklım tıklım, kilitli bir yerde... Isırık muhtemelen hepsini götürdü.",
"VO__LUCAS__CH02__CHATTER__IDLE_CROPS__010__M__1": "Ekinleri bile vardı...",
"VO__LUCAS__CH02__CHATTER__IDLE_CROPS__030__M__1": "Hep aynı hikâye...",
"VO__LUCAS__CH02__CHATTER__IDLE_ENCNTR_GROUND_1__020__M__1": "Dikkatli ol yoksa zaten ölürüz...",
"VO__LUCAS__CH02__CHATTER__IDLE_ENCNTR_GROUND_2__010__M__1": "Bu inanılmaz...",
"VO__LUCAS__CH02__CHATTER__IDLE_ENCNTR_GROUND_2__030__M__1": "Bilmiyorum. Gün ışığı onları yavaşlatır, ama...",
"VO__LUCAS__CH02__CHATTER__IDLE_ENCNTR_GROUND_2__050__M__1": "Çıkacaklar, kesinlikle.",
"VO__LUCAS__CH02__CHATTER__IDLE_ENCOUNTER_2__020__M__1": "O halleder. Güçlüdür.",
"VO__LUCAS__CH02__CHATTER__IGNI_NO_POT__010__M__1": "Dur! Etrafta kil çömlekler var... Birini al! Bir Ignifer'in etkisini yoğunlaştırıp çarpma anında salabilir!",
"VO__LUCAS__CH02__CHATTER__IGNI_POT_READY__020__M__1": "Kısa bir ateş çıkarmak için at onu! Bizi karşıya geçirir, ama hızlı olmalıyız!",
"VO__LUCAS__CH02__CHATTER__IGNI_POT_THROW__020__M__1": "Evet! Kımılda!",
"VO__LUCAS__CH02__CHATTER__IGNI_SUCCESS__020__M__1": "Epey kolay... Sadece bir çömlek lazım.",
"VO__LUCAS__CH02__CHATTER__IGNI_WITH_POT__010__M__1": "Elindeki o kil çömlek... bir Ignifer'in etkisini yoğunlaştırıp çarpma anında salabilir! Hadi, dene!",
"VO__LUCAS__CH02__CHATTER__IGNI_WRONG_THROW__010__M__1": "Onu şu farelere at Amicia! Arkadaki ateşe ulaşmamız lazım!",
"VO__LUCAS__CH02__CHATTER__IGNIFER_CRAFT__010__M__1": "Güzel. Kükürt ve alkol var. Bir Ignifer için en iyi temellerden biri. Çok tepkin. Onları karıştır!",
"VO__LUCAS__CH02__CHATTER__IGNIFER_CRAFT__030__M__1": "Hayat kurtarır.",
"VO__LUCAS__CH02__CHATTER__IGNIFER_DONE__020__M__1": "Onu sapanınla şu korlara at, ve... işe yaramasını um...",
"VO__LUCAS__CH02__CHATTER__IGNIFER_USE__020__M__1": "Vay!",
"VO__LUCAS__CH02__CHATTER__IGNIFER_USE__040__M__1": "Gerçekten ÇOK tepkinmiş...",
"VO__LUCAS__CH02__CHATTER__IGNIFER_USE__070__M__1": "Sanırım etrafta başka kranklar gördüm.",
"VO__LUCAS__CH02__CHATTER__INTERACT_LIFT__020__M__1": "Tabii.",
"VO__LUCAS__CH02__CHATTER__INTRCT_CHEST_STOCKS__020__M__1": "Evet! İşte bu! Çok iyi! Geri gel!",
"VO__LUCAS__CH02__CHATTER__INTRCT_LIFT__020__M__1": "İnanamıyorum!",
"VO__LUCAS__CH02__CHATTER__INVEST_DOWN_WHERETO__020__M__1": "Sanırım sadece tedbirli davranıyor. Düzen böyle çalışır.",
"VO__LUCAS__CH02__CHATTER__INVEST_GUARD__010__M__1": "Merhaba, affedersiniz, Magister Vaudin'in nerede olduğunu biliyor musunuz?",
"VO__LUCAS__CH02__CHATTER__INVEST_GUARD__030__M__1": "Teşekkürler...",
"VO__LUCAS__CH02__CHATTER__INVEST_GUARD_INTRO__010__M__1": "İşte, bir kasaba muhafızı. Ona sorayım.",
"VO__LUCAS__CH02__CHATTER__INVEST_GUARD_OUTRO__020__M__1": "Bilmeliydim... Tabii ki Düzen'deki unvanıyla açıkça dolaşmaz!",
"VO__LUCAS__CH02__CHATTER__INVEST_HERBORIST_GUARDHELP__030__M__1": "Teşekkürler.",
"VO__LUCAS__CH02__CHATTER__INVEST_HERBORIST_IDEA__020__M__1": "Bu çiçekçinin nerede olduğunu hatırladığından emin misin?",
"VO__LUCAS__CH02__CHATTER__INVEST_HERBORISTHUSB_CHAT__010__M__1": "Merhaba efendim... Karınız bizi gönderdi.",
"VO__LUCAS__CH02__CHATTER__INVEST_HERBORISTHUSB_CHAT__030__M__1": "Merak etmeyin. Teşekkürler.",
"VO__LUCAS__CH02__CHATTER__INVEST_OUTSIDE_DOUBT__010__M__1": "Kanında olanları denetleyemezsin. Macula gelişmeye devam ediyor, Taşıyıcı'yı farklı eşiklerden geçiriyor...",
"VO__LUCAS__CH02__CHATTER__INVEST_OUTSIDE_DOUBT__030__M__1": "Düzen yüzyıllardır Macula'yı inceliyor. Onlar yapamazsa, kim yapar bilmiyorum.",
"VO__LUCAS__CH02__CHATTER__INVEST_OUTSIDE_INTRO__020__M__1": "Senin suçun değil.",
"VO__LUCAS__CH02__CHATTER__INVEST_SLUMS_DANGER_OUTRO__020__M__1": "Saklanıyordur belki?",
"VO__LUCAS__CH02__CHATTER__INVEST_SLUMS_GUARDS__041__M__1": "Sorun değil, gel! Arenanın etrafından dolaşırız.",
"VO__LUCAS__CH02__CHATTER__INVEST_SLUMS_INTRO__020__M__1": "Ne çok ev var...",
"VO__LUCAS__CH02__CHATTER__INVEST_SLUMS_SYMBOL__010__M__1": "Amicia... Duvardaki şu sembol!",
"VO__LUCAS__CH02__CHATTER__INVEST_SLUMS_SYMBOL__030__M__1": "Evet! Burada!",
"VO__LUCAS__CH02__CHATTER__INVEST_SLUMS_UP__020__M__1": "Eee, kanunu çiğnemeye hazır mısın?",
"VO__LUCAS__CH02__CHATTER__INVEST_SLUMS_UP_HELPER__050__M__1": "Yukarıda bir kapı var...",
"VO__LUCAS__CH02__CHATTER__INVEST_SLUMS_WALKINGDOWN__020__M__1": "Şimdi askerlerle tartışmanın sırası değil. Etrafa bakalım.",
"VO__LUCAS__CH02__CHATTER__JAR_LODGE__010__M__1": "Vay, ne çok antika küp var!",
"VO__LUCAS__CH02__CHATTER__JAR_LODGE__030__M__1": "Evet. Bazı şeyler hiç değişmiyor.",
"VO__LUCAS__CH02__CHATTER__KILL__012__M__1": "Şimdi ne olacak?",
"VO__LUCAS__CH02__CHATTER__KILL__061__M__1": "İyi değil...",
"VO__LUCAS__CH02__CHATTER__KNIFE_GRAB__060__M__1": "İnsanlara karşı... bıçak... kullanılmaz.",
"VO__LUCAS__CH02__CHATTER__KNIFE_GRAB__080__M__1": "Pekâlâ. Sana kalmış.",
"VO__LUCAS__CH02__CHATTER__LADDER_TO_CHEST__020__M__1": "İnsanlar onun pek umursamadığını düşünüyor. Ordusu onun yerine hükmediyor.",
"VO__LUCAS__CH02__CHATTER__LADDER_TO_CHEST__040__M__1": "Burayı güvenli sanmıştık...",
"VO__LUCAS__CH02__CHATTER__LEAVE__010__M__1": "İşte! Bir sembol daha!",
"VO__LUCAS__CH02__CHATTER__LEDGE_INTERACT__020__M__1": "Düşme...",
"VO__LUCAS__CH02__CHATTER__LET_GO_CRANKS__020__M__1": "Senin sözünle!",
"VO__LUCAS__CH02__CHATTER__LIFT_UP__006__M__1": "Sakin...",
"VO__LUCAS__CH02__CHATTER__LIFT_UP__020__M__1": "Olağanüstü beceri ve dayanıklılıkla...",
"VO__LUCAS__CH02__CHATTER__LIFT_UP__040__M__1": "Görüyorum... Ama bunu daha önce de yaşadık...",
"VO__LUCAS__CH02__CHATTER__LIFT_UP__060__M__1": "Ama başardık!",
"VO__LUCAS__CH02__CHATTER__LIFT_UP__080__M__1": "Hadi Magister Vaudin'i bulalım! Düzen yanımızdayken bununla artık tek başımıza yüzleşmek zorunda kalmayacağız!",
"VO__LUCAS__CH02__CHATTER__LIGHT_BRASIER_THROW_OK__020__M__1": "Teşekkürler!... Sana katılmaya çalışacağım!",
"VO__LUCAS__CH02__CHATTER__LUCAS_CALLING__010__M__1": "Hey!",
"VO__LUCAS__CH02__CHATTER__LUCAS_CALLING__020__M__1": "Geri döndün!",
"VO__LUCAS__CH02__CHATTER__LUCAS_DOOR__010__M__1": "Kapımız bu!",
"VO__LUCAS__CH02__CHATTER__LUCAS_WELCOME__020__M__1": "Eee, nasıldı?",
"VO__LUCAS__CH02__CHATTER__LUCAS_WELCOME__050__M__1": "Tabii! Biraz taze ot lazım.",
"VO__LUCAS__CH02__CHATTER__OPEN_CHEST__010__M__1": "Eee? Bir şey buldun mu?",
"VO__LUCAS__CH02__CHATTER__OPEN_CHEST__030__M__1": "Evet! İşte bu çok güzel bir haber!",
"VO__LUCAS__CH02__CHATTER__PORTCULLIS_RATS__010__M__1": "Eyvah! Lütfen OLMASIN!",
"VO__LUCAS__CH02__CHATTER__PORTCULLIS_RATS__030__M__1": "Hayır... Hayır... Platforma bak... Mangal! Bütün odayı aydınlatacak kadar büyük görünüyor!",
"VO__LUCAS__CH02__CHATTER__PORTCULLIS_RATS__050__M__1": "Bilmiyorum... güherçile, kükürt, alkol... ne bulabilirsek!",
"VO__LUCAS__CH02__CHATTER__PUSH_PULL_IDEA__009__M__1": "Evet... Bak, yukarıda bir açıklık.",
"VO__LUCAS__CH02__CHATTER__PUSH_PULL_VAUDIN__020__M__1": "Isırığı biliyor. Hastalardan kaçınıyor olmalı.",
"VO__LUCAS__CH02__CHATTER__PUSH_PULL_VAUDIN__040__M__1": "Belki değil... Hasta biri onu şehrin içine sokmuş olabilir...",
"VO__LUCAS__CH02__CHATTER__REACH_CHEST_STOCKS__010__M__1": "Eee? İçinde ne var?",
"VO__LUCAS__CH02__CHATTER__REACH_FOUNTAIN__020__M__1": "Kahverengi tunik. O işte, süpürgeli olan!",
"VO__LUCAS__CH02__CHATTER__RUN__004__M__1": "Bilmiyorum! Çok karanlık!",
"VO__LUCAS__CH02__CHATTER__SECOND_ELEMENT__010__M__1": "Pekâlâ! İkinci bir bileşen lazım! Sonra bir Ignifer üretiriz! Hatırlıyor musun?",
"VO__LUCAS__CH02__CHATTER__SHELTER_GATE__020__M__1": "Belki kimsenin umurunda değildir.",
"VO__LUCAS__CH02__CHATTER__SHELTER_INTRO__010__M__1": "Onları burada çürümeye terk ettiklerine inanamıyorum.",
"VO__LUCAS__CH02__CHATTER__SHELTER_INTRO__030__M__1": "Dışarıdaki gecekondudan olmalılar.",
"VO__LUCAS__CH02__CHATTER__SKILL_TUTO_INTRO__010__M__1": "Evet! Başardık!",
"VO__LUCAS__CH02__CHATTER__SKILL_TUTO_INTRO__030__M__1": "Hayatımıza kaos hükmediyor... onlar da bunun bir parçası. Ve onlarla başa çıkmakta daha iyi oluyorsun... Görüyorum.",
"VO__LUCAS__CH02__CHATTER__STAIRS_BOTTOM__010__M__1": "Fare yok mu?",
"VO__LUCAS__CH02__CHATTER__STAIRS_BOTTOM__050__M__1": "Taze...",
"VO__LUCAS__CH02__CHATTER__STOCK_LODGE_CLOSED__010__M__1": "Bir kulübe... Bir... et kokusu mu alıyorum?",
"VO__LUCAS__CH02__CHATTER__SULFUR_SMELL_LODGE__009__M__1": "Bunu biliyorum...",
"VO__LUCAS__CH02__CHATTER__SULFUR_SMELL_LODGE__010__M__1": "Bu... kükürt! Bir demirci!",
"VO__LUCAS__CH02__CHATTER__SUNLIGHT__010__M__1": "Ben... bir nefes almam lazım...",
"VO__LUCAS__CH02__CHATTER__TAKE_TORCH__010__M__1": "Meşaleyi sana bırakayım, ben... Korkarım düşürürüm...",
"VO__LUCAS__CH02__CHATTER__TO_2ND_CRANK__020__M__1": "İşte bu Amicia!",
"VO__LUCAS__CH02__CHATTER__TO_2ND_CRANK__040__M__1": "Biri bana kendi sirk oyunlarımızın olacağını söyleseydi...",
"VO__LUCAS__CH02__CHATTER__TO_HUSBAND__010__M__1": "Umarım bize söyler...",
"VO__LUCAS__CH02__CHATTER__TOP_OF_STAIRS__020__M__1": "Biraz yaklaştık, değil mi?",
"VO__LUCAS__CH02__CHATTER__USING_LIFT_LEVER__010__M__1": "Hı... Vay...",
"VO__LUCAS__CH02__CHATTER__USING_LIFT_WRONG__020__M__1": "Evet. Hadi sonuna kadar getirelim!",
"VO__LUCAS__CH02__CHATTER__WAITING_FOR_HER__020__M__1": "Tutuyorum!",
"VO__LUCAS__CH02__HELPER__BANDIT_ALONE_DISTRACT_1__010__M__1": "Onun başka tarafa bakmasını sağlamamız gerekecek.",
"VO__LUCAS__CH02__HELPER__BANDIT_ALONE_DISTRACT_2__010__M__1": "Şu sandığa bir taş atmayı dene...",
"VO__LUCAS__CH02__HELPER__BRASEROLIGHTUP_BASE_ROOM2_1__010__M__1": "Bu mangalı indirmemiz gerek...",
"VO__LUCAS__CH02__HELPER__BRASEROLIGHTUP_BASE_ROOM2_2__010__M__1": "Şu kilidi kırmak için sapanını kullansan?",
"VO__LUCAS__CH02__HELPER__CART_POSITIONING_SMITHY_1__010__M__1": "Şu sandığa ulaşmak için bir şeye tırmanmamız gerek...",
"VO__LUCAS__CH02__HELPER__CART_POSITIONING_SMITHY_2__010__M__1": "Şu arabayı getirirsek belki oraya tırmanabilirsin.",
"VO__LUCAS__CH02__HELPER__FLOWER_ARENA_1__010__M__1": "Amicia! Bunu görmelisin!",
"VO__LUCAS__CH02__HELPER__FLOWER_ARENA_2__010__M__1": "Gel şuna bir bak!",
"VO__LUCAS__CH02__HELPER__HAM_SHOOT_STOCKS_1__010__M__1": "Şu fareleri ayartmanın bir yolunu bulmamız gerek...",
"VO__LUCAS__CH02__HELPER__HAM_SHOOT_STOCKS_2__010__M__1": "Amicia! Hadi onlara bunu yedirelim!",
"VO__LUCAS__CH02__HELPER__HAM_USE_CAGES_1_L__010__M__1": "Merdivenlere ulaşmak için fareleri uzaklaştırmamız gerek...",
"VO__LUCAS__CH02__HELPER__HAM_USE_CAGES_2_L__010__M__1": "Amicia! Onlara o eti verebileceğini düşünüyor musun?!",
"VO__LUCAS__CH02__HELPER__IGNIFER_REMINDER_1__010__M__1": "Amicia, mangalı yakmamız gerekecek.",
"VO__LUCAS__CH02__HELPER__IGNIFER_REMINDER_2__010__M__1": "Şu korlara bir Ignifer atabilir misin?",
"VO__LUCAS__CH02__HELPER__IGNIFER_USE_CAGES_1_L__010__M__1": "Şu farelerin arasından geçmek için ışık lazım...",
"VO__LUCAS__CH02__HELPER__IGNIFER_USE_CAGES_2_L__010__M__1": "Duvardaki şu meşaleyi yakmayı dene! Yeterli olabilir!",
"VO__LUCAS__CH02__HELPER__IGNIFER_USE_JARS_1_L__010__M__1": "Sanırım daha çok ışık lazım olacak...",
"VO__LUCAS__CH02__HELPER__IGNIFER_USE_JARS_2_L__010__M__1": "Yukarı bak! Şu mangalı vurup indirebilir misin?!",
"VO__LUCAS__CH02__HELPER__INTERACT_LIFT_LODGE_1__010__M__1": "Bu krank ne yapıyor acaba...",
"VO__LUCAS__CH02__HELPER__INTERACT_LIFT_LODGE_2__010__M__1": "Hadi kranı kullanalım Amicia.",
"VO__LUCAS__CH02__HELPER__LIT_STICK_NEED_BASE_1__010__M__1": "Benim tarafımda bir mangal var! Onu yakabilir misin?",
"VO__LUCAS__CH02__HELPER__LIT_STICK_NEED_BASE_2__010__M__1": "Amicia! Şu mangala yanan bir çubuk atmayı dene!",
"VO__LUCAS__CH02__HELPER__PP_ARCADES_CART_1__010__M__1": "Belki şu kafesi indirebiliriz...",
"VO__LUCAS__CH02__HELPER__PP_ARCADES_CART_2__010__M__1": "Kafesi vurmayı dene belki... Onu tekrar şu tekerleklerin üstüne almamız lazım...",
"VO__LUCAS__CH02__HELPER__PP_INTRO_1__010__M__1": "Oraya çıkmak için bir şey lazım...",
"VO__LUCAS__CH02__HELPER__PP_INTRO_2__010__M__1": "Amicia! Tırmanmak için bu arabayı kımıldatabiliriz!",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_JUPITER_1__010__M__1": "Jüpiter'in sembolü Z'ye benzemeli. Zeus'taki gibi.",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_JUPITER_2__010__M__1": "Amicia, en soldaki Jüpiter'inki olmalı. Sembol Z'ye benziyor.",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_JUPITER_NO_1__010__M__1": "O Jüpiter için doğru sembol değil sanırım...",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_JUPITER_NO_2__010__M__1": "Jüpiter'in sembolü o değil...",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_MARS_1__010__M__1": "Unutma, Mars bir mızrakla çaprazlanmış bir kalkan olmalı.",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_MARS_2__010__M__1": "Mars, içinden bir çizgi geçen bir daireyle simgelenmeli.",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_MARS_NO_1__010__M__1": "O, Mars için yanlış işaret sanırım.",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_MARS_NO_2__010__M__1": "Mars'ın sembolü yanlış sanırım...",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_MERCURE_1__010__M__1": "Merkür'ün sembolünde iç içe geçmiş iki yılan olmalı.",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_MERCURE_2__010__M__1": "Merkür için üstünde iki yılan olan bir asaya benzeyen bir sembol bulmaya çalış.",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_MERCURE_NO_1__010__M__1": "Merkür'ün sembolü doğru değil...",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_MERCURE_NO_2__010__M__1": "Yanılmıyorsam Merkür'ün sembolü yanlış...",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_VENUS_1__010__M__1": "Venüs, aşağı inen bir çizgisi olan bir daireye karşılık gelir.",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_VENUS_2__010__M__1": "Venüs'ün sembolü O harfine benzemeli, ama altında dikey bir çizgiyle.",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_VENUS_NO_1__010__M__1": "Venüs'ün sembolü doğru değil sanırım...",
"VO__LUCAS__CH02__HELPER__PUZZLE_TOWER_VENUS_NO_2__010__M__1": "O, Venüs'ün sembolü değil...",
"VO__LUCAS__CH02__HELPER__STICK_NEED_BASE_1__010__M__1": "Amicia bana bir çubuk atmalısın!",
"VO__LUCAS__CH02__HELPER__STICK_NEED_BASE_2__010__M__1": "Karşıya geçmek için bir çubuk lazım!",
"VO__LUCAS__CH02__HELPER__TAKE_TORCH_ARCADES_1__010__M__1": "İlerlemek için ışık lazım...",
"VO__LUCAS__CH02__HELPER__TAKE_TORCH_ARCADES_2__010__M__1": "Farelerin arasından geçmemiz için meşaleyi al...",
"VO__LUCAS__CH02__ONOM__BASE_FALL_LUCASFALLS__010__M__1": "Ha!",
"VO__LUCAS__CH02__ONOM__ELVATR_CART_LET_GO__010__M__1": "Ha!",
"VO__LUCAS__CH02__RTC__060_ALIVELYTOWN__010__M__1": "İtiraf etmeliyim... burası çok güzel.",
"VO__LUCAS__CH02__RTC__060_ALIVELYTOWN__070__M__1": "Annenin laboratuvarını ve hatta Chateau d'Ombrage'ı bile onlar yaptı, hatırladın mı?",
"VO__LUCAS__CH02__RTC__070_TOTHEALCHEMIST__140__M__1": "Deniyorum, ama ben... mantığına takılıp kalıyorum.",
"VO__LUCAS__CH02__RTC__070_TOTHEALCHEMIST__160__M__1": "Belki de... ben insan olmakta pek iyi değilim.",
"VO__LUCAS__CH02__RTC__070_TOTHEALCHEMIST__185__M__1": "Amicia!... AMICIA!",
"VO__LUCAS__CH02__RTC__070_TOTHEALCHEMIST__220__M__1": "Şoktan... Bugün olanlar onu uyandırmış olmalı.",
"VO__LUCAS__CH02__RTC__090_ENTER_ARENA__020__M__1": "Isırık... Evet.",
"VO__LUCAS__CH02__RTC__090_ENTER_ARENA__030__M__1": "Arenayı kapatmışlar. Onları burada ölüme terk ettiler.",
"VO__LUCAS__CH02__RTC__090_ENTER_ARENA__045__M__1": "Başlamıyor... yayılıyor. Hugo...",
"VO__LUCAS__CH02__RTC__090_ENTER_ARENA__046__M__1": "Onu buraya biz getirdik.",
"VO__LUCAS__CH02__RTC__092_RATFIRSTENCOUNTER__010__M__1": "Bundan emin misin?",
"VO__LUCAS__CH02__RTC__092_RATFIRSTENCOUNTER__060__M__1": "Ayağa... kalkabilir misin?",
"VO__LUCAS__CH02__RTC__092_RATFIRSTENCOUNTER__140__M__1": "Buradalar!",
"VO__LUCAS__CH02__RTC__092_RATFIRSTENCOUNTER__180__M__1": "Sakin ol! Işıkta güvendesin!",
"VO__LUCAS__CH02__RTC__092_RATFIRSTENCOUNTER__210__M__1": "Daha fazlası geliyor...",
"VO__LUCAS__CH02__RTC__092_RATFIRSTENCOUNTER__250__M__1": "Durma!",
"VO__LUCAS__CH02__RTC__095_SOUTH_TOWER__010__M__1": "Geldik... Sanırım artık güvendeyiz.",
"VO__LUCAS__CH02__RTC__095_SOUTH_TOWER__015__M__1": "Harikaydın.",
"VO__LUCAS__CH02__RTC__095_SOUTH_TOWER__040__M__1": "Sorun ne? Vaudin burada bir yerde! Başardık!",
"VO__LUCAS__CH02__RTC__095_SOUTH_TOWER__070__M__1": "Hepimiz öyle olmasını umut ettik.",
"VO__LUCAS__CH02__RTC__095_SOUTH_TOWER__080__M__1": "Kimse buna hazır olamazdı. Ama yakında bununla artık yalnız olmayacağız. En iyi simyacılar yanımızda olacak.",
"VO__LUCAS__CH02__RTC__095_SOUTH_TOWER__085__M__1": "Güzel mi?",
"VO__LUCAS__CH02__RTC__095_SOUTH_TOWER__100__M__1": "Şimdi bak...",
"VO__LUCAS__CH02__RTC__095_SOUTH_TOWER__110__M__1": "Gerçek bir Düzen kulübesi...",
"VO__LUCAS__CH02__RTC__100_AN_ALCHEMIST__090__M__1": "Ben Lucas. Ben de bir simyacıyım.",
"VO__PEOPLE_F1__CH02__CHATTER__FIRE_CROWD__030__M__1": "Bravo!",
"VO__PEOPLE_F1__CH02__CHATTER__HUBT1_FLAVOR_LINE_RTC_OUTRO__020__M__1": "Geyik eti! Domuz eti! Gelin tadına bakın!",
"VO__PEOPLE_F1__CH02__CHATTER__HUBT1_MEATSTAND__060__M__1": "Ee...",
"VO__PEOPLE_F1__CH02__CHATTER__HUBT1_MEATSTAND_CALL__010__M__1": "Kızarmış et! Gelin tadına bakın!",
"VO__PEOPLE_F1__CH02__CHATTER__MARKET_SELLING_FABRIC__030__M__1": "En güzel giysiler, emin olun! Biriyle ilgilenir misiniz?",
"VO__PEOPLE_F1__CH02__CHATTER__SMALLTALK_GUYENNE__020__M__1": "Ah evet, tüm arenadaki bütün hayvanların telef olduğunu duydum.",
"VO__PEOPLE_F2__CH02__CHATTER__HALLES_EVENT_ITALY_CALL__010__M__1": "Floransa'dan fırçalar ve taraklar! Deneyin!",
"VO__PEOPLE_F2__CH02__CHATTER__HALLES_EVENT_ITALY_INTERACT__010__M__1": "Leydim! Saç stilinizi değiştirseniz?",
"VO__PEOPLE_F2__CH02__CHATTER__HALLES_EVENT_ITALY_INTERACT__030__M__1": "Ah... Sizin için hayırlısı! Bir kadının saçı onun gerçek tacıdır!",
"VO__PEOPLE_F2__CH02__CHATTER__INVEST_SLUMS_DANGER__020__M__1": "Havada bir kötülük var, hissedebiliyorum.",
"VO__PEOPLE_F2__CH02__CHATTER__WINE_STAND__020__M__1": "Ah, güzel bir hipokrasa bayılırım... bir düşüneyim...",
"VO__PEOPLE_F3__CH02__CHATTER__CRIER_NPC_CHAT__020__M__1": "Şu tezgâha bir bakmalıyım... Stoklarımız azalıyor...",
"VO__PEOPLE_F4__CH02__CHATTER__HALLES_CRIT_HERBORIST_CALL__020__M__1": "Aromatik otlar, merhemler, pomatlar!",
"VO__PEOPLE_F4__CH02__CHATTER__HALLES_CRIT_HERBORIST_CHAT__020__M__1": "Ah! Herbaryumdan anlıyorsun!",
"VO__PEOPLE_F4__CH02__CHATTER__HALLES_CRIT_HERBORIST_CHAT__040__M__1": "Çiçek almak ister misiniz o zaman?",
"VO__PEOPLE_F4__CH02__CHATTER__HALLES_CRIT_HERBORIST_CHAT__055__M__1": "Anlıyorum. İyi günler!",
"VO__PEOPLE_F4__CH02__CHATTER__HUBT1_NPC_AUCTIONREADY__010__M__1": "Balık mezatı birazdan başlıyor, gitmiyor musunuz?",
"VO__PEOPLE_F4__CH02__CHATTER__INVEST_HERBORIST_CHAT__010__M__1": "Ah, sizsiniz! Küçük için çiçek mi arıyorsunuz?",
"VO__PEOPLE_F4__CH02__CHATTER__INVEST_HERBORIST_CHAT__030__M__1": "O kocamın müşterisi. Şifalı otlarla o ilgilenir.",
"VO__PEOPLE_F4__CH02__CHATTER__INVEST_HERBORIST_CHAT__040__M__1": "Ama Martin tam çeşmenin yanında olmalı! Onu ben gönderdim deyin yeter. Kahverengi tunik giyiyor!",
"VO__PEOPLE_F5__CH02__CHATTER__GALLOW_ROMANCE__020__M__1": "Emin misin? Seni hep nöbette tutuyorlar!",
"VO__PEOPLE_F5__CH02__CHATTER__INVEST_SLUMS_DANGER__040__M__1": "Evet. O yüzden çocukları içeride tutuyorum!",
"VO__PEOPLE_F6__CH02__CHATTER__CRIER_NPC_CHAT__030__M__1": "Yeni bir elbise lazım. Ucuz bir tane.",
"VO__PEOPLE_M1__CH02__CHATTER__FIRE_BREATHER_SPEECH__010__M__1": "Dikkatinizi rica ederim! Dikkatli olun ve olduğunuz yerde kalın! Çünkü işte tehlike geliyor! İşte ateş geliyor!",
"VO__PEOPLE_M1__CH02__CHATTER__FIRE_BREATHER_SPEECH__020__M__1": "Ne dersiniz, ha?! Hile yok!",
"VO__PEOPLE_M1__CH02__CHATTER__FIRE_BREATHER_SPEECH__030__M__1": "Hadi! Sizi duyamıyorum!",
"VO__PEOPLE_M1__CH02__CHATTER__FIRE_BREATHER_SPEECH__040__M__1": "Teşekkürler! Hepinize teşekkürler!",
"VO__PEOPLE_M1__CH02__CHATTER__FORGE__021__M__1": "Bölgenin en iyi demircisine bakıyorsunuz!",
"VO__PEOPLE_M1__CH02__CHATTER__FORGE__040__M__1": "Orası kesin!",
"VO__PEOPLE_M1__CH02__CHATTER__HALLES_EVENT_ARMW__030__M__1": "Ha... Lanet olsun!",
"VO__PEOPLE_M1__CH02__CHATTER__HALLES_EVENT_ARMW_CALL__010__M__1": "Hadi...",
"VO__PEOPLE_M1__CH02__CHATTER__HALLES_EVENT_ARMW_VICTORY__030__M__1": "Bir tane daha! Hadi!",
"VO__PEOPLE_M1__CH02__CHATTER__HALLES_EVENT_ARMW_WARMUP__010__M__1": "Bu sefer! Bu sefer kolunu kıracağım!",
"VO__PEOPLE_M1__CH02__CHATTER__HUBT1_FLAVOR_LINE_RTC_OUTRO__010__M__1": "Nehirlerimizden taze balık! Bu sabah yakalandı!",
"VO__PEOPLE_M1__CH02__CHATTER__HUBT1_MEATSTAND__020__M__1": "Hey! Hadi! Küçük bir parça deneyin!",
"VO__PEOPLE_M1__CH02__CHATTER__HUBT1_MEATSTAND__042__M__1": "Beğendin mi?",
"VO__PEOPLE_M1__CH02__CHATTER__HUBT1_MEATSTAND__080__M__1": "Evet!",
"VO__PEOPLE_M1__CH02__CHATTER__WINE_STAND__010__M__1": "Bunların hepsi tepelerimizin bitkilerinden yapılmış şaraplar ve likörler!",
"VO__PEOPLE_M1__CH02__CHATTER__WINESTAND_INTERACT__020__M__1": "Belki babanız için bir hediye?",
"VO__PEOPLE_M1__CH02__CHATTER__WINESTAND_INTERACT__050__M__1": "Demek çok kibar bir adammış!",
"VO__PEOPLE_M2__CH02__CHATTER__ANIMALS_DISEASE__020__M__1": "Şurada bazı hasta hayvanları olduğunu duydum.",
"VO__PEOPLE_M2__CH02__CHATTER__CRIER_NPC_CHAT__010__M__1": "Bu yılki panayır geçen yılkinden bile büyük!",
"VO__PEOPLE_M2__CH02__CHATTER__FIRE_CROWD__040__M__1": "Şunu gördün mü?",
"VO__PEOPLE_M2__CH02__CHATTER__HALLES_EVENT_ARMW_VICTORY__020__M__1": "Ağzını değil, kolunu çalıştır!",
"VO__PEOPLE_M2__CH02__CHATTER__HALLES_EVENT_ARMW_VICTORY__040__M__1": "...Tabii.",
"VO__PEOPLE_M2__CH02__CHATTER__INSTRUMENTSTAND_CALL__010__M__1": "Lavtalar! En iyileri!",
"VO__PEOPLE_M2__CH02__CHATTER__INSTRUMENTSTAND_INTERACT__020__M__1": "Teşekkürler! Onları ben yapıyorum! Çalmayı biliyor musunuz?",
"VO__PEOPLE_M2__CH02__CHATTER__VEGETABLES_SELLER__010__M__1": "Yakındaki bir köyden taze ıspanak!",
"VO__PEOPLE_M3__CH02__CHATTER__GOAT_MILK__010__M__1": "Keçi sütü!",
"VO__PEOPLE_M3__CH02__CHATTER__GOAT_MILK__020__M__1": "İstendiğinde taze keçi sütü!",
"VO__PEOPLE_M3__CH02__CHATTER__HALLES_EVENT_ARMW_COMMENTS__010__M__1": "Evet!",
"VO__PEOPLE_M3__CH02__CHATTER__HALLES_EVENT_ARMW_COMMENTS__050__M__1": "İki kuruşuna bahse girerim kazanacak!",
"VO__PEOPLE_M4__CH02__CHATTER__CARPENTERSTAND_INTERACT__020__M__1": "Dev mi? Hayır... Sen sadece miniksin, o kadar.",
"VO__PEOPLE_M4__CH02__CHATTER__CARPENTERSTAND_INTERACT__060__M__1": "Pekâlâ! Minik... ama epey de karakterli...",
"VO__PEOPLE_M4__CH02__CHATTER__CHAMBOULETOUT_BARK__010__M__1": "Gelin oynayın! Bedava! Arles Kontu'ndan ziyaretçilerimize bir armağan!",
"VO__PEOPLE_M4__CH02__CHATTER__CHAMBOULETOUT_BARK__030__M__1": "Ne dersiniz leydim? Kazanan birine benziyorsunuz!",
"VO__PEOPLE_M4__CH02__CHATTER__CHAMBOULETOUT_LOSS__005__M__1": "Herkes ilk seferde beceremez. Sadece biraz daha pratik lazım.",
"VO__PEOPLE_M4__CH02__CHATTER__CHAMBOULETOUT_LOSS__010__M__1": "Şey, umut verici bir başlangıçtı!",
"VO__PEOPLE_M4__CH02__CHATTER__CHAMBOULETOUT_PLAY__020__M__1": "Olabildiğince çok küpü devirmek için dört atış hakkın var! Anladın mı?",
"VO__PEOPLE_M4__CH02__CHATTER__CHAMBOULETOUT_PLAY__040__M__1": "Hazır mısın?",
"VO__PEOPLE_M4__CH02__CHATTER__CHAMBOULETOUT_PLAY__070__M__1": "Başla!",
"VO__PEOPLE_M4__CH02__CHATTER__CHAMEBOULETOUT_WIN__040__M__1": "Bugünkü en iyi oyuncumuzsun!",
"VO__PEOPLE_M4__CH02__CHATTER__CRIER_TALK__010__M__1": "Duyduk duymadık demeyin! Arles Kontu Victor, hepinizi yıllık Aziz Yahya panayırına davet ediyor!",
"VO__PEOPLE_M4__CH02__CHATTER__CRIER_TALK__020__M__1": "Pazarda bölgemizden ve ötesinden mallar! Balık mezadımızda alışveriş yapın ve bedava bir atış oyununda hünerinizi deneyin!",
"VO__PEOPLE_M4__CH02__CHATTER__CRIER_TALK__030__M__1": "Yarınki etkinlik, uzun zamandır beklenen İnek Panayırı! Açık artırmaya hazır olun!",
"VO__PEOPLE_M4__CH02__CHATTER__CRIER_TALK__040__M__1": "Arles Kontu Victor hepinize harika bir Aziz Yahya panayırı diler!",
"VO__PEOPLE_M4__CH02__CHATTER__HALLES_EVENT_ARMW_COMMENTS__020__M__1": "Ne yumruk ama!",
"VO__PEOPLE_M4__CH02__CHATTER__HUBT1_NPC_AUCTIONREADY__020__M__1": "Hayır. Ben yarınki büyük sığır gösterisi için buradayım!",
"VO__PEOPLE_M4__CH02__CHATTER__INVEST_HERBORISTHUSB_CHAT__013__M__1": "Ah, şimdi ne istiyor?! Bu pisliği temizlemekle meşgulüm!",
"VO__PEOPLE_M4__CH02__CHATTER__INVEST_HERBORISTHUSB_CHAT__020__M__1": "O mu?! Rahatsız edilmekten hoşlanmaz! Tıpkı benim gibi...",
"VO__PEOPLE_M4__CH02__CHATTER__INVEST_HERBORISTHUSB_CHAT__22__M__1": "Pekâlâ, pekâlâ... Tam olarak nerede bilmiyorum, ama sanırım arenanın yakınında yaşıyor, şurada. Onu ben gönderdim demeyin!",
"VO__PEOPLE_M5__CH02__CHATTER__ANIMALS_DISEASE__010__M__1": "Sığır panayırı hâlâ devam ediyor mu? Çoktan orada olmalıydık!",
"VO__PEOPLE_M5__CH02__CHATTER__ANIMALS_DISEASE__030__M__1": "Ah... O zaman beklesek iyi olur.",
"VO__PEOPLE_M5__CH02__CHATTER__HALLES_EVENT_ARMW_COMMENTS__040__M__1": "Hadi, yenebilirsin onu!",
"VO__PEOPLE_M5__CH02__CHATTER__HUBT1_FISHAUCTION_CRIER__040__M__1": "Ton balığı! Sardalye! Tekneden taze.",
"VO__PEOPLE_M1__CH02__CHATTER__HALLES_EVENT_ARMW_VICTORY__030__M__1": "Bir tane daha! Hadi!",
"VO__SLAVE_F1__CH02__CHATTER__DYING_WOMAN__020__M__1": "Ah... Alice... Sensin!",
"VO__SLAVE_F1__CH02__CHATTER__DYING_WOMAN__040__M__1": "Söz ver... kendine iyi bakacaksın.",
"VO__SLAVE_M1__CH02__CHATTER__BANDIT_LOOP__040__M__1": "Lütfen, bırakın gideyim...",
"VO__SLAVE_M1__CH02__CHATTER__BANDIT_LOOP__060__M__1": "Belki o... başka yollar kullanıyordur...",
"VO__SLAVE_M1__CH02__CHATTER__KILL__010__M__1": "Lütfen, hayır!",
"VO__SLAVE_M1__CH02__CHATTER__KILL__050__M__1": "Onu tanımıyorum! Yemin ederim!",
"VO__SLAVE_M1__CH02__RTC__092_RATFIRSTENCOUNTER__100__M__1": "Lütfen bana zarar vermeyin...",
"VO__SLAVE_M1__CH02__RTC__092_RATFIRSTENCOUNTER__120__M__1": "Evet...",
"VO__SLAVE_M1__CH02__RTC__092_RATFIRSTENCOUNTER__130__M__1": "Ne?! O da ne?",
"VO__SLAVE_M1__CH02__RTC__092_RATFIRSTENCOUNTER__160__M__1": "Benden ne istiyorlar?",
"VO__SLAVE_M1__CH02__RTC__092_RATFIRSTENCOUNTER__190__M__1": "Pekâlâ!",
"VO__SLAVE_M1__CH02__RTC__092_RATFIRSTENCOUNTER__200__M__1": "Bunlar nereden geliyor?!",
"VO__SLAVE_M1__CH02__RTC__092_RATFIRSTENCOUNTER__240__M__1": "Çok kalabalıklar!",
"VO__SLAVE_M1__CH02__RTC__092_RATFIRSTENCOUNTER__270__M__1": "Evet...",
"VO__SLAVE_M1__CH02__RTC__092_RATFIRSTENCOUNTER__280__M__1": "Ne?... Haaa!",
"VO__SOLDIER_S1__CH02__CHATTER__GALLOW_ROMANCE__010__M__1": "Nöbetimden sonra görüşürüz, tamam mı?",
"VO__SOLDIER_S1__CH02__CHATTER__GALLOW_ROMANCE__030__M__1": "Biliyorum... Kont kaptana daha fazla yetki verdiğinden beri böyle işte.",
"VO__SOLDIER_S1__CH02__CHATTER__INVEST_GUARD__020__M__1": "Bir Sir Vaudin duydum, \"Magister\" değil...",
"VO__SOLDIER_S1__CH02__CHATTER__INVEST_GUARD__025__M__1": "Pazar yerini deneyin. Orada birkaç çiçekçi var. Sanırım onunla ara sıra iş yapıyorlar.",
"VO__SOLDIER_S1__CH02__CHATTER__INVEST_HERBORIST_GUARDHELP__020__M__1": "Arkanızda, pazarın diğer tarafında!",
"VO__SOLDIER_S1__CH02__CHATTER__INVEST_SLUMS_GUARDS__010__M__1": "Kimse giremez! Arena yasak bölge.",
"VO__SOLDIER_S1__CH02__CHATTER__INVEST_SLUMS_GUARDS__030__M__1": "Çünkü Provence Kontu öyle dedi! Yürüyün lütfen!",
}
