# -*- coding: utf-8 -*-
# CH05 VO. onom/EMPTY atlanir. Arnaud=dusman; Joseph=BOATMAN(tekneci).
# Pyrite/Ignifer korunur; tar->katran, the Order->Duzen, the Bite->Isirik, Marseille->Marsilya.
T = {
"VO__AMICIA__CH05__CHATTER__AFTER_EXPLO__010__M__1": "Lucas! Oraya ulaşabilir misin?",
"VO__AMICIA__CH05__CHATTER__AFTER_EXPLO__030__M__1": "Pekâlâ! Yola çıkıyorum!",
"VO__AMICIA__CH05__CHATTER__AFTER_EXPLO__060__M__1": "Evet, evet...",
"VO__AMICIA__CH05__CHATTER__BELOW__025__M__1": "Sadece kendimi savundum!",
"VO__AMICIA__CH05__CHATTER__BELOW__060__M__1": "Hayır! Birinin Joseph'i koruması gerek!",
"VO__AMICIA__CH05__CHATTER__BELOW__080__M__1": "Bu benim kararım Anne! Sen içeride kal!",
"VO__AMICIA__CH05__CHATTER__BIRD_APPROACH__010__M__1": "Lütfen... sakın... sakın kımıldama...",
"VO__AMICIA__CH05__CHATTER__BIRD_NOISE__015__M__1": "Hayır, hayır, hayır!",
"VO__AMICIA__CH05__CHATTER__BIRD_REACT__010__M__1": "Hayır!...",
"VO__AMICIA__CH05__CHATTER__BIRDS__010__M__1": "HAYIR!",
"VO__AMICIA__CH05__CHATTER__BIRDS__030__M__1": "Çabuk... Koş!",
"VO__AMICIA__CH05__CHATTER__BODY_FALLS__010__M__1": "Ha... Tamam! Bir dene!",
"VO__AMICIA__CH05__CHATTER__BODY_FALLS__030__M__1": "Evet... Lütfen!",
"VO__AMICIA__CH05__CHATTER__BRAZIER_TWO__020__M__1": "Beni tanırsın, hadi! Ben hep geri dönerim!",
"VO__AMICIA__CH05__CHATTER__BRAZIER_TWO__070__M__1": "Onunla biz ilgileniriz!",
"VO__AMICIA__CH05__CHATTER__BRAZIER_TWO__080__M__1": "Bakalım ne yapıyor.",
"VO__AMICIA__CH05__CHATTER__BRIDGE_FIRE__010__M__1": "Cehennemde yanın, hepiniz!",
"VO__AMICIA__CH05__CHATTER__BRIDGE_STUCK__010__M__1": "Hadi, yapabilirsin... Bu sadece... ayağına batan başka bir diken.",
"VO__AMICIA__CH05__CHATTER__BRIDGE_VISTA__010__M__1": "Yaklaştık! Nefes al...",
"VO__AMICIA__CH05__CHATTER__BROKEN_CHAIN_PATH__010__M__1": "Artık geri dönebilmem gerek.",
"VO__AMICIA__CH05__CHATTER__CART_FIRE__044__M__1": "İzin vermeyeceğim!",
"VO__AMICIA__CH05__CHATTER__CART_FIRE__046__M__1": "Buradan uzaklaşmalıyız!",
"VO__AMICIA__CH05__CHATTER__CART_FIRE__051__M__1": "Yan... Yan, lanet olsun!",
"VO__AMICIA__CH05__CHATTER__CART_FIRE__052__M__1": "Çok uzun sürüyor!",
"VO__AMICIA__CH05__CHATTER__CART_HOLE__010__M__1": "İçeri giriyorum!",
"VO__AMICIA__CH05__CHATTER__CART_IS_COMING__010__M__1": "İşte orada...",
"VO__AMICIA__CH05__CHATTER__CART_IS_COMING__020__M__1": "Şimdi tekneye...",
"VO__AMICIA__CH05__CHATTER__CART_MOVED__020__M__1": "Bir delik var!",
"VO__AMICIA__CH05__CHATTER__CHAIN__010__M__1": "Hmmm... İşe yarayabilir...",
"VO__AMICIA__CH05__CHATTER__CHAIN__012__M__1": "Lucas! Zincirden uzaklaş!",
"VO__AMICIA__CH05__CHATTER__CHAIN__020__M__1": "Yakaladım!...",
"VO__AMICIA__CH05__CHATTER__CHAIN_BREAKS__030__M__1": "Bu da ne...?",
"VO__AMICIA__CH05__CHATTER__CHAIN_BREAKS__050__M__1": "İyiyim!... Az kalsın eziliyordum...",
"VO__AMICIA__CH05__CHATTER__CHASE_DOWN__010__M__1": "Geri dön! Hâlâ yapabilirsin...",
"VO__AMICIA__CH05__CHATTER__CHASE_DOWN_BOAT__010__M__1": "Tekne! Evet!",
"VO__AMICIA__CH05__CHATTER__CHASE_DOWN_CONT__010__M__1": "Hayır... Hayır!... Cehenneme git!",
"VO__AMICIA__CH05__CHATTER__CHASE_FALL__010__M__1": "Hayır... Hayır, hayır!",
"VO__AMICIA__CH05__CHATTER__CHASE_FALL__020__M__1": "Ha... Ha... Devam... et...",
"VO__AMICIA__CH05__CHATTER__CHASE_FALL__040__M__1": "Panik... yapma...",
"VO__AMICIA__CH05__CHATTER__CHASE_FALL_TREES__010__M__1": "Titremeyi kes! İçine işlemesine izin verme!",
"VO__AMICIA__CH05__CHATTER__CHASE_SLOPE__020__M__1": "Güvendesin... Şimdilik... nefes al...",
"VO__AMICIA__CH05__CHATTER__CHASE_START__020__M__1": "Ona zarar veremem... Koş!",
"VO__AMICIA__CH05__CHATTER__CLIFF_ECHO__020__M__1": "Şimdilik bundan en iyi şekilde yararlanalım... Hugo'yu neşelendirmeye çalışabiliriz.",
"VO__AMICIA__CH05__CHATTER__CLIFF_ECHO__040__M__1": "İstediğinde epey yüksek sesle bağırabiliyorsun...",
"VO__AMICIA__CH05__CHATTER__CLIFF_ECHO__060__M__1": "Evet... Bir, iki, üç deyince! EEEHOOO!",
"VO__AMICIA__CH05__CHATTER__CLIFF_ECHO__080__M__1": "Bekle...",
"VO__AMICIA__CH05__CHATTER__CLIFF_ECHO__100__M__1": "Bizi gördü! Gidelim...",
"VO__AMICIA__CH05__CHATTER__CLIMB_CRATE__010__M__1": "Güzel, bu bir adım...",
"VO__AMICIA__CH05__CHATTER__CLIMB_TOO_HIGH__010__M__1": "Hâlâ çok yüksek... Yine bir araba lazım olacak...",
"VO__AMICIA__CH05__CHATTER__COLLAPSING__005__M__1": "O da ne?!",
"VO__AMICIA__CH05__CHATTER__COLLAPSING__010__M__1": "Eyvah... Hayır, hayır, hayır!",
"VO__AMICIA__CH05__CHATTER__COLLAPSING__030__M__1": "İşte onlar!",
"VO__AMICIA__CH05__CHATTER__CRANK_COMPANION__020__M__1": "Pekâlâ... Ben geçeceğim...",
"VO__AMICIA__CH05__CHATTER__CRANK_IDLE_1__012__M__1": "O fareler her yerde... Onlardan kurtulamayacağız...",
"VO__AMICIA__CH05__CHATTER__CRANK_IDLE_2__020__M__1": "Üzerinde çalışıyorum!",
"VO__AMICIA__CH05__CHATTER__CRANK_LUCAS_GO__010__M__1": "O deliği gördün mü? Artık neler yapabildiklerini...",
"VO__AMICIA__CH05__CHATTER__CRANK_LUCAS_GO__030__M__1": "Hugo'nun duygularını görmezden gelmeye devam edersek yine olacak.",
"VO__AMICIA__CH05__CHATTER__CRANK_MOVE__020__M__1": "Evet... Bu karşıya geçmemizi sağlayabilir!",
"VO__AMICIA__CH05__CHATTER__CRANK_PUZZLE__030__M__1": "Belki diğer tarafta! Feribot beni oraya götürebilir!",
"VO__AMICIA__CH05__CHATTER__CRANK_PUZZLE__040__M__1": "Bu... paslanmış... ya da öyle bir şey!",
"VO__AMICIA__CH05__CHATTER__CRANK_PUZZLE_BLOCK__010__M__1": "Sıkışmış!",
"VO__AMICIA__CH05__CHATTER__CRANK_PUZZLE_BLOCK__030__M__1": "Pekâlâ, bir bakayım!",
"VO__AMICIA__CH05__CHATTER__CRANK_PUZZLE_BLOCK__050__M__1": "Bir yol buluruz.",
"VO__AMICIA__CH05__CHATTER__CRANK_SELF__010__M__1": "Öf... Pekâlâ... Bu bir başlangıç...",
"VO__AMICIA__CH05__CHATTER__CRANK_SELF__031__M__1": "Bir yol olmalı... şu vinçler...",
"VO__AMICIA__CH05__CHATTER__CRANK_SELF__050__M__1": "Bir denemeliyiz.",
"VO__AMICIA__CH05__CHATTER__CROSSBOW_DONE__040__M__1": "Nasıl?!",
"VO__AMICIA__CH05__CHATTER__CROSSBOW_DONE__070__M__1": "Tabii! Lucas, yol açıldığında sana söylerim!",
"VO__AMICIA__CH05__CHATTER__CROSSBOWS_LUCAS__015__M__1": "Pekâlâ!",
"VO__AMICIA__CH05__CHATTER__CROSSBOWS_LUCAS__030__M__1": "Çekin ellerinizi ondan, sizi köpekler!",
"VO__AMICIA__CH05__CHATTER__CROSSBOWS_LUCAS__060__M__1": "Acele et Amicia!",
"VO__AMICIA__CH05__CHATTER__CROSSBOWS_NERVES__010__M__1": "Bu nasıl?!",
"VO__AMICIA__CH05__CHATTER__CROSSBOWS_NERVES__020__M__1": "Lucas! İyi misin?!",
"VO__AMICIA__CH05__CHATTER__CROSSED__010__M__1": "Pekâlâ. Şu ya da bu şekilde o zincirin gitmesi gerek.",
"VO__AMICIA__CH05__CHATTER__CROSSED__040__M__1": "Arıyorum!",
"VO__AMICIA__CH05__CHATTER__CROSSED__050__M__1": "Burada bir şey olmalı...",
"VO__AMICIA__CH05__CHATTER__CROSSING__010__M__1": "Yola çıkıyorum!",
"VO__AMICIA__CH05__CHATTER__CROSSING__012__M__1": "Evet... Ha...",
"VO__AMICIA__CH05__CHATTER__CROSSING_NEXT__020__M__1": "Ha... Havaya ihtiyacım var...",
"VO__AMICIA__CH05__CHATTER__CROSSING_NEXT__050__M__1": "Olma... senin suçun değil.",
"VO__AMICIA__CH05__CHATTER__CROSSING_NEXT__090__M__1": "Onun adası, Anne...",
"VO__AMICIA__CH05__CHATTER__CROSSING_NEXT__110__M__1": "Peki!",
"VO__AMICIA__CH05__CHATTER__CURRENT__020__M__1": "Evet!",
"VO__AMICIA__CH05__CHATTER__EXIT_CAVE__040__M__1": "Hayır... Alçak!",
"VO__AMICIA__CH05__CHATTER__EXIT_CAVE__045__M__1": "Ondan önce tekneye ulaşmalıyım!",
"VO__AMICIA__CH05__CHATTER__EXIT_CAVE__046__M__1": "Çok çabuk hareket et...",
"VO__AMICIA__CH05__CHATTER__EXIT_CAVE__049__M__1": "İzin verme... Bir şey yap! Hemen!",
"VO__AMICIA__CH05__CHATTER__EXIT_CAVE__050__M__1": "Hey! Geri gel!",
"VO__AMICIA__CH05__CHATTER__EXIT_CAVE__060__M__1": "Hayır, hayır, hayır... Onlara dokunamayacaksın!",
"VO__AMICIA__CH05__CHATTER__FIND_BODY__010__M__1": "Ah... Hayır... Lütfen olmasın...",
"VO__AMICIA__CH05__CHATTER__FIND_BODY__015__M__1": "Üzgünüm... yapmak zorundayım...",
"VO__AMICIA__CH05__CHATTER__FIND_BODY__020__M__1": "Lütfen... beni affet... Bunu... yapmalıyım!",
"VO__AMICIA__CH05__CHATTER__FIRST_PASS_THROUGH__010__M__1": "Hadi... Ha... Güzel...",
"VO__AMICIA__CH05__CHATTER__FIRST_PASS_THROUGH__030__M__1": "Bir ada bul... Hı... Bunu nasıl yapacaksın...? Belki Joseph'e sorsam? Gizlice...",
"VO__AMICIA__CH05__CHATTER__FLOWER__010__M__1": "Hey... Şu hâline bak, burada mahsur kalmışsın... Üzgünüm, sana ihtiyacım olacak...",
"VO__AMICIA__CH05__CHATTER__FLOWER__020__M__1": "Onu neşelendirebilecek her şey...",
"VO__AMICIA__CH05__CHATTER__FLOWER__030__M__1": "Şunu bitirelim...",
"VO__AMICIA__CH05__CHATTER__FROM_THE_BOAT__015__M__1": "Anne! Lucas hâlâ yanında değil mi?!",
"VO__AMICIA__CH05__CHATTER__FROM_THE_BOAT__030__M__1": "Nasıl...? Ne yapıyor?!",
"VO__AMICIA__CH05__CHATTER__GOING_BACK__010__M__1": "Çok saçma... Eğlenmek için oynuyor olmalıyız. Şimdi onun dağılmasını engellemek için oynuyoruz.",
"VO__AMICIA__CH05__CHATTER__GOING_BACK__030__M__1": "Asla...",
"VO__AMICIA__CH05__CHATTER__HAY__020__M__1": "Şu saman balyası iyi yanar gibi görünüyor!",
"VO__AMICIA__CH05__CHATTER__HAY__030__M__1": "Ama hızlı yanacak!",
"VO__AMICIA__CH05__CHATTER__HAY_FALLS__010__M__1": "Ne?! Hayır, hayır! Lucas! Ne yapacağım?!",
"VO__AMICIA__CH05__CHATTER__HAY_FALLS__030__M__1": "Vay! Bu... Bu da ne?!",
"VO__AMICIA__CH05__CHATTER__HAY_FALLS__040__M__1": "Geri! Geri çekil!",
"VO__AMICIA__CH05__CHATTER__HAY_FALLS__050__M__1": "Bundan hoşlanmıyorlar!",
"VO__AMICIA__CH05__CHATTER__HAY_SHOOT__020__M__1": "Hadi! Koş!",
"VO__AMICIA__CH05__CHATTER__INCOMING_BRIDGE__020__M__1": "Bir ordular!",
"VO__AMICIA__CH05__CHATTER__INCOMING_BRIDGE__040__M__1": "Onu göreceğiz!",
"VO__AMICIA__CH05__CHATTER__INTRO_BOAT2__040__M__1": "Hadi, etrafından dolaşacak bir yol bulalım.",
"VO__AMICIA__CH05__CHATTER__ISLAND_FINAL__010__M__1": "Bunca ölü... Bunu hak etmediler...",
"VO__AMICIA__CH05__CHATTER__ISLAND_FINAL__030__M__1": "Onun için çok geç... Ama bu ada—Hugo bütün bunları düzelteceğini söylüyor... O zaman düzeltecek.",
"VO__AMICIA__CH05__CHATTER__ISLAND_FINAL__050__M__1": "Mesele nerede olduğu. Onu bulmalıyız.",
"VO__AMICIA__CH05__CHATTER__ISLAND_FINAL__070__M__1": "Umurumda değil. Ama bir taraf seçmek zorunda kalacaksın.",
"VO__AMICIA__CH05__CHATTER__KILL_BOLT_1__010__M__1": "Geber işte!",
"VO__AMICIA__CH05__CHATTER__KILL_BOLT_2__010__M__1": "Sıradaki kim?!",
"VO__AMICIA__CH05__CHATTER__KILL_BOLT_3__010__M__1": "Lanet olsun sana...",
"VO__AMICIA__CH05__CHATTER__LAST_BRIDGE_FIRE__010__M__1": "Bu, ben ve kardeşim için! Ve diğer herkes için!",
"VO__AMICIA__CH05__CHATTER__LEDGE_POI__010__M__1": "O koku berbat... Hugo'yu buradan uzaklaştırmalıyız.",
"VO__AMICIA__CH05__CHATTER__LEDGE_POI__024__M__1": "Geliyoruz!",
"VO__AMICIA__CH05__CHATTER__LEDGE_POI__027__M__1": "Evet!... Korkmaya başlıyor. Gidelim.",
"VO__AMICIA__CH05__CHATTER__LEDGE_TREMOR__030__M__1": "Hayır... Geliyorlar! Tekneye, çabuk!",
"VO__AMICIA__CH05__CHATTER__LOOK_AT_HOLE__010__M__1": "Hm. Buradaki kalaslarda bir delik var.",
"VO__AMICIA__CH05__CHATTER__LOOK_AT_THE_BRIDGE__010__M__1": "Tanrım... O şeyi nasıl geçeceğim?... Bir karmaşa daha!",
"VO__AMICIA__CH05__CHATTER__LOOK_AT_THE_BRIDGE__020__M__1": "Sakin ol... tedirginsin... Ve nedenini biliyorsun...",
"VO__AMICIA__CH05__CHATTER__LOOK_AT_THE_BRIDGE__030__M__1": "Ada... Onu sonra çözersin... Odaklan...",
"VO__AMICIA__CH05__CHATTER__LOOK_AT_THE_BRIDGE__040__M__1": "Yukarıda... İyi bir başlangıç gibi...",
"VO__AMICIA__CH05__CHATTER__LUCAS_2ND_RUN__010__M__1": "Şimdi, burada bir saman balyamız daha var! Onu yakıyorum—Koşuyoruz!",
"VO__AMICIA__CH05__CHATTER__LUCAS_2ND_RUN__030__M__1": "Sıcak kal!",
"VO__AMICIA__CH05__CHATTER__LUCAS_2ND_RUN__040__M__1": "Hazır mısın?",
"VO__AMICIA__CH05__CHATTER__LUCAS_2ND_RUN__060__M__1": "Hadi! Hadi!",
"VO__AMICIA__CH05__CHATTER__LUCAS_2ND_RUN__080__M__1": "Başardık! Bu arada \"savaş narana\" bayıldım!",
"VO__AMICIA__CH05__CHATTER__LUCAS_CHAIN__030__M__1": "İşte! Hazır!",
"VO__AMICIA__CH05__CHATTER__LUCAS_STUCK_LOCK__020__M__1": "Onunla ben ilgilenirim!",
"VO__AMICIA__CH05__CHATTER__MIDDLE__020__M__1": "O neydi?!",
"VO__AMICIA__CH05__CHATTER__MIDDLE__040__M__1": "Hayatımı kurtardı! Teşekkürler!",
"VO__AMICIA__CH05__CHATTER__MIDDLE__054__M__1": "Daha çok lazım!",
"VO__AMICIA__CH05__CHATTER__MIDDLE__058__M__1": "Pekâlâ, seni karşıya geçirme sırası bende!",
"VO__AMICIA__CH05__CHATTER__MIDDLE_CRANK__010__M__1": "Şuna bir bakalım...",
"VO__AMICIA__CH05__CHATTER__MIDDLE_CRANK__020__M__1": "Dayan Lucas!",
"VO__AMICIA__CH05__CHATTER__MIDDLE_CRANK_USE__010__M__1": "Pekâlâ, sonuna kadar dönüyor gibi...",
"VO__AMICIA__CH05__CHATTER__MIDDLE_RUN__010__M__1": "Evet!",
"VO__AMICIA__CH05__CHATTER__MIDDLE_RUN__020__M__1": "Hadi, hadi, hadi!",
"VO__AMICIA__CH05__CHATTER__MORE_RIGHT_GORGE__010__M__1": "Onu yap! Çoktan öldüklerini söyle onlara!",
"VO__AMICIA__CH05__CHATTER__MOVE_CART_RELEASE__010__M__1": "Yokuşta... Durmaz...",
"VO__AMICIA__CH05__CHATTER__MOVING_CRANE_2__010__M__1": "Sırf Marsilya'ya gitmek için bunca uğraş...",
"VO__AMICIA__CH05__CHATTER__MOVING_CRANE_2__030__M__1": "Değil! Ve Hugo artık ona inanmıyor!",
"VO__AMICIA__CH05__CHATTER__MOVING_CRANE_3__020__M__1": "Ne hakkında?",
"VO__AMICIA__CH05__CHATTER__MOVING_CRANE_3__040__M__1": "Sana söyledim. Bir taraf seçmek zorundasın.",
"VO__AMICIA__CH05__CHATTER__MOVING_THE_CRANK__030__M__1": "Doğru yoldasın... Tekneye ulaş, sonra Lucas...",
"VO__AMICIA__CH05__CHATTER__NEED_OIL__010__M__1": "Saman yetmeyecek!",
"VO__AMICIA__CH05__CHATTER__NEXT_CRANK__005__M__1": "Buradayım!",
"VO__AMICIA__CH05__CHATTER__NEXT_CRANK__010__M__1": "Hazırım!",
"VO__AMICIA__CH05__CHATTER__NEXT_CRANK_COMPANION__010__M__1": "Sanırım yine yapmamız gerekecek.",
"VO__AMICIA__CH05__CHATTER__NEXT_CRANK_DONE__020__M__1": "Hareket etmeye devam edelim...",
"VO__AMICIA__CH05__CHATTER__NEXT_CRANK_DONE__027__M__1": "Yoldayız Hugo!... Hâlâ korkuyor. Ona çabuk ulaşmalıyım.",
"VO__AMICIA__CH05__CHATTER__NEXT_CRANK_DONE__050__M__1": "Kendini kaybetmiş durumda Lucas, ve o da bunu biliyor.",
"VO__AMICIA__CH05__CHATTER__NEXT_CRANK_DONE__070__M__1": "Evet...",
"VO__AMICIA__CH05__CHATTER__NEXT_CRANK_RELEASE__030__M__1": "Şimdi! Geliyorum!",
"VO__AMICIA__CH05__CHATTER__NEXT_CRANK_RELEASE__040__M__1": "Hadi... Kımılda!",
"VO__AMICIA__CH05__CHATTER__PATH_HELPER__020__M__1": "Biliyorum!",
"VO__AMICIA__CH05__CHATTER__PATH_PROGRESS__030__M__1": "Tamam! Gelebilirsin!",
"VO__AMICIA__CH05__CHATTER__PLATFORM__014__M__1": "Yeter Anne!",
"VO__AMICIA__CH05__CHATTER__PLATFORM__020__M__1": "Evet, gel... Hak ettiğini bulacaksın...",
"VO__AMICIA__CH05__CHATTER__PLATFORM_FIRE__010__M__1": "Hadi bakalım! Bu nasıl?",
"VO__AMICIA__CH05__CHATTER__POST_COLLAPSE__030__M__1": "Evet! Merak etme!",
"VO__AMICIA__CH05__CHATTER__POST_COLLAPSE__060__M__1": "Bunu nasıl yapacağımızı biliyoruz! Geliyoruz!",
"VO__AMICIA__CH05__CHATTER__POST_COLLAPSE__080__M__1": "Diğer tarafta mangallar var...",
"VO__AMICIA__CH05__CHATTER__PRE_BOSSFIGHT__020__M__1": "Ailemden uzak dur!",
"VO__AMICIA__CH05__CHATTER__PRE_BOSSFIGHT__023__M__1": "Geliyorlar... Sipere geç, çabuk!",
"VO__AMICIA__CH05__CHATTER__PRE_BOSSFIGHT__025__M__1": "Geride durun! Hepinizi öldürürüm!",
"VO__AMICIA__CH05__CHATTER__PRE_BOSSFIGHT__050__M__1": "Her hakka sahip olduğunu sanıyorsun, ha?!...",
"VO__AMICIA__CH05__CHATTER__PRE_BOSSFIGHT__080__M__1": "Lideriniz nerede?! Şu Arnaud nerede?! Gel karşıma!",
"VO__AMICIA__CH05__CHATTER__PUSH_BOAT__020__M__1": "Bu çok uzun sürer...",
"VO__AMICIA__CH05__CHATTER__PUSH_BOAT__030__M__1": "Belki sadece itebiliriz?",
"VO__AMICIA__CH05__CHATTER__PUSH_BOAT__050__M__1": "Hazır mısın?",
"VO__AMICIA__CH05__CHATTER__PUSH_BOAT__070__M__1": "O zaman it!",
"VO__AMICIA__CH05__CHATTER__PUSH_PULL__010__M__1": "Evet...",
"VO__AMICIA__CH05__CHATTER__PUSH_PULL__020__M__1": "İşte.",
"VO__AMICIA__CH05__CHATTER__PUSH_PULL_AGAIN__010__M__1": "Buraya gel... Sana ihtiyacım var...",
"VO__AMICIA__CH05__CHATTER__PUSH_PULL_AGAIN__020__M__1": "İşe yarar.",
"VO__AMICIA__CH05__CHATTER__RIGHT_GORGE__020__M__1": "Bunu hiç istemedim! Ama gerekirse şu Arnaud domuzunun işini bitiririm!",
"VO__AMICIA__CH05__CHATTER__ROCKS__022__M__1": "Beni merak etme!",
"VO__AMICIA__CH05__CHATTER__ROCKS__030__M__1": "Hâllettin!",
"VO__AMICIA__CH05__CHATTER__ROCKS__050__M__1": "Hâllederim! Saklanmaya devam et! Bunu atlatacağız!",
"VO__AMICIA__CH05__CHATTER__ROCKS_MOVE__020__M__1": "Bizi durduramayacaksınız... Onca şeyden sonra olmaz...",
"VO__AMICIA__CH05__CHATTER__ROCKS_RIGHT__020__M__1": "Hallediyorum!",
"VO__AMICIA__CH05__CHATTER__RUN__030__M__1": "Ne yaptım ben?! Onlara zarar verecek! Kımılda!",
"VO__AMICIA__CH05__CHATTER__RUN__040__M__1": "Hadi!",
"VO__AMICIA__CH05__CHATTER__RUN_TWO__010__M__1": "Çok uzaktayım! Hayır! Onlara dokunursan, ben...",
"VO__AMICIA__CH05__CHATTER__RUN_TWO__020__M__1": "Hugo... Lucas... Daha hızlı!",
"VO__AMICIA__CH05__CHATTER__SEARCHING__070__M__1": "Seninle... dövüşebilseydim...",
"VO__AMICIA__CH05__CHATTER__SEARCHING__110__M__1": "Hareket etmeye devam et...",
"VO__AMICIA__CH05__CHATTER__SHORE__015__M__1": "Evet! Gel! Bak bakalım ne olacak!",
"VO__AMICIA__CH05__CHATTER__SHORE__030__M__1": "Senin... çeneni... kendi bağırsaklarınla... kapatacağım...",
"VO__AMICIA__CH05__CHATTER__SHORE_CLOSE__010__M__1": "Hepsini öldüreceğim Arnaud! Başladığım işi bitireceğim!",
"VO__AMICIA__CH05__CHATTER__SHORE_CORNER__020__M__1": "Yavaşlayamam... Ona göz kulak ol...",
"VO__AMICIA__CH05__CHATTER__SHORE_UP__010__M__1": "Hepsi bu kadar... Şimdi... Evet, tekneyi kurtar... Şu ipleri kes...",
"VO__AMICIA__CH05__CHATTER__SQUEEZE_ARNAUD__010__M__1": "Tekne... Onu atlat... İpler için geri dön...",
"VO__AMICIA__CH05__CHATTER__STICK__010__M__1": "Başardım!",
"VO__AMICIA__CH05__CHATTER__STICK_BOAT__010__M__1": "Güzel... Neredeyse vardık...",
"VO__AMICIA__CH05__CHATTER__STICK_BOAT__030__M__1": "Düzen onu eline geçirdiğinde çok geç olacak.",
"VO__AMICIA__CH05__CHATTER__STICK_BOAT__050__M__1": "Haklı mısın diye görmek için bu riski alamayız.",
"VO__AMICIA__CH05__CHATTER__STICK_LIGHT__011__M__1": "Güzel yakaladın!",
"VO__AMICIA__CH05__CHATTER__STICK_LIGHT__013__M__1": "Başarabilirsin! Sadece koşmaya devam et!",
"VO__AMICIA__CH05__CHATTER__STICK_LIGHT__015__M__1": "Koş! Düşünme!",
"VO__AMICIA__CH05__CHATTER__STICK_LIGHT_OK__010__M__1": "Evet! Epey hızlı koşuyorsun!",
"VO__AMICIA__CH05__CHATTER__STICK_THROW__007__M__1": "Bu tam işimi görür.",
"VO__AMICIA__CH05__CHATTER__STICK_THROW__010__M__1": "Hadi bakalım!",
"VO__AMICIA__CH05__CHATTER__TO_LEDGE__010__M__1": "Bir geçit, burada...",
"VO__AMICIA__CH05__CHATTER__TO_LEDGE__020__M__1": "İşte nehir...",
"VO__AMICIA__CH05__CHATTER__TO_LEDGE__030__M__1": "İşte oradalar!",
"VO__AMICIA__CH05__CHATTER__TO_NEXT_CRANK__005__M__1": "Evet!",
"VO__AMICIA__CH05__CHATTER__TO_NEXT_CRANK__007__M__1": "Varıyoruz!",
"VO__AMICIA__CH05__CHATTER__TO_NEXT_CRANK__010__M__1": "Bir vinç daha var! Sanırım seni karşıya geçirebilirim!",
"VO__AMICIA__CH05__CHATTER__TO_NEXT_CRANK__030__M__1": "Geliyor!",
"VO__AMICIA__CH05__CHATTER__TO_SOUVENIR_CLIFF__010__M__1": "Yukarıda ne var acaba...",
"VO__AMICIA__CH05__CHATTER__TO_SOUVENIR_NO_GO__010__M__1": "Lucas olmadan gitmemeliyim.",
"VO__AMICIA__CH05__CHATTER__TO_THE_BRIDGE__010__M__1": "Güvende olmak umurumda değil...",
"VO__AMICIA__CH05__CHATTER__TO_THE_BRIDGE__020__M__1": "Bütün mesele Hugo, Anne! Bana güvenmediğini biliyorum ama sadece onu dinle!",
"VO__AMICIA__CH05__CHATTER__TO_THE_BRIDGE__030__M__1": "Sakin ol... Odaklan.",
"VO__AMICIA__CH05__CHATTER__TO_THE_SITE__016__M__1": "Ha... Biz... Güvendeyiz... Sanırım...",
"VO__AMICIA__CH05__CHATTER__UNDER_PONTOON__010__M__1": "Aman Tanrım!...",
"VO__AMICIA__CH05__CHATTER__UNDER_PONTOON__030__M__1": "Ben... İyiyim! Ha...",
"VO__AMICIA__CH05__CHATTER__UNDER_PONTOON__070__M__1": "Hayır!... Her şey yoluna girecek.",
"VO__AMICIA__CH05__CHATTER__UNDER_PONTOON__080__M__1": "Beni affet...",
"VO__AMICIA__CH05__CHATTER__WOODS_SOUVENIR__010__M__1": "Buradan deneyelim...",
"VO__AMICIA__CH05__CHATTER__WOODS_SOUVENIR__030__M__1": "Vay! Bu da ne?!",
"VO__AMICIA__CH05__CHATTER__WOODS_SOUVENIR__050__M__1": "Öf... Tanrım, var olduklarını unutmuşum...",
"VO__AMICIA__CH05__CHATTER__WOODS_SOUVENIR__070__M__1": "Sanki onlar için hiçbir şey değişmemiş gibi...",
"VO__AMICIA__CH05__CHATTER__WOODS_SOUVENIR__090__M__1": "Ama onlar kur yapıyor, biz ölmemeye çalışıyoruz.",
"VO__AMICIA__CH05__CHATTER__WOODS_SOUVENIR__110__M__1": "Geri dönelim...",
"VO__AMICIA__CH05__HELPER__BRIDGE_PLATFORM_1__010__M__1": "Yine tırmanmam gerekecek... O diğer araba tam doğru boyuttaydı...",
"VO__AMICIA__CH05__HELPER__BRIDGE_PLATFORM_2__010__M__1": "Şu yükleme platformu... Arabayı onun üstüne taşıyabilirim...",
"VO__AMICIA__CH05__HELPER__CHAIN_BREAK_1__010__M__1": "Zinciri takip et Amicia... Bir şey bulursun...",
"VO__AMICIA__CH05__HELPER__FIRST_BRIDGE_CLIMB_1__010__M__1": "Diğer tarafa tırmanmak için bir şey lazım...",
"VO__AMICIA__CH05__HELPER__FIRST_BRIDGE_CLIMB_2__010__M__1": "Şu araba... Onu taşıyabilirim... Belki gereken yüksekliği verir.",
"VO__AMICIA__CH05__HELPER__FOURTH_HAY_1__010__M__1": "O vinç şu saman balyasını taşıyor... İşe yarayabilir.",
"VO__AMICIA__CH05__HELPER__FOURTH_HAY_2__010__M__1": "Pekâlâ... kranı çevir, samanı ateşe ver ve var gücünle koş... Yapabilirsin...",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__053__M__1": "Hey...",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__056__M__1": "Ona bakma.",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__070__M__1": "Hugo, nöbet geçiriyordun.",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__085__M__1": "Annem senden...",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__110__M__1": "Hey hey hey... Biliyorum! Senin için iyi olanı yapacağım. Yapacağım.",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__170__M__1": "Onu yine kilit altına almak istiyorsun, bu aynı şey değil.",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__190__M__1": "\"Bu\", senin ve şu Vaudin'in Hugo'ya yaptıkları yüzünden oldu! Anne... Onu kapatıp bu işkenceyi sürdürmek onu öldürecek! O bir çocuk, o da bütün bunların kurbanı!",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__220__M__1": "Haklısın...",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__230__M__1": "Sadece anlamıyorsun.",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__250__M__1": "Bir bakacağım.",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__270__M__1": "Onunla birlikte ilgileneceğiz.",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__290__M__1": "Hey... İstersen içeri geri dönebilirsin...",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__310__M__1": "Seni yarı yolda bırakmam, söylemiştim... Şimdilik şu tekneyi hareket ettireceğiz. Ama henüz bitmedi.",
"VO__AMICIA__CH05__RTC__190_AFTER_CARNAGE__330__M__1": "Teşekkürler...",
"VO__AMICIA__CH05__RTC__195_TROUBLE__040__M__1": "Bu da ne?",
"VO__AMICIA__CH05__RTC__195_TROUBLE__080__M__1": "Rahat bırakın onu!",
"VO__AMICIA__CH05__RTC__200_EMBUSH__010__M__1": "İyi misin?",
"VO__AMICIA__CH05__RTC__200_EMBUSH__050__M__1": "Gidelim! Hemen!",
"VO__AMICIA__CH05__RTC__210_LANDING__020__M__1": "Dümene odaklan! Onları bana bırak!",
"VO__AMICIA__CH05__RTC__210_LANDING__050__M__1": "HAYIR!",
"VO__AMICIA__CH05__RTC__210_LANDING__070__M__1": "Joseph öldü! İçeri dön! Hugo'yu koru!",
"VO__AMICIA__CH05__RTC__210_LANDING__080__M__1": "Aah! Alçaklar!",
"VO__AMICIA__CH05__RTC__210_LANDING__100__M__1": "Bize yetiştiler! Tekneyi kurtarmalıyım!",
"VO__AMICIA__CH05__RTC__210_LANDING__120__M__1": "Önce onlar ölecek!",
"VO__AMICIA__CH05__RTC__210_LANDING__140__M__1": "Dövüşmek istemiyorsan içeri dön!",
"VO__AMICIA__CH05__RTC__220_THE_ROPE__002__M__1": "Orada dur!",
"VO__AMICIA__CH05__RTC__220_THE_ROPE__006__M__1": "Sana bir oyun göstereyim...",
"VO__AMICIA__CH05__RTC__220_THE_ROPE__095__M__1": "Hugo...",
"VO__AMICIA__CH05__RTC__220_THE_ROPE__100__M__1": "Sakin ol... Gittiler...",
"VO__AMICIA__CH05__RTC__220_THE_ROPE__120__M__1": "Hayır...",
"VO__AMICIA__CH05__RTC__220_THE_ROPE__165__M__1": "Açık denize çıksak nasıl olur, sadece ikimiz?",
"VO__AMICIA__CH05__RTC__220_THE_ROPE__170__M__1": "Hadi adanı bulalım.",
"VO__AMICIA__CH05__RTC__ARNAUD_CHASE__030__M__1": "Hayır!...",
"VO__AMICIA__CH05__RTC__ARNAUD_CHASE_ONOM__026__M__1": "Lanet olsun sana!",
"VO__ARNAUD__CH05__CHATTER__BIRD_NOISE__010__M__1": "Şurada bir şey var gibi.",
"VO__ARNAUD__CH05__CHATTER__BIRD_NOISE__020__M__1": "Çok gürültücüsün... Nereye gittin?",
"VO__ARNAUD__CH05__CHATTER__CHASE_CORNER__010__M__1": "Öldürmekte iyisin, bunu kabul ediyorum! Ama şimdi ne olacak?!",
"VO__ARNAUD__CH05__CHATTER__CHASE_DOWN_BOAT__011__M__1": "Manzaranın tadını mı çıkarıyorsun?",
"VO__ARNAUD__CH05__CHATTER__CHASE_FALL__030__M__1": "Öldürüyorsan, öldürülmeye de hazır ol. Adil olan bu, değil mi?",
"VO__ARNAUD__CH05__CHATTER__CHASE_FENCE__010__M__1": "Neden kaçıyorsun?! Senin için geldim, tıpkı istediğin gibi!",
"VO__ARNAUD__CH05__CHATTER__CHASE_SLOPE__009__M__1": "Ne oldu? Ölmek istiyorsun sanmıştım!",
"VO__ARNAUD__CH05__CHATTER__CHASE_SLOPE__011__M__1": "İşte böyle... Kendini göm. Tam sana göre. Yine de seni yakalarım!",
"VO__ARNAUD__CH05__CHATTER__CHASE_START__010__M__1": "Buradayım! Şimdi tam zırhlı bir savaşçıyla nasıl dövüşüyormuşsun göster bana!",
"VO__ARNAUD__CH05__CHATTER__CHASE_TREES__010__M__1": "Şu hâline bak... Ne kadar hazırlıksız...",
"VO__ARNAUD__CH05__CHATTER__EXIT_CAVE__010__M__1": "Kız buralarda bir yerde. Bakalım onu bulabilecek misin.",
"VO__ARNAUD__CH05__CHATTER__EXIT_CAVE__030__M__1": "Ailesinin icabına bakmak için. Bu onu dışarı çıkarır.",
"VO__ARNAUD__CH05__CHATTER__SEARCHING__030__M__1": "Buldun mu onu?",
"VO__ARNAUD__CH05__CHATTER__SEARCHING__050__M__1": "Mezarının tadını çıkarıyor musun bakalım hanımefendi? Pek iyi bir fikir değildi...",
"VO__ARNAUD__CH05__CHATTER__SEARCHING__080__M__1": "Burada mısın?!",
"VO__ARNAUD__CH05__CHATTER__SEARCHING__100__M__1": "Seni bulamayacağımı mı sanıyorsun?",
"VO__ARNAUD__CH05__CHATTER__SEARCHING_MORE__010__M__1": "Burada! Daha çok adam topla!",
"VO__ARNAUD__CH05__RTC__200_EMBUSH__030__M__1": "Demek meşhur \"sapanlı kız\" buymuş!",
"VO__ARNAUD__CH05__RTC__200_EMBUSH__040__M__1": "Ama görünüşe göre adamlarımı öldürme konusunda epey marifetlisin!",
"VO__ARNAUD__CH05__RTC__200_EMBUSH__055__M__1": "Evet. Onu bir dene.",
"VO__ARNAUD__CH05__RTC__200_EMBUSH__060__M__1": "Adamlar! Yakalayın onları!",
"VO__ARNAUD__CH05__RTC__220_THE_ROPE__004__M__1": "Ah, demek oyun bitti?",
"VO__ARNAUD__CH05__RTC__220_THE_ROPE__030__M__1": "Olduğun yerde kal yoksa sıradaki sensin!",
"VO__ARNAUD__CH05__RTC__220_THE_ROPE__040__M__1": "Son ders: pervasız olmak istiyorsan...",
"VO__ARNAUD__CH05__RTC__220_THE_ROPE__050__M__1": "...bundan daha iyi ol.",
"VO__ARNAUD__CH05__RTC__220_THE_ROPE__090__M__1": "Şuna bak... Takviye...",
"VO__ARNAUD__CH05__RTC__ARNAUD_CHASE__010__M__1": "O kadar kolay değil...",
"VO__ARNAUD__CH05__RTC__ARNAUD_CHASE__023__M__1": "Peki şimdi ne yapacaksın?",
"VO__ARNAUD__CH05__RTC__ARNAUD_CHASE__028__M__1": "Hm. Daha iyisini yapman gerek.",
"VO__BANDIT_N1__CH05__CHATTER__CROSSBOWS_LUCAS__040__M__1": "Seninle ve arkadaşlarınla tanışmak için sabırsızlanan birini tanıyorum!",
"VO__BANDIT_N1__CH05__CHATTER__CROSSBOWS_LUCAS__050__M__1": "Son sözün var mı?",
"VO__BANDIT_N1__CH05__CHATTER__KILL__010__M__1": "Hayır!",
"VO__BANDIT_N1__CH05__CHATTER__PRE_BOSSFIGHT__010__M__1": "Şu tekneye bin!",
"VO__BANDIT_N1__CH05__CHATTER__PRE_BOSSFIGHT__022__M__1": "Köşeye sıkıştı! Yakalayın!",
"VO__BANDIT_N1__CH05__CHATTER__PRE_BOSSFIGHT__070__M__1": "İlerleyin! Yalnız!",
"VO__BANDIT_N1__CH05__CHATTER__SHORE__020__M__1": "Sen kim olduğunu sanıyorsun?! Bağırsaklarını deşerim!",
"VO__BANDIT_S1__CH05__CHATTER__BELOW__030__M__1": "Ateş! Durdurun şu tekneyi!",
"VO__BANDIT_S1__CH05__CHATTER__BIRDS__020__M__1": "İşte!",
"VO__BANDIT_S1__CH05__CHATTER__CART_FIRE__010__M__1": "Hiçbir yere gitmiyorsun!",
"VO__BANDIT_S1__CH05__CHATTER__EXIT_CAVE__020__M__1": "Nereye gidiyorsun?",
"VO__BANDIT_S1__CH05__CHATTER__EXIT_CAVE__047__M__1": "Şunu çabuk halledelim kızım. Dışarı çık!",
"VO__BANDIT_S1__CH05__CHATTER__EXIT_CAVE__048__M__1": "Sana zarar vermem. Söz veriyorum.",
"VO__BANDIT_S1__CH05__CHATTER__KILL__020__M__1": "Bunun için öleceksin!",
"VO__BANDIT_S1__CH05__CHATTER__LEFT_GORGE__010__M__1": "Tam atış açım var!",
"VO__BANDIT_S1__CH05__CHATTER__MORE_LEFT_GORGE__010__M__1": "Onları köprüde yakalarız! Adamlara söyle, geliyorlar!",
"VO__BANDIT_S1__CH05__CHATTER__PLATFORM__010__M__1": "İşte! Buradalar!",
"VO__BANDIT_S1__CH05__CHATTER__PRE_BOSSFIGHT__040__M__1": "Saldırın! Kıza odaklanın, gerisini sonra alırız!",
"VO__BANDIT_S1__CH05__CHATTER__ROCKS_MOVE__010__M__1": "Arnaud'yu duydun! Durdur şu şeyi, hemen!",
"VO__BANDIT_S1__CH05__CHATTER__RUN_TWO__030__M__1": "Yakalayın onu!",
"VO__BANDIT_S1__CH05__CHATTER__SEARCHING__010__M__1": "Buradan!",
"VO__BANDIT_S1__CH05__CHATTER__SEARCHING__040__M__1": "Hayır! Ama hâlâ burada olmalı!",
"VO__BANDIT_S1__CH05__CHATTER__SEARCHING__060__M__1": "Kendini tuzağa düşürmek asla iyi bir fikir değildir!",
"VO__BANDIT_S1__CH05__CHATTER__SHORE__010__M__1": "Hadi millet! Sadece çılgın bir kız!",
"VO__BANDIT_S1__CH05__CHATTER__SHORE_CORNER__010__M__1": "Seni yakalayacağım, tatlım!",
"VO__BANDIT_S2__CH05__CHATTER__BELOW__015__M__1": "Nehir yukarı çıkın! Çevirin onları!",
"VO__BANDIT_S2__CH05__CHATTER__BRIDGE__010__M__1": "Hazır... Nişan al... Ateş!",
"VO__BANDIT_S2__CH05__CHATTER__CART_FIRE__040__M__1": "Kaçmadan önce yakalayın onları!",
"VO__BANDIT_S2__CH05__CHATTER__ROCKS__024__M__1": "Şu teknenin geçmesine izin vermeyin!",
"VO__BANDIT_S2__CH05__CHATTER__ROCKS_MOVE__030__M__1": "Onları durdurmalıyız!",
"VO__BANDIT_S2__CH05__CHATTER__RUN__020__M__1": "Kaçmasına izin vermeyin!",
"VO__BANDIT_S2__CH05__CHATTER__SEARCHING__020__M__1": "Hey! Arnaud!",
"VO__BEATRICE__CH05__CHATTER__AFTER_EXPLO__050__M__1": "Sağ salim ol!",
"VO__BEATRICE__CH05__CHATTER__BELOW__050__M__1": "Amicia! İçeri, yanımıza gel!",
"VO__BEATRICE__CH05__CHATTER__BELOW__070__M__1": "Akılsızlık etme!",
"VO__BEATRICE__CH05__CHATTER__BELOW__075__M__1": "Çok kalabalıklar!",
"VO__BEATRICE__CH05__CHATTER__BRAZIER_TWO__030__M__1": "Ona da öyle dedim. Yine de ikinizi de sağ salim görmek güzel!",
"VO__BEATRICE__CH05__CHATTER__CHAIN_BREAKS__040__M__1": "Cevap ver!",
"VO__BEATRICE__CH05__CHATTER__CROSSBOW_DONE__030__M__1": "Amicia! Ona bir yol aç!",
"VO__BEATRICE__CH05__CHATTER__CROSSBOW_DONE__050__M__1": "Oklarının ucuna bir Ignifer yerleştir!",
"VO__BEATRICE__CH05__CHATTER__CROSSBOW_DONE__060__M__1": "Onları ahşap olan her şeye at! Okların yanmaya devam etmesini sağlar!",
"VO__BEATRICE__CH05__CHATTER__CROSSING_NEXT__060__M__1": "Marsilya'da iyi olacaksın Hugo...",
"VO__BEATRICE__CH05__CHATTER__CROSSING_NEXT__080__M__1": "Magister Vaudin iyi bir adam değildi, biliyorum. Ama bu farklı olacak.",
"VO__BEATRICE__CH05__CHATTER__CROSSING_NEXT__100__M__1": "Şimdi değil Amicia!",
"VO__BEATRICE__CH05__CHATTER__FROM_THE_BOAT__010__M__1": "Lucas!",
"VO__BEATRICE__CH05__CHATTER__FROM_THE_BOAT__021__M__1": "Hayır! Onu gözden kaybettik!",
"VO__BEATRICE__CH05__CHATTER__INTRO_BOAT__060__M__1": "Seni aşağıda, akıntı yönünde bekleyeceğiz!",
"VO__BEATRICE__CH05__CHATTER__LEDGE_POI__025__M__1": "Aşağı inen bir yol var!",
"VO__BEATRICE__CH05__CHATTER__PATH_HELPER__010__M__1": "Ahşaptan yapılmış her şeye nişan al! Lucas'a bize ulaşacak açık bir yol yeter!",
"VO__BEATRICE__CH05__CHATTER__PATH_PROGRESS__050__M__1": "Başardın!...",
"VO__BEATRICE__CH05__CHATTER__PLATFORM__012__M__1": "Amicia! Hemen buraya gel!",
"VO__BEATRICE__CH05__CHATTER__POST_COLLAPSE__040__M__1": "İyi o, Hugo! Bak, ikisi de iyi!",
"VO__BEATRICE__CH05__CHATTER__TO_THE_SITE__040__M__1": "Geride dur!",
"VO__BEATRICE__CH05__CHATTER__UNDER_PONTOON__020__M__1": "İyi misin?!",
"VO__BEATRICE__CH05__HELPER__CART_FIRE_2__010__M__1": "Amicia! Bir Ignifer kullan! Onu yakıp geçer!",
"VO__BEATRICE__CH05__RTC__190_AFTER_CARNAGE__120__M__1": "Lucas, Hugo'yla kaptana gider misin?",
"VO__BEATRICE__CH05__RTC__190_AFTER_CARNAGE__135__M__1": "Tekneyi nasıl kullanacağınızı gösterir.",
"VO__BEATRICE__CH05__RTC__190_AFTER_CARNAGE__160__M__1": "Onu güvenli bir yere götürmeliyiz, Amicia.",
"VO__BEATRICE__CH05__RTC__190_AFTER_CARNAGE__180__M__1": "Ne olduğunu gördün! Düzen'in insanları ve ekipmanı var. Bununla nasıl başa çıkacaklarını biliyorlar!",
"VO__BEATRICE__CH05__RTC__190_AFTER_CARNAGE__200__M__1": "O BENİM çocuğum!",
"VO__BEATRICE__CH05__RTC__190_AFTER_CARNAGE__210__M__1": "Biz düşman değiliz, Amicia. Hugo'yu çok sevdiğini biliyorum... Ve aranızda gerçekten anlayamadığım bir bağ olduğunu da biliyorum... ama gözlerini açmalısın: orada olan şey yine olacak!",
"VO__BEATRICE__CH05__RTC__200_EMBUSH__025__M__1": "Arenada ne oldu? Ve kim bu Arnaud?",
"VO__BEATRICE__CH05__RTC__210_LANDING__060__M__1": "Neler oluyor?",
"VO__BEATRICE__CH05__RTC__210_LANDING__090__M__1": "İçeri gel!",
"VO__BEATRICE__CH05__RTC__210_LANDING__110__M__1": "Yeter! Seni öldürecekler!",
"VO__BEATRICE__CH05__RTC__220_THE_ROPE__080__M__1": "HUGO!",
"VO__BEATRICE__CH05__RTC__220_THE_ROPE__130__M__1": "Geri dön! Fazla vaktimiz yok!",
"VO__BEATRICE__CH05__RTC__220_THE_ROPE__140__M__1": "Ne yapıyorsun? Amicia!",
"VO__BEATRICE__CH05__RTC__220_THE_ROPE__142__M__1": "Amic... Amicia! ne yapıyorsun?",
"VO__BEATRICE__CH05__RTC__220_THE_ROPE__143__M__1": "Ne... Ne yapıyorsun...",
"VO__BEATRICE__CH05__RTC__220_THE_ROPE__145__M__1": "Dur... Dur...",
"VO__BOATMAN__CH05__CHATTER__BELOW__005__M__1": "Bu kötü!",
"VO__BOATMAN__CH05__CHATTER__BELOW__020__M__1": "Onlara ne yaptın?!",
"VO__BOATMAN__CH05__CHATTER__BRAZIER_TWO__040__M__1": "Böldüğüm için üzgünüm ama devam etmeliyiz ve yolumuzu lanet bir zincir kapatıyor!",
"VO__BOATMAN__CH05__CHATTER__CART_DROPS__005__M__1": "Eyvah... Yolu kapattılar!",
"VO__BOATMAN__CH05__CHATTER__CART_DROPS__010__M__1": "Tutun!",
"VO__BOATMAN__CH05__CHATTER__CART_FIRE__042__M__1": "Bize çıkartma yapacaklar!",
"VO__BOATMAN__CH05__CHATTER__CART_FIRE__048__M__1": "Lanet! Önümüzü kestiler! Şu arabayı ateşe ver!",
"VO__BOATMAN__CH05__CHATTER__CART_FIRE__049__M__1": "Şu şeyi yakmak için... ateş oklarını kullan!",
"VO__BOATMAN__CH05__CHATTER__CART_FIRE__050__M__1": "Daha fazlası geliyor!",
"VO__BOATMAN__CH05__CHATTER__CHAIN_BREAKS__061__M__1": "Tamam... zincir gitti ama iskeleler de gitti! Köprünün savaklarına yanaşacağım!",
"VO__BOATMAN__CH05__CHATTER__CRANK_PUZZLE__025__M__1": "Bize feribot lazım değil, o zincirin gevşemesi lazım!",
"VO__BOATMAN__CH05__CHATTER__CRANK_PUZZLE_BLOCK__020__M__1": "Şu iskelenin altı tam bir karmaşa! Zinciri sıkıştıran bir şey olmalı!",
"VO__BOATMAN__CH05__CHATTER__CROSSBOWS_LUCAS__010__M__1": "Sadece nişan al ve ateş et! Yeniden doldurmak için krank kolunu kullan!",
"VO__BOATMAN__CH05__CHATTER__CROSSED__030__M__1": "Bir şey görüyor musun?",
"VO__BOATMAN__CH05__CHATTER__CURRENT__010__M__1": "Yola çıktık!",
"VO__BOATMAN__CH05__CHATTER__INCOMING_BRIDGE__010__M__1": "O köprü tıklım tıklım!",
"VO__BOATMAN__CH05__CHATTER__INCOMING_BRIDGE__030__M__1": "Öldürebileceğinden fazla!",
"VO__BOATMAN__CH05__CHATTER__INCOMING_BRIDGE__050__M__1": "Sen delisin!",
"VO__BOATMAN__CH05__CHATTER__INTRO_BOAT__010__M__1": "Ah, kahretsin! Yetişmen gerekecek!",
"VO__BOATMAN__CH05__CHATTER__LAST_BRIDGE_FIRE__020__M__1": "Pekâlâ, pekâlâ... Hepsi etkileyiciydi, ama biraz sakinleşsen iyi olur!",
"VO__BOATMAN__CH05__CHATTER__LEDGE_POI__020__M__1": "Hey! Yukarıdalar!",
"VO__BOATMAN__CH05__CHATTER__PLATFORM_FIRE__020__M__1": "Tanrım... Bu bir delilik!",
"VO__BOATMAN__CH05__CHATTER__RIGHT_GORGE__010__M__1": "Sağda daha fazlası! Duvar elindeki her şeyi yolluyor! Lanet bir savaş başlattın!",
"VO__BOATMAN__CH05__CHATTER__ROCKS__020__M__1": "İyi misin?!",
"VO__BOATMAN__CH05__CHATTER__ROCKS__026__M__1": "Geliyorlar! Onları benden uzak tut!",
"VO__BOATMAN__CH05__CHATTER__ROCKS_RIGHT__010__M__1": "Sağda!",
"VO__BOATMAN__CH05__CHATTER__TO_THE_SITE__030__M__1": "Kahretsin!",
"VO__BOATMAN__CH05__HELPER__CART_FIRE_1__010__M__1": "Acele et! Şu şeyi yak da buradan çıkalım!",
"VO__BOATMAN__CH05__HELPER__CHAIN_BREAK_2__010__M__1": "Kırılacak bir şey için kirişlere bak! Karşı ağırlık orada olmalı!",
"VO__BOATMAN__CH05__RTC__190_AFTER_CARNAGE__010__M__1": "Aynı şeyin Guyenne'de de olduğunu duydum... Fareler, kanını zehirleyen Isırık. Bizden uzak görünüyordu...",
"VO__BOATMAN__CH05__RTC__190_AFTER_CARNAGE__240__M__1": "Enkaz... Hepsi burada birikmiş.",
"VO__BOATMAN__CH05__RTC__190_AFTER_CARNAGE__280__M__1": "Pekâlâ çocuklar, bunu size bırakıyorum.",
"VO__BOATMAN__CH05__RTC__195_TROUBLE__050__M__1": "Eyvah, bunlar Arnaud'nun adamları...",
"VO__BOATMAN__CH05__RTC__200_EMBUSH__028__M__1": "Şimdi başında büyük bir bela var. Gitmeliyiz.",
"VO__BOATMAN__CH05__RTC__210_LANDING__010__M__1": "Boğazdan çıktık! Akıntı güçleniyor!",
"VO__BOATMAN__CH05__RTC__210_LANDING__040__M__1": "İyi gidiyorsun hanımefendi! O arbalet senin için yapılmış!",
"VO__HUGO__CH05__CHATTER__AFTER_EXPLO__040__M__1": "Dikkatli ol!",
"VO__HUGO__CH05__CHATTER__BELOW__010__M__1": "Neler oluyor?",
"VO__HUGO__CH05__CHATTER__BRAZIER_TWO__010__M__1": "Amicia! Korktum!",
"VO__HUGO__CH05__CHATTER__CHAIN_BREAKS__060__M__1": "Nasıl geri dönecek?!",
"VO__HUGO__CH05__CHATTER__CLIFF_ECHO__090__M__1": "Amicia! Lucas!",
"VO__HUGO__CH05__CHATTER__CROSSING__009__M__1": "Geri dön!",
"VO__HUGO__CH05__CHATTER__CROSSING__011__M__1": "Korkunç olmuş olmalı...",
"VO__HUGO__CH05__CHATTER__CROSSING_NEXT__040__M__1": "Üzgünüm, Amicia...",
"VO__HUGO__CH05__CHATTER__CROSSING_NEXT__070__M__1": "Düzen'e gitmek istemiyorum!",
"VO__HUGO__CH05__CHATTER__FROM_THE_BOAT__005__M__1": "Lucas!",
"VO__HUGO__CH05__CHATTER__FROM_THE_BOAT__011__M__1": "Neredesin?",
"VO__HUGO__CH05__CHATTER__INTRO_BOAT__050__M__1": "Amicia! Bizi takip et!",
"VO__HUGO__CH05__CHATTER__LEDGE_POI__022__M__1": "Amicia! Geri dön!",
"VO__HUGO__CH05__CHATTER__LEDGE_POI__026__M__1": "Çabuk ol!",
"VO__HUGO__CH05__CHATTER__NEXT_CRANK_DONE__023__M__1": "Amicia!",
"VO__HUGO__CH05__CHATTER__POST_COLLAPSE__020__M__1": "İyi misin?!",
"VO__HUGO__CH05__CHATTER__POST_COLLAPSE__050__M__1": "Evet... ama fareler...",
"VO__HUGO__CH05__CHATTER__ROCKS__040__M__1": "Dikkatli ol Amicia!",
"VO__HUGO__CH05__CHATTER__TO_THE_SITE__020__M__1": "Uzaklaş, Amicia!",
"VO__HUGO__CH05__CHATTER__UNDER_PONTOON__060__M__1": "Her yerde ölü insanlar var! Çık oradan!",
"VO__HUGO__CH05__ONOM__CHAIN_BREAKS__010__M__1": "Amicia, hayır!",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__015__M__1": "Kuş... Bekle!...",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__040__M__1": "Vardık mı?",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__060__M__1": "Neden olmasın? Onları gitmiş yapmaz. Olanı geri almaz.",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__080__M__1": "Marsilya'ya gitmek istemiyorum. Daha çok insan ölecek! Biliyorsun!",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__090__M__1": "Hayır. Ada. Gitmem gereken yer orası. Düzeleceğim yer orası, Amicia! Onu bulabiliriz! Lütfen! Kimse dinlemiyor! Anneme kendimi kötü hissettiğimi söyledim ama Magister beni susturdu. Bunun testin bir parçası olduğunu söyledi... Annem ve Magister, bildiklerini sanıyorlar... ama bilmiyorlar. Ve insanlar ölüyor... benim yüzümden...",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__091__M__1": "Hayır. Ada. Gitmem gereken yer orası. Düzeleceğim yer orası, Amicia! Onu bulabiliriz! Lütfen!",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__092__M__1": "Kimse dinlemiyor! Anneme kendimi kötü hissettiğimi söyledim ama Magister beni susturdu.",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__093__M__1": "Bunun testin bir parçası olduğunu söyledi... Annem ve Magister, bildiklerini sanıyorlar... ama bilmiyorlar.",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__094__M__1": "Ve insanlar ölüyor... benim yüzümden...",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__150__M__1": "Evet!",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__300__M__1": "Hayır, sorun değil...",
"VO__HUGO__CH05__RTC__190_AFTER_CARNAGE__320__M__1": "Evet... Devam et...",
"VO__HUGO__CH05__RTC__220_THE_ROPE__020__M__1": "Amicia hayır!",
"VO__HUGO__CH05__RTC__220_THE_ROPE__060__M__1": "Ona yardım etmeliyiz!",
"VO__HUGO__CH05__RTC__220_THE_ROPE__110__M__1": "Ölmeyeceksin, değil mi?",
"VO__LUCAS__CH05__CHATTER__AFTER_EXPLO__020__M__1": "Bir yol bulacağım!",
"VO__LUCAS__CH05__CHATTER__BODY_FALLS__020__M__1": "Başardın! Feribotu sana getiriyorum!",
"VO__LUCAS__CH05__CHATTER__BRAZIER_TWO__077__M__1": "Buradaki krank zincire bağlı!",
"VO__LUCAS__CH05__CHATTER__BRIDGE_VISTA__020__M__1": "Deniyorum...",
"VO__LUCAS__CH05__CHATTER__CART_HOLE__020__M__1": "Dikkatli ol.",
"VO__LUCAS__CH05__CHATTER__CART_MOVED__010__M__1": "Eee? Bir geçit var mı?",
"VO__LUCAS__CH05__CHATTER__CART_MOVED_HOLE__010__M__1": "Deliğe ulaşabiliyor musun?",
"VO__LUCAS__CH05__CHATTER__CHAIN__014__M__1": "Anladım!",
"VO__LUCAS__CH05__CHATTER__CHAIN_BREAKS__020__M__1": "İncindin mi?!",
"VO__LUCAS__CH05__CHATTER__CLIFF_ECHO__010__M__1": "Epey yüksekteyiz...",
"VO__LUCAS__CH05__CHATTER__CLIFF_ECHO__015__M__1": "Hâlâ bizi bekliyorlar.",
"VO__LUCAS__CH05__CHATTER__CLIFF_ECHO__030__M__1": "Sence bizi duyarlar mı?",
"VO__LUCAS__CH05__CHATTER__CLIFF_ECHO__050__M__1": "Beni öldürmeye çalışan şeye bağlı. Yani... birlikte mi?",
"VO__LUCAS__CH05__CHATTER__CLIFF_ECHO__070__M__1": "EEEHOOO!",
"VO__LUCAS__CH05__CHATTER__COLLAPSING__020__M__1": "Bu da ne be?!",
"VO__LUCAS__CH05__CHATTER__COLLAPSING__040__M__1": "Çoktan burada mılar?!",
"VO__LUCAS__CH05__CHATTER__CRANK_COMPANION__010__M__1": "Dayanmaz, bir karşı ağırlık olmalı... Sen sapanla ilgilenirken ben vinci hâlledebilirim.",
"VO__LUCAS__CH05__CHATTER__CRANK_COMPANION__030__M__1": "İyi şanslar...",
"VO__LUCAS__CH05__CHATTER__CRANK_IDLE_2__010__M__1": "Hıı... Hâlâ buradayım! Geçmem için sana ihtiyacım var...",
"VO__LUCAS__CH05__CHATTER__CRANK_LUCAS_GO__020__M__1": "Koca bir şehri yerle bir ettiler...",
"VO__LUCAS__CH05__CHATTER__CRANK_MOVE__010__M__1": "İşe yarıyor! Saman hareket ediyor!",
"VO__LUCAS__CH05__CHATTER__CRANK_PUZZLE__020__M__1": "Bir feribotu kumanda ediyor!",
"VO__LUCAS__CH05__CHATTER__CRANK_PUZZLE__027__M__1": "Bizim tarafta hiçbir şey yok!",
"VO__LUCAS__CH05__CHATTER__CRANK_PUZZLE__050__M__1": "Sıkışmış!",
"VO__LUCAS__CH05__CHATTER__CRANK_PUZZLE_BLOCK__040__M__1": "Oraya nasıl ineceğiz?",
"VO__LUCAS__CH05__CHATTER__CRANK_SELF__020__M__1": "Etrafımız sarıldı...",
"VO__LUCAS__CH05__CHATTER__CRANK_SELF__040__M__1": "Evet... molozu oraya buraya taşıyabiliyorlarsa o zaman... Ve bunun bir krankı var!",
"VO__LUCAS__CH05__CHATTER__CROSSBOW_DONE__010__M__1": "Ben... Tir tir titriyorum... Teşekkürler!",
"VO__LUCAS__CH05__CHATTER__CROSSBOW_DONE__020__M__1": "Çok fazla fare var! Sana ulaşamıyorum!",
"VO__LUCAS__CH05__CHATTER__CROSSBOW_DONE__080__M__1": "Anladım!",
"VO__LUCAS__CH05__CHATTER__CROSSBOWS_LUCAS__020__M__1": "Bırakın gideyim! Bırakın gideyim!",
"VO__LUCAS__CH05__CHATTER__CROSSING_NEXT__010__M__1": "İyi misin? Hazır mısın?",
"VO__LUCAS__CH05__CHATTER__CROSSING_NEXT__030__M__1": "Acele etme... Hazır olunca söyle...",
"VO__LUCAS__CH05__CHATTER__FIRST_HAY_ALT__010__M__1": "Amicia! Ateş sönüyor! Saman balyasını yeniden yak! Çabuk!",
"VO__LUCAS__CH05__CHATTER__GOING_BACK__020__M__1": "Onu yarı yolda bırakmadığımız sürece...",
"VO__LUCAS__CH05__CHATTER__HAY_FALLS__020__M__1": "Bunu yakala! Onunla yere vur! Şu merdivenlere git!",
"VO__LUCAS__CH05__CHATTER__HAY_FALLS__035__M__1": "Acele et! Uzun sürmez!",
"VO__LUCAS__CH05__CHATTER__INTRO_BOAT__030__M__1": "N-ne?!",
"VO__LUCAS__CH05__CHATTER__INTRO_BOAT2__050__M__1": "Şey, umarım Joseph durmanın bir yolunu bulur...",
"VO__LUCAS__CH05__CHATTER__ISLAND_FINAL__020__M__1": "Bir trajedi... Hiç düşünmemiştim...",
"VO__LUCAS__CH05__CHATTER__ISLAND_FINAL__040__M__1": "Nasıl...?",
"VO__LUCAS__CH05__CHATTER__ISLAND_FINAL__060__M__1": "Peki ya annen?",
"VO__LUCAS__CH05__CHATTER__ISLAND_FINAL__080__M__1": "O... benim Magistram...",
"VO__LUCAS__CH05__CHATTER__LEDGE_POI__005__M__1": "Tanrım... Yukarıdan daha da beter...",
"VO__LUCAS__CH05__CHATTER__LEDGE_POI__040__M__1": "Ne büyük bir kaos...",
"VO__LUCAS__CH05__CHATTER__LEDGE_TREMOR__040__M__1": "Onları görmüyorum!",
"VO__LUCAS__CH05__CHATTER__LUCAS_2ND_RUN__020__M__1": "Pekâlâ!",
"VO__LUCAS__CH05__CHATTER__LUCAS_2ND_RUN__050__M__1": "Şimdi!",
"VO__LUCAS__CH05__CHATTER__LUCAS_2ND_RUN__090__M__1": "Ha... Teşekkürler... Hız kazanmama yardımcı oluyor... Sanırım.",
"VO__LUCAS__CH05__CHATTER__LUCAS_STUCK_LOCK__010__M__1": "Sıkıştım! Bu şey kilitli!",
"VO__LUCAS__CH05__CHATTER__MIDDLE__030__M__1": "Pyrite! Bir mineral! Yolda biraz almıştım!",
"VO__LUCAS__CH05__CHATTER__MIDDLE__052__M__1": "Kıvılcım bekliyordum ama bunu değil...",
"VO__LUCAS__CH05__CHATTER__MIDDLE__056__M__1": "Ona göz kulak ol!",
"VO__LUCAS__CH05__CHATTER__MIDDLE_CRANK__021__M__1": "Acele etme! Buraya tırmanmadıkları sürece...",
"VO__LUCAS__CH05__CHATTER__MOVING_CRANE_2__020__M__1": "Yine de buna değebilir!",
"VO__LUCAS__CH05__CHATTER__MOVING_CRANE_2__040__M__1": "Evet... Neden öyle hissettiğini anlayabiliyorum...",
"VO__LUCAS__CH05__CHATTER__MOVING_CRANE_3__010__M__1": "Amicia, aklından geçeni bana söylemelisin.",
"VO__LUCAS__CH05__CHATTER__MOVING_CRANE_3__030__M__1": "O ada. Seni tanırım.",
"VO__LUCAS__CH05__CHATTER__NEXT_CRANK__006__M__1": "Orada tut!",
"VO__LUCAS__CH05__CHATTER__NEXT_CRANK__020__M__1": "Geliyorum!",
"VO__LUCAS__CH05__CHATTER__NEXT_CRANK_DONE__005__M__1": "Öf!... Bırakabilirsin!",
"VO__LUCAS__CH05__CHATTER__NEXT_CRANK_DONE__010__M__1": "Teşekkürler...",
"VO__LUCAS__CH05__CHATTER__NEXT_CRANK_DONE__030__M__1": "Annen orada.",
"VO__LUCAS__CH05__CHATTER__NEXT_CRANK_DONE__060__M__1": "Hadi seni çabucak şu tekneye geri götürelim. O vinci yine kullanırız.",
"VO__LUCAS__CH05__CHATTER__NEXT_CRANK_RELEASE__020__M__1": "Tamam! Ne zaman bırakacağımı söyle!",
"VO__LUCAS__CH05__CHATTER__PATH_PROGRESS__010__M__1": "Teşekkürler! Bu işimi görür!",
"VO__LUCAS__CH05__CHATTER__PATH_PROGRESS__020__M__1": "Neredeyse bir geçit görüyorum!",
"VO__LUCAS__CH05__CHATTER__PATH_PROGRESS__040__M__1": "Evet! Harika... Yola çıkıyorum!",
"VO__LUCAS__CH05__CHATTER__POST_COLLAPSE__010__M__1": "Bu gerçekten çok yakındı...",
"VO__LUCAS__CH05__CHATTER__POST_COLLAPSE__070__M__1": "Şey... Nereden başlıyoruz?",
"VO__LUCAS__CH05__CHATTER__PUSH_BOAT__010__M__1": "Bak... Gövdenin altına bir sürü enkaz sıkışmış. Onu çekip çıkaralım mı?",
"VO__LUCAS__CH05__CHATTER__PUSH_BOAT__040__M__1": "Şey, deneyelim...",
"VO__LUCAS__CH05__CHATTER__PUSH_BOAT__060__M__1": "Evet...",
"VO__LUCAS__CH05__CHATTER__STICK_BOAT__020__M__1": "Birkaç saat, derim... Dinle, endişeli olduğunu biliyorum ama...",
"VO__LUCAS__CH05__CHATTER__STICK_BOAT__040__M__1": "Amicia, hepsi Vaudin gibi olamaz.",
"VO__LUCAS__CH05__CHATTER__STICK_DIRECT__010__M__1": "Aferin! Beni sana ulaştıracak bir şey görüyor musun?!",
"VO__LUCAS__CH05__CHATTER__STICK_LIGHT__010__M__1": "Evet! Güzel atış!",
"VO__LUCAS__CH05__CHATTER__STICK_LIGHT__012__M__1": "Pekâlâ, sıra bende... Tanrım...",
"VO__LUCAS__CH05__CHATTER__STICK_LIGHT__014__M__1": "Evet! Sadece fare bunlar, değil mi? Fareleri bilirim... Evet... Peki neyi bekliyorum?... Hadi! Hadi! Yah!",
"VO__LUCAS__CH05__CHATTER__STICK_LIGHT__016__M__1": "Düşünmüyorum!",
"VO__LUCAS__CH05__CHATTER__STICK_LIGHT_OK__020__M__1": "Teşekkürler! İyi bir motivasyon gibisi yok...",
"VO__LUCAS__CH05__CHATTER__TO_NEXT_CRANK__006__M__1": "Harika!",
"VO__LUCAS__CH05__CHATTER__TO_NEXT_CRANK__011__M__1": "Evet! Şu saman balyasını bana doğru taşımayı dene! Onu yakabilirim!",
"VO__LUCAS__CH05__CHATTER__TO_NEXT_CRANK__020__M__1": "Pekâlâ! Samanı bekliyorum! Onu yakarım!",
"VO__LUCAS__CH05__CHATTER__TO_SOUVENIR_CLIFF__020__M__1": "Yukarı çıktığımız sürece... güvendeyiz...",
"VO__LUCAS__CH05__CHATTER__WOODS_SOUVENIR__020__M__1": "Sessiz.",
"VO__LUCAS__CH05__CHATTER__WOODS_SOUVENIR__040__M__1": "Panik yapma! Sadece... böğüren bir geyik, sanırım...",
"VO__LUCAS__CH05__CHATTER__WOODS_SOUVENIR__060__M__1": "Çiftleşme mevsimi çoktan başlamış olmalı.",
"VO__LUCAS__CH05__CHATTER__WOODS_SOUVENIR__080__M__1": "Doğa yolundan dönmez. Yüzleştiğimiz kaos da bir şekilde onun bir parçası.",
"VO__LUCAS__CH05__CHATTER__WOODS_SOUVENIR__100__M__1": "Doğru.",
"VO__LUCAS__CH05__CHATTER__WOODS_SOUVENIR__120__M__1": "Önden buyur...",
"VO__LUCAS__CH05__HELPER__CART_LUCAS_1__010__M__1": "O arabada yardım edebilirim, biliyorsun...",
"VO__LUCAS__CH05__HELPER__CART_LUCAS_2__010__M__1": "İstersen o arabayı hâlledebilirim...",
"VO__LUCAS__CH05__HELPER__CART_MOVE_1__010__M__1": "Sanırım o araba yolu kesiyor, Amicia.",
"VO__LUCAS__CH05__HELPER__CART_MOVE_2__010__M__1": "Amicia, şu arabayı kımıldatmalıyız, deliği kapatıyor.",
"VO__LUCAS__CH05__HELPER__FIRST_CRANK_1__010__M__1": "Yakacak hâlâ biraz saman var! Onu taşımak için vinci kullanabiliriz!",
"VO__LUCAS__CH05__HELPER__FIRST_CRANK_2__010__M__1": "Hazır olunca söyle, kranı ben çalıştırayım!",
"VO__LUCAS__CH05__HELPER__FIRST_HAY_1__010__M__1": "Amicia! Sanırım o saman balyası karşıya geçmemize yardımcı olabilir!",
"VO__LUCAS__CH05__HELPER__FIRST_HAY_2__010__M__1": "Şu samana bir Ignifer at!",
"VO__LUCAS__CH05__HELPER__LUCAS_CHAIN_1__010__M__1": "Amicia! Şu çit yolumdayken aşağı atlayamam!",
"VO__LUCAS__CH05__HELPER__LUCAS_CHAIN_2__010__M__1": "Şu kilidi kırabilir misin, lütfen?",
"VO__LUCAS__CH05__HELPER__SECOND_HAY_1__010__M__1": "Sonraki vinç epey uzak! Büyük bir ateş lazım olacak!",
"VO__LUCAS__CH05__HELPER__SECOND_HAY_2__010__M__1": "Saman yanarken üstüne biraz katran atmayı dene! Ateşi güçlendirir!",
"VO__LUCAS__CH05__HELPER__STICK_THROW_1__010__M__1": "Senin yardımın olmadan şu farelerin arasından geçemem!",
"VO__LUCAS__CH05__HELPER__STICK_THROW_2__010__M__1": "Amicia! Şu çubuklar! Bana bir tane atabilir misin?!",
"VO__LUCAS__CH05__HELPER__THIRD_HAY_1__010__M__1": "Diğer tarafa geçmek için ışık lazım olacak!",
"VO__LUCAS__CH05__HELPER__THIRD_HAY_2__010__M__1": "Samanı ateşe ver, Amicia!",
"VO__LUCAS__CH05__RTC__190_AFTER_CARNAGE__025__M__1": "Hey... Rüya görüyordun...",
"VO__LUCAS__CH05__RTC__190_AFTER_CARNAGE__050__M__1": "Hayır, ama uzun sürmemeli.",
"VO__LUCAS__CH05__RTC__190_AFTER_CARNAGE__130__M__1": "Tabii...",
"VO__LUCAS__CH05__RTC__190_AFTER_CARNAGE__140__M__1": "Bize denizci düğümleri öğretebilir mi diye sorarım... Ve belki dümeni tutmamıza izin verir?",
"VO__LUCAS__CH05__RTC__190_AFTER_CARNAGE__260__M__1": "Sanırım sorunu görüyorum!",
"VO__LUCAS__CH05__RTC__195_TROUBLE__030__M__1": "İmdat!",
"VO__LUCAS__CH05__RTC__200_EMBUSH__020__M__1": "Evet... Sanırım kanım dondu... Ama ıskalamadığın için teşekkürler... Arenadakilerle aynı gruptandılar, Amicia.",
"VO__LUCAS__CH05__RTC__220_THE_ROPE__010__M__1": "Amicia!",
}
