# -*- coding: utf-8 -*-
# CH03 VO (kasaplar mahallesi). onom/EMPTY atlanir.
# Ton: Amicia siddete suruklenir (sert ic monolog). Lucas onu dizginler.
# nightshade->kopek uzumu, Stupefacio/Exstinguis korunur, the Beast->Canavar,
# saltpeter->guhercile, ballista->balista, herbalist->sifaci.
T = {
"VO__ALCHEMIST__CH03__RTC__122_GUILT__060__M__1": "Evet. Çoktan yeterince vakit kaybettik.",
"VO__ALCHEMIST__CH03__RTC__122_GUILT__090__M__1": "İyi. Emin ellerde.",
"VO__ALCHEMIST__CH03__RTC__122_GUILT__100__M__1": "En iyi ellerde, emin olabilirsin.",
"VO__AMICIA__CH03__CHATTER__1ST_TOWER_REMPART__020__M__1": "Muhafız. Bir şey yapamam. Sessizce geçelim.",
"VO__AMICIA__CH03__CHATTER__2ND_STREET__030__M__1": "Bu da ne...?",
"VO__AMICIA__CH03__CHATTER__2ND_TOWER_REMPART__020__M__1": "Çok yakın... Aşağı inmenin bir yolunu bulmalı.",
"VO__AMICIA__CH03__CHATTER__2ND_TOWER_REMPART__040__M__1": "Annem çok öfkelenecek... Herkesi hayal kırıklığına uğrattım...",
"VO__AMICIA__CH03__CHATTER__2ND_TOWER_SUCCESSFUL__020__M__1": "Öyleyiz...",
"VO__AMICIA__CH03__CHATTER__ABOUT_BALLISTA__010__M__1": "Ne?",
"VO__AMICIA__CH03__CHATTER__ABOUT_BALLISTA__020__M__1": "Balista mı?!",
"VO__AMICIA__CH03__CHATTER__ABOUT_BALLISTA__030__M__1": "Ve hepsini kör edecek kadar duman çıkar...",
"VO__AMICIA__CH03__CHATTER__ABOUT_BALLISTA__040__M__1": "Daha iyi bir fikrimiz yok. Hadi şu balistayı indirelim!",
"VO__AMICIA__CH03__CHATTER__ABOUT_BALLISTA__046__M__1": "Şu kranka geçelim...",
"VO__AMICIA__CH03__CHATTER__AFTER_SLIDE__015__M__1": "Eyvah, sakın deme...",
"VO__AMICIA__CH03__CHATTER__AFTER_SLIDE__030__M__1": "Nefesini tut dedim!",
"VO__AMICIA__CH03__CHATTER__AFTER_SLIDE__050__M__1": "Ah Lucas...",
"VO__AMICIA__CH03__CHATTER__ALLEY_MURDER__050__M__1": "Birini öldürüyorlar...",
"VO__AMICIA__CH03__CHATTER__AMICIA_FAKELOOKING_4__010__M__1": "Hadi... Hadi!",
"VO__AMICIA__CH03__CHATTER__AMICIA_FAKELOOKING_4__020__M__1": "Ne rezalet!",
"VO__AMICIA__CH03__CHATTER__AMICIA_LOOKING_1__010__M__1": "Silahlar!... Kılıçlar... bıçaklar...",
"VO__AMICIA__CH03__CHATTER__AMICIA_LOOKING_1__020__M__1": "Sapan yok... Başka yere bakalım.",
"VO__AMICIA__CH03__CHATTER__AMICIA_LOOKING_2__010__M__1": "O ne? Hmm... Hayır...",
"VO__AMICIA__CH03__CHATTER__AMICIA_LOOKING_2__020__M__1": "Lütfen... lütfen... Her an içeri girebilirler...",
"VO__AMICIA__CH03__CHATTER__AMICIA_LOOKING_3__010__M__1": "Belki burada... Lütfen...",
"VO__AMICIA__CH03__CHATTER__AMICIA_LOOKING_3__020__M__1": "Bir yerlerde olmalı!",
"VO__AMICIA__CH03__CHATTER__AMICIA_LOOKING_5__010__M__1": "Nereye koydular acaba...",
"VO__AMICIA__CH03__CHATTER__AMICIA_LOWER__010__M__1": "Gidelim...",
"VO__AMICIA__CH03__CHATTER__AMICIA_LOWER__020__M__1": "Ah, bu şey... ağır!",
"VO__AMICIA__CH03__CHATTER__AMICIA_LOWER__040__M__1": "Tabii ki hayır...",
"VO__AMICIA__CH03__CHATTER__AMICIA_RELEASE__005__M__1": "Ne?!",
"VO__AMICIA__CH03__CHATTER__AMICIA_RELEASE__010__M__1": "Bir karşı ağırlık var!",
"VO__AMICIA__CH03__CHATTER__AMICIA_RELEASE__030__M__1": "Evet...",
"VO__AMICIA__CH03__CHATTER__ANOTHER_SOLDIER_STREET__010__M__1": "Eğil! Bir tane daha!",
"VO__AMICIA__CH03__CHATTER__ANOTHER_WAVE__020__M__1": "Ah öyle mi?! Gel o zaman! Nasıl yapacağını göster bana!",
"VO__AMICIA__CH03__CHATTER__ANOTHER_WAVE__030__M__1": "Hepsi bu mu?! Hadi!",
"VO__AMICIA__CH03__CHATTER__ANOTHER_WAY__090__M__1": "Hayır... Hugo'nun bekleyecek hâli yok!",
"VO__AMICIA__CH03__CHATTER__ARMING_BALLISTA__010__M__1": "Peki, kapıları ne zaman açacaksın?",
"VO__AMICIA__CH03__CHATTER__ARMING_BALLISTA__030__M__1": "Ne? Ama... geçecek mi onu bile bilmiyoruz!",
"VO__AMICIA__CH03__CHATTER__BACK_IN_POND__010__M__1": "Vay.",
"VO__AMICIA__CH03__CHATTER__BALLISTA_CART_OK__010__M__1": "Hadi kapıya götürelim, çabuk.",
"VO__AMICIA__CH03__CHATTER__BARN_APPROACH__010__M__1": "Buradan geliyordu... Lütfen hayatta ol... Lütfen...",
"VO__AMICIA__CH03__CHATTER__BLOOD_POND__020__M__1": "Hangi akla hizmet bunu düşünüyorsun ki?!",
"VO__AMICIA__CH03__CHATTER__BLOOD_POND__040__M__1": "Ama bu... beni KENDİMİNKİNİ kaybetmeye yaklaştırıyor!",
"VO__AMICIA__CH03__CHATTER__BLOOD_POND__060__M__1": "Kusacağım.",
"VO__AMICIA__CH03__CHATTER__BLOOD_POND__070__M__1": "Neredeyse vardık... Şimdi kayma sakın.",
"VO__AMICIA__CH03__CHATTER__BLOOD_POND_EXIT__010__M__1": "Aman Tanrım... Öf...",
"VO__AMICIA__CH03__CHATTER__BULLIES_DEAD__010__M__1": "Sana zarar verdiler mi?!",
"VO__AMICIA__CH03__CHATTER__BULLIES_DEAD__030__M__1": "Bu dersini aldı... Uyuz köpekler!",
"VO__AMICIA__CH03__CHATTER__BULLYING_LUCAS_STOP__010__M__1": "İstediğiniz ben miyim?!",
"VO__AMICIA__CH03__CHATTER__BUTCHER_RAIN_NIGHTSHADE__030__M__1": "Pis kokuyor...",
"VO__AMICIA__CH03__CHATTER__BUTCHER_RAIN_OUTRO__020__M__1": "Evet, gidelim.",
"VO__AMICIA__CH03__CHATTER__BY_HERSELF_1__020__M__1": "Lucas'ı al. Köpek üzümünü al. Çık. Seni durdurmaya çalışanı öldür.",
"VO__AMICIA__CH03__CHATTER__CAPTAIN_CHURCH__020__M__1": "Çoktan kaybettikleri bir savaş...",
"VO__AMICIA__CH03__CHATTER__CART_BLOCK__005__M__1": "Yolda bir araba var...",
"VO__AMICIA__CH03__CHATTER__CART_BLOCK__010__M__1": "Devam etmeliyiz. Bana bunda yardım et.",
"VO__AMICIA__CH03__CHATTER__CART_MOVE_BALLISTA__010__M__1": "Tek bir atış hakkımız var...",
"VO__AMICIA__CH03__CHATTER__CART_MOVE_BALLISTA__030__M__1": "Başarısız olursak... Hugo yalnız kalır ve...",
"VO__AMICIA__CH03__CHATTER__CART_MOVE_BALLISTA__050__M__1": "Ve bunu istemiyoruz...",
"VO__AMICIA__CH03__CHATTER__CART_MOVE_BALLISTA_OK__010__M__1": "Burada duralım.",
"VO__AMICIA__CH03__CHATTER__CART_OK__010__M__1": "Güzel!",
"VO__AMICIA__CH03__CHATTER__CART_ROLL__010__M__1": "Dur, hayır!",
"VO__AMICIA__CH03__CHATTER__CART_ROLL__030__M__1": "O da ne?!",
"VO__AMICIA__CH03__CHATTER__CART_ROLL__036__M__1": "Eyvah! HAYIR! Onlar olmasın! Yine olmasın!",
"VO__AMICIA__CH03__CHATTER__CART_ROLL__070__M__1": "Biliyordum... Çoktan yayılıyorlar! Şimdi yine aralarından geçmemiz gerekecek...",
"VO__AMICIA__CH03__CHATTER__CART_ROLL__090__M__1": "Evet... Evet.",
"VO__AMICIA__CH03__CHATTER__CART_STOP__010__M__1": "Bu kadar yeter!",
"VO__AMICIA__CH03__CHATTER__CHEST_TOOL__002__M__1": "Bir alet...",
"VO__AMICIA__CH03__CHATTER__CHEST_TOOL__010__M__1": "Bir tezgâh bulsam ekipmanımı geliştirebilirim.",
"VO__AMICIA__CH03__CHATTER__CHURCH_EMPTY_IDLE__020__M__1": "Artık hiç umursamıyorlar Lucas! Kasaplar bunlar! Ne bekliyordun ki?",
"VO__AMICIA__CH03__CHATTER__CHURCH_EMPTY_IDLE__030__M__1": "Bir kiliseyi kirletmek artık onlara ağır gelmiyor.",
"VO__AMICIA__CH03__CHATTER__CLIMB_WINDOW__010__M__1": "Vaay! Tanrım, ne kadar yüksek...",
"VO__AMICIA__CH03__CHATTER__CLIMB_WINDOW__030__M__1": "Bir bakıma... Gel!",
"VO__AMICIA__CH03__CHATTER__CLIMB_WINDOW__050__M__1": "Şşş... Sakin ol! Gel...",
"VO__AMICIA__CH03__CHATTER__CRANK_DROP__010__M__1": "Ha... Öf...",
"VO__AMICIA__CH03__CHATTER__CRANK_DROP__030__M__1": "Pardon...",
"VO__AMICIA__CH03__CHATTER__CRANK_RELEASE_OK__010__M__1": "İşte böyle. İşaretimle bırak.",
"VO__AMICIA__CH03__CHATTER__CRANK_RELEASE_OK__020__M__1": "Şimdi! Hadi!",
"VO__AMICIA__CH03__CHATTER__CRANK_RELEASE_OK__040__M__1": "Hadi! Daha hızlı!",
"VO__AMICIA__CH03__CHATTER__CRANK_USE__005__M__1": "Hadi, işe koyulalım.",
"VO__AMICIA__CH03__CHATTER__CRANK_USE__010__M__1": "Bir sorunumuz olacak...",
"VO__AMICIA__CH03__CHATTER__CRANK_USE__030__M__1": "Bu şeyde fren yok... O yüzden koşmamız gerekecek.",
"VO__AMICIA__CH03__CHATTER__CROSSING_RATS_AGAIN__010__M__1": "Hadi... Nerede o lanet köpek üzümü?!",
"VO__AMICIA__CH03__CHATTER__CRUEL_SOLDIERS_IDLE__010__M__1": "Kan dökmek... Bildikleri tek şey bu...",
"VO__AMICIA__CH03__CHATTER__CRUEL_SOLDIERS_IDLE__030__M__1": "Kılıçlı et yığınından başka bir şey değiller.",
"VO__AMICIA__CH03__CHATTER__DEAD_ANIMALS__020__M__1": "Tıpkı arena gibi... Burası baştan aşağı bir yem.",
"VO__AMICIA__CH03__CHATTER__DEAD_BLACKSMITH__010__M__1": "Burada bir ceset var!",
"VO__AMICIA__CH03__CHATTER__DEAD_BLACKSMITH__030__M__1": "Hayır...",
"VO__AMICIA__CH03__CHATTER__DEAD_BLACKSMITH__040__M__1": "Bıçaklanmış. Muhtemelen askerler.",
"VO__AMICIA__CH03__CHATTER__DEPOT_ENTRANCE__010__M__1": "Burada.",
"VO__AMICIA__CH03__CHATTER__ENTER_SQUARE__010__M__1": "Şehir kapısı!",
"VO__AMICIA__CH03__CHATTER__ENTERING_TAVERN__010__M__1": "Tanrım... Kaynıyor burası...",
"VO__AMICIA__CH03__CHATTER__EVIL_SOLDIERS_IDLE__020__M__1": "Aptalca. O 'Canavar' beyinsizin teki.",
"VO__AMICIA__CH03__CHATTER__EXTERIOR__001__M__1": "Öf... Evet...",
"VO__AMICIA__CH03__CHATTER__EXTERIOR__005__M__1": "Bak... Fare yok...",
"VO__AMICIA__CH03__CHATTER__EXTERIOR__020__M__1": "Duvarları umursamıyorlar. Yiyeceği umursuyorlar.",
"VO__AMICIA__CH03__CHATTER__EXTERIOR__040__M__1": "Hey, az önce hatırladım... Vaudin'in laboratuvarında üzerinde bir ada olan bir fresk vardı! Onu gördüm Lucas! Ya o?! Vaudin onu biliyor olmalı!",
"VO__AMICIA__CH03__CHATTER__EXTERIOR__060__M__1": "Teşekkürler... Şimdi... Annem şifacının bir ormanın kıyısında yaşadığını söyledi. Yakın olmalıyız.",
"VO__AMICIA__CH03__CHATTER__EXTINGUIS_BAG_TUTO__006__M__1": "Elbette istiyorlar.",
"VO__AMICIA__CH03__CHATTER__EXTINGUIS_BAG_TUTO_OK__015__M__1": "O toz da ne?",
"VO__AMICIA__CH03__CHATTER__EXTINGUIS_BAG_TUTO_OK__030__M__1": "Bilmek güzel.",
"VO__AMICIA__CH03__CHATTER__EXTINGUIS_TUTO_EXPLANATION__020__M__1": "Exstinguis... Pekâlâ.",
"VO__AMICIA__CH03__CHATTER__EXTINGUIS_USE__010__M__1": "Tamam...",
"VO__AMICIA__CH03__CHATTER__EXTINGUIS_USE__030__M__1": "Biliyorum...",
"VO__AMICIA__CH03__CHATTER__EXTINGUISH_REMINDER__020__M__1": "Evet... Evet!",
"VO__AMICIA__CH03__CHATTER__FAKE_NIGHTSHADE__010__M__1": "Hmmm... Bunu tanıyorum... papatya...",
"VO__AMICIA__CH03__CHATTER__FAKE_NIGHTSHADE__030__M__1": "Evet... Karnımız ağrıdığında annem bize bundan verirdi. Bunun başımıza gelebilecek en kötü şeylerden biri olduğu zamanlarda.",
"VO__AMICIA__CH03__CHATTER__FIRE_EXTINGUISHED__010__M__1": "Bir iş tamam...",
"VO__AMICIA__CH03__CHATTER__FIRE_HAM__010__M__1": "Şimdi ateş...",
"VO__AMICIA__CH03__CHATTER__FIRE_HAM__020__M__1": "Evet...",
"VO__AMICIA__CH03__CHATTER__FIRST_KILL_EXTINGUIS__006__M__1": "Bunu daha önce de yaptık, ama hâlâ...",
"VO__AMICIA__CH03__CHATTER__FIRST_KILL_EXTINGUIS__010__M__1": "Evet... Yine kullanmam gerekebilir. Her neyse... sağ ol.",
"VO__AMICIA__CH03__CHATTER__FIRST_MEMORY__010__M__1": "Bir mezar... tam bir evin yanında...",
"VO__AMICIA__CH03__CHATTER__FIRST_MEMORY__030__M__1": "Bunu anlayabiliyorum... Babamı hiç gömemedik...",
"VO__AMICIA__CH03__CHATTER__FIRST_MEMORY__050__M__1": "Haklısın... Hadi işimize dönelim.",
"VO__AMICIA__CH03__CHATTER__FIRST_MEMORY_LOCK__010__M__1": "İçeride ne var bakalım...",
"VO__AMICIA__CH03__CHATTER__FIRST_WORKBENCH__005__M__1": "Biri bu ocağı yakın zamanda kullanmış...",
"VO__AMICIA__CH03__CHATTER__FIRST_WORKBENCH__015__M__1": "Haklısın.",
"VO__AMICIA__CH03__CHATTER__FIRST_WORKBENCH__020__M__1": "Artık bulduğum o aleti kullanabilirim...",
"VO__AMICIA__CH03__CHATTER__FLEEING_HOUSE__027__M__1": "Sanırım.",
"VO__AMICIA__CH03__CHATTER__FLEEING_HOUSE__040__M__1": "Kaç tanesi kaldı?",
"VO__AMICIA__CH03__CHATTER__FOLLOWING_WAVE__020__M__1": "Yanlış! Sen sadece korkuyorsun... onların içine korku salmalısın!",
"VO__AMICIA__CH03__CHATTER__FOREST_IDLE_1__010__M__1": "Hepsi senin suçun. Şimdi düzelt!",
"VO__AMICIA__CH03__CHATTER__FOREST_IDLE_2__010__M__1": "Hadi... Hadi...! Daha hızlı!",
"VO__AMICIA__CH03__CHATTER__FOREST_IDLE_2__020__M__1": "Ölmedi... Henüz ölmedi... Merak etme, bedelini ödeyecekler... Çabuk olacak.",
"VO__AMICIA__CH03__CHATTER__FOREST_IDLE_3__010__M__1": "Hugo seni bekliyor... Yakında onu göreceksin.",
"VO__AMICIA__CH03__CHATTER__FOREST_IDLE_4__010__M__1": "Yoluna çıkan herkesi öldür... Yol bu. Güvenli yol.",
"VO__AMICIA__CH03__CHATTER__FOREST_KILL_1__010__M__1": "İşte böyle. Bu işin yolu bu.",
"VO__AMICIA__CH03__CHATTER__FOREST_KILL_2__010__M__1": "Gördün mü? İşe yarıyor... Geliyorum Lucas.",
"VO__AMICIA__CH03__CHATTER__FOREST_KILL_4__010__M__1": "Artık korkmuyorum... ama sen korkacaksın...",
"VO__AMICIA__CH03__CHATTER__FOREST_KILL_THIRD__010__M__1": "Devam et... Avcı artık sensin...",
"VO__AMICIA__CH03__CHATTER__GALLOWS__015__M__1": "Hayır... Sadece... ilerliyorum...",
"VO__AMICIA__CH03__CHATTER__GET_EXTINGUIS__010__M__1": "Gel! Orada kalma!",
"VO__AMICIA__CH03__CHATTER__GET_EXTINGUIS__040__M__1": "Aldım... Geride dur!",
"VO__AMICIA__CH03__CHATTER__GET_READY__010__M__1": "Hazır ol!",
"VO__AMICIA__CH03__CHATTER__GOING_DOWN__010__M__1": "Düşünme. Sadece nefesini tut...",
"VO__AMICIA__CH03__CHATTER__GOING_DOWN__020__M__1": "Hayır... ah!",
"VO__AMICIA__CH03__CHATTER__GOINGDOWN_RAIN_ANGER__020__M__1": "Zaman mı? Ne için? Hugo'yu daha da kötü hissettirmek için mi?",
"VO__AMICIA__CH03__CHATTER__GOINGDOWN_RAIN_ANGER__040__M__1": "Ah, yeter artık! Kardeşime bir hayvan gibi davranıyor! Hayır! Başka bir çözüm lazım, mesela... Hugo'nun rüyasını gördüğü o ada!",
"VO__AMICIA__CH03__CHATTER__GOINGDOWN_RAIN_ANGER__060__M__1": "Sadece... onu önemsemeye devam et, lütfen...",
"VO__AMICIA__CH03__CHATTER__GUARD_1ST_REMPART__010__M__1": "Bir muhafız daha...",
"VO__AMICIA__CH03__CHATTER__GUARD_1ST_REMPART__020__M__1": "Kımıldamayacak... Ama bir ateş var! Hâlâ o duman şeyinden var mı sende?",
"VO__AMICIA__CH03__CHATTER__GUARD_1ST_REMPT_OK__010__M__1": "Evet! O şey resmen sihir!",
"VO__AMICIA__CH03__CHATTER__HALLES_RAIN_ARENA__030__M__1": "Pekâlâ, gidiyoruz.",
"VO__AMICIA__CH03__CHATTER__HALLES_RAIN_INTRO__005__M__1": "Herkes gitmiş...",
"VO__AMICIA__CH03__CHATTER__HANGING_SHEEP_FAR__010__M__1": "Gidip şuna bakalım...",
"VO__AMICIA__CH03__CHATTER__HANGING_SHEEP_FAR__020__M__1": "Yer değiştirmeleri lazım...",
"VO__AMICIA__CH03__CHATTER__HEAR_SCREAM__020__M__1": "Mahalleyi boşaltmamışlar! Tıpkı arenadaki gibi!",
"VO__AMICIA__CH03__CHATTER__HELMET_RUNAWAY__030__M__1": "Dikkat!",
"VO__AMICIA__CH03__CHATTER__HELMET_RUNAWAY__070__M__1": "Artık ya biz ya onlar. Hugo'nun bekleyecek hâli yok. O köpek üzümü çabuk lazım.",
"VO__AMICIA__CH03__CHATTER__HERBALIST_ANGER__020__M__1": "Nasıl?! Bu köpekler Hugo'nun çektiklerini daha da kötüleştiriyor sadece!",
"VO__AMICIA__CH03__CHATTER__HERBALIST_CONCLUSION__010__M__1": "Köpek üzümü Lucas... Bitti!",
"VO__AMICIA__CH03__CHATTER__HERBALIST_DEATH__085__M__1": "Bir şey yapmalıyız!",
"VO__AMICIA__CH03__CHATTER__HERBALIST_DEATH__170__M__1": "Hayır! Alçak! Lanet alçak!",
"VO__AMICIA__CH03__CHATTER__HERBALIST_DEBRIEF__010__M__1": "Belki şu kasaplardan kurtulmalıydım...",
"VO__AMICIA__CH03__CHATTER__HERBALIST_DEBRIEF__030__M__1": "O arabalardan birinde sen olabilirdin...",
"VO__AMICIA__CH03__CHATTER__HERBALIST_DEBRIEF_ALL__010__M__1": "Bundan emin oldum.",
"VO__AMICIA__CH03__CHATTER__HERBALIST_DEBRIEF_ALL__030__M__1": "Sen o arabalardan birinde olmadığına sevin yeter.",
"VO__AMICIA__CH03__CHATTER__HERBALIST_DEBRIEF_ONE__010__M__1": "O kasaplardan kurtulsaydım olurduk.",
"VO__AMICIA__CH03__CHATTER__HERBALIST_DEBRIEF_ONE__030__M__1": "Ölmek daha da öyle.",
"VO__AMICIA__CH03__CHATTER__HERBALIST_ENCOUNTER_START__022__M__1": "Aptal! Neden tek başına gitmesine izin verdin? Dur! Zayıf olmayı bırak! Korkmayı bırak! Git! Git onu geri getir!",
"VO__AMICIA__CH03__CHATTER__HERBALIST_ENCOUNTER_START__030__M__1": "Artık kendini tutmak yok. Onu kurtar. Ne pahasına olursa olsun.",
"VO__AMICIA__CH03__CHATTER__HERBALIST_GARDEN__010__M__1": "Bitkiler... Lucas? Söyle bana! Burada olduğunu söyle!",
"VO__AMICIA__CH03__CHATTER__HERBALIST_GARDEN__030__M__1": "Peki köpek üzümü neye benziyor?",
"VO__AMICIA__CH03__CHATTER__HERBALIST_GARDEN__050__M__1": "Mor yıldız... Mor yıldız...",
"VO__AMICIA__CH03__CHATTER__HERBALIST_GATE__020__M__1": "Evet... Devam edelim...",
"VO__AMICIA__CH03__CHATTER__HERBALIST_GATE_FAKE__010__M__1": "Kilitlemişler!",
"VO__AMICIA__CH03__CHATTER__HERBALIST_GATE_FAKE__030__M__1": "Evet... Bakalım...",
"VO__AMICIA__CH03__CHATTER__HERBALIST_INTERRUPT__020__M__1": "Ben... Başka çarem yoktu...",
"VO__AMICIA__CH03__CHATTER__HERBALIST_REMORSE__020__M__1": "Deniyorum! Ama bu köpekler Hugo'nun çektiklerini daha da kötüleştiriyor sadece!",
"VO__AMICIA__CH03__CHATTER__HERBALIST_SHACK__002__M__1": "Bahçe aletleri... Şaka yapıyor olmalısın! Hepsi çöp!",
"VO__AMICIA__CH03__CHATTER__HERBALIST_SHACK__020__M__1": "Bu hiçbir yere varmıyor! Ve şimdi onun yanında bile değilim! Geri bile nasıl döneceğiz?!",
"VO__AMICIA__CH03__CHATTER__HERBALIST_SHACK__027__M__1": "Ah... Başım...",
"VO__AMICIA__CH03__CHATTER__HERBALIST_SHACK__030__M__1": "Ellerim terliyor...",
"VO__AMICIA__CH03__CHATTER__HERBALIST_SHACK__050__M__1": "Askerler mi?",
"VO__AMICIA__CH03__CHATTER__HERBALIST_WIFE_DEAD__010__M__1": "Çiçekçi... şifacının karısı... Onu öldürmüşler...",
"VO__AMICIA__CH03__CHATTER__HERBALIST_WIFE_DEAD__030__M__1": "Alçaklar... Nazik bir kadındı...",
"VO__AMICIA__CH03__CHATTER__HIDE_TABLE__020__M__1": "Masanın altına! Çabuk!",
"VO__AMICIA__CH03__CHATTER__HIDE_TABLE__030__M__1": "Kıpırdama...",
"VO__AMICIA__CH03__CHATTER__HIDE_TABLE__040__M__1": "Gidelim.",
"VO__AMICIA__CH03__CHATTER__HIGHER_SQUARE__030__M__1": "Sakın bana kenar mahalleleri de temizlediklerini söyleme! Lanet olsun!",
"VO__AMICIA__CH03__CHATTER__HIGHER_SQUARE__050__M__1": "Hiç bitmiyor...",
"VO__AMICIA__CH03__CHATTER__IDLE_CHASE_01__010__M__1": "Evet, beni takip et... İyi köpek...",
"VO__AMICIA__CH03__CHATTER__IDLE_CHASE_01__030__M__1": "Seni öldürenin sadece bir çocuk olması!",
"VO__AMICIA__CH03__CHATTER__IDLE_CHASE_02__010__M__1": "Sabret... yakında sıra sana gelecek!",
"VO__AMICIA__CH03__CHATTER__IDLE_CHASE_02__030__M__1": "Evet, gel! Gel dene!",
"VO__AMICIA__CH03__CHATTER__IDLE_CHASE_03__010__M__1": "Bak! Artık böyle yürüyor! Kuralları ben koyuyorum!",
"VO__AMICIA__CH03__CHATTER__IDLE_CHASE_03__030__M__1": "Hayır! Artık benim elimde!",
"VO__AMICIA__CH03__CHATTER__INSIDE_HOUSE__010__M__1": "Bu şehirden gitmeliyiz... Şu Vaudin'i geride bırakmalıyız...",
"VO__AMICIA__CH03__CHATTER__INSIDE_HOUSE__030__M__1": "Haftalardır gördüğü bir rüya!",
"VO__AMICIA__CH03__CHATTER__JAIL_STAIRS__010__M__1": "Bu... etkiliydi...",
"VO__AMICIA__CH03__CHATTER__JAR_EXTINGUIS_TUTO__010__M__1": "İki meşale...",
"VO__AMICIA__CH03__CHATTER__JAR_EXTINGUIS_TUTO__040__M__1": "Bir çömlek Exstinguis... İşe yarayabilir...",
"VO__AMICIA__CH03__CHATTER__JAR_EXTINGUIS_TUTO_AIM__010__M__1": "İşte geliyor...",
"VO__AMICIA__CH03__CHATTER__JAR_EXTINGUIS_TUTO_OK__010__M__1": "Ah evet, bunu sevdim...",
"VO__AMICIA__CH03__CHATTER__JAR_EXTINGUIS_TUTO_OK__030__M__1": "Çoktan yeterince vaktimizi harcadılar. Gel.",
"VO__AMICIA__CH03__CHATTER__KILL_1__010__M__1": "İşte katlettiklerin için...",
"VO__AMICIA__CH03__CHATTER__KILL_1__030__M__1": "Zaten gitmesi gerekiyordu.",
"VO__AMICIA__CH03__CHATTER__KILL_2__020__M__1": "Yeterince dikkatliyim!",
"VO__AMICIA__CH03__CHATTER__KILL_3__020__M__1": "Biliyorum! Bunu Hugo için yapıyorum!",
"VO__AMICIA__CH03__CHATTER__KILL_4__010__M__1": "Cehenneme git...",
"VO__AMICIA__CH03__CHATTER__KILL_5__010__M__1": "İşte! Sanırım... bu kadar...",
"VO__AMICIA__CH03__CHATTER__KILL_5__030__M__1": "Kimse onları aramayacak.",
"VO__AMICIA__CH03__CHATTER__KNOWING_RATS_IDLE__010__M__1": "Ne pahasına olursa olsun... Bizi durduramayacaklar...",
"VO__AMICIA__CH03__CHATTER__LAST_ENEMY__010__M__1": "Öldün sen! Lanet olası öldün!",
"VO__AMICIA__CH03__CHATTER__LOCK_SPOT__030__M__1": "Lanet bir kilit...",
"VO__AMICIA__CH03__CHATTER__LOOKING_FOR_CART__020__M__1": "Nasıl tırmanacağız? Hiçbir şey göremiyorum...",
"VO__AMICIA__CH03__CHATTER__LOOKING_FOR_CART__050__M__1": "Acele etmeliyiz! Yakında daha da çok olacak!",
"VO__AMICIA__CH03__CHATTER__LOOKING_FOR_CART__080__M__1": "Evet... Aferin! Hadi şunu yerine koyalım...",
"VO__AMICIA__CH03__CHATTER__LOOT_CART__060__M__1": "Ona güven...",
"VO__AMICIA__CH03__CHATTER__LOOT_CART__080__M__1": "Riske giremeyiz. Hugo'nun bize ihtiyacı var. Onsuz idare ederiz.",
"VO__AMICIA__CH03__CHATTER__LUCAS_LOWER__020__M__1": "İşe yarıyor...",
"VO__AMICIA__CH03__CHATTER__LUCAS_ORDER_LOWER__010__M__1": "Sen hâllet!",
"VO__AMICIA__CH03__CHATTER__LUCAS_SCREAM_1__010__M__1": "Lucas! Hayatta! Alçaklar... Size ulaştığımda...",
"VO__AMICIA__CH03__CHATTER__LUCAS_SCREAM_2__010__M__1": "Dayan Lucas... Buradayım... Bedelini ödeteceğim...",
"VO__AMICIA__CH03__CHATTER__LUCAS_WAITING__020__M__1": "Evet...",
"VO__AMICIA__CH03__CHATTER__MEAT_REACTION__010__M__1": "Lezzetli görünüyor, orası kesin...",
"VO__AMICIA__CH03__CHATTER__MEET_MURDERER__050__M__1": "Biz... sadece geçiyoruz...",
"VO__AMICIA__CH03__CHATTER__MEET_MURDERER__070__M__1": "Dur... Hayır...",
"VO__AMICIA__CH03__CHATTER__NEAR_SQUEEZE__010__M__1": "Burada... Bir delik var...",
"VO__AMICIA__CH03__CHATTER__NEW_PLAN__010__M__1": "Lanet... Kapı tam şurada!",
"VO__AMICIA__CH03__CHATTER__NEW_PLAN__030__M__1": "Burada da kalamayız... Bir plan lazım!",
"VO__AMICIA__CH03__CHATTER__NEW_PLAN__050__M__1": "Etrafa bir bakalım.",
"VO__AMICIA__CH03__CHATTER__NEW_WAVE__020__M__1": "Gel... İstediğini vereceğim sana!",
"VO__AMICIA__CH03__CHATTER__NIGHTSHADE_FOUND__080__M__1": "Nihayet! Boşuna olmadı...",
"VO__AMICIA__CH03__CHATTER__NIGHTSHADE_FOUND__100__M__1": "Şimdi sadece sapanım lazım, sonra gideceğiz!",
"VO__AMICIA__CH03__CHATTER__NIGHTSHADE_FOUND__110__M__1": "Muhafızlar...",
"VO__AMICIA__CH03__CHATTER__NIGHTSHADE_LOOKAT_A__010__M__1": "Hayır, hayır, doğru şekil değil!",
"VO__AMICIA__CH03__CHATTER__NIGHTSHADE_LOOKAT_B__010__M__1": "Hayır... O değil.",
"VO__AMICIA__CH03__CHATTER__NIGHTSHADE_LOOKAT_C__010__M__1": "Burada çiçek yok... Tanrım! Odaklan! Odaklan...",
"VO__AMICIA__CH03__CHATTER__NIGHTSHADE_REACT_4__010__M__1": "Burada hiçbir şey yok Lucas!",
"VO__AMICIA__CH03__CHATTER__NIGHTSHADE_REACT_4__040__M__1": "Evet, orada olmalı...",
"VO__AMICIA__CH03__CHATTER__NIGHTSHADE_SEARCH__020__M__1": "Pekâlâ, sen köpek üzümünü ara, ben sapanımı arayacağım! Lazım olabilir.",
"VO__AMICIA__CH03__CHATTER__NIGHTSHADE_SEARCH__040__M__1": "Dua edelim de kimse içeri girmesin, yoksa...",
"VO__AMICIA__CH03__CHATTER__NIGHTSHADE_SEARCH__060__M__1": "Evet...",
"VO__AMICIA__CH03__CHATTER__NOT_FINE_IDLE__030__M__1": "İyiyim dedim ya... Gayet iyiyim...",
"VO__AMICIA__CH03__CHATTER__OPENED_WINDOW__015__M__1": "Bir çatıya bakıyor Lucas!",
"VO__AMICIA__CH03__CHATTER__OPENED_WINDOW__020__M__1": "Başka çare yok...",
"VO__AMICIA__CH03__CHATTER__OUTSIDE_RAIN_VISTA__010__M__1": "İşler gittikçe kötüleşiyor...",
"VO__AMICIA__CH03__CHATTER__PULL_DOWN_CHAIN__010__M__1": "Şimdi bırak!",
"VO__AMICIA__CH03__CHATTER__PULL_DOWN_CHAIN__024__M__1": "Bir karşı ağırlık var! Tekrar deneyelim.",
"VO__AMICIA__CH03__CHATTER__PULL_DOWN_NO_CHAIN__010__M__1": "Zincir kesildi! Bırakabilirsin!",
"VO__AMICIA__CH03__CHATTER__PUSHCART_DEPOT__010__M__1": "Aşırı sessizler...",
"VO__AMICIA__CH03__CHATTER__PUSHCART_DEPOT__030__M__1": "Evet. Korkmaya başlıyorlar.",
"VO__AMICIA__CH03__CHATTER__RAT_HOLES_IDLE__020__M__1": "Şu altta çoktan onlarca galeri olmalı...",
"VO__AMICIA__CH03__CHATTER__RAT_HOLES_IDLE__030__M__1": "Her şey geçen seferkinden çok daha hızlı oluyor...",
"VO__AMICIA__CH03__CHATTER__ROTTEN_SLOPE__010__M__1": "Ah... Şaka yapıyor olmalısın...",
"VO__AMICIA__CH03__CHATTER__SALTPETER_PUSH_PULL__010__M__1": "Dışarıdaki insanlar olanları bilseydi... Burada aileleri var... çocukları...",
"VO__AMICIA__CH03__CHATTER__SALTPETER_PUSH_PULL__030__M__1": "Kaos olacak Lucas...",
"VO__AMICIA__CH03__CHATTER__SECOND_MEMORY__010__M__1": "Dur... Bunu biliyorum! Lucas! Guyenne'nin haritası var ellerinde!",
"VO__AMICIA__CH03__CHATTER__SECOND_MEMORY__030__M__1": "Bilmiyorum! İşte okyanus... göl... Evimiz... Şuralardaydı, evet... ha...",
"VO__AMICIA__CH03__CHATTER__SECOND_MEMORY__050__M__1": "Evet. Hepsi... geçmişte kaldı.",
"VO__AMICIA__CH03__CHATTER__SECOND_WAVE__010__M__1": "Bu nasıl, ha? Biri karşılık verince!",
"VO__AMICIA__CH03__CHATTER__SECOND_WAVE__030__M__1": "İstiyorsan git! Burası artık BENİM toprağım! Öldükleri yer burası!",
"VO__AMICIA__CH03__CHATTER__SECRET_CHEST_TUTO__010__M__1": "Kilitli görünüyor... Belki bir bıçakla...",
"VO__AMICIA__CH03__CHATTER__SECRET_CHEST_TUTO__020__M__1": "Lanet...",
"VO__AMICIA__CH03__CHATTER__SECRET_CHEST_TUTO__040__M__1": "Bir bıçak kırdım... ama değdi! İçinde bir sürü şey var!",
"VO__AMICIA__CH03__CHATTER__SECRET_CHEST_TUTO__050__M__1": "Gözümü açık tutmalıyım... Bu sandıklardan daha fazlası olabilir...",
"VO__AMICIA__CH03__CHATTER__SENTINEL_SQUARE__020__M__1": "Tabii. Cesetleri çıkar. Fareler peşinden gelir.",
"VO__AMICIA__CH03__CHATTER__SHAKING_IDLE__020__M__1": "İyiyim... Geçer...",
"VO__AMICIA__CH03__CHATTER__SHOOT_HAM__010__M__1": "İşte böyle... Devam edelim!",
"VO__AMICIA__CH03__CHATTER__SHOT_POTS_1__010__M__1": "Hiçbir şey...",
"VO__AMICIA__CH03__CHATTER__SHOT_POTS_2__010__M__1": "Boş...",
"VO__AMICIA__CH03__CHATTER__SLING_BACK__020__M__1": "Ah! İşte buradasın! Buldum!",
"VO__AMICIA__CH03__CHATTER__SLING_BACK__040__M__1": "Biliyorum!",
"VO__AMICIA__CH03__CHATTER__SLING_BACK__050__M__1": "Hadi kapıya gidip buradan çıkalım.",
"VO__AMICIA__CH03__CHATTER__SMALL_LEDGE__005__M__1": "Sanırım... buradan çıkmanın tek yolu bu...",
"VO__AMICIA__CH03__CHATTER__SMALL_LEDGE__010__M__1": "Hayır... Sadece duvara yapış!",
"VO__AMICIA__CH03__CHATTER__SMALL_LEDGE__030__M__1": "Yapabilirsin!",
"VO__AMICIA__CH03__CHATTER__SMALL_LEDGE__040__M__1": "Bunu sana yaşattığım için üzgünüm... bu benim suçum...",
"VO__AMICIA__CH03__CHATTER__SMALL_LEDGE__047__M__1": "Bir çatı daha var! Neredeyse vardık!",
"VO__AMICIA__CH03__CHATTER__SMALL_LEDGE__100__M__1": "Ha... Başardım... Ha...",
"VO__AMICIA__CH03__CHATTER__SMOKE_GO__010__M__1": "Şimdi...",
"VO__AMICIA__CH03__CHATTER__SMOKE_TUTO__010__M__1": "Ne?! Lucas!",
"VO__AMICIA__CH03__CHATTER__SMOKE_TUTO__040__M__1": "O neydi?!...",
"VO__AMICIA__CH03__CHATTER__SOLDIER_STREET_DEAD__020__M__1": "Onlara ağlayacak vakit yok. Hugo bekliyor.",
"VO__AMICIA__CH03__CHATTER__SOLDIERS_1ST_WAVE__020__M__1": "Geliyorlar... Git saklan! Onlarla ben ilgilenirim!",
"VO__AMICIA__CH03__CHATTER__SOLDIERS_1ST_WAVE__040__M__1": "Hayır. Peşimizden gelirler... ve ben artık kaçmaktan bıktım...",
"VO__AMICIA__CH03__CHATTER__SOLDIERS_1ST_WAVE__060__M__1": "İşte böyle... Gel... Tam buradayım.",
"VO__AMICIA__CH03__CHATTER__SOLDIERS_PATROL__040__M__1": "Alçaklar... Hepiniz bedelini ödeyeceksiniz...",
"VO__AMICIA__CH03__CHATTER__SPEARMAN_REACTION__001__M__1": "Aman Tanrım... Çok yakındı...",
"VO__AMICIA__CH03__CHATTER__SPEARMAN_REACTION__004__M__1": "Biliyorum! Bize neden saldırdı ki?!",
"VO__AMICIA__CH03__CHATTER__SPEARMAN_VICTIM__020__M__1": "Onlar... artık mahalleleri temizliyorlar...",
"VO__AMICIA__CH03__CHATTER__SPOT_SALTPETER__010__M__1": "Bu daha çok güherçile, değil mi?",
"VO__AMICIA__CH03__CHATTER__SPOT_SALTPETER__016__M__1": "Bu her türlü ateşi söndürür.",
"VO__AMICIA__CH03__CHATTER__SQUIZZ_SPOT__020__M__1": "Bir giriş görüyor musun?",
"VO__AMICIA__CH03__CHATTER__SQUIZZ_THROUGH_STREET__010__M__1": "Güvenli görünüyor.",
"VO__AMICIA__CH03__CHATTER__SQUIZZ_THROUGH_STREET__030__M__1": "Sadece geçiyoruz...",
"VO__AMICIA__CH03__CHATTER__STUPEFACIO_BALLISTA__020__M__1": "Bu delilik Lucas...",
"VO__AMICIA__CH03__CHATTER__STUPEFACIO_BALLISTA__040__M__1": "Öf... pekâlâ.",
"VO__AMICIA__CH03__CHATTER__STUPEFACIO_SET__020__M__1": "Hallediyorum...",
"VO__AMICIA__CH03__CHATTER__TO_CRANK__020__M__1": "Onu tekrar açmanın bir yolu olmalı.",
"VO__AMICIA__CH03__CHATTER__TO_CRANK__040__M__1": "Umarım Hugo dayanıyordur.",
"VO__AMICIA__CH03__CHATTER__TO_CRANK__060__M__1": "Bunun durması gerek.",
"VO__AMICIA__CH03__CHATTER__TORTURE_ROOM__010__M__1": "Sapanım hâlâ onlarda!",
"VO__AMICIA__CH03__CHATTER__TOWER_DOOR__010__M__1": "Kilitli...",
"VO__AMICIA__CH03__CHATTER__TOWER_SAFE__005__M__1": "Bu onları yavaşlatır! Aşağıda paçamızı kurtardın...",
"VO__AMICIA__CH03__CHATTER__TOWER_SAFE__020__M__1": "Bir geçit ya da... bir çatı olmalı...",
"VO__AMICIA__CH03__CHATTER__TRAPDOOR_ROOF__010__M__1": "Burada! Aşağı inen bir yol!",
"VO__AMICIA__CH03__CHATTER__TRY_LEAVE_NO_USED__020__M__1": "Tabii.",
"VO__AMICIA__CH03__CHATTER__TWO_FIRST_KILLS__010__M__1": "İşte böyle!",
"VO__AMICIA__CH03__CHATTER__TWO_FIRST_KILLS__020__M__1": "Gördün mü? Hiçbir şey değiller! Korkulacak bir şey değiller!",
"VO__AMICIA__CH03__CHATTER__TWO_FIRST_KILLS__040__M__1": "HAYIR! Korkmaktan bıktım! Onlara her şeyin bittiğini göstereceğim!",
"VO__AMICIA__CH03__CHATTER__UPSTAIRS_ROOM__020__M__1": "O şehrin dışında, değil mi? O zaman belki güvendedir.",
"VO__AMICIA__CH03__CHATTER__VILLAGE_BARRICADES__010__M__1": "Barikatlar...",
"VO__AMICIA__CH03__CHATTER__VILLAGE_EMPTY__020__M__1": "Tuhaf bir his var... Kısa süre önce burada insanlar vardı...",
"VO__AMICIA__CH03__CHATTER__VILLAGE_EMPTY__040__M__1": "Neredeler?",
"VO__AMICIA__CH03__CHATTER__VILLAGE_RATS__020__M__1": "Sana söylemiştim... Hiçbir duvar onları durduramaz.",
"VO__AMICIA__CH03__CHATTER__VILLAGE_RATS__040__M__1": "Evet... Kanı takip etmeye devam ediyorlar.",
"VO__AMICIA__CH03__CHATTER__VILLAGE_SAVED__020__M__1": "O lanet alçak...",
"VO__AMICIA__CH03__CHATTER__VILLAGE_SAVED__040__M__1": "Bunun bitmesi gerek...",
"VO__AMICIA__CH03__CHATTER__VILLAGE_SURPRISED__020__M__1": "Hayır...",
"VO__AMICIA__CH03__CHATTER__VISTA__020__M__1": "Daha varmadık... ve Hugo şu an daha da kötüye gidiyor olabilir! Acele edelim!",
"VO__AMICIA__CH03__CHATTER__VISTA_CITY__010__M__1": "Hugo şurada bir yerlerde... Umarım iyidir...",
"VO__AMICIA__CH03__CHATTER__VISTA_CITY__030__M__1": "Evet... Hadi evimize dönelim...",
"VO__AMICIA__CH03__CHATTER__WAITING_DOOR__020__M__1": "Henüz değil... Burada o kadar çok şey var ki...",
"VO__AMICIA__CH03__CHATTER__WAR_TREASURE__005__M__1": "Ah... Lucas... Sanırım depolarını bulduk!",
"VO__AMICIA__CH03__CHATTER__WAR_TREASURE__020__M__1": "Ve sapanım da burada!",
"VO__AMICIA__CH03__CHATTER__WASTING_TIME_IDLE__030__M__1": "Çok fazla vakit kaybediyoruz!",
"VO__AMICIA__CH03__CHATTER__WORKBENCH_NO_TOOL__010__M__1": "Alet olmadan hiçbir şey yapamam...",
"VO__AMICIA__CH03__CHATTER__WORKBENCH_NOT_YET__010__M__1": "Dur... Şu tezgâha bir bakayım.",
"VO__AMICIA__CH03__CHATTER__WORKBENCH_OK_GO__020__M__1": "Evet. Gidelim.",
"VO__AMICIA__CH03__CHATTER__WORKBENCH_UNUSED__010__M__1": "Hmmm, hayır... Onu sonra yaparım. Şimdilik gidelim.",
"VO__AMICIA__CH03__CHATTER__WORKBENCH_USED__010__M__1": "Bu daha iyi! İşe yarar...",
"VO__AMICIA__CH03__ONOM__CART_ROLL__025__M__1": "Vay!",
"VO__AMICIA__CH03__ONOM__NOT_FINE_IDLE__010__M__1": "Hah...",
"VO__AMICIA__CH03__ONOM__WASTING_TIME_IDLE__010__M__1": "Ha...",
"VO__AMICIA__CH03__RTC__112_CLOSEDDOOR__030__M__1": "Hugo'nun ağladığını duydum, neler oluyor?",
"VO__AMICIA__CH03__RTC__112_CLOSEDDOOR__050__M__1": "Ne? Anne... Buna son vermelisin!",
"VO__AMICIA__CH03__RTC__112_CLOSEDDOOR__060__M__1": "Bu adamı tanımıyoruz!",
"VO__AMICIA__CH03__RTC__112_CLOSEDDOOR__120__M__1": "Geliyorum.",
"VO__AMICIA__CH03__RTC__112_CLOSEDDOOR__130__M__1": "Zaten burada kendimi işe yaramaz hissediyorum.",
"VO__AMICIA__CH03__RTC__118_CONTROL_LOST__030__M__1": "Ne?",
"VO__AMICIA__CH03__RTC__118_CONTROL_LOST__050__M__1": "Öyleyim...",
"VO__AMICIA__CH03__RTC__118_CONTROL_LOST__070__M__1": "Başım dönüyor. Kalbim küt küt atıyor.",
"VO__AMICIA__CH03__RTC__118_CONTROL_LOST__090__M__1": "Hayır.",
"VO__AMICIA__CH03__RTC__118_CONTROL_LOST__110__M__1": "Her ihtimale karşı...",
"VO__AMICIA__CH03__RTC__118_CONTROL_LOST__130__M__1": "Benim neyim var?",
"VO__AMICIA__CH03__RTC__118_CONTROL_LOST__135__M__1": "Eyvah, biliyordum, biliyordum!",
"VO__AMICIA__CH03__RTC__118_CONTROL_LOST__137__M__1": "Pekâlâ, çabuk hareket et...",
"VO__AMICIA__CH03__RTC__118_CONTROL_LOST__140__M__1": "Hadi!",
"VO__AMICIA__CH03__RTC__121_JAIL__020__M__1": "Otursan iyi olur.",
"VO__AMICIA__CH03__RTC__121_JAIL__050__M__1": "Dur.",
"VO__AMICIA__CH03__RTC__121_JAIL__080__M__1": "Bir hata yaptım, tamam mı!",
"VO__AMICIA__CH03__RTC__121_JAIL__090__M__1": "Bana ne oluyor bilmiyorum Lucas. Aklımın kaydığını hissediyorum.",
"VO__AMICIA__CH03__RTC__122_GUILT__020__M__1": "Şey, ben...",
"VO__AMICIA__CH03__RTC__122_GUILT__063__M__1": "Nasıl o?",
"VO__AMICIA__CH03__RTC__122_GUILT__070__M__1": "Lütfen, ona söyle...",
"VO__AMICIA__CH03__RTC__122_GUILT__110__M__1": "Umarım öyledir... senin iyiliğin için.",
"VO__AMICIA__CH03__RTC__ENTER_BUTCHER_DISTRICT__010__M__1": "Çürümüş et.",
"VO__BEATRICE__CH03__RTC__112_CLOSEDDOOR__010__M__1": "Lucas! Gel, hemen!",
"VO__BEATRICE__CH03__RTC__112_CLOSEDDOOR__040__M__1": "İyi tepki vermedi. Nöbet geçiriyor.",
"VO__BEATRICE__CH03__RTC__112_CLOSEDDOOR__070__M__1": "Amicia, böyle bir şey her zaman olasıydı. Ve \"bu adam\" var olan en kadim simyacılar topluluğunun yüceltilmiş bir üyesi. Düzen, Macula'yı bilir! Hugo yalnız değil. Ben buradayım.",
"VO__BEATRICE__CH03__RTC__112_CLOSEDDOOR__080__M__1": "Titremeleri yatıştırmak için bir an önce köpek üzümü lazım. Şehrin kenar mahallesinde bir şifacı var. Kasaplar mahallesinin öbür ucunda, bir ormanın kıyısında; görürsün.",
"VO__BEATRICE__CH03__RTC__122_GUILT__010__M__1": "Nihayet! Neden bu kadar geciktiniz?",
"VO__BEATRICE__CH03__RTC__122_GUILT__055__M__1": "Bunu ona vereceğiz.",
"VO__BEATRICE__CH03__RTC__122_GUILT__065__M__1": "Bitkin düşmüş, sakinleşince uyuyakaldı.",
"VO__KID_F1__CH03__CHATTER__WOMAN_CRYING__020__M__1": "Yakında gideceğiz anne...",
"VO__LUCAS__CH03__CHATTER__2ND_STREET__040__M__1": "İyi bir şey değil gibi...",
"VO__LUCAS__CH03__CHATTER__2ND_TOWER_REMPART__010__M__1": "Hey! Şuradaki ana kapı!",
"VO__LUCAS__CH03__CHATTER__2ND_TOWER_REMPART__030__M__1": "Eve dönmek için sabırsızlanıyorum...",
"VO__LUCAS__CH03__CHATTER__2ND_TOWER_REMPART__050__M__1": "Şimdi onu düşünme.",
"VO__LUCAS__CH03__CHATTER__2ND_TOWER_SUCCESSFUL__010__M__1": "Güzel! Yapıyoruz!",
"VO__LUCAS__CH03__CHATTER__ABOUT_BALLISTA__005__M__1": "Elbette! Benim gördüğümü görüyor musun?",
"VO__LUCAS__CH03__CHATTER__ABOUT_BALLISTA__015__M__1": "Yukarıda!",
"VO__LUCAS__CH03__CHATTER__ABOUT_BALLISTA__020__M__1": "Dinle... Burada bol miktarda Stupefacio yapacak kadar malzeme topladım. Yani macunu okun ucuna yapıştırırız, ateşleriz ve umarım çarpmanın sürtünmesi onu tutuşturur...",
"VO__LUCAS__CH03__CHATTER__ABOUT_BALLISTA__035__M__1": "İşe yararsa...",
"VO__LUCAS__CH03__CHATTER__AFTER_SLIDE__020__M__1": "Evet... Ağzıma biraz kaçtı!",
"VO__LUCAS__CH03__CHATTER__AFTER_SLIDE__040__M__1": "Panikledim!",
"VO__LUCAS__CH03__CHATTER__ALLEY_MURDER__040__M__1": "O neydi?!",
"VO__LUCAS__CH03__CHATTER__AMICIA_LOWER__030__M__1": "Daha önce hiç... böyle bir şey \"kullandın\" mı?",
"VO__LUCAS__CH03__CHATTER__AMICIA_LOWER_OK__010__M__1": "Şu zincirden kurtulmanın bir yolu olmalı...",
"VO__LUCAS__CH03__CHATTER__ANOTHER_WAY__100__M__1": "Başka bir giriş olabilir.",
"VO__LUCAS__CH03__CHATTER__ARMING_BALLISTA__020__M__1": "Açmayacağım. İçinden ateş et. Tepkime için sürtünme lazım.",
"VO__LUCAS__CH03__CHATTER__ARMING_BALLISTA__040__M__1": "Onun için çok geç.",
"VO__LUCAS__CH03__CHATTER__BALLISTA_PLAN_HELPER__010__M__1": "İstersen kranka ben bakabilirim.",
"VO__LUCAS__CH03__CHATTER__BALLISTA_REMINDER__010__M__1": "Amicia, buraya gel!",
"VO__LUCAS__CH03__CHATTER__BLOOD_POND__010__M__1": "Bütün canlılar... bundan doğmuş... olmalı...",
"VO__LUCAS__CH03__CHATTER__BLOOD_POND__030__M__1": "Bu beni... aklımı kaçırmaktan alıkoyuyor...",
"VO__LUCAS__CH03__CHATTER__BLOOD_POND__050__M__1": "Onu sadece dönüşen... madde olarak düşün...",
"VO__LUCAS__CH03__CHATTER__BLOOD_POND_EXIT__020__M__1": "Çizmelerim mahvoldu...",
"VO__LUCAS__CH03__CHATTER__BULLIES_DEAD__020__M__1": "Atlatırım... Sağ ol...",
"VO__LUCAS__CH03__CHATTER__BULLIES_DEAD__040__M__1": "Hey, onu boş ver! Köpek üzümünü buldum! Hemen gitmeliyiz!",
"VO__LUCAS__CH03__CHATTER__BULLYING_LUCAS__060__M__1": "Sadece... Bırakın gideyim...",
"VO__LUCAS__CH03__CHATTER__BUTCHER_RAIN_GATE_SPOTTED__010__M__1": "İşte orada!",
"VO__LUCAS__CH03__CHATTER__BUTCHER_RAIN_NIGHTSHADE__020__M__1": "Pekâlâ, kapımız şurada olmalı.",
"VO__LUCAS__CH03__CHATTER__BUTCHER_RAIN_NIGHTSHADE__040__M__1": "Şey, bu doğru yolda olduğumuz anlamına geliyor.",
"VO__LUCAS__CH03__CHATTER__BUTCHER_RAIN_OUTRO__010__M__1": "Pekâlâ, hazır mısın?",
"VO__LUCAS__CH03__CHATTER__CAPTAIN_CHURCH__015__M__1": "Savaşmış gibi davranıyorlar...",
"VO__LUCAS__CH03__CHATTER__CART_BLOCK__020__M__1": "Evet!",
"VO__LUCAS__CH03__CHATTER__CART_MOVE_BALLISTA__020__M__1": "Biliyorum...",
"VO__LUCAS__CH03__CHATTER__CART_MOVE_BALLISTA__040__M__1": "Ve öleceğiz.",
"VO__LUCAS__CH03__CHATTER__CART_ROLL__040__M__1": "Ateş lazım olacak, çabuk!",
"VO__LUCAS__CH03__CHATTER__CART_ROLL__080__M__1": "Bunu yapabiliriz... Sadece köpek üzümünü almaya odaklan!",
"VO__LUCAS__CH03__CHATTER__CHURCH_EMPTY_IDLE__010__M__1": "İnsanları öldürmüşler... bir kilisenin içinde...",
"VO__LUCAS__CH03__CHATTER__CHURCH_EMPTY_IDLE__025__M__1": "Bilmiyorum...",
"VO__LUCAS__CH03__CHATTER__CLIMB_WINDOW__020__M__1": "Güvenli mi?",
"VO__LUCAS__CH03__CHATTER__CLIMB_WINDOW__040__M__1": "Aman be! Bu hiç ama hiç güvenli değil!",
"VO__LUCAS__CH03__CHATTER__CRANK_DROP__020__M__1": "Hmmm... Tekrar deneyelim... Bırakmamaya çalış...",
"VO__LUCAS__CH03__CHATTER__CRANK_RELEASE_OK__030__M__1": "Geliyorum!",
"VO__LUCAS__CH03__CHATTER__CRANK_RELEASE_OK__050__M__1": "Tam arkandayım!",
"VO__LUCAS__CH03__CHATTER__CRANK_USE__020__M__1": "Ne?",
"VO__LUCAS__CH03__CHATTER__CRUEL_SOLDIERS_IDLE__020__M__1": "Asker bunlar.",
"VO__LUCAS__CH03__CHATTER__DEAD_ANIMALS__010__M__1": "Zemin kana bulanmış...",
"VO__LUCAS__CH03__CHATTER__DEAD_BLACKSMITH__020__M__1": "Fareler mi?",
"VO__LUCAS__CH03__CHATTER__ENTER_SQUARE__020__M__1": "Nihayet...",
"VO__LUCAS__CH03__CHATTER__EVIL_SOLDIERS_IDLE__010__M__1": "İnsanların yardımına ihtiyaçları olabilir... Hepsini öldürmek...",
"VO__LUCAS__CH03__CHATTER__EVIL_SOLDIERS_IDLE__030__M__1": "Bu... kötülük.",
"VO__LUCAS__CH03__CHATTER__EXTERIOR__003__M__1": "Geldik... İyi iş...",
"VO__LUCAS__CH03__CHATTER__EXTERIOR__010__M__1": "Demek şehir surlarında durdular?",
"VO__LUCAS__CH03__CHATTER__EXTERIOR__030__M__1": "Asker de görmüyorum...",
"VO__LUCAS__CH03__CHATTER__EXTERIOR__050__M__1": "Pekâlâ, pekâlâ! Ben... sormaya çalışırım...",
"VO__LUCAS__CH03__CHATTER__EXTINGUIS_BAG_TUTO__005__M__1": "Şu asılı leşi istiyorlar, değil mi?",
"VO__LUCAS__CH03__CHATTER__EXTINGUIS_BAG_TUTO__010__M__1": "Şu torba... Arabadakilere benziyor...",
"VO__LUCAS__CH03__CHATTER__EXTINGUIS_BAG_TUTO__015__M__1": "Sapanınla vurmayı dene!",
"VO__LUCAS__CH03__CHATTER__EXTINGUIS_BAG_TUTO_OK__020__M__1": "Güherçile! Normalde eti korur, ama alevleri boğacak kadar yoğun.",
"VO__LUCAS__CH03__CHATTER__EXTINGUIS_TUTO_EXPLANATION__010__M__1": "Dinle... O güherçileyi onlara karşı kullanabilirsin. Biraz Exstinguis üretmek için bunu al. Şu meşaleyi söndürmeye yeter.",
"VO__LUCAS__CH03__CHATTER__EXTINGUIS_USE__020__M__1": "Şimdi onu şu meşaleye at, hani... bilirsin...",
"VO__LUCAS__CH03__CHATTER__EXTINGUIS_WAIT__010__M__1": "Amicia? Al şunu!",
"VO__LUCAS__CH03__CHATTER__EXTINGUISH_REMINDER__010__M__1": "Torbaları vur Amicia! Onları kör eder!",
"VO__LUCAS__CH03__CHATTER__FAKE_NIGHTSHADE__020__M__1": "Ah. Güzel bir bitki. Çok faydalı.",
"VO__LUCAS__CH03__CHATTER__FAKE_NIGHTSHADE__040__M__1": "Daha iyi günler gelecek.",
"VO__LUCAS__CH03__CHATTER__FIRE_HAM__004__M__1": "Biraz güherçile lazım...",
"VO__LUCAS__CH03__CHATTER__FIRE_HAM__015__M__1": "Dışarıda güherçilemiz var...",
"VO__LUCAS__CH03__CHATTER__FIRST_KILL_EXTINGUIS__003__M__1": "Ha... Tanrım...",
"VO__LUCAS__CH03__CHATTER__FIRST_KILL_EXTINGUIS__005__M__1": "Şey, işe... yaradı...",
"VO__LUCAS__CH03__CHATTER__FIRST_KILL_EXTINGUIS__008__M__1": "Rahatsız edici.",
"VO__LUCAS__CH03__CHATTER__FIRST_MEMORY__020__M__1": "Ölülerini yanlarında tutmak istemişler.",
"VO__LUCAS__CH03__CHATTER__FIRST_MEMORY__040__M__1": "O evinde ve huzur içinde Amicia...",
"VO__LUCAS__CH03__CHATTER__FIRST_WORKBENCH__010__M__1": "Hey! Burada bir tezgâh var! Ekipmanını onunla geliştirebilirsin... Hemen bir bakmalısın... Bizi neyin beklediğini bilmiyoruz.",
"VO__LUCAS__CH03__CHATTER__FLEEING_HOUSE__025__M__1": "Kasaba halkı mı?",
"VO__LUCAS__CH03__CHATTER__FOLLOW_LUCAS__010__M__1": "Sanırım buradan...",
"VO__LUCAS__CH03__CHATTER__FOLLOWING_WAVE__010__M__1": "Durmalısın! Burada öleceğiz!",
"VO__LUCAS__CH03__CHATTER__GALLOWS__005__M__1": "Nereye gittiğimizi biliyor musun?",
"VO__LUCAS__CH03__CHATTER__GATE_PATROL__020__M__1": "Askerler!",
"VO__LUCAS__CH03__CHATTER__GET_EXTINGUIS__020__M__1": "Dur, biraz alıyorum. Bu şey fazla faydalı!",
"VO__LUCAS__CH03__CHATTER__GET_EXTINGUIS__035__M__1": "Pekâlâ. Artık hepsi senin!",
"VO__LUCAS__CH03__CHATTER__GET_READY__020__M__1": "Hazırım!",
"VO__LUCAS__CH03__CHATTER__GOING_DOWN__040__M__1": "Eyvah, hayır, hayır!",
"VO__LUCAS__CH03__CHATTER__GOINGDOWN_RAIN_ANGER__010__M__1": "Endişeli olduğunu biliyorum... ama Magister Vaudin'e biraz zaman tanımalısın.",
"VO__LUCAS__CH03__CHATTER__GOINGDOWN_RAIN_ANGER__030__M__1": "Testler yapıyor! Ama ne yaptığını biliyor. Bu alanda en yetkin kişi.",
"VO__LUCAS__CH03__CHATTER__GOINGDOWN_RAIN_ANGER__050__M__1": "Bir rüya! Bir rüyayla ne yapabiliriz Amicia?",
"VO__LUCAS__CH03__CHATTER__GOINGDOWN_RAIN_ANGER__070__M__1": "Önemsiyorum! Ama artık yeterli değil...",
"VO__LUCAS__CH03__CHATTER__GOINGDOWN_RAIN_BLOCKED__010__M__1": "Bu yol kapalı...",
"VO__LUCAS__CH03__CHATTER__GUARD_1ST_REMPART__030__M__1": "Stupefacio mu? Evet!... Hazır olduğunda söyle!",
"VO__LUCAS__CH03__CHATTER__GUARD_1ST_REMPT_OK__020__M__1": "Bununla... epey gurur duyuyorum, itiraf ediyorum.",
"VO__LUCAS__CH03__CHATTER__HALLES_RAIN_ARENA__020__M__1": "O-o taraftan gitmiyoruz.",
"VO__LUCAS__CH03__CHATTER__HANGING_PIGS__020__M__1": "Et için geldiler...",
"VO__LUCAS__CH03__CHATTER__HANGING_SHEEP__015__M__1": "Ona ulaşamıyorlar.",
"VO__LUCAS__CH03__CHATTER__HANGING_SHEEP_COURTYARD__010__M__1": "İşte böyle.",
"VO__LUCAS__CH03__CHATTER__HEAR_SCREAM__010__M__1": "Şunu duyuyor musun?!... Hâlâ etrafta insanlar var!",
"VO__LUCAS__CH03__CHATTER__HELMET_RUNAWAY__060__M__1": "Bizi görür görmez infaz eder...",
"VO__LUCAS__CH03__CHATTER__HELMET_RUNAWAY__080__M__1": "Sanırım haklısın.",
"VO__LUCAS__CH03__CHATTER__HERBALIST_ANGER__010__M__1": "Sakinleşmeye çalış! O hâlde başaramazsın!",
"VO__LUCAS__CH03__CHATTER__HERBALIST_CONCLUSION__020__M__1": "Henüz değil! Neye benzediğini biliyorum! Hâlâ bunu yapabiliriz. Sadece şifacının dükkânını bulmamız lazım.",
"VO__LUCAS__CH03__CHATTER__HERBALIST_DEATH__040__M__1": "İşte şifacı!",
"VO__LUCAS__CH03__CHATTER__HERBALIST_DEATH__087__M__1": "Etraflarını fareler sarmış...",
"VO__LUCAS__CH03__CHATTER__HERBALIST_DEATH__150__M__1": "Onu öldürecek!",
"VO__LUCAS__CH03__CHATTER__HERBALIST_DEATH__155__M__1": "Ne yapacağımı bilmiyorum!",
"VO__LUCAS__CH03__CHATTER__HERBALIST_DEBRIEF__005__M__1": "Güzel, sanırım şimdilik güvendeyiz...",
"VO__LUCAS__CH03__CHATTER__HERBALIST_DEBRIEF__020__M__1": "Asker öldürmek bizim kavgamız değil...",
"VO__LUCAS__CH03__CHATTER__HERBALIST_DEBRIEF_ALL__020__M__1": "Hepsini öldürmek zorunda değildin...",
"VO__LUCAS__CH03__CHATTER__HERBALIST_DEBRIEF_ONE__020__M__1": "Öldürmek bize köpek üzümünü vermez...",
"VO__LUCAS__CH03__CHATTER__HERBALIST_GARDEN__020__M__1": "Şifacıdayız, ama... Aramamız gerekecek!",
"VO__LUCAS__CH03__CHATTER__HERBALIST_GARDEN__040__M__1": "Mor bir çiçek ara! Yıldız biçiminde!",
"VO__LUCAS__CH03__CHATTER__HERBALIST_GATE__010__M__1": "O hâlde devam edelim! O kapıdan geçtiler. Şifacının dükkânı öbür tarafta bir yerde olmalı.",
"VO__LUCAS__CH03__CHATTER__HERBALIST_GATE_FAKE__020__M__1": "Sakin... ol! Eski bir duvar bu, başka bir yol olabilir...",
"VO__LUCAS__CH03__CHATTER__HERBALIST_INTERRUPT__010__M__1": "Hayır! Hayır!",
"VO__LUCAS__CH03__CHATTER__HERBALIST_INTERRUPT__030__M__1": "Belki! Ama yine de oldu işte. Burada kalmayalım...",
"VO__LUCAS__CH03__CHATTER__HERBALIST_REMORSE__010__M__1": "Kendini tut! O hâlde başaramazsın!",
"VO__LUCAS__CH03__CHATTER__HERBALIST_SHACK__010__M__1": "Dur...",
"VO__LUCAS__CH03__CHATTER__HERBALIST_SHACK__025__M__1": "Dur! İşimiz bitmedi! Daha yeni geldik!",
"VO__LUCAS__CH03__CHATTER__HERBALIST_SHACK__040__M__1": "Amicia... Gel bak...",
"VO__LUCAS__CH03__CHATTER__HERBALIST_SHACK__060__M__1": "Kendi gözlerinle görmelisin...",
"VO__LUCAS__CH03__CHATTER__HERBALIST_WIFE_DEAD__020__M__1": "Eyvah...",
"VO__LUCAS__CH03__CHATTER__HIDE_TABLE__010__M__1": "Eyvah...",
"VO__LUCAS__CH03__CHATTER__HIGHER_SQUARE__020__M__1": "Eyvah... Dışarı çıkıyorlar! Şifacımız orada bir yerde!",
"VO__LUCAS__CH03__CHATTER__HIGHER_SQUARE__040__M__1": "Hey, hey... Onlardan önce ona ulaşabiliriz.",
"VO__LUCAS__CH03__CHATTER__INSIDE_HOUSE__020__M__1": "Ne uğruna Amicia? Bir ada... rüyası mı?",
"VO__LUCAS__CH03__CHATTER__JAIL_STAIRS__020__M__1": "Acele edelim! Uzun süre şaşkın kalmazlar!",
"VO__LUCAS__CH03__CHATTER__JAR_EXTINGUIS_TUTO__020__M__1": "Bir Exstinguis için fazla, ama... bir çömleğe koy! Bir bulutunu elde edersin!",
"VO__LUCAS__CH03__CHATTER__JAR_EXTINGUIS_TUTO__030__M__1": "Çömleğin! Bir Exstinguis bulutu birkaç meşaleyi söndürür!",
"VO__LUCAS__CH03__CHATTER__JAR_EXTINGUIS_TUTO_OK__020__M__1": "Faydalı diyelim.",
"VO__LUCAS__CH03__CHATTER__KILL_1__020__M__1": "İntikam vakti değil Amicia...",
"VO__LUCAS__CH03__CHATTER__KILL_2__010__M__1": "Daha dikkatli ol!",
"VO__LUCAS__CH03__CHATTER__KILL_3__010__M__1": "Ne yapıyorsun? Buraya ne için geldiğimizi hatırla!",
"VO__LUCAS__CH03__CHATTER__KILL_4__020__M__1": "Amicia, lütfen...",
"VO__LUCAS__CH03__CHATTER__KILL_5__020__M__1": "Evet... hepsini öldürdün...",
"VO__LUCAS__CH03__CHATTER__KNOWING_RATS_IDLE__020__M__1": "Dikkatli ol. Fareleri çoğu kişiden iyi tanıyoruz... ama uyum sağlamaya başlıyorlar.",
"VO__LUCAS__CH03__CHATTER__LIT_BRASIERS__005__M__1": "Ateşler karşıya geçmemize yetecek kadar parlak olmayacak...",
"VO__LUCAS__CH03__CHATTER__LOOKING_FOR_CART__010__M__1": "Yukarıda bir krank var!",
"VO__LUCAS__CH03__CHATTER__LOOKING_FOR_CART__030__M__1": "Bir şey olmalı...",
"VO__LUCAS__CH03__CHATTER__LOOKING_FOR_CART__060__M__1": "Şey, bilmiyorum! Burası darmadağın! Olabilir...",
"VO__LUCAS__CH03__CHATTER__LOOKING_FOR_CART__070__M__1": "İşte! Bir araba buldum!",
"VO__LUCAS__CH03__CHATTER__LOOT_CART__070__M__1": "O araba Amicia... köpek üzümü içinde olabilir! Belki sapanın da!",
"VO__LUCAS__CH03__CHATTER__LOOT_CART__090__M__1": "Daha akıllıca, evet.",
"VO__LUCAS__CH03__CHATTER__LUCAS_LOOKING_1__010__M__1": "Kuru bitkiler, tozlar...",
"VO__LUCAS__CH03__CHATTER__LUCAS_LOOKING_1__020__M__1": "Aramaya devam et...",
"VO__LUCAS__CH03__CHATTER__LUCAS_LOOKING_2__010__M__1": "Belki burada... Hayır... Hmmm bunu sonraya saklayalım...",
"VO__LUCAS__CH03__CHATTER__LUCAS_LOOKING_2__020__M__1": "Hadi, nerede o köpek üzümü...?",
"VO__LUCAS__CH03__CHATTER__LUCAS_LOOKING_3__010__M__1": "Hayır... Hayır... Hayır... Ama şu... yine de işe yarayabilir...",
"VO__LUCAS__CH03__CHATTER__LUCAS_LOOKING_3__020__M__1": "Bana biraz köpek üzümü ver!",
"VO__LUCAS__CH03__CHATTER__LUCAS_LOWER__010__M__1": "İniyoruz...",
"VO__LUCAS__CH03__CHATTER__LUCAS_LOWER__030__M__1": "Ha... evet...",
"VO__LUCAS__CH03__CHATTER__LUCAS_ORDER_LOWER__020__M__1": "Hemen şimdi!",
"VO__LUCAS__CH03__CHATTER__LUCAS_RELEASE__010__M__1": "Hey!",
"VO__LUCAS__CH03__CHATTER__LUCAS_SCREAM_1__005__M__1": "Aah!",
"VO__LUCAS__CH03__CHATTER__LUCAS_SCREAM_2__005__M__1": "Aah! Dur!",
"VO__LUCAS__CH03__CHATTER__LUCAS_WAITING__010__M__1": "Amicia... O zinciri kırabilirsin!",
"VO__LUCAS__CH03__CHATTER__MEET_MURDERER__020__M__1": "Biri!",
"VO__LUCAS__CH03__CHATTER__MEET_MURDERER__040__M__1": "Eyvah, bir asker!",
"VO__LUCAS__CH03__CHATTER__MEET_MURDERER__095__M__1": "Fırlatacak!",
"VO__LUCAS__CH03__CHATTER__MEET_MURDERER__100__M__1": "Amicia!",
"VO__LUCAS__CH03__CHATTER__NEAR_SQUEEZE__020__M__1": "Denemeye değer...",
"VO__LUCAS__CH03__CHATTER__NEW_PLAN__020__M__1": "Çok kalabalıklar... Aralarından gizlice geçemeyiz...",
"VO__LUCAS__CH03__CHATTER__NEW_PLAN__040__M__1": "Bilmiyorum... Burası tıka basa... Bir şeyler dolu?",
"VO__LUCAS__CH03__CHATTER__NEW_WAVE__030__M__1": "Kalkanı var! Dikkat!",
"VO__LUCAS__CH03__CHATTER__NIGHTSHADE_FOUND__065__M__1": "Ah! Burada bir sürü faydalı şey var...",
"VO__LUCAS__CH03__CHATTER__NIGHTSHADE_FOUND__071__M__1": "O koku... bu... Evet! Köpek üzümünü buldum Amicia!",
"VO__LUCAS__CH03__CHATTER__NIGHTSHADE_FOUND__090__M__1": "Bir simyacının burnuna her zaman güven...",
"VO__LUCAS__CH03__CHATTER__NIGHTSHADE_FOUND__110__M__1": "Gidip kapıyı kontrol edeyim.",
"VO__LUCAS__CH03__CHATTER__NIGHTSHADE_FOUND__120__M__1": "Dışarıdan sesler duyuyorum. Dikkatli olmalıyız.",
"VO__LUCAS__CH03__CHATTER__NIGHTSHADE_LOOKAT_A__020__M__1": "Sorun değil... Sadece aramaya devam et!",
"VO__LUCAS__CH03__CHATTER__NIGHTSHADE_LOOKAT_C__020__M__1": "Hey! Artık buradayız! Sorun yok!",
"VO__LUCAS__CH03__CHATTER__NIGHTSHADE_REACT_4__030__M__1": "Biliyorum! Hadi evi kontrol edelim!",
"VO__LUCAS__CH03__CHATTER__NIGHTSHADE_SEARCH__030__M__1": "Tamam. Köpek üzümü. Umarım hâlâ kesesindedir.",
"VO__LUCAS__CH03__CHATTER__NIGHTSHADE_SEARCH__050__M__1": "Hayır. O kelimeyi söyleme.",
"VO__LUCAS__CH03__CHATTER__NOT_FINE_IDLE__020__M__1": "Sorun ne?!",
"VO__LUCAS__CH03__CHATTER__OPENED_WINDOW__010__M__1": "Şurada bir pencere var!",
"VO__LUCAS__CH03__CHATTER__OUTSIDE_RAIN_INTRO__010__M__1": "Berbat bir yağmur... Önümüzde uzun bir yol var — vakit kaybetmeyelim.",
"VO__LUCAS__CH03__CHATTER__PULL_DOWN_CHAIN__026__M__1": "Zincir hâlâ tutuyor!",
"VO__LUCAS__CH03__CHATTER__PULL_DOWN_NO_CHAIN__020__M__1": "Güzel...",
"VO__LUCAS__CH03__CHATTER__PUSHCART_DEPOT__020__M__1": "Şehirdeki karmaşa bizim lehimize işliyor olmalı...",
"VO__LUCAS__CH03__CHATTER__RAT_HOLES_IDLE__010__M__1": "Fare delikleri...",
"VO__LUCAS__CH03__CHATTER__ROTTEN_SLOPE__020__M__1": "Kasapların çöplüğü mü?... Oraya mı giriyoruz?!",
"VO__LUCAS__CH03__CHATTER__SALTPETER_PUSH_PULL__020__M__1": "Ordunun bunu saklamasına imkân yok...",
"VO__LUCAS__CH03__CHATTER__SALTPETER_PUSH_PULL__040__M__1": "Evet...",
"VO__LUCAS__CH03__CHATTER__SECOND_MEMORY__020__M__1": "Gerçekten mi?! Burada ne işi var?",
"VO__LUCAS__CH03__CHATTER__SECOND_MEMORY__040__M__1": "Hey, şu an... kendine bununla işkence etme...",
"VO__LUCAS__CH03__CHATTER__SECOND_WAVE__020__M__1": "Çok kalabalıklar! Gitmezsek gelmeye devam edecekler!",
"VO__LUCAS__CH03__CHATTER__SECRET_CHEST_TUTO__030__M__1": "O neydi?",
"VO__LUCAS__CH03__CHATTER__SENTINEL_SQUARE__030__M__1": "Nasıl bu kadar aptal olabiliyorlar?",
"VO__LUCAS__CH03__CHATTER__SHAKING_IDLE__010__M__1": "Titriyorsun...",
"VO__LUCAS__CH03__CHATTER__SHOOT_HAM__020__M__1": "Evet, aferin...",
"VO__LUCAS__CH03__CHATTER__SLING_BACK__030__M__1": "Onunla dikkatli ol, tamam mı?",
"VO__LUCAS__CH03__CHATTER__SMALL_LEDGE__005__M__1": "Şaka mı yapıyorsun?!",
"VO__LUCAS__CH03__CHATTER__SMALL_LEDGE__020__M__1": "Ah lütfen... Lütfen, lütfen...",
"VO__LUCAS__CH03__CHATTER__SMALL_LEDGE__045__M__1": "Ben... açıkçası... şu an umurumda değil...",
"VO__LUCAS__CH03__CHATTER__SMALL_LEDGE__110__M__1": "Öf... Şu çatıdan inelim, lütfen...",
"VO__LUCAS__CH03__CHATTER__SMOKE_PRESSURE__010__M__1": "Hazırım. Ne zaman olduğunu söyle...",
"VO__LUCAS__CH03__CHATTER__SMOKE_PRESSURE__030__M__1": "Amicia... Acele etmeliyiz...",
"VO__LUCAS__CH03__CHATTER__SMOKE_TUTO__020__M__1": "Merdivenler, koş! Uzun sürmez!",
"VO__LUCAS__CH03__CHATTER__SMOKE_TUTO__050__M__1": "Ona Stupefacio diyorum! Alışacaksın!",
"VO__LUCAS__CH03__CHATTER__SOLDIER_STREET_DEAD__010__M__1": "Sanırım müstahaktı.",
"VO__LUCAS__CH03__CHATTER__SOLDIERS_1ST_WAVE__030__M__1": "Hayır! İhtiyacımız olanı aldık! Hemen gidelim!",
"VO__LUCAS__CH03__CHATTER__SPEARMAN_REACTION__002__M__1": "Az önce... Provence ordusunun bir askerini öldürdün...",
"VO__LUCAS__CH03__CHATTER__SPEARMAN_VICTIM__010__M__1": "Bak... Kasaba halkını öldürüyorlar...",
"VO__LUCAS__CH03__CHATTER__SPOT_SALTPETER__012__M__1": "Evet. Hem de çok.",
"VO__LUCAS__CH03__CHATTER__SPOT_SALTPETER__018__M__1": "Deneyelim.",
"VO__LUCAS__CH03__CHATTER__SQUIZZ_OK__010__M__1": "Buradan Amicia!",
"VO__LUCAS__CH03__CHATTER__SQUIZZ_SPOT__010__M__1": "Hey... şuradan bir arka sokak var... Ne dersin?",
"VO__LUCAS__CH03__CHATTER__SQUIZZ_SPOT__030__M__1": "Dur...",
"VO__LUCAS__CH03__CHATTER__SQUIZZ_SPOT__040__M__1": "Sanırım...",
"VO__LUCAS__CH03__CHATTER__SQUIZZ_SPOT__050__M__1": "Evet!",
"VO__LUCAS__CH03__CHATTER__SQUIZZ_THROUGH_STREET__020__M__1": "Birinin evi mi?",
"VO__LUCAS__CH03__CHATTER__STUPEFACIO_BALLISTA__010__M__1": "Dur! Stupefacio!",
"VO__LUCAS__CH03__CHATTER__STUPEFACIO_BALLISTA__030__M__1": "Sanırım o noktayı geçtik.",
"VO__LUCAS__CH03__CHATTER__STUPEFACIO_SET__010__M__1": "Hazır. Sanırım yandaki krank onu kuruyor...",
"VO__LUCAS__CH03__CHATTER__TO_CRANK__010__M__1": "Sürgülü kapıyı kapatmışlar...",
"VO__LUCAS__CH03__CHATTER__TO_CRANK__050__M__1": "Söylemekten nefret ediyorum... ama o daha beterini atlattı.",
"VO__LUCAS__CH03__CHATTER__TORTURE_ROOM__020__M__1": "Şimdi sırası değil!",
"VO__LUCAS__CH03__CHATTER__TOWER_DOOR__020__M__1": "Hayır, hayır, kapana kısılamayız...",
"VO__LUCAS__CH03__CHATTER__TOWER_SAFE__010__M__1": "Evet, evet... Şimdi nereye?!",
"VO__LUCAS__CH03__CHATTER__TRY_LEAVE_NO_USED__010__M__1": "Şu tezgâha gerçekten şimdi bir baksan iyi olur. O köpek üzümünü bulmak için her türlü yardıma ihtiyacımız var.",
"VO__LUCAS__CH03__CHATTER__TWO_FIRST_KILLS__030__M__1": "Amicia! Ne yapıyorsun?! Gitmeliyiz!",
"VO__LUCAS__CH03__CHATTER__UPSTAIRS_ROOM__010__M__1": "Umarım bu karmaşada şifacımızı buluruz...",
"VO__LUCAS__CH03__CHATTER__VILLAGE_EMPTY__010__M__1": "Çok sessiz...",
"VO__LUCAS__CH03__CHATTER__VILLAGE_EMPTY__030__M__1": "Kan yok. Çatışma izi yok.",
"VO__LUCAS__CH03__CHATTER__VILLAGE_EMPTY__050__M__1": "Şimdilik bunun avantajını kullanalım.",
"VO__LUCAS__CH03__CHATTER__VILLAGE_RATS__010__M__1": "Hadi! Buradalar! Burada da varlar!",
"VO__LUCAS__CH03__CHATTER__VILLAGE_RATS__030__M__1": "Şu leşler yüzünden...",
"VO__LUCAS__CH03__CHATTER__VILLAGE_RATS__060__M__1": "Ama biz... kanın nerede bittiğini bilmiyoruz...",
"VO__LUCAS__CH03__CHATTER__VILLAGE_SAVED__010__M__1": "Öf... Bunu beklemiyordum!",
"VO__LUCAS__CH03__CHATTER__VILLAGE_SAVED__030__M__1": "Korkarım onlarla işimiz bitmedi.",
"VO__LUCAS__CH03__CHATTER__VILLAGE_SURPRISED__030__M__1": "Dikkat et!",
"VO__LUCAS__CH03__CHATTER__VISTA__010__M__1": "İşte şehir kapısı.",
"VO__LUCAS__CH03__CHATTER__VISTA__030__M__1": "Her şey yoluna girecek...",
"VO__LUCAS__CH03__CHATTER__VISTA_CITY__020__M__1": "Şehrin günleri sayılı...",
"VO__LUCAS__CH03__CHATTER__WAITING_DOOR__010__M__1": "Sapanını buldun mu?",
"VO__LUCAS__CH03__CHATTER__WAR_TREASURE__010__M__1": "Gerçekten mi?! Evet! Haklısın! O zaman demek ki... Köpek üzümü burada bir yerde olmalı!",
"VO__LUCAS__CH03__CHATTER__WASTING_TIME_IDLE__020__M__1": "Geliyoruz...",
"VO__LUCAS__CH03__CHATTER__WORKBENCH_NO_TOOL__020__M__1": "Bir tane için tetikte oluruz.",
"VO__LUCAS__CH03__CHATTER__WORKBENCH_OK_GO__010__M__1": "Gitmeye hazır mıyız?",
"VO__LUCAS__CH03__HELPER__ANOTHER_WAY_1__010__M__1": "Amicia, burada!",
"VO__LUCAS__CH03__HELPER__ANOTHER_WAY_2__010__M__1": "Bir giriş açtım Amicia!",
"VO__LUCAS__CH03__HELPER__BALLISTA_CRANK_1__010__M__1": "Şu krankta yardım gerekirse söyle...",
"VO__LUCAS__CH03__HELPER__BALLISTA_CRANK_2__010__M__1": "Amicia, kranı bana bırak, sen kilidi kır!",
"VO__LUCAS__CH03__HELPER__CART_ROLL_1__010__M__1": "Ateşlerin üstünden bir şekilde köprü kurmamız gerek...",
"VO__LUCAS__CH03__HELPER__CART_ROLL_2__010__M__1": "Hey! Bir çömlek Ignifer kullan! Geçmemize tam yetebilir!",
"VO__LUCAS__CH03__HELPER__EXTINGUIS_STREET_1__010__M__1": "O asker yoldayken geçemeyiz...",
"VO__LUCAS__CH03__HELPER__EXTINGUIS_STREET_2__010__M__1": "Amicia, Exstinguis'i meşaleye atmalısın!",
"VO__LUCAS__CH03__HELPER__EXTINGUIS_TUTO_1__010__M__1": "Meşaleyi vurduğundan emin ol...",
"VO__LUCAS__CH03__HELPER__EXTINGUIS_TUTO_2__010__M__1": "Amicia, Exstinguis'i meşaleye atmalısın!",
"VO__LUCAS__CH03__HELPER__EXTINGUISH_JAR_1__010__M__1": "Çömlekle ikisini birden vurduğundan emin ol...",
"VO__LUCAS__CH03__HELPER__EXTINGUISH_JAR_2__010__M__1": "Çömleği tam ikisinin arasına at!",
"VO__LUCAS__CH03__HELPER__FREE_BALLISTA_1__010__M__1": "Balistayı kurtarmak için o zinciri kırmanın bir yolu olabilir!",
"VO__LUCAS__CH03__HELPER__FREE_BALLISTA_2__010__M__1": "Sanırım o zincirin ucunda bir kilit var! Sapanınla kırabilirsin!",
"VO__LUCAS__CH03__HELPER__GUARD_1ST_REMPART_1__010__M__1": "Amicia, hâlâ biraz Stupefacio'm var! Senin sözünle kullanabilirim!",
"VO__LUCAS__CH03__HELPER__GUARD_1ST_REMPART_2__010__M__1": "O ateşle bir duman bulutu daha oluşturabilirim. Ne zaman olduğunu söyle yeter.",
"VO__LUCAS__CH03__HELPER__HANGING_SHEEP_1__010__M__1": "Şu fareleri oyalamamız gerek...",
"VO__LUCAS__CH03__HELPER__HANGING_SHEEP_2__010__M__1": "Yukarı bak! Şaşırtmamız işte o!",
"VO__LUCAS__CH03__HELPER__HOUSE_CARCASSSES_1__010__M__1": "Bir merdiven var... Fareleri kımıldatmanın bir yolunu bulmalıyız...",
"VO__LUCAS__CH03__HELPER__HOUSE_CARCASSSES_2__010__M__1": "Amicia! Bir jambonu kesmeyi dene. Dikkatlerini dağıtmaya yetebilir!",
"VO__LUCAS__CH03__HELPER__HOUSE_FIRE_1__010__M__1": "Ha... Şu ateşi bir şekilde söndürmemiz gerek...",
"VO__LUCAS__CH03__HELPER__HOUSE_FIRE_2__010__M__1": "Güherçile! Alevleri boğmak için biraz kullanabiliriz!",
"VO__LUCAS__CH03__HELPER__PIG_BRASIER_1__010__M__1": "Hey! Şu evin orada zaten yanan bir ateş var! Ona ulaşmanın bir yolunu bulmaya çalışmalıyız!",
"VO__LUCAS__CH03__HELPER__PIG_BRASIER_2__010__M__1": "Bak! Bir mangal daha! Şu domuz leşlerinin yanında! Karşıya geçişimiz işte o!",
"VO__LUCAS__CH03__HELPER__REACH_BALLISTA_1__010__M__1": "Şu kranka ulaşmak için bir şey lazım...",
"VO__LUCAS__CH03__HELPER__REACH_BALLISTA_2__010__M__1": "Sanırım bu araba bizi oraya çıkarmaya yetebilir!",
"VO__LUCAS__CH03__HELPER__SMOKE_TUTO_1__010__M__1": "Ne zaman olduğunu söyle, bir şaşırtma yaratayım...",
"VO__LUCAS__CH03__HELPER__SMOKE_TUTO_2__010__M__1": "Bana bir işaret ver, bizi buradan çıkarayım...",
"VO__LUCAS__CH03__HELPER__TO_CRANK__010__M__1": "Kranklar yukarıda olmalı...",
"VO__LUCAS__CH03__ONOM__CART_ROLL__020__M__1": "Ah!",
"VO__LUCAS__CH03__RTC__112_CLOSEDDOOR__020__M__1": "Geliyorum!",
"VO__LUCAS__CH03__RTC__112_CLOSEDDOOR__110__M__1": "Elbette.",
"VO__LUCAS__CH03__RTC__118_CONTROL_LOST__010__M__1": "Hayır, içeri giriyorlar... Ne yapacağız?",
"VO__LUCAS__CH03__RTC__118_CONTROL_LOST__020__M__1": "Hey...",
"VO__LUCAS__CH03__RTC__118_CONTROL_LOST__040__M__1": "İyi değilsin.",
"VO__LUCAS__CH03__RTC__118_CONTROL_LOST__060__M__1": "Hayır değilsin, şu an düzgün nefes bile alamıyorsun.",
"VO__LUCAS__CH03__RTC__118_CONTROL_LOST__080__M__1": "Biliyorum... Dinle, Kont'un askerleri her şeye el koyacak. Onlardan önce köpek üzümünü almalıyız. Ben almalıyım.",
"VO__LUCAS__CH03__RTC__118_CONTROL_LOST__100__M__1": "Bunu yapacak hâlde değilsin. Ben gidiyorum. İçeri sızarım. Yapabilirim.",
"VO__LUCAS__CH03__RTC__118_CONTROL_LOST__120__M__1": "Koşarım. İlk seferim değil.",
"VO__LUCAS__CH03__RTC__118_CONTROL_LOST__132__M__1": "Dur! Bırak gideyim!",
"VO__LUCAS__CH03__RTC__121_JAIL__030__M__1": "Demek bütün söyleyeceğin bu!",
"VO__LUCAS__CH03__RTC__121_JAIL__040__M__1": "Hadi, bundan iyisini yapabilirsin! Koca bir garnizonun var burada! Neden gerçekten kendini koyvermiyorsun?!",
"VO__LUCAS__CH03__RTC__121_JAIL__060__M__1": "HAYIR!",
"VO__LUCAS__CH03__RTC__121_JAIL__070__M__1": "İçinde bulunduğumuz durumu görüyor musun? Sadece ot toplamamız gerekiyordu. Sence Hugo şu an onlarsız ne hissediyor? Ablası asıldığında ne hissedecek?",
"VO__LUCAS__CH03__RTC__121_JAIL__100__M__1": "Evet, çünkü bu dünya acıtıyor, acıtmaya devam ediyor ve sen de ona acı çektirmek istiyorsun... Ama bu, kazanamayacağın bir kavga... Amicia... Sen onlar değilsin. Sen bir De Rune'sün.",
"VO__LUCAS__CH03__RTC__121_JAIL__110__M__1": "Bu biziz... Dinle.",
"VO__LUCAS__CH03__RTC__121_JAIL__130__M__1": "Bu şey ateşle çalışıyor. Hazır olduğumda söylerim.",
"VO__LUCAS__CH03__RTC__122_EXIT_RUN__030__M__1": "İşe yaradı!",
"VO__LUCAS__CH03__RTC__122_GUILT__030__M__1": "Vardığımızda şifacı dışarıdaydı. Beklemek zorunda kaldık.",
"VO__LUCAS__CH03__RTC__122_GUILT__040__M__1": "Ama her şey bizde.",
"VO__LUCAS__CH03__RTC__ENTER_BUTCHER_DISTRICT__020__M__1": "Evet, kasaplar mahallesi. Şifacıya giden en kısa yol bu.",
"VO__PEOPLE_F1__CH03__CHATTER__2ND_STREET__130__M__1": "Çocuklarım içeride!",
"VO__PEOPLE_F1__CH03__CHATTER__FLEEING_HOUSE__010__M__1": "Paul! Hemen gidelim!",
"VO__PEOPLE_F2__CH03__CHATTER__2ND_STREET__140__M__1": "Bir şeyler döndüğünü biliyoruz!",
"VO__PEOPLE_F2__CH03__CHATTER__HALLES_RAIN_CHAT_AMBIENT1__010__M__1": "Bu yağmur hiç dinmeyecek.",
"VO__PEOPLE_F2__CH03__CHATTER__HALLES_RAIN_CHAT_AMBIENT2__010__M__1": "Tam bir felaket. Mallarımın üstü çamur içinde kaldı!",
"VO__PEOPLE_F3__CH03__CHATTER__2ND_STREET__160__M__1": "İnsanlar mı öldü?!",
"VO__PEOPLE_F4__CH03__CHATTER__2ND_STREET__020__M__1": "Bırakın geçelim!",
"VO__PEOPLE_F4__CH03__CHATTER__WOMAN_CRYING__010__M__1": "Babam evde tek başına!",
"VO__PEOPLE_F5__CH03__CHATTER__2ND_STREET__070__M__1": "Ne?!",
"VO__PEOPLE_F5__CH03__CHATTER__HALLES_RAIN_CHAT_ARENA__020__M__1": "Şurada ne oldu?",
"VO__PEOPLE_M1__CH03__CHATTER__2ND_STREET__010__M__1": "Neler oluyor?!",
"VO__PEOPLE_M1__CH03__CHATTER__ANOTHER_SOLDIER_STREET__040__M__1": "Bırakın çıkalım! Fareler yakında!",
"VO__PEOPLE_M1__CH03__CHATTER__MERCHANT_SHOUTS__015__M__1": "Domuz! Domuz! Kızartmalık! Haşlamalık! Dünyanın en lezzetli eti!",
"VO__PEOPLE_M1__CH03__CHATTER__MERCHANT_SHOUTS__018__M__1": "Tavuklarına bak sen, geveze herif!",
"VO__PEOPLE_M2__CH03__CHATTER__MERCHANT_SHOUTS__020__M__1": "Hiç dana eti yemediysen, neyi kaçırdığını bilmiyorsun!",
"VO__PEOPLE_M3__CH03__CHATTER__MERCHANT_SHOUTS__010__M__1": "Hadi iyi insanlar! İsteyeceğiniz her türlü kümes hayvanı bende!",
"VO__PEOPLE_M3__CH03__CHATTER__MERCHANT_SHOUTS__016__M__1": "O yalancıyı dinlemeyin!",
"VO__PEOPLE_M3__CH03__CHATTER__MERCHANT_SHOUTS__017__M__1": "Domuzlarının ne kadar pis olduğunu hepimiz biliyoruz!",
"VO__PEOPLE_M4__CH03__CHATTER__ALLEY_MURDERS__010__M__1": "Lütfen! Lütfen hayır!",
"VO__PEOPLE_M4__CH03__CHATTER__FLEEING_HOUSE__020__M__1": "Dur, ışık!",
"VO__PEOPLE_M4__CH03__CHATTER__HERBALIST_DEATH__010__M__1": "Bu rezalet! Karım nerede?! Bitkilerimle ne yapıyorsunuz?! Onlara ihtiyacı olan doktorlarım ve hastalarım var!",
"VO__PEOPLE_M4__CH03__CHATTER__HERBALIST_DEATH__050__M__1": "Aman Tanrım... bu cesetler... Bu insanları tanıyordum!",
"VO__PEOPLE_M4__CH03__CHATTER__HERBALIST_DEATH__070__M__1": "Bu farelerin işi değil... Siz yaptınız! Hepsini siz öldürdünüz! Karımı görmek istiyorum!",
"VO__PEOPLE_M4__CH03__CHATTER__HERBALIST_DEATH__090__M__1": "Size yardım etmemi mi istiyorsunuz? Ama hepiniz çoktan ölüsünüz zaten!",
"VO__PEOPLE_M4__CH03__CHATTER__HERBALIST_DEATH__130__M__1": "Hepiniz yakında hastalanacaksınız. Ve ben de ölüşünüzü izlerken güleceğim!",
"VO__PEOPLE_M4__CH03__CHATTER__HERBALIST_DEATH__160__M__1": "Benden yardım istiyorsan SEN diz çök, köpek!",
"VO__PEOPLE_M5__CH03__CHATTER__2ND_STREET__080__M__1": "Bizi dışarıda tutamazsınız!",
"VO__PEOPLE_M5__CH03__CHATTER__2ND_STREET__120__M__1": "Neler olduğunu söyleyin bize!",
"VO__PEOPLE_M5__CH03__CHATTER__2ND_STREET__150__M__1": "Bizden ne saklıyorsunuz?!",
"VO__PEOPLE_M6__CH03__CHATTER__2ND_STREET__170__M__1": "Nereye gitmemizi istiyorsunuz?!",
"VO__PEOPLE_M6__CH03__CHATTER__HALLES_RAIN_CHAT_ARENA__010__M__1": "Arenaya giden yolu kapattıklarına inanamıyorum...",
"VO__PEOPLE_M6__CH03__CHATTER__HALLES_RAIN_CHAT_ARENA__030__M__1": "Bilmiyorum, bir koku vardı... Umarım uzun sürmez...",
"VO__PEOPLE_M6__CH03__CHATTER__HELMET_RUNAWAY__020__M__1": "Hayır! Bırakın gideyim!",
"VO__SOLDIER_B1__CH03__CHATTER__ANOTHER_SOLDIER_STREET__020__M__1": "Evleri gözleyin! Kimsenin çıkmadığından emin olun! Sokaklarda ne kadar çok ölü olursa, o kadar çok lanet fare gelir!",
"VO__SOLDIER_B1__CH03__CHATTER__HERBALIST_ENCOUNTER_START__010__M__1": "Dikkat! Az önce şurada bir yağmacı yakaladık! Başkaları olabilir! Bölgeyi arayın ve görür görmez öldürün!",
"VO__SOLDIER_B1__CH03__CHATTER__SMOKE_PRESSURE__020__M__1": "Orada dur! Cellatı bekleyeceğiz, şu an birini bitiriyor olmalı.",
"VO__SOLDIER_B1__CH03__CHATTER__SMOKE_PRESSURE__040__M__1": "Canavar'ın önünde terbiyeli ol! Artık soğumuş etsin. Kargalara yem. Ona göre davran.",
"VO__SOLDIER_B1__CH03__CHATTER__SMOKE_PRESSURE_IDLE__010__M__1": "Şehrimizi kurtarmaya çalışan eğitimli adamları öldürdün. Bizi kaosa biraz daha yaklaştırdın. Ölümün yavaş olacak.",
"VO__SOLDIER_B1__CH03__CHATTER__SMOKE_PRESSURE_IDLE__020__M__1": "İçine cin kaçmış! Ama içindeki o şeytanı boğacağız.",
"VO__SOLDIER_B1__CH03__CHATTER__SMOKE_TUTO__030__M__1": "Bu da ne be?!",
"VO__SOLDIER_B1__CH03__CHATTER__SMOKE_TUTO__060__M__1": "Hiçbir şey göremiyorum!",
"VO__SOLDIER_B1__CH03__RTC__118_CONTROL_LOST__005__M__1": "Sen! Burada kal ve devriye gez! Tek bir lanet fare bile görürsen haber ver!",
"VO__SOLDIER_B1__CH03__RTC__118_CONTROL_LOST__007__M__1": "Diğerleri benimle! Değerli ne varsa arayın! Yiyecek, ilaç... her türlü mal lazım!",
"VO__SOLDIER_B1__CH03__RTC__120_JAIL__040__M__1": "Adamlarımı öldürmeyi göstereceğim sana!",
"VO__SOLDIER_B1__CH03__RTC__120_JAIL__050__M__1": "Seninle işimizin bittiğini sanma.",
"VO__SOLDIER_B1__CH03__RTC__121_JAIL__010__M__1": "Yaptıklarından sonra çabuk bir ölüm bekleme! Asılmadan önce seninle biraz vakit geçirsin diye cellata para ödedik...",
"VO__SOLDIER_B1__CH03__RTC__121_JAIL__140__M__1": "Dışarı. İlmikleriniz bekliyor.",
"VO__SOLDIER_N1__CH03__CHATTER__ANOTHER_SOLDIER_STREET__030__M__1": "Kahretsin... O kapıları açmak için bana güvenme... İçeride ne olduğunu biliyorum...",
"VO__SOLDIER_N1__CH03__CHATTER__ANOTHER_SOLDIER_STREET__050__M__1": "Kapa çeneni! O senin sorunun! Kim çıkarsa, öldürülür!",
"VO__SOLDIER_N1__CH03__CHATTER__ANOTHER_SOLDIER_STREET__060__M__1": "İçeride kalın! Hâlâ hayattaysanız tabii.",
"VO__SOLDIER_N1__CH03__CHATTER__ANOTHER_SOLDIER_STREET__070__M__1": "Duydun mu?! Kim çıkarsa, öldürülür!",
"VO__SOLDIER_N1__CH03__CHATTER__ARCHER_PATROL__020__M__1": "Henüz bir şey yok! Çalıları gözden kaçırma! İçlerinde saklanıyor olabilirler!",
"VO__SOLDIER_N1__CH03__CHATTER__GATE_PATROL__030__M__1": "Kont'tan haber var mı?",
"VO__SOLDIER_N1__CH03__CHATTER__GATE_PATROL__040__M__1": "Canavar mı? Bu katliamı açıklıyor... Adam bir savaş köpeği.",
"VO__SOLDIER_N1__CH03__CHATTER__GATE_PATROL_IDLE__020__M__1": "Belki geride bir şey bırakmışlardır.",
"VO__SOLDIER_N1__CH03__CHATTER__HERBALIST_ENCOUNTER__010__M__1": "Bir yağmacı mı? Buraya gelecek kadar deli olan kim ki...?",
"VO__SOLDIER_N1__CH03__CHATTER__HERBALIST_ENCOUNTER_START__020__M__1": "Anlaşıldı! Dağılın çocuklar! Dikkatli olun!",
"VO__SOLDIER_N1__CH03__CHATTER__HIGHER_SQUARE__010__M__1": "Unutmayın çocuklar! Ne pahasına olursa olsun ışıkta kalın!",
"VO__SOLDIER_N1__CH03__CHATTER__INSIDE_HOUSE_IDLE__010__M__1": "Bütün mahalleyi ateşe versek daha iyi... Lanet hikâyenin sonu.",
"VO__SOLDIER_N1__CH03__CHATTER__LOOKING_FOR_CART__040__M__1": "Hey! Git daha çok adam getir! Devriyelerdeki adam sayısını ikiye katlıyoruz!",
"VO__SOLDIER_N1__CH03__CHATTER__NIGHTSHADE_FOUND__102__M__1": "Bilmiyorum, umurumda değil... Oraya çıkmak istemezsin, inan bana!",
"VO__SOLDIER_N1__CH03__CHATTER__SENTINEL_SQUARE__010__M__1": "Temizlediğiniz evleri haçla işaretlemeyi unutmayın! Cesetlerin şehirden çıkarılması şart!",
"VO__SOLDIER_N1__CH03__CHATTER__SOLDIERS_PATROL__020__M__1": "Bizim gibi mi?",
"VO__SOLDIER_N2__CH03__CHATTER__2ND_STREET__050__M__1": "Bu mahalle artık Arles Kontu Victor'un yetkisiyle kapatılmıştır!",
"VO__SOLDIER_N2__CH03__CHATTER__2ND_STREET__060__M__1": "Kendi güvenliğiniz için içeri girmeye çalışmayın!",
"VO__SOLDIER_N2__CH03__CHATTER__ABOUT_COUNT__010__M__1": "Cidden... bir kuşatma için stok yapmanın ne anlamı var? İnsanlar panikler demiyorum, ama bir isyan...?",
"VO__SOLDIER_N2__CH03__CHATTER__ABOUT_COUNT__030__M__1": "Bize karşı dönerler, evet...",
"VO__SOLDIER_N2__CH03__CHATTER__ALARM_SOLDIER__020__M__1": "Neyle?",
"VO__SOLDIER_N2__CH03__CHATTER__ALARM_SOLDIER__040__M__1": "İki gündür tam da onu yapıyorum! Bırak da molamı vereyim, kahretsin!",
"VO__SOLDIER_N2__CH03__CHATTER__ALARM_SOLDIER__050__M__1": "Çok yorgunum... Olan bitenle uyuyamıyorum...",
"VO__SOLDIER_N2__CH03__CHATTER__CAPTAIN_CHURCH__010__M__1": "Cehennem gibi göründüğünü biliyorum, ama görevlerinize odaklanın! Temizleyiciler! Cesetlerin ışıkta kaldığından emin olun! Toplayıcılar! Yalnızca garnizona lazım olanı alın! Yiyecek ve silah!",
"VO__SOLDIER_N2__CH03__CHATTER__GATE_PATROL__035__M__1": "Hayır. Canavar'a şehir üzerinde tam yetki verdiğini duydum.",
"VO__SOLDIER_N2__CH03__CHATTER__GATE_PATROL_IDLE__010__M__1": "Ne yapıyorsun? Toplayıcılar burayı çoktan süpürdü!",
"VO__SOLDIER_N2__CH03__CHATTER__GATE_PATROL_IDLE__030__M__1": "İyi şanslar bununla.",
"VO__SOLDIER_N2__CH03__CHATTER__HALLES_RAIN_ARENA__010__M__1": "Arena mahallesi kapalı! Kimse geçemez!",
"VO__SOLDIER_N2__CH03__CHATTER__HELMET_IDLE__010__M__1": "Cehennem... Bunlar nereden geliyor?",
"VO__SOLDIER_N2__CH03__CHATTER__HELMET_IDLE__020__M__1": "Şuna bak... Resmen saldırıyorlar... Dehşet verici...",
"VO__SOLDIER_N2__CH03__CHATTER__HELMET_RUNAWAY__010__M__1": "Hey! Buraya gel, seni alçak!",
"VO__SOLDIER_N2__CH03__CHATTER__HELMET_RUNAWAY__040__M__1": "Kahrolası! Neyse, daha öteye gidemezsin...",
"VO__SOLDIER_N2__CH03__CHATTER__HELMET_RUNAWAY__050__M__1": "Lanet ısıranlar bizden hızlı öldürüyor...",
"VO__SOLDIER_N2__CH03__CHATTER__IDLE_CHASE_03__020__M__1": "Yeter! Ordunun onuru bizim elimizde!",
"VO__SOLDIER_N2__CH03__CHATTER__LOOT_CART__020__M__1": "Ne var? Daha çok el koyma mı?",
"VO__SOLDIER_N2__CH03__CHATTER__LOOT_CART__040__M__1": "Ah, şu çılgın kızla karşılaşanlar sizsiniz, değil mi?",
"VO__SOLDIER_N2__CH03__CHATTER__LOOT_CART__046__M__1": "İyi iş! Çabuk depoya gidin! Kız yakında asılacak. Epey kalabalık olacak.",
"VO__SOLDIER_N2__CH03__CHATTER__NIGHTSHADE_FOUND__100__M__1": "Eee? Gitmemize ne kadar var?",
"VO__SOLDIER_N2__CH03__CHATTER__SOLDIER_TALKING_PATROL__010__M__1": "Kont, Canavar'a güvenmekle hata etti! Öldürdüğümüz insanlar hâlâ hasta mı onu bile bilmiyoruz! Bu nerede duracak?!",
"VO__SOLDIER_N2__CH03__CHATTER__SOLDIER_TALKING_PATROL__030__M__1": "Ya da adamlar panikler, biliyorum!",
"VO__SOLDIER_N3__CH03__CHATTER__ABOUT_COUNT__020__M__1": "Şehirden kaçmak isteyecekler. Asıl sorun, kaçamayacaklarını fark ettiklerinde olacak.",
"VO__SOLDIER_N3__CH03__CHATTER__ALARM_SOLDIER__010__M__1": "Hey, bu arada bitirdin mi?",
"VO__SOLDIER_N3__CH03__CHATTER__ALARM_SOLDIER__030__M__1": "Depoyu temizliyorum!",
"VO__SOLDIER_N3__CH03__CHATTER__LOOT_CART__030__M__1": "Hı hı. Kenar mahalleden. Kasaplar mahallesi kapısından.",
"VO__SOLDIER_N3__CH03__CHATTER__LOOT_CART__045__M__1": "Evet... O lanet cadı ve sapanı... Ama Canavar onu yakaladı. Ve bir hafta dayanacak kadar etimiz var.",
"VO__SOLDIER_N3__CH03__CHATTER__LOOT_CART__050__M__1": "Orada olacağım!",
"VO__SOLDIER_S1__CH03__CHATTER__1ST_TOWER_REMPART__010__M__1": "Umarım mahalleleri güvene alabilmişlerdir... yoksa gerçekten büyük beladayız.",
"VO__SOLDIER_S1__CH03__CHATTER__ALLEY_MURDER__020__M__1": "Sadece emirleri uyguluyorum!",
"VO__SOLDIER_S1__CH03__CHATTER__ANOTHER_WAVE__010__M__1": "Seni öldüreceğim! Öldün sen!",
"VO__SOLDIER_S1__CH03__CHATTER__ARCHER_PATROL__010__M__1": "Bir şey görüyor musun?!",
"VO__SOLDIER_S1__CH03__CHATTER__BULLYING_LUCAS__010__M__1": "Konuş çocuk! Yanında kim var?!",
"VO__SOLDIER_S1__CH03__CHATTER__BULLYING_LUCAS__030__M__1": "Hadi! Senin gibi bir velet buraya tek başına gelemez!",
"VO__SOLDIER_S1__CH03__CHATTER__BULLYING_LUCAS__050__M__1": "Hemen konuş, yoksa seni öldürürüm!",
"VO__SOLDIER_S1__CH03__CHATTER__HERBALIST_DEATH__030__M__1": "Sana ve bitkilerine bu yüzden ihtiyacımız var! Şimdi kapa çeneni!",
"VO__SOLDIER_S1__CH03__CHATTER__HERBALIST_DEATH__060__M__1": "Seni üzüyorsa onlara bakma!",
"VO__SOLDIER_S1__CH03__CHATTER__HERBALIST_DEATH__080__M__1": "Dinle... uzun ve lanet bir gündü, kılıcım hâlâ sıcak, o yüzden...",
"VO__SOLDIER_S1__CH03__CHATTER__HERBALIST_DEATH__100__M__1": "Dinle şifacı... Hemen dur...",
"VO__SOLDIER_S1__CH03__CHATTER__HERBALIST_DEATH__140__M__1": "DUR! Diz çök! Hemen!",
"VO__SOLDIER_S1__CH03__CHATTER__HERBALIST_DEATH__165__M__1": "Şimdi haddini aştın...",
"VO__SOLDIER_S1__CH03__CHATTER__HERBALIST_SHACK__035__M__1": "Saklanan var mı diye bakın!",
"VO__SOLDIER_S1__CH03__CHATTER__HERBALIST_SHACK__045__M__1": "Fazla vaktimiz yok, o yüzden iyi değerlendirelim!",
"VO__SOLDIER_S1__CH03__CHATTER__IDLE_CHASE_02__020__M__1": "Buraya! Haddini bildirin ona!",
"VO__SOLDIER_S1__CH03__CHATTER__MEET_MURDERER__010__M__1": "Burada üç tane daha!... Kolay teslim olmadılar!",
"VO__SOLDIER_S1__CH03__CHATTER__MEET_MURDERER__030__M__1": "Hey! Burada ne işin var?!",
"VO__SOLDIER_S1__CH03__CHATTER__MEET_MURDERER__060__M__1": "Kimse çıkamaz! Emirler böyle!",
"VO__SOLDIER_S1__CH03__CHATTER__MEET_MURDERER__090__M__1": "Ölmüş olman gerekirdi!",
"VO__SOLDIER_S1__CH03__CHATTER__NEW_WAVE__010__M__1": "Burada neler oluyor be? Kimsin sen?!",
"VO__SOLDIER_S1__CH03__CHATTER__NEW_WAVE__040__M__1": "Burada davetsiz biri var! Silahlı!",
"VO__SOLDIER_S1__CH03__CHATTER__SOLDIER_TALKING_PATROL__020__M__1": "Canavar harekete geçiyor. Buna hemen ihtiyacımız var yoksa...",
"VO__SOLDIER_S1__CH03__CHATTER__SOLDIERS_PATROL__010__M__1": "Yağmacılar o yerde ne arıyor? Sence onlar da mı ilaç peşinde?",
"VO__SOLDIER_S1__CH03__CHATTER__SOLDIERS_PATROL__030__M__1": "Heh.",
"VO__SOLDIER_S1__CH03__CHATTER__VILLAGE_SURPRISED__010__M__1": "Bu da ne--Hey!",
"VO__SOLDIER_S1__CH03__CHATTER__VILLAGE_SURPRISED__040__M__1": "Seni unuttuk mu?! Bunu hemen düzeltirim!",
"VO__SOLDIER_S1__CH03__RTC__121_JAIL__105__M__1": "Hey! Darağacı neredeyse hazır! Mahkûmu hazırlayın!",
"VO__SOLDIER_S2__CH03__CHATTER__IDLE_CHASE_01__020__M__1": "Durdurun onu! Büyümüş de küçülmüş bir velet sadece!",
"VO__SOLDIER_S2__CH03__CHATTER__SOLDIERS_1ST_WAVE__010__M__1": "Ahırda bağırışlar duydum! Benimle gel! Tutsağı kim koruyor?!",
"VO__SOLDIER_S2__CH03__CHATTER__SOLDIERS_1ST_WAVE__050__M__1": "Adam yere düştü! Davetsiz biri var! Alarm!",
}
