# -*- coding: utf-8 -*-
# CH06 VO. onom/EMPTY atlanir. Perreux=haci lideri; flagellant->kamcili.
# Macula korunur; the Beast->Canavar, Count of Arles->Arles Kontu, the Wall->Duvar,
# dyeworks->boyahane, quarry->tas ocagi, jubilee->jubile, mass->ayin, Amen->Amin.
T = {
"VO__AMICIA__CH06__CHATTER__1ST_GALLERIES_IDLE__020__M__1": "Acıyor...",
"VO__AMICIA__CH06__CHATTER__2ND_DOOR__010__M__1": "Üşümeye... başlıyorum... daha hızlı hareket etmeliyim...",
"VO__AMICIA__CH06__CHATTER__2ND_ENCOUNTER_ENTRANCE__010__M__1": "Aman Tanrım... Bu yerin... büyüklüğü... Nasıl...?",
"VO__AMICIA__CH06__CHATTER__2ND_ENCOUNTER_ENTRANCE__030__M__1": "Henüz... değil...",
"VO__AMICIA__CH06__CHATTER__2ND_ENCOUNTER_ENTRANCE__060__M__1": "Askerler... Fareler... Dikkat.",
"VO__AMICIA__CH06__CHATTER__2ND_GALLERIES_IDLE__010__M__1": "Çıkış... bir çıkış lazım...",
"VO__AMICIA__CH06__CHATTER__2ND_GALLERIES_IDLE__030__M__1": "Hayır... İlerle.",
"VO__AMICIA__CH06__CHATTER__ABOUT_DEATH_IDLE__010__M__1": "Hugo, işler gerçekten kötüye giderse, sen...",
"VO__AMICIA__CH06__CHATTER__ABOUT_DEATH_IDLE__030__M__1": "Peki... Peki.",
"VO__AMICIA__CH06__CHATTER__AMICIA_COLLAPSE__020__M__1": "Başım çok... dönüyor...",
"VO__AMICIA__CH06__CHATTER__APPROACH_PULL__010__M__1": "Seni... yukarı... iteceğim... Hazır ol...",
"VO__AMICIA__CH06__CHATTER__BEGINNING_RATMOVE__030__M__1": "Kontrolü... koru... Hugo...",
"VO__AMICIA__CH06__CHATTER__BLEEDING_AGAIN__010__M__1": "Ah... Başım dönüyor... Ha... Elin...",
"VO__AMICIA__CH06__CHATTER__BLEEDING_AGAIN__030__M__1": "Tanrım...",
"VO__AMICIA__CH06__CHATTER__BUILDING_IDLE__020__M__1": "Evet...",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_FIGHT__010__M__1": "Başardığımıza... inanamıyorum...",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_FIGHT__040__M__1": "Ne?!... Hayır!",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_FIGHT__080__M__1": "Umurumda değil... Bunu... bitireceğim...",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_FIGHT__100__M__1": "Ha... Yanımda dur, Hugo...",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_FIRST_WEAKNESS__020__M__1": "Evet... Görüyorum...",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_ORDER_FOREST__030__M__1": "Çabuk...",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_ORDER_FOREST__070__M__1": "Çabuk, yayılıyorlar...",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_RING__030__M__1": "Henüz değil... ha... başım...",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_RING__050__M__1": "Hayır... hayır, yapamayacaksın...",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_SECOND_RESISTANCE__020__M__1": "Zırhı... Onu delemiyorum...",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_STUNNED_FIRST__020__M__1": "Şimdi o kadar... güçlü hissetmiyorsun, ha?!",
"VO__AMICIA__CH06__CHATTER__CAPTAIN_STUNNED_SECOND__020__M__1": "Ha... Şu hâline bak...",
"VO__AMICIA__CH06__CHATTER__CARNAGE__010__M__1": "Nasıl... hissediyorsun?",
"VO__AMICIA__CH06__CHATTER__CARNAGE__030__M__1": "Sen... onları kontrol ettin... eskisi gibi mi?",
"VO__AMICIA__CH06__CHATTER__CARNAGE__050__M__1": "Dikkatli ol... seni... ele geçirmemeliler...",
"VO__AMICIA__CH06__CHATTER__CARNAGE__055__M__1": "Macula seni... ele geçirmek istiyor... duygularınla besleniyor...",
"VO__AMICIA__CH06__CHATTER__CARNAGE__070__M__1": "Çok... dikkatli olmalısın...",
"VO__AMICIA__CH06__CHATTER__CARNAGE_PART_2__020__M__1": "İşçiler...",
"VO__AMICIA__CH06__CHATTER__CARNAGE_PART_2__030__M__1": "Demek ki... fareler biz gelmeden önce de... buradaydı...",
"VO__AMICIA__CH06__CHATTER__CARNAGE_PART_2__050__M__1": "Sen... fareler değilsin...",
"VO__AMICIA__CH06__CHATTER__CAUTIOUS_IDLE__020__M__1": "Güvende olana kadar... kendimi kötü hissetmeyeceğim...",
"VO__AMICIA__CH06__CHATTER__CHASED__020__M__1": "Koş Hugo! Dosdoğru!",
"VO__AMICIA__CH06__CHATTER__CRANE_COLLAPSE__010__M__1": "Eyvah...",
"VO__AMICIA__CH06__CHATTER__CROSSING_PEN__010__M__1": "Hadi, buradan uzaklaşmalıyız.",
"VO__AMICIA__CH06__CHATTER__CROSSING_PEN__030__M__1": "Bizi bulmazlarsa kimseye zarar vermezler. Olabildiğince uzaklaşalım!",
"VO__AMICIA__CH06__CHATTER__DEAD_WORKERS_IDLE__020__M__1": "Bu senin yaptığın bir şey değil...",
"VO__AMICIA__CH06__CHATTER__DISCOVER_CANYON__010__M__1": "Şu binaya... ulaşmalıyız...",
"VO__AMICIA__CH06__CHATTER__DISCOVER_CANYON__030__M__1": "Bilmiyorum... ama çok açıktayız... orada deneriz... belki daha güvenlidir...",
"VO__AMICIA__CH06__CHATTER__DISTRACT_WAIT__010__M__1": "İyi fikir!",
"VO__AMICIA__CH06__CHATTER__DISTRACT_WAIT__030__M__1": "Henüz değil. İşaretini bekle.",
"VO__AMICIA__CH06__CHATTER__DYEWORKS_DOOR_LOCKED__010__M__1": "Başka... bir yol buluruz...",
"VO__AMICIA__CH06__CHATTER__ENCOUNTER_CANYON_INTRO__030__M__1": "Onlar... kasap.",
"VO__AMICIA__CH06__CHATTER__ENCOUNTER_CANYON_INTRO__050__M__1": "Gerekenden fazlasını...",
"VO__AMICIA__CH06__CHATTER__ENCOUNTER_KILL_1__010__M__1": "Temiz...",
"VO__AMICIA__CH06__CHATTER__ENCOUNTER_KILL_1__030__M__1": "Merak... etme...",
"VO__AMICIA__CH06__CHATTER__ENCOUNTER_KILL_2__010__M__1": "Tamam...",
"VO__AMICIA__CH06__CHATTER__ENCOUNTER_KILL_2__030__M__1": "Bir tane eksildi...",
"VO__AMICIA__CH06__CHATTER__ENCOUNTER_KILL_3__010__M__1": "Çekil yolumuzdan!",
"VO__AMICIA__CH06__CHATTER__ENCOUNTER_KILL_4__010__M__1": "İyiyim...",
"VO__AMICIA__CH06__CHATTER__ENTRANCE_QUARRY__020__M__1": "Bilmiyorum... Elimi sıkı tut.",
"VO__AMICIA__CH06__CHATTER__ENTRANCE_QUARRY__040__M__1": "Evet... Ben... Kendimi kaybettim.",
"VO__AMICIA__CH06__CHATTER__ENTRANCE_QUARRY__060__M__1": "Utandım... Şimdi, odaklan.",
"VO__AMICIA__CH06__CHATTER__EXHAUSTED_IDLE__010__M__1": "Yapabiliriz... Başarabiliriz...",
"VO__AMICIA__CH06__CHATTER__FAKE_DOOR_DYEWORKS__010__M__1": "O yoldan değil...",
"VO__AMICIA__CH06__CHATTER__FAKE_DOOR_RATS__010__M__1": "Kımıldamıyor...",
"VO__AMICIA__CH06__CHATTER__FAKE_INTERACT_BIGDOOR__010__M__1": "Yerinden oynamıyor...",
"VO__AMICIA__CH06__CHATTER__FEATHER_COLLECTED__010__M__1": "Ah!... Bu bana hatırlattı... Lucas'la dışarıdayken güzel çiçekler bulmuştum.",
"VO__AMICIA__CH06__CHATTER__FEATHER_COLLECTED__020__M__1": "İster misin?",
"VO__AMICIA__CH06__CHATTER__FEATHER_COLLECTED__040__M__1": "Ah... Peki...",
"VO__AMICIA__CH06__CHATTER__FIELD_ANXIOUS__020__M__1": "Hugo...",
"VO__AMICIA__CH06__CHATTER__FIELD_ANXIOUS__040__M__1": "İyi olacaklar!",
"VO__AMICIA__CH06__CHATTER__FIELD_ANXIOUS__060__M__1": "Evet! Ha...",
"VO__AMICIA__CH06__CHATTER__FIELD_FALL__020__M__1": "Ah!",
"VO__AMICIA__CH06__CHATTER__FIELD_FALL__040__M__1": "Üzgünüm, ama öyle...! Canını acıttın mı?",
"VO__AMICIA__CH06__CHATTER__FIELD_FALL_AWAY__020__M__1": "Geliyorum!",
"VO__AMICIA__CH06__CHATTER__FIELD_FLOWERS__010__M__1": "Vay... Şu çiçeklere bak!",
"VO__AMICIA__CH06__CHATTER__FIELD_FLOWERS__030__M__1": "Hadi, çiçekleri seversin!",
"VO__AMICIA__CH06__CHATTER__FIELD_RACE__010__M__1": "Hey!",
"VO__AMICIA__CH06__CHATTER__FIELD_RACE__030__M__1": "Ay... Hayır, yine kanamaya başlama...",
"VO__AMICIA__CH06__CHATTER__FIELD_RACE__050__M__1": "Ha... Geçer...",
"VO__AMICIA__CH06__CHATTER__FIELD_TREE__010__M__1": "Dur... Şu ağacı görüyor musun?",
"VO__AMICIA__CH06__CHATTER__FIELD_TREE__020__M__1": "Ona senden daha hızlı ulaşabileceğime eminim.",
"VO__AMICIA__CH06__CHATTER__FIELD_TREE__040__M__1": "Çünkü sen küçük bir korkaksın.",
"VO__AMICIA__CH06__CHATTER__FIELD_TREE__055__M__1": "O zaman göster bana! Üç...",
"VO__AMICIA__CH06__CHATTER__FIELD_TREE__070__M__1": "İki...",
"VO__AMICIA__CH06__CHATTER__FIELD_TREE__080__M__1": "Bir...",
"VO__AMICIA__CH06__CHATTER__FIRST_HELP_RING_CAPTAIN__010__M__1": "Zırhını parçalamanın bir yolu olmalı!",
"VO__AMICIA__CH06__CHATTER__FOOD__040__M__1": "Ne şaşırtıcı... Hadi!",
"VO__AMICIA__CH06__CHATTER__FROGS__035__M__1": "Merhaba kurbağacıklar!",
"VO__AMICIA__CH06__CHATTER__FROGS__050__M__1": "Güzel bacakları var!",
"VO__AMICIA__CH06__CHATTER__FROGS__070__M__1": "Hm... Hayır...",
"VO__AMICIA__CH06__CHATTER__GORGE_ENTRY__018__M__1": "Evet... Hareket etmeye... devam etmeliyiz...",
"VO__AMICIA__CH06__CHATTER__GORGE_ENTRY__030__M__1": "Bir taş ocağına... benziyor...",
"VO__AMICIA__CH06__CHATTER__GORGE_ENTRY__050__M__1": "Başka bir yol var mı... bilmiyorum...",
"VO__AMICIA__CH06__CHATTER__GORGE_ENTRY__070__M__1": "İçeri ilerleyelim. Açıkta... kalmamalıyız.",
"VO__AMICIA__CH06__CHATTER__HELLO_RANDOM__020__M__1": "Ah, merhaba!",
"VO__AMICIA__CH06__CHATTER__HELLO_TREE__020__M__1": "Merhaba...",
"VO__AMICIA__CH06__CHATTER__HIDE_UNDER_CART__010__M__1": "Hadi...",
"VO__AMICIA__CH06__CHATTER__HIDE_UNDER_CART__030__M__1": "Biliyorum, şşş...",
"VO__AMICIA__CH06__CHATTER__HOPEFUL_IDLE__010__M__1": "Ellerinde... o kadar çok kan var ki... alçaklar...",
"VO__AMICIA__CH06__CHATTER__IDLE_PAIN_1__010__M__1": "Ha... Sakın... Sakın şimdi yıkılma...",
"VO__AMICIA__CH06__CHATTER__IDLE_PAIN_2__010__M__1": "Hı... Lütfen... bana biraz daha zaman ver...",
"VO__AMICIA__CH06__CHATTER__IDLE_PAIN_3__010__M__1": "Sakın... Gözünü ondan ayırma...",
"VO__AMICIA__CH06__CHATTER__IDLE_QUARRY_CHEST__020__M__1": "Biliyorum... ama şimdi duramayız...",
"VO__AMICIA__CH06__CHATTER__IDLE_QUARRY_CHEST__030__M__1": "Beni merak etme...",
"VO__AMICIA__CH06__CHATTER__IDLE_QUARRY_LEFT__010__M__1": "Başaracağız... Artık denizin nerede olduğunu biliyoruz...",
"VO__AMICIA__CH06__CHATTER__IDLE_QUARRY_LEFT__030__M__1": "Evet... Üzerinde... çalışıyorum...",
"VO__AMICIA__CH06__CHATTER__IDLE_QUARRY_UP__020__M__1": "Evet...",
"VO__AMICIA__CH06__CHATTER__IDLE_QUARRY_UP__040__M__1": "İyi görünüyorlardı... ama değillerdi, inan bana.",
"VO__AMICIA__CH06__CHATTER__INTERACT_FEATHER__010__M__1": "Ne güzel bir tüy!",
"VO__AMICIA__CH06__CHATTER__INTERACT_FEATHER__030__M__1": "Ağaçtaki şu yuvadan düşmüş olmalı, gördün mü?",
"VO__AMICIA__CH06__CHATTER__INTERACT_FEATHER__050__M__1": "Başka yuvalar ararız. Eminim daha çok tüy buluruz!",
"VO__AMICIA__CH06__CHATTER__INTERACT_FEATHER__065__M__1": "Bu arada, sana bir...",
"VO__AMICIA__CH06__CHATTER__INTERACT_FEATHER__070__M__1": "...kuş yapacağım!",
"VO__AMICIA__CH06__CHATTER__LAST_METERS__020__M__1": "Ben... başarabilirim...",
"VO__AMICIA__CH06__CHATTER__LAST_METERS__030__M__1": "Yapabilirim... İhtiyacım var...",
"VO__AMICIA__CH06__CHATTER__LAST_METERS__040__M__1": "Bana... gücü ver...",
"VO__AMICIA__CH06__CHATTER__LAST_METERS__060__M__1": "Ben... başaracağım...",
"VO__AMICIA__CH06__CHATTER__LASTPART_RATMOVE__030__M__1": "Buna son vermelisin Hugo! Çok ileri gidiyor!",
"VO__AMICIA__CH06__CHATTER__LASTPART_RATMOVE__060__M__1": "DUR, HUGO! KONTROLÜ KAYBEDİYORSUN!",
"VO__AMICIA__CH06__CHATTER__LOCK_SECRET__020__M__1": "İçeride işe yarar bir şey olmalı.",
"VO__AMICIA__CH06__CHATTER__MASS_APPROACH__005__M__1": "İşte ayinimiz.",
"VO__AMICIA__CH06__CHATTER__MASS_APPROACH__040__M__1": "Burada bekleriz, teşekkürler.",
"VO__AMICIA__CH06__CHATTER__MASS_FROM_AFAR__020__M__1": "İlahiler... Bir ayine benziyor...",
"VO__AMICIA__CH06__CHATTER__MASS_FROM_AFAR__040__M__1": "Göreceğiz...",
"VO__AMICIA__CH06__CHATTER__MASS_OVER__020__M__1": "Teşekkürler.",
"VO__AMICIA__CH06__CHATTER__MASS_OVER__040__M__1": "Âmin \"teşekkürler\" demek değil, biliyorsun değil mi?",
"VO__AMICIA__CH06__CHATTER__MASS_OVER__060__M__1": "Onunla konuşalım...",
"VO__AMICIA__CH06__CHATTER__MORE_MEN_CAVE__010__M__1": "Buradan nasıl çıkacağız?!",
"VO__AMICIA__CH06__CHATTER__MORE_MEN_TALKING__040__M__1": "Cehenneme git...",
"VO__AMICIA__CH06__CHATTER__NEW_SOLDIERS_DYEFACTORY__040__M__1": "Askerler!... Hayır... Yapamam...",
"VO__AMICIA__CH06__CHATTER__NEW_SOLDIERS_DYEFACTORY__060__M__1": "Nasıl?...",
"VO__AMICIA__CH06__CHATTER__OPENED_DOOR__020__M__1": "Aferin.",
"VO__AMICIA__CH06__CHATTER__OPENING_DOOR_FALL__010__M__1": "Biz... ah... hayır...",
"VO__AMICIA__CH06__CHATTER__OPENING_DOOR_FALL__020__M__1": "Ha... çok acıyor... Başaracağımdan emin değilim...",
"VO__AMICIA__CH06__CHATTER__OPENING_DOOR_FALL__040__M__1": "Evet... Buradan... çıkmalıyız...",
"VO__AMICIA__CH06__CHATTER__OPENING_DOOR_SMELL__014__M__1": "Cesetler...",
"VO__AMICIA__CH06__CHATTER__PERREUX_DISTRACT_OK__010__M__1": "Gidelim.",
"VO__AMICIA__CH06__CHATTER__PERREUX_GOODBYE__020__M__1": "Bunu unutmayacağız.",
"VO__AMICIA__CH06__CHATTER__PERREUX_HELP__020__M__1": "Deniyorum...",
"VO__AMICIA__CH06__CHATTER__PILGRIM_WELCOME__020__M__1": "Merhaba! Evet, yolumuzu bulmaya çalışıyoruz...",
"VO__AMICIA__CH06__CHATTER__PILGRIM_WELCOME__040__M__1": "Ah, Roma'ya gidiyorsunuz!",
"VO__AMICIA__CH06__CHATTER__PILGRIM_WELCOME__075__M__1": "Bir adaya... Onun hakkında pek bir şey bilmiyoruz...",
"VO__AMICIA__CH06__CHATTER__PILGRIM_WELCOME__110__M__1": "Ah, evet... teşekkürler!",
"VO__AMICIA__CH06__CHATTER__POST_RATMOVE__030__M__1": "Ne oldu?!... Fareler... Fare sesi mi... duyuyorum?!",
"VO__AMICIA__CH06__CHATTER__POST_RATMOVE__050__M__1": "Ne?...",
"VO__AMICIA__CH06__CHATTER__POST_SWING__010__M__1": "Şey, teşekkürler! Çok... rahatlatıcıydı...",
"VO__AMICIA__CH06__CHATTER__POST_SWING__030__M__1": "Önce ada. Sonra yuva.",
"VO__AMICIA__CH06__CHATTER__PRE_RAT_SENSE__020__M__1": "Hiçbir şey duymuyorum... Nereden biliyorsun?",
"VO__AMICIA__CH06__CHATTER__PRE_RAT_SENSE__040__M__1": "Bundan emin misin?",
"VO__AMICIA__CH06__CHATTER__PRE_RAT_SENSE__060__M__1": "Peki... Dikkatli ol...",
"VO__AMICIA__CH06__CHATTER__PROBLEM__020__M__1": "Sorun...",
"VO__AMICIA__CH06__CHATTER__PROMISE_IDLE__020__M__1": "Evet... Merak etme...",
"VO__AMICIA__CH06__CHATTER__QUARRY_ALL_DEAD__020__M__1": "Şimdilik güvendeyiz...",
"VO__AMICIA__CH06__CHATTER__QUARRY_DOOR__010__M__1": "Bir kapı, yukarıda...",
"VO__AMICIA__CH06__CHATTER__QUARRY_DOOR_INTERACT__020__M__1": "İyiyim... Fareler, Hugo? Bir tehlike var mı? Çıkıyorlar mı?",
"VO__AMICIA__CH06__CHATTER__QUARRY_DOOR_INTERACT__040__M__1": "Onlara odaklanmaya devam et.",
"VO__AMICIA__CH06__CHATTER__QUARRY_FIFTH_KILL__010__M__1": "Çekil yoldan...",
"VO__AMICIA__CH06__CHATTER__QUARRY_FIRST_KILL__010__M__1": "Ha... Devam edelim...",
"VO__AMICIA__CH06__CHATTER__QUARRY_RATSENSE_REMINDER__010__M__1": "Çok fazla... saklı köşe...",
"VO__AMICIA__CH06__CHATTER__QUARRY_STAIRS_RATSENSE__020__M__1": "İyi gidiyorsun...",
"VO__AMICIA__CH06__CHATTER__QUARRY_THIRD_KILL__010__M__1": "Daha hızlı hareket etmeliyiz...",
"VO__AMICIA__CH06__CHATTER__RACE_DEBRIEF__020__M__1": "Şey... öyle...",
"VO__AMICIA__CH06__CHATTER__RACE_DEBRIEF__040__M__1": "Hayır... En çok canımı yakan... artık bir korkak olmam...",
"VO__AMICIA__CH06__CHATTER__RACE_DEBRIEF__060__M__1": "Çok naziksin.",
"VO__AMICIA__CH06__CHATTER__RACE_DEBRIEF__080__M__1": "Ah hayır... bir dahaki sefere seni ezerim...",
"VO__AMICIA__CH06__CHATTER__RAT_MOVE_ENDS__020__M__1": "Evet... Ama dikkatli ol...",
"VO__AMICIA__CH06__CHATTER__RAT_MOVE_ENDS__040__M__1": "Sadece... benimle aynı hataları yapma... Hepsi bu...",
"VO__AMICIA__CH06__CHATTER__RAT_MOVE_KILLS_2__020__M__1": "Sakin ol... Odağını koru...",
"VO__AMICIA__CH06__CHATTER__RAT_MOVE_KILLS_3__020__M__1": "Kendini kaptırma... Onların kontrolünü elinde tutmalısın...",
"VO__AMICIA__CH06__CHATTER__RAT_MOVE_OVER__030__M__1": "O neydi?! Gerçekten sen mi...?",
"VO__AMICIA__CH06__CHATTER__RAT_MOVE_OVER__043__M__1": "Pekâlâ... Şimdilik gidelim yeter...",
"VO__AMICIA__CH06__CHATTER__RAT_MOVE_OVER__050__M__1": "Bu... ha... dur... dur... Ha...",
"VO__AMICIA__CH06__CHATTER__RAT_MOVE_OVER_ALT__020__M__1": "Onları gerçekten... kontrol mü ettin?!",
"VO__AMICIA__CH06__CHATTER__RAT_MOVE_OVER_ALT__040__M__1": "İhtiyacım var...",
"VO__AMICIA__CH06__CHATTER__RAT_MOVE_OVER_ALT__050__M__1": "Sakin ol...",
"VO__AMICIA__CH06__CHATTER__RAT_MOVE_START__010__M__1": "Devam et... Onları kullan...",
"VO__AMICIA__CH06__CHATTER__RAT_SENSE_TUTO_OK__010__M__1": "Dur... Nasıl...",
"VO__AMICIA__CH06__CHATTER__RAT_SENSE_TUTO_OK__030__M__1": "Peki neredeler?",
"VO__AMICIA__CH06__CHATTER__RAT_SENSE_TUTO_OK__050__M__1": "Anladım. Gidelim, dikkatli.",
"VO__AMICIA__CH06__CHATTER__RATMOVE_AMICIA__020__M__1": "Dur! Neler oluyor?",
"VO__AMICIA__CH06__CHATTER__RATMOVE_AMICIA__040__M__1": "Hugo... Neler oluyor?",
"VO__AMICIA__CH06__CHATTER__RATMOVE_AMICIA__050__M__1": "Cevap ver bana!",
"VO__AMICIA__CH06__CHATTER__RATMOVE_AMICIA__060__M__1": "Bunu sen mi yapıyorsun?",
"VO__AMICIA__CH06__CHATTER__RATS_ATTACK_REMINDER__020__M__1": "Evet, doğru...",
"VO__AMICIA__CH06__CHATTER__RATS_BASINS_REACTION__015__M__1": "Belki onları... çıkarabilirsin...",
"VO__AMICIA__CH06__CHATTER__RATS_CALLING_IDLE__020__M__1": "Bu yüzden... tedbirli olmalısın...",
"VO__AMICIA__CH06__CHATTER__RATS_FOLLOWING__020__M__1": "Onları şimdilik orada bırak...",
"VO__AMICIA__CH06__CHATTER__RATS_INSIDE_HOUSE__010__M__1": "Vay... Geri çekil!",
"VO__AMICIA__CH06__CHATTER__RATS_INSIDE_HOUSE__020__M__1": "İçeride bir sürü var... İşe yarayabilirler...",
"VO__AMICIA__CH06__CHATTER__RATWAVE_ESCAPE__010__M__1": "Ha... Aman Tanrım... Tanrım...",
"VO__AMICIA__CH06__CHATTER__RATWAVE_ESCAPE__030__M__1": "Buradan çıkmalıyız!",
"VO__AMICIA__CH06__CHATTER__RATWAVE_ESCAPE__060__M__1": "Bizi... buradan çıkaracağım...",
"VO__AMICIA__CH06__CHATTER__REACHING_BUILDING__010__M__1": "Geldik, ama... Üzgünüm, iyi değilim, Hugo...",
"VO__AMICIA__CH06__CHATTER__REACHING_GATE__010__M__1": "Geldik... Nihayet...",
"VO__AMICIA__CH06__CHATTER__REINFORCEMENTS__040__M__1": "İyi... olacağız...",
"VO__AMICIA__CH06__CHATTER__REINFORCEMENTS_KILL_1__010__M__1": "Gerekirse hepinizi öldürürüm!",
"VO__AMICIA__CH06__CHATTER__REINFORCEMENTS_REACT__020__M__1": "Yapabilirim... Bunu yapabilirim...",
"VO__AMICIA__CH06__CHATTER__SALPETER_REMINDER_1__010__M__1": "Vakit kazanmalıyım... Onu sersemlet...",
"VO__AMICIA__CH06__CHATTER__SALPETER_REMINDER_2__020__M__1": "Belki... bir yolu var, evet...",
"VO__AMICIA__CH06__CHATTER__SECOND_HELP_RING_CAPTAIN__010__M__1": "Sırtındaki halka! Onu vurabilirim!",
"VO__AMICIA__CH06__CHATTER__SOUVENIR_BANDAGE__010__M__1": "Pekâlâ...",
"VO__AMICIA__CH06__CHATTER__SOUVENIR_BANDAGE__030__M__1": "Umarım...",
"VO__AMICIA__CH06__CHATTER__SOUVENIR_BANDAGE__050__M__1": "Ben—Ha... şu...",
"VO__AMICIA__CH06__CHATTER__SOUVENIR_BANDAGE__100__M__1": "Teşekkürler...",
"VO__AMICIA__CH06__CHATTER__SOUVENIR_BANDAGE_DENIED__010__M__1": "Hareket etmeye devam etmeliyiz, Hugo...",
"VO__AMICIA__CH06__CHATTER__SOUVENIR_SWING__170__M__1": "Etrafında ağaçlar olan bir tane buluruz.",
"VO__AMICIA__CH06__CHATTER__SOUVENIR_SWING__190__M__1": "Elbette!",
"VO__AMICIA__CH06__CHATTER__SOUVENIR_SWING_DENIED__010__M__1": "Üzgünüm Hugo, ama devam etsek iyi olur.",
"VO__AMICIA__CH06__CHATTER__SPOT_DYE_END__010__M__1": "Neredeyse... vardık...",
"VO__AMICIA__CH06__CHATTER__STANDING_UP__030__M__1": "Ah... Başım...",
"VO__AMICIA__CH06__CHATTER__STANDING_UP__050__M__1": "Evet... Evet...",
"VO__AMICIA__CH06__CHATTER__STORYTELLER_REACTION__020__M__1": "Hm, evet, fırsat varken şu Perreux'yü yakalayalım...",
"VO__AMICIA__CH06__CHATTER__STORYTELLER_SPEECH__050__M__1": "Şşş... Bunu söyleyemezsin...",
"VO__AMICIA__CH06__CHATTER__SWING__020__M__1": "Ah... Evdekimiz hep bozuktu...",
"VO__AMICIA__CH06__CHATTER__SWING__040__M__1": "Gerçekten mi? Kendin gitmek istemiyor musun?",
"VO__AMICIA__CH06__CHATTER__SWING_STOP__010__M__1": "Hey... Sanırım yeterince uçtum. Geri dönelim mi?",
"VO__AMICIA__CH06__CHATTER__SWINGING__030__M__1": "Kendini incitme!",
"VO__AMICIA__CH06__CHATTER__THIRDPART_RATMOVE__040__M__1": "Sakin ol! Odaklan yoksa... kontrolü kaybedersin!",
"VO__AMICIA__CH06__CHATTER__THROUGH_CAMP__020__M__1": "Çünkü gelecek yıl jübile, çok özel bir yıl... Hadi şu Perreux'yü bulmaya çalışalım.",
"VO__AMICIA__CH06__CHATTER__TO_CAMP__010__M__1": "O da ne?",
"VO__AMICIA__CH06__CHATTER__TO_CAMP__030__M__1": "Hayır, bir şehirden çok uzaktayız... ama ilahiler oradan geliyor...",
"VO__AMICIA__CH06__CHATTER__TO_CAMP_DOWN__020__M__1": "Evet, gidip soracağız.",
"VO__AMICIA__CH06__CHATTER__TRAP_DOOR__020__M__1": "Evet... Çıkış yolumuz bu...",
"VO__AMICIA__CH06__CHATTER__TRAP_DOOR_FALL__010__M__1": "Ah... Şimdi olmaz...",
"VO__AMICIA__CH06__CHATTER__TRAP_DOOR_FALL__030__M__1": "Bırak da... nefes... alayım...",
"VO__AMICIA__CH06__CHATTER__TRAP_DOOR_FALL__060__M__1": "Hayır... Bizi bulurlar...",
"VO__AMICIA__CH06__CHATTER__WAITING_FOR_RATMOVE__010__M__1": "Ne yapıyorsun?...",
"VO__AMICIA__CH06__CHATTER__WAKING_UP__023__M__1": "Ha... Hugo...",
"VO__AMICIA__CH06__CHATTER__WEAKNESS__010__M__1": "Elimden geleni yapıyorum... biliyorsun...",
"VO__AMICIA__CH06__CHATTER__WEAKNESS__030__M__1": "Evet, yakında...",
"VO__AMICIA__CH06__CHATTER__WOOD_START__020__M__1": "Tekneyle. Nerede olduğunu öğrenince.",
"VO__AMICIA__CH06__CHATTER__WOOD_START__040__M__1": "Hoşuna gitmeyecek ama... Merak etme.",
"VO__AMICIA__CH06__CHATTER__WOOD_START__070__M__1": "Hayır. Güvende olacaklar.",
"VO__AMICIA__CH06__CHATTER__WOOD_START__090__M__1": "Kaçar ya da aralarına karışırlar, Hugo.",
"VO__AMICIA__CH06__CHATTER__WOODS_FALL__020__M__1": "Çek... ellerini... üstümden!...",
"VO__AMICIA__CH06__CHATTER__WOODS_FALL__030__M__1": "Ah... Hayır! Hugo!",
"VO__AMICIA__CH06__CHATTER__WOODS_WRONGWAY__020__M__1": "Hayır... O paralı askerlerle yine karşılaşma riskini alamayız.",
"VO__AMICIA__CH06__CHATTER__WORRIED_IDLE__020__M__1": "Öyleyim...",
"VO__AMICIA__CH06__CHATTER__WOUND_IDLE__020__M__1": "Lütfen... sadece devam et...",
"VO__AMICIA__CH06__RTC__230_FREEDOM__035__M__1": "Ah...",
"VO__AMICIA__CH06__RTC__230_FREEDOM__040__M__1": "İyiler, Hugo... Tanıdığım en akıllı insanlar.",
"VO__AMICIA__CH06__RTC__230_FREEDOM__060__M__1": "Evet... Sanırım iltihap kapmadan onu sarmalıyız.",
"VO__AMICIA__CH06__RTC__230_FREEDOM__070__M__1": "Evet!",
"VO__AMICIA__CH06__RTC__230_FREEDOM__080__M__1": "Bu senin adan mı?",
"VO__AMICIA__CH06__RTC__230_FREEDOM__100__M__1": "Biliyor musun, sanırım onu gördüm... Vaudin'in laboratuvarındaki bir tabloda.",
"VO__AMICIA__CH06__RTC__230_FREEDOM__130__M__1": "Nazik ol, lütfen.",
"VO__AMICIA__CH06__RTC__230_FREEDOM__160__M__1": "Şimdiden mi?...",
"VO__AMICIA__CH06__RTC__230_FREEDOM__170__M__1": "Güzel! Teşekkürler! Bunda iyisin...",
"VO__AMICIA__CH06__RTC__230_FREEDOM__190__M__1": "Bunda iyisin! Şimdi hadi bayım! Adanı bulmamız gerek!",
"VO__AMICIA__CH06__RTC__240_FLAGELLANT__060__M__1": "Evet... Şey, aslında biraz yolumuzu kaybettik.",
"VO__AMICIA__CH06__RTC__240_FLAGELLANT__080__M__1": "Muhtemelen iki büyük dağı olan bir ada. Onu bulmamıza yardım edebileceğiniz söylendi?",
"VO__AMICIA__CH06__RTC__240_FLAGELLANT__100__M__1": "Evet, teşekkürler, bu harika olur!",
"VO__AMICIA__CH06__RTC__240_FLAGELLANT__120__M__1": "Eyvah. Bunu tanıyorum...",
"VO__AMICIA__CH06__RTC__240_FLAGELLANT__180__M__1": "Gitmeliyiz. Hemen!",
"VO__AMICIA__CH06__RTC__240_FLAGELLANT__300__M__1": "Teşekkürler!",
"VO__AMICIA__CH06__RTC__249_CAPTAIN_DEATH__020__M__1": "İyiyim. İyiyim. Gidelim.",
"VO__AMICIA__CH06__RTC__250_DEAD_END__050__M__1": "Yapamam... Onu kendin hâlletmelisin...",
"VO__AMICIA__CH06__RTC__250_DEAD_END__070__M__1": "Yap, çabuk!",
"VO__AMICIA__CH06__RTC__260_WAVE__010__M__1": "Hugo? Hugo! Neyin var? Neyin var?!",
"VO__AMICIA__CH06__RTC__260_WAVE__020__M__1": "Eyvah! Hugo!",
"VO__AMICIA__CH06__RTC__260_WAVE__040__M__1": "Hayır!",
"VO__AMICIA__CH06__RTC__270_COMEBACK__011__M__1": "... Yapamam... Yapamam...",
"VO__AMICIA__CH06__RTC__270_COMEBACK__025__M__1": "... Yapamam...",
"VO__HUGO__CH06__CHATTER__1ST_GALLERIES_IDLE__010__M__1": "Başın nasıl?",
"VO__HUGO__CH06__CHATTER__2ND_DOOR__020__M__1": "Evet! Seni sıcak tutar!",
"VO__HUGO__CH06__CHATTER__2ND_ENCOUNTER_ENTRANCE__020__M__1": "Başaracağız! Lütfen ölme...",
"VO__HUGO__CH06__CHATTER__2ND_ENCOUNTER_ENTRANCE__070__M__1": "Sana göz kulak olacağım.",
"VO__HUGO__CH06__CHATTER__2ND_GALLERIES_IDLE__020__M__1": "Belki geri dönmeliyiz...",
"VO__HUGO__CH06__CHATTER__ABOUT_DEATH_IDLE__020__M__1": "Hayır! Sana bir doktor buluruz! Her şey yoluna girecek!",
"VO__HUGO__CH06__CHATTER__AMICIA_COLLAPSE__010__M__1": "Hayır... Hayır!... Ölme!",
"VO__HUGO__CH06__CHATTER__AMICIA_COLLAPSE__030__M__1": "Hayır! Burada uyuyamazsın! Lütfen! Uyan!",
"VO__HUGO__CH06__CHATTER__AMICIA_COLLAPSE__040__M__1": "Amicia! Uyan!",
"VO__HUGO__CH06__CHATTER__AMICIA_COLLAPSE_ALT__045__M__1": "Uyan!",
"VO__HUGO__CH06__CHATTER__BEGINNING_RATMOVE__010__M__1": "Hayır! Rahat bırakın onu!",
"VO__HUGO__CH06__CHATTER__BEGINNING_RATMOVE__020__M__1": "Ona yeterince zarar verdiniz!",
"VO__HUGO__CH06__CHATTER__BEGINNING_RATMOVE__050__M__1": "Durun! Yoksa hepinizi öldürürüm! Daha önce de yaptım!",
"VO__HUGO__CH06__CHATTER__BEGINNING_RATMOVE__110__M__1": "Ben bir canavar değilim!",
"VO__HUGO__CH06__CHATTER__BLEEDING_AGAIN__020__M__1": "Yine kanıyorsun!",
"VO__HUGO__CH06__CHATTER__BUILDING_IDLE__010__M__1": "Neredeyse vardık, Amicia...",
"VO__HUGO__CH06__CHATTER__CAPTAIN_FIGHT__030__M__1": "Eyvah...",
"VO__HUGO__CH06__CHATTER__CAPTAIN_FIGHT__070__M__1": "Amicia... yaran!",
"VO__HUGO__CH06__CHATTER__CAPTAIN_FIRST_WEAKNESS__010__M__1": "Amicia! Sırtına bak!",
"VO__HUGO__CH06__CHATTER__CAPTAIN_ORDER_FOREST__020__M__1": "Eyvah...",
"VO__HUGO__CH06__CHATTER__CAPTAIN_RING__020__M__1": "Onu vurdun!",
"VO__HUGO__CH06__CHATTER__CAPTAIN_SECOND_RESISTANCE__010__M__1": "İşe yaramıyor, Amicia!",
"VO__HUGO__CH06__CHATTER__CARNAGE__020__M__1": "Hâlâ... kafamda onları duyuyorum... çınlıyor...",
"VO__HUGO__CH06__CHATTER__CARNAGE__040__M__1": "Eskisi gibi değil... Bu sefer onların kafasının içindeydim!",
"VO__HUGO__CH06__CHATTER__CARNAGE__080__M__1": "Olacağım...",
"VO__HUGO__CH06__CHATTER__CARNAGE_PART_2__010__M__1": "Şu diğer insanlar... Fareler onları yedi...",
"VO__HUGO__CH06__CHATTER__CARNAGE_PART_2__040__M__1": "Beni takip ediyorlar. Benim suçum.",
"VO__HUGO__CH06__CHATTER__CAUTIOUS_IDLE__010__M__1": "Kendini çok kötü hissedersen söyle...",
"VO__HUGO__CH06__CHATTER__CROSSING_PEN__020__M__1": "Umarım askerler onlara zarar vermez...",
"VO__HUGO__CH06__CHATTER__DEAD_WORKERS_IDLE__010__M__1": "İşçilerin hepsi ölmüş...",
"VO__HUGO__CH06__CHATTER__DEAD_WORKERS_IDLE__030__M__1": "Biliyorum ama... hiç bitmiyor...",
"VO__HUGO__CH06__CHATTER__DISCOVER_CANYON__020__M__1": "Bu bir kilise mi?",
"VO__HUGO__CH06__CHATTER__DISTRACT_WAIT__020__M__1": "Şimdi gidiyor muyuz, Amicia?",
"VO__HUGO__CH06__CHATTER__ENCOUNTER_CANYON_INTRO__020__M__1": "Vazgeçmeyecekler...",
"VO__HUGO__CH06__CHATTER__ENCOUNTER_CANYON_INTRO__040__M__1": "Kızıl şehirde çok kişi öldürdün mü?",
"VO__HUGO__CH06__CHATTER__ENCOUNTER_KILL_1__020__M__1": "Dikkatli ol... Çok yorgunsun...",
"VO__HUGO__CH06__CHATTER__ENCOUNTER_KILL_2__020__M__1": "Çok fazlalar...",
"VO__HUGO__CH06__CHATTER__ENCOUNTER_KILL_3__020__M__1": "Lütfen başına dikkat et...",
"VO__HUGO__CH06__CHATTER__ENTRANCE_QUARRY__010__M__1": "Neredeler?",
"VO__HUGO__CH06__CHATTER__ENTRANCE_QUARRY__030__M__1": "Gerçekten asker mi öldürdün?",
"VO__HUGO__CH06__CHATTER__ENTRANCE_QUARRY__050__M__1": "Bana söylemedin...",
"VO__HUGO__CH06__CHATTER__EXHAUSTED_IDLE__020__M__1": "Evet... Sonra dinlenirsin...",
"VO__HUGO__CH06__CHATTER__FAKE_DOOR_RATS__020__M__1": "Belki başka bir giriş vardır?",
"VO__HUGO__CH06__CHATTER__FAKE_INTERACT_BIGDOOR__020__M__1": "Başka bir kapı buluruz!",
"VO__HUGO__CH06__CHATTER__FEATHER_COLLECTED__030__M__1": "Hmmm, sanırım artık tüyleri tercih ediyorum.",
"VO__HUGO__CH06__CHATTER__FIELD_ANXIOUS__010__M__1": "Ama... ya tekneleri batarsa?",
"VO__HUGO__CH06__CHATTER__FIELD_ANXIOUS__030__M__1": "Yüzmeyi biliyorlar mı?",
"VO__HUGO__CH06__CHATTER__FIELD_ANXIOUS__050__M__1": "Söz mü?",
"VO__HUGO__CH06__CHATTER__FIELD_FALL__030__M__1": "Komik değil!",
"VO__HUGO__CH06__CHATTER__FIELD_FALL__050__M__1": "Hayır...",
"VO__HUGO__CH06__CHATTER__FIELD_FALL__060__M__1": "Ah!",
"VO__HUGO__CH06__CHATTER__FIELD_FALL__070__M__1": "Bak!",
"VO__HUGO__CH06__CHATTER__FIELD_FALL_AWAY__010__M__1": "Amicia! Bak ne buldum!",
"VO__HUGO__CH06__CHATTER__FIELD_FLOWERS__020__M__1": "Evet...",
"VO__HUGO__CH06__CHATTER__FIELD_RACE__020__M__1": "Sen... korkak... olacaksın!",
"VO__HUGO__CH06__CHATTER__FIELD_RACE__040__M__1": "Kazanıyorum!",
"VO__HUGO__CH06__CHATTER__FIELD_TREE__030__M__1": "Şimdi mi? Neden?",
"VO__HUGO__CH06__CHATTER__FIELD_TREE__045__M__1": "Değilim! Sensin!",
"VO__HUGO__CH06__CHATTER__FOOD__010__M__1": "Yahni gibi kokuyor...",
"VO__HUGO__CH06__CHATTER__FOOD__030__M__1": "Şimdi acıktım...",
"VO__HUGO__CH06__CHATTER__FOURTHPART_RATMOVE__020__M__1": "Gelin! Sizi yemeye devam edecekler!",
"VO__HUGO__CH06__CHATTER__FOURTHPART_RATMOVE__040__M__1": "Sizi... yiyeceğim!",
"VO__HUGO__CH06__CHATTER__FROGS__032__M__1": "Kurbağalar! Bak, tam şurada!",
"VO__HUGO__CH06__CHATTER__FROGS__040__M__1": "Hadi! Zıpla! Zıpla!",
"VO__HUGO__CH06__CHATTER__FROGS__060__M__1": "Keşke benim de öyle olsaydı!",
"VO__HUGO__CH06__CHATTER__GOOSE_TALK__010__M__1": "Selam, kaz!",
"VO__HUGO__CH06__CHATTER__GORGE_ENTRY__010__M__1": "Amicia...",
"VO__HUGO__CH06__CHATTER__GORGE_ENTRY__015__M__1": "Gitmeliyiz...",
"VO__HUGO__CH06__CHATTER__GORGE_ENTRY__020__M__1": "Neredeyiz?",
"VO__HUGO__CH06__CHATTER__GORGE_ENTRY__040__M__1": "Oraya mı giriyoruz? Karanlık!",
"VO__HUGO__CH06__CHATTER__HELLO_RANDOM__030__M__1": "Merhaba...",
"VO__HUGO__CH06__CHATTER__HELLO_TREE__030__M__1": "Selam!",
"VO__HUGO__CH06__CHATTER__HIDE_UNDER_CART__020__M__1": "Amicia...",
"VO__HUGO__CH06__CHATTER__HOPEFUL_IDLE__020__M__1": "Yakında... Yakında buradan uzaklaşacağız...",
"VO__HUGO__CH06__CHATTER__IDLE_PAIN_1__020__M__1": "Hayır... nefes al!",
"VO__HUGO__CH06__CHATTER__IDLE_PAIN_2__020__M__1": "Dayan! Lütfen!",
"VO__HUGO__CH06__CHATTER__IDLE_QUARRY_CHEST__010__M__1": "Amicia... Başın...",
"VO__HUGO__CH06__CHATTER__IDLE_QUARRY_LEFT__020__M__1": "Önemi yok. Güvende olmanı istiyorum!",
"VO__HUGO__CH06__CHATTER__IDLE_QUARRY_UP__010__M__1": "Bunlar şehirdeki askerler mi?",
"VO__HUGO__CH06__CHATTER__IDLE_QUARRY_UP__030__M__1": "Ama iyilerdi...",
"VO__HUGO__CH06__CHATTER__INTERACT_FEATHER__020__M__1": "Çok yumuşak ve çok mavi!",
"VO__HUGO__CH06__CHATTER__INTERACT_FEATHER__040__M__1": "Ah! Evet!",
"VO__HUGO__CH06__CHATTER__INTERACT_FEATHER__060__M__1": "Evet!",
"VO__HUGO__CH06__CHATTER__INTERACT_FEATHER__080__M__1": "Bir şövalye-kuş!",
"VO__HUGO__CH06__CHATTER__ISLAND_IDLE__010__M__1": "İyileşeceksin... adada, iyileşeceksin...",
"VO__HUGO__CH06__CHATTER__LAST_METERS__010__M__1": "Üzgünüm... Üzgünüm!",
"VO__HUGO__CH06__CHATTER__LAST_METERS__050__M__1": "Beni yere bırak! Yürüyebilirim!",
"VO__HUGO__CH06__CHATTER__LAST_METERS__070__M__1": "Bırak beni! Koşarım! Ölemezsin!",
"VO__HUGO__CH06__CHATTER__LASTPART_RATMOVE__020__M__1": "Getirin onları! Hepinizi yiyeceğim!",
"VO__HUGO__CH06__CHATTER__LASTPART_RATMOVE__050__M__1": "Evet yapabilirim! Sizi de evlerinizi de yok edebilirim!",
"VO__HUGO__CH06__CHATTER__LOCK_SECRET__010__M__1": "Güzel...",
"VO__HUGO__CH06__CHATTER__MASS_APPROACH__010__M__1": "Arkadaki Perreux mu?!",
"VO__HUGO__CH06__CHATTER__MASS_APPROACH__030__M__1": "Ah... Pardon...",
"VO__HUGO__CH06__CHATTER__MASS_FROM_AFAR__010__M__1": "Ah... Şunu duyuyor musun?! Bu ne?!",
"VO__HUGO__CH06__CHATTER__MASS_FROM_AFAR__030__M__1": "Burada bir kilise mi var?",
"VO__HUGO__CH06__CHATTER__MASS_OVER__030__M__1": "Âmin.",
"VO__HUGO__CH06__CHATTER__MORE_MEN_CAVE__005__M__1": "Burada da varlar...",
"VO__HUGO__CH06__CHATTER__NEW_SOLDIERS_DYEFACTORY__050__M__1": "Dinlen... Onlarla ben ilgilenirim...",
"VO__HUGO__CH06__CHATTER__NEW_SOLDIERS_DYEFACTORY__070__M__1": "Sana göstereceğim...",
"VO__HUGO__CH06__CHATTER__OPENED_DOOR__010__M__1": "Açık.",
"VO__HUGO__CH06__CHATTER__OPENED_DOOR_STUCK__010__M__1": "Kapıyı açacağım! Arkasında durma!",
"VO__HUGO__CH06__CHATTER__OPENING_DOOR_FALL__030__M__1": "Hayır! Gideceğiz! Seni koruyacağım! Adaya birlikte gideceğiz!",
"VO__HUGO__CH06__CHATTER__OPENING_DOOR_SMELL__013__M__1": "Çok pis kokuyor...",
"VO__HUGO__CH06__CHATTER__PAIN_BURST_IDLE__020__M__1": "Gerçekten acıyor mu?",
"VO__HUGO__CH06__CHATTER__PAIN_BURST_IDLE__040__M__1": "Geçecek. Seni iyileştireceğim.",
"VO__HUGO__CH06__CHATTER__PERREUX_GOODBYE__030__M__1": "Teşekkürler.",
"VO__HUGO__CH06__CHATTER__PERREUX_HELP__010__M__1": "İnsanlar bizi ihbar eder mi?",
"VO__HUGO__CH06__CHATTER__PILGRIM_WELCOME__025__M__1": "İnsanlar neden şarkı söylüyor?",
"VO__HUGO__CH06__CHATTER__PILGRIM_WELCOME__120__M__1": "Teşekkürler!",
"VO__HUGO__CH06__CHATTER__POST_RATMOVE__010__M__1": "Ha... ne...?! O gerçek miydi?",
"VO__HUGO__CH06__CHATTER__POST_RATMOVE__040__M__1": "Merak etme! Yardım ettiler!",
"VO__HUGO__CH06__CHATTER__POST_SWING__020__M__1": "Kendimizinkine sahip olmak için sabırsızlanıyorum!",
"VO__HUGO__CH06__CHATTER__PRE_RAT_SENSE__010__M__1": "Dur, Amicia... İnsanlar var...",
"VO__HUGO__CH06__CHATTER__PRE_RAT_SENSE__030__M__1": "Ben... onları hissediyorum... Sanırım fareler... Daha iyi hissetmeye çalışabilirim...",
"VO__HUGO__CH06__CHATTER__PRE_RAT_SENSE__050__M__1": "Evet, merak etme...",
"VO__HUGO__CH06__CHATTER__PROMISE_IDLE__010__M__1": "Gerçekten iyi hissetmiyorsan söyleyeceğine söz ver...",
"VO__HUGO__CH06__CHATTER__QUARRY_ALL_DEAD__010__M__1": "Hepsini öldürdün... Sanırım...",
"VO__HUGO__CH06__CHATTER__QUARRY_DOOR_INTERACT__010__M__1": "Başın kötü görünüyor...",
"VO__HUGO__CH06__CHATTER__QUARRY_DOOR_INTERACT__030__M__1": "Hayır, onlar... derinde... şimdilik...",
"VO__HUGO__CH06__CHATTER__QUARRY_FIRST_KILL__020__M__1": "Evet... çıkmalıyız...",
"VO__HUGO__CH06__CHATTER__QUARRY_RATSENSE_REMINDER__020__M__1": "İstersen farelerin yankısını kullanabiliriz...",
"VO__HUGO__CH06__CHATTER__QUARRY_STAIRS_RATSENSE__010__M__1": "Daha fazlasını görüyorum...",
"VO__HUGO__CH06__CHATTER__QUARRY_THIRD_KILL__020__M__1": "Evet, bizi görmeden önce...",
"VO__HUGO__CH06__CHATTER__RACE_DEBRIEF__010__M__1": "Güzel bir yarıştı!",
"VO__HUGO__CH06__CHATTER__RACE_DEBRIEF__030__M__1": "Hâlâ acıyor...",
"VO__HUGO__CH06__CHATTER__RACE_DEBRIEF__050__M__1": "Ama tatlı bir korkak!",
"VO__HUGO__CH06__CHATTER__RACE_DEBRIEF__070__M__1": "Bir dahaki sefere kazanmana izin vereceğim!",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_ENDS__010__M__1": "Tamam... Gösterdim onlara!",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_ENDS__030__M__1": "Evet...",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_KILLS_1__010__M__1": "Bırakın... geçelim!",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_KILLS_2__010__M__1": "Şimdi korktun, ha?",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_KILLS_3__010__M__1": "Bizi durduramayacaksınız...",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_OVER__010__M__1": "İşte... Tamam...",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_OVER__020__M__1": "Öldüler...",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_OVER__040__M__1": "Evet... Onları... kullanmama izin verdiler...",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_OVER__047__M__1": "Evet... Ayağa kalkabilir misin?",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_OVER__060__M__1": "Hadi, gidelim!",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_OVER_ALT__010__M__1": "Hepsi öldü... Gidebiliriz.",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_OVER_ALT__030__M__1": "Evet... Ayağa kalkabilir misin?",
"VO__HUGO__CH06__CHATTER__RAT_MOVE_START__010__M__1": "Evet. Güvenli bir yol açacağım...",
"VO__HUGO__CH06__CHATTER__RAT_SENSE_TUTO_OK__005__M__1": "Evet! Onları görüyorum! Buradalar... Askerler!",
"VO__HUGO__CH06__CHATTER__RAT_SENSE_TUTO_OK__020__M__1": "Fareler... İnsanların kanını hissedebiliyorlar!... Artık ben de... bir ses gibi... bir yankı gibi...",
"VO__HUGO__CH06__CHATTER__RAT_SENSE_TUTO_OK__040__M__1": "Yakın. Geliyor. İstersen tekrar yapabilirim.",
"VO__HUGO__CH06__CHATTER__RATMOVE_AMICIA__070__M__1": "Sana... zarar vermezler...",
"VO__HUGO__CH06__CHATTER__RATS_ARRIVAL__010__M__1": "Buradalar! Amicia!",
"VO__HUGO__CH06__CHATTER__RATS_ARRIVAL__020__M__1": "Uyanmalısın!",
"VO__HUGO__CH06__CHATTER__RATS_ATTACK_REMINDER__010__M__1": "Amicia, hâlâ farelere saldırtabilirim...",
"VO__HUGO__CH06__CHATTER__RATS_BASINS_REACTION__010__M__1": "Amicia, havuzların içinde saklanan fareler var...",
"VO__HUGO__CH06__CHATTER__RATS_CALLING_IDLE__010__M__1": "Amicia... fareler çağırıyor... onları kullanmamdan hoşlanıyorlar...",
"VO__HUGO__CH06__CHATTER__RATS_FOLLOWING__010__M__1": "Fareler... onları hissediyorum... altta hareket ediyorlar... Bizi takip ediyorlar...",
"VO__HUGO__CH06__CHATTER__RATWAVE_ESCAPE__040__M__1": "Bu... bu gürültü de ne?",
"VO__HUGO__CH06__CHATTER__RATWAVE_ESCAPE__050__M__1": "Ne... oldu?",
"VO__HUGO__CH06__CHATTER__RATWAVE_ESCAPE__070__M__1": "Yine... yine yaptım...",
"VO__HUGO__CH06__CHATTER__RATWAVE_ESCAPE__080__M__1": "Hep... yanlış yapıyorum...",
"VO__HUGO__CH06__CHATTER__REACHING_BUILDING__020__M__1": "İçeride dinleneceksin!",
"VO__HUGO__CH06__CHATTER__REACHING_GATE__020__M__1": "Evet! Güvende olacağız!",
"VO__HUGO__CH06__CHATTER__REINFORCEMENTS__030__M__1": "Amicia...",
"VO__HUGO__CH06__CHATTER__REINFORCEMENTS_KILL_2__010__M__1": "Bizden uzak durun!",
"VO__HUGO__CH06__CHATTER__REINFORCEMENTS_REACT__010__M__1": "Daha fazlası var, Amicia!",
"VO__HUGO__CH06__CHATTER__SALPETER_REMINDER_2__010__M__1": "Onun başını döndüremez... ya da onu kör edemez misin?!",
"VO__HUGO__CH06__CHATTER__SECONDPART_RATMOVE__030__M__1": "Senden bıktım! Senden ve ordundan nefret ediyorum! Öldün sen! ÖLDÜN!",
"VO__HUGO__CH06__CHATTER__SOLDIERS_ENTERING_DYEING__015__M__1": "Eyvah... Askerler!",
"VO__HUGO__CH06__CHATTER__SOLDIERS_ENTERING_DYEING__030__M__1": "Hayır! Bizi görecekler! Ne yapayım?",
"VO__HUGO__CH06__CHATTER__SOLDIERS_ENTERING_DYEING__080__M__1": "Amicia...",
"VO__HUGO__CH06__CHATTER__SOUVENIR_BANDAGE__020__M__1": "Daha iyi hissetmeni sağlayacak.",
"VO__HUGO__CH06__CHATTER__SOUVENIR_BANDAGE__040__M__1": "Hangisi...?",
"VO__HUGO__CH06__CHATTER__SOUVENIR_BANDAGE__070__M__1": "Kıpırdama...",
"VO__HUGO__CH06__CHATTER__SOUVENIR_BANDAGE__090__M__1": "Pardon... Bitti.",
"VO__HUGO__CH06__CHATTER__SOUVENIR_BANDAGE__110__M__1": "Umarım faydası olur.",
"VO__HUGO__CH06__CHATTER__SOUVENIR_BANDAGE_DENIED__020__M__1": "Pekâlâ.",
"VO__HUGO__CH06__CHATTER__SOUVENIR_BANDAGE_INTRO__010__M__1": "Ah... kumaş... yepyeni...",
"VO__HUGO__CH06__CHATTER__SOUVENIR_BANDAGE_INTRO__020__M__1": "Sargın kirli. Değiştirebiliriz.",
"VO__HUGO__CH06__CHATTER__SOUVENIR_BANDAGE_INTRO__030__M__1": "Sanırım şunları kullanabiliriz... Temizler.",
"VO__HUGO__CH06__CHATTER__SOUVENIR_SWING__160__M__1": "Yeni evimizde bir salıncağımız olabilir mi?!",
"VO__HUGO__CH06__CHATTER__SOUVENIR_SWING__180__M__1": "Ah! Evet! Elma ağaçları!",
"VO__HUGO__CH06__CHATTER__SOUVENIR_SWING_DENIED__020__M__1": "Ah... O zaman bir dahaki sefere.",
"VO__HUGO__CH06__CHATTER__SPOT_DYE_END__020__M__1": "Evet... Gördün mü? Başaracağız!",
"VO__HUGO__CH06__CHATTER__STANDING_UP__020__M__1": "Amicia...",
"VO__HUGO__CH06__CHATTER__STANDING_UP__040__M__1": "Kalk! Gitmeliyiz...",
"VO__HUGO__CH06__CHATTER__STORYTELLER_REACTION__010__M__1": "Ayine mi gidiyoruz?",
"VO__HUGO__CH06__CHATTER__STORYTELLER_SPEECH__040__M__1": "Şey, ben kendi adama gitmeyi yeğlerim... Eminim daha güzeldir!",
"VO__HUGO__CH06__CHATTER__STORYTELLER_SPEECH__060__M__1": "Eyvah...",
"VO__HUGO__CH06__CHATTER__SWING__010__M__1": "Ah, bak! Bir salıncak!",
"VO__HUGO__CH06__CHATTER__SWING__030__M__1": "Sen bin! Ben iterim!",
"VO__HUGO__CH06__CHATTER__SWING__050__M__1": "Hayır, ben iteceğim. Sen yorgunsun.",
"VO__HUGO__CH06__CHATTER__SWING_STOP__020__M__1": "Evet!",
"VO__HUGO__CH06__CHATTER__SWINGING__010__M__1": "Hadi bakalım!",
"VO__HUGO__CH06__CHATTER__SWINGING__040__M__1": "İyiyim! Sadece gözlerini kapat ve uçtuğunu hayal et!",
"VO__HUGO__CH06__CHATTER__THIRDPART_RATMOVE__030__M__1": "Hepiniz aynısınız! Hepiniz canavarsınız!",
"VO__HUGO__CH06__CHATTER__THROUGH_CAMP__010__M__1": "Neden Roma'ya gidiyorlar?",
"VO__HUGO__CH06__CHATTER__TO_CAMP__020__M__1": "Bir pazar!",
"VO__HUGO__CH06__CHATTER__TO_CAMP_DOWN__010__M__1": "Belki ada hakkında bir şey biliyorlardır!",
"VO__HUGO__CH06__CHATTER__TRAP_DOOR__010__M__1": "Burada! Bir kapak...",
"VO__HUGO__CH06__CHATTER__TRAP_DOOR_FALL__020__M__1": "Amicia...",
"VO__HUGO__CH06__CHATTER__TRAP_DOOR_FALL__050__M__1": "Beklemeliyiz, Amicia...",
"VO__HUGO__CH06__CHATTER__TREMORS__010__M__1": "Ne?!...",
"VO__HUGO__CH06__CHATTER__TREMORS__020__M__1": "Hayır, hayır...",
"VO__HUGO__CH06__CHATTER__TREMORS__025__M__1": "Geliyorlar!",
"VO__HUGO__CH06__CHATTER__TREMORS__030__M__1": "Amicia...",
"VO__HUGO__CH06__CHATTER__TREMORS__040__M__1": "Kımılda!",
"VO__HUGO__CH06__CHATTER__WAITING_FOR_RATMOVE__020__M__1": "Göreceksin... Odaklanıyorum...",
"VO__HUGO__CH06__CHATTER__WAKING_UP__020__M__1": "Ah! Döndün!",
"VO__HUGO__CH06__CHATTER__WAKING_UP__026__M__1": "İyi misin?",
"VO__HUGO__CH06__CHATTER__WEAKNESS__020__M__1": "İyileşeceksin! Yakında denizde olacağız!",
"VO__HUGO__CH06__CHATTER__WOOD_START__010__M__1": "Bir adaya nasıl ulaşacağız?",
"VO__HUGO__CH06__CHATTER__WOOD_START__030__M__1": "Sence annem kızar mı?",
"VO__HUGO__CH06__CHATTER__WOOD_START__060__M__1": "Peki sence o haydutlar onları takip eder mi?",
"VO__HUGO__CH06__CHATTER__WOOD_START__080__M__1": "Ama silahları yok...",
"VO__HUGO__CH06__CHATTER__WOODS_WRONGWAY__010__M__1": "Geri mi dönüyoruz?",
"VO__HUGO__CH06__CHATTER__WORRIED_IDLE__010__M__1": "Hâlâ iyi misin?",
"VO__HUGO__CH06__CHATTER__WOUND_IDLE__010__M__1": "Kaçtığımızda yaranı yıkayacağım...",
"VO__HUGO__CH06__HELPER__RATS_FIRE_1__010__M__1": "Karşıya geçmek için ateş lazım...",
"VO__HUGO__CH06__HELPER__RATS_FIRE_2__010__M__1": "Amicia, belki şu meşaleyi kullanabiliriz?",
"VO__HUGO__CH06__RTC__230_FREEDOM__010__M__1": "Tekne kullanmayı bilmiyorlar.",
"VO__HUGO__CH06__RTC__230_FREEDOM__030__M__1": "Annem ve Lucas.",
"VO__HUGO__CH06__RTC__230_FREEDOM__050__M__1": "Yine kanıyor...",
"VO__HUGO__CH06__RTC__230_FREEDOM__065__M__1": "Şurada su var.",
"VO__HUGO__CH06__RTC__230_FREEDOM__090__M__1": "Evet. Bunlar dişe benziyor. İki dişli bir ada!",
"VO__HUGO__CH06__RTC__230_FREEDOM__110__M__1": "Demek gerçekten gerçek!",
"VO__HUGO__CH06__RTC__230_FREEDOM__120__M__1": "Ben yaparım.",
"VO__HUGO__CH06__RTC__230_FREEDOM__140__M__1": "Evet.",
"VO__HUGO__CH06__RTC__230_FREEDOM__150__M__1": "Tamam!",
"VO__HUGO__CH06__RTC__230_FREEDOM__180__M__1": "Canını acıtmamaya çalıştım!",
"VO__HUGO__CH06__RTC__230_FREEDOM__200__M__1": "Evet!",
"VO__HUGO__CH06__RTC__240_FLAGELLANT__020__M__1": "Merhaba!",
"VO__HUGO__CH06__RTC__240_FLAGELLANT__075__M__1": "Hayır! Bir ada arıyoruz! İki dişi var, bir kuş var, küçük bir göl ve çiçekler var...",
"VO__HUGO__CH06__RTC__249_CAPTAIN_DEATH__010__M__1": "Amicia! İyi misin?",
"VO__HUGO__CH06__RTC__250_DEAD_END__010__M__1": "Am... Amicia... Amicia...",
"VO__HUGO__CH06__RTC__250_DEAD_END__020__M__1": "Hayır. Çok kanıyor...",
"VO__HUGO__CH06__RTC__250_DEAD_END__040__M__1": "Geliyorlar!",
"VO__HUGO__CH06__RTC__250_DEAD_END__060__M__1": "Emin misin?",
"VO__HUGO__CH06__RTC__270_COMEBACK__010__M__1": "Amicia! Gel!",
"VO__HUGO__CH06__RTC__270_COMEBACK__020__M__1": "Lütfen! Amicia! Çabuk!",
"VO__HUGO__CH06__RTC__270_COMEBACK__030__M__1": "Amicia! Lütfen gel! Amicia!",
"VO__HUGO__CH06__RTC__270_COMEBACK__035__M__1": "Amicia, lütfen! Lütfen, Amicia!",
"VO__HUGO__CH06__RTC__270_COMEBACK__040__M__1": "Hayır, ona zarar verme!",
"VO__KID_F2__CH06__CHATTER__STORYTELLER_SPEECH__010__M__1": "Roma'da Papa'yı görecek miyiz?",
"VO__KID_F2__CH06__CHATTER__STORYTELLER_SPEECH__030__M__1": "Sabırsızlanıyorum!",
"VO__KID_F2__CH06__CHATTER__STORYTELLER_SPEECH__110__M__1": "Altın! Altına bayılırım!",
"VO__KID_M1__CH06__CHATTER__STORYTELLER_SPEECH__070__M__1": "Bütün bazilikalarda dua edecek miyiz?",
"VO__KID_M1__CH06__CHATTER__STORYTELLER_SPEECH__090__M__1": "Çok güzel olacak.",
"VO__PEOPLE_F1__CH06__CHATTER__PILGRIMS_REACTION__010__M__1": "Neler oluyor?!",
"VO__PEOPLE_F2__CH06__CHATTER__FRIENDS_TALKING__010__M__1": "Hey Jeannine, biraz tuzun kaldı mı acaba?",
"VO__PEOPLE_F2__CH06__CHATTER__FRIENDS_TALKING__030__M__1": "Son gelen grupla daha da kalabalığız. Daha çok tabak, daha büyük tencere demek.",
"VO__PEOPLE_F2__CH06__CHATTER__FRIENDS_TALKING__050__M__1": "Haklısın...",
"VO__PEOPLE_F2__CH06__CHATTER__MASS__060__M__1": "Âmin.",
"VO__PEOPLE_F2__CH06__CHATTER__PERREUX_IDLE__020__M__1": "B-ben mi?",
"VO__PEOPLE_F2__CH06__CHATTER__PILGRIMS_REACTION__020__M__1": "Birini arıyorlar...",
"VO__PEOPLE_F3__CH06__CHATTER__HELLO_RANDOM__010__M__1": "Merhaba!",
"VO__PEOPLE_F3__CH06__CHATTER__MASS__040__M__1": "Âmin.",
"VO__PEOPLE_F3__CH06__CHATTER__PILGRIM_PRAYING__010__M__1": "Umarım hava güzel kalır...",
"VO__PEOPLE_F4__CH06__CHATTER__FRIENDS_TALKING__020__M__1": "Şimdiden mi bitirdin?",
"VO__PEOPLE_F4__CH06__CHATTER__FRIENDS_TALKING__040__M__1": "Bırak süpürmeyi bitireyim, sonra sana biraz veririm. Sadece çok çabuk tüketme—onlara daha çok içmek için bahane oluyor.",
"VO__PEOPLE_F4__CH06__CHATTER__PILGRIM_WELCOME__010__M__1": "Merhaba... Sizin için... bir şey yapabilir miyim?",
"VO__PEOPLE_F4__CH06__CHATTER__PILGRIM_WELCOME__030__M__1": "Çünkü ayin vakti! Hac yolundayız, bu yüzden yolculuğumuzun başarısı için dua ediyoruz.",
"VO__PEOPLE_F4__CH06__CHATTER__PILGRIM_WELCOME__070__M__1": "Aynen! Ya siz? Nereye gidiyorsunuz?",
"VO__PEOPLE_F4__CH06__CHATTER__PILGRIM_WELCOME__080__M__1": "Ah! Liderimiz Perreux bölgeyi iyi bilir. Size yardım eder.",
"VO__PEOPLE_F4__CH06__CHATTER__PILGRIM_WELCOME__090__M__1": "Onu harabelerin yanında bulursunuz. Ayini yöneten kişi o.",
"VO__PEOPLE_F4__CH06__CHATTER__PILGRIM_WELCOME__100__M__1": "Yine de gölgede biraz dinlenmelisiniz. Yaralı görünüyorsunuz...",
"VO__PEOPLE_F4__CH06__CHATTER__PILGRIM_WELCOME__130__M__1": "Rica ederim!",
"VO__PEOPLE_F4__CH06__CHATTER__SOLDIER_INTERROGATION__020__M__1": "Her gün yeni insanlar geliyor, biliyorsunuz...",
"VO__PEOPLE_F4__CH06__CHATTER__TENT_EVENT__010__M__1": "Hey! Dikkatli ol!",
"VO__PEOPLE_M1__CH06__CHATTER__MASS_APPROACH__020__M__1": "Şşş! Evet... Onu ayin bitince görürsünüz.",
"VO__PEOPLE_M1__CH06__CHATTER__MASS_OVER__010__M__1": "Artık gidebilirsiniz...",
"VO__PEOPLE_M1__CH06__CHATTER__STORYTELLER_SPEECH__020__M__1": "Belki... şanslıysak. Orada binlerce, on binlerce insan olacak!",
"VO__PEOPLE_M1__CH06__CHATTER__STORYTELLER_SPEECH__080__M__1": "Yapabilirsek... Ama her hâlükârda Tanrı'ya hiç olmadığımız kadar yakın olacağız.",
"VO__PEOPLE_M1__CH06__CHATTER__STORYTELLER_SPEECH__100__M__1": "Ah, öyle olacak! Roma baştan aşağı altın ve mermer!",
"VO__PEOPLE_M1__CH06__RTC__240_FLAGELLANT__190__M__1": "Hey! Ne yapıyorsun?",
"VO__PEOPLE_M2__CH06__CHATTER__MASS__050__M__1": "Âmin",
"VO__PEOPLE_M2__CH06__CHATTER__PILGRIMS_REACTION__050__M__1": "Lütfen bize zarar vermeyin!",
"VO__PEOPLE_M2__CH06__CHATTER__TALKING_BENCH__020__M__1": "Evet, bunlar sağlam.",
"VO__PEOPLE_M3__CH06__CHATTER__MASS__030__M__1": "Âmin.",
"VO__PEOPLE_M3__CH06__CHATTER__PILGRIM_COMPLAINING__010__M__1": "Zavallı ayaklarım... Hiç bu kadar yürümemiştim...",
"VO__PEOPLE_M3__CH06__CHATTER__PILGRIMS_REACTION__060__M__1": "Hiçbir şey yapmadık! Biz iyi Hristiyanlarız!",
"VO__PEOPLE_M4__CH06__CHATTER__CHILDREN_RUNNING__010__M__1": "Dikkatli olun çocuklar, çok hızlı değil!",
"VO__PEOPLE_M4__CH06__CHATTER__FOOD__020__M__1": "Burnun iyiymiş!",
"VO__PEOPLE_M4__CH06__CHATTER__HELLO_TREE__010__M__1": "Merhaba.",
"VO__PEOPLE_M4__CH06__CHATTER__SOLDIER_INTERROGATION__040__M__1": "Emin değilim, artık çok kalabalığız...",
"VO__PEOPLE_M5__CH06__CHATTER__TALKING_BENCH__010__M__1": "Yaşlılar iyi görünüyor.",
"VO__PEOPLE_M5__CH06__CHATTER__TALKING_BENCH__030__M__1": "Evet, imanları güçlü.",
"VO__PILGRIM_LEADER__CH06__CHATTER__FIRST_STEPS__010__M__1": "Sizi kamptan çıkarmalıyız! Beni yakından takip edin! Aranıza karışmaya çalışın!",
"VO__PILGRIM_LEADER__CH06__CHATTER__FIRST_STEPS__020__M__1": "Bu taraftan.",
"VO__PILGRIM_LEADER__CH06__CHATTER__MASS__010__M__1": "Bu mütevazı hacıları kutsal yolculuklarında koru; bu karanlık zamanlarda merhamet ararlarken, en zayıfların dualarını kabul et.",
"VO__PILGRIM_LEADER__CH06__CHATTER__MASS__020__M__1": "Âmin.",
"VO__PILGRIM_LEADER__CH06__CHATTER__MASS_PRAY__010__M__1": "Şimdi dua edelim.",
"VO__PILGRIM_LEADER__CH06__CHATTER__MASS_PRAY__020__M__1": "Tanrım, sana daha da yaklaşıyorum.",
"VO__PILGRIM_LEADER__CH06__CHATTER__PERREUX_DISTRACT__010__M__1": "Affedersiniz...",
"VO__PILGRIM_LEADER__CH06__CHATTER__PERREUX_DISTRACT__030__M__1": "Şuradaki grubu kontrol ettiniz mi? Bazıları bize yakın zamanda katıldı. Pek aradığınız kaçaklara benzemiyorlar ama... kim bilir?",
"VO__PILGRIM_LEADER__CH06__CHATTER__PERREUX_DISTRACT_OK__005__M__1": "Yol açık! Gelin, sakince.",
"VO__PILGRIM_LEADER__CH06__CHATTER__PERREUX_GOODBYE__010__M__1": "Bu ağılın diğer tarafında denize giden bir yol bulacaksınız.",
"VO__PILGRIM_LEADER__CH06__CHATTER__PERREUX_GOODBYE__040__M__1": "Dikkatli olun...",
"VO__PILGRIM_LEADER__CH06__CHATTER__PERREUX_HELP__011__M__1": "Hayır, ama... umarım kefaretini ödersin.",
"VO__PILGRIM_LEADER__CH06__CHATTER__PERREUX_HELP__021__M__1": "Hepimiz eninde sonunda yargılanırız.",
"VO__PILGRIM_LEADER__CH06__CHATTER__PROBLEM__010__M__1": "Hayır...",
"VO__PILGRIM_LEADER__CH06__CHATTER__PROBLEM__030__M__1": "Sizi görmeden o arabanın altına saklanın! Onlarla ben ilgilenirim...",
"VO__PILGRIM_LEADER__CH06__CHATTER__PROBLEM_HELPER__010__M__1": "Arabanın altına girin! Çabuk! Onlarla ben ilgilenirim!",
"VO__PILGRIM_LEADER__CH06__CHATTER__SLOPE__015__M__1": "Yavaşça. Daha fazlası var.",
"VO__PILGRIM_LEADER__CH06__CHATTER__SOLDIER_INTERROGATION__005__M__1": "Dikkatli ol.",
"VO__PILGRIM_LEADER__CH06__RTC__240_FLAGELLANT__040__M__1": "Ah... Merhaba!",
"VO__PILGRIM_LEADER__CH06__RTC__240_FLAGELLANT__050__M__1": "Ve hoş geldiniz. Buralarda yenisiniz...",
"VO__PILGRIM_LEADER__CH06__RTC__240_FLAGELLANT__070__M__1": "Peki nereye gidiyorsunuz? Roma'ya değil herhâlde?",
"VO__PILGRIM_LEADER__CH06__RTC__240_FLAGELLANT__090__M__1": "Ezbere değil ama bir yerde eski bir Akdeniz haritam var... Bakmak ister misiniz?",
"VO__PILGRIM_LEADER__CH06__RTC__240_FLAGELLANT__110__M__1": "Neler oluyor?...",
"VO__PILGRIM_LEADER__CH06__RTC__240_FLAGELLANT__295__M__1": "Suçlu bir bakışı gördüğümde tanırım... ama ne yapmış olursanız olun, bir çocuğu ele vermem. Benimle gelin.",
"VO__SOLDIER_B1__CH06__CHATTER__BLIND_RECOVER_1__010__M__1": "O kadar kolay olacağını sanma!",
"VO__SOLDIER_B1__CH06__CHATTER__BLIND_RECOVER_2__010__M__1": "Benden kaçamayacaksın!",
"VO__SOLDIER_B1__CH06__CHATTER__BLIND_RECOVER_3__010__M__1": "Bir gün daha göremeyeceksin!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_CROSSBOW__010__M__1": "Bu zırh bundan beterini durdurdu!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_FIGHT__020__M__1": "İşte buradasın!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_FIGHT__050__M__1": "Şimdi, meydan okumanın BEDELİNİ ödeyeceksin! Şimdi Canavar'ın ısırığını tanıyacaksın!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_FIGHT__060__M__1": "Kapana kısıldın. Bu kişisel—artık benimsin.",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_FIGHT__090__M__1": "Çocuğun da icabına bakarım... Bu topraklarda yeterince yabani ot var!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_FIGHT__110__M__1": "Bu sefer ilmik yok. Kafanı ezeceğim!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_FIGHT__120__M__1": "Ben kanunun koluyum... Ve onun cellatı olacağım!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_FUTILE__010__M__1": "Zavallı...",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_FUTILE__020__M__1": "Hünerini mi kaybettin?!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_IDLE_1__010__M__1": "Bunun geleceğini biliyordun!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_IDLE_2__010__M__1": "Kaçmayı kesin, sizi küçük bok parçaları!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_IGNIFER__020__M__1": "Büyün bugün seni kurtarmayacak!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_ORDER_FOREST__010__M__1": "Bazıları az önce kampı geçen bir oğlanla bir kız gördü! Aramayı genişletin!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_RING__010__M__1": "Seni küçük velet! Bu beni durdurmaz!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_RING__040__M__1": "İkinizi de öldüreceğim!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_SEARCH__010__M__1": "Neredesin?!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_SEARCH__020__M__1": "Saklanmaya mı çalışıyorsun?",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_SEARCH__030__M__1": "Benden kaçamazsın! Burada olmaz!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_SLING__010__M__1": "Gerçekten mi?! O oyuncak silahın bana işleyeceğini mi sandın?!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_SPOTTED__010__M__1": "Buldum seni!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_SPOTTED__020__M__1": "Buraya gel!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_SPOTTED__030__M__1": "İşte buradasın!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_STUNNED_FIRST__010__M__1": "Ucuz numara! Hiç onurun yok!",
"VO__SOLDIER_B1__CH06__CHATTER__CAPTAIN_STUNNED_SECOND__010__M__1": "Lanet cadı! Kafanı... ezeceğim!",
"VO__SOLDIER_B1__CH06__CHATTER__GORGE_ENTRY__009__M__1": "Peşlerinden! Tehlikeli olan kız! Görür görmez öldürün!",
"VO__SOLDIER_B1__CH06__CHATTER__REINFORCEMENTS_DEAD__005__M__1": "Seni pislik! Buraya gel!",
"VO__SOLDIER_B1__CH06__CHATTER__REINFORCEMENTS_DEAD__010__M__1": "Kardeşlerimizin ölümünü boşa harcatmayacağım!",
"VO__SOLDIER_B1__CH06__CHATTER__SOLDIER_INTERROGATION__010__M__1": "Yakın zamanda yeni hacı geldi mi? Davetsiz biri?",
"VO__SOLDIER_B1__CH06__RTC__240_FLAGELLANT__105__M__1": "İyi insanlar!",
"VO__SOLDIER_B1__CH06__RTC__240_FLAGELLANT__175__M__1": "Bir oğlanla bir kız arıyoruz! Kız birkaç asker öldürdü! Silahlı ve tehlikeli!",
"VO__SOLDIER_B1__CH06__RTC__240_FLAGELLANT__185__M__1": "Arles Kontu Victor'un emriyle bu kampı arıyoruz... Yürüyün!",
"VO__SOLDIER_B1__CH06__RTC__240_FLAGELLANT__195__M__1": "Çekil yolumdan!",
"VO__SOLDIER_B2__CH06__CHATTER__BEGINNING_RATMOVE__060__M__1": "Fareler burada ne arıyor?!",
"VO__SOLDIER_B2__CH06__CHATTER__SECONDPART_RATMOVE__010__M__1": "Kapa çeneni, seni iğrenç şey! Şehrimizi yok ettin!",
"VO__SOLDIER_N1__CH06__CHATTER__CAPTAIN_ORDER_FOREST__040__M__1": "Üç kişi benimle! Sen! Aşağı in! Sen, yukarı!",
"VO__SOLDIER_N1__CH06__CHATTER__GORGE_ENTRY__060__M__1": "Buradan! Bir ekip aşağı inen bir yol buldu! Kımıldayın!",
"VO__SOLDIER_N1__CH06__CHATTER__LASTPART_RATMOVE__040__M__1": "Seni yakalayacağız! Hepimizi durduramazsın!",
"VO__SOLDIER_N1__CH06__CHATTER__MORE_MEN_TALKING__010__M__1": "O kız... Eğitimli askerleri alt etti. Kim bu? Duvar'ın savaş köpeklerinden biri mi?",
"VO__SOLDIER_N1__CH06__CHATTER__PERREUX_DISTRACT__020__M__1": "Ne istiyorsun?",
"VO__SOLDIER_N1__CH06__CHATTER__PERREUX_DISTRACT__040__M__1": "Hiç yoktan iyidir. Gidip bakalım...",
"VO__SOLDIER_N1__CH06__CHATTER__PERREUX_DISTRACT__045__M__1": "Onu duydunuz! Tetikte olun ve gözünüzü açık tutun!",
"VO__SOLDIER_N1__CH06__CHATTER__PERREUX_IDLE__010__M__1": "Hey! Sen!",
"VO__SOLDIER_N1__CH06__CHATTER__PERREUX_IDLE__030__M__1": "Ne zamandır bu alaydasın?!",
"VO__SOLDIER_N1__CH06__CHATTER__PILGRIMS_REACTION__040__M__1": "İş birliği yapın, kimseye zarar gelmez!",
"VO__SOLDIER_N1__CH06__CHATTER__REINFORCEMENTS_HELMET__010__M__1": "Suçlarının bedelini ölümle ödeyeceksin! Sana mezar bile olmayacak!",
"VO__SOLDIER_N1__CH06__CHATTER__SECONDPART_RATMOVE__020__M__1": "Onu sağ bırakamayız!",
"VO__SOLDIER_N1__CH06__CHATTER__SOLDIERS_ENCOUNTER__010__M__1": "Unutmayın! Arles Kontu bu toprakları ayaktakımından temizlemek istiyor! Bu kız kardeşlerinizi öldürdü! İnfazı burada gerçekleşecek!",
"VO__SOLDIER_N1__CH06__CHATTER__SOLDIERS_ENCOUNTER__030__M__1": "Emirleri veren o! Biraz saygı göster!",
"VO__SOLDIER_N1__CH06__CHATTER__SOLDIERS_ENTERING_DYEING__020__M__1": "Aman Meryem... Fareler! Burada da varlar!",
"VO__SOLDIER_N1__CH06__CHATTER__SOLDIERS_ENTERING_DYEING__050__M__1": "Gitmeliyiz! Gelin!",
"VO__SOLDIER_N1__CH06__CHATTER__SOLDIERS_LANDED__020__M__1": "İşçiler nerede? Bu maden terk edilmiş değil, değil mi?",
"VO__SOLDIER_N1__CH06__CHATTER__TENT_EVENT__020__M__1": "Geride dur!",
"VO__SOLDIER_N1__CH06__CHATTER__THIRDPART_RATMOVE__020__M__1": "Kızıl şehir için!",
"VO__SOLDIER_N2__CH06__CHATTER__2ND_ENCOUNTER_ENTRANCE__050__M__1": "Ölüleri rahat bırakın! Kızı infaz etmezsek kaptan bize daha beterini yapar!",
"VO__SOLDIER_N2__CH06__CHATTER__CAPTAIN_ORDER_FOREST__050__M__1": "Birbirinize göz kulak olun! Daha fazla adam yolda!",
"VO__SOLDIER_N2__CH06__CHATTER__DYING_BACKGROUND__010__M__1": "İblisler! İb—aaah!",
"VO__SOLDIER_N2__CH06__CHATTER__LASTPART_RATMOVE__010__M__1": "Çıldırmış! Onu durdurmalıyız! Daha çok adam lazım!",
"VO__SOLDIER_N2__CH06__CHATTER__REINFORCEMENTS__010__M__1": "Adamlarımız yere serildi! Bölgeyi tarayın! Ne olduğunu öğrenin!",
"VO__SOLDIER_N2__CH06__CHATTER__SOLDIERS_LANDED__010__M__1": "Gözünüzü açın, askerler! Burada kapana kısıldılar, geri dönemezler!",
"VO__SOLDIER_N2__CH06__CHATTER__SOLDIERS_LANDED__030__M__1": "Ah, şu lanet batıl inançlarınla başlama!",
"VO__SOLDIER_N3__CH06__CHATTER__2ND_ENCOUNTER_ENTRANCE__040__M__1": "Bu insanları silip süpürmüşler...",
"VO__SOLDIER_N3__CH06__CHATTER__BEGINNING_RATMOVE__040__M__1": "Bu senin için sonun!",
"VO__SOLDIER_N3__CH06__CHATTER__BEGINNING_RATMOVE__100__M__1": "Onları çocuk kontrol ediyor olmalı! Öldürün şu canavarları!",
"VO__SOLDIER_N3__CH06__CHATTER__MORE_MEN_TALKING__030__M__1": "İçine cin kaçmış! Bedenini yakmamız gerekecek!",
"VO__SOLDIER_N3__CH06__CHATTER__REINFORCEMENTS__020__M__1": "Anlaşıldı!",
"VO__SOLDIER_N3__CH06__CHATTER__SOLDIER_INTERROGATION__030__M__1": "İki çocuk. Bir kız ve küçük bir oğlan.",
"VO__SOLDIER_N3__CH06__CHATTER__SOLDIER_INTERROGATION__050__M__1": "O zaman düşün!",
"VO__SOLDIER_N3__CH06__CHATTER__SOLDIERS_ENTERING_DYEING__010__M__1": "Bu gürültü de ne?! Benimle!",
"VO__SOLDIER_N3__CH06__CHATTER__SOLDIERS_ENTERING_DYEING__060__M__1": "Sakin olun! Burada, yukarıda güvendeyiz! Şunlara bakın...",
"VO__SOLDIER_N3__CH06__CHATTER__SOLDIERS_LANDED__040__M__1": "Asıl korkman gereken kaptan! O kız onu bin tane İngiliz'den beter kızdırdı...",
"VO__SOLDIER_S1__CH06__CHATTER__ARROW_STUCK__010__M__1": "Dur!",
"VO__SOLDIER_S1__CH06__CHATTER__BEGINNING_RATMOVE__080__M__1": "Yine de öldürün onları! Onur için!",
"VO__SOLDIER_S1__CH06__CHATTER__CAPTAIN_ORDER_FOREST__060__M__1": "Anlaşıldı!",
"VO__SOLDIER_S1__CH06__CHATTER__CHASED__010__M__1": "İşte! Buradalar!",
"VO__SOLDIER_S1__CH06__CHATTER__CHASED__030__M__1": "Bana doğru!",
"VO__SOLDIER_S1__CH06__CHATTER__ENCOUNTER_CANYON_INTRO__010__M__1": "Yakında olduklarına dair ihbar aldık! Bölgeyi arayın! Yakalayın şu cadıyı!",
"VO__SOLDIER_S1__CH06__CHATTER__FOURTHPART_RATMOVE__010__M__1": "Ne yapıyorsun? Öldür şu iblisi!",
"VO__SOLDIER_S1__CH06__CHATTER__MORE_MEN_TALKING__020__M__1": "Duvar kadın ya da çocuk kullanmaz.",
"VO__SOLDIER_S1__CH06__CHATTER__NEW_SOLDIERS_DYEFACTORY__010__M__1": "Hey! Fareler... Şunu görüyor musun?! Fareler!",
"VO__SOLDIER_S1__CH06__CHATTER__NEW_SOLDIERS_DYEFACTORY__030__M__1": "Dikkat!",
"VO__SOLDIER_S1__CH06__CHATTER__PILGRIMS_REACTION__030__M__1": "Yol açın! Çadırlarınızı boşaltın!",
"VO__SOLDIER_S1__CH06__CHATTER__RATS_APPEARANCE__010__M__1": "Kız burada! Toplanın!",
"VO__SOLDIER_S1__CH06__CHATTER__REINFORCEMENTS_LIGHT__010__M__1": "Durdurun şu cadıyı!",
"VO__SOLDIER_S1__CH06__CHATTER__STANDING_UP__010__M__1": "Bana doğru! Buradalar! Takviye lazım!",
"VO__SOLDIER_S1__CH06__CHATTER__THIRDPART_RATMOVE__010__M__1": "Düşen kardeşlerimiz için!",
"VO__SOLDIER_S1__CH06__CHATTER__WOODS_FALL__010__M__1": "Yakaladım! İşte!",
"VO__SOLDIER_S1__CH06__RTC__250_DEAD_END__030__M__1": "Bakın! Buradalar!",
"VO__SOLDIER_S2__CH06__CHATTER__BEGINNING_RATMOVE__090__M__1": "Fareler! Onları savunuyorlar!",
"VO__SOLDIER_S2__CH06__CHATTER__NEW_SOLDIERS_DYEFACTORY__020__M__1": "Evet! Burada ne oldu?! Onlar... adamlarımızdan bazılarını... yiyorlar!",
"VO__SOLDIER_S2__CH06__CHATTER__SOLDIERS_ENCOUNTER__020__M__1": "Peki Kont'umuz nerede, ha? Toprakları veba kırıyor!",
}
