# -*- coding: utf-8 -*-
# CH15 VO - kaynak proper Turkce; build asamasinda SUB uygulanir.
# Arnaud=sen, Count Victor=sen(dusman). Marseille->Marsilya, Nebula/Macula korunur, Defiler->Kirletici.
T = {
"VO__AMICIA__CH15__CHATTER__ABOUT_COUNT__010__M__1": "Kont... bir şey söyledi mi?",
"VO__AMICIA__CH15__CHATTER__ABOUT_COUNT__030__M__1": "Fethedilecek bir şey kalmayacak.",
"VO__AMICIA__CH15__CHATTER__AMICIA_KILL_1__010__M__1": "Geçmemize izin verin!",
"VO__AMICIA__CH15__CHATTER__AMICIA_KILL_2__010__M__1": "Neden hepiniz ölmeye bu kadar can atıyorsunuz?!",
"VO__AMICIA__CH15__CHATTER__AMICIA_KILL_3__010__M__1": "Geliyorum Hugo... Bizi durduramazlar...",
"VO__AMICIA__CH15__CHATTER__AMICIA_KILL_4__010__M__1": "Gerekirse hepinizi öldürürüm...",
"VO__AMICIA__CH15__CHATTER__AMICIA_KILL_5__010__M__1": "Hepiniz boşuna ölüyorsunuz!",
"VO__AMICIA__CH15__CHATTER__AMICIA_KILL_6__010__M__1": "Lanet aptallar! Yaşamayı hak etmediğimizin kanıtısınız sadece!",
"VO__AMICIA__CH15__CHATTER__BLOCKER__050__M__1": "Dur, şu topumuz var!",
"VO__AMICIA__CH15__CHATTER__BLOCKER__063__M__1": "Bilmiyorum... dur...",
"VO__AMICIA__CH15__CHATTER__BLOCKER__067__M__1": "Buraya bastır... Bu olmalı...",
"VO__AMICIA__CH15__CHATTER__BLOCKER__070__M__1": "Çözdüm... galiba!",
"VO__AMICIA__CH15__CHATTER__BLOCKER__090__M__1": "Olduğun yerde kal!",
"VO__AMICIA__CH15__CHATTER__BREACH__010__M__1": "Ne?!... GEDİK!",
"VO__AMICIA__CH15__CHATTER__BREACH__030__M__1": "Müdahale etmemize... izin vermeyecekler...",
"VO__AMICIA__CH15__CHATTER__COUNT_CHARGING__030__M__1": "Bitti!",
"VO__AMICIA__CH15__CHATTER__DUEL_1__005__M__1": "Kardeşimi nereye götürdün?!",
"VO__AMICIA__CH15__CHATTER__DUEL_IDLE_2__020__M__1": "Onu kendi yalanlarınla mahvettin!",
"VO__AMICIA__CH15__CHATTER__DUEL_IDLE_4__020__M__1": "Arnaud!",
"VO__AMICIA__CH15__CHATTER__DUEL_IDLE_5__020__M__1": "Arnaud! Dayan!",
"VO__AMICIA__CH15__CHATTER__FIGHT_FOG_1__030__M__1": "Lanet aptallar! Bir kez olsun gerçekle yüzleşin! Son şansınız bu!",
"VO__AMICIA__CH15__CHATTER__FIGHT_FOG_3__020__M__1": "Kardeşimi geri vermezsen hiçbir şeyin olmayacak!",
"VO__AMICIA__CH15__CHATTER__FIGHT_NOFOG_2__015__M__1": "Ah, vereceğim! Ama önce senin işini bitireceğim!",
"VO__AMICIA__CH15__CHATTER__FIGHT_NOFOG_6__030__M__1": "O benim KARDEŞİM!",
"VO__AMICIA__CH15__CHATTER__FIRE_OK__010__M__1": "Sanırım gidebiliriz!",
"VO__AMICIA__CH15__CHATTER__FIRE_WAITING__010__M__1": "Hadi, hadi!",
"VO__AMICIA__CH15__CHATTER__GATE_BARRICADE__010__M__1": "Marsilya!",
"VO__AMICIA__CH15__CHATTER__HEART_BEATS__020__M__1": "Evet! Bu o!",
"VO__AMICIA__CH15__CHATTER__LOSING_TIME__010__M__1": "Vakit kaybediyoruz, Arnaud! Hugo'yu bulmalıyız... Hugo daha...",
"VO__AMICIA__CH15__CHATTER__LUCAS_CALL__020__M__1": "Biliyorum! Elimizden geleni yapıyoruz!",
"VO__AMICIA__CH15__CHATTER__LUCAS_SOPHIA__020__M__1": "Lucas! Yaralı mısın?!",
"VO__AMICIA__CH15__CHATTER__LUCAS_SOPHIA__040__M__1": "Seni buradan çıkaracağız!",
"VO__AMICIA__CH15__CHATTER__RASCASSE_WRECK__010__M__1": "Sophia ve Lucas?!",
"VO__AMICIA__CH15__CHATTER__RASCASSE_WRECK__040__M__1": "Hayatta olduklarına çok sevindim...",
"VO__AMICIA__CH15__CHATTER__RATS_BEHIND__015__M__1": "Evet!",
"VO__AMICIA__CH15__CHATTER__RATS_BEHIND__070__M__1": "Çok geç! Olabildiğince uzağa...",
"VO__AMICIA__CH15__CHATTER__RATS_BEHIND__080__M__1": "Olamaz... Hayır!",
"VO__AMICIA__CH15__CHATTER__RATS_CHASE_TURNING__020__M__1": "Kahretsin... ya!",
"VO__AMICIA__CH15__CHATTER__RATS_CLOSING_IN__010__M__1": "Şimdilik! Ama fazlasıyla çoklar!",
"VO__AMICIA__CH15__CHATTER__RATS_KEEP_COMING__010__M__1": "Durmuyorlar!",
"VO__AMICIA__CH15__CHATTER__RATS_LEFT__015__M__1": "Daha hızlı, Sophia! DAHA HIZLI!",
"VO__AMICIA__CH15__CHATTER__RATS_LEFT__030__M__1": "Yeterince hızlı gitmiyoruz!",
"VO__AMICIA__CH15__CHATTER__RATS_LEFTSIDE__020__M__1": "GERİ... DURUN!",
"VO__AMICIA__CH15__CHATTER__RATS_TUNNEL__045__M__1": "Dayan... dayan... DAYAN!",
"VO__AMICIA__CH15__CHATTER__RATS_TUNNEL__062__M__1": "Öyle görünüyor!",
"VO__AMICIA__CH15__CHATTER__RUMBLE__020__M__1": "Sanki... bir kalp atışı gibi... onun kalbi... onlara komuta ediyor...",
"VO__AMICIA__CH15__CHATTER__RUMBLE__040__M__1": "Demek böyle başlıyor...",
"VO__AMICIA__CH15__CHATTER__RUMBLE__060__M__1": "Cezamız!",
"VO__AMICIA__CH15__CHATTER__SOPHIA_PUSH__010__M__1": "Kapın nerede, Sophia?!",
"VO__AMICIA__CH15__CHATTER__SQUEEZE_THROUGH__020__M__1": "Evet. Sanırım... iksirin etki etmeye başlıyor.",
"VO__AMICIA__CH15__CHATTER__SQUEEZE_THROUGH__040__M__1": "Bunu kazanamazdın, Arnaud.",
"VO__AMICIA__CH15__CHATTER__START_CART__007__M__1": "Hayır... Yapabilirdim...",
"VO__AMICIA__CH15__CHATTER__START_CART__030__M__1": "Kont'un ölümü...",
"VO__AMICIA__CH15__CHATTER__START_CART__050__M__1": "Evet... Evet, bizim için canını verdi. Boşa gitmesine izin vermeyeceğim! Şimdi Hugo'nun nerede olduğunu öğrenmemiz gerek!",
"VO__AMICIA__CH15__CHATTER__START_CART__070__M__1": "Nasıl bilebiliriz... hâlâ hayatta olduğunu?",
"VO__AMICIA__CH15__CHATTER__USE_FIRE__020__M__1": "Evet! Kont, Düzen'in yaptığı bazı arabaları ele geçirmiş!",
"VO__AMICIA__CH15__CHATTER__USE_FIRE__025__M__1": "Gidelim, Sophia!",
"VO__AMICIA__CH15__RTC__820_STILL_ALIVE__010__M__1": "Kahrol, seni domuz!",
"VO__AMICIA__CH15__RTC__820_STILL_ALIVE__040__M__1": "Hugo...",
"VO__AMICIA__CH15__RTC__820_STILL_ALIVE__070__M__1": "Onu geri almamız gerek. Kont, Hugo'nun neler yapabileceğini biliyor. Onlara ulaşmalıyız, daha o...",
"VO__AMICIA__CH15__RTC__820_STILL_ALIVE__080__M__1": "...ona daha fazla zarar vermeden.",
"VO__AMICIA__CH15__RTC__820_STILL_ALIVE__110__M__1": "Kahretsin.",
"VO__AMICIA__CH15__RTC__825_UNFINISHED_DUEL__010__M__1": "Mahvolmuş... Bir daha asla yelken açamaz.",
"VO__AMICIA__CH15__RTC__825_UNFINISHED_DUEL__040__M__1": "Teşekkürler.",
"VO__AMICIA__CH15__RTC__825_UNFINISHED_DUEL__070__M__1": "Hayır...",
"VO__AMICIA__CH15__RTC__825_UNFINISHED_DUEL__090__M__1": "Kardeşim nerede, seni alçak?!",
"VO__AMICIA__CH15__RTC__825_UNFINISHED_DUEL__114__M__1": "Alçak...",
"VO__AMICIA__CH15__RTC__825_UNFINISHED_DUEL__120__M__1": "Hayatta olmaz!",
"VO__AMICIA__CH15__RTC__825_UNFINISHED_DUEL__124__M__1": "Neden?! İntikamını alabilesin diye mi?!",
"VO__AMICIA__CH15__RTC__830_NEBULA__220__M__1": "Öldüğümü sanıyor.",
"VO__AMICIA__CH15__RTC__830_NEBULA__235__M__1": "Kendini Macula'ya teslim etmiş...",
"VO__AMICIA__CH15__RTC__830_NEBULA__260__M__1": "Gözünü aç! ÇOK GEÇ! Artık herkes ölecek! Ve o... o...",
"VO__AMICIA__CH15__RTC__830_NEBULA__270__M__1": "Arnaud! Hemen gitmeliyiz!",
"VO__AMICIA__CH15__RTC__840_REVENGE__010__M__1": "ARNAUD!",
"VO__AMICIA__CH15__RTC__840_REVENGE__105__M__1": "Ne yapabilirim?",
"VO__AMICIA__CH15__RTC__840_REVENGE__130__M__1": "Üzgünüm... Ben...",
"VO__AMICIA__CH15__RTC__840_REVENGE__140__M__1": "Lütfen, yapma... Hayır...",
"VO__AMICIA__CH15__RTC__840_REVENGE__160__M__1": "Biliyorum...",
"VO__AMICIA__CH15__RTC__840_REVENGE__200__M__1": "Hâlâ vaktimiz var mı?",
"VO__AMICIA__CH15__RTC__850_FIRE__040__M__1": "Hugo...",
"VO__AMICIA__CH15__RTC__850_FIRE__090__M__1": "Sophia!",
"VO__AMICIA__CH15__RTC__850_FIRE__150__M__1": "Kim yaralı?",
"VO__AMICIA__CH15__RTC__850_FIRE__170__M__1": "Marsilya'ya hiç gitmedim.",
"VO__AMICIA__CH15__RTC__850_FIRE__190__M__1": "Hadi kardeşimi bulalım.",
"VO__ARNAUD__CH15__CHATTER__ABOUT_COUNT__020__M__1": "Kalbini kırdın, o yüzden artık savaş istiyor. Kardeşini kullanacağını söyledi... fethetmek için.",
"VO__ARNAUD__CH15__CHATTER__ABOUT_COUNT__040__M__1": "Biliyorum.",
"VO__ARNAUD__CH15__CHATTER__COUNT_ARNAUD_IDLE__020__M__1": "Senin asla olamayacağın kadar iyi adamlardı onlar!",
"VO__ARNAUD__CH15__CHATTER__COUNT_CHARGING__020__M__1": "Yap Amicia!",
"VO__ARNAUD__CH15__CHATTER__DUEL_1__010__M__1": "Cevap ver de belki sana çabuk bir ölüm bahşederim! Çocuk nerede!",
"VO__ARNAUD__CH15__CHATTER__DUEL_2__010__M__1": "Onun adını ağzına alma! Kanı SENİN ellerinde!",
"VO__ARNAUD__CH15__CHATTER__DUEL_2__030__M__1": "Bizi düşmana terk ettin! Ama şimdi kendini affettirebilirsin! Soylu bir emir ver! Bu çılgınlığa son ver ve çocuğu bırak!",
"VO__ARNAUD__CH15__CHATTER__DUEL_IDLE_3__010__M__1": "Seni öldürmeyi öyle çok isterdim ki... ama Hugo'yu nereye sakladığını söyleyecek kadarını sağ bırakacağım...",
"VO__ARNAUD__CH15__CHATTER__DUEL_IDLE_4__030__M__1": "Beni merak etme! Bir şey olmaz!",
"VO__ARNAUD__CH15__CHATTER__DUEL_IDLE_5__030__M__1": "İcabına bakarım. Cehennemi yaşat onlara!...",
"VO__ARNAUD__CH15__CHATTER__DUEL_INTERRUPT_1__010__M__1": "Ona zarar veremezsin! Onu bana bırak!",
"VO__ARNAUD__CH15__CHATTER__DUEL_INTERRUPT_2__010__M__1": "Yapma! Onun icabına bakabileceğimi söyledim sana!",
"VO__ARNAUD__CH15__CHATTER__FIGHT_FOG_2__030__M__1": "Sizi kurtarmaya çalışıyor, sizi gerizekâlılar!",
"VO__ARNAUD__CH15__CHATTER__FIGHT_NOFOG_3__025__M__1": "Yık geç onları, kızım! Onlardan daha sağlamsın!",
"VO__ARNAUD__CH15__CHATTER__FIGHT_NOFOG_6__040__M__1": "Konuş! Nerede o?!",
"VO__ARNAUD__CH15__CHATTER__FIRST_STEPS__020__M__1": "Dayan. Birazdan etkisini gösterir.",
"VO__ARNAUD__CH15__CHATTER__LOSING_TIME__020__M__1": "Saçmalamayı kes, Victor! Nerede o?!",
"VO__ARNAUD__CH15__CHATTER__LOSING_TIME__040__M__1": "Yanlış! Kurtarabileceğimi kurtarmak istiyorum!",
"VO__ARNAUD__CH15__CHATTER__LUCAS_SOPHIA__060__M__1": "Seni aptal alçak! Çocuğa ne yaptın?",
"VO__ARNAUD__CH15__CHATTER__RASCASSE_WRECK__020__M__1": "Sarsılmış ama iyi...",
"VO__ARNAUD__CH15__CHATTER__RASCASSE_WRECK__030__M__1": "Çocuk... yaranı temizleyen oydu. İyi biri... Erzak bulmak için enkaza gittiler.",
"VO__ARNAUD__CH15__CHATTER__RASCASSE_WRECK__050__M__1": "Seni görünce sevinirler.",
"VO__ARNAUD__CH15__CHATTER__SQUEEZE_THROUGH__005__M__1": "Buradan, gel...",
"VO__ARNAUD__CH15__CHATTER__SQUEEZE_THROUGH__010__M__1": "Yavaş ol... Sakın o yarayı yeniden açma.",
"VO__ARNAUD__CH15__CHATTER__SQUEEZE_THROUGH__030__M__1": "O alçak Kont'u öldürebilecekken, düşünsene...",
"VO__ARNAUD__CH15__RTC__820_STILL_ALIVE__020__M__1": "Şşş! Bağırmayı kes!",
"VO__ARNAUD__CH15__RTC__820_STILL_ALIVE__030__M__1": "Acı için... Savaş meydanında kullanırız bunu.",
"VO__ARNAUD__CH15__RTC__820_STILL_ALIVE__050__M__1": "Ben... Üzgünüm... Sıkışmıştım.",
"VO__ARNAUD__CH15__RTC__820_STILL_ALIVE__060__M__1": "Bizi çekip çıkarmam gerekti, yoksa ölmüştük.",
"VO__ARNAUD__CH15__RTC__820_STILL_ALIVE__090__M__1": "Gidelim. Sophia ve Lucas önden gitti, at arıyorlar.",
"VO__ARNAUD__CH15__RTC__820_STILL_ALIVE__100__M__1": "Dişini sık.",
"VO__ARNAUD__CH15__RTC__820_STILL_ALIVE__120__M__1": "Evet...",
"VO__ARNAUD__CH15__RTC__825_UNFINISHED_DUEL__020__M__1": "Tekneler gelir geçer... ama Sophia'yı ayakta tutan denizdir.",
"VO__ARNAUD__CH15__RTC__825_UNFINISHED_DUEL__030__M__1": "Ne demek istediğimi biliyorsun... Senin için önemli olana odaklan... çünkü o gidince...",
"VO__ARNAUD__CH15__RTC__825_UNFINISHED_DUEL__050__M__1": "Onu geri alacağız.",
"VO__ARNAUD__CH15__RTC__825_UNFINISHED_DUEL__118__M__1": "Onun icabına ben bakarım.",
"VO__ARNAUD__CH15__RTC__825_UNFINISHED_DUEL__122__M__1": "Bir kez olsun beni dinle, seni inatçı katır!",
"VO__ARNAUD__CH15__RTC__825_UNFINISHED_DUEL__126__M__1": "SEN kardeşini kurtarabilesin diye. Ben ona Hugo'nun yerini söyletirim.",
"VO__ARNAUD__CH15__RTC__825_UNFINISHED_DUEL__130__M__1": "Arkamı kolla ve hayatta kal.",
"VO__ARNAUD__CH15__RTC__830_NEBULA__210__M__1": "Hugo...",
"VO__ARNAUD__CH15__RTC__830_NEBULA__230__M__1": "Marsilya...",
"VO__ARNAUD__CH15__RTC__830_NEBULA__240__M__1": "O lanet adanın başına gelenlerden sonra çocuğu Marsilya'ya mı götürdün?!",
"VO__ARNAUD__CH15__RTC__840_REVENGE__070__M__1": "Ve sen de feci aptalsın.",
"VO__ARNAUD__CH15__RTC__840_REVENGE__080__M__1": "AMICIA! O SENİN!",
"VO__ARNAUD__CH15__RTC__840_REVENGE__120__M__1": "Bağırmayı kesebilirsin.",
"VO__ARNAUD__CH15__RTC__840_REVENGE__145__M__1": "Tam zamanı. Ve bana epey güzel bir son koşu yaşattın.",
"VO__ARNAUD__CH15__RTC__840_REVENGE__155__M__1": "Harika bir çocuk. Ve sen... Sen...",
"VO__COUNT__CH15__CHATTER__COUNT_ARNAUD_IDLE__010__M__1": "Tekniğin özensiz! Ayaktakımıyla idman ederek çok vakit harcamışsın!",
"VO__COUNT__CH15__CHATTER__COUNT_CHARGING__010__M__1": "Şimdi sıra sende! Sonra... geri kalan herkes!",
"VO__COUNT__CH15__CHATTER__DUEL_1__020__M__1": "Uzlaşma zamanı Emilie'yle birlikte bitti! Şimdi öleceksin!",
"VO__COUNT__CH15__CHATTER__DUEL_2__005__M__1": "Neden bu cadıyla silaha sarılıyorsun, Arnaud?! Oğlunun bıraktığı boşluğu doldurmak için mi?",
"VO__COUNT__CH15__CHATTER__DUEL_2__020__M__1": "Savaştı bu!",
"VO__COUNT__CH15__CHATTER__DUEL_2__040__M__1": "Bu dünyayı döndüren çılgınlıktır! Ama ben onu kendi yöntemimle düzelteceğim!",
"VO__COUNT__CH15__CHATTER__DUEL_IDLE_1__010__M__1": "Emilie öldü! Bu dünyaya verilen tek şanstı o! Şimdi ya hepiniz önümde diz çökeceksiniz ya da öleceksiniz!",
"VO__COUNT__CH15__CHATTER__DUEL_IDLE_2__010__M__1": "Barış zamanıydı! Ama her şeyi mahvetmek zorundaydın! Sahip olduğum her şeyi!",
"VO__COUNT__CH15__CHATTER__DUEL_IDLE_3__020__M__1": "Ne kadar emin...",
"VO__COUNT__CH15__CHATTER__DUEL_IDLE_4__010__M__1": "Ne oldu?! Kılıcın ağırlaşıyor mu?!",
"VO__COUNT__CH15__CHATTER__DUEL_IDLE_5__010__M__1": "Şu hâline bak! Pes et artık!",
"VO__COUNT__CH15__CHATTER__DUEL_INTERRUPT_1__020__M__1": "İşte böyle! Köpeğini geri çağır!",
"VO__COUNT__CH15__CHATTER__DUEL_INTERRUPT_2__020__M__1": "İkiniz de yapamazsınız! Ben yarının kılıcıyım! Daha aydınlık bir geleceğin meşalesi!",
"VO__COUNT__CH15__CHATTER__FIGHT_FOG_2__020__M__1": "Hayır! Bunu bitiriyoruz! Öldürün şu kızı!",
"VO__COUNT__CH15__CHATTER__FIGHT_NOFOG_3__005__M__1": "Bitirin onu, Tanrı aşkına!",
"VO__COUNT__CH15__CHATTER__FIGHT_NOFOG_6__020__M__1": "Onu küçümsemeyin! Çocuğun üzerinde gücü vardı!",
"VO__COUNT__CH15__CHATTER__FIGHT_NOFOG_6__050__M__1": "Ölü bir adamla neden konuşayım ki?!",
"VO__COUNT__CH15__CHATTER__LOSING_TIME__030__M__1": "Onu umursamıyorsun! Sadece beni öldürmek istiyorsun!",
"VO__COUNT__CH15__CHATTER__LUCAS_SOPHIA__050__M__1": "Hiçbir yere gidemezsin!",
"VO__COUNT__CH15__CHATTER__LUCAS_SOPHIA__070__M__1": "O artık benim oğlum... Kutsal silahım!",
"VO__COUNT__CH15__RTC__825_UNFINISHED_DUEL__060__M__1": "Gerçek bir şövalyenin sözleri, Arnaud.",
"VO__COUNT__CH15__RTC__825_UNFINISHED_DUEL__080__M__1": "Cidden, senin gibisini hiç görmedim...",
"VO__COUNT__CH15__RTC__825_UNFINISHED_DUEL__100__M__1": "Güvenle benim elimde! Hizmete hazır olana dek!",
"VO__COUNT__CH15__RTC__825_UNFINISHED_DUEL__110__M__1": "Senin kelleni bir bez içinde görüp bu eski dünyanın yanması gerektiğini anlayana dek.",
"VO__COUNT__CH15__RTC__825_UNFINISHED_DUEL__140__M__1": "Bununla ben ilgilenirim. Öldürün şu kızı!",
"VO__COUNT__CH15__RTC__830_NEBULA__250__M__1": "Kes sesini! Ben hallederim onu.",
"VO__COUNT__CH15__RTC__830_NEBULA__280__M__1": "Hiçbir yere gitmiyorsun!",
"VO__COUNT__CH15__RTC__830_NEBULA__300__M__1": "Hayır! Öldürün şu kızı!",
"VO__COUNT__CH15__RTC__840_REVENGE__060__M__1": "İşte bu kadar. Çok yaşlısın, Arnaud. Savaşamayacak kadar yaşlı.",
"VO__KID_F1__CH15__CHATTER__SPECTATORS_3__020__M__1": "Anneciğim!",
"VO__KID_M1__CH15__CHATTER__REFUGEES__035__M__1": "Anneciğim! Geri dönüp annemi bulmamız lazım!",
"VO__KID_M1__CH15__CHATTER__SPECTATORS_1__030__M__1": "Korkuyorum! Annem nerede?!",
"VO__KID_M2__CH15__CHATTER__SPECTATORS_4__020__M__1": "Evet!",
"VO__LUCAS__CH15__CHATTER__BLOCKER__020__M__1": "Ne yapacağız?!",
"VO__LUCAS__CH15__CHATTER__BLOCKER__060__M__1": "Nasıl çalıştığını biliyor musun?!",
"VO__LUCAS__CH15__CHATTER__BREACH__015__M__1": "Sür, Sophia, SÜR!",
"VO__LUCAS__CH15__CHATTER__FIRE_WAITING__030__M__1": "Şimdi onu düşünme...",
"VO__LUCAS__CH15__CHATTER__GATE_BARRICADE__050__M__1": "Çünkü o gürültü... öbür taraftan geliyor...",
"VO__LUCAS__CH15__CHATTER__HEART_BEATS__030__M__1": "Ama iyiye işaret olduğunu sanmıyorum...",
"VO__LUCAS__CH15__CHATTER__LUCAS_CALL__010__M__1": "Amicia! Bu kötü! Hugo'ya çabuk ulaşmalıyız!",
"VO__LUCAS__CH15__CHATTER__LUCAS_SOPHIA__010__M__1": "Amicia! Arnaud! Geliyorlar!",
"VO__LUCAS__CH15__CHATTER__LUCAS_SOPHIA__015__M__1": "Dikkat, buradalar!",
"VO__LUCAS__CH15__CHATTER__RATS_BEHIND__010__M__1": "Şimdi kullan!",
"VO__LUCAS__CH15__CHATTER__RATS_BIG__010__M__1": "Hepsi burada... Bu gerçekten son...",
"VO__LUCAS__CH15__CHATTER__RATS_CLOSE__010__M__1": "Fazlasıyla yakın!",
"VO__LUCAS__CH15__CHATTER__RATS_KEEP_COMING__010__M__1": "Ah... Aman Tanrım...",
"VO__LUCAS__CH15__CHATTER__RATS_LEFT__013__M__1": "Hayır!",
"VO__LUCAS__CH15__CHATTER__RATS_LEFTSIDE__030__M__1": "İşe yarıyor!",
"VO__LUCAS__CH15__CHATTER__RATS_TUNNEL__030__M__1": "Umarım öyledir!",
"VO__LUCAS__CH15__CHATTER__RATS_TUNNEL__040__M__1": "Lütfen, lütfen... yavaşlayın!",
"VO__LUCAS__CH15__CHATTER__RATS_TUNNEL__050__M__1": "Dayandı!",
"VO__LUCAS__CH15__CHATTER__REFUGEES__010__M__1": "Ne?! Ne oldu?!",
"VO__LUCAS__CH15__CHATTER__REFUGEES__028__M__1": "Bu... Macula'nın... son ezgisi...",
"VO__LUCAS__CH15__CHATTER__RUMBLE__010__M__1": "Bu sarsıntılar yerden gelmiyor!",
"VO__LUCAS__CH15__CHATTER__RUMBLE__030__M__1": "Kaç tane olduğunu hayal edebiliyor musun...?",
"VO__LUCAS__CH15__CHATTER__START_CART__002__M__1": "Marsilya'ya ne kadar uzaktayız?!",
"VO__LUCAS__CH15__CHATTER__START_CART__010__M__1": "Yapamazdın... Hâlâ nasıl ayakta durduğunu bile bilmiyorum!",
"VO__LUCAS__CH15__CHATTER__START_CART__060__M__1": "Nebula'nın patlaması muhtemelen izler bırakmıştır... Orada her ne oluyorsa, Hugo onun merkezinde olmalı.",
"VO__LUCAS__CH15__CHATTER__START_CART__080__M__1": "İşaretler olacaktır... umarım...",
"VO__LUCAS__CH15__CHATTER__USE_FIRE__010__M__1": "Vay! Bu... Rum ateşi mi?!",
"VO__LUCAS__CH15__RTC__840_REVENGE__170__M__1": "“Güneşi öldürecek”... Nebula...",
"VO__LUCAS__CH15__RTC__840_REVENGE__190__M__1": "Her yerde. Sıçanlar önüne geçilmeden yayılacak. Bu, onun hükmü.",
"VO__LUCAS__CH15__RTC__840_REVENGE__210__M__1": "Önemi var mı? Hadi gidelim.",
"VO__LUCAS__CH15__RTC__850_FIRE__165__M__1": "Geldik.",
"VO__PEOPLE_F1__CH15__CHATTER__SPECTATORS_1__020__M__1": "Yerden geliyor!",
"VO__PEOPLE_F2__CH15__CHATTER__REFUGEES__005__M__1": "Kaçın! Şehirde korkunç bir şey oldu!",
"VO__PEOPLE_F2__CH15__CHATTER__SPECTATORS_2__020__M__1": "Sanki... cehennemin dibinden geliyor...",
"VO__PEOPLE_F2__CH15__CHATTER__SPECTATORS_3__030__M__1": "Yeter! Çocukları daha da korkutuyorsun!",
"VO__PEOPLE_F3__CH15__CHATTER__REFUGEES__050__M__1": "Yapamıyorum... Bacağım...",
"VO__PEOPLE_F3__CH15__CHATTER__SPECTATORS_4__010__M__1": "Hemen gidiyoruz! Git ninenı bul! Ve eski battaniyeyi al!",
"VO__PEOPLE_F4__CH15__CHATTER__GATE_BARRICADE__080__M__1": "Ya hâlâ içeride olanlar?!",
"VO__PEOPLE_F4__CH15__CHATTER__REFUGEES__045__M__1": "Kalk! Lütfen kalk!",
"VO__PEOPLE_F4__CH15__CHATTER__REFUGEES__060__M__1": "Kalkmalısın! Seni burada bırakmayacağım!",
"VO__PEOPLE_F5__CH15__CHATTER__GATE_BARRICADE__090__M__1": "Onlar zaten öldü! Devam et!",
"VO__PEOPLE_F5__CH15__CHATTER__REFUGEES__015__M__1": "O tarafa gitme! Tepelere kaç!",
"VO__PEOPLE_F5__CH15__CHATTER__REFUGEES__025__M__1": "Cehennemin kapıları açıldı! Marsilya kayıp!",
"VO__PEOPLE_M1__CH15__CHATTER__REFUGEES__017__M__1": "Hayır! Hayır, deniz! Küçük bir tekne bulalım!",
"VO__PEOPLE_M1__CH15__CHATTER__SPECTATORS_1__010__M__1": "Bu ses de ne?! Şehirden mi... geliyor?!",
"VO__PEOPLE_M2__CH15__CHATTER__REFUGEES__040__M__1": "Çok geç!",
"VO__PEOPLE_M2__CH15__CHATTER__SPECTATORS_2__010__M__1": "Hava leş gibi kokuyor...",
"VO__PEOPLE_M2__CH15__CHATTER__SPECTATORS_3__010__M__1": "Kıyamet günü! Kıyamet günü bu! Hepimizin sonu geldi!",
"VO__PEOPLE_M3__CH15__CHATTER__REFUGEES__030__M__1": "Yer yarılıp bizi yutacak!",
"VO__PEOPLE_M3__CH15__CHATTER__SPECTATORS_2__030__M__1": "Muhafızlar nerede?! Buraya asker lazım!",
"VO__PEOPLE_M4__CH15__CHATTER__GATE_BARRICADE__020__M__1": "Yardım için daha çok insan lazım!",
"VO__PEOPLE_M4__CH15__CHATTER__SPECTATORS_1__035__M__1": "Onu bulup gitmemiz gerek...",
"VO__PEOPLE_M5__CH15__CHATTER__GATE_BARRICADE__030__M__1": "Dayanacağına emin misin?!",
"VO__SOLDIER_B1__CH15__CHATTER__FIGHT_FOG_1__010__M__1": "O lanet şey de ne?!",
"VO__SOLDIER_B1__CH15__CHATTER__FIGHT_FOG_2__010__M__1": "Efendim! Hemen tahliye etmeliyiz!",
"VO__SOLDIER_B1__CH15__CHATTER__FIGHT_FOG_3__010__M__1": "Sen nasıl hâlâ hayattasın?! Adamızı yok ettin! Aydınlık Günler'i çaldın bizden!",
"VO__SOLDIER_B1__CH15__CHATTER__FIGHT_NOFOG_6__010__M__1": "O cadıyı kendi ellerimle geberteceğim!",
"VO__SOLDIER_N1__CH15__CHATTER__FIGHT_NOFOG_4__010__M__1": "Kontesimizin intikamını alacağım! Ve katlettiğin tüm masumların!",
"VO__SOLDIER_N3__CH15__CHATTER__FIGHT_FOG_1__020__M__1": "Büyü bu! Üzerimize büyü yaptı! Çabuk öldürün onu!",
"VO__SOLDIER_S1__CH15__CHATTER__FIGHT_FOG_IDLE_1__010__M__1": "İmanım kolumu yönetsin! Bizi aydınlık günlere götürsün!",
"VO__SOLDIER_S1__CH15__CHATTER__FIGHT_NOFOG_1__010__M__1": "Yanınızdayım, lordum! Takviye geliyor!",
"VO__SOLDIER_S1__CH15__CHATTER__FIGHT_NOFOG_3__010__M__1": "Yapacağım! Hemen!",
"VO__SOLDIER_S1__CH15__CHATTER__FIGHT_NOFOG_5__010__M__1": "Senin kirli kanın bu toprağı sulayacak!",
"VO__SOLDIER_S1__CH15__CHATTER__FIGHT_NOFOG_IDLE_1__010__M__1": "Çocuk hepimizi kurtaracak!",
"VO__SOLDIER_S1__CH15__RTC__830_NEBULA__290__M__1": "Efendim! Tahliye etmeliyiz!",
"VO__SOLDIER_S2__CH15__CHATTER__FIGHT_NOFOG_2__010__M__1": "Çocuk artık bizimle! Şeytani işini bitiremeyeceksin, Kirletici!",
"VO__SOPHIA__CH15__CHATTER__BLOCKER__030__M__1": "İleride başka bir kapı var, ama şu saman yolu kapatıyor!",
"VO__SOPHIA__CH15__CHATTER__BLOCKER__080__M__1": "Hadi o zaman!",
"VO__SOPHIA__CH15__CHATTER__BREACH__020__M__1": "Bunların nesi var, kahretsin?!",
"VO__SOPHIA__CH15__CHATTER__FIRE_WAITING__020__M__1": "Demek bu duvarların... ardına gidiyoruz...",
"VO__SOPHIA__CH15__CHATTER__GATE_BARRICADE__040__M__1": "Kapıyı barikatla kapatıyorlar! Neden?!",
"VO__SOPHIA__CH15__CHATTER__HEART_BEATS__010__M__1": "Vay... Bu tür... bir işaret mi?",
"VO__SOPHIA__CH15__CHATTER__LUCAS_CALL__030__M__1": "Onu sıkıştırma! Hayatta kal, Amicia!",
"VO__SOPHIA__CH15__CHATTER__LUCAS_SOPHIA__030__M__1": "Hayır, ama kımıldayamıyoruz! Sadece hayatta kal!",
"VO__SOPHIA__CH15__CHATTER__RATS_BEHIND__060__M__1": "Kapıyı görüyorum!",
"VO__SOPHIA__CH15__CHATTER__RATS_CHASE_TURNING__010__M__1": "Viraj! Tutun!",
"VO__SOPHIA__CH15__CHATTER__RATS_LEFT__010__M__1": "Bu da ne?!",
"VO__SOPHIA__CH15__CHATTER__RATS_LEFT__020__M__1": "Deh! DEH!",
"VO__SOPHIA__CH15__CHATTER__RATS_LEFT__040__M__1": "Atlar daha hızlı gidemez!",
"VO__SOPHIA__CH15__CHATTER__RATS_TUNNEL__025__M__1": "Su kemeri! Onları yavaşlatabilir!",
"VO__SOPHIA__CH15__CHATTER__RATS_TUNNEL__060__M__1": "Bizi kovalamayı bıraktılar mı?!",
"VO__SOPHIA__CH15__CHATTER__REFUGEES__020__M__1": "Bu lanet gürültü de ne?!",
"VO__SOPHIA__CH15__CHATTER__RUMBLE__015__M__1": "Hayır! Şehir surlarından geliyorlar!",
"VO__SOPHIA__CH15__CHATTER__RUMBLE__050__M__1": "Ne?!",
"VO__SOPHIA__CH15__CHATTER__SOPHIA_PUSH__020__M__1": "Bilmiyorum ama durmayacağım!",
"VO__SOPHIA__CH15__CHATTER__START_CART__003__M__1": "Çok uzak değil, derim!",
"VO__SOPHIA__CH15__CHATTER__START_CART__005__M__1": "Amicia... İyi misin?",
"VO__SOPHIA__CH15__CHATTER__START_CART__020__M__1": "Elinden geleni yaptın, ve o bunu biliyordu, Amicia! Üstelik ona en çok ihtiyaç duyduğu şeyi verdin!",
"VO__SOPHIA__CH15__CHATTER__START_CART__040__M__1": "Hayır! İlgileneceği birini! Gerçek bir amaç!",
"VO__SOPHIA__CH15__CHATTER__START_CART__055__M__1": "Sorun da bu! Marsilya kocaman bir şehir!",
"VO__SOPHIA__CH15__CHATTER__USE_FIRE__030__M__1": "Yine başlıyoruz!",
"VO__SOPHIA__CH15__HELPER__USE_FIRE_EXPLODE_1__010__M__1": "Amicia! Şu samanı yoldan çekmeliyiz!",
"VO__SOPHIA__CH15__HELPER__USE_FIRE_EXPLODE_2__010__M__1": "Şu topu kullanacak mısın, kullanmayacak mısın?!",
"VO__SOPHIA__CH15__RTC__840_REVENGE__080__M__1": "Arnaud!",
"VO__SOPHIA__CH15__RTC__840_REVENGE__081__M__1": "Hayır!",
"VO__SOPHIA__CH15__RTC__840_REVENGE__180__M__1": "Başardın, seni aptal... Artık hepimiz sana borçluyuz.",
"VO__SOPHIA__CH15__RTC__840_REVENGE__220__M__1": "Yer aç, dizginleri ben alıyorum. Bir şey yapmam gerek.",
"VO__SOPHIA__CH15__RTC__850_FIRE__100__M__1": "BURAYA!",
"VO__SOPHIA__CH15__RTC__850_FIRE__160__M__1": "Kim değil ki?",
"VO__SOPHIA__CH15__RTC__850_FIRE__180__M__1": "Oh, en güzel mevsimde geldin.",
}
