# -*- coding: utf-8 -*-
# CH17 VO (epilog) - kaynak proper Turkce; build asamasinda SUB uygulanir.
# Amicia<->Sophia: yakin dost, sen. Carrier->Tasiyici, Protector->Koruyucu, Aelia/Macula korunur.
T = {
"VO__AMICIA__CH17__CHATTER__BACK_TO_SOPHIA__020__M__1": "Evet... Sadece... fikre alışmaya çalışıyorum...",
"VO__AMICIA__CH17__CHATTER__COMMITMENT__010__M__1": "Her şey yoluna girecek...",
"VO__AMICIA__CH17__CHATTER__DOOR__010__M__1": "Ha... Sıcaklığını özleyeceğim... sessiz geceleri... beni fırtınalardan nasıl koruduğunu... Ama bunu yapmam gerek.",
"VO__AMICIA__CH17__CHATTER__GOATS__010__M__1": "Pekâlâ, hanımlar... Gitmem gerek. Ziyaretlerinizden keyif aldım... Lütfen buraya göz kulak olun.",
"VO__AMICIA__CH17__CHATTER__INTRO__020__M__1": "Yürüyüş, evi onarmak... Kendimi yormaya çalışmak...",
"VO__AMICIA__CH17__CHATTER__INTRO__040__M__1": "Daha... iyi, evet.",
"VO__AMICIA__CH17__CHATTER__INTRO__060__M__1": "İyiyim, Sophia... Bir yıl oldu.",
"VO__AMICIA__CH17__CHATTER__LAST_STEPS_2__010__M__1": "Her şey yoluna girecek...",
"VO__AMICIA__CH17__CHATTER__LEDGE__010__M__1": "Hadi, neredeyse vardın...",
"VO__AMICIA__CH17__CHATTER__LETS_GO__010__M__1": "Pekâlâ, gidelim...",
"VO__AMICIA__CH17__CHATTER__LUCAS_DID_KILL__020__M__1": "Gelmeyecek... Onu hâlâ... bunu yaparken görebiliyorum.",
"VO__AMICIA__CH17__CHATTER__LUCAS_DID_KILL__040__M__1": "Her neyse, hâlâ yollarda bir yerdedir. Okuyor.",
"VO__AMICIA__CH17__CHATTER__LUCAS_DIDNT_KILL__020__M__1": "Lucas mı?... Ah, hayır... Hâlâ yollarda. Okuyor.",
"VO__AMICIA__CH17__CHATTER__LUCAS_DIDNT_KILL__040__M__1": "Buna ihtiyacı vardı...",
"VO__AMICIA__CH17__CHATTER__NO_GO_PATH__020__M__1": "Hâlâ... O yoldan gitmem gerek... Hadi. Mecbursun.",
"VO__AMICIA__CH17__CHATTER__NO_ONE__020__M__1": "Buna kıyasla deniz çok dümdüz görünecek...",
"VO__AMICIA__CH17__CHATTER__PROJECTIONS__020__M__1": "Henüz değil... Ama sanırım işaretlere rastladığımda anlayacağım...",
"VO__AMICIA__CH17__CHATTER__PROJECTIONS__070__M__1": "Evet. Şeylerin ve insanların üzerinde... izler bırakıyor. Sanırım... bir sonraki Taşıyıcı ve Koruyucu'nun nerede ortaya çıkacağını bulabilirim. Bir sonraki vebayı. Onlara yolu hazırlamak istiyorum, tıpkı Aelia'nın bizim için yaptığı gibi.",
"VO__AMICIA__CH17__CHATTER__PROJECTIONS__090__M__1": "Hiç!",
"VO__AMICIA__CH17__CHATTER__RUNNING__020__M__1": "Biraz hızlanalım.",
"VO__AMICIA__CH17__CHATTER__SENTIMENTAL_PART1__005__M__1": "Peki... işler nasıl gidiyor?",
"VO__AMICIA__CH17__CHATTER__SENTIMENTAL_PART1__020__M__1": "Ah! Ne oldu?",
"VO__AMICIA__CH17__CHATTER__SENTIMENTAL_PART1__040__M__1": "Gerçekten mi?",
"VO__AMICIA__CH17__CHATTER__SENTIMENTAL_PART2__060__M__1": "Harika. Harika...",
"VO__AMICIA__CH17__CHATTER__SMELLS_GOOD__020__M__1": "Evet... Özleyeceğim.",
"VO__AMICIA__CH17__CHATTER__SQUEEZE_THROUGH__010__M__1": "Benim... İçeri giriyorum...",
"VO__AMICIA__CH17__CHATTER__VISTA__010__M__1": "Huzur... Unutmamaya... çalışacağım...",
"VO__AMICIA__CH17__CHATTER__WATERFALL__010__M__1": "Ah... Bugün akış daha güçlü. Sabah yağmur yağdı...",
"VO__AMICIA__CH17__CHATTER__WATERFALL__015__M__1": "Lütfen, asla akmayı bırakma...",
"VO__AMICIA__CH17__CHATTER__WATERFALL__030__M__1": "Onlardan biri!",
"VO__AMICIA__CH17__RTC__A_VALLEY__020__M__1": "Sophia, gelmişsin!",
"VO__AMICIA__CH17__RTC__A_VALLEY__060__M__1": "Pekâlâ, o hâlde topraklarına hoş geldin, keçi.",
"VO__AMICIA__CH17__RTC__A_VALLEY__080__M__1": "Sanırım öyle...",
"VO__AMICIA__CH17__RTC__A_VALLEY__100__M__1": "Bekle!",
"VO__AMICIA__CH17__RTC__DEPARTURE__010__M__1": "Hey...",
"VO__AMICIA__CH17__RTC__DEPARTURE__020__M__1": "Eskiden buraya gelmezlerdi...",
"VO__AMICIA__CH17__RTC__DEPARTURE__030__M__1": "Dost edinmede iyi olacağını hep biliyordum.",
"VO__AMICIA__CH17__RTC__DEPARTURE__040__M__1": "Hazır olduğumdan emin değildim. Ama... Sophia burada.",
"VO__AMICIA__CH17__RTC__DEPARTURE__050__M__1": "Üzgünüm...",
"VO__AMICIA__CH17__RTC__DEPARTURE__060__M__1": "Neden bu kadar zor?",
"VO__AMICIA__CH17__RTC__DEPARTURE__070__M__1": "Hiç geri adım atmadık, değil mi?",
"VO__AMICIA__CH17__RTC__DEPARTURE__080__M__1": "Dayandık...",
"VO__AMICIA__CH17__RTC__DEPARTURE__090__M__1": "Bu toprak, onu ne kadar sevdiğini hatırlasın... Onu korumak için verdiğin her şeyi... hatırlasın.",
"VO__AMICIA__CH17__RTC__DEPARTURE__100__M__1": "Ben hatırlıyorum.",
"VO__AMICIA__CH17__RTC__DEPARTURE__110__M__1": "Ve unutulmasına izin vermeyeceğim.",
"VO__AMICIA__CH17__RTC__SOMETHING_TO_DO__020__M__1": "Merhaba...",
"VO__AMICIA__CH17__RTC__SOMETHING_TO_DO__030__M__1": "Bana biraz zaman verir misin? Yapmam gereken son bir şey var.",
"VO__AMICIA__CH17__RTC__SOMETHING_TO_DO__050__M__1": "Fırtına gelmiyor mu?",
"VO__AMICIA__CH17__RTC__SOMETHING_TO_DO__070__M__1": "Çok uzun sürmez.",
"VO__SOPHIA__CH17__CHATTER__BACK_TO_SOPHIA__010__M__1": "İyi... hissediyor musun?",
"VO__SOPHIA__CH17__CHATTER__BACK_TO_SOPHIA__030__M__1": "Yola koyulunca daha iyi hissedeceksin.",
"VO__SOPHIA__CH17__CHATTER__GETTING_THERE__010__M__1": "Geliyoruz neredeyse...",
"VO__SOPHIA__CH17__CHATTER__INTRO__010__M__1": "Atları yukarıda bıraktım... Peki... son aylarda neler yaptın?",
"VO__SOPHIA__CH17__CHATTER__INTRO__030__M__1": "İşe yarıyor mu?",
"VO__SOPHIA__CH17__CHATTER__INTRO__050__M__1": "Güzel. Beni epey endişelendirmiştin, biliyor musun...",
"VO__SOPHIA__CH17__CHATTER__INTRO__070__M__1": "Şimdiden mi...",
"VO__SOPHIA__CH17__CHATTER__LETS_GO__020__M__1": "Nasıl istersen!",
"VO__SOPHIA__CH17__CHATTER__LUCAS_DID_KILL__010__M__1": "Peki... Lucas?",
"VO__SOPHIA__CH17__CHATTER__LUCAS_DID_KILL__030__M__1": "Belki geçer... zamanla...",
"VO__SOPHIA__CH17__CHATTER__LUCAS_DID_KILL__050__M__1": "O çocuk...",
"VO__SOPHIA__CH17__CHATTER__LUCAS_DIDNT_KILL__010__M__1": "Bizim simyacı... geliyor mu?",
"VO__SOPHIA__CH17__CHATTER__LUCAS_DIDNT_KILL__030__M__1": "Tek başına... Ne çabuk büyüyorlar...",
"VO__SOPHIA__CH17__CHATTER__PROJECTIONS__010__M__1": "Peki, seni nereye çıkarabileceğimizi biliyor musun?",
"VO__SOPHIA__CH17__CHATTER__PROJECTIONS__050__M__1": "Macula'nın mı?",
"VO__SOPHIA__CH17__CHATTER__PROJECTIONS__080__M__1": "O hâlde sana sadece dinlen demenin bir anlamı yok, değil mi?",
"VO__SOPHIA__CH17__CHATTER__PROJECTIONS__100__M__1": "Peki.",
"VO__SOPHIA__CH17__CHATTER__RUNNING__010__M__1": "Hava soğuyor!",
"VO__SOPHIA__CH17__CHATTER__SENTIMENTAL_PART1__010__M__1": "İyi! Bu aralar daha çok yasal ticaret yapıyorum...",
"VO__SOPHIA__CH17__CHATTER__SENTIMENTAL_PART1__030__M__1": "Şey, sadece daha uzun yaşamak istiyorum.",
"VO__SOPHIA__CH17__CHATTER__SENTIMENTAL_PART1__050__M__1": "Sakin bir denizi fırtınaya yeğlerim... Hazır lafı açılmışken, yarın yola çıkıyoruz.",
"VO__SOPHIA__CH17__CHATTER__SMELLS_GOOD__010__M__1": "Ne güzel kokuyor... Ve şu sessizlik...",
"VO__SOPHIA__CH17__CHATTER__WAITING__010__M__1": "Hazır olunca söyle, veda etmek için... daha çok zaman lazımsa.",
"VO__SOPHIA__CH17__CHATTER__WATERFALL__020__M__1": "Burası en sevdiğin yer mi?",
"VO__SOPHIA__CH17__CHATTER__WATERFALL__040__M__1": "Nedenini anlıyorum!",
"VO__SOPHIA__CH17__RTC__A_VALLEY__010__M__1": "Her seferinde daha yüksek geliyor...",
"VO__SOPHIA__CH17__RTC__A_VALLEY__030__M__1": "Elbette!",
"VO__SOPHIA__CH17__RTC__A_VALLEY__040__M__1": "Bunu kaçırmazdım...",
"VO__SOPHIA__CH17__RTC__A_VALLEY__050__M__1": "Dikkat et, keçi gibi kokuyorum.",
"VO__SOPHIA__CH17__RTC__A_VALLEY__070__M__1": "Nasıl hissediyorsun? Hazır mısın?",
"VO__SOPHIA__CH17__RTC__A_VALLEY__090__M__1": "O hâlde vakit kaybetmenin anlamı yok.",
"VO__SOPHIA__CH17__RTC__SOMETHING_TO_DO__010__M__1": "Çocuklar, bu Amicia. Ona iyi davranın, özel bir gün bu.",
"VO__SOPHIA__CH17__RTC__SOMETHING_TO_DO__040__M__1": "İstediğin kadar al. Sırtım hâlâ yoldan ağrıyor.",
"VO__SOPHIA__CH17__RTC__SOMETHING_TO_DO__060__M__1": "Gördüğüm tek kişi sensin.",
}
