# -*- coding: utf-8 -*-
# CH02 VO bolum 1/2 (satir 1-720). onom/EMPTY atlanir.
# Sen/siz: kardesler+Lucas+Beatrice=sen; Amicia->Vaudin=siz, Vaudin->Amicia=sen(otorite);
# saticilar<->Amicia=siz; paralı askerler kendi aralarinda/tutsaga=kaba sen.
T = {
"VO__ALCHEMIST__CH02__RTC__100_AN_ALCHEMIST__020__M__1": "Kız...",
"VO__ALCHEMIST__CH02__RTC__100_AN_ALCHEMIST__040__M__1": "Aşağıdaki o kabaların neden bu kadar sessiz olduğunu açıklıyor bu... Düzen, Guyenne'de Engizisyon'u alt edişinden hayli etkilenmişti.",
"VO__ALCHEMIST__CH02__RTC__100_AN_ALCHEMIST__060__M__1": "Bir seçim değil, bir çağrı. Bir Taşıyıcı'nın Koruyucusu olmak.",
"VO__ALCHEMIST__CH02__RTC__100_AN_ALCHEMIST__073__M__1": "Bir koruyucu. Düzen içindeki görevin.",
"VO__ALCHEMIST__CH02__RTC__100_AN_ALCHEMIST__080__M__1": "Ya sen?",
"VO__ALCHEMIST__CH02__RTC__100_AN_ALCHEMIST__100__M__1": "Bir çırak. Magistran kendine bu unvanı yakıştırdığını biliyor mu?",
"VO__ALCHEMIST__CH02__RTC__100_AN_ALCHEMIST__120__M__1": "Alevini denetle, Koruyucu...",
"VO__ALCHEMIST__CH02__RTC__100_AN_ALCHEMIST__140__M__1": "Başkaları onun içinde yandı.",
"VO__ALCHEMIST__CH02__RTC__100_AN_ALCHEMIST__160__M__1": "Çantamı al. Gidip şu Taşıyıcı'yı görelim.",
"VO__ALCHEMIST__CH02__RTC__100_AN_ALCHEMIST__180__M__1": "Nerede o?",
"VO__ALCHEMIST__CH02__RTC__100_AN_ALCHEMIST__230__M__1": "Hemen başlamalıyız. Sessizlik gerekecek.",
"VO__AMICIA__CH02__CHATTER__2ND_CRANK__010__M__1": "Beni boş ver...",
"VO__AMICIA__CH02__CHATTER__2ND_CRANK__020__M__1": "Şimdi kranka... Şu asansörü indirip bu cehennemden çıkma vakti.",
"VO__AMICIA__CH02__CHATTER__2ND_CRANK_REACHED__050__M__1": "Lütfen, çalış... Lütfen...",
"VO__AMICIA__CH02__CHATTER__2ND_HAM_SPOT__010__M__1": "Bunu severler.",
"VO__AMICIA__CH02__CHATTER__2ND_LODGE_ALONE__010__M__1": "Yardım getireceğim Hugo... Şu Vaudin'i bulacağım... Ama dayanmalısın... Elimden geleni yapıyorum.",
"VO__AMICIA__CH02__CHATTER__2ND_SYMBOL__010__M__1": "Ah... hayır... Lütfen olmasın...",
"VO__AMICIA__CH02__CHATTER__2ND_SYMBOL__030__M__1": "Olamaz...",
"VO__AMICIA__CH02__CHATTER__ACROSS__020__M__1": "Sakin ol! Şimdilik iyisin!",
"VO__AMICIA__CH02__CHATTER__ACROSS__040__M__1": "Seni yarı yolda bırakmam, bunu biliyorsun!",
"VO__AMICIA__CH02__CHATTER__ACROSS_CLIMBING__010__M__1": "İyi gidiyorsun!",
"VO__AMICIA__CH02__CHATTER__ACROSS_COMING__020__M__1": "Yapabilirsin! Panik yapma!",
"VO__AMICIA__CH02__CHATTER__ARCADE_EXIT_CLOSE__010__M__1": "İşte böyle. Git buradan.",
"VO__AMICIA__CH02__CHATTER__ARCADES_DISPENS_AFTER__010__M__1": "Onu durdurabilir miyiz Lucas?",
"VO__AMICIA__CH02__CHATTER__ARCADES_DISPENS_AFTER__030__M__1": "Evet, ama Hugo'yu iyileştirirsek...?",
"VO__AMICIA__CH02__CHATTER__ARCADES_DISPENS_AFTER__050__M__1": "Hâlâ bir tane görmedik...",
"VO__AMICIA__CH02__CHATTER__ARCADES_DISPENS_AFTER__070__M__1": "Güneşten saklanıyorlar. Bekliyorlar...",
"VO__AMICIA__CH02__CHATTER__ARCADES_DISPENS_INTRO__050__M__1": "Cesetler.",
"VO__AMICIA__CH02__CHATTER__ARCADES_DISPENS_INTRO__070__M__1": "Sanırım eskiden burada yaşıyorlardı.",
"VO__AMICIA__CH02__CHATTER__ARCADES_DISPENS_OUTRO__010__M__1": "Lütfen söyle, burası burası.",
"VO__AMICIA__CH02__CHATTER__ARCADES_DISPENS_SCENE__060__M__1": "Biri hâlâ hayatta!",
"VO__AMICIA__CH02__CHATTER__ARCADES_DISPENS_SKILL_TUTO__020__M__1": "Yaşamasına izin verip kendim ölme riskine girmesem daha iyi...",
"VO__AMICIA__CH02__CHATTER__ARCADES_DISPENS_SKILL_TUTO__030__M__1": "Evet... Muhtemelen bu yüzden hâlâ bunu konuşacak kadar hayattayız.",
"VO__AMICIA__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_BRIDGE__010__M__1": "Buraya...",
"VO__AMICIA__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_BRIDGE__030__M__1": "Merak etme.",
"VO__AMICIA__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_FIRSTBLOOD__010__M__1": "Bir baş belası eksildi...",
"VO__AMICIA__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_FIRSTBLOOD__030__M__1": "İlerlemeye devam etmeliyiz.",
"VO__AMICIA__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_INTRO__010__M__1": "Vaudin'i henüz bulmadılar.",
"VO__AMICIA__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_INTRO__030__M__1": "Yalnız. Eninde sonunda onu yakalarlar. Yakalarlarsa, Hugo'nun da işi biter.",
"VO__AMICIA__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_LEFT__010__M__1": "Vaktimizi boşa harcıyorlar...",
"VO__AMICIA__CH02__CHATTER__ARCADES_ENCOUNT_INTRO__070__M__1": "Asker gibi konuşuyorlar... Eski askerler. Paralı askerler sanırım.",
"VO__AMICIA__CH02__CHATTER__ARCADES_ENCOUNT_INTRO__100__M__1": "Okçu! Yukarıda...",
"VO__AMICIA__CH02__CHATTER__ARCADES_ENCOUNT_UP_ARCHER__010__M__1": "Ne yaptığımı biliyorum.",
"VO__AMICIA__CH02__CHATTER__ARCADES_ENCOUNT_UP_INTRO__010__M__1": "Neredeyse buradan çıktık...",
"VO__AMICIA__CH02__CHATTER__ARCADES_GOINGUP__010__M__1": "Şuradan deneyelim...",
"VO__AMICIA__CH02__CHATTER__ARCADES_INTRO__010__M__1": "Ah!",
"VO__AMICIA__CH02__CHATTER__ARCADES_PP_CART_DOWN__020__M__1": "Hadi... itelim...",
"VO__AMICIA__CH02__CHATTER__ARCADES_PP_CART_OK__010__M__1": "Hadi, çabuk.",
"VO__AMICIA__CH02__CHATTER__ARCADES_PP_CART_PUSH__040__M__1": "Onu buraya biz getirdik... Onları biz mahkûm ettik...",
"VO__AMICIA__CH02__CHATTER__ARCADES_PP_CART_PUSH__060__M__1": "Evet, ama... gelişini görürlerdi...",
"VO__AMICIA__CH02__CHATTER__ARCADES_PP_CART_UP__020__M__1": "Yukarıdaki o kafes doğru boyutta görünüyor.",
"VO__AMICIA__CH02__CHATTER__ARCADES_PP_CART_UP__040__M__1": "Onlara bakma...",
"VO__AMICIA__CH02__CHATTER__ARCADES_PP_INTRO_HELPER__020__M__1": "Hadi... çıkmak için bir şey bulalım o zaman... çabuk!",
"VO__AMICIA__CH02__CHATTER__ARCADES_PP_INTRO2__010__M__1": "Demek onlar da Vaudin'in peşinde...",
"VO__AMICIA__CH02__CHATTER__ARCADES_PP_INTRO2__030__M__1": "Bizim talihimiz işte...",
"VO__AMICIA__CH02__CHATTER__ARCADES_TOWER__010__M__1": "Tanrım... Koca bir şehir!",
"VO__AMICIA__CH02__CHATTER__ARCADES_TOWER__030__M__1": "Şart mı? Lucas, bu karmaşayı geçmek ne kolay olacak ne de hızlı.",
"VO__AMICIA__CH02__CHATTER__ARCADES_TOWER__050__M__1": "Hadi oraya varalım yeter...",
"VO__AMICIA__CH02__CHATTER__ARCADES_UP_HOMES__030__M__1": "Evet... Ama hiçbiri yenmiş gibi görünmüyor...",
"VO__AMICIA__CH02__CHATTER__ARENA_AMICIA_KILL_1__010__M__1": "Kaybedecek vakit yok...",
"VO__AMICIA__CH02__CHATTER__ARENA_AMICIA_KILL_2__010__M__1": "Çekil yoldan!",
"VO__AMICIA__CH02__CHATTER__ARENA_COMMUNE_CHAPEL__020__M__1": "Bunu takdir ediyorum, ama vaktimiz yok.",
"VO__AMICIA__CH02__CHATTER__ARENA_COMMUNE_CHAPELDOOR__010__M__1": "İçeride ne var bir bakalım...",
"VO__AMICIA__CH02__CHATTER__ARENA_COMMUNE_FLOWER__010__M__1": "Hey, sen burada ne arıyorsun?",
"VO__AMICIA__CH02__CHATTER__ARENA_COMMUNE_FLOWER__030__M__1": "Hugo buna bayılacak. Eskisi gibi orada saklayacağım...",
"VO__AMICIA__CH02__CHATTER__ARENA_COMMUNE_FLOWER__050__M__1": "Şey, teşekkürler. Devam edelim.",
"VO__AMICIA__CH02__CHATTER__ARENA_COMMUNE_GALLERY__010__M__1": "Son bir gayret...",
"VO__AMICIA__CH02__CHATTER__ARENA_COMMUNE_GALLERY__011__M__1": "Bu şey kocaman... İçeride olmalı.",
"VO__AMICIA__CH02__CHATTER__ARENA_COMMUNE_GALLERY__030__M__1": "Düzen'in hâlâ o gücü varsa... Belki Hugo'yu kurtarabilirler.",
"VO__AMICIA__CH02__CHATTER__ARENA_COMMUNE_SQUARE__020__M__1": "Isırıktan önce, evet...",
"VO__AMICIA__CH02__CHATTER__ARENA_COMMUNE_START__010__M__1": "O paralı askerlerden iz yok.",
"VO__AMICIA__CH02__CHATTER__ARENA_COMMUNE_START__030__M__1": "Hadi acele edelim.",
"VO__AMICIA__CH02__CHATTER__ARENA_FIELD_AFTER_END__010__M__1": "Sakin... Nefes al...",
"VO__AMICIA__CH02__CHATTER__ARENA_FIELD_AFTER_NEAR__010__M__1": "Hâlâ bizi yavaşlatıyorlar!",
"VO__AMICIA__CH02__CHATTER__ARENA_FIELD_AFTER_NEAR__030__M__1": "Neredeyse...",
"VO__AMICIA__CH02__CHATTER__ARENA_FIELD_INTRO__020__M__1": "Ve yakında baskın verecekler! Lucas, bu Hugo'yu kurtarmak için son şansımız!",
"VO__AMICIA__CH02__CHATTER__ARENA_FIELD_INTRO__040__M__1": "Hadi!",
"VO__AMICIA__CH02__CHATTER__ARENA_FIELD_RATS_HEROES__020__M__1": "Bizi takip ettiler... Hayır! Vaktimiz yok!",
"VO__AMICIA__CH02__CHATTER__ARENA_IDLE_1__010__M__1": "Hadi... Hadi!",
"VO__AMICIA__CH02__CHATTER__ARENA_IDLE_2__010__M__1": "Başarısız olamayız... Hugo'nun hayatı bize bağlı...",
"VO__AMICIA__CH02__CHATTER__ARENA_REUNITED_INTRO__020__M__1": "Lütfen beni soğuk terler içinde bırakmayı kes... Devam edelim.",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_DONE__020__M__1": "İyi iş! Hadi şu magisteri bulalım!",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_GENERIC_DONE__010__M__1": "Hepsi bu kadar, sanırım!",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_INTRO__020__M__1": "Yukarı nasıl çıkacağız?",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_INTRO__040__M__1": "Bütün bu şey nasıl çalışıyor?",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_INTRO__060__M__1": "Ama anahtarımız yok, yani...",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_INTRO__080__M__1": "Pekâlâ!",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_JUPITER_AMICIA__020__M__1": "Sırada ne var?",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_JUPITER_HELPER__025__M__1": "Z...",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_MARS_AMICIA__010__M__1": "Mars, işte bu!",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_MARS_HELPER__025__M__1": "Mızrak. Kalkan.",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_MERCURY_AMICIA__010__M__1": "Ve tamam!",
"VO__AMICIA__CH02__CHATTER__ARENA_TOWER_VENUS_AMICIA__010__M__1": "Sanırım bu Venüs...",
"VO__AMICIA__CH02__CHATTER__ARENA_UP_AFTERDOOR__005__M__1": "Eyvah...",
"VO__AMICIA__CH02__CHATTER__ARENA_UP_AFTERDOOR__020__M__1": "İniyoruz.",
"VO__AMICIA__CH02__CHATTER__ARENA_UP_AFTERDOOR__040__M__1": "Hayır. Ve Hugo'nun durumu burada geçirdiğimiz her saniye kötüleşiyor.",
"VO__AMICIA__CH02__CHATTER__ARENA_UP_VAUDIN__009__M__1": "Güneş ışığına yaklaşıyoruz!",
"VO__AMICIA__CH02__CHATTER__ARENA_UP_VAUDIN__030__M__1": "Çok iyi bir plan olsa iyi olur.",
"VO__AMICIA__CH02__CHATTER__ARMS_READY__010__M__1": "Pekâlâ Lucas, hazırım!",
"VO__AMICIA__CH02__CHATTER__BACKSTAGE_ENTRANCE__010__M__1": "Ah... O da ne?",
"VO__AMICIA__CH02__CHATTER__BANDITS__010__M__1": "O kaba herif asker değil.",
"VO__AMICIA__CH02__CHATTER__BANDITS__030__M__1": "Hayır... Kaç kişiler?",
"VO__AMICIA__CH02__CHATTER__BANDITS__050__M__1": "Onu yerinden kımıldatacağım.",
"VO__AMICIA__CH02__CHATTER__BASE_FALL_CROSSING__010__M__1": "Tamam. Sakin.",
"VO__AMICIA__CH02__CHATTER__BASE_FALL_CROSSING__030__M__1": "Sadece acele etme.",
"VO__AMICIA__CH02__CHATTER__BASE_FALL_LUCASFALLS__020__M__1": "Lucas!",
"VO__AMICIA__CH02__CHATTER__BASE_FALL_LUCASFALLS__040__M__1": "İyi misin?!",
"VO__AMICIA__CH02__CHATTER__BASE_FALL_LUCASFALLS__060__M__1": "Merdiven! Yüksek yere çık, çabuk!",
"VO__AMICIA__CH02__CHATTER__BASE_FALL_START__020__M__1": "Tek yol bu.",
"VO__AMICIA__CH02__CHATTER__BASE_INTRO_RATS__020__M__1": "Buradan çıkmalıyız... şu ya da bu şekilde.",
"VO__AMICIA__CH02__CHATTER__BASE_INTRO_RATS__050__M__1": "Bana tutunmaya devam et!",
"VO__AMICIA__CH02__CHATTER__BASE_INTRO_RATS__070__M__1": "Mecburuz... Hadi dikkatlice gidelim...",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM1_CLIMB__010__M__1": "Evet... O dayanır...",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM1_CLIMB__030__M__1": "Ne?! Nasıl?",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM1_CLIMB__050__M__1": "Şu kuleye ulaşırız, Vaudin'i alırız, Hugo'ya götürürüz ve gideriz.",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM1_FURTHER__020__M__1": "Onsuz idare ederiz!",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM1_OBSTACLE__010__M__1": "Sanırım şu duvara tırmanabiliriz. Ama ellerimin serbest olması gerek.",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM1_TORCHHOLD__010__M__1": "Başka çare yok...",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM2_BRASEROLIGHTUP__010__M__1": "Işık merdivene ulaşmıyor...",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM2_BRASEROLIGHTUP__030__M__1": "Görüyorum.",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM2_BRASEROOFF__020__M__1": "Evet, onu kullanabilirim.",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM2_EXIT__009__M__1": "Hadi, çabuk!",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM2_SPOTLADDER__010__M__1": "Başarabiliriz. Başarıyoruz.",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM2_START__010__M__1": "İğrenç pislik!",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM2_START__030__M__1": "Bir çubuk kullanalım.",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM2_STICKFIRST__020__M__1": "Ateş şimdilik... idare ediyor...",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM2_WHERE__010__M__1": "Düz bir çizgide gideceğiz...",
"VO__AMICIA__CH02__CHATTER__BASE_ROOM2_WHERE__020__M__1": "Lucas, gece çöktüğünde...",
"VO__AMICIA__CH02__CHATTER__BEFORE_SQUEEZE__010__M__1": "Kuleye gerçekten çok yaklaşıyoruz!",
"VO__AMICIA__CH02__CHATTER__BIG_CART_DEAD_END__010__M__1": "Ölüleri şehirden çıkarmak için kullandıkları araba bu.",
"VO__AMICIA__CH02__CHATTER__CAGES_LODGE__010__M__1": "Şimdi ne olacak?",
"VO__AMICIA__CH02__CHATTER__CAGES_LODGE__030__M__1": "Her neyse... Şu yeri aydınlatalım.",
"VO__AMICIA__CH02__CHATTER__CAGES_LODGE_ALONE__010__M__1": "Kafesler... içlerinde daha çok hayvan vardı...",
"VO__AMICIA__CH02__CHATTER__CANCEL_LUCAS_NOTREADY__020__M__1": "Pekâlâ!",
"VO__AMICIA__CH02__CHATTER__CANT_LIGHT_BRASIER__020__M__1": "Hallediyorum!",
"VO__AMICIA__CH02__CHATTER__CARPENTER_SPOT__020__M__1": "Bir bakalım",
"VO__AMICIA__CH02__CHATTER__CARPENTERSTAND_INTERACT__031__M__1": "Tanrım...",
"VO__AMICIA__CH02__CHATTER__CARPENTERSTAND_INTERACT__040__M__1": "Pardon! Haklısın — bunlar dev testereler.",
"VO__AMICIA__CH02__CHATTER__CART_GRAB__010__M__1": "Vakit kaybediyoruz...",
"VO__AMICIA__CH02__CHATTER__CART_SPOT__010__M__1": "Bu işe yarayabilir.",
"VO__AMICIA__CH02__CHATTER__CATCH_FLAM_NOT_OK__020__M__1": "Pekâlâ!",
"VO__AMICIA__CH02__CHATTER__CENTRAL_CRANK__010__M__1": "Hm... Hayır, bu krank daha fazlasını yapmaz, diğerini bulmam lazım...",
"VO__AMICIA__CH02__CHATTER__CENTRAL_LIFT_CRANK__020__M__1": "Evet. Deneyelim.",
"VO__AMICIA__CH02__CHATTER__CHAMBOULETOUT_PLAY__010__M__1": "Pekâlâ! Peki, bunu nasıl oynuyoruz?",
"VO__AMICIA__CH02__CHATTER__CHAMBOULETOUT_PLAY__030__M__1": "Varım!",
"VO__AMICIA__CH02__CHATTER__CHAMBOULETOUT_PLAY__060__M__1": "Kolay!",
"VO__AMICIA__CH02__CHATTER__CHAMEBOULETOUT_BYE__010__M__1": "Sanırım gitmemiz gerek.",
"VO__AMICIA__CH02__CHATTER__CHAMEBOULETOUT_BYE__015__M__1": "Teşekkürler!",
"VO__AMICIA__CH02__CHATTER__CHAMEBOULETOUT_FAILURE__010__M__1": "Pek iyi gitmedi...",
"VO__AMICIA__CH02__CHATTER__CHAMEBOULETOUT_FAILURE__030__M__1": "Sanırım öyleyim...",
"VO__AMICIA__CH02__CHATTER__CHAMEBOULETOUT_WIN__030__M__1": "Elbette yaptım! Ne bekliyordun ki!",
"VO__AMICIA__CH02__CHATTER__CHAPEL_LOCKED__010__M__1": "Kilitli...",
"VO__AMICIA__CH02__CHATTER__CHASE_BURST__010__M__1": "Hayır, hayır!",
"VO__AMICIA__CH02__CHATTER__CHASE_BURST__030__M__1": "Hayır... Işığımız var... Şimdilik güvendeyiz...",
"VO__AMICIA__CH02__CHATTER__CHASE_DOOR__010__M__1": "Kapat onu!",
"VO__AMICIA__CH02__CHATTER__CHASE_DOOR__030__M__1": "Tut!... Tut!",
"VO__AMICIA__CH02__CHATTER__CHEST_SPOT_SMITHY__010__M__1": "Bu kükürt, değil mi?",
"VO__AMICIA__CH02__CHATTER__CHEST_SPOT_SMITHY__015__M__1": "Kükürt mü?",
"VO__AMICIA__CH02__CHATTER__CHEST_SPOT_SMITHY__030__M__1": "Hadi oraya çıkalım...",
"VO__AMICIA__CH02__CHATTER__CLIMB_QUICK__020__M__1": "Asansöre gidelim! Çabuk!",
"VO__AMICIA__CH02__CHATTER__CLIMB_STAIRS__010__M__1": "Lütfen söyle, ondan sapmadık...",
"VO__AMICIA__CH02__CHATTER__CLIMB_STAIRS__030__M__1": "Evet! Kule!",
"VO__AMICIA__CH02__CHATTER__CONCERT_ENDS__010__M__1": "Pekâlâ delikanlı! Gidip şu eve bakmalıyız!",
"VO__AMICIA__CH02__CHATTER__CONCERT_ENDS__030__M__1": "Evet! Annem bizi bekliyordur.",
"VO__AMICIA__CH02__CHATTER__CONCERT_INTERACT__008__M__1": "Hey, biliyor musun? Seni omuzlarıma alacağım, tamam mı?",
"VO__AMICIA__CH02__CHATTER__CONCERT_INTERACT__010__M__1": "Hadi bakalım!",
"VO__AMICIA__CH02__CHATTER__CONCERT_INTERACT__011__M__1": "Yukarıda iyi misin?",
"VO__AMICIA__CH02__CHATTER__CONCERT_SINGING__020__M__1": "Evet, ama harika!",
"VO__AMICIA__CH02__CHATTER__CRANK_DROP_INCOMPLETE__030__M__1": "Pardon, düşürdüm! Yeniden başlayalım!",
"VO__AMICIA__CH02__CHATTER__CRANK_USE_ALONE__010__M__1": "Pekâlâ... Şu canavarı... kımıldatalım!",
"VO__AMICIA__CH02__CHATTER__CRANK_USE_ALONE__030__M__1": "Ha... Bu şey çok ağır.",
"VO__AMICIA__CH02__CHATTER__CRANK_USE_ALONE__060__M__1": "Pekâlâ, sen orada kal, ben gidip şu diğerini kullanayım!",
"VO__AMICIA__CH02__CHATTER__CROSSING_ALONE__010__M__1": "Çabuk... Daha çabuk...",
"VO__AMICIA__CH02__CHATTER__CROSSING_RATS_TORCH__010__M__1": "Biliyordum! Burada olduklarını söylemiştim!",
"VO__AMICIA__CH02__CHATTER__CROSSING_RATS_TORCH__040__M__1": "Hugo... Onun için buradalar...",
"VO__AMICIA__CH02__CHATTER__DEAD_FAMILY__020__M__1": "Mecbur değilsin...",
"VO__AMICIA__CH02__CHATTER__DYING_WOMAN__010__M__1": "Hanımefendi...",
"VO__AMICIA__CH02__CHATTER__DYING_WOMAN__030__M__1": "Ben... Ben Alice değilim.",
"VO__AMICIA__CH02__CHATTER__DYING_WOMAN__050__M__1": "Edeceğim. Huzur içinde ol.",
"VO__AMICIA__CH02__CHATTER__DYING_WOMAN__080__M__1": "Bir şey yapmadım... gidelim.",
"VO__AMICIA__CH02__CHATTER__ELEPHANT_REMAINS__010__M__1": "Lucas... O şey de ne?!",
"VO__AMICIA__CH02__CHATTER__ELEPHANT_REMAINS__030__M__1": "Kocaman! Şu... dişlerine bak...",
"VO__AMICIA__CH02__CHATTER__ELEPHANT_REMAINS__050__M__1": "Evet... Etrafta yeterince kemik var. Hadi buradan çıkalım.",
"VO__AMICIA__CH02__CHATTER__ELEVATOR_LEVER__020__M__1": "Ne yaptığına bakalım...",
"VO__AMICIA__CH02__CHATTER__ELVATR_CART__020__M__1": "Devam et.",
"VO__AMICIA__CH02__CHATTER__ELVATR_CRANK_SPOT__010__M__1": "Bir krank. Bir asansör var.",
"VO__AMICIA__CH02__CHATTER__ELVATR_CRANK_USE__010__M__1": "Tabii ki... Sabit kalmayacak.",
"VO__AMICIA__CH02__CHATTER__ELVATR_CRANK_USE__020__M__1": "Hayatımın... en güzel anı...",
"VO__AMICIA__CH02__CHATTER__ELVATR_CRANK_USE__030__M__1": "İyi fikir.",
"VO__AMICIA__CH02__CHATTER__ELVATR_POSITIONING__010__M__1": "Daha hızlı hareket etmeliyiz! Hugo için endişeleniyorum!",
"VO__AMICIA__CH02__CHATTER__ELVATR_POSITIONING__030__M__1": "Orada olup olmadığını bile bilmiyoruz! Ve fareler... ve o paralı askerler...",
"VO__AMICIA__CH02__CHATTER__ELVATR_POSITIONING__050__M__1": "Evet...",
"VO__AMICIA__CH02__CHATTER__ELVATR_WITH_AMICIA__010__M__1": "Kendine zarar verme...",
"VO__AMICIA__CH02__CHATTER__ELVATR_WITH_AMICIA__030__M__1": "Hm... Bilmek güzel...",
"VO__AMICIA__CH02__CHATTER__ENCOUNTER_LOCKED__010__M__1": "Hmmm, hayır...",
"VO__AMICIA__CH02__CHATTER__ENTER_ENCOUNTER__010__M__1": "Ha... Burası kocaman...",
"VO__AMICIA__CH02__CHATTER__ENTER_ENCOUNTER__030__M__1": "Güzel, ama... Lucas, bu insanlar hastalandıysa demek ki... bazıları ısırılmış olmalı.",
"VO__AMICIA__CH02__CHATTER__ENTER_ENCOUNTER__050__M__1": "Henüz değil... Her neyse, gidelim.",
"VO__AMICIA__CH02__CHATTER__ENTER_STOCKS__010__M__1": "Et deposu...",
"VO__AMICIA__CH02__CHATTER__ENTER_STOCKS__030__M__1": "Pekâlâ... Önce şu fareleri oyalamaya çalışalım...",
"VO__AMICIA__CH02__CHATTER__FIRE_BREATHER__020__M__1": "Ah!",
"VO__AMICIA__CH02__CHATTER__FIRE_BREATHER__040__M__1": "Anne babası ejderha olmalı.",
"VO__AMICIA__CH02__CHATTER__FIRE_BREATHER__060__M__1": "Aynen!",
"VO__AMICIA__CH02__CHATTER__FIRE_BREATHER__080__M__1": "Tabii ki. O haindir.",
"VO__AMICIA__CH02__CHATTER__FIRST_KILL__020__M__1": "Bana güven.",
"VO__AMICIA__CH02__CHATTER__FORGE__020__M__1": "Bu daha büyük... Ve daha sıcak...",
"VO__AMICIA__CH02__CHATTER__FOUND_HIM_3__010__M__1": "Affedersiniz efendim, karınız bizi gönderdi!",
"VO__AMICIA__CH02__CHATTER__FOUNTAIN__010__M__1": "Çok güzel!",
"VO__AMICIA__CH02__CHATTER__FOUNTAIN__030__M__1": "Belki şimdi değil...",
"VO__AMICIA__CH02__CHATTER__GATE_PASS_1__020__M__1": "Aah... pis kokuyor!",
"VO__AMICIA__CH02__CHATTER__GO_CRANK__010__M__1": "Şimdi gidip şu kranka bakalım!",
"VO__AMICIA__CH02__CHATTER__GOING_TO_FLORIST__010__M__1": "Buradan!",
"VO__AMICIA__CH02__CHATTER__HALLES_CRIT_HERBORIST_CHAT__050__M__1": "Teşekkürler, ama biz... onları doğada toplamayı severiz. Bizim âdetimiz.",
"VO__AMICIA__CH02__CHATTER__HALLES_CRIT_HERBORIST_CHAT__070__M__1": "Tabii!",
"VO__AMICIA__CH02__CHATTER__HALLES_EVENT_ITALY_INTERACT__020__M__1": "Teşekkürler, ama ben böyle seviyorum.",
"VO__AMICIA__CH02__CHATTER__HALLES_EVENT_ITALY_INTERACT__040__M__1": "Çok güzel söylediniz.",
"VO__AMICIA__CH02__CHATTER__HALLES_EVENT_ITALY_INTERACT__060__M__1": "Teşekkürler efendim!",
"VO__AMICIA__CH02__CHATTER__HALLES_INTRO__030__M__1": "Evet. Manzara muhteşem olacak...",
"VO__AMICIA__CH02__CHATTER__HALLES_LEAVING__010__M__1": "Gidip evimizi görelim! Hemen şurada olmalı.",
"VO__AMICIA__CH02__CHATTER__HALLES_LEAVING__030__M__1": "Kendi odanı istemez misin?",
"VO__AMICIA__CH02__CHATTER__HALLES_LEAVING__050__M__1": "Ama o zaman birbirimizi odamıza davet edebiliriz!",
"VO__AMICIA__CH02__CHATTER__HALLES_LEAVING__070__M__1": "Ben de!",
"VO__AMICIA__CH02__CHATTER__HAM_SHOOT__010__M__1": "Güzel. Şu sandığa ulaşalım!",
"VO__AMICIA__CH02__CHATTER__HIDDEN_HELPER__010__M__1": "Miğferi var, hiçbir şey yapamam...",
"VO__AMICIA__CH02__CHATTER__HIDEOUT_UNLOCKED__010__M__1": "Giriş yolumuz işte.",
"VO__AMICIA__CH02__CHATTER__HOUSE_ARRIVAL__020__M__1": "Sakin görünüyor...",
"VO__AMICIA__CH02__CHATTER__HOUSE_FINAL_LUCAS__020__M__1": "Evet, sen önden git!",
"VO__AMICIA__CH02__CHATTER__HOUSE_LUCASCHAT__040__M__1": "Ve sanırım birinin kestirmesi gerekiyor.",
"VO__AMICIA__CH02__CHATTER__HOUSE_LUCASCHAT__060__M__1": "Tabii. Hadi içeri bakalım.",
"VO__AMICIA__CH02__CHATTER__HOUSE_REMINDER_1__010__M__1": "Evimizin içi nasıldır acaba çok merak ediyorum...",
"VO__AMICIA__CH02__CHATTER__HOUSE_SQUARE__010__M__1": "Şuna bak... Sanırım... buraya yuva diyebiliriz.",
"VO__AMICIA__CH02__CHATTER__HUBT1_ALLEY__020__M__1": "Ne?",
"VO__AMICIA__CH02__CHATTER__HUBT1_ALLEY__031__M__1": "Ah... Doğru...",
"VO__AMICIA__CH02__CHATTER__HUBT1_ALLEY_EXIT__010__M__1": "Ah bak, yukarıda! Fırıldaklı ev! Bizimki o!",
"VO__AMICIA__CH02__CHATTER__HUBT1_BURGUNDY__020__M__1": "Hadi... sen daha fazlasını istemeden devam edelim...",
"VO__AMICIA__CH02__CHATTER__HUBT1_ENTERING__020__M__1": "Peki, ne görmek istiyorsun?",
"VO__AMICIA__CH02__CHATTER__HUBT1_ENTERING__040__M__1": "Deneriz!",
"VO__AMICIA__CH02__CHATTER__HUBT1_MEATSTAND__010__M__1": "Ah, çok güzel kokuyor...",
"VO__AMICIA__CH02__CHATTER__HUBT1_MEATSTAND__030__M__1": "Devam et!",
"VO__AMICIA__CH02__CHATTER__HUBT1_MEATSTAND__070__M__1": "Hadi, gidip gerisini görelim!",
"VO__AMICIA__CH02__CHATTER__HUBT1_UPHOUSE_CARRY_FAIR__020__M__1": "Kötü şeyler mi?",
"VO__AMICIA__CH02__CHATTER__HUBT1_UPHOUSE_CARRY_FAIR__040__M__1": "Bence biliyorlar. Sadece burada güvende hissediyorlar. Sen de hissedeceksin.",
"VO__AMICIA__CH02__CHATTER__HUBT1_UPHOUSE_DROP__010__M__1": "Hey, seni biraz yere bırakacağım. Hadi temponu artıralım!",
"VO__AMICIA__CH02__CHATTER__HUBT1_VIEW_FISH__020__M__1": "Akşam yemeği için yiyecek almaya Annemle birlikte geliriz.",
"VO__AMICIA__CH02__CHATTER__HUNGRY_PIGGY__010__M__1": "Eyvah... Onları yeme...",
"VO__AMICIA__CH02__CHATTER__IDLE_BODIES__020__M__1": "Burada kaç kişi öldü?!",
"VO__AMICIA__CH02__CHATTER__IDLE_BODIES__040__M__1": "Mahkûm edilmişler.",
"VO__AMICIA__CH02__CHATTER__IDLE_CROPS__020__M__1": "Bütün bunları yoktan var ettiler. Ve birkaç günde ellerinden alındı.",
"VO__AMICIA__CH02__CHATTER__IDLE_ENCNTR_GROUND_1__010__M__1": "Bu çok vakit alıyor.",
"VO__AMICIA__CH02__CHATTER__IDLE_ENCNTR_GROUND_1__030__M__1": "Biliyorum!",
"VO__AMICIA__CH02__CHATTER__IDLE_ENCNTR_GROUND_2__020__M__1": "Fareler diğer mahallelere yayılana dek ne kadar var?",
"VO__AMICIA__CH02__CHATTER__IDLE_ENCNTR_GROUND_2__040__M__1": "Yer altından hareket ediyorlar. Yiyecek olan yere giderler. Kan olan yere.",
"VO__AMICIA__CH02__CHATTER__IDLE_ENCOUNTER_2__010__M__1": "Annem buna nasıl tepki verecek acaba...",
"VO__AMICIA__CH02__CHATTER__IDLE_ENCOUNTER_2__030__M__1": "Yeterince güçlü değil, korkarım.",
"VO__AMICIA__CH02__CHATTER__IDLE_MARKET_2__010__M__1": "Bütün bu insanları nasıl getirtmeyi başardılar?",
"VO__AMICIA__CH02__CHATTER__IDLE_MARKET_3__010__M__1": "Umarım Annemle Lucas'ın yukarıda çok işi yoktur.",
"VO__AMICIA__CH02__CHATTER__IDLE_MARKET_MOM__010__M__1": "Her şey çok güzel...",
"VO__AMICIA__CH02__CHATTER__IDLE_MARKET_MOM__030__M__1": "Tabii. Panayır birkaç gün sürecek. Burası artık bizim şehrimiz.",
"VO__AMICIA__CH02__CHATTER__IDLE_MARKET_PEOPLE__020__M__1": "Tüccarlar dört bir yandan geliyor.",
"VO__AMICIA__CH02__CHATTER__IGNI_JAR_TUTO__010__M__1": "Hâlâ fare kaldı...",
"VO__AMICIA__CH02__CHATTER__IGNI_JAR_TUTO__020__M__1": "Umarım işe yarar.",
"VO__AMICIA__CH02__CHATTER__IGNI_POT_READY__010__M__1": "Tamam...",
"VO__AMICIA__CH02__CHATTER__IGNI_POT_THROW__010__M__1": "Şimdi!",
"VO__AMICIA__CH02__CHATTER__IGNI_SUCCESS__010__M__1": "İşte bu harika bir fikirdi!",
"VO__AMICIA__CH02__CHATTER__IGNIFER_CRAFT__020__M__1": "Ignifer... O şeye bayılırdım.",
"VO__AMICIA__CH02__CHATTER__IGNIFER_DONE__010__M__1": "Tamam!",
"VO__AMICIA__CH02__CHATTER__IGNIFER_USE__030__M__1": "Bu da ne?!",
"VO__AMICIA__CH02__CHATTER__IGNIFER_USE__060__M__1": "Sağ ol Lucas, o Ignifer çok işe yarayacak! Şimdi şu platformu indirmeye çalışalım.",
"VO__AMICIA__CH02__CHATTER__IGNIFER_USE__080__M__1": "Bir bakarız...",
"VO__AMICIA__CH02__CHATTER__INSIDE_BANDITS_CHAT_A__011__M__1": "Bir doktor mu?",
"VO__AMICIA__CH02__CHATTER__INSTRUMENTSTAND_INTERACT__010__M__1": "Ah, çok güzeller...",
"VO__AMICIA__CH02__CHATTER__INSTRUMENTSTAND_INTERACT__030__M__1": "Hayır, ben... öğrenmeye hiç vakit ayıramadım.",
"VO__AMICIA__CH02__CHATTER__INSTRUMENTSTAND_INTERACT__050__M__1": "Çalabilirdim! Çok isterdim... Bir gün öğreneceğim!",
"VO__AMICIA__CH02__CHATTER__INTERACT_LIFT__010__M__1": "Sana ihtiyacım olacak...",
"VO__AMICIA__CH02__CHATTER__INTRCT_CHEST_STOCKS__020__M__1": "Alkol şişeleri!",
"VO__AMICIA__CH02__CHATTER__INTRCT_LIFT__010__M__1": "Çalışıyor!",
"VO__AMICIA__CH02__CHATTER__INTRCT_LIFT__030__M__1": "Tanrı'ya şükür...",
"VO__AMICIA__CH02__CHATTER__INVEST_DOWN_WHERETO__010__M__1": "Vaudin neden hâlâ ortaya çıkmadı?",
"VO__AMICIA__CH02__CHATTER__INVEST_DOWN_WHERETO__030__M__1": "Birileri onu tanıyor olmalı. Hadi soralım.",
"VO__AMICIA__CH02__CHATTER__INVEST_GUARD_OUTRO__010__M__1": "Güzel, bu bir başlangıç.",
"VO__AMICIA__CH02__CHATTER__INVEST_GUARD_OUTRO__030__M__1": "Az önce çiçekçinin oradan geçtik, bu pazar meydanının bir yerlerinde.",
"VO__AMICIA__CH02__CHATTER__INVEST_HERBORIST_CHAT__005__M__1": "Yine merhaba...",
"VO__AMICIA__CH02__CHATTER__INVEST_HERBORIST_CHAT__020__M__1": "Aslında... Sir Vaudin'i arıyorum. Sanırım müşterilerinizden biri?",
"VO__AMICIA__CH02__CHATTER__INVEST_HERBORIST_CHAT__031__M__1": "Ah...",
"VO__AMICIA__CH02__CHATTER__INVEST_HERBORIST_CHAT__041__M__1": "Kahverengi tunik. Yardımınız için teşekkürler!",
"VO__AMICIA__CH02__CHATTER__INVEST_HERBORIST_GUARDHELP__010__M__1": "Pardon, çiçekçi tezgâhını arıyoruz...",
"VO__AMICIA__CH02__CHATTER__INVEST_HERBORIST_IDEA__030__M__1": "Hmmm... Belki birine sorabiliriz...",
"VO__AMICIA__CH02__CHATTER__INVEST_HERBORIST_OUTRO__010__M__1": "Tamam, vakit kaybetmeyelim.",
"VO__AMICIA__CH02__CHATTER__INVEST_HERBORISTHUSB_CHAT__017__M__1": "Onun için değil. Sir Vaudin'i bulmalıyız.",
"VO__AMICIA__CH02__CHATTER__INVEST_HERBORISTHUSB_CHAT__21__M__1": "Dinleyin, kardeşim çok hasta! Ona hemen ihtiyacımız var!",
"VO__AMICIA__CH02__CHATTER__INVEST_OUTSIDE_DOUBT__020__M__1": "Bu Magister Vaudin gerçekten yardım edecek mi?",
"VO__AMICIA__CH02__CHATTER__INVEST_OUTSIDE_DOUBT__040__M__1": "Tanrım... Onu koru...",
"VO__AMICIA__CH02__CHATTER__INVEST_OUTSIDE_INTRO__010__M__1": "O çiftçiler yüzünden... Asla yapmamalıydım...",
"VO__AMICIA__CH02__CHATTER__INVEST_OUTSIDE_INTRO__030__M__1": "Bundan nasıl bu kadar emin olabiliyorsun?",
"VO__AMICIA__CH02__CHATTER__INVEST_SLUMS_DANGER_OUTRO__010__M__1": "Burası bir gecekondu! Düzen fakir değil, peki bir Magister burada ne yapsın?",
"VO__AMICIA__CH02__CHATTER__INVEST_SLUMS_DANGER_OUTRO__030__M__1": "Muhtemelen...",
"VO__AMICIA__CH02__CHATTER__INVEST_SLUMS_GUARDS__020__M__1": "Neden öyle?",
"VO__AMICIA__CH02__CHATTER__INVEST_SLUMS_GUARDS__040__M__1": "Dinleyin, gerçekten geçmem gerek...",
"VO__AMICIA__CH02__CHATTER__INVEST_SLUMS_GUARDS__050__M__1": "Ha...",
"VO__AMICIA__CH02__CHATTER__INVEST_SLUMS_INTRO__010__M__1": "Arena mahallesi...",
"VO__AMICIA__CH02__CHATTER__INVEST_SLUMS_INTRO__030__M__1": "Onu nasıl bulacağız?",
"VO__AMICIA__CH02__CHATTER__INVEST_SLUMS_SYMBOL__020__M__1": "Düzen!",
"VO__AMICIA__CH02__CHATTER__INVEST_SLUMS_UP__010__M__1": "Evet!",
"VO__AMICIA__CH02__CHATTER__INVEST_SLUMS_WALKINGDOWN__030__M__1": "Haklısın. Pardon.",
"VO__AMICIA__CH02__CHATTER__INVEST_SLUMS_WINDOW__010__M__1": "Hadi...",
"VO__AMICIA__CH02__CHATTER__JAR_LODGE__020__M__1": "Gladyatörler dövüşürken şarapla coşan bir kalabalığı kolayca gözümde canlandırabiliyorum...",
"VO__AMICIA__CH02__CHATTER__JAR_LODGE_ALONE__010__M__1": "Bunca küp... Muhtemelen arena seyircileri için şarap... Bazı şeyler hiç değişmiyor.",
"VO__AMICIA__CH02__CHATTER__KILL__011__M__1": "İnsanlar! Şşşt!",
"VO__AMICIA__CH02__CHATTER__KILL__062__M__1": "Hadi geçelim yeter. Tek ses çıkarma.",
"VO__AMICIA__CH02__CHATTER__KNIFE_GRAB__050__M__1": "Bir bıçak bırakmışlar...",
"VO__AMICIA__CH02__CHATTER__KNIFE_GRAB__053__M__1": "Sıkışmış...",
"VO__AMICIA__CH02__CHATTER__KNIFE_GRAB__055__M__1": "Hadi!",
"VO__AMICIA__CH02__CHATTER__KNIFE_GRAB__057__M__1": "Ha... Neyse, şuradan devam edelim.",
"VO__AMICIA__CH02__CHATTER__KNIFE_GRAB__070__M__1": "Öyle yaptım... Başka çarem yoktu. Bir bıçak sessiz ve hızlıdır. Şimdi ihtiyacımız olan bu.",
"VO__AMICIA__CH02__CHATTER__LADDER_TO_CHEST__010__M__1": "Provence Kontu bu karmaşayla nasıl başa çıkmayı umuyor acaba.",
"VO__AMICIA__CH02__CHATTER__LADDER_TO_CHEST__030__M__1": "Ki bu o paralı askerlerin ortalıkta dolaşmasını engellemiyor.",
"VO__AMICIA__CH02__CHATTER__LEAVE__020__M__1": "Peki, o zaman içeri girelim.",
"VO__AMICIA__CH02__CHATTER__LEDGE_INTERACT__010__M__1": "Hadi bakalım...",
"VO__AMICIA__CH02__CHATTER__LEDGE_INTERACT__030__M__1": "Teşekkürler Lucas!",
"VO__AMICIA__CH02__CHATTER__LET_GO_CRANKS__010__M__1": "İşte bu!",
"VO__AMICIA__CH02__CHATTER__LET_GO_CRANKS__030__M__1": "HADİ!",
"VO__AMICIA__CH02__CHATTER__LIFT_UP__010__M__1": "Ha... Bunu nasıl yaptık?",
"VO__AMICIA__CH02__CHATTER__LIFT_UP__030__M__1": "Yine başlıyor... Bunun ne anlama geldiğinin farkında mısın?",
"VO__AMICIA__CH02__CHATTER__LIFT_UP__050__M__1": "Üzerimize nasıl saldırdıklarını gördün! Hareket edişlerini! Daha hızlılar! Daha çevikler! Daha akıllılar!",
"VO__AMICIA__CH02__CHATTER__LIFT_UP__070__M__1": "Zar zor!",
"VO__AMICIA__CH02__CHATTER__LIFT_UP__090__M__1": "Gerçekten umarım haklısındır...",
"VO__AMICIA__CH02__CHATTER__LIGHT_BRASIER_THROW_OK__010__M__1": "İşte böyle!",
"VO__AMICIA__CH02__CHATTER__LUCAS_WELCOME__040__M__1": "Doğru. Hep birlikte geri dönmemiz gerekecek!",
"VO__AMICIA__CH02__CHATTER__MARKET_FURNITURE_SELLER__010__M__1": "Burada gerçekten çok güzel mobilyalar var...",
"VO__AMICIA__CH02__CHATTER__MARKET_FURNITURE_SELLER__030__M__1": "Elbette yaptın.",
"VO__AMICIA__CH02__CHATTER__MARKET_SELLING_FABRIC__020__M__1": "Bununla yapabileceğin giysileri bir düşün...",
"VO__AMICIA__CH02__CHATTER__MARKET_SELLING_FABRIC__040__M__1": "Çoğuyla ilgileniyorum...",
"VO__AMICIA__CH02__CHATTER__OPEN_CHEST__020__M__1": "Haklıymışsın! Kükürt bu!",
"VO__AMICIA__CH02__CHATTER__POORQUARTER_BLOCKED__010__M__1": "Görünüşe göre bu taraftan panayır yok artık.",
"VO__AMICIA__CH02__CHATTER__PORTCULLIS_RATS__020__M__1": "Tanrım... Şu sayıya bak! Sıkıştık Lucas!",
"VO__AMICIA__CH02__CHATTER__PORTCULLIS_RATS__040__M__1": "Onu nasıl ateşe vereceğiz?!",
"VO__AMICIA__CH02__CHATTER__PORTCULLIS_RATS__060__M__1": "Pekâlâ... Bu odalar artık açık, belki bir şey buluruz.",
"VO__AMICIA__CH02__CHATTER__PUSH_PULL_IDEA__008__M__1": "Sembollerin onu bulmamızı sağlayacağını mı düşünüyorsun?",
"VO__AMICIA__CH02__CHATTER__PUSH_PULL_IDEA__010__M__1": "Yukarı çıkmanın bir yolu olmalı.",
"VO__AMICIA__CH02__CHATTER__PUSH_PULL_VAUDIN__010__M__1": "Vaudin buradaysa, başı dertte.",
"VO__AMICIA__CH02__CHATTER__PUSH_PULL_VAUDIN__030__M__1": "Lucas... buradaki bütün bu insanlar ısırıldıysa, demek ki...",
"VO__AMICIA__CH02__CHATTER__RATS_CLIMB__010__M__1": "İğrenç.",
"VO__AMICIA__CH02__CHATTER__RATS_POURING__010__M__1": "Güvendeyiz... Güvendeyiz... Sakin ol...",
"VO__AMICIA__CH02__CHATTER__REACH_CHEST__010__M__1": "Güzel...",
"VO__AMICIA__CH02__CHATTER__REACH_FOUNTAIN__010__M__1": "Geldik...",
"VO__AMICIA__CH02__CHATTER__RUN__003__M__1": "Bir çıkış görüyor musun?!",
"VO__AMICIA__CH02__CHATTER__SECOND_ELEMENT__020__M__1": "Ignifer... Bunu unutmuştum... Şu diğer odaya bakalım.",
"VO__AMICIA__CH02__CHATTER__SHELTER_GATE__010__M__1": "Kayboluşlarını nasıl olur da kimse fark etmedi?",
"VO__AMICIA__CH02__CHATTER__SHELTER_GATE__030__M__1": "Belki...",
"VO__AMICIA__CH02__CHATTER__SHELTER_INTRO__020__M__1": "Bu insanlar fakir görünüyor...",
"VO__AMICIA__CH02__CHATTER__SKILL_TUTO_INTRO__020__M__1": "Geldik, ama hırsızlardan, katillerden, paralı askerlerden—yolumuza çıkıp duran bütün o lanet ayaktakımından bıktım!",
"VO__AMICIA__CH02__CHATTER__STAIRS_BOTTOM__020__M__1": "Hayır...",
"VO__AMICIA__CH02__CHATTER__STAIRS_BOTTOM__040__M__1": "Ama kısa süre önce buradaydılar. Şu cesetlere bak...",
"VO__AMICIA__CH02__CHATTER__STAIRS_BOTTOM__060__M__1": "Yakınlar, dikkat.",
"VO__AMICIA__CH02__CHATTER__STICK_OK__010__M__1": "Güzel... Bu işe yarar.",
"VO__AMICIA__CH02__CHATTER__STOCK_LODGE_CLOSED__010__M__1": "Sana güveniyorum. Buradan pek göremiyorum...",
"VO__AMICIA__CH02__CHATTER__STORAGE__010__M__1": "Burası nereye çıkıyor?",
"VO__AMICIA__CH02__CHATTER__SULFUR_SMELL_LODGE__005__M__1": "Şu koku...",
"VO__AMICIA__CH02__CHATTER__SULFUR_SMELL_LODGE__020__M__1": "Epey kapalı görünüyor... Aramaya devam edelim.",
"VO__AMICIA__CH02__CHATTER__SUNLIGHT__005__M__1": "Yüksek yer... bu daha iyi...",
"VO__AMICIA__CH02__CHATTER__SUNLIGHT__020__M__1": "Hızlı nefes al. Ne kadar süreceğini bilmiyorum.",
"VO__AMICIA__CH02__CHATTER__SWORDS_STAND__020__M__1": "Hayır. Ben... onları hâlâ sevmiyorum.",
"VO__AMICIA__CH02__CHATTER__SWORDS_STAND__040__M__1": "Kılıçlar... öldürmek içindir.",
"VO__AMICIA__CH02__CHATTER__TAKE_TORCH__020__M__1": "Pekâlâ...",
"VO__AMICIA__CH02__CHATTER__TO_2ND_CRANK__030__M__1": "Umarım!",
"VO__AMICIA__CH02__CHATTER__TO_2ND_CRANK__050__M__1": "Biri bana dünyanın yine çökmek üzere olduğunu söyleseydi...",
"VO__AMICIA__CH02__CHATTER__TO_HUSBAND__020__M__1": "Söyleyecek.",
"VO__AMICIA__CH02__CHATTER__TOP_OF_STAIRS__030__M__1": "Biraz. Ama buna razıyım.",
"VO__AMICIA__CH02__CHATTER__UPHOUSE_ALMOSTTHERE__010__M__1": "Birinin uzun bir günü olmuş.",
"VO__AMICIA__CH02__CHATTER__UPHOUSE_ALMOSTTHERE__050__M__1": "Çok güzel...",
"VO__AMICIA__CH02__CHATTER__UPHOUSE_TALKINGHOME__020__M__1": "Umarım gerçek yatakları vardır.",
"VO__AMICIA__CH02__CHATTER__UPHOUSE_TALKINGHOME__040__M__1": "Bir kralın odası, elbette!",
"VO__AMICIA__CH02__CHATTER__USING_LIFT_LEVER__020__M__1": "Eyvah... Şunu duyuyor musun..?!",
"VO__AMICIA__CH02__CHATTER__USING_LIFT_WRONG__010__M__1": "Bir karşı ağırlık var...",
"VO__AMICIA__CH02__CHATTER__VEGETABLES_SELLER__030__M__1": "Annemin pişirme şeklini sevmiyor musun?",
"VO__AMICIA__CH02__CHATTER__VEGETABLES_SELLER__050__M__1": "Doğru!",
"VO__AMICIA__CH02__CHATTER__VISTA_WALLS__020__M__1": "Bu bölgedeki toprağın bazı yerlerde kırmızı olduğunu duydum! Ona \"Aşı Boyaları\" diyorlar!",
"VO__AMICIA__CH02__CHATTER__WINESTAND_INTERACT__010__M__1": "Ah, bu şarap...",
"VO__AMICIA__CH02__CHATTER__WINESTAND_INTERACT__040__M__1": "Ama o bu şarabı severdi.",
"VO__AMICIA__CH02__CHATTER__WINESTAND_INTERACT__060__M__1": "Öyleydi. Teşekkürler.",
"VO__AMICIA__CH02__CHATTER__WISH_MORE__020__M__1": "Geri geleceğiz!",
"VO__AMICIA__CH02__CHATTER__WRONG_WAY__020__M__1": "Hmmm, haklısın!",
"VO__AMICIA__CH02__HELPER__HAM_USE_CAGES_1_A__010__M__1": "Merdivenler çok uzak... Fareleri uzaklaştıracak bir şey lazım...",
"VO__AMICIA__CH02__HELPER__HAM_USE_CAGES_2_A__010__M__1": "Belki onlara o eti vermek işe yarar... Sadece zinciri kırmam yeter...",
"VO__AMICIA__CH02__HELPER__IGNIFER_USE_CAGES_1_A__010__M__1": "Onları yolumdan çekmek için ışık lazım...",
"VO__AMICIA__CH02__HELPER__IGNIFER_USE_CAGES_2_A__010__M__1": "Duvardaki şu meşale... Onu yakmak yeterli olabilir...",
"VO__AMICIA__CH02__HELPER__IGNIFER_USE_JARS_1_A__010__M__1": "Şu merdivene ulaşmak için daha çok ışık lazım...",
"VO__AMICIA__CH02__HELPER__IGNIFER_USE_JARS_2_A__010__M__1": "Belki şu mangalı indirebilirim... Yeterli olabilir.",
"VO__AMICIA__CH02__ONOM__CRANK_USE_ALONE__020__M__1": "Ha!",
"VO__AMICIA__CH02__ONOM__LIFT_UP__005__M__1": "Vay!",
"VO__AMICIA__CH02__RTC__060_ALIVELYTOWN__001__M__1": "Başardığımıza inanamıyorum...",
"VO__AMICIA__CH02__RTC__060_ALIVELYTOWN__030__M__1": "Simyacının bizi beklediğinden emin misin?",
"VO__AMICIA__CH02__RTC__060_ALIVELYTOWN__120__M__1": "Majesteleri, şehre yanında girmemize izin verir mi?",
"VO__AMICIA__CH02__RTC__060_ALIVELYTOWN__160__M__1": "Teşekkürler!",
"VO__AMICIA__CH02__RTC__060_ALIVELYTOWN__180__M__1": "Anlaşıldı!",
"VO__AMICIA__CH02__RTC__060_ALIVELYTOWN__200__M__1": "Beğendiğin bir şey buldun mu?",
"VO__AMICIA__CH02__RTC__060_ALIVELYTOWN__220__M__1": "Gel! Görülecek başka bir sürü şey vardır!",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__010__M__1": "Evimizdeyiz Hugo! Yeni evimiz! Hadi etrafa bakalım!",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__030__M__1": "Tamam, onu sonra yaparız.",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__040__M__1": "Anne! Hugo'nun odası nerede? Bitkin durumda!",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__060__M__1": "Sağ ol!",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__070__M__1": "Hadi seni uykucu canavar.",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__090__M__1": "Nereye geleyim?",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__110__M__1": "İyileşmek mi? Şey... bu güzel olurdu, eminim.",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__175__M__1": "Hayııır! Hayır! Hugo! Hugo, hayır!",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__176__M__1": "Ve gerekirse seni yine öldürürüm! HEPİNİZİ ÖLDÜRÜRÜM!",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__190__M__1": "Kâbus mu gördü?",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__210__M__1": "Macula...",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__240__M__1": "Hemen.",
"VO__AMICIA__CH02__RTC__070_TOTHEALCHEMIST__260__M__1": "Biliyorum. Dikkatli olacağız.",
"VO__AMICIA__CH02__RTC__090_ENTER_ARENA__010__M__1": "Bu...?",
"VO__AMICIA__CH02__RTC__090_ENTER_ARENA__040__M__1": "Her şey baştan başlıyor.",
"VO__AMICIA__CH02__RTC__090_ENTER_ARENA__050__M__1": "Hadi Magister Vaudin'i bulalım.",
"VO__AMICIA__CH02__RTC__090_ENTER_ARENA__060__M__1": "Çoktan ölmediyse.",
"VO__AMICIA__CH02__RTC__092_RATFIRSTENCOUNTER__015__M__1": "Şey, tek yol bu. Sadece dikkatli ol.",
"VO__AMICIA__CH02__RTC__092_RATFIRSTENCOUNTER__020__M__1": "Lucas!",
"VO__AMICIA__CH02__RTC__092_RATFIRSTENCOUNTER__030__M__1": "Tanrım!",
"VO__AMICIA__CH02__RTC__092_RATFIRSTENCOUNTER__080__M__1": "Çalışıyorum...",
"VO__AMICIA__CH02__RTC__092_RATFIRSTENCOUNTER__110__M__1": "Sakin ol! O adamlarla değiliz... Burada mı yaşıyorsun?",
"VO__AMICIA__CH02__RTC__092_RATFIRSTENCOUNTER__150__M__1": "Meşaleyi düşürme! O sende olduğu sürece sana zarar veremezler!",
"VO__AMICIA__CH02__RTC__092_RATFIRSTENCOUNTER__170__M__1": "Bize gel! Yukarı çıkmalıyız! Güneş bizi korur!",
"VO__AMICIA__CH02__RTC__092_RATFIRSTENCOUNTER__220__M__1": "Çok daha fazla...",
"VO__AMICIA__CH02__RTC__092_RATFIRSTENCOUNTER__230__M__1": "Hareket etmeye devam et!",
"VO__AMICIA__CH02__RTC__092_RATFIRSTENCOUNTER__260__M__1": "Onları görmezden gel! HAREKETE DEVAM!",
"VO__AMICIA__CH02__RTC__092_RATFIRSTENCOUNTER__290__M__1": "KAÇ!",
"VO__AMICIA__CH02__RTC__095_SOUTH_TOWER__050__M__1": "Yollardaki o son aylar... Guyenne'de olan onca şeyden sonra... Hugo hep her şeyin yeniden başlayacağından korkuyordu.",
"VO__AMICIA__CH02__RTC__095_SOUTH_TOWER__065__M__1": "Ama her şey öyle güzel ve sakindi ki! Ve... Ben de ona dedim ki...",
"VO__AMICIA__CH02__RTC__095_SOUTH_TOWER__067__M__1": "...belki bitmiştir. En kötüsü geride kalmıştır.",
"VO__AMICIA__CH02__RTC__095_SOUTH_TOWER__075__M__1": "Ama şimdi ona ne diyeceğiz? Farelerin geri döndüğünü mü? Isırığın yüzlerce kişiyi öldürdüğünü mü? Ve sevdiği bu yeni yuva çoktan ölüyor...",
"VO__AMICIA__CH02__RTC__095_SOUTH_TOWER__077__M__1": "Buna hazır değilim.",
"VO__AMICIA__CH02__RTC__095_SOUTH_TOWER__090__M__1": "Güzel.",
"VO__AMICIA__CH02__RTC__095_SOUTH_TOWER__120__M__1": "Hadi şu Magister Vaudin'i Hugo'ya götürelim.",
"VO__AMICIA__CH02__RTC__100_AN_ALCHEMIST__010__M__1": "Magister Vaudin? Ben Amicia De Rune...",
"VO__AMICIA__CH02__RTC__100_AN_ALCHEMIST__050__M__1": "Şey, başka çarem yoktu.",
"VO__AMICIA__CH02__RTC__100_AN_ALCHEMIST__068__M__1": "Bir ne?",
"VO__AMICIA__CH02__RTC__100_AN_ALCHEMIST__076__M__1": "Durun, ben değilim...",
"VO__AMICIA__CH02__RTC__100_AN_ALCHEMIST__110__M__1": "Kimin umurunda?! Macula yine uyandı! Kardeşimin yardımınıza ihtiyacı var ve fareler çoktan orada!",
"VO__AMICIA__CH02__RTC__100_AN_ALCHEMIST__195__M__1": "Nasılsın?",
"VO__AMICIA__CH02__RTC__100_AN_ALCHEMIST__250__M__1": "Anne...",
"VO__BANDIT_N1__CH02__CHATTER__ARENA_FIELD_AFTER_BANDIT_CHAT__010__M__1": "Burada kalamayız! Hemen kaçmalıyız!",
"VO__BANDIT_N1__CH02__CHATTER__ARENA_FIELD_AFTER_BANDIT_CHAT__030__M__1": "Onlar buralardayken buraya asla ulaşamaz!",
"VO__BANDIT_N1__CH02__CHATTER__ARENA_FIELD_RATS_BANDITRATS__010__M__1": "Hey! Neler oluyor?!",
"VO__BANDIT_N1__CH02__CHATTER__BANDIT_LOOP__030__M__1": "Yalnızsın ve dünyanın bütün zamanı bende. Sadece konuş benimle...",
"VO__BANDIT_N1__CH02__CHATTER__BANDIT_LOOP__050__M__1": "Adamın burada, bir yerlerde olduğunu biliyoruz... Biz biliyorsak, sen de biliyorsun.",
"VO__BANDIT_N1__CH02__CHATTER__BANDIT_LOOTING__010__M__1": "Lanet bir simyacı aramaya geliyoruz, bir toplu mezar buluyoruz... Ama sorun değil, burada oturup ölümü bekleyelim...",
"VO__BANDIT_N1__CH02__CHATTER__GETTING_VAUDIN__020__M__1": "Duymadın mı?! Kayıp adamlarımız var! Burada bir şeyler dönüyor! Hadi simyacıyı alıp bu lanet yerden gidelim!",
"VO__BANDIT_N1__CH02__CHATTER__GETTING_VAUDIN__040__M__1": "Pekâlâ! Sen bilirsin!",
"VO__BANDIT_N1__CH02__CHATTER__KILL__020__M__1": "Nerede o?! Konuş!",
"VO__BANDIT_N1__CH02__CHATTER__KILL__060__M__1": "Seni aşağılık...",
"VO__BANDIT_N1__CH02__CHATTER__MERCENARY_IDLE_1__010__M__1": "Bu kadar çoğunu hiç görmemiştim... Neler oluyor?!",
"VO__BANDIT_N1__CH02__CHATTER__MERCENARY_IDLE_3__020__M__1": "Neredeyse!",
"VO__BANDIT_N2__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_BANDSOLO3__010__M__1": "Bize lazım olan gerçek bir doktor, simyacı değil... Veba bir yana, ama savaş yaraları...",
"VO__BANDIT_N2__CH02__CHATTER__ARCADES_ENCOUNT_INTRO__080__M__1": "Kaynaklarımız tükeniyor! O yüzden yolda değerli ne varsa al!",
"VO__BANDIT_N2__CH02__CHATTER__BANDIT_ALONE_A__020__M__1": "Burada bir köpek gibi ölmene izin verdiği için şu alçak Kont'a teşekkür et.",
"VO__BANDIT_N2__CH02__CHATTER__BANDIT_ALONE_A__030__M__1": "Lanet olsun, çirkin bir ölüm bu...",
"VO__BANDIT_N2__CH02__CHATTER__BANDIT_LOOTING__020__M__1": "O zaman yağmayı kes de şu lanet simyacıyı ara!",
"VO__BANDIT_N2__CH02__CHATTER__BANDITS__020__M__1": "Pöff... Tek bir kuruş yok! Adamımıza odaklansam daha iyi. Onu bulursam ödül isteyebilirim...",
"VO__BANDIT_N2__CH02__CHATTER__INSIDE_BANDITS_CHAT_A__020__M__1": "Hayır, o Vaudin saklanmakta epey iyi diyorum sana.",
"VO__BANDIT_N2__CH02__CHATTER__INSIDE_BANDITS_CHAT_A__040__M__1": "Kahretsin...",
"VO__BANDIT_N2__CH02__CHATTER__INSIDE_BANDITS_KO__010__M__1": "Hmmm? Bir şey mi de— Ah... kahretsin.",
"VO__BANDIT_N2__CH02__CHATTER__RATS_CHASED__010__M__1": "Kahretsin! Kaç! KAÇ!",
"VO__BANDIT_S1__CH02__CHATTER__ARENA_FIELD_RATS_BANDITRATS__020__M__1": "Ne?! Fareler bunlar! Lanet fareler!",
"VO__BANDIT_S1__CH02__CHATTER__GETTING_VAUDIN__010__M__1": "Yani, onu çıkarmak için Arnaud gelene kadar bekliyoruz. Adamlarına söyle, kuleye baskın için hazır olsunlar.",
"VO__BANDIT_S1__CH02__CHATTER__GETTING_VAUDIN__030__M__1": "Arnaud'yu bekliyoruz. Bu bir emir!",
"VO__BANDIT_S1__CH02__CHATTER__MERCENARY_IDLE_2__010__M__1": "Lanet fareler! Burası lanetli... O simyacı yüzünden... Eminim!",
"VO__BANDIT_S1__CH02__CHATTER__MERCENARY_REACT_2__010__M__1": "Bunlar da nereden çıkıyor be?!",
"VO__BANDIT_S2__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_BANDSOLO2__010__M__1": "Kont'un askerleriyle dövüşmek, onu yaparım... Ama bunu mu? Hayır... Böyle bir vebayla dövüşülmez...",
"VO__BANDIT_S2__CH02__CHATTER__ARCADES_ENCOUNT_INTRO__090__M__1": "Hey! Kargalar! Kızarmış kuş isteyen var mı?",
"VO__BANDIT_S2__CH02__CHATTER__ARCADES_ENCOUNT_INTRO__120__M__1": "Hadi ama! Ben ateş edince kaçtılar!",
"VO__BANDIT_S2__CH02__CHATTER__ARENA_FIELD_AFTER_BANDIT_CHAT__020__M__1": "Arnaud ne yapılacağını bilir!",
"VO__BANDIT_S2__CH02__CHATTER__ARENA_FIELD_AFTER_BANDITS_ARNAUD__010__M__1": "Şimdi ne yapmamız gerekiyor be?!",
"VO__BANDIT_S2__CH02__CHATTER__ARENA_FIELD_AFTER_BANDITS_ARNAUD__030__M__1": "Lanet FARELERE karşı mı tutalım?!",
"VO__BANDIT_S2__CH02__CHATTER__ARENA_FIELD_RATS_BANDITRATS__030__M__1": "Bak! Işıktan korkuyorlar! Işık bul!",
"VO__BANDIT_S2__CH02__CHATTER__MERCENARY_IDLE_3__010__M__1": "Yaralanan var mı? Isırılan oldu mu?",
"VO__BANDIT_S2__CH02__CHATTER__MERCENARY_IDLE_3__030__M__1": "Bir şey olursa haber ver!",
"VO__BANDIT_S3__CH02__CHATTER__ARCADES_ENCOUNT_INTRO__035__M__1": "Dağılın! Çevreyi arayın! Eğitiminizi hatırlayın. Arnaud disiplin bekler!",
"VO__BANDIT_S3__CH02__CHATTER__ARCADES_ENCOUNT_INTRO__110__M__1": "Az önce bir cesede ateş ettin, seni salak!",
"VO__BANDIT_S3__CH02__CHATTER__ARCADES_ENCOUNT_INTRO__130__M__1": "Oyunu kes de gözünü dört aç! Yoksa Arnaud geldiğinde neden eli boş olduğumuzu ona sen açıklarsın!",
"VO__BANDIT_S3__CH02__CHATTER__ARCADES_ENCOUNT_UP_INTRO__010__M__1": "Daha çok asker bekliyordum... Neredeler? Belki hastalar ya da... bir şeyler çeviriyorlar...",
"VO__BANDIT_S3__CH02__CHATTER__ARENA_FIELD_AFTER_BANDITS_ARNAUD__020__M__1": "Takviye bekliyoruz! Burayı tutun!",
"VO__BANDIT_S3__CH02__CHATTER__ARENA_FIELD_AFTER_BANDITS_ARNAUD__040__M__1": "Tutun işte, hepsi bu!",
"VO__BANDIT_S3__CH02__CHATTER__BANDIT_LOOTING__010__M__1": "Şey, buradaysa, bu insanları iyileştirmek için pek çaba göstermemiş... Şuna bak, bizden bile fakirler. Tek kuruş yok...",
"VO__BANDIT_S3__CH02__CHATTER__BANDIT_LOOTING__030__M__1": "Biri onu bulur.",
"VO__BANDIT_S3__CH02__CHATTER__INSIDE_BANDITS_CHAT_A__010__M__1": "Eee, doktordan iz var mı? Henüz bir şey duymadım.",
"VO__BANDIT_S3__CH02__CHATTER__INSIDE_BANDITS_CHAT_A__030__M__1": "Ve patron yakında burada olur...",
"VO__BANDIT_S3__CH02__CHATTER__MERCENARY_REACT_1__010__M__1": "Panik yapmayı kes! Işıkta kal, bir şey olmaz!",
"VO__BANDIT_S3__CH02__CHATTER__RATS_CHASED__020__M__1": "Fareler! Geliyorlar!",
"VO__BEATRICE__CH02__RTC__060_ALIVELYTOWN__005__M__1": "Burada kimse bize saldırmaz Hugo. Bu kasaba Provence Kontu'nun korumasında. Çok güçlü bir lord!",
"VO__BEATRICE__CH02__RTC__060_ALIVELYTOWN__040__M__1": "Şey, Magister Vaudin bize bir ev hazırladığını söylemişti.",
"VO__BEATRICE__CH02__RTC__060_ALIVELYTOWN__060__M__1": "Evet! Düzen çok eskidir. Evleri ve çok daha fazlası var!",
"VO__BEATRICE__CH02__RTC__060_ALIVELYTOWN__100__M__1": "Çünkü onlar için çok önemlisin.",
"VO__BEATRICE__CH02__RTC__060_ALIVELYTOWN__150__M__1": "Onunla gidip kısaca bir bak.",
"VO__BEATRICE__CH02__RTC__060_ALIVELYTOWN__170__M__1": "Ev kasabanın yukarı kısmında. Üzerinde bir anka fırıldağı var!",
"VO__BEATRICE__CH02__RTC__060_ALIVELYTOWN__190__M__1": "Ve çok dikkatli olun!",
"VO__BEATRICE__CH02__RTC__070_TOTHEALCHEMIST__050__M__1": "Yukarıda! Yatak hazır!",
"VO__BEATRICE__CH02__RTC__070_TOTHEALCHEMIST__130__M__1": "Çok fazla düşünüyorsun... bazen sadece hislerine güvenmek daha iyidir...",
"VO__BEATRICE__CH02__RTC__070_TOTHEALCHEMIST__150__M__1": "Maddeler doğa yasasına uyar. Macula da öyle. Mantığa ihtiyacın yok Lucas... sadece insan olman yeter.",
"VO__BEATRICE__CH02__RTC__070_TOTHEALCHEMIST__170__M__1": "İnsansın, bu yüzden şüphelerin var.",
"VO__BEATRICE__CH02__RTC__070_TOTHEALCHEMIST__180__M__1": "Hugo...",
"VO__BEATRICE__CH02__RTC__070_TOTHEALCHEMIST__230__M__1": "İkinci eşiği geçtikten sonra altı ay rahat ettik... ama kanının dengesi çok hassas. Amicia, Lucas'la git. Magister Vaudin bu kasabanın bir yerinde. Onu bul ve çabuk gelmesini söyle.",
"VO__BEATRICE__CH02__RTC__070_TOTHEALCHEMIST__250__M__1": "Amicia...",
"VO__BEATRICE__CH02__RTC__100_AN_ALCHEMIST__170__M__1": "Magister Vaudin.",
"VO__BEATRICE__CH02__RTC__100_AN_ALCHEMIST__185__M__1": "Yukarıda.",
"VO__BEATRICE__CH02__RTC__100_AN_ALCHEMIST__205__M__1": "Hugo, bu Magister Vaudin.",
"VO__BEATRICE__CH02__RTC__100_AN_ALCHEMIST__240__M__1": "Ben hallederim.",
"VO__HUGO__CH02__CHATTER__BIG_APPLES__010__M__1": "Meyveler çok büyük...",
"VO__HUGO__CH02__CHATTER__BREAD__010__M__1": "Mmm... Sıcak ekmek! Mmisss!",
"VO__HUGO__CH02__CHATTER__CARPENTER_SPOT__010__M__1": "Vay! Şu testereler kocaman!",
"VO__HUGO__CH02__CHATTER__CARPENTERSTAND_INTERACT__010__M__1": "Bunlar dev insanlar için testere mi?",
"VO__HUGO__CH02__CHATTER__CARPENTERSTAND_INTERACT__030__M__1": "Ben minik değilim!",
"VO__HUGO__CH02__CHATTER__CARPENTERSTAND_INTERACT__032__M__1": "Gülmeyi kes!",
"VO__HUGO__CH02__CHATTER__CARPENTERSTAND_INTERACT__050__M__1": "Gördünüz mü efendim?",
"VO__HUGO__CH02__CHATTER__CHAMBOULETOUT_BARK__011__M__1": "Bir oyun!",
"VO__HUGO__CH02__CHATTER__CHAMBOULETOUT_INTRO__010__M__1": "Öyle!",
"VO__HUGO__CH02__CHATTER__CHAMBOULETOUT_PLAY__050__M__1": "Memleketteki panayır gibi Amicia!",
"VO__HUGO__CH02__CHATTER__CHAMEBOULETOUT_BYE__020__M__1": "Güle güle efendim!",
"VO__HUGO__CH02__CHATTER__CHAMEBOULETOUT_FAILURE__020__M__1": "Sorun değil! Sapanla daha iyisin!",
"VO__HUGO__CH02__CHATTER__CHAMEBOULETOUT_SUPPORT__020__M__1": "Evet!",
"VO__HUGO__CH02__CHATTER__CHAMEBOULETOUT_SUPPORT__030__M__1": "Harikasın!",
"VO__HUGO__CH02__CHATTER__CHAMEBOULETOUT_SUPPORT__040__M__1": "Az kalsın!",
"VO__HUGO__CH02__CHATTER__CHAMEBOULETOUT_SUPPORT__060__M__1": "Devam et!",
"VO__HUGO__CH02__CHATTER__CHAMEBOULETOUT_WIN__020__M__1": "Bir sürüsünü vurdun!",
"VO__HUGO__CH02__CHATTER__CHAMEBOULETOUT_WIN__050__M__1": "Hem de sapanını kullanmadan!",
"VO__HUGO__CH02__CHATTER__CONCERT_ENDS__020__M__1": "Ah, şimdiden mi?",
"VO__HUGO__CH02__CHATTER__CONCERT_FAR__010__M__1": "Ho! Müzik çalıyorlar!",
"VO__HUGO__CH02__CHATTER__CONCERT_INTERACT__009__M__1": "Ah evet, lütfen!",
"VO__HUGO__CH02__CHATTER__CONCERT_INTRO__010__M__1": "Ah, göremiyorum...",
"VO__HUGO__CH02__CHATTER__CONCERT_INTRO__012__M__1": "Evet! Her şeyi görebiliyorum!",
"VO__HUGO__CH02__CHATTER__CONCERT_INTRO__020__M__1": "Yaşasın! Yaşasın!",
"VO__HUGO__CH02__CHATTER__CONCERT_SINGING__010__M__1": "Bu müzik komik!",
"VO__HUGO__CH02__CHATTER__CONCERT_SINGING__030__M__1": "Çok iyiler!",
"VO__HUGO__CH02__CHATTER__FIRE_BREATHER__010__M__1": "Vaay!",
"VO__HUGO__CH02__CHATTER__FIRE_BREATHER__030__M__1": "Bunu nasıl yapıyor?",
"VO__HUGO__CH02__CHATTER__FIRE_BREATHER__050__M__1": "Bir insan-ejderha!",
"VO__HUGO__CH02__CHATTER__FIRE_BREATHER__070__M__1": "Eminim Lucas da ateş püskürebilir.",
"VO__HUGO__CH02__CHATTER__FORGE__010__M__1": "Tıpkı evimizdeki gibi!",
"VO__HUGO__CH02__CHATTER__FORGE__030__M__1": "Çok terliyordur...",
"VO__HUGO__CH02__CHATTER__FOUNTAIN__020__M__1": "İçine atlamak isterdim!",
"VO__HUGO__CH02__CHATTER__HALLES_CRIT_HERBORIST_CALL__010__M__1": "Bak! Çiçekler!",
"VO__HUGO__CH02__CHATTER__HALLES_CRIT_HERBORIST_CHAT__010__M__1": "Ah, kadife çiçekleri! Çuha çiçekleri!",
"VO__HUGO__CH02__CHATTER__HALLES_CRIT_HERBORIST_CHAT__030__M__1": "Sadece çiçekler. Annem öğretti. Evde bir kitapta saklardık.",
"VO__HUGO__CH02__CHATTER__HALLES_CRIT_HERBORIST_CHAT__060__M__1": "Evet, gel, gerisini görelim!",
"VO__HUGO__CH02__CHATTER__HALLES_EVENT_ITALY_INTERACT__050__M__1": "Saçın böyle güzel.",
"VO__HUGO__CH02__CHATTER__HALLES_INTRO__020__M__1": "Ah! Tam pazarın üstünde!",
"VO__HUGO__CH02__CHATTER__HALLES_LEAVING__020__M__1": "Ah, istersen odamı paylaşabiliriz?",
"VO__HUGO__CH02__CHATTER__HALLES_LEAVING__040__M__1": "Bilmem...",
"VO__HUGO__CH02__CHATTER__HALLES_LEAVING__060__M__1": "Evet! Burayı çok seviyorum!",
"VO__HUGO__CH02__CHATTER__HOUSE_ARRIVAL__010__M__1": "Ooo...",
"VO__HUGO__CH02__CHATTER__HOUSE_HUGOLUCAS__010__M__1": "Lucas!",
"VO__HUGO__CH02__CHATTER__HOUSE_LUCASCHAT__030__M__1": "Geldiğimize sevindim...",
"VO__HUGO__CH02__CHATTER__HOUSE_LUCASCHAT__050__M__1": "Yorgun değilim!",
"VO__HUGO__CH02__CHATTER__HUBT1_ALLEY__010__M__1": "Gördün mü?",
"VO__HUGO__CH02__CHATTER__HUBT1_ALLEY__030__M__1": "Buradaki insanlar gülümsüyor.",
"VO__HUGO__CH02__CHATTER__HUBT1_BURGUNDY__010__M__1": "Güzeldi! Şimdi acıktım!",
"VO__HUGO__CH02__CHATTER__HUBT1_ENTERING__010__M__1": "Nereden başlıyoruz?",
"VO__HUGO__CH02__CHATTER__HUBT1_ENTERING__030__M__1": "Her şeyden!",
"VO__HUGO__CH02__CHATTER__HUBT1_MEATSTAND__040__M__1": "Ah...",
"VO__HUGO__CH02__CHATTER__HUBT1_MEATSTAND__041__M__1": "Misss!",
"VO__HUGO__CH02__CHATTER__HUBT1_MEATSTAND__050__M__1": "Evet, ama... domuzcuk değil, değil mi?",
"VO__HUGO__CH02__CHATTER__HUBT1_UPHOUSE_CARRY_FAIR__010__M__1": "Buradaki insanlar kötü şeyleri bilmiyor gibi.",
"VO__HUGO__CH02__CHATTER__HUBT1_UPHOUSE_CARRY_FAIR__030__M__1": "Dışarıda olup biten her şeyi.",
"VO__HUGO__CH02__CHATTER__HUBT1_UPHOUSE_DROP__020__M__1": "Evet! Evi görmek için sabırsızlanıyorum!",
"VO__HUGO__CH02__CHATTER__HUBT1_VIEW_FISH__010__M__1": "Ne çok balık!",
"VO__HUGO__CH02__CHATTER__HUBT1_VIEW_FISH__030__M__1": "Ah evet, bir sürü alacağız!",
"VO__HUGO__CH02__CHATTER__IDLE_MARKET_4__010__M__1": "Burayı çoook, çoook seviyorum!",
"VO__HUGO__CH02__CHATTER__IDLE_MARKET_MOM__020__M__1": "Annemle ve Lucas'la geri geleceğiz!",
"VO__HUGO__CH02__CHATTER__IDLE_MARKET_PEOPLE__010__M__1": "Ne çok insan var... Hepsi burada mı yaşıyor?",
"VO__HUGO__CH02__CHATTER__INSTRUMENTSTAND_INTERACT__040__M__1": "Ama o iyi nişancı!",
"VO__HUGO__CH02__CHATTER__LUCAS_WELCOME__030__M__1": "HER ŞEYLERİ var!",
"VO__HUGO__CH02__CHATTER__MARKET_FURNITURE_SELLER__020__M__1": "Odamda öyle bir dolap vardı! İçine saklanmayı severdim.",
"VO__HUGO__CH02__CHATTER__MARKET_SELLING_FABRIC__010__M__1": "Renklere bak!",
"VO__HUGO__CH02__CHATTER__PIGGIES__010__M__1": "Merhaba domuzcuklar!",
"VO__HUGO__CH02__CHATTER__SWORDS_STAND__010__M__1": "Kılıçlar... Bir tane istemez miydin?",
"VO__HUGO__CH02__CHATTER__SWORDS_STAND__030__M__1": "Ama dövüşmeyi biliyorsun!",
"VO__HUGO__CH02__CHATTER__UPHOUSE_ALMOSTTHERE__040__M__1": "Ve burası daha az sıcak.",
"VO__HUGO__CH02__CHATTER__UPHOUSE_SINGING__010__M__1": "Elbette!",
"VO__HUGO__CH02__CHATTER__UPHOUSE_TALKINGHOME__010__M__1": "Ne kadar büyük acaba...",
"VO__HUGO__CH02__CHATTER__UPHOUSE_TALKINGHOME__030__M__1": "Umarım odamdan pazarı görebilirim!",
"VO__HUGO__CH02__CHATTER__VEGETABLES_SELLER__020__M__1": "İğrenç! İnsanlar bunu nasıl yiyor?",
"VO__HUGO__CH02__CHATTER__VEGETABLES_SELLER__040__M__1": "Dişlerime tuhaf bir şey yapıyor...",
"VO__HUGO__CH02__CHATTER__VISTA_WALLS__010__M__1": "Amicia... Duvarlar neden kırmızı?",
"VO__HUGO__CH02__CHATTER__VISTA_WALLS__030__M__1": "Aşı Boyaları...",
"VO__HUGO__CH02__CHATTER__WINESTAND_INTERACT__030__M__1": "O öldü...",
"VO__HUGO__CH02__CHATTER__WISH_MORE__010__M__1": "Keşke biraz daha kalabilseydik...",
"VO__HUGO__CH02__CHATTER__WRONG_WAY__010__M__1": "Pazara mı dönüyoruz? Ev bu tarafta değil.",
"VO__HUGO__CH02__RTC__060_ALIVELYTOWN__003__M__1": "Buradaki insanlar iyi mi?",
"VO__HUGO__CH02__RTC__060_ALIVELYTOWN__050__M__1": "Koca bir ev mi?",
"VO__HUGO__CH02__RTC__060_ALIVELYTOWN__090__M__1": "Evet! Bize bir ev vermeleri güzel!",
"VO__HUGO__CH02__RTC__060_ALIVELYTOWN__130__M__1": "İzin veriyorum!",
"VO__HUGO__CH02__RTC__060_ALIVELYTOWN__140__M__1": "Vaah! Bu bir panayır mı?",
"VO__HUGO__CH02__RTC__060_ALIVELYTOWN__210__M__1": "Burada her şeyi seviyorum!",
"VO__HUGO__CH02__RTC__070_TOTHEALCHEMIST__020__M__1": "Hmm... Evet...",
"VO__HUGO__CH02__RTC__070_TOTHEALCHEMIST__080__M__1": "Gelmelisin Amicia...",
"VO__HUGO__CH02__RTC__070_TOTHEALCHEMIST__100__M__1": "Ada... Sen de orada iyileşeceksin...",
"VO__HUGO__CH02__RTC__070_TOTHEALCHEMIST__120__M__1": "Olacak...",
"VO__HUGO__CH02__RTC__070_TOTHEALCHEMIST__177__M__1": "Amicia!",
"VO__HUGO__CH02__RTC__100_AN_ALCHEMIST__200__M__1": "Korkuyorum...",
"VO__HUGO__CH02__RTC__100_AN_ALCHEMIST__220__M__1": "Merhaba...",
"VO__ISLANDER_F1__CH02__CHATTER__SMALLTALK_GUYENNE__010__M__1": "Kapatma sadece bir önlem. Arena domuzları yüzünden, bilirsin...",
"VO__ISLANDER_F1__CH02__CHATTER__SMALLTALK_GUYENNE__030__M__1": "Hasta hâlde ölmüş... Orası cehennem gibi kokuyor.",
"VO__KID_M1__CH02__CHATTER__FIRE_CROWD__010__M__1": "Vaaah!",
"VO__LUCAS__CH02__CHATTER__2ND_SYMBOL__020__M__1": "Ah... Midem bulanacak...",
"VO__LUCAS__CH02__CHATTER__ACROSS__010__M__1": "Ben... Yardım lazım! Peşimdeler!",
"VO__LUCAS__CH02__CHATTER__ACROSS__030__M__1": "Şimdilik!",
"VO__LUCAS__CH02__CHATTER__ACROSS_COMING__010__M__1": "Pekâlâ. Hızlı ol. Cesur ol ve bu sefer düşme.",
"VO__LUCAS__CH02__CHATTER__ACROSS_COMING__030__M__1": "Onun için çok geç!",
"VO__LUCAS__CH02__CHATTER__ACROSS_RATS__010__M__1": "Aman Tanrım, çok, çok yakınlar...",
"VO__LUCAS__CH02__CHATTER__ARCADES_DISPENS_AFTER__020__M__1": "Yani, ısırığı mı?",
"VO__LUCAS__CH02__CHATTER__ARCADES_DISPENS_AFTER__040__M__1": "Asıl soru şu—fareleri durduracak mı? Henüz bilmiyorum.",
"VO__LUCAS__CH02__CHATTER__ARCADES_DISPENS_AFTER__060__M__1": "Buradalarsa...",
"VO__LUCAS__CH02__CHATTER__ARCADES_DISPENS_INTRO__040__M__1": "Şunu kokluyor musun?",
"VO__LUCAS__CH02__CHATTER__ARCADES_DISPENS_INTRO__060__M__1": "Burası neresi? Bir hastane mi?",
"VO__LUCAS__CH02__CHATTER__ARCADES_DISPENS_INTRO__080__M__1": "Hepsinin hastalanmasına şaşmamalı.",
"VO__LUCAS__CH02__CHATTER__ARCADES_DISPENS_SKILL_TUTO__010__M__1": "Orada epey gizliydin...",
"VO__LUCAS__CH02__CHATTER__ARCADES_DISPENS_SKILL_TUTO__025__M__1": "Orada pek canlı bırakmadın...",
"VO__LUCAS__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_BRIDGE__020__M__1": "Okçu...",
"VO__LUCAS__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_FIRSTBLOOD__020__M__1": "Dikkat... Burada olduğumuzu anlarlarsa...",
"VO__LUCAS__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_INTRO__020__M__1": "O, onlardan daha akıllı...",
"VO__LUCAS__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_INTRO__040__M__1": "Haklısın.",
"VO__LUCAS__CH02__CHATTER__ARCADES_ENCOUNT_GROUND_LEFT__020__M__1": "Nefes almaya çalış. İlerleme kaydediyoruz.",
"VO__LUCAS__CH02__CHATTER__ARCADES_ENCOUNT_INTRO__090__M__1": "Bozulmuş askerler. Kulağa hiç iyi gelmiyor.",
"VO__LUCAS__CH02__CHATTER__ARCADES_ENCOUNT_UP_ARCHER__009__M__1": "Dikkatli ol.",
"VO__LUCAS__CH02__CHATTER__ARCADES_PP_CART_PUSH__020__M__1": "Bir katliam...",
"VO__LUCAS__CH02__CHATTER__ARCADES_PP_CART_PUSH__050__M__1": "Guyenne'de hâlâ sürüyor. Şimdiden yayılıyor.",
"VO__LUCAS__CH02__CHATTER__ARCADES_PP_CART_PUSH__070__M__1": "Hiçbir şeyi değiştirmezdi.",
"VO__LUCAS__CH02__CHATTER__ARCADES_PP_CART_UP__010__M__1": "Burada bir tür... yarım araba var... Ama yeterince yüksek değil... Sanırım cesetleri onunla taşıyorlardı.",
"VO__LUCAS__CH02__CHATTER__ARCADES_PP_CART_UP__030__M__1": "Ha... Cesetlerle dolu...",
"VO__LUCAS__CH02__CHATTER__ARCADES_PP_INTRO_HELPER__010__M__1": "Yukarıda... İçeri geri götürüyor gibi...",
"VO__LUCAS__CH02__CHATTER__ARCADES_PP_INTRO2__020__M__1": "Onu doktor sanıyorlar!",
"VO__LUCAS__CH02__CHATTER__ARCADES_TOWER__020__M__1": "Sembol! O kulede! Orada olmalı!",
"VO__LUCAS__CH02__CHATTER__ARCADES_TOWER__040__M__1": "Düzen bu. Yüksek bir magister sadece... yüksek kulede yaşardı, değil mi?",
"VO__LUCAS__CH02__CHATTER__ARCADES_UP_HOMES__020__M__1": "Şimdiden o kadar çok ölü var ki... sanki... bizden bir adım önde.",
"VO__LUCAS__CH02__CHATTER__ARCADES_UP_KNIFE__005__M__1": "Bak... Sanırım ölülerin sayısını tutuyorlardı.",
"VO__LUCAS__CH02__CHATTER__ARENA_COMMUNE_CHAPEL__010__M__1": "Derme çatma bir şapel... Dua etmek... ister misin? Yardımı olur diye düşünüyorsan...",
"VO__LUCAS__CH02__CHATTER__ARENA_COMMUNE_FLOWER__020__M__1": "Onu eken kişi büyüdüğünü göremeyecek.",
"VO__LUCAS__CH02__CHATTER__ARENA_COMMUNE_FLOWER__040__M__1": "Sana yakışıyor.",
"VO__LUCAS__CH02__CHATTER__ARENA_COMMUNE_FLOWER_CALL__010__M__1": "Bir sebze bahçesi... Ah, şuna bak!",
"VO__LUCAS__CH02__CHATTER__ARENA_COMMUNE_GALLERY__020__M__1": "Yine de en güvenli yer gibi görünüyor.",
"VO__LUCAS__CH02__CHATTER__ARENA_COMMUNE_SQUARE__010__M__1": "Burası aslında epey güzel görünüyordu...",
"VO__LUCAS__CH02__CHATTER__ARENA_COMMUNE_START__020__M__1": "Umarım bu onu buldukları anlamına gelmez...",
"VO__LUCAS__CH02__CHATTER__ARENA_FIELD_AFTER_NEAR__020__M__1": "Neredeyse vardık!",
"VO__LUCAS__CH02__CHATTER__ARENA_FIELD_INTRO__010__M__1": "Gerçekten kulede!",
"VO__LUCAS__CH02__CHATTER__ARENA_FIELD_INTRO__030__M__1": "Evet, şefleri gelmeden Magister Vaudin'i çıkarmalıyız!",
"VO__LUCAS__CH02__CHATTER__ARENA_FIELD_RATS_HEROES__010__M__1": "Çıkıyorlar!",
"VO__LUCAS__CH02__CHATTER__ARENA_REUNITED_INTRO__010__M__1": "Berbattı... Teşekkürler.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_AMICIA_MOVES__010__M__1": "Evet!... Ah! Bak!",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_DONE__010__M__1": "O duvar bir kapı! Çok ilkel!",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_INTRO__010__M__1": "Bir giriş holü bu...",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_INTRO__030__M__1": "Kapı görmüyorum. Ama şu tür demir çanlar var. Bak, gezegen sembolleri taşıyorlar. Ve burada, Güneş tam ortalarında. Gezegenlerin sırası doğru değil.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_INTRO__050__M__1": "Her çanın altında anahtar için kilitler var. Tek bir büyük mekanizma!",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_INTRO__070__M__1": "Sanırım anahtar her çanı döndürüyor, ama belki sapanın da işe yarar. Soldan başlayalım!",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_JUPITER_AMICIA__010__M__1": "İşte bu, Jüpiter!",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_JUPITER_HELPER__020__M__1": "Jüpiter'in sembolü Z'ye benziyor. Zeus'taki gibi.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_MARS_HELPER__010__M__1": "Jüpiter'in sağında Mars var. Savaş tanrısı.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_MARS_HELPER__020__M__1": "Bir mızrakla çaprazlanmış bir kalkan.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_MARS_HELPER__030__M__1": "Mars, içinden bir çizgi geçen bir daire olmalı.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_MERCURY_HELPER__010__M__1": "Sonuncusu Merkür. Ticaret tanrısı.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_MERCURY_HELPER__020__M__1": "İç içe geçmiş iki yılanlı bir asa taşır.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_MERCURY_HELPER__030__M__1": "Merkür'ün sembolü iç içe geçmiş iki yılan.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_PUZZLEPLAN__010__M__1": "Soldan sağa doğru sıra... Jüpiter, Mars, Güneş, Venüs ve Merkür.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_VENUS_AMICIA__020__M__1": "Evet!",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_VENUS_HELPER__010__M__1": "Şimdi, Güneş'in sağındaki ilk gezegen Venüs.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_VENUS_HELPER__020__M__1": "Bir kolyeye benziyor.",
"VO__LUCAS__CH02__CHATTER__ARENA_TOWER_VENUS_HELPER__030__M__1": "Aşağı inen bir çizgisi olan bir daire ara.",
"VO__LUCAS__CH02__CHATTER__ARENA_UP_AFTERDOOR__010__M__1": "Yine mi aşağı iniyoruz?!",
"VO__LUCAS__CH02__CHATTER__ARENA_UP_AFTERDOOR__030__M__1": "Şaka bu...",
"VO__LUCAS__CH02__CHATTER__ARENA_UP_AFTERDOOR__050__M__1": "Annen onun yanında. İyi olmalı.",
"VO__LUCAS__CH02__CHATTER__ARENA_UP_VAUDIN__010__M__1": "Belki o kuleye daha yakın bir yerden çıkarız?",
"VO__LUCAS__CH02__CHATTER__ARENA_UP_VAUDIN__020__M__1": "Magister Vaudin'in bu konudaki planını duymak için sabırsızlanıyorum.",
"VO__LUCAS__CH02__CHATTER__ARENA_UP_VAUDIN__040__M__1": "Olacak.",
"VO__LUCAS__CH02__CHATTER__ARMS_READY__020__M__1": "İşaretini bekliyorum!",
"VO__LUCAS__CH02__CHATTER__BACKSTAGE_ENTRANCE__020__M__1": "Duvarlarda raylar... Bir asansöre benziyor! Bir çıkış yolu olabilir!",
"VO__LUCAS__CH02__CHATTER__BANDITS__011__M__1": "Ama biri gibi giyinmiş.",
"VO__LUCAS__CH02__CHATTER__BANDITS__040__M__1": "Amicia, bizi görecek...",
"VO__LUCAS__CH02__CHATTER__BASE_BRASERO_HELPER__040__M__1": "Korlar... Şurada bir mangal var!",
"VO__LUCAS__CH02__CHATTER__BASE_FALL_CROSSING__020__M__1": "Vay... Pekâlâ...",
"VO__LUCAS__CH02__CHATTER__BASE_FALL_LUCASFALLS__030__M__1": "Biliyordum!",
"VO__LUCAS__CH02__CHATTER__BASE_FALL_LUCASFALLS__050__M__1": "Hayır! Etrafım sarıldı!",
"VO__LUCAS__CH02__CHATTER__BASE_FALL_LUCASFALLS__070__M__1": "Evet!",
"VO__LUCAS__CH02__CHATTER__BASE_FALL_LUCASFALLS__080__M__1": "Tabii ki benim başıma gelecekti...",
"VO__LUCAS__CH02__CHATTER__BASE_FALL_START__010__M__1": "Gerçekten mi? Bir kiriş mi?",
"VO__LUCAS__CH02__CHATTER__BASE_INTRO_RATS__010__M__1": "Evet... Ben... Nefes almam lazım...",
"VO__LUCAS__CH02__CHATTER__BASE_INTRO_RATS__060__M__1": "Bundan kurtulabileceğimizi düşünüyor musun?",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM1_CLIMB__020__M__1": "Bak! Tırmanıyorlar!",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM1_CLIMB__040__M__1": "Bu çok kötü...",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM1_FURTHER__010__M__1": "Malzemelerim... Düşerken hepsini kaybettim...",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM1_FURTHER__030__M__1": "Evet... Lütfen, şu meşaleyi düşürme...",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM1_TORCHHOLD__030__M__1": "Meşaleyi geride bıraktığımıza inanamıyorum.",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_BRASEROFREE__010__M__1": "İşe yaramalı! Onu yakma vakti!",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_BRASEROFURTHER__010__M__1": "Güzel. Tek seferde bir mangal.",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_BRASEROLIGHTUP__020__M__1": "O zincirdeki kilit zayıf görünüyor...",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_BRASEROOFF__010__M__1": "Yukarıdaki şu mangal...",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_EXIT__005__M__1": "Evet! Aferin!",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_SPOTLADDER__020__M__1": "Bir merdiven var!",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_START__020__M__1": "Ne yapacağız?!",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_STICKFIRST__009__M__1": "Çabuk ol.",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_STICKFIRST__010__M__1": "Gerçekten yüksek bir yere çıkmalıyız...",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_STICKFIRST__030__M__1": "Şimdilik...",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_WHERE__009__M__1": "Hızlı yanacak...",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_WHERE__011__M__1": "Evet. Dümdüz.",
"VO__LUCAS__CH02__CHATTER__BASE_ROOM2_WHERE__030__M__1": "Evet. Onları çıkmaktan hiçbir şey alıkoyamaz...",
"VO__LUCAS__CH02__CHATTER__BIG_CART_DEAD_END__020__M__1": "Tıpkı... et parçaları gibi...",
}
