# -*- coding: utf-8 -*-
# CH01 VO altyazilari. onom/EMPTY yer tutuculari atlanir (sozlukte yok).
# Sen/siz: kardesler+Lucas+Tonin=sen; yabanci sorgucular<->Beatrice=siz; haydutlar->Amicia=asagilayici sen.
T = {
"VO__AMICIA__CH01__CHATTER__2ND_BEEKEEPER__020__M__1": "Buradan deneyelim...",
"VO__AMICIA__CH01__CHATTER__2ND_BEEKEEPER__030__M__1": "Dur! Bekle...",
"VO__AMICIA__CH01__CHATTER__2ND_BEEKEEPER__040__M__1": "Şimdi...",
"VO__AMICIA__CH01__CHATTER__2ND_DISTRACT__010__M__1": "Tırmanmamız gerekecek. Sessizce.",
"VO__AMICIA__CH01__CHATTER__AFTER_2ND_DISTRACT__040__M__1": "Belki... hâlâ uzaktadır...",
"VO__AMICIA__CH01__CHATTER__AFTER_DISTRACT__010__M__1": "Arabaya dönüp bu yerden uzaklaşalım.",
"VO__AMICIA__CH01__CHATTER__AFTER_DISTRACT__030__M__1": "Ona söylemeyiz işte. Zaten arabaya varır varmaz gideceğiz.",
"VO__AMICIA__CH01__CHATTER__AFTER_DOOR__010__M__1": "Bilmiyorum. Bir çıkış yolu lazım.",
"VO__AMICIA__CH01__CHATTER__AFTER_DROP__010__M__1": "Dikkat... Yaparsın sen.",
"VO__AMICIA__CH01__CHATTER__AFTER_DROP__050__M__1": "Devam et...",
"VO__AMICIA__CH01__CHATTER__AFTER_FALL__010__M__1": "Hayır...",
"VO__AMICIA__CH01__CHATTER__AFTER_FALL__017__M__1": "Sapanım... Hâlâ arabada... Devam et... Eğil...",
"VO__AMICIA__CH01__CHATTER__AFTER_FALL__020__M__1": "Araba... Sana ihtiyaçları var... Hugo'nun sana ihtiyacı var...",
"VO__AMICIA__CH01__CHATTER__AFTER_FALL__070__M__1": "Evet... Git buradan...",
"VO__AMICIA__CH01__CHATTER__AFTER_STUNG__020__M__1": "Evet... Daha dikkatli olmalıyız.",
"VO__AMICIA__CH01__CHATTER__AFTER_THE_WAR__014__M__1": "Öyleydi, evet.",
"VO__AMICIA__CH01__CHATTER__ARRIVAL_RUINS__030__M__1": "Yeni evini sevdim!",
"VO__AMICIA__CH01__CHATTER__ARRIVAL_RUINS__050__M__1": "Pekâlâ...",
"VO__AMICIA__CH01__CHATTER__BEATRICE_SCREAM__020__M__1": "Anne... Hadi... Hadi...",
"VO__AMICIA__CH01__CHATTER__BEATRICE_SCREAM__030__M__1": "Hayır!",
"VO__AMICIA__CH01__CHATTER__BEATRICE_VOICE__020__M__1": "Anne! Geliyorum!",
"VO__AMICIA__CH01__CHATTER__BROTHER_BACK__050__M__1": "Geçemeyiz... Yolu kesmişler...",
"VO__AMICIA__CH01__CHATTER__BROTHERS_ARRIVAL__030__M__1": "Eğil! Çabuk!",
"VO__AMICIA__CH01__CHATTER__BROTHERS_ARRIVAL__140__M__1": "Şşşt!",
"VO__AMICIA__CH01__CHATTER__BROTHERS_ARRIVAL__150__M__1": "Hayır...",
"VO__AMICIA__CH01__CHATTER__CHARGE__010__M__1": "Şimdi! HÜCUM!",
"VO__AMICIA__CH01__CHATTER__CHARGE_FAIL__020__M__1": "Bir bakayım!",
"VO__AMICIA__CH01__CHATTER__CHASED__020__M__1": "Bize bir çıkış lazım!",
"VO__AMICIA__CH01__CHATTER__CLIMB_TUTO__010__M__1": "Hmmm, buraya tırmanmamız gerekecek. Bu sefer sen beni yukarı çek.",
"VO__AMICIA__CH01__CHATTER__CLIMB_TUTO__035__M__1": "Şaka yapıyorum. Sana yardım edeceğim.",
"VO__AMICIA__CH01__CHATTER__CLIMB_TUTO__043__M__1": "Ne cüretle?!",
"VO__AMICIA__CH01__CHATTER__CLOSE_TO_RIVER__010__M__1": "Eee?",
"VO__AMICIA__CH01__CHATTER__CLOSE_TO_RIVER__030__M__1": "O dal senin sınırın mı?",
"VO__AMICIA__CH01__CHATTER__CLOSE_TO_RIVER__050__M__1": "Neden olmasın...",
"VO__AMICIA__CH01__CHATTER__CLOSE_TO_RIVER__070__M__1": "Eyvah! Ne yapacağız?!",
"VO__AMICIA__CH01__CHATTER__CLOSE_TO_RIVER__090__M__1": "Anladım! Güçlü sapanım emrinde!",
"VO__AMICIA__CH01__CHATTER__CLOSED_DOOR_HURRY__010__M__1": "Hayır! Hayır!",
"VO__AMICIA__CH01__CHATTER__CLOSED_DOOR_HURRY__020__M__1": "Gel!",
"VO__AMICIA__CH01__CHATTER__COURTYARD_RUIN__010__M__1": "Bir çıkış için gözünü dört aç!",
"VO__AMICIA__CH01__CHATTER__CROUCH_PROGRESS__010__M__1": "Buradan çıkmalıyız!",
"VO__AMICIA__CH01__CHATTER__CROUCH_PROGRESS__030__M__1": "Delirmişler bunlar...",
"VO__AMICIA__CH01__CHATTER__DEBRIEF_TONIN__020__M__1": "Biliyorum... Ama yakında yerleşeceğiz ve arkadaşlar edineceksin!",
"VO__AMICIA__CH01__CHATTER__DEBRIEF_TONIN__040__M__1": "Durumunun nasıl olduğunu öğrenir öğrenmez.",
"VO__AMICIA__CH01__CHATTER__DEBRIEF_TONIN__060__M__1": "Bu sefer değil. Bu sefer farklı. Biliyorum!",
"VO__AMICIA__CH01__CHATTER__DISCOVER_RIVER__020__M__1": "Çok güzel...",
"VO__AMICIA__CH01__CHATTER__DOOR_OPENING__010__M__1": "Sımsıkı kilitli!",
"VO__AMICIA__CH01__CHATTER__DOOR_OPENS__020__M__1": "Evet! Aferin!",
"VO__AMICIA__CH01__CHATTER__DROP_ARROW__030__M__1": "Şu sapanı al, çabuk, çabuk!",
"VO__AMICIA__CH01__CHATTER__DROP_ARROW__035__M__1": "Hadi! Evet...",
"VO__AMICIA__CH01__CHATTER__EMERGENCY_TUTO_OK__030__M__1": "Gidelim!",
"VO__AMICIA__CH01__CHATTER__ENCOUNTER_2_KILL__020__M__1": "İşte buyur, hak ettin!",
"VO__AMICIA__CH01__CHATTER__ENCOUNTER_2_KILL__030__M__1": "Hadi... Kımılda!",
"VO__AMICIA__CH01__CHATTER__ENCOUNTER_2_KILL__040__M__1": "Çabuk... O tepenin aşağısında olmalılar...",
"VO__AMICIA__CH01__CHATTER__ENCOUNTER_2_KILL__043__M__1": "Olmamalıydı...",
"VO__AMICIA__CH01__CHATTER__ENCOUNTER_2_KILL__046__M__1": "Aptal... Aptal!",
"VO__AMICIA__CH01__CHATTER__ENCOUNTER_2_KILL__050__M__1": "Artık... güvenli. Kımılda!",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_BEFORE_DROP__010__M__1": "Bu taraftan...",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_BEFORE_DROP__030__M__1": "İnsanlar nerede?",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_COLLAPSE__010__M__1": "Vay!",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_EXPLORE_ROOM__020__M__1": "Burada insanlar yaşıyor.",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_EXPLORE_ROOM__040__M__1": "Şimdilik... sadece dikkatli olalım.",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_FALLEN__010__M__1": "Ha... ha... İncindin mi?!",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_FALLEN__030__M__1": "Ben... katılıyorum. Bugünlük bu kadar yeter.",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_FLOOR__010__M__1": "Yanındayım, merak etme.",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_FLOOR__030__M__1": "Ah, sanırım büyücünün adamları yakınımızda...",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_OUTSIDE__010__M__1": "Ne?!...",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_OUTSIDE__030__M__1": "Yeni olmuş...",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_OUTSIDE__050__M__1": "Bu sepetler... arı kovanı bunlar...",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_OUTSIDE__070__M__1": "Bilmiyorum! Sessiz olalım ve çıkalım...",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_STAIRS__005__M__1": "Ah, çevremizde bir kötülük hissediyorum...",
"VO__AMICIA__CH01__CHATTER__ENTER_CASTLE_STAIRS__020__M__1": "Hadi kralım! İçeri sızacağımızı beklemiyorlar...",
"VO__AMICIA__CH01__CHATTER__ENTER_THE_CASTLE__020__M__1": "Ne dersin? Ona saldıralım mı?",
"VO__AMICIA__CH01__CHATTER__EXIT_DOOR__010__M__1": "Şuradaki kapı... onu deneyelim...",
"VO__AMICIA__CH01__CHATTER__EXIT_HOUSE__010__M__1": "Dikkat...",
"VO__AMICIA__CH01__CHATTER__FINAL_SQUEEZE_THROUGH__010__M__1": "Dayan...",
"VO__AMICIA__CH01__CHATTER__FINAL_SQUEEZE_THROUGH__050__M__1": "Onu öldürecek! Kımılda!",
"VO__AMICIA__CH01__CHATTER__FIRE_HOUSE__025__M__1": "Ha... Ne...?",
"VO__AMICIA__CH01__CHATTER__FIRE_HOUSE__030__M__1": "Durma...",
"VO__AMICIA__CH01__CHATTER__FIRE_SPREAD__010__M__1": "Bu da ne?!",
"VO__AMICIA__CH01__CHATTER__FIRE_SPREAD__011__M__1": "Hayır, hayır, hayır!",
"VO__AMICIA__CH01__CHATTER__FIRE_SPREAD__012__M__1": "Kaç!",
"VO__AMICIA__CH01__CHATTER__FIRE_SPREAD__020__M__1": "Ev!",
"VO__AMICIA__CH01__CHATTER__FIRST_STEPS__020__M__1": "Uzun bir yol oldu. Bacaklarını açmaya hakkın var!",
"VO__AMICIA__CH01__CHATTER__FIRST_STEPS__050__M__1": "Şuna bak...",
"VO__AMICIA__CH01__CHATTER__HELP_TONIN__020__M__1": "Hâlleder! Gitmeliyiz Hugo! Yakalarlarsa bizi öldürürler!",
"VO__AMICIA__CH01__CHATTER__HELP_TONIN__040__M__1": "Şşt! Sessiz ol!",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_BEGIN__050__M__1": "Amazon Amicia!",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_BEGIN__075__M__1": "Evet... Onları da kullanabiliriz.",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_BEGIN__090__M__1": "Yanında duracağım kralım!",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_END__020__M__1": "Lucas...",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_END__065__M__1": "Pekâlâ, git çalış! Biz biraz daha kalacağız.",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_END__090__M__1": "Nasıl istersen, iyi Kral!",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_ROUND_1__020__M__1": "Güzel, şimdi gözümüzü ondan ayırmayalım!",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_ROUND_1_BEGIN__020__M__1": "Nefes almayı unutma kralım...",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_ROUND_1_LOST__030__M__1": "Hadi, umutsuzluğa kapılma...",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_ROUND_2__010__M__1": "Sanırım görünmemek için daha çok yer değiştirmeliyiz kralım!",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_ROUND_2_LOST__030__M__1": "Ya da... pek iyi değiliz.",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_ROUND_3__015__M__1": "Çabuk kralım!",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_ROUND_3__055__M__1": "Merak ediyorum...",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_ROUND_3_LOST__030__M__1": "Ne kadar da hainsin...",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_WIN__010__M__1": "Hain.",
"VO__AMICIA__CH01__CHATTER__HIDESEEK_WIN__020__M__1": "Rhaaarh!",
"VO__AMICIA__CH01__CHATTER__HOUSE__020__M__1": "İyi gördün!",
"VO__AMICIA__CH01__CHATTER__HUNTER_SEEKER_1__020__M__1": "Biliyor musun? Biz de onu avlamalıyız!",
"VO__AMICIA__CH01__CHATTER__HUNTER_SEEKER_2__020__M__1": "Avcıyı yine avlayalım!",
"VO__AMICIA__CH01__CHATTER__HUNTER_SEEKER_3__020__M__1": "Evet!",
"VO__AMICIA__CH01__CHATTER__INCOMING_THREAT__010__M__1": "Geri çekil!",
"VO__AMICIA__CH01__CHATTER__INSIDE_HOUSE__020__M__1": "Bizi bulurlar... Devam etmeliyiz...",
"VO__AMICIA__CH01__CHATTER__JAR_TUTO_OK__020__M__1": "Şimdi fırsatımız var.",
"VO__AMICIA__CH01__CHATTER__KILL_3__010__M__1": "Sen ölürsen, onlar da ölür...",
"VO__AMICIA__CH01__CHATTER__LAST_AIM__010__M__1": "Sakin. Iskalama.",
"VO__AMICIA__CH01__CHATTER__LAST_KILL_SHOT__010__M__1": "DUR!",
"VO__AMICIA__CH01__CHATTER__LAST_KILL_SHOT__030__M__1": "Bırak onu!",
"VO__AMICIA__CH01__CHATTER__LAST_KILL_SHOT__060__M__1": "BIRAK ONU dedim!",
"VO__AMICIA__CH01__CHATTER__LOCKED_GATE__010__M__1": "Lütfen söyle, çıkış yolumuz bu...",
"VO__AMICIA__CH01__CHATTER__LOCKED_GATE__030__M__1": "Hayır! Kilitlemişler!",
"VO__AMICIA__CH01__CHATTER__LOCKED_GATE__047__M__1": "Evet...",
"VO__AMICIA__CH01__CHATTER__LOCKED_GATE__060__M__1": "Keşke mecbur olmasaydık...",
"VO__AMICIA__CH01__CHATTER__MORE_EXPLORATION__020__M__1": "Evet.",
"VO__AMICIA__CH01__CHATTER__NAVAL_HIT_1__010__M__1": "Biri gitti!",
"VO__AMICIA__CH01__CHATTER__NAVAL_HIT_2__010__M__1": "Hiçbir kötü büyü bu krallığı kirletemez!",
"VO__AMICIA__CH01__CHATTER__NAVAL_HIT_3__020__M__1": "Birçokları bizi istila etmeye çalıştı!",
"VO__AMICIA__CH01__CHATTER__NAVAL_HIT_3__040__M__1": "Çünkü biz De Rune hanesiyiz!",
"VO__AMICIA__CH01__CHATTER__NAVAL_MORE__020__M__1": "Onlara hazırım!",
"VO__AMICIA__CH01__CHATTER__NAVAL_START__020__M__1": "Onları görüyorum! Toprağını kurtaracağız Kralım!",
"VO__AMICIA__CH01__CHATTER__NO_SHOOT_1__020__M__1": "Pekâlâ.",
"VO__AMICIA__CH01__CHATTER__NO_SHOOT_2__020__M__1": "Evet, evet!",
"VO__AMICIA__CH01__CHATTER__QUICK_IDLE_1__010__M__1": "Durma... Hayattalar... Sana ihtiyaçları var!",
"VO__AMICIA__CH01__CHATTER__QUICK_IDLE_2__010__M__1": "Neredesin?!... Dayan... Geliyorum...",
"VO__AMICIA__CH01__CHATTER__QUICK_IDLE_3__010__M__1": "Aşağı... Aşağı inmeye devam et...",
"VO__AMICIA__CH01__CHATTER__REACH_SQUEEZE__010__M__1": "Buradan! Çabuk!",
"VO__AMICIA__CH01__CHATTER__REACHING_COVER__040__M__1": "Pekâlâ... Tepeden aşağı inmiş olmalı. Hızlı hareket et... Görünmeden.",
"VO__AMICIA__CH01__CHATTER__ROCK_WALK__010__M__1": "Yukarıdan ne görüyorsun?",
"VO__AMICIA__CH01__CHATTER__ROCK_WALK__030__M__1": "Müreffeh mi?",
"VO__AMICIA__CH01__CHATTER__ROCK_WALK__050__M__1": "Ah evet... O ünlü büyücü.",
"VO__AMICIA__CH01__CHATTER__ROCK_WALK__055__M__1": "Oraya devriye atalım!",
"VO__AMICIA__CH01__CHATTER__ROCKS__020__M__1": "Tabii ki... Sadece... düşme.",
"VO__AMICIA__CH01__CHATTER__ROCKS__040__M__1": "Evet, tabii...",
"VO__AMICIA__CH01__CHATTER__SLING_BACK__010__M__1": "Alçaklar! Geri gelmek zorundaydınız!",
"VO__AMICIA__CH01__CHATTER__SNEAK_IN__010__M__1": "İçeri sızalım...",
"VO__AMICIA__CH01__CHATTER__SPRINTING__010__M__1": "Hugo, domuz gibi terleyeceksin!",
"VO__AMICIA__CH01__CHATTER__SPRINTING__030__M__1": "Sana iyi gelir!",
"VO__AMICIA__CH01__CHATTER__SPRINTING__040__M__1": "Hadi Lucas! Sen artık ısınmışsındır!",
"VO__AMICIA__CH01__CHATTER__SQUEEZE_THROUGH__010__M__1": "Buradan... bizi takip edemez!",
"VO__AMICIA__CH01__CHATTER__STEPS_REWARDS_1__020__M__1": "Bırak gelsinler! Ezerim onları!",
"VO__AMICIA__CH01__CHATTER__STEPS_REWARDS_3__020__M__1": "Seni ve krallığını korumaya söz verdim!",
"VO__AMICIA__CH01__CHATTER__SWITCH_SIDE__010__M__1": "Şimdi geçelim...",
"VO__AMICIA__CH01__CHATTER__SWITCH_SIDE__030__M__1": "Hayır, çünkü bizi görmezler.",
"VO__AMICIA__CH01__CHATTER__TO_MOTHER__010__M__1": "Çabuk!",
"VO__AMICIA__CH01__CHATTER__TO_RIVER__020__M__1": "Ben de. O olmasa burada olmazdık.",
"VO__AMICIA__CH01__CHATTER__TONIN__020__M__1": "Ah, merhaba?",
"VO__AMICIA__CH01__CHATTER__TONIN__043__M__1": "Ah... Epey gürültülü olabiliyor, evet...",
"VO__AMICIA__CH01__CHATTER__TONIN__050__M__1": "Evet, ama... Sen kimsin?",
"VO__AMICIA__CH01__CHATTER__TONIN__055__M__1": "Pekâlâ! Biz Hugo ve Amicia'yız!",
"VO__AMICIA__CH01__CHATTER__TONIN_HIT_1__030__M__1": "Geçemezler, diyorum sana!",
"VO__AMICIA__CH01__CHATTER__TONIN_HIT_2__030__M__1": "Ve batmaya devam edecekler!",
"VO__AMICIA__CH01__CHATTER__TONIN_HIT_3__010__M__1": "Savunmamız onlar için fazla güçlü!",
"VO__AMICIA__CH01__CHATTER__TONIN_HIT_3__050__M__1": "Hey, sakin ol! Şeytanın dilini konuşmaya başladın!",
"VO__AMICIA__CH01__CHATTER__TONIN_HIT_3__080__M__1": "Pekâlâ, son darbeyi indir Tonin!",
"VO__AMICIA__CH01__CHATTER__TONIN_SHOOT__030__M__1": "Şimdi... Savaşalım!",
"VO__AMICIA__CH01__CHATTER__TRACKS__011__M__1": "Şurada... evet...",
"VO__AMICIA__CH01__CHATTER__TUTO_DISTRACT_AIM__030__M__1": "Sakin...",
"VO__AMICIA__CH01__CHATTER__TUTO_DISTRACT_OK__020__M__1": "Çabuk olalım...",
"VO__AMICIA__CH01__CHATTER__TUTO_DISTRACT_START__020__M__1": "Ben hâllederim...",
"VO__AMICIA__CH01__CHATTER__TUTO_DISTRACT_START__021__M__1": "Şu alet kutusu... Ses çıkarır...",
"VO__AMICIA__CH01__CHATTER__TUTO_JAR__010__M__1": "Şu kapıya ulaşmalıyız... Onun dikkatini dağıtmam gerekecek...",
"VO__AMICIA__CH01__CHATTER__TUTO_JAR__030__M__1": "İşe yarar...",
"VO__AMICIA__CH01__CHATTER__TUTO_JAR__040__M__1": "Arkasına atarsam...",
"VO__AMICIA__CH01__CHATTER__TUTO_ORDER_CRAWL__010__M__1": "Pekâlâ, ama çok dikkatli ol!",
"VO__AMICIA__CH01__CHATTER__TUTO_ORDER_CRAWL__030__M__1": "Lütfen, fark edilme...",
"VO__AMICIA__CH01__CHATTER__TUTO_ORDER_CRAWL__040__M__1": "Hadi Hugo...",
"VO__AMICIA__CH01__CHATTER__TUTO_SPRINT__010__M__1": "Pekâlâ o zaman...",
"VO__AMICIA__CH01__CHATTER__TUTO_SPRINT__020__M__1": "Koşma vakti!",
"VO__AMICIA__CH01__CHATTER__VISTA_ROOF__005__M__1": "Hadi...",
"VO__AMICIA__CH01__CHATTER__VISTA_ROOF__010__M__1": "Araba... Sapanım!",
"VO__AMICIA__CH01__CHATTER__VISTA_ROOF__020__M__1": "Hayattalar!",
"VO__AMICIA__CH01__CHATTER__WINDOW_HURRY__010__M__1": "Burada!",
"VO__AMICIA__CH01__CHATTER__WRONGWAY_GAME__010__M__1": "Yanına dön, yoksa onu bir ağacın tepesinde bulursun sonunda...",
"VO__AMICIA__CH01__CHATTER__WRONGWAY_GAME__030__M__1": "Gidip ne yaptığına bakmalıyım...",
"VO__AMICIA__CH01__CHATTER__WRONGWAY_HIDE__020__M__1": "Evet, gideceğiz.",
"VO__AMICIA__CH01__ONOM__ARRIVAL_RUINS__010__M__1": "Öf...",
"VO__AMICIA__CH01__ONOM__DROP_ARROW__010__M__1": "Ah!",
"VO__AMICIA__CH01__ONOM__DROP_ARROW__011__M__1": "Of!",
"VO__AMICIA__CH01__ONOM__FIRE_HOUSE__010__M__1": "Öf!",
"VO__AMICIA__CH01__ONOM__VISTA_ROOF__001__M__1": "Öksürük öksürük.",
"VO__AMICIA__CH01__RTC__010_OPENING__060__M__1": "Koşmaya devam et!",
"VO__AMICIA__CH01__RTC__010_OPENING__066__M__1": "Başaracağız!",
"VO__AMICIA__CH01__RTC__010_OPENING__115__M__1": "Hey, yavaşla—zalimimizi yoracaksın...",
"VO__AMICIA__CH01__RTC__010_OPENING__205__M__1": "Hadi... Bugün uzun bir yol katettik! Lütfen, annem onu yormaya çalış dedi...",
"VO__AMICIA__CH01__RTC__010_OPENING__215__M__1": "Cesur ol büyücü! Savaşın bitmekten çok uzak!",
"VO__AMICIA__CH01__RTC__020_END_GAME__020__M__1": "Eyvah Hugo... Siper al!",
"VO__AMICIA__CH01__RTC__020_END_GAME__050__M__1": "Tamam! Tamam çocuklar, kazandınız! Teslim oldular!",
"VO__AMICIA__CH01__RTC__020_END_GAME__083__M__1": "İyi misin?",
"VO__AMICIA__CH01__RTC__020_END_GAME__090__M__1": "İyi şanslar o zaman!",
"VO__AMICIA__CH01__RTC__020_END_GAME__120__M__1": "Gel kralım, savaş bitti. Bu nehri takip etmeye devam edelim.",
"VO__AMICIA__CH01__RTC__021_BEEKEEPER__030__M__1": "Ne... neler oluyor?",
"VO__AMICIA__CH01__RTC__021_BEEKEEPER__050__M__1": "Durun, izinsiz girmek istemedik... Buraya kazara düştük! Nasıl olduğunu gösterirseniz gideriz!",
"VO__AMICIA__CH01__RTC__021_BEEKEEPER__070__M__1": "Yemin ederim! Burada ne olduğunu bilmiyorum, ama bizim bununla bir ilgimiz yok!",
"VO__AMICIA__CH01__RTC__021_BEEKEEPER__100__M__1": "Kaç!",
"VO__AMICIA__CH01__RTC__022_BREAKING_POINT__040__M__1": "Hugo, arkamda kal!",
"VO__AMICIA__CH01__RTC__022_BREAKING_POINT__060__M__1": "Yolumuzu kaybettik, gidiyoruz! Bırakın çocuk gitsin.",
"VO__AMICIA__CH01__RTC__022_BREAKING_POINT__090__M__1": "Hayır, daha yeni geldik.",
"VO__AMICIA__CH01__RTC__022_BREAKING_POINT__100__M__1": "Dinleyin, geç kaldıysa bu bizim suçumuz...",
"VO__AMICIA__CH01__RTC__022_BREAKING_POINT__150__M__1": "Bunu yapmak istemezsiniz... İnanın bana...",
"VO__AMICIA__CH01__RTC__035_CART__010__M__1": "Yine ada rüyan mıydı?",
"VO__AMICIA__CH01__RTC__035_CART__030__M__1": "Nehir kenarında oynuyorduk, hatırladın mı? Ama birden çok yorgun hissettin, ben de seni geri taşıdım ve uyuyakaldın.",
"VO__AMICIA__CH01__RTC__035_CART__080__M__1": "Yine de kaçmak zorunda kalmadan önce Guyenne'de bize yardıma gelmediler.",
"VO__AMICIA__CH01__RTC__035_CART__100__M__1": "O zaman umarım bunu telafi ederler.",
"VO__AMICIA__CH01__RTC__035_CART__130__M__1": "Bilmiyorum... Dikkatli ol.",
"VO__AMICIA__CH01__RTC__040_CONSEQUENCES__050__M__1": "Anne, hemen gitmeliyiz.",
"VO__BANDIT_N1__CH01__CHATTER__AFTER_FALL__040__M__1": "Hayır! Tam oradaydı!",
"VO__BANDIT_N1__CH01__CHATTER__AFTER_FALL__060__M__1": "Aramayı tarlalara genişletelim!",
"VO__BANDIT_N1__CH01__CHATTER__REACHING_COVER__030__M__1": "Dikkat, sinsidir o! Tam yanı başında olabilir!",
"VO__BANDIT_N2__CH01__CHATTER__FIRE_HOUSE__005__M__1": "Sen!",
"VO__BANDIT_N2__CH01__CHATTER__FIRE_HOUSE__011__M__1": "Öldün sen, cadı!",
"VO__BANDIT_N2__CH01__ONOM__FIRE_HOUSE__020__M__1": "Hı?!",
"VO__BANDIT_S1__CH01__CHATTER__AFTER_DROP__020__M__1": "Mathias ve Remi'yi nasıl yediklerini gördün! Böyle canavarları nasıl öldüreceğiz?!",
"VO__BANDIT_S1__CH01__CHATTER__BROTHERS_ARRIVAL__050__M__1": "Geri gelmeyeceğim! Yemin ederim!",
"VO__BANDIT_S1__CH01__CHATTER__BROTHERS_ARRIVAL__100__M__1": "Hayır! Lütfen, hayır!",
"VO__BANDIT_S1__CH01__CHATTER__BROTHERS_ARRIVAL__110__M__1": "Merhamet et! Yalvarırım!",
"VO__BANDIT_S1__CH01__CHATTER__DROP_ARROW__005__M__1": "Cadıyı görüyorum!",
"VO__BANDIT_S1__CH01__CHATTER__DROP_ARROW__022__M__1": "Burada, hadi yakalayın onu!",
"VO__BANDIT_S1__CH01__CHATTER__FINAL_SQUEEZE_THROUGH__040__M__1": "Ama görevim tamamlanacak!",
"VO__BANDIT_S1__CH01__CHATTER__LAST_KILL_SHOT__020__M__1": "Sen! Onları sen öldürdün! Bu adil olur!",
"VO__BANDIT_S1__CH01__CHATTER__LAST_KILL_SHOT__050__M__1": "Cehenneme gidiyor! Sen de onunla!",
"VO__BANDIT_S1__CH01__CHATTER__LAST_KILL_SHOT__070__M__1": "GEBER!",
"VO__BANDIT_S1__CH01__CHATTER__OFFSCREEN_SQUEEZE__020__M__1": "Senin tohumun ailemi öldürdü, iblis!",
"VO__BANDIT_S1__CH01__ONOM__BROTHERS_ARRIVAL__070__M__1": "Ah!",
"VO__BANDIT_S1__CH01__ONOM__THIEF_DIE__010__M__1": "Ah!",
"VO__BANDIT_S2__CH01__CHATTER__AFTER_DROP__030__M__1": "Kafalarını kesmeyi deneyelim! Gerekirse bir rahip çağırırız!",
"VO__BANDIT_S2__CH01__CHATTER__AFTER_FALL__005__M__1": "Kızla ben ilgilenirim!",
"VO__BANDIT_S2__CH01__CHATTER__AFTER_FALL__015__M__1": "Bir yerlerde olduğunu biliyorum! Göster kendini!",
"VO__BANDIT_S2__CH01__CHATTER__AFTER_FALL__030__M__1": "Nerede o? Görüyor musun?",
"VO__BANDIT_S2__CH01__CHATTER__AFTER_FALL__050__M__1": "Hâlâ buralarda olmalı! Aç gözünü!",
"VO__BANDIT_S2__CH01__RTC__040_CONSEQUENCES__090__M__1": "Çocuk! Onlar bu!",
"VO__BANDIT_S3__CH01__CHATTER__BROTHERS_BACK__010__M__1": "Anladım.",
"VO__BANDIT_S3__CH01__CHATTER__BROTHERS_BACK__050__M__1": "Muhtemelen bir yerlerde saklanıyor...",
"VO__BANDIT_S3__CH01__CHATTER__FATHER_FIRE__010__M__1": "Onu görüyorum! Burada!",
"VO__BANDIT_S3__CH01__CHATTER__FATHER_FIRE__022__M__1": "Umurumda değil! Oğlumu öldürdün! Cehennemde yan!",
"VO__BANDIT_S3__CH01__CHATTER__JACQUES__005__M__1": "Bir katliam bu... Tanrım...",
"VO__BANDIT_S3__CH01__CHATTER__JACQUES__020__M__1": "İyi hissetmiyorum Mathias...",
"VO__BANDIT_S3__CH01__CHATTER__JACQUES__040__M__1": "Her... neyse.",
"VO__BANDIT_S3__CH01__CHATTER__JACQUES__060__M__1": "Hepsini öldürmek zorunda değiliz... seni manyak...",
"VO__BANDIT_S3__CH01__CHATTER__JACQUES_DISTRACTED__010__M__1": "Hâlâ saklanan biri mi var?",
"VO__BANDIT_S3__CH01__CHATTER__JACQUES_DISTRACTED__020__M__1": "Yine mi? Sizi bulacağım, lanet aptallar!",
"VO__BANDIT_S3__CH01__CHATTER__JAR_TUTO_OK__010__M__1": "Bu da ne?!... Baltam var, uyarıyorum!",
"VO__BANDIT_S3__CH01__CHATTER__JAR_TUTO_OK__030__M__1": "Azizler beni korusun...",
"VO__BANDIT_S3__CH01__CHATTER__NO_EXIT__020__M__1": "Sadece lanet bir iş lazımdı!",
"VO__BANDIT_S3__CH01__CHATTER__NO_EXIT__030__M__1": "Buradan çıkmam lazım...",
"VO__BANDIT_S3__CH01__CHATTER__VISTA_ROOF__015__M__1": "Kızı arayın! Diğerleri tepeden aşağı koştu!",
"VO__BEATRICE__CH01__CHATTER__BEATRICE_SCREAM__010__M__1": "Hayır!",
"VO__BEATRICE__CH01__CHATTER__BEATRICE_VOICE__010__M__1": "Durun!",
"VO__BEATRICE__CH01__CHATTER__BEATRICE_VOICE__030__M__1": "O bir çocuk! Bir çocuk!",
"VO__BEATRICE__CH01__CHATTER__FINAL_SQUEEZE_THROUGH__030__M__1": "Ateş... bizimle birlikte öleceksiniz!",
"VO__BEATRICE__CH01__CHATTER__LAST_KILL_SHOT__040__M__1": "Dikkat... Amicia!",
"VO__BEATRICE__CH01__CHATTER__OFFSCREEN_SQUEEZE__010__M__1": "Onları bağışlayın, yalvarırım!",
"VO__BEATRICE__CH01__RTC__035_CART__004__M__1": "Bak kim uyanmış...",
"VO__BEATRICE__CH01__RTC__035_CART__060__M__1": "Uzun bir yolculuk oldu Hugo, hepimiz bitkiniz. Ama kızıl şehir çok yakın! Seni orada muayene ettireceğiz.",
"VO__BEATRICE__CH01__RTC__035_CART__090__M__1": "Engizisyon'un peşimize düşeceğini bilmiyorlardı... Artık bizi karşılamaya hazırlar.",
"VO__BEATRICE__CH01__RTC__035_CART__120__M__1": "Bu da ne?",
"VO__BEATRICE__CH01__RTC__035_CART__140__M__1": "Bir bakalım...",
"VO__BEATRICE__CH01__RTC__035_CART__160__M__1": "Merhaba. Neler oluyor?",
"VO__BEATRICE__CH01__RTC__035_CART__180__M__1": "Uzaktan. Batı kıyısından geliyoruz. Savaştan kaçtık.",
"VO__BEATRICE__CH01__RTC__040_CONSEQUENCES__010__M__1": "Tam olarak ne yaptılar?",
"VO__BEATRICE__CH01__RTC__040_CONSEQUENCES__030__M__1": "Ah, bu korkunç... Umarım suçluları bulursunuz.",
"VO__BEATRICE__CH01__RTC__040_CONSEQUENCES__055__M__1": "Evet.",
"VO__BEATRICE__CH01__RTC__040_CONSEQUENCES__060__M__1": "Üzgünüz, önümüzde hâlâ epey yol var.",
"VO__BEATRICE__CH01__RTC__040_CONSEQUENCES__110__M__1": "Hayır, durun!",
"VO__BEATRICE__CH01__RTC__050_ONCE_AGAIN__080__M__1": "Bitti...",
"VO__BEATRICE__CH01__RTC__050_ONCE_AGAIN__120__M__1": "Geçti. Geçti...",
"VO__HUGO__CH01__CHATTER__2ND_CRISIS__010__M__1": "Hayır...",
"VO__HUGO__CH01__CHATTER__2ND_CRISIS__020__M__1": "Acıyor...",
"VO__HUGO__CH01__CHATTER__2ND_CRISIS__040__M__1": "Yardım... lazım...",
"VO__HUGO__CH01__CHATTER__2ND_CRISIS__050__M__1": "Hayır... O olmasın... Beni rahat bırak... Beni rahat bırak!",
"VO__HUGO__CH01__CHATTER__2ND_CRISIS__060__M__1": "Lütfen... lütfen...",
"VO__HUGO__CH01__CHATTER__2ND_CRISIS__070__M__1": "Amicia! Anne! Beni almaya geliyor!",
"VO__HUGO__CH01__CHATTER__2ND_CRISIS__080__M__1": "Cıyaklamayı kes de yardım et bana!",
"VO__HUGO__CH01__CHATTER__3RD_CRISIS__010__M__1": "Yardım... et... Uggnnn...",
"VO__HUGO__CH01__CHATTER__3RD_CRISIS__020__M__1": "Onları bulmama... yardım et...",
"VO__HUGO__CH01__CHATTER__3RD_CRISIS__030__M__1": "Kes... şu gürültüyü!",
"VO__HUGO__CH01__CHATTER__3RD_CRISIS__040__M__1": "Kes şunu...",
"VO__HUGO__CH01__CHATTER__AFTER_2ND_DISTRACT__010__M__1": "Eyvah... Tonin burada yaşıyor!",
"VO__HUGO__CH01__CHATTER__AFTER_2ND_DISTRACT__050__M__1": "Umarım...",
"VO__HUGO__CH01__CHATTER__AFTER_DISTRACT__020__M__1": "Annem çok kızacak...",
"VO__HUGO__CH01__CHATTER__AFTER_DOOR__005__M__1": "Neredeler?! Tonin'i buldular mı?",
"VO__HUGO__CH01__CHATTER__AFTER_STUNG__010__M__1": "Az kalsın bizi görüyordu...",
"VO__HUGO__CH01__CHATTER__AFTER_THE_WAR__010__M__1": "Harikaydı! Bir sürüsünü batırdın!",
"VO__HUGO__CH01__CHATTER__AFTER_THE_WAR__011__M__1": "Sadece birkaçını ıskaladın! Çok komikti!",
"VO__HUGO__CH01__CHATTER__AFTER_THE_WAR__012__M__1": "Çok fazlasını batırdın! Harika bir kaptansın!",
"VO__HUGO__CH01__CHATTER__AFTER_THE_WAR__013__M__1": "Ve Tonin iyi biriydi!",
"VO__HUGO__CH01__CHATTER__ARRIVAL_RUINS__040__M__1": "Bir kale bu!",
"VO__HUGO__CH01__CHATTER__BROTHERS_ARRIVAL__040__M__1": "Biri geliyor!",
"VO__HUGO__CH01__CHATTER__CHARGE__020__M__1": "HÜCUUUUM!",
"VO__HUGO__CH01__CHATTER__CHARGE_FAIL__010__M__1": "Kapı kapalı kaptan! Ne yapacağız?!",
"VO__HUGO__CH01__CHATTER__CHASED__030__M__1": "Kapı!",
"VO__HUGO__CH01__CHATTER__CLIMB_TUTO__020__M__1": "Ne?!",
"VO__HUGO__CH01__CHATTER__CLIMB_TUTO__040__M__1": "Zaten çok ağırsın!",
"VO__HUGO__CH01__CHATTER__CLIMB_TUTO__046__M__1": "Bir gün ben de yapabileceğim!",
"VO__HUGO__CH01__CHATTER__CLOSE_TO_RIVER__020__M__1": "Krallığım burada bitiyor!",
"VO__HUGO__CH01__CHATTER__CLOSE_TO_RIVER__040__M__1": "Evet!",
"VO__HUGO__CH01__CHATTER__CLOSE_TO_RIVER__060__M__1": "Dikkat et Amazon Amicia! Düşman gemileri geliyor! Bize saldıracaklar!",
"VO__HUGO__CH01__CHATTER__CLOSE_TO_RIVER__080__M__1": "Sınırda kal ve geçmeden onları batır!",
"VO__HUGO__CH01__CHATTER__CRAWLING__010__M__1": "Ha... Ha... Başım... dönüyor...",
"VO__HUGO__CH01__CHATTER__CROUCH_PROGRESS__020__M__1": "Evet, çabuk...",
"VO__HUGO__CH01__CHATTER__DEBRIEF_TONIN__010__M__1": "Onun gibi bir arkadaşım olsun isterdim.",
"VO__HUGO__CH01__CHATTER__DEBRIEF_TONIN__030__M__1": "Emin misin?",
"VO__HUGO__CH01__CHATTER__DEBRIEF_TONIN__050__M__1": "Hmmm. Bu uzun sürebilir...",
"VO__HUGO__CH01__CHATTER__DEBRIEF_TONIN__070__M__1": "Umarım!",
"VO__HUGO__CH01__CHATTER__DISCOVER_RIVER__010__M__1": "Vaay...",
"VO__HUGO__CH01__CHATTER__DOOR_OPENING__020__M__1": "Geldiğimizi gördüler!",
"VO__HUGO__CH01__CHATTER__DOOR_OPENS__010__M__1": "Çok ağır! Ama artık sen açabilirsin!",
"VO__HUGO__CH01__CHATTER__EMERGENCY_TUTO__010__M__1": "Geliyor!",
"VO__HUGO__CH01__CHATTER__ENTER_CASTLE_BEFORE_DROP__020__M__1": "Belki bir kazaydı...",
"VO__HUGO__CH01__CHATTER__ENTER_CASTLE_EXPLORE_ROOM__010__M__1": "Amicia, yiyecek ve giysi var...",
"VO__HUGO__CH01__CHATTER__ENTER_CASTLE_EXPLORE_ROOM__030__M__1": "Tavanlarını kırdık... Belki duymuşlardır...",
"VO__HUGO__CH01__CHATTER__ENTER_CASTLE_FALLEN__020__M__1": "Hayır... Ama artık geri dönmek istiyorum.",
"VO__HUGO__CH01__CHATTER__ENTER_CASTLE_FALLEN__040__M__1": "Evet...",
"VO__HUGO__CH01__CHATTER__ENTER_CASTLE_FLOOR__020__M__1": "Değilim...",
"VO__HUGO__CH01__CHATTER__ENTER_CASTLE_FLOOR__040__M__1": "Gerçekten mi?",
"VO__HUGO__CH01__CHATTER__ENTER_CASTLE_OUTSIDE__020__M__1": "Her şey yanmış!",
"VO__HUGO__CH01__CHATTER__ENTER_CASTLE_OUTSIDE__060__M__1": "Ama neden yanmışlar?!",
"VO__HUGO__CH01__CHATTER__ENTER_CASTLE_STAIRS__010__M__1": "Hm. Biraz karanlık...",
"VO__HUGO__CH01__CHATTER__ENTER_CASTLE_STAIRS__030__M__1": "Evet...",
"VO__HUGO__CH01__CHATTER__ENTER_THE_CASTLE__010__M__1": "Vaay! Şu kale kocaman!",
"VO__HUGO__CH01__CHATTER__ENTER_THE_CASTLE__030__M__1": "Pekâlâ! Hazırım!",
"VO__HUGO__CH01__CHATTER__EXHAUSTED_WALK__010__M__1": "Çok... gürültücüsün...",
"VO__HUGO__CH01__CHATTER__EXHAUSTED_WALK__020__M__1": "Pekâlâ... Geliyorum...",
"VO__HUGO__CH01__CHATTER__FINAL_CRISIS__020__M__1": "Bu... ölmek mi?",
"VO__HUGO__CH01__CHATTER__FINAL_CRISIS__030__M__1": "Ölmek... istemiyorum...",
"VO__HUGO__CH01__CHATTER__FINAL_CRISIS__040__M__1": "Yalnız... değil...",
"VO__HUGO__CH01__CHATTER__FIRST_CRISIS__010__M__1": "Hayır! Gitme!",
"VO__HUGO__CH01__CHATTER__FIRST_CRISIS__020__M__1": "Nefes al... nefes al...",
"VO__HUGO__CH01__CHATTER__FIRST_STEPS__010__M__1": "Burada bir tek sen mi varsın?",
"VO__HUGO__CH01__CHATTER__FIRST_STEPS__020__M__1": "Amicia nerede...?",
"VO__HUGO__CH01__CHATTER__FIRST_STEPS__040__M__1": "Amicia!",
"VO__HUGO__CH01__CHATTER__FIRST_STEPS__065__M__1": "Gidip bakalım!",
"VO__HUGO__CH01__CHATTER__FLOWERS__010__M__1": "Ne... Ne...?",
"VO__HUGO__CH01__CHATTER__FLOWERS__011__M__1": "Burası neresi?",
"VO__HUGO__CH01__CHATTER__FLOWERS__020__M__1": "Amicia! Anne! Lucas!",
"VO__HUGO__CH01__CHATTER__FLOWERS__030__M__1": "Neredesiniz?!",
"VO__HUGO__CH01__CHATTER__FLOWERS__040__M__1": "Kendimi... kötü hissediyorum...",
"VO__HUGO__CH01__CHATTER__GET_UP__012__M__1": "Ne... istiyorsun...?",
"VO__HUGO__CH01__CHATTER__HELP_TONIN__010__M__1": "Ona zarar vermelerine izin veremeyiz!",
"VO__HUGO__CH01__CHATTER__HELP_TONIN__030__M__1": "Ama belki onu da öldürürler!",
"VO__HUGO__CH01__CHATTER__HELPER_POSITION__010__M__1": "Mevkiine dön Amicia! Dalın arkasına!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_BEGIN__010__M__1": "Hain Lucas kalemi istila ediyor!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_BEGIN__030__M__1": "Amicia! Çok güçlü! Saklanmalıyız!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_BEGIN__070__M__1": "Şurada başka harabeler var!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_BEGIN__080__M__1": "Gel Amazon Amicia! İyi bir saklanma yeri bulmalıyız!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_COUNTING__130__M__1": "Geliyor, geliyor!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_END__040__M__1": "Ama sen bir simyacısın!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_END__050__M__1": "Çok korktun!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_END__085__M__1": "Gel! Kalenin geri kalanını görelim!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_ROUND_1__023__M__1": "Evet! Gelirse yer değiştiririz!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_ROUND_1__050__M__1": "Korkunç biri!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_ROUND_1_BEGIN__010__M__1": "Çabuk! Çabuk!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_ROUND_1_LOST__020__M__1": "Çok kötüsün!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_ROUND_2_LOST__020__M__1": "Çok güçlü!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_ROUND_3__010__M__1": "Gidelim Amicia!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_ROUND_3__020__M__1": "Yoldan geliyor!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_ROUND_3__050__M__1": "Nereden biliyor?!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_ROUND_3_BEGIN__010__M__1": "Ah hadi yine yapalım! Lütfen, lütfen, lütfen!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_ROUND_3_LOST__020__M__1": "Ah hayııır!",
"VO__HUGO__CH01__CHATTER__HIDESEEK_WIN__030__M__1": "Rhaaarh!",
"VO__HUGO__CH01__CHATTER__HOUSE__010__M__1": "Amicia, ev...",
"VO__HUGO__CH01__CHATTER__HUNTER_SEEKER_1__023__M__1": "Ah, evet!",
"VO__HUGO__CH01__CHATTER__HUNTER_SEEKER_2__023__M__1": "Evet! Kazanmanın tek yolu bu!",
"VO__HUGO__CH01__CHATTER__HUNTER_SEEKER_3__010__M__1": "Amicia, onu yakalamaya çalışalım!",
"VO__HUGO__CH01__CHATTER__INSIDE_HOUSE__010__M__1": "Burada saklanabiliriz...",
"VO__HUGO__CH01__CHATTER__ISLAND_VAULT__010__M__1": "Belki nerede olduklarını biliyordur?",
"VO__HUGO__CH01__CHATTER__ISLAND_VAULT__020__M__1": "Evet... Belki buradan geçmişlerdir!",
"VO__HUGO__CH01__CHATTER__LOCKED_GATE__020__M__1": "Evet...",
"VO__HUGO__CH01__CHATTER__LOCKED_GATE__040__M__1": "Belki başka bir yol vardır?!",
"VO__HUGO__CH01__CHATTER__LOCKED_GATE__043__M__1": "Burada bir delik var!",
"VO__HUGO__CH01__CHATTER__LOCKED_GATE__050__M__1": "Gidip kapıyı diğer taraftan açabilirim...",
"VO__HUGO__CH01__CHATTER__MORE_EXPLORATION__010__M__1": "Şunu kokluyor musun? Şömine gibi kokuyor...",
"VO__HUGO__CH01__CHATTER__NAVAL_HIT_1__020__M__1": "Evet! Devam et! Daha çok gemi geliyor!",
"VO__HUGO__CH01__CHATTER__NAVAL_HIT_2__020__M__1": "Sadece iyi büyü!",
"VO__HUGO__CH01__CHATTER__NAVAL_HIT_3__030__M__1": "Ama onları geri püskürttük!",
"VO__HUGO__CH01__CHATTER__NAVAL_MORE__010__M__1": "Bir tane daha!",
"VO__HUGO__CH01__CHATTER__NAVAL_START__010__M__1": "İşte büyücünün ordusu geliyor!",
"VO__HUGO__CH01__CHATTER__NO_SHOOT_1__010__M__1": "Ateş et Amicia!",
"VO__HUGO__CH01__CHATTER__NO_SHOOT_2__010__M__1": "Ah, komik değil Amicia! Ateş et!",
"VO__HUGO__CH01__CHATTER__PHOENIX_FLIES_OFF__010__M__1": "Nereye gidiyorsun?!",
"VO__HUGO__CH01__CHATTER__PHOENIX_FLIES_OFF__020__M__1": "Geri dönmem lazım...",
"VO__HUGO__CH01__CHATTER__PHOENIX_FLIES_OFF__030__M__1": "Ablam ve annem lazım bana...",
"VO__HUGO__CH01__CHATTER__ROCK_CLIMB__010__M__1": "Evet! Kral Hugo, büyük surunun mazgallarında devriye geziyor!",
"VO__HUGO__CH01__CHATTER__ROCK_WALK__020__M__1": "Krallığım!",
"VO__HUGO__CH01__CHATTER__ROCK_WALK__040__M__1": "Öyleydi! Ama sonra Lucas saldırdı!",
"VO__HUGO__CH01__CHATTER__ROCK_WALK__060__M__1": "Ah! Bir nehir!",
"VO__HUGO__CH01__CHATTER__ROCK_WALK__065__M__1": "Deniz bu!",
"VO__HUGO__CH01__CHATTER__ROCKS__010__M__1": "Ah, şu kayalara tırmanabilir miyim?!",
"VO__HUGO__CH01__CHATTER__ROCKS__030__M__1": "Ben asla düşmem!",
"VO__HUGO__CH01__CHATTER__SNEAK_IN__020__M__1": "Evet. İyi bir plan.",
"VO__HUGO__CH01__CHATTER__SQUEEZE_THROUGH__020__M__1": "Çabuk!",
"VO__HUGO__CH01__CHATTER__STEPS_REWARDS_1__010__M__1": "Evet! Kral alkışlıyor!",
"VO__HUGO__CH01__CHATTER__STEPS_REWARDS_3__010__M__1": "Vay! Onları yerle bir ediyorsun!",
"VO__HUGO__CH01__CHATTER__STUNG__020__M__1": "Eyvah...",
"VO__HUGO__CH01__CHATTER__SWITCH_SIDE__020__M__1": "Bizi öldürecekler...",
"VO__HUGO__CH01__CHATTER__TO_RIVER__010__M__1": "Lucas'ın bizimle kalmasına sevindim.",
"VO__HUGO__CH01__CHATTER__TONIN__030__M__1": "Merhaba...",
"VO__HUGO__CH01__CHATTER__TONIN__060__M__1": "Ateş edebilir misin Tonin?",
"VO__HUGO__CH01__CHATTER__TONIN_HIT_1__020__M__1": "Aferin!",
"VO__HUGO__CH01__CHATTER__TONIN_HIT_2__020__M__1": "Ama gelmeye devam ediyorlar!",
"VO__HUGO__CH01__CHATTER__TONIN_HIT_3__020__M__1": "Asker Tonin! O topu ateşlemeye devam et!",
"VO__HUGO__CH01__CHATTER__TONIN_HIT_3__040__M__1": "Kötü kıçlarına! Haha!",
"VO__HUGO__CH01__CHATTER__TONIN_SHOOT__010__M__1": "Harika! Ben kralım, o da kaptanım ve bir büyücünün ordusuyla savaşıyoruz!",
"VO__HUGO__CH01__CHATTER__TUTO_DISTRACT_OK__010__M__1": "Git buradan...",
"VO__HUGO__CH01__CHATTER__TUTO_DISTRACT_START__010__M__1": "Kımıldamıyor...",
"VO__HUGO__CH01__CHATTER__TUTO_JAR__020__M__1": "Amicia, çömlekler...",
"VO__HUGO__CH01__CHATTER__TUTO_ORDER_CRAWL__020__M__1": "Merak etme...",
"VO__HUGO__CH01__CHATTER__WINDOW_HURRY__020__M__1": "Hâlâ arkamızda!",
"VO__HUGO__CH01__CHATTER__WRONGWAY_HIDE__010__M__1": "Amicia, kale diğer tarafta!",
"VO__HUGO__CH01__HELPER__DOOR_OPENS_HUGO_1__010__M__1": "Amicia, duvarda bir delik var! Onu kullanabiliriz!",
"VO__HUGO__CH01__HELPER__DOOR_OPENS_HUGO_2__010__M__1": "Amicia, bırak delikten geçeyim, yapabileceğimi biliyorum!",
"VO__HUGO__CH01__HELPER__ENTER_CASTLE_SECRET__010__M__1": "Burada! Gizli geçit!",
"VO__HUGO__CH01__ONOM__2ND_CRISIS__030__M__1": "Öf!",
"VO__HUGO__CH01__ONOM__CHARGE__030__M__1": "Ha... ha...",
"VO__HUGO__CH01__ONOM__FINAL_CRISIS__010__M__1": "Ah...",
"VO__HUGO__CH01__ONOM__FIRST_STEPS__070__M__1": "Yaaah!",
"VO__HUGO__CH01__ONOM__TUTO_ORDER_CRAWL__050__M__1": "Ic, ic!",
"VO__HUGO__CH01__RTC__010_OPENING__050__M__1": "Tam arkamızda Amicia! Bizi yakalayacak!",
"VO__HUGO__CH01__RTC__010_OPENING__063__M__1": "Çok hızlı!",
"VO__HUGO__CH01__RTC__010_OPENING__068__M__1": "Eyvah! Kule!",
"VO__HUGO__CH01__RTC__010_OPENING__070__M__1": "Geliyor!",
"VO__HUGO__CH01__RTC__010_OPENING__100__M__1": "Hadi büyücü! Yakala bizi!",
"VO__HUGO__CH01__RTC__010_OPENING__130__M__1": "Bu senin kulen! Kötü bir kule!",
"VO__HUGO__CH01__RTC__020_END_GAME__030__M__1": "Hayır!",
"VO__HUGO__CH01__RTC__020_END_GAME__040__M__1": "BUUUM!",
"VO__HUGO__CH01__RTC__020_END_GAME__070__M__1": "Çalışıyor musun?",
"VO__HUGO__CH01__RTC__020_END_GAME__100__M__1": "Güle güle Tonin!",
"VO__HUGO__CH01__RTC__020_END_GAME__105__M__1": "İyi biriydi!",
"VO__HUGO__CH01__RTC__021_BEEKEEPER__010__M__1": "Amicia...",
"VO__HUGO__CH01__RTC__022_BREAKING_POINT__030__M__1": "DUR!",
"VO__HUGO__CH01__RTC__022_BREAKING_POINT__170__M__1": "Dur! Bırak onu!",
"VO__HUGO__CH01__RTC__025_DRIFTING__060__M__1": "Amicia?...",
"VO__HUGO__CH01__RTC__025_DRIFTING__070__M__1": "Bana zarar verme...",
"VO__HUGO__CH01__RTC__025_DRIFTING__080__M__1": "Neredeyiz?",
"VO__HUGO__CH01__RTC__025_DRIFTING__090__M__1": "Ha... Ha... Hayır...",
"VO__HUGO__CH01__RTC__025_DRIFTING__100__M__1": "Yine başlıyor... Yardım lazım...",
"VO__HUGO__CH01__RTC__025_DRIFTING__110__M__1": "Bekle... Beni bekle!",
"VO__HUGO__CH01__RTC__030_PURIFIED__010__M__1": "Geçiyor...",
"VO__HUGO__CH01__RTC__030_PURIFIED__020__M__1": "Su sayesinde!",
"VO__HUGO__CH01__RTC__030_PURIFIED__025__M__1": "Beni kurtardın. Teşekkür ederim.",
"VO__HUGO__CH01__RTC__030_PURIFIED__030__M__1": "Buraya geri gelebilir miyim? Biriyle birlikte?",
"VO__HUGO__CH01__RTC__035_CART__008__M__1": "Rüya görüyordum... Neredeyiz?...",
"VO__HUGO__CH01__RTC__035_CART__020__M__1": "Evet... Hastaydım ve sonra beni kurtaran büyük bir kuş vardı, ama... Ne oldu Amicia? Çiftlikte?",
"VO__HUGO__CH01__RTC__035_CART__050__M__1": "Ama Amicia...",
"VO__HUGO__CH01__RTC__040_CONSEQUENCES__135__M__1": "Amicia!",
"VO__LUCAS__CH01__CHATTER__FIRST_STEPS__010__M__1": "Annen nerede olduğumuzu merak edecek.",
"VO__LUCAS__CH01__CHATTER__FIRST_STEPS__030__M__1": "Evet...",
"VO__LUCAS__CH01__CHATTER__FIRST_STEPS__060__M__1": "Bir kale...",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_BEGIN__020__M__1": "Evet! Ve seni bir böceğe dönüştüreceğim!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_BEGIN__040__M__1": "Ona kadar sayacağım! Sonra peşinize geleceğim Kral Hugo ve...",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_BEGIN__060__M__1": "Tabii ki... O hâlde HEMEN GİDİN!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__010__M__1": "Biiir!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__020__M__1": "İki!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__030__M__1": "Üç!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__040__M__1": "Dört!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__050__M__1": "Beeeş!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__060__M__1": "Altı!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__070__M__1": "Yedi!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__080__M__1": "Sekiz!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__090__M__1": "Dokuuuz!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__110__M__1": "On!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__115__M__1": "Sekiz! Dokuz! On!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_COUNTING__120__M__1": "Geliyoruuum!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_END__010__M__1": "Peki o zaman. Neyse, ben şimdi çalışmaya döneyim.",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_END__030__M__1": "Şey, simyacı olmak istiyorsam...",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_END__040__M__1": "Aman!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_END__050__M__1": "Hâlâ annenin çırağıyım.",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_END__080__M__1": "Tamam! Hoşça kalın!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_ROUND_1__030__M__1": "Korku kokusu alıyorum...",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_ROUND_1__040__M__1": "Ben Lucas, hainlerin haini, ayak parmaklarından yahni yapmaya yemin ederim! VE ONU YERİM!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_ROUND_2__030__M__1": "Neredesiniiiz? Korkunuzun kokusunu alıyorum! Yoksa... kraliyet ağız kokun mu bu?!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_ROUND_2__040__M__1": "Bütün krallar düşer, Efendim!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_ROUND_2_BEGIN__010__M__1": "Çok kolay! O hâlde... sana ikinci bir şans vereceğim!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_ROUND_3__030__M__1": "Bu sefer merhamet göstermeyeceğim! Sana son iyilik kıvılcımımı sundum!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_ROUND_3__040__M__1": "Aklınızı okuyabiliyorum... Kral Hugo'nun geceleri elma yediğini bile biliyorum!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_ROUND_3_BEGIN__020__M__1": "Peki! Kara, kötü kalbim hâlâ avın heyecanından zevk alabilir... Gidin! Gidin aptallar!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_ROUND_3_BEGIN__030__M__1": "Bu sefer sadece beşe kadar sayacağım!",
"VO__LUCAS__CH01__CHATTER__HIDESEEK_ROUND_3_LOST__010__M__1": "Bu kale benim!",
"VO__LUCAS__CH01__CHATTER__OFFSCREEN_SQUEEZE__030__M__1": "Bırakın onu, lütfen!",
"VO__LUCAS__CH01__CHATTER__SPRINTING__020__M__1": "Domuz gibi terliyorum...",
"VO__LUCAS__CH01__CHATTER__SPRINTING__050__M__1": "Yanıyorum desene!",
"VO__LUCAS__CH01__ONOM__ARRIVAL_RUINS__020__M__1": "Ha...",
"VO__LUCAS__CH01__ONOM__CART_SQUEEZE_THROUGH__040__M__1": "Ah!",
"VO__LUCAS__CH01__RTC__010_OPENING__090__M__1": "Lanet böğürtlenler!",
"VO__LUCAS__CH01__RTC__010_OPENING__095__M__1": "Benim için çok hızlısın...",
"VO__LUCAS__CH01__RTC__010_OPENING__200__M__1": "Bu hiç yorulmaz mı? Gerçekten çalışmaya dönmeliyim...",
"VO__LUCAS__CH01__RTC__035_CART__006__M__1": "İyi uyudun mu?",
"VO__LUCAS__CH01__RTC__035_CART__040__M__1": "Muhtemelen kanındaki tuz eksikliğinden.",
"VO__LUCAS__CH01__RTC__035_CART__070__M__1": "Biliyor musun, orada Düzen'den büyük bir simyacıyla buluşacağız! Macula'yı çok iyi biliyorlar. Yüzyıllardır onu inceliyorlar.",
"VO__LUCAS__CH01__RTC__035_CART__110__M__1": "Bulacaklar. Macula sadece Hugo'nun kanında değil, herkesi ilgilendiriyor ve her şeyi değiştirebilir.",
"VO__LUCAS__CH01__RTC__040_CONSEQUENCES__065__M__1": "Merhaba...",
"VO__LUCAS__CH01__RTC__050_ONCE_AGAIN__050__M__1": "Hâlâ nefes alıyor.",
"VO__LUCAS__CH01__RTC__050_ONCE_AGAIN__060__M__1": "Şoktan...",
"VO__PEOPLE_M1__CH01__CHATTER__BROTHERS_ARRIVAL__080__M__1": "Yakaladım!",
"VO__PEOPLE_M1__CH01__CHATTER__BROTHERS_ARRIVAL__160__M__1": "Tanrım, Mathias...",
"VO__PEOPLE_M1__CH01__CHATTER__BROTHERS_ARRIVAL__190__M__1": "Pekâlâ...",
"VO__PEOPLE_M1__CH01__CHATTER__NEMESIS_BACK__020__M__1": "Hayır... Yerdeki o adam yakaladığımız sonuncusuydu...",
"VO__PEOPLE_M1__CH01__RTC__022_BREAKING_POINT__080__M__1": "Bu hırsızlarla mısın sen?!",
"VO__PEOPLE_M1__CH01__RTC__022_BREAKING_POINT__120__M__1": "Ama çocuk...",
"VO__PEOPLE_M1__CH01__RTC__022_BREAKING_POINT__140__M__1": "Gelmemeliydin...",
"VO__PEOPLE_M1__CH01__RTC__022_BREAKING_POINT__160__M__1": "Çok konuşuyorsun...",
"VO__PEOPLE_M2__CH01__CHATTER__BROTHERS_ARRIVAL__010__M__1": "Seni alçak!",
"VO__PEOPLE_M2__CH01__CHATTER__BROTHERS_ARRIVAL__020__M__1": "İşin bitti!",
"VO__PEOPLE_M2__CH01__CHATTER__BROTHERS_ARRIVAL__060__M__1": "Yakalayın onu!",
"VO__PEOPLE_M2__CH01__CHATTER__BROTHERS_ARRIVAL__090__M__1": "Durun! Onu bana bırakın.",
"VO__PEOPLE_M2__CH01__CHATTER__BROTHERS_ARRIVAL__120__M__1": "Bizden çalmadan önce bunu düşünseydiniz!",
"VO__PEOPLE_M2__CH01__CHATTER__BROTHERS_ARRIVAL__170__M__1": "Geri gelmediklerinden böyle emin oluruz işte!",
"VO__PEOPLE_M2__CH01__CHATTER__BROTHERS_ARRIVAL__180__M__1": "Git kapının kilitli olduğundan emin ol.",
"VO__PEOPLE_M2__CH01__CHATTER__BROTHERS_BACK__005__M__1": "Burada nöbet tut! Yarına kadar sırayla nöbetleşiriz!",
"VO__PEOPLE_M2__CH01__CHATTER__BROTHERS_BACK__020__M__1": "Tonin nerede?! Babamdan önce onu ben ellerime geçireyim...",
"VO__PEOPLE_M2__CH01__CHATTER__BROTHERS_BACK__060__M__1": "Eninde sonunda geri gelir.",
"VO__PEOPLE_M2__CH01__CHATTER__CROUCH_PROGRESS__040__M__1": "Ne rezalet!",
"VO__PEOPLE_M2__CH01__CHATTER__CROUCH_PROGRESS__050__M__1": "Şimdi etimiz ve balımız ne işine yarayacak, ha? Öldün sen.",
"VO__PEOPLE_M2__CH01__CHATTER__JACQUES__010__M__1": "Hey! Orada sızlanıp durma! Hâlâ buralarda olabilirler! Git diğerlerine yardım et!",
"VO__PEOPLE_M2__CH01__CHATTER__JACQUES__030__M__1": "Umurumda değil!",
"VO__PEOPLE_M2__CH01__CHATTER__JACQUES__050__M__1": "Buraya son gelişleri bu, diyorum sana.",
"VO__PEOPLE_M2__CH01__CHATTER__OLDER_BROTHER_2__010__M__1": "Şimdi bu küçük bok nerede?! Nöbet tutman gerekiyordu! Hepsi senin yüzünden...",
"VO__PEOPLE_M2__CH01__CHATTER__OLDER_BROTHER_2__020__M__1": "TONIN! Lanet kıçını HEMEN buraya getir!... Canını çıkaracağım senin...",
"VO__PEOPLE_M2__CH01__CHATTER__WHEELBARROW__020__M__1": "Kahretsin, hayır!... Hayır, hayır! Dede!",
"VO__PEOPLE_M2__CH01__CHATTER__WHEELBARROW__030__M__1": "Ah, kötü görünüyor... Babam her an pazardan dönebilir!",
"VO__PEOPLE_M2__CH01__CHATTER__WHEELBARROW__050__M__1": "Evet... Şimdilik ona göz kulak ol!",
"VO__PEOPLE_M2__CH01__RTC__022_BREAKING_POINT__020__M__1": "Babamın en büyük hatasıydın... ama ben bunu düzelteceğim.",
"VO__PEOPLE_M2__CH01__RTC__022_BREAKING_POINT__050__M__1": "Ne?... Kimsin sen?!",
"VO__PEOPLE_M2__CH01__RTC__022_BREAKING_POINT__070__M__1": "Duydun mu Remi?",
"VO__PEOPLE_M2__CH01__RTC__022_BREAKING_POINT__110__M__1": "Burada bulunmaya hakkın yok! Remi, sen hâllet. Ve beni hayal kırıklığına uğratma.",
"VO__PEOPLE_M2__CH01__RTC__022_BREAKING_POINT__130__M__1": "Öğrenecek yaşta.",
"VO__PEOPLE_M2__CH01__RTC__035_CART__150__M__1": "Merhaba!",
"VO__PEOPLE_M2__CH01__RTC__035_CART__170__M__1": "Nereden geldiğinizi sorabilir miyim?",
"VO__PEOPLE_M2__CH01__RTC__035_CART__190__M__1": "Vay, gerçekten uzun yol... Hmm... Şey, geride bir çiftliğe saldırı oldu. Genç bir kız, senin yaşlarında, yanında küçük bir oğlanla.",
"VO__PEOPLE_M3__CH01__CHATTER__CHASED__010__M__1": "Geri gel buraya!",
"VO__PEOPLE_M3__CH01__CHATTER__IDLE_TRACKING_1__010__M__1": "Bu fazlasıyla çok oldu! Bu sefer gitmenize izin vereceğimizi sanmayın!",
"VO__PEOPLE_M3__CH01__CHATTER__IDLE_TRACKING_2__010__M__1": "Sizi asla geri alamayız sandınız, değil mi?!",
"VO__PEOPLE_M3__CH01__CHATTER__IDLE_TRACKING_3__010__M__1": "Sizi lanet hırsızlar... emeğimizi çalmaya çalışıyorsunuz...",
"VO__PEOPLE_M3__CH01__CHATTER__NEMESIS_BACK__010__M__1": "Hey! İkisini kaybettim, bir oğlanla bir kız! Onları görmediniz mi?!",
"VO__PEOPLE_M3__CH01__CHATTER__NEMESIS_BACK__030__M__1": "Bulursanız öldürün onları!",
"VO__PEOPLE_M3__CH01__CHATTER__WHEELBARROW__010__M__1": "Mathias! Gel! Dedeyi fena hâlde yaralamışlar!",
"VO__PEOPLE_M3__CH01__CHATTER__WHEELBARROW__040__M__1": "Çok öfkelenecek...",
"VO__PEOPLE_M3__CH01__CHATTER__WRONG_WAY__030__M__1": "Kapana kısıldınız! Hiçbir yere gidemezsiniz!",
"VO__PEOPLE_M3__CH01__RTC__021_BEEKEEPER__020__M__1": "Hey!",
"VO__PEOPLE_M3__CH01__RTC__021_BEEKEEPER__040__M__1": "Kaç kişisiniz?!",
"VO__PEOPLE_M3__CH01__RTC__021_BEEKEEPER__060__M__1": "Yalan...",
"VO__PEOPLE_M3__CH01__RTC__021_BEEKEEPER__080__M__1": "YALAN!",
"VO__PEOPLE_M3__CH01__RTC__021_BEEKEEPER__090__M__1": "Sizi lanet hırsızlar... Parçalara ayıracağım sizi!",
"VO__PEOPLE_M4__CH01__CHATTER__2ND_BEEKEEPER__025__M__1": "En azından bunlara zarar vermemişler...",
"VO__PEOPLE_M4__CH01__CHATTER__EMERGENCY_TUTO_THROW__040__M__1": "Bu da ne?!",
"VO__PEOPLE_M4__CH01__CHATTER__EMERGENCY_TUTO_THROW__050__M__1": "Hey! Göster kendini!",
"VO__PEOPLE_M4__CH01__CHATTER__FATHER_FIRE__021__M__1": "Hayır! Her şeyi yakacaksın!",
"VO__PEOPLE_M4__CH01__CHATTER__STUNG__040__M__1": "Ne?! Kim var orada?!",
"VO__PEOPLE_M4__CH01__RTC__040_CONSEQUENCES__005__M__1": "Bir oğlanla bir kız arıyoruz.",
"VO__PEOPLE_M4__CH01__RTC__040_CONSEQUENCES__020__M__1": "Bir ailenin mülküne izinsiz girdiler. Bir tartışma çıktı ve adamlar katledildi. Küçük kardeş buna tanık oldu.",
"VO__PEOPLE_M4__CH01__RTC__040_CONSEQUENCES__040__M__1": "Ah, ben de. Çocuklar yeğenlerim.",
"VO__PEOPLE_M4__CH01__RTC__040_CONSEQUENCES__070__M__1": "Uzun sürmez...",
"VO__PEOPLE_M4__CH01__RTC__040_CONSEQUENCES__100__M__1": "Buraya gel!",
"VO__PEOPLE_M4__CH01__RTC__040_CONSEQUENCES__130__M__1": "Sen! Arabayı al! Kaçmasına izin verme!",
"VO__TONIN__CH01__CHATTER__TONIN__010__M__1": "Merhaba!",
"VO__TONIN__CH01__CHATTER__TONIN__040__M__1": "Buradan geçiyordum ve sapanını duydum...",
"VO__TONIN__CH01__CHATTER__TONIN__046__M__1": "Sormak istedim... Sizinle oynayabilir miyim?",
"VO__TONIN__CH01__CHATTER__TONIN__051__M__1": "Ben Tonin!... Yakında yaşıyorum!",
"VO__TONIN__CH01__CHATTER__TONIN__070__M__1": "Elbette yapabilirim!",
"VO__TONIN__CH01__CHATTER__TONIN_BOOM_1__010__M__1": "BUM!",
"VO__TONIN__CH01__CHATTER__TONIN_HIT_1__010__M__1": "Vay! Keskin nişancısın!",
"VO__TONIN__CH01__CHATTER__TONIN_HIT_2__010__M__1": "İyisin!",
"VO__TONIN__CH01__CHATTER__TONIN_HIT_3__030__M__1": "Evet! Kıçlarına tekmeyi basıyoruz!",
"VO__TONIN__CH01__CHATTER__TONIN_HIT_3__060__M__1": "Savaş bu! Nezakete yer yok!",
"VO__TONIN__CH01__CHATTER__TONIN_SHOOT__020__M__1": "Topu ateşleyeyim o zaman!",
"VO__TONIN__CH01__RTC__020_END_GAME__010__M__1": "İşte gülle geliyor!",
"VO__TONIN__CH01__RTC__020_END_GAME__060__M__1": "Teslimiyet kabul edildi!",
"VO__TONIN__CH01__RTC__020_END_GAME__065__M__1": "Ee... Artık gitmeliyim... İşe geç kaldım...",
"VO__TONIN__CH01__RTC__020_END_GAME__080__M__1": "Evet, babamın çiftliğinde... kardeşlerimle...",
"VO__TONIN__CH01__RTC__020_END_GAME__086__M__1": "Ee... Gitmeliyim! Güle güle!",
"VO__TONIN__CH01__RTC__022_BREAKING_POINT__010__M__1": "Durun! Lütfen!",
}
