# -*- coding: utf-8 -*-
# CH10 VO. onom/EMPTY atlanir. Milo(LEADER=kole tuccari reisi), slavers->kole tuccarlari,
# slaves->koleler, chapel->sapel, temple->tapinak, fort->kale, crypt->kript,
# portcullis->kapi kafesi, chandelier->avize, the Protector->Koruyucu, Carrier->Tasiyici,
# Aelia/Basilius/Milo/Diaz/Vaudin korunur, raven->kuzgun, convent->manastir, prism->prizma.
# Amicia/Hugo/Sophia=sen; dusmanlar=sen (hor).
T = {
"VO__AMICIA__CH10__CHATTER__AFTER_EVENT_KNIFE__005__M__1": "Lütfen...",
"VO__AMICIA__CH10__CHATTER__AFTER_EVENT_KNIFE__010__M__1": "Onu çekin!",
"VO__AMICIA__CH10__CHATTER__AFTER_EVENT_KNIFE__023__M__1": "Ha... Teşekkürler...",
"VO__AMICIA__CH10__CHATTER__AFTER_EVENT_KNIFE__030__M__1": "Hugo... Bitti...",
"VO__AMICIA__CH10__CHATTER__AFTER_EVENT_KNIFE__043__M__1": "Sorun yok. İyi yaptın—Bizim halletmemize izin verdin. Şimdi gitmeliyiz, hadi.",
"VO__AMICIA__CH10__CHATTER__AFTER_EVENT_KNIFE__047__M__1": "Nasılsın Sophia?",
"VO__AMICIA__CH10__CHATTER__AFTER_EVENT_KNIFE__060__M__1": "Gerçekten üzgünüm ama... yaptığına sevindim...",
"VO__AMICIA__CH10__CHATTER__AFTER_EVENT_KNIFE__110__M__1": "Edeceğim. Devam edelim...",
"VO__AMICIA__CH10__CHATTER__AFTER_FALL__020__M__1": "Bilmiyorum... Eğik dur!",
"VO__AMICIA__CH10__CHATTER__AFTER_STRIKE__010__M__1": "Hugo, dinle... Ha...",
"VO__AMICIA__CH10__CHATTER__AFTER_STRIKE__020__M__1": "Hugo...",
"VO__AMICIA__CH10__CHATTER__AFTER_STRIKE__040__M__1": "Ne yapsaydım?! \"Ah, bu arada, kardeşim fareleri kontrol ediyor ve onlara insan yedirtiyor...\"? Kaçardın! Ve ben... istemedim ki... Yanlıştı, evet! Ama düşündüm ki... burası bize bir şans verir! Düşündüm ki... bizi böyle... görmek zorunda kalmazsın...",
"VO__AMICIA__CH10__CHATTER__AFTER_STRIKE__070__M__1": "Anlıyorum.",
"VO__AMICIA__CH10__CHATTER__AMICIA_IS_BACK__020__M__1": "Evet! Buradayım!",
"VO__AMICIA__CH10__CHATTER__AMICIA_IS_BACK__040__M__1": "İyiyim ama öldürmeye niyetliler... Vakit kaybetmeyelim.",
"VO__AMICIA__CH10__CHATTER__AMICIA_IS_BACK__060__M__1": "Ama... Gitmen gerekiyorsa, şimdi yap, Sophia.",
"VO__AMICIA__CH10__CHATTER__AMICIA_SOPHIA__010__M__1": "Teşekkürler... Onun için biraz zor.",
"VO__AMICIA__CH10__CHATTER__AMICIA_SOPHIA__030__M__1": "Biliyorum. Ve öyle. Bunu da bu yüzden yapıyoruz.",
"VO__AMICIA__CH10__CHATTER__AMICIA_SOPHIA__050__M__1": "Cehennemden geçtik, Sophia. Hayal bile edemezsin...",
"VO__AMICIA__CH10__CHATTER__AMICIA_SOPHIA__070__M__1": "Başka hiçbir şeyimiz yok.",
"VO__AMICIA__CH10__CHATTER__ARMORED_SLAVERS_IDLE__020__M__1": "Gergin görünüyorlar... her ne sebeptense...",
"VO__AMICIA__CH10__CHATTER__ARMY_IDLE__010__M__1": "Bir ordu gibiler...",
"VO__AMICIA__CH10__CHATTER__ARMY_IDLE__030__M__1": "Biliyorum...",
"VO__AMICIA__CH10__CHATTER__BABY_BOAT__050__M__1": "Güzel ifade ettin...",
"VO__AMICIA__CH10__CHATTER__BABY_BOAT__080__M__1": "Teşekkürler, Sophia...",
"VO__AMICIA__CH10__CHATTER__BACK_ON_TRACK__010__M__1": "Hey Hugo, yolda şenliklerinin ne durumda olduğuna bakabiliriz!",
"VO__AMICIA__CH10__CHATTER__BACK_ON_TRACK__040__M__1": "Yine de bir bakarız.",
"VO__AMICIA__CH10__CHATTER__BACK_TO_MAP__010__M__1": "Pekâlâ... Burada bir kule var mı yoksa...?",
"VO__AMICIA__CH10__CHATTER__BACK_TO_MAP__023__M__1": "Haklısın!",
"VO__AMICIA__CH10__CHATTER__BACK_TO_MAP__030__M__1": "O zaman yine yolumuza döndük, gidelim!",
"VO__AMICIA__CH10__CHATTER__BACK_TO_MAP_ENTER__010__M__1": "Şu haritaya bir daha bakalım...",
"VO__AMICIA__CH10__CHATTER__BACK_TO_TOPIC__040__M__1": "Sonra, evet...",
"VO__AMICIA__CH10__CHATTER__BACK_TO_TOPIC__080__M__1": "Evet, yakında. Şapelimizi bulup göreceğiz.",
"VO__AMICIA__CH10__CHATTER__BAD_SIGNS__010__M__1": "Eyvah...",
"VO__AMICIA__CH10__CHATTER__BAD_SIGNS__050__M__1": "Zincire vurulmuş...",
"VO__AMICIA__CH10__CHATTER__BAD_SIGNS__070__M__1": "Hayır... O şapele ulaşmamız gerek.",
"VO__AMICIA__CH10__CHATTER__BAD_SIGNS__090__M__1": "Dikkatli olacağız!",
"VO__AMICIA__CH10__CHATTER__BAD_SIGNS__110__M__1": "Gidelim.",
"VO__AMICIA__CH10__CHATTER__BASEMENT__030__M__1": "Ki o da muhtemelen yakınlarda bir yerde...",
"VO__AMICIA__CH10__CHATTER__BODIES__015__M__1": "Buradalar. Eğik dur.",
"VO__AMICIA__CH10__CHATTER__BODIES__050__M__1": "Delilik! Aelia'ya ve şu şapele odaklanalım.",
"VO__AMICIA__CH10__CHATTER__BODIES_TORCHES__010__M__1": "Ah... Tanrım...",
"VO__AMICIA__CH10__CHATTER__BODIES_TORCHES__040__M__1": "Kanın, Çocuk'a şapele giden yolu göstereceğini söyledi.",
"VO__AMICIA__CH10__CHATTER__BRIDGE_TUTO__040__M__1": "Bakalım onu bitirebilecek miyiz.",
"VO__AMICIA__CH10__CHATTER__BRIGHTER_IDLE__010__M__1": "Adanın geri kalanı... bu... olup biterken nasıl kutlama yapabiliyor?...",
"VO__AMICIA__CH10__CHATTER__BRIGHTER_IDLE__030__M__1": "Zaten bu Milo aklını tamamen kaçırmış gibi görünüyor...",
"VO__AMICIA__CH10__CHATTER__BROKEN_LEAVE__020__M__1": "Başka bir yol buluruz.",
"VO__AMICIA__CH10__CHATTER__BUSINESS_IDLE__020__M__1": "Bir parça toprak ve... insan satma hakkı... karşılığında paranın bir payı.",
"VO__AMICIA__CH10__CHATTER__CART_BRIDGE__020__M__1": "O şapelde ne yapıyorlar?!",
"VO__AMICIA__CH10__CHATTER__CART_BRIDGE_IN__010__M__1": "Bunlar kadim duvarlar. Bir açıklık olacaktır.",
"VO__AMICIA__CH10__CHATTER__CART_BRIDGE_IN__040__M__1": "Gitmemiz lazım. Bu karmaşa bir anlam taşıyor.",
"VO__AMICIA__CH10__CHATTER__CHANDELIER_CRANK__010__M__1": "Bakalım bu ne yapıyor...",
"VO__AMICIA__CH10__CHATTER__CHANDELIER_DOOR__030__M__1": "Kabul.",
"VO__AMICIA__CH10__CHATTER__CHANDELIER_HOLD__020__M__1": "Tuttum...",
"VO__AMICIA__CH10__CHATTER__CHANDELIER_MOVING__020__M__1": "Sanırım bir avize!",
"VO__AMICIA__CH10__CHATTER__CHANDELIER_MOVING__040__M__1": "Şu zincir dayanıyor gibi!",
"VO__AMICIA__CH10__CHATTER__CHANDELIER_PULL__010__M__1": "Tut! Çekiyorum!",
"VO__AMICIA__CH10__CHATTER__CHANDELIER_ROPE__010__M__1": "Sadece... şanssızlık.",
"VO__AMICIA__CH10__CHATTER__CHANDELIER_ROPE_GRAB__020__M__1": "Şu halata bakalım...",
"VO__AMICIA__CH10__CHATTER__CHAPEL_COURTYARD__020__M__1": "Kurban edilmişler... hayvanlar gibi...",
"VO__AMICIA__CH10__CHATTER__CHAPEL_COURTYARD__040__M__1": "Kanın, Çocuk'un onları sevmesini sağlayacağını sanıyorlar.",
"VO__AMICIA__CH10__CHATTER__CHAPEL_COURTYARD__060__M__1": "O şapele girip sonra gidelim...",
"VO__AMICIA__CH10__CHATTER__CHAPEL_DOWN__010__M__1": "Şuraya, aşağı bakalım...",
"VO__AMICIA__CH10__CHATTER__CHAPEL_EIGHTH_IDLE__040__M__1": "Hugo! Sophia'yı dinle!",
"VO__AMICIA__CH10__CHATTER__CHAPEL_ENTER__005__M__1": "Nihayet...",
"VO__AMICIA__CH10__CHATTER__CHAPEL_ENTER__020__M__1": "Bu fresk... Taşıyıcı ve Koruyucusu... Onun göründüğü tek fresk bu...",
"VO__AMICIA__CH10__CHATTER__CHAPEL_ENTER__040__M__1": "Koruyucu'ya... Aelia sadece bir görevi dolduruyordu. Bu onun... Düzen içindeki işleviydi.",
"VO__AMICIA__CH10__CHATTER__CHAPEL_FIFTH_WAVE__010__M__1": "Dur, lanet olsun!",
"VO__AMICIA__CH10__CHATTER__CHAPEL_FIFTH_WAVE__030__M__1": "Sakin ol, Hugo! Sophia, lütfen!",
"VO__AMICIA__CH10__CHATTER__CHAPEL_FIRST_IDLE__010__M__1": "Sakin kal... Sabit dur...",
"VO__AMICIA__CH10__CHATTER__CHAPEL_FIRST_KILL__010__M__1": "Bizi durduramayacaksın... Şimdi olmaz...",
"VO__AMICIA__CH10__CHATTER__CHAPEL_FIRST_WAVE__030__M__1": "Bir çıkış görüyor musun, Sophia?!",
"VO__AMICIA__CH10__CHATTER__CHAPEL_FIRST_WAVE__060__M__1": "Hata yapıyorsun!",
"VO__AMICIA__CH10__CHATTER__CHAPEL_FOURTH_KILL__010__M__1": "Bırakın gidelim! Buna burada son verebiliriz!",
"VO__AMICIA__CH10__CHATTER__CHAPEL_NINTH_WAVE__030__M__1": "Buna son veriyorum, Hugo, tamam mı?!... Vermek zorundayım... ne pahasına olursa olsun.",
"VO__AMICIA__CH10__CHATTER__CHAPEL_SEVENTH_WAVE__030__M__1": "Dayanamayacak... Buna çabucak son vermeliyim...",
"VO__AMICIA__CH10__CHATTER__CHAPEL_SEVENTH_WAVE__050__M__1": "Hayır! Gözlerini kapat ve kulaklarını tıka, duydun mu beni?!",
"VO__AMICIA__CH10__CHATTER__CHAPEL_SIXTH_IDLE__020__M__1": "Buradan... çıkamayacağız...",
"VO__AMICIA__CH10__CHATTER__CHAPEL_SIXTH_WAVE__010__M__1": "Tanrım... Gelmeye devam ediyorlar!",
"VO__AMICIA__CH10__CHATTER__CHAPEL_THIRD_IDLE__010__M__1": "Neredeyse vardık... Şimdi yıkılma!",
"VO__AMICIA__CH10__CHATTER__CHAPEL_THIRD_WAVE__020__M__1": "O zaman bir tane bulmaya çalış!",
"VO__AMICIA__CH10__CHATTER__CHAPEL_THIRD_WAVE__060__M__1": "Geri çekil! Yoksa ölürsün!",
"VO__AMICIA__CH10__CHATTER__CHILD_IDLE__010__M__1": "Milo'nun Çocuk hakkında ne kadar şey bildiğini merak ediyorum...",
"VO__AMICIA__CH10__CHATTER__CLIFF_FALL__050__M__1": "Vay! Ne?!",
"VO__AMICIA__CH10__CHATTER__CLIFF_FALL_REACTION__020__M__1": "Şşş! Sessiz!",
"VO__AMICIA__CH10__CHATTER__CLIFF_FALL_REACTION__040__M__1": "Tam üstümüzde...",
"VO__AMICIA__CH10__CHATTER__CLOSE_TRENCH_TWO__010__M__1": "Güzel! Şu hendeği yine geçme vakti...",
"VO__AMICIA__CH10__CHATTER__CLOSED_GATE__010__M__1": "Hmm... Diğer taraftan kilitli.",
"VO__AMICIA__CH10__CHATTER__CLOSED_GATE_OK__010__M__1": "Evet... Açık—geri dönebiliriz.",
"VO__AMICIA__CH10__CHATTER__CLOSED_GATE_VAULT__010__M__1": "Burada!",
"VO__AMICIA__CH10__CHATTER__CLOSED_GATE_VAULT__030__M__1": "Sana söylemedim ama Hugo kral ve ben de muhafızlarının kaptanıyım...",
"VO__AMICIA__CH10__CHATTER__CLOSED_GATE_VAULT__070__M__1": "Unutma, hâlâ fethedecek gerçek bir kalemiz var.",
"VO__AMICIA__CH10__CHATTER__COME_DOWN__020__M__1": "Evet...",
"VO__AMICIA__CH10__CHATTER__CONTINUE_CHECK__010__M__1": "İyi... misin?",
"VO__AMICIA__CH10__CHATTER__CONTINUE_CHECK__030__M__1": "...evet.",
"VO__AMICIA__CH10__CHATTER__CONTINUE_CHECK__050__M__1": "Evet...",
"VO__AMICIA__CH10__CHATTER__COUNTESS_RELATIONS__030__M__1": "Bu insanların nasıl çalıştığını biliyor...",
"VO__AMICIA__CH10__CHATTER__CRANK__010__M__1": "Bu, kapı kafesini hareket ettirmeli...",
"VO__AMICIA__CH10__CHATTER__CRANK__030__M__1": "Evet.",
"VO__AMICIA__CH10__CHATTER__CROSS_HOW__020__M__1": "Bize güvenli bir yol açacağım...",
"VO__AMICIA__CH10__CHATTER__CROSSING_VILLAGE__030__M__1": "Bu insanların var olduğunu biliyorsun, Hugo...",
"VO__AMICIA__CH10__CHATTER__CRYPT_ENTER__020__M__1": "Bilmiyorum... Aelia daha önemli.",
"VO__AMICIA__CH10__CHATTER__CRYPT_ENTER__025__M__1": "Bir kript mi?",
"VO__AMICIA__CH10__CHATTER__CRYPT_ENTER__040__M__1": "Bir bakayım...",
"VO__AMICIA__CH10__CHATTER__DO_IT__010__M__1": "Şu an önemi yok, Hugo!",
"VO__AMICIA__CH10__CHATTER__DO_IT__020__M__1": "Panik yapma... Düşün... Etrafına bak...",
"VO__AMICIA__CH10__CHATTER__DOOR_LOCKED__007__M__1": "O zaman... onu açmamız gerekecek...",
"VO__AMICIA__CH10__CHATTER__DOOR_LOCKED__010__M__1": "Kıpırdamıyor...",
"VO__AMICIA__CH10__CHATTER__DOOR_OPEN__050__M__1": "Biliyorum...",
"VO__AMICIA__CH10__CHATTER__EXIT__010__M__1": "Kale ileride... Güzel.",
"VO__AMICIA__CH10__CHATTER__EXIT__030__M__1": "Rüyalar nadiren tüm gerçeği gösterir.",
"VO__AMICIA__CH10__CHATTER__EXIT__055__M__1": "Rüyaların vermediğini biz alabiliriz, Hugo.",
"VO__AMICIA__CH10__CHATTER__FALL_CRASH_EVENT__040__M__1": "Hayır! Ha... Hayır.... Hı....",
"VO__AMICIA__CH10__CHATTER__FALL_CRASH_EVENT__050__M__1": "Gnnn...",
"VO__AMICIA__CH10__CHATTER__FEATHER__010__M__1": "Gördün mü, Hugo? Bir tüy!",
"VO__AMICIA__CH10__CHATTER__FEATHER__030__M__1": "Neden? Çok güzel! Bir kuzgundan!",
"VO__AMICIA__CH10__CHATTER__FEATHER__070__M__1": "Ki insanlar onu rahat bıraksın diye!",
"VO__AMICIA__CH10__CHATTER__FEATHER__090__M__1": "İnsanlardan daha karanlık değiller...",
"VO__AMICIA__CH10__CHATTER__FEATHER_PATH__010__M__1": "Buradan deneyelim...",
"VO__AMICIA__CH10__CHATTER__FIRE_CROSS__010__M__1": "Geldik...",
"VO__AMICIA__CH10__CHATTER__FIRE_EXTINGUISHED__010__M__1": "Al bakalım...",
"VO__AMICIA__CH10__CHATTER__FIRE_LIT__010__M__1": "Şimdi ne olacak?!",
"VO__AMICIA__CH10__CHATTER__FIRST_KILL__020__M__1": "Ne?",
"VO__AMICIA__CH10__CHATTER__FIRST_KILL__040__M__1": "Hoşuma gitmiyor. Ama hep yapmak zorunda kalıyorum.",
"VO__AMICIA__CH10__CHATTER__GATE_HALLWAY__010__M__1": "Evet... Geldik...",
"VO__AMICIA__CH10__CHATTER__HUB2_FLOWERPATH__010__M__1": "Şuradaki bizim kule, değil mi?",
"VO__AMICIA__CH10__CHATTER__HUB2_FLOWERPATH__040__M__1": "Olacak... Geçmiş asla ölmez, Hugo. Onun görüntüleri rüyandan geçti, değil mi?",
"VO__AMICIA__CH10__CHATTER__HUB2_FLOWERPATH__070__M__1": "O şapelde bir şey bulacağız.",
"VO__AMICIA__CH10__CHATTER__HUB2_FOREST_NOMAP__020__M__1": "Evet, sağ ol... Unutmamıştım.",
"VO__AMICIA__CH10__CHATTER__HUB2_GOINGDOWN_START__010__M__1": "Ben de... ama bir ipucumuz var.",
"VO__AMICIA__CH10__CHATTER__HUB2_GOINGDOWN_START__030__M__1": "Hm. Neden olmasın...",
"VO__AMICIA__CH10__CHATTER__HUB2_NEW_THINGS__020__M__1": "Buradan geçelim, hoş olur.",
"VO__AMICIA__CH10__CHATTER__HUB2_SOPHIA_STORY__005__M__1": "Bu epey ilginçti. Ama bir manastıra gittiğine hâlâ inanamıyorum...",
"VO__AMICIA__CH10__CHATTER__HUB2_SOPHIA_STORY__020__M__1": "Görünüşe göre pek işe yaramamış.",
"VO__AMICIA__CH10__CHATTER__HUB2_SOPHIA_STORY__050__M__1": "Ah, hı... Göreceğiz, merak etme.",
"VO__AMICIA__CH10__CHATTER__HUB2_SOPHIA_STORY__080__M__1": "Haklı. Biz seninleyiz.",
"VO__AMICIA__CH10__CHATTER__HUB2_VILLAGE_NOMAP__030__M__1": "Geri döneceğiz. Zaten sanırım yolumuz bu.",
"VO__AMICIA__CH10__CHATTER__IDLE_CHAPEL__010__M__1": "Evet...",
"VO__AMICIA__CH10__CHATTER__IDLE_CHAPEL__030__M__1": "Tam kusursuz.",
"VO__AMICIA__CH10__CHATTER__IDLE_FORT_1__020__M__1": "Bu daha da beter...",
"VO__AMICIA__CH10__CHATTER__IDLE_FORT_1__040__M__1": "Başaracağız.",
"VO__AMICIA__CH10__CHATTER__IDLE_FORT_2__010__M__1": "Nasıl hissediyorsun, Hugo?",
"VO__AMICIA__CH10__CHATTER__IDLE_FORT_2__030__M__1": "Söz... veriyorum, geçecek.",
"VO__AMICIA__CH10__CHATTER__IDLE_FORT_3__020__M__1": "Sana koymalarına izin verme. Sen bundan daha iyisin.",
"VO__AMICIA__CH10__CHATTER__IDLE_FORT_4__020__M__1": "Yanımızda kal...",
"VO__AMICIA__CH10__CHATTER__IDLE_FORT_4__040__M__1": "Fırsat bulur bulmaz gideceğiz, sana söz veriyorum.",
"VO__AMICIA__CH10__CHATTER__IDLE_FORT_5__030__M__1": "Olacak.",
"VO__AMICIA__CH10__CHATTER__INTERACT_CART__010__M__1": "Pekâlâ, ilerliyoruz...",
"VO__AMICIA__CH10__CHATTER__INTERACT_FALL__010__M__1": "Gel.",
"VO__AMICIA__CH10__CHATTER__INTERACT_FALL__020__M__1": "Gel...",
"VO__AMICIA__CH10__CHATTER__INTERACT_FALL__035__M__1": "Hı!",
"VO__AMICIA__CH10__CHATTER__INTERACT_FALL__045__M__1": "Sanırım... öyle...",
"VO__AMICIA__CH10__CHATTER__INTRO_SLAVES__005__M__1": "Dahası var...",
"VO__AMICIA__CH10__CHATTER__INTRO_SLAVES__060__M__1": "Diğerleri?",
"VO__AMICIA__CH10__CHATTER__INTRO_SLAVES__100__M__1": "Lanet olsun... Kim bunlar?!",
"VO__AMICIA__CH10__CHATTER__INTRO_SLAVES__150__M__1": "Ama bu bizi durduramaz.",
"VO__AMICIA__CH10__CHATTER__KILL_FORT_1__020__M__1": "Yapmam gerekeni... yapacağım...",
"VO__AMICIA__CH10__CHATTER__KILL_FORT_3__010__M__1": "Tamam...",
"VO__AMICIA__CH10__CHATTER__KILL_FORT_3__030__M__1": "Üzerinde çalışıyorum...",
"VO__AMICIA__CH10__CHATTER__KILLED_ALL_FORT__010__M__1": "Hepsi buydu... Artık daha kolay olacak.",
"VO__AMICIA__CH10__CHATTER__KNIFE_EVENT__020__M__1": "Lanet...",
"VO__AMICIA__CH10__CHATTER__LADY_IDLE__040__M__1": "Göreceğiz. Neler olduğunu bile bilmiyoruz.",
"VO__AMICIA__CH10__CHATTER__LIGHT_FIRE_CART__010__M__1": "Bir iş tamam...",
"VO__AMICIA__CH10__CHATTER__LIKE_FEATHER__070__M__1": "Şey, şimdi sakın uçup gitme, lütfen.",
"VO__AMICIA__CH10__CHATTER__MANY_SLAVERS_IDLE__010__M__1": "Kaç tane var?",
"VO__AMICIA__CH10__CHATTER__MILO_LEFT__040__M__1": "Evet... Geçmeyi deneyelim.",
"VO__AMICIA__CH10__CHATTER__PATROL_MERCENARIES__060__M__1": "Bunun sonu iyi bitemez...",
"VO__AMICIA__CH10__CHATTER__PORTCULLIS_FOUND__020__M__1": "Hadi yapalım şunu!",
"VO__AMICIA__CH10__CHATTER__PORTCULLIS_INSIDE__010__M__1": "Onu kaldırmamız lazım...",
"VO__AMICIA__CH10__CHATTER__PORTCULLIS_MOVING__020__M__1": "Biliyorum...",
"VO__AMICIA__CH10__CHATTER__PORTCULLIS_MOVING__040__M__1": "Pek değil... Ama gidelim.",
"VO__AMICIA__CH10__CHATTER__PORTCULLIS_NEAR__010__M__1": "Kapının üstündeyiz... Krank yakında olmalı...",
"VO__AMICIA__CH10__CHATTER__PORTCULLIS_OPENED__030__M__1": "Onların icabına bakarız. Artık çok yakınız.",
"VO__AMICIA__CH10__CHATTER__POST_RAT_CTRL_KILL__050__M__1": "Buna... alışacaksın...",
"VO__AMICIA__CH10__CHATTER__PRISM_1ST_MOVE__020__M__1": "Geri döndüğün için teşekkürler.",
"VO__AMICIA__CH10__CHATTER__PULL_ACTION__010__M__1": "Umarım!",
"VO__AMICIA__CH10__CHATTER__PULL_SUCCESS__025__M__1": "Şey... İşe yaradı!",
"VO__AMICIA__CH10__CHATTER__PULL_SUCCESS__050__M__1": "Sadece üstüne atlama.",
"VO__AMICIA__CH10__CHATTER__RAT_CTRL_KILL__020__M__1": "Öyle... Korkma...",
"VO__AMICIA__CH10__CHATTER__RATS_IN_SCARED__030__M__1": "Tam şu kapı kafesinin arkasında...",
"VO__AMICIA__CH10__CHATTER__RATS_PASSED__030__M__1": "İşte bu. Şu kapı kafesini geçmemiz lazım...",
"VO__AMICIA__CH10__CHATTER__RATS_PASSED__040__M__1": "Aelia'nın bir mahkûm olarak aynı yoldan yürüdüğünü düşününce.",
"VO__AMICIA__CH10__CHATTER__RATS_PASSED__070__M__1": "Şimdilik, ihtiyacımız olan cevap Aelia...",
"VO__AMICIA__CH10__CHATTER__REACH_TEMPLE_DOOR__030__M__1": "Onu açmanın bir yolu olmalı...",
"VO__AMICIA__CH10__CHATTER__REACHING_CRANK__010__M__1": "Demek... burada bir halatımız var.",
"VO__AMICIA__CH10__CHATTER__READY_TO_FORT__020__M__1": "Evet, yola koyulalım.",
"VO__AMICIA__CH10__CHATTER__RELIEVED__010__M__1": "Şşş!",
"VO__AMICIA__CH10__CHATTER__RELIEVED__040__M__1": "Başka ne olduğunu görmüyorum...",
"VO__AMICIA__CH10__CHATTER__REUNION__040__M__1": "Eee, o kule artık bizim mi?",
"VO__AMICIA__CH10__CHATTER__REUNITED_WITH_SOPHIA__030__M__1": "Buradasın...",
"VO__AMICIA__CH10__CHATTER__REUNITED_WITH_SOPHIA__050__M__1": "Kötü durumda, Sophia! Bundan bir çıkış yolu görüyor musun?!",
"VO__AMICIA__CH10__CHATTER__REUNITED_WITH_SOPHIA__080__M__1": "Elbette!",
"VO__AMICIA__CH10__CHATTER__ROPE_RUINS_PICKUP__010__M__1": "Şurada ne var?",
"VO__AMICIA__CH10__CHATTER__ROPE_RUINS_PULLED__010__M__1": "Sanırım bir şey buldum...",
"VO__AMICIA__CH10__CHATTER__RUN_TOWER__010__M__1": "Neredeyse vardık!",
"VO__AMICIA__CH10__CHATTER__RUN_TOWER__070__M__1": "Görüş alanında kal!",
"VO__AMICIA__CH10__CHATTER__SEA__020__M__1": "Güzel... Şimdiden denizi mi özledin?",
"VO__AMICIA__CH10__CHATTER__SEA__080__M__1": "Ah, neyse...",
"VO__AMICIA__CH10__CHATTER__SECOND_AREA_KILL_1ST__005__M__1": "Bu ona ders olur.",
"VO__AMICIA__CH10__CHATTER__SECOND_AREA_KILL_2ND__005__M__1": "Çekil yoldan...",
"VO__AMICIA__CH10__CHATTER__SECOND_AREA_KILL_4TH__005__M__1": "Alçak...",
"VO__AMICIA__CH10__CHATTER__SECOND_AREA_KILL_4TH__020__M__1": "Ne?",
"VO__AMICIA__CH10__CHATTER__SECOND_AREA_KILL_4TH__040__M__1": "Sadece bir yol açıyorum.",
"VO__AMICIA__CH10__CHATTER__SECOND_KILL__020__M__1": "Biliyorum... Ve bilmek istemiyorum, Sophia.",
"VO__AMICIA__CH10__CHATTER__SEE_FORT__050__M__1": "Soldaki şu bina! Şapelimize benziyor, değil mi?!",
"VO__AMICIA__CH10__CHATTER__SEE_FORT__070__M__1": "Mükemmel! Kıyı şeridini takip etmeye devam edelim!",
"VO__AMICIA__CH10__CHATTER__SERIOUS_TALK__010__M__1": "Hugo...",
"VO__AMICIA__CH10__CHATTER__SERIOUS_TALK__020__M__1": "Üzgün olduğunu biliyorum... Ve yardım etmek istediğini de biliyorum... Ama insanları öldürmek... kötü insanları bile...",
"VO__AMICIA__CH10__CHATTER__SERIOUS_TALK__050__M__1": "Ve bazen bizi harekete geçmeye zorluyorlar, evet! Ama o kararı vermeyi bana bırak, lütfen.",
"VO__AMICIA__CH10__CHATTER__SERIOUS_TALK__070__M__1": "Biliyorum. Seni nasıl iyileştireceğimizi bulunca duracak. Gel buraya. Sanırım Sophia'ya bir özür borçluyuz.",
"VO__AMICIA__CH10__CHATTER__SERIOUS_TALK__090__M__1": "Ben de öyleyim...",
"VO__AMICIA__CH10__CHATTER__SLAVE_RAGDOLL__020__M__1": "Tanrım... Bu ağacı köleleri zincirlemek için kullanmışlar...",
"VO__AMICIA__CH10__CHATTER__SLAVE_RAGDOLL__040__M__1": "Ah, öyle mi...",
"VO__AMICIA__CH10__CHATTER__SLAVE_RAGDOLL__090__M__1": "Üzgünüm...",
"VO__AMICIA__CH10__CHATTER__SLAVE_RAGDOLL__110__M__1": "Onu... geri koysan iyi olur...",
"VO__AMICIA__CH10__CHATTER__SLAVE_RAGDOLL__130__M__1": "Ama belki kaçmışlardır. En önemlisi bu.",
"VO__AMICIA__CH10__CHATTER__SLAVE_RAGDOLL__150__M__1": "Gel, Hugo... Buradan gidelim...",
"VO__AMICIA__CH10__CHATTER__SMELL_OF_DEATH_IDLE__020__M__1": "Evet... Bu pis kokuda nasıl durabiliyorlar?...",
"VO__AMICIA__CH10__CHATTER__SO_MANY_DEAD_IDLE__010__M__1": "Hiç böyle bir katliam görmedim...",
"VO__AMICIA__CH10__CHATTER__SOPHIA_SHOW_PRISM__030__M__1": "Vay...",
"VO__AMICIA__CH10__CHATTER__SOPHIA_SHOW_PRISM__050__M__1": "O şey muhteşem!",
"VO__AMICIA__CH10__CHATTER__TEMPLE_IN_SIGHT__030__M__1": "Şunu geçelim... Kaleye giden bir yol bulmalıyız.",
"VO__AMICIA__CH10__CHATTER__TEMPLE_UPSTAIRS__020__M__1": "Hâlâ düşünüyorum...",
"VO__AMICIA__CH10__CHATTER__THROWER_DEAD__020__M__1": "Yan, seni domuz!",
"VO__AMICIA__CH10__CHATTER__TO_GATE__020__M__1": "Ben... evet. Söz veriyorum.",
"VO__AMICIA__CH10__CHATTER__TO_GATE_RATS__040__M__1": "Makul geliyor.",
"VO__AMICIA__CH10__CHATTER__TORTURE__010__M__1": "Ha... Lütfen Hugo... Bakma...",
"VO__AMICIA__CH10__CHATTER__TRENCH_OPENING__020__M__1": "Doğru. Ve geçmek için bir yola ihtiyacımız var.",
"VO__AMICIA__CH10__CHATTER__TRENCH_TWO__010__M__1": "İşte geçeceğimiz yer...",
"VO__AMICIA__CH10__CHATTER__TUTO_PRISM__020__M__1": "Ben hallederim.",
"VO__AMICIA__CH10__CHATTER__TUTO_PRISM__040__M__1": "Evet... Seni yüzüstü bırakmayacağım...",
"VO__AMICIA__CH10__CHATTER__TUTO_PULL_INTERACT__010__M__1": "Hm. Belki arbaletimle...",
"VO__AMICIA__CH10__CHATTER__TUTO_PULL_INTERACT__015__M__1": "Evet!",
"VO__AMICIA__CH10__CHATTER__UNSTABLE_BRIDGE__030__M__1": "Şuraya, aşağı bakalım.",
"VO__AMICIA__CH10__CHATTER__WATER_WAY__005__M__1": "Buradan deneyelim...",
"VO__AMICIA__CH10__CHATTER__WATER_WAY__030__M__1": "Hey...",
"VO__AMICIA__CH10__CHATTER__WATER_WINDOW__009__M__1": "İçeri girişimiz bu!",
"VO__AMICIA__CH10__CHATTER__WATER_WINDOW__030__M__1": "Öyleyiz.",
"VO__AMICIA__CH10__CHATTER__WEDGE_DONE__010__M__1": "Lanet...",
"VO__AMICIA__CH10__CHATTER__WEDGE_DONE__030__M__1": "Evet...",
"VO__AMICIA__CH10__CHATTER__WEDGE_INTERACT__010__M__1": "Hadi bakalım...",
"VO__AMICIA__CH10__CHATTER__WHERE_IS_MILO__020__M__1": "Şey... zaten \"işi\" bitmiş gibi görünüyordu...",
"VO__AMICIA__CH10__ONOM__KNIFE_EVENT__030__M__1": "Aaah!",
"VO__AMICIA__CH10__ONOM__PULL_SUCCESS__010__M__1": "Ha!",
"VO__AMICIA__CH10__RTC__460_BACK_FROM_SANCTUARY__005__M__1": "Pekâlâ... Hiçbir şey olmamış gibi.",
"VO__AMICIA__CH10__RTC__460_BACK_FROM_SANCTUARY__030__M__1": "Bak, rüyanda kale yoksa, o yuvarlak kuleyi ararız, tamam mı?",
"VO__AMICIA__CH10__RTC__460_BACK_FROM_SANCTUARY__050__M__1": "Belki adayı daha da süslemişlerdir!",
"VO__AMICIA__CH10__RTC__470_LEAVE_TO_FORT__010__M__1": "İşte orada... Umarım bu kale, Mabetleri kadar kalabalık değildir.",
"VO__AMICIA__CH10__RTC__470_LEAVE_TO_FORT__030__M__1": "Kont ve Kontes'in Düzen'in yazılarını kurcaladığını sanmıyorum. Burayı fazla kutsal saymış olmalılar.",
"VO__AMICIA__CH10__RTC__470_LEAVE_TO_FORT__050__M__1": "Evet, gidelim.",
"VO__AMICIA__CH10__RTC__480_ENTER_FORT__020__M__1": "Neler oluyor?",
"VO__AMICIA__CH10__RTC__480_ENTER_FORT__040__M__1": "Nereden anlıyorsun?",
"VO__AMICIA__CH10__RTC__480_ENTER_FORT__060__M__1": "En son ne zaman bir rüya senin için her şey demekti?",
"VO__AMICIA__CH10__RTC__480_ENTER_FORT__130__M__1": "Hmm... Bir zamanlar çiçeği alan bendim.",
"VO__AMICIA__CH10__RTC__480_ENTER_FORT__150__M__1": "Pekâlâ, şu kaleye çabucak varalım.",
"VO__AMICIA__CH10__RTC__480_ENTER_FORT__156__M__1": "Burada kalmak sana faydası olmaz, Hugo. Yola koyulmalıyız.",
"VO__AMICIA__CH10__RTC__480_ENTER_FORT__160__M__1": "Ayrıca, bir fırtına geliyor...",
"VO__AMICIA__CH10__RTC__485_UNEXPECTED_STRIKE__090__M__1": "Eğik dur!",
"VO__AMICIA__CH10__RTC__485_UNEXPECTED_STRIKE__160__M__1": "Çoktan çok geç.",
"VO__AMICIA__CH10__RTC__485_UNEXPECTED_STRIKE__180__M__1": "Hayır!",
"VO__AMICIA__CH10__RTC__485_UNEXPECTED_STRIKE__200__M__1": "Ne yapıyorsun?",
"VO__AMICIA__CH10__RTC__485_UNEXPECTED_STRIKE__220__M__1": "Hugo! İnsanları öyle durup dururken öldürmezsin!",
"VO__AMICIA__CH10__RTC__485_UNEXPECTED_STRIKE__240__M__1": "Çünkü...",
"VO__AMICIA__CH10__RTC__485_UNEXPECTED_STRIKE__260__M__1": "İNSANLARA TEK BAŞINA SALDIRMAZSIN! Beni dinler ve dediğimi yaparsın, anlaşıldı mı?",
"VO__AMICIA__CH10__RTC__485_UNEXPECTED_STRIKE__280__M__1": "Hugo!",
"VO__AMICIA__CH10__RTC__490_ENTER_FORT2__120__M__1": "Ya sen?",
"VO__AMICIA__CH10__RTC__490_ENTER_FORT2__140__M__1": "Şimdi!",
"VO__AMICIA__CH10__RTC__490_ENTER_FORT2__150__M__1": "O nerede?",
"VO__AMICIA__CH10__RTC__490_ENTER_FORT2__160__M__1": "Ne?",
"VO__AMICIA__CH10__RTC__490_ENTER_FORT2__200__M__1": "Eyvah... şimdi olmaz...",
"VO__AMICIA__CH10__RTC__490_ENTER_FORT2__270__M__1": "Hadi! Tırman!",
"VO__AMICIA__CH10__RTC__490_ENTER_FORT2__275__M__1": "Tutun!",
"VO__AMICIA__CH10__RTC__495_LEGACY__010__M__1": "\"Unum tueri omnes tuendo\"?",
"VO__AMICIA__CH10__RTC__495_LEGACY__030__M__1": "Bu Koruyucu'dan... Düzen onu buraya kapatmış...",
"VO__AMICIA__CH10__RTC__495_LEGACY__065__M__1": "Bunu o çizmiş...",
"VO__AMICIA__CH10__RTC__495_LEGACY__070__M__1": "Öfkeli... Taşıyıcı için korkmuş... çok küçük... Onu geri istiyor. Ve onu nereye götürdüklerini biliyor.",
"VO__AMICIA__CH10__RTC__495_LEGACY__080__M__1": "Mabet. Saray. Kale...",
"VO__AMICIA__CH10__RTC__495_LEGACY__090__M__1": "Harita mı?",
"VO__AMICIA__CH10__RTC__495_LEGACY__100__M__1": "Onu işte buraya götürmüşler.",
"VO__AMICIA__CH10__RTC__495_LEGACY__120__M__1": "Sadece...",
"VO__AMICIA__CH10__RTC__495_LEGACY__130__M__1": "...işte böyle.",
"VO__AMICIA__CH10__RTC__495_LEGACY__140__M__1": "Bir Koruyucu'nun mirası. Başka bir Koruyucu'ya.",
"VO__AMICIA__CH10__RTC__495_LEGACY__190__M__1": "Haritaya geri dönelim!",
"VO__AMICIA__CH10__RTC__500_FRESCOE__170__M__1": "Saklan! Hugo'ya göz kulak ol!",
"VO__AMICIA__CH10__RTC__510_END__060__M__1": "Hayır! Geri çekil!",
"VO__AMICIA__CH10__RTC__510_END__090__M__1": "Hugo, bu kadar yeter! Dur!",
"VO__AMICIA__CH10__RTC__510_END__110__M__1": "Onlar ÖLDÜ! Her yer çöküyor, gitmeliyiz!",
"VO__AMICIA__CH10__RTC__510_END__132__M__1": "Hey...",
"VO__AMICIA__CH10__RTC__510_END__138__M__1": "Sophia...",
"VO__AMICIA__CH10__RTC__510_END__200__M__1": "Demek... kalıyor musun?",
"VO__HUGO__CH10__CHATTER__AFTER_EVENT_KNIFE__028__M__1": "Amicia...",
"VO__HUGO__CH10__CHATTER__AFTER_EVENT_KNIFE__040__M__1": "Ne yapacağımı... bilemedim...",
"VO__HUGO__CH10__CHATTER__AFTER_FALL__010__M__1": "Kim o?!",
"VO__HUGO__CH10__CHATTER__AMICIA_IS_BACK__030__M__1": "Yaralandın mı?!",
"VO__HUGO__CH10__CHATTER__ARRESTED_SLAVERS_IDLE__010__M__1": "Ama... köle tüccarları askerler tarafından tutuklanmaz mı?",
"VO__HUGO__CH10__CHATTER__ARRESTED_SLAVERS_IDLE__030__M__1": "Neden? Çok korkunç...",
"VO__HUGO__CH10__CHATTER__BABY_BOAT__010__M__1": "Bu tekne çok, çok eski görünüyor...",
"VO__HUGO__CH10__CHATTER__BABY_BOAT__030__M__1": "Teknesi böyle kırılınca insanlara ne olur?",
"VO__HUGO__CH10__CHATTER__BABY_BOAT__070__M__1": "İğrenç...",
"VO__HUGO__CH10__CHATTER__BACK_ON_TRACK__020__M__1": "Pekâlâ...",
"VO__HUGO__CH10__CHATTER__BACK_TO_MAP__025__M__1": "Yanıyor gibi görünüyor...",
"VO__HUGO__CH10__CHATTER__BACK_TO_TOPIC__010__M__1": "Bir kaçakçı ne yapabilir?",
"VO__HUGO__CH10__CHATTER__BACK_TO_TOPIC__030__M__1": "Tekneni alıp gidebilir miyiz?",
"VO__HUGO__CH10__CHATTER__BACK_TO_TOPIC__060__M__1": "Hemen gitmek isterdim.",
"VO__HUGO__CH10__CHATTER__BAD_SIGNS__009__M__1": "Amicia... Kan var!",
"VO__HUGO__CH10__CHATTER__BAD_SIGNS__020__M__1": "Bir ceset!",
"VO__HUGO__CH10__CHATTER__BAD_SIGNS__060__M__1": "Geri dönmeliyiz...",
"VO__HUGO__CH10__CHATTER__BASEMENT__010__M__1": "Burası neresi?",
"VO__HUGO__CH10__CHATTER__BODIES_TORCHES__020__M__1": "Hayır...",
"VO__HUGO__CH10__CHATTER__BODIES_TORCHES__060__M__1": "Ne olduğundan korkuyorum...",
"VO__HUGO__CH10__CHATTER__BRIDGE_TUTO__020__M__1": "O kadar yaklaşma...",
"VO__HUGO__CH10__CHATTER__BROKEN_LEAVE__010__M__1": "Kırılmış...",
"VO__HUGO__CH10__CHATTER__CART_BRIDGE__025__M__1": "Kötü şeyler... Gerçekten gitmemiz gerekiyor mu?",
"VO__HUGO__CH10__CHATTER__CART_BRIDGE_IN__020__M__1": "Ama gitmemeliyiz...",
"VO__HUGO__CH10__CHATTER__CHANDELIER_MOVING__030__M__1": "Ağır görünüyor...",
"VO__HUGO__CH10__CHATTER__CHANDELIER_PULL__030__M__1": "Çok gürültülü olacak...",
"VO__HUGO__CH10__CHATTER__CHANDELIER_ROPE__005__M__1": "Amicia, neden köle tüccarları var? Neden burada?",
"VO__HUGO__CH10__CHATTER__CHANDELIER_ROPE__020__M__1": "Sadece o değil. Onların buraya gelmesine izin vermişler...",
"VO__HUGO__CH10__CHATTER__CHAPEL_COURTYARD__010__M__1": "Hayır... Biliyordum...",
"VO__HUGO__CH10__CHATTER__CHAPEL_COURTYARD__030__M__1": "Neden?",
"VO__HUGO__CH10__CHATTER__CHAPEL_COURTYARD__050__M__1": "Bunun için onları öldürürdü...",
"VO__HUGO__CH10__CHATTER__CHAPEL_EIGHTH_IDLE__010__M__1": "Çok tehlikeli, Amicia! Bırak onlarla ben yüzleşeyim!",
"VO__HUGO__CH10__CHATTER__CHAPEL_EIGHTH_IDLE__030__M__1": "Bana ne yapacağımı söyleme! O benim ablam!",
"VO__HUGO__CH10__CHATTER__CHAPEL_ENTER__010__M__1": "Ah... Bu... Çocuk... O kadar çoklar ki!",
"VO__HUGO__CH10__CHATTER__CHAPEL_ENTER__050__M__1": "Onu cezalandırmak istemişler.",
"VO__HUGO__CH10__CHATTER__CHAPEL_FIFTH_WAVE__025__M__1": "Hepiniz öleceksiniz!",
"VO__HUGO__CH10__CHATTER__CHAPEL_FIFTH_WAVE__050__M__1": "Bırak da gidip ona yardım edeyim!",
"VO__HUGO__CH10__CHATTER__CHAPEL_FINAL_WAVE__020__M__1": "Bu onları durdurmaz! Ben dururum!",
"VO__HUGO__CH10__CHATTER__CHAPEL_FOURTH_KILL__020__M__1": "Seni dinlemeyecekler! Çok aptallar!",
"VO__HUGO__CH10__CHATTER__CHAPEL_NINTH_WAVE__010__M__1": "Gelmeye devam ediyorlar! Bırak onları durdurayım, Amicia!",
"VO__HUGO__CH10__CHATTER__CHAPEL_NINTH_WAVE__050__M__1": "Ona dokunma!",
"VO__HUGO__CH10__CHATTER__CHAPEL_SEVENTH_WAVE__010__M__1": "Bırak ben de onları öldüreyim!",
"VO__HUGO__CH10__CHATTER__CHAPEL_SEVENTH_WAVE__040__M__1": "Çok fazlalar! Bırak yardım edeyim!",
"VO__HUGO__CH10__CHATTER__CHAPEL_SEVENTH_WAVE__060__M__1": "Hepsini öldürebilirim! Fareler bunu istiyor!",
"VO__HUGO__CH10__CHATTER__CHAPEL_SIXTH_WAVE__020__M__1": "Evet! Göster onlara!",
"VO__HUGO__CH10__CHATTER__CHAPEL_THIRD_WAVE__030__M__1": "Amicia, bırak yardım edeyim!",
"VO__HUGO__CH10__CHATTER__CHILD_IDLE__020__M__1": "Bildiği şey yanlış...",
"VO__HUGO__CH10__CHATTER__CLIFF_FALL_REACTION__010__M__1": "Bir tane daha!",
"VO__HUGO__CH10__CHATTER__CLOSE_ROPE_BOLT__010__M__1": "Burada başka bir halat var...",
"VO__HUGO__CH10__CHATTER__CLOSE_STAIRS_UP__010__M__1": "Bir tane daha!",
"VO__HUGO__CH10__CHATTER__CLOSED_GATE_VAULT__050__M__1": "Ama sen benim... kaçakçım olabilirsin.",
"VO__HUGO__CH10__CHATTER__COUNTESS_RELATIONS__020__M__1": "Kont, ona zarar vermek istediklerini bilmiyor...",
"VO__HUGO__CH10__CHATTER__CROSS_HOW__010__M__1": "Bu çok fazla ateş...",
"VO__HUGO__CH10__CHATTER__CROSSING_VILLAGE__010__M__1": "Ama neden köle tüccarları var? Neden burada?!",
"VO__HUGO__CH10__CHATTER__CROSSING_VILLAGE__040__M__1": "Evet...",
"VO__HUGO__CH10__CHATTER__CRYPT_ENTER__030__M__1": "Hiçbir şey yok...",
"VO__HUGO__CH10__CHATTER__DOOR_OPEN__010__M__1": "Güvende miyiz?",
"VO__HUGO__CH10__CHATTER__DOOR_OPEN__030__M__1": "Şimdilik...",
"VO__HUGO__CH10__CHATTER__EXIT__020__M__1": "Rüyam neden bana köle tüccarlarını göstermedi?",
"VO__HUGO__CH10__CHATTER__EXIT__040__M__1": "Ama bana yalan söyledi! Beni buraya getirmek için! İyileşecektik!",
"VO__HUGO__CH10__CHATTER__FEATHER__020__M__1": "Bırak onu...",
"VO__HUGO__CH10__CHATTER__FEATHER__040__M__1": "Ama bu karanlık bir kuş...",
"VO__HUGO__CH10__CHATTER__FEATHER__080__M__1": "Ah...",
"VO__HUGO__CH10__CHATTER__FEATHER_PATH__015__M__1": "Çok güzel bir yerdi...",
"VO__HUGO__CH10__CHATTER__FEATHER_PATH__030__M__1": "Bilmiyorum...",
"VO__HUGO__CH10__CHATTER__FIRE_CROSS__040__M__1": "Dikkat!",
"VO__HUGO__CH10__CHATTER__FIRE_EXTINGUISHED__020__M__1": "Ah, geçiyorlar!",
"VO__HUGO__CH10__CHATTER__GATE_HALLWAY__020__M__1": "Korkuyorum...",
"VO__HUGO__CH10__CHATTER__GATE_WAIT__015__M__1": "Tam şuradalar!",
"VO__HUGO__CH10__CHATTER__HUB2_FESTIVAL_TALK__040__M__1": "Ya gerçeği bilselerdi?",
"VO__HUGO__CH10__CHATTER__HUB2_FESTIVAL_TALK__060__M__1": "Keşke onlar gibi olsaydım.",
"VO__HUGO__CH10__CHATTER__HUB2_FESTIVAL_TALK__080__M__1": "Bunu nasıl yapıyorsun?",
"VO__HUGO__CH10__CHATTER__HUB2_FLOWERPATH__030__M__1": "Burada her şey çok eski... Nasıl yardımcı olacak bir şey olabilir?",
"VO__HUGO__CH10__CHATTER__HUB2_FLOWERPATH__060__M__1": "Hm...",
"VO__HUGO__CH10__CHATTER__HUB2_NEW_THINGS__030__M__1": "Hâlâ mutlu görünüyorlar...",
"VO__HUGO__CH10__CHATTER__HUB2_SOPHIA_STORY__040__M__1": "Kulede ne var?",
"VO__HUGO__CH10__CHATTER__HUB2_SOPHIA_STORY__060__M__1": "Dikkatli olmalıyız... Rüyam yanıldıysa, daha çok şey yanlış olabilir.",
"VO__HUGO__CH10__CHATTER__HUB2_VILLAGE_NOMAP__020__M__1": "O zaman oraya da gitmeliyiz... Çok sessiz.",
"VO__HUGO__CH10__CHATTER__HUB2_VILLAGE_NOMAP__040__M__1": "Evet...",
"VO__HUGO__CH10__CHATTER__HUGO_WAITING_1__010__M__1": "Hey! Ne yapıyorsun?!",
"VO__HUGO__CH10__CHATTER__HUGO_WAITING_2__010__M__1": "Seni bekliyorum!",
"VO__HUGO__CH10__CHATTER__IDLE_FORT_1__030__M__1": "Hep öyle.",
"VO__HUGO__CH10__CHATTER__IDLE_FORT_2__020__M__1": "Bu şapelin gerçekten yardımı olacağını mı düşünüyorsun?",
"VO__HUGO__CH10__CHATTER__IDLE_FORT_3__010__M__1": "Farelerden de beterler... Keşke hepsi ölse...",
"VO__HUGO__CH10__CHATTER__IDLE_FORT_4__010__M__1": "Bir kâbus gibi... Belki sadece bir kâbustur... lütfen...",
"VO__HUGO__CH10__CHATTER__IDLE_FORT_4__030__M__1": "Ha? Evet...",
"VO__HUGO__CH10__CHATTER__IDLE_FORT_5__020__M__1": "Belki...",
"VO__HUGO__CH10__CHATTER__INTERACT_CART__030__M__1": "Bunu... çok yaptık.",
"VO__HUGO__CH10__CHATTER__INTERACT_FALL__030__M__1": "Amicia!",
"VO__HUGO__CH10__CHATTER__INTRO_SLAVES__120__M__1": "Köle tüccarları mı?",
"VO__HUGO__CH10__CHATTER__INTRO_SLAVES__140__M__1": "Gerçekten mi?!",
"VO__HUGO__CH10__CHATTER__KILL_FORT_1__010__M__1": "Evet! Devam et...",
"VO__HUGO__CH10__CHATTER__KILL_FORT_2__010__M__1": "Oh olsun!",
"VO__HUGO__CH10__CHATTER__KILLED_ALL_FORT__030__M__1": "Bu onlara ders olur...",
"VO__HUGO__CH10__CHATTER__KNIFE_EVENT__040__M__1": "Amicia!",
"VO__HUGO__CH10__CHATTER__LADY_IDLE__010__M__1": "Adam... O hanımı götürdü... Ona ne yapacak?",
"VO__HUGO__CH10__CHATTER__LADY_IDLE__030__M__1": "Ona yardım edebilir miyiz?",
"VO__HUGO__CH10__CHATTER__LIKE_FEATHER__020__M__1": "Hayır. Artık tüyleri tercih ediyorum.",
"VO__HUGO__CH10__CHATTER__LIKE_FEATHER__040__M__1": "Tüyler daha iyi!",
"VO__HUGO__CH10__CHATTER__LIKE_FEATHER__055__M__1": "Çünkü seni uçururlar.",
"VO__HUGO__CH10__CHATTER__MILO_LEFT__010__M__1": "Ne yapacak?",
"VO__HUGO__CH10__CHATTER__PATROL_MERCENARIES__050__M__1": "Hepsi ölecek...",
"VO__HUGO__CH10__CHATTER__PORTCULLIS_OPENED__020__M__1": "Daha fazlası vardı...",
"VO__HUGO__CH10__CHATTER__POST_RAT_CTRL_KILL__010__M__1": "Tamam...",
"VO__HUGO__CH10__CHATTER__POST_RAT_CTRL_KILL__030__M__1": "Ne?",
"VO__HUGO__CH10__CHATTER__POST_WAVE__010__M__1": "O kadar çoklar ki! Ben... onları buraya ben getirdim!",
"VO__HUGO__CH10__CHATTER__PRISM_1ST_MOVE__030__M__1": "Evet, teşekkürler.",
"VO__HUGO__CH10__CHATTER__PULL_SUCCESS__040__M__1": "Dayanacak mı?",
"VO__HUGO__CH10__CHATTER__RATS_PASSED__060__M__1": "Üzgündü.",
"VO__HUGO__CH10__CHATTER__REACH_TEMPLE_DOOR__040__M__1": "Evet... ve buradan gidelim...",
"VO__HUGO__CH10__CHATTER__RELIEVED__030__M__1": "Arabada ne var? Daha çok ölü mü?",
"VO__HUGO__CH10__CHATTER__REUNION__010__M__1": "Çok yavaşsın!",
"VO__HUGO__CH10__CHATTER__REUNION__030__M__1": "O kadar da yaşlı değilsin!",
"VO__HUGO__CH10__CHATTER__REUNION__050__M__1": "Hayır... Kapı kilitli...",
"VO__HUGO__CH10__CHATTER__REUNITED_WITH_SOPHIA__020__M__1": "Sophia!",
"VO__HUGO__CH10__CHATTER__RUN_TOWER__025__M__1": "Ne?",
"VO__HUGO__CH10__CHATTER__RUN_TOWER__060__M__1": "Evet!",
"VO__HUGO__CH10__CHATTER__RUN_TOWER__080__M__1": "Evet!",
"VO__HUGO__CH10__CHATTER__SEA__040__M__1": "Ama şimdi gitmiyorsun, değil mi?",
"VO__HUGO__CH10__CHATTER__SEA__060__M__1": "Ne?",
"VO__HUGO__CH10__CHATTER__SEA__090__M__1": "İyi ki yapmış!",
"VO__HUGO__CH10__CHATTER__SECOND_AREA_KILL_2ND__010__M__1": "Bu köleler için...",
"VO__HUGO__CH10__CHATTER__SEE_FORT__010__M__1": "Ah, bak!",
"VO__HUGO__CH10__CHATTER__SEE_FORT__030__M__1": "Büyük... Bu... korkutucu...",
"VO__HUGO__CH10__CHATTER__SERIOUS_TALK__040__M__1": "Tıpkı Engizisyon gibiler! Vaudin gibi! İnsanlara canları ne isterse yapıyorlar!",
"VO__HUGO__CH10__CHATTER__SERIOUS_TALK__060__M__1": "Bütün bunlar... adil değil...",
"VO__HUGO__CH10__CHATTER__SERIOUS_TALK__080__M__1": "Sophia... Özür dilerim.",
"VO__HUGO__CH10__CHATTER__SLAVE_RAGDOLL__035__M__1": "Bak...",
"VO__HUGO__CH10__CHATTER__SLAVE_RAGDOLL__050__M__1": "Bir bez bebek...",
"VO__HUGO__CH10__CHATTER__SLAVE_RAGDOLL__070__M__1": "Bir çocuk... köle mi?",
"VO__HUGO__CH10__CHATTER__SLAVE_RAGDOLL__080__M__1": "Bu mümkün mü? Değil... değil mi?",
"VO__HUGO__CH10__CHATTER__SLAVE_RAGDOLL__100__M__1": "Bebeklerini ellerinden almışlar!",
"VO__HUGO__CH10__CHATTER__SLAVE_RAGDOLL__120__M__1": "Onu yanlarında bile... getiremediler...",
"VO__HUGO__CH10__CHATTER__SLAVE_RAGDOLL__140__M__1": "Evet...",
"VO__HUGO__CH10__CHATTER__SMELL_OF_DEATH_IDLE__010__M__1": "Çok pis kokuyor...",
"VO__HUGO__CH10__CHATTER__TEMPLE_IN_SIGHT__010__M__1": "Bak... başka bir şapel...",
"VO__HUGO__CH10__CHATTER__TO_GATE__010__M__1": "Ya şapelde bir şey yoksa? Annem ve Lucas'ı görmeye geri döneceğimize söz ver...",
"VO__HUGO__CH10__CHATTER__TO_GATE_RATS__030__M__1": "Pekâlâ...",
"VO__HUGO__CH10__CHATTER__TORTURE__005__M__1": "Ah...",
"VO__HUGO__CH10__CHATTER__TRENCH_TWO__030__M__1": "Bırak gelsinler, yardımı olabilir...",
"VO__HUGO__CH10__CHATTER__TUTO_PULL_INTERACT__020__M__1": "İşe yarayacak mı?",
"VO__HUGO__CH10__CHATTER__UNSTABLE_BRIDGE__020__M__1": "Nasıl geçeceğiz?",
"VO__HUGO__CH10__CHATTER__WATER_WAY__020__M__1": "Dans... müzik... çiçekler...",
"VO__HUGO__CH10__CHATTER__WATER_WAY__040__M__1": "Yel değirmenleri...",
"VO__HUGO__CH10__CHATTER__WATER_WAY__060__M__1": "Ne?",
"VO__HUGO__CH10__CHATTER__WATER_WAY__080__M__1": "Evet.",
"VO__HUGO__CH10__CHATTER__WATER_WINDOW__015__M__1": "Bu kale kötü...",
"VO__HUGO__CH10__CHATTER__WEDGE_DONE__020__M__1": "Daha fazlası gelmeden gidelim...",
"VO__HUGO__CH10__ONOM__CHANDELIER_DOOR__010__M__1": "Ah...",
"VO__HUGO__CH10__ONOM__PULL_SUCCESS__020__M__1": "Ah!",
"VO__HUGO__CH10__ONOM__SOPHIA_SHOW_PRISM__020__M__1": "Ah!",
"VO__HUGO__CH10__RTC__460_BACK_FROM_SANCTUARY__040__M__1": "Pekâlâ...",
"VO__HUGO__CH10__RTC__480_ENTER_FORT__110__M__1": "İster misin?",
"VO__HUGO__CH10__RTC__480_ENTER_FORT__153__M__1": "Burada kalabiliriz. Burayı seviyorum.",
"VO__HUGO__CH10__RTC__485_UNEXPECTED_STRIKE__150__M__1": "Onlara yardım etmeliyiz!",
"VO__HUGO__CH10__RTC__485_UNEXPECTED_STRIKE__170__M__1": "Onları durduracağım!",
"VO__HUGO__CH10__RTC__485_UNEXPECTED_STRIKE__175__M__1": "DURUN!",
"VO__HUGO__CH10__RTC__485_UNEXPECTED_STRIKE__210__M__1": "Onları kurtarmak istedim!",
"VO__HUGO__CH10__RTC__485_UNEXPECTED_STRIKE__230__M__1": "Neden? Sen sürekli yapıyorsun!",
"VO__HUGO__CH10__RTC__485_UNEXPECTED_STRIKE__250__M__1": "Ve senden daha hızlı öldürebilirim!",
"VO__HUGO__CH10__RTC__485_UNEXPECTED_STRIKE__270__M__1": "Umurumda değil! Zaten artık hepsi öldü!",
"VO__HUGO__CH10__RTC__490_ENTER_FORT2__130__M__1": "Şşş!",
"VO__HUGO__CH10__RTC__490_ENTER_FORT2__153__M__1": "Amicia...",
"VO__HUGO__CH10__RTC__490_ENTER_FORT2__190__M__1": "Geliyorlar.",
"VO__HUGO__CH10__RTC__495_LEGACY__050__M__1": "Dikkatli ol. İçeride bir örümcek olabilir...",
"VO__HUGO__CH10__RTC__500_FRESCOE__030__M__1": "HAYIR!",
"VO__HUGO__CH10__RTC__500_FRESCOE__070__M__1": "Hepsini öldürdün...",
"VO__HUGO__CH10__RTC__500_FRESCOE__090__M__1": "BANA NE İSTEDİĞİMİ SÖYLEMEYİ KES!",
"VO__HUGO__CH10__RTC__510_END__100__M__1": "Ölmeliler!",
"VO__HUGO__CH10__RTC__510_END__133__M__1": "Burası yardım edecekti! Ama hâlâ aynıyım! Hatta daha beter!",
"VO__HUGO__CH10__RTC__510_END__143__M__1": "Çünkü gideceksin! Benim yüzümden!",
"VO__HUGO__CH10__RTC__510_END__215__M__1": "Teşekkürler.",
"VO__HUGO__CH10__RTC__510_END_ONOM__080__M__1": "Hıçkırık",
"VO__HUGO__CH10__RTC__510_END_ONOM__090__M__1": "Hıçkırık",
"VO__HUGO__CH10__RTC__510_END_ONOM__100__M__1": "Hıçkırık",
"VO__BANDIT_N1__CH10__CHATTER__ABOUT_PLAGUE__010__M__1": "Burada ne oldu?! Fareler neden burada?!",
"VO__BANDIT_N1__CH10__CHATTER__ABOUT_PLAGUE__030__M__1": "Cehennem... Bu hoşuma gitmedi... Kontrolü kaybedeceğimizi biliyordum!",
"VO__BANDIT_N1__CH10__CHATTER__ALMOST_DONE__010__M__1": "Sonuncuları bunlar mı?",
"VO__BANDIT_N1__CH10__CHATTER__ALMOST_DONE__030__M__1": "O zaman işe yaraması için dua edelim...",
"VO__BANDIT_N1__CH10__CHATTER__BODIES__010__M__1": "Leş gibi kokuyor! Bu cesetleri daha ne kadar asılı tutmamız gerekiyor?!",
"VO__BANDIT_N1__CH10__CHATTER__BODIES__030__M__1": "Ki bu sonsuza dek sürebilir!",
"VO__BANDIT_N1__CH10__CHATTER__BROKEN_BRIDGE__010__M__1": "Şu Aydınlık Günler şeylerinde olup biraz kızarmış domuz yemek için neler vermezdim ki...",
"VO__BANDIT_N1__CH10__CHATTER__BROKEN_BRIDGE__030__M__1": "Çocuk seni duysun!",
"VO__BANDIT_N1__CH10__CHATTER__CART_BRIDGE__030__M__1": "Köprü kaldırıldı! İkinci bir emre kadar kimse girmiyor!",
"VO__BANDIT_N1__CH10__CHATTER__CHAPEL_FIRST_WAVE__010__M__1": "Milo'yu doğradılar, lanet olsun! Adamlar! Buraya gelin! Herkes lazım!",
"VO__BANDIT_N1__CH10__CHATTER__CHAPEL_SIXTH_IDLE__010__M__1": "Sen de kimsin be?!",
"VO__BANDIT_N1__CH10__CHATTER__CHAPEL_THIRD_WAVE__050__M__1": "Ritüeli bitirin! Kanlarını dökersek, Çocuk bizi bağışlayabilir!",
"VO__BANDIT_N1__CH10__CHATTER__CHAPEL_THIRD_WAVE__070__M__1": "Öldürün şu kızı!",
"VO__BANDIT_N1__CH10__CHATTER__FALL_CRASH_EVENT__010__M__1": "Ne...?... Hey!",
"VO__BANDIT_N1__CH10__CHATTER__FALL_CRASH_EVENT__030__M__1": "Buraya gelmekle... hata ettin!",
"VO__BANDIT_N1__CH10__CHATTER__GUARD_FRONT__010__M__1": "Aman be... Diri diri yenmek nasıl bir şey, bilmek istemiyorum...",
"VO__BANDIT_N1__CH10__CHATTER__INTRO_SLAVES__020__M__1": "Kahretsin...",
"VO__BANDIT_N1__CH10__CHATTER__INTRO_SLAVES__040__M__1": "Anlaşıldı!",
"VO__BANDIT_N1__CH10__CHATTER__PATROL_TALK__010__M__1": "Ha... Umarım Milo haklıdır... Daha fazla adam kaybedemeyiz.",
"VO__BANDIT_N1__CH10__CHATTER__PORTCULLIS_OPENED__010__M__1": "Kapı açık! Neler oluyor?!",
"VO__BANDIT_N1__CH10__CHATTER__RELIEVED__020__M__1": "Değerinin bin katını alınca minnettar olacaksın...",
"VO__BANDIT_N1__CH10__CHATTER__THROWER_HAND__010__M__1": "Ne?... Ne cüretle?!",
"VO__BANDIT_N2__CH10__CHATTER__ABOUT_PLAGUE__020__M__1": "Ne yaptılar... Hey! Kimse var mı?!",
"VO__BANDIT_N2__CH10__CHATTER__CART_BRIDGE__010__M__1": "İşte bu! Şu arabayı şapele götür! Sonuncusu bu olacak! Köprüyü kaldırın!",
"VO__BANDIT_N2__CH10__CHATTER__GATE_WAIT__010__M__1": "Arabada hâlâ nefes alan kimse kalmadığından emin ol.",
"VO__BANDIT_N2__CH10__CHATTER__GATE_WAIT__030__M__1": "Emin. Ol.",
"VO__BANDIT_N2__CH10__CHATTER__IMPATIENT__010__M__1": "Eee?! Hepsini kontrol ettin mi?!",
"VO__BANDIT_N2__CH10__CHATTER__MILO_STUCK__010__M__1": "Lanet, ucuz kurtulduk! Milo ne yapıyor? Bizim tarafa geçmemeleri gerekiyordu, değil mi?!",
"VO__BANDIT_N2__CH10__CHATTER__MILO_STUCK__030__M__1": "Ve bu sırada bizi kapana kıstırıyorlar! Sadece şapel kalacak elimizde! Ne rezalet...",
"VO__BANDIT_N2__CH10__CHATTER__PATROL_MERCENARIES__010__M__1": "Hepsi Milo'nun çıldırdığını sanıyordu... Ama bak! Geri döndüler! İşe yarıyor!",
"VO__BANDIT_N2__CH10__CHATTER__PATROL_MERCENARIES__030__M__1": "Sakin ol! Çocuk bizi bütün bu kandan arındıracak ve bize talih bağışlayacak!",
"VO__BANDIT_N2__CH10__CHATTER__RATS_PASSED__020__M__1": "Kahretsin! Meşaleleri kapın! Yukarı çıkın! Kapı onları tutar!",
"VO__BANDIT_N2__CH10__RTC__490_ENTER_FORT2__102__M__1": "Yola koyulalım. Diaz gibi bitmek istemiyorum.",
"VO__BANDIT_N2__CH10__RTC__490_ENTER_FORT2__105__M__1": "Şu kapı kafesi neden hâlâ kaldırılmadı?",
"VO__BANDIT_N2__CH10__RTC__490_ENTER_FORT2__107__M__1": "HEY! KALDIRIN ŞU LANET KAPIYI!",
"VO__BANDIT_S1__CH10__CHATTER__ALMOST_DONE__020__M__1": "Evet... Milo'ya artık yetmiş olmalı!",
"VO__BANDIT_S1__CH10__CHATTER__BODIES__020__M__1": "Fareler geri gelene... ve Çocuk onları takip edene kadar...",
"VO__BANDIT_S1__CH10__CHATTER__BODIES__040__M__1": "Hayır, bu seferki gerçek! Fareler burada! Önceki bunca yıl boyunca böyle bir şey olmadı! Milo oraya varmak için ne gerekiyorsa yapıyor ve haklı!",
"VO__BANDIT_S1__CH10__CHATTER__CHAPEL_FIFTH_WAVE__020__M__1": "Ne yaptın?! Ritüel yarım kaldı!",
"VO__BANDIT_S1__CH10__CHATTER__COUNTESS_RELATIONS__010__M__1": "Milo'nun planı ödümü koparıyor. Kontrol edemeyeceğimiz şeylerle oynuyoruz.",
"VO__BANDIT_S1__CH10__CHATTER__GUARDING_CHEST__005__M__1": "İzinsiz gireni öldür. Zaten geri dönen olmaz.",
"VO__BANDIT_S1__CH10__CHATTER__MILO_REPUTATION__030__M__1": "Bundan o kadar emin olma... Tek başına hüküm sürmeyi sever. Daha güçlenirse işler düzelmez...",
"VO__BANDIT_S1__CH10__CHATTER__PATROL_TALK__020__M__1": "Buna değer... Buraya kadar ona güvendik.",
"VO__BANDIT_S1__CH10__RTC__500_FRESCOE__150__M__1": "Milo'yu öldürdüler! Burada!",
"VO__BANDIT_S2__CH10__CHATTER__CHAPEL_FIRST_WAVE__020__M__1": "Öldürün kızı! Çabuk!",
"VO__BANDIT_S2__CH10__CHATTER__CHAPEL_FIRST_WAVE__050__M__1": "Her şeyi mahvettin! Bunun için cehenneme gideceksin!",
"VO__BANDIT_S2__CH10__CHATTER__CHAPEL_NINTH_WAVE__040__M__1": "Yorulacak! Doğrayın onu! Milo'nun intikamını alın!",
"VO__BANDIT_S2__CH10__CHATTER__COUNTESS_RELATIONS__020__M__1": "Biliyorum. Ama Kont'u devirmenin bedeli buysa, öderim.",
"VO__BANDIT_S2__CH10__CHATTER__MILO_REPUTATION__010__M__1": "Zengin olursak... umarım Milo bazılarımızı terfi ettirir...",
"VO__BANDIT_S2__CH10__CHATTER__MILO_REPUTATION__040__M__1": "Yanılmıyorsun. Ama altın kırıntısı yine de altındır...",
"VO__BANDIT_S2__CH10__CHATTER__PATROL_MERCENARIES__020__M__1": "Fazla iyi işliyor! Dün adamlarımızdan birkaçını aldılar ve fareler yarı kadardı! Milo bunu çabucak bitirmeli!",
"VO__BANDIT_S2__CH10__CHATTER__PATROL_MERCENARIES__040__M__1": "Onu göreceğiz.",
"VO__BANDIT_S2__CH10__CHATTER__RELIEVED__005__M__1": "Şu araba güzel paranın lanet bir israfı...",
"VO__BANDIT_S2__CH10__RTC__485_UNEXPECTED_STRIKE__015__M__1": "Canı cehenneme bu işin!",
"VO__BANDIT_S2__CH10__RTC__485_UNEXPECTED_STRIKE__040__M__1": "Şey... Bu şeyler yerden çıkıp bizi yiyor, kölelerimiz kaçıyor, peki şimdi ne olacak?! O deli Kontes uğruna geri kalanı da heba ediyorsun!",
"VO__BANDIT_S2__CH10__RTC__485_UNEXPECTED_STRIKE__060__M__1": "Söyle bana... Senin Çocuk'unu görmeden kaçımız farelere yem olacak?!",
"VO__BANDIT_S3__CH10__CHATTER__BROKEN_BRIDGE__020__M__1": "Bu iş bitince, hayatının her günü ziyafet çekeceksin!",
"VO__BANDIT_S3__CH10__CHATTER__FIRE_CROSS__020__M__1": "Hepiniz! Mevzilerinizi tutun ve şu hendekleri gözleyin! Milo! İstediğin zaman gidebilirsin!",
"VO__BANDIT_S3__CH10__CHATTER__GATE_WAIT__020__M__1": "Hepsi bana epey ölü görünüyor...",
"VO__BANDIT_S3__CH10__CHATTER__IMPATIENT__020__M__1": "Neredeyse!",
"VO__BANDIT_S3__CH10__CHATTER__KNIFE_EVENT__010__M__1": "Hey! Ne?! Seni kim soktu içeri?!",
"VO__BANDIT_S3__CH10__CHATTER__KNIFE_EVENT__050__M__1": "Lanet davetsiz misafir!",
"VO__BANDIT_S3__CH10__CHATTER__KNIFE_EVENT__070__M__1": "Öldüreceğim seni!",
"VO__BANDIT_S3__CH10__CHATTER__MILO_LEFT__020__M__1": "Patronu duydunuz! Herkes gözünü açsın! Ve kapatın şu kapı kafesini!",
"VO__BANDIT_S3__CH10__CHATTER__MILO_STUCK__020__M__1": "Sanırım sadece vakit alıyor!",
"VO__BANDIT_S3__CH10__CHATTER__PATROL_DOWN__010__M__1": "Fareler... lanet fareler... Hepsi doğruymuş... Sadece lanet bir delinin şakası sanmıştım. Şey, şimdi gülmüyorum, değil mi?",
"VO__BANDIT_S3__CH10__CHATTER__RATS_IN_SCARED__020__M__1": "Anlaşıldı!",
"VO__BANDIT_S3__CH10__CHATTER__RATS_PASSED__010__M__1": "Ne?! Hey! Geçtiler! Fareler hendeği geçti!",
"VO__BANDIT_S3__CH10__CHATTER__RATS_PASSED__030__M__1": "Milo ne yapıyor?! Aşırı yaklaşıyorlar!",
"VO__BANDIT_S3__CH10__RTC__490_ENTER_FORT2__003__M__1": "Haklıydın... Biri hâlâ canlıymış...",
"VO__BANDIT_S3__CH10__RTC__490_ENTER_FORT2__123__M__1": "Hadi, ne yapıyor bu? İnanılmaz.",
"VO__BANDIT_S3__CH10__RTC__490_ENTER_FORT2__126__M__1": "Gidip onu pataklayacağım.",
"VO__BANDIT_S3__CH10__RTC__490_ENTER_FORT2__134__M__1": "Ah...",
"VO__BANDIT_S3__CH10__RTC__490_ENTER_FORT2__137__M__1": "Sonunda be!",
"VO__BANDIT_S3__CH10__RTC__490_ENTER_FORT2__230__M__1": "Onlar... Yine başlıyor!",
"VO__BANDIT_S3__CH10__RTC__490_ENTER_FORT2__250__M__1": "KAHRETSİN! KAÇIN!",
"VO__BANDIT_S3__CH10__RTC__510_END__070__M__1": "Küçük alçak... Geber!",
"VO__LEADER__CH10__CHATTER__CLIFF_FALL__010__M__1": "Kaçışın bitti, dostum!",
"VO__LEADER__CH10__CHATTER__CLIFF_FALL__060__M__1": "Özgürlüğünün tadını çıkar!",
"VO__LEADER__CH10__CHATTER__CLIFF_FALL_REACTION__050__M__1": "Lanet alçak beni terletti!",
"VO__LEADER__CH10__CHATTER__CLIFF_FALL_REACTION__060__M__1": "Onlara gerçekten disiplin öğretmemiz lazım...",
"VO__LEADER__CH10__CHATTER__INTRO_SLAVES__010__M__1": "Şunu yakaladım. Diğerleri kaçtı.",
"VO__LEADER__CH10__CHATTER__INTRO_SLAVES__030__M__1": "Geri kalanı kurtarmaya dönerler diye gözünüzü açık tutun. Bunu ben geri götürüyorum.",
"VO__LEADER__CH10__CHATTER__INTRO_SLAVES__080__M__1": "Ah... Götüreceğim. Yakında.",
"VO__LEADER__CH10__CHATTER__INTRO_SLAVES__090__M__1": "Sessizlik istiyorum. İzinsiz gireni öldürün.",
"VO__LEADER__CH10__CHATTER__POST_WAVE__020__M__1": "Hendeği ateşe verin! Biraz zaman kazanmalıyız!",
"VO__LEADER__CH10__CHATTER__RATS_IN_SCARED__010__M__1": "Fareleri şapelden olabildiğince uzun tutun!",
"VO__LEADER__CH10__CHATTER__RATS_IN_SCARED__040__M__1": "Rahatsız edilmediğimden emin olun! Bu, Çocuk'la benim aramda!",
"VO__LEADER__CH10__RTC__485_UNEXPECTED_STRIKE__010__M__1": "Sorun yok, yakında bitecek.",
"VO__LEADER__CH10__RTC__485_UNEXPECTED_STRIKE__025__M__1": "Bir sorunun mu var, Diaz?",
"VO__LEADER__CH10__RTC__485_UNEXPECTED_STRIKE__043__M__1": "Yanlış! Artık onun için çalışmıyoruz...",
"VO__LEADER__CH10__RTC__485_UNEXPECTED_STRIKE__046__M__1": "Hepsi freskte! Fareler Çocuk'un gelişini müjdeliyor, ve ne kadar aç olduklarını gördünüz! Yani basit: onları memnun edersek, Çocuk'u memnun ederiz, tahtının yanında bir yer kapatırız!",
"VO__LEADER__CH10__RTC__485_UNEXPECTED_STRIKE__050__M__1": "Sonra Kont önümüzde diz çökecek ve dünya da peşinden gelecek.",
"VO__LEADER__CH10__RTC__485_UNEXPECTED_STRIKE__070__M__1": "Ne kadar az inancın var...",
"VO__LEADER__CH10__RTC__485_UNEXPECTED_STRIKE__080__M__1": "Ama benimle... lanet... tartışıp duruyorsun!",
"VO__LEADER__CH10__RTC__485_UNEXPECTED_STRIKE__100__M__1": "Başka var mı?",
"VO__LEADER__CH10__RTC__485_UNEXPECTED_STRIKE__110__M__1": "Pekâlâ. Başlayalım. Kan, Çocuk'a şapele giden yolu gösterecek.",
"VO__LEADER__CH10__RTC__485_UNEXPECTED_STRIKE__115__M__1": "Buradaki sevgili Diaz'ımız onu başlatma şerefine sahip.",
"VO__LEADER__CH10__RTC__490_ENTER_FORT2__210__M__1": "Hayır... Çok erken... Bu çok erken!",
"VO__LEADER__CH10__RTC__490_ENTER_FORT2__220__M__1": "Kımıldayın! Daha hızlı!",
"VO__LEADER__CH10__RTC__490_ENTER_FORT2__260__M__1": "Gedik!",
"VO__LEADER__CH10__RTC__490_ENTER_FORT2__280__M__1": "Şapele gidiyorum! Kan bağını kapatacağım!",
"VO__LEADER__CH10__RTC__500_FRESCOE__010__M__1": "Orada ne halt ediyordun?",
"VO__LEADER__CH10__RTC__500_FRESCOE__020__M__1": "Burası kutsal!",
"VO__LEADER__CH10__RTC__500_FRESCOE__040__M__1": "Sen...",
"VO__LEADER__CH10__RTC__500_FRESCOE__050__M__1": "Sensin!... Çağrıma cevap verdin! Adağımı beğendin mi?",
"VO__LEADER__CH10__RTC__500_FRESCOE__060__M__1": "Hüküm sürmene yardım edebilirim! Adamlarım var! Kölelerim!",
"VO__LEADER__CH10__RTC__500_FRESCOE__080__M__1": "Senin için! Kontes, kendine anne diyor ama... senin anneye ihtiyacın yok... Hizmetkârlara ihtiyacın var!",
"VO__LEADER__CH10__RTC__500_FRESCOE__100__M__1": "Sen o kızsın... tablodaki...",
"VO__PEOPLE_M3__CH10__CHATTER__HUB2_FESTIVAL_TALK__010__M__1": "Çocuk kutsansın! Anne kutsansın!",
"VO__PEOPLE_M4__CH10__CHATTER__HUB2_FESTIVAL_TALK__020__M__1": "Onun geri döneceği günler kutsansın!",
"VO__PEOPLE_M4__CH10__CHATTER__HUB2_YELLER__005__M__1": "Bu aydınlık günde, Köz Çocuğu'nu yaşamımızla, neşemizle ve hepimizin Anne'yle paylaştığı bağın birliğiyle kutluyoruz!",
"VO__PEOPLE_M4__CH10__CHATTER__HUB2_YELLER__010__M__1": "Ruhlarımızın ışığı Çocuk'u derin uykusundan uyandırsın. Onu, en parlak ruhların en parlağı Kontes'imize ulaştırsın ve kalbini tamamlasın.",
"VO__PEOPLE_M4__CH10__CHATTER__HUB2_YELLER__020__M__1": "Bu, yeni bir çağın ilk günü olabilir! Kutlayın onu. Ve bu gece gündüzünüzden daha aydınlık olsun!",
"VO__SLAVE_F1__CH10__CHATTER__INTRO_SLAVES__070__M__1": "Bırak beni, domuz!",
"VO__SLAVE_M1__CH10__CHATTER__CLIFF_FALL__020__M__1": "Lütfen olmaz! HAYIR!",
"VO__SLAVE_M1__CH10__RTC__485_UNEXPECTED_STRIKE__120__M__1": "Hayır! Hayır lütfen olmaz!",
"VO__SOPHIA__CH10__CHATTER__AFTER_EVENT_KNIFE__020__M__1": "İyi misin?!",
"VO__SOPHIA__CH10__CHATTER__AFTER_EVENT_KNIFE__027__M__1": "Lanet... alçak...",
"VO__SOPHIA__CH10__CHATTER__AFTER_EVENT_KNIFE__050__M__1": "Ha... Kendime... bunu bir daha asla yapmayacağıma söz vermiştim...",
"VO__SOPHIA__CH10__CHATTER__AFTER_EVENT_KNIFE__070__M__1": "Evet, şey... sen sadece kendini öldürtmemeye bak...",
"VO__SOPHIA__CH10__CHATTER__AFTER_STRIKE__030__M__1": "O neydi?! Bu delilik! Hiç söylemedin...",
"VO__SOPHIA__CH10__CHATTER__AFTER_STRIKE__050__M__1": "Sen... git onunla konuş.",
"VO__SOPHIA__CH10__CHATTER__AFTER_STRIKE__060__M__1": "Biraz... vakte ihtiyacım var.",
"VO__SOPHIA__CH10__CHATTER__AMICIA_IS_BACK__010__M__1": "Amicia?!",
"VO__SOPHIA__CH10__CHATTER__AMICIA_IS_BACK__050__M__1": "Lanet...",
"VO__SOPHIA__CH10__CHATTER__AMICIA_IS_BACK__070__M__1": "Bana en çok ihtiyacın olabilecekken mi? Hayır.",
"VO__SOPHIA__CH10__CHATTER__AMICIA_SOPHIA__020__M__1": "Ben... Sana sormak istedim—bütün bundan emin misin? Onun için ağır bir yük gibi görünüyor.",
"VO__SOPHIA__CH10__CHATTER__AMICIA_SOPHIA__040__M__1": "Dinle, birbirimizi pek tanımıyoruz ama... Hayaletlerin peşindesin. Onu korkutan hayaletler.",
"VO__SOPHIA__CH10__CHATTER__AMICIA_SOPHIA__060__M__1": "Yapamam... Asıl soru şu: daha fazlasına ihtiyacı var mı?",
"VO__SOPHIA__CH10__CHATTER__AMICIA_SOPHIA__080__M__1": "Sana inanıyorum... Peki.",
"VO__SOPHIA__CH10__CHATTER__ARMORED_SLAVERS_IDLE__010__M__1": "Köle tüccarı için epey ağır silahlılar.",
"VO__SOPHIA__CH10__CHATTER__ARMY_IDLE__020__M__1": "Kalenin içinde bizi neyin beklediğini biliyorsun, değil mi?",
"VO__SOPHIA__CH10__CHATTER__ARRESTED_SLAVERS_IDLE__020__M__1": "Hayır...",
"VO__SOPHIA__CH10__CHATTER__ARRESTED_SLAVERS_IDLE__040__M__1": "Kazanılacak para olunca çok şey olabilir...",
"VO__SOPHIA__CH10__CHATTER__BABY_BOAT__020__M__1": "Evet... ardında ne hikâye yatıyor kim bilir...",
"VO__SOPHIA__CH10__CHATTER__BABY_BOAT__040__M__1": "Kimi sağ kalır... Kimini deniz alır ve dalgaların kucağında sonsuza dek uyurlar.",
"VO__SOPHIA__CH10__CHATTER__BABY_BOAT__060__M__1": "Sonra yengeçlere yem olurlar.",
"VO__SOPHIA__CH10__CHATTER__BABY_BOAT__090__M__1": "Rica ederim.",
"VO__SOPHIA__CH10__CHATTER__BACK_ON_TRACK__030__M__1": "Belki biraz ateş atlama ve başka... güvenli faaliyetler görürüz.",
"VO__SOPHIA__CH10__CHATTER__BACK_TO_MAP__020__M__1": "Hayır, ama... o sembol şapelimiz olabilir mi?... Onu götürdükleri şu \"capella\"!",
"VO__SOPHIA__CH10__CHATTER__BACK_TO_MAP__027__M__1": "Bir çizim... Yani, mabedin orada olduğunu bilince, sanırım şu büyük süslü ağaca giden yolda, muhtemelen yel değirmenlerinin ötesinde.",
"VO__SOPHIA__CH10__CHATTER__BACK_TO_TOPIC__020__M__1": "Şey, sana istediğin her şeyi sağlayabilirim!",
"VO__SOPHIA__CH10__CHATTER__BACK_TO_TOPIC__050__M__1": "Burada... işimizi bitirelim, sonra seni bir geziye çıkarırım, olur mu?",
"VO__SOPHIA__CH10__CHATTER__BACK_TO_TOPIC__070__M__1": "Yakında.",
"VO__SOPHIA__CH10__CHATTER__BACK_TO_TOPIC__090__M__1": "Anlaştık.",
"VO__SOPHIA__CH10__CHATTER__BAD_SIGNS__030__M__1": "Ne?!",
"VO__SOPHIA__CH10__CHATTER__BAD_SIGNS__080__M__1": "Amicia, burada ölü bir adam var!",
"VO__SOPHIA__CH10__CHATTER__BAD_SIGNS__100__M__1": "Olmak zorundayız.",
"VO__SOPHIA__CH10__CHATTER__BASEMENT__020__M__1": "Belli ki sığınakları değil...",
"VO__SOPHIA__CH10__CHATTER__BEFORE_SERIOUS_TALK__010__M__1": "Bana bir dakika ver...",
"VO__SOPHIA__CH10__CHATTER__BODIES__060__M__1": "Zavallı kızın pek aydınlık bir geleceği olmamış...",
"VO__SOPHIA__CH10__CHATTER__BODIES_TORCHES__030__M__1": "Milo'nun işi...",
"VO__SOPHIA__CH10__CHATTER__BODIES_TORCHES__050__M__1": "Demek orada bir şey var...",
"VO__SOPHIA__CH10__CHATTER__BRIDGE_TUTO__010__M__1": "Kurt yemiş...",
"VO__SOPHIA__CH10__CHATTER__BRIDGE_TUTO__030__M__1": "Şu köprü çökmek üzere görünüyor...",
"VO__SOPHIA__CH10__CHATTER__BRIDGE_TUTO__050__M__1": "Bu direkte bir halat ve kanca var!",
"VO__SOPHIA__CH10__CHATTER__BRIGHTER_IDLE__020__M__1": "Ya bilmiyorlar ya da umurlarında değil.",
"VO__SOPHIA__CH10__CHATTER__BUSINESS_IDLE__010__M__1": "Milo, Kontes için çalıştığını söyledi. Burayı muhtemelen o ve Kont vermiştir...",
"VO__SOPHIA__CH10__CHATTER__BUSINESS_IDLE__030__M__1": "Evet. Kirli iş.",
"VO__SOPHIA__CH10__CHATTER__CART_BRIDGE__040__M__1": "Ve giriş yolumuz da gitti...",
"VO__SOPHIA__CH10__CHATTER__CART_BRIDGE_IN__030__M__1": "Katılıyorum.",
"VO__SOPHIA__CH10__CHATTER__CHANDELIER_DOOR__020__M__1": "Gerçekten gürültülü. Yola koyulmalıyız.",
"VO__SOPHIA__CH10__CHATTER__CHANDELIER_DROP__010__M__1": "Umarım kimse duymamıştır...",
"VO__SOPHIA__CH10__CHATTER__CHANDELIER_HOLD__010__M__1": "Çabuk ol, lütfen...",
"VO__SOPHIA__CH10__CHATTER__CHANDELIER_MOVING__010__M__1": "Bir avize kaldırıyor... Büyük bir tane!",
"VO__SOPHIA__CH10__CHATTER__CHANDELIER_MOVING__050__M__1": "Zincir hâlâ epey sağlam görünüyor!",
"VO__SOPHIA__CH10__CHATTER__CHANDELIER_PULL__020__M__1": "Devam et!",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_COURTYARD__015__M__1": "Bu barbarca...",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_COURTYARD__055__M__1": "Bak, kapıda... Senin Düzen'inin sembolü...",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_EIGHTH_IDLE__020__M__1": "Şimdi beni dinle! Buna bir son ver!",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_ENTER__015__M__1": "Epey yeniler. Bunu kim yaptı? Milo mu?",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_ENTER__030__M__1": "Yani, ne... Bu şapel ona mı adanmıştı?",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_FIFTH_WAVE__040__M__1": "Eğik dur, Hugo!",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_FINAL_WAVE__010__M__1": "Amicia! Şapele girmemiz lazım! Başka yol yok!",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_FINAL_WAVE__040__M__1": "Ne yapıyorsun?! Hey! Dur!",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_FIRST_WAVE__040__M__1": "Hayır! Henüz değil!",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_NINTH_WAVE__020__M__1": "Hiçbir şey yapmıyorsun, evlat!",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_SEVENTH_WAVE__020__M__1": "Hugo! Bırak yapsın!",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_SEVENTH_WAVE__070__M__1": "Amicia! İş acilleşiyor!",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_SIXTH_WAVE__030__M__1": "Sakin ol! Ablanın sana söylediğini hatırla!",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_THIRD_WAVE__010__M__1": "Bunun sonu kötü bitecek, Amicia! Bir çıkış olmalı!",
"VO__SOPHIA__CH10__CHATTER__CHAPEL_THIRD_WAVE__040__M__1": "Hayır! Sen orada kal!",
"VO__SOPHIA__CH10__CHATTER__CHILD_IDLE__030__M__1": "Bu Çocuk meselesi delilere bir mıknatıs...",
"VO__SOPHIA__CH10__CHATTER__CLIFF_FALL_REACTION__030__M__1": "Bu da ne be?!",
"VO__SOPHIA__CH10__CHATTER__CLOSE_ROPE_BOLT__020__M__1": "İyi gördün! Giriş yolumuz bu.",
"VO__SOPHIA__CH10__CHATTER__CLOSED_GATE__020__M__1": "Biraz etrafa bakma vakti mi?",
"VO__SOPHIA__CH10__CHATTER__CLOSED_GATE_VAULT__020__M__1": "Demek sonunda onu fethediyoruz!",
"VO__SOPHIA__CH10__CHATTER__CLOSED_GATE_VAULT__040__M__1": "Yani bu şeye sen mi hükmedeceksin?",
"VO__SOPHIA__CH10__CHATTER__CLOSED_GATE_VAULT__060__M__1": "Kraliyet sözleşmesi! Onur duydum!",
"VO__SOPHIA__CH10__CHATTER__CLOSED_GATE_VAULT__080__M__1": "Ah, doğru. Kale ve şapeli...",
"VO__SOPHIA__CH10__CHATTER__COME_DOWN__010__M__1": "Şimdi in aşağı!",
"VO__SOPHIA__CH10__CHATTER__CONTINUE_CHECK__020__M__1": "Sindirmeye çalışıyorum...",
"VO__SOPHIA__CH10__CHATTER__CONTINUE_CHECK__040__M__1": "Fareler...",
"VO__SOPHIA__CH10__CHATTER__CRANK__020__M__1": "Boşuna. Gitmeliyiz.",
"VO__SOPHIA__CH10__CHATTER__CROSSING_VILLAGE__020__M__1": "Her yerdeler... tıpkı... katiller ve hainler gibi.",
"VO__SOPHIA__CH10__CHATTER__CRYPT_ENTER__010__M__1": "Milo nerede be?",
"VO__SOPHIA__CH10__CHATTER__DOOR__010__M__1": "Evet... İyi iş...",
"VO__SOPHIA__CH10__CHATTER__DOOR_LOCKED__005__M__1": "Şu kapı uzun zamandır sıkışmış gibi görünüyor...",
"VO__SOPHIA__CH10__CHATTER__DOOR_LOCKED__020__M__1": "Evet... Sert bir itiş gerekecek...",
"VO__SOPHIA__CH10__CHATTER__DOOR_OPEN__020__M__1": "Sanırım... şimdilik...",
"VO__SOPHIA__CH10__CHATTER__EXIT__060__M__1": "Yorucu... Ama hayat bu.",
"VO__SOPHIA__CH10__CHATTER__FEATHER__050__M__1": "Kurnaz bir kuş! İnsanları kötü olduğuna inandırmayı başarmış...",
"VO__SOPHIA__CH10__CHATTER__FEATHER__100__M__1": "Bir de beni sabah uyandığımda görmelisin. En kötüsü benim.",
"VO__SOPHIA__CH10__CHATTER__FEATHER_PATH__020__M__1": "Hâlâ olabilir.",
"VO__SOPHIA__CH10__CHATTER__FIRE_CROSS__030__M__1": "Burada da varlar...",
"VO__SOPHIA__CH10__CHATTER__FIRE_EXTINGUISHED__030__M__1": "Evet... Lanet küçük fırsatçılar...",
"VO__SOPHIA__CH10__CHATTER__FIRE_LIT__020__M__1": "Şimdi... ya işe yarar... ya da ölürüm... Bunu yaptığıma inanamıyorum...",
"VO__SOPHIA__CH10__CHATTER__FIRST_KILL__010__M__1": "Lanet...",
"VO__SOPHIA__CH10__CHATTER__FIRST_KILL__030__M__1": "Bunu yaptığını... hiç görmemiştim.",
"VO__SOPHIA__CH10__CHATTER__GATE_HALLWAY__030__M__1": "Bunu birlikte yapalım...",
"VO__SOPHIA__CH10__CHATTER__HUB2_FESTIVAL_TALK__030__M__1": "Şunlara bak... Kutlamayı iyi biliyorlar doğrusu!",
"VO__SOPHIA__CH10__CHATTER__HUB2_FESTIVAL_TALK__050__M__1": "Buna ihtiyaçları yok. Ve BİZİM de bilmelerine ihtiyacımız yok.",
"VO__SOPHIA__CH10__CHATTER__HUB2_FESTIVAL_TALK__070__M__1": "Sadece bunun üstesinden gelmen lazım.",
"VO__SOPHIA__CH10__CHATTER__HUB2_FESTIVAL_TALK__090__M__1": "Sen... başka bir şey düşün!",
"VO__SOPHIA__CH10__CHATTER__HUB2_FLOWERPATH__020__M__1": "Şey, en azından bir kısmı...",
"VO__SOPHIA__CH10__CHATTER__HUB2_FLOWERPATH__050__M__1": "Ve o mabedin anlatacak DAHA ÇOK şeyi vardı...",
"VO__SOPHIA__CH10__CHATTER__HUB2_FOREST_NOMAP__010__M__1": "Hey, nereye gideceğini bilmiyorsan, şu haritayı unutma.",
"VO__SOPHIA__CH10__CHATTER__HUB2_GOINGDOWN_START__005__M__1": "Yani... bu... o neydi bilmiyorum bile...",
"VO__SOPHIA__CH10__CHATTER__HUB2_GOINGDOWN_START__020__M__1": "Pratik! Bunu sevdim! O kulenin nerede olduğunu bilmiyorsan şu haritaya tekrar baksana?",
"VO__SOPHIA__CH10__CHATTER__HUB2_NEW_THINGS__010__M__1": "İşte geldik! Görünüşe göre asıl şenlikler başladı!",
"VO__SOPHIA__CH10__CHATTER__HUB2_SOPHIA_STORY__010__M__1": "Annem varlıklı bir aileden geliyordu. Babamın bir kaçakçı olduğunu öğrenince pek memnun olmadılar. Beni de bir manastıra yolladılar—onun günahlarından \"arındırmak\" için.",
"VO__SOPHIA__CH10__CHATTER__HUB2_SOPHIA_STORY__030__M__1": "Günahkâr olup özgür olmayı yeğlerim. Bu yüzden kaçtım. Babama katıldım, ve...",
"VO__SOPHIA__CH10__CHATTER__HUB2_SOPHIA_STORY__070__M__1": "Hey, etrafına bak. Sorun yok. Yüzyıllar sonrasındayız, değil mi?",
"VO__SOPHIA__CH10__CHATTER__HUB2_VILLAGE_NOMAP__010__M__1": "Hm. Sessiz... Sanırım hepsi şu ziyafette.",
"VO__SOPHIA__CH10__CHATTER__IDLE_CHAPEL__005__M__1": "Liderleri...",
"VO__SOPHIA__CH10__CHATTER__IDLE_CHAPEL__020__M__1": "Milo. O ismi biliyorum. Akdeniz kıyılarında dolaşır. Bir kasaptır.",
"VO__SOPHIA__CH10__CHATTER__IDLE_FORT_1__010__M__1": "Bütün bunları daha önce yaşadığına inanamıyorum...",
"VO__SOPHIA__CH10__CHATTER__IDLE_FORT_5__010__M__1": "Senin için üzgünüm, Hugo... Ama daha iyi günler olacak.",
"VO__SOPHIA__CH10__CHATTER__INTERACT_CART__020__M__1": "Nasıl bu kadar sakin olabiliyorsun?...",
"VO__SOPHIA__CH10__CHATTER__INTERACT_CART__040__M__1": "Belli ki. Aptalca bir soru...",
"VO__SOPHIA__CH10__CHATTER__INTERACT_FALL__040__M__1": "Yaralandın mı?",
"VO__SOPHIA__CH10__CHATTER__INTRO_SLAVES__110__M__1": "Görünüşe bakılırsa... köle tüccarları derim...",
"VO__SOPHIA__CH10__CHATTER__INTRO_SLAVES__130__M__1": "İnsanları yakalıyorlar... Ve hayvan gibi satıyorlar...",
"VO__SOPHIA__CH10__CHATTER__KILL_FORT_2__020__M__1": "Şşş... Sakin.",
"VO__SOPHIA__CH10__CHATTER__KILL_FORT_3__020__M__1": "O şapele çabucak ulaşmamız lazım...",
"VO__SOPHIA__CH10__CHATTER__KILLED_ALL_FORT__020__M__1": "Bu biraz fazla kaçtı, değil mi?",
"VO__SOPHIA__CH10__CHATTER__KILLED_ALL_FORT__040__M__1": "Sadece... ilerleyelim, lütfen.",
"VO__SOPHIA__CH10__CHATTER__KNIFE_EVENT__060__M__1": "Kahretsin!",
"VO__SOPHIA__CH10__CHATTER__KNIFE_EVENT__075__M__1": "Hayır... Hayır!",
"VO__SOPHIA__CH10__CHATTER__KNIFE_EVENT__080__M__1": "Çek... ellerini... ondan!",
"VO__SOPHIA__CH10__CHATTER__LADY_IDLE__020__M__1": "Bunu düşünmemeye çalış...",
"VO__SOPHIA__CH10__CHATTER__LIKE_FEATHER__010__M__1": "Eee, Hugo... Hiç kendi yaşında bir hanıma çiçek verdin mi?",
"VO__SOPHIA__CH10__CHATTER__LIKE_FEATHER__030__M__1": "Hm... Daha heyecanlı bir şeye geçelim... Çiçekler... tüyler...",
"VO__SOPHIA__CH10__CHATTER__LIKE_FEATHER__050__M__1": "Neden?",
"VO__SOPHIA__CH10__CHATTER__LIKE_FEATHER__060__M__1": "Anlıyorum.",
"VO__SOPHIA__CH10__CHATTER__MANY_SLAVERS_IDLE__020__M__1": "Çok olabilir. Milo büyük bir balık...",
"VO__SOPHIA__CH10__CHATTER__MILO_LEFT__030__M__1": "Yani Koruyucu'nun oraya götürüldüğü mü söyleniyor?",
"VO__SOPHIA__CH10__CHATTER__MILO_REPUTATION__020__M__1": "Daha çok var!",
"VO__SOPHIA__CH10__CHATTER__PORTCULLIS_FOUND__010__M__1": "İşte orada!",
"VO__SOPHIA__CH10__CHATTER__PORTCULLIS_INSIDE__005__M__1": "Bunu asla geçemeyiz...",
"VO__SOPHIA__CH10__CHATTER__PORTCULLIS_MOVING__010__M__1": "Amicia, Milo tam şu duvarın arkasında...",
"VO__SOPHIA__CH10__CHATTER__PORTCULLIS_MOVING__030__M__1": "Sadece... hazır olduğundan emin oluyorum...",
"VO__SOPHIA__CH10__CHATTER__POST_RAT_CTRL_KILL__020__M__1": "Bu nasıl... Bunu nasıl...?",
"VO__SOPHIA__CH10__CHATTER__POST_RAT_CTRL_KILL__040__M__1": "Hayır, bir şey değil. Boş ver. Devam edelim.",
"VO__SOPHIA__CH10__CHATTER__PRISM_1ST_MOVE__040__M__1": "Sana söz verdim.",
"VO__SOPHIA__CH10__CHATTER__PRISM_REMINDER__010__M__1": "Hangi ateşe gitmek istediğini söyle, sana oraya bir yol açayım!",
"VO__SOPHIA__CH10__CHATTER__PULL_SUCCESS__030__M__1": "Yukarı çıkan altın bir merdiven.",
"VO__SOPHIA__CH10__CHATTER__RAT_CTRL_KILL__010__M__1": "Sen mi...? Bunu o yapıyor, değil mi?!",
"VO__SOPHIA__CH10__CHATTER__RAT_CTRL_KILL__030__M__1": "Peki... Peki...",
"VO__SOPHIA__CH10__CHATTER__RATS_PASSED__050__M__1": "Basilius'a ne oldu acaba...",
"VO__SOPHIA__CH10__CHATTER__REACH_TEMPLE_DOOR__020__M__1": "Şunu görüyor musun? Tapınak kapısını barikatlamışlar.",
"VO__SOPHIA__CH10__CHATTER__READY_TO_FORT__010__M__1": "Sanırım bu kadar. Gitmeye hazır mısın?",
"VO__SOPHIA__CH10__CHATTER__REUNION__020__M__1": "Hey! Yaşlılara nazik ol!",
"VO__SOPHIA__CH10__CHATTER__REUNITED_WITH_SOPHIA__010__M__1": "Hey! Burada!",
"VO__SOPHIA__CH10__CHATTER__REUNITED_WITH_SOPHIA__040__M__1": "Ne oldu be?!",
"VO__SOPHIA__CH10__CHATTER__REUNITED_WITH_SOPHIA__060__M__1": "Onlar etraftayken, bilmiyorum... belki! Ama bu... Boş ver!",
"VO__SOPHIA__CH10__CHATTER__REUNITED_WITH_SOPHIA__070__M__1": "Önce aşağıdaki şu ateşi yakmanı istiyorum!",
"VO__SOPHIA__CH10__CHATTER__RUN_TOWER__020__M__1": "Hugo, dur... Şövalyem o kuleyi benim için fetheder mi?!",
"VO__SOPHIA__CH10__CHATTER__RUN_TOWER__030__M__1": "Ona nasıl hücum ettiğini görmek istiyorum!",
"VO__SOPHIA__CH10__CHATTER__RUN_TOWER__040__M__1": "Onu benim için ele geçir!",
"VO__SOPHIA__CH10__CHATTER__RUN_TOWER__050__M__1": "Git!",
"VO__SOPHIA__CH10__CHATTER__SEA__010__M__1": "Vay... Şu manzaraya bak!",
"VO__SOPHIA__CH10__CHATTER__SEA__030__M__1": "Henüz değil, ama geri gelecek...",
"VO__SOPHIA__CH10__CHATTER__SEA__050__M__1": "Hayır, ablana olan borcumu ödeyene kadar olmaz.",
"VO__SOPHIA__CH10__CHATTER__SEA__070__M__1": "Sana söylemedi mi?! Hayatımı kurtardı!",
"VO__SOPHIA__CH10__CHATTER__SEA__100__M__1": "Şey, ben de!",
"VO__SOPHIA__CH10__CHATTER__SECOND_AREA_KILL_1ST__010__M__1": "Bunu özleyeceğimi söyleyemem.",
"VO__SOPHIA__CH10__CHATTER__SECOND_AREA_KILL_2ND__020__M__1": "Bu beladan çıkmamız gerçekten lazım...",
"VO__SOPHIA__CH10__CHATTER__SECOND_AREA_KILL_4TH__010__M__1": "Amicia...",
"VO__SOPHIA__CH10__CHATTER__SECOND_AREA_KILL_4TH__030__M__1": "Kendini kaptırma...",
"VO__SOPHIA__CH10__CHATTER__SECOND_KILL__010__M__1": "Bu iki etti...",
"VO__SOPHIA__CH10__CHATTER__SECOND_KILL__030__M__1": "Pekâlâ... Yapman gerekeni yap...",
"VO__SOPHIA__CH10__CHATTER__SEE_FORT__020__M__1": "İşte kalemiz!",
"VO__SOPHIA__CH10__CHATTER__SEE_FORT__060__M__1": "Sanırım... evet!",
"VO__SOPHIA__CH10__CHATTER__SERIOUS_TALK__100__M__1": "Evet, şey... hadi sadece yürüyelim.",
"VO__SOPHIA__CH10__CHATTER__SLAVE_RAGDOLL__030__M__1": "Yaptıkları bu...",
"VO__SOPHIA__CH10__CHATTER__SLAVE_RAGDOLL__060__M__1": "Burada bir çocuk vardı... Sevimli.",
"VO__SOPHIA__CH10__CHATTER__SO_MANY_DEAD_IDLE__020__M__1": "O kadar çok kişiyi öldürdüler ki...",
"VO__SOPHIA__CH10__CHATTER__SOPHIA_SHOW_PRISM__010__M__1": "Beni yüzüstü bırakma...",
"VO__SOPHIA__CH10__CHATTER__SOPHIA_SHOW_PRISM__040__M__1": "Pekâlâ. Yapıyorum.",
"VO__SOPHIA__CH10__CHATTER__SOPHIA_SHOW_PRISM__043__M__1": "Evet, doğru...",
"VO__SOPHIA__CH10__CHATTER__SOPHIA_SHOW_PRISM__046__M__1": "Şimdiye kadar iyi gidiyor!",
"VO__SOPHIA__CH10__CHATTER__SOPHIA_SHOW_PRISM__060__M__1": "Öff... Evet! En büyük hazinem! O ateşin ışığını yeterince toplayabileceğinden emin değildim...",
"VO__SOPHIA__CH10__CHATTER__TEMPLE_IN_SIGHT__020__M__1": "Hayır... Bir tür tapınak.",
"VO__SOPHIA__CH10__CHATTER__TEMPLE_UPSTAIRS__015__M__1": "Eee? Bizi buradan çıkaracak bir yol buldun mu?",
"VO__SOPHIA__CH10__CHATTER__TORTURE__020__M__1": "Bunu nasıl yapabildiler... ha...",
"VO__SOPHIA__CH10__CHATTER__TRENCH_OPENING__010__M__1": "Yani şapel şu hendeğin diğer tarafında, değil mi?...",
"VO__SOPHIA__CH10__CHATTER__TRENCH_TWO__020__M__1": "Bak, onlar da geçiyor!",
"VO__SOPHIA__CH10__CHATTER__TUTO_PRISM__010__M__1": "Dinle, onunla üçümüzü koruyabilirim, ama bizi bu cehennemden geçirmek için başka bir ateşe ihtiyacım olacak...",
"VO__SOPHIA__CH10__CHATTER__TUTO_PRISM__030__M__1": "Tamam! Fareleri sana bırakıyorum... Şimdi hangi ateşe gitmek istediğini ve ne zaman durmamı istediğini söyle yeter...",
"VO__SOPHIA__CH10__CHATTER__UNSTABLE_BRIDGE__010__M__1": "Hm. Burada küçük bir sorun var...",
"VO__SOPHIA__CH10__CHATTER__WATER_WAY__010__M__1": "Peki. Biraz daha güvenli görünüyor...",
"VO__SOPHIA__CH10__CHATTER__WATER_WAY__012__M__1": "Peki.",
"VO__SOPHIA__CH10__CHATTER__WATER_WAY__015__M__1": "Biraz daha güvenli görünüyor...",
"VO__SOPHIA__CH10__CHATTER__WATER_WAY__050__M__1": "Hey, Hugo!",
"VO__SOPHIA__CH10__CHATTER__WATER_WAY__070__M__1": "Zor olduğunu biliyorum ama lütfen, odaklanmaya devam et!",
"VO__SOPHIA__CH10__CHATTER__WATER_WINDOW__025__M__1": "Muhtemelen öyle. Ama hâlâ birlikteyiz.",
"VO__SOPHIA__CH10__CHATTER__WEDGE_INTERACT__020__M__1": "Birazcık gürültüye hazır ol...",
"VO__SOPHIA__CH10__CHATTER__WHERE_IS_MILO__010__M__1": "Yine de bize Milo'nun nerede olduğunu söylemiyor.",
"VO__SOPHIA__CH10__HELPER__CHANDELIER_1__010__M__1": "Şu avize kapıyı kırıp açacak kadar ağır görünüyor! Sadece onu kaldıracak bir yol lazım.",
"VO__SOPHIA__CH10__HELPER__CHANDELIER_2__010__M__1": "Avizeyi şu krankla kaldırabilirim. Sadece ne zaman olduğunu söyle!",
"VO__SOPHIA__CH10__HELPER__FIRE_1__010__M__1": "Benim için yakabileceğin başka bir ateş görüyor musun?",
"VO__SOPHIA__CH10__HELPER__FIRE_2__010__M__1": "Amicia! Şuradaki ateşi yak! Sonra prizmamı kullanabilirim!",
"VO__SOPHIA__CH10__HELPER__RAM_1__010__M__1": "Arbalet numaranı kullanıp o avizeyle kapıyı kırarak açabilir misin sence?",
"VO__SOPHIA__CH10__HELPER__RAM_2__010__M__1": "Hey! Şu halatı kullanıp avizeyi çekerek kapıyı açsana?",
"VO__SOPHIA__CH10__HELPER__TEMPLE_WEDGE_1__010__M__1": "Sanırım arbaletin bizi tapınağa sokabilir. Sana bir halat bulmamız gerek.",
"VO__SOPHIA__CH10__HELPER__TEMPLE_WEDGE_2__010__M__1": "Şu çatılardan birinde halat olabilir? Tapınağa girmek için tek ihtiyacımız o.",
"VO__SOPHIA__CH10__RTC__460_BACK_FROM_SANCTUARY__010__M__1": "İyiyiz.",
"VO__SOPHIA__CH10__RTC__460_BACK_FROM_SANCTUARY__015__M__1": "Özellikle sen. Tanıdığım en sinsi çocuksun.",
"VO__SOPHIA__CH10__RTC__470_LEAVE_TO_FORT__020__M__1": "Kulağa kesinlikle o kadar... cazip gelmiyor.",
"VO__SOPHIA__CH10__RTC__470_LEAVE_TO_FORT__040__M__1": "Öğrenmenin tek yolu var.",
"VO__SOPHIA__CH10__RTC__480_ENTER_FORT__030__M__1": "Bir fırtına geliyor.",
"VO__SOPHIA__CH10__RTC__480_ENTER_FORT__042__M__1": "Bana güven.",
"VO__SOPHIA__CH10__RTC__480_ENTER_FORT__050__M__1": "Üzgün... Bütün bunlar bir rüya yüzünden.",
"VO__SOPHIA__CH10__RTC__480_ENTER_FORT__070__M__1": "Çocuk olmayı bıraktığım gün.",
"VO__SOPHIA__CH10__RTC__480_ENTER_FORT__106__M__1": "Hey! Bu güzel bir çiçek!",
"VO__SOPHIA__CH10__RTC__480_ENTER_FORT__120__M__1": "Elbette!",
"VO__SOPHIA__CH10__RTC__480_ENTER_FORT__140__M__1": "Zaman geçiyor, tatlım... Büyüyorlar!",
"VO__SOPHIA__CH10__RTC__485_UNEXPECTED_STRIKE__140__M__1": "Lanet manyaklar...",
"VO__SOPHIA__CH10__RTC__485_UNEXPECTED_STRIKE__290__M__1": "Ne... oluyor... be?...",
"VO__SOPHIA__CH10__RTC__490_ENTER_FORT2__110__M__1": "Gidiyorum! Fırsat bulunca arabaya saklan!",
"VO__SOPHIA__CH10__RTC__495_LEGACY__020__M__1": "\"Birini koru, hepsini koru.\"",
"VO__SOPHIA__CH10__RTC__495_LEGACY__040__M__1": "Amma da güzel bir ahmaklar hanedanın varmış...",
"VO__SOPHIA__CH10__RTC__495_LEGACY__060__M__1": "Yine bu şey... Neden?",
"VO__SOPHIA__CH10__RTC__495_LEGACY__110__M__1": "Dur... Demek bu kadar kolay... Haritanın altında mı? Öylece?",
"VO__SOPHIA__CH10__RTC__495_LEGACY__150__M__1": "Tabii... Mantıklı.",
"VO__SOPHIA__CH10__RTC__495_LEGACY__185__M__1": "Her neyse, hayatında sıradan bir gün işte.",
"VO__SOPHIA__CH10__RTC__495_LEGACY__200__M__1": "Evet.",
"VO__SOPHIA__CH10__RTC__500_FRESCOE__110__M__1": "Hayır... O.",
"VO__SOPHIA__CH10__RTC__500_FRESCOE__120__M__1": "Hiçbir şey söyleme...",
"VO__SOPHIA__CH10__RTC__500_FRESCOE__160__M__1": "İşte başlıyor! Geliyorlar!",
"VO__SOPHIA__CH10__RTC__510_END__045__M__1": "HUGO!",
"VO__SOPHIA__CH10__RTC__510_END__120__M__1": "AMICIA! BURADAN!",
"VO__SOPHIA__CH10__RTC__510_END__130__M__1": "Denize, çabuk!",
"VO__SOPHIA__CH10__RTC__510_END__134__M__1": "Hugo. Bana bak.",
"VO__SOPHIA__CH10__RTC__510_END__136__M__1": "Hugo, bana bak!",
"VO__SOPHIA__CH10__RTC__510_END__140__M__1": "Neden ağlıyorsun?",
"VO__SOPHIA__CH10__RTC__510_END__150__M__1": "Sakin ol! Şimdi beni dinle... Sizin ikiniz gibisini hiç görmedim.",
"VO__SOPHIA__CH10__RTC__510_END__155__M__1": "Ve, aptalca bir sebepten, sizi seviyorum. Hem de hayatınızın en boktan, en kötü hâlinde seviyorum, tamam mı? Buna razıyım. En tuhaf şeyler bile bir sebeple olur. Denizci hikâyeleri bununla doludur. Yine de...",
"VO__SOPHIA__CH10__RTC__510_END__157__M__1": "SEN ciddi ciddi sakinleşip yetişkinlerin söylediğini dinlemelisin! Anlaştık mı?",
"VO__SOPHIA__CH10__RTC__510_END__160__M__1": "Ve SEN, lanet bir ordu değilsin! O sana hayranlıkla bakıyor! Ve senin ölüm arzun onunki olunca...",
"VO__SOPHIA__CH10__RTC__510_END__180__M__1": "...işte böyle oluyor! Ve bunun sonuçları olacak.",
"VO__SOPHIA__CH10__RTC__510_END__210__M__1": "Yüksek sesle söyleme.",
"VO__SOPHIA__CH10__RTC__510_END__220__M__1": "Kürek çekmesi gerekenler sizsiniz.",
}
