# -*- coding: utf-8 -*-
# CH07 VO. onom/EMPTY atlanir. Arnaud(=Duvar), Sophia(=Deniz Akrebi), la Rascasse(tekne).
# Episanguis/Odoris korunur; the Count->Kont, smugglers->kacakcilar, saltpeter->guhercile,
# the Survivor->Hayatta Kalan, dry dock->kuru havuz. shorty->ufaklik.
T = {
"VO__AMICIA__CH07__CHATTER__ABOUT_ARNAUD_SKILLS__020__M__1": "Şey, artık onun için çok geç...",
"VO__AMICIA__CH07__CHATTER__ABOUT_ARNAUD_SKILLS__040__M__1": "Hiç öğrenmedim ve şimdi vaktim yok.",
"VO__AMICIA__CH07__CHATTER__ABOUT_LAST_SOLDIER__020__M__1": "Yine de bir sorunumuz var ve zırh giyiyor...",
"VO__AMICIA__CH07__CHATTER__ABOUT_LAST_SOLDIER__040__M__1": "Onun da icabına bakılabilir.",
"VO__AMICIA__CH07__CHATTER__ABOUT_RATS__020__M__1": "Ah, hiç sanmıyorum.",
"VO__AMICIA__CH07__CHATTER__ABOUT_RATS__040__M__1": "Göreceğiz.",
"VO__AMICIA__CH07__CHATTER__ABOUT_RATS_KILL__080__M__1": "Bu yara acıdığı sürece olmaz...",
"VO__AMICIA__CH07__CHATTER__ABOUT_SOPHIA__010__M__1": "Deniz kuduruyor... İyi bir denizci mi? Sophia?",
"VO__AMICIA__CH07__CHATTER__ABOUT_SOPHIA__040__M__1": "Ben de peşinden gelirdim.",
"VO__AMICIA__CH07__CHATTER__ABOUT_THE_COUNT__010__M__1": "Birkaç kaçakçı için epey çok adam...",
"VO__AMICIA__CH07__CHATTER__ABOUT_THE_COUNT__030__M__1": "Onu pek sevmiyorsun.",
"VO__AMICIA__CH07__CHATTER__ABOUT_THE_COUNT__050__M__1": "Hmmm.",
"VO__AMICIA__CH07__CHATTER__AFTER_LEDGE_2__020__M__1": "Bu... sadece bir fırtına.",
"VO__AMICIA__CH07__CHATTER__AFTER_LEDGE_2__040__M__1": "Umarım önce oraya bir ulaşırız.",
"VO__AMICIA__CH07__CHATTER__AMICIA_KILL__020__M__1": "Babam. Ama sonra çalıştım.",
"VO__AMICIA__CH07__CHATTER__AMICIA_KILL__040__M__1": "Ya bu ya ölüm.",
"VO__AMICIA__CH07__CHATTER__ANCHOR_BREAK__020__M__1": "Gitmesi gerek, ama nasıl...?",
"VO__AMICIA__CH07__CHATTER__ANCHOR_CHECK__010__M__1": "Senden hoşlanıyor, o yüzden bilmelisin. Hugo ölüyor.",
"VO__AMICIA__CH07__CHATTER__ANCHOR_CHECK__030__M__1": "Kanı zehirlenmiş. Bir çare varsa, o adada.",
"VO__AMICIA__CH07__CHATTER__ANCHOR_CHECK__050__M__1": "Ah, ulaşacak...",
"VO__AMICIA__CH07__CHATTER__ANCHOR_ISSUE__010__M__1": "Sıkışmış!",
"VO__AMICIA__CH07__CHATTER__ANCHOR_OK__020__M__1": "Hadi şu çapayı çekip yelken açalım!",
"VO__AMICIA__CH07__CHATTER__ANCHOR_PULL__010__M__1": "Hafif değil...",
"VO__AMICIA__CH07__CHATTER__ANCHOR_RELEASED__010__M__1": "Hadi...",
"VO__AMICIA__CH07__CHATTER__ANCHOR_RELEASED__012__M__1": "O zaman onu kırabilirim!",
"VO__AMICIA__CH07__CHATTER__ARNAUD_2ND_KILL__010__M__1": "Aferin.",
"VO__AMICIA__CH07__CHATTER__ARNAUD_2ND_KILL__030__M__1": "Görebiliyorum...",
"VO__AMICIA__CH07__CHATTER__ARNAUD_KILL__020__M__1": "Eyvah, yaptın işte! Bir tane daha geliyor!",
"VO__AMICIA__CH07__CHATTER__ARNAUD_KILL__040__M__1": "Tanrım...",
"VO__AMICIA__CH07__CHATTER__ARNAUD_LEVER__020__M__1": "Umarım görür...",
"VO__AMICIA__CH07__CHATTER__ARNAUD_LEVER__040__M__1": "Evet...",
"VO__AMICIA__CH07__CHATTER__ARNAUD_MOVES__010__M__1": "Bu havada gerçekten yelken mi açacağız?",
"VO__AMICIA__CH07__CHATTER__ARNAUD_MOVES__030__M__1": "Lanet olsun, hayır...",
"VO__AMICIA__CH07__CHATTER__ARNAUD_MOVES__050__M__1": "Ne yapıyorsun?",
"VO__AMICIA__CH07__CHATTER__ARNAUD_SOPHIA__010__M__1": "Sophia senden pek hoşlanmıyor gibi!",
"VO__AMICIA__CH07__CHATTER__ARNAUD_SOPHIA__030__M__1": "Ne için?",
"VO__AMICIA__CH07__CHATTER__ARNAUD_SOPHIA__050__M__1": "Anladım.",
"VO__AMICIA__CH07__CHATTER__ARNAUD_X_KILL__010__M__1": "Tanrım... Hiç ıskalamıyorsun... Şimdi seni bir savaş alanında gözümde canlandırabiliyorum...",
"VO__AMICIA__CH07__CHATTER__BOAT__010__M__1": "Sakın bana bunun senin teknen olduğunu söyleme...",
"VO__AMICIA__CH07__CHATTER__BOAT__040__M__1": "Emin değilim, kırılabilirim...",
"VO__AMICIA__CH07__CHATTER__BOAT_PONTOON__010__M__1": "Demek... bu la Rascasse, değil mi?",
"VO__AMICIA__CH07__CHATTER__BOAT_PULL_READY__010__M__1": "Çekiyorum! Hadi!",
"VO__AMICIA__CH07__CHATTER__BOLT_FIRE_REACT__020__M__1": "Simya. Gizli tarif.",
"VO__AMICIA__CH07__CHATTER__BOLT_FIRE_REACT__040__M__1": "Göreceksin...",
"VO__AMICIA__CH07__CHATTER__CAVE_HALLWAY__010__M__1": "Demek bu kaçakçılarına çıkıyor?",
"VO__AMICIA__CH07__CHATTER__CAVE_HALLWAY__030__M__1": "Kısayolunda fareler var, biliyor musun?",
"VO__AMICIA__CH07__CHATTER__CAVE_HALLWAY__050__M__1": "Tanrım... Bu hiç hoşuma gitmiyor...",
"VO__AMICIA__CH07__CHATTER__CAVE_WRECK__030__M__1": "\"O\" mu?!",
"VO__AMICIA__CH07__CHATTER__CAVE_WRECK__070__M__1": "Onunla buluşunca göreceğiz. Hadi. Son bir gayret...",
"VO__AMICIA__CH07__CHATTER__CHANNEL__010__M__1": "Su mu?",
"VO__AMICIA__CH07__CHATTER__CHANNEL__046__M__1": "Ah, hadi ama, sadece deniz suyu, bak.",
"VO__AMICIA__CH07__CHATTER__CHANNEL__050__M__1": "Hugo, lütfen... Yorgunum... Sadece... adanı düşün...",
"VO__AMICIA__CH07__CHATTER__CHANNEL__070__M__1": "Sen de başlama! Elini tutarım Hugo! Karşıya geçeceğiz!",
"VO__AMICIA__CH07__CHATTER__CHANNEL__093__M__1": "Tanrım...",
"VO__AMICIA__CH07__CHATTER__CHANNEL__130__M__1": "Güne göre değişir...",
"VO__AMICIA__CH07__CHATTER__CHANNEL_FOWARD__080__M__1": "Her şey yolunda!... Artık o sakinleştiğine göre...",
"VO__AMICIA__CH07__CHATTER__CHANNEL_OK__020__M__1": "Şey... Teşekkürler, Arnaud...",
"VO__AMICIA__CH07__CHATTER__EMBUSH__020__M__1": "Hugo! Umarım ona rüyanı ve... diğer her şeyi anlatmadın!",
"VO__AMICIA__CH07__CHATTER__ENCOUNTER_1ST_PART__030__M__1": "Onu tanıyorlar...",
"VO__AMICIA__CH07__CHATTER__ENTER_CAVE__010__M__1": "Ha... burası Guyenne'den de beter oluyor...",
"VO__AMICIA__CH07__CHATTER__ENTER_CAVE__030__M__1": "Peki.",
"VO__AMICIA__CH07__CHATTER__ENTER_CAVE__060__M__1": "Ah lütfen...",
"VO__AMICIA__CH07__CHATTER__EPISANGUIS_BACK__020__M__1": "Haklısın... Geri geldi!... Arnaud!",
"VO__AMICIA__CH07__CHATTER__EPISANGUIS_BACK__040__M__1": "Yanında sarı kristaller var! Birini kır ve bana at!",
"VO__AMICIA__CH07__CHATTER__FEATHER_GRAB__010__M__1": "Bir deniz kuşu olmalı...",
"VO__AMICIA__CH07__CHATTER__FEATHER_GRAB__030__M__1": "Muhtemelen... Ve artık senin. Al...",
"VO__AMICIA__CH07__CHATTER__FEATHER_SPOT__010__M__1": "Hey, şuna bak...",
"VO__AMICIA__CH07__CHATTER__FISHERMAN_DOOR__010__M__1": "Sakin görünüyor...",
"VO__AMICIA__CH07__CHATTER__FISHERMAN_DOOR__030__M__1": "Hiç sanmıyorum.",
"VO__AMICIA__CH07__CHATTER__GAP__040__M__1": "Hey! Dikkat!",
"VO__AMICIA__CH07__CHATTER__GAP__051__M__1": "Peki...",
"VO__AMICIA__CH07__CHATTER__GAP__060__M__1": "Beni bekleyemez misin?!",
"VO__AMICIA__CH07__CHATTER__HUGO_CABIN__010__M__1": "Nasıl dayanıyorsun?",
"VO__AMICIA__CH07__CHATTER__HUGO_CABIN__030__M__1": "Buradan ayrılınca bakarız!",
"VO__AMICIA__CH07__CHATTER__IDLE_CAVE_1__010__M__1": "Peki bu kaçakçılar kaç kişi?",
"VO__AMICIA__CH07__CHATTER__IDLE_CAVE_1__030__M__1": "Öyle mi? Bir aziz mi?",
"VO__AMICIA__CH07__CHATTER__IDLE_CAVE_3__030__M__1": "Biz... güvenlik arıyoruz. Tıpkı senin gibi.",
"VO__AMICIA__CH07__CHATTER__IDLE_CAVE_3__050__M__1": "Evet.",
"VO__AMICIA__CH07__CHATTER__KILL_ARNAUD_REACT_1__020__M__1": "Teşekkür mü?",
"VO__AMICIA__CH07__CHATTER__KILL_ARNAUD_REACT_3__020__M__1": "Bu bir yarışma değil...",
"VO__AMICIA__CH07__CHATTER__KILL_RNO_RATS_1__020__M__1": "Biliyorum...",
"VO__AMICIA__CH07__CHATTER__KILL_RNO_RATS_2__020__M__1": "Gerekli olanından...",
"VO__AMICIA__CH07__CHATTER__LA_RASCASSE__010__M__1": "Arnaud! Hugo nerede?",
"VO__AMICIA__CH07__CHATTER__LA_RASCASSE__025__M__1": "Dışarıda ne yapıyorsun?! Kamaraya gir! Sırılsıklam olmuşsun!",
"VO__AMICIA__CH07__CHATTER__LA_RASCASSE__100__M__1": "Evet!",
"VO__AMICIA__CH07__CHATTER__LEDGE_FALL__030__M__1": "Tanrım, hayır!",
"VO__AMICIA__CH07__CHATTER__LEDGE_FALL__050__M__1": "Dur, dur! Ben yaparım!",
"VO__AMICIA__CH07__CHATTER__LEDGE_NEST__010__M__1": "Buradan, sanırım... Dikkat.",
"VO__AMICIA__CH07__CHATTER__LET_GO_OK__020__M__1": "O zaman gidelim.",
"VO__AMICIA__CH07__CHATTER__LET_GO_OK__040__M__1": "Bilmiyorum. Kendini ne kadar iştah açıcı hissediyorsun?",
"VO__AMICIA__CH07__CHATTER__LOCK_SPOT__010__M__1": "Bir kilit...",
"VO__AMICIA__CH07__CHATTER__LOCK_WONT_HOLD__010__M__1": "Ha, dayanmaz...",
"VO__AMICIA__CH07__CHATTER__MEETING_AGAIN__010__M__1": "Hayatta hissediyor musun kendini?",
"VO__AMICIA__CH07__CHATTER__MEETING_AGAIN__050__M__1": "Hayır... Vuracak bir şey görmüyorum... Ve yeterince uzun dayanacak bir şeyim de yok.",
"VO__AMICIA__CH07__CHATTER__MID_SECTION__050__M__1": "Bu bir şok...",
"VO__AMICIA__CH07__CHATTER__MORE_RATS__040__M__1": "Mutlu musun şimdi? Yine de karşıya geçiyoruz.",
"VO__AMICIA__CH07__CHATTER__NEGOCIATION__010__M__1": "Hugo... Artık gitmeliyiz.",
"VO__AMICIA__CH07__CHATTER__NEGOCIATION__030__M__1": "O tehlikeli!",
"VO__AMICIA__CH07__CHATTER__NEGOCIATION__060__M__1": "Ben... Pekâlâ, tamam...",
"VO__AMICIA__CH07__CHATTER__NEST_CART__010__M__1": "Bir araba... kaçakçıların onu terk etmiş olmalı...",
"VO__AMICIA__CH07__CHATTER__NEST_CART_NO_LIGHTS__020__M__1": "Evet, haklısın.",
"VO__AMICIA__CH07__CHATTER__NEST_PUSH__010__M__1": "Pekâlâ... Bir nefes al. Gidelim.",
"VO__AMICIA__CH07__CHATTER__NEST_PUSH__040__M__1": "Başka yol olmadığına eminim. Arabanın ışığı bizi koruyacak.",
"VO__AMICIA__CH07__CHATTER__NEST_PUSH_ENTER__020__M__1": "Onu... yakaladıkları şeylerden yapıyorlar.",
"VO__AMICIA__CH07__CHATTER__NEST_PUSH_ENTER__080__M__1": "Bunda onun hiçbir suçu yok, tamam mı?! Herkes gibi biz de bu şeylerle baş başa kaldık!",
"VO__AMICIA__CH07__CHATTER__NEST_PUSH_ENTER__110__M__1": "La Cuna'ya ulaşacağız. Seni iyileştireceğiz.",
"VO__AMICIA__CH07__CHATTER__NEST_REVEAL__020__M__1": "Eyvah...",
"VO__AMICIA__CH07__CHATTER__NEST_REVEAL__040__M__1": "Bir yuva.",
"VO__AMICIA__CH07__CHATTER__NEST_REVEAL__060__M__1": "Öyleyiz.",
"VO__AMICIA__CH07__CHATTER__NEST_REVEAL__080__M__1": "Ya bu ya burada kalmak.",
"VO__AMICIA__CH07__CHATTER__OBJECTIVE_HIDEOUT__010__M__1": "\"Enkazın diğer tarafındayız\", peki şimdi nereye?",
"VO__AMICIA__CH07__CHATTER__OBJECTIVE_HIDEOUT__030__M__1": "Güzel...",
"VO__AMICIA__CH07__CHATTER__OBJECTIVE_HIDEOUT__050__M__1": "Ne? Neden olmasın ki?!",
"VO__AMICIA__CH07__CHATTER__OBJECTIVE_HIDEOUT__070__M__1": "Hayır, hayır, hayır... Orada olmak zorunda!",
"VO__AMICIA__CH07__CHATTER__ODORIS_BOLT_OK__010__M__1": "İşte! Dayanmalı!",
"VO__AMICIA__CH07__CHATTER__ODORIS_DONE__010__M__1": "İşte! Odoris! Hadi deneyelim!",
"VO__AMICIA__CH07__CHATTER__ODORIS_DONE__020__M__1": "Arnaud! Krankın olduğu şu yüksek yeri görüyor musun? Fareleri yolundan çektiğimde, oraya koş!",
"VO__AMICIA__CH07__CHATTER__ODORIS_SUCCESS__050__M__1": "Daha kurtulmadık! Şu krank ne işe yarıyor?",
"VO__AMICIA__CH07__CHATTER__ODORIS_TUTO__010__M__1": "Mükemmel! Ama tek başına işe yaramaz... Bir şeye eklemem lazım... uçucu yapmam lazım... Belki güherçile?",
"VO__AMICIA__CH07__CHATTER__ODORIS_TUTO_SALPETER__010__M__1": "Mükemmel! Ama tek başına işe yaramaz... Uçucu yapmak için güherçile lazım... belki etrafta vardır...",
"VO__AMICIA__CH07__CHATTER__ODORIS_TUTO_SALPETER_OK__010__M__1": "Bu... Güherçile mi?... Evet... Şimdi onu Episanguis ile karıştıralım.",
"VO__AMICIA__CH07__CHATTER__ODORIS_USE__020__M__1": "Şimdi!",
"VO__AMICIA__CH07__CHATTER__ODORIS_USELESS__030__M__1": "Evet... Başka bir şey deneyeceğim!",
"VO__AMICIA__CH07__CHATTER__PERMISSION__020__M__1": "Hey! Ne demiştim? Kamaraya geri dön!",
"VO__AMICIA__CH07__CHATTER__PERMISSION__040__M__1": "Hadi şu çapayı bitirelim!",
"VO__AMICIA__CH07__CHATTER__PLANK_LIFT__030__M__1": "Bir bakayım!",
"VO__AMICIA__CH07__CHATTER__POST_FEATHER__040__M__1": "Gel, geri dönelim.",
"VO__AMICIA__CH07__CHATTER__PUSH_CHEST_ADD__040__M__1": "Bu onun sadece bir hâli. Bir sürü başkasını gördük.",
"VO__AMICIA__CH07__CHATTER__RAT_MOVE__020__M__1": "Yavaş ol, tamam mı?",
"VO__AMICIA__CH07__CHATTER__RAT_MOVE__050__M__1": "Şşş!",
"VO__AMICIA__CH07__CHATTER__RATS_BELOW__020__M__1": "Bakacağım.",
"VO__AMICIA__CH07__CHATTER__RATS_FIRST_KILL__030__M__1": "Kötü insanlar, Hugo.",
"VO__AMICIA__CH07__CHATTER__REACH_DROP__010__M__1": "Evet. Geldik...",
"VO__AMICIA__CH07__CHATTER__REACH_DROP__030__M__1": "Ah hadi ama, bir şey olmaz.",
"VO__AMICIA__CH07__CHATTER__RESUME_RUN__010__M__1": "Hugo, geri gel! Oyun oynamak istemiyorum!",
"VO__AMICIA__CH07__CHATTER__RESUME_RUN__030__M__1": "Nazik olmak senin için bu kadar zor mu?! Seni küçük...",
"VO__AMICIA__CH07__CHATTER__RESUME_RUN__040__M__1": "En azından daha iyi görünüyorsun...",
"VO__AMICIA__CH07__CHATTER__RNO_CROSSING__013__M__1": "Sadece kan—avlarından kalanlar... ve sanırım salgıladıkları bir şey.",
"VO__AMICIA__CH07__CHATTER__RNO_CROSSING__020__M__1": "Hadi... Neredeyse vardın!",
"VO__AMICIA__CH07__CHATTER__RNO_CROSSING_OK__020__M__1": "Evet!",
"VO__AMICIA__CH07__CHATTER__SAILS_ORDER__010__M__1": "Evet! Çapa kalktı!",
"VO__AMICIA__CH07__CHATTER__SAILS_ORDER__030__M__1": "Emredersiniz, kaptan.",
"VO__AMICIA__CH07__CHATTER__SAILS_ORDER__071__M__1": "Çok yaklaştık...",
"VO__AMICIA__CH07__CHATTER__SAILS_START__020__M__1": "Hı... tamam. Ben... diğerini alırım.",
"VO__AMICIA__CH07__CHATTER__SAILS_START__030__M__1": "Pekâlâ hadi!",
"VO__AMICIA__CH07__CHATTER__SAILS_STUCK__009__M__1": "Evet! Yapıyoruz... Bu yerden... ayrılıyoruz!",
"VO__AMICIA__CH07__CHATTER__SAILS_STUCK__010__M__1": "Ne?! Benim tarafımda yelken açılmıyor!",
"VO__AMICIA__CH07__CHATTER__SAILS_STUCK__030__M__1": "Sophia! Gel!",
"VO__AMICIA__CH07__CHATTER__SAILS_STUCK__074__M__1": "Onu kesmeyi deneyebilirim!",
"VO__AMICIA__CH07__CHATTER__SAILS_STUCK__090__M__1": "Anladım!",
"VO__AMICIA__CH07__CHATTER__SEAGULLS__040__M__1": "İstersen. Sadece gözümün önünde dur...",
"VO__AMICIA__CH07__CHATTER__SEAGULLS__080__M__1": "Savaştan ne anlarsın ki?",
"VO__AMICIA__CH07__CHATTER__SEAGULLS__100__M__1": "Ah. Biz... Guyenne'deniz.",
"VO__AMICIA__CH07__CHATTER__SEAGULLS__120__M__1": "Öyleydi...",
"VO__AMICIA__CH07__CHATTER__SHIELD_IDEA__020__M__1": "Ne?!",
"VO__AMICIA__CH07__CHATTER__SHIELD_IDEA__030__M__1": "Ama yanacak!",
"VO__AMICIA__CH07__CHATTER__SHIELD_IDEA__050__M__1": "Pekâlâ. Ben yaparım.",
"VO__AMICIA__CH07__CHATTER__SHIELD_LOCK__010__M__1": "Gidelim!",
"VO__AMICIA__CH07__CHATTER__SHIELD_RUN__050__M__1": "Gördün mü? Onlara alışıyorsun!",
"VO__AMICIA__CH07__CHATTER__SHIELD_RUN__080__M__1": "Neredeyse vardık! Biraz daha dayan.",
"VO__AMICIA__CH07__CHATTER__SHIELD_RUN_GO__010__M__1": "Hadi yapalım şunu!",
"VO__AMICIA__CH07__CHATTER__SHIELD_RUN_OK__020__M__1": "Yandın mı?",
"VO__AMICIA__CH07__CHATTER__SMELL_THE_SEA__009__M__1": "Eee, ne buldun?",
"VO__AMICIA__CH07__CHATTER__SMELL_THE_SEA__020__M__1": "At kokusu alıyorum ve... aman Tanrım, ben miyim yoksa?",
"VO__AMICIA__CH07__CHATTER__SMELL_THE_SEA__040__M__1": "Dur! Konuşmamız lazım!",
"VO__AMICIA__CH07__CHATTER__SMELL_THE_SEA__060__M__1": "Hugo! Bu önemli!",
"VO__AMICIA__CH07__CHATTER__SMUGGLERS_HUNT__005__M__1": "Farelere rağmen kaçakçı avındalar mı?",
"VO__AMICIA__CH07__CHATTER__SMUGGLERS_HUNT__020__M__1": "Bu delilik...",
"VO__AMICIA__CH07__CHATTER__SOPHIA_BAR__010__M__1": "Dümeni mi kırmışlar?!",
"VO__AMICIA__CH07__CHATTER__SOPHIA_BAR__040__M__1": "Ha... pardon.",
"VO__AMICIA__CH07__CHATTER__SOUVENIR_1__005__M__1": "Hmmm... Bu tekne artık hiçbir yere gitmiyor...",
"VO__AMICIA__CH07__CHATTER__SOUVENIR_1__080__M__1": "Birine benziyor, evet.",
"VO__AMICIA__CH07__CHATTER__SOUVENIR_1__100__M__1": "O zaman bırak dinlensin, hak etti. Gel?...",
"VO__AMICIA__CH07__CHATTER__SOUVENIR_CAVE__010__M__1": "Ooo... Bak... Bu ne?",
"VO__AMICIA__CH07__CHATTER__SOUVENIR_CAVE__070__M__1": "Bekle... Sadece biraz.",
"VO__AMICIA__CH07__CHATTER__SOUVENIR_CAVE__090__M__1": "Öyle.",
"VO__AMICIA__CH07__CHATTER__SOUVENIR_CAVE__110__M__1": "Sadece onu aklında tut... Gel?",
"VO__AMICIA__CH07__CHATTER__SOUVENIR_CAVE_WRONGWAY__010__M__1": "Burası çok karanlık...",
"VO__AMICIA__CH07__CHATTER__SQUIZZ_THROUGH__010__M__1": "Buradan mı?",
"VO__AMICIA__CH07__CHATTER__STICK_CROSSING_1__010__M__1": "Yanımda dur. Gidiyoruz.",
"VO__AMICIA__CH07__CHATTER__STICK_CROSSING_1__030__M__1": "Hey, sıkma! Daha hızlı gitmemi sağlamaz!",
"VO__AMICIA__CH07__CHATTER__STICK_CROSSING_OK__010__M__1": "İşte geldik. Kolay!",
"VO__AMICIA__CH07__CHATTER__STICK_GRAB__010__M__1": "Bu işe yarar.",
"VO__AMICIA__CH07__CHATTER__STICK_GRAB__030__M__1": "Sadece... takip et.",
"VO__AMICIA__CH07__CHATTER__THE_SEA__020__M__1": "Geçer...",
"VO__AMICIA__CH07__CHATTER__THE_SEA__050__M__1": "Neredeyse vardık.",
"VO__AMICIA__CH07__CHATTER__TO_PONTOON__020__M__1": "Hiçbir şey! Hazırlan! La Cuna'ya gidiyoruz!",
"VO__AMICIA__CH07__CHATTER__TO_THE_BEACH__030__M__1": "Bu kadar hızlı gitmeyi kes!",
"VO__AMICIA__CH07__CHATTER__TO_THE_BEACH__050__M__1": "Ne kadar düşünceli...",
"VO__AMICIA__CH07__CHATTER__TORCH_OK__010__M__1": "İşte!",
"VO__AMICIA__CH07__CHATTER__TORCH_OK__040__M__1": "İyi misin? Isırık yok?",
"VO__AMICIA__CH07__CHATTER__UNEXPECTED_FOES__030__M__1": "Şşş...",
"VO__AMICIA__CH07__CHATTER__UNEXPECTED_FOES__090__M__1": "Hayır. Ben yaparım.",
"VO__AMICIA__CH07__CHATTER__UNEXPECTED_RATS__040__M__1": "Görünüşe göre senden hoşlanıyorlar...",
"VO__AMICIA__CH07__CHATTER__UNEXPECTED_RATS__070__M__1": "Ah, hadi ama... Peki, yolu açalım.",
"VO__AMICIA__CH07__CHATTER__UNEXPECTED_RATS__111__M__1": "Geçen sefer iyi bitmemişti...",
"VO__AMICIA__CH07__CHATTER__UPPER_HOUSE__020__M__1": "Senin adamların daha iyi değil. Kanunsuz ayaktakımı. Övünülecek bir şey yok...",
"VO__AMICIA__CH07__CHATTER__USE_HAM__010__M__1": "Yemek hazır!",
"VO__AMICIA__CH07__CHATTER__USE_HAM__030__M__1": "Gitmek güvenli!",
"VO__AMICIA__CH07__CHATTER__VICTORIOUS__020__M__1": "Evet, yakında geri gelmezler!",
"VO__AMICIA__CH07__CHATTER__VILLAGE_ENTRANCE__041__M__1": "Yaklaşıyoruz.",
"VO__AMICIA__CH07__CHATTER__VISTA_BOAT__020__M__1": "Demek sana göre kısayol bu?!",
"VO__AMICIA__CH07__CHATTER__VISTA_BOAT__050__M__1": "Hayır! Yolu ben açarım, sen takip et ve itaat et.",
"VO__AMICIA__CH07__CHATTER__WONT_GET_HER__005__M__1": "Arnaud, kaçakçını yakalarlarsa...",
"VO__AMICIA__CH07__CHATTER__WONT_GET_HER__020__M__1": "Farelerden bahsediyorum!",
"VO__AMICIA__CH07__CHATTER__WONT_GET_HER__040__M__1": "Pekâlâ...",
"VO__AMICIA__CH07__CHATTER__WRECK_SECRET__010__M__1": "Burası bir tekne mezarlığı...",
"VO__AMICIA__CH07__RTC__280_SCAR__020__M__1": "Dur...",
"VO__AMICIA__CH07__RTC__280_SCAR__040__M__1": "Ne?...",
"VO__AMICIA__CH07__RTC__280_SCAR__043__M__1": "Hayır!",
"VO__AMICIA__CH07__RTC__280_SCAR__140__M__1": "Sesinin yardımı dokunmuyor.",
"VO__AMICIA__CH07__RTC__280_SCAR__170__M__1": "Peki... O zaman söyle bana, neden geri döndün? Neden beni öylece ölüme bırakmadın?",
"VO__AMICIA__CH07__RTC__280_SCAR__180__M__1": "Söyle bana, sana neden güveneyim?... Fareler seni bir sorun eksiltsin diye neden izin vermeyeyim?!",
"VO__AMICIA__CH07__RTC__280_SCAR__200__M__1": "Demek kaçıyorsun.",
"VO__AMICIA__CH07__RTC__280_SCAR__220__M__1": "Fareler.",
"VO__AMICIA__CH07__RTC__280_SCAR__250__M__1": "Geliyorum!",
"VO__AMICIA__CH07__RTC__280_SCAR__260__M__1": "Çok dikkatli ol. Bu, seni öldürmem gerektiğinin sürekli bir hatırlatıcısı.",
"VO__AMICIA__CH07__RTC__290_TRANSPORT__010__M__1": "Hugo, cevap vermedin!",
"VO__AMICIA__CH07__RTC__290_TRANSPORT__030__M__1": "Önce nereye gittiğimizi söyle.",
"VO__AMICIA__CH07__RTC__290_TRANSPORT__050__M__1": "Kim?",
"VO__AMICIA__CH07__RTC__290_TRANSPORT__070__M__1": "Harika. Daha çok suçlu.",
"VO__AMICIA__CH07__RTC__290_TRANSPORT__110__M__1": "\"İşte doğru tavır bu\"...",
"VO__AMICIA__CH07__RTC__300_SMUGGLER__006__M__1": "Şey, buyur bakalım...",
"VO__AMICIA__CH07__RTC__300_SMUGGLER__090__M__1": "Onu bir dene!",
"VO__AMICIA__CH07__RTC__302_WAITING_FOR_SOPHIA__010__M__1": "Güvenli görünüyor.",
"VO__AMICIA__CH07__RTC__302_WAITING_FOR_SOPHIA__040__M__1": "Bilmiyorum, Hugo...",
"VO__AMICIA__CH07__RTC__302_WAITING_FOR_SOPHIA__090__M__1": "Nazik davranmazsa fareleri üstüne sal.",
"VO__AMICIA__CH07__RTC__303_SAVING_SOPHIA__050__M__1": "İyi misin?",
"VO__AMICIA__CH07__RTC__303_SAVING_SOPHIA__070__M__1": "Bana hiçbir borcun yok.",
"VO__AMICIA__CH07__RTC__303_SAVING_SOPHIA__090__M__1": "Peki. Yardımı olacaksa arkadaş olabiliriz.",
"VO__ARNAUD__CH07__CHATTER__ABOUT_ARNAUD_SKILLS__010__M__1": "Daha çok çalışmalıydı.",
"VO__ARNAUD__CH07__CHATTER__ABOUT_ARNAUD_SKILLS__030__M__1": "Neden kendin bir kılıç kullanmıyorsun?",
"VO__ARNAUD__CH07__CHATTER__ABOUT_ARNAUD_SKILLS__050__M__1": "Yazık.",
"VO__ARNAUD__CH07__CHATTER__ABOUT_ARNAUD_SKILLS__070__M__1": "Fareli çocuğa bak sen...",
"VO__ARNAUD__CH07__CHATTER__ABOUT_LAST_SOLDIER__030__M__1": "Hiçbir zaman insanı ölümsüz yapmaz.",
"VO__ARNAUD__CH07__CHATTER__ABOUT_RATS__010__M__1": "Hiç şüphesiz.",
"VO__ARNAUD__CH07__CHATTER__ABOUT_RATS__030__M__1": "Bir gün seçecek kadar büyüyecek.",
"VO__ARNAUD__CH07__CHATTER__ABOUT_RATS_KILL__050__M__1": "O ilk seferde yaratıklarını üstüme saldığını düşününce...",
"VO__ARNAUD__CH07__CHATTER__ABOUT_RATS_KILL__070__M__1": "Geçmişte kaldı.",
"VO__ARNAUD__CH07__CHATTER__ABOUT_SOPHIA__020__M__1": "En iyisi. Kanında var. Sanırım bir yerde duramamasının nedeni de bu.",
"VO__ARNAUD__CH07__CHATTER__ABOUT_THE_COUNT__020__M__1": "Kont kanun ve düzen adamı. Lanet bir şerefsiz. Ama o korkak, kim bilir nereye kayboldu.",
"VO__ARNAUD__CH07__CHATTER__ABOUT_THE_COUNT__040__M__1": "Birbirimizden nefret ederiz.",
"VO__ARNAUD__CH07__CHATTER__AFTER_LEDGE_2__030__M__1": "Umarım o tekneye varmadan sakinleşir.",
"VO__ARNAUD__CH07__CHATTER__AMICIA_KILL__010__M__1": "Sana ateş etmeyi kim öğretti?",
"VO__ARNAUD__CH07__CHATTER__AMICIA_KILL__030__M__1": "Güzel. Disiplin...",
"VO__ARNAUD__CH07__CHATTER__ANCHOR_CHECK__020__M__1": "Ne?",
"VO__ARNAUD__CH07__CHATTER__ANCHOR_CHECK__040__M__1": "O zaman oraya vardığından emin olalım.",
"VO__ARNAUD__CH07__CHATTER__ANCHOR_ISSUE__020__M__1": "Sophia! Sanırım çapayı sıkıştırmışlar!",
"VO__ARNAUD__CH07__CHATTER__ANCHOR_OK__010__M__1": "Temiz atış.",
"VO__ARNAUD__CH07__CHATTER__ANCHOR_PULL__020__M__1": "Bu bir çapa. Çapalamak için yapılmış.",
"VO__ARNAUD__CH07__CHATTER__ANCHOR_RELEASED__011__M__1": "Kilitli bir karşı ağırlık var!",
"VO__ARNAUD__CH07__CHATTER__ANCHOR_RELEASED__020__M__1": "Yardım lazım mı?",
"VO__ARNAUD__CH07__CHATTER__ANCHOR_SPOTTED__010__M__1": "Şu zincir çapayı kilitliyor!",
"VO__ARNAUD__CH07__CHATTER__ARNAUD_2ND_KILL__020__M__1": "Benim işim bu.",
"VO__ARNAUD__CH07__CHATTER__ARNAUD_KILL__030__M__1": "Ne olmuş? Onun icabına bakarım... Sen söyle yeter—Emret, ben infaz edeyim.",
"VO__ARNAUD__CH07__CHATTER__ARNAUD_LEVER__010__M__1": "Neredeyse vardık. Kardeşin yakında La Cuna'yı görecek.",
"VO__ARNAUD__CH07__CHATTER__ARNAUD_LEVER__030__M__1": "Kır şu şeyi!",
"VO__ARNAUD__CH07__CHATTER__ARNAUD_MOVES__040__M__1": "Burada kal!",
"VO__ARNAUD__CH07__CHATTER__ARNAUD_SOPHIA__020__M__1": "Rüzgâra göre değişir... ama her hâlükârda bana borçlu.",
"VO__ARNAUD__CH07__CHATTER__ARNAUD_SOPHIA__040__M__1": "Bana emredildiğinde onu öldürmediğim için.",
"VO__ARNAUD__CH07__CHATTER__ARNAUD_X_KILL__020__M__1": "Bunu yapamazsın. Ve yapmamalısın.",
"VO__ARNAUD__CH07__CHATTER__BEACH_2_START__020__M__1": "Epey hasarlı, ama amacı bu—benim yerime o acı çeker.",
"VO__ARNAUD__CH07__CHATTER__BEACH_2_START__040__M__1": "Ben de.",
"VO__ARNAUD__CH07__CHATTER__BOAT__009__M__1": "İşte geldik.",
"VO__ARNAUD__CH07__CHATTER__BOAT__020__M__1": "Tabii ki değil, ama oraya çıkıyor.",
"VO__ARNAUD__CH07__CHATTER__BOAT__030__M__1": "Şu direği görüyor musun? Üzerinde bir halat var. Ben kendi tarafımdan iterken sen oradan tekneyi çek! Yapabileceğini düşünüyor musun?",
"VO__ARNAUD__CH07__CHATTER__BOAT__070__M__1": "Hazır olduğunda...",
"VO__ARNAUD__CH07__CHATTER__BOAT_PULL_READY__020__M__1": "Güzel. Devam et!",
"VO__ARNAUD__CH07__CHATTER__BOAT_PULL_READY__040__M__1": "Ne?",
"VO__ARNAUD__CH07__CHATTER__BOLT_FIRE_REACT__030__M__1": "Tarif istemiyorum, sadece dayanmasını umuyorum!",
"VO__ARNAUD__CH07__CHATTER__CAVE_HALLWAY__020__M__1": "Evet. Bir kısayol.",
"VO__ARNAUD__CH07__CHATTER__CAVE_HALLWAY__040__M__1": "Hı, evet... Yani daha az asker. Ve elimizde çocuk var, değil mi?",
"VO__ARNAUD__CH07__CHATTER__CAVE_WRECK__020__M__1": "Öyle. Neredeyse vardık. İni şu teknenin diğer tarafında.",
"VO__ARNAUD__CH07__CHATTER__CAVE_WRECK__040__M__1": "Evet... Sophia. \"Deniz Akrebi\". Lider o.",
"VO__ARNAUD__CH07__CHATTER__CAVE_WRECK__060__M__1": "Şu lanet ısıranlardan daha az korkutucu.",
"VO__ARNAUD__CH07__CHATTER__CHANNEL__011__M__1": "İn tam sonda.",
"VO__ARNAUD__CH07__CHATTER__CHANNEL__047__M__1": "Haklı!",
"VO__ARNAUD__CH07__CHATTER__CHANNEL__065__M__1": "Neredeyse vardık... Daha sonra tartışamaz mısınız?",
"VO__ARNAUD__CH07__CHATTER__CHANNEL__090__M__1": "Yeter! Seni sonuna kadar taşırım, o kadar!",
"VO__ARNAUD__CH07__CHATTER__CHANNEL__092__M__1": "Güzel! İşte böyle!",
"VO__ARNAUD__CH07__CHATTER__CHANNEL__100__M__1": "Bu sana yeterince yüksek mi? Bak, suya değmiyorsun bile!",
"VO__ARNAUD__CH07__CHATTER__CHANNEL__120__M__1": "Şey, o kadar küçükken her gün kolay geçmez.",
"VO__ARNAUD__CH07__CHATTER__CHANNEL_FOWARD__010__M__1": "Hâlâ korkuyor musun?",
"VO__ARNAUD__CH07__CHATTER__CHANNEL_FOWARD__030__M__1": "İşte şimdi bana neden Duvar dediklerini anladın!",
"VO__ARNAUD__CH07__CHATTER__CHANNEL_FOWARD__050__M__1": "Aynen! Kimse beni geçemez.",
"VO__ARNAUD__CH07__CHATTER__CHANNEL_FOWARD__070__M__1": "Orada işler nasıl?",
"VO__ARNAUD__CH07__CHATTER__CHANNEL_OK__040__M__1": "Deniz Akrebi'yle tanışma vakti.",
"VO__ARNAUD__CH07__CHATTER__ENCOUNTER_1ST_PART__040__M__1": "Elbette. Yıllardır onların başına dert.",
"VO__ARNAUD__CH07__CHATTER__ENTER_CAVE__020__M__1": "İyi ilerliyoruz. Baş nasıl?",
"VO__ARNAUD__CH07__CHATTER__ENTER_CAVE__050__M__1": "Bana teşekkür et...",
"VO__ARNAUD__CH07__CHATTER__EPISANGUIS_BACK__030__M__1": "Nihayet!",
"VO__ARNAUD__CH07__CHATTER__EPISANGUIS_BACK__050__M__1": "Pekâlâ! Hazırım!",
"VO__ARNAUD__CH07__CHATTER__EPISANGUIS_BACK__060__M__1": "Senin işaretinle!",
"VO__ARNAUD__CH07__CHATTER__FIRST_CROSSING__010__M__1": "Gerçekten mi?! Hey ufaklık, sana itaat ediyorlar! Hepsini denize yolla işte!",
"VO__ARNAUD__CH07__CHATTER__FIRST_CROSSING__030__M__1": "Ah, harika...",
"VO__ARNAUD__CH07__CHATTER__FISHES__010__M__1": "Aç şerefsizler... Hı. Alınma, ufaklık...",
"VO__ARNAUD__CH07__CHATTER__GAP__030__M__1": "Atla! Seni yakalarım.",
"VO__ARNAUD__CH07__CHATTER__HUGO_SIGNALS__010__M__1": "Hey! O şey de ne? Onu adamlarıma karşı kullandın!",
"VO__ARNAUD__CH07__CHATTER__HUGO_SUPPORT__030__M__1": "Yapar. O iyidir.",
"VO__ARNAUD__CH07__CHATTER__IDLE_CAVE_1__020__M__1": "Bir avuç. Akdeniz'in dört bir yanından topladığı ayaktakımı. Sophia karanlıkta onların deniz feneri. Onu bir aziz gibi görüyorlar.",
"VO__ARNAUD__CH07__CHATTER__IDLE_CAVE_1__040__M__1": "Eyvah...",
"VO__ARNAUD__CH07__CHATTER__IDLE_CAVE_2__010__M__1": "Teknesinin adı \"la Rascasse\"—zehirli dikenleri olan yerel bir balık, deniz akrebi diye de bilinir, yani...",
"VO__ARNAUD__CH07__CHATTER__IDLE_CAVE_2__030__M__1": "Eminim sokabiliyordur da...",
"VO__ARNAUD__CH07__CHATTER__IDLE_CAVE_3__010__M__1": "Peki La Cuna'da ne arıyorsunuz?",
"VO__ARNAUD__CH07__CHATTER__IDLE_CAVE_3__040__M__1": "Şehirde kulaklarım vardı. Garnizonda bir karışıklık duydum. Bir kız ve bir oğlan?",
"VO__ARNAUD__CH07__CHATTER__IDLE_CAVE_3__060__M__1": "Güzel iş.",
"VO__ARNAUD__CH07__CHATTER__KILL_ARNAUD_REACT_1__010__M__1": "Epey keskin.",
"VO__ARNAUD__CH07__CHATTER__KILL_ARNAUD_REACT_1__030__M__1": "Yine de daha iyisini yapabilirsin.",
"VO__ARNAUD__CH07__CHATTER__KILL_ARNAUD_REACT_3__010__M__1": "Sana nasıl yaptığımı göstermek için sabırsızlanıyorum.",
"VO__ARNAUD__CH07__CHATTER__KILL_ARNAUD_REACT_3__030__M__1": "Hayır, ama bir zorunluluk olabilir.",
"VO__ARNAUD__CH07__CHATTER__KILL_RNO_RATS_1__010__M__1": "Öff... bu iğrenç...",
"VO__ARNAUD__CH07__CHATTER__KILL_RNO_RATS_1__030__M__1": "Ama etkili.",
"VO__ARNAUD__CH07__CHATTER__KILL_RNO_RATS_2__010__M__1": "Elinde ne korkunç bir silah var...",
"VO__ARNAUD__CH07__CHATTER__LA_RASCASSE__030__M__1": "Peki bu şeyi suya nasıl indireceğiz?",
"VO__ARNAUD__CH07__CHATTER__LA_RASCASSE__090__M__1": "Onu bana bırak!",
"VO__ARNAUD__CH07__CHATTER__LEDGE_FALL__010__M__1": "Ah, kahretsin!",
"VO__ARNAUD__CH07__CHATTER__LEDGE_FALL__040__M__1": "Peşimdeler! Işık lazım, çabuk!",
"VO__ARNAUD__CH07__CHATTER__LEDGE_FALL__060__M__1": "Hadi! Hadi!",
"VO__ARNAUD__CH07__CHATTER__LEDGE_NEST__002__M__1": "Lanet... O şey ne kadar büyük?!",
"VO__ARNAUD__CH07__CHATTER__LEDGE_NEST__020__M__1": "Bu şey hiç... görünmüyor...",
"VO__ARNAUD__CH07__CHATTER__LET_GO_OK__030__M__1": "Bizi... takip etmezler, değil mi?",
"VO__ARNAUD__CH07__CHATTER__MEETING_AGAIN__020__M__1": "Yüz savaşa girdim... ölümün gözünün içine de o kadar baktım... ama bu küçük pislikler... bana acemi bir er gibi hissettiriyor...",
"VO__ARNAUD__CH07__CHATTER__MEETING_AGAIN__040__M__1": "İyimserliğin koruyucu azizisin... Peki... bizi yürütecek başka numaran kaldı mı?",
"VO__ARNAUD__CH07__CHATTER__MEETING_AGAIN__060__M__1": "Hayır, hayır, buradan çıkıyoruz... Dur... Buldum.",
"VO__ARNAUD__CH07__CHATTER__MID_SECTION__020__M__1": "Pek değil. İyi ortak oluruz derim, ama iyi dost değil.",
"VO__ARNAUD__CH07__CHATTER__MID_SECTION__040__M__1": "Birlikte iyi çalışırız, ama bir süre sonra birbirimizi öldürmek isteriz.",
"VO__ARNAUD__CH07__CHATTER__MORE_RATS__030__M__1": "Ne?! Milyonlarca var!",
"VO__ARNAUD__CH07__CHATTER__MORE_RATS__050__M__1": "Harika.",
"VO__ARNAUD__CH07__CHATTER__NEGOCIATION__050__M__1": "Hey! Aşağıda sana ihtiyacım var!",
"VO__ARNAUD__CH07__CHATTER__NEST_CART__020__M__1": "Nedenini gerçekten anlamıyorum...",
"VO__ARNAUD__CH07__CHATTER__NEST_PUSH__030__M__1": "Hadi ama, çocuk bile korkuyor! Bundan emin misin?",
"VO__ARNAUD__CH07__CHATTER__NEST_PUSH__050__M__1": "Buna hazır değilim...",
"VO__ARNAUD__CH07__CHATTER__NEST_PUSH_ENTER__010__M__1": "Bu pis koku... O şey de ne? Tüylerimi diken diken ediyor...",
"VO__ARNAUD__CH07__CHATTER__NEST_PUSH_ENTER__040__M__1": "Aman be...",
"VO__ARNAUD__CH07__CHATTER__NEST_PUSH_ENTER__050__M__1": "Guyenne'de yaşadığını söyledin. Hepsi orada başladı! Sen...",
"VO__ARNAUD__CH07__CHATTER__NEST_PUSH_ENTER__070__M__1": "Bunu sen mi başlattın?!",
"VO__ARNAUD__CH07__CHATTER__NEST_PUSH_ENTER__090__M__1": "Bu hepimizin hak ettiği cehennem.",
"VO__ARNAUD__CH07__CHATTER__NEST_PUSH_ENTER__120__M__1": "Bu çılgınlık...",
"VO__ARNAUD__CH07__CHATTER__NEST_REVEAL__030__M__1": "Ne? O ne?!",
"VO__ARNAUD__CH07__CHATTER__NEST_REVEAL__050__M__1": "Sakın bana oraya gireceğimizi söyleme...",
"VO__ARNAUD__CH07__CHATTER__NEST_REVEAL__070__M__1": "Girmemeliyiz.",
"VO__ARNAUD__CH07__CHATTER__OBJECTIVE_HIDEOUT__020__M__1": "Şu meşale, aşağıda, enkazın yanında. Orada.",
"VO__ARNAUD__CH07__CHATTER__OBJECTIVE_HIDEOUT__040__M__1": "Umarım Sophia hâlâ oradadır...",
"VO__ARNAUD__CH07__CHATTER__OBJECTIVE_HIDEOUT__060__M__1": "Ah, o epey... öngörülemez biri...",
"VO__ARNAUD__CH07__CHATTER__ODORIS_BOLT_OK__020__M__1": "Ne zaman bırakacağımı söyle!",
"VO__ARNAUD__CH07__CHATTER__ODORIS_DONE__030__M__1": "Evet! Her neyse!",
"VO__ARNAUD__CH07__CHATTER__ODORIS_SUCCESS__020__M__1": "Evet! O neydi bilmiyorum ama paçamı kurtardın!",
"VO__ARNAUD__CH07__CHATTER__ODORIS_SUCCESS__060__M__1": "Fikrim yok! Deneyebiliriz...",
"VO__ARNAUD__CH07__CHATTER__ODORIS_USELESS__010__M__1": "Hı... O yemden emin misin?!",
"VO__ARNAUD__CH07__CHATTER__PLANK_LIFT__010__M__1": "İşine yarayacak bir şeye benziyor, değil mi? Şu arbalet sihrinle?!",
"VO__ARNAUD__CH07__CHATTER__PLANK_RELEASE__020__M__1": "Hem de nasıl yapacağım!",
"VO__ARNAUD__CH07__CHATTER__POST_FEATHER__010__M__1": "Burada onlara \"kahkaha martıları\" diyoruz.",
"VO__ARNAUD__CH07__CHATTER__POST_FEATHER__030__M__1": "Gördün mü? Sen de birine dönüşüyorsun...",
"VO__ARNAUD__CH07__CHATTER__PUSH_CHEST_ADD__010__M__1": "Demek... bütün bunları zaten gördün?",
"VO__ARNAUD__CH07__CHATTER__PUSH_CHEST_ADD__030__M__1": "Cehennem işte böyle görünüyor.",
"VO__ARNAUD__CH07__CHATTER__PUSH_CHEST_ADD__050__M__1": "Ben de gördüm... ama hiç böyle değil.",
"VO__ARNAUD__CH07__CHATTER__RAIN_VISTA__020__M__1": "Evet... bir sağanak fırtınası olmalı...",
"VO__ARNAUD__CH07__CHATTER__RAT_MOVE__040__M__1": "Pekâlâ, onlar... Sana gerçekten itaat ediyorlar. Bunu... Bunu nasıl yapıyorsun? Bunu nereden aldın?!",
"VO__ARNAUD__CH07__CHATTER__RATS_BELOW__010__M__1": "Lanet fareler... Onlara bir şey yapabilir misin?",
"VO__ARNAUD__CH07__CHATTER__RATS_FIRST_KILL__010__M__1": "Biliyor musun, bazıları seni yanlarında tutmak için bir servet öder, ufaklık...",
"VO__ARNAUD__CH07__CHATTER__RATS_FIRST_KILL__040__M__1": "Haklı.",
"VO__ARNAUD__CH07__CHATTER__RNO_CROSSING__010__M__1": "Ha, bu da ne?! Yerde yapışkan bir şey var!",
"VO__ARNAUD__CH07__CHATTER__RNO_CROSSING__018__M__1": "Şaka mı yapıyorsun?! Bu çizmeleri yakıyorum!",
"VO__ARNAUD__CH07__CHATTER__RNO_CROSSING__030__M__1": "Lanet... çürümüş... bok!",
"VO__ARNAUD__CH07__CHATTER__RNO_CROSSING_OK__010__M__1": "Buradayım!",
"VO__ARNAUD__CH07__CHATTER__SAILS_ORDER__070__M__1": "Hadi oraya çıkalım!",
"VO__ARNAUD__CH07__CHATTER__SAILS_START__010__M__1": "Ben iskele tarafını alırım.",
"VO__ARNAUD__CH07__CHATTER__SAILS_START__030__M__1": "Hazır olunca!",
"VO__ARNAUD__CH07__CHATTER__SAILS_STUCK__020__M__1": "Açılması gerekirdi!",
"VO__ARNAUD__CH07__CHATTER__SAILS_STUCK__070__M__1": "O zaman çözelim!",
"VO__ARNAUD__CH07__CHATTER__SAILS_STUCK__076__M__1": "Evet! Sancak iskelesine geç! Daha iyi bir açın olur!",
"VO__ARNAUD__CH07__CHATTER__SEAGULLS__020__M__1": "Öyle görünüyor... Ve bence hücum borusunu çalmalısın.",
"VO__ARNAUD__CH07__CHATTER__SEAGULLS__050__M__1": "Hadi asker! HÜCUM!",
"VO__ARNAUD__CH07__CHATTER__SEAGULLS__070__M__1": "Saflarımızda onun gibi daha çoğu olsaydı İngilizleri çoktan geri püskürtürdük.",
"VO__ARNAUD__CH07__CHATTER__SEAGULLS__090__M__1": "O zamanlar Guyenne'de bir şövalyeydim.",
"VO__ARNAUD__CH07__CHATTER__SEAGULLS__110__M__1": "Boşa gitti.",
"VO__ARNAUD__CH07__CHATTER__SHIELD_IDEA__010__M__1": "Alev oklarından birini kalkanıma at.",
"VO__ARNAUD__CH07__CHATTER__SHIELD_IDEA__040__M__1": "Umursar gibi bir hâli var mı?",
"VO__ARNAUD__CH07__CHATTER__SHIELD_QUICK_1__010__M__1": "Hey! Bu ateş yüzümü kavuruyor, acele edebilir misin?!",
"VO__ARNAUD__CH07__CHATTER__SHIELD_QUICK_2__010__M__1": "Amicia! Buraya... gelmen lazım... HEMEN!",
"VO__ARNAUD__CH07__CHATTER__SHIELD_RUN__010__M__1": "Bunu yapıyoruz! Sözüme kulak ver!",
"VO__ARNAUD__CH07__CHATTER__SHIELD_RUN__020__M__1": "Çekil yoldan!",
"VO__ARNAUD__CH07__CHATTER__SHIELD_RUN__040__M__1": "Şu korkakların deliklerine geri sürünmesine bak!... İşte böyle! Duvar'ın kudreti karşısında geri çekilin!",
"VO__ARNAUD__CH07__CHATTER__SHIELD_RUN__070__M__1": "Hem de nasıl, evet!... Ama kolum sanki alev almış gibi...",
"VO__ARNAUD__CH07__CHATTER__SHIELD_RUN__074__M__1": "Ve bu Duvar yeterince darbe yedi, ufaklık... Bedenim de kalkanım kadar hırpalanmış durumda.",
"VO__ARNAUD__CH07__CHATTER__SHIELD_RUN__078__M__1": "Savaş işte böyle...",
"VO__ARNAUD__CH07__CHATTER__SHIELD_RUN__090__M__1": "Ah dayanırım. Benim işim bu...",
"VO__ARNAUD__CH07__CHATTER__SHIELD_RUN_OK__010__M__1": "Pekâlâ, yeter!...",
"VO__ARNAUD__CH07__CHATTER__SHIELD_RUN_OK__030__M__1": "Öyle demezdim... Sadece iyi bir ter. Devam edelim.",
"VO__ARNAUD__CH07__CHATTER__SHIELD_SHOOT__010__M__1": "Onu hissettim... Güzel! Hazır olduğunda! Çabuk lütfen!",
"VO__ARNAUD__CH07__CHATTER__SMUGGLERS_HUNT__010__M__1": "Demiştim... Kont Provence'ı temizleme görevinde.",
"VO__ARNAUD__CH07__CHATTER__SOUVENIR_1__020__M__1": "Evet... Bu gövde yolculuklarında çok kum ve kaya öptü.",
"VO__ARNAUD__CH07__CHATTER__SOUVENIR_1__040__M__1": "Şey, ona yeni bir ad ver...",
"VO__ARNAUD__CH07__CHATTER__SOUVENIR_1__060__M__1": "Tabii! Neden olmasın? Bence hak ediyor.",
"VO__ARNAUD__CH07__CHATTER__SOUVENIR_1__090__M__1": "Şey... hiçbir şey tamamen gömülene kadar büsbütün ölmez.",
"VO__ARNAUD__CH07__CHATTER__SOUVENIR_CAVE__020__M__1": "Ah... bu eski... Çok eski...",
"VO__ARNAUD__CH07__CHATTER__SOUVENIR_CAVE__040__M__1": "Hayır... el izleri. Burada yaşamış ilk insanların... Romalılardan bile önce.",
"VO__ARNAUD__CH07__CHATTER__SOUVENIR_CAVE__060__M__1": "Devam etmeliyiz.",
"VO__ARNAUD__CH07__CHATTER__SQUIZZ_THROUGH__020__M__1": "Evet. Gizli insanlar için gizli bir yol.",
"VO__ARNAUD__CH07__CHATTER__STICK_CROSSING_1__020__M__1": "Burada sana güveniyorum...",
"VO__ARNAUD__CH07__CHATTER__STICK_CROSSING_1__040__M__1": "Pardon, şu an rahatlamak epey zor...",
"VO__ARNAUD__CH07__CHATTER__STICK_CROSSING_1__060__M__1": "Şey, hâline imrenmiyorum...",
"VO__ARNAUD__CH07__CHATTER__STICK_CROSSING_OK__020__M__1": "Aradığım kelime buydu işte...",
"VO__ARNAUD__CH07__CHATTER__STICK_CROSSING_OK__040__M__1": "Kimse imrenmez, ufaklık.",
"VO__ARNAUD__CH07__CHATTER__STICK_GRAB__020__M__1": "O minik çubuk mu?",
"VO__ARNAUD__CH07__CHATTER__THE_SEA__030__M__1": "Adana ulaşacağız. La Cuna güzel, güneşli bir yer.",
"VO__ARNAUD__CH07__CHATTER__TO_THE_BEACH__010__M__1": "Hafif değilsin... Ablan seni iyi besliyor...",
"VO__ARNAUD__CH07__CHATTER__TO_THE_BEACH__040__M__1": "Asıl koşan o! Yavaşla, ufaklık! Yaralımız var!",
"VO__ARNAUD__CH07__CHATTER__TORCH_OK__030__M__1": "Lanet... pislikler!",
"VO__ARNAUD__CH07__CHATTER__TORCH_OK__050__M__1": "İyiyim! Tek sorun sıkıştım ve bana sanki bir parça kızarmış etmişim gibi bakıyorlar!",
"VO__ARNAUD__CH07__CHATTER__UNEXPECTED_FOES__050__M__1": "Eğilik kal.",
"VO__ARNAUD__CH07__CHATTER__UNEXPECTED_FOES__080__M__1": "Evet, askerler. Onlardan kurtulurum.",
"VO__ARNAUD__CH07__CHATTER__UNEXPECTED_FOES__100__M__1": "Hâlâ bana güvenmiyorsun, ha? Devam et o zaman, izliyorum.",
"VO__ARNAUD__CH07__CHATTER__UNEXPECTED_RATS__010__M__1": "Bu da ne be?!",
"VO__ARNAUD__CH07__CHATTER__UNEXPECTED_RATS__030__M__1": "Ah kahretsin! KAHRETSİN!",
"VO__ARNAUD__CH07__CHATTER__UNEXPECTED_RATS__060__M__1": "Az kalsın beni yiyorlardı! Sen hastasın, lanet olsun!",
"VO__ARNAUD__CH07__CHATTER__UPPER_HOUSE__010__M__1": "Şu askerler rezalet.",
"VO__ARNAUD__CH07__CHATTER__UPPER_HOUSE__030__M__1": "Paralı askerler işte böyledir.",
"VO__ARNAUD__CH07__CHATTER__USE_HAM__020__M__1": "Güzel atış!",
"VO__ARNAUD__CH07__CHATTER__VILLAGE_ENTRANCE__060__M__1": "Devam edelim.",
"VO__ARNAUD__CH07__CHATTER__VISTA_BOAT__010__M__1": "Pekâlâ, bak... Mağaralar şurada devam ediyor. Yolumuz orası.",
"VO__ARNAUD__CH07__CHATTER__VISTA_BOAT__040__M__1": "Evet, şey, o farelerle... Bence dışarı geri dönelim.",
"VO__ARNAUD__CH07__CHATTER__VISTA_BOAT__060__M__1": "Sağ çıktığımız sürece...",
"VO__ARNAUD__CH07__CHATTER__VISTA_LIGHTHOUSE_FAR__010__M__1": "Işığı görüyor musun? Balıkçı köyünün deniz feneri. Sophia'nın teknesi orada.",
"VO__ARNAUD__CH07__CHATTER__WONT_GET_HER__010__M__1": "Ah, o askerler onun için fazla aptal...",
"VO__ARNAUD__CH07__CHATTER__WONT_GET_HER__030__M__1": "Endişelenmeyi kes. O Deniz Akrebi. Asıl baş belası o.",
"VO__ARNAUD__CH07__CHATTER__WRECK_SECRET__020__M__1": "Buralarda akıntılar epey çetrefilli.",
"VO__ARNAUD__CH07__HELPER__ANCHOR_CRANK_1__010__M__1": "Şu krankta yardım lazım mı?",
"VO__ARNAUD__CH07__HELPER__ANCHOR_CRANK_2__010__M__1": "Zinciri kaldırmayı bana bıraksan.",
"VO__ARNAUD__CH07__HELPER__ANCHOR_FREE_2__010__M__1": "Hadi! Şu çapayı kaldırmama yardım et!",
"VO__ARNAUD__CH07__HELPER__ANCHOR_PULL_REMINDER_1__010__M__1": "Hadi, hayal kurmayı kes de buraya gel!",
"VO__ARNAUD__CH07__HELPER__ANCHOR_PULL_REMINDER_2__010__M__1": "Şu krankta bana yardım edecek misin etmeyecek misin?!",
"VO__ARNAUD__CH07__HELPER__ANCHOR_RELEASED_ARNAUD_1__010__M__1": "Neyi bekliyorsun?!",
"VO__ARNAUD__CH07__HELPER__ANCHOR_RELEASED_ARNAUD_2__010__M__1": "Hadi! Kır şu zinciri!",
"VO__ARNAUD__CH07__HELPER__RAT_MOVE_1__010__M__1": "Hey, fareler çocuğun işi, değil mi? Buna bir şey yapamaz mısın?",
"VO__ARNAUD__CH07__HELPER__TRADPOOR_1__010__M__1": "Şu lanet balık kapakta sıkışmış!",
"VO__ARNAUD__CH07__HELPER__TRADPOOR_2__010__M__1": "Hey! Şu kilit kapağı kapalı tutuyor! Kır onu!",
"VO__ARNAUD__CH07__HELPER__USE_HAM_BOAT_1__010__M__1": "Amicia! Şu fareleri oyalayabilirsin, değil mi? Yani... senin işin bu.",
"VO__ARNAUD__CH07__HELPER__USE_HAM_BOAT_2__010__M__1": "Hey! Şu balık! İyi bir açı bulursan sapanınla onu indirebilirsin!",
"VO__ARNAUD__CH07__RTC__280_SCAR__060__M__1": "Çünkü çıkamadın...",
"VO__ARNAUD__CH07__RTC__280_SCAR__080__M__1": "Hı... Anladım.",
"VO__ARNAUD__CH07__RTC__280_SCAR__105__M__1": "Uzak değil. Atları serbest bırakacağım. Son kısmı güvenli bir yoldan yürüyerek gideceğiz.",
"VO__ARNAUD__CH07__RTC__280_SCAR__112__M__1": "Sadece çabuk bir kontrol. İzin var mı?...",
"VO__ARNAUD__CH07__RTC__280_SCAR__115__M__1": "İki gün oldu... yani...",
"VO__ARNAUD__CH07__RTC__280_SCAR__120__M__1": "Güzel. İyileştin. Bir nevi. Bundan sonra bırak nefes alsın yeter.",
"VO__ARNAUD__CH07__RTC__280_SCAR__130__M__1": "Zaman zaman acıyacak. Sadece nefes al ve rahatla.",
"VO__ARNAUD__CH07__RTC__280_SCAR__150__M__1": "Bu kadar sert görünmeye çalışmayı bırak. Bir şey öğrenebilirsin.",
"VO__ARNAUD__CH07__RTC__280_SCAR__190__M__1": "Kont'un ordusu bizimle—\"Provence'ın ayaktakımı\"yla—savaş hâlinde. Adamlarımın çoğu... dostlarım... öldürüldü ya da kaçtı. Beni yakalamaları an meselesi.",
"VO__ARNAUD__CH07__RTC__280_SCAR__210__M__1": "Evet. İlmik şimdiden boynumda ama... sende benimde olmayan bir şey var.",
"VO__ARNAUD__CH07__RTC__280_SCAR__230__M__1": "En çok aranan adam için bu beladan en güvenli çıkış yolu. Adanın nerede olduğunu biliyorum. Tek yapman gereken oraya varana dek beni hayatta tutmak.",
"VO__ARNAUD__CH07__RTC__290_TRANSPORT__020__M__1": "Gidelim. Buraya manzaranın tadını çıkarmaya gelmedik.",
"VO__ARNAUD__CH07__RTC__290_TRANSPORT__040__M__1": "Tekneni almaya. Birini tanıyorum.",
"VO__ARNAUD__CH07__RTC__290_TRANSPORT__060__M__1": "Bir kaçakçı. Gözden uzak bir gemi. Hızlı. İhtiyacın olan şey.",
"VO__ARNAUD__CH07__RTC__290_TRANSPORT__080__M__1": "Evet. Alış buna. Artık hayatın bu. Yani çıkardığın onca karışıklıktan sonra La Cuna'ya gitmek istiyorsan, ya bu tekne ya da on millik lanet bir yüzüş.",
"VO__ARNAUD__CH07__RTC__290_TRANSPORT__100__M__1": "Ah, gördün mü? İşte doğru tavır bu...",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__003__M__1": "Liderlik etmeyi sevdiğini biliyorum, ama önce ben geçsem iyi olur.",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__010__M__1": "Benim, lanet olsun...",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__055__M__1": "Yardım aldım.",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__080__M__1": "Bunlar Amicia ve Hugo. Küçük olanda potansiyel var. Abla... daha terbiye edilmesi gerekiyor...",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__100__M__1": "Gördün mü?",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__140__M__1": "Teknen. La Cuna'ya gitmemiz gerek. Soru sorulmadan.",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__160__M__1": "O zaman yalnız gel. Sophia, bana borçlusun.",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__180__M__1": "Devam et...",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__200__M__1": "Anlaştık.",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__220__M__1": "Ah! \"Denizin Çağrısı\", ha?",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__250__M__1": "Tabii.",
"VO__ARNAUD__CH07__RTC__300_SMUGGLER__260__M__1": "Gidelim.",
"VO__ARNAUD__CH07__RTC__302_WAITING_FOR_SOPHIA__020__M__1": "Evet... İdare eder.",
"VO__ARNAUD__CH07__RTC__302_WAITING_FOR_SOPHIA__050__M__1": "Onu ben alabilirim. Sen biraz dinlen.",
"VO__ARNAUD__CH07__RTC__302_WAITING_FOR_SOPHIA__060__M__1": "Bir şey olmaz.",
"VO__ARNAUD__CH07__RTC__302_WAITING_FOR_SOPHIA__070__M__1": "Hemen şurada olacağız.",
"VO__ARNAUD__CH07__RTC__302_WAITING_FOR_SOPHIA__110__M__1": "O böyle şeyler söyleyince bu kadar sevinme...",
"VO__ARNAUD__CH07__RTC__310_SET_SAIL__030__M__1": "Hava atan...",
"VO__ARNAUD__CH07__RTC__310_SET_SAIL__070__M__1": "Hey, nereye gidiyorsun denizci? Bu ailede hepinizde mi ölüm arzusu var?",
"VO__ARNAUD__CH07__RTC__310_SET_SAIL__080__M__1": "Sorun yok. Tuttum seni.",
"VO__HUGO__CH07__CHATTER__ABOUT_ARNAUD_SKILLS__060__M__1": "Hem kılıcı hem sapanı severim!",
"VO__HUGO__CH07__CHATTER__ABOUT_LAST_SOLDIER__010__M__1": "Tekne bu kadar yakından çok büyük görünüyor!",
"VO__HUGO__CH07__CHATTER__ABOUT_RATS_KILL__060__M__1": "Amicia'yı öldürmek istedin...",
"VO__HUGO__CH07__CHATTER__ABOUT_SOPHIA__030__M__1": "Bir teknem olsa buradan çok uzağa giderdim.",
"VO__HUGO__CH07__CHATTER__AFTER_LEDGE_2__010__M__1": "Yağmur şiddetleniyor!",
"VO__HUGO__CH07__CHATTER__ARNAUD_FIGHT__020__M__1": "Vaay...",
"VO__HUGO__CH07__CHATTER__BEACH_2_START__010__M__1": "Kalkanın çok mu bozuk?",
"VO__HUGO__CH07__CHATTER__BEACH_2_START__030__M__1": "Bayıldım ona!",
"VO__HUGO__CH07__CHATTER__BOAT_IN_POSITION__010__M__1": "Sana yardım edeceğim, Amicia!",
"VO__HUGO__CH07__CHATTER__BOAT_PULL_READY__030__M__1": "Arnaud!",
"VO__HUGO__CH07__CHATTER__BOAT_PULL_READY__050__M__1": "Geri çekil!",
"VO__HUGO__CH07__CHATTER__CAVE_WRECK__010__M__1": "Ohhh... Büyük enkaz bu mu?",
"VO__HUGO__CH07__CHATTER__CAVE_WRECK__050__M__1": "Kulağa korkutucu geliyor.",
"VO__HUGO__CH07__CHATTER__CHANNEL__020__M__1": "Hayır...",
"VO__HUGO__CH07__CHATTER__CHANNEL__043__M__1": "Hayır! Dalgalardan korkuyorum!",
"VO__HUGO__CH07__CHATTER__CHANNEL__048__M__1": "Ama derin!",
"VO__HUGO__CH07__CHATTER__CHANNEL__060__M__1": "Ama dalgalar var!",
"VO__HUGO__CH07__CHATTER__CHANNEL__080__M__1": "Korkuyorum!",
"VO__HUGO__CH07__CHATTER__CHANNEL__091__M__1": "Peki.",
"VO__HUGO__CH07__CHATTER__CHANNEL__110__M__1": "Evet...",
"VO__HUGO__CH07__CHATTER__CHANNEL_FOWARD__020__M__1": "Hayır...",
"VO__HUGO__CH07__CHATTER__CHANNEL_FOWARD__040__M__1": "Çünkü... bir kale gibisin?",
"VO__HUGO__CH07__CHATTER__CHANNEL_FOWARD__060__M__1": "Ve kalkanın da bir duvara benziyor!",
"VO__HUGO__CH07__CHATTER__CHANNEL_OK__030__M__1": "Evet, teşekkürler!",
"VO__HUGO__CH07__CHATTER__EMBUSH__010__M__1": "Yaaah! Bütün paranı ver bana!",
"VO__HUGO__CH07__CHATTER__EMBUSH__030__M__1": "Beni asla canlı yakalayamazsın!",
"VO__HUGO__CH07__CHATTER__ENCOUNTER_1ST_PART__050__M__1": "Çünkü sokuyor...",
"VO__HUGO__CH07__CHATTER__ENTER_CAVE__040__M__1": "Yeni saçını sevdim...",
"VO__HUGO__CH07__CHATTER__EPISANGUIS_BACK__010__M__1": "Amicia, bak! Sarı kristaller! Bu Episanguis!",
"VO__HUGO__CH07__CHATTER__FEATHER_GRAB__020__M__1": "Bir martı mı?!",
"VO__HUGO__CH07__CHATTER__FEATHER_GRAB__040__M__1": "Martılara bayılırım...",
"VO__HUGO__CH07__CHATTER__FIRST_CROSSING__020__M__1": "Aynı anda sadece birkaçını kontrol edebiliyorum...",
"VO__HUGO__CH07__CHATTER__FISHERMAN_DOOR__020__M__1": "Burada biri mi yaşıyor?",
"VO__HUGO__CH07__CHATTER__FISHERMAN_DOOR__040__M__1": "Ben burada yaşardım! Tam denizin önünde...",
"VO__HUGO__CH07__CHATTER__GAP__010__M__1": "Çok yüksek...",
"VO__HUGO__CH07__CHATTER__GAP__041__M__1": "Vuuh!",
"VO__HUGO__CH07__CHATTER__GAP__050__M__1": "Teşekkürler!",
"VO__HUGO__CH07__CHATTER__HUGO_CABIN__020__M__1": "Harika! Bu tekne harika! Şu kamara da harika! Şu eşyalara bak!",
"VO__HUGO__CH07__CHATTER__HUGO_SIGNALS__010__M__1": "Amicia! Geldik!",
"VO__HUGO__CH07__CHATTER__HUGO_SOPHIA_CABIN__010__M__1": "Ne yapıyorsun?",
"VO__HUGO__CH07__CHATTER__HUGO_SOPHIA_CABIN__030__M__1": "Bence onlar da alçak.",
"VO__HUGO__CH07__CHATTER__HUGO_SOPHIA_CABIN__050__M__1": "Evet, kaptan.",
"VO__HUGO__CH07__CHATTER__HUGO_SUPPORT__010__M__1": "Yapabilirsin, Amicia!",
"VO__HUGO__CH07__CHATTER__IDLE_CAVE_2__005__M__1": "Sophia'ya insanları soktuğu için mi deniz akrebi diyorlar?",
"VO__HUGO__CH07__CHATTER__IDLE_CAVE_2__020__M__1": "Ah...",
"VO__HUGO__CH07__CHATTER__IDLE_CAVE_3__020__M__1": "Bir kuş!",
"VO__HUGO__CH07__CHATTER__LA_RASCASSE__020__M__1": "Buradayım! İnanılmaz!",
"VO__HUGO__CH07__CHATTER__LA_RASCASSE__027__M__1": "Evet! Kamaraya!",
"VO__HUGO__CH07__CHATTER__LEDGE_FALL__020__M__1": "Arnaud!",
"VO__HUGO__CH07__CHATTER__LEDGE_NEST__006__M__1": "Çok büyük olabilir...",
"VO__HUGO__CH07__CHATTER__LET_GO_OK__010__M__1": "Tamam!",
"VO__HUGO__CH07__CHATTER__MEETING_AGAIN__030__M__1": "Artık eğitimlisin!",
"VO__HUGO__CH07__CHATTER__MID_SECTION__010__M__1": "Sophia senin en iyi arkadaşın mı?",
"VO__HUGO__CH07__CHATTER__MID_SECTION__030__M__1": "Bu ne demek?",
"VO__HUGO__CH07__CHATTER__MORE_RATS__020__M__1": "Eyvah...",
"VO__HUGO__CH07__CHATTER__MORE_RATS__060__M__1": "Korkma.",
"VO__HUGO__CH07__CHATTER__NEGOCIATION__020__M__1": "Ne?! Neden?!",
"VO__HUGO__CH07__CHATTER__NEGOCIATION__040__M__1": "Sen de öylesin! Ve ben daha da tehlikeliyim... Ama ona ihtiyacımız var.",
"VO__HUGO__CH07__CHATTER__NEST_CART_NO_LIGHTS__010__M__1": "Amicia, dur! Ateşsiz gitmemeliyiz...",
"VO__HUGO__CH07__CHATTER__NEST_PUSH__020__M__1": "Korkunç olacak, Amicia...",
"VO__HUGO__CH07__CHATTER__NEST_PUSH_ENTER__030__M__1": "Tıpkı... insan gibi.",
"VO__HUGO__CH07__CHATTER__NEST_PUSH_ENTER__060__M__1": "Bilerek yapmadım!",
"VO__HUGO__CH07__CHATTER__NEST_PUSH_ENTER__100__M__1": "Durmasını istiyorum...",
"VO__HUGO__CH07__CHATTER__NEST_REVEAL__010__M__1": "Ah...",
"VO__HUGO__CH07__CHATTER__ODORIS_SUCCESS__010__M__1": "İşe yarıyor!",
"VO__HUGO__CH07__CHATTER__ODORIS_USELESS__020__M__1": "Haklı, yer tuhaf görünüyor!",
"VO__HUGO__CH07__CHATTER__PERMISSION__010__M__1": "Amicia, gidiyor muyuz?",
"VO__HUGO__CH07__CHATTER__PERMISSION__030__M__1": "Evet kaptan!",
"VO__HUGO__CH07__CHATTER__PLANK_RELEASE__010__M__1": "Koş, Arnaud!",
"VO__HUGO__CH07__CHATTER__POST_FEATHER__020__M__1": "Ne?!",
"VO__HUGO__CH07__CHATTER__PUSH_CHEST_ADD__020__M__1": "Evet. İlk evimiz onunla kaplıydı.",
"VO__HUGO__CH07__CHATTER__RAIN_VISTA__010__M__1": "Ah... Çok yağıyor...",
"VO__HUGO__CH07__CHATTER__RAT_MOVE__030__M__1": "Evet...",
"VO__HUGO__CH07__CHATTER__RATS_FIRST_KILL__020__M__1": "Gerçekten mi?",
"VO__HUGO__CH07__CHATTER__REACH_DROP__020__M__1": "Akrep olmasından korkuyorum...",
"VO__HUGO__CH07__CHATTER__RESUME_RUN__020__M__1": "Ve ben korkaklarla konuşmam!",
"VO__HUGO__CH07__CHATTER__RNO_CROSSING__016__M__1": "Merak etme! Tehlikeli değil!",
"VO__HUGO__CH07__CHATTER__SAILS_ORDER__040__M__1": "Emredersiniz kaptan!",
"VO__HUGO__CH07__CHATTER__SEAGULLS__010__M__1": "Vay... O kadar çoklar ki! Bir... kuş ordusu mu?",
"VO__HUGO__CH07__CHATTER__SEAGULLS__030__M__1": "Yapabilir miyim, Amicia?!",
"VO__HUGO__CH07__CHATTER__SEAGULLS__060__M__1": "HÜCUUUM!",
"VO__HUGO__CH07__CHATTER__SHIELD_RUN__030__M__1": "Evet! Kışt!",
"VO__HUGO__CH07__CHATTER__SHIELD_RUN__060__M__1": "Evet! Artık senden korkuyorlar!",
"VO__HUGO__CH07__CHATTER__SHIELD_RUN__072__M__1": "Ama sen Duvar'sın!",
"VO__HUGO__CH07__CHATTER__SHIELD_RUN__076__M__1": "İğrenç...",
"VO__HUGO__CH07__CHATTER__SMELL_THE_SEA__010__M__1": "Sen koklamıyor musun?!",
"VO__HUGO__CH07__CHATTER__SMELL_THE_SEA__030__M__1": "Hayır! Yosun gibi kokuyor! Hadi!",
"VO__HUGO__CH07__CHATTER__SMELL_THE_SEA__050__M__1": "Şimdi olmaz! Deniz tam şurada!",
"VO__HUGO__CH07__CHATTER__SOUVENIR_1__010__M__1": "Bak, adı buradaymış! Okuyamıyoruz...",
"VO__HUGO__CH07__CHATTER__SOUVENIR_1__030__M__1": "Düşünsene, adını kaybetmek...",
"VO__HUGO__CH07__CHATTER__SOUVENIR_1__050__M__1": "Yapabilir miyim?",
"VO__HUGO__CH07__CHATTER__SOUVENIR_1__070__M__1": "Adını... \"Hayatta Kalan\" koyuyorum!",
"VO__HUGO__CH07__CHATTER__SOUVENIR_CAVE__030__M__1": "Bir çizim mi?",
"VO__HUGO__CH07__CHATTER__SOUVENIR_CAVE__050__M__1": "İlk insanlar...",
"VO__HUGO__CH07__CHATTER__SOUVENIR_CAVE__080__M__1": "Çok güzel.",
"VO__HUGO__CH07__CHATTER__SOUVENIR_CAVE__100__M__1": "İçimden ağlamak geliyor... ama nedenini bilmiyorum.",
"VO__HUGO__CH07__CHATTER__SOUVENIR_CAVE__120__M__1": "Evet.",
"VO__HUGO__CH07__CHATTER__STICK_CROSSING_1__050__M__1": "Bunu çok yaptık!",
"VO__HUGO__CH07__CHATTER__STICK_CROSSING_OK__030__M__1": "Fareleri gerçekten sevmiyorsun...",
"VO__HUGO__CH07__CHATTER__THE_SEA__010__M__1": "Şu dalgalar korkutucu...",
"VO__HUGO__CH07__CHATTER__THE_SEA__040__M__1": "Evet... Sabırsızlanıyorum...",
"VO__HUGO__CH07__CHATTER__TO_PONTOON__010__M__1": "Neler oluyor?!",
"VO__HUGO__CH07__CHATTER__TO_PONTOON__030__M__1": "La Cuna! Gerçekten La Cuna'ya gidiyoruz!",
"VO__HUGO__CH07__CHATTER__TO_THE_BEACH__020__M__1": "Yemek yemeye bayılırım! Hey, şuraya bak!",
"VO__HUGO__CH07__CHATTER__TORCH_OK__020__M__1": "Evet!",
"VO__HUGO__CH07__CHATTER__UNEXPECTED_FOES__010__M__1": "Vaay... Büyük bir tekne...",
"VO__HUGO__CH07__CHATTER__UNEXPECTED_FOES__060__M__1": "Askerler mi?",
"VO__HUGO__CH07__CHATTER__UNEXPECTED_RATS__050__M__1": "Evet!",
"VO__HUGO__CH07__CHATTER__UNEXPECTED_RATS__110__M__1": "Onları hareket ettirebilir miyim?",
"VO__HUGO__CH07__CHATTER__UNEXPECTED_RATS__112__M__1": "Aynı şey değil! Yapabilirim!",
"VO__HUGO__CH07__CHATTER__UPPER_HOUSE__040__M__1": "Hmmm...",
"VO__HUGO__CH07__CHATTER__VICTORIOUS__010__M__1": "Hey! Hücumumu gördün mü?",
"VO__HUGO__CH07__CHATTER__VICTORIOUS__030__M__1": "Asker olabilirim!",
"VO__HUGO__CH07__CHATTER__VILLAGE_ENTRANCE__050__M__1": "Rascasse... Komik bir ad...",
"VO__HUGO__CH07__CHATTER__WAITING__010__M__1": "Amicia! Ne yapıyorsun?!",
"VO__HUGO__CH07__CHATTER__WAITING__020__M__1": "Hadi! Amicia! Sana göstereceğim bir şey var!",
"VO__HUGO__CH07__HELPER__ODORIS_BOLT__010__M__1": "Amicia, bu kalası arbaletinle vurabilirsin! Belki Odoris ile işe yarar...?",
"VO__HUGO__CH07__HELPER__ODORIS_BOLT__020__M__1": "Amicia! Şu kalas... Belki ona bir Odoris oku atabilirsin?",
"VO__HUGO__CH07__HELPER__RAT_MOVE_2__010__M__1": "Amicia! Fareleri uzaklaştırabilirim! Şurada balıklar var! Onları severler!",
"VO__HUGO__CH07__RTC__280_SCAR__010__M__1": "Uyandın! O seni kurtardı! Bizi adaya götüreceğini söylüyor! Nerede olduğunu biliyor ve adının La Cuna olduğunu söylüyor!",
"VO__HUGO__CH07__RTC__280_SCAR__030__M__1": "Bir tekne de bulacak!",
"VO__HUGO__CH07__RTC__280_SCAR__047__M__1": "Amicia!",
"VO__HUGO__CH07__RTC__280_SCAR__050__M__1": "Ve evimizde bir köpeğimiz vardı, ama onu pek görmüyordum...",
"VO__HUGO__CH07__RTC__280_SCAR__070__M__1": "Evet. Bu yüzden onunla oynadığımı hayal ederdim.",
"VO__HUGO__CH07__RTC__280_SCAR__090__M__1": "Demek geldik? Tekne nerede? Nerede o? Umarım koocamandır!",
"VO__HUGO__CH07__RTC__280_SCAR__110__M__1": "Martılar!",
"VO__HUGO__CH07__RTC__280_SCAR__240__M__1": "Amicia! Gel! GEL DE GÖR!",
"VO__HUGO__CH07__RTC__290_TRANSPORT__090__M__1": "Bir tekneye binmek için sabırsızlanıyorum.",
"VO__HUGO__CH07__RTC__302_WAITING_FOR_SOPHIA__030__M__1": "İşte orada! Amicia! Sophia olmadan da görmeye gidebilir miyiz?",
"VO__HUGO__CH07__RTC__302_WAITING_FOR_SOPHIA__100__M__1": "Evet!",
"VO__HUGO__CH07__RTC__310_SET_SAIL__020__M__1": "Amicia! Çabuk!",
"VO__HUGO__CH07__RTC__310_SET_SAIL__040__M__1": "Amicia, yelken açıyoruz!",
"VO__HUGO__CH07__RTC__310_SET_SAIL__050__M__1": "Denizdeyiz! Gerçekten!",
"VO__HUGO__CH07__RTC__310_SET_SAIL__060__M__1": "VUUU! Ben bir korsanım!",
"VO__HUGO__CH07__RTC__310_SET_SAIL__090__M__1": "LA CUNA'YA!",
"VO__PEOPLE_M1__CH07__RTC__300_SMUGGLER__270__M__1": "Demek... yine her şeyi bırakacağın yılın o vakti geldi?",
"VO__PEOPLE_M2__CH07__RTC__300_SMUGGLER__290__M__1": "Tabii... Her zamanki gibi beştaş oynayıp dönmeni bekleriz.",
"VO__SOLDIER_N1__CH07__CHATTER__CAVE_SOLDIERS__010__M__1": "Kaçakçılar neden umurumuzda olsun ki? O fareler binlerce kişiyi öldürüyor!",
"VO__SOLDIER_N1__CH07__CHATTER__ENCOUNTER_1ST_PART__010__M__1": "Lanet yağmur! Tam isabet... Hiçbir kaçakçı bu havada dışarı çıkmaz! Sırılsıklam olan bir tek biziz.",
"VO__SOLDIER_N1__CH07__CHATTER__INSIDE_HOUSE__010__M__1": "Marangozlukta kalsaydım... Bol iş, kolay ve sıcak... Ama hayır... Macera dolu bir hayat istedim... Ama lanet fareler mi? Hayır, efendim... Hayır...",
"VO__SOLDIER_N1__CH07__RTC__303_SAVING_SOPHIA__020__M__1": "Yakaladım seni!",
"VO__SOLDIER_N1__CH07__RTC__303_SAVING_SOPHIA__040__M__1": "Kaçacak yerin yok! Ve Kont seni canlı istemiyor!",
"VO__SOLDIER_N2__CH07__CHATTER__ABOUT_STORM__020__M__1": "Suratına bir tane patlatacakmış gibi hissediyorum!",
"VO__SOLDIER_N2__CH07__CHATTER__ABOUT_STORM__040__M__1": "Defol!",
"VO__SOLDIER_N2__CH07__CHATTER__UNEXPECTED_FOES__040__M__1": "Hiçbir şey! O farelerle burada hâlâ insan olduğundan emin misin?",
"VO__SOLDIER_N3__CH07__CHATTER__ARNAUD_MOVES__020__M__1": "Hey, kimsin sen?! Buraya gel!",
"VO__SOLDIER_N3__CH07__CHATTER__ARNAUD_MOVES__060__M__1": "Hey! Dur!",
"VO__SOLDIER_N3__CH07__CHATTER__CAVE_SOLDIERS__020__M__1": "Kont'un bunun ne kadar ciddi olduğunu bildiğinden bile emin değilim...",
"VO__SOLDIER_N3__CH07__CHATTER__ENCOUNTER_1ST_PART__020__M__1": "Kapa çeneni... Deniz Akrebi kaçmak için yağmuru kullanabilir!",
"VO__SOLDIER_S1__CH07__CHATTER__UNEXPECTED_FOES__020__M__1": "HEY! İz buldun mu?!",
"VO__SOLDIER_S1__CH07__CHATTER__UNEXPECTED_FOES__070__M__1": "Etrafına bak, burası lanet bir labirent! Dinle, bir iki ölü kaçakçı getirirsek Kont bize nişan takar!",
"VO__SOLDIER_S1__CH07__CHATTER__VILLAGE_ENTRANCE__010__M__1": "Sana diyorum, uğursuzluk bu!",
"VO__SOLDIER_S1__CH07__CHATTER__VILLAGE_ENTRANCE__030__M__1": "Adı la Rascasse! O balık uğursuzdur!",
"VO__SOLDIER_S2__CH07__CHATTER__ABOUT_STORM__010__M__1": "Hey! Peşinden gelen epey bir maiyetin var! Kendini ne kadar kraliyetten hissediyorsun?",
"VO__SOLDIER_S2__CH07__CHATTER__ABOUT_STORM__030__M__1": "Ah hadi ama, bir kez olsun aşkı bulmuşsun! Tadını çıkar!",
"VO__SOLDIER_S2__CH07__CHATTER__VILLAGE_ENTRANCE__020__M__1": "Sadece bir tekne...",
"VO__SOLDIER_S2__CH07__CHATTER__VILLAGE_ENTRANCE__040__M__1": "Seninle her şey uğursuz! Hadi, devriyeye devam et ve kıçını kolla!",
"VO__SOPHIA__CH07__CHATTER__ANCHOR_ISSUE__030__M__1": "Ha, alçaklar! Krankın olduğu şu iskeleye git! Zinciri o kumanda ediyor!",
"VO__SOPHIA__CH07__CHATTER__BOAT_PONTOON__020__M__1": "Bir tek o! Umarım onu mahvetmemişlerdir.",
"VO__SOPHIA__CH07__CHATTER__HUGO_SOPHIA_CABIN__020__M__1": "O alçakların... Kötü adamların... yaptığını onarmaya çalışıyorum.",
"VO__SOPHIA__CH07__CHATTER__HUGO_SOPHIA_CABIN__040__M__1": "Şşş! O kötü bir kelime. Doğru ama kötü. Anladın mı?",
"VO__SOPHIA__CH07__CHATTER__HUGO_SUPPORT__020__M__1": "Lütfen, tekneme zarar verme!",
"VO__SOPHIA__CH07__CHATTER__LA_RASCASSE__080__M__1": "Ben La Cuna'ya giden rotayı kontrol ederken sen Amicia'yla çapayı kaldır!",
"VO__SOPHIA__CH07__CHATTER__LA_RASCASSE__082__M__1": "Pruvadaki krank!",
"VO__SOPHIA__CH07__CHATTER__SAILS_ORDER__009__M__1": "Hey! Yaptın mı?!",
"VO__SOPHIA__CH07__CHATTER__SAILS_ORDER__020__M__1": "Harika! Şimdi birlikte ana yelkeni açın! Üst güvertede!",
"VO__SOPHIA__CH07__CHATTER__SAILS_STUCK__040__M__1": "Şimdi ne var?!",
"VO__SOPHIA__CH07__CHATTER__SAILS_STUCK__050__M__1": "Kahretsin! O şerefsizler yelkenimi mi bağlamış?!",
"VO__SOPHIA__CH07__CHATTER__SAILS_STUCK__072__M__1": "Oraya çıkacak vaktimiz yok!",
"VO__SOPHIA__CH07__CHATTER__SAILS_STUCK__075__M__1": "Evet! Sancak iskelesine geç! Daha iyi bir açın olur!",
"VO__SOPHIA__CH07__CHATTER__SAILS_STUCK__080__M__1": "Sadece yelkene zarar verme!",
"VO__SOPHIA__CH07__CHATTER__SOPHIA_BAR__030__M__1": "Biraz eğri. Bu hödükler onu kumun üstünde çekmiş olmalı...",
"VO__SOPHIA__CH07__CHATTER__SOPHIA_BAR__050__M__1": "Daha beterini gördü! Bu tekne bir hayatta kalan.",
"VO__SOPHIA__CH07__CHATTER__SOPHIA_WARN_ANCHOR__010__M__1": "Hey! Çapa geminin diğer tarafında, Amicia!",
"VO__SOPHIA__CH07__CHATTER__TO_PONTOON__010__M__1": "Soluklandın mı? Gitmeye hazır mısın?",
"VO__SOPHIA__CH07__CHATTER__WRONG_PONTOON__010__M__1": "O iskele değil, diğeri!",
"VO__SOPHIA__CH07__HELPER__ANCHOR_FREE_1__010__M__1": "Amicia! Nerede olduğunu bilmiyorum ama şu çapanın kaldırılması lazım!",
"VO__SOPHIA__CH07__HELPER__SAILS_ORDER_MAINSAIL_1__010__M__1": "Ana yelkeni aç yoksa bu lanet yerden asla ayrılamayız!",
"VO__SOPHIA__CH07__HELPER__SAILS_ORDER_MAINSAIL_2__010__M__1": "Amicia, ana yelkeni bağlamak için kandilisa halatını aşağı çek!",
"VO__SOPHIA__CH07__HELPER__SAILS_STUCK_TOGETHER_1__010__M__1": "Amicia! İskeleye çık ve yelkene bir bak!",
"VO__SOPHIA__CH07__HELPER__SAILS_STUCK_TOGETHER_2__010__M__1": "İskeleye çık ve yelkeni kurtarmak için şu kilidi kır!",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__030__M__1": "Bırakın geçsin.",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__050__M__1": "Arnaud... O leş yiyen fareler bile seni istemedi...",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__060__M__1": "Şuna bak...",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__070__M__1": "Yeni mürettebatı sevdim!",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__110__M__1": "Görüyorum ki ona çoktan damganı vurmuşsun.",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__120__M__1": "Utanma tatlım. Sana yakışmış.",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__130__M__1": "Ne istiyorsun?",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__150__M__1": "İşimiz bitti, Arnaud. Kont'un ordusu peşimizde ve binlerce fare kapımın önüne sıçıyor. Bu yerin sonu geldi. Mürettebatı dağıtıyorum.",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__170__M__1": "Pekâlâ o zaman! Denizin Çağrısı olsun! Biraz molaya ihtiyacım var. Kimin umurunda? Ama bir şey var...",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__190__M__1": "Eğer gözümün önünde ona bir kez zarar verirsen, seni öldürürüm.",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__210__M__1": "Bu arada... Kont'un adamları teknemi kuru havuza koydu.",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__230__M__1": "O kısım çok doğru. Mürettebatımla iki çift laf etmem lazım.",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__240__M__1": "Siz köye gidin, teknem orada. Size katılırım.",
"VO__SOPHIA__CH07__RTC__300_SMUGGLER__280__M__1": "Korkarım bu sefer temelli.",
"VO__SOPHIA__CH07__RTC__303_SAVING_SOPHIA__010__M__1": "Açın! Açın!",
"VO__SOPHIA__CH07__RTC__303_SAVING_SOPHIA__060__M__1": "Hayır... Daha yeni tanıştık ve şimdiden sana borçluyum.",
"VO__SOPHIA__CH07__RTC__303_SAVING_SOPHIA__080__M__1": "Kuralları sen koymuyorsun.",
"VO__SOPHIA__CH07__RTC__303_SAVING_SOPHIA__100__M__1": "Deneyelim... ama sonunda sen de beni öldürmek isteyeceksin.",
"VO__SOPHIA__CH07__RTC__310_SET_SAIL__010__M__1": "Güzel iş! Şimdi hazırlan!",
"VO__SOPHIA__CH07__RTC__310_SET_SAIL__015__M__1": "Sıkı tutun!",
}
